### ISSUE TITLE
blackangus: vagrant up on server boot

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#100]
Child of #78 

Vagrant dirs are at /home/jenkins. These should `vagrant up` when the server boots.

**Comment by mchitten** [comment]
Would this require a `vagrant destroy` before `vagrant up`, to make sure we're getting the latest and greatest?

**Comment by mshmsh5000** [comment]
That would make reboot awful long.... Let's try `vagrant up` as a first attempt. We can go the `destroy`/`up` route if we run into problems.

**Comment by mchitten** [comment]
Chatting with Matt, we came to the conclusion that `vagrant reload` would be a good choice here.  This is done now.
