### ISSUE TITLE
auth - error messages for password and confirm password

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1000]
When registering for the site if I don't enter in a password, I don't get any error message on the password form and it doesn't shake.

I do get an error message on the confirm password field, however the confirm password field only displayed the "That doesn't match." message, the field doesn't shake.

The confirm password field fails to shake any time it doesn't match up with the password field (i.e. whether I don't enter a password or if my passwords just don't match)

![image](https://f.cloud.github.com/assets/6330971/2335721/042a2cd0-a487-11e3-83b8-77ea83e501c7.png)

**Comment by mikefantini** [comment]
@DFurnes misspoke - if I enter in a password and then don't enter in a match the confirm password field both shakes and gives me an error message, it's only when I don't enter in a password originally that it doesn't shake.

However, I'm still not getting any message on the password field (even when I enter a password I don't get a "Tough stuff" message).

![image](https://f.cloud.github.com/assets/6330971/2335927/35422f1e-a489-11e3-990b-c4af84d029c9.png)

**Comment by DFurnes** [comment]
Gonna look into this.
