### ISSUE TITLE
partners - make partners page dynamic not static content

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1001]
should pull from partners taxonomy and be a dynamically rendered page rather than be static content that goes stale

**Comment by barryclark** [comment]
@mikefantini This would be a lot of work and doesn't seem worth the time. Can we close this please?

**Comment by mikefantini** [comment]
@barryclark - yeah sure, it was @aaronschachter's idea originally. If it's not worth it I'm fine to close it.
