### ISSUE TITLE
pw reset - remove username in field title

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1004]
Field name should just read "E-mail address" not "Username or e-mail address" since most users don't know their username or that they even have one and it will just create confusion.

![image](https://f.cloud.github.com/assets/6330971/2336480/343edd9a-a490-11e3-8cbd-e9014dc8c18d.png)

**Comment by barryclark** [comment]
@aaronschachter Looks like a quick fix?

**Comment by aaronschachter** [comment]
It is. We should knock out the Password Reset confirmation message issue (or come up with copy for it) when we fix this.
