### ISSUE TITLE
auth - modal cut off on mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1006]
In safari app on iPhone 5 as I'm registering for the site the modal cuts off showing part of what is behind the modal (see where Hotline List appears below Email).

![photo 1](https://f.cloud.github.com/assets/6330971/2336630/3062051a-a492-11e3-8a67-56c3fa9d1cdc.PNG)

**Comment by DFurnes** [comment]
Looking into this now.

**Comment by DFurnes** [comment]
It seems there's a known issue with `position: fixed` when the virtual keyboard is triggered on iOS. It's affecting iOS 6 and 7 from some quick testing. Working fine on Chrome for Android.

**Comment by DFurnes** [comment]
Pushed up a fix in DoSomething/ds-neue#175. It changes modal behavior on iOS, but it seems like the only reasonable way to fix this since there's a bug in mobile safari. Lame.
