### ISSUE TITLE
Auth modal - layout messed up

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1012]
![screen shot 2014-03-05 at 2 53 59 pm](https://f.cloud.github.com/assets/583202/2337677/109c0d30-a4a0-11e3-8504-d9b4df271d01.png)

Something exploded when I pulled upstream changes.

... :mag:

**Comment by DFurnes** [comment]
Thinking we can't use `unset()` to remove Drupal fields if we're not using variables by reference, after the change in @7f398099318f59563a1e8eb25bd86c7f4614572f. Jumping into investigate a bit more. Let me know if there's a better way I should be doing this.

/cc @angaither @aaronschachter

**Comment by DFurnes** [comment]
Actually the form modifications that were changed in that commit are not being applied at all now. No placeholder text, modified labels, etc. Should we just remove the "shortcut" variables and reference the thing by the super long array?

**Comment by angaither** [comment]
@DFurnes blergggghh either that or put it back in the module.

**Comment by DFurnes** [comment]
Putting it back in the module won't make any difference.
