### ISSUE TITLE
action page (prove it) – report back modal markup

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1014]
We're abandoning the original field implementation for file uploads and using a custom-built form implementation. We need to be able to:
1. Upload a single image using a standard `<input type="file">` tag.
2. Display the previously uploaded image if editing an existing report back.

**Comment by barryclark** [comment]
@DFurnes is this guy closed?

**Comment by barryclark** [comment]
@DFurnes bump :bug:

**Comment by DFurnes** [comment]
Still needs some work on the interface for uploading & viewing images.
