### ISSUE TITLE
campaigns form - add another item ajax error

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1019]
Alyssa flagged this as a bug. She added three facts in the More Facts section of /node/add/campaign and then went to add another item and got the AJAX error depicted below.

Can't reproduce but have seen it before. Will update this card when it's experienced again.

Not a user facing error though and usually fixed by a refresh so nothing to prioritize.

![facts_ajax_error](https://f.cloud.github.com/assets/6330971/2339745/e3377b44-a4b9-11e3-9140-425e388dae19.png)

**Comment by barryclark** [comment]
Closing this as it doesn't seem like it's continuing to happen -- likely because of bad internet connectivity.
