### ISSUE TITLE
ds build: Permission denied errors

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#102]
Trying to run ds build or ds build --install results in:

```
Wiping build directory...
rm: cannot remove `/vagrant/html/sites/default/default.settings.php': Permission denied
rm: cannot remove `/vagrant/html/sites/default/files': Permission denied
rm: cannot remove `/vagrant/html/sites/default/settings.php': Permission denied
```

**Comment by aaronschachter** [comment]
If I  `sudo rm -rf html` before running the script, it builds.  Should the ds script be updated to use sudo?  I suppose then it'd prompt you for PW ?

**Comment by mshmsh5000** [comment]
sudo is nopasswd within Vagrant.

**Comment by dosomething-machines** [comment]
Yeah, we can use sudo for this.

**Comment by aaronschachter** [comment]
I must have just been running the script from outside of Vagrant.  This is working.
