### ISSUE TITLE
touch screen - pinch zoom does not work

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1020]
on IOS 7.06, when viewing the site in Safari. on one occasion the app actually crashed.

The crashes seem random, but we have seen it more than once on iPhone, always in landscape. Zooming in or out issue easy to reproduce - you see the screen trying to change size and then snap back. Occasionally the zoom works to a small extent - 10-20% enlargement.
The site looks and works better on iPad, but zoom still does not work. No crashes observed.

BTW, similar zooming issue was seen on Android too ( no crashes observed), so maybe this has to do with the way the site renders on a mobile.

https://trello.com/c/qxLc0kot

**Comment by DFurnes** [comment]
Setting `user-scalable=no` lets us remove the default 300ms touch delay on mobile devices (where the browser is trying to figure out whether it is a "double tap" to zoom or not). This is something we can change, but keep in mind it's a trade-off.
