### ISSUE TITLE
User mailing address

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1026]
We'll need someplace to store a user's mailing address.

For newer campaigns that needed to collect mailing addresses, we programmatically submit them into a webform node.

Refs #74

**Comment by deezone** [comment]
For what it's worth, the Message Broker has a persistent data solution using a mySQL database. This is a temporary in anticipation of the DS User API. Currently the Message Broker needs are a table of indexed by email addresses and a subscribe / unsubscribe column. 

Would it make sense to share the temporary solution? @jonuy is currently the lead on the Message Broker db.

**Comment by barryclark** [comment]
Assigning this over to you @angaither for this sprint. 

One thing to keep in mind is that we'll be looking to store the user's school data soon too. We currently use the Great School database as a reference for this.

**Comment by angaither** [comment]
[Address module](https://drupal.org/project/addressfield)
- adds a field, can be added to user object
- very basic
- saves data to one table

[Location module](https://drupal.org/project/location)
- lots of configures - can be added to custom entities, etc
- geocodes values
- multiple talbes

neither modules validate addresses.

**Comment by desmondmorris** [comment]
My vote is for the Address module.  Primarily because its not the Location module.

**Comment by angaither** [comment]
Why do you hate location?

**Comment by desmondmorris** [comment]
It adds alot of overhead I feel.  Though, it may make sense for something like schools, that could be reused.  But not much value over a school entity really.

I think addressfield + http://geocod.io for geocding and address normalization would be a good pairing
