### ISSUE TITLE
Cache clear Image URLs

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1033]
`drush cc all` should clear the custom `cache_dosomething_image` table
it should also create a custom `clear images` drush command

**Comment by aaronschachter** [comment]
This is not working for me upon `drush cc all`.  Made sure to `drush cc drush` as well, but still images in the cache_dosomething_image table.

**Comment by barryclark** [comment]
@angaither I can verify that this isn't clearing the cache_dosomething_image table for me either
