### ISSUE TITLE
Add and configure Optimizely

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1034]
- [ ] Add relevant version of Optimizely into `dosomething.info`
- [ ] Update drupal-org.make to download it
- [ ] Upon deploy, configure Optimizely with relevant settings for H&M

**Comment by mikefantini** [comment]
@barryclark not critical for 0.2 launch day itself, _however_ we will need to have this working so that we can implement the optimizely test, get results, and implement the direction we want to go with by H&M's hard launch of April 10th

see https://trello.com/c/ugUgjjwJ for the request we have out to the data team

**Comment by barryclark** [comment]
Cool @mikefantini gonna 0.3 this, we'll be redefining 0.3 soon.

**Comment by deezone** [comment]
I'll take care of getting all the settings in place on the New World module with the related Optimizely experiments snippets.

**Comment by mikefantini** [comment]
@deezone nothing to work on now. We'll sort this out next sprint

On Friday, March 7, 2014, DeeZone notifications@github.com wrote:

> I'll take care of getting all the settings in place.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1034#issuecomment-37049976
> .

## 

Mike Fantini
Head of Product, DoSomething.org
212.254.2390 x232

follow me: @mfantini12
follow us: @dosomething

... and we're hiring! www.dosomething.org/jobs

**Comment by Bladt** [comment]
@mikefantini any update on this? This is currently blocking the logo placement test
