### ISSUE TITLE
Image: Find field collection references

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1055]
Backlog issue.  Display on an image node related field collections (field_gallery_item, field_parnters) that an Image node may be referenced in.

**Comment by angaither** [comment]
@aaronschachter blast from the past, do you know if we do this field collection references on other node types? is that [`dosomething_helpers_get_entityref_parent_list()`](https://github.com/DoSomething/phoenix/blame/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L307)?
is this still something we should build?

**Comment by aaronschachter** [comment]
`dosomething_helpers_get_entityref_parent_list` i believe is just used when an editor is viewing an Image node, to see what nodes reference it via the given `field_name`. I don't remember where the need came from though.. there may have not been one. If no one is looking for this functionality, I don't think we'd need to build it. If no one actually uses that internal view either as is , I'd vote for just getting rid of all that code. Does that make sense @angaither  ?

**Comment by angaither** [comment]
totally, going to get rid of this issue then @aaronschachter 

also @mikefantini do you know if people look at these views? 
https://www.dosomething.org/image/6133

**Comment by mikefantini** [comment]
I don't believe anyone does but I'll ask in design and campaigns-team channels

**Comment by mikefantini** [comment]
Yeah seems like no one is using these. We should get rid of these.

**Comment by mikefantini** [comment]
Also there is a similar view for Facts that we can kill as well @angaither
