### ISSUE TITLE
Message Broker - Gather remaining merge_var values

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1071]
Need help finding the missing details in the related entity.

dosomething_signup_mbp_request()
      'call_to_action' => '??',
      'step_one' => '??',
      'step_two' => '??',
      'step_three' => '??',

dosomething_reportback_mbp_request()
      'event_id' => '??',
      'impact_verb' => '??',
      'impact_number' => '??',
      'impact_noun' => '??',

**Comment by aaronschachter** [comment]
I don't mind taking this on as i'm pretty familiar with the fields we need, but what is `event_id` for `dosomething_reportback_mbp_request` ?

**Comment by barryclark** [comment]
@aaronschachter @DeeZone Looks like this one is fixed?

**Comment by aaronschachter** [comment]
Nope still open.  @DeeZone let's connect tomorrow, still don't know what `event_id` would be.

**Comment by deezone** [comment]
@aaronschachter 

`event_id` is the NID for the campaign.

**Comment by mikefantini** [comment]
'step_one' => 'field_pre_step_header',
'step_two' => is not a variable field. this will always be "Snap a Pic"
'step_three' => 'field_post_step_header',
