### ISSUE TITLE
campaign admin - view that shows which campaigns have used which fields

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1083]
Similar to what @aaronschachter built on the original pantheon site

This way we'd be able to see if there are fields that are not used frequently (and candidates for re-thinking implementation to clean up the node), fields that editors are not using properly (i.e. filling out BOTH the solution fact and the solution statement), etc.

**Comment by barryclark** [comment]
Do we still want to build this @mikefantini @aaronschachter?

**Comment by mikefantini** [comment]
I think it'd be useful. When I originally talked to @aaronschachter it seemed pretty straightforward but if it's significant work let's skip it. I'd say biz value is 3.

**Comment by aaronschachter** [comment]
It's possible we could build our own custom form to query various tables, but I think this would require some significant effort.. I believe the Pantheon site, which I used a Drupal view for -- only had 3 or 4 different fields which were displayed (vs the very many we currently have on the campaign).  I don't really think we could pull this off with Drupal views but would need to write custom code.

The easiest way to do this would be to just sit down with a dev or data team member and go through the various field tables with production data to see how often each is used, and what kind of data is available.

**Comment by barryclark** [comment]
Sitting down with someone from dev or data every now and then and seeing which fields are used seems like a good plan given that it'd be difficult to build the view.

What do you think about closing this one out and going with the manual option when we need to review field usage @mikefantini?

**Comment by mikefantini** [comment]
yeah that makes sense to me
