### ISSUE TITLE
Reportback form client-side validation

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1088]
Mirror the validations we're doing server-side on the client-side. :1234: 

References #1087.

**Comment by barryclark** [comment]
Is this absolutely necessary for Tuesday, Dave? If not plz backlog.

**Comment by barryclark** [comment]
cc @DFurnes

**Comment by aaronschachter** [comment]
I don't know if its _absolutely_ necessary, but it's kind of lame without it.  If you don't fill out required fields, the page reloads with errors, and you have to scroll back down to click on the form again.  Might be confusing for some users.

![screen shot 2014-03-15 at 2 45 03 pm](https://f.cloud.github.com/assets/1236811/2429228/58324e14-ac72-11e3-988d-c59dd0678922.png)

**Comment by DFurnes** [comment]
This is a pretty quick fix. Less priority than some other things, but hoping to get it in.

**Comment by mikefantini** [comment]
@DFurnes making this high priority if you have time today pick this guy up

**Comment by aaronschachter** [comment]
@DFurnes is this ready to be closed?

**Comment by DFurnes** [comment]
Still need to add a check for whether an image has been attached.

**Comment by mikefantini** [comment]
associated trello card https://trello.com/c/oXYXKWOW

**Comment by barryclark** [comment]
@DFurnes I think we can close this one, right?

**Comment by DFurnes** [comment]
Yep, closing.
