### ISSUE TITLE
11 Facts: Remove sources

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1092]

**Comment by weerd** [comment]
Should I fully remove the code for the sources output or just temporarily comment it out. Don't want to remove it all if it's coming back at a later date. Just confirming :)

**Comment by mikefantini** [comment]
@weerd I would just comment it out for now. We're working on a better solution for displaying sources on the action page of the campaigns template. Once we sort that, we'll most likely be able to implement it across 11 Facts as well - so we would need the sources output eventually.

cc: @julielorch @barryclark

**Comment by weerd** [comment]
Cool. That makes sense :) Thanks!
