### ISSUE TITLE
site registration - notification message copy

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1109]
We need to update the copy of the notification message a user receives when they register for the site.

Language should be: 
"You've created an account with DoSomething.org."

Language currently:
![site reg copy](https://f.cloud.github.com/assets/6330971/2379260/048a97d0-a899-11e3-9346-b0c951f7a449.png)

**Comment by mikefantini** [comment]
#971 is a related issue

**Comment by barryclark** [comment]
Assigning over to @blisteringherb

**Comment by aaronschachter** [comment]
@blisteringherb @angaither @mshmsh5000 Perhaps a good reason to introduce "String overrides" module ?  Might be the easiest way to implement. This line is harcoded (and translated) in https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_register_submit/7

**Comment by desmondmorris** [comment]
No module necessary.  You can change this right from settings.php. 
https://drupal.org/node/522036
