### ISSUE TITLE
pitch page (all) - styling updates

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1115]
- [x] pull in actual image (not trello placeholder) and make sure filter is properly added
- [x] SIGN UP button not rendering
- [ ] SIGN UP button treatment should match button treatment on action page (i.e. larger button, proper font)
- [ ] need to show H&M logo, not just H&M in text
- [ ] H&M logo should be located in the bottom right hand corner (aligned with the sign up button)
- [ ] scholarship callout should match the [psd](https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/HM_pitch_mob.psd?attredirects=0&d=1) or see the [jpeg](https://a0465d35-a-5d563b7e-s-sites.googlegroups.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/HM_pitch_desk.jpg?attachauth=ANoY7crvQiobqcP_PdHI1c2yWFpnPU30JOfgh-44GYGjobmIx3gi11gre1QHYkwuDg_WgdwdeYlX7GHLkJJlKwGgYWEMCYwkYL7-5sGB-n5oLEE68IOfGKZgyrpbinJTRH6Lxong_7E_Jzx1Maxob0RwKkL6lHWOdPRsfTcVm-q6BH3Ey30Ua_DMJblQI0_JnRoeYqYfQLXnIQ83xT_PI5N1C9L60FivozpcKGloWRxH31vxsBV58efcEREw6xrKavx-_DnzFzCcsJ_WXDor61Kikh2h378TzNtwxBFCAwqPyHd3P1l-oso%3D&attredirects=0)

**Comment by DFurnes** [comment]
SIGN UP button font bug will be fixed when #1133 gets taken care of.

**Comment by mmwtsn** [comment]
SIGN UP button presence bug will be fixed when #1131 gets taken care of.
