### ISSUE TITLE
Site Registration (campaign) - should only display one message to the user

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1118]
When I register for the site _and_ sign up for a campaign I get two notification messages. I should only be getting the "You're signed up for Comeback Clothes! Get started below." message.

See #980 for related issue.

![image](https://f.cloud.github.com/assets/6330971/2380300/3edec5b4-a8a8-11e3-80fe-63e8150ac7fb.png)

**Comment by aaronschachter** [comment]
The "Registration successful" message is a default core message: https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_register_submit/7

Our best bet may be to use the `$clear_queue` parameter in [drupal_get_messages](https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_get_messages/7) within the relevant `dosomething_signup` function to avoid displaying the message altogether upon campaign signup.

**Comment by barryclark** [comment]
@mikefantini I'd disagree. I think you really would want to know that you're both registered for DoSomething and signed up for comeback clothes. 

I think the messaging here could be clearer/better though.

**Comment by aaronschachter** [comment]
Closing per discussion with @mikefantini -- we're going with keeping a message upon user registration.
