### ISSUE TITLE
ds script cleanup: profile symlinks

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#112]
There's commented symlinking of dosomething.info, dosomething.profile and dosomething.install file.

Let's either:
- fix it if it's broken
- remove if we can't do it, and update the wiki accordingly with how to make profile changes. https://github.com/DoSomething/dosomething/wiki/DoSomething-Profile

**Comment by aaronschachter** [comment]
Related #60

**Comment by mchitten** [comment]
Seems to be good now.
