### ISSUE TITLE
action page (prove it) - don't display arrows if only one image

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1120]
Since there is only one image in the prove it section on the H&M campaign (nid 362), we shouldn't display arrows or have the functionality to click through the gallery (because there is no gallery).

![image](https://f.cloud.github.com/assets/6330971/2380819/a5c1c39e-a8b2-11e3-8f6f-25d4b1686174.png)

However, this doesn't seem to be an issue when we use the placeholder image: 
![image](https://f.cloud.github.com/assets/6330971/2380835/2e2d4f82-a8b3-11e3-85ea-ad17fc7bd845.png)

So if needed, we could take two additional photos and upload those.

**Comment by barryclark** [comment]
Backlogging as we can find a quick solve for H&M tomorrow, and fix this properly in future.

**Comment by barryclark** [comment]
@weerd Is this still an issue?

**Comment by DFurnes** [comment]
No longer an issue.
