### ISSUE TITLE
action page (plan it) - location finder styling updates

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1122]
The location finder is not styled properly:

![image](https://f.cloud.github.com/assets/6330971/2380898/bd8b3044-a8b4-11e3-9eca-d4bfa7d15f4c.png)

See psd for how it should look:
https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/HM_Mock_Desk.psd?attredirects=0&d=1

**Comment by DFurnes** [comment]
I'll jump on this. /cc @mmwtsn

**Comment by mmwtsn** [comment]
:yellow_heart:
