### ISSUE TITLE
action page (modals) - header missing

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1123]
Modals are missing their headers (i.e. black bar across the top that says "We <3 H&M" or "FAQ").

Should look like these:
- https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/Xk7eqRtsusVCuKB/keri_actionpg%20mob_aero_modal.jpg
- https://trello-attachments.s3.amazonaws.com/512d12ee7b27cd4d4000056b/52e7ed3ae02756b4541ec4a8/bdfc4b6ac3babf42ca4390aa4a547316/keri_modals_mob_preentry.jpg

Currently looks like this:
![image](https://f.cloud.github.com/assets/6330971/2381024/eb268fd2-a8b7-11e3-8c3c-7950472c834c.png)

**Comment by DFurnes** [comment]
I'll take this one. :bear:
