### ISSUE TITLE
campaign (all) – break out pitch/action template into partials

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1127]
The campaign template is getting long. Let's break out each section into a separate partial to match the [SCSS structure](https://github.com/DoSomething/dosomething/tree/dev/lib/themes/dosomething/paraneue_dosomething/scss/feature/campaign).

Note: the header partial should be shared across the pitch and action pages.

**Comment by barryclark** [comment]
This has been broken out into many other issues over the past couple of months. Closing.
