### ISSUE TITLE
Webfonts aren't working correctly in Firefox

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1133]
Webfonts aren't loading correctly in Firefox in some cases.

**Comment by DFurnes** [comment]
I think a likely cause for this is that it seems Apache is serving our webfonts with the mime type `application/octet-stream` and Firefox is getting upset that this isn't strictly what it's looking for.

Reference: http://stackoverflow.com/questions/2871655/proper-mime-type-for-fonts

**Comment by mshmsh5000** [comment]
Poor Firefox.

![sad_fox_kit_by_magekl](https://f.cloud.github.com/assets/149811/2386509/ee7d4156-a92c-11e3-80dc-5178266fb4de.jpg)

**Comment by mshmsh5000** [comment]
Note to @desmondmorris that we'll have to implement/check this against our nginx config on the new servers.

**Comment by desmondmorris** [comment]
@mshmsh5000 +1

@DFurnes can you try adding the types to the .htaccess file? http://www.jbarker.com/blog/2009/mime-type-css-web-fonts

**Comment by DFurnes** [comment]
@desmondmorris Adding to `.htaccess` seems to do the trick. Was unsure how to get this hooked in with Salt though, since the `html/` directory isn't getting saved in version control.

``` apache
AddType application/vnd.ms-fontobject .eot
AddType application/font-sfnt .otf .ttf
AddType application/font-woff .woff
```

Mimetype reference: http://stackoverflow.com/a/20723357

**Comment by mikefantini** [comment]
@DFurnes @desmondmorris I've been seeing this in chrome incognito window, logged in as a non-admin authenticated user as well.

![image](https://f.cloud.github.com/assets/6330971/2386870/8f1c16c0-a930-11e3-9d47-6394eaba27fa.png)

**Comment by mshmsh5000** [comment]
@mikefantini That's because one of the font files is just missing.

![screen shot 2014-03-11 at 11 38 21 am](https://f.cloud.github.com/assets/149811/2387083/417e1c6c-a933-11e3-9c5f-c82247533e6a.png)

**Comment by DFurnes** [comment]
@mshmsh5000 Well, not being served. It exists [in the repo](https://github.com/DoSomething/ds-neue/blob/dev/assets/fonts/proxima-nova/ProximaNova-Sbold.woff) and in my local Paraneue bower installation. (But is still 404ing, regardless. I'd assume there's some sort of Apache configuration issue.)

![screen shot 2014-03-11 at 11 43 41 am](https://f.cloud.github.com/assets/583202/2387176/39bbfcb4-a934-11e3-8103-1e8a52ba99dc.png)

**Comment by mshmsh5000** [comment]
@dave [the link you posted](https://github.com/DoSomething/ds-neue/blob/dev/assets/fonts/proxima-nova/ProximaNova-Sbold.woff) 404s for me. Appears to be `SBold` in the repo. ?

**Comment by DFurnes** [comment]
Yep, changed in https://github.com/DoSomething/ds-neue/pull/185.

**Comment by DFurnes** [comment]
Was leaving this issue open for the correct webfont mime-types, but happy to close if that isn't something we're interested in doing.

**Comment by barryclark** [comment]
@DFurnes Could you close this please and add a new issue for the mime-types to the backlog? Ty
