### ISSUE TITLE
campaign (form) - Alt background pattern field bug

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1134]
When I upload an image in the Alt background pattern field and hit save, the background shows up properly. However, if I go to edit the campaign later I am unable to save and get this error message:

![image](https://f.cloud.github.com/assets/6330971/2386585/ba278064-a92d-11e3-97e9-0ff561573767.png)

**Comment by aaronschachter** [comment]
Investigating this fix https://drupal.org/comment/6866102#comment-6866102

**Comment by mmwtsn** [comment]
I was able to get around this by re-uploading the file under a different name.

**Comment by aaronschachter** [comment]
Confirmed this is fixed in staging.
