### ISSUE TITLE
Markdown - bold disabled 

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1143]
Intro text section. Tried both `**bold**` and `<strong>bold</strong>`. Neither output bold html tags.

**Comment by aaronschachter** [comment]
This is by design, to prevent use and abuse.  Allows HTML tags are configured in  admin/config/content/formats/markdown, but we would need to update the `dosomething_settings` feature in order to make any changes to this.

**Comment by barryclark** [comment]
@aaronschachter So you cant bold things inline, by design?

**Comment by aaronschachter** [comment]
Yes, but we can easily change the text format to allow that. The idea in not allowing was restricting people from going bold crazy.

**Comment by barryclark** [comment]
BOLD MOVE @aaronschachter

**Comment by DFurnes** [comment]
:b: :bangbang:

**Comment by mikefantini** [comment]
+1 on not having bold.. let's see what individual issues with that come up.

**Comment by barryclark** [comment]
I'm reviewing static content stuff with Julie and Crystal this afternoon, so will see if there's a real need for it based on the static content pages we have planned.

**Comment by barryclark** [comment]
@julielorch Want to flag this above with you. Is there anywhere that we'll absolutely need to be able to bold things in static content?

**Comment by mikefantini** [comment]
closing unless someone comes up with a good argument to enable
