### ISSUE TITLE
White screen "set_group_operator" error on campaign nodes

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1146]
Getting a `Fatal error: Call to a member function set_group_operator() on a non-object in /vagrant/html/profiles/dosomething/modules/contrib/views/includes/view.inc on line 987` error whenever I go to a campaign node. Running latest code and just pulled updated DB from staging.

![screen shot 2014-03-11 at 1 43 38 pm](https://f.cloud.github.com/assets/583202/2388733/df7300a2-a944-11e3-86ac-6b485c29e2c3.png)

**Comment by barryclark** [comment]
No longer happening for @DFurnes
