### ISSUE TITLE
Rework Image, Fact node non-staff access

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1153]
- [ ] Replace `hook_node_access` with `hook_init` to prevent non-staff from viewing Images or Facts
- [x] Update Image node type to default to published status
- [x] Update Fact node type to default to published status (in case we revisit using $vars instead of the $wrapper in Fact functions)

Currently `dosomething_user_node_access` is in place to deny access to non-staff users from viewing an image or fact node.

This causes issues when using the node's `$vars` to preprocess image nodereferences, because auth users aren't able to view the image.  So we get [weird behavior](https://github.com/DoSomething/dosomething/issues/1119#issuecomment-37252482) where staff sees images in a node but regular users cannot: https://github.com/DoSomething/dosomething/pull/1150#issuecomment-37339291

Either we always use the node->field / wrapper->field values directly instead of `vars` in our preprocess, or implement a different way to deny access to non-staff for Image nodes.  @blisteringherb mentioned that at MSL used a module to show a 404 if you visited the image node directly, although we'd want this to only happen for non-staff.  The fact and image nodes are useful for staff to see where they are referenced.

**Comment by blisteringherb** [comment]
Here's basically the same func we used, any issues with doing this in an init hook?

```
function dosomething_helpernodes_init() {
  global $user;
  if (arg(0) == 'node' && is_numeric(arg(1)) && (!arg(2) || arg(2) == 'view')) {
    $query = 'SELECT type FROM {node} where nid = %d';
    $type = db_result(db_query_slave($query, arg(1)));
  }
  else {
    return;
  }

  $helper_status = in_array($type, variable_get('helpernodes_restricted', array()));

  if ($helper_status && user_is_anonymous()) {
    drupal_not_found();
  }
}
```

**Comment by aaronschachter** [comment]
OK!  Here's the deal.  The `dosomething_user_node_access` is not the issue here, the issue is that the target image nodes are unpublished.  When you use `$vars`, Drupal knows that an authenticated user should not be able to see an unpublished node, and is rendering the $vars according to that permission.

So, yes, a quick fix could be to just publish the images by default and say "that's just the way it needs to work" - but this is going to bite us later when an editor unpublishes an image and doesn't know why the image upload is not working.

Moving forward, no go on inspecting the node `$vars` for image node preprocessing because rendering the image in the campaign or static content should not depend on the target Image node's published status.  Opening up a separate issue to alter any preprocess functions which use `$vars`.

**Comment by barryclark** [comment]
@blisteringherb Do you see any disadvantages of updating the static content, 11 facts and /campaigns page pre-process functions to use the node->field / wrapper->field values directly rather than $vars?

**Comment by blisteringherb** [comment]
Other than the potential performance hit by running the wrapper functions and the getValue() functions for fields, and having to redo the theming, I don't see any disadvantages.  I do think that images should be automatically published, but I can see where Aaron is coming from if an image gets unpublished.  In that case though, what's the utility of unpublishing an image?

@angaither

**Comment by angaither** [comment]
I agree, it makes sense to publish image nodes. Images should be treated like other content on the site, in that it has a workflow and is accessible to users once it's published.

**Comment by mshmsh5000** [comment]
I think that we need to have rilly rilly good reasons to bypass default publishing/viewing logic on content. Sometimes we have those reasons, for sure.

It doesn't make sense to me to add complexity to avoid the case where "an editor unpublishes an image and doesn't know why the image upload is not working," but perhaps I'm not understanding the likelihood / horror of that scenario. I'll get clarity from @aaronschachter.

**Comment by aaronschachter** [comment]
Ok, let's go with Image nodes need to be published in order for the world to see them.  

Makes sense to not fight with the `$vars`, the way @dries wants it to be, and also this gives us an easy way to take down an Image node across all nodes that reference it.

This issue remains open -- instead of denying access to the node, we'll go the route of the init hook and inspecting the arg(0), arg(1) to just deny users based on the current path.  I'll be updating this issue description with a checklist -- we'll need to update the default publishing status for Image nodes as well as create the `hook_init`.
