### ISSUE TITLE
Internal import.sh script

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#116]
A script to download the DB from prod for dev's to use locally.  Requires #115

Ideally would default to run sanitization / cleanup script #71 but also include a parameter allow for unsanitized data, to allow for testing / fixing production data bugs.

**Comment by barryclark** [comment]
@aaronschachter Maxwell mentioned that there's potentially an easier way to download content from stage, will this be the case for prod too?

**Comment by barryclark** [comment]
@aaronschachter I think this is done with `ds pull stage --db`?

**Comment by aaronschachter** [comment]
yep
