### ISSUE TITLE
action page (nav) - breaks on mobile in Do It section

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1176]
On mobile the text goes over the persistent nav. But this only happens in the Do It section.

![photo 6](https://f.cloud.github.com/assets/6330971/2398859/b61ba80c-a9f9-11e3-853d-d0fc57d3047b.PNG)

**Comment by DFurnes** [comment]
Uncle Mike, charge your phone!

![screen shot 2014-03-12 at 1 59 40 pm](https://f.cloud.github.com/assets/583202/2400935/1888598e-aa10-11e3-97e6-a6e0b2c2d261.png)
