### ISSUE TITLE
action page (prove it) - arrows should be centered on photo

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1177]
Particularly an issue on on tablet break points:

![image](https://f.cloud.github.com/assets/6330971/2398985/c59984ce-a9fa-11e3-805e-ffce7b16c1d0.png)

@barryclark putting in backlog for now

**NOTE:** Vertically centering with unknown heights can be a little tricky. Here's a [pseudo-element  technique](http://css-tricks.com/centering-in-the-unknown/) from Mr. Coyier that may be of use.

**Comment by mikefantini** [comment]
actually @barryclark mock on mobile has these arrows located at the bottom of the photo, not the center... let's discuss this in the design QA meeting.

**Comment by barryclark** [comment]
Thanks @mikefantini I think this is worth fixing for 0.2.0.

**Comment by crystalruthbell** [comment]
Hey @mikefantini, this is a pretty obvious bug, is there a way we can bump it up in priority?
