### ISSUE TITLE
campaign – JavaScript is not compiling on Stage

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1179]
`App.js` is not compiling correctly on Stage. What is currently a 938 line file is only showing 37 lines. Running `ds grunt --prod` should compile all JavaScript assets and is working correctly in our local Vagrant environments.

Something is going wrong with [Browserify](http://browserify.org/).

Causing #1114.

**Comment by mshmsh5000** [comment]
@desmondmorris Browserify is def installed on the staging server. And it's called in the Grunt file for paraneue_dosomething. Any ideas?

@mmwtsn @DFurnes Have you tried running Grunt directly on staging to see what happens?

**Comment by DFurnes** [comment]
SSH'd into the staging server and ran both a normal `grunt` task and `grunt prod`. Both ran without errors but didn't properly include Browserify modules in the outputted JS. Also tried re-installing NPM modules and checking that Bower components were up to date.

**Comment by DFurnes** [comment]
Are there any big differences between the environment on staging and on our Vagrant boxes?

**Comment by desmondmorris** [comment]
@DFurnes there are not major differences between the two environments.  Each are built from the same provisioner.

**Comment by desmondmorris** [comment]
Okay so the issue is that the gruntfile browserify step is looking for "js/app.js", but the actually file is "js/App.js".  Changing this, makes browserify play nice.

https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/Gruntfile.js#L87

@DFurnes or @mmwtsn will follow up with a patch

**Comment by DFurnes** [comment]
Super weird. Thanks for the help. :thumbsup:

**Comment by mmwtsn** [comment]
Chalking this one up to ![Jackie](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/jackie.png)
