### ISSUE TITLE
User Partners field: Check "display on user registration form".

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1180]
Allows for 1 step creation of Partner/Sponsor User accounts.

Check "Display on user registration form" for Users.field_partner and update features accordingly. (its either in `dosomething_user` or `dosomething_taxonomy`.

The field will always be unset via `dosomething_user_form_alter`.

**Comment by barryclark** [comment]
Is this still valid @aaronschachter?

**Comment by aaronschachter** [comment]
Yes, it is still valid and a super quick one. it's just for admin's creating an account that is tied to a Sponsor. I think we needed for H&M and that's where this was from.

**Comment by barryclark** [comment]
Assigning over to you to tackle in this sprint of mega issues cleanup.
