### ISSUE TITLE
action (header) – add scholarship call out

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1184]
## Description

Add handwritten scholarship call-out to the mobile action page.
### Mobile

![action-mobile](https://cloud.githubusercontent.com/assets/1479130/2618990/13698e20-bc29-11e3-8c8b-646e1933c4a6.png)
**NOTE:** Some of the elements of this design may have changed since the mock was created.

Related to #1592

**Comment by mikefantini** [comment]
this is only needed for mobile
