### ISSUE TITLE
action page (know it) - move links to modals below The Solution on mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1195]
on mobile any of the links to modals should appear below The Solution not in between The Problem and The Solution.

![image](https://f.cloud.github.com/assets/6330971/2404419/9a30615e-aa3b-11e3-8ec3-1e2e7f27186b.png)

**Comment by barryclark** [comment]
Could you take a look into this please @tjrosario?

**Comment by tjrosario** [comment]
@mikefantini @barryclark, without getting hacky, the markup for modals would have to appear after these two columns.  Is there any other reason why these links appear in the 'Problem' column other than to even out white space?  This is how it would look if it did: 
![image](https://cloud.githubusercontent.com/assets/1566749/3445469/d60fb8f2-0137-11e4-8a0d-5131e92510c7.png)

**Comment by mikefantini** [comment]
@tjrosario yeah it's just to even out white space. when there is a PSA those flip over to the solution side (and then on mobile are below the solution).

![image](https://cloud.githubusercontent.com/assets/6330971/3445545/6bee78b8-0138-11e4-8e0c-ffb2b4a8b014.png)

![image](https://cloud.githubusercontent.com/assets/6330971/3445553/7a1c1882-0138-11e4-97c6-bfa6953f6941.png)

But @tjrosario if this is super hacky and the only other solution would be to add that white space below the problem then I'll just close this out.

If you think of any other way we can do it feel free to re-open but closing out for now.
