### ISSUE TITLE
action page - general style tweaks

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1199]
- [x] Body/paragraph text to #444
- [x] Primary links should be blue and bold, with a underline as a hover state
- [x] Secondary link should be underlined ~~gray~~ not bold!
- [x] Make the navigation background a lighter gray

**Comment by mmwtsn** [comment]
@barryclark Do we currently have any examples of a secondary anchor on the campaign? I remember us talking about having the fact sources link be underlined but we haven't implemented source links yet.

**Comment by barryclark** [comment]
@mmwtsn this guy is one too...

![image](https://f.cloud.github.com/assets/692762/2422465/9ae4d41e-ab8e-11e3-8be9-50100a7b5a48.png)
