### ISSUE TITLE
action page (do it) - hide tips in modal on mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1200]
Tips in the do it section on mobile should be in a modal.

Modal should look similarly to FAQs, except instead:
- [x] H1 text should read "Tips"
- [x] tip headers should have H2 treatment and color (i.e. either purple or sponsor's alternate color) 
  ![image](https://f.cloud.github.com/assets/6330971/2404445/f817b5ba-aa3b-11e3-8624-edcaff984561.png)

[Annotated mocks](https://a0465d35-a-5d563b7e-s-sites.googlegroups.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/Action%20Page%20Mobile%20-%20annotated%20mock%200.2.png?attachauth=ANoY7cq9Ey0lsPWYKOswG_2TYY4votgrAFI3ITW_qk8PTHa0EHzpokDzd8ynMW6aRprt9HosQVGlYw1kIYrx3BEJDFKtkHisdIBqpoyOhzMm39dJeUD9WhADZsynq5N4bIaaAKvom2F9zSCZiE3OuldoO3Id7VSOqdLUF6W-lq7FUeUM5B_unLX6ABwGggWU_jWb6lE-gimbQ1OQaYZVIC_RutoOpbgHN1-lCDeDO1pzef368YmiPdVxzvGEheYYK_pTPM2-mghdrkD67eFZb86wE9FUQM38TQ_CQ_z9rf7cwjtsFN56cqpsz5YfubcCwWvU4pXvpYWe&attredirects=0) for mobile Do It section (except link should read "View tips" instead of "View more tips").

**Comment by mikefantini** [comment]
@mmwtsn we need to pull in the During Tips (field_step_pre and field_step_post) for these.
- field_compound_text_header should have H2 color (i.e. either purple or sponsor's alternate color)
- field_compound_text_copy should have normal body copy treatment

So for Comeback Clothes we should see Get Loud and Hit Da Clubs as the two tips for Run Your Drive! in mobile.

Right now we're currently pulling in the FAQ: 
![image](https://f.cloud.github.com/assets/6330971/2423439/747f1da6-ab99-11e3-90de-9cdaaf22879f.png)

**Comment by aaronschachter** [comment]
This is closely related to #1253 -- where the FAQs seem to be printing for Tips.  cc: @blisteringherb

**Comment by mikefantini** [comment]
cool then @blisteringherb assigning over to you then. Let me know if you have any questions. Oddly it's pulling in the proper fields on desktop but not on mobile.

**Comment by mikefantini** [comment]
this is working now for field_step_pre on mobile.. once we have #1253 set up we'll need to make sure that it gets rendered the same way field_step_pre is being rendered on mobile.

and then "View tips" should appear as hyperlinked text below the third step in the Do It section (just like we have below the first step in the Do It section).
