### ISSUE TITLE
action page (prove it) - move official rules below the photo in mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1201]
official rules should be located below the photo in the action page on mobile

**Comment by mikefantini** [comment]
![photo 10](https://f.cloud.github.com/assets/6330971/2431977/2793589a-ad4c-11e3-9057-78d6a3ac8f94.PNG)

**Comment by mmwtsn** [comment]
Weren't we supposed to keep the official rules link next to the submit button for legal reasons?

**Comment by mikefantini** [comment]
@Bladt do you know what the legal restrictions are on this?

**Comment by Bladt** [comment]
I know we were dinged in the past for moving the CTIA language too far from the CTA. Not sure for official rules

**Comment by barryclark** [comment]
I'm pretty sure that they just need to be on the same page.

**Comment by mmwtsn** [comment]
Fair enough. I'll move it down on mobile.

**Comment by barryclark** [comment]
Another mobile campaign template issue @tjrosario. Let's see how possible these are without hackery / duplicating markup.
