### ISSUE TITLE
action page (plan it) - tighten up margin under The Solution

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1203]
There's an inconsistently big margin under The Solution. It should be the same as The Problem. 

![image](https://f.cloud.github.com/assets/692762/2428660/f1317a44-ac55-11e3-8e3b-327d758842f5.png)

**Comment by barryclark** [comment]
This is happening because the Solution Statement field is wrapping it's content in a `<p>` elements. @mikefantini @aaronschachter do we need markdown on this field? (toggling to "plain text" on the field didn't resolve)

**Comment by mikefantini** [comment]
hmmm yeah it only seems to be happening for campaigns that use field_solution_copy instead of field_fact_solution.

@barryclark @aaronschachter is there another way around this or is the only solution to remove markdown on field_solution_copy? Also are we sure that this will fix it?
