### ISSUE TITLE
action page (plan it) - rework layout of plan it section

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1206]
Plan It includes up to 5 sections:
- Stuff You Need
- Time and Place
- VIPs
- Hype
- Location Finder

Notes:
- each section is optional (although campaign creator must fill out at least two)
- the order of the sections stays consistent campaign to campaign (even if certain sections are omitted)
- each will have a character limit of 135 characters

**Comment by barryclark** [comment]
Bourbon should actually take care of a LOT of this stuff for us with just span-columns and omegas!

**Comment by barryclark** [comment]
@mikefantini We're not going to have time to do this for Tuesday. Shifting to Backlog. I don't think it should affect any campaigns, right? If it does, we shouldn't publish those campaigns for now.

**Comment by mikefantini** [comment]
@barryclark that's totally cool. Already talked to campaigns team about
that plan

On Saturday, March 15, 2014, Barry Clark notifications@github.com wrote:

> @mikefantini https://github.com/mikefantini We're not going to have
> time to do this for Tuesday. Shifting to Backlog. I don't think it should
> affect any campaigns, right? If it does, we shouldn't publish those
> campaigns for now.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1206#issuecomment-37728162
> .

## 

Mike Fantini
Head of Product, DoSomething.org
212.254.2390 x232

follow me: @mfantini12
follow us: @dosomething

... and we're hiring! www.dosomething.org/jobs

**Comment by barryclark** [comment]
@mikefantini Awesome, thanks

**Comment by mikefantini** [comment]
Update:
We should _not_ include the Location Finder in our layout considerations. That should always remain as a separate box at the bottom (we can re-examine once we have internal location finders, but I'd imagine we've want it to work like this when we have some of those and we show results).

Also keep in mind we always want the order to remain the same:
- Stuff You Need
- Time and Place
- VIPs
- Hype

Example of what it should look like:
https://docs.google.com/a/dosomething.org/presentation/d/1Ge9Un1bK2jftkE6muhydZkMC9KyRnQZc0XDW9kFbqPg/edit?usp=sharing

**Comment by mikefantini** [comment]
update made this it's own issue (#1707): 

when we tackle this let's clean up the spacing of the location finder so it's consistent with spacing between other sections:

![image](https://cloud.githubusercontent.com/assets/6330971/2609208/99fa1bf0-bb73-11e3-894e-3556384b7eed.png)

**Comment by weerd** [comment]
Will be addressing this, AND reworking the markup to what we dictated during our last fender meeting w/ @mikefantini. Will eliminate columnar markup in favor of floated mini boxes of content.

**Comment by weerd** [comment]
Chatted with @mikefantini and will only address the spacing between the "Find a Location" block and the items above it. Will address markup at a later date; probs best to address it during a refactoring sprint.

**Comment by weerd** [comment]
This ticket now refers specifically to the refactoring of the markup for the columnar blocks in Action page sections. The spacing was temporarily addressed in issue #1734

**Comment by weerd** [comment]
@mikefantini is there a preferred order. I'm assuming the order (if content is present), should be.
- Stuff You Need
- Hype
- Time and Place
- VIPs
- Find a Location

**Comment by mikefantini** [comment]
- stuff you need
- time and place
- vips
- hype
- find a location

thanks @weerd
