### ISSUE TITLE
Global - Site-specific CSS not loading correctly

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1207]
When attempting to access the campaign website in IE8 on Windows XP, the site does not render properly. ~~The three lines icon that accesses the sign in link on a mobile device is displayed instead of a sign in link and instead of accessing a sign in link it does nothing when clicked.~~ (See #1058.)

![image](https://f.cloud.github.com/assets/692762/2404861/1807a8b0-aa43-11e3-954d-ba2fa4003ba8.png)

**Comment by mikefantini** [comment]
From @mshmsh5000:
"One clue: JS error: "'Drupal' is undefined" -- see: https://trello-attachments.s3.amazonaws.com/52ea92c7ccdaf8415b8cab3a/5320cb007f9622487a1c8401/0017f1b21f43d46f86804051cd16b9e9/IE8-Drupal.png

That's also an error on other browsers BTW. It's from the jQuery.extend() call (see: https://trello-attachments.s3.amazonaws.com/52ea92c7ccdaf8415b8cab3a/5320cb007f9622487a1c8401/b84af965ba59862436c8661774e5a9e2/Chrome-Drupal.png

I have a Win XP / IE 8 VM on my machine -- LMK if you want to debug on it."

**Comment by mikefantini** [comment]
also update https://trello.com/c/xTW30rud when closed.

**Comment by desmondmorris** [comment]
Okay, so the issue is that html5shiv is not being loaded properly.  The path set in `html5shiv.php` is incorrect.  Replacing this temporarily with the cdn version seems to fix the issue.  I will open a PR with the fix

**Comment by DFurnes** [comment]
Hmm, still seeing this issue on my local after pulling in all the latest Neue, Paraneue, and DS app changes:

![uh oh](http://www.browserstack.com/issue-tracker/e5cb8cb6d9f23bc2b92c4e5ea7b1235c27bdd335/winxp_IE_8.0.jpg)

HTML5Shiv is correctly loading now and seems(?) to be working. So it seems like there are still some other unresolved issues on this.

**Comment by DFurnes** [comment]
Interestingly, styles seem to be partially applied on static content pages:

![static content pages](http://www.browserstack.com/issue-tracker/844859f5084a353eb48f0b62659e124c6c0994b6/winxp_IE_8.0.jpg)

Currently leaning towards the explanation that something in the CSS is fucking up IE parsing partway through. Gonna keep investigating.

**Comment by barryclark** [comment]
YESSSS!!! :dancers: :clap: :tada: :tada: :tada: :tada: :tada: :tada: :clap: :dancers:
