### ISSUE TITLE
action page (do it) - menu items in nav aren't active when in Do It

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1208]
Any menu item that is located in Do It is in an inactive state (i.e. I can click on Know and Plan but not Prove It in the image below). 

If the nav is fully in the Do It section, none of the items are clickable.

May be related to #1176 

![image](https://f.cloud.github.com/assets/6330971/2404927/5d1484ae-aa44-11e3-9a04-789d94c502ce.png)

**Comment by mikefantini** [comment]
updated trello card when closed: https://trello.com/c/YdU75MOY

**Comment by barryclark** [comment]
- @DFurnes

**Comment by mikefantini** [comment]
@DFurnes @barryclark this is working now for me. Closing this issue.

**Comment by barryclark** [comment]
Well, that's sweet.
