### ISSUE TITLE
Legacy campaign redirects

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1213]
For campaigns with signups, we'll use the Beta NID's pitch page to serve as the gate.  After signup (stored in the beta app), we redirect to the legacy nid's new path.

| Campaign | Legacy NID | Beta NID | Signups |
| --- | --- | --- | --- |
| Mind on my money | 731098 | 850 | yes |
| ~~PB Jam Slam~~ | ~~731234~~ | ~~955~~ | ~~yes~~ |
| Bully Text | 730939 | 832 | no |
| Pregnancy Text | 729027 | 843 | no |
| Would you rather | 731226 | 51 | no |

**Comment by mikefantini** [comment]
@angaither @aaronschachter for Would you rather the legacy NID is 731226 and the beta NID is 51

**Comment by aaronschachter** [comment]
Updated issue description, per @mikefantini PBJ content will be ported into the beta node, and we won't need to redirect back to legacy node.  We will still need to import the PBJ signups.

**Comment by aaronschachter** [comment]
The redirects are working, however for some redirects, its directing to specifically to "node/730939".  If we care about this, we need to just these redirects to point to paths.  Otherwise ready to be closed.

**Comment by blisteringherb** [comment]
The 3 non-login redirects are working properly.

**Comment by mikefantini** [comment]
@aaronschachter want to just create an issue in the backlog for that and close this one out.

**Comment by aaronschachter** [comment]
WE DID IT
