### ISSUE TITLE
campaign - header image starts below the navigation for all campaigns other than Comeback Clothes

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1244]
The header image for all campaigns other than Comeback Clothes starts below the navigation. 

Comeback clothes properly has the image laying behind the navigation. This causes all content to be pushed down way further than it should be:

![image](https://f.cloud.github.com/assets/6330971/2415718/f35f3102-aaf8-11e3-8d64-89523fb5b6b7.png)

![image](https://f.cloud.github.com/assets/6330971/2415725/fea22376-aaf8-11e3-9176-3bfebba6aa2d.png)

**Comment by mikefantini** [comment]
@DFurnes @barryclark do you guys know if that pull request is good to go?

**Comment by barryclark** [comment]
@DFurnes Assigning you on this one to review and merge into paraneue. Ty.
