### ISSUE TITLE
Message Broker - Password Reset NULL email

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1248]
Password reset request sends NULL email address.

------- Thu Mar 13 22:05:51:000000 UTC 2014 -------
 [x] Received payload:{"activity":"user_password","email":null,"uid":null,"merge_vars":{"FNAME":null,"USERNAME":null,"RESET_LINK":"http:\/\/staging.beta.dosomething.org\/user\/reset\/\/1394748351\/4WNFBPRSQGyono2pWy30ANaRNANU0cIS0owzLOz50_g"},"activity_timestamp":1394748351,"application_id":"2"}

**Comment by deezone** [comment]
Resolved

**Comment by deezone** [comment]
Found the source of the blank / NULL queue entries. The logic for "user_pass" was trigger on initial page load as well as when the form is submitted but does not find a matching account by username or password.

**Comment by aaronschachter** [comment]
@DeeZone is this resolved?

**Comment by deezone** [comment]
Sorry, yes, it's been resolved.
