### ISSUE TITLE
auth - error notifications don't appear on campaign pages

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1249]
If I fuck up going through the auth flow on a campaign page I don't get any error messages. Instead the pitch page just reloads and does not sign me up for the campaign.

To re-create:
- go to /campaigns/comeback-clothes
- click sign up
- enter in dummy email and pw combo
- click log in

**Comment by angaither** [comment]
The error messages are being printed, they are just set to display:none
![](http://f.cl.ly/items/152Y2X0T161F2w3G3L1Y/Screen%20Shot%202014-03-14%20at%2010.34.13%20AM.png)
