### ISSUE TITLE
Link up all of the header/footer links

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1251]

**Comment by barryclark** [comment]
WHAT IS DOSOMETHING: /content/any-cause-anytime-anywhere
EXPLORE CAMPAIGNS: /campaigns

---

OUR PEEPS: /content/our-peeps-0  (This is the landing page for OUR TEAM in the footer)
YAC: /content/youth-advisory-council
TEAM: /content/our-team
BOARD: /content/board
JOBS: /content/were-hiring
INTERNSHIPS: /content/internships
OLD PEOPLE: /content/old-people
SEXY FINANCIALS: /content/sexy-financials
INTERNATIONAL: /content/dosomethingorg-around-globe
PARTNERS: /content/our-partners
DONATE: /content/please-give-us-your-money
TMI AGENCY: http://www.tmiagency.org/
TOS: /content/terms-service
PRIVACY POLICY: /content/privacy-policy
FAQS: /content/frequently-asked-questions
HOTLINES: /content/hotline-list
CONTACT: /content/get-touch-0

**Comment by aaronschachter** [comment]
We need to code this using the drupal `l` function and pass through the `node/[nid]` paths to avoid having to always change this anytime a title changes.

Also, the `'/content/[title]` pattern is nasty, and super "Hey we just built a new drupal site".  Can we just change it to `about/[title]` or just `[title]`.  Will need to delete aliases and bulk update based on new pattern.

**Comment by barryclark** [comment]
+1 for [title]

**Comment by barryclark** [comment]
@mshmsh5000 Any problems with us going with just [title] and dropping the /content/[title]

**Comment by mshmsh5000** [comment]
The URL patterns, in addition to SEO, are about building stable patterns for pool switching in Varnish. It's nice to have a rule that says

```
If pattern = "/content/*" then use new app
```

instead of 

```
If (pattern = "/title1" or pattern = "title2" or pattern="title3"...) then use new app
```

So `about/[title]` is a nice compromise if `content/` gives @aaronschachter the heebie jeebies. Also, Hey we just built a new Drupal site!

**Comment by angaither** [comment]
`content/1` gives everyone the heebie jeebies.

**Comment by barryclark** [comment]
Yep, about/[title] sounds like a good compromise. 

@julielorch It'd be great if we can get rid of the "-0" from the end of the URLs that have it too. (e.g. /content/our-peeps-0 would now be /about/our-peeps)

**Comment by angaither** [comment]
That's generated when two pieces with the same title are saved. Super easy to remove the other piece of content and or update the url.

**Comment by barryclark** [comment]
@angaither sweet, thanks

**Comment by barryclark** [comment]
@julielorch an updated list based on discussion above, and a few names that I'd suggest tidying up:

WHAT IS DOSOMETHING: /about/any-cause-anytime-anywhere
EXPLORE CAMPAIGNS: /campaigns

OUR PEEPS: /about/our-peeps (This is the landing page for OUR TEAM in the footer)
YAC: /about/youth-advisory-council
TEAM: /about/our-team
BOARD: /about/board
JOBS: /about/were-hiring ---> change to /about/jobs ?
INTERNSHIPS: /about/internships
OLD PEOPLE: /about/old-people
SEXY FINANCIALS: /about/sexy-financials
INTERNATIONAL: /about/dosomethingorg-around-globe ---> change to /about/international ?
PARTNERS: /about/our-partners
DONATE: /about/please-give-us-your-money  ---> change to /about/donate ?
TMI AGENCY: http://www.tmiagency.org/
TOS: /about/terms-service
PRIVACY POLICY: /about/privacy-policy
FAQS: /about/frequently-asked-questions
HOTLINES: /about/hotline
CONTACT: /about/get-in-touch

**Comment by barryclark** [comment]
L functions with node paths!

FUTURE! Open new issue to look at Drupal Menu... also look at migrating to paraneue_dosomething
