### ISSUE TITLE
action page (do it) - after tips are not appearing

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1253]
The after tips are not appearing on the action page:

After tips:
![image](https://f.cloud.github.com/assets/6330971/2421596/f2553168-ab83-11e3-9b52-b0839e122079.png)

Example: 
http://staging.beta.dosomething.org/campaigns/music-march-out

And this should be treated as this issue outlines on mobile: https://github.com/DoSomething/dosomething/issues/1200

**Comment by mikefantini** [comment]
upload trello card when closed: https://trello.com/c/Hmii36am

**Comment by aaronschachter** [comment]
Assigning to @blisteringherb
