### ISSUE TITLE
Simple redirects for Legacy SMS Game Campaigns

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1259]
Refs #1213 
- Enable redirect module
- Redirect stub non-signup nodes to their corresponding www.dosomething.org URL's (for now)

**Comment by blisteringherb** [comment]
The redirects for the following have been set up on staging.

| Campaign | Legacy NID | Beta NID |
| --- | --- | --- |
| Bully Text | 730939 | 832 |
| Pregnancy Text | 729027 | 843 |
| Would you rather | 731226 | 51 |

**Comment by blisteringherb** [comment]
Fixes #1213
