### ISSUE TITLE
Destination being set on incorrect login on some content types

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1273]
On incorrect login on static content and fact pages that a ?destination is being appended to the url.

**Comment by aaronschachter** [comment]
Hm. This is a drupal core thing tho, no?  Is this issue to override the that behavior and login the user to their user profile?

**Comment by angaither** [comment]
Hm, don't think so since it only happens on certain content types.

**Comment by aaronschachter** [comment]
But we have custom behavior on a campaign that would override the 'destination' param since we're setting a custom form action?  I'd guess (but haven't tested) that this happens everywhere except campaigns.

**Comment by barryclark** [comment]
@aaronschachter @angaither Thoughts on next steps for this?
