### ISSUE TITLE
Transactional Emails - not displaying main body

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1278]
When users get transactional emails (campaign sign-up, general sign-up, report back, forgot pw) the banner and button display correctly but there is no text content.

**Comment by mikefantini** [comment]
text is missing (although it's in the template): 

Report back transactional:
![image](https://f.cloud.github.com/assets/6330971/2425146/cc2e78d2-abb0-11e3-8c34-fd810b50975b.png)

Campaign sign up transactional:
![image](https://f.cloud.github.com/assets/6330971/2425160/e692f388-abb0-11e3-86d8-f41efb73583a.png)

**Comment by barryclark** [comment]
@DeeZone Any idea when the body text for the email wouldn't be displaying here?

cc'ing @aaronschachter @blisteringherb in case you guys have time to help out.

**Comment by deezone** [comment]
Fixed

For reference, the `mc:edit="static-main"` on the body of the message must not reference `mc:edit="main"` is it gets switched with the `message->html` value sent in the request to the Mandrill API.

**Comment by mikefantini** [comment]
@marahml confirmed that this is fixed.

Closing.
