### ISSUE TITLE
pitch page (sponsor logo) - need to fix the container for sponsor logos

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1280]
Mind On My Money is launching a pitch page on Monday EOD. Need to fix the sponsor container so that the whole logo fits:

![image](https://f.cloud.github.com/assets/6330971/2425340/91c0ff3c-abb3-11e3-99b1-005e31c37c4c.png)

**Comment by barryclark** [comment]
@mmwtsn This one is high priority as it's a sponsor logo issue. Could you take a quick look at this and hopefully get a fix in before EOD? Thx!

@mikefantini's about to attach a link to the node, and the sponsor image.

**Comment by mikefantini** [comment]
- Mind On My Money edit node: http://staging.beta.dosomething.org/node/850/edit
- H&R Block partner edit node: http://staging.beta.dosomething.org/taxonomy/term/443/edit
- H&R Block logo (originally from Farah):
  ![hrb d s 3c logo](https://f.cloud.github.com/assets/6330971/2425525/8c544858-abb6-11e3-99bd-3039c7ad379f.png)
- H&R Block logo I cropped and uploaded:
  ![hrblock logo](https://f.cloud.github.com/assets/6330971/2425527/91c63ec2-abb6-11e3-90ef-c53fe4dfb314.png)

**Comment by barryclark** [comment]
Thanks @mikefantini

**Comment by barryclark** [comment]
We're not going to worry about the black text in the logo for now. This issue is just to get the whole logo showing.

**Comment by mikefantini** [comment]
yeah totally... the black logo shit is not on devs that's a design/biz dev thing

**Comment by mmwtsn** [comment]
Well, that's interesting.

We had originally designed the sponsor logo region of the campaign header to receive a fixed height image of unspecified widths. That would allow Keri to cut sponsor logos to a consistent vertical size and the layout would allow for various sponsor logo sizes (e.g. H&M vs H&R Block).

The image module currently requires a fixed size to be specified in the template which means that all sponsor logos will be the same width/height. We'll need to sync w/Andrea on this one.

**Comment by barryclark** [comment]
@angaither The H&R Block logo is 423x101 so isn't getting 300x300 cropped too well. Sponsor logos might just need to be uploaded at the correct size that we want them to be output at?

I'm happy to put in a quick fix to pull the logo png directly from /sites/default/files/partners/HRBlock%20Logo.png for now if we'd prefer to look at this after Tuesday.

**Comment by aaronschachter** [comment]
I can jump in here, as I added the sponsor logo preprocessing. It's using a function I added to the image module called `dosomething_image_get_themed_image_by_fid` which requires a `$style` parameter.  I can modify this function to make that parameter optional, so it has the ability to display the raw image file without any resizing.  I'm not sure if this would disrupt the H&M campaign though (we'd just need to upload the H&M logo with the proper dimensions)

**Comment by barryclark** [comment]
@aaronschachter Nice one. I think that's the best way to go. 

@mikefantini cc'ing you on the above. The site won't resize sponsor logos if we go this route, so we'll have to make sure that the H&M logo gets re-uploaded at 300px x 300px.

**Comment by mikefantini** [comment]
@barryclark not a problem. 

@aaronschachter just let me know when it's all set and I'll re-upload.

**Comment by angaither** [comment]
@aaronschachter I think that's fine for now, but if we need more flexibility with the image styles we can add in new standards that only crops to the max-width. 
wmax-423px which would crop the image to the correct width and let the height be sized by the ratio of the image.

**Comment by aaronschachter** [comment]
@angaither that def sounds like a good addition.  Wanna create an issue to track it?

**Comment by angaither** [comment]
@aaronschachter we can use this one? it's no big deal to add a new image style now.

**Comment by aaronschachter** [comment]
sure, go for it.

**Comment by barryclark** [comment]
Re-opening for fender work.

**Comment by mikefantini** [comment]
taking high priority label off since it's no longer due today

**Comment by barryclark** [comment]
Aaaand we're doing this now. Assigning to @mmwtsn and setting as High Priority for this sprint. 

Should look like this:

![image](https://f.cloud.github.com/assets/692762/2517215/b21105ce-b456-11e3-8cb8-66cd0e6a6bca.png)
