### ISSUE TITLE
General User Reg Email - Active Campaigns Merge Tag Needed

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1286]
"Active Campaigns" merge tag not displaying

**Comment by deezone** [comment]
@marahml I think this might be a future feature. I think the plan was to start with static text and links?

**Comment by mikefantini** [comment]
@marahml this is a feature we will get to in a future sprint. Can you please add the spec to this issue?

**Comment by marahml** [comment]
Here's the FFA: https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGxYYkhEX3Y5OHhhUGp1dkJKd3NBQlE&disco=AAAAAGCU2yM#gid=10

The ID for that issue is #10.

Is that what you were looking for?

Just let me know!

**Comment by barryclark** [comment]
Thanks @marahml. I think there's probably an issue for this in Message Broker? Gonna close this one out.
