### ISSUE TITLE
Automatically lint PHP files on pull requests.

### ISSUE THREAD

**Issue by mchitten** [DoSomethingArchive/legacy-website#129]
Automatically lint Pull requests after they are opened with PHP Coder Sniffer (#88) and leave comments with test results.

Tag PR's with status of results.

**Comment by mchitten** [comment]
Possibly leave proper status on PR.  http://developer.github.com/v3/repos/statuses/

**Comment by barryclark** [comment]
@aaronschachter close?

**Comment by aaronschachter** [comment]
No, this is still open. It's not working anymore.

**Comment by angaither** [comment]
could also use style ci 
DoSomething/voting-app/pull/453
https://styleci.io/

cc @DFurnes

**Comment by DFurnes** [comment]
Awwww yiss! We've been using it on the Voting App and I've really liked it. Super super quick test results, slick interface, one-click to create fix PRs... what's not to like? Potential gotcha is that it seems intended for object-oriented projects, so I'm not sure if it'd have trouble with Drupal-style code.

**Comment by angaither** [comment]
closing, done with styleci
