### ISSUE TITLE
Action Guide modals

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1297]
Render action guides in a modal.

**Comment by aaronschachter** [comment]
@mikefantini Do these modals need a header?  If so, what field should we use.. or is there a value we can just hardcode for each one, like "More info".

**Comment by mikefantini** [comment]
@aaronschachter pull in the title from the action guide

**Comment by mikefantini** [comment]
@aaronschachter hold off on that right now actually. Going to circle up with @barryclark and Deluca first thing on Monday and figure out how to move forward with the header for that modal.

We will need one though and we'll want to treat it consistently with the other modal headers we have.
