### ISSUE TITLE
galleries - refactor to make them consistent

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1302]
we have some inconsistencies in our gallery treatments, especially on 

campaign confirmation page:
![image](https://f.cloud.github.com/assets/6330971/2431772/77102628-ad42-11e3-9159-a8184181d144.png)

/campaigns:
![image](https://f.cloud.github.com/assets/6330971/2431774/8010b31e-ad42-11e3-90c2-0db2ddd8dc04.png)

**Comment by mikefantini** [comment]
Closer but still not there:

confirmation page:
![image](https://cloud.githubusercontent.com/assets/6330971/2570368/f52d9362-b8f8-11e3-8f92-090ba026126e.png)

/campaigns:
![image](https://cloud.githubusercontent.com/assets/6330971/2570362/e62af81e-b8f8-11e3-81f3-23064d84564b.png)

**Comment by barryclark** [comment]
@tjrosario @weerd What's the current state of these? If one of you guys is working on this, please assign yourself this issue. Ty.

**Comment by DFurnes** [comment]
Fixed with Neue 6.0 cleanup.
