### ISSUE TITLE
email - prove it link in email body copy not linked properly

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1304]
signed up for campaign: Free to Pee Petition.

confirmation email I received has a Prove It button, takes me to http://www.dosomething.org/campaign/*%7CCAMPAIGN_LINK%7C*

should take me to http://staging.beta.dosomething.org/campaigns/free-pee-petition#prove

@barryclark need to make sure this is working before we launch H&M on Monday

**Comment by mikefantini** [comment]
confirmation email after signing up for Comeback Clothes has a Prove It button that takes me to the same link: http://www.dosomething.org/campaign/*%7CCAMPAIGN_LINK%7C*

**Comment by barryclark** [comment]
@DeeZone @aaronschachter Any idea where this link is getting set?

**Comment by aaronschachter** [comment]
@DeeZone I'm not seeing a `CAMPAIGN_LINK` being called in `dosomething_user_mbp_request` or `dosomething_signup_mbp_request`.  This must be handled in message broker somewhere. 

If we want to send a path into the mandrill template, we should be using `$node->path` as value to pass from within `dosomething_signup_mbp_request`.  But I'd imagine the mandrill template should be coded to `http://www.dosomething.org/` with no trailing `/campaign/`.  Or hardcode it to the node url in case the path ever changes.

**Comment by deezone** [comment]
@aaronschachter Thanks for the details, very helpful.

**Comment by mikefantini** [comment]
@DeeZone @aaronschachter I'm still seeing this error on recent emails I got.

Re-opening this issue.

**Comment by blisteringherb** [comment]
The #prove hash needs to be removed from the URL.
