### ISSUE TITLE
action page (contact us) - Contact us modal needs to be styled

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1307]
- [ ] Modal header should read "CONTACT US"
- [ ] "Enter your question..." should be in our body copy.
- [ ] Submit button should be our primary call to action button style

![image](https://f.cloud.github.com/assets/6330971/2432000/36d26aca-ad4d-11e3-9d1a-fac05db6816f.png)

**Comment by DFurnes** [comment]
What should the label be, if we're making the "Enter your question..." text into body copy?

**Comment by mikefantini** [comment]
just so it's documented let's make the label "Your Question"
