### ISSUE TITLE
action page (nav) - glitches when I scroll to the top on mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1313]
if you scroll down so that the nav follows you along the page on mobile, and then scroll up quickly the nav glitches for a second and freezes at the top of the page with a blank white space open where it originally started:

![photo 1 1](https://f.cloud.github.com/assets/6330971/2432273/0badb04c-ad5d-11e3-9790-ca08ddb30134.PNG)

![photo 2 1](https://f.cloud.github.com/assets/6330971/2432274/0d88b420-ad5d-11e3-8bdd-1fc3bfed63d4.PNG)

**Comment by DFurnes** [comment]
This is a downside of not using a `position: sticky` polyfill, since Mobile Safari pauses JavaScript execution during scroll. Definitely looking in doing some progressive enhancement on this once things quiet down a bit.

**Comment by DFurnes** [comment]
This has been fixed by using `position: sticky` and the [fixed-sticky](https://github.com/filamentgroup/fixed-sticky) polyfill.
