### ISSUE TITLE
/campaigns - Comeback clothes opens up in new tab

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1315]
on /campaigns Comeback Clothes defaults to open up in a new tab (it's the only campaign I could find that was doing this)

**Comment by mikefantini** [comment]
scratch that, now I'm seeing all campaigns opening up in a new tab

**Comment by barryclark** [comment]
@mikefantini thoughts on moving this up to "low priority"?

**Comment by barryclark** [comment]
Moved it up, it's kinda shitty and that page will get traffic
