### ISSUE TITLE
Footer Menu

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1321]
Figure out a better, less hardcodey way to render the footer/nav menu.

**Comment by barryclark** [comment]
Sweet! Thanks :octopus:

**Comment by DFurnes** [comment]
@angaither Would love to get your thoughts on DoSomething/paraneue#49.

**Comment by barryclark** [comment]
@angaither @DFurnes Pretty sure this can be closed as @desmondmorris reworked the footer?
