### ISSUE TITLE
Add birthday to user_register MBP call

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1323]
New user registrations need to include the birthday value for the MBP call. The Message Broker will include the birthday value in the MailChimp subscription call.

**Comment by aaronschachter** [comment]
FYI - We've been referring to birthday as `birthdate` in the beta app.  Not sure what the expected merge vars name is in Mailchimp.

**Comment by aaronschachter** [comment]
Fixed by #1323
