### ISSUE TITLE
Image nodes, alt text

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1325]
Need to set alt text on all images when being themed. 
aka, need to save the alt text after a new image is uploaded.

**Comment by barryclark** [comment]
This looks quick if either of you have time to grab it @aaronschachter @angaither

**Comment by aaronschachter** [comment]
The File Entity module has already added Image Alt and Image Title fields to the database, we just haven't exported them to features yet.  Perhaps it makes sense to add them to the Image content type as well, in the interest of sharing fields / less tables.

**Comment by aaronschachter** [comment]
So -- it's not too quick but not super difficult either. we'll need to add the existing fields to the content type, and then update the`dosomething_image_get_themed_image` function to use those fields when it loads the Image node.
