### ISSUE TITLE
notifications (mobile) - logo makes them unreadable

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1328]
The notifications on mobile are pushing down the menu but not the logo. The logo is going over the notification message, making the message unreadable.

![photo 2 2](https://f.cloud.github.com/assets/6330971/2438845/a81fd0b0-adf6-11e3-8eda-66d9bcd387ec.PNG)
![photo 1 2](https://f.cloud.github.com/assets/6330971/2438846/a99e2914-adf6-11e3-889a-e0f2fa9cdc5f.PNG)

**Comment by DFurnes** [comment]
Fixed in latest Paraneue/Neue.
