### ISSUE TITLE
pitch page (sponsor logo) - powered by still showing if no logo present

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1329]
If a campaign is sponsored but we don't have a logo attached to the sponsor then we should not show the "Powered by:" text.

![image](https://f.cloud.github.com/assets/6330971/2439231/b314222e-adfa-11e3-8e7c-5755c92ae356.png)

**Comment by barryclark** [comment]
@mikefantini fixed by unsetting the sponsor on the campaign node on staging.

**Comment by mikefantini** [comment]
Yeah Barry that's the hack. The problem is that the campaign won't be
prioritized in /campaigns which is kind of fucked. But if that's what we
have to do for today that's fine

On Monday, March 17, 2014, Barry Clark notifications@github.com wrote:

> Closed #1329 https://github.com/DoSomething/dosomething/issues/1329.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1329
> .

## 

Mike Fantini
Head of Product, DoSomething.org
212.254.2390 x232

follow me: @mfantini12
follow us: @dosomething

... and we're hiring! www.dosomething.org/jobs

**Comment by barryclark** [comment]
Damn. Can we leave "is sponsor" checked, but not enter the sponsor and still have it prioritized? cc @mikefantini

**Comment by mikefantini** [comment]
Oh of call try that (and let's make sure we remember that)

On Monday, March 17, 2014, Barry Clark notifications@github.com wrote:

> Damn. Can we leave "is sponsor" checked, but not enter the sponsor and
> still have it prioritized? cc @mikefantinihttps://github.com/mikefantini
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1329#issuecomment-37849234
> .

## 

Mike Fantini
Head of Product, DoSomething.org
212.254.2390 x232

follow me: @mfantini12
follow us: @dosomething

... and we're hiring! www.dosomething.org/jobs

**Comment by DFurnes** [comment]
Shouldn't we just be checking for presence of the sponsor image field here? And either falling back to plain-text "H&R Block: Dollars and Sense" or omitting if the image doesn't exist?

**Comment by mikefantini** [comment]
+1 for omitting if the image doesn't exist.. I just didn't know how
difficult this was

On Mon, Mar 17, 2014 at 2:06 PM, David Furnes notifications@github.comwrote:

> Shouldn't we just be checking for presence of the sponsor image field
> here? And either falling back to plain-text "H&R Block: Dollars and Sense"
> or omitting if the image doesn't exist?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1329#issuecomment-37849680
> .

## 

Mike Fantini
Head of Product, DoSomething.org
212.254.2390 x232

follow me: @mfantini12
follow us: @dosomething

... and we're hiring! www.dosomething.org/jobs

**Comment by aaronschachter** [comment]
reassigning to myself to implement comment per @DFurnes -https://github.com/DoSomething/dosomething/issues/1329#issuecomment-37849680

**Comment by aaronschachter** [comment]
@barryclark let's add the Sponsor info back in.

**Comment by mikefantini** [comment]
added sponsor back in; let me know when it's ready to re-test on staging

**Comment by aaronschachter** [comment]
Give it a go, @mikefantini .  http://staging.beta.dosomething.org/node/850/pitch

**Comment by aaronschachter** [comment]
Heads up @barryclark -- i added the `copy` class in order to align the Sponsor Name with the "Powered by".  It's printing nicely, although when you use a longer sponsor name, e.g. "H&R Dollars&Sense", the line will get cut off because of the line-height: `100px.`  This is the danger of allowing me to css.  Markup can be altered appropriately in `dosomething_campaign_preprocess_partners_vars`.

**Comment by mikefantini** [comment]
@barryclark @DFurnes @barryclark another option is just to hide "Powered by:" if there is no image. Let's just do whichever is easier.

**Comment by mikefantini** [comment]
@barryclark @DFurnes @aaronschachter "Powered by:" is showing up _any time_ a partner is attached to a node. Even if they aren't a sponsor.

Can we move forward with just hiding "Powered by:" if there is no image attached to a partner for now?

**Comment by mikefantini** [comment]
_another_ example: https://beta.dosomething.org/campaigns/welcome-home
