### ISSUE TITLE
action page (report back) - error message when updating report back with second image

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1347]
On prod on comeback clothes when I tried to update my report back with this image:

![imag0074](https://f.cloud.github.com/assets/6330971/2441729/27268d24-ae18-11e3-8d9e-1577e52a360c.jpg)

I got this error message:
https://s3.amazonaws.com/uploads.hipchat.com/34218/261430/PP6QhdvbDBhxBpJ/upload.png

**Comment by desmondmorris** [comment]
Thanks, this has to do with the client_max_body_size setting in nginx

**Comment by mikefantini** [comment]
@desmondmorris I'm no longer getting this error on production. Cool to close this issue?

**Comment by barryclark** [comment]
This looks more and more delicious every time I re-view the issue.

**Comment by mikefantini** [comment]
closing
