### ISSUE TITLE
action page (do it) - tips functionality is broken

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1349]
![image](https://f.cloud.github.com/assets/692762/2442382/42b35a78-ae21-11e3-8892-f2ecc44241d7.png)

https://beta.dosomething.org/node/362

~~Clicking "hit da clubs" tip hides~~ "announce your results" should live in a modal.

**Comment by mmwtsn** [comment]
[According to the mocks](https://github.com/DoSomething/dosomething/blob/12f0a02f8548e3fd2e768ffa872490bb69ee3c69/lib/themes/dosomething/paraneue_dosomething/scss/feature/_content.scss#L39-L41) the "post tips" section should not be shown at all. That section should be a modal.

I updated the issue above.

**Comment by barryclark** [comment]
cc @mikefantini

**Comment by mikefantini** [comment]
@mmwtsn @barryclark that was something we wanted to make a call on in browser, let's leave them exposed and treat them the same as we do "Before Tips"

@barryclark I thought the issue here was that the after tips were default exposed, but when you clicked through on the before tips the after tips became hidden

**Comment by mmwtsn** [comment]
Spoke with Mike. We're going to hold off on this until Keri/Crystal can weigh in on how this is going to be treated as a final design has not been approved for this section.

**Comment by barryclark** [comment]
Sounds good @mmwtsn @mikefantini. It'd be great to let the content for some of the existing campaigns inform what we do with this section too.

**Comment by barryclark** [comment]
This is still a pretty nasty bug that we should put a temporary fix in place for now. 

@mmwtsn @mikefantini Thoughts on... in the 2nd tips section, displaying ONE item of tip content it's subheader (as shown in my original attached photo). But not having the subheader be a link?

**Comment by mmwtsn** [comment]
@barryclark Fantini would like the current styles to be respected and have the JavaScript fixed. I'm working on that now.

**Comment by mmwtsn** [comment]
Fixed by #1416
