### ISSUE TITLE
campaign (zendesk)  - error message when submit a question

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1352]
To re-create:
- go to beta.dosomething.org/campaigns/peanut-butter-jam-slam
- sign up for the campaign
- scroll down to the bottom and click on "Give us a shout"
- submit a question to the contact us modal

![image](https://f.cloud.github.com/assets/6330971/2442518/7604deae-ae23-11e3-846e-35d808a79969.png)

**Comment by aaronschachter** [comment]
Works for me again. What uid / email are you using to submit questions?

![screen shot 2014-03-17 at 6 59 39 pm](https://f.cloud.github.com/assets/1236811/2442767/e73a59ce-ae27-11e3-8471-9f23fdb1705b.png)

**Comment by aaronschachter** [comment]
Ah, I can replicate using my `batman@example.com`.  Must be an error when an email is not in zendesk already. Ok this is a bug

**Comment by blisteringherb** [comment]
Any objections to creating a new user if necessary and then creating the ticket like this?

@aaronschachter

**Comment by aaronschachter** [comment]
Nope i think its what we need to do, in order to track the communication history.

**Comment by blisteringherb** [comment]
Approved? 
@aaronschachter 
@angaither

**Comment by aaronschachter** [comment]
yup i approved #1359 with the ol :+1:
