### ISSUE TITLE
FNAME var in Comeback Clothes sign up email subject and body

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#1354]
`*|TEXT:FNAME|*` in the subject and `*|FNAME|*` in the body.

![screen shot 2014-03-17 at 6 49 58 pm](https://f.cloud.github.com/assets/696595/2442685/900a4b42-ae26-11e3-9ea0-bc165f0e24f2.png)

**Comment by aaronschachter** [comment]
I got an email 4 hrs ago with my name in it.  This may be because this user didn't have a first name?  @jonuy can you confirm?

**Comment by jonuy** [comment]
Retested at 5am after all the migrating happened with a new user. Didn't get this problem then.

Crystal also made updates to default FNAME to "friend" in the rare case the user won't have an FNAME.

**Comment by deezone** [comment]
@jonuy @mikefantini  Should we create an issue to send "friend" or "doer" (old app solution) when FNAME == "" Perhaps a question for Marah?

**Comment by mikefantini** [comment]
duplicate issue. @DeeZone focus on the one in the message broker repository.
