### ISSUE TITLE
Error message after deleting nodes, entities: Warning: array_flip(): Can only flip STRING and INTEGER 

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1356]
Got this error message when deleting an image on beta.dosomething.org:

![image](https://f.cloud.github.com/assets/6330971/2443053/735d75a8-ae2d-11e3-9df8-3cc803a771e1.png)

![screen shot 2014-03-07 at 8 58 04 pm](https://cloud.githubusercontent.com/assets/1236811/2638646/95fb827c-beb2-11e3-8f25-18e74611e436.png)

**Comment by barryclark** [comment]
Looks like we can close this one @mikefantini @aaronschachter?

**Comment by mikefantini** [comment]
yeah closing
