### ISSUE TITLE
/campaigns - all characters not being pulled in properly

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1357]
See Peanut Butter & Jam Slam:

![image](https://f.cloud.github.com/assets/6330971/2443114/2fd6919c-ae2e-11e3-8584-469002bfecc2.png)

**Comment by mikefantini** [comment]
@barryclark I removed & and used + instead. It's working now. Going to close this.

**Comment by barryclark** [comment]
@mikefantini Cheers. Gonna keep this open and backlog on it as we should still fix this.

**Comment by mikefantini** [comment]
Here's an example of it happening again on /campaigns... Most likely happening on the campaign page as well after you report back on a campaign.

![image](https://cloud.githubusercontent.com/assets/6330971/2615710/524bf974-bbfd-11e3-87b2-bc1d8ebe069e.png)

**Comment by mikefantini** [comment]
@angaither assigning this guy to you

**Comment by mikefantini** [comment]
kicking it over to @blisteringherb

**Comment by aaronschachter** [comment]
@blisteringherb Did #1660 fix this for title as well?  Seems like it's only decoding the label and not title...

**Comment by aaronschachter** [comment]
Lots of funky characters on production /campaigns.
