### ISSUE TITLE
Set up Cron in Jenkins

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#1360]
Set up cron to run every X mins

**Comment by blisteringherb** [comment]
The section of the puppet fabfile related to cron for the old Drupal cron job looked liked this:

```
@roles('drush')
def cron():
  env.warn_only = True
  with cd('/var/www/html'):
    run('mv status.php status-temp.php')
    run('drush cron')
    run('mv status-temp.php status.php')
```

 I'm not seeing a status.php file and the html directory is different so I've updated it to this :

```
@roles('drush')
def cron():
  env.warn_only = True
  with cd('/var/www/beta.dosomething.org/current/html'):
    run('drush cron')
```

Can I get a sanity check to make sure this makes sense before I re-enable it?

@desmondmorris 
@mshmsh5000 

Here's a link to the Jenkins job.  http://admin.dosomething.org/jenkins/job/Drupal-Cron/configure

**Comment by desmondmorris** [comment]
Seems okay to me.  +1

**Comment by mshmsh5000** [comment]
Looks good. +2

**Comment by blisteringherb** [comment]
That job is now enabled in prod.
