### ISSUE TITLE
email - update subject line for site registration template

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1361]
When I register for DoSomething.org I get an email that has no subject.

Instead the subject should read: Welcome to DoSomething.org

![image](https://f.cloud.github.com/assets/6330971/2443619/85efd35c-ae3a-11e3-950a-f4596fd1327f.png)

**Comment by blisteringherb** [comment]
@DeeZone mentioned that this gets set in the Mandrill interface.  If I can get credentials to that, I can take a look in there to see if something is missing there.  From the digging I've done, the subject isn't being set in Drupal.

**Comment by blisteringherb** [comment]
I updated the subject in Mandrill, this should be good to go now.
