### ISSUE TITLE
email - spacing off in all email templates

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1364]
Too much space between h1 and h2 in the email templates.

![image](https://f.cloud.github.com/assets/6330971/2443754/b9ee7d76-ae3e-11e3-9061-b184f9ee0cce.png)

**Comment by mikefantini** [comment]
full disclosure not sure if this is a dev task or design but want to make sure it's documented

**Comment by barryclark** [comment]
Looks a bit better to me now... ![image](https://cloud.githubusercontent.com/assets/692762/3436207/f51bde50-009d-11e4-9906-1a065031103e.png)

Closing this, Mike.
