### ISSUE TITLE
nav - not aligned horizontally and partially hidden on ie

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1368]
![image](https://f.cloud.github.com/assets/6330971/2444170/bd10a3b4-ae4b-11e3-840e-a7407d2be260.png)

**Comment by mikefantini** [comment]
this is most recent version of ie

**Comment by mikefantini** [comment]
nav actually looks better in ie8 (according to ie developer tools):

![image](https://f.cloud.github.com/assets/6330971/2444186/143a6c88-ae4c-11e3-81bc-0812d9a85a6c.png)

**Comment by barryclark** [comment]
shooting over to @DFurnes

**Comment by DFurnes** [comment]
It's an issue with HTML5 tags. I assume it's not triggering in IE 8 because HTML5Shiv is loading in the conditional comment there... why they're not loading in IE 9+ though? Strange.

**Comment by DFurnes** [comment]
Fixed by adding a `display: block` to those two classes. Worth looking into again since the [Meyer reset](https://github.com/DoSomething/ds-neue/blob/dev/scss/vendor/_reset.scss#L27-L30) should be taking care of that for us...
