### ISSUE TITLE
email - create default replacement for first name if none exists

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1378]
If we don't have a first name for a user in MailChimp we should have some fall back so that we don't use "Hey _|TEXT:FNAME|_!

![image](https://f.cloud.github.com/assets/6330971/2444888/8ddb5bf2-ae64-11e3-9775-0fd35101b2e9.png)

**Comment by angaither** [comment]
@mikefantini what should the default be?

**Comment by mikefantini** [comment]
@marahml it's your call on this

**Comment by marahml** [comment]
@mikefantini thanks! Let's go with "Doer"
