### ISSUE TITLE
Mind On My Money - getting incorrect under 13 flag

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1390]
I created an account (email mfantini+tester@dosomething.org) using Log In modal in the upper right hand corner on the homepage.

The user's birthday is 5/30/1999.

I then went to www.dosomething.org/money, signed up for the campaign, selected a school, and went to report back.

When I clicked on the upload images on the old app's /money "action" page I get this error message:

![image](https://f.cloud.github.com/assets/6330971/2445730/3ba5a062-ae79-11e3-8c26-bd212977de60.png)
- Path: money/report-back

**Comment by aaronschachter** [comment]
This is code in the legacy db. Didn't realize we're checking for parental permission on reportbacks. Per @mikefantini we're just going to remove this check and you can reportback now matter how old you are.

**Comment by aaronschachter** [comment]
@mikefantini This should be fixed when deploy today.  I was able to recreate it and will close if verified fixed

**Comment by aaronschachter** [comment]
Its fixed!  #DRIES
