### ISSUE TITLE
Path based legacy redirects

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1392]
Refs #1213

Instead of redirecting to "node/730939", redirect to a pretty path "bully".

Make sure all legacy redirects are directing to paths, not node url's.

**Comment by mikefantini** [comment]
@aaronschachter can we close this one out at this point?

**Comment by mshmsh5000** [comment]
Whoa. I was proceeding with the understanding that we were going to redirect all legacy paths to canonical (`node/*`) beta paths, in case the aliases changed over time.

I can alter the script in #3404 and related logic to redirect to an alias of each canonical beta path, but let's make the decision before we close any of these out. /cc @aaronschachter @mikefantini

**Comment by aaronschachter** [comment]
This was created when legacy was up and serving content, but redirecting live users to the canonical paths.  I honestly don't think this is worth too much trouble and would be happy to redirect to the canonical path instead for said reasons, so happy to close this and continue as is @mshmsh5000

**Comment by mikefantini** [comment]
yeah same. i'd rather be safe and send them to beta canonicals
