### ISSUE TITLE
/user/login styles broken

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1395]
![user-login](https://f.cloud.github.com/assets/1479130/2448539/7c87e65c-aea7-11e3-9dc3-71757f7052ad.png)

**Comment by DFurnes** [comment]
Looking into this. I think we can just style the default node template since we're overriding everything else.

**Comment by DFurnes** [comment]
There's plenty that's not _great_ about this, but it's a better "default state" until we can figure out some better template inheritance stuff.

![screen shot 2014-03-18 at 3 50 33 pm](https://f.cloud.github.com/assets/583202/2452838/9d0646ec-aed6-11e3-9b0a-57dd9d903966.png)

**Comment by mmwtsn** [comment]
Looks grand. I'll send up a PR with a default wrapper width once that gets merged in.
