### ISSUE TITLE
Sign-up Email - First Name merge tag not working 

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1396]
Sign-up transactional email for Comeback Clothes is showing: 

Time to get started, _|FNAME|_! Recycle old or worn-out clothes to help our planet. Here’s how to make it happen:

Subject line also shows:
_|TEXT:FNAME|_!

**Comment by mikefantini** [comment]
@marahml can you please update this with the user you noticed this issue with and confirm is attached to that user account?

**Comment by marahml** [comment]
My account is one example - and what do you mean by attached to the user
account?

[image: Inline image 1]

On Tue, Mar 18, 2014 at 12:15 PM, mikefantini notifications@github.comwrote:

> @marahml https://github.com/marahml can you please update this with the
> user you noticed this issue with and confirm is attached to that user
> account?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1396#issuecomment-37952598
> .

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething

**Comment by mikefantini** [comment]
closing, this is occurring because user's don't have first name attached to their user profile. the merge tag _is working properly_
