### ISSUE TITLE
Sign-up email - Report back button not linked correctly 

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1397]
Link for the "Prove It" button appears to be broken

Correct link is: https://www.dosomething.org/campaigns/comeback-clothes#prove

**Comment by deezone** [comment]
@marahml I assume the "Prove It" link is in message coming from a campaign sign up. 
- the template is looking for: href="_|CAMPAIGN_LINK|_"
- the URL for the campaign is set to campaigns/comeback-clothes

Is the "not linked correctly" issue that the link doesn't have the "#prove" anchor at the end of the link?

**Comment by marahml** [comment]
Yes please! Looking for the #prove anchor. 

So each email RB link should look like this for each campaign: 
https://www.dosomething.org/campaigns/comeback-clothes#prove

**Comment by aaronschachter** [comment]
Yo @mikefantini @blisteringherb -- please chiem in here.  I believe we are not including anything with a #prove anchor.

**Comment by deezone** [comment]
A very simple solution... I've updated the template from:

```
href="*|CAMPAIGN_LINK|*"
```

to

```
href="*|CAMPAIGN_LINK|*#prove"
```

This locks us into a specific anchor for report backs but it can easily be updated.

**Comment by marahml** [comment]
Great! Did you already push that update?

On Wed, Mar 19, 2014 at 12:14 PM, DeeZone notifications@github.com wrote:

> A very simple solution... I've updated the template from:
> 
> href="_|CAMPAIGN_LINK|_"
> 
> to
> 
> href="_|CAMPAIGN_LINK|_#prove"
> 
> This locks us into a specific anchor for report backs but it can easily be
> updated.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1397#issuecomment-38070629
> .

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething

**Comment by mikefantini** [comment]
@marahml @DeeZone I don't think we should include the # prove ending to the link. I think just linking to the campaign itself is the best course of action. And I believe that is working properly (as I last tested last night).

So let's please make sure that the template reflects this so that it's not going to "_|campaign_link|_#prove"

Main UX reason I don't think it makes sense to take the user straight to the prove it section is because that section is very bare bones and doesn't really provide much context that you're even on the right page AND it's super easy to navigate to using the campaign nav if we just take you to the campaign itself.

**Comment by deezone** [comment]
@marahml Sorry to make you repeat yourself but did you not tell me in person to keep `"|campaign_link|#prove"` ? It's a quick change in the MailChimp template if needed. Let me know either way.

**Comment by marahml** [comment]
@deezone - discussed this with Mike in person. I think its best to point to
where the button says we're pointing to. Please send users to the link with
#prove in it

On Wed, Mar 19, 2014 at 2:01 PM, mikefantini notifications@github.comwrote:

> @marahml https://github.com/marahml @DeeZonehttps://github.com/DeeZoneI don't think we should include the # prove ending to the link. I think
> just linking to the campaign itself is the best course of action. And I
> believe that is working properly (as I last tested last night).
> 
> So let's please make sure that the template reflects this so that it's not
> going to "_|campaign_link|_#prove"
> 
> Main UX reason I don't think it makes sense to take the user straight to
> the prove it section is because that section is very bare bones and doesn't
> really provide much context that you're even on the right page AND it's
> super easy to navigate to using the campaign nav if we just take you to the
> campaign itself.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1397#issuecomment-38085553
> .

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething

**Comment by marahml** [comment]
Tested again and looks like you haven't changed it since yesterday - so
we're all good @deezone. Thanks!

On Thu, Mar 20, 2014 at 9:17 AM, Marah Lidey mlidey@dosomething.org wrote:

> @deezone - discussed this with Mike in person. I think its best to point
> to where the button says we're pointing to. Please send users to the link
> with #prove in it
> 
> On Wed, Mar 19, 2014 at 2:01 PM, mikefantini notifications@github.comwrote:
> 
> > @marahml https://github.com/marahml @DeeZonehttps://github.com/DeeZoneI don't think we should include the # prove ending to the link. I think
> > just linking to the campaign itself is the best course of action. And I
> > believe that is working properly (as I last tested last night).
> > 
> > So let's please make sure that the template reflects this so that it's
> > not going to "_|campaign_link|_#prove"
> > 
> > Main UX reason I don't think it makes sense to take the user straight to
> > the prove it section is because that section is very bare bones and doesn't
> > really provide much context that you're even on the right page AND it's
> > super easy to navigate to using the campaign nav if we just take you to the
> > campaign itself.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1397#issuecomment-38085553
> > .
> 
> ## 
> 
> _Marah Lidey_
> Digital Engagement Manager, DoSomething.org
> (212) 254-2390 Ext. 215
> 
> follow me: twitter.com/marahml
> follow us: twitter.com/dosomething http://www.twitter.com/dosomething

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething
