### ISSUE TITLE
campaigns – updated image mask not always loading

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1399]
The current header images on the following campaigns are not pulling the updated image mask with a darker gradient:
- [Comeback Clothes](https://www.dosomething.org/campaigns/comeback-clothes)
- [Hello Kittens](https://www.dosomething.org/campaigns/hello-kitties)
- [Support Board](https://www.dosomething.org/campaigns/support-board)
- [Momm-o-grams](https://www.dosomething.org/campaigns/momm-o-grams)
- [Project Shutdown](https://www.dosomething.org/campaigns/project-shutdown)
- [Throwback Games](https://www.dosomething.org/campaigns/throwback-game-night)
- [Faces of Immigration](https://www.dosomething.org/campaigns/faces-immigration)
- [Party Animal](https://www.dosomething.org/campaigns/party-animal)
- [Prom for All](https://www.dosomething.org/campaigns/prom-all)

[example of the updated gradient](https://www.dosomething.org/campaigns/digital-debates)

**Comment by mikefantini** [comment]
@mmwtsn made this high priority because this makes the text unreadable on mobile

**Comment by mikefantini** [comment]
@mmwtsn if you can pick this one up today that'd be great

**Comment by mmwtsn** [comment]
Our caching layers look like this:

![onion](http://1.bp.blogspot.com/-lVDxH1IS4sA/TpybaJqKFmI/AAAAAAAABYE/oPtTVih6xTA/s1600/onion.jpeg)

Andrea cleared the relevant caches and we're good to go!
