### ISSUE TITLE
Share users/sessions tables across new and old DBs

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#140]
This is tricky. @aaronschachter @desmondmorris if we share users, don't we also need to share roles? And if we do that, how do we square the cleaner roles definition in the new build against what's in the current app?

As long as both databases are running on the same machine, we should be able to use [this basic config trick](https://github.com/DoSomething/dosomething/blob/dev/settings.php#L150).

**Comment by mshmsh5000** [comment]
Thinking right now that we can require all authenticated traffic to be served by the new app, in which case we may not need to do this. We need to consider & solve any edge-case issues, e.g., the Foot Locker app, before we can be sure.

**Comment by mshmsh5000** [comment]
Assigning this to @mchitten while we figure out Foot Locker.

**Comment by mchitten** [comment]
Just to be clear on this: Foot Locker will still be on the old instance, right? So anyone who's actually going to the applications will be able to log in through the old database.

Where do we stand on this now? Do we want to import all users from the old database into the new one, then run a two-way queueing system to keep both up-to-date? Do we want to [share tables across databases](https://drupal.org/node/201673)?

I'd like some input from some of the other devs because this will affect you more than it will me, in the long run.

**Comment by desmondmorris** [comment]
![screen shot 2013-11-21 at 10 25 49 am](https://f.cloud.github.com/assets/129360/1592774/43a72f10-52c1-11e3-8f99-a411027601cd.png)

for the records

**Comment by mshmsh5000** [comment]
I think sharing tables will screw us on the roles side if we define roles & permissions differently in the new app.

Speaking more generally, there are two use cases (unless I'm missing more) that we need to consider:
1. An applicant registers/logs in, and submits an application
2. A reviewer logs in, and reviews applications

In the first case, we need to account for new users, and users who change their information. This should remain consistent with the new app's data. The mitigating factor here is that **the Foot Locker app ends on 19 Dec**. We obviously don't want to build any data sync facility that we may not need to use.

In the second case, user data should remain stable, and we can direct reviewers explicitly to the old app pool's admin area.

**Comment by mshmsh5000** [comment]
Closing this out, as some of the issues here are stale. By the time we launch the new app pool into production, we may not have any public-facing authenticated actions on the old pool.
