### ISSUE TITLE
campaign / static content – button text underlined

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1400]
The primary call to action button on campaigns and static content are underlined on hover because of a [Port to Neue style](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/scss/feature/_port-to-neue.scss#L13-L15) and a [Static Content](https://github.com/DoSomething/dosomething/blob/12f0a02f8548e3fd2e768ffa872490bb69ee3c69/lib/themes/dosomething/paraneue_dosomething/scss/feature/_content.scss#L39-L41) style.

**Comment by mmwtsn** [comment]
This is also affecting `.secondary` buttons which, by default, are underlined. Rules to exclude any `.btn` class should be added.

![btn](https://f.cloud.github.com/assets/1479130/2449090/a6cba51a-aead-11e3-92b7-fc7b25d57d70.png)

**Comment by DFurnes** [comment]
Fixed in earlier PR when we pulled overrides into Neue.
