### ISSUE TITLE
Mind On My Money - header image not showing up on /money ("action" page)

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1401]
go to /money, sign up, action page will be missing the header image

![image](https://f.cloud.github.com/assets/6330971/2450090/0a6bd1d0-aeb8-11e3-910f-1643e1d18287.png)

**Comment by mikefantini** [comment]
please update trello card when closed: https://trello.com/c/Z1DE8l5R

**Comment by barryclark** [comment]
@mmwtsn Could you take a quick look at this one plz?

**Comment by mmwtsn** [comment]
It looks like the background image was unset in the [stylesheet](https://github.com/DoSomething/DoSomething-7.x/blob/dev/sites/all/modules/dosomething/dosomething_campaign_styles/campaign_styles/2013/money/sass/_sections.sass#L42).

Should we send that over to Jacob? He's online.

**Comment by barryclark** [comment]
Yea, I'll do that just now. Thanks!

**Comment by jacobcassidy** [comment]
I took a look. There's a new global style that's conflicting with campaigns... "body background-image: none !important" which is hiding all background images across campaigns (the few that have one).

Not sure what the global style is there for, but it can be easily worked around by adding a line of markup for each campaign that needs it: "body.node-type-campaign background-image: url('THE-FILE-PATH') !important".

**Comment by mmwtsn** [comment]
It's coming from an [inline stylesheet](https://github.com/DoSomething/DoSomething-7.x/blob/6d969f21184d8638c57df30eda43b2abc09d91e2/sites/all/themes/doit/templates/html.tpl.php#L90) that was added into a template file last night.

@jonuy Do we need to nuke `background` styles on the old site?

**Comment by mikefantini** [comment]
closing this out since it's fixed
