### ISSUE TITLE
Zendesk - not showing users' name when questions submitted from Action Page contact us modal

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1402]
When users submit a question on the contact form for campaigns (PBJ, Comeback Clothers, etc) tickets are showing in Zendesk. (yay!) However we're not seeing the users name in Zendesk - instead (in place of the name) we're seeing a number.

**Comment by mikefantini** [comment]
Top entry is from mfantini+tester@dosomething.org (uid 1700010). First name on that user is set to "tester".

Second entry is from mfantini (uid 329195). First name on that user is set to "Mike".

**Removed zendesk account screenshot as it had user data in it - Barry**

**Comment by blisteringherb** [comment]
There are some users who don't have a first name set or an email address.  The priority for populating this field will be as follows unless we want to prompt the user to add their first name if they don't have one:
1. First name
2. Email address
3. UID

@mikefantini

**Comment by marahml** [comment]
Perfect!

@mikefantini what are your thoughts on prompting for first name / other
data in the future?

On Fri, Mar 21, 2014 at 11:27 AM, Morgan Rich notifications@github.comwrote:

> There are some users who don't have a first name set or an email address.
> The priority for populating this field will be as follows unless we want to
> prompt the user to add their first name if they don't have one:
> 1. First name
> 2. Email address
> 3. UID
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1402#issuecomment-38287061
> .

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething

**Comment by mikefantini** [comment]
sounds good... really shouldn't be a problem for most users, especially once @blisteringherb 's pull request gets merged to fix the problem.

Add it to the Zendesk FFA, an improved progressive data collection flow is a prerequisite though.

**Comment by marahml** [comment]
Will do - thanks!

On Fri, Mar 21, 2014 at 3:11 PM, mikefantini notifications@github.comwrote:

> sounds good... really shouldn't be a problem for most users, especially
> once @blisteringherb https://github.com/blisteringherb 's pull request
> gets merged to fix the problem.
> 
> Add it to the Zendesk FFA, an improved progressive data collection flow is
> a prerequisite though.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1402#issuecomment-38312026
> .

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething
