### ISSUE TITLE
Theme header / nav eats up content.

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1403]
Makes things like user/password, or devel/php unusable because the header/nav appears over the content.

![screen shot 2014-03-18 at 12 54 34 pm](https://f.cloud.github.com/assets/1236811/2451151/5af3b892-aec3-11e3-91a8-48b01732cd77.png)

**Comment by DFurnes** [comment]
Duplicate #1395.
