### ISSUE TITLE
Paypal donate button - not working

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1404]
Wonky link - either find a better link or integrate a Paypal "donate" button. Button current turns up poop.

**Comment by joolaay** [comment]
link: https://www.dosomething.org/about/donate

**Comment by mikefantini** [comment]
from @mshmsh5000 : 
We need to follow the procedure here: https://www.paypal.com/cgi-bin/webscr?cmd=_donate-intro-outside

The link as written doesn't work: http://screencast.com/t/jS3YqsNo8X

please update trello card here when closed: https://trello.com/c/5psdFIAq

**Comment by mmwtsn** [comment]
Sent Ritika a note about generating the button. We'll need to log in with the DoSomething PayPal account to generate it. I'll update this card once we have the HTML form from them.

**Comment by mmwtsn** [comment]
@blisteringherb What's the best way to add PayPal's donate form to the `/about/donate` page?

**Comment by joolaay** [comment]
eff this let's ask Lucas if donates to DoSomething.

**Comment by blisteringherb** [comment]
If we think we're only going to add that button to this one page, we can put the markup in a template var with a preprocess function, and only print it out on the about page.

**Comment by joolaay** [comment]
yawps - it's just on the /donate page.

**Comment by blisteringherb** [comment]
Actually all I'll need is the link that PayPal generates.  So I'll either need to log into Paypal or just get the email address that accepts payments and the donation ID.

**Comment by mmwtsn** [comment]
Here it is:

```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
  <input type="hidden" name="cmd" value="_s-xclick">
  <input type="hidden" name="hosted_button_id" value="F88PKVL23N3UA">
  <input type="image" src="https://www.dosomething.org/files/u/awesome-things/donate.png" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
  <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
```

**Comment by joolaay** [comment]
Hey @blisteringherb anything I can do to help?

**Comment by blisteringherb** [comment]
I updated the link.  Please take a look and make sure it's working how it should.  Thanks!

**Comment by joolaay** [comment]
Rad - it works! Thanks so much guys!
