### ISSUE TITLE
auth - failed log in on pitch page takes the user to a 404

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1408]
To recreate:
- go to https://www.dosomething.org/campaigns/project-shutdown  as an anonymous user
- click sign up
- give an invalid email/password combo

I've only see it happen on pitch pages not when trying to log in on the homepage.

**Comment by mikefantini** [comment]
I'm not getting error messages and it's just trying to take me to https://www.dosomething.org/node/31

![image](https://f.cloud.github.com/assets/6330971/2453240/9537a474-aedb-11e3-8b1e-58821026db20.png)

**Comment by barryclark** [comment]
@angaither @DFurnes You pass straight through both client-side and server-side checks if you enter an invalid email/password.

**Comment by mikefantini** [comment]
happening on all campaigns we just launched at 2pm today

**Comment by aaronschachter** [comment]
Seems like we need to add `node/[nid]` into varnish for all newly published campaigns... or change the form's destination to use path instead of the node URL....

@desmondmorris @mshmsh5000 any chance you can help with this?  Or instructions for how to update?

**Comment by mikefantini** [comment]
this wasn't happening on /money or /pbj... got the ip error message so can't confirm whether it's happening on /comeback-clothes

**Comment by barryclark** [comment]
@aaronschachter "change the form's destination to use path instead of the node URL" seems like a win, right?

**Comment by aaronschachter** [comment]
i suppose so...  guess its better than always needing to add rules to varnish, which we'll be stuck doing until we change the default node path to point to beta. which doesn't seem too soon.

**Comment by barryclark** [comment]
@aaronschachter  Yep, it's also ugly to get a "node/121" in the browser address bar. 

Assigning this one over to you @angaither. 2 issues here really:
1. [ ] Server-side email/password checking isn't throwing the user an error state (like "you entered an incorrect email/password".
2. [x] After auth it looks like users are been thrown to "node/[nid]" rather than "campaign/[title]".

**Comment by mikefantini** [comment]
@angaither this occurs even if the user gets the log in credentials right

**Comment by barryclark** [comment]
Still gotta fix the 2nd part.

**Comment by mikefantini** [comment]
Just retested. When I'm on any of the campaigns we published after 2pm today (i.e. any new nodes except for PBJ, MOMM, and Comeback Clothes) and I go to log in I receive a 404 message. This happens whether my login credentials are correct or not.

This works fine if I'm creating a new account. It's just when I'm logging in to an existing account that I get the 404 message.

And when I get this 404 message the url I'm seeing is https://www.dosomething.org/node/84 for example for /campaigns/hello-kitties

@angaither ^

**Comment by aaronschachter** [comment]
Yeah this one is weird. I get same behavior using an existing account, everything's working fine on Comeback Clothes but I get same behavior when trying to sign in on Project Shutdown.  node/31.

BTW can only edit a beta node if admin is in the URL.
works: https://www.dosomething.org/node/31/edit?destination=admin/content
doesn't work: https://www.dosomething.org/node/31/edit

On comeback clothes if you enter an invalid login, you do get an error message:
![screen shot 2014-03-19 at 10 18 15 am](https://f.cloud.github.com/assets/1236811/2460919/626ff51e-af71-11e3-8b80-8d847bad11b4.png)

But note, I am redirected to `node/362` upon invalid login.

**Comment by angaither** [comment]
We need to decide if we want to spend the time digging into fixing this temporarily, or we can update the rules in varnish and have 'node' point to the beta app. 
This would fix both the redirects on login & editors having to navigate to beta.node/XX/edit 
@mshmsh5000 thoughts?

**Comment by aaronschachter** [comment]
Also seems like #415 didn't do the trick as far as directing to a path instead of a node URL:

![screen shot 2014-03-19 at 10 24 17 am](https://f.cloud.github.com/assets/1236811/2461020/8a34466c-af72-11e3-8e67-317a1260c4c8.png)

**Comment by angaither** [comment]
Oh, duh. I didn't change the redirect in both places.
