### ISSUE TITLE
New users get opted into two Mobile Commons paths when signing up for a campaign

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#1411]
New users to the site who sign up for a campaign and provide their mobile number get both the general DoSomething registration message and the campaign sign up transactional message on SMS. In these cases, they should only get the campaign transactional.

![screen shot 2014-03-18 at 4 51 15 pm](https://f.cloud.github.com/assets/696595/2453533/3c73a8ca-aedf-11e3-801b-bd1bb76a5e8e.png)

Screenshot is an example with Comeback Clothes. Seems to also occur for non-staff pick campaigns.

Once fixed, we'll also need to re-add `164905` to the `Mobile Commons General Opt-In` field on `/admin/config/services/optins`.

cc: @mikefantini

**Comment by mikefantini** [comment]
desired actions:
- user registers for the site AND signs up for staff pick campaign -> user should go into that staff pick's mobile commons opt-in (e.g. 165501 for Comeback Clothes)
- user registers for the site AND signs up for non-staff pick campaign -> user should go into the non-staff pick mobile commons opt-in (164951)
- user registers for the site WITHOUT signing up for a campaign -> user should go into the General Do Something Web Sign up mobile commons opt-in (164905)

**Comment by mikefantini** [comment]
ok so apparently this is really hard...

I added 164905 back in to https://www.dosomething.org/admin/config/services/optins so that users will be getting two messages if they sign up for a campaign and register for the site.

Let's think about this more and see if Mobile Commons can help us come up with a solution.

cc: @jonuy

**Comment by aaronschachter** [comment]
Actually, might be possible to handle in our codebase... just a little tricky. And tricky to test. And, kinda just complicates the logic in the code. But possibly do-able.

Let me know if you want me to spend some time looking into it.

**Comment by angaither** [comment]
@mikefantini is this still happening?
