### ISSUE TITLE
/campaigns - images paths point to dev.dosomething

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1412]
Ones I'm seeing it for are:
- Prom for All
- Faces of Immigration
- Support Board
- Hello Kitties

![image](https://f.cloud.github.com/assets/6330971/2453693/e0d7d4c6-aee0-11e3-9017-e5f819051a73.png)

![image](https://f.cloud.github.com/assets/6330971/2453687/d6b108aa-aee0-11e3-8c5f-cb7ad8f6a109.png)

**Comment by barryclark** [comment]
Looks fine to me @mikefantini 

![image](https://f.cloud.github.com/assets/692762/2453703/f8fc8e98-aee0-11e3-9b34-6eeec7c51cec.png)

**Comment by barryclark** [comment]
Ooo that's weird. One for you @blisteringherb 

```
<div class="search-result">

  <div class="views-field views-field-ss-field-search-image">        <span class="field-content"><a href="/campaigns/faces-immigration"><img src="http://dev.dosomething.org:8888/sites/default/files/styles/300x300/public/StopDeportation_hero_square.jpg?itok=_AaFf3JN"></a></span>  </div>  
  <div class="views-field views-field-label">        <span class="field-content"><a href="/campaigns/faces-immigration">Faces of Immigration</a></span>  </div>  
  <div class="views-field views-field-sm-field-call-to-action">        <span class="field-content">Post a selfie to teach your friends about unjust deportation.</span>  </div>  </div>
```

**Comment by blisteringherb** [comment]
I just reindexed, and everything looks good now.  Can you double check?

@mikefantini

**Comment by barryclark** [comment]
:+1: looks good to me
