### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1419]
- [x] mobile number
- [x] birthdate
- [x] first name

**Comment by angaither** [comment]
The mobile number script is already [created](https://github.com/DoSomething/dosomething/blob/dev/scripts/import-mobile-data.php)
Just need to know how/where to run it.

**Comment by angaither** [comment]
Mobile numbers finished importing on Friday.

First name & birthdate are running now.

**Comment by barryclark** [comment]
@mshmsh5000 This is running reeeeaaally slow! About 1 field import per minute, so won't be completed for about a million years. Any ideas why?

**Comment by angaither** [comment]
Finished.
