### ISSUE TITLE
Update wiki with instructions on how to run Coder locally with vagrant

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#142]
- Do we use the Coder module?  Different command line stuff?

Please update https://github.com/DoSomething/dosomething/wiki/Contributing#coder with instructions for how to run locally, to ideally avoid tons of Developer spam (because devs will fix all errors first!)

**Comment by aaronschachter** [comment]
Also - if we're using the Coder module, shall we add Coder Tough Love - https://drupal.org/project/coder_tough_love ?  this would enforce good block comments.  Might want to open a separate issue for installing this module if so.

**Comment by mchitten** [comment]
Done @ https://github.com/DoSomething/dosomething/wiki/Contributing#coder
