### ISSUE TITLE
Foot Locker - log in takes you to a 404

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1424]
To recreate:
- go to https://www.dosomething.org/footlocker/associate/status as an anonymous user
- click log in 
- takes you to https://www.dosomething.org/user/registration?destination=footlocker/associate/status

![image](https://f.cloud.github.com/assets/6330971/2464676/ee48181e-af99-11e3-9bbd-576f973cf78f.png)

**Comment by mikefantini** [comment]
please update trello card here when closed: https://trello.com/c/MVAslZWv

**Comment by aaronschachter** [comment]
This is a legacy 7.x issue. Seems like all we need to do is change the login to link to `user/login?destination=footlocker/associate/status` instead of `user/registration`.  I can give this a shot.

**Comment by aaronschachter** [comment]
404 fixed via updating the legacy node's panelizer content, and clearing legacy varnish cache.
