### ISSUE TITLE
campaign (form) - AJAX error on entity reference fields

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1436]
When trying to fill out any entity reference field I get the this AJAX error below.

This is preventing us from updating photos and adding photos to add new campaigns.

To recreate, go to /node/add/campaign, try to reference an image in the Cover Image field (in Images) or typing anything in the Problem Fact field (in Know It)

![image](https://f.cloud.github.com/assets/6330971/2474096/deec81c6-b047-11e3-9c25-22c2ff513af6.png)

**Comment by mikefantini** [comment]
also happens on taxonomy reference fields (like Issue in Taxonomy and Discovery)

**Comment by angaither** [comment]
SO. Good news bad news.

`https://www.dosomething.org/entityreference/autocomplete/single/field_partner/field_collection_item/field_partners/NULL/h` 
was resolving to the legacy app which was causing the error.
it's not pointing to the beta app, but the error is still appearing.

Most [forums](https://drupal.org/node/1015938) about this issue point to the fact that the `base_url` is set incorrectly.
I was looking in production at `settings.php` and it doesn't look like it's ever set properly.
`if (!empty($insecure_port) && ($insecure_port != 80)) {
  $base_url = $protocol . $hostname . ':' . $insecure_port;
}
else {
  $base_url = $protocol . $hostname;
}`
but it's never set as a `$conf` variable.   So a `variable_get('base_url');` returns nothing.
@desmondmorris @mshmsh5000 we should probably fix that :flushed:

**Comment by angaither** [comment]
Although, I tried that. and it did NOTHING. 
So it also _could_ be issues with `beta.ds` vs `www.ds` protocally thingys. 
But now I'm just guessing.

**Comment by blisteringherb** [comment]
Were you saying it's _now_ pointing to the beta app?  I'm still seeing the error come from www.  Could this be an issue w/Varnish?

**Comment by angaither** [comment]
Confirmed.

https://www.dosomething.org/node/add/campaign?destination=admin/content
This url the entity references return normally

https://beta.dosomething.org/node/add/campaign
They throw an error here.

**Comment by mshmsh5000** [comment]
I don't have base_url set on legacy so we can avoid exactly this type of issue. I want to see how base_url is getting set on beta. I suspect it's not necessary or helpful.

**Comment by aaronschachter** [comment]
My recollection is that was added for securepages.

**Comment by mshmsh5000** [comment]
Host name is an env var.

`dosomething@web1:~$ printenv | grep DS
DS_DB_MASTER_USER=dosomething
DS_REDIS_HOST=10.241.0.32
DS_DB_MASTER_HOST=10.241.0.29
DS_INSECURE_PORT=80
DS_DB_MASTER_NAME=dosomething
DS_ENVIRONMENT=production
DS_REDIS_PORT=6379
DS_HOSTNAME=www.dosomething.org
DS_SECURE_PORT=443`

I don't think we should hard-code host name.

**Comment by mshmsh5000** [comment]
DS_\* env vars are set in two places on the web heads:

/etc/environment
/etc/php5/fpm/pool.d/www.conf

I unset these and restarted both php-fpm and nginx, but the hostname defaulted to dev.DS. Not good.

I'll get a PR together so that the hostname defaults to blank. This will require making sure the local dev environment still works without the defined hostname.

**Comment by mshmsh5000** [comment]
@desmondmorris FYI

**Comment by desmondmorris** [comment]
@mshmsh5000 +1 on killing hostname.  the envvars in /etc/environment are to make cli (drush play nice).

**Comment by mikefantini** [comment]
please update https://trello.com/c/7Pg0jgLU when closed

**Comment by desmondmorris** [comment]
![screen shot 2014-03-21 at 4 12 21 pm](https://f.cloud.github.com/assets/129360/2487469/2a2b4f4e-b135-11e3-88a8-371bf29f35bc.png)

**Comment by angaither** [comment]
Removing an image can only be done successfully on www
Request URL:https://www.dosomething.org/file/ajax/field_image_landscape/und/0/form-zbweI7q-OQxz_c6YTwq1efXKNEjZqiN5P--sOS6Q-ak

Adding an image only works on beta
but the thumbnail is no longer showing up.

**Comment by desmondmorris** [comment]
Replace:

`$hostname = getenv('DS_HOSTNAME') ?: 'dev.dosomething.org';`

WITH:

`$hostname = $_SERVER['HTTP_HOST'] ?: 'dev.dosomething.org';`

https://github.com/DoSomething/dosomething/blob/dev/config/settings.php#L27
