### ISSUE TITLE
action guides - remove subtitle field

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1440]
not a priority but whenever you get to it..

**Comment by mikefantini** [comment]
hold off on this actually, until we see what they look like when fully styled

**Comment by aaronschachter** [comment]
@mikefantini What's the status on this?  Close?

**Comment by mikefantini** [comment]
wow sorry super late on this... closing it out; have seen it used, not super concerned about it so let's just close it for now.
