### ISSUE TITLE
Footer - design QA todos

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1442]
- [x] remove “any cause, any time, any where”, from footer at bottom bottom left
- [x] Keep “privacy policy and terms of service” links to bottom right of footer
- [x] 1px gray border just above Privacy Policy and Terms and Conditions
- [x] tighten up space of end of About column and 
- [x] add bottom divider on footer above Privacy Policy and Terms and Conditions

**Comment by DFurnes** [comment]
Closed by DoSomething/paraneue#60 and DoSomething/neue@c2651662faa488d3b7bcbb98d0d2fb3bb7cc0baa.
