### ISSUE TITLE
Header - design QA todos

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1443]
- [x] Make sure line is clear down from the E in Explore in the header through to H1, H2, date, button, and the F of the facebook icon in the footer. 
- [x] Look at spacing of Header width
- [ ] Ask about register copyright logo on DS branding
- [x] Reposition the hamburger nav so it sits balanced with the logo (move left and down)

**Comment by DFurnes** [comment]
@barryclark Who should I be checking with re: the copyright mark on the logo?

**Comment by DFurnes** [comment]
Also, any clarification on "Look at spacing of Header width"?

**Comment by barryclark** [comment]
@DFurnes Crystal for the copyright. 

Re: header width, i'm not sure. We can just close that one.

**Comment by DFurnes** [comment]
Waiting on Crystal to hear back from Nancy on the copyright mark. Going to close this issue open a new one if we're going to change that.
