### ISSUE TITLE
Action page - 18px base font size?

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1447]
Re-visit 18px as a base font size for body copy. Implement back into neue if this works and rejigger the rest of the action page fonts so that they're not huge.

**Comment by mmwtsn** [comment]
Dave and I looked at this yesterday. Content width and gutter spacing both felt cramped with the larger base font size:

![18px](https://f.cloud.github.com/assets/1479130/2486976/44541ac4-b12e-11e3-8dea-56e4885c0b53.png)

**Comment by DFurnes** [comment]
Yeah, I'm actually thinking sticking to 16px as a base font size seems like a good idea after looking at the before-after more closely. One thing that we should look into though is a separate "article copy" size... which could be something more aggressive like 20-22px even.

This would be something that would be good to get the design team's input on.

**Comment by barryclark** [comment]
Cool, gonna close this one as we aren't going to revert to 18px base font-size.
