### ISSUE TITLE
action page (plan it) - location finder one column

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1450]
Make "find a location" one column (rather than spanning two columns). It should be treated the same as any of the other sections ("Hype", "VIPs", etc.) in this step.

**Comment by mmwtsn** [comment]
@mikefantini Votes to close the issue!

**Comment by mikefantini** [comment]
Yeah the reason for this is once we have the internal location finders (i.e. not linking off to an external site, but asking for zip code and displaying locations below) I think we're going to want this to remain as two columns.

Let's re-examine once we're ready to launch our first one of those.
