### ISSUE TITLE
Static Content Front end tweaks 

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1456]
Barry + Crystal have discussed most of these changes...let's step through them bc there may be dupes with other lists.

**Galleries**
- [x] vector art check box for image galleries - ON HOLD

**Spacing**
- [ ] text wrapping on top text
- [ ] eliminate gap between intro and additional text when there isn’t a gallery
- [ ] bullet points appear different on different pages - will correct in markdown 
- [ ] update spacing on the CTA styles to have less space inside horizontal rules and more space outside
- [ ] CTA on bottom of the page should have a bottom horizontal rule and spacing afterward
- [ ] spacing (leading) between lines is a bit awkward sometimes (like job/internship listings), Crystal + Barry discussed this as well
- [ ] lets have all content start a little lower than it is (see old people page and how that looks with no header)
- [ ] more space at the end of page before footer. 

**Typography**
- [ ] remove underlines from links, add teeny rollover change in color (crystal - thoughts?)
- [ ] buttons should not have underline on rollover
- [ ] sync header styles with campaign page
- [ ] sync section headers with campaign pages
- [ ] update section subheader formatting to what Barry/Crystal discussed (no longer purple)

**Comment by joolaay** [comment]
- [x] Look I _learned_ how to use **markdown!**

**Comment by angaither** [comment]
:+1: :dancer: :dancers: :tada:

**Comment by barryclark** [comment]
@julielorch Diego and I broke these out into issues based on the sections of the static content page. You can view all of the Design QA issues here - https://github.com/DoSomething/dosomething/issues?direction=desc&labels=design+QA&page=1&state=open

Let's close this card, if you're done with it?

**Comment by joolaay** [comment]
#woop
