### ISSUE TITLE
action page (partners) - comma and "and" logic with multiple partners

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1457]
If there are multiple partners attached to a campaign we should have commas and the word "and" separating them.

So if there are two partners, we just need "and" separating them. If there are three or more partners we'd need commas separating each and "and" right before the last comma.

example: https://beta.dosomething.org/campaigns/cell-phones-survivors

![image](https://f.cloud.github.com/assets/6330971/2477136/22372506-b06d-11e3-966f-3f1a30324902.png)

**Comment by barryclark** [comment]
@angaither Could you take a look at this one? Looks like a quickie and we'd love to get it knocked out this sprint. Thanks!

**Comment by mikefantini** [comment]
@angaither if we could get this in before deploy tomorrow evening that would be great
