### ISSUE TITLE
Coder: Sniff changes on pull requests

### ISSUE THREAD

**Issue by mchitten** [DoSomethingArchive/legacy-website#146]
Check pull request changes and run [PHP Code Sniffer](https://github.com/DoSomething/dosomething/issues/88) on them.  Leave comments for anything that's broken.

Requires #88

**Comment by mchitten** [comment]
This is done.  Just wanted to document that it happened.

**Comment by aaronschachter** [comment]
How does this work in relation to the actual d.o. contrib Coder module?  Does it use that?  I believe Coder will add some Drupal syntaxy type checks.  https://drupal.org/node/1419980

**Comment by mchitten** [comment]
Yes.  It runs php code sniffer with Drupal's ruleset.

**Comment by desmondmorris** [comment]
I did not know that was possible.  Pretty cool.  Did you use this: https://github.com/Ishino/Drupal-PHP-CodeSniffer-ruleset

**Comment by mchitten** [comment]
Yep! There's a command alias that actually makes it happen but the command that's run (for the automated tests) is:

`phpcs --standard=/var/www/hooks/test/coder/coder_sniffer/Drupal/ruleset.xml --extensions=php,module,inc,install,test,profile,theme --report=json`

**Comment by aaronschachter** [comment]
This doesn't seem to be running on PR's anymore. Mike documented the setup here: 

https://docs.google.com/a/dosomething.org/document/d/13WfT3WBJb75fMMI9wsGePehdmvR8Vbz9NUws5RxlNa4/edit#heading=h.as335mm36coj

Re-opening to either get this working again, or to scrap it all.  Ideally it should work, so we're not leaving comments on PR's for spacing and things like that.

**Comment by desmondmorris** [comment]
I can take a look this afternoon

**Comment by barryclark** [comment]
Adding you @desmondmorris seems related to #129

**Comment by desmondmorris** [comment]
We really should be doing this before code gets pushed.  We can achieve this via githooks.  I am going to close this in favor of a better all around solution for tasks like this.
