### ISSUE TITLE
Vector art galleries in static content pages

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1460]
We have awesome galleries for photos, but we need a modified gallery for icons to support wider spacing between icons than the spacing between photos. 

It would be awesome to default to photo gallery, and  just have a check box on the static content form to denote an icon gallery. 

@barryclark Then front end can tweak properly! yes!

**Comment by mmwtsn** [comment]
:palm_tree: Do you have a sketch to illustrate?

**Comment by joolaay** [comment]
@mmwtsn yes, but pause for a sec b/c crystal and I still have to sell the idea of icons to Nancy.

**Comment by joolaay** [comment]
(news from last night)

**Comment by joolaay** [comment]
OTAY - we're currently removing all vector icons from the site, so we don't need these specific galleries at this time. I'd like to bring it up again in 3 months or so, but scratch for now.
