### ISSUE TITLE
Add Google Analytics tracking to auth modal

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1473]
We need to fire a custom Google Analytics event when users click the "Sign Up" button on the pitch page (triggering the modal), and when the form is successfully submitted (when they reach the logged in state).

**Comment by mikefantini** [comment]
@DFurnes possible to fire custom event to someone failing log in or account creation as well?

**Comment by DFurnes** [comment]
@Bladt When the user clicks the signup button, we'll trigger a Google Analytics custom event. If the user closes the login modal and clicks the signup button again, we should re-trigger this event right?

**Comment by DFurnes** [comment]
@mikefantini Yep, this shouldn't be too hard.

**Comment by DFurnes** [comment]
Game plan. This should let us know when users open the auth modal, close it manually, and whether or not it submits successfully:
- We fire a `Modal - Open - [#id]` custom event when a modal is opened (such as the sign-in modal, or any of the 'more info' modals on the campaign page).
- We fire a `Modal - Close - [#id]` when that modal is closed (only by user interaction... navigating to another page by a link in the modal or by submitting a form would **not** trigger this.
  - We fire a `Form - Submitted - [#id]` event when a form with client-side validation submits without errors (even if errors have been triggered before).
  - We fire a `Form - Validation Error on Submit - [#id]` event when a form with client-side validation is blocked from submitting by client-side validation error(s).

For more information on what happens in the form, we have some events firing on inline validation checks:
- We fire a `Form - Inline Validation Error - [#field]` whenever a field causes a client-side validation prompt (this is _any_ error, but could be useful just to see where errors occur).
- We fire a `Form - Mailcheck Suggestion - [domain]` when we offer a Mailcheck suggestion for a potentially misspelled email.
- We fire a `Form - Mailcheck Suggestion Used - [suggestion]` when the Mailcheck suggestion is clicked.

**Comment by mikefantini** [comment]
@DFurnes re: @Bladt When the user clicks the signup button, we'll trigger a Google Analytics custom event. If the user closes the login modal and clicks the signup button again, we should re-trigger this event right?

@Bladt said let's _not_ re-trigger the event because it would artificially inflate our numbers.

**Comment by DFurnes** [comment]
Is that different from a user clicking back on their browser though (in the old flow) and then clicking on "Sign Up" again? I'm not sure if it makes sense to start tracking clicks in some circumstances and not others.

(If that's what we want to do, that's cool too. It just means we'll need to find a way to track what events have already fired in a session and not fire them twice.)

**Comment by DFurnes** [comment]
Talked with @mikefantini and @joshcusano and we're gonna go with the simpler implementation of this for now. We can re-visit this next sprint and change if we need to do something more complex.
