### ISSUE TITLE
Mailchimp vars cleanup: group_id

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1476]
Depends on #1454 

Once message broker is properly handling `mailchimp_grouping_id` and `mailchimp_group_name` variables, remove all references to the `mailchimp_group_id` variables / form elements and delete the variables from the db.

**Comment by deezone** [comment]
See https://github.com/DoSomething/mbc-registration-email/pull/7 to expand to use `mailchimp_grouping_id` and `mailchimp_group_name`

**Comment by deezone** [comment]
Latest release (0.1.4) of mbc-registrations-email (https://github.com/DoSomething/mbc-registration-email/compare/0.1.3...master) is processing all variations of mailchimp_group_id / group_name / groupings / etc. It should be through the backlog of entries in the queue in the next 24 hours. I'll start the cleanup at that time.

**Comment by aaronschachter** [comment]
This was fixed in #1576
