### ISSUE TITLE
mobile number in new MailChimp accounts

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1480]
The payload to dosomething_user_mbp_request(''user_register'') needs to include the mobile number.

See issue #892

**Comment by mikefantini** [comment]
@DeeZone moved this to the backlog as there are more pressing issues open for now.

**Comment by deezone** [comment]
@mikefantini This was a quickie that I took care of while I was working in the same area of code. It will be in place for the Monday deployment.
