### ISSUE TITLE
Signup optin form mailchimp enhancements

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1483]
Refs #1454 
- Store the valid `grouping_id` values as an array in a variable.  Create a separate form to enter them.  Use the variable array as a select list on the optin form, in the interest of preventing data entry errors.

~~Verify that the Mailchimp grouping ID and group_names values are legit via Mailchimp API call.  Would require adding Mailchimp API as a variable, and adding mailchimp API library to connect... so... eh.  Probably not this one so much.~~

**Comment by aaronschachter** [comment]
Updating this to drop connecting to Mailchimp to verify valid values.  The dropdown for Grouping ID is still valid though and should be handled along with #2258.

**Comment by angaither** [comment]
@aaronschachter do you know if this issue is still needed?

**Comment by aaronschachter** [comment]
Seems like this one is okay to close -- I'm trying to connect the pieces through the various linked issues, I think this was for when we had hardcoded 2 List ID's for Old People and Members -- making those variables (and then possibly moving storage into the Helpers table to keep things in one place?). I've been out of the loop on what our Mailchimp configuration looks like these days, but this one seems more like a nice-to-have refactor type issue.

**Comment by angaither** [comment]
great, thanks @aaronschachter
