### ISSUE TITLE
Signup Data Form

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1484]
Build functionality to include a signup data form on a campaign.

Required for Comeback Clothes:
- Collect address in form and save to user - depends on #1026
- Add link to campaign, which opens form in modal
- Track whether or not the user has submitted the form

Tech specs: https://docs.google.com/a/dosomething.org/document/d/15NfJ8UoUfkjImPpjKFo-NIYxoQq8NNU2mT4Whmaj_Vc/edit

**Comment by mikefantini** [comment]
@aaronschachter the link to trigger this modal for Comeback Clothes will live as a bullet point in Stuff You Need in the Plan It section... this should be the last bullet point (i.e. below all content a campaigns lead enters in that field and below any action guide they associate with the campaign)

**Comment by aaronschachter** [comment]
@mikefantini Do we want to add some type of confirmation message upon submit?  Is there a generic message we can use, or do we need to add another field into the Signup Data Form config?

**Comment by mikefantini** [comment]
Yeah just put this in an FFA I'm starting. We're going to need this to be specific to each form.
