### ISSUE TITLE
EntityMetadataWrapperException: Unknown data property field_video.

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1489]
Code pull as of 24 March, 11:15 with a fresh import of the db with dosomething-20140321-stage.sql produces:

```
EntityMetadataWrapperException: Unknown data property field_video. in EntityStructureWrapper->getPropertyInfo() (line 335 of /vagrant/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).
```

Front page -> http://localhost:8888

**Comment by aaronschachter** [comment]
where is this occurring?

**Comment by deezone** [comment]
Front page -> http://localhost:8888

**Comment by deezone** [comment]
After a `ds pull stage` the error continued to appear on the front page but navigating to `http://localhost:8888/node/362` seem to clear it up including returning to the front page as well as other content types.
