### ISSUE TITLE
Disable optimizely in ds pull 

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1507]
Promote developer sanity and disable the optimizely module upon `ds pull stage`.  Technically needs to happen in the `pull_db` function.

**Comment by deezone** [comment]
If possible, I'd like to figure this out. I'll work through the details and perhaps poke you a few times if it's OK with you? I'm close to a new release of the module and I'd like to understand / work on the `ds pull stage` disable options.

**Comment by barryclark** [comment]
Was there any progress on this one @DeeZone?

**Comment by deezone** [comment]
@barryclark Nope but I hope to have some extra bandwidth next week. I'll add this to my list.

**Comment by angaither** [comment]
@DeeZone did you get a chance to look at this? is it done? I don't see anything in the build script about this, but I'm not sure if it happened elsewhere

**Comment by deezone** [comment]
Ha! A 1.5 year later and...

> I'm close to a new release of the module and I'd like to understand / work on the ds pull 
> stage disable options

Is true once again. I'm working on a `7.x.-3.x` release of the module. I'll take a look and close this issue out this week.
