### ISSUE TITLE
Aaron Schachter takeover

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1508]
@aaronschachter's username appears in an incognito tab on the `/user` sign in page on 
https://beta.doseomthing.org/user
![](http://f.cl.ly/items/462B0V293b2f0g1t3Y22/Screen%20Shot%202014-03-25%20at%2010.18.20%20AM.png)

**Comment by angaither** [comment]
Seems to have been some drupal crazy cache. It's gone now. 

![](https://pbs.twimg.com/profile_images/344513261577739462/0ffdff5acd5ff3bcd34c0cd10baf2a14.png)

**Comment by DFurnes** [comment]
This is one of my favorite issues so far. +1. Value added.
