### ISSUE TITLE
Method to swap out github username in make files

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#151]
Currently, the only way you can test the make files is by committing them into the repo, since the build-dosomething.make is hardcoded to use the DoSomething repo: projects[dosomething][download][url] = "git@github.com:DoSomething/dosomething.git"

Maybe this is issue is just a nice to have, and we change the file to our forks locally to test ... and then just make sure to not commit that change to the make file back into the repo.

If this is the case, update documentation to do so: https://github.com/DoSomething/dosomething/wiki/Contributing

**Comment by desmondmorris** [comment]
#386 actually borks the install step.  This needs to be reverted for now

**Comment by aaronschachter** [comment]
Hey @desmondmorris -- we're attempting to close out issues for milestone 0.1 and this is the last one.  Any ideas on how we could test make files locally?

**Comment by mshmsh5000** [comment]
Does this formulation not work?

`projects[my-module][type] = "module"
projects[my-module][download][type] = "file"
projects[my-module][download][url] = "http://localhost/mymodule"`

**Comment by aaronschachter** [comment]
It might for local, but wouldn't that bork it for QA / Production environments?

**Comment by aaronschachter** [comment]
Speaking with @desmondmorris , this isn't necessary for milestone 0.1  Moving to milestone 0.3

**Comment by barryclark** [comment]
un-milestoning and assigning to @desmondmorris

**Comment by desmondmorris** [comment]
This is fixed with the introduction of drush make local #526
