### ISSUE TITLE
static content - call to action

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1511]
- [x] Large button on the CTA
- [x] .cta padding-bottom: 25px; .cta h3 { margin: 25px 0 10px 0; }
- [x] CTA on bottom of the page should have a bottom horizontal rule and spacing afterward

**Comment by weerd** [comment]
Ended up doing 35px padding top and bottom of CTA and removing top margin on h3. No need to address underline in new style for CTA. Looks good!
