### ISSUE TITLE
static content - gallery

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1513]
- [x] Gallery wrapper background #eee
- [x] Gallery h3 headers #444 18px bold

**Comment by DFurnes** [comment]
Should all `h3` be getting these styles? If not, does it make sense to use a different heading here?

**Comment by DFurnes** [comment]
Also, should we be using `#ddd` as our `$light-gray` Neue variable? Or if not, should we be switching that variable to be `#eee`? The argument against `#eee` when we were setting up the variables is that it will disappear on lower-quality monitors (see one of the shitty 19" ones in the office for test case).

**Comment by weerd** [comment]
We should probably add a class to the headings if not a universal change.

**Comment by DFurnes** [comment]
:+1:

**Comment by weerd** [comment]
I'm using the `$light-gray` variable for the gallery background. If it needs to be a slightly bit lighter we can run it through a sass lighten() function. But this way we're using Neue's vars :) I'm going to run the visuals by Crystal to confirm how it looks, etc.

**Comment by weerd** [comment]
Chatted with Crystal. Adding background color to the CTA, etc. instead. Looks nice :)
