### ISSUE TITLE
static content - misc spacing

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1514]
- [x] lets have all content start a little lower than it is (see old people page and how that looks with no header)
- [x] ~~50px margin at the bottom of all of the page's content wrapper~~ 
- [x] spacing (leading) between lines is a bit awkward sometimes (like job/internship listings), Crystal + Barry discussed this as well
- [x] eliminate gap between intro and additional text when there isn’t a gallery
- [x] add a bit more top margin to CTA's on static pages.

**Comment by DFurnes** [comment]
Re: the bottom margin, let's standardize this across content types (as a mixin) and use rems.

**Comment by mmwtsn** [comment]
:thumbsup: to setting that margin in rems and scaling it off our base font size if possible.

If this becomes a common pattern, it's a good candidate for a little pixel to rem mixin.

**Comment by weerd** [comment]
_NOTE_: 
- The 50px margin at bottom was addressed with new CTA styles (the spacing was desired for CTAs that are at the bottom of the page, but the new styles take care of need for spacing).
- The leading between lines in listing was addressed by editing the markdown. Used a markdown list to render the content in the backend.
