### ISSUE TITLE
static content - link / button and misc styling

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1515]
- [x] buttons should not have underline on rollover
- [x] text wrapping on top text
- [x] update section subheader to match campaigns template subheaders - and lose the purple

*removed the underline links item to separate out into issue for Dave on Neue.

**Comment by DFurnes** [comment]
The first two re: links and buttons should already have been fixed in Neue.

**Comment by weerd** [comment]
I believe there may be some things overriding the button style from neue that's affecting it.

**Comment by weerd** [comment]
Looked it over w/ @DFurnes and he confirmed some of those items are now covered in Neue. Need to run others by Crystal to confirm design choices.
