### ISSUE TITLE
Log-in form is now requesting address

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1521]
![screen shot 2014-03-25 at 12 56 08 pm](https://f.cloud.github.com/assets/583202/2514942/64821f5e-b43e-11e3-9a74-70f93f0adfc0.png)

It seems like the login form is prematurely requesting the user's address information. This is potentially kinda awkward. :cactus: 

Production Link: https://www.dosomething.org/user/register

**Comment by angaither** [comment]
Temporarily hidden in production. will submit a PR to fix.

**Comment by DFurnes** [comment]
Cool cool. That was super quick. :bicyclist:
