### ISSUE TITLE
Rework the drupal.scss .element-invisible

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#1525]

**Comment by DFurnes** [comment]
@weerd Perusing through old issues (nostalgia!), is this [looking better](https://github.com/DFurnes/phoenix/blob/6ac3dd25a7238dfce747176f5be46d5ad9cb0f4e/lib/themes/dosomething/paraneue_dosomething/scss/overrides/_drupal.scss#L24-L26) now?

**Comment by weerd** [comment]
¡Es bueno! :+1:
