### ISSUE TITLE
Reportback file extensions

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1526]
The `dosomething_reportback_get_file_dest` function is not consistently writing image files with extensions.

![extension sadness](http://f.cl.ly/items/0o3g1U1Z2V0G43442e1X/Screen%20Shot%202014-03-25%20at%202.54.20%20PM.png)

**Comment by barryclark** [comment]
Got time to take a look this sprint @angaither?

**Comment by angaither** [comment]
I haven't been able to replicate this locally. 
Perhaps we can add watchdog when the files get uploaded?

**Comment by aaronschachter** [comment]
@jonuy do we have a way to test whether or not these guys are coming from SMS reportbacks? i haven't seen it either in my testing...

**Comment by angaither** [comment]
Confirmed, this is coming from mobile reportbacks. 
@jonuy HALP
