### ISSUE TITLE
Merge Paraneue into main repo

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1529]
Since Neue is already handling most of our style abstraction, we're thinking of merging Paraneue and Paraneue_DS to simplify workflow.

Looking at where our views are actually being generated, Paraneue is basically responsible for two partials (`html.tpl.php` and `page.tpl.php`) and the Drupal defaults, and everything else comes from the app-specific theme. Since we'll likely need to override the site chrome for international sites as well, it seems to basically boil down to just one template that's actually getting inherited.

With this in mind, we came to the conclusion that Neue itself is the shared "starter" that all of our child themes should be inheriting from. This also means we can keep all of our dependencies in one place, which makes the system as a whole a bit easier to grasp and keep tabs on (for example, with more tightly locking Bower versioning to releases).

**Comment by mmwtsn** [comment]
![Desmond](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/34218/desmond-1384801076.png)

**Comment by mikefantini** [comment]
@DFurnes is something that needs to get in for this sprint?

**Comment by mmwtsn** [comment]
@mikefantini This would fall under refactoring. It would be better to get this in sooner rather than later (if we decide to move forward with this decision) but it isn't urgent.

Having only one theme will simplify development and deployment which should help stabilize the code base somewhat.

**Comment by mikefantini** [comment]
@mmwtsn cool thanks, I'll peg it to this sprint as medium priority then
