### ISSUE TITLE
action page (button) - need to rework font size

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1540]
Flagging it in this individual instance but we need to solve this for the system as a whole.

Because we made the buttons on the action page our big button style we're now running into issues with it on mobile. See screen shots.

It seems like the largest number of characters we have on any of our buttons is 19 characters.

Given that, perhaps we should re-examine the font on our big button style so that it doesn't make the button go into two lines on mobile.

![photo 13](https://f.cloud.github.com/assets/6330971/2528174/d47a0424-b50c-11e3-885f-a3aee3bf046f.PNG)
![photo 14](https://f.cloud.github.com/assets/6330971/2528176/d5c08a06-b50c-11e3-9018-6396f08e4cab.PNG)

**Comment by mikefantini** [comment]
@crystalruthbell this is something I'd love for you to weigh in on; we just need to make sure that we come up with a solution that works across the entire system

**Comment by weerd** [comment]
Line height could be adjusted as well to be tighter on mobile.

**Comment by barryclark** [comment]
@mikefantini I don't think this is a problem any more as BIG buttons are gone from the site completely. Happy to close this out?
