### ISSUE TITLE
Teens for Jeans - redirect needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1550]
Need to have Teens for Jeans show up in search results. It currently only lives on the old app and we're not pulling in anything from the old app into search.

In order to have this show up in search, I had Nami create a dummy campaign (nid 1144) on beta. Now we just need that to redirect to nid 731115 on legacy.

No signup needed (basically treating this the same as we did for Bully Text or Pregnancy Text in #1213).

**Comment by blisteringherb** [comment]
I set this redirect up in the admin.  We should be good to go.
