### ISSUE TITLE
Replace Apache with Nginx in Staging & Development

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#1553]
We should replace Apache with Nginx on both the staging and development instances to get things closer to the production setup.  Nginx treats some things differently than Apache (ex: ip_address()) and we should not be adding conditional code to handle both instances.

@mshmsh5000 priority?

**Comment by aaronschachter** [comment]
Would this eliminate the need for the `dosomething_helpers_ip_address` function?  Or would `ip_address()` still not work?

**Comment by desmondmorris** [comment]
@aaronschachter yeah the `HTTP_X_FORWARDED_FOR` _should_ always be present in nginx, so the helper function should always evaluate and the first condition.  I think the we should def keep a wrapper function around the check of the `$_SERVER` variable though, so that helper function can live on I believe.  We may just have it return just `$_SERVER['HTTP_X_FORWARDED_FOR']` in the future though

**Comment by aaronschachter** [comment]
@desmondmorris Do we still need this?

**Comment by angaither** [comment]
done!
