### ISSUE TITLE
Update Campaign Module vars to match classes in template

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#1561]
Quick fix to make things more right in the world.

**Comment by aaronschachter** [comment]
Is this for static content?

**Comment by weerd** [comment]
Static and would apply to campaigns as well. (Need to double check if anywhere else).

From:
 `<h2 class="subtitle"><?php print $cta; ?></h2>`

To:
 `<h2 class="subtitle"><?php print $subtitle; ?></h2>`

AND updating where the module sets the variable for the template file.

Basically changing the $cta vars to $subtitle (in headers), since it's a subtitle where it's being used and thus unify the headers across static pages and campaigns w/ both the vars and the classes :)

**Comment by weerd** [comment]
I think this was completed in the Neue refactor sprint, etc.
