### ISSUE TITLE
Eliminate PHP short tags

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#1565]
The PHP config on QA is sensitive to this. Instead of changing the config, I'd rather fix the few outliers. I see [just one in this template](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/node--static_content.tpl.php#L61):

![screen shot 2014-03-28 at 12 30 34 am](https://cloud.githubusercontent.com/assets/149811/2546301/d9a31aa0-b631-11e3-9976-60141b29eb75.png)

**Comment by weerd** [comment]
Righty-o! Working on wrapping up a couple morning issues and then I'll jump on this one :)
