### ISSUE TITLE
Deployment should build from a master branch and tag things

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1573]
Currently once you commit to dev, you can't actually test the production codebase anymore.

Have Georgie Boy merge dev into master and create a relevant release tag.

**Comment by desmondmorris** [comment]
We should be tagging releases before code is moved to staging/production.  The common strategy is to use releases branches, but we can use a the master branch as well.  This may get hairy if we decided to manage hotfix patches, but will be fine for now.

### Release
1.  Merge contents of dev into the master branch
2.  Version bump.  We will need a file that we we use to keep track of the current version of the package.  (eg. ./VERSION).  Then we can provide a simple.sh to bump said version
3.  Create release tag based off of version in marker.  Push master and tag to remote

_Ideally_, we can provide a release.sh script that does this for us

### Deploy

Our deployment process will need to be modified to accept tag numbers as deployment markers.  We could assume that master is "latest greatest", but again this gets difficult when we start talking hotfixes.

**Comment by aaronschachter** [comment]
We do this. Except for the whole master branch thing. But who needs that.  We have releases and so far so good. Closing.
