### ISSUE TITLE
Add Stage File Proxy, enable in QA/Vagrant environments

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#1575]
Important for keeping QA files in sync, and obviates the need to pull files in Vagrant.

**Comment by blisteringherb** [comment]
Here's a link to the Jenkins job that enables Stage File Proxy in QA - http://cerebro.dosomething.org:8080/job/Enable%20Development%20Tools

@aaronschachter

**Comment by aaronschachter** [comment]
Gotcha... looks like it's working correctly in QA.  Is there anything else we need to do on this one, or can we close this @blisteringherb ?

**Comment by aaronschachter** [comment]
Oh. Part of the issue description is to enable in Vagrant.... eliminating the need for `ds pull stage --files` anymore.
