### ISSUE TITLE
Home page hard-codes some images to http

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#1582]
[Here](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/node--home.tpl.php#L18) and [here](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/node--home.tpl.php#L32). Really these four should all be protocol-neutral URLs.

**Comment by DFurnes** [comment]
Whoops. Good catch.

**Comment by mikefantini** [comment]
@mshmsh5000 @DFurnes is this for the current homepage? If so is it worth fixing before next Thursday or just keep as it is until we have our new homepage?
