### ISSUE TITLE
/campaigns (staging) - HTTP 0; Request failed: Connection timed out

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1585]
Can't access /campaigns on staging site (everything is fine in prod). Preventing me from showing an example of a bug in prod that I don't want visible to the public.

Getting this error message:

![image](https://cloud.githubusercontent.com/assets/6330971/2569880/4bc62a2e-b8f2-11e3-86c5-05e18319e2d4.png)

**Comment by mikefantini** [comment]
once I have this I can show example for https://github.com/DoSomething/dosomething/issues/1438

**Comment by angaither** [comment]
This is fixed on staging, closing.
