### ISSUE TITLE
Fact Page CTA alignment

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1587]
Looks weaksauce.

example: http://staging.beta.dosomething.org/node/604

![screen shot 2014-03-31 at 12 43 40 pm](https://cloud.githubusercontent.com/assets/1236811/2570024/ed9c9940-b8f3-11e3-8c7e-9ad050b18cc3.png)

**Comment by mikefantini** [comment]
Should keep it looking consistent with static content (like https://www.dosomething.org/about/donate).

![image](https://cloud.githubusercontent.com/assets/6330971/2570234/9a6beffc-b8f6-11e3-94d7-be4a4e681557.png)

**Comment by mikefantini** [comment]
scratch that should look like this: https://s3.amazonaws.com/uploads.hipchat.com/34218/734460/7H0BR42z8n1TKB0/Screen%20Shot%202014-03-28%20at%203.24.12%20PM.png

**Comment by weerd** [comment]
All set :)
