### ISSUE TITLE
CTIA messaging

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1617]
Need to have CTIA compliant messaging on registration form (at the bottom of the form is fine).

4 msg/mo. Message & data rates may apply. Text STOP to opt-out, HELP for help

**Comment by mikefantini** [comment]
only needed when a user is creating an account, not needed on the log in view... needed on both the modal and /user/register.

@DFurnes i think this makes the most sense at the very bottom of the form (below both button _and_ "Log in to an existing account"), but your call on what makes the most sense.

**Comment by DFurnes** [comment]
Bottom of form:
![screen shot 2014-04-03 at 5 43 25 pm](https://cloud.githubusercontent.com/assets/583202/2609782/421674da-bb7b-11e3-937c-b5a43c26dc55.png)

Inline in form:
![screen shot 2014-04-03 at 5 59 17 pm](https://cloud.githubusercontent.com/assets/583202/2609790/4921cc20-bb7b-11e3-8c1c-0ee443346423.png)

I think it might actually make more sense by the specific field in the form it relates to. Otherwise I feel like I might be afraid to register due to the lack of context when its off on its own in the footer. Thoughts?

**Comment by DFurnes** [comment]
Talked with @mikefantini and @Bladt and we're gonna try going with Option 2. :dart:

**Comment by mikefantini** [comment]
@marahml told @DFurnes to hold off on adding this to the form until you get him updated language. Please update this issue with the new language when you get a chance so we can get it up.

Thanks!

**Comment by mikefantini** [comment]
@mmwtsn @DFurnes did you guys get updated language for this? don't think we should close it until we have this from @marahml

**Comment by DFurnes** [comment]
That's ok, I'll put in another PR when I get updated language.

**Comment by marahml** [comment]
Here's a better way to say what we want to: (similar to old site)

Creating an account with us won't sell your soul, but it means you agree to our terms of service (LINK HERE) & to receive our weekly update. Message & data rates may apply. You can always text STOP to opt-out, HELP for help.

*sorry in my original issue I forgot to mention that we need to link Ts&Cs

**Comment by Bladt** [comment]
From what we have tested in the past, we've seen the simplest, most straight forward CTIA language perform the best. That is, have higher conversion rates. My hypothesis was (and remains) that when use language like "we promise we will never send you spam," a user skimming will see the word spam and think "wait, I might receive spam" and at the margin not convert as often.

**Comment by marahml** [comment]
@Bladt If more simple has higher conversions, lets go for it! As long as they can understand it, I'm game.

Hows this?

Creating an account means you agree to our terms of service (LINK) & to receive our weekly update. Msg & data rates may apply. Text STOP to opt-out, HELP for help.

**Comment by DFurnes** [comment]
Sounds great to me! Do we no longer need the "4 msg/mo." text?

**Comment by marahml** [comment]
@DFurnes "weekly update" covers the frequency requirement!

**Comment by mikefantini** [comment]
@marahml @Bladt so this is what this will look like:

![](https://cloud.githubusercontent.com/assets/583202/2633312/1c87a7d0-be6d-11e3-96f6-7fe07e660f27.png)

**Comment by marahml** [comment]
Looks good! I'm going to chat with @crystalruthbell about making that font a shade lighter, so that its less prominent than the help text.

But we can close this for now. If we decide to change font - I'll reopen. 

Thanks!

**Comment by DFurnes** [comment]
@marahml Cool cool! You can just open a new issue if we need to make any further changes.

**Comment by marahml** [comment]
@DFurnes - @crystalruthbell said we can go ahead and make the CTIA text a shade lighter than the help text in the reg form

**Comment by DFurnes** [comment]
Ok, going to open a new issue for that.
