### ISSUE TITLE
QA: Add New Relic support

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#164]
We have a bulk licensing deal with New Relic now, so we can get the agent on all instances.

We want to keep this out of the Salt build in the public repo, so non-DS users can fork the project when this becomes public. So I'll be doing this on a per-instance basis for now.

Setting app name:

https://newrelic.com/docs/php/php-agent-phpini-settings#inivar-appname

**Comment by mchitten** [comment]
Could we use the `ds` build script to populate a newrelic.ini file?
