### ISSUE TITLE
campaign (action guides) – "banner" font sizes on mobile

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#1643]
## Description

Pending the design approval of @crystalruthbell, Mike suggested we reduce the font size of the "banner" header type in the action guide modals to allow for longer titles as the current limit is `~12` characters.

![modal](https://cloud.githubusercontent.com/assets/1479130/2608536/0b9c1d74-bb6c-11e3-84b2-1841e74f0520.png)
### Notes
- This change should affect all modal styles
- This is waiting on a fix to [re-instate](https://github.com/DoSomething/dosomething/issues/1644) the default styles from Neue

**Comment by DFurnes** [comment]
This is fixed in Neue 6.0! Closing.
