### ISSUE TITLE
campaigns - additional report back question

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1647]
For now just need a radio button hard coded into Comeback Clothes.

Question: 
- Did you recycle the clothes through H&M?

Options:
- Yes
- No

Eventually we'll want this in the campaign creation interface so that campaigns can add their own additional report back questions.

---
- [x] New table: `dosomething_reportback_field` -- stores a node's additional reportback fields
- [x] New table:  `dosomething_reportback_field_data` - stores the user submitted field data per reportback
- [x] Render reportback_field as form element on reportback form
- [x] Write reportback_field form value to dosomething_reportback_field_data
- [x] Log reportback_field form value to dosomething_reportback_log
- [x] Update hook to populate record in `dosomething_reportback_field` for Comeback Clothes (nid 362)

**Comment by aaronschachter** [comment]
I've been giving thought to whether or not these additional reportback fields should be implemented as a Field Collection, or as a custom table. Leaning toward a custom table, details of pros and cons are listed out here https://docs.google.com/a/dosomething.org/document/d/1MYr1pu0n4o3TIO72vUIJBqF4TN5yIDFPKBojIt9MPmk/edit#

As far as storing these in the database, I think it makes the most sense to store each additional question as a row in a `dosomething_reportback_data` table, vs. adding extra columns into the dosomethign_reportback table, where each column would only be for one campaign.

@angaither @blisteringherb @mshmsh5000 @desmondmorris if you have a minute, mind reviewing the google doc above and commenting, or responding to this thread with any thoughts / questions / concerns?

**Comment by aaronschachter** [comment]
@mikefantini what sequence should this question appear? Before quantity?

**Comment by mikefantini** [comment]
@aaronschachter after quantity before why is this important to you... are you pushing this to production? does it need styling first or will it look alright?

**Comment by aaronschachter** [comment]
This won't be enabled on production until the node is configured to display it.  yes it will need styling because it looks like shit, see #1693.
