### ISSUE TITLE
campaign listings (staging) - ability to view listings based on changes to campaigns in staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1648]
When we make a change to a campaign on staging, we need to see how this will effect things like the finder results, how they are displayed, the order, etc.

There are certain changes we will want to make to campaigns in order to manipulate these results and we'll want to view these in staging first before making the changes in production.

**Comment by blisteringherb** [comment]
The solr server is set up in staging and this should be working now.
