### ISSUE TITLE
Production: Add New Relic support

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#165]
See #164 for details. Prod server provisioning must include New Relic agent installation  & config.

**Comment by mikefantini** [comment]
talked to @mshmsh5000 moving to 0.3 milestone.

**Comment by desmondmorris** [comment]
@mshmsh5000 - All servers except the db servers.  The agent is installed on both the master and the slave, but they are not being registered in new relic for some reason.  This could be naming collision maybe?

![screen-shot-2014-03-17-at-10 41 36-am](https://f.cloud.github.com/assets/129360/2437014/7cd1f55a-ade2-11e3-959e-ce19729d0514.jpg)

**Comment by mshmsh5000** [comment]
Fixed by customizing host names in `/etc/newrelic/nrsysmond.cfg`:

`# See response to our ticket: https://support.newrelic.com/requests/85424
hostname=db1-beta`
