### ISSUE TITLE
ds build must use env vars

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#1659]
**Currently breaking QA builds**

bin/ds build includes this line:

`# Create the db, if for some reason it's not there yet.
  mysql -uroot -e "CREATE DATABASE IF NOT EXISTS dosomething;"`

This is great for Vagrant boxes, but elsewhere needs to obey env vars that control DB connections.

**Comment by mshmsh5000** [comment]
I have rejiggered root MySQL access on blackangus so that this is no longer a blocker. But does need to be fixed.

**Comment by aaronschachter** [comment]
@blisteringherb -- Is this still an issue?
