### ISSUE TITLE
profile issue (staging) - Fatal error

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1662]
Seeing this error message on staging site when go to 
http://staging.beta.dosomething.org/campaigns/comeback-clothes

![image](https://cloud.githubusercontent.com/assets/6330971/2619554/5434dae2-bc31-11e3-8645-7b5ee5ee2574.png)

**Comment by mikefantini** [comment]
@angaither @weerd not sure which of you this should be on.

Also if it's only happening in staging I'm not so concerned about it. I don't see it in production, but if it would be happening in production in the future that'll dictate the priority.

**Comment by angaither** [comment]
@mikefantini are we still seeing this

**Comment by mikefantini** [comment]
Nope closing it out.
