### ISSUE TITLE
action page (action guides) -copy running over modal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1665]
copy is running over the modal of action guides. 

example: https://beta.dosomething.org/campaigns/i-want-you-quit-because  

https://trello-attachments.s3.amazonaws.com/52ea92c7ccdaf8415b8cab3a/533eb9e7334d9e9f53da6a2d/692x681/0ac9cad1aba7bd7b54130849f8125f67/Screen_Shot_2014-04-04_at_9.55.33_AM.png

**Comment by weerd** [comment]
Should the link be explicitly output showing the full link, or would it potentially be better if the maybe the initial text of the list item was created as a link, with the `href` defined as the link that is currently printed. Might not be feasible based on how the info is input; just a thought but I could look into it.

**Comment by mikefantini** [comment]
so like we talked about let's have the text wrap. also happening here with URLs (https://www.dosomething.org/campaigns/comeback-clothes when go to view the sources): 
![image](https://cloud.githubusercontent.com/assets/6330971/2634759/6975ab7c-be7d-11e3-921a-1c92fd4b8157.png)

**Comment by weerd** [comment]
@mikefantini the above screenshot is for content outside of the modal, so I'll do a different fix for the sources. Do you want to add a separate ticket?
