### ISSUE TITLE
Help tickets not going into ZenDesk for 6 days

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1674]
Looks like tickets from the campaign pages have stopped going into ZenDesk - starting April 1. 

Did a test with Comeback Clothes today - and when you submit the help form, you get an error message.

**Comment by aaronschachter** [comment]
This is occurring because the `bmathias@dosomething.org` username has been deactivated, and the Zendesk API on prod was configured to use this username.

**Comment by aaronschachter** [comment]
Changing to valid username `mlidey@dosomething.org` now works.  It may be worth changing the admin username to a more generic email to avoid this if we ever change it again.
