### ISSUE TITLE
[Finder] Pagination

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1679]
Add "view more campaigns" to bottom of finder results.

Crystal's user testing confirmed that our demo loves scrolling. 
![homepage - see more campaigns](https://cloud.githubusercontent.com/assets/6331017/2639003/0fb53452-bebb-11e3-9fc1-fd254387ca83.jpg)

**Comment by mikefantini** [comment]
closing this one since it's a duplicate of #1729
