### ISSUE TITLE
Finder filter respsonsive bug 

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1680]
Longer filters not stacking properly, including Bullying + Violemce, Discrimination, Homelessness + Poverty, Sex + Relationships, Less than 2 hours, and all of TYPE.
![finder responsive bug](https://cloud.githubusercontent.com/assets/6331017/2639068/0b161acc-bebd-11e3-8937-4e89321637e8.png)

**Comment by DFurnes** [comment]
:arrow_backward: :arrow_double_down: :arrow_down: :arrow_right: :arrow_left: :arrow_right_hook: 
Closed by #1684.
