### ISSUE TITLE
Remove gray box behind finder, add purple + gradient

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1681]
![homepage - purple header](https://cloud.githubusercontent.com/assets/6331017/2639163/a9070f46-bebf-11e3-8b28-ffef39c86661.jpg)
![remove this gray box behind filter](https://cloud.githubusercontent.com/assets/6331017/2639168/b59dbbc4-bebf-11e3-825f-4e8376ba7522.png)

**Comment by DFurnes** [comment]
Closed by #1684.
