### ISSUE TITLE
Add additional line of four campaign boxes on the homepage

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1682]
Add row of campaigns, so there are 9 campaigns total on the homepage (1 big box and 8 little ones)

![homepage - add addl row of 4 campaigns](https://cloud.githubusercontent.com/assets/6331017/2639216/313360f8-bec1-11e3-9ef2-4013c32808e2.jpg)

**Comment by DFurnes** [comment]
Fixed by #1708.
