### ISSUE TITLE
Make filters single select on Finder

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1689]
@blisteringherb @mikefantini let's head in this direction, like we discussed today.

**Comment by DFurnes** [comment]
Re-labeling this as a front-end issue.

**Comment by joolaay** [comment]
Yes, but @blisteringherb has to make some adjustments as well...

**Comment by joolaay** [comment]
@DFurnes let's hold off on this for a bit - we just stepped through the code w Chris and Morgan and  may take a different approach. Apologies - we'll get more clarity soon.

**Comment by DFurnes** [comment]
After further discussion in morning check-in, we ended up making these single-select for now. Closing.
