### ISSUE TITLE
Production: Remove temp tables

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1692]
All scripts have finished running, it's safe to remove any table prefixed with and underscore matching `_XXXX_old_world`

**Comment by angaither** [comment]
Removed :fire::fire:

**Comment by desmondmorris** [comment]
![char char](http://img2.wikia.nocookie.net/__cb20131213083222/pokemon/images/1/10/006Charizard_OS_anime.png)

**Comment by angaither** [comment]
:+1:
