### ISSUE TITLE
Finder: Multiple Select Issue

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#1695]
When selecting multiple causes, the causes aren't aggregated properly in the query.

**Comment by barryclark** [comment]
I think it's worth holding off on this for now. Multiple select isn't going to be needed for our first launch version so this isn't a priority. Right @julielorch?

**Comment by barryclark** [comment]
Just noticed it's already fixed, nevermind. We'll be syncing on this stuff tomorrow morning.
