### ISSUE TITLE
[Global] Styling for default pages within the site.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#1706]
They be brokenz.

Need to address styling for all pages throughout the site that don't have a specific template and Drupal defaults to chucking the content into the $content vars in the page.tpl.php.

**Comment by mikefantini** [comment]
please update https://trello.com/c/YlZx7V9V once this is fixed

**Comment by DFurnes** [comment]
A (hopefully accurate) summary of an offline conversation with @weerd and @angaither a while back:

We're gonna try to fix this by making the default `page.tpl.php` basically reflect the Static Content layout, and then have a `page-override.tpl.php` (or something) which we can choose to use instead on nodes that need more extensive control over the design of the site.

:fallen_leaf:
