### ISSUE TITLE
[Finder] Server-side blank slate

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1711]
We need to generate a "blank slate" for the initial homepage tiles and layout on the server. This will keep the page crawlable for search engines.

**Comment by DFurnes** [comment]
Partially fixed by #1708 (hard-coded in home template, definitely not a permanent solution).

**Comment by aaronschachter** [comment]
@DFurnes Is this still valid?  This should be resolved by the Home node's `field_campaigns`, no?

**Comment by DFurnes** [comment]
Yup, been fixed for a long time. Closing!
