### ISSUE TITLE
Campaign Finder - Filter items in Cause not being deactivated correctly 

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1723]
When you select a filter in Time or Type it doesn't deactivate links with no results in the filters in Cause. 

Selecting "Donate Something" as shown below should deactivate some of the filters in Cause and Time. 

![image](https://cloud.githubusercontent.com/assets/692762/2657297/e7c8062c-bffa-11e3-94b1-3ed3f19d4861.png)

**Comment by blisteringherb** [comment]
@DFurnes Did some reorganizing of the code and merged my PR that fixed this issue in resolved #1744, so I'm going to close this.
