### ISSUE TITLE
Campaign Finder - Selecting a Type filter clears inactive filters in Type

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1727]
To replicate: Select Homelessness + Poverty from Cause, then select Host An Event from Type. It now clears all of the inactive filter items from the Type... the desired result is that they should stay inactive.

![image](https://cloud.githubusercontent.com/assets/692762/2657637/114bf6ee-bfff-11e3-867b-ea488af77dfd.png)

![image](https://cloud.githubusercontent.com/assets/692762/2657607/b6ae921e-bffe-11e3-8e59-1095bb835620.png)

**Comment by mikefantini** [comment]
also happening with time category as well: http://screencast.com/t/aY3QXMs84Y3y

**Comment by mikefantini** [comment]
@blisteringherb has this been fixed and pushed to staging?

**Comment by mikefantini** [comment]
nope I'm wrong, this is still an open issue

**Comment by mikefantini** [comment]
trello card here: https://trello.com/c/xSjUYzq1

**Comment by mikefantini** [comment]
this then results in previous selections being de-selected: http://screencast.com/t/IF3UGSjRvn

but again, we just need to solve the root issue and then hopefully this bug will never re-appear

**Comment by DFurnes** [comment]
Fixed.
