### ISSUE TITLE
Campaign Finder - Update Time filters

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1728]
Up to 1 hour, 
2–5 hours, 
5 hours +

**Comment by mikefantini** [comment]
@julielorch shouldn't this be:
- Up to 1 hour
- 2-5 hours
- 10 hours

?

**Comment by joolaay** [comment]
I'd like more internal feedback on this category next week before launch.. For now we need it to be a bit more parallel, so close to Fantini's suggestion but we have to get the number out in front:

1 hour or less
2-5 hours
10 hours

**Comment by DFurnes** [comment]
Saw this paging through notifications from when I was out, but didn't get a chance to reply until now. Doesn't the third option have to be "5+", or else we're ignoring the 5-10 range? I'm a bit confused where that gap is represented in the wording you guys are suggesting.

**Comment by DFurnes** [comment]
Also let's open a new issue if this is still something that needs consideration.
