### ISSUE TITLE
Campaign Finder - Empty state

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1730]

**Comment by mikefantini** [comment]
@julielorch please provide copy you want

**Comment by joolaay** [comment]
"Oh snap! We'll work on that. Want to try another combo?"

Or similarly cheesy - thoughts?

**Comment by weerd** [comment]
Aimed to do something simple, that fits in with the design:

Mobile:
![screen shot 2014-04-16 at 3 39 03 pm](https://cloud.githubusercontent.com/assets/105849/2724261/039e52b2-c59f-11e3-8ec7-ce51723467e7.png)

Tablet/Desktop:
![screen shot 2014-04-16 at 3 39 17 pm](https://cloud.githubusercontent.com/assets/105849/2724266/0ae95990-c59f-11e3-9ac4-55a2bb63cac0.png)

**Comment by weerd** [comment]
Font size for the main message ("Oh snap...") is smaller on mobile, and increases on tablet/desktop.

Hopefully this is cool and very unlikely someone will see it! :boom:

@barryclark @julielorch @mikefantini

**Comment by barryclark** [comment]
@weerd Oops, misclick. Looks good!
