### ISSUE TITLE
Campaign Finder - Network connectivity error state

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1731]
For when the user isn't online, solr search is down, etc.

**Comment by mikefantini** [comment]
@julielorch please add copy you want for this state

**Comment by joolaay** [comment]
"Ooof! We're not sure what's up? Maybe it's us, or it could be your internet connection. Want to try again in a few minutes?"

--or even zanier?

**Comment by weerd** [comment]
@julielorch @mikefantini @barryclark 

Does this location work with you all, in regards of where to add the message. If there's an error w/ Solr or getting the query results via Ajax, I'd rather not hide the campaigns visible, so the user can still click on stuff. Figured the location above the campaigns, but below the filters was ideal:

![network error message](https://cloud.githubusercontent.com/assets/105849/2709527/0d56d68c-c4b7-11e3-89e9-7c75e348d5fe.png)

*styled better and w/ a bit more room around the message, but ya get the idea ;)

**Comment by weerd** [comment]
This is the final result ;) Lemme know if you want any changes.

![screen shot 2014-04-15 at 12 54 04 pm](https://cloud.githubusercontent.com/assets/105849/2710228/ddc7386e-c4be-11e3-86ae-38276b2e537f.png)

**Comment by weerd** [comment]
Change of plans. Chatted with @DFurnes and he suggested making use of the pattern library error messages, which makes sense. Here's the new look.

![screen shot 2014-04-15 at 6 30 24 pm](https://cloud.githubusercontent.com/assets/105849/2713865/b5a0ca56-c4ed-11e3-9d51-59fdf73839a5.png)

**Comment by weerd** [comment]
@DFurnes is going to address adding in the close button. Right now it's not something that gets added w/ Ajax-y data... but he's planning on changing that in Neue.

**Comment by joolaay** [comment]
Hey - I totally missed this. @Dfurnes awesome call.

On Wed, Apr 16, 2014 at 11:37 AM, Diego Lorenzo notifications@github.comwrote:

> Closed #1731 https://github.com/DoSomething/dosomething/issues/1731 via
> #1805 https://github.com/DoSomething/dosomething/pull/1805.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/1731
> .

## 

Julie Lorch
