### ISSUE TITLE
Campaign Finder - Mobile gallery view front-end pass

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1732]
In mobile view:
- [ ] ~~Get rid of descriptions~~
- [x] Reduce size of staff pic icon
- [x] Single column on mobile, two column on tablet
- [x] Remove underline on 'today' in headline
- [x] Adjust spacing and line height around filter title and subtitle

**Comment by mikefantini** [comment]
@barryclark @julielorch i believe we are keeping the two column campaign view on tablet though correct?

**Comment by joolaay** [comment]
@mikefantini this is what we discussed, yes. Preference to include CTA.

**Comment by mikefantini** [comment]
great! just want to make sure that's documented as well.

**Comment by weerd** [comment]
Chatted with @crystalruthbell and since we're doing a single column for the campaign squares on mobile the descriptions have been added back in.

**Comment by weerd** [comment]
I've added some of the items Crystal requested to update into the checklist above ;)
