### ISSUE TITLE
Campaign Finder - Mobile filters front-end pass

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1733]
Mobile view should include:
- [x] Single column list for filters
- [x] Bigger click targets on filters
- [x] Filters in separate boxes (see screenshot below)

https://s3.amazonaws.com/uploads.hipchat.com/34218/297405/qe9QeMFYLQmqSti/mobile%20-%20boxes.JPG

**Comment by mikefantini** [comment]
trello card here: https://trello.com/c/t5ZdNgTe

**Comment by weerd** [comment]
These are all set, but I'm going to run the visual changes by @crystalruthbell before I do the PR. She has some additional quick modifications, and I'll add them to this issue.
