### ISSUE TITLE
Dosomething Web Tests failing

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1746]
Occurring for both the Signup and Reportback web tests.

Complains about not able to find the `field_config` table.

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=1700045&op=do StatusText: OK ResponseText: Additional uncaught exception thrown while handling exception.OriginalPDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;dosomething.simpletest485992field_config&#039; doesn&#039;t exist: SELECT fc.\* FROM {field_config} fc WHERE (fc.module = :db_condition_placeholder_0) AND (fc.active = :db_condition_placeholder_1) AND (fc.storage_active = :db_condition_placeholder_2) ; Array ( [:db_condition_placeholder_0] =&gt; taxonomy [:db_condition_placeholder_1] =&gt; 1 [:db_condition_placeholder_2] =&gt; 1 ) in field_read_fields() (line 372 of /vagrant/html/modules/field/field.crud.inc).AdditionalPDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;dosomething.simpletest485992watchdog&#039; doesn&#039;t exist: INSERT INTO {watchdog} (uid, type, message, variables, severity, link, location, referer, hostname, timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array ( [:db_insert_placeholder_0] =&gt; 5 [:db_insert_placeholder_1] =&gt; php [:db_insert_placeholder_2] =&gt; %type: !message in %function (line %line of %file). [:db_insert_placeholder_3] =&gt; a:6:{s:5:&quot;%type&quot;;s:12:&quot;PDOException&quot;;s:8:&quot;!message&quot;;s:461:&quot;SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.simpletest485992field_config&amp;#039; doesn&amp;#039;t exist: SELECT fc.\* FROM {field_config} fc WHERE (fc.module = :db_condition_placeholder_0) AND (fc.active = :db_condition_placeholder_1) AND (fc.storage_active = :db_condition_placeholder_2) ; Array ( [:db_condition_placeholder_0] =&amp;gt; taxonomy [:db_condition_placeholder_1] =&amp;gt; 1 [:db_condition_placeholder_2] =&amp;gt; 1 ) &quot;;s:9:&quot;%function&quot;;s:19:&quot;field_read_fields()&quot;;s:5:&quot;%file&quot;;s:42:&quot;/vagrant/html/modules/field/field.crud.inc&quot;;s:5:&quot;%line&quot;;i:372;s:14:&quot;severity_level&quot;;i:3;} [:db_insert_placeholder_4] =&gt; 3 [:db_insert_placeholder_5] =&gt; [:db_insert_placeholder_6] =&gt; http://dev.dosomething.org:8888/batch?id=1700045&amp;op=do [:db_insert_placeholder_7] =&gt; http://dev.dosomething.org:8888/batch?op=start&amp;id=1700045 [:db_insert_placeholder_8] =&gt; 10.0.2.2 [:db_insert_placeholder_9] =&gt; 1397078135 ) in dblog_watchdog() (line 160 of /vagrant/html/modules/dblog/dblog.module).Uncaught exception thrown in session handler.PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;uid&#039; cannot be null: INSERT INTO {sessions} (sid, ssid, uid, cache, hostname, session, timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] =&gt; Kl7BhPuISca9Z_9R6N9iPC0KthAMn1VCnNUXSKyQDbI [:db_insert_placeholder_1] =&gt; [:db_insert_placeholder_2] =&gt; [:db_insert_placeholder_3] =&gt; 0 [:db_insert_placeholder_4] =&gt; 10.0.2.2 [:db_insert_placeholder_5] =&gt; node_overview_filter|a:1:{i:0;a:2:{i:0;s:4:&quot;type&quot;;i:1;s:8:&quot;campaign&quot;;}}batches|a:1:{i:1700045;b:1;} [:db_insert_placeholder_6] =&gt; 1397078075 ) in _drupal_session_write() (line 209 of /vagrant/html/includes/session.inc).

Seems related http://drupal.stackexchange.com/questions/66708/simpletest-fails-to-create-the-field-config-table

**Comment by aaronschachter** [comment]
Seems like the introduction of caching has caused this https://drupal.org/node/1645356.  still investigating.

**Comment by aaronschachter** [comment]
Tried turning off redis and varnish in my database locally, and also by commenting out from the dosomething.info as well.  Still no luck.

![screen shot 2014-04-10 at 4 52 12 pm](https://cloud.githubusercontent.com/assets/1236811/2673337/0e52d1d0-c0f2-11e3-9bfa-13ef0095c149.png)

An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=1700065&op=do StatusText: Service unavailable (with message) ResponseText: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dosomething.simpletest327292field_config' doesn't exist: SELECT fc.\* FROM {field_config} fc WHERE (fc.module = :db_condition_placeholder_0) AND (fc.active = :db_condition_placeholder_1) AND (fc.storage_active = :db_condition_placeholder_2) ; Array ( [:db_condition_placeholder_0] => taxonomy [:db_condition_placeholder_1] => 1 [:db_condition_placeholder_2] => 1 ) in field_read_fields() (line 372 of /vagrant/html/modules/field/field.crud.inc).Uncaught exception thrown in session handler.PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;uid&#039; cannot be null: INSERT INTO {sessions} (sid, ssid, uid, cache, hostname, session, timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] =&gt; Kl7BhPuISca9Z_9R6N9iPC0KthAMn1VCnNUXSKyQDbI [:db_insert_placeholder_1] =&gt; [:db_insert_placeholder_2] =&gt; [:db_insert_placeholder_3] =&gt; 0 [:db_insert_placeholder_4] =&gt; 10.0.2.2 [:db_insert_placeholder_5] =&gt; node_overview_filter|a:1:{i:0;a:2:{i:0;s:4:&quot;type&quot;;i:1;s:8:&quot;campaign&quot;;}}batches|a:16:{i:1700045;b:1;i:1700046;b:1;i:1700047;b:1;i:1700053;b:1;i:1700054;b:1;i:1700055;b:1;i:1700056;b:1;i:1700057;b:1;i:1700058;b:1;i:1700059;b:1;i:1700060;b:1;i:1700061;b:1;i:1700062;b:1;i:1700063;b:1;i:1700064;b:1;i:1700065;b:1;} [:db_insert_placeholder_6] =&gt; 1397162771 ) in _drupal_session_write() (line 209 of /vagrant/html/includes/session.inc).

**Comment by aaronschachter** [comment]
Commented out all of the caching section in settings.php.  Ran for longer, and now got this old familiar error:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=1700067&op=do StatusText: OK ResponseText: Fatal error: Maximum execution time of 30 seconds exceeded in /vagrant/html/includes/registry.inc on line 0

Upped the execution_time to 90 in php.ini and now this weird guy. I'm beginning to think we may want to consider removing non-essential modules from dosomething.info (e.g. see messages below from Optimizely and Metatags)

An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=1700068&op=do StatusText: Service unavailable (with message) ResponseText: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dosomething.simpletest926552menu_custom' doesn't exist: SELECT \* FROM {menu_custom}; Array ( ) in menu_load_all() (line 237 of /vagrant/html/modules/menu/menu.module).Uncaught exception thrown in session handler.PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;uid&#039; cannot be null: INSERT INTO {sessions} (sid, ssid, uid, cache, hostname, session, timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] =&gt; Kl7BhPuISca9Z_9R6N9iPC0KthAMn1VCnNUXSKyQDbI [:db_insert_placeholder_1] =&gt; [:db_insert_placeholder_2] =&gt; [:db_insert_placeholder_3] =&gt; 0 [:db_insert_placeholder_4] =&gt; 10.0.2.2 [:db_insert_placeholder_5] =&gt; node_overview_filter|a:1:{i:0;a:2:{i:0;s:4:&quot;type&quot;;i:1;s:8:&quot;campaign&quot;;}}batches|a:19:{i:1700045;b:1;i:1700046;b:1;i:1700047;b:1;i:1700053;b:1;i:1700054;b:1;i:1700055;b:1;i:1700056;b:1;i:1700057;b:1;i:1700058;b:1;i:1700059;b:1;i:1700060;b:1;i:1700061;b:1;i:1700062;b:1;i:1700063;b:1;i:1700064;b:1;i:1700065;b:1;i:1700066;b:1;i:1700067;b:1;i:1700068;b:1;}messages|a:1:{s:6:&quot;status&quot;;a:5:{i:0;s:128:&quot;Additional image style actions should now be available in the presets &lt;a href=&quot;/?q=admin/config/media/image-styles&quot;&gt;settings&lt;/a&gt;&quot;;i:1;s:280:&quot;Thank you for installing the Metatag module. It is recommended to read the module&#039;s &lt;a href=&quot;/?q=profiles/dosomething/modules/contrib/metatag/README.txt&quot; title=&quot;Read the Metatag module&#039;s documentation&quot;&gt;README.txt&lt;/a&gt; file as there are some known issues that may afffect this site.&quot;;i:2;s:43:&quot;Optimizely database table has been created.&quot;;i:3;s:331:&quot;A default project / experiment entry has been created. Next, enter your &lt;a href=&quot;/?q=/admin/config/system/optimizely/settings&quot;&gt;Optimizely account ID&lt;/a&gt;. There&#039;s also an &lt;a href=&quot;/?q=/admin/people/permissions/module-optimizely&quot;&gt;optimizely permission&lt;/a&gt; that can be set for specific roles to access the adminstration functionality.&quot;;i:4;s:169:&quot;The Optimizely account ID has not been set, please added it to complete the default setup at &lt;a href=&quot;/?q=/admin/config/system/optimizely/settings&quot;&gt;Account Settings&lt;/a&gt;.&quot;;}} [:db_insert_placeholder_6] =&gt; 1397164247 ) in _drupal_session_write() (line 209 of /vagrant/html/includes/session.inc).

**Comment by aaronschachter** [comment]
Hey @desmondmorris -- pinging you on this guy per our discussion this morning.  haven't attempted command line tests yet, was just running through the UI.  (which also completely dies on stage)

**Comment by aaronschachter** [comment]
Different error when attempting to run through command line:

```
vagrant@dev:/vagrant/html$ drush test-run --verbose DoSomething
Initialized Drupal 7.26 root directory at /vagrant/html                 [notice]
Initialized Drupal site default at sites/default                        [notice]
Loading outputformat engine.                                            [notice]
PHP Fatal error:  Class 'CommentHelperCase' not found in /vagrant/html/profiles/dosomething/modules/contrib/entity/entity.test on line 541
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'CommentHelperCase' not found in
/vagrant/html/profiles/dosomething/modules/contrib/entity/entity.test,
line 541
```

**Comment by desmondmorris** [comment]
Try running just a single test group rather than the whole DS suite.  Lets
try and narrow it down more

**Comment by aaronschachter** [comment]
Same error about CommentHelperCase when running `drush test-run DoSomethingSignupWebTestCase --verbose`.

Going to test if upgrading to Entity 1.3 makes a difference (#956)

**Comment by desmondmorris** [comment]
Cool.  Try turning on Comment module too for shits and giggles

**Comment by aaronschachter** [comment]
Turning on comment and you get the same initial error. Although the --verbose gives a little more information with the user module undefined indexes:

```
Initialized Drupal 7.26 root directory at /vagrant/html                                                                                         [notice]
Initialized Drupal site default at sites/default                                                                                                [notice]
Undefined index: 1258186 user.module:3640                                                                                                       [notice]
Trying to get property of non-object user.module:3640                                                                                           [notice]
Undefined index: 1258186 user.module:3641                                                                                                       [notice]
Trying to get property of non-object user.module:3641                                                                                           [notice]
Undefined index: 1258186 user.module:3642                                                                                                       [notice]
Trying to get property of non-object user.module:3642                                                                                           [notice]
Loading outputformat engine.                                                                                                                  [notice]
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.simpletest620330field_config&amp;#039; doesn&amp;#039;t exist: SELECT fc.*
FROM 
{field_config} fc
WHERE  (fc.module = :db_condition_placeholder_0) AND (fc.active = :db_condition_placeholder_1) AND (fc.storage_active = :db_condition_placeholder_2) ; Array
(
    [:db_condition_placeholder_0] =&amp;gt; taxonomy
    [:db_condition_placeholder_1] =&amp;gt; 1
    [:db_condition_placeholder_2] =&amp;gt; 1
)
 in field_read_fields() (line 372 of /vagrant/html/modules/field/field.crud.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.simpletest620330watchdog&amp;#039; doesn&amp;#039;t exist: INSERT INTO {watchdog} (uid, type, message, variables, severity, link, location, referer, hostname, timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array
(

```

**Comment by aaronschachter** [comment]
This issue still lives.  This d.o. issue seems to give a clue https://www.drupal.org/node/1011314#comment-8187693

**Comment by aaronschachter** [comment]
Actually, this thread suggests caching: http://drupal.stackexchange.com/questions/66708/simpletest-fails-to-create-the-field-config-table

**Comment by sergiitk** [comment]
I also faced this issue. The only way to make simpletests work is to comment line `$conf['cache_default_class'] = 'Redis_Cache';` of the settings file. I successfully ran DoSomething User tests with it.

Unfortunately, there's no way to fix it. It's due to Drupal design, see Redis [`README.testing.txt`](/omega8cc/redis/blob/7.x-2.x/README.testing.txt):

> Unit tests won't cover the cache backend until the 8.x series.
> 
> This won't be fixed, by design. Drupal 8.x now ships a complete cache backend
> unit tests suite which will be used when this module will be upgraded.

We can only find a workaround to omit redis caching on tests. I tried to find anything specific to such requests, but with no luck.

**Comment by aaronschachter** [comment]
Curious if we remove `redis` from `dosomething.info` if this could fix tests.  Will test once my `vagrant up` finishes.

**Comment by sergiitk** [comment]
I think, you'll still have to to remove redis backends settings from `settings.php`.

**Comment by aaronschachter** [comment]
:(

**Comment by aaronschachter** [comment]
Confirmed that simply removing the `redis` module from the .info file in https://github.com/DoSomething/dosomething/issues/1746#issuecomment-56828729 does not work.  Looks like we are kinda screwed with simple tests for a while, as long as we're using Redis... :frowning:

**Comment by aaronschachter** [comment]
.. unless maybe these caching variables were set via `ds build` and not in settings.php..
