### ISSUE TITLE
Fatal error: Call to a member function publishMessage()

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#1749]
As reported by @angaither 

> seeing this locally on new user registration
> 
> ```
> Fatal error: Call to a member function publishMessage() on a non-object in /vagrant/html/profiles/dosomething/modules/contrib/message_broker_producer/message_broker_producer.module on line 231
> ```

**Comment by aaronschachter** [comment]
I haven't been seeing this, and I haven't seen it on staging either.  Is this just a result of the local setups not being up to date with the latest `message_broker_producer` code?

**Comment by aaronschachter** [comment]
@DeeZone is this still an open issue?

**Comment by deezone** [comment]
This has been resolved. I keep forgetting the connection between the dosomething repo issues and the message_broker_producer repo.
