### ISSUE TITLE
Add custom report back field to Comeback Clothes SMS report back submission

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#1751]
see: #1647

**Comment by aaronschachter** [comment]
For Comeback Clothes, the extra field should be passed into the `$values` array as:
`'dropoff_hm' => 1`, where 1 is Yes and 0 is No.

If you wanted to dynamically grab the question label, you could query `dosomething_reportback_field` for nid = 362 and name = 'dropoff_hm' and use the label column.  Or... just hardcode it.
