### ISSUE TITLE
Update Zendesk tests

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1756]
Tests must be updated with changes made in `dosomething_zendesk_get_ticket_array`.

![screen shot 2014-04-10 at 1 47 38 pm](https://cloud.githubusercontent.com/assets/1236811/2671242/62622164-c0d8-11e3-9118-fe853d520a4d.png)

**Comment by angaither** [comment]
as tests aren't running, these test def aren't :new_moon_with_face:
