### ISSUE TITLE
campaign finder - filter disabling behaving incorrectly

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1760]
Goal: prevent the user from choosing a combination of filters that would provide 0 results

The ideal situation for the finder interactions:
- cause is limited by selections that are made to time and type (but disregards selections that are made to cause)
- time is limited by selections that are made to type and cause (but disregards selections made to time)
- type is limited by selections that are made by cause and time (but disregards selections made to type)
- the results are limited by selections that are made to cause, time, and type

For example, if I select 5+ hours, then Animals, I should be able to change my mind on Time and select 2-5 hours (because the combination of Animals + no preference of Type should allow me to select 2-5 hours and get results). As you can see, currently I can't do that: http://screencast.com/t/lKdUH7Lj3P

The reason (I suspect) that I can't change my mind on Time is because Solr is saying that there is no combination that has Animals + 5+ hours + 2-5 hours, however, it _should not_ be factoring the 5+ hours into it's calculation.

This appears to be happening across the board. In this example I should be able to change my mind to Share Something from Donate Something but I can't. The only Type I can change is to Improve a Space because Party Animal happens to be tagged with both Donate Something _and_ Improve a Space, so it seems that Solr is factoring in choices made within a particular category as limiting factors for which choices should be available: http://screencast.com/t/WqMd4301GCHc

Again, since the goal of the graying out is to prevent me from making combinations that will return 0 results, I _should_ be able to select Animals _and_ Share Something.

Hopefully one of these drawings help clarify as well:

![image](https://cloud.githubusercontent.com/assets/6330971/2674243/e3540394-c0fd-11e3-93b0-357ae3ae52fe.png)

![photo 42](https://cloud.githubusercontent.com/assets/6330971/2674299/1a973bae-c0ff-11e3-9a79-ed74ac38831b.JPG)

cc: @mshmsh5000 @julielorch @weerd

**Comment by weerd** [comment]
I need to connect with @blisteringherb and confirm this is a bender issue and not a fender issue since the query that is sent to Solr is built in JS... we can chat further during standup :)

**Comment by blisteringherb** [comment]
Chatted w/ @weerd on the best way to fix this.  We'll need to keep track of both the first clicked and the last selected and then clear those once everything has been deselected.  Working on doing this now.

**Comment by DFurnes** [comment]
Per discussion this morning, side-stepped this issue by disabling all other fields in a field group when one is selected (requiring you to deselect then re-select, which updates facets from Solr).
