### ISSUE TITLE
Campaign Finder - when I change a selection, grayed out options don't reset

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1764]
If I do the following combination:
- \+ Environment
- \+ Improve a Space
- \- Environment
- \- Improve a Space

I am now unable select Face to Face, even though there is _nothing else selected_. Clearly there is something in the database that is tagged with Face to Face, so I should be able to select it.

Video here: http://screencast.com/t/bM6bUKaRiZ0

Not sure if this is related to other solr issues or not so wanted to make sure it was documented separately.

**Comment by mikefantini** [comment]
Easier combination: Select Education. 5+ hours then becomes inactive. Then de-select Education, and 5+ hours remains inactive. Even though, again I should be able to select 5+ hours since there are campaigns that have 5+ hours in the database.

**Comment by DFurnes** [comment]
This should be fixed now.
