### ISSUE TITLE
Darken footer text color

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1769]
Please adjust both the footer nav and subnav to a darker gray values consistent with use elsewhere. The colors should be consistent between mobile and desktop. 

Here is a mock for reference, but feel free to diverge a bit, this is flexible...

![footer](https://cloud.githubusercontent.com/assets/6550604/2697142/97479836-c3ea-11e3-8f76-c386e66a67bf.jpg)

**Comment by DFurnes** [comment]
Fixed this up in DoSomething/neue#315.
