### ISSUE TITLE
Move down campaign name and tagline on mobile action page

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1770]
Need to build in some logic to rework line spacing on positioning on mobile. Here are some more comments about the specific designs:

![screen shot 2014-04-14 at 11 43 33 am](https://cloud.githubusercontent.com/assets/6550604/2697215/ac2389a8-c3eb-11e3-98e2-3905620aa8e9.png)
- need to tighten up line spacing between different elements so everything fits closer to bottom of the image.

![screen shot 2014-04-14 at 11 41 38 am](https://cloud.githubusercontent.com/assets/6550604/2697216/ac23c6e8-c3eb-11e3-82a6-63a5e3e28fad.png)
- need to tighten up line spacing between different elements so everything fits closer to bottom of the image but also need to have everything moved down on mobile if there is not sponsor or scholarship info.

**Comment by weerd** [comment]
Working on a fix for this today :)

**Comment by crystalruthbell** [comment]
Holler at me when you've got something to eyeball @weerd

**Comment by DFurnes** [comment]
This has been fixed!
