### ISSUE TITLE
Remove "nipple" from tips that only have one listed

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1771]
Nancy's descriptive word choice, not mine. 

When there is only one tip lets not have the selection arrow show up. 

Here is an example:
https://www.dosomething.org/campaigns/petition-plates
![screen shot 2014-04-14 at 12 00 25 pm](https://cloud.githubusercontent.com/assets/6550604/2697424/13827a12-c3ee-11e3-9348-c3d47653918c.png)

**Comment by angaither** [comment]
NSFW.

**Comment by DFurnes** [comment]
Does it make sense to create a special case here? A tabbed container with only one tab is still a tabbed container.
