### ISSUE TITLE
Campaign Finder - when I make a selection within a category, all other options should be unselectable

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1777]
For instance, if in cause I select Animals, all other causes should be unselectable.

We should also add some sort of x in a circle so it's clear to the user that they can remove their selection (need to make sure this treatment doesn't get too chunky on mobile).

cc: @julielorch @crystalruthbell @barryclark

**Comment by DFurnes** [comment]
Fixed. Let's revisit the styling at standup tomorrow morning.
