### ISSUE TITLE
Campaign Finder (mobile) - Remove type and time from mobile

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1779]
Sort only by cause on mobile - we need more time to a) work out the UI to avoid null set and to b) have more campaigns in the database. cc @barryclark @mikefantini

**Comment by DFurnes** [comment]
CHANGE EVERYTHING. :godmode:

**Comment by joolaay** [comment]
NOW NOW NOW

**Comment by mikefantini** [comment]
@julielorch since we will only have cause, what do you think about getting rid of the button and just filtering once the user makes a choice on cause?

**Comment by barryclark** [comment]
@mikefantini oh hell yes :dancer:

**Comment by barryclark** [comment]
We decided to go a different route with this. See #1799
