### ISSUE TITLE
Search bar standardization

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1784]
_Looking forward to frontend/design brainstorm before we move forward, here are notes to get us started_
- [ ] Make the design of the search field comparable to desktop, outline only, with search icon

![screen shot 2014-04-14 at 5 19 20 pm](https://cloud.githubusercontent.com/assets/6550604/2701390/67070f9a-c420-11e3-813b-9623dd5530f0.png)
![screen shot 2014-04-14 at 5 19 06 pm](https://cloud.githubusercontent.com/assets/6550604/2701391/67077200-c420-11e3-9fd1-3187eff302fb.png)
![screen shot 2014-04-14 at 5 20 35 pm](https://cloud.githubusercontent.com/assets/6550604/2701392/6707890c-c420-11e3-8566-46057cd17849.png)

**Comment by DFurnes** [comment]
Will be updated in the next Neue release alongside some other code cleanup.
