### ISSUE TITLE
Bullet points turn to squares

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1786]
Please update all CSS for bullet points to show square, standard color, comparable (maybe larger) size. 

It might be cleaner to left align bullet points flush to text, let's mock and discuss!

![screen shot 2014-04-14 at 6 27 39 pm](https://cloud.githubusercontent.com/assets/6550604/2701614/2351130a-c424-11e3-91b9-ae267306f253.png)
![screen shot 2014-04-14 at 6 27 13 pm](https://cloud.githubusercontent.com/assets/6550604/2701615/2351973a-c424-11e3-90da-288ce57a6638.png)

**Comment by weerd** [comment]
http://staging.beta.dosomething.org/about/youth-advisory-council

@crystalruthbell Something like this? I did this in browser so it's not saved anywhere... just a mock for reference :)

![screen shot 2014-04-30 at 4 19 31 pm](https://cloud.githubusercontent.com/assets/105849/2846648/ff4c8e0c-d0a4-11e3-92cd-ccf987ab4695.png)

**Comment by barryclark** [comment]
@crystalruthbell ^^

**Comment by crystalruthbell** [comment]
@weerd, I like it! what do you think?

**Comment by weerd** [comment]
I like it too :) I'll make the change globally. So it'll happen to all lists as you mentioned in the initial description and then check and see if it looks funky anywhere; but I think it should work ;)

**Comment by weerd** [comment]
So once the new version of Neue is pushed up this should be updated! Here's the Neue fix for reference https://github.com/DoSomething/neue/pull/319 :tropical_drink:
