### ISSUE TITLE
Static content pages gallery text line spacing 

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1787]
Please tighten up the line spacing on static content gallery text. 

![screen shot 2014-04-14 at 6 30 54 pm](https://cloud.githubusercontent.com/assets/6550604/2701652/bd9d61d4-c424-11e3-97cd-26a2907510e1.png)

**Comment by DFurnes** [comment]
This has been fixed! :hammer:
