### ISSUE TITLE
Button padding

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1789]
- [ ] Buttons should never have extra padding anywhere on the site. The button can switch to center alignment on mobile but should remain the same "medium size."

![screen shot 2014-04-14 at 6 42 14 pm](https://cloud.githubusercontent.com/assets/6550604/2701761/50c559ca-c426-11e3-9a78-2cb4968487d6.png)
![screen shot 2014-04-14 at 6 44 31 pm](https://cloud.githubusercontent.com/assets/6550604/2701767/6781af1a-c426-11e3-8046-ab069cdd2c47.png)

**Comment by tjrosario** [comment]
This is resolved
