### ISSUE TITLE
Action page prove it section contact us should have sec link treatment

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1791]
Lets give the Contact Us link a variation of secondary link treatment by giving it standard underline, not just on rollover. 

![screen shot 2014-04-14 at 6 54 58 pm](https://cloud.githubusercontent.com/assets/6550604/2701856/11d03198-c428-11e3-87cd-759153ee30b7.png)

It can stay white font color.

**Comment by weerd** [comment]
I'm going to add the underline to the sponsor link in this info-bar footer as well. Since the contact us will have a link, makes sense for the sponsor to have it as well, otherwise there's an inconsistency in link treatment in the info bar.

**Comment by weerd** [comment]
There's a PR in Neue which once merged will update this :)

**Comment by weerd** [comment]
Should be updated once Neue is updated on stage.
