### ISSUE TITLE
Campaign Finder - Mind On My Money shows up twice in results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1792]
Can replicate just by going to staging.beta.dosomething.org. However, once I start to filter, there is only one result for Mind On My Money.

Filters are:
- Education
- One hour or less
- Host an event

I checked the content on staging and there is only one campaign for Mind On My Money.

![image](https://cloud.githubusercontent.com/assets/6330971/2702668/3a7bdf9a-c43a-11e3-9eaf-203c5b23626d.png)

**Comment by barryclark** [comment]
This is blocked on @julielorch and @mikefantini speaking with Dave Deluca about how the top block is selected.

**Comment by mikefantini** [comment]
@DFurnes needs to look like this: 
![image](https://cloud.githubusercontent.com/assets/6330971/2722708/69b81b96-c58b-11e3-853b-ea21f8612f1d.png)

Let's make sure we get this order right before we flip. Since it's required for flip I'm making this a high priority.

**Comment by DFurnes** [comment]
Fixed by #1830.
