### ISSUE TITLE
Campaign Finder (mobile) - cause should be single select

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1793]
On mobile I'm able to select multiple causes. 

The behavior should be the same as on desktop: I select one cause and all other choices become unselectable and grayed out.

Tablet seems to be working fine.

![photo 2](https://cloud.githubusercontent.com/assets/6330971/2702759/bc69aa26-c43c-11e3-8797-d881908b544f.PNG)

**Comment by DFurnes** [comment]
GOT IT.
