### ISSUE TITLE
Campaign Finder - Copy for mobile/desktop homepage views

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1800]

**Comment by joolaay** [comment]
Nancy approved:

Desktop:
Join 2.5 million young people. --> H1
Any cause, anytime, anywhere.  -->H2 (hidden)
Start by finding a campaign below: -->H2?

Mobile:
Any cause, anytime, anywhere.  -->H2 

Thanks @weerd for talking through this!
@barryclark ready to hand off

**Comment by barryclark** [comment]
Sweet! Passing this one over to @weerd  as high priority.
