### ISSUE TITLE
[Campaign Finder] Subpixel rendering issue with campaign boxes

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#1801]
At certain sizes of the browser, the campaign boxes sometimes clear and cause gaps due to subpixel rendering issues. Need to find a solution; potentially force a few clear-fixes on specific boxes. Likely use nth-child() to address clearing box, and ignore the support for IE8...

**Comment by joolaay** [comment]
@weerd I'm actually seeing a lot of these gaps when other people open the finder - maybe you can talk me through this so I understand properly?

**Comment by weerd** [comment]
@julielorch sure. It's a browser specific issue. Sometimes happens on certain browsers more than others. We can discuss further :)

**Comment by barryclark** [comment]
I think this got fixed, right @weerd?

**Comment by DFurnes** [comment]
Yup, this was fixed by #1835.

**Comment by barryclark** [comment]
Thanks @DFurnes
