### ISSUE TITLE
action page (address collection) - post-form-submission state

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1806]
If a user has submitted a form requesting we send them stuff (i.e. banners for Comeback Clothes) we should prevent them from submitting that form a second time.

If I have already requested banners, I should still see the link to trigger the address collection modal. However, when I click on the link the modal I see should hide the address fields and the copy from the "form copy" field and instead give me a message saying "We received your request blah blah blah".

@aaronschachter I assume you'd rather have this be a standard message across all rather than being another field. Definitely open to trying to start but I feel like for Thumb Wars we'll run into a bunch of questions, but happy to tackle that if/when it comes if you'd prefer. Let me know what you think.

If we do go with just one standard message, for now let's do "You requested your package on [time stamp in the form of Month, xxst/nd/rd/th] and it's on it's way! Questions? Fill out our contact us at the bottom of the page and we'll get right back to you."

**Comment by aaronschachter** [comment]
I'm building this as a new field to fill out in the Signup Data configuration form.

**Comment by mikefantini** [comment]
@aaronschachter sounds good

**Comment by angaither** [comment]
@aaronschachter what's going to be a new field? the text?

**Comment by aaronschachter** [comment]
Yep, a new column rather, on the `dosomething_signup_data_form` table called `form_submitted_copy` that editors can fill out in the Signup Data Form section on the campaign edit form.  

If the user has submitted the signup data form already, this copy will be displayed.  It will need to tokenize a [submitted] variable to display the date submitted.

**Comment by aaronschachter** [comment]
@mikefantini We will have the ability to have custom messages per signup form.  Did you still want to stick with "You requested your package on [time stamp in the form of Month, xxst/nd/rd/th] and it's on it's way! Questions? Fill out our contact us at the bottom of the page and we'll get right back to you." ?

**Comment by mikefantini** [comment]
@aaronschachter awesome let's just go with the field and I'll have the campaigns team fill it out. What will they need to enter in order to get the time stamp of when the user submitted the form?

**Comment by aaronschachter** [comment]
#1826 caused the great epic fail #1840.  these commits have been reverted, still need to get this back in.
