### ISSUE TITLE
Contrib module subdirectory

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#181]
The securepages module is being placed into `profiles/dosomething/modules` instead of `profiles/dosomething/modules/contrib`

**Comment by aaronschachter** [comment]
FYI - This is now occurring for the newly added `search_api` and `search_api_solr` modules too.

**Comment by aaronschachter** [comment]
Since we've removed `search_api` and `search_api_solr`, only `securespages` lives outside of the contrib directory.  Guess the build / make file has a thing for modules that start with "se".

**Comment by desmondmorris** [comment]
@aaronschachter since @angaither also removed secure pages, I guess this is not an issue any more

![](http://www.chud.com/articles/content_images/47/TimandEricSeason2/TimEric7.jpg)
