### ISSUE TITLE
admin view - update so that admin bar drops other content lower

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1814]
Admin bar covers admin tabs making it difficult to access admin tools.

![image](https://cloud.githubusercontent.com/assets/6330971/2720306/8a3a8cb4-c56d-11e3-85bb-a9da146bc15d.png)

**Comment by mikefantini** [comment]
https://trello.com/c/4FYvBZOj

**Comment by barryclark** [comment]
Fixed
