### ISSUE TITLE
Auth - using email address we suggest on wrong, but close cases doesn't work

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1820]
When entering a _close but wrong_ email address and try to use our suggestion to fix it I get an error message and it doesn't pull in the suggestion.

To replicate:
- create an account
- enter mfantini@dotmail.com
- it suggests mfantini@hotmail.com
- click "Fix it!"
- and it pulls in Fix it! not mfantini@hotmail.com

![image](https://cloud.githubusercontent.com/assets/6330971/2722583/aa5e188c-c589-11e3-9c14-a88af89e9eb1.png)

**Comment by barryclark** [comment]
@DFurnes fixed this guy
