### ISSUE TITLE
address collection - enter wrong address, enter right address, still get error

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1825]
Steps to replicate:
- logged out, go to Comeback Clothes
- create a new account when signing up for Comeback Clothes
- enter in a bullshit address
- get error message
- try to update your address with a real address
- get error message again

It should give them a success message because they entered in an appropriate address.

**Comment by mikefantini** [comment]
@angaither weird I'm now just getting error messages any time I try to use my home address growing up. 

But trying to replicate that bug with our address at the office didn't actually replicate it.

**Comment by angaither** [comment]
Your :house: is gone.

**Comment by angaither** [comment]
I'm having trouble replicating this as well.

**Comment by mikefantini** [comment]
@angaither yeah I'm just getting the error message on my home address... which is definitely a real address...

**Comment by angaither** [comment]
Yes. Yes. Since we are validating against the developement API on stage, it only checks NY & California addresses. If we switch to validate against the production API it should be ok :ballot_box_with_check:

**Comment by angaither** [comment]
Tested with my parents address, kablam. The dev API was the issue. 
FYI: I've flipped this back to the dev api on stage.
