### ISSUE TITLE
address collection - some invalid addresses are accepted as valid

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1836]
Issue occurs when you input an invalid street number that has the same number of digits as a valid street address (such as a 3 digit number or 1 digit number).. 

For example:
- 40 Kellie Ann Ct. Orinda CA 94563 is a valid address and is correctly accepted. 
- The address 90 Kellie Ann Ct. Orinda CA 94563 is not valid because there is no number 90 house on that street, but it is still being accpeted. 

However, if we do:
- 2 Kellie Ann Ct. Orinda Ca 94563 it gets correctly rejected 
- 200 Kellie Ann Ct. Orinda CA 94563 also correctly gets rejected as expected. 

That is because there are only houses with 2 digit numbers on the given street and the website therefore thinks that all 2 digit numbers are valid.

Trello issue: https://trello.com/c/4Q6JhuLQ

**Comment by angaither** [comment]
Not sure there is much I can do about this one, the UPS api returns 1-99 as 'valid' addresses. 
They should report this bug to UPS

99 Kellie Ann Ct. Orinda CA 94563
![](http://cl.ly/image/0f340j433F28/Screen%20Shot%202014-04-16%20at%205.58.42%20PM.png)

990 Kellie Ann Ct. Orinda CA 94563
![](http://cl.ly/image/0T0P0U3B0d3O/Screen%20Shot%202014-04-16%20at%205.59.37%20PM.png)

**Comment by angaither** [comment]
Closing, confirmed this is a bug in the UPS API.
