### ISSUE TITLE
Version paths for static assets + long expire times

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#1841]
We want the best of both worlds:
1. Have browsers cache static assets for a long time.
2. Retain the ability to force browsers to load updated assets.

We have the first quality right now, but not the second: `file.css` is usually served with a 30-day [TTL](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9), but browsers may then ignore when we update `file.css` within the TTL period.

The classic solution for providing the second quality is versioning within the path. So `file.css` becomes, e.g., `/v1.0.1/file.css`. `/v1.0.1` gets stripped out by the web server, making it just a logical designation. The next deployment will update this to, e.g., `/v1.0.2`, or `/v1.1`.

This approach would fit nicely with our desire to version every release and supply the web heads with an env var set to the deployed version. This could get injected at the application level on page construction.

**Comment by mshmsh5000** [comment]
@desmondmorris @DFurnes @weerd @aaronschachter @barryclark Take a think on this, plz. /cc @mikefantini

**Comment by mikefantini** [comment]
@mshmsh5000 @desmondmorris @aaronschachter @DFurnes @weerd @barryclark since we just launched a new homepage and it looks super whack without the proper css (see image below), is there any way we could change the TTL period to be 1 day just momentarily and then update it to 30-day TTL?

![rge-screenshot 1](https://cloud.githubusercontent.com/assets/6330971/2736522/903a7eb0-c66e-11e3-8e55-1779a86b7588.png)

**Comment by barryclark** [comment]
Assigning this one to @mshmsh5000

**Comment by DFurnes** [comment]
:+1:

Makes sense to me to make a set of theme helper methods that generate the stylesheet, script, or image tag with the proper versioned path on the Drupal application side. Shouldn't have any problems with URLs in CSS then since those are all relative & will be tied to the cache on the old versioned CSS.

We'll also need to make sure we tie Bower assets to the same versioned path, since our Neue CSS in there changes fairly frequently.

**Comment by mikefantini** [comment]
Went to our site using intern computer on Chrome, Windows 7, and saw this: 
![image](https://cloud.githubusercontent.com/assets/6330971/2818934/7f2a5c34-cee9-11e3-90f2-5ae33c0e8506.png)

@barryclark let's chat when you get in and prioritize this accordingly.

**Comment by barryclark** [comment]
@mshmsh5000 is release tagging blocking this moving forward? 

cc @mikefantini @desmondmorris @aaronschachter @DFurnes

**Comment by mikefantini** [comment]
let's update trello card once this is fixed: https://trello.com/c/u6l5l0Rq

**Comment by mikefantini** [comment]
any update on this @mshmsh5000 @DFurnes?

this is what a newer campaign pitch page currently looks like on production:

![image](https://cloud.githubusercontent.com/assets/6330971/2963783/1ebb4898-dadf-11e3-90f8-fa2a759d5a8c.png) 

and what the homepage looked like: ![image](https://cloud.githubusercontent.com/assets/6330971/2963769/f29f15fa-dade-11e3-8a06-f998061cb04b.png)

cc: @weerd

**Comment by barryclark** [comment]
@mikefantini Matt/Dave met about this and Dave is now unblocked to start working on this next week, once Signup Data work is done and dusted.

**Comment by barryclark** [comment]
Also #2099 is the issue for the subtask that Matt/Dave broke out.

**Comment by mikefantini** [comment]
@barryclark @DFurnes did we do something recently that would make the pages look so whack on browsers again? Or is it that the TTL period expired for people's browsers in the office?

**Comment by barryclark** [comment]
I'm not sure, but @desmondmorris and @DFurnes are currently working on the fix...

**Comment by desmondmorris** [comment]
We decided the best course of action is to generate distribution assets post release.  The assets are then placed into the drupal "files" directory to take advantage of the akamai network.  So:

`https://www.dosomething.com/sites/default/files/assets/v0.2.25/app.css`

becomes

`https://dosomething-a.akamaihd.net/sites/default/files/assets/v0.2.25/app.css`

I rigged all of this stuff already.  There is a `Deploy Assets` job in jenkins that runs downstream from the `Release` job.  The next step is to set a VERSION marker post deployment

**Comment by desmondmorris** [comment]
#2131 adds a static VERSION marker to the webroot during deployment.  It also adds a variable accessible in Drupal (`ds_version`).  When this is merged in, you will be able to access either from the application

**Comment by DFurnes** [comment]
That's magical. :+1:

**Comment by barryclark** [comment]
:sparkling_heart: :sparkling_heart: :sparkling_heart:
