### ISSUE TITLE
auth - able to create new account even with invalid phone number

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1847]
When registering for the website, you can add an invalid phone number of any type and you will be signed up for the website, if all of the other required data is present. 

I get an error message that phone number is invalid and does not save the phone number data you entered, but it does still allow you to register.

To replicate:
- go to site
- get to create account modal
- enter in proper info for all fields except enter 5555555555 into mobile field
- hit create account
- get taken to white screen
- go back to homepage or user profile

**Comment by mikefantini** [comment]
Trello card here: https://trello.com/c/nGiMFtHL

Trello card is for nigeria site but I checked and it's happening on domestic site as well.

**Comment by barryclark** [comment]
@DFurnes We can close this old one now, right?

**Comment by DFurnes** [comment]
Yep! Fixed in #3037 and [DS-303](https://jira.dosomething.org/browse/DS-303).
