### ISSUE TITLE
international - taken to blank page after register

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1848]
when you create a new account on http://nigeria.international.dosomething.org/ you get taken to http://nigeria.international.dosomething.org/user/register which appears as a blank page.

This happens whether you are creating an account through the log in in the upper right hand corner of the nav or going through a pitch page.

The ideal behavior is that a user should remain on the page they are on.

cc: @barryclark

**Comment by desmondmorris** [comment]
This is an issue with message broker.  Its the same issue as #1850.  The call to `dosomething_user_mbp_request` is causing the WSOD.
