### ISSUE TITLE
international - error when report back

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1850]
On http://nigeria.international.dosomething.org/ when I go to report back on a campaign I am currently taken to this screen:

![image](https://cloud.githubusercontent.com/assets/6330971/2736786/edd7379a-c671-11e3-8c7d-04de286c1d82.png)

Previously this error occurred when reporting back:
![upload 2014-04-04 at 9 41 23 am](https://cloud.githubusercontent.com/assets/6330971/2736804/454b6820-c672-11e3-9544-0162c8d72efb.png)

In both instances reported back with a photo I have used previously to test report backs (successfully) and properly filled out # of items collected and why is this important to you.

cc: @barryclark

**Comment by mshmsh5000** [comment]
@desmondmorris Problem with /tmp?

**Comment by desmondmorris** [comment]
@mshmsh5000 @mikefantini This is an issue with message broker.  Its a similar issue to #1848.  The call to `dosomething_user_mbp_request` is causing the WSOD.

**Comment by desmondmorris** [comment]
Looks like `dosomething_user_mbp_request` has be deprecated and the logic has been abstracted to dosomething_mbp_request.  The platform codebase on international is out of date.

**Comment by desmondmorris** [comment]
@mshmsh5000 @mikefantini I just ran deploy to international and it looks like we are experiencing the same entitywrapper issues that @aaronschachter has been fighting through.  I was forced to rollback the deploy.  We can not deploy here until #1840 is resolved.

**Comment by mikefantini** [comment]
@desmondmorris @mshmsh5000 #1840 is closed, your call on when we should deploy the fix. I can just talk through it right now since it's just with registration.

**Comment by desmondmorris** [comment]
@mikefantini I have updated the international platform and each of the individual sites.
