### ISSUE TITLE
DS Build: drupal-org.make doesn't respect version numbers

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1854]
- [x] Audit what versions of all contrib modules that are in the codebase: https://gist.github.com/aaronschachter/c279be7308f9132da096
- [x] Update `drupal-org.make` to specify `[version]` for each module, and updating any versions which don't match what we're currently using (e.g. Entity and Field Collection examples below)

---

The build is not using the specified version numbers, but instead grabbing the latest recommended release.  This makes for trickier debugging when shit starts failing.

A guess would be maybe we have to specify the whole version number, e.g. "7.x-1.2"

Examples:

makefile Entity:
`projects[entity] = "1.2"` 
In entity.info:
`
; Information added by Drupal.org packaging script on 2014-04-08
version = "7.x-1.5"`

makefile Field Collection:
`projects[field_collection] = "1.0-beta5"` 
but in `html/profiles/dosomething/modules/contrib/`, FC is `"7.x-1.0-beta7"`

**Comment by mshmsh5000** [comment]
For comparison, here is the make file generated by Drush: https://gist.github.com/mshmsh5000/11054040

**Comment by aaronschachter** [comment]
Seems like the issue may be that we're not specifying the `[version]`:

e.g. 

```
; Date
projects[date] = "2.6"
```

instead of `projects[date][version] = "2.6"`

I'll test to confirm.

**Comment by aaronschachter** [comment]
Confirmed that specifying the `[version]` will download the specific version.  Updated the issue description with what needs to happen to resolve.
