### ISSUE TITLE
Show form validation errors within modal

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#1855]
We're looking to show Drupal form validation errors within the form they were submitted from, rather than (or even in addition to) at the top of the page. The problem we're running into is that Drupal clears the `$messages` variable when printing it to the page so it's empty later on when we try to grab it again in the node template.

Does anyone have any suggestions on the proper way to handle printing the page messages in two different places on the page?

/cc @desmondmorris @aaronschachter

**Comment by DFurnes** [comment]
One thought would be registering messages that we want shown on the form with [`drupal_set_message`](https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_set_message/7) as a "form" type and then popping those from the `$messages` array and storing them in a separate variable for use by the node later when preprocessing the page.

**Comment by aaronschachter** [comment]
My inclination would be to use Drupal's `#ajax` Form API stuff if possible: https://drupal.org/node/752056 

But I'm not sure if we're stripping out the required JS in neue to make this work

**Comment by DFurnes** [comment]
Hacky solution in place; see #1858, #1863, DoSomething/neue#248.
