### ISSUE TITLE
Knock the size down on the boiler plate.

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1866]
Lets figure out leading and font size that tightens up this boiler plate on the pages it shows up on. 

![screen shot 2014-04-19 at 12 42 54 am](https://cloud.githubusercontent.com/assets/6550604/2747687/45e486b6-c77d-11e3-864b-996403db25a0.png)

**Comment by tjrosario** [comment]
Refers to #2135.  Already resolved.
