### ISSUE TITLE
campaign (form) - can't remove official rules pdf

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1869]
Admin (or editor) users can't remove official rules pdf from Official Rules field located in the Prove It section.

When you click to remove the file it just spins as if it is removing the file but it doesn't actually remove anything.

It works properly in staging but not in production.

Check out https://www.dosomething.org/node/955/edit to see the file that needs to be removed.

Bug came up because Nami needs to update the official rules for PB Jam Slam since we are extending the date.

cc: @desmondmorris @barryclark @aaronschachter

**Comment by aaronschachter** [comment]
@mshmsh5000 Possibly a varnish configuration we need to add, similar to the autocomplete issue we saw on prod?

**Comment by mikefantini** [comment]
please update trello card when fixed: https://trello.com/c/pdTgslmI

**Comment by mikefantini** [comment]
closing this out since work around exists to just use beta. instead of www.
