### ISSUE TITLE
[User Profile] Collect data for campaign signups from view instead of markup

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#1870]
```
$account->content['campaigns'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Campaigns'),
    '#markup' => views_embed_view('user_signups', 'block', $account->uid),
  );
```

Instead of collecting the markup as a string for the signed up campaigns for a user, collect the data into an array to preprocess and send to the template.

**Comment by aaronschachter** [comment]
Per @julielorch -- this array should be sorted by signup timestamp, descending.

We could loop through the view result to get the array, but we actually have the array of signups already in `dosomething_signup_get_signup_nids_by_uid`, it just needs `$query->orderBy('timestamp', 'DESC');` added.

Then, we can use the campaign partial #1872 to display each campaign block per returned $nid in `dosomething_signup_get_signup_nids_by_uid`, similar to how the recommended campaigns are being returned.
