### ISSUE TITLE
Campaign confirmation links bug

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1873]
The campaign confirmation page link URL's are incorrect.

On https://www.dosomething.org/node/362/confirmation:

All links link to:
https://www.dosomething.org/node/362/node/832
https://www.dosomething.org/node/362/node/6
etc
and therefore link you back to the campaign you reported back on.

Check the bottom left status:
![screen shot 2014-04-21 at 3 24 26 pm](https://cloud.githubusercontent.com/assets/1236811/2757954/d3328270-c98a-11e3-850f-9e8ef4bc81d5.png)

**Comment by barryclark** [comment]
Shooting this one over to you, @weerd
