### ISSUE TITLE
Environment variable for Drupal hash salt

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1882]
In order to make our repo public, the `$drupal_hash_salt` variable needs to be set as an environment variable.

**Comment by aaronschachter** [comment]
There's also a `$conf['varnish_control_key']`, which has the comment `This is managed from salt://varnishd/secret`.

@desmondmorris @mshmsh5000 @blisteringherb  -- Is this something that needs to be removed as well?

**Comment by mshmsh5000** [comment]
Two things:
1. We're going to move the Salt provisioning logic out of this repo, which will remove this as a blocker for taking the platform code public.
2. I don't think we need to manage this hash at all. I will confirm before closing this issue.

**Comment by barryclark** [comment]
Prittay sure we can close this @mshmsh5000 ?
