### ISSUE TITLE
Make varnish control key private

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1884]
Is this varnish control key dangerous to expose to the public?  Is the solution to use an environment variable instead?

```
// This is managed from salt://varnishd/secret
$conf['varnish_control_key'] = '00c9203c65874ca5b4c359e19f00bf56';
```

**Comment by mshmsh5000** [comment]
This is fine -- only used by Salt-provisioned (dev) instances. If we ever switch to using Salt for production, we'll need to sweep through the .sls files thoroughly.
