### ISSUE TITLE
Font color on report back file upload is a usability concern. 

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1890]
Users can not see the font color used on the report back modal which shows that the file has been attached. Please consider a change in color, or a change in design to increase usability here. 

![screen shot 2014-04-29 at 12 49 57 pm](https://cloud.githubusercontent.com/assets/6550604/2831879/6b3783fc-cfbe-11e3-95b7-f0c63fef7862.png)

**Comment by DFurnes** [comment]
Just gonna [drop this here](DoSomething/dosomething#1928)…

![fileupload](https://cloud.githubusercontent.com/assets/583202/2848191/6272b6be-d0b9-11e3-8400-49b2646c4afe.gif)
