### ISSUE TITLE
Jump to campaigns on mobile when find a campaign button is clicked

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1891]
Users are clicking Find a Campaign button with no filters and don't know how to see campaigns. It should just jump down to campaigns listed in the same order as we have them on the standard homepage screen that way we can recommend the campaigns that are most of interest to us if users dont care to filter. 

![screen shot 2014-04-29 at 1 06 41 pm](https://cloud.githubusercontent.com/assets/6550604/2832055/b9cd759c-cfc0-11e3-8908-009e10456c01.png)

**Comment by mikefantini** [comment]
Closing this in favor of #6375
