### ISSUE TITLE
Campaign Group: Child signup should also signup for Group

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1896]
When signing up for a child campaign of a Campaign Group, a signup entity should also be created for the parent Campaign Group, in order to opt-in the user for the 3rd party communications of the Campaign Group.

**Comment by aaronschachter** [comment]
@mikefantini @barryclark  Does the campaign group appear on a user profile? Or should the profile filter out Campaign Group signups?

**Comment by mikefantini** [comment]
@aaronschachter campaign group will not appear on the user profile
