### ISSUE TITLE
[Refactor] Add more media queries and rename to be more generic for sizes and not device specific.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#1902]
Custom media queries needed for scenarios in between currently established media queries. May be useful to add additional media queries to allow flexibility within the established breakpoints. Could be useful to change the naming to be more generic, such as $small, $medium, $large, $extra-large, etc…

**Comment by DFurnes** [comment]
More media queries and generic naming were added in Neue 6.0! Closing!
