### ISSUE TITLE
Duplicate users

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1907]
There's two records for one email & mobile.  

My guess would be this is replicable by clicking the submit button multiple times upon creating an account.  See users 1753377 and 1753376 on production: identical email and mobile values.  

(can't include screenshot if we're going public repo!)

**Comment by aaronschachter** [comment]
Confirmed this can be replicated by clicking the submit button multiple times upon creating an account

![screen shot 2014-04-30 at 9 48 41 am](https://cloud.githubusercontent.com/assets/1236811/2841898/4a715f3e-d06e-11e3-9604-91b251f17104.png)

Assigning to @barryclark to triage.  This is an age old Drupal issue that can happen by clicking any button twice, not sure if the solution is strictly server-side or not...

**Comment by DFurnes** [comment]
I'm thinking this should be a server-side fix, since we don't want the integrity of the database to be relying on a user having JavaScript enabled. Ideally, I think we should be generating a token for each form on the server-side and then preventing the same form from being submitted more than once.

**Comment by DFurnes** [comment]
We can also do some UX niceties on the client-side (disabling a form submit button and showing a spinner, for example) but that probably isn't a very robust fix for the underlying problem.

**Comment by barryclark** [comment]
@aaronschachter - Would you agree that we shouldn't allow the user to be able to create multiple accounts like this on the server-side? 

Then we could also add in some client-side UX niceties, like a "submitting" button state. (via @DFurnes)

**Comment by aaronschachter** [comment]
I would agree that it should be prevented with server side validation methods, it's just unfortunate Drupal doesn't do this by default.  There's not a lot out there (most forums suggest JS solutions) but this could be a lead: https://drupal.org/node/1436258#comment-5881346

**Comment by barryclark** [comment]
@aaronschachter Would we need to hack core to implement the fix that @DFurnes suggested? Should there not be a check in there anyway to prevent someone signing up with the same email address? :imp:

**Comment by aaronschachter** [comment]
I think we'd be able to do this with Form API stuff, and wouldn't need to hack core.  It would be similar to that d.o comment I posted, where potentially we'd be adding extra data into the form with a `hook_form_alter` and validate.

**Comment by DFurnes** [comment]
Assigning myself after an offline conversation, we're gonna go with a little JavaScript fix for now. :dancers:
