### ISSUE TITLE
Signup Data Form: Prompt user after signup

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1913]
Blocked by #1904

If a signup data form is required, present the signup data form modal when the user first visits the action page.

For now, this will be done in somewhere in the theme template.php checking to see if the user has submitted the modal (by checking the timestamp).  If not, `drupal_add_js`: https://gist.github.com/aaronschachter/304bb24b0d5d81ac17b8

**Comment by aaronschachter** [comment]
Assigning to @DFurnes and changing to "fender" -- all that's left is getting the modal to render once you visit a campaign and haven't submitted the signup form.  I've set up http://staging.beta.dosomething.org/campaigns/thumb-wars with the proper signup data form configuration, you can see the inline JS in the footer.

**Comment by DFurnes** [comment]
Found the problem, `$` is not defined in the global scope because Drupal forces jQuery into `noConflict` mode. Switching it to this should fix it:

``` js
require(["neue/modal"], function(Modal) { Modal.open( jQuery("#modal-signup-data-form"), false); });
```

I'll throw in a PR in a minute.
