### ISSUE TITLE
Report back photos should become squares

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1916]
Based on our organizational decisions, all report back photos should be displayed on campaign pages as squares. 

![screen shot 2014-04-30 at 11 10 36 am](https://cloud.githubusercontent.com/assets/6550604/2842914/a3bca458-d079-11e3-81e5-b6d59eb94ee5.png)

**Comment by mikefantini** [comment]
@barryclark assigning this over to you; seems to be creating a lot of issues for Keri/campaigns team and is slowing them down from getting report back photos up.

Do you have thoughts on this issue and if we might be able to get it in next sprint?

**Comment by barryclark** [comment]
Next sprint seems like a good goal @mikefantini, thanks.

**Comment by weerd** [comment]
I could do this one quick since it's within the stuff I worked on w/ the campaigns template refactor. Just lemme know :)

**Comment by barryclark** [comment]
Yep, assigning over to you @weerd thanks

**Comment by weerd** [comment]
I'm working on this issue. I had a quick thought though, and most cameras that user's would be using for taking a picture (likely their mobile phones or a digital camera) all take landscape photos. So Drupal will be auto-cropping these, and will potentially cut parts of the image off to square it... just something to consider.

**Comment by weerd** [comment]
Sample of what it looks like as square on tablet-y size:
![screen shot 2014-07-11 at 10 54 18 am](https://cloud.githubusercontent.com/assets/105849/3554264/6363b822-090b-11e4-84ef-d7dd80cb0966.png)

**Comment by weerd** [comment]
Sample of what it looks like as square on desktop at full width:
![screen shot 2014-07-11 at 10 54 29 am](https://cloud.githubusercontent.com/assets/105849/3554275/79167be6-090b-11e4-9f71-5227d03fa917.png)

We should probably limit the height of the fluid image at a certain point otherwise it looks kinda weird... @mikefantini @crystalruthbell let me know if examples above look good and I can move forward to make adjustments, etc to finalize update :tropical_drink:

**Comment by mikefantini** [comment]
@weerd we may want to hold on this right now. As part of the template re-vamp we will be giving users the ability to crop their image into a square (a la instagram). This will limit the grossness of how the images look.

We then can take a look at the images we have currently in the galleries and decide if it is worth the effort to re-crop them and re-upload them to fit the square layout or if we just want to display new report backs moving forward.

cc: @crystalruthbell

**Comment by weerd** [comment]
Okie doke. Sounds good. I'll hold off on this. Can we unlabel this as high priority then? :sun_with_face: 

For future dev reference, need to adjust the pixel values specified in:

```
$vars['reportback_image'][$key] = dosomething_image_get_themed_image_url($rb_image->nid, 'landscape', '400x400');
```

Line exists in the **dosomething_campaign** module, in **dosomething_campaign.theme.inc**.

**Comment by aaronschachter** [comment]
This will be addressed in https://github.com/DoSomething/dosomething/milestones/Reportbacks%20v2.0
