### ISSUE TITLE
Signup Data Form: Need ability to skip form

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1920]
As a user I want the ability to skip the required form I get presented with.

**Comment by aaronschachter** [comment]
Do we actually need a "Skip This" link to click on, or is having the "X" close button enough?

**Comment by mikefantini** [comment]
I feel like a skip this link similar to the "Back to main page" link we have on content modals on the action page makes sense in addition to the "X" but I'm open.

@DFurnes do you have thoughts?
