### ISSUE TITLE
Signup Data Form: Old people messaging

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1921]
- [x] Create a `dosomething_user_is_old_person` function which returns TRUE if user is over 25
- [x] Create a new property for a signup data form, "Prevent old people from submitting", which will not be checked by default.
- [x] Modify the auto-prompt user (refs #1913) functionality to check for this setting, and if set, auto-prompt based on whether not `dosomething_user_is_old_person`
- [x] Create a new property for "Old people copy", which is only visible in the config form when "Prevent old people from submitting" is checked
- [x] Modify the user-facing signup data form to display the "Old people copy" if an old person is viewing the signup data form (which would be done by clicking the modal link in the action page)

**Comment by aaronschachter** [comment]
@mikefantini Updated this issue description with steps to make it happen.  Please provide copy for the 3rd step, unless the copy I've provided works.

**Comment by aaronschachter** [comment]
@mikefantini Is it accurate that the auto-prompt should check for whether or not the signup_data_form ONLY when configured to collect addresses?

**Comment by mikefantini** [comment]
@aaronschachter i think it makes the most sense to allow the campaign lead to determine whether to ask old people or not.

The primary case we're trying to protect against right now is running out of thumb socks and having old people ask for them because in general we don't want to spend money sending stuff to old people.

However, I could see a case potentially of wanting to send banner to a teacher that signs up.

So if we can make it toggle on/off that would be best.

**Comment by aaronschachter** [comment]
Updated issue to create a property to determine whether or not Old People can submit the form, and to create an additional property for an editor to set the copy to display when an Old Person accesses the form via modal.

**Comment by barryclark** [comment]
@aaronschachter Does @DFurnes need to take care of anything on the front-end for this?

**Comment by aaronschachter** [comment]
Nope.  To simplify things, when a old person is presented with a modal, I am not rendering the header and close button.  But when you click out, the modal goes away.  That might confuse old people but was the simplest way to build.

**Comment by barryclark** [comment]
Cool thanks
