### ISSUE TITLE
[Signup Data Form] Close button logic for required forms

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1930]
For a signup data form which is required:

If the user has not submitted it before (the signup `signup_data_form_submitted` value is NULL) , the close button should not appear.  user is forced to either submit or skip (if skip is allowed).  In this case the modal is usually being displayed directly after signup.

If the user has submitted it (there is a value for `signup_data_form_submitted`), the close button should display.  This is the scenario where they're viewing it again, via clicking on the link to the modal within "Stuff You Need."

**Comment by mikefantini** [comment]
@DFurnes is this one easier to do than #1985? Because if we can knock 1985 out, we don't need this one. Originally we had put it in just so we would have something in place and be good for launch, but just wanted to make sure that plan still makes sense.
