### ISSUE TITLE
[Signup Data Form] button placement

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1947]
For the address collection modal, we have the button left aligned. For the report back modal (and auth modal) we have the button centered.

We should probably pick one direction and standardize across.

Thoughts @crystalruthbell @DFurnes?

![image](https://cloud.githubusercontent.com/assets/6330971/2863817/85967634-d209-11e3-89e3-6fffb562b5d5.png)

![image](https://cloud.githubusercontent.com/assets/6330971/2863820/8f843406-d209-11e3-9f4b-726729638b7c.png)

**Comment by barryclark** [comment]
Done!
