### ISSUE TITLE
[Signup Data Form] invalid address worked

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1950]
I entered an incorrect address (no street, wrong zip code) and it said it was valid.

http://screencast.com/t/MhphozJU

**Comment by mikefantini** [comment]
also accepted:

19 West 21st Street
8th Floor
New York, NY
111

Not even a valid zip...

**Comment by angaither** [comment]
values are being saved correctly, they were close enough that UPS knew what the values were
