### ISSUE TITLE
[Signup Data Form] weird spacing at top of modal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1952]
Additional spacing at the top of the modal. I believe this is happening because I got rid of the notification message upon signing up.

This would mean everyone who signs up for comeback clothes and closes the notification and then opens up the modal after they first sign up would see this.

If you log out and then log back in and then open the modal everything looks fine.

http://screencast.com/t/KKh64X3oo

When testing something else it seems as if ALL notifications are appearing at the top of this modal. Clearly not something that makes sense since previous notifications (like creating an account and signing up for the campaign) have nothing to do with that modal.

http://screencast.com/t/wewA0uT6m9Nt

**Comment by barryclark** [comment]
Fixed
