### ISSUE TITLE
[Signup Data Form] closing notification closes modal as well

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1953]
Can't close out the notification message at top of address collection modal without closing the modal too.

Obviously example doesn't make as much sense in this video, BUT imagine the error message here was that I entered in the wrong address. If I want to remove that error message and then fix my address I can't because it closes the modal as well.

Also after closing the modal (in an attempt to remove the error message), when I re-open the modal I am still seeing the error message.

http://screencast.com/t/FuYdVdCVdP

**Comment by DFurnes** [comment]
Is the desired solution that we have two "x" buttons – one for closing the error message, and one for closing the modal?

**Comment by mikefantini** [comment]
Yeah I think this makes sense. @DFurnes let me know if you want to connect on the various issues around this notification I put in on Friday.

**Comment by mikefantini** [comment]
for notifications in modals, we won't allow the user to close the notification

instead we'll have the notification appear below the black bar of the modal
