### ISSUE TITLE
[Campaign Group] Remove unnecessary fields and rearrange

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#1954]
The image and video fields are unnecessary because the sponsors field collection already has those fields.  Also the Pre signup and post signup fields should be grouped.

**Comment by aaronschachter** [comment]
@blisteringherb The image/video on the partners collection seems like it would be separate from the video/image on the actual page display.  Those fields are used within the partner modal: http://staging.beta.dosomething.org/node/362#modal-partner-0

If a campaign group did not have partners, we'd still want the video/image to display in the main group (I think? Is there something I'm missing?)

**Comment by blisteringherb** [comment]
@mikefantini Do you want editors to be able to potentially add a video or photo for both the sponsor and a separate video or photo in the intro?

**Comment by mikefantini** [comment]
@blisteringherb for now let's just allow for the campaign lead to add a video to the intro area (not a photo).

For the sponsor modal, we should allow for the campaign lead to add a separate photo/video to that modal.

So this would work the same way that action pages do on campaigns. In the Know It section we can have a video AND in the sponsor modal we can have a different video OR photo.
