### ISSUE TITLE
[Signup Data Form] wrong but close addresses

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1956]
When someone enters an invalid address but it's close to the real address, can we have them confirm the address we think it is before submitting it?

In this example, 21 Pineapple Lane isn't real, but 21 Pineapple Street is. Here even though the user submits Pineapple Lane, we enter it as Pineapple Street and save that to their profile.

http://screencast.com/t/rP8DJqxfwI

Ideally we would have the user confirm this suggestion before just going with it.

Some error message like "Hmmmm we couldn't quite find that address, is this what you meant?" and then display for them the address we think it is.

@barryclark not sure if this is a fender or bender task.

**Comment by mikefantini** [comment]
is this related to or a duplicate of #2091?

**Comment by barryclark** [comment]
@mikefantini Kinda yea... we talked about consolidating them but it's not really worth the time. We'll loop back around on all of these at EOD sync.

**Comment by mikefantini** [comment]
sounds good
