### ISSUE TITLE
[Signup Data Form] error messages for leaving required fields blank

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1957]
Ideally we would treat required fields for all signup data forms (like state or zip code when collecting addresses) the same as we treat last name.

This way the page wouldn't re-load with error messages but instead prevent the user from submitting the form with those blank fields.

http://screencast.com/t/A5dByVsMIx2q

**Comment by mikefantini** [comment]
Here are error messages Ben had put together. I'm open to having consistent language for all fields if you think that's a better way to go.

https://docs.google.com/a/dosomething.org/document/d/13JTQzGEY0vesU1417KJ-hMOWrnahL40rTqUDx5shLJc/edit

**Comment by DFurnes** [comment]
I had to cut some of the messages since they didn't fit inside the field labels (city, state, and zip in particular). I like the separate confirmation/error messages though, keeps it feeling a bit more natural.

**Comment by mikefantini** [comment]
sweet sounds good

**Comment by DFurnes** [comment]
Super success mode:
![screen shot 2014-05-14 at 12 04 01 pm](https://cloud.githubusercontent.com/assets/583202/2973826/66798d82-db81-11e3-8226-8c61946b6f29.png)

Catastrophic failure mode:
![screen shot 2014-05-14 at 12 04 45 pm](https://cloud.githubusercontent.com/assets/583202/2973832/7e03e02e-db81-11e3-80d9-689cd9c6513c.png)
