### ISSUE TITLE
[campaign template] - need ability to link to partner sites in "In partnership with"

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1959]
Add a link field to the `field_partners` field collection.

We should have this link out to partner pages in the "In partnership with" section of the action page of the campaign template AND grouped campaigns.

We still don't want the sponsor logo itself to link anywhere though.

**Comment by mikefantini** [comment]
let's make sure to update the trello card once this is closed: https://trello.com/c/zxSUWG7M

**Comment by aaronschachter** [comment]
@barryclark @mikefantini Should the link open in a new tab?

**Comment by mikefantini** [comment]
@aaronschachter i'm on board with it opening in a new tab but I know @barryclark and @DFurnes feel otherwise... honestly I'll defer to you guys on whatever you think makes the most sense

**Comment by DFurnes** [comment]
My vote would be to be consistent with however we're treating other external links for now.

**Comment by barryclark** [comment]
+1 to what Furnes said -- which is currently not opening in new tab

**Comment by mikefantini** [comment]
(note we do open in a new tab on location finder; see Comeback Clothes)

**Comment by aaronschachter** [comment]
@mikefantini Need to know whether or not this link should be defined on the Partner term, or on the node itself.

If on the Partner term: any time the Partner is displayed in the footer, it will link out.

Defining on the node would allow this to differ from node to node, or possibly link to different URLs for different nodes. e.g. The Hunt may link to toyota.com/kids and Thumb Wars could be toyota.com/driving

**Comment by mikefantini** [comment]
@aaronschachter - Chatted with Deluca, safer to go on the node itself so they can link to different URLs on different nodes.

**Comment by aaronschachter** [comment]
Updated issue description, working on this one next.
