### ISSUE TITLE
[Static content] need the ability to add a partner to static content

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1960]
Should work the same way as it does on campaigns (although for now we don't need fields for "Why is x sponsoring" so will only need partner name and whether they are a sponsor or not).

If it's a sponsor their logo should appear in the header AND we should have their name with "In partnership with" at the bottom.

If it's not a sponsor their name should just appear along with "In partnership with" at the bottom.

Need this ready and tested for May 27th launch of the Hunt

**Comment by aaronschachter** [comment]
This requires adding the `field_partners` field collection to the Static Content node type, and using similar / same functions that campaign use to display the header and footer.

**Comment by barryclark** [comment]
Wanna take care of this one, @aaronschachter? ... and shoot it over to @weerd for the front end after.

**Comment by aaronschachter** [comment]
Assigning to @weerd - ready for fending.

**Comment by mikefantini** [comment]
@weerd yeah tried adding sponsor to http://staging.beta.dosomething.org/about/hunt-member-created-campaign-challenge and logo isn't showing up

can you take a look once other grouped campaigns stuff is in a better place?

**Comment by weerd** [comment]
Partner shows up in footer now. Working on the login in the header :)

Also, didn't mean to close the issue. Accidentally pressed the wrong button :(

**Comment by mikefantini** [comment]
@weerd still not seeing sponsor logo in header. See http://staging.beta.dosomething.org/about/hunt-create-challenge

**Comment by mikefantini** [comment]
@weerd also doesn't seem to be showing up along the bottom either

**Comment by weerd** [comment]
@mikefantini  doh! sorry. I was looking at grouped campaigns. My bad. I'll do an update on this today and add it to static content as well! Got confused cause it was labeled with "grouped campaigns" :sun_with_face:

**Comment by weerd** [comment]
http://staging.beta.dosomething.org/about/hunt-create-challenge link to confirm!

**Comment by mikefantini** [comment]
yup! confirmed... thanks @weerd
