### ISSUE TITLE
[Admin report back view] - ability to look up report backs via email address

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1969]
Campaigns team would like to be able to search through reportbacks by email in addition to UID. 

They get a number of emails asking if a member's submission went through and it would be great if they could just search for the email address that appears on the ZenDesk ticket.

**Comment by mikefantini** [comment]
please update trello card when issue is closed out: https://trello.com/c/62V2qj3d

**Comment by aaronschachter** [comment]
I can take this one, it's a quickie.
