### ISSUE TITLE
Stage: Share cookies between http/https

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#198]
Currently authenticated only against the https stage-secure.ds. There should be a secure, https-only cookie and a non-secure cookie against *.dosomething.org.

This _might_ require specifying a more fine-grained shared domain, so that the naming convention would become

stage.dosomething.org
secure.stage.dosomething.org

That way, the cookies can be shared across *.stage.dosomething.org.

**Comment by barryclark** [comment]
Shooting this over to you, @angaither. Matt will speak with you about it.

**Comment by mshmsh5000** [comment]
Assigning myself -- FYI @barryclark -- as it's part of the http/https work I'm doing elsewhere.

**Comment by barryclark** [comment]
You didn't seem to get assigned, added you now @mshmsh5000

**Comment by barryclark** [comment]
@mshmsh5000 @angaither bumpppp - this might be done now?

**Comment by barryclark** [comment]
:boom:
