### ISSUE TITLE
Home entityreference (homepage)

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#1996]
Add the existing `field_campaigns` entityreference field to the `home` content type.

Alter the `paraneue_dosomething_preprocess_node` logic to use the field content to determine what to display, instead of a hardcoded array.

I'd argue that this preprocess code should go into a `dosomething_home.theme.inc` vs the theme.

See #1994

**Comment by barryclark** [comment]
Assigning this one over to @angaither. We'll be meeting soon to specify this out a bit more before building.
