### ISSUE TITLE
[Campaign Template] - allow more than three photos in the gallery

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2004]
Campaigns team needs to highlight more than just three report back photos.

The form allows you to enter more than three photos, but even still only three display.

@barryclark thoughts on this issue? If it's a small guy could we get it in this week?

**Comment by barryclark** [comment]
@mikefantini sounds like a good plan. @weerd can just ensure that lots of photos don't hold back page load time. 

We have loooots of high priority stuff right now that takes lead over this, so pushing it down to medium right now. But totally on our plate and will get it soon (likely next sprint).

**Comment by barryclark** [comment]
@weerd Would you be able to knock this one out real quick this sprint? It looks like a quickie and is being requested a lot. Upgrading to High Priority. Thanks

**Comment by weerd** [comment]
All set! I think there should be a recommended cap on number of photos ideally. But this works now :)
