### ISSUE TITLE
[user profile] Use l function for link to user profile

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2019]
Link to user profile should print `l($name, 'user/'. $user->uid)` instead of using `<a href="/users/<?php print $user->uid ?>`

Linking to "users/[uid]" doesn't work for any user with a readable username (like staff members), and will break things if we ever change that path alias.

**Comment by aaronschachter** [comment]
Actually all these links in the nav should be using `l`.

**Comment by weerd** [comment]
Cool. Will update! Thanks for flagging!
