### ISSUE TITLE
[Grouped Campaigns] Change intro title so it defaults to plain text.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2025]
@aaronschachter adding you to this but not sure if it should be for Morgan?

Anyway to change it so there is NO option to change it to markdown? We can't have <p> tags outputting inside of the heading tags...

**Comment by aaronschachter** [comment]
assigning to @blisteringherb

**Comment by weerd** [comment]
Should I do a feature revert or something? Cause I'm still getting markdown output in the title. I've pulled down latest code...

**Comment by aaronschachter** [comment]
Same. Will investigate.
