### ISSUE TITLE
[Grouped Campaigns] Link / modalize Zendesk form

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2034]
Depends on #2033

**Comment by aaronschachter** [comment]
This should ideally turn into a partial that we can place anywhere.  You'll notice that the code in `node--campaign.tpl.php` adds some help text.  We can either add that into the `zendesk_form` constructor function, or just maintain it in a tpl if easier.

**Comment by weerd** [comment]
We can discuss templating this, and how to best approach early next week. I think it's a good idea. Gonna close this issue for now and create a new one for refactoring to create a zendesk partial.
