### ISSUE TITLE
[Grouped Campaigns] alt color custom style field needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2041]
This would allow campaign lead to change the color of H2's on the page.

Same as we have on campaign node:

![image](https://cloud.githubusercontent.com/assets/6330971/2919359/61252950-d6da-11e3-99d6-49b302ee441d.png)

**Comment by aaronschachter** [comment]
Re-opening, value is not saving.

**Comment by aaronschachter** [comment]
@blisteringherb -- The original PR #2046 which closed this issue is 2 weeks old -- testing the changes would have indicated that both the form values weren't saving, and that the inline CSS was not being added.
