### ISSUE TITLE
Move DS specific message template setting logic

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2051]
The DoSomething specific email (Mandrill) template selection logic currently lives in mbc-transactional-email. This setting is specific to business rules of the producer. This logic should be in **dosomething_mbp.module**.

See:
https://github.com/DoSomething/message-broker/issues/56
https://github.com/DoSomething/mbc-transactional-email/issues/11

**Comment by aaronschachter** [comment]
@DeeZone just checking on this -- is this still a relevant issue?
