### ISSUE TITLE
email Banner Image field

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2055]
In order to support specific banner images for each Group Campaign's transactional email message a field needs to be added to the group_campaign node type. The value of this field needs to be passed in the payload sent to Message Broker via dosomething_mbp. The image upload and hosting will be managed by the Mailchimp template UI with the resulting image path from their server being the value entered in the new field.

**Comment by aaronschachter** [comment]
@mikefantini Is this banner the same image as the campaign cover image, or does it actually need to be a new field?

**Comment by mikefantini** [comment]
my understanding is that it needs to be a new field. question is really for @marahml though

In terms of my concern re: responsiveness, that's not really isolated to this issue since we're going to want to pull in our campaign cover images anyways so really we'll need to figure that out regardless of how we decide to handle this particular issue

**Comment by aaronschachter** [comment]
@marahml Can you weigh in here? It'd be great to reuse the campaign cover image field instead of creating a new specific field to only be used by emails.

**Comment by marahml** [comment]
@DeeZone @aaronschachter cover image works! As long as there is the gradient with white text (like our current banners) than that works fine.

**Comment by aaronschachter** [comment]
Hmm, would have worked until the gradient part, which is applied with css.  Per @mikefantini we may put this issue on hold for right now and just hardcode an image into the template until we need to launch another Grouped Campaign.

**Comment by mikefantini** [comment]
@marahml what would go in the white text?

do you have a visual you could share of what ideally it would look like? if not no need to create one, just wondering if one already existed.

**Comment by marahml** [comment]
This is what we currently have for staff pick broadcast emails, & I imagined it looking similar:

![image](https://cloud.githubusercontent.com/assets/6784628/2986473/d1dbb29e-dc44-11e3-83c7-17cdc58bbe44.png)

But since it sounds complex to automate - why don't we nix that and just do a normal sign-up email template w/ our purple background and white text? See image below.

The text would just need to be customizable.

![image](https://cloud.githubusercontent.com/assets/6784628/2986498/0e577e7e-dc45-11e3-954c-b6e87df8fafe.png)

**Comment by aaronschachter** [comment]
@DeeZone Where does that staff pick image come from?  Is it a field on the campaign node?

**Comment by mikefantini** [comment]
@aaronschachter that's for broadcast emails so I assume it's just a design element that gets added before they send out the broadcast.. no variables involved.

**Comment by aaronschachter** [comment]
oh, okay. so yeah, the white text on purple sounds like our best bet for now. @marahml @DeeZone.  If this is the route we're going on, this issue can be closed, as there isn't any work to be done in the Drupal app.

**Comment by marahml** [comment]
We need to customize the text for each banner (sometimes users will be "signing up" other times they will have just shown interest pre-launch, etc.).

If we have to create different banners for each of these - that means different Mandrill templates. (We don't edit the text in the tool.)

Is there a way to pull in text from Drupal? Or another solution for getting the custom text?

**Comment by deezone** [comment]
@marahml Moving this to a Message Broker issue as there's nothing from the Drupal side to be done. Please see https://github.com/DoSomething/message-broker/issues/59

Closing this issue. All further discussion should be on the Message Broker issue.

**Comment by aaronschachter** [comment]
Actually per meetings on Friday, we do need an image file to grab from the campaign node. Didn't realize that purple BG / white text is an image.  Because the desired functionality is for this white text to be customizable, we do need a new field to store an image.

**Comment by deezone** [comment]
@aaronschachter Wouldn't text in the banner area be the quickest / easiest solution (purple background, white text)? Perhaps matching the typeface is an important requirement?

**Comment by aaronschachter** [comment]
Yeah per convo with @marahml and @mikefantini --  it was the typeface that prevents us from using text. @mikefantini -- Is this accurate?

@barryclark If we need a new field, we may want to wait until we determine the fate of the `campaign_group` content type.

**Comment by mikefantini** [comment]
@marahml can you please go ahead and just add the banner you want to the template itself? Once we decide we want a second grouped campaign we will then work out a more scaleable solution (i.e. added banner field to content type and new merge tag to the template)

**Comment by marahml** [comment]
@mikefantini not a problem. @DeeZone can you link me the template or tell me the name?

**Comment by mikefantini** [comment]
@marahml I believe it's this one: https://us4.admin.mailchimp.com/templates/edit?id=56153
