### ISSUE TITLE
Zendesk form not submitting tickets

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2064]
Creating a ticket on Comeback Clothes on Production gives the general Exception catching error: "There was an error processing your request."

this is working for me locally, going to try grabbing a stage DB to see if i can replicate.  replicated on QA and checking watchdog:

exception 'Zendesk\API\ResponseException' with message 'Response to Zendesk\API\Tickets::create is not valid. Call $client->getDebug() for details' in /var/www/qa-beta/releases/20140509160246/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Tickets.php:108 Stack trace: #0 /var/www/qa-beta/releases/20140509160246/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module(160): Zendesk\API\Tickets->create(Array) #1 /var/www/qa-beta/releases/20140509160246/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module(128): dosomething_zendesk_create_ticket(Array) #2 /var/www/qa-beta/releases/20140509160246/html/includes/form.inc(1483): dosomething_zendesk_form_submit(Array, Array) #3 /var/www/qa-beta/releases/20140509160246/html/includes/form.inc(868): form_execute_handlers('submit', Array, Array) #4 /var/www/qa-beta/releases/20140509160246/html/includes/form.inc(380): drupal_process_form('dosomething_zen...', Array, Array) #5 /var/www/qa-beta/releases/20140509160246/html/includes/form.inc(131): drupal_build_form('dosomething_zen...', Array) #6 /var/www/qa-beta/releases/20140509160246/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module(304): drupal_get_form('dosomething_zen...', Object(stdClass)) #7 [internal function]: dosomething_campaign_node_view(Object(stdClass), 'full', 'en') #8 /var/www/qa-beta/releases/20140509160246/html/includes/module.inc(895): call_user_func_array('dosomething_cam...', Array) #9 /var/www/qa-beta/releases/20140509160246/html/modules/node/node.module(1445): module_invoke_all('node_view', Object(stdClass), 'full', 'en') #10 /var/www/qa-beta/releases/20140509160246/html/modules/node/node.module(1335): node_build_content(Object(stdClass), 'full', 'en') #11 /var/www/qa-beta/releases/20140509160246/html/modules/node/node.module(2671): node_view(Object(stdClass), 'full', NULL) #12 /var/www/qa-beta/releases/20140509160246/html/modules/node/node.module(1470): node_view_multiple(Array, 'full') #13 /var/www/qa-beta/releases/20140509160246/html/modules/node/node.module(2755): node_show(Object(stdClass)) #14 [internal function]: node_page_view(Object(stdClass)) #15 /var/www/qa-beta/releases/20140509160246/html/includes/menu.inc(517): call_user_func_array('node_page_view', Array) #16 /var/www/qa-beta/releases/20140509160246/html/index.php(21): menu_execute_active_handler() #17 {main}

**Comment by aaronschachter** [comment]
On staging, this is happening after creating a ticket, which I imagine must be the same errors on production.  Something possibly up with the `ds build` and Zendesk library?

Warning: fopen({): failed to open stream: No such file or directory in Zendesk\API\Http::send() (line 49 of /var/www/beta.dosomething.org/releases/20140509181648/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
Warning: filesize(): stat failed for { in Zendesk\API\Http::send() (line 50 of /var/www/beta.dosomething.org/releases/20140509181648/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
Warning: fread() expects parameter 1 to be resource, boolean given in Zendesk\API\Http::send() (line 51 of /var/www/beta.dosomething.org/releases/20140509181648/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
Warning: curl_setopt(): supplied argument is not a valid File-Handle resource in Zendesk\API\Http::send() (line 53 of /var/www/beta.dosomething.org/releases/20140509181648/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).

**Comment by aaronschachter** [comment]
Navigating to /var/www/beta.dosomething.org/current/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API on staging, and there is a Http.php

The Http.php file does exist here: /var/www/beta.dosomething.org/releases/20140509181648/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API
and upon opening it up I definitely see a `send()` function... :(

**Comment by angaither** [comment]
I'm seeing this error locally, and I have the files, and the `send()` function as well.

**Comment by aaronschachter** [comment]
Good investigative work by @angaither points to https://github.com/zendesk/zendesk_api_client_php/pull/12/files as a possibility for failure. Going to attempt to revert locally to a commit before https://github.com/DoSomething/dosomething/pull/2033 to see if that still breaks with the latest Zendesk PHP library.

**Comment by aaronschachter** [comment]
I've reverted back to commit 5f3a95767f46315e8c6889d81e1da5950667afc9 and can still replicate the errors:

```
Warning: fopen({): failed to open stream: No such file or directory in Zendesk\API\Http::send() (line 49 of /vagrant/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
Warning: filesize(): stat failed for { in Zendesk\API\Http::send() (line 50 of /vagrant/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
Warning: fread() expects parameter 1 to be resource, boolean given in Zendesk\API\Http::send() (line 51 of /vagrant/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
Warning: curl_setopt(): supplied argument is not a valid File-Handle resource in Zendesk\API\Http::send() (line 53 of /vagrant/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Http.php).
```

The good news is that it doesn't seem to be caused by the Zendesk code introduced for Grouped Campaigns  in #2033 but the very bad news is that it does seem to point to changes/bugs in the Zendesk PHP library.

**Comment by angaither** [comment]
I tried checking out a commit https://github.com/zendesk/zendesk_api_client_php/commit/6aa9662fb1ed45b6bcc93ef9e1e4ab14685e80ac to see if that fixed the error, but it didn't, but perhaps there is an extra step I'm missing when you use composer.

**Comment by aaronschachter** [comment]
Kellie reports that Zendesk tickets stopped being submitted at Monday, May 5 at 2:59 pm. This corresponds to commits happening on May 5 in the Zendesk repo: https://github.com/zendesk/zendesk_api_client_php/commits/master

The last commits before May 5 were April 18.

I am able to fix this locally by checkout to that commit before May 5, https://github.com/zendesk/zendesk_api_client_php/commit/6aa9662fb1ed45b6bcc93ef9e1e4ab14685e80ac.  Here are the steps:
- Navigate to `/vagrant/html/profiles/dosomething/libraries`
- Kill the existing Zendesk library: `rm -rf zendesk`
- Clone the Zendesk repo: `git clone https://github.com/zendesk/zendesk_api_client_php.git zendesk`
- `cd zendesk`
- Check out the last pre-May 5 commit: `git checkout 6aa9662fb1ed45b6bcc93ef9e1e4ab14685e80ac`
- Run `composer install`.

We could potentially run this directly on the webservers as a hotfix... @mshmsh5000 thoughts?

@angaither Do the steps above correspond to how you tested?

**Comment by angaither** [comment]
@aaronschachter those are the steps I ran locally as well, but I still get `Sorry, there was an error with your request. Please try again.` with nothing in the dblog

I think it's definitely worth trying this on stage.
We can also submit an issue to the zendesk repo.

**Comment by aaronschachter** [comment]
Good idea, will try on stage. Also drafting an issue in their repo now :hammer:

**Comment by aaronschachter** [comment]
Running `composer install` from that commit https://github.com/zendesk/zendesk_api_client_php/commit/6aa9662fb1ed45b6bcc93ef9e1e4ab14685e80ac fixes on stage.  Filed an issue in Zendesk repo: https://github.com/zendesk/zendesk_api_client_php/issues/14

**Comment by aaronschachter** [comment]
Seems like https://github.com/zendesk/zendesk_api_client_php/pull/12 fixes: https://github.com/zendesk/zendesk_api_client_php/issues/14#issuecomment-42716992

**Comment by aaronschachter** [comment]
No response from Zendesk yet, because they hate the children.  

Currently testing changes to our make file which checks out the repo from the last working commit (https://github.com/zendesk/zendesk_api_client_php/commit/6aa9662fb1ed45b6bcc93ef9e1e4ab14685e80ac), will open a PR once tested.

**Comment by aaronschachter** [comment]
The Zendesk issue I filed has been closed: https://github.com/zendesk/zendesk_api_client_php/issues/14#issuecomment-50951605

It's questionable whether or not to update our commit.  There's the good argument of "if-its-not-broke", but... potentially could provide security fixes or new functionality.

**Comment by angaither** [comment]
We could always try it on stage, it's probably better to keep things as updated as possible if we can.
That way we aren't behind when major versions come out.
