### ISSUE TITLE
Zendesk API kill switch

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2066]
We need a setting in `dosomething_zendesk` that toggles whether or not to create a ticket via API for when shit like #2064 hits the fan.

If set to not create a Zendesk API, send an email to `help@dosomething.org` to create the ticket.  

@DeeZone are we able to send just regular Drupal mail messages, or does that introduce new problems?

**Comment by aaronschachter** [comment]
This is essentially a duplicate of the first task in #1675. It may be worth looking into using Message Broker instead of implementing a queue / email backup. @DeeZone Let's connect on what would be needed to make this happen, and how I could potentially jump on the MBP side to help.

**Comment by deezone** [comment]
@aaronschachter 

I assume this is the issue:

> If Zendesk authentication fails, backlog the ticket so it's not gone forever (or possibly just email it 
> to help@dosomething.org instead of keeping a backlog... but probably safer to keep a backlog 
> in case zendesk just freaks out on us)

What type of functionality are you looking for? Perhaps on "Zendesk authentication failure" a queue entry could be created Message Broker that could then be "consumed". The consumer can do anything you like with the queue entry including sending email, logging and talking to the Zendesk API.

Anytime that works for you to discuss this further is good for me.

**Comment by aaronschachter** [comment]
Closing this, as the long term plan is to move Zendesk submissions into the Message Broker system (https://github.com/DoSomething/dosomething/issues/1675)
