### ISSUE TITLE
George automatically creating minor releases

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2067]
@desmondmorris what do you think of George automatically creating a minor release when we run `george deploy beta staging` without a release specified. It'd save you having to go back to https://github.com/DoSomething/dosomething/releases to figure out what the next release is to set. 

Workflow:
1. `george deploy beta staging`
2. George creates a new minor release. 
3. George deploys to staging.

**Comment by DFurnes** [comment]
Another suggestion might be to allow "incrementor" selectors like `george version patch` or `george version minor` to increment to the next relevant semver version. That's how we've been handling things on the Neue side.

**Comment by angaither** [comment]
+1 @DFurnes

**Comment by desmondmorris** [comment]
Cool +1.  This will require a way to ping GH for the current release version, which is doable.  Then I suggest just adding to the current release logic:

`george release major|minor|patch`

AND then we can add a release flag to the deploy script:

`george deploy --release=major|minor|path|X.X.X` - Where patch would be the default

**Comment by angaither** [comment]
@sheyd @DFurnes what do we think about this :older_man: guy?

**Comment by DFurnes** [comment]
Should definitely still try to do it. We have the `george version` stuff hooked up to get the latest tag, so running that through something like [node-semver](https://github.com/npm/node-semver) to automatically increment that value for the new release should be pretty easy!

**Comment by angaither** [comment]
this is sorta different in gerogieboi meow.
