### ISSUE TITLE
[QA] Varnish not getting cleared properly?

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2072]
On QA environment, Varnish is not getting cleared properly, so a bunch of the front-end work that needs to get tested can't, because the changes don't take effect even though the correct files have been pushed to QA.

**Comment by mshmsh5000** [comment]
@weerd Working on this here: https://github.com/DoSomething/ServerConfig/issues/16

**Comment by mshmsh5000** [comment]
@weerd The Varnish config issue is closed. Please take a look in QA and reopen if you see problems. Thanks!
