### ISSUE TITLE
Can't request new password due to default styles

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2075]
![image](https://cloud.githubusercontent.com/assets/692762/2947798/b2a89c76-d9fa-11e3-98ea-039642553720.png)

@DFurnes any chance you could bust something quick in for this before deploy? :dash:

**Comment by aaronschachter** [comment]
This is essentially a duplicate issue of https://github.com/DoSomething/dosomething/issues/1706.. would be great to fix sitewide.

**Comment by barryclark** [comment]
@aaronschachter Fix sitewide is going to be a much bigger job, it's at the top of our backlog. We need to get a fix out for this instance of the problem immediately.
