### ISSUE TITLE
Sign Up transactional emails don't receive the needed merge_vars

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#2081]
`FNAME`, `CAMPAIGN_TITLE`, and `CAMPAIGN_LINK` are getting lost before the payload is sent through to the message broker.

The offending code looks like it's here (dosomething_mbp.module):

```
case 'campaign_signup':
      dosomething_mbp_get_common_campaign_payload($payload, $params);
      $payload['merge_vars'] = array(
        'CALL_TO_ACTION' => $params['call_to_action'],
        'STEP_ONE' => $params['step_one'],
        'STEP_TWO' => $params['step_two'],
        'STEP_THREE' => $params['step_three'],
      );
      break;

    case 'group_campaign_signup':
      dosomething_mbp_get_common_campaign_payload($payload, $params);
      $payload['merge_vars'] = array(
        'CAMPAIGN_COPY' => $params['transactional_email_copy'],
      );
      break;
```

When you're doing `$payload['merge_vars'] = array(...`, you're losing the values set when you passed the reference to `$payload` through to `dosomething_mbp_get_common_campaign_payload()`. Either return `$payload` from the function instead of passing by reference or do...

```
$payload['merge_vars']['CALL_TO_ACTION'] = $params['call_to_action'];
... etc...
```

cc: @mikefantini, @DeeZone

**Comment by deezone** [comment]
@jonuy Bingo! :fireworks: I'll get a fix in later tonight and restore the template related to campaing_signups. This was a regression introduced when I broke the code up for `group_campaign_signup`.

**Comment by mikefantini** [comment]
@DeeZone let's hold off on changing the template itself until we can deploy to production tomorrow so that our hack (changing the template itself to remove the variables) is still in place.

**Comment by deezone** [comment]
@mikefantini Of course, after the merge of the code to fix the issue and the related deployment to production :)

**Comment by mikefantini** [comment]
@marahml this is in production now, so can you please update the template back to what it was and re-test?

**Comment by marahml** [comment]
tested! first name and campaign is working and template is edited.
