### ISSUE TITLE
[Campaign Template] - 404'd when submit report back on "new" campaigns

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2084]
report back goes through on the backend, but the user is presented with a 404 message on the legacy app after submitting a report back.

this happens for more recently published campaigns (like Oppression Monopoly [nid 42] and Kickball for All [nid 886]) but not for some of the original campaigns (Comeback Clothes [nid 362]).

Since the campaigns team is publishing campaigns on a regular basis we should make sure there is a scaleable solution in place moving forward in addition to fixing this particular issue.

**Comment by mshmsh5000** [comment]
Fixed in [ServerConfig v1.0.5](https://github.com/DoSomething/ServerConfig/blob/v1.0.5/varnish/pools.vcl).
