### ISSUE TITLE
DS MBP setting for campaign cache

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2085]
@DeeZone Not sure if this taken care of or not, feel free to close if so.

Ideally the `hook_node_insert` and `hook_node_update` functions which update the message broker's campaign cache should only execute if a variable is set to TRUE.  

The variable should only be set to TRUE on production, whereas making content changes on QA or Staging should not alter any MBP campaign cache (the variable would be set to FALSE)

---
- [x] Add Admin interface path
- [x] Add checkbox admin setting to manage campaign_caching setting. This will only be enabled on the production site to avoid caching campaign settings created / edited on non-production sites.
- [x] Add check for setting in `dosomething_mbp_request()` to control sending campaign caching request to `message_broker_producer_request()`.

**Comment by deezone** [comment]
@aaronschachter This is a fantastic suggestion that I was not aware of until you poked me. The Message Broker consumer functionality related to this issue still needs to be completed. I'll try to get to this later this week when I wrap up work on the consumer for the Digest functionality.

**Comment by deezone** [comment]
@aaronschachter Is there an existing variable to check to test for production or should I be looking at the URL with `basename($_SERVER['REQUEST_URI'])`?

**Comment by aaronschachter** [comment]
There is not an existing variable right now, although this question is a bit similar to desired functionality in #1889, which @desmondmorris was asking about today. Checking the URL would work fine for DS purposes but not so much for international, although I don't know whether or not we're using Message Broker for international. @desmondmorris any thoughts?

**Comment by aaronschachter** [comment]
Actually I'm thinking that there would just be an on/off variable in `dosomething_mbp` that would control whether or not to send the cache requests.  That way you can turn this off until the related consumer functoinality is built, but also just simply check on/off and don't need to check any URLs.

**Comment by aaronschachter** [comment]
The variable would only be set to TRUE on production, and just be stored in the database, like how we store 3rd party module login credentials.
