### ISSUE TITLE
[Grouped Campaigns] needs to show up in finder results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2095]
Not sure if this is set up or not yet (can't test because home page is not up and /campaigns is only showing two campaigns on staging), but we need to make sure that Grouped Campaigns appear in the finder and on /campaigns.

Also need to make sure that content type (i.e. whether they are a grouped campaign or a campaign) doesn't affect where they are prioritized in the listing.

I think the best rule to handle whether we show the grouped campaign in the finder or not is a check box on the node itself. But open to other suggestions.

Assigning this over to you @aaronschachter.

cc: @blisteringherb

**Comment by barryclark** [comment]
@blisteringherb It'd be best for you to tackle this one when you're back in on Tuesday. cc @mikefantini

**Comment by mikefantini** [comment]
sounds good. we should make sure to get this in early so we can test it out properly next week, since it's definitely an important thing campaigns team is going to be watching out for.

also, not sure how the home node works, but I assume Deluca will want to put this grouped campaign on the home page, so we should make sure that's available

cc: @angaither?

**Comment by aaronschachter** [comment]
Re-deployed to stage with #2297, indexed all content (no remaining items, and no entity metadata wrapper errors) but the node (http://staging.beta.dosomething.org/node/1194/)  is not displayed when selecting  filters like "Donate Something", "Animals" or "2 hours" . 

I've double checked that it's published.

The DoSomething Search feature is overridden and I'm not sure if reverting will fix.  I suppose I can try, but  @blisteringherb  why is it overridden?  There are a bunch of field biases that show in default that don't appear in the overrrides: http://staging.beta.dosomething.org/admin/structure/features/dosomething_search/diff

**Comment by mikefantini** [comment]
confirmed!
