### ISSUE TITLE
DoSomething Search documentation / installation steps

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2096]
We need documentation on: 
- how to set up solr locally (assuming this goes in tech wiki)
- how to do things like adding content types or changing biases so any dev can jump in on issues like #2095.

The tech wiki stuff looks like solr for the legacy app.  I'm moving these pages into Retired Content.

**Comment by aaronschachter** [comment]
@blisteringherb -- This is still an open issue as we could use some documentation for local setup, so other devs can jump in when needed.  Changing priority to label to "low" though.

**Comment by blisteringherb** [comment]
Since search is automatically included in the developer setup, the docs for how Solr works apply to the developer setup.
