### ISSUE TITLE
Reportback form filename color

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2101]
The gray color on the purple makes it unreadable. There's a filename underneath that "Change Pic" button.

![screen shot 2014-05-13 at 10 31 19 am](https://cloud.githubusercontent.com/assets/1236811/2962380/252deb04-dad0-11e3-8bee-b53c86ade398.png)

**Comment by DFurnes** [comment]
@aaronschachter Is this happening on your local or on stage/production? If local, have you run a `ds grunt` from within your Vagrant box lately?

**Comment by aaronschachter** [comment]
This was happening on staging.  I just checked out production... on first page load, the styles weren't up to date at all.  On another refresh on production, it looks nice though.  

![screen shot 2014-05-13 at 2 56 29 pm](https://cloud.githubusercontent.com/assets/1236811/2964713/9c4a6280-dae9-11e3-96f4-5b8440f96bc6.png)

Close?

**Comment by DFurnes** [comment]
Bah, that's crummy. I think this is the same caching issue we're seeing elsewhere.
Closing since refreshing fixed it. See #1841.
