### ISSUE TITLE
[Campaign] Adjust  "Submit" button size on Pitch page

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2105]
Maybe switch from large to medium?

![screen shot 2014-05-13 at 3 25 48 pm](https://cloud.githubusercontent.com/assets/105849/2962838/c2f9c4ee-dad4-11e3-8109-d2aa227476e2.png)

**Comment by weerd** [comment]
@crystalruthbell @mikefantini

**Comment by mikefantini** [comment]
yeah I mean the big thing here is that submit button on the pitch page is a different size for a logged out user vs. a logged in user.

regardless of which size we decide to go with, these should be the same.

Let's figure out what direction we want to go and make it consistent.

And then let's keep @Bladt updated when it's pushed to make sure that our decision doesn't negatively affect conversion (I don't think it will, but as a best practice, when major changes are made to a major conversion point, we should flag it for data to make sure conversion rate isn't affected).

**Comment by barryclark** [comment]
We previous decided that .large doesn't exist any more @weerd. We should stick with that for consistency.

**Comment by weerd** [comment]
Cool. Yeah, I can change it. I don't think I touched the button size that was there before. Does that mean that `medium` is the new `large`? Maybe change in Neue? Not sure how much of an overhaul it would be. @DFurnes wanna weigh in?

**Comment by Bladt** [comment]
@mikefantini thanks for the heads up - I don't anticipating this moving conv rates, but will keep my eyes open for any changes

**Comment by aaronschachter** [comment]
@weerd Not sure if this is relevant, or if you're already aware, but just chiming in to note that when you're logged out: the Signup button is not rendered as form, but a link (which opens up the login modal).  When you're logged in already, it's rendered as form.

**Comment by DFurnes** [comment]
Currently, `.medium` is the "default" size for [all buttons](http://neue.dosomething.org/#forms), and `.small` and `.large` override that if set. That makes sense to me, but I'm open to considering changing that default.

@barryclark I know we decided that we were going to use `.medium` on all forms, but are we deciding that `.large` is banned everywhere? If so, we should remove the class from Neue. I think it makes sense to have a bigger button though for primary CTAs.

**Comment by DFurnes** [comment]
@weerd Just noticed we should update `.btn` to use the new modifier class naming scheme though. Worth doing a pass over all of Neue at some point when we have enough downtime.

**Comment by barryclark** [comment]
I thought we decided never to use .large. Even for primary CTAs. @weerd please loop back around with @crystalruthbell on this to double check.

**Comment by crystalruthbell** [comment]
@dfurnes you can remove from neue if you like. Im not sure if it's "Banned" per se but I don't see us using it for anything we have built so far. .medium as our default please!

**Comment by weerd** [comment]
Cooooool! Ok, so all signup buttons now default to medium size :)

**Comment by barryclark** [comment]
Crushing the last issues today @weerd! :speedboat:
