### ISSUE TITLE
Update remaining FAQ modals to use new modal code

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#2109]
See: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_helpers/modal-links.tpl.php

**Comment by aaronschachter** [comment]
Is this what's causing the modals to break on http://staging.beta.dosomething.org/content/hunt# ? this would mean modals will also break on campaigns if we push.  bumping this up to high priority.

**Comment by DFurnes** [comment]
I think that PR should fix it. Waiting to pull down staging DB/files so I can test it against a campaign group though.
