### ISSUE TITLE
[search] - searching on a page on the legacy app just takes you to /search/site#

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2121]
ex: https://www.dosomething.org/tipsandtools/info-animal-cruelty

Then if you try to search for something while on /search/site# it again doesn't work and takes you to /search/apachesolr_search. Finally if you try to search on that page, it works and takes you to /search/apachesolr_search/bullying (for example).

Ideally when searching for a term on a legacy page it would take you to /search/apachesolr_search/[term](i.e. I search for bullying when on https://www.dosomething.org/tipsandtools/info-animal/cruelty, it should take me to /search/apachesolr_search/bullying).

**Comment by barryclark** [comment]
@blisteringherb  around for any thoughts on this one?

**Comment by mikefantini** [comment]
closing this since we're killing legacy soon anyways..
