### ISSUE TITLE
[Signup Data Form] - changes to Old People Copy doesn't work

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2125]
Trying to change the copy in Old People Copy on staging. It let's me change it and save, but it doesn't save my changes.

Changes to other fields are saving properly.

![image](https://cloud.githubusercontent.com/assets/6330971/2977124/e46930f0-dba7-11e3-8e07-f2d31bd5ebc3.png)

**Comment by aaronschachter** [comment]
This is an easy fix, on it.
