### ISSUE TITLE
Custom form for The Hunt MGC

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2144]
For The Hunt, we're allowing users to submit their MGC ideas to the campaigns team. After concerns about the Wufoo route not looking good enough visually we decided to go the embedded Google Form route instead.

Handing this over to you @DFurnes to take care of next week. Here are the steps:
- [x] Awaiting @aaronschachter completing #2142 which will give a place to embed the form. 
- [x] Alyssa and SPG will finalize the form content by Tuesday, then you can rip the form markup out and dump it into the node Aaron creates. (guide here: http://morning.am/tutorials/how-to-style-google-forms)
- [x] Neuify and fix up any visual bugs (floats on labels are causing problems right now)
- [x] Put it in redirect (e.g. http://stackoverflow.com/questions/17880977/html-form-redirect-after-submit ?) to send the user to /campaigns/hunt after completing. 
- [x] If possible, add in a thankyou confirmation message after the redirect.

**Comment by aaronschachter** [comment]
Ready for fending, @DFurnes.  `camapigns/hunt/campaign-form`.  Template lives in `templates/campaign/` directory.

**Comment by crystalruthbell** [comment]
@barryclark @DFurnes please let me know when this is ready for design QA.

**Comment by DFurnes** [comment]
@barryclark Is there a link to the finalized form content?

**Comment by barryclark** [comment]
@DFurnes Ya, it's in an emailed titled "Final Hunt Form Content!" that you're on. Pasting in here too... 

This form should have the most updated copy: https://docs.google.com/a/dosomething.org/forms/d/1PjmkallseEPvmmrJuEyEIgOWTlGThg1ylzxgPZloXfU/edit

The only PDFs need to go in the text highlighted below. Let me know if you'd prefer this on Trello, happy to move it there.
(Right under the form title): Please fill out the following questions by FRIDAY, JUNE 20TH if you are interested in submitting a campaign for The Hunt 2014! If you have any questions, please email hunt@dosomething.org. Read this document (should link to Hunt Submission Rules doc) before submitting. CAMPAIGNS MUST MEET THESE REQUIREMENTS TO BE ELIGIBLE.
(Under the "What type of campaign are you creating?" question): If your call to action has more than one campaign type, choose the one that is most relevant. E.g if your campaign is an event (host an event) where people donate a piece of clothing as admission (donate an item), choose host an event. See descriptions of all campaign type options here (should link to the campaign_types doc).

**Comment by DFurnes** [comment]
Oh hah, I see that now. :dancer:

**Comment by DFurnes** [comment]
@barryclark If we put in a custom redirect on submit, we won't be able to show the user any form errors from Google for required fields. Is this okay?

**Comment by DFurnes** [comment]
Closing, should be all good now!

**Comment by barryclark** [comment]
For reference it's living at /volunteer/hunt/campaign-form
