### ISSUE TITLE
[Campaign Template] - new report back question for TW

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2153]
Campaigns team wants to ask "Who did you share your Thumb Socks with and how did it go?" on Thumb Wars.

your call @aaronschachter if we want to handle this like we did Comeback Clothes or if we want to build it so they can add an additional question.

**Comment by aaronschachter** [comment]
The functionality for "Comeback Clothes" allows you to add 1 additional reportback form element on the reportback form, and right now it only allows for radios.  We can expand this functionality to allow an editor to select radios or textarea as the additional reportback form question.

**Comment by mikefantini** [comment]
cool let's do that.. do editors need a dev to enter "field name"

**Comment by aaronschachter** [comment]
Yeah that would be best. Do we have a node on production now?

**Comment by mikefantini** [comment]
@aaronschachter https://beta.dosomething.org/campaigns/thumb-wars

**Comment by aaronschachter** [comment]
This has been added to production. Editors can edit the form label via https://beta.dosomething.org/node/1508/custom-settings
