### ISSUE TITLE
DS Campaign: Move query functions into inc file

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2155]
Open to discussion, but there are so many campaign query type functions in the `dosomething_campaign.module`. Thinking of adding a file like `dosomething_campaign.query.inc` or a similar name, to house all these functions here:
- [ ] `_dosomething_campaign_get_recommended_base_query`
- [ ] `_dosomething_campaign_get_recommended_query_nids`
- [ ] `dosomething_campaign_get_recommended_published_nids`
- [ ] `dosomething_campaign_get_recommended_staff_pick_nids`
- [ ] `dosomething_campaign_get_recommended_nids_by_term`
- [ ] `dosomething_campaign_get_recommended_campaign_nids`
- [ ] `dosomething_campaign_get_staff_picks`
- [ ] `dosomething_campaign_get_scholarships`

**Comment by angaither** [comment]
@weerd did this with reportbacks, it's much cleaner
