### ISSUE TITLE
[Campaigns] Bug in modal display logic

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2157]
Campaign template is checking for `if isset($psa)` to determine whether or not to `print $modals`.. but the other modals for partners or FAQ should not be depending on the `$psa` variable.

There is a relevant TODO listed here https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/campaign/node--campaign.tpl.php#L64 so not sure if issue exists for this already. Also not sure what it means to DRY it up.

**Comment by aaronschachter** [comment]
Ok, I get it now. It checks for the `$psa` variable to determine which column to output the modal links. 

As far as the TODO comment and DRYing it up... it seems relevant to keep this issue open. Ideally we should make the "Know it" section its own themeable function, to share this code between the Campaign Action Page and the SMS Game.  Thoughts, @barryclark ?

**Comment by barryclark** [comment]
@weerd to look at this one when he starts tackling SMS theming

**Comment by aaronschachter** [comment]
@weerd Any thoughts on whether or not to make the "Know it" section its own themeable function? Since this issue, there's been comments in the Campaign template that describe the logic, but the comments don't exist in the SMS template.  Ideally both would share the same code, no?

**Comment by angaither** [comment]
@weerd is this still something we need to look into?

**Comment by weerd** [comment]
:shrug: gonna close and if it comes back we can reopen or create another issue.
