### ISSUE TITLE
[Campaign Template] - on mobile, the Sprint link results in error page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2161]
@barryclark I'm not sure if there is anything we can do about this, but the the link for Sprint in the "In partnership with" section at the bottom of the page takes you to a page that does not exist on mobile because it tries to take you to http://m.sprint.com/drive?INTNAV=FS:HP:Redirect. It works properly on desktop.

Made high priority because it's with sponsor link, but it seems like we may need to ask them for a different link. Just wanted to get your thoughts before kicking it back to the sponsor. Other alternative is to not link to them at all, which I can talk to campaigns team about.

Let me know what you think.

![photo 18](https://cloud.githubusercontent.com/assets/6330971/2997662/ef237860-dd01-11e3-9b7e-e18de43dc00f.PNG)

**Comment by mikefantini** [comment]
trello card here: https://trello.com/c/WeRu6d62

**Comment by mikefantini** [comment]
@barryclark can you chat with Aaron B directly about this tomorrow if we do need a new link from the sponsor?

**Comment by barryclark** [comment]
@mikefantini Tested on my iPhone and works fine for me! @DFurnes Could you give it a quick try too plz?

**Comment by mikefantini** [comment]
@barryclark I saw the issue on my iphone 5 using safari app and whatever Android/browser Bladt has.

**Comment by barryclark** [comment]
Hmm, it's maybe in the redirect... gonna do a bit more testing.

**Comment by barryclark** [comment]
Linking directly to http://www.sprint.com/landings/focusondriving/ would resolve this. Sprint might have tracking on the original http://www.sprint.com/drive link though. I'll speak to Aaron B about it just now.

**Comment by barryclark** [comment]
Aaron B is going to resolve this with Sprint just now. I'm leaving this open for us to close when we see it actually fixed on staging/prod.

**Comment by mikefantini** [comment]
worked on my iphone 5 this time. @Bladt can you test on your Android and confirm?

**Comment by Bladt** [comment]
@mikefantini worked on my Nexus 5

**Comment by mikefantini** [comment]
cool thanks.. closing this out now
