### ISSUE TITLE
[Campaign Template] - Unable to upload report back photon on Android 4.4.2 KitKat

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2165]
When you are using the stock built in web browser that comes with android 4.4.2, you are unable to upload a picture for the thumb sock campaign. Instead of Android popping up with the system's default file picker, nothing happens. If you tap and hold the icon and then chose to go to the link, you start loading a bogus page indefinitely.

This issue only works with the browser that comes by default with android and not other android browsers that you can download from the Play Store such as "Chrome", "Firefox", "Opera Mini" or "Dolphin Browser". This just may be a specific browser related issue, but it should still be looked at carefully.

**Comment by mikefantini** [comment]
https://trello.com/c/6ojw1EQW

**Comment by barryclark** [comment]
@DFurnes

**Comment by DFurnes** [comment]
Tested on stock browser Android 4.1 through BrowserStack and this is functional now. I was unable to test Android 4.4.2 since that is not available on BrowserStack. I believe this was fixed by #2436.
