### ISSUE TITLE
[Nav] all sorts of whack on iOS

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2166]
search bar and log out appear to be fixed at the bottom and cover Explore Campaigns/What is DoSomething.org

https://mail.google.com/mail/u/0/?ui=2&ik=4cc3e6e3b6&view=att&th=1460591325e4a8d7&attid=0.1&disp=safe&zw

https://mail.google.com/mail/u/0/?ui=2&ik=4cc3e6e3b6&view=att&th=1460591325e4a8d7&attid=0.3&disp=safe&zw

https://mail.google.com/mail/u/0/?ui=2&ik=4cc3e6e3b6&view=att&th=1460591325e4a8d7&attid=0.5&disp=safe&zw

https://mail.google.com/mail/u/0/?ui=2&ik=4cc3e6e3b6&view=att&th=1460591325e4a8d7&attid=0.7&disp=safe&zw

https://mail.google.com/mail/u/0/?ui=2&ik=4cc3e6e3b6&view=att&th=1460591325e4a8d7&attid=0.9&disp=safe&zw

**Comment by mikefantini** [comment]
https://trello.com/c/PDSXOSH8

**Comment by DFurnes** [comment]
No longer an issue, closing!
