### ISSUE TITLE
Welcome Home campaign listed twice on /Campaigns

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2171]
The campaign is listing twice on our Explore Campaigns page. 

![screen shot 2014-05-16 at 1 37 37 pm](https://cloud.githubusercontent.com/assets/6550604/3000225/dc1791d8-dd20-11e3-9be5-d977eae221c6.png)

**Comment by aaronschachter** [comment]
not seeing duplicates.
