### ISSUE TITLE
[Refactor] Create new partial for Zendesk form output 

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2172]
Based on @aaronschachter comment in #2034 

"This should ideally turn into a partial that we can place anywhere. You'll notice that the code in `node--campaign.tpl.php` adds some help text. We can either add that into the `zendesk_form` constructor function, or just maintain it in a tpl if easier."

**Comment by aaronschachter** [comment]
Hey @weerd I beat you by two issues on this one #2169.  Was thinking there that perhaps we could just store the help text in a variable in order to change it without any code deployments...

**Comment by DFurnes** [comment]
This was fixed in #2169. Closing.
