### ISSUE TITLE
Move some dosomething_sms workflows into separate ds-mdata-responder tool

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#2179]
Comeback Clothes has the start-campaign transition and tip delivery in `dosomething_sms.workflows.inc`. Let's take it out of there and move it to the `ds-mdata-responder` tool.
- [ ] add to ds-mdata-responder
- [ ] remove from dosomething_sms.workflows.inc
- [ ] update mData settings on Mobile Commons

**Comment by angaither** [comment]
omg this is the most done thing that's never been closed

**Comment by jonuy** [comment]
Whoa whoa whoa, this is still on my todo list
