### ISSUE TITLE
Report back rejects submissions with spaces

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2181]
Users are submitting report back impact numbers with a space before or after the number and it is rejecting their submission. EX: "5 " or " 11"

Definite usability issue because a user can not see their error. 

You can see the issue at the very end of this video (and I recreated to verify it was happening): 
**Removed user feedback video URL - Barry**

Recommendation is accept entry and remove spacing when recording in database.

**Comment by angaither** [comment]
we should be able to use `trim()` and remove those spaces before validating the number

**Comment by angaither** [comment]
@sbsmith86 mind knocking this one out?
