### ISSUE TITLE
[campaign template] can't remove signup as admin

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2201]
as an admin on http://staging.beta.dosomething.org/node/1173/unsignup the "DELETE" button is inactive and doesn't work.

![image](https://cloud.githubusercontent.com/assets/6330971/3018223/31644438-df83-11e3-9cfa-bbf701271b09.png)

**Comment by aaronschachter** [comment]
Assigning to @barryclark to triage, this is a front end task.

**Comment by barryclark** [comment]
Yeeeeep, same problem as a lot of this. We need to get to this soon.

**Comment by aaronschachter** [comment]
Not sure where the fender commit which fixed, but this is now resolved.

![screen shot 2014-05-23 at 11 21 42 am](https://cloud.githubusercontent.com/assets/1236811/3068413/29823e38-e28e-11e3-9439-50f6bc8152c6.png)
