### ISSUE TITLE
[signup data] don't ask user to confirm SUPER nit picky issues

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2203]
Super low priority but want to document it. It would be great if we could avoid asking people to fix super small issues like the ones documented below and just fix them on our end:

![image](https://cloud.githubusercontent.com/assets/6330971/3018368/a12a179c-df84-11e3-8939-7224a8dba674.png)

@DFurnes did you say you started a list of things to ask to confirm vs. just fixing without asking?

I'd rather be safe and ask them to confirm for now then just accepting shit on our own and not having them confirm but there are definitely some instances we should feel safe making the assumption.

**Comment by DFurnes** [comment]
Totally. Right now, we're automatically fixing capitalization (UPS wants everything all-caps) and zipcodes (as long as the first 5 digits match, we just silently add the +4). I'm in favor of doing more, but eventually we're going to have a lot of rules for a lot of special cases. It's a shame the UPS API doesn't give some sort of indicator of "how much" of a correction it made.

**Comment by mikefantini** [comment]
ok cool... like i said low priority and if it's a too much of a pain it's not a _terrible_ experience... we can touch base some time this week but yeah don't want to just go down a rabbit hole either.

**Comment by DFurnes** [comment]
UPS returns an `"ambiguous"` flag when it isn't certain about the corrections it is making. If we're okay with it doing some more "aggressive" corrections without prompting the user, then we can definitely cut down the number of prompts.

**Comment by barryclark** [comment]
Closing this one as there's not really much we can do here. But opened #2226 which would help resolve this UX issue.
