### ISSUE TITLE
SMS Reportback: Reportback extra data for Thumb Wars

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2210]
Refs #2153 

Need to set a `$reportback->tw_shared_with` property in order to save the custom question.  

Question text is currently set to "Who did you share your Thumb Socks with and how did it go?".  This text can be found dynamically by querying the `dosomething_reportback_field` table for the TW nid, 1508.

**Comment by aaronschachter** [comment]
@jonuy @mikefantini This is an old one... and Thumb Wars has been live for a while now. Close?

**Comment by mikefantini** [comment]
@jonuy can you confirm that reports work over mobile without this?

**Comment by jonuy** [comment]
@aaronschachter @mikefantini Tested just now. On SMS it's still just asking for how many you shared with and why. Report back went through successfully and I verified it showed up on our backed. If we're cool with still just asking that instead of "who did you share with, etc", then we're good.

**Comment by mikefantini** [comment]
@jonuy estimate on how long it would take to add this in?

**Comment by jonuy** [comment]
@mikefantini Probably a day.

@marahml ^^^

**Comment by aaronschachter** [comment]
We are no longer supporting custom fields in Reportbacks.
