### ISSUE TITLE
Remove DS User email variables

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2218]
International sites will use Drupal's default email for Welcome/Registration and Password reset emails for the time being.

Remove the definitions of the `user_mail_register_no_approval_required_notify` and `user_mail_password_reset_notify` variables from the `dosomething_user` feature, to prevent these settings from being altered when reverting features.

Related Trello card: https://trello.com/c/MfJ6y30L

**Comment by barryclark** [comment]
Moved to Jira, closing. https://jira.dosomething.org/browse/DS-214
