### ISSUE TITLE
[International] Revisit dosomething.info module dependencies

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2219]
International uses the same `ds build` script that we use for the main app to deploy. This means that if you want to turn off a module like Message Broker, it's going to be enabled upon every deploy.

We can either 

a) Remove the code from `ds build` which scans for any modules listed which are not enabled, and enables them

or 

b) Remove non "core" DS modules from `dosomething.info` that would not be used on the international platform

Listing out modules should not be turned on for international:

Contrib:
- [ ] message_broker_producer

Custom:
- [ ] dosomething_mbp
- [ ] dosomething_zendesk

@angaither @desmondmorris What are your thoughts on which route to go?

**Comment by angaither** [comment]
I would prefer to treat is in a multi-site-esque way, where we have a file for things needed in every app and another file that is specific to our app.

I've gone this route before, using a `ds.modulefile` or a `uk.modulefile` before and listed out all the modules needed for that install with a status of 0 or 1

**Comment by angaither** [comment]
we can safely close this out, since we are moving to one site eventually, we probably don't need to invest time in this.
