### ISSUE TITLE
Fix misconfigured helper/home modules in make file

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#2221]
https://github.com/DoSomething/dosomething/blob/dev/lib/profiles/dosomething/dosomething.make#L39-L49

**Comment by aaronschachter** [comment]
Fixed by https://github.com/DoSomething/dosomething/commit/da245d19280919f806fae2e0ad700a351fa52f67#diff-4853f3bfe84346585812ac00c3a356e3
