### ISSUE TITLE
Campaign Finder feature flag should only toggle Finder UI

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#2224]
Right now, we're toggling between the old homepage design and the "new" homepage design with the Campaign Finder feature flag. This should _only_ toggle the Finder UI now that we're rendering homepage elements from the Home node. We can also get rid of all the old SCSS.

**Comment by desmondmorris** [comment]
Is it safe to say all of this will and can be deprecated: https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/home/node--home.tpl.php#L109-L180

cc: @DFurnes

**Comment by DFurnes** [comment]
Yup, we can also get rid of the old homepage styles in https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/scss/content/_homepage.scss
