### ISSUE TITLE
Address collection validation flow - rework to be 2 step process

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2226]
Related to #2203. It sucks for the user to have to correct each field individually like this. It might be better to go to more of an e-commerce style flow, where the user is prompted with the address that we've matched in our DB afterwards, and asked if they'd like to update it. 

Kind of like a confirmation screen after they've filled out their address... just asking to accept that the address we found (in our format) is correct. 

cc @mikefantini

**Comment by barryclark** [comment]
Potentially leave this until after Thumb Wars?

**Comment by angaither** [comment]
closing, this isn't possible with the UPS api
