### ISSUE TITLE
Vanity URL - Legacy redirects

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#2230]
Updated:
In order to have a vanity URL (e.g. dosomething.org/boss), we create a redirect within legacy and then usually there's some complications with varnish and it not working for anon users, etc.  Once we kill legacy, this is not an issue anymore.

Original desc:
We should probably be able to do this....

**Comment by aaronschachter** [comment]
@angaither what is this issue for?

**Comment by aaronschachter** [comment]
Updated description. Going thru the confusion for the 5th Harmony campaign definitely reminded me of where this issue came from. Once we RIP Legacy, this should no longer be needed.
