### ISSUE TITLE
[Grouped Campaigns] Pathauto pattern

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2232]
Export pathauto pattern to `dosomething_campaign_group`

**Comment by aaronschachter** [comment]
@barryclark Please update issue with the desired pattern and assign.

**Comment by barryclark** [comment]
? Not sure what this means @aaronschachter

**Comment by aaronschachter** [comment]
We talked yesterday about having default URL patterns be something like `volunteer/[node-title]`

**Comment by barryclark** [comment]
@mshmsh5000 just to finalize, we're going with `/volunteer/[node-title]` for grouped campaigns URLs, right? Or was it `/volunteering/[node-title]`?

**Comment by barryclark** [comment]
Let's just set this at /campaigns/hunt @aaronschachter tyty

**Comment by mshmsh5000** [comment]
The pattern @Bladt and I suggest is 

`/volunteer/[node-title]`

I imagine we'll often override `[node-title]`, or possibly the entire URL, for sponsors.

**Comment by mshmsh5000** [comment]
v1.0.7 of Varnish config is done: `/volunteer` is routing to the beta app in production now. [Config here](https://github.com/DoSomething/ServerConfig/blob/v1.0.7/varnish/pools.vcl).
