### ISSUE TITLE
Add campaign details to dosomething_mbp_campaign_request()

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2237]
`dosomething_mbp_campaign_request()` needs access to the following node variables:
- path to image reference in edit-field-image-campaign-cover-und-0-target-id
- fact problem text referenced in edit-field-fact-problem-und-0-target-id
- fact solution text referenced in edit-field-fact-solution-und-0-target-id
- high season start date referenced in:
  - edit-field-high-season-und-0-value-month
  - edit-field-high-season-und-0-value-day
  - edit-field-high-season-und-0-value-year
- high season end date referenced in:
  - edit-field-high-season-und-0-value2-month
  - edit-field-high-season-und-0-value2-day
  - edit-field-high-season-und-0-value2-year
- low season start date referenced in:
  - edit-field-low-season-und-0-value-month
  - edit-field-low-season-und-0-value-day
  - edit-field-low-season-und-0-value-year
    -low season end date referenced in:
  - edit-field-low-season-und-0-value2-month
  - edit-field-low-season-und-0-value2-day
  - edit-field-low-season-und-0-value2-year
- report back details:
  - edit-field-reportback-noun-und-0-value
  - edit-field-reportback-verb-und-0-value
  - edit-field-reportback-copy-und-0-value
  - edit-field-reportback-confirm-msg-und-0-value

to ultimately send in $payload for a `message_broker_producer_request()`.

**Comment by deezone** [comment]
@aaronschachter Do we have a custom function to get at the node reference and / or date values? For the node reference, should I just use `node_load()` on I know the nid?

**Comment by aaronschachter** [comment]
`node_load` is fine, there are not any custom functions.

**Comment by aaronschachter** [comment]
For the image, take a look in the `dosomething_campaign.theme.inc` for `dosomething_image` functions that will return a path.
