### ISSUE TITLE
Client-side auth flow

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#224]
Original goal for client-side auth:

We include the login form on all unauthenticated pages and display it with JS when user clicks to login. Submit a single AJAX login HTTP request, and render confirmation or followup questions without reloading page.

**Comment by DFurnes** [comment]
Some thoughts from researching implementation for this:

Issue with making a HTTPS AJAX request from a unsecured page – browser security restrictions make this kinda tricky since a HTTPS request from a non-HTTPS page is considered cross-domain. We can fix this using CORS headers and XHR `withCredentials`, which has pretty good browser support but will need a fallback XDomainRequest implementation for IE8/9.

One other downside, the user doesn't get the padlock on their browser even though the request with the credentials is encrypted. Is this worth cutting a HTTP request?

**Comment by barryclark** [comment]
Assigning to @mshmsh5000 as he's looking at this.

**Comment by DFurnes** [comment]
Can close this, was related to old requirement that we authenticate people without a page refresh.
