### ISSUE TITLE
[Campaign Template] - prove it modal issues on Android 4.04

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2244]
part of the submission popup window is missing/obscured so that not all information fields are visible or accessible. The popup window cannot be moved to correct the problem.

Also, entering text (not an integer) into the "total number of socks shared" field does not result in any error message - however the information cannot be uploaded with the error in this field.

![obscured popup](https://cloud.githubusercontent.com/assets/6330971/3040366/2e4c1bc2-e0eb-11e3-8e78-f9c413b3527e.jpg)

**Comment by mikefantini** [comment]
https://trello.com/c/YfQQlC6C

**Comment by DFurnes** [comment]
This doesn't seem to be an issue any longer.
