### ISSUE TITLE
ZenDesk system info

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#2254]
Updated description:
- [x] Add Zendesk custom fields to Tickets for Browser Info, IP Address.
- [x] Submit as custom fields in Zendesk Ticket creation, using `dosomething_helpers_ip_address` and possibly PHP's `get_browser()` ?

---

Get the system info in the zenddesk tickets.

It looks like this happens with an [audit](http://developer.zendesk.com/documentation/rest_api/ticket_audits.html)

**Comment by barryclark** [comment]
cc @aaronschachter have you looked into this yet at all? It'd be awesome to have the user's system info populate in the tiicket automagically.

**Comment by aaronschachter** [comment]
Taking a look now.  According to this http://developer.zendesk.com/documentation/rest_api/tickets.html#setting-metadata, it seems like the audit would be generated upon ticket creation... just trying to find where it is to see if it's already doing that.

**Comment by aaronschachter** [comment]
Per http://developer.zendesk.com/documentation/rest_api/tickets.html#setting-metadata, it does suggest you can include audit metadata, but it seems our best bet may be adding a custom field to Tickets, and storing the browser there. That would allow us to query by tickets per browser in Zendesk's search.

**Comment by aaronschachter** [comment]
Confirmed that I'm not finding any audit info for tickets created via Web Service. Updated the issue description to find the relevant values in PHP and submit as custom fields.

**Comment by aaronschachter** [comment]
Using PHP's `get_browser()` doesn't seem to work:

Warning: get_browser(): browscap ini directive not set in eval() (line 1 of /vagrant/html/profiles/dosomething/modules/contrib/devel/devel.module(1415) : eval()'d code).

This module https://drupal.org/project/browscap seems like it could possibly provide what we're looking for... anybody use it much? @angaither @desmondmorris @mshmsh5000

**Comment by DFurnes** [comment]
It looks like `get_browser()` needs an `browscap.ini` file that maps to user agent strings. If that's not an option, even just getting the user agent from `$_SERVER['HTTP_USER_AGENT']` would be nice.

**Comment by DFurnes** [comment]
Looks like you can get updated `browscap.ini` files here: http://browscap.org

**Comment by aaronschachter** [comment]
Hmm maybe just setting up a `browser.ini` may be the easiest.  The browsercap module looks like it's been around a while but def comes with more than we're looking for.

This thread http://stackoverflow.com/questions/2257597/reliable-user-browser-detection-with-php suggests that the `$_SERVER['HTTP_USER_AGENT']` is not too reliable.

**Comment by DFurnes** [comment]
Yeah, I think `get_browser()` just maps the user agent string to a more human-readable array, but its still nicer than having to ask the user every time.

**Comment by aaronschachter** [comment]
Confirmed by James P at Zendesk that we're on our own for submitting this info to tickets when creating via API.  For now, I'm going to just send the `$_SERVER['HTTP_USER_AGENT']` now to get started and open a separate issue for adding a browscap.ini file into Vagrant.

> If the ticket is created via API, it will only display web service and the IP address of the request, as this is generated by a direct call to our API and not via browser. To get the information of the browser, you would have to capture the data yourself and send it via custom field.
> 
> I hope this makes sense, and if you have any other question, please let me know.
> 
> Sincerely,
> James P

**Comment by aaronschachter** [comment]
I've created 2 new fields via the Zendesk admin interface:

Field ID: 22583110 for Browser

Field ID: 22583120 for IP Address

**Comment by aaronschachter** [comment]
Confirmed we have user information in tickets.  This was tested from stage and will be available upon our next deploy.

![screen shot 2014-05-23 at 3 00 14 pm](https://cloud.githubusercontent.com/assets/1236811/3070689/a4b39386-e2ac-11e3-99b1-22e0893c9ad1.png)

**Comment by DFurnes** [comment]
Sweeeeeeeeet.

**Comment by barryclark** [comment]
That is awesome :sparkling_heart:

**Comment by aaronschachter** [comment]
Confirmed this is working in production as of this morning's deploy (v.0.2.65)
