### ISSUE TITLE
ds build dies on Git predis clone

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#2256]
In `/lib/profiles/dosomething/drupal-org.make`, the reference to the Git predis repo has been killing `ds build`. Changing this to an `https` URL seems to fix the problem.

**Comment by angaither** [comment]
:+1: This worked for me

**Comment by deezone** [comment]
For what it's worth, from this `git@github.com:nrk/predis.git` to this 
`libraries[predis][download][url] = "https://github.com/nrk/predis.git"`.

Works for me too :rocket:
