### ISSUE TITLE
PHP undefined index: 329195 in user_node_load

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2279]
Check out the dblog table and this is all over the place. 

Notice: Undefined index: 329195 in user_node_load() (line 3642 of /var/www/beta.dosomething.org/releases/20140522162955/html/modules/user/user.module).

**Comment by angaither** [comment]
Oh, this is totally fine.

I ran the 'update-node-authors' script on stage, which changed the author to a user that doesn't exist on stage, so that's why it's throwing that error. 
Also that's @mikefantini 
always causin trouble.

**Comment by aaronschachter** [comment]
This makes it a lot harder to debug using the dblog table, because it's flooded with these.  Can we confirm this isn't happening on production?

Also @mshmsh5000 -- thoughts on using the production database for staging at this point?  The problem here would be that the size of the users table is substantially bigger.. and not sanitized.

**Comment by angaither** [comment]
You can clear that stuff out locally by just changing node authors, set them all to uid 1.

**Comment by aaronschachter** [comment]
Locally I ran `UPDATE node SET uid = 1` and confirmed I don't see them anymore.  I've run this query on stage so it won't show up for everyone upon their next db staging pull.

**Comment by aaronschachter** [comment]
This is still happening.

**Comment by aaronschachter** [comment]
Ran `UPDATE node_revision SET uid = 1;` on stage

**Comment by aaronschachter** [comment]
Still occurs, with `node` and `node_revision` uid columns all set to 1.

**Comment by angaither** [comment]
![](http://cl.ly/image/0I3e110a3r1u/Screen%20Shot%202014-06-18%20at%2010.29.07%20AM.png)

All the node authors were still anonymous, just updated them so they were all admin. 

![](http://cl.ly/image/462j0c0M1M3T/Screen%20Shot%202014-06-18%20at%2010.30.36%20AM.png)

**Comment by aaronschachter** [comment]
Oh, I forgot I had to actually `node_save`.  Did you do this via script and saving the nodes?
