### ISSUE TITLE
[Grouped Campaigns] text wrap intro text area

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2280]
Let's have text wrap around image/video so we don't have lots of whack white space when text area is super tall vertically

![image](https://cloud.githubusercontent.com/assets/6330971/3057972/c574bc34-e1db-11e3-8eaa-243a43df87ed.png)

cc: @crystalruthbell

**Comment by barryclark** [comment]
@crystalruthbell Wouldn't look great for pages like... https://beta.dosomething.org/volunteer/hunt 

cc'ing @weerd @DFurnes for comments too :)

**Comment by DFurnes** [comment]
Yup, my fear would be having awkwardly long lines instead.

![screen shot 2014-05-23 at 11 31 40 am](https://cloud.githubusercontent.com/assets/583202/3068519/60594b9e-e28f-11e3-880b-096af211b16a.png)

**Comment by mikefantini** [comment]
@crystalruthbell @julielorch thoughts?

**Comment by DFurnes** [comment]
No longer an issue, closing! :dancers:
