### ISSUE TITLE
Light color drop on nav

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2282]
Please replicate the drop shadow effect that is in place on page titles to the nav. 

White on black nav (campaign template)

![screen shot 2014-05-22 at 2 11 29 pm](https://cloud.githubusercontent.com/assets/6550604/3058046/accae464-e1dc-11e3-82b5-fc5ba5df4d62.png)

Black on white nav (static content pages)

![screen shot 2014-05-22 at 2 12 05 pm](https://cloud.githubusercontent.com/assets/6550604/3058045/a85e2832-e1dc-11e3-9517-fbc77f57e481.png)

**Comment by weerd** [comment]
Resolved in #2360

**Comment by crystalruthbell** [comment]
Thanks @weerd its good, very subtle (maybe too subtle but user testing will tell!!)
