### ISSUE TITLE
[campaign template] do we want this space on confirmation page right above the footer?

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2299]
![image](https://cloud.githubusercontent.com/assets/6330971/3059826/54f2be10-e1f0-11e3-866c-13159ce929c2.png)

**Comment by barryclark** [comment]
@weerd looks like the grouped campaigns sponsor footer bit got added globally?

**Comment by weerd** [comment]
Noticed this last week and fixed it a few days ago. Didn't realize there was a ticket for it, haha. Lemme know if it still crops up anywhere, but should be fixed!
