### ISSUE TITLE
Vagrant: Add browscap.ini

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2306]
Refs https://github.com/DoSomething/dosomething/issues/2254#issuecomment-44034659 - Make for better browser detection when submitting tickets to Zendesk API.

**Comment by aaronschachter** [comment]
@DFurnes @barryclark This was more for a cleaner way to track the user's browser information when we submit to Zendesk.  If what we have now is sufficient, I'm happy to close this one - thoughts?

**Comment by DFurnes** [comment]
That sounds fine to me. It doesn't seem like we'll be dealing with too many tickets like this, and it's easy enough to copy and paste the User Agent string into something like http://www.useragentstring.com manually when we do.

**Comment by barryclark** [comment]
:+1:
