### ISSUE TITLE
Action page prove it section gallery arrows are non-navigable

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2307]
Perhaps we should create a wider margin around the photo so that the arrows can fit within the page? Please grab me if you are tweaking and want my insights. 

![screen shot 2014-05-23 at 2 03 32 pm](https://cloud.githubusercontent.com/assets/6550604/3070115/c0815420-e2a4-11e3-889b-1d629e0197d4.png)

**Comment by crystalruthbell** [comment]
Also, this is mobile view.

**Comment by weerd** [comment]
This will be fixed in PR #2519
