### ISSUE TITLE
Clean tags in user submission

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#2314]
Someone put a bunch of enters in and it was really sad for the CSV. We should strip_tags on this field before we save it. 
![](http://cl.ly/image/191W3B0t0K1z/Screen%20Shot%202014-05-23%20at%204.41.40%20PM.png)
- [ ] User Signup Data Form (per screenshot above)
- [ ] Reportback Form

**Comment by aaronschachter** [comment]
This one is definitely still valid. Updated issue with forms to update.

**Comment by aaronschachter** [comment]
This is problematic when a user is updating their Reportback submission. The form loads the stripped content, and then is saved with weird characters. See https://github.com/DoSomething/dosomething/pull/3716
