### ISSUE TITLE
[grouped campaigns] call to action

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2318]
Call to action is no longer appearing in the header for grouped campaigns even though the field is filled out:

![image](https://cloud.githubusercontent.com/assets/6330971/3090315/b11c63ba-e58a-11e3-90bb-c98d4a85b3e0.png)

cc: @barryclark

**Comment by weerd** [comment]
Working on it.

**Comment by weerd** [comment]
Checked on stage, CTA is back.
