### ISSUE TITLE
[Fact Page] Group Fact list by selective Cause terms

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2342]
Desired functionality for 11 Facts page archive is that they are grouped under similar terms as Finder, where some causes such as Sex and Violence are considered one term and not two.

Alter the Fact Page List block output to group by the relevant Cause headers / terms.

**Comment by barryclark** [comment]
Mind if I close this @aaronschachter? We can re-open if it gets requested, otherwise I don't think we should take action on it.

**Comment by aaronschachter** [comment]
Mind if _I_ close it?? ha ha

**Comment by barryclark** [comment]
:dancers:
