### ISSUE TITLE
Homepage - Update <title> and description meta tag for better SEO

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2343]
Update both to "America's largest organization for youth volunteering opportunities, with 2,500,000 members and counting."

Based on Jeff's research:

> "youth volunteering opportunities" is the top keyword phrase for volunteering + youth, though the more generic "volunteering opportunities" is 5x more popular. Location specific search terms (e.g. volunteer in chicago) are the most popular. "online volunteering" and "how to volunteer" are other top location-agnostic search phrases.

Reference Trello cards:
- https://trello.com/c/mVXSpQfS/1135-seo-consider-home-page-title-tag-in-light-of-target-search-keywords
- https://trello.com/c/yW3VEOuW/1134-seo-home-page-missing-meta-description

cc @mshmsh5000 @aaronschachter

**Comment by aaronschachter** [comment]
/admin/config/system/site-information

Current value for Site Title: 
`DoSomething.org | Largest organization for teens and social cause`

Updating to
`DoSomething.org | America's largest organization for youth volunteering opportunities, with 2,500,000 members and counting.`

**Comment by aaronschachter** [comment]
Edited default metatag config at `admin/config/search/metatags/config/global` to add description.

**Comment by aaronschachter** [comment]
This was done via module configuration. Purposely not exporting this stuff into features to avoid needing to deploy for changes like this.

**Comment by aaronschachter** [comment]
Umm this stuff is not present anymore.  Need to check if the `dosomething_metatags` feature is overriding this.
