### ISSUE TITLE
Fonts not loading in Firefox

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2344]
![image](https://cloud.githubusercontent.com/assets/692762/3105922/8a984a68-e677-11e3-8714-44ef80a921fc.png)

On staging and prod. Since deploying earlier today.

**Comment by barryclark** [comment]
@DFurnes helped debug this. 

@mshmsh5000 @aaronschachter The issue is because we're serving our fonts from Akamai now and Firefox doesn't like it, as it's on another domain. 

It looks like the fix is to add the following to the htaccess file: `Header set Access-Control-Allow-Origin "*"` as covered in the examples below.
- http://stackoverflow.com/questions/5008944/how-to-add-an-access-control-allow-origin-header/5009126#5009126
- http://stackoverflow.com/questions/2856502/css-font-face-not-working-with-firefox-but-working-with-chrome-and-ie

**Comment by tjrosario** [comment]
Here is the referenced solution: http://davidwalsh.name/cdn-fonts.  Related issue occuring in IE: #2347

**Comment by mshmsh5000** [comment]
![woff-ttf-cors](https://cloud.githubusercontent.com/assets/149811/3113409/2111c640-e6d7-11e3-80a5-6e44c2a634c7.png)

**Comment by mshmsh5000** [comment]
The most obvious place for us to address this is in Akamai, which is after all serving the assets.

![akamai-config](https://cloud.githubusercontent.com/assets/149811/3113541/da3003e6-e6da-11e3-899e-d2d675f88fba.png)

**Comment by mshmsh5000** [comment]
New response headers:

![new-response-headers](https://cloud.githubusercontent.com/assets/149811/3113568/949af902-e6db-11e3-84c5-0a48fa907002.png)

This was produced by the Akamai staging URL. I'm rolling these changes out to production now.

**Comment by mshmsh5000** [comment]
The updated Akamai config is almost finished propagating. Working for me in Firefox now.

![firefox-working](https://cloud.githubusercontent.com/assets/149811/3113943/eaeb28de-e6e7-11e3-8fca-d022a0648ba8.png)

**Comment by barryclark** [comment]
Awesome!

**Comment by barryclark** [comment]
Confirmed that this is fixed!

**Comment by mikefantini** [comment]
yup confirmed working for me in firefox now too

**Comment by weerd** [comment]
Relating to the IE8 bug, it's now working on Production correctly, but still borked on Staging...?
