### ISSUE TITLE
[Grouped Campaigns] Contact Us not showing up on prod

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2346]
It is showing up on staging but not on prod. It is working properly on campaigns template.

![image](https://cloud.githubusercontent.com/assets/6330971/3106363/d0fb45e8-e67a-11e3-9660-cb1628a36bac.png)

**Comment by weerd** [comment]
@mikefantini might be a bender issue. The contact us doesn't show up if there isn't a ZenDesk form associated with the page. I'm not sure where that's controlled. It's not in the CMS portion of the edit page for the campaign-group. 

@aaronschachter ^ any ideas?

**Comment by mikefantini** [comment]
@aaronschachter kicking over to you

**Comment by weerd** [comment]
@aaronschachter curious to know where that actually happens ;)

**Comment by aaronschachter** [comment]
Cleared cache. it works.
