### ISSUE TITLE
rem polyfill error breaks DS.org in IE8

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2347]
![image](https://cloud.githubusercontent.com/assets/692762/3107245/5d884a3a-e683-11e3-84c9-460f03fdbaa0.png)

via @weerd: There's an error w/ the polyfill for IE8 for rem support (rem.js). it's erroring out and blocking any proper rendering for respond.js in IE8. 

via @DFurnes: I think IE 8 issue _might_ be fixed if you take rem.js and respond.js out of excludeShallow config and remove Features.\* if statements by their respective require() calls in main.js

**Comment by weerd** [comment]
@tjrosario suggested this might be a cross-origin resource sharing issue. We tested this by turning off CDN assets on stage and IE8 works great again.

**Comment by barryclark** [comment]
Unfortunately doesn't look like this has been resolved by the #2344 fix. cc @mshmsh5000 @weerd @tjrosario @DFurnes

**Comment by weerd** [comment]
So it looks like the Rem Polyfill is no longer an issue, but for some reason respond.js is not running, which is why the site is stuck on mobile view on IE8.

**Comment by barryclark** [comment]
cc'ing @DFurnes @tjrosario on this

**Comment by DFurnes** [comment]
Waiting on a HTTP endpoint for our CDN, but this should be fixed next time we deploy on production and will be a quick setting change on staging.
