### ISSUE TITLE
[Campaign Template] - closed campaign state fields needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2348]
Just starting the list, will clean up in our meeting.

Fields needed for Campaign Closed State:
- [x] description
- [x] custom output (i.e. impact)
- [x] winners field collection #2378
- [ ] sign up call out text - TBD
- [x] Field collections. Ideally share common fields to make for an all-encompassing preprocessing function.
  - [x] Tweets
  - [x] Press

Let's discuss:
- [x] ~~check box to hide from finder - on campaign~~ See #2377 
- [x] video section title
- [x] video section text
- [ ] logo gallery
- [ ] two column gallery type
- [x] winner label
- [ ] signup threshold
- [ ] output threshold
- [x] custom output label

**Comment by aaronschachter** [comment]
Discussed in meeting today, the plan is to build out a new node type, a Campaign Run, to house these fields. It will contain an entityreference to the Campaign.  This allows us to store multiple runs, so we'll have the data structures to store data for Thumbwars 2014, 2013, etc.

**Comment by barryclark** [comment]
cc @angaither

**Comment by aaronschachter** [comment]
@mikefantini Safe to close this issue? As we've discussed, I don't think it's worth adding fields for thresholds and auto-display.  Once we have Reportback Flagging in place, we could potentially display the totals within the campaign Run node edit form as help text, and editors can enter whatever values they wish, having those numbers as references.

**Comment by mikefantini** [comment]
@aaronschachter yeah I think it's fine for now.

Depending on if we expand this to all campaigns and not just top campaigns we may need to bring this feature back.

Displaying the signup count and output count on the admin form would be sweet if possible. Want to create another issue as low priority assuming this is what you were thinking?

**Comment by aaronschachter** [comment]
ya we can open an issue to display counts in the form, but ideally we need the invalid flag before this to get us closer to having accurate quantity totals. total reportback count would be valid though.

**Comment by aaronschachter** [comment]
signup count or reportback count?

**Comment by mikefantini** [comment]
yeah sorry i was saying signup count and report back value sum
