### ISSUE TITLE
Devel: Drush was unable to export FirePHP

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#235]
Can't use `krumo()` because "Drush was unable to export FirePHP to /vagrant/html//FirePHPCore".

Seems like vagrant doesn't have SVN installed?  Per https://drupal.org/comment/5620972#comment-5620972

**Comment by desmondmorris** [comment]
That warning does not seem to be the cause of this issue.  Krumo, dpm and other devel related functions are functional for me.

**Comment by desmondmorris** [comment]
This is related to #248.  Krumo is failing because it is not available for anonymous users
