### ISSUE TITLE
[SMS game] - add mobile fields

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2359]
Need a new field group "Mobile Referrals".

This should be a field set where you add:
- [ ] field name
- [ ] mobile commons beta opt-in ID

Need to check with @jonuy / Alysha but I'm pretty sure we'll be launching with all betas going through the same experience so may not need the second part yet. However, soon we'll want betas to have different experiences from each other.

cc: @julielorch

**Comment by mikefantini** [comment]
ah shit... I see you added SMS Games to http://staging.beta.dosomething.org/admin/config/services/optins

We may need to update the beta aspect depending on what @jonuy says.

**Comment by mikefantini** [comment]
Just chatted with Alysha and seems incredibly unlikely we'll need opt-in ID per beta, but still need the ability to set field name so we can prompt the user who to share with.

Example:
- your best friend
- you cousin
- etc.

One thing also to keep in mind though is that this is one of the major assumptions we want to test out, so maybe we can do this in optimizely or just hard code it for usertesting.com first before building it out?

thoughts @aaronschachter @barryclark?

**Comment by aaronschachter** [comment]
@jonuy So is the desired functionality to just send multiple regular opt_in requests with the various numbers?  We wouldn't be able to pull off actual texting multiple people via optimizely

**Comment by mikefantini** [comment]
@jonuy @aaronschachter just put time on the calendar today for a quick in person sync

**Comment by mikefantini** [comment]
just closing this out for now since we won't need this any time soon and not sure what this will actually look like when we do need it.
