### ISSUE TITLE
New field on campaign page - for email

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#2362]
We need a field on the campaign page where a campaign lead can enter custom content for email.

Right now this will be used for (1) the campaign signup transactional emails and possibly for (2) the email digest.

Let me know what specifics I can help provide!

**Comment by mikefantini** [comment]
@marahml just put a quick sync on for today for the three of us to chat

**Comment by marahml** [comment]
@mikefantini awesome - thanks!

**Comment by aaronschachter** [comment]
@marahml Just following up on this.  I want to avoid calling it something like "Transactional Email Copy" in the database because I can see us possibly using this content in other places as well, like on the User Profile where a user can view the campaigns they have signed up for but not reported back yet.  Would it be safe to say that this is kind of like a "Getting Started Overview" ?  or is it more for any recent news about the campaign?

**Comment by marahml** [comment]
@mikefantini sweet. love that it could have multiple uses. 

I think there are really 2 needs: 
1. a getting started overview - that has a starter statement for your campaign that could be used in email and other places
2. a dynamic field that can override the content in emails (and maybe sms in the future) with updates about the campaign

Thoughts?

**Comment by aaronschachter** [comment]
They sound like two different fields then. Is the immediate need for the first, for better copy within the signup transactional?

**Comment by aaronschachter** [comment]
@DeeZone @marahml Has this been closed by the additional field `field_recent_updates` that was added to the campaign form?

**Comment by marahml** [comment]
Yas. But is it live on campaign pages? Correlating issue in Jira says that
its built but not live.

On Fri, Sep 12, 2014 at 2:52 PM, Aaron Schachter notifications@github.com
wrote:

> @DeeZone https://github.com/DeeZone @marahml
> https://github.com/marahml Has this been closed by the additional field
> field_recent_updates that was added to the campaign form?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/dosomething/issues/2362#issuecomment-55445308
> .

## 

Marah Lidey

Director of Mobile Product & Messaging
@dosomething http://twitter.com/dosomething @marahml
https://twitter.com/marahml
(212) 254-2390 x215

**Comment by aaronschachter** [comment]
Ok - closing this for discussions to continue in Jira.
