### ISSUE TITLE
[Campaign Close] Campaign closed template

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2367]
**Updated:**

Create a `node--campaign--closed.tpl.php` to render a Campaign in a closed state.  The preprocessing should add relevant content variables from the relevant Campaign Run.

A campaign run node does not need to be themed (for now).  In the future we may display multiple Campaign Runs nodes at a time to display a Campaign's timeline / history.

---

**Original description:** 

Create a `node--campaign-run.tpl.php` for a Campaign Run node.

Needs to display the header and footer of its parent Campaign node.

When it's time to close a campaign, we unpublish it and change the Campaign Run URL alias to the now unpublished Campaign's URL alias, a.k.a. `The Old Switcharoo`.

**Comment by aaronschachter** [comment]
A disadvantage of the Switcharoo would be if any place on the web is hardcoding links to `/node/362`, but I can't imagine this is happening anywhere on the interwebs.

**Comment by mshmsh5000** [comment]
Are you imagining this as an automated process (I hope)?

What about the option where we render campaign run content instead of the main campaign content based on a flag?

E.g., the campaign content type has a modal switch, from "live" to "ended", either determined by date or by manually changing the mode. When the mode is "ended", we grab the run content in prerender and display that instead of the campaign node content.

This seems cleaner, because a lot of other things (node ID, url alias) can remain stable.

**Comment by aaronschachter** [comment]
The option of rendering the Campaign Run within the Campaign node is definitely do-able. 
Editorially, it just requires editing the Campagin Run node, and then refreshing the Campaign in a different tab. For developing, also requires theming the Campaign Run tpl without the wrapper of the Campaign node tpl around it.

The thoughts around having the Campaign Run switcharoo was that we could build out the entire closed campaign without touching the Campaign node or tpl much.  And editors would just be in the Campaign Run node the entire time while building it.

It's more of a UX-y type approach but I agree that the node nid changing and worrying about alias is probably not worth the greater headache it could cause.

We do have an issue for a Campaign State field in related to hiding from Finder #2377, which touches upon the comment you made yesterday, @mshmsh5000 about figuring out what happens in the Pre-Live state, which is what's missing from the complete cycle right now.  It would be useful  to figure this out sooner than later in regards to rules for when Campaigns should appear in Finder, and commiting code against #2377.

**Comment by aaronschachter** [comment]
Going with the route of embedding the Campaign Run node content within a Campaign node's template.  Updated issue title and description.
