### ISSUE TITLE
[Fact Page] Styles for Fact Page List

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2369]
Node does not exist on Production yet, but stage node can be found here: http://staging.beta.dosomething.org/facts

**Comment by barryclark** [comment]
@tjrosario Would be great if you could take care of this one. Not too much styling work to do here as default neue styles have taken care of most things... but it'd be good to use @weerd's containers on the content so that it has appropriate margins.

**Comment by barryclark** [comment]
@julielorch Take a peek at http://staging.beta.dosomething.org/facts too!

**Comment by joolaay** [comment]
Sweet totally missed this. I want to grab crystal for some design
QA...cool??

**Comment by tjrosario** [comment]
@julielorch sure!

**Comment by joolaay** [comment]
Can't wait can't wait can't wait
