### ISSUE TITLE
Prove It gallery is not displaying one of the photos

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2372]
7th photo on Prove It section is not displaying properly. 

https://www.dosomething.org/campaigns/pb-jam-slam
![screen shot 2014-05-29 at 6 02 18 pm](https://cloud.githubusercontent.com/assets/6550604/3124428/0661932e-e77d-11e3-9574-6ca70228e5bc.png)

**Comment by tjrosario** [comment]
This doesn't seem to be an issue anymore.
