### ISSUE TITLE
[Campaign Run] Video field

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2376]
Low priority. For Comeback Clothes's Campaign Run, we'll just pull the Video from the parent campaign's `field_video` value.
- [ ] Add the existing `field_video` field collection to the Campaign Run to specify a video.
- [ ] Modify Campaign Run template such that:
  - If a video_id exists on the parent Campaign, render the parent Campaign's video_id.
  - If a value is set on the Campaign Run's `video_id`, display this value instead.  this allows us to have different PSA's for Thumb Wars for older Thumb Wars Campaign Runs.

**Comment by angaither** [comment]
@mikefantini is this something we still want to do?

**Comment by mikefantini** [comment]
@angaither this has come up in the past. It's honestly probably worth doing if we're looking to make things more explicit and less hacky.
