### ISSUE TITLE
[Campaign template] Hide campaign from Finder

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2377]
Refs desired functionality specified here: https://github.com/DoSomething/dosomething/issues/2348
- [ ] Add setting to hide node from Finder (without unpublishing)
- [ ] Configure SOLR to exclude node from Finder based on this setting

This may be a simple checkbox, but could also possibly suggest that we need a Campaign State field, with different states:
- Pre-Launch
- Live
- Closed

It depends on if there are different views for Pre-Launch and Closed.  @mikefantini @barryclark Thoughts?  I don't think it makes much sense that you'd be able to find any campaigns within the Finder that don't have Campaign State == 'Live'

Ideally this could be more of a variable than a field, as we wouldn't necessarily need to be tracking revisions and the data is really simple.  Potentially similar to the `dosomething_signup_variable` concept.. maybe that should just be abstracted out to a simple `dosomething_variable` table where we can store things like campaign status (and both the Campaign and Grouped Campaign content types could make use of it).

**Comment by mshmsh5000** [comment]
I can see an editorial case for having manual control over whether a particular campaign gets indexed. I see three possibilities:
1. An `is_search_indexed` field exposed to editors, and manually managed
2. A variable not exposed to editors, managed when the campaign transitions to a new state (pre-live, live, closed)
3. A field whose value is managed during campaign transitions, but which editors can also see and manually override

As usual, I lean towards the option that gives us the most flexibility, which is the third. But I'd love to hear opposing opinions, @barryclark / @mikefantini / @aaronschachter.

**Comment by aaronschachter** [comment]
I like option 3, would this field be what actually transitions the campaign into the Closed state?  Vs. anything automated based on End Date values?  

We actually don't have a closed date anywhere on the campaign: just low season and high season -- which don't actually detail when the campaign ends, but controls its weight in the Finder.

**Comment by mikefantini** [comment]
Late following up on this but I think the critical path for comeback clothes we should follow is (as @barryclark touched upon in his email on Monday):
- editor manually puts the campaign in a closed state (since new information is needed I'm not comfortable yet with campaigns automatically going into a closed state since the editor may not have put in the necessary info)
- when a campaign is in the closed state, it should be removed from the finder AND /campaigns; but is still discoverable via search

I'm going to confirm this in management meeting this morning and will update this issue based on that conversation.

**Comment by mikefantini** [comment]
confirmed from management meeting that for now, when something goes into the closed state it should:
- be removed from finder
- be removed from /campaigns
- still be discoverable via search
- direct link should still work (obviously)

**Comment by barryclark** [comment]
Adding @blisteringherb in. 

@aaronschachter is there a variable that @blisteringherb should reference to decide whether a campaign is to be displayed in finder and /campaigns?

**Comment by aaronschachter** [comment]
@angaither is working on adding a Campaign State/Status field to the Campaign node.

**Comment by aaronschachter** [comment]
@blisteringherb @barryclark There is a function `dosomething_campaign_is_closed($node)` which will return TRUE if the given campaign node is closed. It is checking if the `field_campaign_status` value == closed

**Comment by barryclark** [comment]
@blisteringherb shooting this one over to you to complete this week so that we can test early next week with the Campaign Closed template.

Give @mikefantini or I a shout if you have any questions about implementation. Fantini's latest comment should spec it pretty clearly:

> confirmed from management meeting that for now, when something goes into the closed state it should:
> 
> be removed from finder
> be removed from /campaigns
> still be discoverable via search
> direct link should still work (obviously)

**Comment by barryclark** [comment]
:+1:
