### ISSUE TITLE
Julie would like an emoticon for hipchat

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#2386]
This is EXTREMELY high priority. CC: @crystalruthbell @DFurnes @barryclark

**Comment by crystalruthbell** [comment]
THIS IS SO URGENT!

![screen shot 2014-05-30 at 2 45 27 pm](https://cloud.githubusercontent.com/assets/6550604/3134825/9e5fdf98-e82a-11e3-9811-9ccf83110363.png)

**Comment by crystalruthbell** [comment]
http://emoji.zone/

**Comment by DFurnes** [comment]
That's my new homepage.

**Comment by DFurnes** [comment]
![julie](https://cloud.githubusercontent.com/assets/583202/3148835/d0fee476-ea64-11e3-8c4d-1669867d3357.png)
