### ISSUE TITLE
Search results show file names within preview

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2388]
Would be rad if we could hide this. Reads pretty pretty weird. 

![screen shot 2014-05-30 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/6550604/3134935/035a9f54-e82c-11e3-9216-4acc99f4df8d.png)

Hahahahhahahahah

**Comment by aaronschachter** [comment]
Assigning to @blisteringherb
