### ISSUE TITLE
[campaign close] "Results coming soon" state

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2402]
We need to add a state to the campaign close template for those few days after a campaign closes that we don't yet have final signup & reportback numbers. This message will display in place of the results numbers at the top of the template. 

The content editor needs a way to be able to display it instead of the numbers (maybe a checkbox?). For now that message can read "Results coming soon", the editor doesn't need to be able to change the message. @mikefantini is going to finalize the wording. 

cc @weerd

**Comment by mikefantini** [comment]
yeah @angaither hold off on this just now, need to chat with Deluca about this because there may be a time we want to close it but don't have scholarship winner yet either and will want to call that out as well

**Comment by mikefantini** [comment]
finalizing language with Ben tomorrow. will update this issue as soon as I have final copy

**Comment by mikefantini** [comment]
default language for output:

"We’re still tallying the [Total Quantity Label]. The bigger the number, the longer it takes...so stay tuned!"

default language for winners section:

"Hold on! We’re still sifting through the (amazing!) submissions you sent to choose a winner. We’ll email you and post his or her name here soon!"

**Comment by aaronschachter** [comment]
@angaither Were you thinking of adding a new field for to control this display?
