### ISSUE TITLE
[SMS game] - need to get optimizely up on staging for Bully Text

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2404]
@Bladt mentioned that we need to add `<script src="//cdn.optimizely.com/js/1158700146.js"></script>` into the header of http://staging.beta.dosomething.org/campaigns/bully-text-0 in order for him to make the optimizely tests we want to run for user testing live; can we get that set up today so we can send off to usertesting.com by EOD?

**Comment by barryclark** [comment]
@DeeZone @angaither 

Any thoughts on the best way to add this?

**Comment by mikefantini** [comment]
Just a note we'll also need it on http://staging.beta.dosomething.org/campaigns/bully-text-1

**Comment by deezone** [comment]
The Optimizely module should take care of this. There needs to be a test project entry with the ID "1158700146"

**Comment by Bladt** [comment]
Optimizely recommends pasting the snippet immediately after your opening `<head>` tag

**Comment by deezone** [comment]
The module puts the tag in the head of the document which is to spec from Optimizely the last time I checked. Has something changed or are your needs different?

**Comment by Bladt** [comment]
@DeeZone the Optimizely Drupal module (at least via the GUI) does not allow us to target something.dosomething.org urls and this test needs to run on staging.beta.dosomething.org/...

**Comment by barryclark** [comment]
@DeeZone Does this mean that we need to install the Optimizely module on staging? ... and if so, would you be able to set that up please?

**Comment by deezone** [comment]
Ah, I understand - a new use case for running Optimizely tests only on sub domains. Is this something we'll be doing often?

At any rate, to get this done today a "fender" needs to add the following to the `<head>` section of the Drupal template (tpl) file that's used on `http://staging.beta.dosomething.org/campaigns/bully-text-1` but not loaded on other campaign landing pages.

```
<script src="//cdn.optimizely.com/js/1158700146.js"></script>
```

This assumes that Opotimizely will support running tests on subdomains.

**Comment by barryclark** [comment]
@weerd Assigning over to you as you're working in this .tpl file already for Bully Text.

**Comment by mikefantini** [comment]
@weerd we need this for http://staging.beta.dosomething.org/campaigns/bully-text-0 and http://staging.beta.dosomething.org/campaigns/bully-text-1

**Comment by weerd** [comment]
Cool. So my thought is to use the `drupal_add_js()` function in the `.tpl` for the SMS game template. Does this make sense to you @aaronschachter @angaither @DeeZone ?

**Comment by aaronschachter** [comment]
I would vote for adding it into `template.php` or https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L276 instead of in the actual tpl

**Comment by weerd** [comment]
And still targeting the specific SMS campaigns? @aaronschachter

**Comment by aaronschachter** [comment]
Somethin like this:

```
function dosomething_campaign_preprocess_sms_game(&$vars, &$wrapper) {
    drupal_add_js( [SWEET INLINE JS HERE]  );
}
```

This function is only called for SMS Game nodes.

**Comment by weerd** [comment]
Cool. Sounds good. I'll punch it in!

**Comment by weerd** [comment]
```
Warning: file_get_contents(//http://cdn.optimizely.com/js/1158700146.js): failed to open stream: No such file or directory in _locale_parse_js_file() (line 1488 of /vagrant/html/includes/locale.inc).
```

Should this error be expected on my local?

@DeeZone @Bladt

**Comment by deezone** [comment]
Quick chat with @weerd , used "external" with `drupal_add_js()` to reference the Optimizely CDN.

**Comment by weerd** [comment]
thanks @DeeZone :dancers:
