### ISSUE TITLE
[SMS Campaign] Add wrapping <div>s for input fields in sign up form.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2411]
Allow for wrapping the "Your Cell" and the first "xxxx's Cell" fields in a div AND then another wrapping div for the other 2 "xxxx's Cell".

Please change the "xxxx's" text to "Friend's".

cc @mikefantini

**Comment by mikefantini** [comment]
also change text in all mobile fields to read "(555) 555-5555"
