### ISSUE TITLE
[Signup Data Form] - add Guam back to list of state options

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2413]
@angaither can you add Guam back in as one of the options for state on the address collection form?

**Comment by angaither** [comment]
The UPS Address validation that we use will not validate against Guam Addresses. 
We can add it in, but additional validation would be required for those.

![](http://cl.ly/image/2l360X3u2y0h/Screen%20Shot%202014-06-05%20at%209.50.14%20AM.png)

**Comment by mikefantini** [comment]
ok yeah I don't think it's worth it. closing this out for now. thanks for looking into it @angaither
