### ISSUE TITLE
Campaign Template - Can't submit report backs in IE10 / Windows 8

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2423]
SUBMIT YOUR PIC button goes active, but then the form doesn't submit. 

![image](https://cloud.githubusercontent.com/assets/692762/3174995/29e79ce8-ebf7-11e3-92af-3ff4fce65186.png)

Not tried with other versions of IE. Please test the fix in those too. 

Update https://trello.com/c/JbxUf7Zr/1171-trouble-uploading-photo-on-pb-jam-slam when this gets fixed. Thanks!

**Comment by barryclark** [comment]
@DFurnes Need to prioritize a fix for this.

**Comment by DFurnes** [comment]
IE10 seems to block form submission when both the file upload field and the form are submitted programmatically. Working on a fix.

**Comment by DFurnes** [comment]
Have a fix ready for this. Going to make sure to test thoroughly across browsers and will push up for review.
