### ISSUE TITLE
[Campaign Template] - update text on Contact Us modal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2431]
Let's update the body copy of the Contact Us modal to read "Enter your question below. Please be as specific as possible. If you are having a technical issue, please make sure to provide detailed steps (click by click) on how you encountered the problem, so our developers can re-create the issue."

![image](https://cloud.githubusercontent.com/assets/6330971/3180017/4c493eba-ec2c-11e3-953b-969fb9358e06.png)

@barryclark feel free to suggest any copy edits. Not sure if this is fender or bender.

**Comment by aaronschachter** [comment]
I'd like to make this copy a variable in the `dosomething_zendesk` module, so we don't have to deploy code changes.  Labelling as bender.

**Comment by aaronschachter** [comment]
Relates to #2169 and not having to make this change all over the place.
