### ISSUE TITLE
Thumb Wars [Reporting Back Bug] 

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2439]
When reporting back on the Thumb Wars campaign, I was hit with the issue where I would try to report back after sending all the necessary information to the forum, I was given a error message that said that I wasn't authorized to that page. (Note: I've done this now on two different accounts and I get the same error message.)
![image](https://cloud.githubusercontent.com/assets/7773483/3192660/0c3ab962-ece9-11e3-8924-d10482a3a9ac.png)

System: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36

**Comment by aaronschachter** [comment]
Was testing with @apatheticslacker -- seems like this was occurring because of uploading a specific file. @apatheticslacker Can you give more information aroudn which files worked and didn't work, and upload or link to them into this ticket?

**Comment by aaronschachter** [comment]
This also seemed to happen across all campaigns, not just Thumb Wars.  And upon creating a new account as well.

**Comment by apatheticslacker** [comment]
@aaronschachter When I kept getting that error message, I was using a jpeg image beforehand, but when I changed it to a jpeg, it seemed to work just fine. 
Image that was giving me errors: 
![a0 original](https://cloud.githubusercontent.com/assets/7773483/3192774/3b19c628-ecea-11e3-8f4b-86c5c008fcd5.jpg) 
Working image (all random ones on the laptop I'm using:
![img_1789](https://cloud.githubusercontent.com/assets/7773483/3192791/5cc77ea0-ecea-11e3-8a58-671d9c5e921e.JPG)

**Comment by aaronschachter** [comment]
>  I was using a jpeg image beforehand, but when I changed it to a jpeg, it seemed to work just fine. 

Do you mean a png? You mentioned int hat in chat. Also what was the file name?

**Comment by apatheticslacker** [comment]
There was just some confusion on my end, it was a jpeg the first image that was giving me a problem. 
The file name was A0 original.jpeg and I pulled it from the iPhoto library.

**Comment by aaronschachter** [comment]
I tried to upload a file with a space in name to see if that's it but still can't replicate.  @barryclark Can we attach original file somewhere so i can download?

**Comment by barryclark** [comment]
@apatheticslacker can provide you with that @aaronschachter, it was on his laptop

**Comment by apatheticslacker** [comment]
@barryclark Sure, I attached it earlier but it's this image.
![a0 original](https://cloud.githubusercontent.com/assets/7773483/3200958/a7351342-ed82-11e3-8cd1-ab04777f4dfe.jpg)

**Comment by aaronschachter** [comment]
I'm fairly certain this was because of the original file uploaded.  Uploading into the GH comments actually adds it as a new file.  Closing because this hasn't come up since (afaik)
