### ISSUE TITLE
[SMS game] - h2 needs to be purple

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2440]
need to make h2 (i.e. The Problem, The Solution) our purple.

![image](https://cloud.githubusercontent.com/assets/6330971/3193405/3cd2999c-ecf2-11e3-93bf-e38324a43ec4.png)

similar to how we have it on non-SMS campaigns:

![image](https://cloud.githubusercontent.com/assets/6330971/3193424/6692097a-ecf2-11e3-8ba7-fd0f4c300edd.png)

**Comment by DFurnes** [comment]
![screen shot 2014-06-05 at 5 01 14 pm](https://cloud.githubusercontent.com/assets/583202/3193613/909b6af2-ecf4-11e3-9c75-1ebf34d91667.png)
:japanese_ogre:

**Comment by mikefantini** [comment]
ha i didn't want to do it @DFurnes i swear, but i just know we won't launch it without this...

**Comment by DFurnes** [comment]
Haha, just having fun. :smile:  Right now we have `h3` and `h4` set to be `$dark-gray` in Neue. Should we just change these to be `$purple` by default? 

https://github.com/DoSomething/neue/blob/dev/scss/_main/_base.scss#L52-L54

**Comment by mikefantini** [comment]
great convo for Monday!

**Comment by weerd** [comment]
Did this convo happen??

**Comment by weerd** [comment]
Oh wait. I was part of this convo. haha.

**Comment by weerd** [comment]
I'll temp fix this in the container, but this will be properly addressed once we hear back from @crystalruthbell and design team regarding the named class hierarchy for headings, (ie: .alpha, .beta, .gamma, .delta, etc...)
