### ISSUE TITLE
Remove old button size classes from markup

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2445]
In addition to #2429 there are other massive buttons:
- [ ] Campaign confirmation page
- [ ] Log In/Create Account

![image](https://cloud.githubusercontent.com/assets/6330971/3201748/f3414dfc-ed8a-11e3-9882-aec43dfd166c.png)

![image](https://cloud.githubusercontent.com/assets/6330971/3201736/e00bc6d6-ed8a-11e3-8476-0292c25dbf8b.png)

![image](https://cloud.githubusercontent.com/assets/6330971/3201741/e7c7b92a-ed8a-11e3-8d32-693c2153e72c.png)

**Comment by DFurnes** [comment]
Fixed by removing alternative button styles in the latest Neue release.

Leaving this issue open as a reminder to remove those classes from the markup so we don't get any surprises if we reuse those class names later on.
