### ISSUE TITLE
Campaign Close - Pre-signup button adds user to MailChimp

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2449]
~~Blocked by #2463~~
- [x] New pre-signup form rendered in campaign header
- [x] Pre-signup form submit 
  - [x] Write a presignup record
  -  [ ] Subscribe user to Mailchimp
  - [x]  Upon submit, display the copy  "Sweet, we'll send you an email as soon as [campaign_title] re-opens. In the meantime, <a href="/campaigns">find a campaign</a> you can do right now."

**Comment by aaronschachter** [comment]
@barryclark @mikefantini 
- Can you confirm this is Mailchimp only and no Mobilecommons?  
- should a message appear after signing up, and if so what is the copy
- Is a transactional email to be sent?

**Comment by mikefantini** [comment]
@aaronschachter 
- yes Mailchimp only and not Mobile Commons
- yes, the user should get a notification, for copy let's go with "Sweet, we'll send you an email as soon as [campaign_title] re-opens. In the meantime <a href="/campaigns">find a campaign</a> you can do right now."
- I don't think we need to send a transactional email letting them know that we will be sending them an email in the future, but @marahml do you have any thoughts on this?

For context, when a campaign is in the closed state, users will be able to sign up to get notified via email when the campaign re-opens. The idea is that we will add the user to the campaign's MailChimp group and then send out a broadcast when the campaign re-opens.

Eventually we may want to do message broker-y things, but this is the idea for the first implementation.

**Comment by aaronschachter** [comment]
We are currently handling Mailchimp subscriptions via Message Broker.

@deezone Is there a function to call which will only subscribe a user to a Mailchimp Group (and no transactional)?

**Comment by mikefantini** [comment]
@aaronschachter right... i guess i meant rather than send a broadcast, handle the sending of the message once the campaign re-opens via the message broker.

Nothing we need to worry about yet though

**Comment by aaronschachter** [comment]
@mikefantini  What I meant was that just to get a user subscribed to Mailchimp in the beta app, we use Message Broker to handle that.  There is no Mailchimp code within the DS repo.

**Comment by mikefantini** [comment]
right makes sense

**Comment by marahml** [comment]
@mikefantini @aaronschachter yes - we should send users a transactional email anytime they sign up for something on the site, even if its just for future updates. (ie. We'll tell you when Thumb Wars is ready again next year, but in the meantime do these campaigns).

One issue with the previous flow for when campaigns were closed was that there was no thought to the UX on the notification side. We'd just say "we'll send you updates in the future" with no transactional email confirm & many times no follow-through on those updates.

**Comment by barryclark** [comment]
We clarified earlier today that when the Pre-Signup button is clicked the user should be prompted to Login/Register if they aren't currently logged in.

**Comment by barryclark** [comment]
Current status: we're storing pre-signups for each campaign and next need to decide how we're going to send them emails before the campaign launches and also how we add them to the bucket for email subscriptions for that campaign. 

Closed this related MailChimp issue out for now: https://github.com/DoSomething/message_broker_producer/issues/35

**Comment by angaither** [comment]
@mikefantini @marahml is this still something we should have open?

**Comment by marahml** [comment]
HAI @angaither @mikefantini. Yes, would love to revisit this. The 'notify me' promise that we offer users on closed campaigns doesn't actually ever happen. 

I'd make more sense for the experience to be: 
- BEST FOR UX: Button pushes to an existing campaign that's related OR just to /campaigns
- BEST FOR CONVERSION: Change the copy from "Notify Me" to something around "join our email list & hear about other campaigns" (but obvi much shorter)

Let me know your thoughts!
