### ISSUE TITLE
[SMS game] - scholarship callout should be in the form section

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2453]
pointing to the CTA button; similar to how we have on desktop action page

cc: @crystalruthbell @julielorch

**Comment by joolaay** [comment]
rad.

**Comment by weerd** [comment]
Working on this as a pattern now that it's not just for scholarships!

**Comment by mikefantini** [comment]
@weerd you're sorting this out so that it looks like the mocks right? https://docs.google.com/a/dosomething.org/file/d/0B5fENCbpVZv9cnBGNW1rWUZOQVE/edit

currently the call out is still up in the header section 
![image](https://cloud.githubusercontent.com/assets/6330971/3359219/fb828efa-fae5-11e3-891e-6a25fe6a5a67.png)

**Comment by weerd** [comment]
Yep. Will be removed on desktop in this update :)
