### ISSUE TITLE
Static Content - Gallery (link photos)

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2454]
Add ability for static content pages to link photos like on this What is DoSomething.org page.

![screen shot 2014-06-09 at 12 14 30 pm](https://cloud.githubusercontent.com/assets/6550604/3219020/27fc180c-eff1-11e3-8663-3149331235f0.png)

**Comment by barryclark** [comment]
IF the subheaders are linked, then link the photos too.
