### ISSUE TITLE
[campaign close] - hide "Add another item" and "Remove" buttons in the gallery field set

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2457]

**Comment by aaronschachter** [comment]
Can you give context for why this is needed?

**Comment by mikefantini** [comment]
@aaronschachter it's because an editor should only be allowed to add one gallery type at a time (i.e. I shouldn't be able to add two press galleries one on top of the other).

I should still be able to add two different galleries on top of each other (i.e. Press and then Celeb Mention) but that is handled by the other "Add another item" in the Klout Gallery field set.

**Comment by aaronschachter** [comment]
But don't you need the "Add another item" and "Remove" buttons within the Gallery field collection to be able to edit the items in it?

**Comment by angaither** [comment]
There are multiple klout galleries, but not multiple galleries within the klout type. You'll still be able to add/remove items inside
