### ISSUE TITLE
[SMS game] - remove auto-filling in phone number info

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2460]
When a user goes to fill in a phone number, the browser is suggesting data to auto-fill in the field (i.e. if I used 555-555-5555 before in my browser as a phone number, it suggests I use that for my phone number AND all three of the friends' phone number fields).

Let's just remove all phone number suggestions if we can for all of those field's (user's phone number included).

Making high priority because it creates a pretty terrible experience for the user because you have to delete data in the fields every time you try to fill out the form.

**Comment by weerd** [comment]
Is there a specific browser to test on? In chrome they show up as a suggestion but doesn't autofill...

**Comment by mikefantini** [comment]
@weerd looks like it's happening in chrome.. check out **removing user video** at the 7:00 minute mark

The issue is that when you select on the of the suggestions for your mobile number it also puts them in for all of the other mobile fields

**Comment by weerd** [comment]
Might be just in Chrome on Windows. I can't replicate on mac. Going to try in BrowserStack on Chrome :disappointed:

**Comment by barryclark** [comment]
We can't seem to replicate this @mikefantini. Lowering priority and will see if Diego V can replicate it.

**Comment by weerd** [comment]
Chatted w/ @DFurnes and we found this: http://css-tricks.com/snippets/html/autocomplete-off/

No guarantee a browser will listen to it, but it's something.... Might need some bender-ing help to override the form fields and add this attribute.

**Comment by mikefantini** [comment]
Happening for me on Chrome in Windows 7:

**Removed potential sensitive phone number - Barry**

not happening in Firefox

**Comment by weerd** [comment]
@mikefantini try a test once this gets pushed to stage. You can confirm that the code went through and you're trying the solution with the attribute by inspecting the code in Chrome and checking to see if the phone input fields have a `autocomplete="off"` attribute :dancer:
