### ISSUE TITLE
[campaign close] - add User First Name field to Winner field collection

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2465]
Field name "User First Name" (open to it being "Winner First Name" or whatever you think makes sense).

Help text "User First Name should only be needed if there isn't a user to lookup. If there is a user to lookup, then we'll pull in their first name from the UID."

cc: @aaronschachter 
- [ ] Add `field_winner_name` to `field_winners` field collection
- [ ] Use value in preprocess for when a User UID not set

**Comment by aaronschachter** [comment]
I'd prefer we build with machine name `field_winner_name` as per spec in #2378, in case we ever need to store a first name + last name combo, or a school name
