### ISSUE TITLE
"400 Bad Request" Error when adding a node

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#248]
If you create a content type and then add a node, you get a 400 Bad Request error.

The node/add form redirects you to the secure pages port, e.g. http://localhost:8889/content/blog-2.

This is not a blocker for campaigns, but will need to be resolved in order to create content types like static pages.

![screen shot 2013-12-10 at 3 15 07 pm](https://f.cloud.github.com/assets/1236811/1718052/20a0fe8a-61d8-11e3-840d-57b3f003c731.png)

**Comment by desmondmorris** [comment]
The fix is to enable secure pages for authenticated users

**Comment by desmondmorris** [comment]
With authenticated users added to the secure pages config, it is now impossible to visit the <front> anonymously.  I am also experiencing with the logout path.  This may or may not be related to cookies.

@mshmsh5000 mentioning you for visibility

**Comment by desmondmorris** [comment]
Considering this issue closed.  My last comment is related, but not bound to this issue
