### ISSUE TITLE
campaign run: calculated totals help text in node form

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2480]
within the totals section, display the parent node's reportback count and quantity totals as help text to guide usage of the input fields.

**Comment by mikefantini** [comment]
@aaronschachter this should be signup count and quantity totals

**Comment by barryclark** [comment]
Would be great to just display the signup count & quantity sum (without flags). That's enough to close this out. Shooting this one over to you @angaither
