### ISSUE TITLE
[campaign close] - rules for displaying info in winner section

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2490]
- [x] if anything in the field_winners group is filled out display in the "CONGRATULATIONS TO..." section
- [x] if nothing in the field_winners group is filled out display the section header ("CONGRATULATIONS TO...") and the default winner text (#2402)

Mobile mocks with (outdated) copy:
![image](https://cloud.githubusercontent.com/assets/6330971/3247957/a9d8331c-f189-11e3-9bb9-a89cf06f76ef.png)

**Comment by barryclark** [comment]
@crystalruthbell 

Are we moving to using italics for all placeholder type messaging? Should this become a pattern?

cc @weerd @DFurnes @tjrosario

**Comment by tjrosario** [comment]
I've made this it's own pattern specific to campaign closed for now, but we should consider porting it over to neue.  I left a todo comment in the CSS just as a reminder.

**Comment by barryclark** [comment]
Awesome, @tjrosario. Thanks.
