### ISSUE TITLE
[campaign close] - update LOVE FROM CELEBS section header copy

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2491]
update section header "LOVE FROM CELEBS" to read "THE BUZZ"

![image](https://cloud.githubusercontent.com/assets/6330971/3248021/4a03e098-f18a-11e3-9508-26c2bc3df3d2.png)

@barryclark not sure if it's bender or fender so just assigning to you

**Comment by barryclark** [comment]
One for tom, thanks
