### ISSUE TITLE
[campaign close] - changing the subheader colors

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2494]
For closed campaigns, any text or sections that are red in the mocks (https://docs.google.com/a/dosomething.org/file/d/0BxBqwT7gEBtQZ2w2aVBYbWVLRnc/edit) should be our purple by default. However, editors should have the ability to override the default purple by filling out the "Alt color" field in Custom Settings -> Styles on the _campaign node_.

![image](https://cloud.githubusercontent.com/assets/6330971/3248221/87f85256-f18c-11e3-95e3-953f0bf5fba5.png)

@barryclark again not sure who this should be on so assigning to you

**Comment by barryclark** [comment]
Shooting over to @tjrosario -- thanks Mike

**Comment by mikefantini** [comment]
sweet also cc'ing @aaronschachter in case there are any questions.

**Comment by aaronschachter** [comment]
This is not in place because the `<h4>` elements need a class `inline--alt-color`.  Check out the `node--campaign.tpl.php`.  Sending this one over to @tjrosario as he's working in the closed template.

**Comment by tjrosario** [comment]
This was fixed in a previous PR!
