### ISSUE TITLE
Cap deploys to public production and staging IPs 

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#2497]
The [config settings](https://github.com/DoSomething/dosomething/blob/dev/config/deploy/production.rb) refer to a public IP, which is sub-optimal: (a) it publishes a public IP that we don't / shouldn't need for a web head, and (b) it requires both a public IP and an open SSH port in the firewall.

Instead, use private subnet equivalents for production deploy targets.

**Comment by desmondmorris** [comment]
We must keep in mind that this will require the deployment machine to be within the RPC firewall.  So jenkins should be all good, but will fail from individual machines.

+1

**Comment by mshmsh5000** [comment]
Yes, will fail from individual machines unless they're on VPN, which is as it should be.
