### ISSUE TITLE
User Profile PageTitle

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2502]
Implement `drupal_set_title` to override the default behavior, which uses the user's username as the page title. Which in our case, is set to the uid so it makes no sense.

Maybe just have it read as "My Profile"? "My campaigns?" 

Screenshot shows bug in user profile, but note the `<TITLE>` value.
![screen shot 2014-06-12 at 2 34 44 pm](https://cloud.githubusercontent.com/assets/1236811/3262000/5ed0756e-f260-11e3-877a-6d08082c0f8b.png)

**Comment by barryclark** [comment]
@angaither this is more of a bendery issue—assigning over to you. The title tag should say the user's name instead of the ID.
