### ISSUE TITLE
Campaigns page layout is broken on production

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#2506]
Now campaigns are aligned in one column in the center of the page.
Both [production](https://www.dosomething.org/campaigns) and [staging](http://staging.beta.dosomething.org/campaigns) are affected.

![image](https://cloud.githubusercontent.com/assets/672669/3262223/eb8f4186-f262-11e3-813d-bcc61da60a24.png)

Btw, this is the very first page new user sees when he follows "Take Action Now" link in the welcome email.

**Comment by aaronschachter** [comment]
Fixed yesterday.
