### ISSUE TITLE
Import legacy campaign activity

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2513]
This is a big task.  Import legacy reportbacks (records in `webform_submission`) into relevant beta reportbacks.

Relevant legacy tables:
- `dosomething_signups` (newer campaigns)
- `webform_submissions`
  - all reportbacks are webform submissions with type=`campaign_report_back`
  - old signups were webform submissions for type=`campaign_sign_up`
  - there is a webform entity field, `webform_pictures` which stores reportback files.

Would be nice to have for Mind on My Money close.

Not necessary to import MOMM if only for this run which is just closing... but things brings up how we need to how to best store Signups and Reportbacks per campaign run, and bigger picture of should we build Reportbacks  to be associated with a Signup (thus only needing to store Signups by Run ID, and not both tables)

Related trello card: https://trello.com/c/9zOQCB7a

**Comment by barryclark** [comment]
Could be a great one for you to work on @sergii-tkachenko? cc @mshmsh5000

**Comment by aaronschachter** [comment]
Besides the DB import scripts, this will require copying files from legacy over to beta.  Or... keeping it on the legacy server but somehow pointing it there?  Or... moving it all those files into the cloud somewhere.

**Comment by sergiitk** [comment]
I've discussed this issue with @barryclark. I'll deploy legacy site to my local env next Monday and start playing with it so I can ask right questions here.

**Comment by aaronschachter** [comment]
Updated issue description with relevant tables to check.

**Comment by aaronschachter** [comment]
Renamed issue to "import legacy campaign activity."  Ideally we want to import signups as well as the reportbacks.  If we go the route of #2523, each legacy reportback would be stored against its legacy signup.

**Comment by sergiitk** [comment]
Hey @aaronschachter, I've started looking into the legacy. One thing though: could you please provide me with db dump or credentials to server I can receive it from?

**Comment by aaronschachter** [comment]
@blisteringherb @mshmsh5000 Would you be able to point @sergii-tkachenko in the right place?

**Comment by mshmsh5000** [comment]
I've HipChatted the info to @sergii-tkachenko. /cc @aaronschachter

**Comment by angaither** [comment]
since legacy is now well murderd, I'm closing under the assumptions either 
1. we've done this
2. we didn't need this

cc @sergii-tkachenko feel free to re-open if I'm wrong

**Comment by aaronschachter** [comment]
FYI - I don't believe we ever imported legacy signups and reportbacks... it doesn't sound like anyone's been asking for them.
