### ISSUE TITLE
[Campaign Template] - clean up spacing in Prove It section

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2526]
@crystalruthbell - @weerd made rules more consistent on the template.

Some things I'd love your input on:
- treating space of primary button same as secondary button (I think we should give more space between primary button and copy than secondary button and copy)
- location of official rules (@weerd updated it so that it gets vertical space treatment like Sources, would love you to confirm this works. I think right now it looks a bit funny but potentially less so if we give primary buttons more vertical spacing).

Primary button:
![image](https://cloud.githubusercontent.com/assets/6330971/3272591/c72348ee-f319-11e3-8392-7529a3e973ae.png)

Secondary button:
![image](https://cloud.githubusercontent.com/assets/6330971/3272586/bd200dc8-f319-11e3-8608-0702ede47a55.png)

Official Rules:
![image](https://cloud.githubusercontent.com/assets/6330971/3272639/5b9d2dc8-f31a-11e3-9f82-0cf2bebe5f65.png)

**Comment by crystalruthbell** [comment]
@mikefantini sorry for the delay on this. My notifications aren't properly set up. 
1. I agree that primary button should get more space as secondary button. Let me now if I can review when a new spacing has been decided on (@weerd has a good eye so he can frame up, I just want to take a look when its done). 
2. Official rules feels very low in this design. Is the coding that it comes after the last thing in both columns? What is the logic here?

**Comment by mikefantini** [comment]
sweet. @weerd want to update this issue when you get a chance to add some spacing for primary button on the action page? Would this affect the pitch page at all?

and yes @crystalruthbell without doing a bunch of fucker-y official rules needs to clear the image as well. as part of the revamp we may be adding more content to call out the value proposition to reporting back, which could help, but it kind of needs to stay where it is for now.

**Comment by DFurnes** [comment]
This has been fixed with Neue 6.0 spacing refresh and new Reportback v2 design! :dancer:
