### ISSUE TITLE
[SMS game] - Know It Image Needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2533]
Need an image field in the Know It section for SMS Games. This serves the purpose of showing the user what they can expect to receive by playing the game. Also makes the page a bit more visually interesting.

Maybe we can just use the Video Replacement Image field. It might make sense to change the field name for this, especially since we aren't using it as a video replacement ever. Maybe we just call it Know It Image?

![image](https://cloud.githubusercontent.com/assets/6330971/3288803/38a5732c-f566-11e3-9937-ec1a9c76af2c.png)

**Comment by aaronschachter** [comment]
Would be best to use this existing field.

Technically we do use this as a Video Replacement though -- I guess you mean that no one has ever uploaded one?  Renaming this to "Know It Image" is fine, however there should still be copy that suggests it will only be displayed if a Video is not set.

**Comment by aaronschachter** [comment]
I'll update the field to say "Know It" image. The template is already set up to output the image: http://staging.beta.dosomething.org/node/1199
