### ISSUE TITLE
Reportback: Add record to file_usage

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2535]
- [ ] Upon adding a new file, a record should be added to the `file_usage` table. 
- [ ] Update all existing reportback file records to add a record into `file_usage` for each file.  This may need to be done via cron queue.

I don't see this happening, but this is terriyfing: http://drupal.stackexchange.com/questions/60445/why-is-drupal-deleting-my-images

> you might want to check the file_usage table after adding an image to see if it's recording a usage. If it's not recording a usage, it's being deleted because on cron run, Drupal automatically deletes files from file_managed that don't have a usage recorded in file_usage.

But this seems to suggest it won't be deleted:
http://drupal.stackexchange.com/questions/27304/will-managed-files-be-deleted-if-no-corresponding-entry-exists-in-file-usage

> The file won't be deleted unless it has a status of zero in the file_managed table

We are setting the file status to permanent here, https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L443, so we should be okay. It does make sense for us to implement the usage table though.

**Comment by aaronschachter** [comment]
Will need to adjust the `$reportback->deleteFiles()` function accordingly if we end up implementing `file_usage`

**Comment by angaither** [comment]
going to close this one out (cc @aaronschachter)
