### ISSUE TITLE
[SMS game] - need to display copy indicating # of ppl who have participated in SMS Games

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2538]
We want to show users how many ppl have participated in SMS games since they launched back in 2012.

Ideally this would be automated so we don't have to update copy on an ongoing basis, but that's not needed just yet if that's too difficult for launch.

@Bladt @joshcusano do you have thoughts on how to show the total number of people who have participated in SMS Games?

![image](https://cloud.githubusercontent.com/assets/6330971/3289823/9df14152-f570-11e3-968c-922453a0394c.png)

**Comment by aaronschachter** [comment]
This is just implemented as a copy field for now. Can revisit if we want the # to be grabbed from somewhere.
