### ISSUE TITLE
[SMS game] - prompt user to create account/log in on confirmation page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2541]
For SMS Games, we should prompt the user to create an account or log in after they have submitted the form.

Let's take the real estate we give to "Find More Campaigns" and replace it with this call out.

Clicking on the button should prompt auth modal.

Ideally we would have CTA copy above the button like we do on static content.

@aaronschachter let me know how you want to handle this copy... I can either get copy to you in this issue or if you're going to build that thing for admin's to control copy I'll just put it in there.

![image](https://cloud.githubusercontent.com/assets/6330971/3290283/9fe5c554-f576-11e3-8868-4961f191aa54.png)

**Comment by aaronschachter** [comment]
@mikefantini So we just need copy for what the "Find More Campaigns" button says?  Or an additional sentence besides that?  Would be helpful to provide default text, although we can build it to use variables to override, to avoid making copy changes in code.

Also i take it that the desired behavior is to login and then direct to `/campaigns` ?

**Comment by mikefantini** [comment]
yeah we need copy for what the button says and an additional sentence besides that

@julielorch want to get @aaronschachter default copy for these?

in terms of behavior I think it makes most sense to give the user the normal account creation notification message and just reload the page but defer to @julielorch to make the final call on that

**Comment by aaronschachter** [comment]
It is much simpler for us to reload the page vs. redirecting.

**Comment by mikefantini** [comment]
@aaronschachter if possible, I think it would make sense to keep it as is (i.e. find more campaigns) if the user is already logged in.

This could also be the state when the page re-loads if the user filled out the form as anon but then logs in.

If all of that is too difficult, we _could_ just not show the call out to join.

**Comment by aaronschachter** [comment]
Per #2591: 
- The copy will be editable through the admin interface at `admin/config/dosomething/dosomething_campaign`
- Only displays the CTA copy variable for anonymous users
- Keeps the button text as "Find more campaigns" if the user is already logged in.

**Comment by joolaay** [comment]
Sweet @aaronschachter
