### ISSUE TITLE
Vagrant up error: host_name setting doesn't exist

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#255]
Doing a new build with vagrant up and:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The following settings don't exist: host_name

![screen shot 2013-12-12 at 10 38 01 am](https://f.cloud.github.com/assets/1236811/1734205/9ba0376a-6343-11e3-9a1f-9aa71d4e02ef.png)

**Comment by desmondmorris** [comment]
What version of vagrant & virtualbox are you running?

**Comment by aaronschachter** [comment]
Vagrant 1.2.2  and VirtualBox 4.2.12.

VirtualBox prompted me to upgrade to 4.3.4, so I'm downloading that now.

**Comment by aaronschachter** [comment]
Upgraded to Vagrant 1.4 and VirtualBox 4.3.4.  All better. 

http://www.youtube.com/watch?v=EemoOviEC74

![brule](https://f.cloud.github.com/assets/1236811/1734702/42358714-634a-11e3-967b-e6f58338fb28.jpg)

**Comment by aaronschachter** [comment]
Reopening, https is not working.  Attempting to get Vagrant 1.3.5 instead of Vagrant 1.4 to see if that works.

**Comment by aaronschachter** [comment]
Current state: Using Vagrant 1.3.5 and VirtualBox 4.3.4.  When I do a vagrant destroy and then vagrant up, I get a SSL connection error.

![screen shot 2013-12-16 at 10 26 47 am](https://f.cloud.github.com/assets/1236811/1755556/90b81a7c-6666-11e3-9671-c5b263d1bf71.png)

I've been able to workaround this by disabling securepages.

**Comment by desmondmorris** [comment]
@aaronschachter open a new issue for SSL not functioning as it is a different issue.

**Comment by aaronschachter** [comment]
Opening #271 for SSL issue.  This original issue been resolved by upgrading Vagrant from 1.2.2 to 1.3.5. (Vagrant 1.4 did not work)
