### ISSUE TITLE
[campaign close] - remove scholarship amount from header

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2558]
If a campaign is in the closed state, we should no longer display the scholarship amount

![image](https://cloud.githubusercontent.com/assets/6330971/3302583/d24a9ffa-f635-11e3-80ef-e123ce7e476a.png)

@barryclark @tjrosario @angaither we could always just remove the scholarship amount from the campaign node but I'd rather keep it and just not display it

@barryclark not sure if this is fender or bender so assigning to you

**Comment by barryclark** [comment]
Assigning over to @tjrosario to take a look at, and can pull in bender help if needed.

**Comment by mikefantini** [comment]
also need this language in its place (so just removing scholarship info doesn't really work)

text reads "we'll hit you up when it re-opens"

![image](https://cloud.githubusercontent.com/assets/6330971/3303360/8b6ddae4-f63e-11e3-9093-646b88118139.png)

**Comment by mikefantini** [comment]
also I tried just removing the scholarship amount and that text above did not appear

**Comment by aaronschachter** [comment]
I don't think the proper way to handle this would be through removing the field vlaue, especially since we need language to display there instead.  Sounds like this should be handled in preprocessing.

**Comment by mikefantini** [comment]
yeah agreed

**Comment by aaronschachter** [comment]
Shouldn't the "Ends June 20" copy be removed too?

**Comment by mikefantini** [comment]
yeah good catch @aaronschachter
