### ISSUE TITLE
[campaign close] - prevent auth/anon users from visiting the campaign run node directly

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2560]
since we have to publish campaign run nodes, let's add a check that prevents auth/anon users from visiting the campaign run node directly, like how we do for Facts or Image nodes

@barryclark assigning to you to assign out

**Comment by barryclark** [comment]
Would you be able to take a look please, @angaither?

**Comment by barryclark** [comment]
@angaither Thanks!
