### ISSUE TITLE
[campaign close] - add commas to signup and output numbers

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2570]
Let's add commas to these numbers so that they are more readable:

![image](https://cloud.githubusercontent.com/assets/6330971/3304434/83c463ba-f64a-11e3-8215-eabc3ed41c5a.png)

@barryclark assigned over to you

**Comment by aaronschachter** [comment]
We'll need editorial to know that these are always numbers, or should enforce. This was specifically implemented as a text field in case we ever wanted a "Over 10,000".

**Comment by barryclark** [comment]
@aaronschachter So editorial can just put "100,000" in there then? So we can close this? @mikefantini

**Comment by aaronschachter** [comment]
Yes they can. If we want to hardcode rules of numbers and adding commas, then the issue is open, but if we want flexibility, then editorial can add commas (and we have ability to have non-numeric values here)

**Comment by mikefantini** [comment]
hmmm I guess I'm fine with having people add in commas.. I don't think we'll ever use these fields as our be-all end-all data documentation for how the campaign went anyways.

closing out for now
