### ISSUE TITLE
Multiple Selection Filter Error

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2584]
Uh, so I'm having this really weird issue on both staging and the regular site where I go ahead and basically select two campaigns at once, and I'll get this weird "Ooof! We're not sure what's up? Maybe it's us, or it could be your internet connection. Want to try again in a few minutes?" message. It's even happened to me when I've unselected a campaign and I'm not entirely sure why. 

On The Regular Site:
![image](https://cloud.githubusercontent.com/assets/7773483/3314846/1e39179c-f6f5-11e3-9814-ff3954f9d728.png)
![image](https://cloud.githubusercontent.com/assets/7773483/3314977/55052396-f6f6-11e3-9426-8b47e15f17f7.png)
On Staging:
![image](https://cloud.githubusercontent.com/assets/7773483/3315110/99065f64-f6f7-11e3-88cb-f7f589e612ad.png)

**Comment by barryclark** [comment]
:boom: Sweet bug dudes

**Comment by barryclark** [comment]
@tjrosario It'd be great if after selecting a cause, it immediately made the other causes inactive. 

Any additional thoughts on this @DFurnes ?

**Comment by DFurnes** [comment]
We should probably just block making any other selections until the server responds with updated facets.

**Comment by barryclark** [comment]
Related: If you quickly click a Cause, then a Time that should be unavailable (before the filters update) you're able to select a combo that there are no results for too. 

![image](https://cloud.githubusercontent.com/assets/692762/3848920/71352e9e-1e74-11e4-99bb-65e6fc7b396c.png)
