### ISSUE TITLE
Campaign Finder - Automate removal of closed campaigns from finder

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#2587]
When a campaign is closed by the campaigns team it'd be great if we could automate the removal of it from the Campaign Finder and /campaigns.

(for now campaigns team are going to add a Trello card notifying @blisteringherb to remove it manually)

**Comment by blisteringherb** [comment]
For the /campaigns page, we're using a hardcoded xml file in the solr conf to make sure that certain campaigns are listed first and in a specific order.  Any boosts or weighting we add doesn't give us the control the product owners wanted over which items appear first on that page.  

Setting the campaign status to 'closed' should remove the item from the finder.

**Comment by barryclark** [comment]
@blisteringherb Great that setting it to closed will remove it from the finder! 

Follow up question on /campaigns: Deluca is currently the QB of specifying which campaigns he'd like to appear on the homepage. https://beta.dosomething.org/node/1141/edit 

Is there a way to use this, or create another similar node that the campaigns team could administer for /campaigns? Then maybe the first set of campaigns to appear on /campaigns could use a separate call to something that and not to solr?

**Comment by blisteringherb** [comment]
We can definitely do something like that.  For purposes of prioritizing that work, we currently have 2 campaigns left that are hardcoded, so once those are closed there won't be any more manual tasks, unless we need to add more to that list in the interim.

**Comment by barryclark** [comment]
Chatted with @blisteringherb about this. Next step is on me to speak with Deluca and check if the campaigns team will be happy with pulling in the same order as the homepage and using that as the display order of the campaigns on /campaigns. 

If so then we could display the 10 campaigns from the homepage first, then the rest of the campaigns after. Using a filter on the view to remove duplicate campaigns that have already been displayed.

**Comment by barryclark** [comment]
cc @aaronschachter

**Comment by barryclark** [comment]
This is done :dancers:
