### ISSUE TITLE
[SMS Campaign] Update output location and markup for new callout.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2592]
Sample output:

```
<div class="scholarship-callout -action -below">
  <p class="copy">$10,000 Scholarship</p>
</div>
```

The classes will likely be different. Also depending on the formatting the `<p>` tag surrounding the copy might already be output by Drupal.

**Comment by aaronschachter** [comment]
@weerd Can you specify where in the markup this should live? You mentioned moving it out of that `group2` fieldset ?

**Comment by aaronschachter** [comment]
discussed with @DFurnes . Ideally the markup classes would be placed via `hook_form_alter` in the theme, but we haven't really been consistent with that at this point. Going to open a refactor/cleanup issue, as we'll want to discuss best place for the code to live.
