### ISSUE TITLE
[campaign close] - create new image crop

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2596]
now that we have the media style gallery with thumb nail images I think 640x640 is too restrictive for a minimum image size for photos.

Can we reduce it to 300x300 for now?

We can always change it back if we end up implementing #2380 and don't think this will disrupt other times we try to go with this two column gallery.

**Comment by DFurnes** [comment]
Where are we getting these 300x300 photos from? That's very low resolution.

**Comment by mikefantini** [comment]
@DFurnes some of them are coming from twitter.. we'll be chatting about this post-stand up today if you want to join

**Comment by mikefantini** [comment]
updated the title

let's call this "thumbnail"

minimum size is 200x200

**Comment by angaither** [comment]
Closed with #2619
