### ISSUE TITLE
DoSomething WebTests fail

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#260]
The 'testCampaignForm' test was working, but now all the tests are failing... seems that records are not being written into the db.  

![screen shot 2013-12-12 at 6 00 18 pm](https://f.cloud.github.com/assets/1236811/1738260/3bb2b632-6381-11e3-93c9-82d8f8fc8545.png)

**Comment by aaronschachter** [comment]
Inspecting the "verbose message" from within the testing UI shows that this message is returned:

GET request to: admin/campaign/add
Ending URL: http://dev.dosomething.org:8888/admin/campaign/add
Fatal error: Cannot access empty property in /vagrant/html/modules/field/field.attach.inc on line 208

There was an empty property error which would appear as a warning on the Campgin Form and was fixed by #230 - it includes a core patch added to the drupal.org make file in order to get Taxonomy and Image widgets to work properly in our Form API Campaign Entity form.  Need to investigate further but commenting in case anyone has any ideas or leads.

**Comment by aaronschachter** [comment]
It's not just liking any of the `field_attach_form` calls, commenting these out will cause the test to pass.  What's troublesome is that the Entity API SimpleTests don't run at all.  

![screen shot 2013-12-13 at 11 41 09 am](https://f.cloud.github.com/assets/1236811/1743993/98af16f2-6415-11e3-8d32-47c8af7b3b94.png)

Going to test Entity API on a separate MAMP setup on my local to see if the Entity API tests pass.

**Comment by aaronschachter** [comment]
Entity API 1.2 Entity CRUD test is passing correctly on clean Drupal install I set up with MAMP.  This bug seems to be an issue with Vagrant / environment setup. Updating issue title accordingly.

**Comment by aaronschachter** [comment]
The dosomething_campaign test is also passing correctly on a Drupal MAMP install (with the corresponding custom modules copied over and enabled as well).  Something's up with the vagrant installation that's causing these tests to fail.

**Comment by desmondmorris** [comment]
What versions of mysql/php in MAMP?

**Comment by aaronschachter** [comment]
Renaming this as Entity API test, since campaign form test is no longer valid.

**Comment by aaronschachter** [comment]
Renaming this as WebTests fail.  Other tests that fail include Administration Menu, and Views.  For Views, I get this error:

```
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=10&op=do StatusText: Service unavailable (with message) ResponseText: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dosomething.simpletest317302views_test' doesn't exist: INSERT INTO {views_test} (name, age, job, created) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3), (:db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7), (:db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11), (:db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15), (:db_insert_placeholder_16, :db_insert_placeholder_17, :db_insert_placeholder_18, :db_insert_placeholder_19); Array ( [:db_insert_placeholder_0] => John [:db_insert_placeholder_1] => 25 [:db_insert_placeholder_2] => Singer [:db_insert_placeholder_3] => 946684800 [:db_insert_placeholder_4] => George [:db_insert_placeholder_5] => 27 [:db_insert_placeholder_6] => Singer [:db_insert_placeholder_7] => 946771200 [:db_insert_placeholder_8] => Ringo [:db_insert_placeholder_9] => 28 [:db_insert_placeholder_10] => Drummer [:db_insert_placeholder_11] => 946708230 [:db_insert_placeholder_12] => Paul [:db_insert_placeholder_13] => 26 [:db_insert_placeholder_14] => Songwriter [:db_insert_placeholder_15] => 946706400 [:db_insert_placeholder_16] => Meredith [:db_insert_placeholder_17] => 30 [:db_insert_placeholder_18] => Speaker [:db_insert_placeholder_19] => 946708210 ) in ViewsSqlTest->setUp() (line 146 of /vagrant/html/profiles/dosomething/modules/contrib/views/tests/views_query.test).
```

However, the tests in core modules like dblog and cache pass.  Maybe SimpleTest is looking in the wrong directory for contrib / custom modules, and thats why the simple SetUp tests are failing to load.

**Comment by aaronschachter** [comment]
Ah, of course all contrib tests are failing, because you can't actually run them in an installation profile, per https://drupal.org/comment/4909532#comment-4909532.  You need to add:

```
protected $profile = 'dosomething';
```

However, adding this in I'm still getting an AJAX error.  

```
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=15&op=do StatusText: Service unavailable (with message) ResponseText: FieldException: Attempt to create a field of unknown type <em class="placeholder">link_field</em>. in field_create_field() (line 110 of /vagrant/html/modules/field/field.crud.inc).Uncaught exception thrown in session handler.PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;uid&#039; cannot be null: INSERT INTO {sessions} (sid, ssid, uid, cache, hostname, session, timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] =&gt; X3kFsdDyxKjPvEVbi1BZueTKbANFDSXNnvg_LH9liYY [:db_insert_placeholder_1] =&gt; [:db_insert_placeholder_2] =&gt; [:db_insert_placeholder_3] =&gt; 0 [:db_insert_placeholder_4] =&gt; 10.0.2.2 [:db_insert_placeholder_5] =&gt; batches|a:13:{i:3;b:1;i:4;b:1;i:5;b:1;i:6;b:1;i:7;b:1;i:8;b:1;i:9;b:1;i:10;b:1;i:11;b:1;i:12;b:1;i:13;b:1;i:14;b:1;i:15;b:1;}messages|a:1:{s:5:&quot;error&quot;;a:1:{i:0;s:282:&quot;There are security updates available for one or more of your modules or themes. To ensure the security of your server, you should update immediately! See the &lt;a href=&quot;/admin/reports/updates/update&quot;&gt;available updates&lt;/a&gt; page for more information and to install your missing updates.&quot;;}} [:db_insert_placeholder_6] =&gt; 1389303619 ) in _drupal_session_write() (line 209 of /vagrant/html/includes/session.inc).
```

Still investigating.

**Comment by desmondmorris** [comment]
@aaronschachter good find.  what happens when you run from command line?

**Comment by aaronschachter** [comment]
I figured it out (again -- I figured this entire issue out another time before, when i got the first test to run).  When a module that another module depends on is not specifically enabled in the dosomething.profile's list of dpendencies, shit breaks.  To fix the AJAX error above, we need to add the Link module into the installation profile.  Will make this change and add it into #356
