### ISSUE TITLE
[campaign close] - if a report back is missing the thumbnail image in the view you can't promote it

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2604]
both Hilary and I tried with this one and got the error message below. she later tried with one that did show the image and it worked properly

![image](https://cloud.githubusercontent.com/assets/6330971/3329540/d974c470-f7c7-11e3-8429-9a9e5d0c9702.png)

**Comment by aaronschachter** [comment]
I know this not ideal but there's a way to process the file manually, I've just tested: https://beta.dosomething.org/node/362/reportbacks?uid=1752507&mail=
1. View into the Reportback by clicking the "Submitted" timestamp, bringing you to `reportback/[rbid]`.
2. Under the list of Files associated with the Reportback, view the actual File by clicking on the FID value, bringing you to `file/[fid]`.
3. Click edit, bringing you to `file/[fid]/edit`.
4. Simply hit save. This processes the file, telling the File Entity module "hey this is an image file"
5. go back to the reportback view. You should now be able to add the image to the gallery.

This manual step will be unneeded within a few days, once all the images in the site have been processed.
