### ISSUE TITLE
User: Get First Name function

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2606]
Add a `dosomething_user_get_first_name` function which uses `dosomething_user_get_field`, but also does string processing to make sure it's Capital letter, lowercase.
- no all lowercase
- no all capitals

We currently have users with lowercase / all caps first names, so just implementing this via `hook_user_save` will not fix for existing users.

**Comment by barryclark** [comment]
@aaronschachter Is there somewhere that this is going to be used? User profile? (looking for some context)

**Comment by aaronschachter** [comment]
It's coming up now because of the campaign closed template, where we are pulling the winner's first name based on the user field_first_name value.  Would apply to user profile too, to keep it from looking inconsistent (caps / lowercase)

**Comment by barryclark** [comment]
Cooool, shooting this one over to @angaither thanks!
