### ISSUE TITLE
Unsupported operand types in... flag_flag.inc

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#2607]
Started getting a white screen of death on my local after the whole feature revert kerfuffle the other day, which stuck around even after doing a `ds pull stage && drush cc all`.  This error was running the latest codebase as of @014c2c22e5a99d1135d7ea2e683260aa0b36e872. Aforementioned error:

```
Fatal error: Unsupported operand types in /var/www/vagrant/html/profiles/dosomething/modules/contrib/flag/includes/flag/flag_flag.inc on line 132
```

**Comment by DFurnes** [comment]
Trying to just rebuild my local from scratch to see if that fixes things (`vagrant destroy && vagrant up`).

**Comment by aaronschachter** [comment]
Let us know how the vagrant up / down goes.  I haven't seen this error yet, there is a related d.o thread with a patch here for reference. https://www.drupal.org/node/1925922#comment-8806105

**Comment by aaronschachter** [comment]
@DFurnes says a `vagrant destroy` and `vagrant up` seems to have fixed.

**Comment by aaronschachter** [comment]
Reoccurring for @DFurnes and per Hipchat convo  this seems to fix:

```
ds pull stage
drush cc all
ds pull stage --db
drush cc all
```

The d.o. thread has later comments from the user who submitted the patch, sounds like it's more DB weirdness than it is code in the Flag module.  

I still haven't run into this one yet.

**Comment by aaronschachter** [comment]
Noooooo!  I've seen this now.  I ran a `drush updb` locally on a branch I'mw orking on, and get 

Fatal error: Unsupported operand types in /var/www/vagrant/html/profiles/dosomething/modules/contrib/flag/includes/flag/flag_flag.inc on line 132

I ran drush cc all, and then it found some stuff I did wrong (was including a wrong file).  Fixed that stuff and the error went away.

**Comment by aaronschachter** [comment]
FYI I'm seeing this as I'm trying to debug #1746 by commenting out various cache configurations in the settings.php and settings.local.php file.
