### ISSUE TITLE
Header: Arrow is overlapping handwritten text

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2612]
Please update to be more consistent with mocks. 

![screen shot 2014-06-19 at 1 58 20 pm](https://cloud.githubusercontent.com/assets/6550604/3331308/6573cfc6-f7db-11e3-8d07-7260eb60cb61.png)
![screen shot 2014-06-19 at 1 59 24 pm](https://cloud.githubusercontent.com/assets/6550604/3331315/752d9c62-f7db-11e3-8487-efa7859f5bd2.png)

**Comment by mikefantini** [comment]
@tjrosario did we review on mobile as well? I noticed it slightly going over the button on my iphone5
