### ISSUE TITLE
Congratulations to: Update to hard coded language. 

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2613]
Please remove this !

:)

![screen shot 2014-06-19 at 2 15 25 pm](https://cloud.githubusercontent.com/assets/6550604/3331557/05252c8e-f7de-11e3-9c8c-a4fd6a1254ea.png)

**Comment by aaronschachter** [comment]
This is stored in a variable.  However, it's not editable.  

![screen shot 2014-06-19 at 2 27 39 pm](https://cloud.githubusercontent.com/assets/1236811/3331723/abdee9ba-f7df-11e3-9cbe-3f28ebd188d3.png)

**Comment by aaronschachter** [comment]
Once #2614 is deployed to stage / production, this can be fixed by manually editing the copy at `admin/config/dosomething/dosomething_campaign`

**Comment by aaronschachter** [comment]
Fixed on staging via `admin/config/dosomething/dosomething_campaign.`  Can close once we deploy to prod and make the same manual copy change.
