### ISSUE TITLE
Krumo message colors

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2625]
Dev wishlist issue:  The `.messages` class in neue sets all the krumo data to white, making it very tough to read on the yellow.

:( 

![screen shot 2014-06-20 at 10 23 14 am](https://cloud.githubusercontent.com/assets/1236811/3341231/73d746e6-f886-11e3-8b7f-e2811bfe62a0.png)

Add a class for something like `.messages .krumo-root` to set the text color to somethign darker to make for happier development / debugging.

:) 

![screen shot 2014-06-20 at 10 23 48 am](https://cloud.githubusercontent.com/assets/1236811/3341243/8551714e-f886-11e3-8bf0-1cef6085a4fb.png)

**Comment by DFurnes** [comment]
I feel like we need to commemorate this moment. Aaron's first CSS! :tada: 

Also yeah this sucks. Will patch for sure.
