### ISSUE TITLE
Reportback: Update quantity count to exclude flagged

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2639]
Now that editors can flag reportbacks, update the `dosomething_reportback_get_total_campaign_reportback_sums` to exclude any reportbacks which have been flagged with the `flagged_reportback` flag.

@angaither Any reason to keep / update the `dosomething_reportback_get_total_campaign_reportbacks` function ?

**Comment by angaither** [comment]
Not sure if that's something we or editors ever need to know within the app vs updates from the data team... 
though we aren't using it currently
cc @mikefantini
