### ISSUE TITLE
SMS Template: Sources in modal formatting is off

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2643]
![screen shot 2014-06-23 at 3 24 48 pm](https://cloud.githubusercontent.com/assets/6550604/3362675/1ce95256-fb0c-11e3-9102-b3298cfc4968.png)

Can we make these numbers superscript and in line that way the line spacing is fixed and readability increases?

**Comment by mikefantini** [comment]
We should also:
- [x] add bullets the facts
- [x] remove bullets from the sources
- [x] add sources treatment we have on action page to this modal (i.e. tap sources and sources appear)

Closing out #1664 since it's a less detailed duplicate at this point
