### ISSUE TITLE
Grey bar behind CTA on 11-facts

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#2645]
The CTA on 11-facts needs to follow the CTA design conventions on the site (with the grey bar). cc @crystalruthbell

**Comment by DFurnes** [comment]
Yup, we had to make a little compromise to get that implemented quickly. @weerd is planning on making a second pass sometime this week to clean up all of that code, I think.

**Comment by weerd** [comment]
The CTA in the middle was specifically requested to not have a background and top gray bar though :\

How it appears in the design shows no background stuff: https://github.com/DoSomething/dosomething/issues/2451

**Comment by joolaay** [comment]
Yes - this was my mistake. The mock was snipped from optimizely, where we weren't able to include the grey bar. I mentioned in the text that it should look exactly like the other CTAs, but I should have been more descriptive in specifically noting that the grey bar should be there or checked in with you about it.

**Comment by joolaay** [comment]
I'm sorry for the confusion @weerd

**Comment by weerd** [comment]
okie doke :)

**Comment by weerd** [comment]
@tjrosario moving this over to you. You're going to have some weird margin issues. Might be a good opportunity for you to refactor the 11 Facts page to use the `.container` stuff? What say you @barryclark ?

**Comment by barryclark** [comment]
Sounds like a good shout dudes. Wanna tackle this one @tjrosario?

**Comment by tjrosario** [comment]
Sure.  @weerd the fact page is already using the refactored `.container` pattern.  

@julielorch screenshot below of what it will look like.

![image](https://cloud.githubusercontent.com/assets/1566749/3400180/1ef95436-fd43-11e3-851a-08899f98dfbb.png)

**Comment by joolaay** [comment]
@crystalruthbell this looks good to me. Good by you?
