### ISSUE TITLE
[Campaign Close] Overlapping Text

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2648]
When I was running testing today, I was testing under Windows XP using IE 8 and there was some overlapping text in the banner throughout the website. 
![banner issue ie xp 2](https://cloud.githubusercontent.com/assets/7773483/3364308/bd1df536-fb1d-11e3-9201-a9a3a2d51d73.png)

![banner issue ie 8 xp](https://cloud.githubusercontent.com/assets/7773483/3364309/bd1e6ee4-fb1d-11e3-8bd3-77b3292fc2b0.png)

**Comment by DFurnes** [comment]
Yep, the rem unit polyfill we're using seems to have broken. Strangely, it's working perfectly on staging over HTTPS, so I'm not sure what is different between those two environments. I'll look into it tomorrow.

**Comment by DFurnes** [comment]
Should be fixed!
