### ISSUE TITLE
[Campaign Close] Sign Up Overlapping Text

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2649]
Again when running testing using XP and IE 8, there was overlapping text, but this time it was on the sign up button. 
![sign up overlap ie8 xp](https://cloud.githubusercontent.com/assets/7773483/3364333/187b78cc-fb1e-11e3-9064-73faffe11895.png)

**Comment by mikefantini** [comment]
assigning over to @weerd

**Comment by weerd** [comment]
Yeah, this is due to a larger issue where `respond.js` is broken in IE8 so lots of stuff is broken. It otherwise works fine if I test in browser stack on my local where `respond.js` is working correctly.

Looping in @DFurnes since he was looking into the IE8 issues.

**Comment by weerd** [comment]
I'l double check this once the IE8 stuff is figured out. Leaving it open for now.

**Comment by barryclark** [comment]
@weerd @DFurnes Any updates on this? Ty

**Comment by weerd** [comment]
This is working now after @DFurnes fixed up the polyfill issues in IE8. Only problem now is that IE8 doesn't support `background-size` property so the arrows don't show, which seems like it's been the case for some time :sun_with_face: . Will close this issue and create a new one to address that!
