### ISSUE TITLE
[SMS game] - anon user no texts sent and confirmation page incorrect

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2653]
Anon user, on chrome, entered my name, my number, and 55555555555555555555 as friend's number. Form submitted and took me to this view:

![image](https://cloud.githubusercontent.com/assets/6330971/3365323/37367056-fb2c-11e3-98f6-fb5587bc569e.png)

no texts were received

**Comment by mikefantini** [comment]
@barryclark mentioned that @apatheticslacker could help re-create. If you need help re-creating @aaronschachter just let Diego know.

**Comment by aaronschachter** [comment]
I can't replicate in Chrome or Firefox in mac. we'll see if still an issue once #2655 is in.

**Comment by apatheticslacker** [comment]
I tried recreating it just now, and it doesn't let me move on due to having an invalid number. 

**killed the image from here as I think it had your cell number in it, Diego - Barry**

**Comment by aaronschachter** [comment]
That is a good thing!  If you and @mikefantini can no longer create I think we can close this.

**Comment by mikefantini** [comment]
@apatheticslacker it wasn't tied to entering an invalid number, it also happened to me when I just entered my name and number and submitted the form

**Comment by apatheticslacker** [comment]
@mikefantini I ran testing again and I had no issues yet again with signing up. Got a screen recording of it and it's up on screencast, though just ignore the last 30 seconds or so of the video [couldn't for the life of it figure out how to stop the recording...] Not sure if this just can't replicated on my machine, but its sent me to the right conformation page every time now. 
http://www.screencast.com/users/qaasst/folders/Default/media/916b9e87-da8e-4bf7-b154-c0453cffea56

**Comment by mikefantini** [comment]
alright I'll close out for now. @apatheticslacker can you please keep your eyes out for it? If I get time I'll try poking around a bit again, but hopefully some of the other issues we closed will resolve this weird behavior
