### ISSUE TITLE
[SMS game] - form submits with invalid number

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2654]
![image](https://cloud.githubusercontent.com/assets/6330971/3365276/86bf3780-fb2b-11e3-9bb3-ef57faf645b5.png)

I also get validation on the form itself (i.e. field shakes and error message appears above the form) before the form submits.

Form only submits upon the first time you try to submit. Otherwise you just get the error on the form itself.

Ideally the form just wouldn't submit at all if there was an error.

Happened on IE11 and chrome on windows 7

Also some inconsistent behavior. Sometimes page reloads, sometimes it takes you to same URL but /campaigns appears on the page (see: #2653)

cc: @aaronschachter

**Comment by aaronschachter** [comment]
I believe this is because the friend's phone number actually isn't required on the bender side. Will see if #2655 fixes.
