### ISSUE TITLE
[SMS game] - make all friend fields required

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2655]
All friend cell number fields should be required to submit the form. The user should not be able to submit the form without providing all three of these.

**Comment by mikefantini** [comment]
cc: @julielorch

**Comment by aaronschachter** [comment]
assigning to myself.

![](http://media.giphy.com/media/8fXIoMfISpIuQ/giphy.gif)

**Comment by joolaay** [comment]
Excellent gif.
