### ISSUE TITLE
[SMS game] - remember anon user's name when creating an account post-share

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2656]
If I submit the SMS form as an anonymous user and then go to create an account on the confirmation page, it would be sweet if DS remembered my first name.

Again, super low priority.

**Comment by barryclark** [comment]
@aaronschachter I'd vote to pass on this one, as it's likely going to take a lot of dev time for a low amount of user value. Thoughts?

**Comment by aaronschachter** [comment]
I would agree. We would need to store a cookie for the user's name, which isn't so bad but kinda feels a little shady. Although yeah, then there's extra code to write whenever we have a login form to check for that cookie. And how long should the cookie last for? This is very similar issue to #2652

**Comment by barryclark** [comment]
@mikefantini Are you cool with closing this for reasons above? ^^

**Comment by mikefantini** [comment]
yeah we can close both.. not critical just wanted to make notes for how to make it better but definitely a user delight thing and we're not there yet.

**Comment by barryclark** [comment]
Thanks @mikefantini :rainbow:
