### ISSUE TITLE
[SMS game] - accept iPhone default phone number structure

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2657]
We need to accept numbers that are formatted as +1 (212) 555-5555 

This is how my iPhone automatically formatted a friend's number and when I went to copy and paste that number into the field I got an error message.

**Comment by aaronschachter** [comment]
The function `dosomething_user_clean_mobile_number` doesn't like this format because it beings with a 1, therefore the string length is greater than 10 and the function returns `FALSE`.

Assigning to myself and tagging as bender.  I think easiest solution for now is just to remove that leading 1.
