### ISSUE TITLE
Move template helper functions into helpers.inc in the theme.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#2663]
Move any template helper functions from dosomething_helpers into [helpers.inc](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/includes/helpers.inc) in the theme.

References #2647.

**Comment by angaither** [comment]
going to close this one, unless you have specific functions you want moved @DFurnes
