### ISSUE TITLE
[SMS Game] Overlapping Elements

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2678]
I was running some more tests with browserstack using IE 8 on XP and there's a few overlapping elements on the site. 
First Part: 
![image](https://cloud.githubusercontent.com/assets/7773483/3390460/3d2ce156-fc9f-11e3-8112-f1bf965159ff.png)
Second Part: 
![image](https://cloud.githubusercontent.com/assets/7773483/3390471/66f9771a-fc9f-11e3-9c9b-a3316e4446ff.png)

**Comment by barryclark** [comment]
@DFurnes Any update on this one?

**Comment by DFurnes** [comment]
Fixed on staging!
