### ISSUE TITLE
[Campaign Close] Disable SMS Reportbacks for Closed Campaigns

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2686]
Comeback Clothes is closed, but users are able to (and still are) submitting reportbacks.  This will mess with totals calculated within the app (which at this point are just for editors to view within the Closed admin form)

The quick fix would be to just remove the relevant code from `dosomething_sms`, but it would be ideal to have an admin config to enable and disable campaigns.  Although -- I suppose the plan is to ditch this module completely, @jonuy ?

**Comment by mikefantini** [comment]
@jonuy @aaronschachter @marahml we should probably have a better ux solution than just removing code... could we change the message that the user gets when they try to trigger the report back?

**Comment by jonuy** [comment]
Module will eventually get removed, and we could get there soon if we get an endpoint setup that would allow us to submit a report back to Drupal via web services.

But yea, to close these things out on SMS, there's always gonna need to be a component on Mobile Commons that needs to be disabled or modified. So for this... we could 1) yea, remove the code. 2) just remove the mData connection and keywords on Mobile Commons? @marahml ?

**Comment by aaronschachter** [comment]
Option 2 sounds nice here because we wouldn't have to deploy anything.

**Comment by marahml** [comment]
@jonuy @aaronschachter @mikefantini can we just change the messaging in the keyword so that the user knows whats up - but also disconnect the mdata?

**Comment by jonuy** [comment]
@marahml Yea, that was the idea with the 2nd option I mentioned - except without the changing of the messaging in the keyword. I was thinking we'd remove the keyword entirely... we've had to do it a bunch of times before when we needed to recycle keywords for new campaigns. Are you ok with that?

**Comment by marahml** [comment]
@jonuy that works! as long as the RB keyword isn't being advertised anywhere, we can deactivate and use for other flows.

**Comment by aaronschachter** [comment]
Sounds good. This should then become part of the process for closing a campaign... which we should add to the wiki we need to build for administering the site.  Once the keyword is de-activated, this issue can be closed.  @marahml Is that something to handle on your end?

**Comment by marahml** [comment]
I think so - unless its in an mdata. @jonuy what is the keyword? I don't see a CC campaign in mobile commons anymore.

**Comment by aaronschachter** [comment]
The last reportback received was 6/24, so it seems that this has been closed out on SMS.  @jonuy can you confirm?

**Comment by aaronschachter** [comment]
This should be closed out once we have an Editors Guide published for how to close out a campaign cc @mikefantini

**Comment by mikefantini** [comment]
editors guide on closing a campaign has already been distributed to the campaigns team so we're good on that front.

@julielorch is putting together a more comprehensive editors guide this quarter for all editorial needs
