### ISSUE TITLE
[User Profile] Style 'staff pick' flag

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#2697]
The flag is in a PR right now, but looks gross.
![](http://cl.ly/image/0J0u1445101b/Screen%20Shot%202014-06-26%20at%205.27.52%20PM.png)
Refs #2126

**Comment by DFurnes** [comment]
Should be fixed by DoSomething/neue#310.

**Comment by weerd** [comment]
Fixed!

Updated in Neue -> https://github.com/DoSomething/neue/pull/310
