### ISSUE TITLE
Invalid campaign signup nids

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2705]
The Message Broker system is turning up user campaign signups to non campaign nodes (nid). An example:

```
    [email] => aruderman@dosomething.org
    [campaigns] => Array
        (
...
            [6] => Array
                (
                    [nid] => 1194
                    [signup] => 0
                )
...
```

nid 1194 (https://www.dosomething.org/node/1194) is an image -> Image Floating Polar Bear.

**Comment by aaronschachter** [comment]
@DeeZone This must be happening becuase Staging node nid's do not match production.

http://staging.beta.dosomething.org/node/1194

**Comment by deezone** [comment]
Ah, good catch! And the flag / switch in `dosomething_mbp` will prevent this from happening further at least for campaign details. I'll simply remove the entries from the test users as they're a special case signing up for campaigns via beta.

Perfect.
