### ISSUE TITLE
[campaign runs] - error when trying to access run edit view

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2707]
Error message when trying to edit campaign runs:

![image](https://cloud.githubusercontent.com/assets/6330971/3415679/b361639e-fe23-11e3-9c8a-bcc051ed9723.png)

**Comment by angaither** [comment]
Seeing this locally 

![](http://cl.ly/image/0d2m2544220B/Screen%20Shot%202014-06-27%20at%202.51.32%20PM.png)

**Comment by angaither** [comment]
@mikefantini if you need to edit this to remove the winners for now you can go to the node
https://beta.dosomething.org/node/2329 and remove the winners by editing the content in the field collection

![](http://cl.ly/image/1Z2W222F442I/Screen%20Shot%202014-06-27%20at%202.59.48%20PM.png)

**Comment by mikefantini** [comment]
@angaither got it thanks.. once we deploy today though one will be able to edit the campaign run node itself though correct?

**Comment by aaronschachter** [comment]
yes @mikefantini the broken edit form is fixed by #2710
