### ISSUE TITLE
Vagrant SSL not functioning

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#271]
Using Vagrant 1.3.5 and VirtualBox 4.3.4, doing a clean vagrant up I get SSL error.

![screen shot 2013-12-16 at 10 26 47 am](https://f.cloud.github.com/assets/1236811/1756292/39a80390-6671-11e3-939f-1e22756ea38a.png)

Working around this by disabling securepages.

**Comment by desmondmorris** [comment]
@angaither @mshmsh5000 @DeeZone anyone else experiencing this issue.  I cannot reproduce

**Comment by aaronschachter** [comment]
Ok this is magically working now.  I do not understand this magic.

I did a `vagrant reload`, then a `vagrant up` and a new `ds build --install` and SSH is working.
