### ISSUE TITLE
Content Search -- Title filter doesn't work for images

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2714]
Content search doesn't work for Image nodes.  Should remove the type from the filter, or get it to work.  Would be nice to search images by title, perhaps for the Search Image view.

Also could be nice to group all the Searches together under one menu group, `admin/content/search/images`, etc

**Comment by aaronschachter** [comment]
Update issue description and title.

**Comment by angaither** [comment]
this is a lie
https://www.dosomething.org/admin/content/search?title=trea&type=All&field_cause_tid=All&status=All&language=All
![image](https://cloud.githubusercontent.com/assets/645205/11602495/ab5f6e02-9aa8-11e5-8e00-dc5eea4d449a.png)
