### ISSUE TITLE
Add reportback image path to mbp payload

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2718]
Add the path to the image related to a campaign report back to the payload sent to mbp `dosomething_mbp_request('campaign_reportback', $params)` requests.

**Comment by deezone** [comment]
@aaronschachter Where can get the image id / url to the image uploaded with a campaign report back?

Looking at `dosomething_reportback_mbp_request()` I can see the submitted `$entity`:

```
ReportbackEntity Object
(
    [files_table:protected] => dosomething_reportback_file
    [log_table:protected] => dosomething_reportback_log
    [field_data_table:protected] => dosomething_reportback_field_data
    [entityType:protected] => reportback
    [entityInfo:protected] => Array
        (
            [label] => Reportback
            [base table] => dosomething_reportback
            [entity keys] => Array
                (
                    [id] => rbid
                    [label] => rbid
                    [revision] => 
                    [bundle] => 
                )

            [entity class] => ReportbackEntity
            [uri callback] => entity_class_uri
            [controller class] => ReportbackEntityController
            [module] => dosomething_reportback
            [views controller class] => EntityDefaultViewsController
            [fieldable] => 
            [static cache] => 1
            [field cache] => 1
            [load hook] => reportback_load
            [bundles] => Array
                (
                    [reportback] => Array
                        (
                            [label] => Reportback
                        )

                )

            [view modes] => Array
                (
                )

            [translation] => Array
                (
                )

            [schema_fields_sql] => Array
                (
                    [base table] => Array
                        (
                            [0] => rbid
                            [1] => uid
                            [2] => nid
                            [3] => created
                            [4] => updated
                            [5] => quantity
                            [6] => why_participated
                        )

                )

            [token type] => reportback
            [apachesolr] => Array
                (
                    [indexable] => 
                    [status callback] => 
                    [document callback] => 
                    [reindex callback] => 
                    [bundles changed callback] => 
                )

            [configuration] => 
        )

    [idKey:protected] => rbid
    [nameKey:protected] => rbid
    [statusKey:protected] => status
    [defaultLabel:protected] => 
    [rbid] => 123
    [uid] => 1700273
    [nid] => 15
    [created] => 1404157597
    [updated] => 1404157597
    [quantity] => 1
    [why_participated] => cuz
    [fids] => Array
        (
        )

    [node_title] => Momm-o-grams
    [noun] => cards
    [verb] => given
    [field] => 
)
```

**Comment by deezone** [comment]
Ideally I'd like to use `dosomething_image_get_themed_image($image_id, 'square', '300x300');` by getting the `$image_d` somewhere.

**Comment by aaronschachter** [comment]
A reportback can have multiple files, which are stored in the `$entity->fids`... but the one you've used as an example doesn't have any, which should not be the case (unless the reportback was flagged to delete files).

With a given File $fid, you can call `dosomething_image_get_themed_image_by_fid($fid, $style);` to get markup.

**Comment by aaronschachter** [comment]
Does the transactional fire upon every reportback update?  If so, then you'll know the reportback file that the user just submitted will have the largest `fid` value (we create a new File fid every time a user submits an image)

**Comment by deezone** [comment]
Currently only `dosomething_reportback_entity_insert()` calls `dosomething_reportback_mbp_request()` resulting in a transactional message. I assume the policy for report backs is only the initial submission should generate a transactional email? From the real-time dashboard perspective, this request is looking for every time an image is submitted but even the initial submission would be a good start.

Is it odd that on my local when I do a test reportback that includes a image in the submission the `$entity->fids` are empty?

**Comment by aaronschachter** [comment]
Try loading the entity after it's submitted, the $fids are calculated in the `construct` function for `ReportbackEntity`

```
$reportback = reportback_load($rbid).
```

Pretty sure that there's an issue or a spec somewhere that states the policy should only be on the first reportback submission and not for updates.  @mikefantini can you confirm?

**Comment by mikefantini** [comment]
that's @marahml's call

**Comment by deezone** [comment]
The ReportbackEntity Object output above is after `reportback_load()` based on:

```
/**
 * Implements hook_entity_insert().
 */
function dosomething_reportback_entity_insert($entity, $type) {
  if ($type == 'reportback') {
    // Reload entity to grab the relevant node variables.
    $reportback = reportback_load($entity->rbid);
    // Pass it into mbp request.
    dosomething_reportback_mbp_request($reportback);
  }
}
```

where ReportbackEntity Object output comes out of a print_r() in `dosomething_reportback_mbp_request()` detailed below.

```
/**
 * Sends mbp request for a reportback.
 */
function dosomething_reportback_mbp_request($entity) {
  if (module_exists('dosomething_user')) {
    $account = user_load($entity->uid);
    $params = array(
      'email' => $account->mail,
      'uid' => $account->uid,
      'first_name' => dosomething_user_get_field('field_first_name', $account),
      'campaign_title' => $entity->node_title,
      'event_id' => $entity->nid,
      'impact_verb' => $entity->verb,
      'impact_number' => $entity->quantity,
      'impact_noun' => $entity->noun,
    );
    echo('<pre>');
    print_r($entity);
    echo('</pre>');
    exit;
```

Should the `$fids` values not be populated at this point?

**Comment by aaronschachter** [comment]
Should be... double check the data?  The `$fids` are stored in `dosomething_reportback_files` table: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback.inc#L31

![rb_load](https://cloud.githubusercontent.com/assets/1236811/3436337/9f6f63d0-009f-11e4-8773-57c96db3506d.png)

**Comment by marahml** [comment]
@mikefantini @aaronschachter @DeeZone not sure im 100% understanding this string, but if the question is when should users get an email - right now it is only after their first report back. in the future it'd be great to thank them for adding more images.

**Comment by deezone** [comment]
@marahml A few related items being discussed in this issue but you've answered the one related to sending transactional email messages. Thank you.

@aaronschachter My take away based on @marahml response is the process could be adjusted to send a transactional message for each report back. This would address the needs of the real-time dashboard project's desire to display all report backs including the report back image.

Now back to the original issue of my efforts to get at the `fids` values.

**Comment by deezone** [comment]
@aaronschachter I'll need to sit down with to you as I'm not able to get a `fids` value out of `$reportback = reportback_load($entity->rbid);` in `dosomething_reportback_entity_insert($entity, $type)`. WIthout the `fids` value I'm blocked on this issue.

**Comment by aaronschachter** [comment]
My apologies @DeeZone  -- tested this out for a new reportback and indeed there are no `$fids` present when the Reportback is loaded in `dosomething_reportback_entity_insert`.  What's the timeline on this one?

**Comment by deezone** [comment]
This functionality comes out of  a request from @joshcusano and the real-time dashboard project. I'll leave it to Joe to define the timeline for this functionality.

**Comment by aaronschachter** [comment]
Actually I see why it's failing -- working on a fix.

**Comment by itsjoekent** [comment]
Thanks @aaronschachter

**Comment by aaronschachter** [comment]
Hm, not as easy as I thought. When do you need this by @deadlybutter ?

**Comment by itsjoekent** [comment]
Sooner is better than later, it's one of the few things left thats blocked

**Comment by aaronschachter** [comment]
@DeeZone Per #2777, I've added an `$inserted_fid` variable into the `dosomething_reportback_mpb_request` function. The `dosomething_image_get_themed_image_by_fid` function takes a File fid and style/size params... if you need to get the image URL you may need to investigate some of the functions it calls.
