### ISSUE TITLE
Campaign Close - Funky arrow in header

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2729]
![arrow](https://cloud.githubusercontent.com/assets/6550604/3448865/bf67af48-015e-11e4-81dd-7f094e835aab.png)

Screenshot above is from campaign closed state for comeback clothes

**Comment by tjrosario** [comment]
@crystalruthbell are you still able to reproduce this?  I've checked staging and prod and can't seem to.

**Comment by tjrosario** [comment]
This is not an issue anymore.
