### ISSUE TITLE
Closed Campaign - Center participants

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2731]
Both the left and right columns featured below should be vertically centered on either side of the vertical rule. 

The image below shows that happening on the right but not left. Page = COMEBACK CLOTHES

![screen shot 2014-07-01 at 4 32 20 pm](https://cloud.githubusercontent.com/assets/6550604/3460375/b9f1f4e8-0216-11e4-9e91-b8159e93c8ed.png)

**Comment by tjrosario** [comment]
Missing screenshot :)

**Comment by crystalruthbell** [comment]
the trickery. @tjrosario I have included for your eyeballs benefit.
