### ISSUE TITLE
The Hunt - Unreadable arrows

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2739]
It seems like this arrows and handwritten text have started to cause a lot of trouble so just grab me if you think we should talk through a better system for this stuff. 

Here is how the header image on the hunt is overlapping text and making it less readable. 

![screen shot 2014-07-02 at 12 56 46 pm](https://cloud.githubusercontent.com/assets/6550604/3459207/28e90574-020a-11e4-9fea-a867b2805979.png)

**Comment by tjrosario** [comment]
This has been resolved.
