### ISSUE TITLE
Search - Photos are coming up as results

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2741]
They link off to a 404 page. 

![screen shot 2014-07-02 at 1 05 24 pm](https://cloud.githubusercontent.com/assets/6550604/3459302/39ac6166-020b-11e4-9a19-b01c1f65c02e.png)

**Comment by blisteringherb** [comment]
Fixed this yesterday, for some reason the image and other content types that shouldn't show up in search were selected in the settings.  They are set correctly in the exported solr settings, but it appears that those settings weren't respected for some reason.
