### ISSUE TITLE
Action Page - Styling Error

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2744]
Styling is getting weird in step two (spacing and header style coloring)
https://www.dosomething.org/campaigns/hunger-games

![screen shot 2014-07-02 at 2 37 59 pm](https://cloud.githubusercontent.com/assets/6550604/3460524/0daed8e8-0218-11e4-9f0c-590ebaa054d0.png)

**Comment by tjrosario** [comment]
This is resolved.
