### ISSUE TITLE
Campaign Close - New scholarship winner background

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2747]
We want to add a background to the background of the action page's scholarship winner section at the bottom. . 

DEFAULT FOR ALL CLOSED PAGES
![stars_purple300-01](https://cloud.githubusercontent.com/assets/6550604/3462297/0b5ab1a2-022c-11e4-9c50-4f1415d96e01.jpg)

CORPORATE PARTNER CUSTOMIZATION FOR COMEBACK CLOTHES
![stars_red300-01](https://cloud.githubusercontent.com/assets/6550604/3462302/1fe6f8c4-022c-11e4-9e0e-70a37036b788.jpg)

**Comment by aaronschachter** [comment]
This will require bender work too if each campaign can have a customized background.

**Comment by crystalruthbell** [comment]
@aaronschachter sorry, I was under the impression the functionality for customizing backgrounds here was already built. Yes, we would need that for certain.

**Comment by mikefantini** [comment]
@aaronschachter do we have to make it customized? Could we instead use one image and just use the alt color to customize as needed since it seems like only the color would change.

**Comment by aaronschachter** [comment]
I'm pretty sure we would still need to use a separate file to display the image with a different color, unless @DFurnes @weerd can work some kind of crazy css magic to apply a hex value to change the color the image...

**Comment by DFurnes** [comment]
I think a transparent PNG overlaid over the hex color would do the trick - @weerd, thoughts?

**Comment by weerd** [comment]
Agreed! :dancer:
