### ISSUE TITLE
Scholarships - Updated Language

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2750]
We need to update all handwritten scholarship call outs to say:
Win a $10,000 scholarship!

Below are the three locations where this needs to be updated. Please grab me to help with where line breaks could should/go.

SMS GAME TEMPLATE

![screen shot 2014-07-02 at 12 56 30 pm](https://cloud.githubusercontent.com/assets/6550604/3462622/631b817a-022f-11e4-8d56-0f70d6947f8a.png)

GROUPED CAMPAIGN TEMPLATE (its a bug, I have an issue in for it)

![screen shot 2014-07-02 at 12 56 46 pm](https://cloud.githubusercontent.com/assets/6550604/3462620/5e04d0a6-022f-11e4-82ba-161c8f20eafc.png)

PITCH PAGE
![screen shot 2014-07-02 at 1 11 23 pm](https://cloud.githubusercontent.com/assets/6550604/3462616/591820ca-022f-11e4-85ec-5f95d245c162.png)

**Comment by barryclark** [comment]
Shooting over to @tjrosario, thanks!
