### ISSUE TITLE
User username not always saved as UID

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2753]
Inconsistent usernames -- not only for legacy imported users, but for new users which are  as well, sometimes they still have a random string set as their username (see #2632).

Makes it difficult to select users within the Winners field collection.

**Comment by angaither** [comment]
For some reason the `db_update` in `dosomething_user_user_insert` isn't always running, maybe we can add logging in there to see what's going on?

**Comment by mikefantini** [comment]
@aaronschachter @angaither is this issue still valid?

**Comment by angaither** [comment]
Yeah, this for sure still happens. It's very inconsistent

**Comment by namimody** [comment]
Hey @angaither could you pop a t-shirt label on this one? Thanks!

**Comment by angaither** [comment]
this happens on profile save now, it's getting overwritten each time.
