### ISSUE TITLE
Campaign Close - Additional call out

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2761]
Add an additional handwritten call out to the campaign close template for an OPTIONAL custom text field that would give content creators the opportunity to celebrate their wins. 

We we can offer this for both sides that would be GREAT but if we can only build on one side then please format as mocked below on comeback clothes. 

![screen shot 2014-07-03 at 12 09 15 pm 1](https://cloud.githubusercontent.com/assets/6550604/3472521/b1d67958-02cc-11e4-9711-bd21b53f05e8.png)

Color is full black!

**Comment by crystalruthbell** [comment]
@mikefantini this is a new request so I just wanted to loop you in to prioritize.

**Comment by mikefantini** [comment]
@tjrosario do you have any thoughts on character count for this?

@crystalruthbell what types of callouts would we want here? We need to have a few more guidelines here before we can built it out.

**Comment by crystalruthbell** [comment]
@mikefantini it would likely be a remark about what our goal was if the goal was crushed.

**Comment by crystalruthbell** [comment]
@mikefantini can you update me what the status of this is? https://trello.com/c/eK33LZZc/635-update-campaign-close-template-with-locations-for-handwritten-text

**Comment by angaither** [comment]
hmm, closing because hot module?
