### ISSUE TITLE
[campaign template] - Do It image not showing up on mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2765]
On mobile, the field_image_step_gallery from the Do It gallery is not being pulled in properly.

It should be pulling in the landscape crop that is uploaded.

**Comment by barryclark** [comment]
@tjrosario Could you take a look at this one please? We need to get a fix on prod by EOD Monday. Thanks!

**Comment by mikefantini** [comment]
photo should be displayed like this:

![image](https://cloud.githubusercontent.com/assets/6330971/3497729/3e56ef4c-05ee-11e4-82ed-38f7868e2960.png)
