### ISSUE TITLE
Play nice with Pantheon

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#277]
Make necessary changes to make this package deployable to Pantheon.  Things like:
- Change drupal core to the Pantheon maintained drops-7 core
- Move settings.php into repo
- Add custom domains
- Install SSL certificate
- Deploy strategy
- Remove Varnish - http://helpdesk.getpantheon.com/customer/portal/articles/425726

**Comment by barryclark** [comment]
@desmondmorris Moving this to 0.3 release pending International work, since we're not deploying the main app to Pantheon.
