### ISSUE TITLE
Campaign object caching

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2771]
Implement a custom cache table to store the Campaign object returned by `dosomething_campaign_load`.
- [ ] Insert/update cache record upon node insert/update
- [ ] Return cache record within `dosomething_campaign_load`
- [ ] Add extra param to `dosomething_campaign_load` to bypass cache

**Comment by deezone** [comment]
Perhaps insert on node create - type "campaign" or "grouped campaign"?

**Comment by aaronschachter** [comment]
Needs both insert and update.  Right now there is no class / endpoint for a Grouped Campaign.. but we can add that in.  I guess we need it for transactionals?  Or is that a separate transaction (campaign vs campaign_group)

**Comment by deezone** [comment]
In terms of the Message Broker they're the same - a user campaign activity can be either. Ideally they would both be available in a request to /api/v1/content/<nid>
