### ISSUE TITLE
Campaign type and status not set

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2776]
The Message Broker system uses the **campaign type** and campaign **status** field values to determine if a user campaign signup should be included in their weekly digest message. It appears that many of the non staff pick campaigns do not have values in these fields even though the Campaign type field is required.

Do all of the campaigns need to be reviewed to set the values for these fields? Currently these campaigns are being skipped due to the missing values. This is not a blocker but less than ideal.

**Comment by aaronschachter** [comment]
Ideally we should change the MB system to use values `$campaign->status` and `$campaign->type` from the Campaign class introduced by `dosomething_campaign_load`: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc#L66

The class handles the fact that not all campaigns have been saved with the default values by calling `dosomething_campaign_get_campaign_type` and `dosomething_campaign_get_campaign_status`. (although it'd be fairly simple to set and save default values in an update hook for nodes which don't have it: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.install#L61)

But the purpose of the class is to avoid having to know which functions to call or which key in a field array holds the correct value.  I have been chipping away at using the class in the preprocess and in the MBP cache request, but it will take a while before its used system-wide..

**Comment by deezone** [comment]
The Message Broker system has made the switch to using the `api/v1/content/<nid>` endpoint for all campaign details. Once it's in production I'll start the process of removing the `mb-campaign-cache` code from `dosomething_mbp.module`.

I'm not sure what has changed but it appears more of the campaigns are returning values for `$campaign->status` and `$campaign->type` when the `api/v1/content/<nid> endpoint is called.

The specific logic that's filtering the campaign basic values is:

```
    foreach ($campaigns as $campaign) {
      if ((isset($campaign->status) && $campaign->status == 'active') &&
          (isset($campaign->type) && $campaign->type == 'campaign') &&
          (isset($campaign->image_cover->src))) {
```

 It appears that it's the lack of `$campaign->image_cover->src` values that's preventing some of the  campaigns from being included in user digest messages. Is it possible to get the staging campaign entries populated with the campaign image assignments to match the production site?

**Comment by aaronschachter** [comment]
It's do-able but we currently don't have any open issues for it (exporting prod db to stage).  However using QA to test should unblock you, since it has prod data.  I believe QA is only available while connecting to VPN though

Re: more values returned for status and type using the Campaign class:  https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc#L79

**Comment by aaronschachter** [comment]
@DeeZone Is this still a valid issue?
