### ISSUE TITLE
Campaign custom settings autocomplete

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2783]
Drupal core only ships with default autocomplete paths for taxonomy and users.

Ideally add two new paths to provide autocomplete Form API elements for:
- Image nodes, for the Alt Header image nid variable
- Files, for the Alt BG File fid variable

**Comment by angaither** [comment]
They are just normal fields. Which is kinda sucky from an admin UX perspective.

#### Example

Setting the "Who We Are" link for US visitors in Theme Settings:

<img width="354" alt="screen shot 2015-10-28 at 3 55 53 pm" src="https://cloud.githubusercontent.com/assets/583202/10801163/637e8566-7d8c-11e5-9dc6-589c7afe3210.png">
:speech_balloon: _Help where's my autocomplete???_

<img width="354" alt="screen shot 2015-10-28 at 3 55 39 pm" src="https://cloud.githubusercontent.com/assets/583202/10801179/75836592-7d8c-11e5-9dfb-566368bb4714.png">
:speech_balloon: _"Alright I guess I'll type this strange and arcanely formatted entry."_

fin.
