### ISSUE TITLE
[Campaign Close] Search Bug 

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2800]
I was running through some testing on prod when I noticed while searching for the Mind on my Money campaign, I noticed part of the search seems to be broken... ![image](https://cloud.githubusercontent.com/assets/7773483/3527138/f8cb93e8-0781-11e4-83e4-70c245906692.png)

**Comment by mikefantini** [comment]
closing this issue since other search updates will resolve this.
