### ISSUE TITLE
[SSHFS] Creating new files creates additional "._filename.ext" files in same directory.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2801]
```
SSHFS version 2.4 (OSXFUSE SSHFS 2.4.1)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.7.0
```

@sergii-tkachenko mentioned it's a SSHFS issue and will need to look into it.

**Comment by sergiitk** [comment]
Few references to investigate in future:
- http://stackoverflow.com/questions/21825237/how-to-prevent-dot-underscore-files
- https://code.google.com/p/macfusion/issues/detail?id=146

**Comment by sergiitk** [comment]
For history: created an issue, that, I believe, will help resolve this
https://github.com/fabiokr/vagrant-sshfs/issues/23

**Comment by angaither** [comment]
deprecated 💥
