### ISSUE TITLE
[campaign close] - too much space in Buzz section

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2808]
We should keep the spacing consistent in The Buzz section regardless of what content begins the section:

![image](https://cloud.githubusercontent.com/assets/6330971/3543751/40881330-0865-11e4-8161-ac727ecde39e.png)

![image](https://cloud.githubusercontent.com/assets/6330971/3543743/2eca7a98-0865-11e4-8bf0-8fc5c6195673.png)

cc: @crystalruthbell not sure if you have any other thoughts or guidance

**Comment by tjrosario** [comment]
This is no longer an issue.
