### ISSUE TITLE
[Refactor] Implement the use of Picturefill polyfill across site for responsive image solution.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#2813]
Using picturefill JS polyfill, we can use the technology of tomorrow today!

![ep19](https://cloud.githubusercontent.com/assets/105849/3554834/b54e48a0-0910-11e4-96bb-db193c564722.jpg)

Implement the use of picturefill and how images should be marked up throughout the site for content images.

**Comment by mikefantini** [comment]
@weerd once you're done with SEO stuff and MCC work let's check in on this guy.

If other work is blocked, it'd be great to get to this since it looks pretty whack on mobile right now:

![photo 20](https://cloud.githubusercontent.com/assets/6330971/3630839/caed597c-0eaf-11e4-93ef-7e632f23c62c.PNG)
