### ISSUE TITLE
PHP Notice: Paraneue DS Preprocess page

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2858]
Notice: Trying to get property of non-object in paraneue_dosomething_preprocess_page() (line 126 of /var/www/vagrant/lib/themes/dosomething/paraneue_dosomething/includes/preprocess.inc).

Git blaming you, @DFurnes 
https://github.com/DoSomething/dosomething/commit/ff53418b6202e425ae0255b4dafe302194171d34

**Comment by DFurnes** [comment]
:no_good:

**Comment by aaronschachter** [comment]
This is the code that checks is for a string int he query string after the MCC Google Form is submitted and displays a message.  I suggest we close this issue by just removing that snippet of code compltely, as the Google Form has since been removed from the site (but available as a page callback).  

It would help cleanup the error logs.

**Comment by DFurnes** [comment]
Totally, perhaps emoji wasn't the best form of acknowledgement. Will take care of tomorrow.
