### ISSUE TITLE
Campaign API: Return timestamps for season values

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2868]
Need to coordinate with @DeeZone but ideally the data returned should be timestamps and not date strings, to keep consistent with the `end_date` property.

**Comment by angaither** [comment]
closing, them seem to still be date strings, but both values are consistant
![image](https://cloud.githubusercontent.com/assets/645205/11192417/09628f72-8c6f-11e5-9e93-2aac625f0bed.png)
