### ISSUE TITLE
Field Collection revision bug

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2872]
Trello card: https://trello.com/c/pih0Toue

Details:
Nid: 2427
`field_step_pre` (During Tips) contains three `field_collection_item` values. Field Collection Item id 1279 is the one in particular is displaying an old revision.

When I first opened up the QA db to inspect, the revision_id was set to 22476, which contains the correct text "Play your fun, upbeat, and energetic playlist as you trash your items.
"
(with a paragraph break)

Wondering if the paragraph break was somehow borking things, I resaved nid 2427 without the line break hoping for a magical quick fix / dumb bug.  However, the data in `field_revision_field_compound_text_copy` now points to revision_id 19370, which is consistent with what's being displayed, as the value in 19370 displays "Make a fun, upbeat, and energetic playlist to play at your bash".

There have been new commits to the dev branch of Field Collection since the commit we're working from, but yet to investigate if each could potentially fix.
https://www.drupal.org/node/947174/commits -- We are pulling from the commit on 4/15/2014 (http://cgit.drupalcode.org/field_collection/commit/?id=ae778f2) which we needed to fix #2561

**Comment by aaronschachter** [comment]
On beta, I deleted the faulty field_collection_item (1279) and recreated it, and it's displaying the correct data.  Keeping this open for now to investigate further to see if it can be replicated.

**Comment by aaronschachter** [comment]
This is occurring for me on http://staging.beta.dosomething.org/about/fantiniz-partnerz

I added and edited a bunch of the Gallery images using the Entity Connect module... and it's making me think that it's actually Entity Connect which seems to be messing up the revisions here.  It would explain this weirdness https://trello.com/c/89TsXoUe

Noticed the AARP image description did not display anymore.  Edited it.  Now it displays the old version before I've edited it.

**Comment by angaither** [comment]
We are kind of far behind on the field collection module. 
It looks like [this commit](https://www.drupal.org/node/2125017) might be the issue we are experiencing.
Might be worth a shot upgrading the module locally and on stage to see if it fixes the issue.

**Comment by aaronschachter** [comment]
Field Collection is still actively being developed, new commits as of this week. https://www.drupal.org/node/947174/commits

This is still an open issue.

**Comment by aaronschachter** [comment]
Closed by https://github.com/DoSomething/dosomething/commit/cf1130a6f2c999616f36ead6fb1436f1b3abf975
