### ISSUE TITLE
dosomething_page: content type

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#29]
We need a basic page content type managed by a feature.  The content type should include:
- Title
- Subtitle
- Body with a basic WSIWYG - this may be dependent on #24

**Comment by DFurnes** [comment]
@desmondmorris This is perhaps a bit late, but can we consider using something more restricted like Markdown rather than a full-fledged WYSIWYG editor? Those things spew out some really horrendous markup.

**Comment by desmondmorris** [comment]
Yeah def not too late.  We need to consider who our users are.  Will we need to train them up on Markdown.  I think a good balance may be to offer both and see what folks like.  We can and should only implement a very limited set of WYSIWYG functionality either way.

**Comment by DFurnes** [comment]
Are we thinking staff or users? If we're thinking users, then super-limited WYSIWYG is probably the right way to go. I'd be interested if we even need rich text formatting for users, though.

**Comment by aaronschachter** [comment]
Just something to consider, that in the long term, we'll have users creating campaigns, and we'll need a WYSIWYG, as I'd imagine Markdown would not be an option.

It's possible to configure the WYSWIYG to limit the number of options, so we could only allow a subset like Image, Link, List.

**Comment by aaronschachter** [comment]
Good point about whether or not users really need those options.

**Comment by mshmsh5000** [comment]
What about WYSIWYG that generates Markdown, or a helper interface? This is happening in a few places:

http://hallojs.org/demo/markdown/

http://developmentseed.org/blog/2012/june/25/prose-a-content-editor-for-github/

I've seen all kinds of numbskulls learn Markdown.

**Comment by aaronschachter** [comment]
Closing this and removing milestone until we have a proper spec for the content type..
