### ISSUE TITLE
Vagrant: Create environment variable for Varnish secret key

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#291]
`varnish_control_key` is hardcoded into settings.php, but it changes upon build.  Therefore, still getting errors upon cache clear:

WD varnish: Authentication to server failed!                        [error]
WD varnish: Recieved status code 101 running ban req.http.host ~    [error]
dev.dosomething.org && req.url ~ "/". Full response text: Unknown
request.

**Comment by desmondmorris** [comment]
Fixed in #292
