### ISSUE TITLE
Vagrant: SSH key goes missing.

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#293]
Never had this issue before, but suddenly I can't push to origin:

root@dev:/vagrant/html# git push origin fact_generator
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

@angaither is also experiencing this issue.  Just started happening to me, pretty randomly.  Made changes to settings to try to fix Varnish issue, but not sure why that'd bork SSH.

**Comment by aaronschachter** [comment]
A workaround for this is to execute the git commit commands outside of the Vagrant instance.  If this works for the long term, we can consider the issue closed.

**Comment by aaronschachter** [comment]
This happened to my personal laptop recently... doing a `vagrant destroy` and `vagrant up` seemed to do the trick.

**Comment by barryclark** [comment]
@aaronschachter close?

**Comment by aaronschachter** [comment]
Hasn't happened to me recently --  @angaither do you still get this issue ?  The vagrant destroy / up seemed to fix for me.

**Comment by barryclark** [comment]
Closing. Can always re-open if it comes back up.

**Comment by mshmsh5000** [comment]
For future reference: If you get GitHub auth issues within Vagrant, check in the host system if you have registered SSH keys:

`% ssh-add -l`

You should see something like

`2048 ef:67:f4:07:6b:2e:48:bc:45:c5:29:01:75:4a:77:4e /Users/mholford/.ssh/id_rsa (RSA)`

This is the key that your host system is able to pass into the Vagrant environment. If you don't see anything here, that's the problem. Try

`% ssh-add ~/.ssh/id_rsa`

Then

`% vagrant ssh`

Then, within Vagrant,

`% ssh git@github.com`

You should see

`Hi dosomething-machines! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.`

If this still fails, then there might be a Vagrant-side problem.
