### ISSUE TITLE
Search Bug: HTML encoding not recognized in search results

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3000]
Doing a search for The Hunt returned this suggestion  
![screen shot 2014-08-21 at 10 54 37 am](https://cloud.githubusercontent.com/assets/1865372/3997911/7554b34e-2943-11e4-9cbb-983dd955f9f3.png)

Which was based off the predominance of &quot; in other search results.
![screen shot 2014-08-21 at 10 54 45 am](https://cloud.githubusercontent.com/assets/1865372/3997912/7b55a488-2943-11e4-9490-f8c29e701146.png)

**Comment by blisteringherb** [comment]
This seems to have been fixed by removing the offending fields from being indexed in another issue.  Feel free to reopen if this issue pops up again.
