### ISSUE TITLE
EntityReference: Prevent delete if referenced

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#303]
Not sure if this is core functionality or not, but I'm sure it's out there somehow. You should not be able to delete a node that is referenced by another node, e.g. You should not be to delete a Fact or Image node if it's referenced by a Campaign, Static Content, etc.

This issue was created as a super safety mechanism.  We are not allowing editors the ability to delete any content, so it's not exactly priority.

**Comment by aaronschachter** [comment]
Updating description and deleting old comments, as this is a general entityreference issue (initial issue was around custom Fact entity, which we have since implemented as a Node Type).

**Comment by angaither** [comment]
This one is really tricky.
A [hook that runs on delete](https://drupal.org/comment/6035968#comment-6035968) would have to query all nodes to check reference fields. 
I would imagine this would considerable slow down the site. 
If we aren't allowing deletes, perhaps we don't need to worry about this.

**Comment by aaronschachter** [comment]
Yeah, only admin's can delete, so it's sort of a super safety check. I don't think we need to worry about this for the current milestone, for sure.
