### ISSUE TITLE
QA broken: Fatal error -- varnish.cache.inc

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#307]
http://qa-beta.dosomething.org/

Fatal error: require_once(): Failed opening required '/vagrant/html/profiles/dosomething/modules/contrib/varnish/varnish.cache.inc' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/html/includes/bootstrap.inc on line 2368

**Comment by mshmsh5000** [comment]
Rebuilding the QA image now.

**Comment by mshmsh5000** [comment]
http://qa-beta.dosomething.org/

Back up. This needed a ds/drush rebuild.
