### ISSUE TITLE
Campaign: Stub module

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#31]
Create a basic content type for campaigns.  This should be managed by a feature.  This should only be a stub as we do not have finalized comps/spec.

**Comment by desmondmorris** [comment]
I believe there may be a good argument for building this as an entity.  My main argument being, we do not need the node bootstrap necessarily.  Also, many of the fields do not need to be cck style fields.

We can discuss more during the wireframe to spec meeting.

**Comment by aaronschachter** [comment]
After heated discussions and fist fights we have decided to implement campaigns as a custom entity instead of a node type.

**Comment by aaronschachter** [comment]
I've created a spreadsheet of fields and field groups based on the wireframes and latest version of the Campaign Creation google form: https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0AnDHGfy1v5bJdDk3NFIycGpNYmUxYmt0ZDVMdFNTUGc&usp=drive_web

Comments are welcome, but keep in mind that Fantini reports that the form / wireframes are being reviewed in mgmt meeting this week and are subject to change.  For now, I'm diving deep into Entity stuff on a local sandbox before doing anything in the repo.
