### ISSUE TITLE
Add revision setting to .make for message_broker_producer

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3126]
Until the `message_broker_producer` is ready for a production release builds of the DoSomething.org site should be locked to a specific release. Add:

```
projects[message_broker_producer][download][revision] = "40e8d9892e378846adf5cb9b295f53c8a533f123"
```

to `/html/profiles/dosomething/drupal-org.make`.

**Comment by aaronschachter** [comment]
@DeeZone I am re-opening this as signing up for a campaign on staging is still not working.. displaying the "Failed to create MessageBroker library (messagebroker-phplib) instance. Check configuration settings in administration interface."

This is a blocker.

**Comment by aaronschachter** [comment]
Works now... Staging settings needed to be reset?

**Comment by deezone** [comment]
Issue resolved - it's the same problem with the module needing a admin form submission to setup the needed system `variable` entries. This issue will be resolved in the next release of the module.
