### ISSUE TITLE
ds pull does not wipe local db

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3132]
In working with @tz-earl on refactoring the `message_broker_producer` module we were working on `.install` and the addition of a new database table. This involved rebuilding the ds database several times.

The use of `sql-sync` in `ds pull stage --db` does not wipe the local db with the staging database but rather merges the databases together, thus the "sync" in `sql-sync` - duh!. Any local specific tables will have to dropped to be in sync with the staging db.

Is this the intended behaviour of  `ds pull stage --db`? I made the assumption that this would make a fresh copy of the stage db wiping out the local copy. Use of the `--create-db` switch with `sql-sync` should produce a fresh copy if that's the intended functionality.

**References**:
http://data.agaric.com/gotcha-drush-sql-sync-does-not-drop-existing-tables
http://www.drushcommands.com/drush-5x/sql/sql-sync

**Comment by deezone** [comment]
@aaronschachter @sergii-tkachenko ^^ Thoughts?

**Comment by sergiitk** [comment]
I think local db must be wiped during `ds pull stage --db`.

**Comment by aaronschachter** [comment]
Currently this is the intended behavior, this has come up before.  @sergii-tkachenko and I discussed that it should be up to the developer whether or not to delete the db, as it's easy enough to run `drush sq-drop` to drop your DB (http://drush.ws/#sql-drop).  

But if everyone is in favor of dropping the DB as part of a `ds pull` i'm ok with that.  We'd just add the drush command into the `ds` script.

**Comment by DFurnes** [comment]
+1 dropping DB. Thought this was already expected behavior.

**Comment by DFurnes** [comment]
Or if not, we should add a disclaimer to the `ds pull` command, and an option `ds pull --force` or something like that to do a real "reset".

**Comment by aaronschachter** [comment]
I'm ok with dropping DB as part of regular behavior.  @DeeZone wanna give this one a shot?

**Comment by deezone** [comment]
@aaronschachter Yep, I got this one.

Related:
https://jira.dosomething.org/browse/INF-41
