### ISSUE TITLE
Hide timezone so users can't change it

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3150]
Causes issues with campaign dates documented here: https://trello.com/c/pnzlbUt8

**Comment by mikefantini** [comment]
this will be done with profile v1.0 updates, but will be part of a bigger /user/[uid]/edit updates.

once those updates are finalized, we may want to reference and close this one

**Comment by aaronschachter** [comment]
This is related to #3805.

**Comment by itsjoekent** [comment]
@aaronschachter you also took care of this one right?
