### ISSUE TITLE
Enable DS Shipments module for TFJ Canada

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3156]
Canada requires the DS Shipments module to be enabled, in order to create Banner Shipments for TFJ.

We can manually enable the module, but we're getting closer towards crazy town with keeping track of what modules should be turned on for what sites.

If we choose not to handle international module listing now, this issue can be closed by manually enabling the module on Canada.

**Comment by aaronschachter** [comment]
Related to https://jira.dosomething.org/browse/INF-16 and https://github.com/DoSomething/dosomething/pull/2976

**Comment by barryclark** [comment]
@blisteringherb @mshmsh5000 @sergii-tkachenko Thoughts on manually enabling the module, or tackling international module configuration?

**Comment by aaronschachter** [comment]
International config is the better option, but a quick way to do this programatically could be through an install hook, which @sergii-tkachenko has been doing in the UK and Canada modules for the External Auth module.

**Comment by blisteringherb** [comment]
It seems like we don't really lose anything by putting these into install hooks for the time being since we can programmatically get a list of the the modules that are installed if we need to do that at some point.  The install hooks will also give us an idea of when things were enabled.

@aaronschachter

**Comment by aaronschachter** [comment]
Yah, it's a good short term solution.  Will wait to begin this until #3176 is merged, to avoid conflicting install hooks.
