### ISSUE TITLE
3M logo needs to be added to the homepage

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3157]
Need to add 3M to the homepage

partner term is here: https://beta.dosomething.org/taxonomy/term/948

@DFurnes let me know if you need anything else on this.

**Comment by DFurnes** [comment]
Waiting on a few other sponsor logos to batch with this update.

**Comment by aaronschachter** [comment]
@DFurnes Closey close?

**Comment by DFurnes** [comment]
Oof. Yup! Closed by #3202.
