### ISSUE TITLE
Taxonomy term template

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3159]
- [x] Create a tpl file for viewing a taxonomy term.
- [x] Currently when viewing certain terms, the page dies:

```
EntityMetadataWrapperException: Unknown data property field_image_campaign_cover. in EntityStructureWrapper->getPropertyInfo() (line 335 of /var/www/vagrant/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).
```
-  [x] Only display Campaign and Grouped Campaign nodes (currently Images can be tagged with Cause, so they show up in the default view)
- [x] CSS Paint

**Comment by aaronschachter** [comment]
@mikefantini Should Grouped Campaign nodes be displayed on a Cause page?  Or only Campaign nodes.

**Comment by aaronschachter** [comment]
@mikefantini Also - what is the desired sort for how campaigns should be listed?

**Comment by mikefantini** [comment]
@aaronschachter yeah I think it makes sense for grouped campaign nodes to be displayed as well. It gets a little funny because we sign you up for the group when you sign up for an individual campaign anyways, but I could see someone wanting to navigate to the group landing page from this page to learn more about the group.

Ideal sort is:
- status = active
- staff pick
- sponsored
- in high season
- newest -> oldest

Let me know if that's doable or needs to be simplified for v1.

**Comment by aaronschachter** [comment]
As we dscussed today, i'm going to attempt to use the existing campaigns view, filtering it by the term being viewed.

**Comment by aaronschachter** [comment]
@mikefantini Assuming that for Cause, we want to filter by `field_cause` , not `field_primary_cause`.

**Comment by mikefantini** [comment]
yeah let's go with field_cause @aaronschachter

**Comment by aaronschachter** [comment]
Finding issues with `dosomething_taxonomy_taxonomy_term_view` ... specifically `hook_taxonomy_term_view` in core.  Thinking that overriding the menu callback per http://www.appnovation.com/blog/custom-taxonomy-term-pages may be the way to implement this.

**Comment by aaronschachter** [comment]
Per https://github.com/DoSomething/dosomething/issues/3159#issuecomment-59257451 -- too crazy to try to pass multiple taxonomy fields as arguments to the /campaigns view.  Using a simplified Taxonomy view, `campaigns_by_term`, for now (which allows the the same view to be used for all terms).  Current view is all published campaign and campaign groups, with prioirty:
- Staff pick first
- Date created descending

**Comment by aaronschachter** [comment]
Closing this issue, although we'll still need to theme each new field we add to the terms.
