### ISSUE TITLE
Canada School API sending incorrect headers

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#3160]
The School API is not sending the correct headers to [allow AJAX access through the browser](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin). It should return `Access-Control-Allow-Origin: *`.

**Comment by aaronschachter** [comment]
The Canada School Finder can be tested on https://canada.dosomething.org/node/1227 by clicking on the "Update your school" link.

To test the form, you'll need to be signed up for the campaign though, which can you do via https://canada.dosomething.org/node/1227/pitch

**Comment by mfurdyk** [comment]
That header is now added! @DFurnes @aaronschachter

**Comment by DFurnes** [comment]
Confirmed working on our end! Thanks @mfurdyk!
