### ISSUE TITLE
Vocabulary fields

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3162]
All user facing vocabularies need the following fields added:
- [x] `field_image_campaign_cover`
- [x] `field_subtitle`
- [x] `field_video`
- [x] `field_partners`
- [x] `field_facts`
- [x] `field_intro_title`

**Comment by mikefantini** [comment]
@aaronschachter we also need:
- title
- facts

**Comment by aaronschachter** [comment]
For title, we'll just be using the Term name.  Does Fact appear on every vocabulary?

**Comment by aaronschachter** [comment]
@mikefantini Confirming: Assuming we want to display the Partner modals (e.g. Why we <3 Toyota) as well? with the video/image/copy fields?

**Comment by mikefantini** [comment]
@aaronschachter let's start with facts just on cause and issue for now.

and yeah we'll want the partner modals on collections that have partners. If you want we can just add that to the campaign collection vocabulary and then add it to other vocabularies as needed.

I could see us wanting it for issue and holiday as well potentially.

**Comment by mikefantini** [comment]
Facts should be listed immediately after the display of campaigns. They should be under the header Facts About [Title].

The display of these facts should use this style: http://neue.dosomething.org/#typography---unordered-lists.

We should also have the Sources animation that we use on the action page and on facts pages.

**Comment by mikefantini** [comment]
@aaronschachter design team wants there to be a field_intro_title for these to break up page a little bit so that it's not just full bleed image above our campaign tiles. can you add this to the fields needed above?

**Comment by aaronschachter** [comment]
We can add it, but there's always going to be a description in the text, which would prevent said situation...

**Comment by mikefantini** [comment]
right sorry they wanted this purple header to further break up the page. The 1-2 lines of text between the header and the campaigns didn't feel like enough.
