### ISSUE TITLE
Don't need Submit Button Label field on shipment form

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3165]
![image](https://cloud.githubusercontent.com/assets/6330971/4640291/b77ba69c-541d-11e4-827c-c893d3861f92.png)

**Comment by aaronschachter** [comment]
@mikefantini Just confirming: Default label is "Submit" ?

**Comment by mikefantini** [comment]
@aaronschachter yup

**Comment by aaronschachter** [comment]
I'd prefer to leave this variable intact in case we ever want to change the label.  Perhaps its just used instead as an Override, and if a value is not set, it will default to "Submit".

**Comment by mikefantini** [comment]
ok fine. but just let the record show i was trying to get rid of a field and @aaronschachter made the call to keep it.
