### ISSUE TITLE
Add member_count merge_var

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3177]
The footer of transactional email message contains the text:

> Join 2.9 million young people. Any cause, anytime, anywhere. _mic drop_

The "2.9 million" needs to be a `merge_var` that can be dynaically updated based on the results of a cURL call to `POST https://beta.dosomething.org/api/v1/get_member_count`.

See:
https://github.com/DoSomething/dosomething/wiki/API#get-member-count
- [x] Add `['merge_vars']['MEMBER_COUNT']` to payload of messages sent via `dosomething_mbp -> message_broker_producer.module`.

See also:
https://github.com/DoSomething/mbp-user-import/issues/13
https://github.com/DoSomething/mbp-user-event/issues/8
https://github.com/DoSomething/mbp-user-digest/issues/11

**Comment by aaronschachter** [comment]
@DeeZone Note that the API is only needed for external apps.  If you're within the `dosomething_mbp` module, use the `dosomething_user_get_member_count` function: https://github.com/DoSomething/dosomething/blob/v0.3.50/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1181

**Comment by ArielSD** [comment]
@DeeZone @barryclark Fantini told me to connect with you about the member count auto-updating at the bottom of the email template. How can I help?

**Comment by deezone** [comment]
@ArielSD On my to-do for the start of next week, This issue needs to be closed and deployed to production before making the Mandrill template update.
