### ISSUE TITLE
International sites need to be able to customize phone number format placeholder

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#3183]
Validation for the phone number field (such as on user login) currently validates any domestic or international number with any country code. The placeholder `(555) 555-5555` that we give to users, however, is not always country-appropriate.

We need a way for each site to use country-appropriate date placeholders, either through translation (which is what we're doing on the UK site through the "UK English" translations), based on the site region settings, or through the admin panel.

/cc @aaronschachter @sergii-tkachenko

**Comment by aaronschachter** [comment]
@DFurnes Is the string wrapped in a `t` function?  If so, this can just be done via the admin translate UI.

**Comment by DFurnes** [comment]
@aaronschachter Yep, that's what we're doing on the UK site:

![translation interface on UK](https://cloud.githubusercontent.com/assets/583202/4703148/5d9603e4-5868-11e4-8f31-de9ffbc8a26e.png)

The string for the placeholder `(555) 555-5555` isn't showing up as translatable on other English-speaking sites, such as Canada, presumably because they don't have any other languages set up to translate to:

![translation interface on Canada QA](https://cloud.githubusercontent.com/assets/583202/4703168/853d31b0-5868-11e4-9953-8d7edf93e513.png)

I see there's an option to add a [custom language](https://www.drupal.org/node/24593), but I want to run that by someone before we do it to make sure that's the correct way of handling this.

**Comment by aaronschachter** [comment]
Hmmm. That I'm not sure of.  I don't see a English (Canadian) language to set as the default language, which would be ideal.  

It's possible that this could be an override within the Canada settings.php, like this: https://github.com/DoSomething/dosomething/blob/v0.3.55/config/settings.php#L114

.. but not sure if that gets too into crazy town either (or.. is it just the cleanest?)

@sergii-tkachenko @blisteringherb Any thoughts?

**Comment by sergiitk** [comment]
@aaronschachter confirming that there's no `en-ca` language in Drupal.

**Comment by sergiitk** [comment]
@aaronschachter let's try with settings override. I think there shouldn't be too much translation exceptions and the fact there's no special language in Drupal proves this point.

**Comment by aaronschachter** [comment]
@blisteringherb @sergii-tkachenko  Any thoughts as to how to add this to Canada's settings.php particularly?  And to keep it tracked within code?

**Comment by blisteringherb** [comment]
@aaronschachter Maybe we can have an additional include statement in the settings.php that includes a settings file that's kept in version control.

**Comment by sergiitk** [comment]
@blisteringherb maybe we should put intl settings.php files to a private repo? I mean sometimes it's difficult to find something in those and I think it'd be better to have at one place.

**Comment by barryclark** [comment]
Sounds good. @blisteringherb or @sergii-tkachenko would one of you be able to tackle that?

**Comment by aaronschachter** [comment]
This has come up somewhere else @barryclark and I were chatting about.  Maybe it's worth adding the contrib module String Overrides to just have a UI to do these one-off not-actual-different-language translations, and keep these translations out of the codebase.

**Comment by mshmsh5000** [comment]
:+1: on String Overrides. It will allow for much more flexibility in situations like Canada. We should just be conservative about when we use it.

**Comment by aaronschachter** [comment]
Upon deployment of #3553, this string can be overridden at `admin/config/regional/stringoverrides` by an administrator.

**Comment by aaronschachter** [comment]
@barryclark Can we close this?

**Comment by barryclark** [comment]
Hells yea. Thanks for putting the string overrides in place!
