### ISSUE TITLE
Views Export displays

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3200]
Refs https://jira.dosomething.org/browse/DS-304 -- Adding Views Data Export to contrib.

Add and export a new Export views display for each view listed:
- [ ] `user_search`
- [ ] `node_signups`
- [ ] `node_reportbacks`

Ensure that if Views Data Export module is creating the files somewhere, that its someplace non public.

**Comment by aaronschachter** [comment]
Views Data Export generates the exported file as a regular Drupal file, but does not set the status to permanent, so it will be deleted upon next cron run.

**Comment by angaither** [comment]
I don't think we want/need this anymore
