### ISSUE TITLE
remove "Did you mean" suggestions on search

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3204]
Creates more confusion than help as is:

![image](https://cloud.githubusercontent.com/assets/6330971/4721017/47e43570-5935-11e4-817a-c0d36d279a0b.png)

**Comment by blisteringherb** [comment]
The "Did you mean" has been removed from the search results.

**Comment by mikefantini** [comment]
sweet thanks! so can we close this out?

**Comment by blisteringherb** [comment]
Yup!

**Comment by aaronschachter** [comment]
@blisteringherb What was done to remove it?
