### ISSUE TITLE
change variables that are displayed on search results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3207]
should look like this (with Search in purple header as is):

![image](https://cloud.githubusercontent.com/assets/6330971/4722895/2181e9c8-5943-11e4-82e1-12ddc750c0b9.png)

We would no longer display results as numbered, we would no longer pull in the snippets that contain the phrase that is searched, and we would pull in the cover image for campaigns and use our logo thumbnail for pages that don't have cover images.

**Comment by mikefantini** [comment]
Display the following content for the following content types:
- Campaigns
  -- Title
  -- Call to action
  -- Cover Image
- Static content
  -- Title
  -- Subtitle
- Fact page
  -- Title
- Campaign Collection
  -- Title
  -- Call to Action
  -- Cover Image

**Comment by mikefantini** [comment]
Also @blisteringherb let's chat in person about out ability to pull in taxonomy terms.

We're doing work to have displays of Taxonomy Campaign Collections. It would be sweet to pull these into search too but only if published (it's not drupal core published though, so may be more difficult).

If we are able to pull these in it'd be sweet to include:
- Title
- Cover Image
- Description (ideally cut off after x characters to fit display).

cc: @aaronschachter

**Comment by mikefantini** [comment]
we'll be using this gallery just for reference: http://neue.dosomething.org/#gallery---duo

**Comment by blisteringherb** [comment]
I've created a branch, https://github.com/blisteringherb/dosomething/tree/search-appearance, that removes the numbers, and adds the cover image as a thumbnail to campaigns in search results.  I've added the HTML from the pattern library, but it doesn't seem to be working properly, so I'm hoping a fender might be able to help with that.  I was also unsure where the 100x100 logo should come from since I didn't see it in the paraneue theme.

@barryclark 
@mikefantini

**Comment by mikefantini** [comment]
ok let's touch base on this before it gets shipped to production because we don't want incomplete stuff getting pushed live

@lkpttn @DFurnes can we get that 100x100 logo you guys recommended up on paraneue?

**Comment by lkpttn** [comment]
This should duplicate the Gallery - Duo pattern.

http://neue.dosomething.org/#gallery---duo

**Comment by DFurnes** [comment]
:+1: to what Luke said. Duo Gallery with Media tiles inside it.

**Comment by DFurnes** [comment]
For the image, we can use the same image as our [touch icon](https://github.com/DoSomething/neue/blob/dev/assets/images/apple-touch-icon-precomposed.png). It's in `paraneue_dosomething/bower_components/neue/dist/assets/images/`.

**Comment by mikefantini** [comment]
closing this out. think we're good
