### ISSUE TITLE
Add "Image Video" field to Image content type 

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3228]
For the 404 page, we want to display a Video on desktop but an Image on mobile.  We are also experimenting with Video Cover images.  It seems useful to add a new field to the Image content type to render an Image node as a video file.
- Add a "Image Video" File field to the Image content type, which allows all video formats.  The resulting machine name should be `field_image_video`.
- Export the new field via Features export  to the DoSomething Image module. You'll need to export the `field_base` and `field_instance` exportables in `drush fe dosomething_image`.

**Comment by mikefantini** [comment]
@aaronschachter would this set us up to have video tiles on the homepage like we ran that test for as well?

**Comment by aaronschachter** [comment]
Yes - It gives us the place to upload the video.  Need a separate issue to style the homepage title as video if it exists.

**Comment by mikefantini** [comment]
yeah figured; just checking
