### ISSUE TITLE
Notfound content type / template

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3229]
- [x] Create a new `notfound` content type, to create instances of 404 pages.  Should contain a `field_images` which contains Image nodes.
- [x] Create new module, `dosomething_notfound` to export content type to.
- [x] Add new module to the`dosomething.make` file, a la https://github.com/DoSomething/dosomething/blob/v0.3.63/lib/profiles/dosomething/dosomething.make#L7
- [x] Create a `node--notfound.tpl.php` within the Paraneue theme's templates to output pretty 404 pages.  Implement `hook_preprocess_node` to display the Image node's Video file on desktop if present, display appropriate image field on mobile.  Depends on #3228.  Lots of our own custom DS functions to use and add to here, but we can talk through it once you get here.

**Comment by itsjoekent** [comment]
done https://github.com/DoSomething/dosomething/pull/3331
