### ISSUE TITLE
sources treatment on collections should match other places on the site

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3241]
The spacing is off around sources for collections, especially between Sources and What You Get.

Let's replicate spacing on the campaign template: 
![image](https://cloud.githubusercontent.com/assets/6330971/4792480/c0f7e654-5de6-11e4-9aad-60a02d08fde7.png)

Here is what it looks like now on collections:
![image](https://cloud.githubusercontent.com/assets/6330971/4792487/d0116a34-5de6-11e4-816c-382baeb14e12.png)

**Comment by aaronschachter** [comment]
@tjrosario Collections here ==  taxonomy terms.

Here is a sample URL -- http://staging.beta.dosomething.org/volunteer/animals.  It's a template for a taxonomy term, which can be found in paraneue's `taxonomy` directory.  You'll also find theme preprocessing going on here: https://github.com/DoSomething/dosomething/blob/v0.3.66/lib/themes/dosomething/paraneue_dosomething/includes/preprocess.inc#L413
