### ISSUE TITLE
need config variable for "Need help locating your school" copy

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3250]
we'll want a config variable for this copy for the school finder in case it updates frequently as we're trying to react to questions and user confusion

wires: https://a0465d35-a-5d563b7e-s-sites.googlegroups.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/school-finder/School%20Finder%20Wires%201.0.png?attachauth=ANoY7cpeKk4nt8wkj2e1iJd7IQv3zS_ByO1bU9RIjwK4pmNryd8w99ignAfWnUardavbnzJKF7Y-8nn9AMMhmpvgdQn2gcbfMyTrb_v_kQqjpdy6-aYbgz7aLV2fGftA72CohfqlRRzkAFQsdVoBo0TQLl5NNGsIyuHUHiyyLGUi71DZMj6-vTnOExs3EiR6JVCVJt7supo03kwg9Eo9mIp0OX2CgfBcf6iFSwN6L4hX-1-8RyZZxoPUIFS2TikL_Rct5Csl5WiwDrTyy_DSJ6GhbJHNFzjFvVSU3UqPvAhLZ202IUT0PTg%3D&attredirects=0

**Comment by aaronschachter** [comment]
@DFurnes I can add a new variable for this into the DS User admin config form and pass the variable to the `dosomething_user_preprocess_page` function... (which i'm thinking actually would be cleaner to move into paraneue preprocess instead) .. but where is the copy displayed?  Would you be able to pick this up once I set up the variable?

**Comment by aaronschachter** [comment]
@mikefantini The copy can be overwritten by an admin at `admin/config/dosomething/dosomething_user`.  If no variable is present, the current copy on the site will be used.

**Comment by mikefantini** [comment]
awesome thanks
