### ISSUE TITLE
Add intro text field below gallery titles

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#3253]
A few static content QBs are asking for a text field to be added to the galleries. They want to write a brief intro to the images under the title.  It would be awesome to have this feature before the Advisory Committee static page launches this sprint.

**Comment by barryclark** [comment]
@julielorch Under http://neue.dosomething.org/#gallery-triad ? 

@weerd Could you tackle this one w/ Julie?

**Comment by joolaay** [comment]
yo yo, it's actually for the duo: http://neue.dosomething.org/#gallery-duo

But might make sense to stick an intro field on both

**Comment by barryclark** [comment]
Sweet, would be great if you and @weerd could iron out how that would look/work.

**Comment by mikefantini** [comment]
we should add this as a field to the field_gallery field collection. this will make it available to any and all galleries.

I think the new field added should be:

machine name: field_gallery_description
user facing form name: Gallery Description
help text: This description will be appear between the gallery title and the images in the gallery. Only include this if you think context is _really_ needed for the gallery you are adding.

This field should be placed between field_gallery_title and field_gallery_style in the field collection.

@barryclark we'll need a bender to add the field.

@julielorch make any edits you want to the description.

**Comment by weerd** [comment]
Is this still a thing? @mikefantini @angaither

**Comment by mikefantini** [comment]
@julielorch this is a question for you. Do you think this is still something we need?

**Comment by namimody** [comment]
@mikefantini @lkpttn should we do this? I think yes?

**Comment by mikefantini** [comment]
Makes sense to me.

**Comment by lkpttn** [comment]
Do we want to fold it into Forge 6.7?
