### ISSUE TITLE
Trim 11-facts spacing between intro & first fact

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#3255]
Whoa - there's way to much spacing here. 

![screen shot 2014-10-27 at 3 51 55 pm](https://cloud.githubusercontent.com/assets/6331017/4798344/cac86a6a-5e12-11e4-9344-627aba5ef4bf.png)

**Comment by aaronschachter** [comment]
This is related to #3297.  cc: @mikefantini @julielorch @lkpttn

**Comment by mikefantini** [comment]
copying over from #3297 The style should display at 2/3 width (although can't find it on neue.dosomething.org). @lkpttn thoughts?

**Comment by lkpttn** [comment]
The 3/4 view isn't explicitly defined in Neue as a pattern we use (yet). It has markup support in production already but I don't know how it would be triggered on the back-end.

**Comment by lkpttn** [comment]
This has been fixed with Neue 6.
