### ISSUE TITLE
Refactor build script to pull from dosomething-dist repo

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3257]
The `hubot release` command runs the dosomething make file, and pushes the built HTML directory to the https://github.com/DoSomething/dosomething-dist repo.

Refactor `ds build` to pull from the repo instead of running the make.  will greatly improve time it takes to deploy.

**Comment by angaither** [comment]
we don't use that repo anymore, additionally we can probably remove that repo!
