### ISSUE TITLE
autocomplete on school finder doesn't work on production

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3259]
when a user goes to find his school and starts typing the school name, no options appear in the autocomplete on production so a user can't sign up his school

video: http://screencast.com/t/IxzMELN7W

this works fine on staging

@aaronschachter not sure if this is you or @DFurnes 

I assume it's not @joshcusano since it works fine on staging.

**Comment by DFurnes** [comment]
API endpoint in settings needed to be set to HTTPS to work on production. Fixed.
