### ISSUE TITLE
Profile template v1.0

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3261]
New User Profile sections for v1.0: https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/profile-template
- [x] You're Doing
  - Displays active standard campaigns which the user has signed up for (Campaign Type == 'campaign' && Campaign is not closed)
  - If no campaigns, displays copy variables
- [x] You Did -- Displays all user reportbacks.  
  - If no reportbacks, this section does not display.
- [x] Account Info, with link to Edit profile

**Comment by aaronschachter** [comment]
@mikefantini @lkpttn The mocks show inconsistent header for the Prizes section between the empty and filled designs.  Is the header to be "My Swag" ?

**Comment by lkpttn** [comment]
These will all be "Your _____" and swag should be prizes. So "Your Prizes".

**Comment by aaronschachter** [comment]
Closing this and creating separate issues for remaining Profile sections.
