### ISSUE TITLE
Refactor dosomething_user_address_country variable

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3264]
The function introduced in #3249 adds some duplication, we need just one place to check for a country code.

This issue is to replace the calls using the variable `dosomething_user_address_country` with the new `dosomething_settings_get_affiliate_country_code` function.

Also the `dosomething_settings_is_affiliate` function can now be refactored to use `dosomething_settings_get_affiliate_country_code() != US`, so we wont need the `is_affiliate` variable.

**Comment by angaither** [comment]
this has been refactored and will be deprecated once we are ~one site~
