### ISSUE TITLE
update display of campaigns on taxonomy collections

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3265]
let's have the following view of campaigns on taxonomy collections:
- if 4 campaigns, goes 4 across
  ![image](https://cloud.githubusercontent.com/assets/6330971/4810332/8d904302-5eb2-11e4-9531-c1c7823a0625.png)
- if 5 campaigns, featured + 4
  ![image](https://cloud.githubusercontent.com/assets/6330971/4810344/9cacd026-5eb2-11e4-883d-5eba3da88050.png)
- if 6+ campaigns, 5 treatment plus show more and then just fill in two rows of 4 at a time

example is http://staging.beta.dosomething.org/volunteer/animals

**Comment by aaronschachter** [comment]
This gallery is using the same template as the Campaign Group node template.  Is this treatment the same for Campaign Groups?  (the answer should be yes)

**Comment by mikefantini** [comment]
yeah that's the plan.. having some debate with campaigns and data on the ideal solution.. will update this issue once we're able to come to a consensus

**Comment by aaronschachter** [comment]
FYI -- Ideally we should refactor the Homepage node template to use this same shared gallery as Taxonomy Terms and Campaign Groups.

**Comment by mikefantini** [comment]
chatted about this in person with both of you, but unfortunately that won't be the case

we'll want to keep Campaign Groups and the homepage as they are and make the updates above for Taxonomy Collections

**Comment by barryclark** [comment]
To clarify this one a little @mikefantini. Everything is perfect with the layout right now EXCEPT 4 campaigns, right?

**Comment by mikefantini** [comment]
@barryclark we need both the 4 or less layout AND the 6 or more layout

currently the only layout that works as desired is exactly 5 campaigns

**Comment by barryclark** [comment]
Gottit. Thanks!
