### ISSUE TITLE
featured campaign on collections is super pixelated

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3267]
## The fix:

See #3474 - We need JS which handles mobile / desktop transition; on desktop, dynamically switch the image src to the data-attribute src defined to replace the 400x400 with the 768x768
## The bug:

Using `400x400` preset for all Campaign Galleries makes the Featured image pixellated.

![image](https://cloud.githubusercontent.com/assets/6330971/4810900/ba407dd2-5eb6-11e4-8f1a-7a216968f185.png)

![image](https://cloud.githubusercontent.com/assets/6330971/4810908/c729db1a-5eb6-11e4-9f85-b523d58c7be7.png)

example http://staging.beta.dosomething.org/volunteer/animals

**Comment by mikefantini** [comment]
happening on the homepage too

**Comment by aaronschachter** [comment]
My guess here is that the `$size` parameter we are passing when we preprocess these galleries with `dosomething_image_get_image` is too small.

**Comment by barryclark** [comment]
@aaronschachter @tjrosario mentioned that this is more of a back-end issue, would you be able to tackle this?

**Comment by aaronschachter** [comment]
This will be handled in #3474.  Assigning to @weerd, as the JS will be what fixes this.

**Comment by aaronschachter** [comment]
@weerd This issue is now ready for JS-ification. I've added the changes in #3474 for the Taxonomy Term template, and am now working on applying them over to the Campaign Group template as well.

**Comment by weerd** [comment]
JS-ification sequence commencing!
