### ISSUE TITLE
Update field name on Confirm password to Confirm Password on user registration

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3275]
Update field name on Confirm password to Confirm Password.

It's the only field that doesn't capitalize first letter of both words:
![image](https://cloud.githubusercontent.com/assets/6330971/4818545/d7d4881e-5ef4-11e4-850e-270285e7391f.png)

**Comment by mikefantini** [comment]
@DFurnes super low priority obviously but super small too and just noticed this inconsistency. thoughts?

**Comment by angaither** [comment]
boom, it's in caps!
![image](https://cloud.githubusercontent.com/assets/645205/11191296/955c72ce-8c68-11e5-8e26-958f084972d9.png)
