### ISSUE TITLE
user never gets logged in on firefox on staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3279]
When I try to create an account, one gets created, I'm just not logged in.

When I try to log in, it says it works, but I'm still not logged in.

This also happens why trying to sign up for a campaign by logging in or creating an account. Instead of being logged in and taken to the action page, the pitch page just reloads and I'm still logged out. When looking at the signups for that campaign, the user does get signed up for the campaign.

This seems to only be happening on firefox. Doesn't happen in Chrome or Safari and seems to not happen in IE either.

Also this is only happening on staging right now, not production.

**Comment by aaronschachter** [comment]
What campaign / user ? Just tested http://staging.beta.dosomething.org/campaigns/hunt-day-2-trash-scavenger-hunt logging with an existing account in Firefox, and it worked for me.  Also works with creating a new account on campaigns/hunt-day-2

**Comment by mikefantini** [comment]
mfantini+banners@dosomething.org was the user

happened when trying to log in on the homepage and trying to log in to /campaigns/sandbox-campaign

also happened when created an account with mfantini+mozillanotworking@dosomething.org

I'm on firefox 33.0.2

**Comment by aaronschachter** [comment]
I'm able to login and create account ok with sandbox campaign too. Firefox 32.0.3.  Will update and test again.

**Comment by aaronschachter** [comment]
Upgraded to 33.0.2, and upon creating a new account, I was directed to homepage after sign in on the Sandbox pitch page.  The new user was not signed up. :crying_cat_face:

**Comment by mshmsh5000** [comment]
:fire: :dog2: == :sob:

**Comment by mikefantini** [comment]
yeah even if I'm just on the homepage and try to log in it doesn't work. the page just reloads and I'm still logged out.

**Comment by mikefantini** [comment]
same with creating an account. the page just reloads and I'm still logged out. but the user gets created -> user 1702369

**Comment by mshmsh5000** [comment]
This is usually about page caching and headers. Firefox has always behaved differently w/r/t honoring page caching headers than has Webkit and other engines.

**Comment by mshmsh5000** [comment]
The inconsistent behavior has been an issue for many years: https://bugzilla.mozilla.org/show_bug.cgi?id=428916

**Comment by mikefantini** [comment]
still experiencing this issue even after @aaronschachter cleared cache

**Comment by lkpttn** [comment]
I was able to create accounts, log in and out with a new account and my admin account. 

Firefox 29.0.x
Firefox 30.0
Firefox 33.0.2

**Comment by mikefantini** [comment]
OS X version 10.9.5

**Comment by mikefantini** [comment]
And I'm getting transactional emails

**Comment by mikefantini** [comment]
others in the office can't seem to replicate it but the specialist guild flagged the issue initially

**Comment by angaither** [comment]
I also can't replicate, but trying to debug with @mikefantini 
Some fun facts
- the session is being created for the user 
- the POST for `/login` returns a 302 error (but it does that on successful logins as well???)
- I put debug statements into the `dosomething_user` module and it shows everything correctly for the `form_alter` but it never prints debug info from 'user_validate`or`login_submit` 

I really have no conclusions, it's really confusing because the dblog shows the session being created, but the header remain 'log in'

**Comment by mikefantini** [comment]
the specialist guild is seeing it on windows 7 pro, Firefox 33

**Comment by aaronschachter** [comment]
it would be helpful to know if the same behavior happens without the modal, if they (and others who can replicate) could test:

http://staging.beta.dosomething.org/user/login

http://staging.beta.dosomething.org/user/register

**Comment by mshmsh5000** [comment]
Unable to replicate with FF 33.0.2 on OS X or Windows 8.

_Request to anyone who can replicate:_
1. Start in unauthenticated state
2. Log in
3. Verify you're experiencing the issue (i.e., header link still says "Log in")
4. Reload the page

Does step 4 resolve the issue?

**Comment by mshmsh5000** [comment]
Also unable to replicate with FF 33.0.2 on Windows 8.1.

**Comment by angaither** [comment]
When I was testing on @mikefantini's computer yesterday 
@mshmsh5000 Step 4 doesn't resolve the issue

**Comment by DFurnes** [comment]
Unable to replicate as well. Tested logging in from homepage through the modal on Firefox 34.0, 33.0, 32.0, 31.0, and 30.0 on Windows 7 through Browserstack. Also unable to replicate on Firefox 33.0 and 32.0 on OS X 10.9 through Browserstack.

We're not doing anything special in the modal that should be causing unique issues there (as compared to the `/user/login` page). It's just a traditional HTML form.

**Comment by mikefantini** [comment]
@aaronschachter trying on http://staging.beta.dosomething.org/user/login and http://staging.beta.dosomething.org/user/register results in the same issue

and yeah @mshmsh5000 like @angaither said refreshing the page does not resolve the issue

**Comment by mikefantini** [comment]
The specialist guild can no longer replicate the issue since their firefox version updated.

Having them look into it more later today. But after they test, if I'm the only one who can replicate then let's just close this issue.

**Comment by mshmsh5000** [comment]
:+1: Closing. This smacks of FF bug, not DS bug.
