### ISSUE TITLE
action guide list margin cleanup

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3282]
In Action Guide modal, if a `<p>` occurs after a `<ul>` add a top margin on the `<p>`.

```
ul + p { margin-top: 1em; }
```

currently using non-breaking spaces, remove them from the cms example: https://beta.dosomething.org/campaigns/speak-out-week

**Comment by sbsmith86** [comment]
Please remove non-breaking spaces!! @mikefantini
