### ISSUE TITLE
Reportback Form cropping

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3286]
After User has uploaded an image, present Square cropping tool to save a Square image.

The Reportback Form should save the original file as the `fid` and the processed file as `fid_processed`.  The options selected (x, y, width, height) should be saved as a serialized array within `options_processed`.

**Comment by angaither** [comment]
@mikefantini @DFurnes do we have a pixel size we should crop to?

**Comment by mikefantini** [comment]
@kerigoff @julielorch thoughts ^?

**Comment by DFurnes** [comment]
I think that's going to depend a lot on what share sheet ends up looking like (since we're using these cropped photos there too, right?). Something like `400x400` seems safe though if you want an estimate.

**Comment by mikefantini** [comment]
yes @DFurnes we will be using these on share cards as well.

@angaither can you start with 400x400? hopefully it's something that's not tough to update if we have to later?

**Comment by aaronschachter** [comment]
I'm guessing the ideal here is we keep a high-res file but also a separate cropped fid.  If we're only storing the cropped fid, we'd be in trouble if we ever wanted to display a bigger pic later (like for the instagram style permalink)

**Comment by angaither** [comment]
Based on [research](http://media.tumblr.com/tumblr_mee2p7e1Yc1row2y8.gif) on the [imagefield crop](https://www.drupal.org/project/imagefield_crop) module, this does not seem like a good way to go.
Here's why:
- It uses the [jcrop](http://deepliquid.com/content/Jcrop.html) plugin, but it [uses an old version that does not support mobile](https://www.drupal.org/node/1961334)
- since the reportback form doesn't use a field type we would have to create a [custom one and attach it as a widget](http://drupal.stackexchange.com/questions/25140/is-displaying-a-working-field-widget-form-on-its-own-possible)

**Comment by mikefantini** [comment]
hmm ok.

@weerd i know you had some ideas for this as well. any thoughts on other solutions that might work better?

**Comment by weerd** [comment]
This is a possibility: http://www.croppic.net/

Work "ok" on mobile. Would probably have to add dragging ability to photo within the container box...  Looking for other plugins as well.

**Comment by weerd** [comment]
The demo for this actually works rather well on mobile: http://tympanus.net/Tutorials/ImageResizeCropCanvas/

Likely means we handle all the cropping on the client side (front-end) and then just pass the original and cropped images to Drupal, with some :sparkles:  magic :sparkles:  in between :dancer:

**Comment by mikefantini** [comment]
ok great so should we try to get basic implementation of this up to test it out?

@weerd @angaither?

**Comment by mikefantini** [comment]
hey @sbsmith86 passing this over to you right now, @mshmsh5000 will help clarify what's needed

**Comment by sbsmith86** [comment]
ok! @mshmsh5000 Do you have a sec to go over this issue?

**Comment by aaronschachter** [comment]
I walked through this with @sbsmith86. @DFurnes We need the thumbnail back on the form, in order to crop it.  What happened to it?  Can you point @sbsmith86 in the right direction for JS land.

**Comment by sbsmith86** [comment]
I'm going to close this issue since cropping is on staging. I'll probably break out some smaller issues to fix bugs I find.
