### ISSUE TITLE
Multiple images reportback flow

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3287]
If User has not reported back, the form is displayed within the Prove It section (sans modal).  The User can upload a photo, rotate it, crop it, and add a caption within a modal on the form.

If User has reported back, the Reportback is displayed as read-only.  Clicking the "Update Submission" button will display the Reportback Form, with all fields populated with the reportback values.
- An "add another image" link will display.  If user clicks this, they are prompted to a new modal: the user can add a new Reportback File (adding an image, cropping it, and adding the caption for it)
- If more than 1 images have been added this reportback, the most recently added Image is displayed as the Primary reportback Image.  There is a thumbnail gallery below it showing the most recent 3 images below it.

**Comment by barryclark** [comment]
Link to latest mocks (Whole Flow PDF) https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/sharing-reportbacks

**Comment by mikefantini** [comment]
closing this, only remaining issue to show multiple reportbacks on preview

**Comment by weerd** [comment]
Resovled via #3817
