### ISSUE TITLE
Prove It theming

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3288]
- [x] Yellow BG
- [x] Display Reportback Form on page (no more modal)
- [x] Gallery, with show more (blocked by #3285)

**Comment by weerd** [comment]
@kerigoff @lkpttn @julielorch 

So just to confirm, across the board now the Prove It section will have the yellow background? No custom background image on some of them (the polaroid one, or the pants one, etc)? Will the sponsored ones also always be yellow?

**Comment by weerd** [comment]
Visuals are behind a feature flag, but they're there! 

Completed in #3698
