### ISSUE TITLE
404 page callback

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3289]
- [x] Create a menu callback `notfound` which will be set as the Drupal 404 path
- [x] Use `hook_install` to set the 404 page variable to `notfound` -- look at `variable_set` for how to do this programmatically. Also create a default notfound node populated with variables for default title, copy, image.
- [x] The page callback needs to find a random published and promoted `notfound` node nid, load it, and then `return node_load($nid, 'full')`.

**Comment by itsjoekent** [comment]
done https://github.com/DoSomething/dosomething/pull/3331
