### ISSUE TITLE
Admin reportback create/edit form

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3293]
Allow administrators ability to create a reportback entity, selecting the User Uid and the Campaign node nid that the reportback should be associated with.

Also expose these fields on the Reportback Edit form.

This will be used to add Reportbacks to the Closed state of Legacy Campaigns for which we'll be creating new beta campaign nodes.

**Comment by aaronschachter** [comment]
@mikefantini Reportbacks can be created from `admin/users/reportbacks/add`.  This has been deployed to staging and probably on prod tomorrow 11/4/2014

**Comment by mikefantini** [comment]
sweet thanks man
