### ISSUE TITLE
add copy as intro to all 11 facts pages

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3297]
"Welcome to DoSomething.org, one of the largest orgs for young people and social change! After you’ve browsed the 11 facts (with citations at the bottom), take action and volunteer with our millions of members. Sign up for  [a campaign](https://www.dosomething.org/campaigns) and make the world suck less."

**Comment by aaronschachter** [comment]
Style?  Just display as the Intro?  Do we still want to keep the Intro field? If so - What does this look like if the intro is also filled out - just 2 paragraphs?

**Comment by aaronschachter** [comment]
Assigning to @mikefantini for more details.

**Comment by mikefantini** [comment]
Let's kill the intro field and replace it with this default copy, so we'd never have a case where we have both.

The style should display at 2/3 width (although can't find it on neue.dosomething.org). @lkpttn thoughts?

**Comment by aaronschachter** [comment]
@mikefantini Just confirming we'll also want to kill the Intro Title field too, as well as Intro:

![screen shot 2014-11-03 at 12 52 57 pm](https://cloud.githubusercontent.com/assets/1236811/4887164/50278aa0-6382-11e4-8d34-ccadc590a4c4.png)

Also the Fact Page hero image field is not used within the template.  Should we also remove this field as well while we're cleaning this up?

**Comment by mikefantini** [comment]
yeah let's remove these variables.

clicking around I can't find any instances in which we use them.

I could see the argument for having an intro title, but probably more as a config variable that is put on all pages rather than as a field on the node

cc: @julielorch

**Comment by aaronschachter** [comment]
Deleting the `field_hero_image` as well.

**Comment by joolaay** [comment]
Hhmmm - was there talk about testing gifs in the hero?

**Comment by aaronschachter** [comment]
The hero image field is currently not displayed at all within the Fact Page template.  There is an "intro image" which is the image to the right of the copy, as per screenshot in https://github.com/DoSomething/dosomething/issues/3297#issuecomment-61518673.  Is that what you are referring to, @julielorch ?

**Comment by mikefantini** [comment]
@julielorch I was pretty sure we squashed testing gifs in the hero for now since we don't have a call to action for the header that makes sense given the context of the user looking for facts

**Comment by joolaay** [comment]
Great! I can, however, imagine requests for header images.
