### ISSUE TITLE
Message Broker / DS MBP errors

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3303]
Per @DeeZone on 10/31:

Something funky going on with message_broker_producer_update_7002 not being built on staging when doing a deploy. As a result dosomething_mbp_update_7002 fails as the database table is missing.

**Comment by deezone** [comment]
For the record, it's a race condition as @aaronschachter suspected. `dosomething_mbp_update_7002` runs first and fails as it's looking for the `message_broker_producer_productions` database table that's created in `message_broker_producer_update_7002`.

**Comment by aaronschachter** [comment]
Re-opening per @DeeZone comment in chat:

> Unfortunatly, dosomething_mbp has changed enough that the whole commit will need to be roled back. This includes the pin in the make file to use the older version of message_broker_producer module as well as changes in dosomething_mbp.
> All that being said, I'm working through getting it all working so we can do another round of testing on staging. The settings can be updated manually but there's still something that's preventing the transactions to be sent.

**Comment by deezone** [comment]
No need to roll back, https://github.com/DoSomething/dosomething/pull/3309 and https://github.com/DoSomething/message_broker_producer/compare/0.2.2...master address all of the issues.

**Comment by aaronschachter** [comment]
Re-opening until we're fixed

**Comment by aaronschachter** [comment]
I've added a `watchdog` into the `message_broker_producer_request` : https://github.com/DoSomething/message_broker_producer/pull/85

and get this output: https://gist.github.com/aaronschachter/a57d6e06888f69daaf99

**Comment by aaronschachter** [comment]
Closed by https://github.com/DoSomething/messagebroker-config/pull/42 !!
