### ISSUE TITLE
can't select a state in the school finder

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3316]
Looks like select field doesn't have any options.

https://s3.amazonaws.com/uploads.hipchat.com/34218/363821/Bfhyz1XY7UvyDHu/Screen%20Shot%202014-11-04%20at%204.57.52%20PM.png

**Comment by mikefantini** [comment]
also @aaronschachter can we remove Puerto Rico and Virgin Islands (if VI is there, or if any other non-50 states are there)? I can open a separate issue for this if you want

**Comment by aaronschachter** [comment]
Can we also remove them from the states dropdown in the Address field?  It would be best to keep in sync.

**Comment by mikefantini** [comment]
ah yeah i get that.. only thing that is a bit frustrating is that here we won't have any schools for them so we're kind of giving them false hope

so if it needs to stay synced I would say just keep PR/virgin islands

just feels kind of crappy because we're giving the user the allusion that it won't fail when we know it will

**Comment by aaronschachter** [comment]
I don't think its worth filtering this list based on whether or not we have schools there.  This can constantly be changing.

Note to self: I visited Yeah Science and the options were present on stage.  Went to sandbox and they went away. Then saw this error that @mikefantini was also seeing too:

Warning: Invalid argument supplied for foreach() in form_select_options() (line 2723 of /var/www/beta.dosomething.org/releases/20141104160507/html/includes/form.inc).

**Comment by mikefantini** [comment]
yeah i'm fine with not changing the options based on context

**Comment by aaronschachter** [comment]
This is because we rolled back the database on staging to debug Message Broker issues, and the codebase didn't match because an update wasn't executed.  Options now live.
