### ISSUE TITLE
Path-specific 404 page suggestions

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3317]
As we kill the legacy app, it will be important to have a few bits of preset copy to provide context for the user depending on which section of the legacy app they were coming from.

For example, if a user is coming from /projects/123, we'll want to provide them with copy that is projects specific.

**Updated description**

Since we only need suggestions for 2 URL patterns, we will just add 2 copy variables for each URL pattern into the admin form. e.g `dosomething_notfound_copy_projects` and `dosomething_notfound_copy_grants`

Each copy variable should be outputted as Markdown , using `check_markup($copy, 'markdown')`

**Original description:**
Ideal scenario is that we have a solid admin interface to configure what URL pattern maps to what copy.

I could see the following fields making sense for this:
- from https://legacy.dosomething.org/
- copy

Similar to here:
![image](https://cloud.githubusercontent.com/assets/6330971/4910541/fac4e7b0-6480-11e4-949f-e6182801f67a.png)

the trick is that we would want this to accept /\* so that all /project/\* got the same copy. Also I guess with this setup we would need to make one for /projects/\* and one for /project/*

Also if someone is hitting a preset path we'll want to also give them our recommended campaigns

Mocks: 
![image](https://cloud.githubusercontent.com/assets/6330971/4910574/8697959e-6481-11e4-8ab6-fb90abca7e01.png)

**Comment by itsjoekent** [comment]
Quick questions -
- Is the results coming from search results? Or manually set? 
- Is there a relation between the results copy and the header? If not than I don't see a reason to supply a specific node like in your example, just the bottom results would change depending if it's path specific or not.

**Comment by mikefantini** [comment]
1. @deadlybutter sorry what "results" are you referring to here? do you mean the campaigns that we recommend to them? if so, these are coming from our recommendation system @aaronschachter put together
2. the header will always be the same regardless if it's a "path specific" 404 or a "search results" 404. there only difference is what shows up below the header. what I was recommending was that we should have some sort of admin field set so that an admin can match copy to the field

for instance (obviously none of this is real copy):
- grants -> After 10 years of giving our grants we are no longer doing so. We gave out $10 billion dollars in grants. 
- clubs -> After 5 years of running clubs we are no longer doing so. Have an existing club? Get them involved in one of the campaigns below!
- projects -> We are no longer storing individual projects on our site, but check out one of the awesome campaigns below to get involved in.

**Comment by itsjoekent** [comment]
I think you answered what I was looking for, thanks!

**Comment by mikefantini** [comment]
fyi asking Ben for thoughts on copy for the different paths

this may include an update to the h3 above the 3 recommended campaigns

**Comment by mikefantini** [comment]
also as I was digging in more and trying to put content together it seems like we actually only need this for grants and projects

**Comment by aaronschachter** [comment]
Just curious -- Why not clubs?  Initial thought was to build a table to hold these.. although considering a leaner approach if we only need it for two (or three).  The trick being to not need to deploy code to add more (devs: i'm considering a big serialized array stored in a variable vs a table)

**Comment by mikefantini** [comment]
yeah that was my thought too @aaronschachter.. in reviewing Google Analytics again we've had <10 people go to a /club/\* page over the past 3 months.

And our FAQ (which is the first result you get if we follow our 404 w/ search results path for "start do something club") gives a good description of it being taken down.

Meanwhile /grants/\* received around 2000 entrances over that time and /project/\* has received about 8000 entrances in the past month alone.

**Comment by mikefantini** [comment]
so really we only need it for /grants/\* and /project/*

**Comment by aaronschachter** [comment]
Ok. we need to hold on this until design and data is finalized (e.g. do we need 2 separate fields or just the copy)

**Comment by mikefantini** [comment]
to clarify only need one copy variable (one for /project/\* one for /grants/*).

We will also have h3 copy above the recommended campaigns but this copy will be the same for both

**Comment by aaronschachter** [comment]
Updated issue description. Instead of a table of adding/editing records we can just use 2 copy variables and hardcode for `grants*` and `project*` as these are the only requested paths.  This saves us a lot of work of creating a Suggestion table and implementing add/edit forms for each record.
