### ISSUE TITLE
search results on 404 page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3318]
We'll want to split up parts of the URL, run a SOLR query, and display the results to the user.

Ex. /blog/puppies-running should do a SOLR query of "puppies running" and provide the user the top 4 search results for that query.

Mocks:
![image](https://cloud.githubusercontent.com/assets/6330971/4910640/2ad6b504-6482-11e4-8453-b12018472ea3.png)

**Comment by mikefantini** [comment]
from @blisteringherb:

Information about the MLT (more like this) blocks for solr:
/dosomething/html/profiles/dosomething/modules/contrib/apachesolr/apachesolr_search.module

You can create MLT blocks in the UI here - admin/config/search/apachesolr/search-pages and then load them with apachesolr_search_mlt_block_load($block_id). I believe those blocks are exportable through Features, but I'd have to take a deeper look to make sure.

Also in dosomething_search_apachesolr_query_alter(), there you can modify the query based on any number of parameters. It may not be necessary, but I figured I'd point it out just in case you need to tweak the MLT results for any reason.

**Comment by mikefantini** [comment]
also we'll want to exclude certain words in the path from the search.

unfortunately these paths we're set up so great to start with but to start the list of terms we'll want excluded:
- actnow
- actionguide
- tipsandtools
- background
- blog
- category
- tags
- news
- page
- quiz
- who
- what
- where
- which
- why
- when
- a
- an
- the
- to
- how
- your

filtering https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dHNiRU5sVURscm80N2dCYlItUWNWSVE&usp=drive_web#gid=0 by 404 w/ search helps give an idea of the types of pages that will meet this path that are still getting a decent amount of traffic

**Comment by itsjoekent** [comment]
Backend functionality: https://github.com/DoSomething/dosomething/pull/3394

Missing the terms filter, doing that next
