### ISSUE TITLE
change display of search results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3319]
need to make fender updates once #3207 is set

should look like this (with Search in purple header as is):

![image](https://cloud.githubusercontent.com/assets/6330971/4910878/7c922e66-6485-11e4-9703-821da86ff554.png)

We would no longer display results as numbered, we would no longer pull in the snippets that contain the phrase that is searched, and we would pull in the cover image for campaigns and use our logo thumbnail for pages that don't have cover images.

**Comment by mikefantini** [comment]
also note for taxonomy collections that show up in search we'd want to display:
- Title
- Cover Image
- Description (ideally cut off after x characters to fit display).

**Comment by mikefantini** [comment]
as @blisteringherb mentioned, fender work on this should be done on this branch: https://github.com/blisteringherb/dosomething/tree/search-appearance

**Comment by barryclark** [comment]
We should change on both the 404 page and the search page. We can chat over this shortly @sbsmith86 :)

**Comment by itsjoekent** [comment]
@barryclark I was holding off on search results for this reason, figured it would be better to reuse the work done here

**Comment by mikefantini** [comment]
yeah not yet implemented on the 404 page, but @deadlybutter and @blisteringherb will start talking through this today

**Comment by sbsmith86** [comment]
@mikefantini @barryclark Will pagination of search results still look the same or is that being updated as well. Currently: http://grab.by/C8AM

**Comment by barryclark** [comment]
cc @DFurnes for his thoughts too

**Comment by DFurnes** [comment]
Is this for the 404 page, or all search results? My thought would be no pagination on 404 page, and up to @DoSomething/design for styling elsewhere. Certainly couldn't hurt to give it a touch up. :)

**Comment by itsjoekent** [comment]
the 404 page mock does not call for pagination

![image](https://cloud.githubusercontent.com/assets/897368/5019250/e1ac98de-6a8b-11e4-9de4-de5486f8b078.png)

**Comment by mikefantini** [comment]
sorry @sbsmith86 pagination was something I meant to flag as something to talk through.

I vote for no pagination on 404 page (although maybe show up to 10 results i.e. 1 page of results?). 

And then on search results can we have a first implementation with just our existing pagination and then see if @lkpttn or @kerigoff have changes they'd want to make?

**Comment by sbsmith86** [comment]
@mikefantini Yea that makes sense. Just making sure I wasn't missing any mocks.

**Comment by mikefantini** [comment]
no i appreciate you asking @sbsmith86!

**Comment by mikefantini** [comment]
from @DFurnes on #3207 

For the image, we can use the same images as our [touch icon](https://github.com/DoSomething/neue/blob/dev/assets/images/apple-touch-icon-precomposed.png). It's in `paraneue_dosomething/bower_components/neue/dist/assets/images/`.
