### ISSUE TITLE
get Zendesk set up on Canada

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3322]
**UPDATE:**

The approach is to set up Zendesk for Canada to avoid all more affiliate-only logic.

Once #3351 is merged and `dosomething_zendesk` is uninstalled on all affiliate sites (per #3349), the steps will be to:
- [x] manually enable DoSomething Zendesk module on Canada
- [x] set up its auth variables
- [x] set its dosomething_zendesk_group_id to the Canada Zendesk group.

**ORIGINAL ISSUE:**

Canada doesn't have zendesk set up so this is a dead link.

Ideally language would be "Still have issues? Email us at teensforjeanscanada@dosomething.org with your school name and provence."

![image](https://cloud.githubusercontent.com/assets/6330971/4912309/7a4f501e-649b-11e4-8556-621599434948.png)

**Comment by mikefantini** [comment]
one possible route (although no idea how hard this is) would be to flag the "Still having issues..." bit to not display for Canada and then we can just include the text above in the admin copy config variables

**Comment by mikefantini** [comment]
from standup the plan is to investigate turning on zendesk for Canada and have all questions from Canadian users go into the one Canadian group

**Comment by aaronschachter** [comment]
Up and running on Canada prod.
