### ISSUE TITLE
Optimizely snippet is causing script errors on production

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#3342]
See Web Inspector console on www.dosomething.org:

![screen shot 2014-11-06 at 12 10 54 pm](https://cloud.githubusercontent.com/assets/583202/4940154/fd18475c-65d7-11e4-94b0-134c7134fd5d.png)

Seems to be coming from the Optimizely module.

/cc @DeeZone

**Comment by DFurnes** [comment]
Seems to mostly be coming from an `optly.Cleanse` method.

**Comment by DFurnes** [comment]
This seems to have been fixed sometime, so closing.

**Comment by deezone** [comment]
Weird...
