### ISSUE TITLE
school finder doesn't work on ie8/ie9 operating system windows 7

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3354]
never actually shows results, just spins searching for matches

**Comment by mikefantini** [comment]
happening in ie9 as well

**Comment by mikefantini** [comment]
works in ie10 and safari and firefox

**Comment by DFurnes** [comment]
Looks fine on [Firefox 32 in BrowserStack](https://cloud.githubusercontent.com/assets/583202/4944250/e6261ab4-65fb-11e4-8982-d501657fd254.png). Continuing to investigate.
