### ISSUE TITLE
Cleanup DS User variables

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3364]
Weird PHP things happening but the `if (!dosomething_settings_is_affiliate()) {` checks in the DS User install hooks are returning TRUE.

We can manually set things right via drush, but should change the code in these update hooks so people don't copy/paste this funkyness.

`dosomething_user_update_7006` set the `dosomething_user_validate_address` variable for all affiliates.

And apparently, `dosomething_user_update_7004` set the Country code to US for all affiliates too:

![screen shot 2014-11-07 at 11 30 45 am](https://cloud.githubusercontent.com/assets/1236811/4956384/add85bc2-669b-11e4-89e5-4a308c4391e1.png)

**Comment by sergiitk** [comment]
Note: it's easier to use `bin/drush-intl vget` and `bin/drush-intl vset -y`.

**Comment by sergiitk** [comment]
QA's dosomething_is_affiliate should work fine:
![image](https://cloud.githubusercontent.com/assets/672669/4956498/8ac457c0-669c-11e4-948d-9e5d9a38a616.png)

**Comment by aaronschachter** [comment]
Right, but I think the trick here is the usage of the function.. particular the negative of the function... `!dosomething_settings_is_affiliate()`...

**Comment by sergiitk** [comment]
@aaronschachter why would you think it would work wrong?

**Comment by aaronschachter** [comment]
Well, because it has been.  All the US only variables have been set on the affiliate sites.  Still haven't looked into how the heck to replicate though.

**Comment by sergiitk** [comment]
As expected...
![image](https://cloud.githubusercontent.com/assets/672669/4959210/344a6168-66b6-11e4-8a25-1ef253a17351.png)
