### ISSUE TITLE
User Email Opt-in preferences

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3365]
Build ability for users to opt-out of:
- User Digest (Here’s the campaigns youre signed up for and here’s the details that are new this week).  Currently weekly
- Campaign updates (Emails specific to a campaign)
- User Events (Your birthday, your anniversary)

Upon user registration, users should saved with all of these values set as "subscribed".
- [ ] Message Broker needs preferences stored in MB User DB, and add logic to conditionally send messages
- [x] Create new MB Production entry for a User Profile update 
- [ ] Adding mutli-value checkbox field to User Profile for Email preferences
- [ ] Upon User Profile submit: If subscription values have changed, submit a `message_broker_producer_request`, sending the User Profile object in the payload
- [ ] User subscription _only_ settings page to be accessed via an "unsubscribe" link at the bottom of DS.email messages. The encryped link needs to contain the target email address and a time sensitive key.
- [ ] Update Mailchimp subscription setting using Message Broker mbc-userProfile-mailchimp consumer.

cc @DeeZone

**Comment by deezone** [comment]
New production entry "transactional-user_profile_update" to reference when sending `message_broker_producer_request() when user profile is updated.
https://www.dosomething.org/admin/config/services/message-broker-producer/add-edit-production/transactional-user_profile_update

**Comment by aaronschachter** [comment]
Shouldn't best practice for us be to add production entries via MBP install hook?  That way we have a record of it (and its populated in staging), and can add inline comments to better document why we're adding it.

**Comment by deezone** [comment]
Good point!

**Comment by aaronschachter** [comment]
Do you mind deleting the entry and adding it via install hook then?

**Comment by deezone** [comment]
Done and on my way...

**Comment by aaronschachter** [comment]
Just checking / making sure I understand: you don't need to update the mb-config.json, because it's using all existing exchanges/queues, right?

**Comment by deezone** [comment]
Yep, that update is in the works too: https://github.com/DoSomething/messagebroker-config/issues/43 as it will require a new queue off of the transactionalExchange.

**Comment by deezone** [comment]
Project moved to stand alone solution: https://github.com/DoSomething/mbc-user-subscriptions/issues/2
