### ISSUE TITLE
all paragraph/bulleted list text should be 3/4 length

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3370]
![image](https://cloud.githubusercontent.com/assets/6330971/4978891/2367c306-68f3-11e4-8b4d-feee5b3d67a7.png)

![image](https://cloud.githubusercontent.com/assets/6330971/4979018/0dd8a2f2-68f4-11e4-8103-3b909a549083.png)

uses the same container as the Do It section on the campaign template

![image](https://cloud.githubusercontent.com/assets/6330971/4978916/639356c0-68f3-11e4-9f99-3fce699ab7c8.png)

on mobile this should go back to full length

cc: @DFurnes @weerd if you have any other details to add like we chatted about the other day

**Comment by DFurnes** [comment]
@tjrosario This may need to done case-by-case by just setting these containers/paragraphs to span 9 columns. We'll be thinking about how we want to adjust our layout patterns to work better in an upcoming sprint.
