### ISSUE TITLE
User Profile: I'm Doing buttons

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3376]
Add "Prove It" buttons to each Figure for the "I'm Doing" section.

@weerd suggested that these be added as a separate `<div>` instead of including within the `description`.  @weerd -- are there Neue updates needed for this?

**Comment by weerd** [comment]
No need for a `<div>` if not needed. A simple `<a>` with appropriate button classes should be fine. Just need to likely add updates to center button in pattern.

**Comment by itsjoekent** [comment]
above comment works fine ^, no changes needed

![screen shot 2014-12-16 at 3 40 47 pm](https://cloud.githubusercontent.com/assets/897368/5461543/0935dcb2-853a-11e4-97a1-a3461c182ac0.png)
