### ISSUE TITLE
add title field to taxonomy collections

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3380]
please add to cause, action type, and issue

**Comment by aaronschachter** [comment]
I'd suggest this is more of a Title Override, so there are less fields for editors to fill out.  If a value exists for Title Override, use it, otherwise use the regular Taxonomy term.

**Comment by mikefantini** [comment]
@aaronschachter so this is an optional field?

**Comment by aaronschachter** [comment]
Yup, that's the idea.
