### ISSUE TITLE
add facts header field to taxonomy collections

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3381]
again add this to cause, action type, and issue terms

**Comment by aaronschachter** [comment]
What's the reasoning behind not just keeping this as "Facts about [Title]" ? If we have the "title override" field (#3380), it could use that for the [Title]

**Comment by mikefantini** [comment]
@Bladt can you please weigh in with your thoughts? Maybe some examples of what you were thinking for the Facts title?

**Comment by Bladt** [comment]
Different cause spaces have different search patterns. For instance, people searching for bullying information want "statistics and definitions". 

Being able to overwrite the title would help some. Would this title be different than the one displayed on the header? For instance, for the Environment collection, I would want to include "pollution" in the facts section header, but not the for the page title.

**Comment by aaronschachter** [comment]
Ok.  I think this should be the same deal as #3380 - optional. If not set, it defaults to "Facts about [term name]" but it can be overridden with whatever text the field is set to.

**Comment by mikefantini** [comment]
works for me
