### ISSUE TITLE
Approved Reportback File flag + Bulk Approval

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3389]
- [x] Use a new Reportback Files status field instead of Flag module to store Reportback Image status
- [x] Add admin views to allow Editors to approve/promote/flag Reportback Files
  - [x] Add admin tab to a Campaign node, and filtering by the nid. Don't display Campaign Title
  - [x] Add admin tab to a Cause term tid, filtering by all nodes with the primary_cause as tid.  Display Campaign Title

**Comment by aaronschachter** [comment]
Thinking more about this, and perhaps adding a new Approval flag is not ideal.  We may need to refactor these reportback files to contain a Status field with various states:
- Pending
- Approved
- Promoted
- Flagged

This would mean refactoring the current Promoted / Flagged functionality.  Sure, we could automatically create the Flag records based on its status but that feels like more work than it's worth.

**Comment by aaronschachter** [comment]
As I'm beginning to build this out, I'm considering if we may want a status for "Exclude".  This would be for a Reportback where the quantity and text all are legit, but the pic is uploaded sideways.  The Reportback shouldn't be flagged, as it should still be counted towards overall numbers, but the pic should be excluded from the gallery.

@julielorch  @mikefantini thoughts?

**Comment by mikefantini** [comment]
makes sense to me, we'll just have to train the team up properly on using it
