### ISSUE TITLE
need code for optimizely test for padding in tiled campaigns view

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3392]
24 px in between each tile

need this for @Bladt to run an optimizely test on the homepage

@lkpttn @weerd can you please update this description with details we chatted through the other day? just wanted to make sure there was an issue in

**Comment by weerd** [comment]
```
$ = jQuery;
if ($('body').hasClass('front')) {
  $gallery = $('.gallery');
  $items = $gallery.find('> li');
  $gallery.css({'background-color':'#fff', 'padding':'12px'});
  $items.css('padding', '12px');
}
```

Sent this code via email, but adding here for closing the issue. @Bladt I'd still like to go over with you how it will be tossed into Optimizely, etc so I can make sure it runs after jQuery is already loaded :)
