### ISSUE TITLE
Contact Us for International Affiliates

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3402]
Email addresses for each of the affiliates:

Nigeria -  help@unveilingafrica.org
Botswana - botswana@yaldafrica.org
Congo - empower@congoleaders.org
Kenya - dosomethingkenya@gmail.com
Ghana - dosomething@yesghana.org
UK - info@vinspired.com
Canada -  dosomething@takingitglobal.org

cc @aaronschachter @DeeZone @mshmsh5000

**Comment by angaither** [comment]
closing, this was done on those static content pages!
