### ISSUE TITLE
Create new redirects from legacy to beta

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3404]
we need a script to run 100+ redirects from legacy to beta

incomplete Google spreadsheet of redirects is here: https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGNhQ2VMNnU5Ynh5Y3cwVlJhSTdHVUE#gid=1

waiting on content to be created to finalize

will add CSV here once final, but above spreadsheet can be saved as a CSV if we want to test anything

@mshmsh5000

**Comment by mshmsh5000** [comment]
This requires #3414 to be completed, although we can generate scripts while the work is still being done.

**Comment by mikefantini** [comment]
going to reopen just so we know to actually run the script

**Comment by mikefantini** [comment]
ok @mshmsh5000 [this spreadsheet](https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGNhQ2VMNnU5Ynh5Y3cwVlJhSTdHVUE&usp=sharing#gid=7) is all set.

The redirects.preprocessed.production tab is completed and ready to go.

**Comment by mshmsh5000** [comment]
These were imported into production on 2 Dec.

**Comment by mshmsh5000** [comment]
Because [Global Redirect](https://www.drupal.org/project/globalredirect) isn't running on prod, we decided to import redirects with beta aliases instead of beta canonical paths as the targets.

**Comment by mshmsh5000** [comment]
All done!
