### ISSUE TITLE
Add link to "Blog" in the footer

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3406]

**Comment by aaronschachter** [comment]
@barryclark We don't need any code for this, this can just be added on http://staging.beta.dosomething.org/admin/appearance/settings/paraneue_dosomething

**Comment by tjrosario** [comment]
@barryclark do we want this in the first column?

**Comment by barryclark** [comment]
Yea, that'd be sweet. Cheers @tjrosario
