### ISSUE TITLE
Import existing Legacy redirects into Beta

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3409]
Any redirects we've added into legacy to point to beta (e.g. "/clothes" to "/campaigns/comeback-clothes") need to be imported into beta in order to kill legacy.

cc @mikefantini

**Comment by mshmsh5000** [comment]
First question here: How will we evaluate whether a redirect points to beta?

The simplest approach may be time-based: we could prove this out by doing a spot test, but I'm guessing that just about 100% of redirects created since mid-March point to beta.

**Comment by mshmsh5000** [comment]
One example of how to cull useless or abandoned redirects:

```
SELECT source, redirect, FROM_UNIXTIME(access) FROM redirect WHERE `count` > 5  AND access > UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 30 DAY)) ORDER BY access DESC
```

**Comment by mikefantini** [comment]
if I get a CSV of these I can spot check and see which ones are needed/not

**Comment by mikefantini** [comment]
@mshmsh5000 will this include ones like epicbookdrive.com?

**Comment by mshmsh5000** [comment]
@mikefantini [The CSV to review.](https://docs.google.com/a/dosomething.org/spreadsheets/d/1xrpAdq1JOqGZDptgq_TAP47cpVwXIWUaMxeSCNYWIII/edit?usp=sharing)

This won't include parked domains, if that's your question. We'll have to do a separate review of that based on DNS records.

**Comment by mikefantini** [comment]
hmmm @mshmsh5000 should we clean up redirects that then lead to redirects? 

i.e. whatsyourthing/Animal+Welfare to taxonomy/term/29 to taxonomy/term/16 (which would be /volunteer/animals)

**Comment by mikefantini** [comment]
also what should we do about something like thumb-wars/bumper-stickers to node/534290? This node doesn't exist on the beta app.

**Comment by mikefantini** [comment]
just some thoughts after a quick browse.. i can definitely look into this more later depending on how granular we want to get

**Comment by mikefantini** [comment]
sorry last thought, should we also set this up so that it gets redirect to the beta canonical path? if that path doesn't exist it would make review a bit easier (either set it to a different canonical path or just don't import the redirect)

**Comment by mikefantini** [comment]
also just a note that we'll be able to get rid of the /grants -> /campaigns redirects because of the path specific copy we now have to handle all /grants/\* pages

**Comment by mikefantini** [comment]
and for post-import cleanup we'll be able to remove redirects that lead to a 404 page correct?

**Comment by mshmsh5000** [comment]
For post-import cleanup, we'll be able to remove any redirects we want, yes. I'm going to try an import to QA now, as a sanity check.

**Comment by mshmsh5000** [comment]
I did one run against QA. The final imports are logged [in this new tab](https://docs.google.com/a/dosomething.org/spreadsheets/d/1xrpAdq1JOqGZDptgq_TAP47cpVwXIWUaMxeSCNYWIII/edit#gid=456254352).

I've started commenting where I need to fix the logic for a few, mostly URLs that are redirecting to beta.ds or other full URLs. The others should be available for spot-testing.

**Comment by mshmsh5000** [comment]
OK, forreals @mikefantini, the [redirects.processed tab](https://docs.google.com/a/dosomething.org/spreadsheets/d/1xrpAdq1JOqGZDptgq_TAP47cpVwXIWUaMxeSCNYWIII/edit#gid=2030114228) has cleaned up redirects. This doesn't check whether the target URL exists in the beta app.

[This tab](https://docs.google.com/a/dosomething.org/spreadsheets/d/1xrpAdq1JOqGZDptgq_TAP47cpVwXIWUaMxeSCNYWIII/edit#gid=1270754896) skips all target URLs that Drupal doesn't think exist in beta.

Let's make the final call together and then run the redirect scripts from here and #3404.
