### ISSUE TITLE
need script that retrieves url aliases from machine paths and vice versa

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3414]
doc is here: https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGNhQ2VMNnU5Ynh5Y3cwVlJhSTdHVUE&usp=sharing#gid=1
- [ ] need beta machine path from beta url aliases in column E
- [ ] need legacy url aliases from legacy machine paths in column D

**Comment by mshmsh5000** [comment]
Need a script that 
1. Reads in the current CSV
2. Adds a new column of **Beta canonical paths** to each row with a **Beta path** entry
3. Looks up all URL aliases in legacy for each **Legacy canonical path**
4. Inserts a row for each legacy alias, repeating the info in common (legacy canonical path, beta path, beta canonical path)

**Comment by mshmsh5000** [comment]
RE: **Step 3**, turns out none of the 114 legacy paths in the CSV has multiple aliases.

**Comment by mshmsh5000** [comment]
RE: **Step 3**, of course -- some of these have multiple _redirects_, which are stored in a separate table. I'll update the logic to check redirects as well as aliases.

**Comment by mshmsh5000** [comment]
@mikefantini Updated sheet [available here](https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGNhQ2VMNnU5Ynh5Y3cwVlJhSTdHVUE&usp=sharing#gid=4) for review. Please do a sanity check and let me know if anything looks/smells weird. Thanks!

**Comment by mikefantini** [comment]
@mshmsh5000 did a quick run through and everything checks out minus the one comment I made about /campaigns not having a canonical url on beta

**Comment by mikefantini** [comment]
@mshmsh5000 just realized there may be an extra space at the end of some of the beta links.. hopefully this is something that can be easily cleaned on your end? if not let me know and i can see what i can do

**Comment by mshmsh5000** [comment]
@mikefantini The script "trims" all of the strings, removing trailing white space.

**Comment by mshmsh5000** [comment]
Also updated the ["redirects.processed" tab](https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGNhQ2VMNnU5Ynh5Y3cwVlJhSTdHVUE&usp=sharing).

**Comment by mikefantini** [comment]
@mshmsh5000 it makes sense that some of the volunteer/ don't have a beta canonical path because they aren't yet created (will get these up and published in the morning).

But I'm not sure why the facts/ aren't returning a beta canonical path. Any thoughts?

**Comment by mshmsh5000** [comment]
These results were from QA. I have to run this in the production environment tomorrow -- might just be old data.

**Comment by mikefantini** [comment]
@mshmsh5000 have you run this in prod? do you have an update sheet of legacy aliases and beta canonical paths?

**Comment by mshmsh5000** [comment]
Latest from production: https://docs.google.com/a/dosomething.org/spreadsheet/ccc?key=0ApfENCbpVZv9dGNhQ2VMNnU5Ynh5Y3cwVlJhSTdHVUE#gid=7

**Comment by mshmsh5000** [comment]
( @mikefantini )
:eyes:
