### ISSUE TITLE
404 page header size reduction

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3421]
We want to reduce the size of the header on 404 pages from 620px on to 520px on desktop and from 465px to 365px on mobile. Should be altering the -centered modifier?

@mikefantini

**Comment by DFurnes** [comment]
:heavy_check_mark: to specifically altering the `-centered` modifier.

**Comment by barryclark** [comment]
@sbsmith86 Would you be able to tackle this one and holler at @lkpttn / @DFurnes if you have any questions? Ty!

**Comment by sbsmith86** [comment]
@lkpttn @DFurnes Do you mean altering the -centered modifier in neue or overwriting in the theme it so this change stays specific to just 404 pages?

**Comment by DFurnes** [comment]
Let's alter the `-centered` modifier in Neue.

**Comment by DFurnes** [comment]
Right now, it's only being used for the 404 page so there's no risk of collateral damage. :)

**Comment by sbsmith86** [comment]
Merged this fix into neue this morning.
