### ISSUE TITLE
Homepage images are broken

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3422]
No images appear.

Per @weerd : JS error is killing the JS from switching the image:
Uncaught TypeError: Cannot read property 'stripeAPIPublish' of undefined

This was introduced by https://github.com/DoSomething/dosomething/pull/3418

**Comment by aaronschachter** [comment]
This must be because we're conditionally adding the JS setting when `dosomething_payment_form` is called, but the Donate.js is always loaded on every page.

**Comment by DFurnes** [comment]
We should always be including a fallback for these `Drupal.settings` values when they're undefined (or at least including them within a `try...catch` block so they don't explode everything else).

**Comment by DFurnes** [comment]
See [date validation method](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/js/validation/auth.js#L67-L72) for an example.

**Comment by aaronschachter** [comment]
Right. All of the Donate JS code in #3412 should really only be loaded when a Donate Form is embedded on a page.  My plan was to keep the `dosomething_payment` module disabled on affiliate sites, since there's no need for it (which also means all the Donate JS code is not needed also)

**Comment by aaronschachter** [comment]
@DFurnes Any idea if it's possible for us to add all the code in #3412 via `drupal_add_js` like we're doing here?  https://github.com/DoSomething/dosomething/blob/v0.3.106/lib/modules/dosomething/dosomething_payment/dosomething_payment.module#L81

**Comment by aaronschachter** [comment]
My JS is atrocious.  Trying to hotfix

```
  stripeAPIKeys = {
    try {
      publish: Drupal.settings.dosomethingPayment.stripeAPIPublish
    } catch (e) {
      publish: ""
    }
  };
```

but no luck.  Can a fender have mercy on my soul and pls guide me how to hotfix (or better yet, can we conditionally only load the Donate / Stripe JS per https://github.com/DoSomething/dosomething/issues/3422#issuecomment-63140943) ?

**Comment by DFurnes** [comment]
For taking care of situations where `Drupal.settings` variable isn't set:

``` js
var stripeAPIKey;

try {
  stripeAPIKey = Drupal.settings.dosomethingPayment.stripeAPIPublish
} catch(e) {
  stripeAPIKey = "<fallback>" // or gracefully handle lack of API key
}
```

For conditionally running the Donate code, we should just move the API key check inside the `init` method here: https://github.com/DoSomething/dosomething/blob/c85076d1ae56d22852bc4b44da992161665936c6/lib/themes/dosomething/paraneue_dosomething/js/donate/Donate.js#L8-L10
