### ISSUE TITLE
Expose multiplayer SMS game IDs in views for A/B testing

### ISSUE THREAD

**Issue by tongxiang** [DoSomethingArchive/legacy-website#3423]
We need to expose the multiplayer SMS game IDs in our views for Optimizely A/B testing. [Code block where multiplayer variables are hidden.](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.forms.inc#L258)

**Comment by tongxiang** [comment]
@Bladt

**Comment by tongxiang** [comment]
Current Science Sleuth (alpha version) ID: 101. 

Test Science Sleuth (beta version) ID: 201. 

@Bladt

**Comment by aaronschachter** [comment]
@tongxiang @Bladt This will be available upon our next deployment to production.  You can check staging now to confirm.

**Comment by aaronschachter** [comment]
This has been deployed to production, @Bladt @tongxiang

**Comment by tongxiang** [comment]
Danke schön @aaronschachter!
