### ISSUE TITLE
404 page video needs a poster image

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#3424]
The `video` tag on the 404 page needs a `poster="…"` attribute to show an image while the video file is loading. Ideally we want this to be the same as the first frame of the video.

Otherwise the user will just see a black background while the video is loaded.

/cc @mikefantini

**Comment by itsjoekent** [comment]
for reference (thanks furnes): ffmpeg -i INPUT_FILE.mp4 -frames 1 POSTER_OUTPUT.jpg
