### ISSUE TITLE
path specific copy should be 3/4 length

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3427]
this path specific copy should be left aligned 3/4 length; similar as in #3370

from @DFurnes This may need to done case-by-case by just setting these containers/paragraphs to span 9 columns.

![image](https://cloud.githubusercontent.com/assets/6330971/5054927/7ae33adc-6c29-11e4-8b49-5316c0144366.png)

**Comment by mikefantini** [comment]
this is the same treatment we use for campaigns on the action page in the do it section (https://beta.dosomething.org/campaigns/teens-jeans)

![image](https://cloud.githubusercontent.com/assets/6330971/5078249/16fc651e-6e79-11e4-9ecc-9f2e35beb62c.png)

**Comment by sbsmith86** [comment]
@mikefantini Does 3/4 length me 3/4 of the width of the page? 

@DFurnes What do you mean by "case-by-case" basis?

**Comment by mikefantini** [comment]
@sbsmith86 yeah it should be 3/4 width of the page (so 9 columns rather than 12 on the grid)

and I believe what @DFurnes meant by case-by-case basis is that it's not a defined pattern in neue yet (opened up a bigger can of worms, so we're holding off a bit to define that pattern) and instead this rule needs to be set in each individual case

**Comment by sbsmith86** [comment]
@mikefantini gotcha. thanks!

**Comment by DFurnes** [comment]
Yep!
