### ISSUE TITLE
dosomething_search_index view mode causes overridden Features

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3449]
Need to Features Update  (`drush fu`) for numerous features which are appearing overridden, to include the `dosomething_search_index` view mode added in #3359 

![screen shot 2014-11-18 at 8 20 07 am](https://cloud.githubusercontent.com/assets/1236811/5087922/c2cc9288-6efb-11e4-8a54-a758816b7fbc.png)

**Comment by aaronschachter** [comment]
#4766

**Comment by sergiitk** [comment]
Thanks @aaronschachter.
