### ISSUE TITLE
load test 404 page w/ search

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3461]
need to apply ?/VERSION to a www. URL in production and load test

we'll have to run this long enough so that we can monitor this in New Relic (minimum 10 minutes)

if we don't see any effects in 10 minutes, we can add more agents to increase the load

cc: @mshmsh5000

**Comment by itsjoekent** [comment]
Leaving this here for reference 

Ran the load test from ~2:12 to ~2:22 PM. Pushed 2 requests per second to random URL's that would trigger a search, appended the /?/VERSION so it was redirected to the beta app. 

@blisteringherb any signs of spontaneous combustion or explosive materials on New Relic? (I have no idea what to look for)

**Comment by blisteringherb** [comment]
@deadlybutter Nothing looks out of the ordinary from the time period for your test.

**Comment by itsjoekent** [comment]
sweet, gonna say this issue is closed than. Thanks @blisteringherb
