### ISSUE TITLE
some campaigns are showing up multiple times in search

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3468]
![image](https://cloud.githubusercontent.com/assets/6330971/5098435/0dada186-6f54-11e4-91e4-02a8b8ba2e1f.png)

![image](https://cloud.githubusercontent.com/assets/6330971/5098440/1534b9bc-6f54-11e4-9b03-b3dca590319e.png)

and I confirmed that these are all the same node (nid=56 for crisis crew)

**Comment by blisteringherb** [comment]
I'm seeing the correct results showing up. The cron job may have run and fixed the issue.
![image](https://cloud.githubusercontent.com/assets/28132/5100423/2d6ff454-6f74-11e4-932d-cd32c70aaabb.png)

**Comment by mikefantini** [comment]
@blisteringherb if you go to page 2 or page 3 of the results you'll see what I mean. Sorry I should have been more clear about that

**Comment by blisteringherb** [comment]
@mikefantini It looks like there were two instances of the index.  I removed one and reindexed, and now things seem to look good.

**Comment by mikefantini** [comment]
@blisteringherb hmmm now seeing multiples of Senior Socials and Ban Binaries on pages 2 and 3 of a "bullying" search:

![image](https://cloud.githubusercontent.com/assets/6330971/5107762/4c69bddc-6fd2-11e4-83ed-ad86d395d53a.png)

![image](https://cloud.githubusercontent.com/assets/6330971/5107771/653eb678-6fd2-11e4-9b94-3db1bf6ff4b6.png)

**Comment by blisteringherb** [comment]
I've taken a look in the index itself and each campaign is indexed only once, so it seems that this is possibly an issue with the pagination.  I'd suggest trying to print out all results on one page to see what's generated there.

**Comment by mikefantini** [comment]
assigning over to @sbsmith86. let me know if you have any questions

**Comment by mikefantini** [comment]
no longer seeing this on bully text or crisis crew, but still seeing this with senior socials and donate on the 3rd page of a "bullying" search

![image](https://cloud.githubusercontent.com/assets/6330971/5173896/7fe38dc4-73fa-11e4-950c-0e4da775404b.png)

**Comment by mikefantini** [comment]
once prod started acting properly again this was resolved

**Comment by sbsmith86** [comment]
@mikefantini Sweet! :candy:
