### ISSUE TITLE
Site Administrator role

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3472]
- Can administer redirects
- Can edit homepage nodes (remove access from Editors)

**Comment by aaronschachter** [comment]
@mikefantini Other permissions to add to this?  Maybe only a Site Admin can create/edit notfound nodes?

**Comment by mikefantini** [comment]
@aaronschachter who are you imagining having this role? Someone like Deluca and Calvin?

**Comment by aaronschachter** [comment]
Whoever is responsible for adding and maintaining "vanity URLs".  e.g. dosomething.org/clothes

**Comment by mikefantini** [comment]
I'd rather keep @lkpttn in charge of not found nodes and he needs enough permissions that keeping him admin seems to make sense

so I think just keeping it at these two permissions makes the most sense
