### ISSUE TITLE
SMS Reportback Caption

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3484]
On the web, we are requiring a caption to be entered along with each Reportback Image.

SMS Reportbacks should follow suit.

**Comment by jonuy** [comment]
@aaronschachter  are captions required? What happens if a report back is submitted from SMS that doesn't include a caption?

**Comment by aaronschachter** [comment]
They are required on the web, but things aren't breaking right now or anything like that -- SMS reportbacks are just being saved without them.  We'll need the captions in place for going live with the new Reportback Gallery (as the caption is included underneath each photo in it).

**Comment by jonuy** [comment]
Hm if that's the case, now might be the best time to do the work that pulls the SMS report back code out of Drupal and into the dedicated SMS app. Is this time sensitive? Or can this be something we work on next sprint?

**Comment by aaronschachter** [comment]
Next sprint sounds good, as we're hoping to close out the Reportbacks 2.0 milestone in mid December.  There are `campaigns/[nid]/reportback` and `campaigns/[nid]/signup` endpoints in the API that will allow unique paths per mDatas, but we'll need to authenticate to use them.  Once we're ready to start on this, we can talk through that process.

**Comment by aaronschachter** [comment]
Note to self: Make sure the caption property works with said Reportback API endpoint (which we currently don't use anywhere yet)

**Comment by aaronschachter** [comment]
Confirmed that the `campaigns/[nid]/endpoint` supports posting the Image Caption.  Closing this issue, as it was added for making the changes into the `dosomething_sms` module.  @uy is working on deprecating this module and using the API to post Reportbacks, so if we need to collect Caption, an issue should be opened in the node app.

**Comment by aaronschachter** [comment]
@mikefantini Assuming we don't need SMS reportbacks to capture Captions for Reportbacks 2.0 launch?

**Comment by mikefantini** [comment]
yeah moving to 2.0.1 - looking into it today and will reopen if it seems like we need this (i.e. center crops are mostly viable on SMS reportbacks)
