### ISSUE TITLE
Donate Form logging

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3489]
For all successful transactions, log the:
- token
- amount
- email (?)

**Comment by mshmsh5000** [comment]
Also the [customer create](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_payment/dosomething_payment.module#L338) event -- we should be able to see the created customer object in the logs.

Let's log the whole response object for successful transactions. If we start getting flooded with donations, we can make this less verbose.
