### ISSUE TITLE
Blog image header - create admin ability to edit image

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#3491]
Hiyo, 

Currently the header image on our blog is hardcoded. We need the ability to change the image at will. Something we talked about at launch but now it's necessary change the image. Hi @barryclark!

Thanks, holler w ??'s.

**Comment by aaronschachter** [comment]
@julielorch Can you please post this issue (and all future blog related issues) into the repo for the DS Blog instead? https://github.com/DoSomething/dosomething-blog

**Comment by joolaay** [comment]
Yes sorry!
