### ISSUE TITLE
Create build job on cerebro jenkins

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#35]
Create a build job on the cerebro jenkins instance that mimics the current steps in the wercker script.  The job should:
- Be triggered on commits
- Update merge statuses in github
- Throw hipchat notifications to the developers chat window

We should deprecate the wercker build once this is functional

**Comment by mchitten** [comment]
1. `drush make build-dosomething.make html`
2. `drush site-install dosomething --db-url=mysql://USER@localhost/dosomething -y`
3. `drush en simpletest -y`
4. `drush vset --yes simpletest_verbose FALSE`
5. `drush runserver --server=builtin 8080 & sleep 4`
6. `drush test-run DrupalGotoTest --xml --uri=http://127.0.0.1:8080`

**Comment by mchitten** [comment]
Done.
