### ISSUE TITLE
need to remove redirects from beta to legacy

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3509]
will add more detail later but for example /campaigns/would-you-rather to node/731226 on legacy

**Comment by mikefantini** [comment]
might only be this one actually... not sure

**Comment by mikefantini** [comment]
Searched https://beta.dosomething.org/admin/config/search/redirect and found the /campaigns/would-you-rather to node/731226 (legacy node) is the only current example of a beta to legacy redirect that we have.

![image](https://cloud.githubusercontent.com/assets/6330971/5191741/f6e29fb8-74be-11e4-878e-42cb40f63b6f.png)

can we just kill this in beta or does it need to be nixed in varnish as well?

@blisteringherb @mshmsh5000

**Comment by blisteringherb** [comment]
@mikefantini You should be able to just kill it in beta.

**Comment by mikefantini** [comment]
sweet. did it. done. closing.
