### ISSUE TITLE
Fact Devel: Notice messages when creating Facts

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#351]
Notice: Undefined index: fact in dosomething_fact_devel_create_facts() (line 80 of /vagrant/modules/dosomething/dosomething_fact/dosomething_fact_devel/dosomething_fact_devel.module).
Warning: array_keys() expects parameter 1 to be array, null given in dosomething_fact_devel_create_facts() (line 80 of /vagrant/modules/dosomething/dosomething_fact/dosomething_fact_devel/dosomething_fact_devel.module).
Notice: Undefined index: fact in dosomething_fact_devel_create_facts() (line 81 of /vagrant/modules/dosomething/dosomething_fact/dosomething_fact_devel/dosomething_fact_devel.module).

**Comment by aaronschachter** [comment]
@DeeZone you need to use "Fixes #[ISSUE NUMBER]"  in order to automatically close issues.  Using 
Fixes Issue #[ISSUE NUMBER]" will not auto close becuase of the word "Issue" in between Fixes and the #
