### ISSUE TITLE
getting weird "blank" result in search - no image, title, or description

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3510]
search query was "27 things can do stop global warming"

![image](https://cloud.githubusercontent.com/assets/6330971/5136718/1041cb7c-70fb-11e4-9091-1b3e6aca4228.png)

**Comment by blisteringherb** [comment]
@mikefantini Have you seen this issue recently?  I think we might be able to close this one.

**Comment by mikefantini** [comment]
yeah seems to be resolved. closing out.
