### ISSUE TITLE
log of search queries for 404 page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3511]
not critical for the Killing Legacy milestone, but we should have a log of search queries we are running through the 404 page so that we can improve and optimize the terms we exclude on https://beta.dosomething.org/admin/config/dosomething/dosomething_notfound

**Comment by aaronschachter** [comment]
This sounds like a good use for Stathat, instead of building our own table (and needing to also build out a UI). And a good way to work on the Stathat module we released and never use (www.drupal.org/project/stathat)
