### ISSUE TITLE
need the ability to add reportbacks without associating them to a real user/First Name

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3514]
We're having a hard time knowing which user to associate past reportbacks to using https://beta.dosomething.org/admin/users/reportbacks/add.

This makes it hard to add reportbacks for old campaigns we are putting in the closed state.

And we can't just use one fake user because First Name is required and First Name gets displayed on the closed state.

cc: @lkpttn

**Comment by aaronschachter** [comment]
I've gamed the system and created a fake user without a First Name that all of these reportbacks should be associated with.  The first name will not be displayed.  The username is `DS Doer`.

**Comment by aaronschachter** [comment]
Campaign gallery is updating with the user uploading the reportback.
