### ISSUE TITLE
Reportback Caption character count

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3527]
Determine character count, and then set up client-side validation to validate it.

Related to #3484 - SMS Reportbacks too

**Comment by joolaay** [comment]
@lkpttn Do you remember the count in the mocks? I can't recall if it was 20, 25, or 40.

**Comment by joolaay** [comment]
@weerd let's go with 20 (but here's the hitch, we're using proxima nova rather than 'covered by your grace'

**Comment by weerd** [comment]
So 20 characters isn't very much... it's like 3 or 4 words.

**Comment by lkpttn** [comment]
Me and Keri had a discussion about this yesterday, the leading thought right now is 60 characters.

**Comment by weerd** [comment]
*Keri and I...

**Comment by mikefantini** [comment]
yeah so character limit is 60 and we should have client side validation on this

**Comment by mikefantini** [comment]
The help text on the caption field (per the mocks) should read "Write something in 60 characters or less" and the error message should read "Please keep your caption to 60 characters or less"

**Comment by weerd** [comment]
Not sure if we need _Please keep your caption to 60 characters or less_ language. We're using a maxlength attribute on the input keep it from exceeding the 60 characters. So user can't physically enter more than the 60 allowed.

**Comment by lkpttn** [comment]
If we cannnnnn though, we should be up-front about the limit so people don't encounter it and are unpleasantly surprised. Maybe a twitter style thing?

![screen shot 2015-02-06 at 3 26 41 pm](https://cloud.githubusercontent.com/assets/1865372/6087050/c9e5d9b4-ae14-11e4-8882-bb626f42bdd2.png)

**Comment by weerd** [comment]
Since this issue is attached to the 2.0 Milestone and @lkpttn suggestion above is more of a UX update, I am going to close this issue, but we can reopen another more specific to addressing that concern.

We do have language regarding the max count as the placeholder text in the field:

![image](https://cloud.githubusercontent.com/assets/105849/6087095/4b52d614-ae15-11e4-88a7-e49c75e4fc1a.png)
