### ISSUE TITLE
Uninstall and remove deprecated SMS Reportback modules

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3529]
Once all SMS Reportback functionality has been moved out of Drupal, cleanup time.
- [x] `conductor`
- [x] `conductor_sms`
- [x] `dosomething_sms`

**Comment by aaronschachter** [comment]
Spoke with @jonuy -- we should be no longer sending SMS Reportback requests to the endpoints defined by the `dosomething_sms` module.

I'm going to disable all of the endpoints defined by DoSomething SMS via the admin configuration page, and we'll monitor to see if we're in a good spot to begin disabling, uninstalling, and removing these modules from the codebase.

**Comment by aaronschachter** [comment]
This issue is ready for dev!

**Comment by sergiitk** [comment]
All modules are disabled and uninstalled on the international production.

**Comment by aaronschachter** [comment]
Can we run this on US too?

**Comment by sergiitk** [comment]
Affirmative!

**Comment by sergiitk** [comment]
Done.
