### ISSUE TITLE
Reportback Permalink page (bender)

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3540]
A page which displays a User's Reportback Image and Caption, and includes a Signup form / modal for its associated Campaign.  Also being referred to as a sharecard within the biz.
- [ ] Menu and page callback
- [ ] Determine path. e.g. `dosomething.org/rb/234`

**Comment by aaronschachter** [comment]
@mikefantini @julielorch I'd suggest that if a Reportback File has been flagged, the permalink view of it will result in a Page Not Found. thoughts?

**Comment by mikefantini** [comment]
@aaronschachter definitely makes sense to me for first implementation

**Comment by mikefantini** [comment]
per meeting with @angaither and @aaronschachter we decided URL structure should be /rb/[rbid]#[fid] - this will set us up for a future where we want the permalink to host all images of a reportback and allow the user to either carousel through or use thumbnails to see different images
