### ISSUE TITLE
add paragraph spacing below bulleted list

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3542]
![image](https://cloud.githubusercontent.com/assets/6330971/5185164/11717ba8-748b-11e4-8dc7-76a5f63d6e6f.png)

example: https://beta.dosomething.org/volunteer/animals

**Comment by aaronschachter** [comment]
FYI This copy is set on https://beta.dosomething.org/admin/config/dosomething/dosomething_settings. May be a good idea to update the settings on Staging site to make it easier for devs to reproduce @mikefantini

**Comment by mikefantini** [comment]
cool done
