### ISSUE TITLE
Change DS Canada log in modal header

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3545]
In the log in modal, change the header from "Log in to get started!" to "Log in to your DoSomething or TakingITGlobal account to get started!".

![image](https://cloud.githubusercontent.com/assets/692762/5188351/3fb643b0-74a2-11e4-8b78-33a205c35c23.png)

to 

![image](https://cloud.githubusercontent.com/assets/692762/5188354/436c88f2-74a2-11e4-9607-341bb98ace89.png)

**Comment by barryclark** [comment]
Unable to change this as we don't have the option of using translate on Canada. See comments at #3183  about enabling String Overrides. cc @aaronschachter @sergii-tkachenko @blisteringherb

**Comment by aaronschachter** [comment]
Upon deployment of #3553, this string can be overridden at `admin/config/regional/stringoverrides` by an administrator.

**Comment by aaronschachter** [comment]
Keeping open until we actually set the string.

**Comment by aaronschachter** [comment]
Currently blocked because Canada settings.php don't use the repository settings, and need the hardcoded override removed:  https://github.com/DoSomething/dosomething/commit/e6907cfe67b3a65903c4b6c92883d5c8b75d0e64

**Comment by aaronschachter** [comment]
@blisteringherb manually changed the Canada `settings.php` to get the Overrides working on Canda prod after I entered them.
