### ISSUE TITLE
Rollback International Affilates Databases

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#3546]
Production DBs of all international affiliates has been defected by the script that cleaned up US users (See #3339 and #3095). It removed nodes created by users that lost administrator privileges and got removed by the script.
#### Rollback plan
- [x] Back up the current state of international sites
- [x] Stop the cron job for the restore script on QA
- [x] Upload last known good DB dump to Production
  - [x] Botswana
  - [x] Canada
  - [x] Congo
  - [x] Ghana
  - [x] Kenya
  - [x] Indonesia
  - [x] Nigeria
  - [x] UK
- [x] Restore from the last known good point (Thursday, Nov 20)
  - [x] Botswana
  - [x] Canada
  - [x] Congo
  - [x] Ghana
  - [x] Kenya
  - [x] Indonesia
  - [x] Nigeria
  - [x] UK
- [x] Verify with affiliates that this looks usable again to them
- [x] Continue running the restore script on QA

**Comment by sergiitk** [comment]
CC @mshmsh5000 @barryclark

**Comment by sergiitk** [comment]
Botswana DB has been restored successfully from `2014-11-20-170001.botswana.sql.gz` in 30 minutes.

**Comment by sergiitk** [comment]
Canada DB has been restored successfully from `2014-11-20-174200.canada.sql.gz` in 25 minutes.

**Comment by sergiitk** [comment]
Congo DB has been restored successfully from `2014-11-20-183117.congo.sql.gz` in 20 minutes.

**Comment by sergiitk** [comment]
Ghana DB has been restored successfully from `2014-11-20-183408.ghana.sql.gz` in 15 minutes.

**Comment by sergiitk** [comment]
Kenya DB has been restored successfully from `2014-11-20-183543.kenya.sql.gz` in 20 minutes.

**Comment by sergiitk** [comment]
Nigeria DB has been restored successfully from `2014-11-20-184542.nigeria.sql.gz` in 40 minutes.

**Comment by sergiitk** [comment]
Indonesia DB has been restored successfully from `2014-11-20-183731.indonesia.sql.gz` in 30 minutes.

**Comment by sergiitk** [comment]
UK DB has been restored successfully from `2014-11-20-185511.uk.sql.gz` in 30 minutes.

**Comment by aaronschachter** [comment]
@sergii-tkachenko Good to close this?

**Comment by sergiitk** [comment]
@aaronschachter Positive.
