### ISSUE TITLE
Alignment of tri-gallery to grid

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3547]
We should align the tri-gallery to the outside containers with first and last column padding tweaks.

Part of a larger front-end refresh with typography? cc: @DFurnes @sbsmith86 

![screen_shot_2014-11-25_at_2_02_50_pm](https://cloud.githubusercontent.com/assets/1865372/5189475/2ae9ea9a-74ac-11e4-9eed-85b8193af662.png)

**Comment by DFurnes** [comment]
Sounds good. Let's aggregate these under the Neue repo when there's time.

**Comment by lkpttn** [comment]
This has been fixed in Neue 6!
