### ISSUE TITLE
Expand Canada Redirect for Teens for Jeans from Domain to US Campaign Page

### ISSUE THREAD

**Issue by mfurdyk** [DoSomethingArchive/legacy-website#3557]
Hi @mshmsh5000 & @barryclark. This is my first new issue post so please confirm that I should be assigning new requests to Barry for gatekeeping?

Right now www.teensforjeans.com redirects Canadians to our campaign page. That works great! However, other than the promo banners, most people will likely just google "Teens for Jeans". Even in Canada, the US site comes up first (actually the Canadian campaign ins't even on page 1). To avoid confusion and to ensure Canadians come to the Canadian site, I have two requests:

1) Can you setup the US and Canadian campaigns to do the same Geolocation to redirect to each other (ideal), or implement the banner we had last year saying something like "You're on the US Campaign page. Click here to go to the Canadian campaign!"

2) We should be able to tell Google to prioritize "canada.dosomething.org" as Canadian-focused content through Webmaster Tools. Could you please add this to the <head> tag, or give me edit on the Analytics property, so we can connect with Webmaster Tools?

<meta name="google-site-verification" content="UvfwZlh42rNaUM6JGODutqxDCzOAWTqEJOVHtQtyjw8" />

Thanks & Happy Thanksgiving :)

Mike

**Comment by barryclark** [comment]
Hi @mfurdyk!

Yep. Assigning me on issues to triage is great.

1) Assigning this issue to @mshmsh5000 so that he can take a look at that.

2) I've given you admin on DS Canada Google Analytics. Let me know if there's anything else you need to be able to connect with Webmaster Tools.

**Comment by mfurdyk** [comment]
Thanks. Unfortunately Google's saying the tag is in the wrong place to use GA to verify site ownership:

Verification failed for http://canada.dosomething.org/ using the Google Analytics method (less than a minute ago). The Google Analytics tracking code on your site is in the wrong location. You can verify site ownership with the asynchronous snippet placed in the <head> section of your home page. Learn more.

OPEN TAG meta name="google-site-verification" content="UvfwZlh42rNaUM6JGODutqxDCzOAWTqEJOVHtQtyjw8" / CLOSE TAG

Is adding the head tag or uploading a file possible? Sorry for the hassle.

**Comment by barryclark** [comment]
@mfurdyk Uploading a file would be easiest. You can upload a file at https://canada.dosomething.org/admin/content/file then select it and use Update Options to set it's status as permanent.

**Comment by mshmsh5000** [comment]
@mfurdyk We don't have geolocation headers going to the US or Canada DS.org sites. teensforjeans.com is a separate app with Varnish providing geo info.

We're running a pilot integration with Fastly, which is the CDN we'd like to use to deliver HTML content for all the DS.org sites. Fastly can provide the geo headers we'd want.

We never considered the cross-affiliate header that we included last year. We don't have any way to add that at the moment.

In January, we are going into serious planning mode for version 2 of this platform. The core challenge is to internationalize the DS.org experience across all sites. We keep running into issues like this (viz., running a campaign across two sites) that challenge us to find a better way.

We'll definitely be looking to you for ideas and feedback!

**Comment by mfurdyk** [comment]
@barryclark Thanks, but Google WT requires the file to be in the root directory. Is it possible to serve a file there temporarily and then remove it?

@mshmsh5000 Okay, sounds good. Is there any interim suggestion you have for telling people about the Canadian site at some point in the process where they might be registering on DS.org or looking for their school and not finding it (perhaps beside the state dropdown?)

**Comment by mshmsh5000** [comment]
@mfurdyk Let us know the file name + contents (I can't remember if these have content), and we'll take care of it.

**Comment by mshmsh5000** [comment]
Re: interim solution, I will ask @mikefantini and @barryclark and @DFurnes and @aaronschachter collectively to mull this over. We'll share any ideas we come up with next week, after the Thanksgiving break.

**Comment by mfurdyk** [comment]
@mshmsh5000 Thanks!

File name: googlecd6495b67dd3d918.html
File contents: google-site-verification: googlecd6495b67dd3d918.html

Happy Turkey/Tofurky :tada:

**Comment by mikefantini** [comment]
@mshmsh5000 the easiest solution is to add help text to the school form. This would require no tech build (or a very small one if we wanted to add markdown so we could link out).

**Comment by mshmsh5000** [comment]
@mfurdyk Apologies for the delay: https://canada.dosomething.org/googlecd6495b67dd3d918.html

@mikefantini That sounds like a great idea. Being able to link out would be obv great if possible -- let's talk about level of effort.

**Comment by barryclark** [comment]
Attaching a preview of a quick content change I could make on US/Canada sites. Does that work for you @mfurdyk @mshmsh5000? cc @DFurnes @aaronschachter 

![image](https://cloud.githubusercontent.com/assets/692762/5303926/cc7c7506-7bbb-11e4-95f6-db5f02850445.png)

Another option could be putting that message within the "Need help locating your school?" dropdown:

![image](https://cloud.githubusercontent.com/assets/692762/5303937/f535475c-7bbb-11e4-9588-30aec2b5e118.png)

**Comment by mfurdyk** [comment]
I think that's great in the interim - thanks @barryclark. Better to make it more prominent as a short-term fix.

Look forward to a deeper future solution (enabled by your move to a new caching platform?) that just redirects them first so they won't have to double-register... Assuming they will in this scenario right? Does a DSUSA login work on the Canadian site? (I think no as they are separate installs?)

Should we perhaps do an onclick alert to let them know they will have to re-register to avoid any confusion? "We're taking you to Do Something Canada to participate in the Canadian Teens for Jeans campaign! Because of privacy laws our databases are separate, so you'll have to sign up quickly again."

Mike

**Comment by barryclark** [comment]
> Look forward to a deeper future solution (enabled by your move to a new caching platform?)

I think so, @mshmsh5000? :)

> that just redirects them first so they won't have to double-register... Assuming they will in this scenario right?

Yea, they'll have to double-register in this scenario.

> Does a DSUSA login work on the Canadian site? (I think no as they are separate installs?)

No is the correct answer, as they're separate DBs like you mentioned.

> Should we perhaps do an onclick alert to let them know they will have to re-register to avoid any confusion? "We're taking you to Do Something Canada to participate in the Canadian Teens for Jeans campaign! Because of privacy laws our databases are separate, so you'll have to sign up quickly again."

That'd be difficult. As for this solution I'm just editing content quickly in the CMS. Maybe I could make the message more clear though? Like this... 

![image](https://cloud.githubusercontent.com/assets/692762/5304165/1b0e3af4-7bbe-11e4-9275-12c855a474b6.png)

Thoughts @DFurnes @mshmsh5000 @mfurdyk?

**Comment by mfurdyk** [comment]
OK, I think that text is a little clearer and makes sense. Thanks for the quick edit! @barryclark

**Comment by DFurnes** [comment]
@barryclark Looks great to me!

**Comment by barryclark** [comment]
Just updated the content on production on the US and Canada sites. Tested and looks good. :beers:
