### ISSUE TITLE
pull in link to user profile and uid into Zendesk

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3565]
When a user submits a a help ticket, the link to the user's profile and the user's uid should be easily accessible on the zendesk ticket.

**Comment by aaronschachter** [comment]
This one is good to go whenever you're ready for it, @deadlybutter.  It will require creating a field or two within the Zendesk admin, so let me know when you're ready to start working on it, and I can work with you on creating the field.

The `dosomething_zendesk_verify_zendesk_user` function will need to update existing ZD Users with the profile link / uid, and `dosomething_zendesk_create_zendesk_user` will need to set the custom fields upon creating new ZD Users.
