### ISSUE TITLE
add beta name fields for SMS game A/B test

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3568]
# Tasks
- [x] Create and output a second SMS Game Signup Form with extra input values for names, which is hidden on the page. ideally using same form constructor with parameter set to include names?
- [x] Second SMS Game Signup Form needs to add additional beta names to submitted MobileCommons request

The Optimizely test can hide the regular Form and unhide the hidden Form to A/B it up.
# Overview

we want to run an A/B test where we ask alphas for the first name of their beta friends

we would need to pass this first name along to mobile commons to be associated with the beta

[mobile mocks](https://s3.amazonaws.com/uploads.hipchat.com/34218/350105/42fQwILikUk4mG0/Mobile%20SMS.png)
[desktop mocks](https://s3.amazonaws.com/uploads.hipchat.com/34218/350105/kg5HrkAu4cMln8t/SMS%20Game.png) -> "First Name" should be the placeholder text in the alpha's first name field.

cc: @jonuy @Bladt @weerd

**Comment by aaronschachter** [comment]
@jonuy @tongxiang What are the parameters to use for the beta names in the Mobile Commons POST ?

**Comment by jonuy** [comment]
@aaronschachter we don't have anything setup in our app to receive the names, so we can flexible. What seems would match closely with params we're taking right now are: beta_first_name_0, beta_first_name_1, and beta_first_name_2 :neutral_face:

**Comment by DFurnes** [comment]
@jonuy @Bladt See PR #4247 for details on Optimizely script.
