### ISSUE TITLE
fender work for adding beta first name fields to SMS games for A/B test

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3569]
need fending on #3568 

[mobile mocks](https://s3.amazonaws.com/uploads.hipchat.com/34218/350105/42fQwILikUk4mG0/Mobile%20SMS.png)
[desktop mocks](https://s3.amazonaws.com/uploads.hipchat.com/34218/350105/kg5HrkAu4cMln8t/SMS%20Game.png) -> "First Name" should be the placeholder text in the alpha's first name field.

cc: @aaronschachter @jonuy @Bladt

**Comment by DFurnes** [comment]
This was done in #4710.
