### ISSUE TITLE
Geolocation for Patients Playbook (for Dec 12th)

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3579]
Similarly to Teens For Jeans, we're running an iteration of Patient's Playbook with Canada. 
- [x] Glamo(u)r URL
- [ ] _Fastly configuration_ -- not needed; used Varnish / MaxMind instead
- [x] Geo-based redirect

**Comment by barryclark** [comment]
Glamour URL = www.ryansplaybooks.com purchased by Gleb. 

URL to redirect to will be www.dosomething.org/campaigns/ryans-playbooks

**Comment by mshmsh5000** [comment]
@gboundin Can you please point this domain to the same IP as teensforjeans.com (209.61.132.44), and update here when it's ready? Thanks.

**Comment by mshmsh5000** [comment]
This is all set for [ryansplaybooks.com](http://ryansplaybooks.com).

@gboundin Looks as though we still need a record for www.ryansplaybooks.com though.

**Comment by mshmsh5000** [comment]
OK, [www](http://www.ryansplaybooks.com) is up and running too.

**Comment by barryclark** [comment]
:beers: @mshmsh5000
