### ISSUE TITLE
Images on the recommended campaigns block on 404 page and no search results aren't clickable

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3580]
These should click through to the appropriate campaign:

![image](https://cloud.githubusercontent.com/assets/6330971/5270786/472ce172-7a3c-11e4-8af3-c636861dad34.png)

![image](https://cloud.githubusercontent.com/assets/6330971/5270797/69b28602-7a3c-11e4-9491-45604d520f0d.png)

**Comment by aaronschachter** [comment]
This is sitewide.  Mocks need to start detailing what is clickable and what is not.

**Comment by sbsmith86** [comment]
@aaronschachter brought up this question in #3586 . Should the whole block be a link or just the image? @mikefantini

**Comment by mikefantini** [comment]
answered on #3586
