### ISSUE TITLE
don't display campaigns on taxonomy collections if status=closed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3583]
so puppy text would not appear on https://www.dosomething.org/volunteer/animals for example:

![image](https://cloud.githubusercontent.com/assets/6330971/5272950/050d50a6-7a50-11e4-9e35-b4374da97eaa.png)

**Comment by aaronschachter** [comment]
The ideal would be that closed campaigns show up last right, vs. not at all?

**Comment by mikefantini** [comment]
@aaronschachter yup

**Comment by aaronschachter** [comment]
Modified the view such that Closed campaigns will still appear, but last in the list.
