### ISSUE TITLE
Reportback Cropping: Do not let users crop an image too small

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#3590]
Need to figure out a minimum size for the cropping area and restrict users from cropping images that are too small.

**Comment by barryclark** [comment]
minimum 480x480

**Comment by sbsmith86** [comment]
@barryclark I just pushed an update that will not allow an image to be cropped smaller than 480x480. I think that resolves this ticket. Just want to make sure, this is separate from letting a user upload a file smaller than 480x480, right?

**Comment by barryclark** [comment]
@sbsmith86 That resolves this issue :fireworks: Woot!
