### ISSUE TITLE
404 Search results repeating words

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3594]
For @deadlybutter:

If a url is something like dosomething.org/facts/facts-about-nothing it will pull "facts" out twice for the search. Preferably would limit it to just one of each unique word.

![screen shot 2014-12-05 at 11 40 56 am](https://cloud.githubusercontent.com/assets/1865372/5319076/d28203ae-7c73-11e4-80be-59bf1b59e70a.png)

**Comment by aaronschachter** [comment]
Fixed this by adding "facts" to the Search Filters words on https://www.dosomething.org/admin/config/dosomething/dosomething_notfound.  Will update the Editors Guide to document.

**Comment by itsjoekent** [comment]
@aaronschachter  hm.. is that the best way to fix this though? Wouldn't facts dogs return a better result than just dogs?

**Comment by aaronschachter** [comment]
Good point.  Maybe we filter duplicate words.
