### ISSUE TITLE
Reportback Cropping: Save original file

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3615]
Save original file in `fid`, and the cropped file in `fid_processed`.  The x,y,width,and height coordinates used by the crop widget should be saved as a serialized array within `options_processed`.

**Comment by mikefantini** [comment]
will reopen if it becomes a concern for marketing

**Comment by aaronschachter** [comment]
There is some cleanup to do here potentially, as if we don't need this we no longer need for the `fid_processed` and `options` columns in the `dosomethinn_reportback_file` table.

**Comment by mikefantini** [comment]
@aaronschachter if you want to create an issue for that go for it. I think we should operate under the assumption that we won't be building this, but again, if it turns out marketing does in fact need it, then we'll roll it out.
