### ISSUE TITLE
DS script: Rebuild permissions

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#362]
Upon doing a fresh build --install, it prompts me to rebuild permissions.  I believe this because of enabling the view_unpublished module.

We can update the install script to execute `drush php-eval 'node_access_rebuild();'` as a last step -- as per https://drupal.org/comment/2978658#comment-2978658

@desmondmorris - thoughts?

**Comment by desmondmorris** [comment]
@aaronschachter this seems okay to me.
