### ISSUE TITLE
video tiles on homepage

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3627]
The goal is to have video tiles play on the homepage, with the caveat that we never want two tiles playing videos at once.

Easiest implementation to start is probably just to play a video on the featured tile if one exists. I assume we would want the video to live on the campaign cover image's node like we do for 404 pages.

Ideally though any of the tiles could play a video. So the _first_ tile that had a campaign with a video on the cover image node would play a video. I.e. if campaign 1 doesn't, check campaign 2. If campaign 2 doesn't, check campaign 3, etc. and if campaign 3 does, then stop checking and video would play on campaign 3.

**Comment by barryclark** [comment]
@mikefantini This is something that @DFurnes will be picking on the first sprint of the new year.

**Comment by mshmsh5000** [comment]
@DFurnes is a legend

**Comment by DFurnes** [comment]
:japanese_ogre:

**Comment by DFurnes** [comment]
Closed by #3826! :movie_camera:
