### ISSUE TITLE
Rotate orientation on image upload

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3630]
When uploading from a mobile device often the image can look like it's rotated to the correct orientation initially, but when you view the preview in the reportback form, it's upside down or sideways.

**Comment by barryclark** [comment]
Could do with steps to be able to 100% replicate this.

**Comment by barryclark** [comment]
Still not seen this reoccurring yet.

**Comment by mikefantini** [comment]
@sbsmith86 @barryclark we can close this one out because we of the rotation feature correct?

**Comment by sbsmith86** [comment]
@mikefantini @barryclark Yea!
