### ISSUE TITLE
Password reset not working on DS Canada site

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3632]
I just tried to password reset on the DoSomething Canada site and didn't receive any email. 

cc @DeeZone @blisteringherb @sergii-tkachenko @aaronschachter @mshmsh5000 

Not entirely sure who owns this one... some conversation from an email thread:

Sergii: As I understand, my task with forgot password functionality is not related at all with sending emails. Now it should works in default mode, I’m only working on syncing it to remote SSO server.

Dee: The password reset functionality on the affiliate sites is all going through the stock Drupal core functionality. The Message Broker system is currently _not_ involved. In terms of diagnosing the the issue on the DS affiliate CA site, I can review the steps Morgan took to diagnose the issue. At launch the affiliate sites had an issue with sending email messages that I think was resolved by adding SPF records to the DNS server. For starters, can I have the email addresses of the two Canadian affiliate users that's not getting their reset email messages.

Dee: Looking at the mail.log entries in what I think is the production international server:

`10.241.0.36     deploy.international.dosomething.org int.prod
$ ssh int.prod`

`/var/log/mail.log`

I can't find log entries with "USER EMAIL REMOVED" or any part of the address. In fact  there appears that the "to" value in the existing entries only have "dosomething.org" addresses. I'm going to hand this off to Morgan / Matt as I'm now at the end of my DevOps skills on this subject.

**Comment by sergiitk** [comment]
Resolved by International Message Broker release.
