### ISSUE TITLE
outstanding redirects needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3647]
for some reason the following redirects didn't get created

https://docs.google.com/a/dosomething.org/spreadsheets/d/1xrpAdq1JOqGZDptgq_TAP47cpVwXIWUaMxeSCNYWIII/edit#gid=1821480830

can we follow the same process with the previous redirects? i.e. use the legacy URL alias and redirect to the beta canonical

**Comment by mshmsh5000** [comment]
Script is done and updated; will wait until a non-Friday to run.

**Comment by mshmsh5000** [comment]
Record of the redirects that were created: https://gist.github.com/mshmsh5000/bb6c30a0295854328bb5
