### ISSUE TITLE
Vagrant: SimpleTest execution timeout

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#365]
Adding more tests into the dosomething_signup.test file and no likey:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=10&op=do StatusText: OK ResponseText: Fatal error: Maximum execution time of 30 seconds exceeded in /vagrant/html/includes/registry.inc on line 132

or 

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=12&op=do StatusText: OK ResponseText: Fatal error: Maximum execution time of 30 seconds exceeded in /vagrant/html/profiles/dosomething/modules/contrib/ctools/includes/utility.inc on line 23

Per suggestion in https://drupal.org/comment/6017026#comment-6017026, we can set the max_execution_time in php.ini to a higher value.

**Comment by desmondmorris** [comment]
Should be an easy update to the php.ini file.
https://github.com/DoSomething/dosomething/blob/dev/salt/roots/salt/php5/cli/php.ini

Should be able to test locally by editing /etc/php5/cli/php.ini and restarting apache

**Comment by aaronschachter** [comment]
Anybody have thoughts for what the value should be increased to?  Do we need different values for diff environments?
