### ISSUE TITLE
User Profile "Prove it" button alignment

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3662]
Min height?

![screen shot 2014-12-18 at 7 21 20 pm](https://cloud.githubusercontent.com/assets/1236811/5498308/3410eadc-86eb-11e4-8c73-329677c3a6b0.png)

**Comment by aaronschachter** [comment]
cc @lkpttn

**Comment by lkpttn** [comment]
If possible, align all as if they had two lines of text. Most campaigns with actual CTAs will span two lines, like on /explore.

![fixedheight](https://cloud.githubusercontent.com/assets/1865372/5506069/9b4b4408-8764-11e4-8c4e-e36020d971d0.png)

**Comment by mikefantini** [comment]
@lkpttn should we have more padding between 2 line call to action and the prove it button? but yes agreed that it should be aligned to worst case scenario

**Comment by lkpttn** [comment]
Yeah, that'll be governed by the new neue padding rules.

**Comment by aaronschachter** [comment]
Potential issues with Campaign titles too.

![screen shot 2014-12-22 at 11 51 51 am](https://cloud.githubusercontent.com/assets/1236811/5527951/06a8f1d2-89d1-11e4-8a98-4c8cc5918c51.png)

**Comment by mikefantini** [comment]
I assume here we also want to align as if all have 2 lines of text as well. you agree @lkpttn?

**Comment by itsjoekent** [comment]
Is this only for user profiles or should all figures be spaced this way?

**Comment by barryclark** [comment]
cc @weerd @DFurnes

**Comment by weerd** [comment]
Hmmm, not sure. Where else do these occur? Static pages?

**Comment by weerd** [comment]
we need a height specification for both the titles and the descriptions. 2 line for each... Maybe use an em height on their respective containers, `p { height: 2em; }` ? @DFurnes ?

**Comment by DFurnes** [comment]
I'm not super keen on hard-coding a description height, since it'd easily bork if we had more/less content than in those cases. Not sure what a better solution is though.

**Comment by itsjoekent** [comment]
Possible idea...? Can the buttons be on there own row and spaced the same? @DFurnes @weerd

**Comment by itsjoekent** [comment]
Reopening: 

[2:39 PM] Luke Patton: @Joe Can we re-open that? That 2em between title and description is too tall
