### ISSUE TITLE
Theme Gallery placeholders

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3664]
**UPDATE**

~~Blocked by #3694~~

This issue is to theme the placeholder images stored in #3694  if not enough approved images exist.

**ORIGINAL Description**

@mikefantini we are blocked on this. what is the decision?

My vote is that a campaign cannot be published without an editor uploading 6 placeholder reportback images (to inform the user of what we're expecting), which others seemed to be in agreement with during Innovation Mtg around this.

We could potentially add these images with a `'placeholder` status.  The gallery could not populate with "real" images until it has at least 6 approved (to avoid complicating the gallery logic of "I have 2 approved so display 4 placeholders").  Hoping to ship simplest solution first and then we can always refine later.

**Comment by aaronschachter** [comment]
@weerd This issue is unblocked -- use the `dosomething_campaign_get_default_gallery_image_urls` function will return the image URL's of Default placeholder image

**Comment by mikefantini** [comment]
@weerd once you have this wrapped up let's grab @kerigoff so she can review the placeholder images (uploaded to staging) so she can make any adjustments to the photos selected.
