### ISSUE TITLE
Make campaign run notification message editable

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3682]
Allow admins to edit the copy for the onscreen notification message after a user signs up to be notified for when a closed campaign re-opens. Field should be added to the campaign run section of https://beta.dosomething.org/admin/config/dosomething/dosomething_campaign

Currently the copy is "Sweet, we'll send you an email as soon as [campaign_title] re-opens. In the meantime, find a [campaign](/campaigns) you can do right now."

**Comment by mikefantini** [comment]
@aaronschachter SPG and Alyssa are trying to get this over to Coke on Friday, think we'd be able to get this in and deployed by then?

**Comment by aaronschachter** [comment]
@mikefantini Does this need to support the Title token and/or link to Campaigns?  And to confirm: This message will be for all closed campaigns' pre-signup forms?

**Comment by mikefantini** [comment]
@aaronschachter yes this would apply to all closed campaigns. and yes would want it to continue to function as it does currently with the campaign title token and link to /campaigns.

like we talked about in person, seems easier to just hard code the change so we'll go with this language (confirmed with SPG):

Sweet, we'll send you an email as soon as [campaign_title] opens. In the meantime, find a [campaign](/campaigns) you can do right now.

**Comment by aaronschachter** [comment]
Oh, the only change here is "re-opens" to "opens" ?
