### ISSUE TITLE
Campaign: Double field -- text formats

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#369]
The double field module we are using to provide campaign steps & FAQs doesn't support text formats. 
We either need to write a patch (and update DB schema) or switch to field collection module.

https://drupal.org/node/1891664

**Comment by aaronschachter** [comment]
The same user who opened that issue also created another issue 9 months later with some proposed patches https://drupal.org/node/2091587.  

I also see a workaround / hack in another issue, https://drupal.org/node/1787454, using hook_form_alter to add the text format stuff into the form.

**Comment by aaronschachter** [comment]
Per the workaround, i attempted this into `dosomething_campaign_form_campaign_node_form_alter()`

```
  $form['field_step_pre'][LANGUAGE_NONE][0]['second']['#type'] = 'text_format';
  $form['field_step_pre'][LANGUAGE_NONE][0]['second']['#base_type'] = 'textarea';
  $form['field_step_pre'][LANGUAGE_NONE][0]['second']['#format'] = 'markdown';
```

The trouble with this approach (so far) is that once you "add more", the form_alter is not called on that 2nd form field widget.

**Comment by aaronschachter** [comment]
Maybe using `#after_build` could fix this, where we loop through all of the field values in an `after_build` callback function. http://www.appnovation.com/blog/drupal-tip-using-formafter-build

Not super scalable though.
