### ISSUE TITLE
Reportback Upload IE Support

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#3699]
Hey there, @mikefantini @barryclark @weerd @DFurnes !

IE8 and 9 don't support the code we are using to allow a user to upload an image and see a preview of the image before we send it to the backend. Without being able to see the preview image there is no way for us to support the cropping functionality. 

So we were discussing ways to change or support the image upload flow for IE users who can not crop images. 

The options thrown out were: 
- We could not pop open the modal, but somehow indicate to the user that file has been uploaded (by showing the filename, for example). Then we would do some sort of auto crop ( I think this is the best option.)
  - We could try to find a polyfill that would allow us to give broswers that don't have it, the support we need to implement cropping. This may or may not be feasible. 
  - Not supporting reportback on IE 8 or 9 all together. 

So I think we just need to settle on a solution and make sure everyone is on the same page.

**Comment by DFurnes** [comment]
My vote is for option A. The flow is preserved (users can still upload a photo and report back), but we progressively enhance that experience for users on modern browsers.

**Comment by barryclark** [comment]
Diego's going to pick this one up @sbsmith86, he'll give you a shout for a chat about.

**Comment by barryclark** [comment]
The caption field needs to be shown in the form now too, as it's currently in the modal which won't exist in IE8/9.

**Comment by weerd** [comment]
Tasks for IE8 Support:
- [x] Style the upload button with fallbacks for IE8. 
- [x] Re-show the caption field in IE8, otherwise you can’t submit the pic.
- [x] Show the file name in IE8/9 to designate to user that a file was properly selected.
