### ISSUE TITLE
Upload Gallery placeholder images

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3702]
Refs #3664
- [x] [Upload](https://github.com/DoSomething/dosomething/wiki/Site-Guide#uploading-files) the Gallery placeholder images to staging and production.  Be sure to remember to set the file as permanent, and also keep track of each File fid you are adding.
- [x] Set the Gallery Defaults variable via `admin/config/dosomething/dosomething_campaign`.

**Comment by mikefantini** [comment]
@kerigoff uploaded these to staging. once we review how they look in the slots we'll add them to prod

**Comment by mikefantini** [comment]
blocked on prod by #3664

**Comment by mikefantini** [comment]
this is now up on prod
