### ISSUE TITLE
DS install broken: Drush terminated due to New Relic PHP Library missing

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#3718]
`bin/ds build --install` and`bin/ds build --intl --install`  fails with the following error:

```
New Relic PHP Library missing. Check <a href="https://newrelic.com/docs/php/new-relic-for-php">Install New Relic for PHP</a> for more information. in install_verify_requirements() (line 768 of /var/www/vagrant/html/includes/install.core.inc).
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                                   
```

/CC: @DeeZone @aaronschachter

**Comment by aaronschachter** [comment]
Easy quickfix here could be to remove the New Relic module from the dosomething.info file, so we don't install it by default.

**Comment by sergiitk** [comment]
@aaronschachter  But why can't it find it? Isn't it in `drupal-org.make`?

**Comment by aaronschachter** [comment]
No, the make file is not adding the PHP Library: https://docs.newrelic.com/docs/agents/php-agent/getting-started/new-relic-php

@mshmsh5000 manually added it for production.

**Comment by sergiitk** [comment]
Ok, I will install this and include into salt-platform.

**Comment by aaronschachter** [comment]
@sergii-tkachenko Is this closed by https://github.com/DoSomething/salt-platform/pull/11 ?

**Comment by sergiitk** [comment]
@aaronschachter Yes, it's closed. Thank you!
