### ISSUE TITLE
Staff Gallery layout breaks for some rows

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3731]
http://staging.beta.dosomething.org/about/our-team

![screen shot 2015-01-14 at 2 19 12 pm](https://cloud.githubusercontent.com/assets/1236811/5745659/5ec4713c-9bf8-11e4-8d59-e3c7bd1c12e5.png)

**Comment by DFurnes** [comment]
Fixed in [Neue v6.0.0-beta2](https://github.com/DoSomething/neue/releases/tag/v6.0.0-beta2).
