### ISSUE TITLE
links in campaign footer should be white

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3760]
staging:
![image](https://cloud.githubusercontent.com/assets/6330971/5827532/1d050b14-a0c9-11e4-8d2a-16e06caf5d49.png)

prod:
![image](https://cloud.githubusercontent.com/assets/6330971/5827538/2c1834a0-a0c9-11e4-8478-14d00d92ea96.png)

**Comment by DFurnes** [comment]
This is related to the Reportback 2.0 styles.

**Comment by weerd** [comment]
This is fixed and will be applied in upcoming PR :hammer:
