### ISSUE TITLE
modal header not rendering properly on image manipulation modal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3762]
![image](https://cloud.githubusercontent.com/assets/6330971/5827608/ef434334-a0c9-11e4-8bb3-67adb72e70b7.png)

**Comment by DFurnes** [comment]
Cropping modal markup/styles have not been updated for Neue 6.0 yet. This will be fixed once @sbsmith86 has a chance to replace `banner` class with Neue 6.0's `heading -banner`.

**Comment by mikefantini** [comment]
related (but create a separate issue if you think that makes more sense @sbsmith86): on mobile, the modal pulls up the browser chrome for me, this causes the modal title to get cutoff. Not sure why browser chrome is being pulled up for this and not other modals (is it because we're accessing the camera?) but it makes the Edit Your Photo header difficult to read (which is important since it's not too intuitive that this is what's happening here).

![image](https://cloud.githubusercontent.com/assets/6330971/5828869/c9018e66-a0d7-11e4-9a58-365fd06b2083.png)

**Comment by sbsmith86** [comment]
@mikefantini @DFurnes This should be fixed in PR i submitted for image rotation.
