### ISSUE TITLE
Remove unused image styles in CMS.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#3775]
Within `CMS > Configuration > Media > Image Styles` there are lots of image styles no longer being used   and we should review the DS app and remove all unused ones to help make the list more manageable.

**Comment by aaronschachter** [comment]
This is a duplicate of https://github.com/DoSomething/dosomething/issues/3475. Feel free to close either to DRY

**Comment by weerd** [comment]
Oh shiza! Good catch. @aaronschachter you're like the official GH Issues police! :cop:
