### ISSUE TITLE
Canada: Sync pre-SSO registered users via API

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#3792]
Use list sent by Michael Furdyk. We will not try to sync their passwords across systems, but we'll still achieve the main goal: Sync email, so that TIG can contact them.

**Comment by sergiitk** [comment]
The task consist from the following:
- [x] Create `dosomething_canada` drush script that posts users to the [laravel-user-api](/DoSomething/laravel-user-api)
- [x] Convert the list to csv or json
- [x] Test the the drush script locally
- [x] Deploy the changes to production
- [x] Run the script
- [x] Send the results to @mfurdyk
- [x] Remove drush script from DS codebase

**Comment by sergiitk** [comment]
CC @mfurdyk
