### ISSUE TITLE
Fix spacing of triad gallery pics and descriptions

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3793]
Couple things here: There might be extra markup on the h2 at the top that's creating extra space between it and the gallery. Then there isn't enough space after the photo description before the next photo. Should probably be treated like a regular paragraph in terms of spacing?

cc @mikefantini 

![screen shot 2015-01-23 at 3 36 48 pm](https://cloud.githubusercontent.com/assets/1865372/5882269/dec7252c-a315-11e4-8668-20d6a0ccceee.png)

**Comment by lkpttn** [comment]
Adding another example, on the donate page.

![screen shot 2015-01-23 at 4 29 56 pm](https://cloud.githubusercontent.com/assets/1865372/5883090/356d25be-a31d-11e4-93e0-5d018dddfd0b.png)

**Comment by DFurnes** [comment]
Fixed in latest Neue release, and live on staging!
