### ISSUE TITLE
Possible form_cache memory sharing between affiliates

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#3800]
The first form created gets served on all affiliates. For example, reg form created on UK containing Last Name field also displayed on Canada.

So far confirmed only on vagrant.

**Comment by angaither** [comment]
@sergii-tkachenko is this still an issue? will it be once we merge the sites together?

**Comment by sergiitk** [comment]
Now we don't know, it's possible.
It will not be when the sites are together.

**Comment by angaither** [comment]
okay, going to close this out since we aren't doing anything but bug fixes for affiliate sites
