### ISSUE TITLE
updates to User Profile Edit form (/user/uid/edit)

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3805]
@deadlybutter after speaking with @aaronschachter it seems like these edits are a nice compromise in terms of updates we can make to the edit profile view (/user/uid/edit).

Sorry easiest way to make the edits was to just hack in browser so I took screen grabs of that, let me know if this rearrangement makes sense.

Zoomed out view:
![image](https://cloud.githubusercontent.com/assets/6330971/5911573/3925d8b6-a595-11e4-9464-cb162c6c2c42.png)

Regular zoom components:
![image](https://cloud.githubusercontent.com/assets/6330971/5911464/d61a9258-a593-11e4-9282-8e32be5b6e9e.png)
![image](https://cloud.githubusercontent.com/assets/6330971/5911470/eb0982c8-a593-11e4-9272-fa25eaf2a44d.png)
![image](https://cloud.githubusercontent.com/assets/6330971/5911483/0f30f30c-a594-11e4-87f1-b9e348333dea.png)

**Comment by mikefantini** [comment]
one thing to keep @deadlybutter in mind is that this _should not_ change the admin view of a user edit page (i.e. as an admin trying to edit a user role for one of our users)

cc: @aaronschachter

**Comment by itsjoekent** [comment]
EDIT: Never mind, talked to Aaron, /user/uid/edit is correct

**Comment by aaronschachter** [comment]
@deadlybutter Nope - we want to be working on the form found in . user/[uid]/edit. Info is for staff only

The user edit form is rendered in teh admin form when your'e logged in as admin, but for a regular authenticated user it will look like the mocks @mikefantini attached.

**Comment by aaronschachter** [comment]
The quickest way to ship this is to alter the form weights in the default form. The default User Profile Edit form groups email and password together into a form group, so splitting them apart is a no go. We either put mail and password at the beginning of the form, or at the end.

Also, I recommend we keep the help text that explains you need to enter your password if you want to change your email.  Screenshot coming in a PR
