### ISSUE TITLE
Prove It button placement should be independent of detail height

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3806]
On the user profile, we should have all the "Prove It" buttons be the same height. I think this is a bug right now, but it still seems to be dictated by number of lines.

![upload](https://cloud.githubusercontent.com/assets/1865372/5920667/48ba9cf4-a60c-11e4-92b2-9bb9fe8b6289.png)

cc: @DFurnes @mikefantini

**Comment by itsjoekent** [comment]
@mikefantini arent front-endy things fender ?

**Comment by mikefantini** [comment]
oh yeah duh. sorry updating.

**Comment by fender** [comment]
Github seemed to pick up my nickname and email me about this thread. What's interesting is that I am also a Drupal 7 developer. :laughing:

**Comment by barryclark** [comment]
Hah @fender! Welcome :smiley: 

Are those labels we're assigning hitting you with a lot of notifications? :grimacing: If so we could change them! We use "fender" as a shortened version of "front-ender".

**Comment by itsjoekent** [comment]
Sorry my fault, original comment accidentally had @fender in it!

**Comment by fender** [comment]
Haha, that would be why. Looks like the "fender" tag is good to use. It's actually my last name and to complicate things even more, I am about to release a [book](https://leanpub.com/front-end-fundamentals) on front-end development.

**Comment by barryclark** [comment]
Your book outline looks great @fender. Best of luck with the launch!
