### ISSUE TITLE
Fact Search: Link to fact page

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#382]
Each fact should link to the fact/[id] page.  Ideally also provide an edit link within the table too.

**Comment by angaither** [comment]
@aaronschachter what's the 'edit link' url for a fact?
fact/[id]/edit doesn't seem to work

**Comment by aaronschachter** [comment]
it's defined via the entity admin ui - i believe its something like admin/fact/[id]/manage
