### ISSUE TITLE
Fact Search: Format updated column

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#383]
Format to MM/DD/YYYY MM:HH

**Comment by angaither** [comment]
the field values 'created' and 'changed' are currently stored as 'int' shouldn't they be 'datetime' ? 
https://github.com/angaither/dosomething/blob/dev/modules/dosomething/dosomething_fact/dosomething_fact.install#L41

if they remain in, the view will need to do php processing to convert the timestamp into that format.

**Comment by aaronschachter** [comment]
hook_entity_property_info() will allow you to tell views that the field should be formatted as a timestamp.http://drupalize.me/videos/better-entity-property-information
