### ISSUE TITLE
Invalid SMS Campaign Reportback CAMPAIGN_TITLE merge_var value

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3835]
An email received for a **SMS campaign reportback** "Make It Happy" - https://www.dosomething.org/node/4987 (email below). It appears "Join [site:member-count] members" is being sent as the value for the *|CAMPAIGN_TITLE|* merge_var. The results are:

**Template: mb-campaign-reportback-us**

> We got your *|CAMPAIGN_TITLE|* pics. Score! Thanks for making the world suck less.

becomes:

> We got your Join [site:member-count] members. pics. Score! Thanks for making the world suck less.

My understanding is the SMS report backs are now triggered by a cURL call to https://www.dosomething.org/api/v1/campaigns/[nid]/reportback from the SMS application.

It appears there's a bug in the service that handles campaign report backs? I wasn't able to find the code in the dosomething repo to point to the specific bug.

![image](https://cloud.githubusercontent.com/assets/2119264/5949533/ba7654f8-a71c-11e4-9db9-28e0e71cff01.png)

**Comment by aaronschachter** [comment]
That's pretty bizarre. the node title of the homepage is "Join [site:member-count]".  I believe this may be  happening because the API will not let you report back on a closed campaign.  Can we confirm that this only happens for node 4987 and not all SMS reportbacks?

**Comment by aaronschachter** [comment]
@jonuy I think this one's on your end. Looks like the reportback endpoint is reporting back to the Homepage node instead of the correct Campaign node.  Check out Ariel's profile:

![screen shot 2015-01-29 at 1 04 37 pm](https://cloud.githubusercontent.com/assets/1236811/5963122/815d2890-a7b7-11e4-9bf3-9edd0dd4daa6.png)

**Comment by jonuy** [comment]
There was a mistake in how this got configured and yea, it was set to say the report back was for node 1141. It's been fixed to use 4987.
