### ISSUE TITLE
Move Mobile Commons Signup Submissions to Message Broker

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3840]
**Motivation**:
This issue is a result of a request to manage "old people" (25+) registrations. 25+ users should not be submitted to Mobile Commons. The goal is to maintain the registration / signup logic based on age in the Drupal application and move the transactional processing of the related services (Mobile Commons / MailChimp / etc) to Message Broker.

The mbc-registration-mobile Message Broker system currently signs up mobile numbers to Mobile Commons opt_in paths in specific cases where a mobile number is present and the "activity" in the message payload is set to:
- user_welcome-niche
- user_import
- cgg2014_signup
- cgg2014_vote

This issue will move the Mobile Commons sign up request from the Drupal application to the `mbc-registration-mobile` consumer. Relevant information (mc_opt_in_path_id) in the `dosomething_mbp_request` - `$params` will be needed and **all** "activity" values will be processed. Excluding the mc_opt_in_path_id value in the message payload will result in the message being skipped by mbc-registration-mobile. In effect meeting the requirements of not submitting 25+ user registrations to Mobile Commons by simply excluding the mc_opt_in_path_id value.

See:
- dosomething_signup_mobilecommons_opt_in($account, $opt_in, $node->title);

```
mobilecommons_request('opt_in', $args);
```

https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_signup/includes/dosomething_signup.mobilecommons.inc#L33

**and**
- dosomething_signup_mobilecommons_opt_in_friends($values)

```
mobilecommons_request('opt_in_with_friends', $vars);
```

https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_signup/includes/dosomething_signup.mobilecommons.inc#L122-L144

**Called from**:
- dosomething_signup_third_party_subscribe($account, $node)
  https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L394-L411
- dosomething_user_new_user($form, &$form_state)
  https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L421-L449
- dosomething_signup_sms_game_signup_request($sms_game_type, $values)
  https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L727-L743

**Related**:
https://github.com/DoSomething/mbc-registration-mobile/issues/8
https://github.com/DoSomething/dosomething/issues/3849 (Old People)

**Comment by deezone** [comment]
@aaronschachter @sergii-tkachenko Thoughts?

**Comment by aaronschachter** [comment]
This makes sense to me. Discussed with @DeeZone and this issue is quite similar to #1675

**Comment by deezone** [comment]
@sergii-tkachenko This is the first step in adding the Old People functionality:
https://github.com/DoSomething/dosomething/issues/3849

**Comment by sergiitk** [comment]
Ref #4058.
