### ISSUE TITLE
spacing of title/cta is off on pitch page if there is a date

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3844]
![image](https://cloud.githubusercontent.com/assets/6330971/5977171/4d3d9200-a863-11e4-88a3-ec23ec90ee4d.png)

![image](https://cloud.githubusercontent.com/assets/6330971/5977174/53c690ea-a863-11e4-90b2-5109d116d7b2.png)

@lkpttn can you please work with @DFurnes on this? Also please check mobile on this as well.

**Comment by lkpttn** [comment]
So what we gonna do is

.date {
margin-top: 0;
}

**Comment by DFurnes** [comment]
Fixed in latest Neue release, and live on staging! Closing!
