### ISSUE TITLE
Content for placeholder image captions.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#3850]
Upcoming PR will include captions on placeholders that will be hard-coded for the time being. 

The language used is currently _lorem ipsum_ so we need to replace that will specific language unless it happens that the majority of our users speak 1st-century BC Latin, and these passages from the nonsensical translation of _Cicero's_ text is somehow _on brand_ ;)

-Cheers!

![image](https://cloud.githubusercontent.com/assets/105849/5980723/53cca03e-a881-11e4-9927-ab9c80808300.png)

**Comment by mikefantini** [comment]
@weerd let's go with these
- DoSomething? Just did.
- Doing good never looked so good.
- Don’t let the smile fool you. I crushed it.
- Making the world suck less, one photo at a time.
- Pics or it didn’t happen? Oh, it happened.
- I get action. Social action.
