### ISSUE TITLE
Broken Campaigns on beta3

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3865]
![Broken](https://s3.amazonaws.com/uploads.hipchat.com/34218/880596/nVlFxKbyQoEmPEO/upload.png)

Per hipchat convo -- seems to happen only beta3... seems php5.5 syntax?

```
Warning: Illegal string offset 'safe_value' in dosomething_campaign_load() (line 128 of /var/www/beta.dosomething.org/releases/20150129215555/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc).
```

**Comment by sergiitk** [comment]
It's not the offset. Looks like this is the error: node--action_guide.tpl.php:37

```
          <?php if (isset($subtitle)): ?>
                                      \_ HERE
==== 5: ERROR: (FATAL) unsupported old-style syntax. Please use {...} instead.
```

**Comment by sergiitk** [comment]
No, that was incorrect. This is the one:
[node--action_guide.tpl.php:31](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_action_guide/node--action_guide.tpl.php#L31)

Short tag used: `<?`
