### ISSUE TITLE
Calculate Reportback Totals upon insert and update

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3874]
Updated description:
- [x] Update the pending total upon Reportback File insert for its campaign, and its primary cause tid.
- [x] Upon review (Reportback File save), update the totals for all statuses for the Reportback's campaign node and the campaign's primary tid.

Original description:

Refs #3846 
- Drush command to run `dosomething_reportback_reset_all`
- Schedule Jenkins job to regularly update saved Reportback Total helper variables.

**Comment by aaronschachter** [comment]
@sergii-tkachenko Is this something you'd be able to take on? I'd be a little lost on scheduling the Jenkins Job.

It may make sense to alternate calculating the totals for the `taxonomy_term` and the `node` entities (vs doing them all in one job)

**Comment by sergiitk** [comment]
Yes, I can do that.
