### ISSUE TITLE
remove field_video_id from image content type

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3877]
![image](https://cloud.githubusercontent.com/assets/6330971/6042517/7bb3d01a-ac53-11e4-9627-481bcefd50cd.png)

**Comment by aaronschachter** [comment]
@deadlybutter Git blame points to you on this guy. You'll need to 
- [x] create a new update hook in `dosomething_image.install` which deletes the `field_video_id` instance via `field_delete_instance`
- [x] Run the update locally via `drush updb`
- [x] Update the DS Image feature via `drush fu dosomething_image` which should remove the relevant Video ID information from the DS Image feature.

**Comment by itsjoekent** [comment]
Now how did that find its way in there...
