### ISSUE TITLE
client side validation needed for accepted image file types

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3878]
error only comes after the whole form has been submitted, ideally this error should appear right after the user selects an invalid file:

![image](https://cloud.githubusercontent.com/assets/6330971/6042932/c1a546a0-ac56-11e4-909a-839d9bdfe79a.png)

related trello card: https://trello.com/c/dflw2sBj

**Comment by barryclark** [comment]
Closed #3914 as it was the same problem as this.
