### ISSUE TITLE
styling borked on caption field

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3879]
![image](https://cloud.githubusercontent.com/assets/6330971/6043036/89d1f164-ac57-11e4-87c7-eb49657aa61e.png)

**Comment by DFurnes** [comment]
Ooooof. @sbsmith86, I never committed the fix to the typo when I used the wrong class name :cry:

**Comment by sbsmith86** [comment]
@DFurnes whoops. easy enough to fix :hammer:
