### ISSUE TITLE
A preview image and caption should only be shown if the user clicks done button.

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#3891]
If a user closes the modal or hits the change photo button. The modal should close, but we shouldn't update the page with a preview image or show the caption field yet. We should only show that when the user clicks the done button.
- [x] remove current functionality that refreshes the page when user clicks "change photo"
- [x] Update code to listen for a done button click instead of the modal close event to kick off crop preview.

**Comment by mikefantini** [comment]
related trello card: https://trello.com/c/1Nz6fUun
