### ISSUE TITLE
Reportback Image limit

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3894]
Some users upload lots of images, as in 20 or 30. We should set a limit.

**Comment by weerd** [comment]
@aaronschachter Other possibility is that we set a limit on total for a user in a campaign, but uploading new ones just replaces the earliest submissions from them for that campaign. I don't want to penalize users for using our system and eagerly adding more photos.

We can probably have some sort of language that lets them know any more past a certain number replaces old one?

**Comment by angaither** [comment]
competition users sometimes submit lots of photos, we don't want to set a limit
