### ISSUE TITLE
Sum variable for Campaign Quantity

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3899]
Store a new calculated helper variable `sum_quantity` for each campaign node, which calculates the sum of all Reportbacks where flagged = 0 and also have no pending Reportback Files.  Call this function within `dosomething_reportback_reset_all` (Refs #3874)

Refs: https://trello.com/c/fRDF3nFy cc @mikefantini

**Comment by mikefantini** [comment]
@aaronschachter what does the "and also have no pending Reportback Files" mean?

Does it only calculate the quantity sum if there are no reportbacks in the inbox?

**Comment by aaronschachter** [comment]
Reportbacks which have any RB Files set to `pending` status should not have their quantity counted in the sum.  Once the pending file status is set to either Approved/Promoted/Excluded, its reportback quantity will be included in the sum (upon next calculation).

**Comment by mikefantini** [comment]
ok great. wanted to make sure that's what it meant.

**Comment by angaither** [comment]
closed with #4317
