### ISSUE TITLE
Improve UX on Caption field in Reportback form/cropping modal.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#3904]
As per @lkpttn's [comment](https://github.com/DoSomething/dosomething/issues/3527#issuecomment-73306672) regarding the user experience on the caption form field.

**Comment by angaither** [comment]
@weerd @lkpttn we have a limit in the box, so going to close this for now, feel free to re-open if there was a different functionality desired here. 
![image](https://cloud.githubusercontent.com/assets/645205/11191082/5d80aff6-8c67-11e5-99a7-86e6b8dc7be2.png)
