### ISSUE TITLE
Squishy preview image on mobile

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3909]
- Image itself was distorted but took up the whole area
- Image was cut off, so only took up a portion of the area

**Comment by sbsmith86** [comment]
@mikefantini @barryclark I think I seemed to have narrowed the squishy image issue to happen when a user uploads a portrait image vs a landscape image on mobile. Just something to keep in mind when testing.

**Comment by mikefantini** [comment]
awesome thanks! i'll keep this in mind when we have TSG re-test once a fix is in. Also also just make sure in general they test reporting back on mobile.
