### ISSUE TITLE
Modal is easy to accidentally close while trying to drag the grab-box™

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3912]
happens when users move too fast to enlarge the grab-box

**Comment by mikefantini** [comment]
@sbsmith86 is this related to #3953 or is it a less descriptive duplicate of that issue?

**Comment by sbsmith86** [comment]
@mikefantini yea, it looks like #3953 is the main issue.

**Comment by mikefantini** [comment]
ok cool closing this one out then thanks @sbsmith86!
