### ISSUE TITLE
DS MBP PHP Notice: Undefined index: username

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3921]
Happens on password reset.

Notice: Undefined index: username in dosomething_mbp_get_transactional_payload() (line 127 of /var/www/beta.dosomething.org/releases/20150209191210/lib/modules/dosomething/dosomething_mbp/dosomething_mbp.module).

**Comment by aaronschachter** [comment]
@DeeZone Why do we need the `username` at all here?

**Comment by deezone** [comment]
@aaronschachter Good point, we could remove it!

**Comment by deezone** [comment]
@aaronschachter ^^
