### ISSUE TITLE
"File upload error. Could not move uploaded file." on node 4044

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3926]
Getting the following error on node 4044:

![image](https://cloud.githubusercontent.com/assets/6330971/6130900/6cfa8862-b116-11e4-9d16-b493f3c7b85b.png)

@aaronschachter thinks this may be a permission error on the reportbacks/4044 folder

also are we able to see error logs for this error occurring on other nodes?

**Comment by blisteringherb** [comment]
@mikefantini the file system status page had an error saying that the /tmp folder couldn't be written.  I changed that which may have fixed your issue.  Would you mind testing it?

**Comment by mikefantini** [comment]
@blisteringherb still seeing the issue on this particular node w/ the original image i tried

**Comment by mikefantini** [comment]
@blisteringherb from @aaronschachter:

i wonder if its because the file may exist already. usually it rewrites with the suffix, like _1 .. but i wonder if its not doing that for some reason. the file i'm trying to upload is called computerdog.jpg. another example is Calvin+Naomi.jpg

**Comment by blisteringherb** [comment]
@mikefantini what action are you trying to take when this happens?  What image are you using and in what field?

**Comment by mikefantini** [comment]
@blisteringherb i'm using Calvin+Naomi.jpg and uploading it to the normal image field on the reportback form

**Comment by aaronschachter** [comment]
This is happening when reporting back, so we're not actually saving it to a Drupal field. The image is saved via Form API, and the reportback file destination is determined here: https://github.com/DoSomething/dosomething/blob/v0.3.218/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L637

**Comment by mikefantini** [comment]
@blisteringherb - also @apatheticslacker was also seeing this issue when trying to upload mirrors.jpg to node 3755

**Comment by aaronschachter** [comment]
@blisteringherb To confirm / document -- this was a file permissions error, correct? Ok to close?

**Comment by blisteringherb** [comment]
@aaronschachter Yes, that's correct, it was a perms error on the beta3 server.
