### ISSUE TITLE
ZenDesk submission error

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#3931]
When users attempt to submit a help ticket to Zendesk on the "Make it Happy" node, they receive the following error:

```
Recoverable fatal error: Argument 1 passed to Zendesk\API\Users::update() must be of the type array, null given, 
called in /var/www/beta.dosomething.org/releases/20150209195759/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module on line 367 and 
defined in Zendesk\API\Users->update() (line 128 of /var/www/beta.dosomething.org/releases/20150209195759/html/profiles/dosomething/libraries/zendesk/src/Zendesk/API/Users.php).
```

@marahml @mikefantini

**Comment by aaronschachter** [comment]
This doesn't occur for a new registration. Seems to be an issue with checking for existing ZD users: https://github.com/DoSomething/dosomething/blob/v0.3.222/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module#L355
