### ISSUE TITLE
Picture rotates in only 180 degree increments after clicking on Change Photo.

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3935]
1. Log in to http://staging.beta.dosomething.org/campaigns/hunt-day-2-trash-scavenger-hunt
2. Click the Add Photo blue +.
3. Select a picture, and then click "Change Photo".
4. Click the Add Photo blue + again.
5. Select a picture, and then click "Rotate Photo".

The image rotates in 180 degree increments instead of the usual 90.

putting this in as a post-launch issue @barryclark @sbsmith86

**Comment by mikefantini** [comment]
related trello card: https://trello.com/c/spE1KKhI

**Comment by sbsmith86** [comment]
Great catch! This should be an easy fix.
