### ISSUE TITLE
Unable to load a PNG, no error messages given

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3950]
To replicate:
1. Go to this campaign: http://staging.beta.dosomething.org/campaigns/patient-playbooks?source=node/1165
2. Click the + to upload your image
3. Select a PNG from your computer
4. User can't continue, no modal pops up, no error message is shown,

**Comment by mikefantini** [comment]
@barryclark @sbsmith86 this one has been closed out too yeah?

**Comment by sbsmith86** [comment]
@mikefantini yep
