### ISSUE TITLE
Use default hardcoded placeholder images as fallback.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#3956]
If there are no placeholder `fids` available, then we need to provide a final fallback of the DS Logo filler so that the placeholders have some image content for the outputted markup.

**Comment by aaronschachter** [comment]
It could also make sense to add the current placeholder images into the theme as files, and use those. When we launch this on international, the DS logo will be all over the place.

**Comment by weerd** [comment]
Hmmm, maybe have the placeholders as fallback if no placeholders uploaded, but if placeholders added to CMS, then default to those?

@mikefantini @barryclark ?

**Comment by mikefantini** [comment]
@weerd sounds good to me. I'm also showing Micah this week how to add placeholders to each international instance

**Comment by aaronschachter** [comment]
Ya sounds good. Def still keep the current ability to override the placeholders within the CMS.

**Comment by weerd** [comment]
Righty-o! Gonna update this issue title to reflect above thoughts!

**Comment by weerd** [comment]
Use default hardcoded placeholder images as fallback if no uploaded placeholders are available for a campaign.
