### ISSUE TITLE
Handle reportback caption overflow

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3960]
Shouldn't happen ongoing with validation added, but still makes sense to have checks in place in case it fails.

![screen shot 2015-02-12 at 12 17 45 pm](https://cloud.githubusercontent.com/assets/1236811/6172822/4139377c-b2b1-11e4-830d-c58cb33e1399.png)

**Comment by weerd** [comment]
This PR #4041 added some fender-y fixes to help visually solve this. Could eventually be useful to truncate the text at 60 characters before outputting, but not sure how crucial that is.
