### ISSUE TITLE
Uploading an image in landscape and switching back to portrait distorts the image in the modal

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#3961]
On Android, when a user uploads and image and the modal pops up in landscape or portrait mode, when the user switches screen orientation, the image is distorted in the modal.

**Comment by mikefantini** [comment]
please look into this @sbsmith86 and close out if no longer an issue

**Comment by sbsmith86** [comment]
I am unable to recreate this issue. But we can reopen if we see it again.
