### ISSUE TITLE
Caption required bug

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3962]
Updating an existing reportback without changing the image always gives a "Caption field" is required error. Unless you choose to add another photo.

**Comment by aaronschachter** [comment]
There is no `caption` property on a Reportback entity, so this check always fails: https://github.com/DoSomething/dosomething/blob/v0.4.2/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.forms.inc#L216

Set the default value of the caption to `$reportback_latest_submission->caption` if it exists.

```
  $caption = t("DoSomething? Sure did");
  if (isset($reportback_latest_submission->caption)) {
    $caption = $reportback_latest_submission->caption;
  }
```

If it does not exist, we need a default value for the caption (for old reportbacks saved without them).  @mikefantini How does "I fucking did something!" sound?

**Comment by mikefantini** [comment]
@aaronschachter i can't remember why we never kept you on the content team full-time

spoke with @weerd about this and we're just going to hard code one of the placeholder captions. for now let's go with "DoSomething? Just did."
