### ISSUE TITLE
Submit button animated icon working funky on mobile browsers

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#3968]
Firefox on Android and Chrome on iOS had some funky and or faint rotation animation icon after hitting submit on reportback form.

This happens on occasion...

**Comment by DFurnes** [comment]
Having trouble replicating this. Most likely culprit is either a browser issue, or it was using the [fallback GIF](https://github.com/DoSomething/neue/blob/dev/assets/images/fallbacks/spinner.gif) which is shown when SVG animation is not supported.

**Comment by DFurnes** [comment]
Going to close – re-open if there are reliable steps to reproduce!

**Comment by weerd** [comment]
Hokay!
