### ISSUE TITLE
Safari photo upload crashes the tab in iOS 8.0.2

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3971]
Too much memory being used? Something is crashing whenever we choose to take a photo from safari instead of uploading from the gallery. Gives the error "An error occurred and the web page was reloaded".

Mostly on iPhone 6.

cc @weerd @sbsmith86

**Comment by aaronschachter** [comment]
FYI - I have been testing with 8.1.2 and was able to post in Safari with camera twice without issues.

**Comment by mikefantini** [comment]
@aaronschachter you have iphone 5 right?

**Comment by aaronschachter** [comment]
iPhone 5S

**Comment by lkpttn** [comment]
Clarification, this has happened mostly on iPhone 6. I think Diego also had it happen once to him, but nowhere near as frequently.

**Comment by sbsmith86** [comment]
@mikefantini any other reports of this? Not able to recreate it.

**Comment by mikefantini** [comment]
closing for now.

@lkpttn if you see this again and are able to consistently reproduce it, please open.

I haven't heard of Zendesk complaints that point to this being an issue for users
