### ISSUE TITLE
Devel generate campaign - PHP Notice

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#398]
When creating test campaign entries with Devel (/admin/config/development/generate/content)

Notice: Undefined index: revision_id in field_collection_field_get_entity() (line 1589 of /vagrant/html/profiles/dosomething/modules/contrib/field_collection/field_collection.module).
Notice: Undefined index: revision_id in field_collection_field_get_entity() (line 1591 of /vagrant/html/profiles/dosomething/modules/contrib/field_collection/field_collection.module).

These notices are generated regardless of settings - "Delete all content...", etc

**Comment by angaither** [comment]
https://drupal.org/node/1852112

https://drupal.org/files/1852112-entityreference-field-value-devel-generate.patch

this patch looks like it will work.

**Comment by deezone** [comment]
Thanks for the pointer @angaither I read through the thread you pointed at and it appears the issue has a few elements involved. The final solution appears to be detailed below. I'll take a shot applying it on my local.

---

Posted by LeviThomason on June 23, 2013 at 1:30am
Confirming entityreference 7.x-1.0+7-dev (2013-Jun-06) and patch in #18 works :)

---

#18
Posted by chrowe on May 6, 2013 at 2:03pm
Status  File    Size
new  entityreference-devel_generate_fix-1852112-18.patch    1022 bytes
PASSED: [[SimpleTest]]: [MySQL] 119 pass(es).
[ View ]
Using the current dev release ( drush dl entityreference --dev ) I still get an error trying to generate nodes that reference other nodes using entityreference.

Took patch from 12 and manually applied it. This fixed my issue and I can now generate nodes that reference other nodes. As long as there are existing nodes to reference.

patch attached.

---

https://drupal.org/files/entityreference-devel_generate_fix-1852112-18.patch

**Comment by angaither** [comment]
@DeeZone @aaronschachter should we add this patch to the makefile?

**Comment by aaronschachter** [comment]
If we can confirm it gets rid of the errors, I'm all for it.  @DeeZone -- did you get a chance to test?

**Comment by barryclark** [comment]
@DeeZone Any update on whether this worked on your local?

**Comment by aaronschachter** [comment]
I don't think we need to spend more time looking into this, it's an issue in devel_generate, which we only use for generating dummy content, and it doesn't break anything.
