### ISSUE TITLE
Questions about http://staging.beta.dosomething.org/api/v1/users.json?parameters[mobile]=2125550001

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#3985]
Looking at the docs for GET `/users?parameters[email]=test@test.com`: 
https://github.com/DoSomething/dosomething/wiki/API#find-a-user

**Questions**:
-  The example URL points to: `http://staging.beta.dosomething.org/api/v1/users.json?parameters[mobile]=2125550001` I assume `http://www.dosomething.org/api/v1/users?parameters[mobile]=2125550001` is the actual URL? Note the domain points to `www` and `/users?` rather than `/users.json?`
- "Only available to a logged in administrator." Does this mean that a POST with an authenticated user is needed using the User Login endpoint `/auth/login`?
  https://github.com/DoSomething/dosomething/wiki/API#user-login
- Would this mean that a GET request to `/users?parameters[email]=test@test.com` needs to include the auth details in the header?

```
      curl_setopt($ch, CURLOPT_HTTPHEADER,
        array(
          'Content-type: application/json',
          'Accept: application/json',
          'X-CSRF-Token: ' . $this->auth->token,
          'Cookie: ' . $this->auth->session_name . '=' . $this->auth->sessid
        )
      );
```

**Comment by aaronschachter** [comment]
1 - yep!  `/users` or `users.json` can be used interchangeably, depending on what is making the request and what the headers are sent to. 
2 - yep!
3 - yep!

**Comment by deezone** [comment]
@aaronschachter

> `/users` or `users.json` can be used interchangeably, depending on what is making the request and what the headers are sent to. 

Is this something that should be documented in the wiki? I'm not clear what the options are for "what is making the request". Perhaps this is common RESTful knowledge that I should already be aware of and documenting it would be stating the obvious?
