### ISSUE TITLE
Devel generage image - PHP Warning

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#399]
When creating test image content with /admin/config/development/generate/content the following PHP warning is produced:

Strict warning: Only variables should be passed by reference in _image_devel_generate() (line 36 of /vagrant/html/profiles/dosomething/modules/contrib/devel/devel_generate/image.devel_generate.inc).

This warning is generated regardless of settings - "Delete all content...", etc

**Comment by deezone** [comment]
Duplicate of https://github.com/DoSomething/dosomething/issues/297

**Comment by aaronschachter** [comment]
Closed - duplicate.
