### ISSUE TITLE
Spin up DoSomething Brazil (on hold)

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3995]
Initial checklist for review @aaronschachter @sergii-tkachenko @blisteringherb @mshmsh5000:
- [ ] Initialize the Brazil site from the most recent US snapshot
- [ ] Copy over campaign images
- [ ] Clean out non-staff users
- [ ] Clean out report backs
- [ ] Create accounts for Brazil admin team

**Comment by sergiitk** [comment]
What's the timeline for this @barryclark?

**Comment by aaronschachter** [comment]
Why would we not just start from a clean database?

**Comment by sergiitk** [comment]
@aaronschachter I think so we won't have to move the existing campaigns.

**Comment by angaither** [comment]
closing #global
