### ISSUE TITLE
After reportbacking back, redirect user to RB confirmation

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4004]
User should see the reportback confirmation page after submitting a reportback
### includes
- reportback photo
- caption
- why important
- number of nouns verbed
- campaign title

URL should be in pattern `reportback_id/{reportback_id}#{file_id}`

**Comment by aaronschachter** [comment]
@angaither - we may need to feature flag this redirect until the front end is done for the new permalink.
