### ISSUE TITLE
remove t-shirt offer ever if user has earned but not redeemed the offer

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4005]
chatted with Chris and Dave and we're going to deal with this requests ad hoc through Zendesk, so let's remove this from the site completely

Currently, if a user has already earned a t-shirt offer (by reporting back on 2 campaigns) they will be prompted to redeem their t-shirt offer every time they report back until the redeem it.

**Comment by aaronschachter** [comment]
Disabled the `dosomething_reward` module manually via the Admin UI
