### ISSUE TITLE
GA custom event on action page has stopped triggering

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4016]
relevant links:

https://github.com/DoSomething/dosomething/blob/7fa9340a3b2a971be0fc52581fd6d86cdef2964d/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L286-L288

http://stackoverflow.com/questions/13414440/checking-if-the-google-analytics-gaq-object-is-loaded-and-available/17474187#17474187

https://github.com/DoSomething/dosomething/pull/3626

**Comment by DFurnes** [comment]
Some further context: When we updated Drupal's Google Analytics module in #3626, it seems to have automatically opted us in to "Universal Analytics" which changes the Custom Tracking API.
