### ISSUE TITLE
Update Campaign Custom Settings

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4017]
Add a **Alt text color** field.

This field will affect the color of:
- Pics or It Didn't Happen
- field_reportback_copy
- view more link

*update: We decided this would be a hex field

**Comment by mikefantini** [comment]
context: we'll no longer be having patterns (i.e. jeans or clothing or steering wheels) but will continue to have the ability to alter the background color of the Prove It section.

So now, Alt color will affect the color of:
- Headers in the Know, Plan, Do sections (as it does now)
- Background color of the Prove It section

The new field will affect the color of:
- Pics or It Didn't Happen
- field_reportback_copy
- view more link

@lkpttn mentioned that this will generally either just be black or white, so if we want to build it like we have the "Dark Image" checkbox on images that probably works too.
