### ISSUE TITLE
First name text in nav should match other nav colors

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4023]
I.e. if nav font is black, user's first name should be black. if nav font is white, user's first name should be white:

![image](https://cloud.githubusercontent.com/assets/6330971/6275801/19b08f76-b850-11e4-89fc-8d17dfc742dd.png)

**Comment by itsjoekent** [comment]
fixed by https://github.com/DoSomething/neue/pull/460
