### ISSUE TITLE
Core Make: Upgrade to 7.26

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#403]
Dries can't stop, he won't stop.

**Comment by deezone** [comment]
Looking at drupal-org-core.make, the Drupal core version number appears to not be defined any more. It looks like we're following pantheon core versions with:

; Drupal Core
projects[drupal][type] = core
projects[drupal][download][type] = "git"
projects[drupal][download][url] = "git@github.com:pantheon-systems/drops-7.git"

Perhaps we don't need to worry about this anymore?

**Comment by aaronschachter** [comment]
Yup, good point.
