### ISSUE TITLE
Autoflagging reportbacks with 0 quantity

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4033]
Would make reviewing reportbacks a whole lot easier for reviewers.  We don't allow 0 on web, but SMS reportbacks currently don't seem to check.  Ideal fix here is to prevent saving a Reportback on SMS until the user enters a valid quantity.

**Comment by mikefantini** [comment]
Chatted with campaigns team and they'd rather just go through these. So we're not going to do this work.
