### ISSUE TITLE
Static content/Fact pages aren't linked in SOLR search.

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#4034]
When searching the site, static content pages and 11 facts pages aren't linked properly in the results.

![screen shot 2015-02-23 at 9 46 06 am](https://cloud.githubusercontent.com/assets/1865372/6330186/46dbee18-bb44-11e4-9809-29bf24ea83ec.png)

**Comment by DFurnes** [comment]
I think this is a mismatch of variables names with the new Figure template. Looking into it.
