### ISSUE TITLE
Remove legacy rb entity file view

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4044]
Remove `dosomething_reportback_file.inc`
As those classes, and build info will no longer be used.

**Comment by aaronschachter** [comment]
@angaither Per the description -- we'll still need the classes defined in `dosomething_reportback_file.inc` ... it has the `review` function and some extra stuff in the `save`.  ~~Just confirming that the items to remove are the `buildContent` and the `default URI` (functions for viewing a Reportback File entity)~~

**Comment by aaronschachter** [comment]
Scratch that - `buildContent` is being used in the Reportback Review form to display File info in each row. I think the only thing you'll need to remove here is the menu path for `rb/[fid]` (and update the Reportback Form to point that page, once it's complete)

**Comment by angaither** [comment]
So this issue is not needed then, correct?

**Comment by aaronschachter** [comment]
Well, it'd be good to remove the `rb/[rbid]` menu hook to avoid confusion for why it exists. I had built it thinking it would be the initial Reportback File permalink.  Could be good to keep open but not required for launch or anything like that.

**Comment by angaither** [comment]
Well, yeah but I'm changing that menu item into `reportback/[rbid]` in the next PR, so this issue is mooooot.

![](https://anuradhapathania48.files.wordpress.com/2014/10/tumblr_m63jh6qme01r82bbmo1_500.gif)
