### ISSUE TITLE
Campaign gallery API endpoint improvements

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4049]
Per convo w @mikefantini 
- [x] Return `promoted` images as well as `approved` in the Gallery endpoint
- [x] Add a new query parameter to filter by status (will allow us to only retrieve promoted files)
- [x] Add a new query parameter to filter by File fid's (can exclude multiples by comma, e.g. `?exclude=12,890,23412`

This would need corresponding changes on the front-end side to alter the logic gathering Gallery data to display.

**Comment by weerd** [comment]
Collecting a bunch of tasks that need to be completed to smoothly upgrade the API endpoints for the campaign gallery:

- [ ] Add a feature flag to toggle using `/api/v1/campaigns/{nid}/gallery.v2.json` so we don't break everything.

**Comment by angaither** [comment]
@weerd is this something that you did with the reportback api already?

**Comment by weerd** [comment]
Not the "excluding" portion of it. We could close this and re-open an issue for that feature alone if it's something we want later on?

**Comment by aaronschachter** [comment]
Didn't we want the exclusion for preventing duplicates on the web gallery? e.g. reportback item 23 is promoted and selected for the 6. it can easily show up agian in the approved section (displayed chronologically after the 6 random promoted)

**Comment by mikefantini** [comment]
@weerd is looking into this as he tackles #5170
