### ISSUE TITLE
Password Reset Endpoint

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4062]
An endpoint (perhaps `/api/v1/users/password_reset?email=<taget email>` is needed to request a password reset link for a specific Drupal user account by email address (or perhaps UID).

The password reset endpoint will be used by the `mbc-user-import`script. A password reset link is needed to send as part of the message content in the transactional email message for newly created Drupal users.

An example being the daily niche.com user import.

**Related**:
https://trello.com/c/Qsywpzzo
https://github.com/DoSomething/mbc-user-import/blob/master/MBC_userImport.class.inc#L128
https://github.com/DoSomething/mbc-user-import/issues/27
https://github.com/DoSomething/mb-toolbox/issues/29

**Comment by aaronschachter** [comment]
There is a Drupal Services password reset to look into before we build anything custom... although I believe it just sends an email (does not return the URL)

**Comment by itsjoekent** [comment]
Looking at a blog post, it seems to be triggered by the following:
$mail = _user_mail_notify('password_reset', $account, $language); - 
http://www.grasmash.com/article/create-passwordreset-resource-services

Looking for alternatives

**Comment by itsjoekent** [comment]
Found it! 

https://api.drupal.org/api/drupal/modules!user!user.module/function/user_pass_reset_url/7

**Comment by aaronschachter** [comment]
This endpoint will need an access check for administrator roles only. If the links were public, the endpoint could be used to login to any account.
- [x] Create a new targeted action: `users/[uid]/password_reset_url` which returns the output of `user_pass_reset_url` for the given uid.  Add this code into the `member_resource.inc` in the `dosomething_api/resources`.  Take a look at the `gallery` resource in the `campaign_resource.inc` for an example on how to implement a targeted action.

To make the endpoint accessible, enable the new `password_reset_url` resource and click Save. You'll need to clear cache to get it working and test it.  If all looks good, commit the code!
- [x] `drush fu dosomething_api` will modify the `dosomething_api.services.inc` file to enable the endpoint. Commit that code too.
