### ISSUE TITLE
Permalink page title

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4065]
After the rb is submitted, the title should say
"Awesome Work"
subtitle of "We got your pics"

@mikefantini is this language the same on every campaign?

**Comment by mikefantini** [comment]
yeah @angaither I want to chat w/ Ben about language. I should have an answer for you tomorrow on whether we can continue to pull from campaign node or if we need new fields added to https://beta.dosomething.org/admin/config/dosomething/dosomething_campaign to pull from

**Comment by mikefantini** [comment]
going to close this issue out as we should continue to use the confirmation page title field from https://beta.dosomething.org/admin/config/dosomething/dosomething_campaign for this. I'll be getting new copy from Ben on this to enter into that field on Monday.

creating a new issue now for new fields needed
