### ISSUE TITLE
Display reportbacks from past runs in Campaign Gallery

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4068]
Related to #4049

The gallery API will need to grab the relevant promoted+approved images from any Campaign Run nodes which belong to the parent Campaign node, and display those last, after the Campaign nid no longer has any more gallery images to display.

**Comment by aaronschachter** [comment]
Perhaps this should be a parameter you can pass into the gallery endpoint, e.g. `campaigns/[nid]/gallery?all-runs=TRUE`, for any instances where maybe we'd want only reportbacks from the current run...

**Comment by namimody** [comment]
When this is fixed, we should also check that published closed states of campaigns with archived activity continue to show member RBs.

**Comment by angaither** [comment]
we can close this because of #6056
