### ISSUE TITLE
Tidy up user profile dropdown UI

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#4071]
- [x] Fix the search bar popping left and right when you activate the dropdown (margin-left is inconsistent)
- [x] After logging in your name isn't correctly vertically aligned, it's too low ![image](https://cloud.githubusercontent.com/assets/692762/6394135/63d0117e-bd9d-11e4-9170-c97857f7c362.png)
- [x] After logging in your name is white. It should be black to match the rest of the navigation ![image](https://cloud.githubusercontent.com/assets/692762/6394022/a130f3f4-bd9c-11e4-8468-24761bb4f3e0.png)

cc @DFurnes

**Comment by DFurnes** [comment]
I just checked the second and third items as done. Joe fixed them in the latest Neue release which will be applied on next deploy.

**Comment by barryclark** [comment]
Great!

**Comment by itsjoekent** [comment]
that margin bug never seems to go away. I'm going to give it a nickname at this rate...
