### ISSUE TITLE
Add Global Redirect to clean up redundant paths

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#4077]
https://www.drupal.org/project/globalredirect

For instance, /taxonomy/term/21 should 301 to /volunteer/healthy-relationships, which is globalredirect's job.

**Comment by angaither** [comment]
@mshmsh5000 is this still a priority?

**Comment by mshmsh5000** [comment]
I wouldn't want to add this to the redirect logic we've been working on. At least, not a priority. We'll open a fresh issue if SEO considerations ever force us into it.
