### ISSUE TITLE
Fatal error introduced in v0.4.15

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4078]
EntityMetadataWrapperException: Invalid data value given. Be sure it matches the required data type and format. in EntityDrupalWrapper->set() (line 736 of /var/www/beta.dosomething.org/releases/20150226192013/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).

![image](https://cloud.githubusercontent.com/assets/672669/6400134/b0cec134-bdff-11e4-9b37-36c68b92d73c.png)

CC @barryclark @mshmsh5000 @DFurnes @angaither @weerd

**Comment by sergiitk** [comment]
https://github.com/DoSomething/dosomething/compare/v0.4.14...v0.4.15
I suspect [this](https://github.com/DoSomething/dosomething/compare/v0.4.14...v0.4.15#diff-6cd2bd158ecf1b2419b491fc3dae7ceaR409) @DFurnes

**Comment by DFurnes** [comment]
^ @angaither Any ideas?

**Comment by sergiitk** [comment]
Located the function producing the error:
https://github.com/DoSomething/dosomething/compare/v0.4.14...v0.4.15#diff-ad30a5d569ca2ae6d2e04223aa501104R1294

**Comment by sergiitk** [comment]
Seems like `dosomething_user_load()` designed to be a utility function, but it created a `hook_user_load()` instead.

**Comment by sergiitk** [comment]
Fixing it.
