### ISSUE TITLE
Static content headers are too far from galleries

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#4083]
Looks like the header here is in a separate div that keeping it far away from the gallery. Should be the same as if the header was above a paragraph.

![screen shot 2015-02-26 at 4 52 33 pm](https://cloud.githubusercontent.com/assets/1865372/6402734/e0a53faa-bdd7-11e4-8d29-b82df5151e4e.png)

cc: @julielorch

**Comment by DFurnes** [comment]
This was fixed! :hammer:
