### ISSUE TITLE
Copy fields needed for DoSomething Campaign config

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4085]
Confirmation Page:
- [ ] Confirmation page subtitle
- [ ] Scholarship subtitle addition
- [ ] Important to you header
- [ ] Social header
- [ ] Social copy
- [ ] Social CTA

Non-owner Permalink:
- [ ] Title

Owner not as confirmation page:
- [ ] Title
- [ ] Subtitle

**Comment by mikefantini** [comment]
@angaither kept these all together like you asked, but feel free to break this out into 3 issues within 3 different milestones if you think that makes more sense

**Comment by angaither** [comment]
@mikefantini once set, are does the text apply to all campaigns or is it different per campaign?

**Comment by mikefantini** [comment]
@angaither this will be for all campaigns.

I just updated copy to http://staging.beta.dosomething.org/admin/config/dosomething/dosomething_campaign

Like we had in the mocks, it requires some tokens. I wasn't sure a. how to list those tokens out and b. if these field's supported those.

Can you take a look and let me know if you have any questions/create any new issues that are needed to support this?

**Comment by angaither** [comment]
@mikefantini cooool, I made an issue for that ^
