### ISSUE TITLE
/api/v1/users.json?parameters[email]=[email] returns invalid results

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4094]
Request to:

```
https://www.dosomething.org/api/v1/users.json?parameters[email]=dlee+update-test01@dosomething.org
```

returns:

```
\n
\n[]
```

while user `dlee+update-test01@dosomething.org` exists: https://www.dosomething.org/user/1827134 where return results should be:

```
\n
\n[{"uid":"1827134"}]
```

Request is done with required credentials:

```
      curl_setopt($ch, CURLOPT_HTTPHEADER,
        array(
          'Content-type: application/json',
          'Accept: application/json',
          'X-CSRF-Token: ' . $this->auth->token,
          'Cookie: ' . $this->auth->session_name . '=' . $this->auth->sessid
        )
      );
```

and is successful with `https://www.dosomething.org/api/v1/users.json?parameters[email]=dlee@dosomething.org` which returns:

```
\n
\n[{"uid":"1019736"}]
```

as expected.

**Comment by aaronschachter** [comment]
@DeeZone I am unclear on what the issue is here: Is it that the endpoint works as expected for the email  address `dlee@dosomething.org`, but not `dlee+update-test01@dosomething.org` ?

**Comment by barryclark** [comment]
Assigning this over to you to take a look at and work with @DeeZone on too @deadlybutter. 

This issue is the highest priority right now :high_heel:

**Comment by itsjoekent** [comment]
okie dokes

**Comment by aaronschachter** [comment]
If the problem is https://github.com/DoSomething/dosomething/issues/4094#issuecomment-76788283, sounds like a potential issue around handling encoding non alpha-numeric characters.

**Comment by itsjoekent** [comment]
Looking at its callback, I don't see it filtering out anything so it doesnt _seem_ to be a backend issue.

https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_api/resources/member_resource.inc#L175

I'll try replicating this tomorrow and figure out whats goin on, @aaronschachter theory sounds right but Ill investigate more

**Comment by barryclark** [comment]
Thanks @deadlybutter!

**Comment by deezone** [comment]
@aaronschachter 

For what it's worth:

> Is it that the endpoint works as expected for the email  address `dlee@dosomething.org`, 
> but not `dlee+update-test01@dosomething.org` ?

"yes"

**Comment by deezone** [comment]
@deadlybutter To add to this, period "." is also a valid character along with "+" and "-" in an email address (ex: darrendouglas.lee@gmail.com) which should result in a match:

```
\n
\n[{"uid":"1091507"}]
```

Perhaps an issue for later work but returning some type of FALSE boolean rather than an empty response when a match is not found would be preferred. Getting a response of:

```
\n
\n[]
```

seems incomplete indicating some kind of internal error.

**Comment by itsjoekent** [comment]
Was able to reproduce the bug, gonna check to see if drupal is throwing any errors 

-update 
Tried two diff. accounts with symbols in there name, neither worked -- gonna log the parameter in my dev environment to see if its getting that far

**Comment by barryclark** [comment]
:+1: Thanks for the update @deadlybutter

**Comment by itsjoekent** [comment]
Found the problem

![screen shot 2015-03-03 at 2 59 15 pm](https://cloud.githubusercontent.com/assets/897368/6471043/e9b01ffc-c1b5-11e4-999a-3cbd4d159975.png)

The string Drupal receives does not contain the + sign 

## 

This answer on SO explains the plus sign problem. 
http://stackoverflow.com/a/5450212/2129670

~~I imagine all of the other chars. having issues fall into this category of invalid / improper encoding. Ill try to find a list~~ 
this function should encode everything correctly http://php.net/manual/en/function.urlencode.php

**Comment by itsjoekent** [comment]
Talked with @DeeZone - closing issue, comment above ^ solves problem. just plug the email into the urlencode

**Comment by aaronschachter** [comment]
@deadlybutter Not exactly sure what best practice is, but wouldn't it make sense for the API to `urlencode` the `email` parameter though, to handle this globally ?

**Comment by itsjoekent** [comment]
@aaronschachter by the time the API gets the email parameter its too late. look @ the screenshot above, thats a print of the parameter once drupal passed it to the callback

**Comment by aaronschachter** [comment]
Right on. Great investigative work, @deadlybutter
