### ISSUE TITLE
Kill current confirmation page

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4095]
Once we go live with the new permalink, we can remove code for the old confirmation page.
- [ ] remove the if that checks for the variable `dosomething_reportback_display_permalink`
- [ ] [remove the menu hook for the confirmation page](https://github.com/DoSomething/dosomething/blob/70bd75b65779ba70220610492942d2a29d9cb2be/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L30-L38)
- [ ] [remove menu hook callback](https://github.com/DoSomething/dosomething/blob/8853999ec664c142c5ae76419a996a6c66bafe4b/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.pages.inc#L8-L16)
- [ ] [tshirt code](https://github.com/DoSomething/dosomething/search?utf8=%E2%9C%93&q=shirt&type=Code)
- [ ] [confirmation page tpl](https://github.com/DoSomething/dosomething/blob/8853999ec664c142c5ae76419a996a6c66bafe4b/lib/themes/dosomething/paraneue_dosomething/templates/campaign/reportback-confirmation.tpl.php)

Putting this in the milestone after the page goes live.

**Comment by angaither** [comment]
@aaronschachter can you think of anything else I'm missing?

**Comment by aaronschachter** [comment]
@angaither -- I'll take a look around.. one question is do we still display the Reportback Confirmation Message field on the Campaign node somewhere in the new page?

@mikefantini Do we want to kill T-Shirt form code completely, or should we leave it? There are actually quite a few variables here.

**Comment by mikefantini** [comment]
@aaronschachter right now we don't have plans to display the reportback confirmation message field anywhere (confirmed by Ben), but I'm hesitant to lose that data just yet.

also re: the t-shirt form code I'm all for removing it completely.

**Comment by aaronschachter** [comment]
I think there should be a separate issue from removing the T-Shirt form and variables. We should not kill the DoSomething Reward module/tables completely because we will need it for the mobile app.

**Comment by angaither** [comment]
Going to close this issue for now, since currently sms campaigns redirect to this campaign.
