### ISSUE TITLE
Permalink var tokens

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4106]
The permalink copy created needs to support tokens
Refs #4085

**Comment by aaronschachter** [comment]
What kind of tokens? Might be able to use built in core Node tokens if it's just fields on the Campaign node...

**Comment by angaither** [comment]
Node title, and user first name are the only two (I think)

**Comment by aaronschachter** [comment]
`token_replace` might work nicely here.

**Comment by angaither** [comment]
@aaronschachter I don't think that will work for the `user:first_name` since it's a custom field, Unless we've already created a custom token that.

**Comment by angaither** [comment]
I don't see one in `dosomething_user.module`

**Comment by aaronschachter** [comment]
I'm referring to using Drupal's default token system:

![screen shot 2015-03-06 at 11 13 32 am](https://cloud.githubusercontent.com/assets/1236811/6531970/fd3ce3f0-c3f1-11e4-8768-c9845239c23d.png)
