### ISSUE TITLE
User UID displayed in password reset one time login web page message

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4111]
When a user requests a password reset a transactional email is sent with a password reset link. The web page confirming the one time login displays the user UID as a part of the message.

![image](https://cloud.githubusercontent.com/assets/2119264/6496647/305c6b4c-c2a4-11e4-98f1-b16355cf4389.png)

Original Trello issue: https://trello.com/c/zFp3y9zl

**Comment by aaronschachter** [comment]
@DeeZone This is Drupal's default password reset email. It is actually displaying the User's username, but we set the username to the UID programatically upon user registration in the `dosomething_user.module`

**Comment by deezone** [comment]
Duh! It's on the template end. 

Thanks... sorry about that!

**Comment by deezone** [comment]
Related: https://github.com/DoSomething/dosomething/issues/2384

Reopening as my understanding is an update is needed on the Drupal side for the reset message contents. Perhaps the message contents can be altered to exclude the Username? The message is within the `user-pass-reset` form that's defined in `user_pass_reset()`:
https://api.drupal.org/api/drupal/modules!user!user.pages.inc/function/user_pass_reset/7

```
          $form['message'] = array('#markup' => t('<p>This is a one-time login for %user_name and will
 expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.
</p>', array('%user_name' => $account->name, '%expiration_date' => format_date($timestamp + 
$timeout))));
```

Would a form_alter be able to provide a new value?

Currently the reset web page on Drupal site is displaying the `username` in the page body:

![image](https://cloud.githubusercontent.com/assets/2119264/6529448/d3873f56-c3f6-11e4-99dd-3604e8579a40.png)

**Comment by aaronschachter** [comment]
A quick and dirty fix without code would be for someone to override the string via String Overrides with the desired text: https://www.dosomething.org/admin/config/regional/stringoverrides

Any objections @sergii-tkachenko @angaither  ?

**Comment by sergiitk** [comment]
@aaronschachter sounds right.

**Comment by deezone** [comment]
@sergii-tkachenko @aaronschachter 
How to use String Overrides in this case? The original text is coming from
https://api.drupal.org/api/drupal/modules!user!user.pages.inc/function/user_pass_reset/7

```
          $form['message'] = array('#markup' => t('<p>This is a one-time login for %user_name and will
 expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.
</p>', array('%user_name' => $account->name, '%expiration_date' => format_date($timestamp + 
$timeout))));
```

How to add an override string that has dynamic content? 

The goal is:

```
          $form['message'] = array('#markup' => t('<p>This is a one-time login that will
 expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.
</p>', array('%expiration_date' => format_date($timestamp + 
$timeout))));
```

**Comment by aaronschachter** [comment]
@DeeZone Anyone with admin access can change the text by adding it as a new entry to the admin ui per link above.

**Comment by deezone** [comment]
@aaronschachter Yes, I get that. My question is: What to do with text strings with tokens?

```
$form['message'] = array('#markup' => t('<p>This is a one-time login for %user_name and will
 expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.
</p>', array('%user_name' => $account->name, '%expiration_date' => format_date($timestamp + 
$timeout))));
```

Would new String Override be:

```
<p>This is a one-time login and will
 expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.
</p>
```

Are tokens: `%expiration_date` supported in String Overrides?

I guess I could just try it and find out... :)

**Comment by aaronschachter** [comment]
Yeup @DeeZone that should be it.  You can tell what tokens are supported by looking at `t()` function in the original code as you're doing, so you should be in good shape with `expiration-date` since it's added as into the array of variables sent in the code. 

just give it a shot on staging first :)

Also I believe you have to clear cache in order for the String Overrides to display.
