### ISSUE TITLE
Add scholarship qualification text

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4121]
This needs display if the incentive field is set on the campaign page.

**Comment by sbsmith86** [comment]
@lkpttn @mikefantini is there a quick mock of what/where this should be? Is it just right next to the subtitle? like "Subtile. [incentive text]"?

**Comment by mikefantini** [comment]
yeah you got it @sbsmith86 it's just the second sentence of the subtitle.
