### ISSUE TITLE
Don't print name if there's no caption

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4123]
Old reportbacks don't have captions, so it looks odd when you print the name without a caption

![](https://i.imgur.com/v8nCx1K.png)

**Comment by weerd** [comment]
It's like you've signed the picture :)

**Comment by sbsmith86** [comment]
lolz good catch!

**Comment by angaither** [comment]
@mikefantini should be proud of my QA

**Comment by mikefantini** [comment]
:clap:
