### ISSUE TITLE
API member count is the wrong request type

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4128]
`/users/member_count`
This is a `POST` request, it should be a `GET`

**Comment by aaronschachter** [comment]
This is because it's using a Services `targeted_action` and I was following examples of existing modules.  can be refactored to use a  Services `relationship` but will need to give a heads up to @DeeZone if/when this happens because email things use this endpoint.

**Comment by deezone** [comment]
Easy to update: https://github.com/DoSomething/mb-toolbox/blob/master/src/MB_Toolbox.php#L179-L210 

The deployment would be the challenge. Any chance of doing this in steps where a GET endpoint could be added while the POST continues to work for awhile? Perhaps GET `/users/member_count` as having "get_" in the URL is not sounding very "RESTful" anyways.

**Comment by angaither** [comment]
also, true @DeeZone 

I don't know the details of the services thing, but I would assume if we created the new endpoint without the `get` in the url, both would work at the same time.

**Comment by weerd** [comment]
:+1: @DeeZone 

Could even simplify it as `/users/count`. We shouldn't have verbs other than the HTTP verb in our enpoints!

**Comment by aaronschachter** [comment]
Worth noting that in the world of DS, the Members Count is different than Users count.  `users/count` looks like total # of users -- this endpoint returns total # of members.

**Comment by weerd** [comment]
`users/members/count` ?

Just tossing out ideas.

**Comment by DFurnes** [comment]
:+1: to changing to a `GET` and  removing `get_` from the endpoint URL. Also makes sense to "deprecate" the old `POST` endpoint but not fully remove for a while.

As for users vs. members, perhaps `users/count` and `members/count`?

**Comment by weerd** [comment]
:+1: @DFurnes I like that better. `/members/count` :dancer:

**Comment by itsjoekent** [comment]
Yes to the deprecating but keeping for a while. The current app that does the member counting for the homepage & dashboard relies on the post _but_ I'm discontinuing that app and migrating it's functionality into dashboard 2.0 so I don't need it for too long

**Comment by deezone** [comment]
My impression is to be even more "RESTful" there would be a parameter in the root GET `/count` request:
- GET `/count?type=user`
- GET `/count?type=member`

But this is stuff is like a religion, everyone has an opinion.

**Comment by weerd** [comment]
@DeeZone lol. I think I'm slowly finding that out, haha.

**Comment by itsjoekent** [comment]
please ping me (and @DeeZone ?) before you change this as we'll need to update our applications accordingly when this is deployed.

**Comment by deezone** [comment]
Due to "All things global" there's a need for this endpoint to return translated text in the supported Drupal app languages. Currently Message Broker makes use of this endpoint with a need to support each of the language types. 

Perhaps it would be better for the endpoint to just returned the number. The translation of the surrounding text could be managed in the requestor? I don't see the amount changing from "million" to "billion" anytime soon :)

**Comment by itsjoekent** [comment]
yeah I see nothing wrong with that

**Comment by angaither** [comment]
refs #6541 

https://github.com/DoSomething/phoenix/pull/6541#issuecomment-223610295
