### ISSUE TITLE
image styles errors on pitch page on staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4130]
![image](https://cloud.githubusercontent.com/assets/6330971/6535514/829b1230-c413-11e4-856a-d55439efde44.png)

**Comment by DFurnes** [comment]
Alrighty, found the issue. I forgot to enable the `imagecache_coloractions` module as well. Enabled on staging and it fixed issues. Putting up a PR to add to installation profile in a minute.
