### ISSUE TITLE
persistent nav is breaking to 2 lines on small screens

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4135]
![img_1045](https://cloud.githubusercontent.com/assets/6330971/6537641/eded40b8-c426-11e4-850b-d610568677d1.PNG)

**Comment by mikefantini** [comment]
iphone 5^

**Comment by DFurnes** [comment]
Closed by [Neue release v6.2.2](https://github.com/DoSomething/neue/releases/tag/v6.2.2).
