### ISSUE TITLE
fatal error on SMS games on staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4139]
![image](https://cloud.githubusercontent.com/assets/6330971/6561661/5e417e08-c669-11e4-8f50-80493d8ee52d.png)

**Comment by mikefantini** [comment]
tested on http://staging.beta.dosomething.org/campaigns/sms-campaign?source=node/1165

**Comment by aaronschachter** [comment]
`dosomething_signup_get_mobilecommons_vars` no longer exists... https://github.com/DoSomething/dosomething/commit/8d776c32bd11f490f8bf00955bfdc449f12b8afa#diff-e0f8778f3c265a20340a22593a3776ffL56

**Comment by aaronschachter** [comment]
This error should occur when a user is logged in: https://github.com/DoSomething/dosomething/blob/v0.4.28/lib/modules/dosomething/dosomething_signup/includes/dosomething_signup.mobilecommons.inc#L24

**Comment by sergiitk** [comment]
On it.
