### ISSUE TITLE
API password reset link is the wrong request type

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4140]
Currently `/users/[uid]/password_reset_url` is a POST request with empty POST values.
https://github.com/DoSomething/dosomething/wiki/API#get-password-reset-url

This should be:
- GET  `/users/[uid]/password_reset_url`

**Related**:
https://github.com/DoSomething/dosomething/issues/4128

**Comment by itsjoekent** [comment]
talked about this before with @aaronschachter -- since were supplying a UID and asking the server to generate a string I figured it was better to make it POST, since were not just getting something

**Comment by DFurnes** [comment]
Yeah, I agree this should be a `POST` since you're changing state on the server by creating a new password reset key. :+1:

**Comment by deezone** [comment]
So perhaps in an ideal RESTful world this could be:

POST `/users/password_reset_url` with `uid` being a POST value?

**Comment by DFurnes** [comment]
Aye.

**Comment by weerd** [comment]
@DeeZone Yeah, I was thinking that too. Plus, hides the users ID w/in the POST body if that's of any value...

**Comment by itsjoekent** [comment]
Hmm, well, you're doing an action for a specific UID 

This is how Github does it for example: /gists/:id/star

**Comment by deezone** [comment]
And thus the endless RESTful debate. "Github does it this way" is not a "pure" example. But whatever!

**Comment by itsjoekent** [comment]
Is there official documentation / resource that could answer this? 

And bringing up the Github point was to show other API's do it this way, whether or not it's right is a different question

**Comment by weerd** [comment]
Nothing that I know of. I've been doing some reading on APIs as well as looking at others. There's some consistent patterns they mostly all follow, but have their own differences. But there is some useful advice to adhere to.

**Comment by DFurnes** [comment]
[JSON API](http://jsonapi.org) seems decently well-respected. It was put together by some big names in the Rails and Ember communities.

**Comment by weerd** [comment]
:+1: 

> If you've ever argued with your team about the way your JSON responses should be formatted, JSON API is your anti-bikeshedding weapon.

**Comment by itsjoekent** [comment]
Based on that JSON API, since were doing a relationship this is technically correct 

http://jsonapi.org/format/#fetching-relationships
