### ISSUE TITLE
Allow users to share the permalink on the confirmation page. 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4143]
- [x] Link up facebook sharing
- [x] Link up twitter sharing
- [x] Link up tumblr sharing

**Comment by angaither** [comment]
twitter metatag

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@nytimes">
<meta name="twitter:creator" content="@SarahMaslinNir">
<meta name="twitter:title" content="Parade of Fans for Houston’s Funeral">
<meta name="twitter:description" content="NEWARK - The guest list and parade of limousines with celebrities emerging from them seemed more suited to a red carpet event in Hollywood or New York than than a gritty stretch of Sussex Avenue near the former site of the James M. Baxter Terrace public housing project here.">
<meta name="twitter:image:src" content="http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg">
```

**Comment by angaither** [comment]
oh, nice [twitter has a validator](https://cards-dev.twitter.com/validator)

**Comment by sbsmith86** [comment]
@angaither sweet! so are these things you would set on your end?

**Comment by angaither** [comment]
@sbsmith86 yeah, I'm working on the twittahz now.

**Comment by aaronschachter** [comment]
FYI @angaither I remember I had to submit our site to twitter to get the Cards working for campaign pages: https://github.com/DoSomething/dosomething/issues/1678#issuecomment-48954404

Unsure if we'll get Twitter Card Magic right off the bat or if there's anything else we'll need to submit.

**Comment by angaither** [comment]
[According to their docs](https://dev.twitter.com/cards/overview) it looks like we should be able to get the share card with just the meta tags. :pray:

**Comment by mikefantini** [comment]
also this is what the shares should [look like on the various social networks](https://a0465d35-a-5d563b7e-s-sites.googlegroups.com/a/dosomething.org/dosomethinguxwiki/product-archive/sharing-reportbacks/Artboard%207.png?attachauth=ANoY7coZwhJgV1B1VbLH2RE2o_PBSlqqT8g8UXuRf8v1qnk5-vZdEDua685zJc3obaB9mwVkIPirBZyrBnGYwKaONHuECOYhG0ZepBYFp4Li1UGZHCZUeJ-rit2ihFFLq-Vlz5XqchOEOkTAZrNArZbF2LeMXQmERxFFE4F5_CE0gG7dZGCkkrosOZnstmSzMZH0zVBhg4eCFs408jxLpmrd_rzz1iZtpAeX3fFL5aL3CVNnV_RWLeZvBnMuEMxFol0DD47yidN3fpGuF_4FDhW71gekKQqaxQ%3D%3D&attredirects=0)

**Comment by sbsmith86** [comment]
Pull requests #4171 #4169 #4172  should take care of sharing on all three platforms, but don't want to close this out without some more testing.
