### ISSUE TITLE
Can't authenticate with Chrome Postman

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4145]
The `seckit` module introduced in #3683 is blocking authenticating using Postman, outputting a watchdog message: 

```
Possible CSRF attack was blocked. IP address: 72.220.194.178, Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm.
```

A dev can workaround this when developing locally by disabling the SecKit module `drush -y dis seckit`, but leaves us hanging when testing API authentication against stage or production.

Possible solutions:
- Find a different tool that SecKit likes
- Something else

cc @jonuy @deadlybutter

**Comment by itsjoekent** [comment]
Not really familiar with CSRF attacks - what are they and why does seckit think this is one of them?

**Comment by jonuy** [comment]
Other tools that seem to work in order of "ooo fancy" to "eh it works":
- [Paw](https://luckymarmot.com/paw)
- [cocoa-rest-client](https://code.google.com/p/cocoa-rest-client/)
- [Poster Firefox plugin](https://addons.mozilla.org/en-us/firefox/addon/poster/)

**Comment by aaronschachter** [comment]
@jonuy for the win
