### ISSUE TITLE
Make all of the Tip fields required on the campaign template

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#4147]
Re: https://trello.com/c/XAO9XYpa/30-step-three-merge-tag

Often campaigns team don't fill them out, resulting in the variable not being filled out correctly in transactional email messages.

![image](https://cloud.githubusercontent.com/assets/692762/6567484/83ec733a-c69e-11e4-8104-7412d96ce262.png)

@angaither is this quick to tackle?

**Comment by mikefantini** [comment]
The fields to make required are:
- field_pre_step_header
- field_pre_step_copy
- field_post_step_header
- field_post_step_copy
