### ISSUE TITLE
Reportback API must support uploading files

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4151]
Investigating using base 64 encoded strings, similar to the Services's default File CREATE resource.

Planning on building this as extra data values to pass into the current `campaigns/:nid/reportback`, `file` and `filename`.  If neither exist, inspect the `file_url` for a given URL string (used by SMS Reportbacks)

cc @jonuy

**Comment by jonuy** [comment]
One potential area to be concerned about with using the base64 encoded method vs multipart is the memory it'll use. A photo that gets base64 encoded is gonna require at least its size and maybe more of additional space allocated on the client app.

Then you're also dealing with submitting the file in a single large payload. I might be wrong here, but for large enough payloads on slow enough connections, we could run into a connection timeout.

**Comment by aaronschachter** [comment]
Hm. I've been just trying to get anything up and running. postman seems to have a bug that doesn't allow you to actually submit a file when testing (https://github.com/a85/POSTMan-Chrome-Extension/issues/391), so i was able to finally get at least something working using the base64 in IOS and submitting the default File CREATE endpoint which expects the base64: http://cgit.drupalcode.org/services/tree/resources/file_resource.inc?id=6e32f77#n177

There is a separate `create_raw` endpoint: http://cgit.drupalcode.org/services/tree/resources/file_resource.inc?id=6e32f77#n209
 which again I had trouble testing with Postman to even get it working. I can download Paw and see if I can get any further.

The Flatiron prototype used S3 to upload Reportback images (to who knows where). Our working endpoint accepts a file URL, reads the contents, and creates it. If we eventually don't want to host these images on Drupal.. maybe this worth looking into?  I can spend a little more time trying to mimic the `create_raw` code, but at this point, just looking for whatever will get us prototyping quicker. Then again, are we prototyping or building the real API ? :\

**Comment by jonuy** [comment]
Given the effort involved, it seems to make sense to just at least get the base64 encoded method of file uploads working for prototypes. We can find out later in mobile app dev if it'll actually be a problem, or just throw someone like drewish at it.

**Comment by aaronschachter** [comment]
Ok, I'll continue with that approach for now, as I'm close to finishing it. I think the other approach using Services would require 2 POSTS: One to create the file and get the resulting fid (using the Services `create_raw` resource , and then another POST to the `reportback` endpoint). 

Using S3 seems like an option to keep in mind also (but not for this week).
