### ISSUE TITLE
updates to twitter card

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4160]
Refs: #4143 

Currently looks like:
![image](https://cloud.githubusercontent.com/assets/6330971/6598051/609f65f6-c7d7-11e4-8c4d-ff1aa8a653bc.png)

**Copy changes needed**:
main copy should read "I made an ACTUAL difference about [issue] and you can too. Sign up for [campaign_title] now: [url]"

Also any idea why it's structured so differently from what @lkpttn had outlined?
![image](https://cloud.githubusercontent.com/assets/6330971/6598071/8a9a0f0a-c7d7-11e4-903d-9dcfbe324356.png)

**Comment by angaither** [comment]
@mikefantini it should be set up like that card. It's supposed to be using  [that style](https://dev.twitter.com/cards/types/summary-large-image)

I pulled the copy from `Social copy on reportback permalink page.`  on the campaigns page, but it looks like that's not what you intended, so I will have to add another variable to that page.

**Comment by mikefantini** [comment]
ah yeah sorry @angaither that copy is for when we add shares to the confirmation page

should we add another field for "copy for social networks"?

**Comment by angaither** [comment]
done #4161

**Comment by mikefantini** [comment]
sweet thanks!

**Comment by mikefantini** [comment]
@angaither any idea why it's not using [this style](https://dev.twitter.com/cards/types/summary-large-image)?

**Comment by angaither** [comment]
@mikefantini 
the tokens you will need to enter in the `social network share copy` are
`[node:title]` `[node:issue]` the url will be added to the end of the text automatically

**Comment by angaither** [comment]
Updated the card
the text your card will look something like this will be replaced with the tweet text

> I made an ACTUAL difference about Mental Health and you can too. Sign up for Patient Playbooks now: http://staging.beta.dosomething.org/reportback/1186?fid=2574

![](http://cl.ly/image/3K313k0F2Q2o/Screen%20Shot%202015-03-12%20at%202.04.35%20PM.png)

**Comment by angaither** [comment]
Fixed with #4169
