### ISSUE TITLE
User Campaign Recommendations API endpoint

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4167]
Expose existing recommended campaign functionality in `dosomething_campaign` module as endpoint to provide x number of recommend campaigns for a given user.  Optionally pass a taxonomy term tid to filter by.

cc @DeeZone @barryclark

**Comment by aaronschachter** [comment]
Worth noting that we'll also want endpoints for a user's "doing" campaigns (signed up but not reported back) and potentially "completed" campaigns... although technically that's kinda just a query for the user's reportbacks..

**Comment by deezone** [comment]
+1 for the User Campaign Recommendations API endpoint, a fantastic addition for the Digest and Report Back MB messages.

There's existing functionality in MB for user's "doing" campaigns and "completed" campaigns. Both key functionality in the Digest message generation process. Perhaps there's value in the for the Drupal app but MB, use of such endpoints is unlikely.
