### ISSUE TITLE
Add a Reportback File Source property

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4168]
Not urgent, but we should create a new varchar column on the `dosomething_reportback_file` to track the source of a Reportback File, and to give us device specific data.  Potential values:
- `sms`
- `iPhone`
- `iPad`
- `android`
- `web` 

Although maybe we should store the browser info that we're sending to Zendesk here?  Or track specific iOS devices / operating systems, etc?

Def could use some input on what would be most useful @Bladt @barryclark @mikefantini

**Comment by angaither** [comment]
we vaguely do this
