### ISSUE TITLE
SMS game webform accepts player names

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#4185]
Currently, the SMS game webform takes an alpha name, alpha number, and 3 beta numbers. We want to run tests that allow for alphas to also include their friends' names.

I think the two main things that need to be done are:
- Modify request to POST to /sms-multiplayer-game/create with 3 additional parameters: `beta_first_name_0`, `beta_first_name_1`, and `beta_first_name_2`
- Setup in Optimizely so we can A/B test this thing

![sms game](https://cloud.githubusercontent.com/assets/696595/6641597/152b8808-c975-11e4-80de-44ddfc25eae8.png)

cc: @barryclark

**Comment by aaronschachter** [comment]
Refs (duplicates?) #3568

**Comment by jonuy** [comment]
oh yuppp totally a duplicate
