### ISSUE TITLE
Campaign: JS for Reportback form

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#419]
Paraneue is stripping out JS that makes Drupal's File upload work properly:
- If you upload an image the whole page refreshes (with your uploaded image present in the Reportback Image field)
- Needs js to remove or re-order uploaded images (I believe this is tabledrag.js)

Add relevant files via `drupal_add_js` in `dosomething_campaign_preprocess_node`.

**Comment by DFurnes** [comment]
This is something we should be building properly into Neue, rather than using Drupal's stock JS. Are multiple image uploads in the spec for Campaigns v1.0 (/cc @barryclark)?

**Comment by aaronschachter** [comment]
Let's discuss in our meeting today.  To get reportbacks functional as is, using Drupal's default JS to handle file uploads would be a quick lift.

**Comment by DFurnes** [comment]
Closing this issue, since we settled on using the normal `<input type="file">` tag for now during yesterday's meeting.

**Comment by aaronschachter** [comment]
Per round table mtg 1/22, re-opening, so we can use Drupal's default Image field to handle multiple images per single reportback.  We can always revisit using our own custom form to handle multiple image uploads at a later date.

**Comment by barryclark** [comment]
@DFurnes Assigning all campaign report back stuff over to you to tackle.

**Comment by DFurnes** [comment]
Closing this; gonna make new ones with actual current tasks since this guy is pretty far out of date.
