### ISSUE TITLE
Implement neue login/registration workflow

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#420]

**Comment by DFurnes** [comment]
Here's the markup I've been working with. The "Create an Account" link just switches the form `action` endpoint at the moment, but it could just as easily switch a hidden field within the form or whatnot.

https://gist.github.com/DFurnes/13e515850177e3b3e157

**Comment by barryclark** [comment]
@DFurnes I think we can close this?

**Comment by DFurnes** [comment]
Dependent on #830, #831, #832. Near the finish line. :checkered_flag:

**Comment by barryclark** [comment]
:racehorse:

**Comment by DFurnes** [comment]
:smoking:

**Comment by barryclark** [comment]
:tada:
