### ISSUE TITLE
Permalink page error in metatag module

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4203]
`Fatal error: Call to a member function getImageURL() on a non-object in /var/www/vagrant/lib/modules/dosomething/dosomething_metatag/dosomething_metatag.module on line 128`

http://staging.beta.dosomething.org/reportback/685

**Comment by angaither** [comment]
That specific reportback has no fids.

**Comment by aaronschachter** [comment]
This scenario will happen when a Reportback has been flagged and we need to delete the image associated with it.

**Comment by angaither** [comment]
@aaronschachter The two particular cases one is 'approved' and the other is 'excluded' both still have the image in the admin section.

What's odd is in `dosomething_reportback_view_entity` the entity loads fine, with the fid(s) however in the metatag module I'm using `reportback_load(id)` and it doesn't load any fids, this doesn't seem to be the case for all reportbacks though
