### ISSUE TITLE
StatHat coverage for donations

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#4208]
1. Simple counter for each successful donation submission
2. Incrementing value for total donations collected

The first will be a health check for this integration in production. The second will be gravy, but worth tracking.

**Comment by angaither** [comment]
currently this repo doesn't have Stathat support, as most of the things are being logged in stathat are being done by message broker, but I think @weerd was looking into this for image cropping errors.

It would be nice to add Stathat tracking into this repo, (huge bummer it's just a php include file)
I'm wondering if there's something like Rules only, better that is an easy way to do event based logging/monitoring?

**Comment by weerd** [comment]
@angaither I hadn't started it yet. It was a low priority issue at the time and doesn't look like I'll be jumping on it the near future, so not much insight I can provide here :\

**Comment by mshmsh5000** [comment]
Well, there's [this](https://www.drupal.org/project/stathat). Created by @aaronschachter, you might know him.

**Comment by angaither** [comment]
well well well

**Comment by aaronschachter** [comment]
Right now that module only supports EZ Stats but i am happy to make others co-contributors on d.o to help build out the non ez stats !

**Comment by angaither** [comment]
These guys would just be EZ stats, as well... right?

**Comment by mshmsh5000** [comment]
@angaither I see the implementation of the first one, but not the second (running total of donations). Is that not in the plan right now?

**Comment by angaither** [comment]
@mshmsh5000 you mean the actual value we've gotten?

**Comment by mshmsh5000** [comment]
Yes! Like, if someone donates $5, we separately (a) record the singular donation event and (b) increment a total by $5.
