### ISSUE TITLE
updates to mobile confirmation page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4209]
- [ ] add in Social cta on reportback permalink page.
- [ ] remove Social header on reportback permalink page.
- [ ] remove Social copy on reportback permalink page.

**Comment by sbsmith86** [comment]
Just to make sure I got it. @mikefantini 
- Show the current social cta that is displaying on desktop on mobile as well
- Remove "Tell your friends" social header ?
- Remove "Get social with social action! Share your photo and impact with friends, and invite them to sign up for Hunt Day 1: #SuperStressFace."

**Comment by mikefantini** [comment]
@sbsmith86 
- yes
- yes, just remove this from mobile
- yes, just remove this from mobile
