### ISSUE TITLE
FB window should close after I post

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4210]
When sharing from the confirmation page, the FB window should close after I post to FB. This is how it works when I share from Twitter.

Currently, the window is staying open and reloading the permalink page after I post to FB. So I then have two windows (or two tabs on mobile) of the permalink page.

This then causes further issues if I try to share on another social channel after I share on FB (on mobile it just updates the "share tab" but it doesn't open it so the user is not made aware).

As a side note, Tumblr keeps the second window/tab open and just does it's celebratory confetti thing with no next step.

**Comment by mikefantini** [comment]
@sbsmith86 just went through the FB share flow on buzzfeed and it has the behavior we are looking for here.

**Comment by sbsmith86** [comment]
@mikefantini : so i have a fix for the fb/window issue going to staging. It doesn't look like we are going to be able to easily close the popup window on mobile but it does on desktop. However, I made an update that opens a new window everytime one of those social buttons are pressed so that we don't run into the issue where the window doesn't seem to open when going back to share on another network.

**Comment by mikefantini** [comment]
got it thanks @sbsmith86. I'll play with it and let you know if I have any adjustments, but what you described sounds like a smart solution

**Comment by mikefantini** [comment]
@sbsmith86 - weird so the window is now closing on desktop but not on mobile

is the intended experience that I stay on FB on mobile vs. being taken back to DS? I could see either making sense, but I guess it makes more sense to have one window stay open of DS and one window remain on FB if we can't close that second one out.

**Comment by sbsmith86** [comment]
@mikefantini yea so, I can't get the second window to close on mobile without some real hackery. So the user would have to go back to the original tab, but since each share button opens a new window they shouldn't have an issue sharing on a different network if they choose.
