### ISSUE TITLE
Admins should see a link to admin permalink page from gallery

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4219]
admins viewing images in the gallery should be able to clickthrough to reportback permalink to exclude/flag the image

```
if (user_access('view any reportback')) {
  link image to `/admin/reportback/<rbid>`
}
```
- [x] add link for gallery items output via PHP
- [x] add link for gallery items inserted via AJAX when viewing more.

**Comment by angaither** [comment]
@weerd since you are already doing refactoring on the gallery, do you think you can add this to your stuff?

**Comment by weerd** [comment]
Yes. Yes I can!

**Comment by mikefantini** [comment]
@angaither @weerd should we keep this open until admins can change status from _all campaigns_ not just ones in the promoted 6?

**Comment by weerd** [comment]
Sure. Working on it next, so should be able to close soon :)
