### ISSUE TITLE
Should updated quantity mean re-reviewing a reportback?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4225]
Currently I believe a User can update their Reportback Quantity to something outrageous after it's been reviewed.

Do Reportbacks need to be set to `pending` upon each update?

This is a question that has come up in spec'ing out the Mobile App but is really around the overall Product logic.

cc @marahml @jonuy

**Comment by mikefantini** [comment]
We talked about this when we originally built the reviewer stuff and I honestly can't remember why we didn't go this route, but it makes sense to me to set it to pending after it's been updated.

**Comment by aaronschachter** [comment]
It may have just been for simplicity sake, to get functional for v1.0.

The complexity here is each Reportback Item has its own status (`pending`, `approved`, `promoted`, `excluded`, `flagged`), but currently a Reportback only has a `flagged` integer property, which defaults to 0, and is set to 1 whenever one the Reportback's Items have been flagged.

So we currently don't have a way to set the Reportback itself to `pending`. Two ideas here, but definitely open to others:
-  A hack could be to set the last submitted Reportback Item status to `pending` in order for it to show up in the Reportback Reviewer form... vs setting all Reportback Item statuses to `pending`.. if that makes sense (only review 1 Item instead of 6 (if 6 items were uploaded).  this would not require any changes to the Reviewer form as is.
- Upon any reportback creation or update, the Reportback.flagged property is set to -1, to indicate that it needs to be reviewed.  This would require updating the logic to the Reviewer form, since it currently only returns all reportback items with status == `pending`.

**Comment by mikefantini** [comment]
@aaronschachter nothing has been changed correct?

cc: @namimody @angaither

**Comment by aaronschachter** [comment]
I don't believe anything has been changed.

**Comment by itsjoekent** [comment]
Relevant issue/PR closed https://github.com/DoSomething/dosomething/issues/4625 https://github.com/DoSomething/dosomething/pull/4677
