### ISSUE TITLE
Signup Reason and Signup Reason Label alignment is off on signup data form

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4229]
related to #4202 Signup Reason and Signup Reason Label is still a bit off

![image](https://cloud.githubusercontent.com/assets/6330971/6696393/67fc5880-ccbf-11e4-83aa-dea47f209dc5.png)

![image](https://cloud.githubusercontent.com/assets/6330971/6696416/9debe0b4-ccbf-11e4-8877-60044613b5dd.png)

**Comment by mikefantini** [comment]
see http://staging.beta.dosomething.org/node/1173/custom-settings as an example

**Comment by DFurnes** [comment]
:sob:

**Comment by mikefantini** [comment]
ha sorry @DFurnes
