### ISSUE TITLE
remove social header/copy fields from DoSomething campaign config

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4234]
- [ ] Social header on reportback permalink page.
- [ ] Social copy on reportback permalink page.

cc: @sbsmith86 @lkpttn

**Comment by sbsmith86** [comment]
These lines just need to be removed for frontend cleanup. https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/reportback/reportback-permalink.tpl.php#L65-L68
