### ISSUE TITLE
Signups API endpoint

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4238]
New API endpoint needed for Mobile app prototyping.  required functionality:
- Post a signup with only a UID and a given source. If the given source is a signup entity e.g. `signup/123` then load Signup 123 and find its corresponding campaign nid. Endpoint should create the signup recordfor the given UID and the source's nid.
- GET all signups with a given source. e.g. GET `signups?source=signup/123` but also include the alpha signup 123 within result set

Background:
The mobile app is looking to introduce functionality that allows Users to join a Signup Group. Current spec is as follows:
- An alpha signs up for a campaign and receives an Invite Code. This is their signup sid.
- The alpha invites betas to signup for a campaign using their Invite Code. The beta signup is psoted with the alpha source, `signup/123`.
- All  betas who have signed up with `signup/123` or whose signup ID is actually 123 (the alpha) are provided with an aggratgate view of reportback items and overall quantity

Desired behavior is that there is a view within the mobile app where a user can simply enter an INvite Code (without viewing the campaign it belongs to).  Entering the Invite Code will signup the user for the campaign its associated with, and then present the campaign (with a view of all users who have used the same invite code)

**Comment by aaronschachter** [comment]
Sample request:
`http://dev.dosomething.org:8888/api/v1/signups.json?parameters[source]=signup/54`

Output:
````
[  
   {  
      "sid":"54",
      "uid":"101",
      "nid":"362",
      "timestamp":"1394654653",
      "signup_data_form_timestamp":"1397683873",
      "signup_data_form_response":"1",
      "why_signedup":null,
      "source":null
   },
   {  
      "sid":"55",
      "uid":"106",
      "nid":"362",
      "timestamp":"1394659408",
      "signup_data_form_timestamp":"1397684404",
      "signup_data_form_response":"1",
      "why_signedup":null,
      "source":"signup/54"
   },
   {  
      "sid":"1621",
      "uid":"5",
      "nid":"362",
      "timestamp":"1426706731",
      "signup_data_form_timestamp":null,
      "signup_data_form_response":null,
      "why_signedup":null,
      "source":"signup/54"
   }
]
````

**Comment by aaronschachter** [comment]
@angaither Here is a screenshot of the scene from Mobile App wireframes which may help visualize #4243. Note that the User is not viewing a campaign at all, the code that the user enter will automatically sign the user up for whatever campaign the code is for.

![screen shot 2015-03-18 at 3 28 33 pm](https://cloud.githubusercontent.com/assets/1236811/6720773/8e20162c-cd83-11e4-82a5-cea20885b0c0.png)

**Comment by angaither** [comment]
@aaronschachter ahh, yes that helps
