### ISSUE TITLE
change cta on non-owner permalink if campaign is closed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4261]
example: https://www.dosomething.org/reportback/57008

logic should go something like this:

if campaign is closed, then on non-owner permalink:
- CTA should read "Tackle a campaign to make the world suck less."
- button should read "Explore Campaigns"
- button should link user to /campaigns (instead of signing them up for the campaign)

**Comment by angaither** [comment]
@mikefantini do we need a new variable for this?

**Comment by mikefantini** [comment]
copy variable?

**Comment by angaither** [comment]
that's the type, for the CTA

**Comment by mikefantini** [comment]
ok yeah let's add two:
1. CTA
2. button copy
