### ISSUE TITLE
Refactor Signup by promo code

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4277]
Move logic for Signup by Source (#4243) into the Signup entity save function, to be re-used by them all

**Comment by aaronschachter** [comment]
This GET signups by source can also be completely removed if we add RESTful module #4260

**Comment by angaither** [comment]
@aaronschachter do we need this, we aren't doing invite codes, are we?

**Comment by aaronschachter** [comment]
@jonuy Are we good to start killing all of the signup id / source code we had built for the initial Invites?

**Comment by jonuy** [comment]
We're still sending a `source` (`letsdothis_ios`, `letsdothis_android`), but the stuff where we're using invite ids for groups and such, there are no current plans to bring that back.

**Comment by aaronschachter** [comment]
@angaither So we def don't need this issue, but it'd be good housekeeping to get rid of the code that #4243 introduces -- there's no more need for the [`dosomething_signup_get_target_nid_for_source($source_string)`](https://github.com/DoSomething/phoenix/blob/68aa5497391f7bde7364f9b710136d94fd984c9e/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L945)

**Comment by angaither** [comment]
thanks @aaronschachter I'll create a new issue for removing that code!

**Comment by aaronschachter** [comment]
#5816
