### ISSUE TITLE
Add helper variable for campaign goal

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4281]
New field on the campaign node - the goal of x things y'ed

**Comment by aaronschachter** [comment]
Is this an integer field?

I know we want to build simple -- but there are some other questions that come to mind that it'd be good to document answers for:
- Assuming it's a number, and it changes overtime, do we need to display the new goal and the old goal?
- Does this just get reset if a campaign has a second run?  Does the value need to be copied over to the archived Campaign Run ?

**Comment by angaither** [comment]
Yeah, there's some questions right now if this should be added to the campaign run, instead of the campaign, as each run will have different goals.

**Comment by angaither** [comment]
It's unclear if we want to add this to the campaign, and port it over to the run as it closes, or if each campaign has to start with a run, and I think that's a larger conversion we need to have when the campaign phases work gets ironed out. 
cc @mikefantini

**Comment by aaronschachter** [comment]
Yup was just typing the same thing about the current process (how we don't start with a run).  Just to document: Is current plan to build it as an integer field, storing the total quantity?

**Comment by angaither** [comment]
yes, the plan for now is to have this as an int on the campaign itself. same thing with the progress field
#4282 

I think we will find that this solution won't work with all the phase/timing stuff, but I adding it to the run right now (without a lot of stuff ironed out) would be a bit to over-engineer-y

**Comment by aaronschachter** [comment]
Yup, sounds easy enough to migrate the values or just completely drop the single field later.

**Comment by angaither** [comment]
Actually this is fixed with #4297 since it doesn't need math or overrides
