### ISSUE TITLE
Discussion - building and maintainence of our Drupal API

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4284]
Opening this issue to document the work that's been done in the DS API module thus far, and as a conversation thread for open questions and issues.
## In the beginning

The first use we had for an endpoint was for the Email Digest to access various properties from a Campaign, such as the Cover Image and Call to Action.

Out of the box, the Services module can be used to GET a node, but it returns it like a `node_load`, with Drupal's field arrays of death. We decided to build our own [custom Campaign class](https://github.com/DoSomething/dosomething/blob/v0.4.59/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc#L8) returned by  `dosomething_campaign_load`.  This class could be returned by the API but also used within our own modules as well, so we can always call `$campaign->call_to_action` instead of inconsistently  using different ways to skin a cat: e.g. `field_call_to_action[LANGUAGE_NONE][0]['value']` or calling the an Entity Metadata Wrapper

I had considered using the [Services Entity](https://www.drupal.org/project/services_entity) module, but at the time, it seemed more convenient for us to just have total control over the object and endpoint instead of massaging the output that Services Entity gives you out of the box.  This module and both regular Services still don't provide different endpoints per node type, everything is the node resource.  Hence [this line](https://github.com/DoSomething/dosomething/blob/v0.4.59/lib/modules/dosomething/dosomething_api/dosomething_api.module#L21).  So if you want custom endpoints by node type, you still need to write custom code.
## Current state

So, [custom code we did](https://github.com/dosomething/dosomething/wiki/api).  I wasn't concerned with making things conform to any API standards, as we weren't using the API in production much except for the Digest, some lobby dashboard things.  

However, we do currently use this API for some business critical functionality:
- GET `campaigns/:nid` -- get Campaign properties for Email Digest
- POST  `campaigns/:nid/reportback` -- creates a Reportback entity for a given campaign, used by SMS. Accepts a `file_url` parameter which gets the contents of the given `file_url`, creates a Drupal File, a Reportback Entity, and then a Reportback File for the newly created Reportback and File
- POST `users` -- used by Message Broker User Imports to create accounts
- POST `auth/login` -- used by apps which require admin access (SMS Reportback, Member Counter)
- POST `system/set_variable` -- Drupal default Services module used by Member Counter
- GET `campaigns/:nid/gallery` -- Returns Reportback Items and relevant joined User/Reportback/Campaign data, used by the Campaign Action page
- POST `users/get_member_count` -- Returns total number of Members. This is essentially just a `variable_get`. Used by Email Digest to display total # of members in footer

Not included as business critical (but does currently consume API)
- Reportback Reviewer iOS app:
  - POST `reportback_files/:fid/review`
  - GET `terms`
  - GET `terms/:tid/inbox`
- Lobby dashboard
  - GET `campaigns` (Retrieves title, image, and live signup count variable)
## What's wrong?

Why are you typing all of this?  Well, our API isn't exactly best practices, it's been a bit more of "let's get this out the door."

Also, writing custom endpoints especially for a GET `campaigns` where we have multiple fields to query by is a mess, because you're writing the code for a join based on whatever parameters are sent to you.  The function that handles all the Reportback Items GET is [a beast](https://github.com/DoSomething/dosomething/blob/v0.4.59/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L954), as it joins on numerous tables to bring back the relevant data we want.

Endpoints we need for the mobile app that don't exist:
- GET a User, UPDATE a User -- Adding more custom code to avoid Drupal field arrays seems gross here
- GET campaigns by various fields -- Again, creating a complex join query based on whatever parameters we want to pass in order to define the output/fields also is gross

Also, lots of chat about proper restful API standards. (https://github.com/DoSomething/api/pull/1, https://gist.github.com/weerd/40328cb6205c2de82db4)
## Possible Solutions
- Continue writing custom endpoints, and cleanup where we feel necessary.
- Use contrib modules. Can revisit Services Entity, maybe [Services Views](https://www.drupal.org/project/services_views), or work on [getting RESTful to work](https://github.com/DoSomething/dosomething/pull/4260,) for us.
- Route to SOLR for GET queries to allow querying based on various fields -- not thrilled about this as it adds extra complexity of configuring SOLR to developing these endpoints.

**Comment by aaronschachter** [comment]
@drewish here are the modules currently in our mix: https://github.com/DoSomething/dosomething/blob/dev/lib/profiles/dosomething/drupal-org.make

**Comment by drewish** [comment]
> `POST system/set_variable` -- Drupal default Services module used by Member Counter

Makes me nervous. I'm hoping it's limited to a specific set of variables. Otherwise it seems like it could be a  beg deal security wise.

**Comment by aaronschachter** [comment]
The default resource does check for access to set variables.  But we're only using this specifically for the member counter variable, which is an app that @deadlybutter built to update the live member count on the site. We'd need to add some custom code in order to limit the specific variables.

**Comment by itsjoekent** [comment]
(for reference) the reason we have to set the member count variable on Drupal is because the member count is a mix of both web signups and mobile signups. Drupal doesn't know about mobile signups so we have to tell it what the combined total is.

**Comment by aaronschachter** [comment]
We're sticking with custom Services endpoints.
