### ISSUE TITLE
& isn't showing properly in captions

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4286]
https://trello.com/c/s2PgyHlH

earliest we're able to confirm as working was 3/13. seems to have broken shortly after that

Hilary estimates about 15% of reportbacks are using this for Comeback Clothes and it would look good for sponsor to be able to promote these.

**Comment by mikefantini** [comment]
potentially related to https://github.com/DoSomething/dosomething/issues/3704

**Comment by mikefantini** [comment]
http://staging.beta.dosomething.org/reportback/676?fid=2684 confirms that apostrophes are working, but & seems to be causing issues.

not sure about other special characters

**Comment by angaither** [comment]
Refs #4098

**Comment by angaither** [comment]
@sergii-tkachenko @aaronschachter I've fixed (locally) this in the permalink by using `filter_xss` instead

@mikefantini are there other places this is broken other than the permalink right now?

**Comment by sergiitk** [comment]
@angaither Sounds good.

**Comment by mikefantini** [comment]
sorry @angaither I put this on the pr but can you check if it's breaking in the gallery as well (showcase + step 4)?
