### ISSUE TITLE
Add signup count to pitch page

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4288]
Add "Join [signup_count] people doing this" as the CTA above the signup button on the bottom of the pitch page. Allow optimizely to target the CTA so we can show/hide the CTA with social count for testing.

**Comment by angaither** [comment]
Refs #4051

**Comment by sbsmith86** [comment]
@mikefantini this is currently blocked by #4051

**Comment by mikefantini** [comment]
@sbsmith86 this should now be unblocked by #4320

**Comment by sbsmith86** [comment]
Sweet! Thanks guys.

**Comment by sbsmith86** [comment]
@mikefantini the work for this is on staging but you won't see in unless the proper classes have been added to the element. The count is set to be hidden by default. How do you go about testing this? Should I pass on the code Jeff will need for optimizely?

**Comment by sbsmith86** [comment]
Closing. We are moving forward with this in #4364
