### ISSUE TITLE
Homepage member counter error handling

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#4289]
As discussed in #realtime-apps, have a fallback in place that assures that the homepage member counter never shows a count < 1.

**Comment by itsjoekent** [comment]
This is now taken care of before the # reaches Drupal, do we still want a fallback here anyway?

**Comment by barryclark** [comment]
Could you link me to the current error handling that's in place outside of Drupal plz @deadlybutter?

**Comment by itsjoekent** [comment]
https://github.com/DoSomething/DSMemberCounter/blob/master/app.js#L32

**Comment by barryclark** [comment]
That checks that the new member count is greater than the previously set member count (with a 50k margin for error factored in), and only updates it if it's higher. Correct?

If so, yep, close this out.

**Comment by itsjoekent** [comment]
Yep!
