### ISSUE TITLE
Media Options preprocess issue

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#4301]
See on: http://staging.beta.dosomething.org/campaigns/space-jam

The error:
![pasted_image_at_2015_03_27_02_53_pm_1024](https://cloud.githubusercontent.com/assets/583202/6875071/ac878e86-d492-11e4-93eb-54c331ff009f.png)

And the form:
![screen shot 2015-03-27 at 3 05 36 pm](https://cloud.githubusercontent.com/assets/583202/6875082/bda15468-d492-11e4-9c93-b543b4565ebb.png)

**Comment by angaither** [comment]
t-shirts are dead
