### ISSUE TITLE
StatHat coverage for login event

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#4324]
Let's please ping StatHat on (a) every successful login event, and (b) every failed login event. Alerts for huge changes to these will provide quick feedback if something is fishy:
- Bad flood behavior in Drupal
- Hackery
- Evil-ry

**Comment by angaither** [comment]
@mshmsh5000 maybe I'm just dense, but I'm not sure where to hook into to get a failed login event... our validation hooks that run don't give us anything info about whether or not the attempt failed, and the submission handler doesn't run on a failed login event.

**Comment by mshmsh5000** [comment]
Oooh interesting. It's in [user_login_final_validate](https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_login_final_validate/7), but I didn't think about how to hook into it.

**Comment by angaither** [comment]
right, I'm not sure if we need to have a second validation hook that could maybe run after `user_login_final_validate`

**Comment by angaither** [comment]
I think since this isn't possible going to close this me-ouwt
