### ISSUE TITLE
update copy of rb question

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4325]
from "Why is this important to you?" to "Why is this campaign important to you?"

campaigns team has seen some confusion about this when a scholarship is attached to a campaign so we're hoping to make it a bit more specific, plus this subtle copy change will hopefully garner better anecdotes to share externally.

we shouldn't have to change anything on the backend because we're still looking for the same info, just asking in a slightly different way.

cc: @barryclark can you please help assign this?

**Comment by barryclark** [comment]
Would you be able to tackle this one please @sbsmith86?

**Comment by sbsmith86** [comment]
sure thang

**Comment by barryclark** [comment]
Thanks @sbsmith86!
