### ISSUE TITLE
SMS games are showing $1000 scholarship whether there is a scholarship or not

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4328]
http://staging.beta.dosomething.org/campaigns/sms-game-fun-great-success no scholarship on the backend, still shows http://staging.beta.dosomething.org/node/1199/edit

http://staging.beta.dosomething.org/campaigns/sms-campaign scholarship is $400 but still showing $1000 on frontend http://staging.beta.dosomething.org/node/1269/edit

rule: 
- if incentive is filled out display "win a [amount] scholarship!"
- if incentive is null, don't display any message

**Comment by barryclark** [comment]
Another one it'd be amazingness if you could tackle @sbsmith86. Thank you!

**Comment by mikefantini** [comment]
@sbsmith86 hopefully this is a quickie we can get into tomorrow's deploy? we currently have an SMS game on prod that shows a scholarship but doesn't really have one, which is pretty crummy.

**Comment by sbsmith86** [comment]
@mikefantini sure, i'll hop on it first thing!
