### ISSUE TITLE
display numeric progress towards goal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4330]
related to #4288, it would be great to display the numerical progress towards the goal that @angaither has been working on somewhere on the action page so we can easily test on staging.

this would need to be feature flagged because obviously we don't want this showing up yet on prod, but it would be awesome if you output this number somewhere on the action page (no preference, really wherever is easiest for you to add and remove).

@angaither if there are any other details you think @sbsmith86 needs for this that would be awesome

**Comment by angaither** [comment]
@sbsmith86 you can grab these for each campaign from `dosomething_helpers_get_variable('node', $nid, 'sum_rb_quanity');`
