### ISSUE TITLE
tumblr dialogue never opens up on permalink

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4337]
![image](https://cloud.githubusercontent.com/assets/6330971/6973817/77396272-d95b-11e4-8919-cc3360ff0154.png)

cc: @barryclark can you please assign this out? not sure if it's fender or bender task

**Comment by barryclark** [comment]
You can just shoot these over to @sbsmith86, @mikefantini. Totally her jam after working on all of the permalink stuffs.
