### ISSUE TITLE
Campaign headers are "dull"

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#4339]
Via Kim in Slack:

> Hey team, I've been realizing for a while that whenever photos are uploaded the colors get a little funky and dull.  Can we play around with our gradient some and bring more life into the our images?

![screen_shot_2015-04-02_at_4 34 03_pm](https://cloud.githubusercontent.com/assets/583202/6974318/b341501e-d95f-11e4-91a2-2f7e70348750.png)

My thoughts are that it's a combination of too strong of a gradient overlay & maybe Drupal dropping the color profile or some other sort of image processing issue.

**Comment by angaither** [comment]
darkness is better for the soul
