### ISSUE TITLE
secondary sign up button isn't showing up on pitch for logged in users

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4349]
![image](https://cloud.githubusercontent.com/assets/6330971/7008850/141d67a4-dc64-11e4-989b-97f3f270e95c.png)

it is working for anonymous users
![image](https://cloud.githubusercontent.com/assets/6330971/7008865/29a0a7a8-dc64-11e4-8ec8-e7bd8628914d.png)

**Comment by sbsmith86** [comment]
@angaither Would you have any insight on this one? I can't seem to hunt down where this is failing. The `$signup_button_secondary` variable is on the page and set, but doesn't display for logged in users.

**Comment by angaither** [comment]
@sbsmith86 I can take a look

**Comment by angaither** [comment]
@sbsmith86 something strange is going on here, if you remove one of the signup buttons the other one will print, but it doesn't render both for logged in users....

**Comment by sbsmith86** [comment]
@angaither yea this is really weird! I `dpm()` the `$signup_button_secondary` and the variable is there, and populated with the correct markup. But it isn't actually printing on the page. 

I was looking into [this function](https://github.com/DoSomething/dosomething/blob/c6a65322315f3d8760ab10d77fd181c9210184d8/lib/modules/dosomething/dosomething_signup/dosomething_signup.theme.inc#L56-L66) and it seems the only place we are taking into consideration user state. 

If I do just a plain `print drupal_get_form()` on the secondary sign up form, directly in the template, then that works.

**Comment by angaither** [comment]
even stranger, if you make the call to print the buttons like this

```
print render($vars['signup_button_primary']);
print render($vars['signup_button_secondary']);
```

from within `dosomething_campaign_preprocess_node` they both work

**Comment by sbsmith86** [comment]
agh. yea I'm stumped. Also, if I inspect the page the `<form></form>` tag is on the page with the id and everything, but the `div` inside of it is completely empty.

**Comment by angaither** [comment]
what are this
