### ISSUE TITLE
Debugging locally 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4352]
This should be easier, maybe the [Whoops package](https://www.drupal.org/project/whoops_error_handler) would be useful

**Comment by sergiitk** [comment]
I can provide XDebug with all related settings to the Vagrant box.

**Comment by angaither** [comment]
Would everyone have to be on an IDE for that to work?

**Comment by sergiitk** [comment]
It both prettifies `var_dump()` and errors output and provides remote debugging using anything that implements DBGp protocol (including Sublime Text and even vim):
http://xdebug.org/docs/

**Comment by angaither** [comment]
Yeah, so this whoops page is a bit different, instead of a WSOD or php error, you would see a stack trace of all the functions called and variables when something dies.

**Comment by sergiitk** [comment]
Oh, should I assign this to myself and include XDebug to the new box?

**Comment by angaither** [comment]
sure, it's not an urgent matter, but it's something we should start thinking about, how we can make development a little easier

**Comment by sergiitk** [comment]
Images for the Wiki:
https://github.com/DoSomething/dosomething/wiki/Debugging-with-Xdebug

![image](https://cloud.githubusercontent.com/assets/672669/7124255/4cd5ab2a-e230-11e4-96a0-6e024eda5e72.png)
![image](https://cloud.githubusercontent.com/assets/672669/7124316/a16f922c-e230-11e4-9b0c-86e29b7a2cfe.png)
![image](https://cloud.githubusercontent.com/assets/672669/7124710/e56e2dd2-e233-11e4-95da-9c97f291d828.png)
![image](https://cloud.githubusercontent.com/assets/672669/7124751/452f5f34-e234-11e4-9ccc-2d80d9bb0a5f.png)
