### ISSUE TITLE
Optimizely A/B/C/D tests on pitch page

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4364]
Set up pitch page to work for 4 different optimizely tests. 
- [x] Persistent nav with sign up count cta
- [x] Persistent nav with secondary cta
- [x] Current implementation with sign up count cta
- [x] Current implementation with secondary cta

cc @mikefantini @lkpttn

**Comment by sbsmith86** [comment]
Here is the code needed to run the optimizely tests. @mikefantini 

### Current Implentation - with secondary cta

Do nothing! 

### Current Implementation - with count

`jQuery(".campaign--pitch").find(".cta").removeClass("optimizely-hide-count").addClass("optimizely-show-count");`

### Persistent Nav - secondary cta

`jQuery(".campaign--pitch").addClass("optimizely-persistent");`

### Persistent Nav - with count

`jQuery(".campaign--pitch").addClass("optimizely-persistent").find(".cta").removeClass("optimizely-hide-count").addClass("optimizely-show-count");`

**Comment by sbsmith86** [comment]
Going to close this now, since testing has been done.

**Comment by DFurnes** [comment]
Should we make an issue to remove the Optimizely classes now that tests are over?

**Comment by sbsmith86** [comment]
@DFurnes  Hmm not sure if testing is done, I should have been more clear. Closing this issue because the tests have been set up. 

@mikefantini are we done with these tests? If so, I can create the issue to clean up the optimizely work.

**Comment by DFurnes** [comment]
Oh herpa derp. :grimacing:

**Comment by mikefantini** [comment]
@sbsmith86 @DFurnes tests are still running. We should have results by early next week and then I'll create an issue for cleanup at that time.

**Comment by DFurnes** [comment]
Sounds good!
