### ISSUE TITLE
Shower songs reportbacks are in wrong camapaign

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4368]
There was a keyword collsion on MobileCommons and reportbacks from shower songs are displaying on the suspended for what - create page.

they need to be migrated over to the correct campaign

`node/5234/rb`

**Comment by angaither** [comment]
Aylsha sent me a CSV of the people who submitted reportbacks to the wrong nid, however I can't seem to find the drupal users that match these numbers

the query that needs to happen would look something like this

```
select u.uid, u.mail, rb.rbid
from users u
inner join dosomething_reportback rb on u.uid = rb.uid
where u.mail in (array of numbers)
```

then with those reportbacks update `rb.nid` from `5234`(suspended for what - create) to `3590` (shower songs)

@jonuy

**Comment by angaither** [comment]
Ok, got the reportbacks that were updated, and imported them as a temp table
I'm going to test run this on QA, then on prod

```
update dosomething_reportback rb
inner join users u on u.uid = rb.uid
inner join _shower_songs s on s.phone_number = u.mail
set rb.nid = 3590
where rb.nid = 5234;
```

**Comment by jonuy** [comment]
That seems about right. Thanks :bow:

**Comment by angaither** [comment]
waiting to test this on QA... the backups haven't been running for a bit so this data wasn't there

**Comment by angaither** [comment]
coool cool cooool, this is fixed now
