### ISSUE TITLE
Potentially switch URL building function in Reportback API

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4384]
Based on @sergii-tkachenko suggestion, might be best to use [drupal_http_build_query](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_build_query/7) to build out URLs in Reportbacks API.

**Comment by angaither** [comment]
nah 
![](http://rack.0.mshcdn.com/media/ZgkyMDEzLzA1LzA2L2NlL2RvbmVoZXJlLjkwOTI3LmdpZgpwCXRodW1iCTEyMDB4OTYwMD4/71ccdc11/f22/donehere.gif)

**Comment by weerd** [comment]
LOL
