### ISSUE TITLE
Release v0.4.86 broke reportback files uploading

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4387]
It very looks like it was related to #4385.
My theory is that rogue php5-fpm server was looking into wrong release directory. New release included new definition of reportback files:

https://github.com/DoSomething/dosomething/compare/v0.4.67...v0.4.86#diff-d177d4f7f20f09dc9807bc79a9998371R3
So it looks like the DB has been changed, but old code was running, ergo the following error:

> `Apr 15 19:17:27 beta-web4 drupal: https://www.dosomething.org|1429125447|dosomething_reportback|72.2.120.4|https://www.dosomething.org/api/v1/campaigns/5140/reportback%7C%7C2069679%7C%7Cexception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'If you don't like being bullied in person, imagine, being bullied online? Where you can see a person's hurtful words on your pho' for column 'quantity' at row 1' in /var/www/beta.dosomething.org/releases/20150415185303/html/includes/database/database.inc:2171#012Stack trace:#012#0 /var/www/beta.dosomething.org/releases/20150415185303/html/includes/database/database.inc(2171): PDOStatement->execute(Array)#012#1 /var/www/beta.dosomething.org/releases/20150415185303/html/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)#012#2 /var/www/beta.dosomething.org/releases/20150415185303/html/includes/database/mysql/query.inc(36): DatabaseConnection->query('INSERT INTO {do...', Array, Array)#012#3 /var/www/beta.dosomething.org/releases/20150415185303/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback.inc(166): InsertQuery_mysql->execute()#012#4 /var/www/beta.dosomething.org/releases/20150415185303/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback.inc(328): ReportbackEntity->insertLog('insert')#012#5 /var/www/beta.dosomething.org/releases/20150415185303/html/profiles/dosomething/modules/contrib/entity/includes/entity.inc(215): ReportbackEntityController->save(Object(ReportbackEntity))#012#6 /var/www/beta.dosomething.org/releases/20150415185303/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module(623): Entity->save()#012#7 /var/www/beta.dosomething.org/releases/20150415185303/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc(270): dosomething_reportback_save(Array)#012#8 [internal function]: _campaign_resource_reportback('5140', Array)#012#9 /var/www/beta.dosomething.org/releases/20150415185303/html/profiles/dosomething/modules/contrib/services/includes/services.runtime.inc(196): call_user_func_array('_campaign_resou...', Array)#012#10 /var/www/beta.dosomething.org/releases/20150415185303/html/profiles/dosomething/modules/contrib/services/includes/services.runtime.inc(106): _services_controller_execute_internals(Array, Array, Array)#012#11 /var/www/beta.dosomething.org/releases/20150415185303/html/profiles/dosomething/modules/contrib/services/servers/rest_server/includes/RESTServer.inc(45): services_controller_execute(Array, Array)#012#12 /var/www/beta.dosomething.org/releases/20150415185303/html/profiles/dosomething/modules/contrib/services/servers/rest_server/rest_server.module(39): RESTServer->handle()#012#13 [internal function]: rest_server_server()#012#14 /var/www/beta.dosomething.org/releases/20150415185303/html/profiles/dosomething/modules/contrib/services/services.module(389): call_user_func('rest_server_ser...')#012#15 [internal function]: services_endpoint_callback('drupalapi', 'campaigns', '5140', 'reportback')#012#16 /var/www/beta.dosomething.org/releases/20150415185303/html/includes/menu.inc(517): call_user_func_array('services_endpoi...', Array)#012#17 /var/www/beta.dosomething.org/releases/20150415185303/html/index.php(21): menu_execute_active_handler()#012#18 {main}`

My point is next prod deployment shouldn't break reportbacks. This also explains why everything works well on staging.

**Comment by sergiitk** [comment]
CC @apatheticslacker

**Comment by angaither** [comment]
closing, I don't think this is an issue anymore cc @sergii-tkachenko
