### ISSUE TITLE
signup count getting overwritten

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4394]
For campaigns with SMS signups, we need to be able to manually add in those SMS signups for now.

When I first put the "real" signup number in, it displays properly. But then web signups should add to this higher number as they come in (updated intermittently). However this number is just getting overwritten with the web signup updates.

i.e. on https://beta.dosomething.org/node/362/custom-settings I changed it from 9302 to 45321 and then later it went to 9304.

**Comment by angaither** [comment]
@mikefantini I haven't been able to recreate this locally

**Comment by angaither** [comment]
The only thing I can think that's causing this is strange DB replication? 
Once the number is set it won't query the database to get the signup count, so maybe that number is getting set in one DB & not migrating to the other DBs...? This would also explain why I can't replicate this locally...

**Comment by angaither** [comment]
For context, this is a `dosomething_helpers` variable `signup_count`

**Comment by angaither** [comment]
@blisteringherb [this](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_signup/includes/dosomething_signup.cron.inc) is the cron function that runs every hour to update the number and [here's the code](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.variable.inc#L170-L182) that updates the signup count on the actual form

**Comment by blisteringherb** [comment]
No queriers are directed to the slave DB so this isn't related to replication.  Is there any way to just run a query to get all of the signups on cron rather than do the incrementing?  Or can you do that query less frequently as a reconciliation to make sure the number is correct?

**Comment by angaither** [comment]
@blisteringherb yeah, cron could run the live count, but it's another one of those issues where we need to include mobile signups, which are not in the drupal database. so we need it to live update, but also be overridden. the classic problem.

**Comment by mikefantini** [comment]
@angaither: one suggestion from @mshmsh5000 was what if we create a new field just for SMS signups. This field would never get overwritten, it would just be a field for an editor to put in SMS signups number once (maybe a few times if an influencer sends a bunch of signups).

We then could take the web signups number that is constantly being updated by cron and add this updating number to the number in the SMS signups field; and so all we would ever display is the sum of these two fields.

Thoughts?

**Comment by angaither** [comment]
:+1:

**Comment by mshmsh5000** [comment]
Also talked to @angaither about this, and we agree it's a puzzle we want to solve. But not top priority, if only because the timing tests are getting put off for a month.

**Comment by mikefantini** [comment]
sounds good @mshmsh5000 @angaither - going this route will let us get up the # of ppl doing tests that are all set and currently blocked by this
