### ISSUE TITLE
placeholder DS image is showing as broken on search

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4398]
![image](https://cloud.githubusercontent.com/assets/6330971/7241542/9c83f5b2-e787-11e4-86ed-b8bc98483ef1.png)

@barryclark can you please assign this out?

**Comment by barryclark** [comment]
@blisteringherb Wanna take a peek first and let me know if it's not yours?

cc @weerd @DFurnes in case they might have some insight into this problem.

**Comment by blisteringherb** [comment]
It looks like just that one 11 facts image is missing.  I"m checking now to see why it's not there.

**Comment by barryclark** [comment]
Cheers @blisteringherb!

**Comment by mikefantini** [comment]
@blisteringherb it's a placeholder image we use for all static content and facts pages.

@sbsmith86 may know more as I believe she actually set it up when we rebooted our search design.

**Comment by sbsmith86** [comment]
We pull in a default image (DS logo) if no image is found for the result. [Code doing that is here](https://github.com/DoSomething/dosomething/blob/54e3ff77bea23419d2d2c5ef84ca2fd557bb0fed/lib/themes/dosomething/paraneue_dosomething/includes/patterns.inc#L26-L42) Maybe that is a bad path? Is there a better way to pull in the default image?

@mikefantini @barryclark @blisteringherb

**Comment by DFurnes** [comment]
Oh, that should be pointing to `...node_modules/dosomething-neue/dist/assets/images/apple-touch-icon-precomposed.png`. Sorry, I missed that one when we moved vendor assets from Bower to NPM. :grimacing: 

You can use `NEUE_ASSET_PATH` as a helper for the Neue path in Drupal.

**Comment by sbsmith86** [comment]
@DFurnes AHhh gotcha. I can handle this fix! @mikefantini

**Comment by mikefantini** [comment]
thanks guys!
