### ISSUE TITLE
Load guzzle with composer

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4411]

**Comment by sergiitk** [comment]
Hey @angaither. I don't think this is good idea for now to use Guzzle. I love it myself, but it [requires](http://docs.guzzlephp.org/en/latest/overview.html#installation) PHP > 5.4.0 and one of our webheads is still 5.3.
I think we should stick with `drupal_http_request()` for now.

As an alternative, we have [`http_client`](https://www.drupal.org/project/http_client) installed (or maybe it's just downloaded for the US).
I'll find you few usage examples.

**Comment by sergiitk** [comment]
Here it is:
- https://github.com/DoSomething/dosomething/blob/8853999ec664c142c5ae76419a996a6c66bafe4b/lib/modules/dosomething/dosomething_uk/includes/dosomething_uk_sso_controller.inc#L555-L564
- https://github.com/DoSomething/dosomething/blob/8853999ec664c142c5ae76419a996a6c66bafe4b/lib/modules/dosomething/dosomething_uk/includes/dosomething_uk_sso_controller.inc#L274-L287

**Comment by angaither** [comment]
ohhh huge bummer, ok.
can we keep this on the backlog as something we want to do in the future?

**Comment by sergiitk** [comment]
Sure!

**Comment by mshmsh5000** [comment]
PHP version will be a non-issue once we're migrated to AWS next month. So let's keep this warm!

**Comment by jonuy** [comment]
@sergii-tkachenko @angaither As a follow up to the meeting we just had, this does now sound like an issue we can actively work on again.
