### ISSUE TITLE
GET requests to https://www.dosomething.org/api/v1/users.json?parameters[email]= failing

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4426]
When `mbc-digest-email` makes requests to: `https://www.dosomething.org/api/v1/users.json?parameters[email]=` to lookup the Drupal UID by email the returned results are status code "0" or "200" In the case where the email address is not found. 

The Drupal UID is needed to generate the Unsubscription link for each users digest message. The md5 hash value that includes the Drupal UID is used in generating the link. When this requests fails the digest message cannot be sent to the email address.
#### Examples of failed requests that return "0":
- https://www.dosomething.org/api/v1/users.json?parameters[email]=zombiemen3%40gmail.com
- https://www.dosomething.org/api/v1/users.json?parameters[email]=zcobb125%40gmail.com
- https://www.dosomething.org/api/v1/users.json?parameters[email]=zdaffner%40icloud.com
#### Examples of successful requests for email addresses that do not exist that return "200":
- https://www.dosomething.org/api/v1/users.json?parameters[email]=zeldballew%40gmail.com
- https://www.dosomething.org/api/v1/users.json?parameters[email]=zdaffner%40icloud.com

It's possible to run the script from my local and get more successful lookups with only a few errors. When the script runs from the `rabbit2` server all of the requests fail with "0" or "200" responses detailed above.

**Update**: There appears to be some kind of flood / throttling at work as smaller / less frequent batches seem to have a higher rate of successful responses. The problem is the digest runs weekly that needs to process 500,000 users.

**Comment by deezone** [comment]
@angaither Not sure if you're the right person to poke about this. With @aaronschachter away I'm assuming you're the "Master of Drupal" these days?

At any rate, thoughts ^^ ?

**Comment by angaither** [comment]
@DeeZone what's the expected response with the users above? 
from what I'm seeing here, the top two return a user id
`https://www.dosomething.org/api/v1/users.json?parameters[email]=zombiemen3%40gmail.com
https://www.dosomething.org/api/v1/users.json?parameters[email]=zcobb125%40gmail.com`

and the others do not
is that expected? 

Is this question about rate limits causing a failure, or about lookups failing?

**Comment by deezone** [comment]
@angaither Agreed, 
- https://www.dosomething.org/api/v1/users.json?parameters[email]=zombiemen3%40gmail.com
  returns the expect UID when it's working **but** when the "throttling" kicks in the following **error response** is returned:

```
Response: 0
CURLINFO_HTTP_CODE: 0
```

The result is small batches of requests work but any kind of volume (over 100 with the same auth key) results in the error response detailed above. Expected is:

```
Response: 
[
    {
        "uid": "x"
    }
]
CURLINFO_HTTP_CODE: 200
```

In the case where the user is not found by the email address: https://www.dosomething.org/api/v1/users.json?parameters[email]=zeldballew%40gmail.com the response is:

```
Response: 0
CURLINFO_HTTP_CODE: 200
```

which works great.

The problem is the error response when volume requests are made. I remember @aaronschachter mentioning applying some kind of throttling to prevent flooding the Drupal app. I'm wondering if in fact throttling is happening and if it can be increased?

**Comment by angaither** [comment]
@DeeZone at first glance I don't see anything in the `dosomething_api` module that limits activity. It's certainly possible it's hidden somewhere though, I'll keep looking around

**Comment by deezone** [comment]
Thanks!

**Comment by angaither** [comment]
@weerd do you have any ideas on this one? you've been in the services weeds for a bit... do you know about any event throttling?

**Comment by jonuy** [comment]
Is there monitoring like New Relic on the DS web app or message broker that we can check for when the digest script is running? I'd be interested to see if any patterns show up there that could shed more light on what's going on here.

**Comment by angaither** [comment]
@jonuy https://rpm.newrelic.com/accounts/108038/applications/3268309/traced_errors?search[name]=https%3A%2F%2Fwww.dosomething.org%2Fapi%2Fv1%2Fusers.json%3Fparameters%5Bemail%5D%3D&search[sort_by]=count&search[type]=all&utf8=%E2%9C%93

there's spikes in there but now real information....

**Comment by angaither** [comment]
oy, the spikes are just requests, but the error rate is low... less than 1%

**Comment by angaither** [comment]
@DeeZone I don't see anything in the UI or anywhere in the code that suggests we are rate limiting requests.

**Comment by deezone** [comment]
@angaither In that case the Drupal API is throwing plain old error / empty responses - random but easily reproduced. I can show it in action if that helps?
