### ISSUE TITLE
"Please upload an image" error message

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4427]
follow these steps to reproduce:
- upload image
- click on change photo in modal
- close file select dialogue box without selecting a new file
- finish report back process 

![image](https://cloud.githubusercontent.com/assets/6330971/7349497/8be71992-ecc7-11e4-9778-aeae688be8f9.png)

**Comment by namimody** [comment]
@mikefantini do you know if this is still a bug? thanks!
