### ISSUE TITLE
no verification message on password reset flow

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4429]
flow works properly on staging, but on production you never get the "If your email address exists in our database, you will receive a password recovery link at your email address in a few minutes."

Lots I'd like to change to the pw rest flow, but at the very least let's 1. get this message showing and 2. tweak the language to read "If we have an account with that email address, we'll send you a password recovery link in a few minutes."

@DFurnes would this guy be you?

**Comment by DFurnes** [comment]
Not something I've worked with. I was under the impression this interface was just stock Drupal functionality?

/cc @angaither @DeeZone

**Comment by angaither** [comment]
@mikefantini yeah I think we override the text here in the `login > password forgot section` & nothing is set in production
https://www.dosomething.org/admin/config/dosomething/dosomething_user

**Comment by deezone** [comment]
@mikefantini @angaither Please confirm that the action that triggers this messaging also triggers a password reset transactional email. My understanding is that only the "Reset Password" link in the user login form triggers this message. Are you looking for additional events to trigger sending this message as well as display the message you're describing?

**Comment by angaither** [comment]
@DeeZone correct, I think @mikefantini is talking about a flash message on the drupal app, not in the actual email here

**Comment by mikefantini** [comment]
@DeeZone yup just talking about the web experience. Everything with the email seems to be working fine.

@angaither hmmm it makes sense that this config form would do the trick, but two things to keep in mind before I put the copy in there:
1. this field is not set on staging, but the flash message still appears properly on staging
2. also the checkboxes in the registration group scare me. also not set on staging (or prod), but like obviously we should be collecting email and SMS. I just want to make sure that adjusting the pw reset logic doesn't like have us stop collecting emails and SMS on registration. I can try to edit language first on staging, but not sure how to verify if this borks what info we're collecting when users register. Unless "collect opt-in email" and "collect opt-in SMS" mean something different, like giving the user the choice to actively opt-in to emails/sms when registering.

![image](https://cloud.githubusercontent.com/assets/6330971/7372018/670bb314-ed92-11e4-9081-3e3bd8450da4.png)

**Comment by DFurnes** [comment]
@mikefantini I believe those are settings to show opt-in checkboxes for each type of communication, which are required for our UK affiliates because of SMS laws over there.

**Comment by mikefantini** [comment]
ok sweet thought that might be it, but just wanted to be sure before we ya know stopped collecting emails/sms.

alright I'll try putting copy in that field in staging and see what happens

**Comment by mikefantini** [comment]
sweet all fixed. thanks all!
