### ISSUE TITLE
site name won't read member count token

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4439]
ideally using [site:member-count] in this instance would pull in the actual member count rounded to the hundred thousands digit (i.e. like it does on the pitch page footer message)

https://beta.dosomething.org/admin/config/system/site-information

![image](https://cloud.githubusercontent.com/assets/6330971/7434386/7d1e91da-f008-11e4-895f-77eedc8d826f.png)

![image](https://cloud.githubusercontent.com/assets/6330971/7434375/7253be9c-f008-11e4-9b36-1ae52c733111.png)

**Comment by angaither** [comment]
@mikefantini do you want this to say the full number or the "readable" one (3.x million)

**Comment by mikefantini** [comment]
@angaither readable please
