### ISSUE TITLE
Add goal animation fields

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4443]
Add 6 fields to the campaign template that will represent different progress points throughout the life of a campaign. There will be 5 animations for each progress point, and a 6th for a final animation if the goal is met or surpassed. 
- Fields can be named "Animation 1, Animation 2, Animation 3, Animation 4, Animation 5, Animation 6"
- They should be able to accept gif, and .mov file types.

**Comment by aaronschachter** [comment]
@sbsmith86 Couldn't this be a single multi-value file field? e.g. `field_goal_animations` ?

**Comment by sbsmith86** [comment]
@aaronschachter sure. I wasn't sure how to best word that, but if that makes more sense on the backend, let's do that. is there a way to limit the number of things people can add?

**Comment by aaronschachter** [comment]
@sbsmith86 There is, you can make it a fixed field size of 6. I'm happy to walk through it with you if you'd like. 

Quick question though, are these files unique to each campaign? Or are they to be used for every campaign? If it's the latter, we'd want to store these as system variables vs on the campaign template...

**Comment by sbsmith86** [comment]
Hmm @mikefantini thoughts on that question ^^ will animations be campaign specific or global?

**Comment by mikefantini** [comment]
they'll be global. but again, we'll most likely have at least one variation for the test, but this will still be for all campaigns we test, not campaign specific.

@sbsmith86 @aaronschachter

**Comment by aaronschachter** [comment]
@sbsmith86 We'll want to store each file as a system variable then, instead of fields on the Campaign node.  The Campaign config page seems like a good spot to put them: http://dev.dosomething.org:8888/admin/config/dosomething/dosomething_campaign.

@mikefantini The variation can be done via Optimizely. We could upload the alternative files via `admin/content/file`, and swap out the file paths in Optimizely (instead of creating a whole set of new variables for the variation)

**Comment by mikefantini** [comment]
sounds great thanks @aaronschachter. Seems to make it easier for everyone this way.

**Comment by mikefantini** [comment]
also @sbsmith86 is this issue for you or @angaither?

**Comment by sbsmith86** [comment]
@mikefantini I will take it.

**Comment by mikefantini** [comment]
sweet thanks @sbsmith86
