### ISSUE TITLE
Goal animation logic 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4445]
Add logic on the backend that delivers one animation file to the campaign template based on goal progress. 

If current progress is: 
- Between 0 and 20% of goal, use animation 1
- Between 21% and 40% of goal, use animation 2
- Between 41% and 60% of goal, use animation 3
- Between 61% and 80% of goal, use animation 4
- Between 81% and 99% of goal, use animation 5
- Goal is met, use animation 6

**Comment by mikefantini** [comment]
@sbsmith86 looks good to me!

**Comment by angaither** [comment]
no longer doing this with animations
