### ISSUE TITLE
Reportback count override

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4453]
With #4396 we lost the ability to override reportback counts
Because of campaigns with 3rd party sponsors, we need this, for now, going to build it like #4320 where the helper text displays the total count in the database, but you can add extra values and the two will be added together for the sum

**Comment by mikefantini** [comment]
For this can we have the title of the field be "Progress Update" and have the help text read "Total approved qnty is: x. Subtract this # from the # our partner provided, and enter the difference here. I.e. if partner said 1,000 and the total approved qnty is 100, enter 900."
