### ISSUE TITLE
Only count non-flagged reportbacks

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4454]
Totally forgot to add this `AND` to the [query](https://github.com/DoSomething/dosomething/blob/b7b36a5c6364b71feab18d88800af88b50f61480/lib/modules/dosomething/dosomething_signup/includes/dosomething_signup.cron.inc)
Currently counting all reportbacks, approved or not :grimacing:

**Comment by mikefantini** [comment]
@angaither this should count reportbacks that are approved, excluded, or promoted.

So all reportbacks that have a status (i.e. have been reviewed) where that status does not equal flagged.

**Comment by angaither** [comment]
Actually, excluding flagged things is in the query, but `flagged` defaults to `0`
It should default to `null` first and, then change to `0` once the reportback has been approved (or not)
