### ISSUE TITLE
non-owner permalink title if user first name does not exist

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4455]
If there is no first name attached to the user who submitted a reportback let's have the top of the non-owner permalink page read "Join DoSomething.org" instead of "Join [user:first_name] and DoSomething.org"

![image](https://cloud.githubusercontent.com/assets/6330971/7461870/2b999416-f27b-11e4-9a10-bd1e64d679ca.png)

This is a consideration for providing the permalink to users via SMS after they have submitting a reportback via SMS.

cc: @angaither @jonuy @tongxiang 

This work should get done before @tongxiang you push the feature live.

**Comment by angaither** [comment]
@mikefantini uhh, it's a bit strange, because the copy 'And' is set in the cms, can we say join your friend and dosomething?

**Comment by mikefantini** [comment]
right that's what I was afraid of.

Honestly the whole title is kind of weird for this use case because most likely they won't be logged in to the site and the experience will be:
- user texts in rb
- we text user permalink
- user clicks through to their permalink
- page of user's permalink says "Join your friend and DS" even though it's their rb

I think it's fine if I'm a user and it says my name (which should be the predominant use case) but it feels pretty weird if it's "your friend".

But I'm not really sure what else we can really do here.

@jonuy you have any thoughts?

**Comment by angaither** [comment]
@mikefantini yeah I just know there's a lot of people we don't have the name for, since there's a lot of the `[user:field_first_name]` text now. 
We could change it for everyone to just say Join DoSomething.org, but the web peeps would loose the name of the friend then...

**Comment by jonuy** [comment]
I've been trying to think of something else other than "your friend" but nothing better really comes to mind. I actually think the "your friend" copy is ok. Even if the main use case is myself looking at my own permalink, the primary action the page is asking me to do is to share it, right? In which case, it could just come off as the site showing me exactly what my friends would see if I shared with them.
