### ISSUE TITLE
Consider disabling XML Response from Services Module

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4462]
Not sure if the default XML response is used anywhere, but we could consider disabling it within the Services module if it is not used and we can designate the default to be JSON.

![image](https://cloud.githubusercontent.com/assets/105849/7519333/5a56cd02-f4ae-11e4-8561-a66c88d184f8.png)

**Comment by weerd** [comment]
Added this issue as a talking point for us to consider. Low priority but wanted to see if XML response is being used anywhere.

@aaronschachter @angaither @jonuy @mshmsh5000 @drewish @DFurnes

**Comment by aaronschachter** [comment]
I think this should be safe to try at least, there's nothing I can think of.  I know I had to turn on the `x-www-form-url-encoded` to get login auth to work in the iOS Reviewer app with the Services endpoint.

**Comment by jonuy** [comment]
Yea, I think it's safe to try removing the XML response. There's nothing I'm aware of using it.

For Request Parsing, I think we could get rid of `appliation/xml`. The other two should probably stay.

**Comment by weerd** [comment]
Yep yep. That's what I figured. I know `x-www-form-url-encoded` is needed for some like file related things too... but can't remember for sure. But yeah, aiming to toggle off:
- `xml` in Response formatters
- `application/xml` in Request parsing 

Cool cool. When I push up a Features update to toggle on the Kudos endpoint I can do another (or in same PR) to toggle off the above two items.
