### ISSUE TITLE
Return existing signups from campaign sign-up endpoint

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#4465]
If an API client (such as Northstar) tries to use the API to create a signup, and the given user is already signed up for the campaign, the API returns a relatively unhelpful `[ false ]` response.

It would be nice if it returned the existing signup, with either an "already exists" message or a timestamp representing when the original signup was made. In this case, it should probably return `200 Okay` rather than `201 Created`.

References DoSomething/Northstar#95.
/cc @jonuy

**Comment by jonuy** [comment]
It'll also be a good idea with this one to standardize the response from this endpoint. Whether it's a success or failure, the response should come back as an object. And in addition to the `sid` should also come back with the rest of that resource data - at least `uid`, `nid`, `source`, and `timestamp`.

**Comment by angaither** [comment]
doi, replaced with #6118
