### ISSUE TITLE
ImageMagick experiments for drawing problem fact images

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#4471]
Computers can do the work for us.
http://www.imagemagick.org/Usage/draw/#text

![problemfact](https://cloud.githubusercontent.com/assets/1865372/7541280/f66e5542-f581-11e4-86f5-6b2dbc191391.png)
### Size

471x248px
Background: #23B7FB  
### Fonts

Proxima Nova 24pt #FFFFFF
Proxima Nova Bold 16pt  #337D9F
### Margins

20px on all sides.

**Comment by sbsmith86** [comment]
@lkpttn how much space is between 'Make a difference' and the problem statement?

**Comment by aaronschachter** [comment]
Curious, what's the context behind this issue? Why display as an image?

**Comment by sbsmith86** [comment]
@aaronschachter we are creating an image with the problem fact statement that will be used for social sharing.

**Comment by lkpttn** [comment]
@sbsmith86 Sketch says 6 pixels, but the box sizing for the text may be different for Sketch vs ImageMagick.

@aaronschachter We want images to attach to FB posts and such so they show up in people's timelines.

![facebook](https://cloud.githubusercontent.com/assets/1865372/7542831/01d8794c-f58e-11e4-9f5c-3e809fbf2f03.png)

**Comment by aaronschachter** [comment]
For sharing individual facts?  Or these images show up when you share a campaign?

**Comment by lkpttn** [comment]
From the action page, there's a new set of share buttons specifically for sharing the problem statement. We just updated the wiki with the most recent mocks and docs.

https://sites.google.com/a/dosomething.org/dosomethinguxwiki/product-archive/fomo-suite/join-me-shares

**Comment by sbsmith86** [comment]
@lkpttn @mikefantini I wrote a script that creates these images. This is what the images are looking like based on this script. 
![test_image](https://cloud.githubusercontent.com/assets/1700409/7573204/fe6ecb1a-f7f1-11e4-8a1d-c54bfca9a073.jpeg)

**Comment by mikefantini** [comment]
@lkpttn I'll leave this to you and @sbsmith86 to sort out in terms of any adjustments we want to/can make to how this is being displayed

**Comment by lkpttn** [comment]
Only thing I'm seeing is just the lowercase of "make a difference", but I'm sure that's just a string thing. Looks like this is going to work out.
