### ISSUE TITLE
Notify Northstar when a kudos is received

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#4472]
When a user receives a kudos, they will get a push notification about it. Northstar's gonna handle the grunt work of sending the push notifications. On the Drupal end, we'll just need to let Northstar who received a kudos and on what.

There's a bunch of work that still needs to get done on Northstar to support it (see https://github.com/DoSomething/northstar/issues/104), but for Drupal, when a kudos is received I'm thinking it'd eventually make a request like...
- Request: POST to `northstar.dosomething.org/api/v1/notifications`
- body:

```
{
  type: "kudos",
  data: {
    kudos_id: 123,
    reportback_item_id: 456,
    drupal_id: 789
  }
}
```

cc: @weerd

**Comment by aaronschachter** [comment]
Not sure if this is implied --  but I'm assuming all POSTs to Northstar are handled via Message Broker ?

**Comment by jonuy** [comment]
Hm does it have to happen through message broker? Or could some of what Andrea was looking at before with guzzle work?

**Comment by aaronschachter** [comment]
It doesn't have to... but it would keep consistent with how we handle subscriptions to Mailchimp, Mobilecommons, and gives us at least some sort of back-up plan with a queue of requests if the Northstar API happens to go down.  There's also been a long standing issue to use Message Broker for Zendesk tickets too (#1675)

**Comment by jonuy** [comment]
That's fair. And to a separate point you've made elsewhere, if these kudos calls should be coming authenticated through Northstar, then this issue doesn't need to even happen. Northstar will know a kudos has happened because the call came through it. And then notification listener type of code could go in there instead of needing to create a separate `/notifications` endpoint which was my idea here.

**Comment by jonuy** [comment]
This is no longer valid due to the work being done here: https://github.com/DoSomething/northstar/issues/137
