### ISSUE TITLE
sharing problem fact on action page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4475]
Prompt user to share the problem statement on the action page (this prompt should not appear on the pitch page).

Desktop:
![image](https://cloud.githubusercontent.com/assets/6330971/7567580/ee618422-f7cb-11e4-972f-b7b20527fb45.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/6330971/7567589/f9b4192a-f7cb-11e4-96d2-72d61fc4f07a.png)

Let's create a variable, "Problem Fact Share Prompt", on https://beta.dosomething.org/admin/config/dosomething/dosomething_campaign for the copy of the prompt (i.e. "F that, spread the word") so that we can update it if need be without any code deploys.

**Comment by lkpttn** [comment]
![new - action l](https://cloud.githubusercontent.com/assets/1865372/7568613/bbed691a-f7d1-11e4-9df1-6a522482da9a.png)

![gallery - pitch s copy](https://cloud.githubusercontent.com/assets/1865372/7568619/c04d5e34-f7d1-11e4-8485-862a36303d8e.png)

**Comment by lkpttn** [comment]
@sbsmith86 We should also push the FAQs to the right column if there are shares present, to prevent them from stacking up on the left. Furnes was saying in Slack that this is a template thing, so I'm not sure if that is something changed front end or back.

**Comment by aaronschachter** [comment]
@mikefantini Edited description to read "variable", not a "field" -- to help clarify it's not a Drupal field.

**Comment by sbsmith86** [comment]
@lkpttn so when shares are present, the FAQ's should display like they do when there is a video?

Also, what are the rules around when the shares are present/when they are not? If there is a problem fact statement, then shares should be present? Would there ever be a case where there is a problem fact statement and shares should not be there?

**Comment by lkpttn** [comment]
Yeah yeah.

I think the intention is for there to always be share buttons, so the FAQ link will always move over. I don't forsee us rolling this out onto only certain campaigns, it would be site-wide. This could be implemented in the template logic or we could change the rule to always have FAQs on the left side.
