### ISSUE TITLE
problem facts on social

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4476]
- [ ] Facebook 
  ![image](https://cloud.githubusercontent.com/assets/6330971/7567907/c9c15b18-f7cd-11e4-84e0-ca4773fe547c.png)
- [ ] Twitter (note: no image is being shared on Twitter, just the problem fact copy and the link) 
  ![image](https://cloud.githubusercontent.com/assets/6330971/7567879/87e70d50-f7cd-11e4-867d-bd4ab74419a8.png)
- [ ] Tumblr 
  ![image](https://cloud.githubusercontent.com/assets/6330971/7567887/92050026-f7cd-11e4-97c0-240b243ff647.png)

**Comment by sbsmith86** [comment]
@mikefantini For twitter shares, do you know what that `dsorg.us` short url is or how it gets generated?

**Comment by aaronschachter** [comment]
Isn't it bit.ly?

**Comment by mikefantini** [comment]
@sbsmith86 I _think_ twitter will just shorten links itself if the tween goes over 140, so I think we're ok without doing any work on this.

can we build based on this assumption, take a look in staging, and make adjustments if need be?

**Comment by sbsmith86** [comment]
@mikefantini yep! thats fine, just making sure.
