### ISSUE TITLE
Campaign API endpoint -- index fields

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4482]
The campaigns index probably shouldn't return a full view of every campaign... but it definitely needs to return:
- Nid / ID
- Title
- Call to Action
- Cover Image (format?)

**Comment by jonuy** [comment]
It'd also be great to return:
- term_id(s): So if I do a call like `/campaigns?on_mobile_app=1`, we'll know what groups to display the campaign in
- fact_problem
- solution_copy and solution_support

**Comment by aaronschachter** [comment]
One point about the `term_ids` query parameter.

It's currently querying on the `taxonomy_index` table that Drupal core provides, which just maps `nid` to `tid` based on any Taxonomy field.  @uy If a term_ids array was returned based on this table, it would provide tids from all vocabularies which have fields, so Action Type, Hours, Cause, Issue, etc.  

I built the query parameter using `term_ids` as a possibly-temporary thing, to avoid needing to determine whether or not we are using `field_tags` or a new vocabulary/field.  The scenario you're describing may require returning specific Taxonomy fields to make the response more helpful..

**Comment by weerd** [comment]
- [x] nid
- [x] title
- [x] tagline/call_to_action
- [x] active_hours
- [x] cover_image (now with sizes!)
- [x] term_id(s)
- [x] fact_problem (in `facts` array)
- [x] fact_solution (in `facts` array)
- [x] fact_sources (in `facts` array)
- [x] solution_copy (in `solution` array)
- [x] solution_support (in `solution` array)
