### ISSUE TITLE
active tab for SMS Games should display SMS Game layout

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4488]
if a campaign is an SMS Game and the campaign is closed, then the active tab should display as if it were an active SMS game. currently it is displaying an action page as if it were an active campaign

see https://beta.dosomething.org/node/2366 as an example

related to #3220

**Comment by aaronschachter** [comment]
This would seem to be an easy fix, but looking at the [code that determines what template to use](https://github.com/DoSomething/dosomething/blob/v0.4.109/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc) makes it apparent that this same logic is used all over the place to determine which template to use (Action Page, Pitch Page, SMS Template, Closed State). we've made tweaks here that have ended up borking various states -- any changes here would need to be carefully tested for all various templates a Campaign node can display.

**Comment by aaronschachter** [comment]
The fix should be that we just need to check for campaign type within [this block](https://github.com/DoSomething/dosomething/blob/v0.4.109/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L45) and call `dosomething_campaign_preprocess_sms_game` if its an SMS game.
