### ISSUE TITLE
new content issue when paginating through content search

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4489]
when you click on a new page on https://beta.dosomething.org/admin/content/search the results go from 5291 to 632 (as of the writing of this issue). The reason for this huge drop in available content is that "Has new content" is selected when you clickthrough to other pages and there is nothing a user can do about that.

see https://trello.com/c/MbH8YJh3 for another example.

ideally "has new content" would just never be selected for a user as she pages through the content

**Comment by mikefantini** [comment]
@angaither do you mind taking a look at this when you have a sec?

**Comment by angaither** [comment]
@mikefantini do you know if the 'has new content' box is useful? should it just be removed?

**Comment by mikefantini** [comment]
@angaither kill it with fire!

**Comment by angaither** [comment]
my favorite.
