### ISSUE TITLE
Promoted options

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4496]
Like having flagged reasons, we should build 'promoted reasons' checkboxes

Options include
- [ ] photo
- [ ] quote 
- [ ] high impact  
- [ ] sponsored

**Comment by aaronschachter** [comment]
Thinking out loud here, but we might want to consider using Taxonomy Terms for Promoted Reason instead of a single value comma separated text column, which we use for Flagged Reason.  It does bring to mind opening pandora's box on whether or a Term field would be appropriate... :expressionless:  

We are storing Kudos Taxonomy Terms in the `dosomething_kudos` table... but a flagged/promoted reason table feels kind of overkill..

**Comment by angaither** [comment]
I mean, it could work. It would be easier to sort/search by those terms then. I'm down to make it a term. 

I was thinking of adding a row to the reportback table, like `flagged` with 

`promoted` | `promoted_reason`

**Comment by angaither** [comment]
though, I guess then it would have to store a vid, meh, I'm not crazy about that. I kind of like that the reason is with the reportback and you don't have to do an additional join to find out why

**Comment by aaronschachter** [comment]
Yep, I hear that. The tradeoff seems itd be in #4497 to filter by the promoted reason text field, esp for multi-values.  I'm cool with keeping it consistent with the `flagged_reason` though, was just commenting for discussion / documentation.

**Comment by angaither** [comment]
I'll play around with trying to sort the flagged reportbacks to see if that can inform the decision

**Comment by angaither** [comment]
from @aaronschachter 

> Random thought around this came to mind. What if a reportback has two items we want to promote, but for different reasons?
> Once a reportback item is flagged, the reportback is ignored entirely, so there would never be the opportunity to update the flagged reason upon adding additional litems. With this its different... wouldnt' the last promoted item always overwrite the reason?

**Comment by aaronschachter** [comment]
Could make sense to keep promoted reason on the Reportback File table...

**Comment by angaither** [comment]
Yeah, had a convo with @mikefantini about this and thought he's going to test what we have in stage, and we might leave it like this till there's demand to change it. 
My thought if we needed to was to keep these `promoted` bool on the reportback table, and store the reason with the file itself.
