### ISSUE TITLE
Campaign: Mobile Commons opt in with campaign name on sign up

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#450]
Two things should happen when a user signs up for a campaign and provides a mobile number:
- Get subscribed into a specified Mobile Commons opt-in path ID
- Pass along the campaign name to a Mobile Commons field

This'll be something like a POST to `https://secure.mcommons.com/profiles/join` with:
- `opt_in_path[]` = the opt in path id
- `person[phone]` = the mobile number to subscribe
- `person[campaign_name]` = the name of the campaign the user signed up for

Probably should use the `mobilecommons` module to make the API call.

**Comment by aaronschachter** [comment]
Agree about using mobilecommons module to handle the API call.  Could multiple campaigns subscribe to the same opt-in path ID, or will each opt-in always be unique?

**Comment by mikefantini** [comment]
@aaronschachter multiple campaigns will subscribe users to the same opt-in path ID (all non-staff pick campaigns will point to the same opt-in path). 

cc: @jonuy

**Comment by mikefantini** [comment]
@aaronschachter the opt-in path for all non-staff pick campaigns is 164453. Are you good on adding this to the campaign node or is there more info you need from me?

cc: @jonuy

**Comment by aaronschachter** [comment]
If this is same across the board, then we don't need to add this into a campaign node for now.  however we don't have anything communicating to Mobilecommons in this app right now. As per @jonuy 's comment, we should use the mobilecommons contrib module but haven't written any code using it yet.  Is mobile signups a requirement for 0.2?

**Comment by mikefantini** [comment]
Yeah we do need these going into mobile commons for 0.2 and pull in
campaign_name. First time we would have a campaign that would use a
different mobile commons id is mid-march.

On Mon, Feb 10, 2014 at 3:24 PM, Aaron Schachter
notifications@github.comwrote:

> If this is same across the board, then we don't need to add this into a
> campaign node for now. however we don't have anything communicating to
> Mobilecommons in this app right now. As per @jonuyhttps://github.com/jonuy's comment, we should use the mobilecommons contrib module but haven't
> written any code using it yet. Is mobile signups a requirement for 0.2?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/450#issuecomment-34677880
> .

## 

Mike Fantini
Head of Product, DoSomething.org
212.254.2390 x232

follow me: @mfantini12
follow us: @dosomething

... and we're hiring! www.dosomething.org/jobs

**Comment by aaronschachter** [comment]
@jonuy Let's sync up when you're back. I have committed code that should be sending the request but want to be sure all the opt-ins are set up properly in Mobile Commons.

**Comment by mikefantini** [comment]
yeah you're in the opt-in path: https://dosomething.mcommons.com/campaigns/5091/opt_in_paths/164453/profiles 

the only reason you didn't get a text was because you're already in mobile commons and it's set up to not send you a text if that's the case.

let's test out tomorrow with an intern to make sure the message goes through properly (not sure if it'll work if we just simply opt you out).

cc: @jonuy @aaronschachter

**Comment by aaronschachter** [comment]
Ok, great. Next I'll need to open up a PR and call the new function introduced in #659 upon signing up for a campaign - so this issue is still open for now.
