### ISSUE TITLE
Add NOODP meta tag to head block

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#451]
Dave, When you're working on the site chrome, could you add the following into the head block pls:

`<meta name="robots" content="NOODP">`

Context at this Trello card - https://trello.com/c/o208GKs3/895-prevent-search-engines-from-using-dmoz-site-descriptions

**Comment by DFurnes** [comment]
Roger. :ok_hand:

**Comment by barryclark** [comment]
This is done! Ty @DFurnes
