### ISSUE TITLE
Mobile Signup to Web Signup Flow

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4510]
Trello card link: https://trello.com/c/Hzstq1j1
- Issue summary: User already signed up for Do Something's text messages but never created an actual account online. Now she is trying to make an account on website but it's not letting her because her number is already registered. (Relevant Zendesk ticket: https://dosomethingorg1.zendesk.com/agent/#/tickets/6648)
- Summary of solution liked by Aaron, Uy, and Andrea: If a user tries to register for an account and it says that their number is already used, we build in an automated way for them to merge the two accounts. This should require sending a verification code to SMS. The user would fill out the "It says my number exists" form, enter the verification code, and it would merge all activity (signups+reportbacks) into one single account with the mobile # and email.

**Comment by namimody** [comment]
From @mshmsh5000: https://boompayments.com/

**Comment by angaither** [comment]
duplicate of #1003

**Comment by namimody** [comment]
Hi @angaither! I don't think this is a duplicate. From what I understand, #1003 deals with allowing a user with _only_ a cell phone number to set a new password, assuming they signed up with a cell number, no email address, and a password. This ticket more deals with the case where an SMS-only member would like to create an account on the web with their associated phone number. They don't even have a password in this case, and can't create an account with an email and cell number because their cell number is already in their system. Currently, their only option is to create an account with an email address and no phone number, and have two disassociated accounts in our system. Additionally, this solution only becomes apparent if they reach out to Hannah.

**Comment by angaither** [comment]
@namimody that's what the comments in #1003 say

> Either way, the use case here is for people who've participated with us solely via mobile before and then trying logging onto our site with their mobile number some time later.

**Comment by namimody** [comment]
I take it all back @angaither :speak_no_evil:
