### ISSUE TITLE
Admin Functionality: Rotate Reportback Photo 

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4512]
Trello: https://trello.com/c/mz4fSadx

The campaigns team has to exclude great photos because they are rotated. Would be great if they could rotate photos on the backend. (Note: users do not get email notification if their reportback has been manipulated.)

Example: https://beta.dosomething.org/admin/reportback/72353

**Comment by sbsmith86** [comment]
@namimody @mikefantini Do admins ever edit other information in the reportback? like caption, or the why statement? If so, where do they go to do that?

**Comment by mikefantini** [comment]
@sbsmith86 ideally no, but i could see someone wanting to fix like a spelling error in order to promote a caption or a spelling error in a why statement to more easily send to a sponsor
