### ISSUE TITLE
Tips Modal Spacing Off on Mobile

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4517]
![image](https://cloud.githubusercontent.com/assets/12396076/7714938/12079a84-fe51-11e4-9d0e-866f7c14faf2.png)
- Issue Summary: On mobile, the tips modal has no margin.
- Browser/Operating System: iPhone 5S, iOS 8.3
- Issue Scope: Happens on at least two campaigns's tips on mobile, FAQ modal on mobile works fine. Desktop modals look correct.

**Comment by mikefantini** [comment]
@DFurnes another lingering neue thing. This is the Do It section tips. We put them in a modal on mobile; there is no modal for these on desktop, instead they are in the gray box in the Do It section.

**Comment by DFurnes** [comment]
Ooooof. :sweat:

**Comment by namimody** [comment]
Hate to be a pain @DFurnes -- seems like this is still an issue :( Could we chat about this on Monday? Thanks!

**Comment by DFurnes** [comment]
It's fixed on staging, but hasn't been deployed to production yet!

**Comment by mikefantini** [comment]
yeah i just deployed to staging so you can verify @namimody!

**Comment by namimody** [comment]
Ahhh I'm so sorry!!

On Fri, Jun 5, 2015 at 3:19 PM, mikefantini notifications@github.com
wrote:

> yeah i just deployed to staging so you can verify @namimody
> https://github.com/namimody!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/dosomething/issues/4517#issuecomment-109410232
> .

## 

Namita (Nami) Mody

Junior Product Manager
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255

**Comment by DFurnes** [comment]
No prob!
