### ISSUE TITLE
Expand on access control measures for resource access in API

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4521]
https://api.drupal.org/api/drupal/modules%21node%21node.module/function/node_access/7

Need to update the following resources:
- [x] reportbacks
- [x] campaigns
- [x] kudos

**Comment by aaronschachter** [comment]
There's also `entity_access` for Reportbacks, and Kudos http://www.drupalcontrib.org/api/drupal/contributions!entity!entity.module/function/entity_access/7

**Comment by weerd** [comment]
We're going to use `user_access()` method instead of `node_access` or `entity_access` since via the endpoint resource we already know the type of resource being requested. `node_access` and `entity_access` require loading the full node to check the access, which is added work when if access is allowed we need to load the node/entity in the class anyhoo.
