### ISSUE TITLE
Reportback flagged status

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4529]
It seems like some flagged reportback items aren't getting set as flagged in the db.

This query on prod returns 2,257 rows
the file is set as flagged, but the reportback isn't 

```
SELECT rb.rbid, rb.nid, rb.flagged, rbf.status, rb.flagged_reason, FROM_UNIXTIME(rbf.reviewed)
FROM dosomething_reportback as rb
INNER JOIN dosomething_reportback_file as rbf on rb.rbid = rbf.rbid
WHERE rbf.status = 'flagged'
AND (rb.flagged = 0 or rb.flagged is null);
```

every test I've done locally (flagging with reasons/without reasons) correctly sets the status from null->0

@aaronschachter are you able to replicate this issue?

**Comment by mikefantini** [comment]
@namimody

**Comment by angaither** [comment]
This has been happening since 1/27/2015
it seems to be happening with more regularity lately, but still haven't been able to reproduce it.

**Comment by mikefantini** [comment]
@angaither did anything change on 1/27/2015? it's also possible that that's just when the campaigns team started really reviewing reportbacks

**Comment by angaither** [comment]
@mikefantini Yeah, the [commits](https://github.com/DoSomething/dosomething/commits/dev?page=35) during that time are all related to setting up the reportback stuff, so it looks like that's when reviews started

**Comment by mikefantini** [comment]
3193 rbs were flagged but are showing up as 0 or null in the reportback_flagged column of the table.

**Comment by aaronschachter** [comment]
Linking #4621

**Comment by mikefantini** [comment]
@mshmsh5000 assigning over to you

**Comment by angaither** [comment]
on staging we get 4 results 

| rbid | nid | flagged | status | flagged_reason | FROM_UNIXTIME(rbf.reviewed) |
| --- | --- | --- | --- | --- | --- |
| 9 | 43 | 0 | flagged | NULL | NULL |
| 184 | 1261 | 0 | flagged | NULL | NULL |
| 290 | 15 | 0 | flagged | NULL | NULL |
| 1292 | 1159 | 0 | flagged | irrelevant | 2015-05-14 18:46:25 |

**Comment by angaither** [comment]
We have recreated the issue!
On staging, @mikefantini and I went though a page of 25 or so that were in the inbox, and reviewed them all at once, after hitting save, there are now 7 reportbacks on staging where the file status is `flagged`, and the flagged boolean is still 0. 

So it seems it may be a problem where there are multiple reportback reviews submitted at the same time. 

Did this on http://staging.beta.dosomething.org/node/1286/rb

```
SELECT rb.rbid, rb.nid, rb.flagged, rb.promoted, rbf.status, rb.flagged_reason, FROM_UNIXTIME(rbf.reviewed) as reviewed
FROM dosomething_reportback as rb
INNER JOIN dosomething_reportback_file as rbf on rb.rbid = rbf.rbid
and rb.nid = 1286
and rbf.reviewed = '1435781716'
and rbf.status = 'flagged';
```

**Comment by mikefantini** [comment]
bad news: #4647 didn't fix the issue

good news: I was able to watch several people recreate the issue in production.

example 1:
- [RB in question](https://www.dosomething.org/admin/reportback/89238) - RBID 89238
- [campaign in question](https://www.dosomething.org/campaigns/1-3-us) - NID 5275
- [video of Jess reviewing](http://screencast.com/t/PbhO2Y3NPzw) happens around 0:24

example 2:
- [RB in question](https://www.dosomething.org/admin/reportback/47994) - RBID 47994
- [campaign in question](https://www.dosomething.org/campaigns/mirror-messages) - NID 7
- [video of Jess reviewing](http://screencast.com/t/hkdyVf1Zze2x) happens around 1:07. save and 504 error happens around 3:30.

example 3:
- [RB in question](https://www.dosomething.org/admin/reportback/89308) - RBID 89308
- [campaign in question](https://www.dosomething.org/campaigns/thumb-wars) - NID 1508
- video seems to be missing but perhaps Adam has it. Trying to find out.

**Comment by angaither** [comment]
![](http://cdn2.hubspot.net/hub/228391/file-745508197-jpg/blog-files/devopsevil.jpg)

@sheydari-ds is it possible db writes are getting locked?

**Comment by itsjoekent** [comment]
can confirm, I cant reproduce this locally

**Comment by itsjoekent** [comment]
just tested with example two from @mikefantini comment -- if you go back and try flagging it again it works fine

I'm thinking @angaither point with db writes being locked is a possible explanation. Prod has much more traffic than our local boxes / stage and might explain why we can't replicate it there. It could also explain why it only seems to occur with large batches of reportback flags and is hard to consistently reproduce.
(Also I don't see any reason why in the code this should be happening)

**Comment by mshmsh5000** [comment]
More on debugging in prod here: https://trello.com/c/pTNjJhhw/121-temporarily-enable-query-logging-on-prod

@angaither @sheydari-ds

**Comment by itsjoekent** [comment]
any updates on this? @angaither @sheydari-ds @mshmsh5000

**Comment by ghost** [comment]
Sitting down with Matt on this today.

**Comment by itsjoekent** [comment]
Okie dokes

**Comment by angaither** [comment]
I looked into how much this could affect campaign numbers, and the answer could be quite a bit. 

For example, [banned book clubs](https://www.dosomething.org/node/4) has 205 books that should be included in the total, but with the bug, the number inflates to 1005.

A simple, but annoying solution is to re-flag those reportbacks... maybe we could automate this?

**Comment by mikefantini** [comment]
i think we recreated this:
1. submit reportback
2. add another image to the same reportback
3. as admin, flag the first file
4. as admin, approve the second file
5. save the inbox
6. check the db and the first file will appear to have status = flagged but flagged status = 0

@angaither 

thanks @DFurnes for figuring this out you goddamn champion

**Comment by mikefantini** [comment]
most recent issue now represented in #4847.

other related issues are in the Reportback Reviewed Bugs Milestone
