### ISSUE TITLE
Campaign resource changes audit

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4534]
The great unification of the established endpoints with the new Campaign and CampaignTransformer classes. Need to plan out how to best transition the code end established endpoints to use the new approach to handling campaign data.
- [ ] Message Broker email things that reference the current `content` endpoint.  The MB stuff just needs to point to the new `campaigns` endpoint and change how it's consuming the data, and then we can kill the `content` endpoint.
- [ ] Lobby dashboard code also references `content` endpoint.  Same as above ^^
- [ ] All code in the dosomething repo where we reference the old Campaign class, mostly preprocessing in template but some other places too.
- [x] Reportback gallery on campaign page relies on targeted action endpoint on `/campaign`. Need to confirm endpoint still works and at a later date update to point to the new `/reportback-items` endpoint.

CC: @aaronschachter @jonuy

**Comment by aaronschachter** [comment]
3 things i know of off the top of my head that would break:
- [ ] Message Broker email things that reference the current `content` endpoint.  The MB stuff just needs to point to the new `campaigns` endpoint and change how it's consuming the data, and then we can kill the `content` endpoint.
- [ ] Lobby dashboard code also references `content` endpoint.  Same as above ^^
- [ ] All code in the dosomething repo where we reference the old Campaign class, mostly preprocessing in template but some other places too.

**Comment by weerd** [comment]
I'm gonna pull out your two items and add to main issue description cause I got some to add as well.

**Comment by aaronschachter** [comment]
Ok!  I re-edited my comment for 3 items FYI

**Comment by mikefantini** [comment]
@weerd is this still high priority?

**Comment by mikefantini** [comment]
removing high priority label now
