### ISSUE TITLE
some campaign tiles in finder are linked to 0.0.0.1

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4559]
saw it previously with https://github.com/DoSomething/ServerConfig/issues/72

then just saw it again today by filtering by Sex and Relationships and 2 of the first 8 campaigns had http://0.0.0.1 instead of https://www.

campaigns were http://0.0.0.1/campaigns/support-survivors and http://0.0.0.1/campaigns/project-shutdown

cc: @sergii-tkachenko

**Comment by sergiitk** [comment]
Found this again
![image](https://cloud.githubusercontent.com/assets/672669/8134192/3d24f664-10fb-11e5-9c72-55de97a0492a.png)

**Comment by sergiitk** [comment]
I've made a change in Jenkins, hopefully it'll fix this. We need to keep an eye on this @mikefantini.
+ Manually fixed current content.

**Comment by angaither** [comment]
@sergii-tkachenko @mikefantini going to close this out, feel free to re-open if we are still seeing this
