### ISSUE TITLE
Wrap Text for "Signup Reason Label"

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4568]
![image](https://cloud.githubusercontent.com/assets/12396076/7994488/d2e447e8-0adb-11e5-9800-fd7a9a90c0e1.png)

Changed copy to be shorter for now, but text for the "Signup Reason Label" should wrap to fit the modal.

**Comment by mikefantini** [comment]
@DFurnes do you mind knocking this guy out?
