### ISSUE TITLE
Reportback: Delete functionality

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#457]
Create functions and menu callback (reportback/*/delete) for deleting a reportback.

Should only be available to administrator role, although possibly other roles later (e.g. a user being able to delete their own reportback)

**Comment by namimody** [comment]
@mikefantini @aaronschachter this seems to not be working -- I can get to this screen but the "Delete" button is unclickable.

![image](https://cloud.githubusercontent.com/assets/12396076/8380429/acb953be-1bf3-11e5-8cf4-3d1c4bbe2a94.png)

**Comment by aaronschachter** [comment]
This is a front end issue @namimody. Please open a new issue and assign to a fender.

**Comment by namimody** [comment]
Oh, sorry @aaronschachter! Will do.
