### ISSUE TITLE
Campaign Titles on Homepage: IE 8

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4572]
- Issue Summary: Campaign titles on homepage appear with black behind them
- Browser/Operating System: Windows 7 / IE 8
  ![image](https://cloud.githubusercontent.com/assets/12396076/8037258/ba75d2de-0dca-11e5-9163-85a31f13f50f.png)

**Comment by DFurnes** [comment]
This is expected behavior. IE 8 does not support [CSS Gradients](http://caniuse.com/#feat=css-gradients), which we use to add that gradient effect on tiles, so we use a transparent black container to make the text readable.
