### ISSUE TITLE
Campaign Header Photos, IE 8

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4573]
- Issue Summary: Campaign header photos do not fill entire header space.
- Browser/Operating System: Windows 7 / IE 8
  ![image](https://cloud.githubusercontent.com/assets/12396076/8037358/4c53350c-0dcb-11e5-9568-ea24abb2b7a5.png)

**Comment by DFurnes** [comment]
This is a known issue. IE 8 does not support [background-size: cover](http://caniuse.com/#feat=background-img-opts), which we use to fit cover images to the header. This only affects 0.76% of our users according to Google Analytics, so I don't think it's worth much engineering time.

**Comment by namimody** [comment]
Ahh, makes sense @DFurnes. I think we can close then?

cc @mikefantini
