### ISSUE TITLE
Rotating RB Image Doesn't Save in Permalink or Backend

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4577]
- Issue Summary: If a user uploads a photo and rotates it, the permalink and back end do not reflect the rotation.
- Browser/Operating System: Firefox 38 / Windows 8, OS X Mountain Lion / Chrome 43 (Seems to happen across browsers.)

**Comment by mikefantini** [comment]
@sbsmith86 mind taking a look at this one when you have a sec?

@namimody do we know when this started happening?

**Comment by sbsmith86** [comment]
looking now

**Comment by namimody** [comment]
@mikefantini it was reported on June 2 by TSG - it could have been happening before that but I don't have any evidence.

**Comment by sbsmith86** [comment]
@mikefantini @namimody This seems to be an issue with PHP 5.5 compatibility with the GD image library/drupal image API that we are using to do the rotation. I think we upgraded to 5.5 recently, during the migration? Anyway, there is a fix for it that's got it working on my dev. I will get it merged in now.
