### ISSUE TITLE
spacing off on permalink on internet explorer

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4579]
![image](https://cloud.githubusercontent.com/assets/6330971/8041852/3740ca58-0de9-11e5-8476-57d43a140db2.png)

![image](https://cloud.githubusercontent.com/assets/6330971/8042032/46526b04-0dea-11e5-9cdb-79444798bd2d.png)

seems to be happening on all versions of IE

**Comment by mikefantini** [comment]
cc: @namimody

**Comment by DFurnes** [comment]
This seems to be an Internet Explorer bug, and probably not worth fixing. It works properly in Edge:

<img width="1275" alt="screen shot 2015-09-03 at 1 43 59 pm" src="https://cloud.githubusercontent.com/assets/583202/9666054/d9563598-5241-11e5-8d22-798e97705128.png">

**Comment by angaither** [comment]
@DFurnes if we don't want to fix this, should we close this issue out?

**Comment by DFurnes** [comment]
I think so. :white_check_mark:
