### ISSUE TITLE
Campaign finder doesn't work on Canada

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4585]
Images and links appear to be broken on Canada when filtering using campaign finder.

https://canada.dosomething.org/
![screen shot 2015-06-09 at 10 28 22 am](https://cloud.githubusercontent.com/assets/672669/8060261/45ef6916-0e92-11e5-852d-4083db28063f.png)

**Comment by sergiitk** [comment]
I think is is related #4559.

**Comment by sergiitk** [comment]
CC @mikefantini

**Comment by namimody** [comment]
This seems to be working now!
