### ISSUE TITLE
Add register & login custom events

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#4589]
We want to trigger a custom event in Google Analytics on the subsequent page load after registering or logging in. :chart_with_upwards_trend: 

/cc @mikefantini @Bladt @namimody

**Comment by DFurnes** [comment]
Since we're adding more of these to the codebase, it might be nice to make a generalized helper function that we can use to make Google Analytics & Optimizely custom events, rather than having to use `drupal_add_js()` to add the inline analytics script each time. Maybe something like:

``` php
function dosomething_helpers_add_analytics_event(string $event_name) {
   // ...
}
```

**Comment by itsjoekent** [comment]
good idea!
