### ISSUE TITLE
update problem fact help text

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4590]
Because of problem shares, instead of "Limit: 135 characters" we need it to be "Limit: 117 characters (for the purposes of sharing this fact via social, this MUST be under 117 characters." 

![image](https://cloud.githubusercontent.com/assets/6330971/8084803/02e56ebc-0f5b-11e5-8712-359c2f5e08c9.png)

**Comment by itsjoekent** [comment]
@angaither need me to take care of this one?

**Comment by angaither** [comment]
@deadlybutter that would be great
