### ISSUE TITLE
Comeback Clothes here’s what happened list: wrong HTML entities

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4591]
https://www.dosomething.org/campaigns/comeback-clothes
![image](https://cloud.githubusercontent.com/assets/672669/8084860/49b7a29c-0f5b-11e5-8404-efac8971d19f.png)

`H&amp;M` must be `H&M`.

CC @mikefantini

**Comment by mikefantini** [comment]
ah crap good catch @sergii-tkachenko.

related to #4286, except happening on closed campaigns.

@angaither mind giving this a look?
