### ISSUE TITLE
Output campaign author information

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4602]
- [x]  ensure that staff members (editors) can change authors on the node
- [ ] output author information, only on campaigns in a hot phase (name, photo, job title)

**Comment by mikefantini** [comment]
just a note: staff photos should be added on the campaign lead's profile on https://www.dosomething.org/user/[uid]/edit

@lkpttn just a heads up may need some of your assistance when we're ready to implement this

**Comment by mikefantini** [comment]
final should look like this:

![image](https://cloud.githubusercontent.com/assets/6330971/8487931/60c4fa14-20dd-11e5-89b7-36c7ed25333a.png)

**Comment by sbsmith86** [comment]
Confirmed that editors can change authors on the node.
