### ISSUE TITLE
Custom template for hot phase campaigns 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4603]
When a campaign is in the hot phase, give it a custom theme suggestion to allow it to be rendered in a completely different tpl

**Comment by mikefantini** [comment]
Just noting here is that one key difference is that the Problem Share should not appear when a campaign is in the hot phase.

This is because we will instead prompt users to share around the goal and progress within the hot module itself

**Comment by mikefantini** [comment]
@sbsmith86 said no longer needed
