### ISSUE TITLE
New job title user field

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4604]
Add a new field on user object for campaign lead job titles
this should only be editable, and viewable on profiles by staff members.

**Comment by mikefantini** [comment]
this should be added to /user/[uid]/info

It can just be added to the Info Group

![image](https://cloud.githubusercontent.com/assets/6330971/8336576/86b1fa80-1a73-11e5-8864-bb4e3297e37d.png)
