### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4606]
create a graph in d3? that tracks the goal progress as it advances

**Comment by sbsmith86** [comment]
I'm looking at using [Chart.js](http://www.chartjs.org/) for this. It is lightweight, because we only have to load in the script for the chart type we want to use (~12kb) and seems to have a polyfill for IE8 support. 

@mshmsh5000 @angaither @mikefantini @namimody @DoSomething/front-end

**Comment by angaither** [comment]
:+1:

**Comment by mshmsh5000** [comment]
:smiley_cat: Sounds good for a prototype. And the docs include guidance for the data array format that will come from the back end.

**Comment by sbsmith86** [comment]
@angaither is it

**Comment by sbsmith86** [comment]
The graph is pretty much done but right now it is using dummy data. I am going to leave this issue open until #4607 is done and I can pull in real data and finish this graph up.
