### ISSUE TITLE
Log-in button on campaigns works as a 'Signup'

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4608]
Just logged in with newly created user on https://www.dosomething.org/campaigns/just-because
It automatically signed me to this campaign.
![image](https://cloud.githubusercontent.com/assets/672669/8317045/6a62ebe8-1a03-11e5-9013-d8dc91e2afed.png)

cc @mikefantini

**Comment by angaither** [comment]
@sergii-tkachenko that is what is supposed to happen
