### ISSUE TITLE
adding UTM parameters to internal links

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4610]
we're looking for all links to pages on the site to be appended by [UTM parameters](https://support.google.com/analytics/answer/1033867?hl=en). this will allow us to do better analysis on the efficacy of various marketing efforts (both external and internal).

this issue relates specifically to links from one page on the site to another (i.e. homepage -> campaign page).

can we append a convention like 
?utm_source=dosomething&utm_medium=site&utm_campaign=node_1141 to the end of internal links?

this convention would follow the following pattern:
- utm_source=dosomething
- utm_medium=site
- utm_campaign = node_nid

I can think of three cases currently on user facing pages that have internal links that don't have nid - profiles, /campaigns, and search. In this case we could go with utm_campaign=profile, utm_campaign=campaigns, utm_campaign=search. Not sure if 404 pages could/would use the nid of the page_not_found, but it currently does not. @Bladt for these edge cases just knowing that they come from the profile and search gives us all the info we really need right? another approach would be to have it be profile_uid (i.e. profile_329195) and search_search_term (i.e. search_bullying) but I think that will just make the more obvious question we'd want to answer harder to get at.

are there other examples where we have user facing pages that have internal links that don't have an nid?

another question is how this should effect the source field we store on the signups table both moving forward and retroactively?

also potentially relevant is seeing [other examples](https://docs.google.com/a/dosomething.org/spreadsheets/d/1O02BK6D6ZwRgweu6N_5mMspW2lLRYz4KOt9iEQoind0/edit?usp=sharing) of how we'll be using UTM parameters with partners.

@Bladt did I miss anything here?

please include thoughts @aaronschachter @angaither @sergii-tkachenko @mshmsh5000 @Bladt @joshcusano 

related to #4575

**Comment by Bladt** [comment]
@mikefantini The scholarships page and campaign collection pages would also be internal links to campaigns. The collections have NIDs, right? But not about/scholarships?

Neither of these cases are pressing. We can, at present, track conversions tied to collections and /scholarships by looking at them as landing pages. E.g. we are currently tracking which campaigns visitors sign up for if they enter on the /scholarship page.

**Comment by aaronschachter** [comment]
Yes this is what the `source` column on the Signups table was aiming to capture. The query string param is appended via code. For scholarships, we could add it if the scholarships page displayed scholarship campaigns dynamically (see #2825).

@bladt The current plan for signups via mobile app was to store something like `ios_letsdothis` or `android_letsdothis`. Do the UTM params aim to capture conversions from the mobile apps as well?

**Comment by Bladt** [comment]
@aaronschachter will the mobile apps be sending traffic to the www? Or will they be pulling all the content into the app? We would only need to use UTM parameters if the apps were sending traffic to the site.

**Comment by aaronschachter** [comment]
Oh, no, we never actually push users out to the web. Which makes it sound like the UTM should be treated separately from the `signup.source` altogether, and my comment about what the Signups.source column is aiming to capture is different (since UTM is just google analytics).  Signup.source tracks how people signup for a campaign: homepage, or mobile app, or a reportback permalink.

Where we can potentially miss a ton of data is when editors link to internal content within text fields in the site.  I can think of two (somewhat unpleasant) ways we could handle:
- Train editors to always include the UTM params 
- JS to append the UTM params

**Comment by mikefantini** [comment]
@aaronschachter yeah definitely hear you on the text area links. I think training editors is the proper step there. I think the first goal should be to get all dynamically generated internal links to have these UTM parameters so traffic tracking is cleaner.

so @aaronschachter if we were to add UTM parameters to dynamically created internal links, you're saying we could just leave `signup.source` as is?

**Comment by angaither** [comment]
@aaronschachter we could also potentially create a custom text filter to append the utm params to links in text

**Comment by aaronschachter** [comment]
@angaither That could be sweet!  

@mikefantini I suppose the `signup.source` could get populated from the `utm_campaign` instead of a `source` parameter... but, I'm also weary of overcomplicating things.  I think we'd need to drill into it more to determine how much we need to look into it, although I imagine it will be useful to track web vs mobile app signups.  Can you or @bladt weigh in on if we even look at the data in `signup.source` ?

**Comment by mikefantini** [comment]
also @joshcusano ^

**Comment by joshcusano** [comment]
@aaronschachter @mikefantini - at some point, we have used the data in signup.source to determine if a campaign has been featured on the homepage, how many sign ups come from /campaigns, and sign ups from collections.

I haven't used it in a couple of months, but I could see it still being useful.

**Comment by sbsmith86** [comment]
@aaronschachter @angaither I'm working on adding UTM parameters to goal shares ( #4447). Thinking about creating a helper function where we can pass in the type of UTM parameters we need (default, share) and some custom values if we need them, and it returns an urlencoded string we can append to any link. Thoughts?

**Comment by angaither** [comment]
sounds genius @sbsmith86! 
maybe `dosomething_helpers` or `dosomething_metatag` don't love either of those, but not sure if a better option exists....

**Comment by sbsmith86** [comment]
@angaither i'll go with `dosomething_helpers` for now.

**Comment by angaither** [comment]
we can close this, we have functions that handle this, if we need this on more pages we can open up more specific issues

**Comment by mikefantini** [comment]
@Bladt if there are things you think you're missing please let us know/create issues.
