### ISSUE TITLE
update help text on /node/add/fact

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4612]
![image](https://cloud.githubusercontent.com/assets/6330971/8318775/f43d604c-19d5-11e5-943e-0ef4ebf1b74d.png)

add to the bottom "If using for problem share this must be 117 characters or less otherwise it will break problem shares."

related to #4590

**Comment by itsjoekent** [comment]
should I also write some logic to make sure it doesn't exceed 117 chars?

**Comment by angaither** [comment]
@deadlybutter I don't think we want to do that, we have as JS script that runs on some fields that does a character count, so just make sure it's going on this and add that help text.

**Comment by itsjoekent** [comment]
okie dokes

**Comment by itsjoekent** [comment]
just checked, the form blocks 255 chars so this needs to be updated as well 

`Fact cannot be longer than 255 characters but is currently 279 characters long.`
