### ISSUE TITLE
changing a file's status should change the rb's flagged status

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4621]
once a reportback is flagged, it always remains flagged, even if an editor made a mistake in flagging it and then changed it to be approved, promoted, excluded, etc.

we should allow for editors to change their minds (provided obviously they didn't delete an image).

so when a file's status changes from flagged to promoted the reportback reportback_flagged should change from 1 to 0

**Comment by itsjoekent** [comment]
Well this is an interesting bug...! I found what I believe is the cause of the problem in this function: https://github.com/DoSomething/dosomething/blob/83b61d349fc441a5e9ff79eb7de11f5dcb57256f/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.admin.inc#L275

Essentially, when we set a report-back to promoted for example, we unset all of the reasons for that specific type (which means flagged reasons don't get unset). I wrote a fix here: https://github.com/deadlybutter/dosomething/commit/2ec6fef592f4d99a67d98f193c5be8a013f71dba

and it worked as intended, but the bug appears to still persist

<img width="432" alt="screen shot 2015-07-08 at 10 49 05 am" src="https://cloud.githubusercontent.com/assets/897368/8573496/e509caa8-255f-11e5-81cb-98280c036147.png">

**Comment by angaither** [comment]
@deadlybutter were you able to reproduce the bug locally?

**Comment by itsjoekent** [comment]
yeah I'm encountering it right now (screenshot above)

**Comment by angaither** [comment]
documenting from real life convo: 
It's actually the `flagged` `promoted` boolean on the `dosomething_reportback` table itself that is causing the issue.
