### ISSUE TITLE
Can't Delete Reportbacks

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4623]
I can get to this page but the button is unclickable.

![image](https://cloud.githubusercontent.com/assets/12396076/8380546/5c9508e6-1bf4-11e5-8213-c4f126140168.png)

**Comment by mikefantini** [comment]
@DFurnes do you mind taking a look at this? see comments in #457

**Comment by DFurnes** [comment]
Sure!
