### ISSUE TITLE
Twitter Permalink Share Shows Jumbled Copy Where Apostrophe Should Be

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4624]
When a campaign name has an apostrophe, the Twitter copy shared from the permalink shows jumbled copy instead.

![image](https://cloud.githubusercontent.com/assets/12396076/8412438/f8998234-1e57-11e5-803a-9a0cb6432b39.png)

**Comment by mikefantini** [comment]
@namimody is this happening on problem shares as well?

**Comment by namimody** [comment]
Not an issue on problem shares with apostrophes:

![image](https://cloud.githubusercontent.com/assets/12396076/8436634/aaf53f0c-1f27-11e5-88c0-f8554fc8154d.png)

**Comment by mikefantini** [comment]
got it thanks. @sbsmith86 do you mind knocking this out this sprint?

**Comment by sbsmith86** [comment]
@mikefantini yerp
