### ISSUE TITLE
Updating RB should reappear in inbox

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4625]
Updated:

Any change to a reportback (new image, changed quantity, changed caption, changed why participated) should go back into the inbox and status should equal pending.

However, we don't want the quantity on the campaign to go below what it was prior to update so we're going to hold off on this until we can more robustly address this issue.

---

Submitted RB. Then approved. The total approved quantity showed correctly. 

Updated the quantity on the reportback, but was not given the opportunity to approve again. However, total approved quantity did update.

Related: https://github.com/DoSomething/dosomething/issues/4225#issuecomment-116768048

**Comment by mikefantini** [comment]
@angaither this is another argument for having reportbacks go back into the inbox when anything on the reportback is updated by the user (i.e. in this case quantity).

let's discuss in standup but I'd like to go this route as discussed in #4225 

FYI @aaronschachter

**Comment by mikefantini** [comment]
@angaither thoughts on just making this issue "put reportback back in inbox if quantity changed"? or is there more to it then that?

**Comment by namimody** [comment]
Per #4677, any time a RB is updated (new photo, new quantity, new caption) by the creator it needs to fall back into the reportback inbox and the status needs to change to pending. As of 8/13, updated RBs are not falling back into the inbox.

**Comment by namimody** [comment]
As a note: created RB on test campaign (http://staging.beta.dosomething.org/campaigns/rb-wtf) with quantity 1. Approved reportback, hot module displayed quantity of 1. Added another photo to the same RB, and changed quantity to 100. Ran CRON, hot module displayed quantity of 100. Second photo remains in inbox, pending approval.

**Comment by angaither** [comment]
@namimody just want to confirm the total is 100, even though the reportback item is still pending?

@deadlybutter this might have to do with the fact that reportback's are set to pending, but the flagged status is still 0, it doesn't change back to null when an item is in review

**Comment by angaither** [comment]
Not sure if we want to change this or leave it the way it is. But I think it's a larger discussion we can have once we've ironed out a few of the other buts

**Comment by namimody** [comment]
Hi @angaither -- yes, the total is 100. I submitted an update on a reportback (both an additional photo and an increased quantity). The photo was still pending review in the inbox, but the new quantity was reflected in the hot module.

@mikefantini can confirm, but I think we are holding on this issue for the moment because it has a lot of other implications. Just wanted to record this behavior because the question was raised in the meeting. :)

**Comment by angaither** [comment]
totally, thanks. good to know that it's different than we thought ;)

**Comment by mikefantini** [comment]
yup yup. still holding on this while we iron out the other issues. thanks for documenting the current status @namimody

**Comment by angaither** [comment]
@mikefantini we should re-group on this issue as well

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;AFtA0OHx&#x2F;1417-do-updated-reviewed-reportbacks-fall-back-into-review-queue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Do updated reviewed reportbacks fall back into review queue?</a>

**Comment by namimody** [comment]
I'm going to close this because:

1) I 90% sure that members can update their quantity without adding a photo
2) we are revamping reportbacks entirely, and this feature is included
