### ISSUE TITLE
Incorrect entity_save ?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#4629]
Question brought up by eagle eye @sergii-tkachenko in meeting around #4529

In https://github.com/DoSomething/dosomething/blob/v0.5.10/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback.inc#L218

Should `return entity_save('reportback_file', $this);` actually be `return entity_save('reportback', $this);`?

**Comment by angaither** [comment]
It looks like this has been `entity_save('reportback_file', $this);` [since the beginning](https://github.com/DoSomething/dosomething/commit/0af84c43c16559c8627d08c59382c814f534e03d)

**Comment by aaronschachter** [comment]
Reviewing the code, it does indeed look like this should be changed to `entity_save('reportback', $this)`.   Not sure how it works though, but making the change could hopefully at least rule out the possibility that this is what is the cause.

 https://github.com/DoSomething/dosomething/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback_file.inc#L70

**Comment by mikefantini** [comment]
@aaronschachter @angaither did one of you make this change?

just circling back to see if we can rule this out as a possibility or not?
