### ISSUE TITLE
Campaign Thumbnails Not Appearing on Affiliate /campaigns

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4630]
Some or all of thumbnails on /campaigns appear as broken images on the following sites:

https://botswana.dosomething.org/campaigns
https://nigeria.dosomething.org/campaigns
https://indonesia.dosomething.org/campaigns
https://uk.dosomething.org/campaigns
https://kenya.dosomething.org/campaigns
https://ghana.dosomething.org/campaigns

Canada seems to be working fine.

**Comment by ghost** [comment]
Tested and fixed.

**Comment by namimody** [comment]
Thanks @sheydari-ds! Is this a permanent fix?

**Comment by ghost** [comment]
Yes, this should be good now. Resolved!!

**Comment by ghost** [comment]
@julielorch Resolving this.
