### ISSUE TITLE
Flagging RB Doesn't Always Change Total Approved Quantity

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4633]
Sometimes, flagging an approved reportback results in the TAQ decreasing correctly, but not always. The current offending reportback is 1440 (on Stay Tuned campaign (http://staging.beta.dosomething.org/campaigns/stay-tuned // http://staging.beta.dosomething.org/admin/reportback/1440) created on staging)

Incorrect TAQ is showing up on:
Custom Settings > Goals Settings section: http://staging.beta.dosomething.org/node/1270/custom-settings
Action page: http://staging.beta.dosomething.org/campaigns/stay-tuned
Top of reviewed reportback view: http://staging.beta.dosomething.org/node/1270/rb/reviewed

Based on how the code is written, this could be due to https://github.com/DoSomething/dosomething/issues/4529

**Comment by namimody** [comment]
@angaither @mikefantini @mshmsh5000 In case it's helpful, another recreation of https://github.com/DoSomething/dosomething/issues/4529!

**Comment by mikefantini** [comment]
@namimody i think this may be resolved, but let's just run through this when you are back and make sure everything makes sense and is looking right

**Comment by namimody** [comment]
Hi @mikefantini! Yesterday I ran through this goals QA doc (https://docs.google.com/spreadsheets/d/16YcysP9i8WtAnoocS_D1k2qxeUIiulDAz4yErdZSi5w/edit#gid=0) that I had made before leaving and this functionality worked!
