### ISSUE TITLE
add action_kit as a shipment item on the campaign signup data form

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4634]
![image](https://cloud.githubusercontent.com/assets/6330971/8436778/c9137b06-1f28-11e5-9561-70547e050364.png)

related to #4303

**Comment by mikefantini** [comment]
if this doesn't get done in time for [GTFO](https://www.dosomething.org/campaigns/gtfo) launch we'll have to programmatically update the shipment_item entries that come in before we deploy this

**Comment by angaither** [comment]
@mikefantini I can get this out today
