### ISSUE TITLE
progress copy override

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4638]
need a field added to the campaign template to override the default progress update

Suggestion: add this field to custom settings under the Goal Settings group with the name "Hot Phase Progress Copy Alternate" help text "Add copy here if you'd like to override the default progress copy in the hot module. Note: The default copy changes as progress increases. Override copy is static. If you create override copy, you'll need to either delete the copy or change it yourself for this text to update."

this would override the copy in #4446 and again is the copy in the speech bubble:

![image](https://cloud.githubusercontent.com/assets/6330971/8456210/ec92206e-1fd7-11e5-9138-6570fc07e0a9.png)

**Comment by mikefantini** [comment]
@deadlybutter this was added to the DoSomething Campaign Configuration. It needs to be added to the campaign node itself under the Custom Settings tab.

The goal of this is that a campaign lead could override the global progress copy for copy specific to that campaign, which is why it needs to be on the node itself.

Also I'm not sure if @sbsmith86 would need to do any work to have this override the progress copy that would display in the hot module based on the percentage towards the goal the campaign is at.

![image](https://cloud.githubusercontent.com/assets/6330971/9510462/ea959ad2-4c39-11e5-9c7c-b274632a5a3d.png)

**Comment by sbsmith86** [comment]
@mikefantini @deadlybutter as long as the variable we send to the template has the correct copy, it should be fine.

**Comment by itsjoekent** [comment]
@mikefantini ah gotcha, Ill change to be Node based!
