### ISSUE TITLE
admin styling off on staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4639]
![image](https://cloud.githubusercontent.com/assets/6330971/8441895/43d87894-1f49-11e5-8003-6d6550437ec8.png)

cc: @DFurnes @sheydari-ds

**Comment by DFurnes** [comment]
![screen shot 2015-06-30 at 5 13 26 pm](https://cloud.githubusercontent.com/assets/583202/8442191/54fd0cfa-1f4b-11e5-91e6-bcc588015390.png)

Having trouble reproducing this on my machine (tested in Safari & Chrome on OS X).

**Comment by angaither** [comment]
think we are good with this one :wink:
