### ISSUE TITLE
accessing legacy site

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4645]
@Bladt and I were able to access the legacy site from Google. 

Steps to recreate:
1. Google "Athletes Gone Good"
2. Click on second or third link (articles about [Olympian tweets](http://217989-www5.dosomething.org/blog/athletes-gone-good-qa-with-kobe-bryant) and [Kobe Bryant](http://217989-www5.dosomething.org/blog/athletes-gone-good-Olympian-tweets-of-the-week))
3. Click around the site

The links start with http://217989-www5.dosomething.org/

I'm able to access it on my phone, but am getting this screen when trying to access on desktop:

![image](https://cloud.githubusercontent.com/assets/6330971/8459413/04ce51e4-1feb-11e5-93b2-3eb3e273de2d.png)

@mshmsh5000 @sheydari-ds thoughts?

**Comment by ghost** [comment]
Changed the domain so that anything that references that URI goes to www.athletesgonegood.com. DNS is propagating, but should be fully live by tomorrow at latest.

**Comment by angaither** [comment]
boom, already done.
