### ISSUE TITLE
Testing plan

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#4646]
DOn't forget this

**Comment by joolaay** [comment]
arf

**Comment by joolaay** [comment]
@angaither I made an issue for this last week, just adding you now. #woop

**Comment by angaither** [comment]
WEE!

**Comment by joolaay** [comment]
Relevant testing plan? https://docs.google.com/spreadsheets/d/16YcysP9i8WtAnoocS_D1k2qxeUIiulDAz4yErdZSi5w/edit#gid=0

**Comment by mikefantini** [comment]
@angaither I tried running through this doc but was blocked by #4751. 

can someone have Toyin run through this on http://staging.beta.dosomething.org/campaigns/hot-module once #4751 is fixed and deployed to staging? I created a Trello card for this here: https://trello.com/c/d4LVMrcL

I imagine that the overrides might not work (set in the custom settings) but this doesn't really matter for August.
