### ISSUE TITLE
Override Feature Input Doesn't Register

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4652]
On Senior Socials on staging (http://staging.beta.dosomething.org/node/9/), there is one approved report back, the total approved quantity correctly registers 15. However, inputting 1000 into the override field and running cron doesn't change the TAQ in any of the following places:

http://staging.beta.dosomething.org/campaigns/senior-socials
http://staging.beta.dosomething.org/node/9/custom-settings
http://staging.beta.dosomething.org/node/9/rb/reviewed

TAQ should say 1015.

**Comment by angaither** [comment]
@deadlybutter the count on the view page should be pulling from both the `sum_rb_quantity` and the `sum_rb_quantity_override`
it's doing that [here](https://github.com/DoSomething/dosomething/blob/8d923bde81bfbbec77f15988d6d8b5423a60c640/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L503)
but then it's not passed into the tpl correctly
