### ISSUE TITLE
give editors access to Goal Settings group on Custom Settings

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4653]
@angaither assign off to @deadlybutter if you'd like

**Comment by angaither** [comment]
This form is currently in `dosomething_helpers` the easiest thing to do is give editors access to the whole form (which includes the shipment form, styles form and this goal setting form)
Otherwise we will need to break this section out into it's own form. 

thoughts @julielorch (cc @mikefantini)

**Comment by angaither** [comment]
I gave Michaela admin access, so she can edit/view the goal settings. We are going to do this for now and change form permissions if/when we decide others need access to it.
