### ISSUE TITLE
Graph: Cross Browser Issues

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4695]
The graph is showing up as blank in IE8, 9, and Safari. 

See trello for screenshots: https://trello.com/c/v4P7UsBb/77-hot-module-looks-different-in-different-browsers

**Comment by sbsmith86** [comment]
@julielorch Can we talk about IE8? There is a lot that is not supported and I'm not sure there is much we can do about it. IE8 is looking like this. I want to get an idea of what we absolutely need and what we can not worry about in IE8.

![screen shot 2015-07-21 at 5 21 21 pm](https://cloud.githubusercontent.com/assets/1700409/8813040/1f5663ba-2fce-11e5-9efb-bc8753484b57.png)

**Comment by DFurnes** [comment]
My 2¢: I think this is a perfect example of progressive enhancement. All the important information is still there & nothing appears broken to the user. IE 8 is only ~1% of our traffic, so let's be careful not to spend too much engineering time on it. :)

**Comment by mikefantini** [comment]
+1 to @DFurnes's comments. As long as the other browsers are set and all that remains is IE8 looking like this I think we should be good to close out this issue.

**Comment by sbsmith86** [comment]
great, closing.
