### ISSUE TITLE
Update Reportback class __construct()

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4703]
The `__construct()` function in the `Reportback` class currently does a lot of extra work whenever the class is instantiated. This is useful for when creating a new Reportback, but conflicts when just loading reportbacks via the class and the construct method always runs first. So best to move this code out of the constructor to avoid having multiple of the same DB queries happening in a single instantiation. If loading Reportbacks in other template code, then replace code to use new class methods to get Reportback data (`get()` or `find()`).

**Comment by angaither** [comment]
same as #6167 we don't need this
