### ISSUE TITLE
Homepage video takeover

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#4706]
@kerigoff requested a video takeover on the homepage for when we hit 4,000,000 members. Since we don't have any functionality built out for this and this needs to be delivered on an extremely short timeline, I think our best solution is to just use Optimizely.

Example with our "big foot" video:
![screen shot 2015-07-20 at 4 19 20 pm](https://cloud.githubusercontent.com/assets/583202/8786262/1692e79a-2efb-11e5-896e-192e56e3ab7d.png)

``` js
window.jQuery('.header--home').append('<video src="https://www.dosomething.org/sites/default/files/BigFoot.mp4" autoplay="" loop="" poster="https://www.dosomething.org/sites/default/files/styles/1440x810/public/Screen%20Shot%202014-12-02%20at%2011.03.39%20AM.png?itok=GxnGXCue"></video>');
```

...okay, maybe a picture isn't the best demonstration of a video, but y'know. :sweat_smile: 

We also have the option of hiding the campaign finder, and adjusting padding depending on the video that we're placing in the header area:

![screen shot 2015-07-20 at 4 22 46 pm](https://cloud.githubusercontent.com/assets/583202/8786348/90678d0a-2efb-11e5-977c-83126138c838.png)

``` js
// in addition to the above...
window.jQuery('.finder--form').remove();
window.jQuery('.header--home').css('padding', '168px 12px 120px');
```

I'm going to keep this issue open so we can track/discuss this project as we get more information.

/cc @weerd @deadlybutter

**Comment by itsjoekent** [comment]
I know this was raised earlier but Im gonna say it again, having multiple videos on the homepage might be distracting / be to much going on. 

A solution I've seen to this used on other sites is by default the header video is playing, but if the mouse hovers over another tile using video, the header video stops and the campaign tile plays instead. this requires more JS logic but will probably load a lot quicker and make it a better user experience

(my 2 cents)

(example: giphy http://giphy.com/page/2 )

**Comment by DFurnes** [comment]
Updated snippet from tweaking things some more in the web inspector...

```
window.jQuery('.header--home').html('<div class="wrapper"><h1 class="header__title" style="font-size: 72px;line-height: 0.9;text-align: center;">Join 4 MILLION members.</h1><h2 class="header__subtitle" style="font-weight: 800;font-size: 32px;margin-top: 24px;-webkit-transform:rotate(-3deg);text-align: center;">F*ck Yeah!</h2></div><video src="http://0.0.0.0:8080/4million.mp4" poster="http://0.0.0.0:8080/4million-poster.jpg" autoplay="" loop=""/>').css('padding', '264px 12px 216px').css('background-image', "url('http://0.0.0.0:8080/4million-mobile.jpg')").removeClass('header--home').addClass('header--4million');
```

![screen shot 2015-07-21 at 4 21 24 pm](https://cloud.githubusercontent.com/assets/583202/8811535/8d59228a-2fc4-11e5-9889-0f7e1069a015.png)

**Comment by itsjoekent** [comment]
this is so hacky, but the result is amazing so I approve

**Comment by DFurnes** [comment]
![hello my name is hack](http://www.pocketfullofliberty.com/wp-content/uploads/2014/01/Hack1-1024x717.jpg)

**Comment by DFurnes** [comment]
@sheydari-ds We need to find a place to host the video, poster image, and mobile fallback image for the duration of the takeover. What's the easiest option?

**Comment by angaither** [comment]
you could upload it to the droops...

**Comment by DFurnes** [comment]
Where dat?

**Comment by ghost** [comment]
Sure, we can put it in the files dir directly. I'll be by shortly.

**Comment by DFurnes** [comment]
Done. Closing! :hammer:

**Comment by itsjoekent** [comment]
are we still going to build out a drupaly way of doing this?

**Comment by DFurnes** [comment]
I think it's somewhere on the roadmap. We can make issues for that once its scope is worked out in the product process.
