### ISSUE TITLE
write a script that retroactively fixes flagging issue

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4713]
Refs #4529 

For the hot module write a script, or a cron, or a jenkins job that goes checks the flagged status and fixes it.
We can do this to only monitor the 4/5 campaigns that are in the hot module or, just all the campaigns. Probably makes more sense to do it for all of them.
This kind of papers over the issue of why it's happening, and we wouldn't have examples anymore... but it should retroactively "fix" the issue. 

cc @mshmsh5000 @sheydari-ds @julielorch @mikefantini

**Comment by angaither** [comment]
The only issue with this fix, is we will won't have the reason that things are getting flagged. 

So this for sure shouldn't be the final solution to #4529

**Comment by mshmsh5000** [comment]
Can we log and then fix? We should at least keep a record for auditing & analysis.

**Comment by angaither** [comment]
We can add that in the future, but we don't have it for anything that's previously been flagged
