### ISSUE TITLE
Display of readable timing goal is off

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4714]
The end date that is set is displaying incorrectly on the hot module front end

see: https://trello.com/c/uxM85STK/80-the-timing-is-off

**Comment by itsjoekent** [comment]
Two points so far

1) There was a small typo on line 127 and that fixed one bug. 
2) The "hours" bug seems is driving me nuts. Debug process so far below, 
- I set the campaign end date to be today and it said the campaign ended in 9 hours :ok: 
- I then set the campaign end date to be on this date in August, saved the node and refreshed. Still displays the campaign ends in 9 hours. 
- I dsm the object containing the time difference, its the one for the old date.
- I saved the node again just to make sure, still broken.
- I dsm the end date object, shows the correct end date, but the difference is still the old one. wtf is going on.

**Comment by angaither** [comment]
cached?

**Comment by itsjoekent** [comment]
just tried, nope

**Comment by itsjoekent** [comment]
I just reproduced the bug on a different campaign node. Changed the end date to be the same day as today, calculates hours correctly. then set the end date to next month. the date saves but the difference still thinks it is ending today.

**Comment by itsjoekent** [comment]
WOW this just keeps getting weirder. So as I said before re-saving it does nothing, however if you change the day of the month, everything updates.

**Comment by itsjoekent** [comment]
not sure how to fix the drupal saving bugs, I think thats out of the scope of this issue. as for the original linked issue... Solved the bug with days left not displaying correctly sometimes and also fixed hours being too short. Problem was I only displayed the difference in hours and didn't account for the hours in the days between. PR comin up in a sec

**Comment by angaither** [comment]
Toyin is still seeing this issue 
Has the end date 4 days away, but the graph displays that there are 3 days left
http://staging.beta.dosomething.org/campaigns/hunt-day-2-trash-scavenger-hunt

**Comment by deadlybutter** [comment]
already see the bug I think,

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L122

pretty sure thats supposed to be using $difference, not $end date

**Comment by itsjoekent** [comment]
wait no, the problem is technically not a bug actually. the difference in days is correct, its just that theres hours in between (so in reality its not 4 days, its 3 days and 6 hours or whatever). Ill just round the day up 1 to account for this

**Comment by itsjoekent** [comment]
talked with @lkpttn -- this is not a bug and is the desired functionality (rounding down verses up). closing the issue
