### ISSUE TITLE
Hard-coded base_url borks things in non-sandbox installs

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#472]
Hard-coding `$base_url` [here](https://github.com/DoSomething/dosomething/blob/dev/settings.php#L281) and anywhere else is not sustainable outside local sandboxes.

I suggest adding a detect-include for a local settings file at the end of settings.php, a la

``` php
// Include local settings file if it exists.
if (is_readable('sites/default/settings.local.php')) {
  include_once('sites/default/settings.local.php');
}
```

Use this to override all non-sandbox config: e.g., DB, memcache/Redis, securepages config, Varnish.

That [ENVIRONMENT switch in the current settings.php](https://github.com/DoSomething/dosomething/blob/dev/settings.php#L572) seems overly complicated, and commits us to versioning instance-specific config.

@desmondmorris @aaronschachter @angaither @blisteringherb looking for opinions here.

**Comment by mshmsh5000** [comment]
Huh. And even when I override all dev.dosomething.org-related settings on stage, I'm still seeing the public theme broken because of hard-coded dev URLs:

http://stage.dosomething.org/

Secure site renders fine, though.

**Comment by blisteringherb** [comment]
I like this.  I prefer being able to override certain settings as needed without having to version those changes.

**Comment by mshmsh5000** [comment]
@desmondmorris Any reason to keep the ENVIRONMENT switch stuff? Want to make sure we understand the thinking behind this before we change our minds.

**Comment by desmondmorris** [comment]
@mshmsh5000  I see no reason why what you have suggested will not work for us.  I think this approach plus using actual system ENVVARS will cover all of the bases

**Comment by mshmsh5000** [comment]
@desmondmorris K, but using actual ENVVARS for what, then? Once I change this, I don't know of any other place where we're referring to [this](https://github.com/DoSomething/dosomething/blob/dev/settings.php#L573). I'll keep that declaration in regardless.

**Comment by desmondmorris** [comment]
So for instance, we could stash things like: `MYSQL_HOST`, `MYSQL_PASS`, `MYSQL_USER` etc, inside of actual environment vars in Linux.  These can default to something generic which possibly hit most cases, ie dev & local.  These settings would be unique to each server.  This way we can use the same exact settings file for every environment.  We would just need to set these vars on the environments.  You can always override if necessary.  Its a pattern common in PAAS.

we could do things like this:

```
$databases = array (
  'default' => 
  array (
    'default' => 
    array (
      'database' => getenv('MYSQL_DB_NAME') || 'dosomething',
      'username' => getenv('MYSQL_DB_USER') || 'root',
      'password' => getenv('MYSQL_DB_PASS') || '',
      'host' => getenv('MYSQL_DB_HOST') || 'localhost',
      'port' => getenv('MYSQL_DB_PORT') || '3306',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);

```

Not a must have, but it could be helpful

**Comment by desmondmorris** [comment]
We should be able to kill that declaration regardless at this point

**Comment by mshmsh5000** [comment]
Got it, makes sense. Let's cross that bridge when we come to it. For now, devs should only have to look one place to find important settings.
