### ISSUE TITLE
Only changing the month when updating the season end doesn't update

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#4720]
Very weird to describe, process in which I encountered / discovered it is in the comments here: https://github.com/DoSomething/dosomething/issues/4714#issuecomment-123751304

**Comment by angaither** [comment]
just to update with a summary here

> strange things happen if you change the month of a high season end date, but not the day

**Comment by angaither** [comment]
cc @namimody

**Comment by namimody** [comment]
As a workaround for the moment, say the current end date is Oct 31 2015, and you want it to be Dec 31 2015. Per Joe's comment, changing just the month will not work (the change will not be reflected on the user facing view of the site). If you change the date to, say, Nov 5, 2015, save, and then change to Dec 31, 2015 and save, you will see the change you're looking for.
