### ISSUE TITLE
Add date fields to campaign template for mobile app support

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4723]
The mobile app needs campaigns to show up for a month, so it needs a specific start/end date. This doesn't alway align with (and will conflict) with the hot module if we use the high season field.

Steps: 
- [x] Add `field_mobile_app_date` - this should have both a start and end date
- [x] Create a new field group called `Mobile App`
- [x] Move the checkbox for `field_on_mobile_app` into the mobile app field group
- [x] Add the `field_mobile_app_date` to the api response for a campaign

@chloealee Once you've added the field to the node, you will have to export them using drupal features!
Also, the fields will need to be exposed in the api @weerd has been working on

**Comment by aaronschachter** [comment]
@angaither @chloealee - Would it be better to build a single `field_mobile_app_date` with start/end, like `high_season` and `low_season` ? Keeps it consistent...

**Comment by aaronschachter** [comment]
I think it'd be nice to have a completely new Field Group for Mobile App too. We can move the "On mobile app" field there. Sounds like we may want to repurpose that field (or build a new renamed one) for the ability to have app-only campaigns.

**Comment by angaither** [comment]
Yeah @aaronschachter you're right. I'll update the issue! thanks!

**Comment by weerd** [comment]
Would make things easier on the response side if it behaves like the `high_season`, `low_season`, and then maybe we can generalize the date grabbing method in the `Campaign` class to apply to both :)

**Comment by angaither** [comment]
Yup, that's the goal @weerd :smile:

**Comment by aaronschachter** [comment]
@weerd @chloealee When exporting the new field to features, you'll also want to export the new field group too (for Mobile app)

**Comment by chloealee** [comment]
okay thanks @aaronschachter !
