### ISSUE TITLE
Check campaign high seasons in the db

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4724]
make sure no other campaigns besides these 10 have high season date set for August 1st 2015 to August 31st 2015. can be done through sql query

**Comment by angaither** [comment]
@julielorch I found a few campaigns who have the high season set in august, we will want to remove the ones we don't want in the hot module

| nid | title | high season start date | high season end date |
| --- | --- | --- | --- |
| 28 | Comics to the Rescue | 2015-08-01 | 2015-10-15 |
| 32 | 13 Gallon Challenge | 2015-08-01 | 2015-08-31 |
| 2015 | Fight Fire With Cookies | 2015-08-01 | 2015-09-10 |
| 2089 | Visionary Volunteer | 2015-08-01 | 2015-08-31 |
| 2900 | You’re Doing It Wrong | 2015-08-01 | 2015-08-31 |
| 3743 | Storm Drain Street Art | 2015-08-01 | 2015-08-31 |

refs #4651

**Comment by joolaay** [comment]
@angaither great should I remove them?

**Comment by angaither** [comment]
yes please @julielorch

**Comment by angaither** [comment]
:cool: the correct 4 campaigns are the only ones displaying a hot module starting August 1, going to close this issue
