### ISSUE TITLE
Graph: Goal line leaves chart

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4727]
Removing the y-axis scale messed up where the goal line gets placed on the graph. If the highest data point is no where near the goal, then the graph doesn't scale to show the goal line. 

Probably need some scaling math that takes into consideration the highest data point so far and scales based on that and the goal.

**Comment by mikefantini** [comment]
adding some photos to make sure I'm seeing the same issue you are @sbsmith86 

[Hunt Day 2](http://staging.beta.dosomething.org/campaigns/hunt-day-2-trash-scavenger-hunt?source=node/1165):
![image](https://cloud.githubusercontent.com/assets/6330971/8859103/40c2369c-3149-11e5-80d3-9a5384f3894b.png)

[Hunt Day 1](http://staging.beta.dosomething.org/campaigns/hunt-day-1-superstressface?source=campaigns):
![image](https://cloud.githubusercontent.com/assets/6330971/8859110/47ce25a4-3149-11e5-866f-0ab543061313.png)

**Comment by toyrobs** [comment]
this is still a problem, now the problem is the scale does not   show up 
![screen shot 2015-07-24 at 1 21 14 pm](https://cloud.githubusercontent.com/assets/11587372/8880618/26855e20-3208-11e5-8e06-59dfd03f5ef9.png)

**Comment by mikefantini** [comment]
also worth keeping an eye on whether that problem persists in the image I included where the goal line seems to just disappear entirely
