### ISSUE TITLE
bring back previous view of /node/[nid]/rb/reviewed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4728]
![image](https://cloud.githubusercontent.com/assets/6330971/8859524/cfacf2a0-314b-11e5-967a-b1b6315dcdb1.png)

honestly can't recall off the top of my head everything that was included but resembled the inbox view

not sure when this broke but must have been since the last prod deploy

![image](https://cloud.githubusercontent.com/assets/6330971/8859694/f2c56474-314c-11e5-8f30-e214f7d04be4.png)

**Comment by itsjoekent** [comment]
Ill revert back to an older commit and see what it looked like (and figure out what changed since)

**Comment by angaither** [comment]
:cool: thanks @deadlybutter

**Comment by itsjoekent** [comment]
hmm, problem reverting back b/c the latest work Diego did doesn't exist and it breaks things

![screen shot 2015-07-23 at 4 24 15 pm](https://cloud.githubusercontent.com/assets/897368/8861253/4a7970ca-3157-11e5-8e25-887035a3e208.png)

**Comment by itsjoekent** [comment]
Ill try fiddling around to see if i can hack it to work

**Comment by angaither** [comment]
I think if you cc all (or you might possibly have to rebuild) it should work without diego's stuff

**Comment by itsjoekent** [comment]
this is what I believe the page is supposed to look like, I reverted back to commit 9e9d85c7601d2b26f3f0ce3abc0974c09f2743e5 which is from several days ago

![screen shot 2015-07-24 at 10 31 04 am](https://cloud.githubusercontent.com/assets/897368/8876676/1c256bfa-31ef-11e5-8970-70828c3afd1e.png)

**Comment by itsjoekent** [comment]
so the only thing thats changed recently (8 days ago) thats related to this is the following commit https://github.com/DoSomething/phoenix/commit/d4e91e479a4ca31930070c544be72dffe8e92694#diff-67bc724f9b8588a3785047d82c4f1510R310

Im guessing in the switch to reportback item a variables usage changed and it broke the admin review form? ill keep digging

**Comment by aaronschachter** [comment]
Yes, that change definitely could have broken this view. If you inspect the Reportback Files (I think thats what its named) view in the Drupal admin views UI.. you will probably see labels like "Broken handler" for where the Reportback Files were. cc @weerd
