### ISSUE TITLE
Hot module json not sending correct max

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4730]
The query that selects the max date from the hot module is actually not returning the most recent timestamp

```
 SELECT quantity, max(from_unixtime(timestamp)) as maxdate
 FROM dosomething_reportback_progress_log
 WHERE nid = :nid
 GROUP BY date(from_unixtime(timestamp)); 
```

**Comment by angaither** [comment]
I think this requires a subquery to get the max timestamp along with the corresponding data, because what I currently have only selects the max timestamp

**Comment by sbsmith86** [comment]
ahhhhhh i see that now

**Comment by angaither** [comment]
ahhh, also the max(quantity) should work!
