### ISSUE TITLE
Include third party opt_in values in Retrieve a campaign endpoint value

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4735]
The "Retrieve a campaign" endpoint (https://github.com/DoSomething/phoenix/wiki/API#retrieve-a-campaign) needs to include the Third Party opt_in values for MailChimp and Mobile Commons. 
- `mobilecommons_opt_in_path`
- `mailchimp_grouping_id`
- `mailchimp_group_name`

The values are associated / administered via the Drupal admin UI: https://www.dosomething.org/admin/config/dosomething/opt_in. The values are stored in the `dosomething_helpers_variable` table:

```
mysql> explain dosomething_helpers_variable;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| entity_type | varchar(255) | NO   | PRI |         |       |
| entity_id   | int(11)      | NO   | PRI | 0       |       |
| name        | varchar(255) | NO   | PRI |         |       |
| value       | blob         | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
```

Values of interest:

```
mysql> select * from dosomething_helpers_variable where name like '%opt_in%';
+-------------+-----------+-----------------------------------+--------+
| entity_type | entity_id | name                              | value  |
+-------------+-----------+-----------------------------------+--------+
| node        |       362 | mobilecommons_opt_in_path         | 165501 |
| node        |       955 | mobilecommons_opt_in_path         | 163587 |
| node        |      1173 | mobilecommons_opt_in_path         | 167197 |
| node        |      1192 | mobilecommons_opt_in_path         | 171303 |
| node        |      1194 | mobilecommons_opt_in_path         | 167401 |
...
```

and

```
mysql> select * from dosomething_helpers_variable where name like '%mailchimp%';
+-------------+-----------+-----------------------+---------------------------+
| entity_type | entity_id | name                  | value                     |
+-------------+-----------+-----------------------+---------------------------+
| node        |      1172 | mailchimp_grouping_id | 10637                     |
| node        |      1172 | mailchimp_group_name  | TheHunt2014               |
| node        |      1173 | mailchimp_grouping_id | 10637                     |
| node        |      1173 | mailchimp_group_name  | ThumbWars2014             |
| node        |      1194 | mailchimp_grouping_id | 10637                     |
| node        |      1194 | mailchimp_group_name  | TheHunt2014               |
...
```

The `dosomething_helpers_get_variable($entity_type, $entity_id, $var_name)` function appears to be how to access the table within the DS app: https://github.com/DoSomething/phoenix/blob/9bce4a77ab5603c44f5d8ae989b0c1789ea5be22/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.variable.inc#L270-L284

**Comment by aaronschachter** [comment]
I'd advise that we do not expose this data to the public.

**Comment by deezone** [comment]
Which means this should be a username / password protected endpoint or something else? Please advise a solution other than not to do it.

Perhaps an alternative is to return the opt_in values when a POST is made to a campaign signup? https://github.com/DoSomething/phoenix/wiki/API#campaign-signup

As things currently stand, user imports from co-marketing partners Teen Life and Her Campus are signed up to campaigns. In the case of Teen Life, the campaigns change over time. Currently the values are hardcoded in a Message Broker configuration file.

This PR is an effort to deal with the current situation of a tightly coupled / dependency in storing these values in a Message Broker configuration file. When these values are added or changed in the Drupal app the related Message Broker functionality has no way of knowing.

What is the potential harm in an already publically exposed endpoint returning settings to third party services that require an API key to access?

**Comment by weerd** [comment]
I chatted with @mshmsh5000 end of last week regarding API security audit. I'm going to working on a bit of that this week and can likely address this item then. It might just be that a request to retrieve a campaign, when admin, can include that information?

**Comment by itsjoekent** [comment]
@DeeZone In general it's just bad practice to reveal any backend configuration to the public. I think a good solution to this problem would be to expose the opt-in values (on this endpoint) if the api request is made by an authenticated admin.

**Comment by aaronschachter** [comment]
Yep, I meant just behind a username/pass that should have access to those values @DeeZone

**Comment by deezone** [comment]
@weerd I think the concerns would be addressed by providing the values in the return values here:

> Perhaps an alternative is to return the opt_in values when a POST is made to a campaign signup? 
> https://github.com/DoSomething/phoenix/wiki/API#campaign-signup

This provides a secure endpoint and the values would be most value after a user campaign signup from the Message Brokers perspective.

Let me know if this makes sense and I'll update the original issue description.

**Comment by weerd** [comment]
Gotcha. I haven't dealt much w/ the `POST` end of things on Campaigns, but it's something I could look into. I need to implement some security stuff w/in the `GET` requests anyhoo, so I may look into that first to get the ball rolling.
