### ISSUE TITLE
SMS webform *Know it* section missing from the Admin View

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#4744]
![screen shot 2015-07-27 at 4 55 39 pm](https://cloud.githubusercontent.com/assets/6331017/8917492/5680a538-3480-11e5-90a5-d90488736d09.png)

Hi - the _Know it_ section is MIA, so admins can't edit the Problem or Solution sections on SMS games. Needed for Aug 1 launch of bully text.

**Comment by itsjoekent** [comment]
@mikefantini messaging you to make sure you know about this change #knowit
