### ISSUE TITLE
Graph dates not corresponding with rb submission dates

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4747]
Just set [Banned Books Club](http://staging.beta.dosomething.org/campaigns/banned-books-club) to be hot from Jan 1 - July 31 2015. It makes sense that the progress is 8, but [these reportbacks](http://staging.beta.dosomething.org/node/4/rb/reviewed) occurred earlier in 2015. Not quite sure why they are showing up as having just happened in July on the graph:

![image](https://cloud.githubusercontent.com/assets/6330971/8922742/1d0bc190-34b5-11e5-9c1a-bd2dd950f8b9.png)

cc: @angaither @julielorch

**Comment by mikefantini** [comment]
is this because the graph starts as soon as it's put into the hot module?

provided we don't want to retroactively put anything as hot (i.e. start the hot season at a date in the past) then this won't actually be an issue. and I can't think of any reason we'd want to do this. leaving this issue here though so this is documented.

**Comment by angaither** [comment]
The graph doesn't take the date of the reportback into account at all, it just takes the total quantity

**Comment by sbsmith86** [comment]
@angaither @mikefantini Could it also be because we weren't logging reportbacks in the new log table before July? So, that table only has totals starting in July and that is what we are using the query to create the data object for the graph.

**Comment by angaither** [comment]
nah, that still just searches all reportbacks, no matter what the date they were submitted is.

**Comment by sbsmith86** [comment]
@angaither Right, so the actual log won't have the total reportbacks we had on Jan 15, 2015,for example? Because we weren't logging that info at that time.

**Comment by angaither** [comment]
The [query](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.cron.inc) that runs to add things to the log takes all reportbacks into account, no matter what date they were submitted. So there won't be a record of what the total quantity was on Jan 15, but a reportback submitted on that day will be included in the total quantity.

**Comment by sbsmith86** [comment]
@angaither yea so that is why when @mikefantini set the hot phase to be a date before we started logging, the graph only shows data from July on. 

@mikefantini So in the rare cases we need to set the hot phase to a time in the past, we will see the data on the graph from when we actually started logging the total reportbacks each day (so from July, 2015 on)

**Comment by angaither** [comment]
AH. right. yes yes yes. Sorry misunderstood the issue!

**Comment by mikefantini** [comment]
sweet sounds good to me! thanks for the explanation @angaither @sbsmith86 closing this one out
