### ISSUE TITLE
live query was resetting value set by cron, causing quantity displayed to be off

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4748]
[Bake Sales for Babies](http://staging.beta.dosomething.org/node/1467/rb/reviewed?status=All&flagged_reason=All&promoted_reason=All&order=quantity&sort=desc) should have a Total Reportback Quantity of 3917 but it's stated as 717. The 717 seems to be excluding [this reportback](http://staging.beta.dosomething.org/admin/reportback/1172) but not sure why since it's set as promoted and doesn't seem to have had any changes to it.

[Baby It's Cold Inside](http://staging.beta.dosomething.org/node/1581/rb/reviewed) has a reportback total of 100 even though there are no reviewed reportbacks. This matches the quantity that is in the inbox.

[Wildlife Cards](http://staging.beta.dosomething.org/node/689/rb/reviewed) has a reportback total of 888 even though there are no reviewed reportbacks. This matches the quantity that is in the inbox.

Found these just reviewing some campaigns that have old reportbacks attached to them so unfortunately not exactly sure how to reproduce. 

However, given these discrepancies, it's worth someone manually checking that the math currently checks out for the Total Reportback Quantity on the campaigns that are going hot  August 1st so that we feel confident that this number is starting off correctly.
- Visionary Volunteer - https://www.dosomething.org/node/2089/rb
- Storm Drain Street Art - https://www.dosomething.org/node/3743/rb
- Justice for Elephants - https://www.dosomething.org/node/1536/rb (is this Lead the Stampede?)
- Get Lucky is a new campaign so we should be fine here

**Comment by angaither** [comment]
@mikefantini yeah, anything that has reportbacks already, that will be included in the total. 
Is this issue the same as #4747 or is this about the numbers being incorrect because it's including non-reviewed reportback quantity in the total?

**Comment by angaither** [comment]
@deadlybutter can you take some time today looking into this?

**Comment by itsjoekent** [comment]
sure

**Comment by itsjoekent** [comment]
- in that first example its excluding a lot more than that 3K reportback. hmm.
- other two is the inbox count like you said.
- flagged campaigns still count towards the total count

edit: current guess / line of thinking is the 'sum_rb_quantity' helper variable is not being updated/set properly

**Comment by mikefantini** [comment]
yeah sorry if this was unclear, I was just pointing out some inconsistencies I was seeing in the Total Reporback Quantity.

The two issues I was seeing here were:
1. The reportback quantity on Bake Sales for Babies for some reason ignoring http://staging.beta.dosomething.org/admin/reportback/1172 and so the total was 3200 less than it should be.
2. Baby It's Cold Outside and Wildlife Cards counting reportback quantities that were not yet reviewed.

Each of these issues could be for a bunch of different reasons (maybe RB 1172 went from flagged to promoted but that change wasn't tracked and the system isn't properly counting it because things it's still flagged; maybe something weird is going on with reportbacks submitted by the app - the reportbacks that are being counted without being reviewed are from ds.test.aurora@gmail.com and ds-api@dosomething.org; maybe the basic principles of arithmetic as we know them are a farce).

Didn't have time to fully investigate and probably easier for someone who's not remote to dig in a bit more, but just wanted to raise the issue here AND make sure that we manually verify the quantity of the campaigns that we'll be putting in the hot phase before they go hot.

Not related to #4747.

**Comment by mikefantini** [comment]
@deadlybutter i'm only seeing the 3200 of http://staging.beta.dosomething.org/admin/reportback/1172 being improperly excluded. The only other quantity that is excluded is the 100 of http://staging.beta.dosomething.org/admin/reportback/2651 but that's intended funtionality since it's flagged.

can you explain what you mean by "in that first example its excluding a lot more than that 3K reportback. hmm."

![image](https://cloud.githubusercontent.com/assets/6330971/8935557/5977e08a-351b-11e5-9162-8072451b6c76.png)

**Comment by itsjoekent** [comment]
oh, I counted reportback items twice on accident, didnt realize it was the same reportback. yeah, then its only that 3200 one being excluded.

**Comment by itsjoekent** [comment]
alright, this was some kind of saving bug I think? I set it (the 3200 reportback we keep referencing) to approved, and then back to promoted and the total quantity is now correct.

**Comment by itsjoekent** [comment]
this RB also has the bug, was made yesterday and not net reviewed, but its going towards the total quantity 

http://staging.beta.dosomething.org/node/1360/rb

this is what the DB looks like for it

![screen shot 2015-07-28 at 11 51 46 am](https://cloud.githubusercontent.com/assets/897368/8936225/1400937c-351f-11e5-9d68-39d3eb3c5f25.png)

**Comment by itsjoekent** [comment]
so far I haven't been able to reproduce this bug locally, only happening on stage?

edit: also tried on an unpublished campaign on prod, couldnt reproduce there either..? 

edit: might have just reproduced it, standby.,, -- confirmed, was able to reproduce locally here http://dev.dosomething.org:8888/node/689/rb

**Comment by angaither** [comment]
put a temp fix in place with  #4773, need to figure out what is wrong with the query `dosomething_reportback_get_reportback_total_by_nid`

**Comment by mikefantini** [comment]
everything for the three campaigns listed above on staging and the four campaigns that are hot on production are looking good.

keeping this issue open just in case we need to do any cleanup or alternative solutions re: @angaither temp fix ^

**Comment by mikefantini** [comment]
closing out. once we fix the other issues in this milestone, we'll re-open if we see that numbers aren't adding up properly based on what's in the database.
