### ISSUE TITLE
admins can no longer change status of rb

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4749]
not sure if you guys purposefully made this change (can't see that documented anywhere in my quick check) but admins are no longer able to change their mind and change the status of a rb after reviewing it.

related to #4621 #4669 

cc: @julielorch putting into Hot Module 1.1 right now. If you want to change the prioritization totally your call.

**Comment by angaither** [comment]
@mikefantini I think this still works, you just have to go to the individual reportback to change the status.
http://staging.beta.dosomething.org/admin/reportback/1802

... not sure if that's different place (#4728) than where it was before, but the functionality is still there

**Comment by mikefantini** [comment]
welp that's embarrassing. definitely couldn't find it last night even after checking multiple times. carry on.
