### ISSUE TITLE
# of hours left should start at 48 hours for Hot Module

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4750]
![image](https://cloud.githubusercontent.com/assets/6330971/8923765/210c7790-34c3-11e5-8dea-d34052763174.png)

http://staging.beta.dosomething.org/campaigns/hot-module

Here it shows 71 Hours Left. Shouldn't this be 2 days left still

refs: #4714

**Comment by itsjoekent** [comment]
ah, this is that same issue we talked about yesterday because of the hours/days remaining (technically it started counting down at 2 days, but its 48 hours + 8 or however many are remaining). I'm gonna update the conditional to be hours based thus it wont start until its 48 or lower.
