### ISSUE TITLE
Undefined index on page loads

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4760]
Seeing lots of these in the logs on page loads

`Notice: Undefined index: dosomething_user_log_login in dosomething_user_preprocess_page() (line 18 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_user/dosomething_user.module).`

**Comment by itsjoekent** [comment]
on staging?

**Comment by angaither** [comment]
yeah, looks like that line should be `if(isset($_SESSION['dosomething_user_log_login']))`

**Comment by itsjoekent** [comment]
yep yep
