### ISSUE TITLE
Add support for last_name / LNAME for UK site

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#4767]
Related Trello card: https://trello.com/c/27Kxpe0B

The UK affiliate site has requested support for the last name to be submitted to their MailChimp account for user registrations. Currently the last name is collected on the UK user registration form with: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1062-L1068

The stored value is accessable with:

```
dosomething_user_get_field('field_last_name', $account),
```
- [ ] last name value needs to be added to the message broker payload at: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L457-L463

```
$params = array(
    'mailchimp_list_id' => dosomething_signup_get_mailchimp_list_id(),
    'email'             => $account->mail,
    'uid'               => $account->uid,
    'first_name'        => dosomething_user_get_field('field_first_name', $account),
    'last_name'        => dosomething_user_get_field('field_last_name', $account),  <-- ++++
    'birthdate'         => dosomething_user_get_field('field_birthdate', $account),
  );
```
- [ ] The dosomething_mbp `user_register` payload:
  https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_mbp/dosomething_mbp.module#L137

```
$payload['merge_vars']['FNAME'] = $params['first_name'];
$payload['merge_vars']['LNAME'] = $params['last_name'];  <= ++++
```
- [ ] `mbc-registration-email`
  https://github.com/DoSomething/mbc-registration-email/blob/master/MBC_UserRegistration.class.inc#L125-L127

```
        if (isset($messagePayload['merge_vars']['FNAME'])) {
          $subscriber['fname'] = $messagePayload['merge_vars']['FNAME'];
        }
        if (isset($messagePayload['merge_vars']['LNAME'])) {  <- +++
          $subscriber['lname'] = $messagePayload['merge_vars']['LNAME']; <- +++
        } <- +++
```
- [ ] The values submitted to MailChimp:
  https://github.com/DoSomething/mbc-registration-email/blob/master/MBC_UserRegistration.class.inc#L308-L324

```
        if ($newSubscriber['application_id'] == 'UK') {
          $mergeVars = array(
            'FNAME' => isset($newSubscriber['fname']) ? $newSubscriber['fname'] : '',
            'LNAME' => (isset($newSubscriber['fname']) && isset($newSubscriber['lname'])) ? $newSubscriber['fname'] . $newSubscriber['lname'] : '', <- +++
            'DOB' => isset($newSubscriber['birthdate_timestamp']) ? date('d/m/Y', $newSubscriber['birthdate_timestamp']) : '',
          );
        }
        else {
          $mergeVars = array(
            'UID' => isset($newSubscriber['uid']) ? $newSubscriber['uid'] : '',
            'FNAME' => isset($newSubscriber['fname']) ? $newSubscriber['fname'] : '',
            'LNAME' => isset($newSubscriber['lname']) ? $newSubscriber['lname'] : '', <- +++
            'MMERGE3' => (isset($newSubscriber['fname']) && isset($newSubscriber['lname'])) ? $newSubscriber['fname'] . $newSubscriber['lname'] : '',
            'BDAY' => isset($newSubscriber['birthdate_timestamp']) ? date('m/d', $newSubscriber['birthdate_timestamp']) : '',
            'BDAYFULL' => isset($newSubscriber['birthdate_timestamp']) ? date('m/d/Y', $newSubscriber['birthdate_timestamp']) : '',
            'MMERGE7' => isset($newSubscriber['mobile']) ? $newSubscriber['mobile'] : '',
          );
        }
```

**Comment by deezone** [comment]
@aaronschachter @angaither @DFurnes Any thoughts on why the user last name may have been excluded from the message payload? Trying to think of any potential gotchas by adding it back in for the UK MailChimp submissions.

**Comment by angaither** [comment]
@DeeZone not really sure what you're asking here. it looks like it isn't getting sent because it isn't included in the payload from Drupal. Is this issue to add it? It should work when it's added [here](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L457-L463)

**Comment by deezone** [comment]
@angaither  My question is if you can think of any reason why `'last_name' => dosomething_user_get_field('field_last_name', $account),` is not currently being set / used? 

I have a vague memory of it being a part of the payload in the past. Perhaps removed when it was clear it would not be collected in the US registration form? Just wondering if there's another reason that might cause problems.

At any rate, just want to get the issue in front of everyone just in case the obvious is not so obvious.

**Comment by angaither** [comment]
@DeeZone from what I remember I don't think we ever sent the last name to the mb payload, so I think we just will need to add it to the params array [here](https://github.com/DoSomething/phoenix/blob/7a1b83591f95a6f9c2e9b9fc95a9ec728c0a563d/lib/modules/dosomething/dosomething_user/dosomething_user.module#L457)

**Comment by deezone** [comment]
@angaither Thanks for your thoughts.

**Comment by angaither** [comment]
🇬🇧 ❌
