### ISSUE TITLE
progress and goal not showing on prod

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4770]
https://www.dosomething.org/node/1536:
![image](https://cloud.githubusercontent.com/assets/6330971/9019979/fef683c6-37c4-11e5-819e-590c0d904ad6.png)

https://www.dosomething.org/node/2089:
![image](https://cloud.githubusercontent.com/assets/6330971/9019981/148756d4-37c5-11e5-8201-12f30644c9f0.png)

@sbsmith86 - not exactly sure what's happening here, but let's touch base on this Monday

**Comment by angaither** [comment]
The theme setting `show_campaign_progress` needed to be checked as well :+1:
