### ISSUE TITLE
Zendesk ticket submission errors

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4780]
Currently the error message for when Zendesk ticket submission fails reads "Sorry, there was an error with your request. Please try again."

first step, let's update the text to say 
- [x] Sorry, there was an error with your request, please email help@dosomething.org and we'll get your question sorted out!

then
- [x] try to figure out what's going wrong, since we should be using an old version of [zendesk lib](https://github.com/DoSomething/phoenix/blob/7283c7965a699150070c22b8e4d526ed44f2533e/lib/profiles/dosomething/drupal-org.make#L294)

**Comment by mikefantini** [comment]
it looks like the last ticket that came in through the site was sent in on Jul 08 07:21 am

https://dosomethingorg1.zendesk.com/agent/tickets/75843

**Comment by mikefantini** [comment]
@DFurnes not sure if this is helpful or not ^

**Comment by DFurnes** [comment]
Looking at our deploy logs for July, our two production deploys during that time period were `v0.5.13` on July 2nd, and `v0.5.22` on July 16th. Here's the [commit diff](https://github.com/DoSomething/phoenix/compare/v0.5.13...v0.5.22) between those tags. From skimming it though, it doesn't look like anything changed that would affect Zendesk...

@mikefantini How many support messages do we average per week? Is it possible that it broke later and we just don't receive messages often enough to specifically pinpoint?

**Comment by DFurnes** [comment]
From poking around on local dev, it seems like we're getting a bad response from their API in [dosomething_zendesk_verify_zendesk_user](https://github.com/DFurnes/phoenix/blob/zendesk-link-error/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module#L343-343).

```
GET /api/v2/search.json?query=type%3Auser+email%3Adfurnes%40dosomething.org
HTTP/1.1 401 Unauthorized
```

Is it possible our account credentials are just out of date?

**Comment by DFurnes** [comment]
It looks like the account that we use for Zendesk API access is Marah's personal account.

@marahml Is it possible you changed your account password at some point and maybe your API tokens were invalidated as a security precaution?

**Comment by angaither** [comment]
We should probably use the ds-tech account for API access

**Comment by DFurnes** [comment]
@angaither Agreed. Switching the API email to `tech-support@dosomething.org` seemed to fix things on my local. Going to try changing it on production as well.

**Comment by DFurnes** [comment]
Verified working now on production. Closing! :hammer:

/cc @mikefantini 

![screen shot 2015-08-04 at 1 38 25 pm](https://cloud.githubusercontent.com/assets/583202/9067893/1a94c1b0-3aae-11e5-8ba1-924862f94c2c.png)

**Comment by mikefantini** [comment]
you're a king @DFurnes :crown:
