### ISSUE TITLE
tips on action page in do it section aren't displaying

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4788]
clicking on 2nd and 3rd tips in the Do It section doesn't reveal the tip

https://trello.com/c/PP9igkzA

@DFurnes can you please take a look?

**Comment by DFurnes** [comment]
Released a patch to [Forge](http://forge.dosomething.org/#tabs) that will be applied on next deploy.

**Comment by DFurnes** [comment]
And the fix is deployed on staging!
