### ISSUE TITLE
mobile common opt-ins aren't working besides SMS Games

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4789]
Looking at Mobile Commons Reports it appears to have happened on Monday 8/3/2015

General Site Registration: https://dosomething.mcommons.com/campaigns/134280/opt_in_paths/164905/report

General Campaign Log In:
https://dosomething.mcommons.com/campaigns/134280/opt_in_paths/164453/report

Thumb Wars:
https://dosomething.mcommons.com/campaigns/134280/opt_in_paths/179762/report

GTFO:
https://dosomething.mcommons.com/campaigns/134280/opt_in_paths/181124/report

happening on staging and production.

you can test by signing up for http://staging.beta.dosomething.org/campaigns/fantini-test with an account that is between 13-25 years old and has a cell phone number associated with it

cc: @sergii-tkachenko @DeeZone @angaither

**Comment by mikefantini** [comment]
from @sergii-tkachenko: last sms registration in the log
------- MBC_RegistrationMobile START #25999 - Sun Aug 2 22:36:19 EDT 2015 -------

**Comment by sergiitk** [comment]
Turned out `mbc-registration-mobile` consumer wasn't started in `mbc-php`.
Fixed it with `sudo start mbc-registration-mobile`.

Note: we need some kind of process monitoring for these.

**Comment by angaither** [comment]
seems like this was fixed, but never closed.

**Comment by sergiitk** [comment]
:+1:
