### ISSUE TITLE
Reportback: Security

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#479]
- [x] Sanitize quantity and why_participated fields
- [x] Prevent manipulation of rbid in browser to save to a different reportback

Having hidden form fields on the reportback form for rbid and nid means a web dev user could open up firebug, change the rbid or nid values, and write to the wrong records.

**Comment by aaronschachter** [comment]
Removing "Thursday" label, the user-submitted fields are now sanitized when staff views a reportback.

**Comment by barryclark** [comment]
@aaronschachter Backlogging this for now, as we don't need it for Tuesday. Thanks! :beers:
