### ISSUE TITLE
SQL error on running database update

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#4792]
When running `drush updb`, I got the following error. It did not seem to cause either of the queued migrations (`dosomething_helpers_update_7008` and `dosomething_reportback_update_70029`) to fail.

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'node-4-sum_rb_quantity' for key 'PRIMARY'
```

/cc @angaither

**Comment by angaither** [comment]
I think we are ok with this one, as it's already run on stage & prod.
