### ISSUE TITLE
Google Analytics: Fender Refactor

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4793]
I think we should refactor how we implement google analytics on the front end. Documenting it here for discussion. 

My idea is that we come up with some standard class names and data attributes to use and then create a function that sends listens to click events on that class and sends different info to GA based on what data attributes it has?

For example, if tracking clicks we could simply do: 

`<a href="http://www.yerp.com" class="ga-click" data-event="share" data-type="facebook" data-module="problem statement" />`

Thoughts? (naming is just for example, im not sure what better names should be) @DoSomething/front-end

**Comment by DFurnes** [comment]
:tada: 

Yeah, this is super needed. It'd also be nice to have this create corresponding [Optimizely custom events](https://help.optimizely.com/hc/en-us/articles/200039925-Custom-event-goals) so that the data team can use those if they need.
