### ISSUE TITLE
reportback inbox submission query retrieval issue

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4797]
watched Jess review 25 FIDs on node 2805. here is [a doc](https://docs.google.com/a/dosomething.org/spreadsheets/d/1R1EOY3TEI1_eJ_otK6DftkTicaTQeNBf7g4R5t8zYqc/edit?usp=sharing) tracking what took place in terms of which FIDs remained in the inbox, which went into the reviewed tab, and which were never actually reviewed but went into the reviewed tab anyway.

**Comment by mikefantini** [comment]
this is happening because when an editor clicks save on the inbox we think it is querying for the most recent files while the form is being submitted, instead of just the data that was submitted (i.e. the 25 or less FIDs that were in the inbox)

steps to replicate:
1. load rb inbox
2. have a user load up a campaign
3. have that user submit a rb
4. wait until rb is submitted
5. review rbs that are in the inbox

when you do this if all rbs that were reviewed (if <25 total) will have the proper status, but the new rb that was submitted will also appear to be reviewed as approved. 

if we don't have approved as default selected in the inbox, and there are less than 25 fids in the inbox, then the user will get an error that he/she made an illegal choice (because he or she would have tried to submit the new fid without selecting a status)

we are changing the order from newest to oldest in the inbox and removing the default approved selected in the inbox to unblock the reviewing of campaigns.

and @weerd is going to try to debug to determine why when an editor clicks save on the inbox it is querying for the most recent files while the form is being submitted, instead of just the data that was submitted

cc: @angaither

**Comment by mikefantini** [comment]
see related slack convo: https://dosomething.slack.com/archives/phoenix/p1438966108001280

**Comment by mikefantini** [comment]
even though user gets errors now, the reviewed rbs still go through properly.

error message user gets just to be clear (happening on node 5459, 25 errors because the inbox is full I imagine):

![image](https://cloud.githubusercontent.com/assets/6330971/9205335/9974a71c-402f-11e5-8e7e-1a04d4cd9f44.png)

**Comment by mikefantini** [comment]
to be clear, when we submit the inbox, it's always trying to grab additional reportbacks outside of the 25 that the user is actually reviewing. a key distinction based on changes that we made:
- when we had reportbacks listed by newest in the inbox, it was attempting to review any reportbacks that were submitted between the time a campaign lead loaded the inbox and submitted it
- currently when we have reportbacks listed by oldest in the inbox, it's attempting to review the next page of reportbacks (the next 25 in the inbox)

**Comment by mikefantini** [comment]
also worth noting, if there are less than 25 fids in the inbox when reproducing this, then the form won't submit because of the illegal choice being made. If there are more than 25 fids, it will submit.

**Comment by mikefantini** [comment]
another thing to note: you can remedy this issue by going to an actual reprotback; for instance staging.beta.dosomething.org/admin/reportback/996 and saving on the individual reportback.

**Comment by angaither** [comment]
@weerd this should function like the `admin/content` form
In that form it grabs multiple nodes, and you can update the status of them all at the same time. If you submit a new node while you are updating a bunch of those nodes, I would be curious to see where the issue is happening.

**Comment by weerd** [comment]
Making progress on my investigation on the `admin/content` list page.

The following are the series of steps taken when the page loads:

```
Step: 1 => node_admin_content
Step: 2 => node_filter_form
Step: 3 => node_admin_nodes
Step: 4 => node_admin_nodes start to build query
Step: 5 => node_admin_nodes calls ->  node_build_filter_query
Step: 6 => node_build_filter_query
Step: 7 => node_admin_nodes calls ->  node_load_multiple
Step: 8 => node_admin_nodes proceeds to load and build out nodes table view
```

**Comment by weerd** [comment]
The following are the series of steps taken when submitting an update to the page, which submits the form (for example, promoting an item to the front page.

```
Step: 1 => node_admin_content
Step: 2 => node_filter_form
Step: 3 => node_admin_nodes
Step: 4 => node_admin_nodes start to build query
Step: 5 => node_admin_nodes calls ->  node_build_filter_query
Step: 6 => node_build_filter_query
Step: 7 => node_admin_nodes calls ->  node_load_multiple
Step: 8 => node_admin_nodes proceeds to load and build out nodes table view

Validate Admin Nodes => node_admin_nodes_validate
Submit Admin Nodes Option => node_admin_nodes_submit

The update has been performed.  (Default Drupal message)

Step: 1 => node_admin_content
Step: 2 => node_filter_form
Step: 3 => node_admin_nodes
Step: 4 => node_admin_nodes start to build query
Step: 5 => node_admin_nodes calls ->  node_build_filter_query
Step: 6 => node_build_filter_query
Step: 7 => node_admin_nodes calls ->  node_load_multiple
Step: 8 => node_admin_nodes proceeds to load and build out nodes table view
```

The steps execute before the actual submitting of the form and then repeat to show the form. Seems that is the norm for Drupal.

Next up testing creation of new content and then updating the form...

**Comment by weerd** [comment]
For future reference if needed, the following are the full set of steps when _submitting_ the `/admin/content` form, with some descriptions:

```
Step: 1 -> node_admin_content  // runs to review form and collect what has changed/been selected
Step: 2 -> node_filter_form
Step: 3 -> node_admin_nodes
Step: 4 -> node_admin_nodes start to build query
Step: 5 -> node_admin_nodes calls ->  node_build_filter_query
Step: 6 -> node_build_filter_query
Step: 7 -> node_admin_nodes calls ->  node_load_multiple  // taking into account the query
Number of nodes collected: 50
Step: 8 -> node_admin_nodes proceeds to load and build out nodes table view

Validate Admin Nodes -> node_admin_nodes_validate
Submit Admin Nodes Option -> node_admin_nodes_submit

Step: 9 -> node_mass_update  // since this a submit action, and if items were selected, update them

The update has been performed.

// After updating, rerunning series of steps to show the content list form on the page
Step: 1 -> node_admin_content
Step: 2 -> node_filter_form
Step: 3 -> node_admin_nodes
Step: 4 -> node_admin_nodes start to build query
Step: 5 -> node_admin_nodes calls ->  node_build_filter_query
Step: 6 -> node_build_filter_query
Step: 7 -> node_admin_nodes calls ->  node_load_multiple
Number of nodes collected: 50
Step: 8 -> node_admin_nodes proceeds to load and build out nodes table view
```

**Comment by angaither** [comment]
@namimody have we been seeing this happen after we added the correct permissions for editors/site admins?

**Comment by angaither** [comment]
@namimody wrong issue. I think we discovered there's no real way around this one.

**Comment by mikefantini** [comment]
yeah just to document on the issue as well, chatted w/ some campaigns folks about this and we're going to stick with what we've got:
- approve not pre-selected
- status required

we'll continue to monitor with them and readdress if this is slowing them down too much moving forward
