### ISSUE TITLE
dosomething_user feature: administrator role

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#48]
- Administrator: for developers, basically like user 1, but to not have all dev's login as user 1.  Add permissions like:
  - Administer modules
  - Administer views
  - Bypass node access

**Comment by desmondmorris** [comment]
What would this entail?  Would this not live in a users feature?  I figure all roles should probably live in the same place

thoughts?

**Comment by aaronschachter** [comment]
Hmm yeah maybe it makes sense to define all roles in one feature, perhaps called dosomething_user_roles?  The thing is that we'll want to keep some specific module permissions in different features: e.g. all metatags permissions would live in dosomething_metatags

**Comment by aaronschachter** [comment]
Renaming this issue to apply only to an "administrator" role, which we'll always need to prevent devs from logging in as user 1.  Creating a separate issue for an Editor role, as there's a bit more to figure out there (and because we don't have content types yet)
