### ISSUE TITLE
Signup: Security / hidden nid

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#480]
Similar to #479  -- Because a signup form is rendered on a node, we can use arg(1) to determine nid for a signup, instead of passing through nid as a hidden field, which a user could change via firebug.

This would be needed for both the dosomething_signup_form for logged in users, and the form_alter for user login/registration

**Comment by barryclark** [comment]
@aaronschachter thoughts on whether this needs done for launch on tues?

**Comment by aaronschachter** [comment]
Was hoping that setting the hidden nid in the login form to `#access = FALSE` would handle this, as it is in #1538 .... but it's adding that property into the `_dosomething_user_add_campaign_data` function results in no signup. Still investigating.

**Comment by angaither** [comment]
Looks like we can set the access to false, but instead of checking for `$form_state['nid']` in the submit handler we check for `$form['nid']`

Here's a dpm of the $form after login.
![](http://f.cl.ly/items/341x282Z1D1n3k2r2D15/Screen%20Shot%202014-04-07%20at%2012.56.19%20PM.png)
