### ISSUE TITLE
Image node reference

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4804]
in `dosomething_campaign` settings add a reference to a node id, this should follow the example of
the "Alternate header image nid" field

Then you can use the `dosomething_image` functions to pass the correct images to the theme

**Comment by sbsmith86** [comment]
@angaither when this is done. Can you just pass the issue back to me so I can implement it on the frontend? I was gonna make a separate issue for adding it as a background image using `drupal_add_css()` but I think we can just leave it as one issue.

**Comment by mikefantini** [comment]
again, let's put this in Win Module Group

field name "Win Module Background Image"
