### ISSUE TITLE
Win copy field

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4805]
Another setting in the dosomething campaign hot module setting grouping to allow for generic template copy when a campaign is in the win phase

**Comment by mikefantini** [comment]
again would prefer this being in a Win Module group

Let's have this field name be "Win Module Copy"

**Comment by mikefantini** [comment]
@deadlybutter for this we'll need the following variables:
- [node:title]
- [campaign_progress] - not sure if this is exactly what this is called
- [node:field_reportback_noun] 
- [node:field_reportback_verb]

**Comment by mikefantini** [comment]
@deadlybutter default copy:

"[campaign_progress] [node:field_reportback_noun] [node:field_reportback_verb]! That's amazing - thanks to everyone for rocking [node:title]. Let's keep it up! Add your contribution in the prove it section below."
