### ISSUE TITLE
Win module shares

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#4811]
Add share bar and functionality to the win module.

**Comment by sbsmith86** [comment]
@mikefantini @lkpttn will need the deets on what the share language/images should be

**Comment by sbsmith86** [comment]
As mentioned in #4875, Im gonna go with 

```
23,519 Playbooks Sent! Thanks to everyone for rocking this campaign with @dosomething. Let’s keep it up!
```

As the share language for fb, tumblr, and twitter. @mikefantini

**Comment by mikefantini** [comment]
:+1:
