### ISSUE TITLE
approved/excluded/promoted fids have flagged = null status

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4815]
example node 2906
- [x] write query to see when status = approved/excluded/promoted and flagged = null. 

review the last time this happened, if it seems like this is a bug that has been resolved and is a thing of the past then...
- [ ] write update hook to retroactively fix reportbacks that are incorrect

if it seems like this bug is still happening currently, then let's hold off on writing the update hook and keep this data to trouble shoot so we can fix the problem

**Comment by angaither** [comment]
```
select rb.rbid, rbf.fid, rb.flagged, rb.promoted, rbf.status, from_unixtime(rb.created), from_unixtime(rbf.reviewed) as reviewed
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
where rbf.status != 'pending'
and rbf.status != 'flagged'
and rb.flagged is null
order by reviewed desc;
```

from this query it looks like this is a thing that's still happening.
neither promoted/flagged are getting set from `NULL > 0|1`

**Comment by mikefantini** [comment]
here is a video http://screencast.com/t/UUCBbBiNAq of Lizzie recreating this.

The following rbids/fids from this video were effected:
- 91575 124272
- 91577 124274
- 91582 124279
- 91583 124280
- 91585 124282
- 91588 124285
- 91592 124289
- 91595 124292
- 91599 124296
- 91603 124301
- 91606 124305
- 91609 124308

**Comment by deadlybutter** [comment]
wondering if the 503 error at the end had anything to do with it

**Comment by itsjoekent** [comment]
wooo more bugs that make absolutely no sense.

I feel like it can't be this function causing this, https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L328

because it would be impossible for the reason to save and neither of the numbers to update. but I dont know of anywhere else in the code where the reason is set.. investigatin time!

**Comment by angaither** [comment]
@deadlybutter it's not the reason that's saving, it's the status on the reportback item that is updating, but the flagged/promoted bool value isn't updated to match

**Comment by itsjoekent** [comment]
ohhh, gotcha

**Comment by itsjoekent** [comment]
@angaither weird, the reportback item review function does call the reportback setFlaggedPromoted function (like it should). ill double check thats actually happening.

https://github.com/DoSomething/phoenix/blob/050f2eacc04bb063490b313ad56fa069cbda9249/lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php#L185

**Comment by angaither** [comment]
@deadlybutter I think the error may be happening before these classes even get called. It might be related to wrong reportbacks getting submitted to be reviewd (might be related to the stuff @weerd was looking into on friday)

**Comment by itsjoekent** [comment]
can you fill me in on what he was looking into / found? (or point me to where that discussion was happening)

**Comment by angaither** [comment]
sent you a link in slack

**Comment by mikefantini** [comment]
@angaither is referring to #4797 here. see steps to reproduce that issue in the comments

**Comment by itsjoekent** [comment]
Joe Kent [5:14 PM] 
@fantini: now I didnt even get the error and the RB didnt skip getting reviewed. had full inbox and waited to submit until after i made a new RB.
(on my local dev)

**Comment by mikefantini** [comment]
There is a discrepancy in the data between the production database and the slave database. The production data is incorrect (i.e. flagged status is null even though entries have been approved, excluded, promoted, etc.).

examples rbid 90788, 91162, 91419.

production database:
![image](https://cloud.githubusercontent.com/assets/6330971/9254000/04f23ab0-41af-11e5-98d5-26c8baaf0f37.png)

slave database:
![image](https://cloud.githubusercontent.com/assets/6330971/9254016/1ce89218-41af-11e5-85f7-60dfd12105a3.png)

**Comment by mikefantini** [comment]
@namimody let's take a look at instances where the rbs are incorrect in production database and see if they are also incorrect in the slave database

**Comment by angaither** [comment]
refs #4887

**Comment by angaither** [comment]
I think we are good to close this issue out, I've confirmed after the script + editor/member support permissions were added we are no longer seeing this
