### ISSUE TITLE
Reportback without image uses undefined constant

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4818]
See [`dosomething_image_get_themed_image_by_fid()`](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_image/dosomething_image.module#L137).

``` php
  if (!$image) {
    $args = array(
      'path' => DS_ASSET_PATH .'/dist/images/no-image-found.png',
      'alt' => 'No image found placeholder',
      'title' => 'No Image Found',
      'attributes' => NULL,
    );
    return theme_image($args);
  }
```

`DS_ASSET_PATH` Is defined in [`template.php`](https://github.com/DoSomething/phoenix/blob/4648825177a0612007e18cfaf5014a7a04a14ef7/lib/themes/dosomething/paraneue_dosomething/template.php#L11-L13) and can't be used in module.

**Comment by weerd** [comment]
Seems to be working fine. The path was updated; still using a constant but seems to work fine: https://github.com/DoSomething/phoenix/blob/29373fa2ba9e67f33e4c7e5aa7f26fdb0aa4bd2c/lib/modules/dosomething/dosomething_image/dosomething_image.module#L146

@DFurnes updated the path in #5624. The constant seems to be available and output the correct path when I tried on local, so will close issue.

_Note: If this is more a debate of whether it **should** be used in the module and instead only used in theme, then that's a different discussion_ ;)

**Comment by sergiitk** [comment]
Great! :+1:
