### ISSUE TITLE
Verify Stripe payment function params

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#4819]
https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_payment/dosomething_payment.module#L265

If we're actually passing CC info to the back end, we're doing it wrong. This should only be passing the single-use token [as outlined here](https://stripe.com/docs/tutorials/forms).

Either the comment needs to be updated, or we need to fix the payment implementation so that no CC info passes into our systems.

**Comment by angaither** [comment]
we moved to paypal. :credit_card: :x:
