### ISSUE TITLE
503 errors when reviewing reportbacks

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4828]
when editors are reviewing reportbacks (example https://www.dosomething.org/node/5459/rb) they are intermittently getting 503 errors. this has happened for several different campaign leads.

![image](https://cloud.githubusercontent.com/assets/6330971/9210210/f2895848-4048-11e5-9359-936705ca3f19.png)

![image](https://cloud.githubusercontent.com/assets/6330971/9210230/1122005c-4049-11e5-9d27-3c542ae780f9.png)

![image](https://cloud.githubusercontent.com/assets/6330971/9210218/fc8d126c-4048-11e5-8754-42c8d7503e81.png)

![image](https://cloud.githubusercontent.com/assets/6330971/9210223/03fd8e96-4049-11e5-8009-acc8531a2910.png)

cc: @sheydari-ds

**Comment by mikefantini** [comment]
another example:

![image](https://cloud.githubusercontent.com/assets/6330971/9236920/ce3b93d4-4115-11e5-9f4e-2135df060d71.png)

**Comment by mikefantini** [comment]
we've seen the errors in the [Reportback Review Bugs](https://github.com/DoSomething/phoenix/milestones/Reportback%20Review%20Bugs) milestone happening with this error and also without this error occurring, but just adding it to the milestone so that everything is together so that we have the full picture

cc: @sheydari-ds

**Comment by angaither** [comment]
I'd be curious to see if this continues to happen after #4863 is deployed.

**Comment by angaither** [comment]
Haven't heard reports of this happening after we switched the order of the inbox from oldest -> newest

**Comment by mikefantini** [comment]
we just got a new one @angaither @sheydari-ds 

![image](https://cloud.githubusercontent.com/assets/6330971/9553635/5c971868-4d8e-11e5-9921-ea190268d3ec.png)

**Comment by mikefantini** [comment]
another one reported @sheydari-ds @angaither 

![image](https://cloud.githubusercontent.com/assets/6330971/9667562/760f5db2-524a-11e5-9a49-75c028e9e1bf.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/9794997/44471f0a-57bc-11e5-92c5-13e0e5048d87.png)

Just had an intern report another error appearing. The RBs she reviewed seem to have been saved though. Is there a status update on this?

**Comment by namimody** [comment]
Today Jess reviewed a page of 25 reportbacks, submitted, and encountered a 503 error. Then, she found one of the photos in this batch (RBID: 96549) still in the inbox, but also appearing in the "reviewed" bank of RBs. (I need to gain access to prod DB to figure out status according to SQL.)

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;C1UNq2rS&#x2F;1490-503-error-while-reviewing-rbs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 503 Error While Reviewing RBs</a>

**Comment by ghost** [comment]
@namimody @mikefantini I've upped the timeouts in Fastly (which had the lowest settings). Let's see if we can re-create/see if this still happens on large data reportback pages.

**Comment by ghost** [comment]
@namimody Can you confirm testing on this, and close if it's looking good?

**Comment by mikefantini** [comment]
@sheyd we just got this error again on node 15. Jess reviewed reportbacks, clicked save, and waited about 1 minute and this error popped up

Even though the error occurred, all report backs saved properly

Momm-o-grams: 26 in queue, 503 error, all went though (last RB submitted at 23:24 on 9/23/2015, error occurred at 16:48 on 9/24)
![image](https://cloud.githubusercontent.com/assets/6330971/10086438/6b7b7a5a-62dc-11e5-89ac-f0b9e1628517.png)

**Comment by sheyd** [comment]
@mshmsh5000 Do you think it's potentially work re-visiting the code logic on approving/saving RB's? We've upped the timeouts at multiple layers of our stack. Our bottleneck is about 60 seconds at this point, raising this value further is likely not the best idea as it introduces some scenarios for cascading failures, or resource starvation with lots of simultaneous requests. Thoughts?

**Comment by mshmsh5000** [comment]
I'd look at an approach like this for now:

https://www.varnish-cache.org/lists/pipermail/varnish-misc/2011-July/020813.html

**Comment by mshmsh5000** [comment]
A similar approach for HAProxy (a "slow back-end" definition) should work: http://serverfault.com/a/324731

**Comment by sheyd** [comment]
Fastly backend timeouts increased to seconds beyond the count of two hands and and two feet (human). Also put in some pass Varnish logic around "/rb" URL's to see if the bottleneck exists on our origin servers.

**Comment by namimody** [comment]
A few more screenshots for additional reference (happened prior to Sena's previous comment)

Cookin' It Old School: 21 in inbox, 503 error occurred, all were saved properly 
![image](https://cloud.githubusercontent.com/assets/12396076/10087788/20f128b0-62e4-11e5-8c05-682dfad28268.png)
Senior Story Swap: 105 in queue, 503 error occurred, all went through
![image](https://cloud.githubusercontent.com/assets/12396076/10087892/e42fad56-62e4-11e5-878f-74ce8473b923.png)
80 in queue: 
![image](https://cloud.githubusercontent.com/assets/12396076/10087908/f75b7504-62e4-11e5-98b6-0170ad582fa9.png)

Before this, Jess reviewed Past Picture Perfect: 5 in queue, ​_no_​ 503 error, all went through

**Comment by angaither** [comment]
@sheyd we can decrease the amount of reportbacks a reviewer can submit at one time pretty easily, would that help?
it's currently at 25, maybe 10? 

for context: 
The code that runs has to check every reportback item thats attached to the reportback and check the status on each to apply the correct status to the reportback as a whole

cc @mikefantini

**Comment by mikefantini** [comment]
going to pose the question to the campaigns team.

also this just happened with Jess reviewing reportbacks, and she disproportionately creates the 503 errors. the good news is that all reportbacks she reviewed went from the inbox to the reviewed tab so everything worked properly:

![image](https://cloud.githubusercontent.com/assets/6330971/10102946/54323332-636f-11e5-88cb-28531043b52b.png)

**Comment by mshmsh5000** [comment]
Looking at this in New Relic, it's clear that Northstar response time is a significant part of the problem:

![newrelic](https://cloud.githubusercontent.com/assets/149811/10103533/74d0d83e-6372-11e5-916b-bc00a5af62c1.png)

Almost 2/3 of the time is spent talking to Northstar.

**Comment by mikefantini** [comment]
Removing blocker from this issue. @mshmsh5000 @angaither given the comment about Northstar response time who should this issue be assigned to?

**Comment by angaither** [comment]
@chloealee is looking into this with her pr #5616

**Comment by angaither** [comment]
@mikefantini have people still seen this? I haven't heard about it in a while. no news is good news

**Comment by mikefantini** [comment]
Not that I've heard. Let's close it out.
