### ISSUE TITLE
Campaign translation: Make provided list of fields translatable

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4835]
Enable translation for provided Campaign fields using Entity Translation.

CC @sheydari-ds @mikefantini @julielorch

**Comment by mikefantini** [comment]
@sergii-tkachenko [here is the list](https://docs.google.com/spreadsheets/d/11Oh8euenazBzQ9s_Ax5Qe1ps-XZbg0XjCWVI_EVQcJo/edit#gid=0) @julielorch and I made. Note the multiple tabs.

Where field collections are concerned (i.e. field_faq) we didn't break out the individual fields that are a part of that collection, but obviously each of these would need to be translated as well. if you want those we can provide those too. just let us know.

Also note the multiple tabs of the sheet where we broke out fields that need to be globally set.

One question on this, if we want a field to only exist in the English version (i.e. field_action_guide) can we just not translate this field? Or does it have to be translated and as an editorial rule the Brazilian editors should just leave it blank? (let's go with the easiest tech solution for v1).

Things that still need to be sorted out for campaign template translation:
1. Taxonomy terms - we will need to translate individual taxonomy terms (i.e. Animals to Animales for v1) and also have specific taxonomy terms just for a specific country experience (i.e. Corruption for Mexico but this is v2, so let's not worry about for now)
2. any custom settings translation we need - maybe none for v1?

**Comment by sergiitk** [comment]
Thanks Mike. Working on this. I'll double check everything and answer your questions.

**Comment by mikefantini** [comment]
@sergii-tkachenko did you have any thoughts on this question:

One question on this, if we want a field to only exist in the English version (i.e. field_action_guide) can we just not translate this field? Or does it have to be translated and as an editorial rule the Brazilian editors should just leave it blank? (let's go with the easiest tech solution for v1).

**Comment by sergiitk** [comment]
Done, except field_collections, see #4850.
