### ISSUE TITLE
Tmblr Problem Share Functionality Lagging

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4837]
![image](https://cloud.githubusercontent.com/assets/12396076/9238412/151d3082-4120-11e5-9a27-4cfd0e6faf72.png)

After trying to share a problem statement to TUmblr, a popup appears and appears to continue to try and load for ages without ever displaying content. Weirdly, shares work from the permalink.

**Comment by namimody** [comment]
<img src="https://github.trello.services/images/trello-icon.png" width="12" height="12"> [Staff Reported Bug TEMPLATE](https://trello.com/c/1pSQ59ZM/1422-staff-reported-bug-template)

**Comment by mikefantini** [comment]
@sbsmith86 do you mind taking a look when you get a chance?

**Comment by sbsmith86** [comment]
Seems the problem share image URLs are 404'ing. Reached out to devops about it. 

ex: https://www.dosomething.org/profiles/dosomething/modules/dosomething/dosomething_campaign/dosomething_campaign_problem_shares/images/832.png
