### ISSUE TITLE
remove field_location_finder from campaign template

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4842]
just the field, not the group, the other fields in the group are needed.

any data loss does not matter for this field, but I don't think there will be any.

**Comment by namimody** [comment]
<img src="https://github.trello.services/images/trello-icon.png" width="12" height="12"> [Twitter Permalink Share Shows Jumbled Copy Where Apostrophe Should Be](https://trello.com/c/mYcGq8Mb/1431-twitter-permalink-share-shows-jumbled-copy-where-apostrophe-should-be)

**Comment by mikefantini** [comment]
@namimody?? ^

**Comment by namimody** [comment]
Sorry @mikefantini! Was testing the new Trello integrations and I didn't realize they affected Github. Deleting!
