### ISSUE TITLE
Deleting Reportbacks Does Not Appropriately Change Displayed Quantity

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4849]
On a test campaign (http://staging.beta.dosomething.org/campaigns/rb-wtf) I deleted an existing approved reportback with quantity 100, and ran CRON. The reportback no longer appears under the reportbacks tab on the microsite, but the hot module display shows 100, as does the total on the top of the reportbacks tab.

![image](https://cloud.githubusercontent.com/assets/12396076/9311211/cf283402-44e2-11e5-8960-5dd1f5a180e1.png)

![image](https://cloud.githubusercontent.com/assets/12396076/9311217/d6d3b0a0-44e2-11e5-9998-5b3b4be6c23f.png)

"100" should be removed from both places, and a value of 0 should be shown.

**Comment by angaither** [comment]
no thanks hot module.
