### ISSUE TITLE
Make field_collections translatable

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4850]
There's an issue with translating field_collection fields: Field translation (entity_translation) isn't supported by default. Fortunately, the patch is ready: https://www.drupal.org/node/1344672

I'm going to need to:
- [x] Update field_collection module to dev version
- [x] Make sure features structure is compatible with the module; or revert/update it
- [x] Patch it with https://www.drupal.org/node/1344672?page=1#comment-10126164
- [x] After enabling the translation, copy existing content into translatable fields

Ref #4835 

CC @sheydari-ds @mikefantini @julielorch

**Comment by sergiitk** [comment]
A little update: let’s skip field_collections for now. In Campaign these kind of fields are:
- FAQ
- Video
- During Tips
- After Tips
- Sponsors and Partners

Tested the patch and it turn out to be problematic yet.

**Comment by angaither** [comment]
guessing this is blocked based on the comments @sergii-tkachenko left

**Comment by mikefantini** [comment]
@sergii-tkachenko what's the status of this issue? Can this be closed out now that #5485 was opened as a 1.1 issue?

**Comment by sergiitk** [comment]
Yes!
