### ISSUE TITLE
production database has incorrect data when slave database has correct data

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4851]
related to #4815 when doing the following query, we got different results when querying the production database and the slave database.

```
select rb.rbid, rbf.fid, rbf.status, rb.quantity, rb.flagged, from_unixtime(rb.created)
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
where rb.nid = 3743
```

The production data is incorrect (i.e. flagged status is null even though entries have been approved, excluded, promoted, etc.).

examples rbid 90788, 91162, 91419.

production database:
![image](https://cloud.githubusercontent.com/assets/6330971/9254000/04f23ab0-41af-11e5-98d5-26c8baaf0f37.png)

slave database:
![image](https://cloud.githubusercontent.com/assets/6330971/9254016/1ce89218-41af-11e5-85f7-60dfd12105a3.png)

note that this is not the only thing causing #4815 as we have seen instances of this happening on the staging database and on the slave database.

**Comment by sheyd** [comment]
@mikefantini This is superseded by #5549, as I'm going to ensure data continuity between all the DB's. Closing this out in favor of the that one.
