### ISSUE TITLE
Translate $ scholarship prefix for various currencies 

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4855]
The UK needs £ to appear on their site instead of $ for their incentives field.

**Comment by namimody** [comment]
<img src="https://github.trello.services/images/trello-icon.png" width="12" height="12"> [Currency Symbol Change on DS UK](https://trello.com/c/Kcub0b1p/1462-currency-symbol-change-on-ds-uk)

**Comment by angaither** [comment]
probably another thing we will need to refactor once we are ~one site~ 
[currently this is set as a prefix](https://github.com/DoSomething/phoenix/blob/75ce57a6b816369f6ec682092551e4fd244ac5ee/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.features.field_instance.inc#L2519) in the scholarship field, but we will probably need to POTify it

**Comment by angaither** [comment]
I was wrong, we don't actually use the prefix, it's hard coded [in the theme](https://github.com/DoSomething/phoenix/blob/e76692b89862573821aaed53f70e709f8c679ddd/lib/themes/dosomething/paraneue_dosomething/templates/campaign/partials/campaign-scholarship.tpl.php)
