### ISSUE TITLE
updates to multiplayer SMS web template for optimizely

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4866]
Need header and copy text added in the middle of the form:

![image](https://cloud.githubusercontent.com/assets/6330971/9361257/8d55bb58-4668-11e5-82db-a45b97827774.png)

**Comment by mikefantini** [comment]
cc: @namimody

**Comment by DFurnes** [comment]
Preliminary snippet for adding in the little interstitial heading:

``` javascript
window.jQuery(".form-item-alpha-mobile").after('<div style="width: 100%;overflow: hidden;clear: both;padding: 48px 12px 12px;"><h3 class="inline--alt-text-color">Which of your friends care about Bullying?</h3><p>We\'ll send your friends a text to start the game.</p></div>');
```

And preview:

![screen shot 2015-08-19 at 1 54 51 pm](https://cloud.githubusercontent.com/assets/583202/9364356/e853617a-4679-11e5-9f71-322fc8f04107.png)

**Comment by DFurnes** [comment]
@namimody Assigning to you for the actual testing! Let me know if I can help with anything else. :smile:

**Comment by namimody** [comment]
THanks @DFurnes! Experiment started 3:41 PM 8.21 @ https://app.optimizely.com/edit?experiment_id=3389060225

**Comment by mikefantini** [comment]
@namimody what percentage breakdown did you go with for the test? I think 50-50 would be ideal.

**Comment by namimody** [comment]
@mikefantini yep! did 50-50 :) no conclusions yet...

**Comment by namimody** [comment]
Hey @DFurnes! For some reason, this code snippet isn't acting as it did on Bully Text. Could we sync on this when you have a chance this morning? Thanks!!

**Comment by angaither** [comment]
I'm 99% sure we killed this
