### ISSUE TITLE
when editors and/or member support roles review reportbacks, flagged status is set to null

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4871]
when admins review reportbacks flagged status is set properly (0 for flagged, 1 for everything else)

we recreated this several times on staging and production with the same user and just changing their permissions

every single reportback that Lizzy reviewed has flagged status of null on nid 5566 has flagged status null. her roles are editor and member support.

when diego reviewed reportbacks on nid 5566 they had the correct flagged status. he is an admin. when we changed him to editor role, the reportbacks he reviewed had incorrect flagged status

also saw this with nid 2900 and sam's accounts

**Comment by mikefantini** [comment]
so we've been able to reproduce this consistently, but it's worth noting times when this has worked properly for editors and has not worked properly for admins.

one example:

```
select rb.nid, rb.rbid, rbf.fid, rb.flagged, rb.flagged_reason, rb.promoted, rb.promoted_reason, rbf.status, from_unixtime(rb.created) as created, from_unixtime(rbf.reviewed) as reviewed, u.mail, r.name
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
inner join users u on u.uid = rbf.reviewer
inner join users_roles ur on u.uid = ur.uid
inner join role r on r.rid = ur.rid
where rb.nid = 2003
order by rb.rbid desc;
```

this may be because we had multiple issues causing the problem, but i'd like to still keep an eye out for this.

also may be worth @angaither running a query to see every time an editor has reviewed a rb and the flagged status is correct and also every time an admin has reviewed a rb and the flagged status was null just to see if there are still other things that may be causing the symptom of #4829 and #4815

**Comment by mikefantini** [comment]
also noting here, the permission that needs to be changed for editor and customer support role is that they need permission to "edit any reportback"

**Comment by angaither** [comment]
#### Every reportback where flagged is null, but reportback file status is flagged
- proves that `editor|member support|site admin` have the issue

```
select rb.nid, rb.rbid, rbf.fid, rb.flagged, rb.flagged_reason, rb.promoted, rb.promoted_reason, rbf.status, from_unixtime(rb.created) as created, from_unixtime(rbf.reviewed) as reviewed, u.mail, r.name
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
inner join users u on u.uid = rbf.reviewer
inner join users_roles ur on u.uid = ur.uid
inner join role r on r.rid = ur.rid
where rb.flagged is NULL
and rbf.status = 'flagged'
order by reviewed asc;
```
