### ISSUE TITLE
Updating flagged RBItem status does not update the flagged state

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4879]
**Context:** viewing a Reportback with a series of reviewed items in the CMS and one of them has a status of _flagged_, all of the items including the flagged one will have a `1` in the `flagged` field.

If you update the flagged item and change the status to promoted or approved, the `status` field updates properly, but the `flagged` field remains as `1` for all the items in the RB.

@mikefantini @namimody @angaither

**Comment by angaither** [comment]
this is a [known issue](#4621) and the way it was built originally, @deadlybutter addressed it here
https://github.com/DoSomething/phoenix/pull/4669
but maybe it is re-broken

**Comment by itsjoekent** [comment]
I changed something around this more recently

**Comment by itsjoekent** [comment]
alright, this actually seems to have no relation to the setFlaggedFunction and is a much deeper problem. 
- I had **3** items (3 is important), top was flagged rest were approved.
- I change the flagged to promoted and print out the reasons for each item. This is a screenshot of that output.

![screen shot 2015-08-25 at 5 21 27 pm](https://cloud.githubusercontent.com/assets/897368/9479919/ca4c0244-4b4d-11e5-93d4-36766220f901.png)

Notice how there is only two reportback items that printed, and those are the two which were already approved. The item which changed never sent it's reason in the request, and thats why the status was never updated, it never got a new status. 

If you do it again however (set that same item to promoted, again), everything works fine.

![screen shot 2015-08-25 at 5 23 19 pm](https://cloud.githubusercontent.com/assets/897368/9479969/0351972a-4b4e-11e5-9a65-1c90e51a2256.png)

Yeah, this is really weird.

**Comment by itsjoekent** [comment]
_okay_ I figured out why this is happening. Since I broke the logic out in  https://github.com/DoSomething/phoenix/pull/4909 it was much easier to debug this.

(Doing same test case as above)

I added this bit of debug logic to setFlaggedPromoted

```
      if($status === "flagged") {
        dsm("flag stat!");
      }
      else if($flagged_reportbacks) {
        dsm("flag rbs!");
      }
```

and got the following output

```
flag rbs!
promoted!
promoted!
```

This means that the reportback item is still marked as flagged when the call to review the reportback is made.

**Comment by itsjoekent** [comment]
Adding the entity save before the call to setFlaggedPromoted resolved the issue, 

```
    // Must be saved before calling setFlaggedPromoted 
    $updatedReportbackItem = entity_save('reportback_item', $this);

    $reportback->setFlaggedPromoted($this->status, $values);

     ....
    return $updatedReportbackItem;
```

new output from the test logic is correct 

```
promoted!
promoted!
promoted!
```

and verified in DB

<img width="954" alt="screen shot 2015-08-31 at 1 47 15 pm" src="https://cloud.githubusercontent.com/assets/897368/9585805/071ce5a6-4fe7-11e5-83ce-e24839fe7a5a.png">

cleaning up and making PR
