### ISSUE TITLE
Display content to users who are searching with the appropriate priorties

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#4885]
Users should see:
1. native campaigns in language
2. global campaigns in language
3. other global campaigns in global english (publish global campaigns initially)

Campaigns must be boosted according to these rules and then the appropriate (translated) fields will be displayed.

Question: Where should Static Content and other content be prioritized in this list?

**Comment by blisteringherb** [comment]
For this functionality to work properly before we create Fastly driven language-detection, the language detection settings in Drupal have to be set to respect a user's language choice.  The user must also then select a default language choice. After that, when a user searches for content, they should see content listed in their preferred language, and if there is no content, the suggested content should be displayed in the user's language.

I've run the auto translation on Thor and set up the necessary settings for this to work. 

To test:
1. Create a new user
2. Set the user's language preference
3. Test by searching in the search box

**Comment by mikefantini** [comment]
related to #4959
