### ISSUE TITLE
Cleanup wonky reportback statuiiii

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4887]
Reportbacks don't have the same status as the file does, due to borked permissions. 

Clean that up. 
### select all reportbacks, with status where status is not pending and flagged is null
- this will need to update `flagged` and `promoted` to the correct values, based on the file status

```
select rb.rbid, GROUP_CONCAT(rbf.fid), rb.flagged, rb.promoted, group_concat(rbf.status)
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
where rbf.status != 'pending'
and rb.flagged is null
group by rb.rbid;

```

then 

```
foreach ($results as $result) {
    if (in_array('flagged', explode(',', $result->stati))) {
      // set a flagged to a 1
      db_query(update things)
    }
    else if (in_array('promoted', explode(',', $result->stati))){
      // set promoted to 1
    }
   else {
    // both get set to 0
   }
```

**Comment by mikefantini** [comment]
@angaither can we test this on node 69 first before we do this for all nodes on production?

**Comment by angaither** [comment]
@mikefantini yeah, that's the plan

**Comment by angaither** [comment]
closing this out, ran the script on prod 8/25
confirmed that no reportbacks have been reviewed and have a `null` flagged/promoted status anymore. 

if we see issues from this point forward, there's a new bug :new_moon_with_face:
