### ISSUE TITLE
Thor Share Buttons Appear Vertically (vs. Horizontally)

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4890]
![image](https://cloud.githubusercontent.com/assets/12396076/9449373/2adf7e12-4a70-11e5-9c3b-1a690e25c87e.png)

**Comment by DFurnes** [comment]
@namimody This should be fixed by #4899.

**Comment by sergiitk** [comment]
#4899 is delivered to thor, the bug is fixed now. Thanks @DFurnes.

![image](https://cloud.githubusercontent.com/assets/672669/9474220/fae0293e-4b67-11e5-903f-205ca5bf7c04.png)
