### ISSUE TITLE
Thor Facebook Problem Share Post Missing Photo

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4891]
![image](https://cloud.githubusercontent.com/assets/12396076/9449680/3626e7a4-4a72-11e5-98f6-c608ec5a117b.png)

**Comment by sbsmith86** [comment]
@namimody has cron been run on this environment?

**Comment by namimody** [comment]
@sbsmith86 I'm not sure -- is there a way to check the last time it was run on Thor?

**Comment by sergiitk** [comment]
@sbsmith86 No, it hasn't been. Will create a ticket and reference you.

**Comment by sergiitk** [comment]
Looks like it works now:
![image](https://cloud.githubusercontent.com/assets/672669/9474505/bc127534-4b69-11e5-8eb8-a8f9858337c2.png)
