### ISSUE TITLE
Thor Internal Search Doesn't Return Results

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4893]
Thor search does not show results shown for same keyword on production.

![image](https://cloud.githubusercontent.com/assets/12396076/9449890/7b6c182e-4a73-11e5-98cb-365fe27fdd50.png)

**Comment by ghost** [comment]
Fixed in #4894.

**Comment by sergiitk** [comment]
Example: https://thor.dosomething.org/search/apachesolr_search/bully
