### ISSUE TITLE
Thor: create Jenkins job to trigger phoenix cron and run it

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4896]
Ref #4891 
cc @namimody @sbsmith86

**Comment by ghost** [comment]
Setup and run.

**Comment by ghost** [comment]
@namimody @sbsmith86 ^^

**Comment by sbsmith86** [comment]
Woot! @namimody let's check that sharing functionality now. Running cron should generate the missing images you were seeing on facebook and tumblr
