### ISSUE TITLE
Thor User Profiles Aren't Displaying All Campaign Images

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4897]
![image](https://cloud.githubusercontent.com/assets/12396076/9468616/a006dabe-4b10-11e5-9d86-6e6ecb50a669.png)

Despite having both the landscape and square crop uploaded, campaign images aren't showing up on user profiles.

**Comment by sergiitk** [comment]
It looks like this happens with Language-neutral Campaigns, e.g. #RealPrincess. Will make the campaign English to test it.

**Comment by sergiitk** [comment]
Yes, making the campaign English fixed the image.
