### ISSUE TITLE
Add Metatag module

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#490]
Let's get [this](https://drupal.org/project/metatag) in ASAP, before anyone starts entering content. Once it's in the code base, please open a Trello card to review global config with the content team.

**Comment by aaronschachter** [comment]
It's in the codebase, we need to just update the .info file to enable upon install.  We'll want to move some general settings like Site Information into features in `dosomething_settings`

**Comment by aaronschachter** [comment]
Trello card for reviewing global config: https://trello.com/c/4GfnyUwN.  Added this to Engineering board and added myself and @mshmsh5000 -- please feel free to move / update accordingly.
