### ISSUE TITLE
br and mx admin roles shouldn't have access to configuration or users admin menu items

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4901]
remove permissions from regional admin roles 
- [x] view user profiles
- [x] translate interface texts

**Comment by angaither** [comment]
## config
- [x] translation config interface

## users
- [x] user search
- [x] clean slate
- [x] shipments

**Comment by angaither** [comment]
@deadlybutter this stuff might be exposed in the `dosomething_user_is_staff` function

**Comment by itsjoekent** [comment]
@sergii-tkachenko re: andrea's comment above, I have no idea what permissions those are. Ive tried a bunch of different searches and I'm not yielding anything (besides user search)

**Comment by sergiitk** [comment]
Were you looking for these?
![image](https://cloud.githubusercontent.com/assets/672669/10316541/68d4337e-6c68-11e5-8c4f-1c2791942694.png)

**Comment by itsjoekent** [comment]
I'm referring too 

clean slate
shipments
translation config interface

**Comment by mikefantini** [comment]
assigning this over to @angaither and adding BLOCKED label until she gets back

**Comment by angaither** [comment]
@deadlybutter [clean slate](https://github.com/DoSomething/phoenix/blob/6f4467256f6b05b11a671253879525665b834d66/lib/modules/dosomething/dosomething_user/dosomething_user.module#L101) and [shipments](https://github.com/DoSomething/phoenix/blob/985d55314a780bf3b92b4781482fff90565249ad/lib/modules/dosomething/dosomething_shipment/dosomething_shipment.module#L37) are custom menu hooks

the translation config is from the module we are using to translate and I think we can override that with a `menu_hook_alter`

**Comment by itsjoekent** [comment]
done, thanks for clarifying!
