### ISSUE TITLE
Make 54 Language-neutral campaigns English

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4904]
This will fix #4897 and bring more consistency to the Thor.
We can do it programmatically (will take about 3 hours) or assign somebody to go through it manually.

![image](https://cloud.githubusercontent.com/assets/672669/9473358/02ef1ad6-4b63-11e5-954b-fe379dc37c38.png)

cc @sheydari-ds @mikefantini @julielorch @namimody

**Comment by sergiitk** [comment]
[7:55 PM] Sergii Tkachenko: as i understand, the field display depends on users’s language
[7:56 PM] Sergii Tkachenko: and when the language is explicitly set to English, it looks for a English “translation” of the image field
[7:56 PM] Sergii Tkachenko: i don’t think this campaigns are suppose to be lanugage-neutral in the first place
[7:57 PM] Sergii Tkachenko: can we clarify that?
[7:57 PM] Sena Heydari: Yeah, let’s ask that during stand-up. It does raise the question of if we should have a “Fallback” image though.

**Comment by mikefantini** [comment]
@angaither @aaronschachter i assume we're good to just move everything set to English instead of having some in English some in Language neutral but just wanted to see if you could think of any gotcha's in doing this?

**Comment by angaither** [comment]
I think we are ok to set things to english. my only concern would be all the things we have set to check `[und]` (undefined language) in the code. some classes and checking for variables _might_ break

https://github.com/DoSomething/phoenix/search?utf8=%E2%9C%93&q=und

**Comment by sergiitk** [comment]
@angaither Good catch. However, this is inevitable since most of campaign are English, not neutral already.

**Comment by sergiitk** [comment]
![image](https://cloud.githubusercontent.com/assets/672669/9477015/ac8871c2-4b78-11e5-942e-a03f79224f46.png)

**Comment by sergiitk** [comment]
CC @DFurnes: see last 3 comments.

**Comment by angaither** [comment]
@sergii-tkachenko what will `[und]` be when the language is set? is there a way to scope it for all languages?

**Comment by sergiitk** [comment]
It depends. If that's field's class and field is not translatable, it'll stay `[und]`. If translatable: I suppose it will be set to current language.

**Comment by sergiitk** [comment]
We need to work out a way to use different language-independent CSS class names.

**Comment by DFurnes** [comment]
The CSS file referenced in the search above is for the admin theme, if that makes any difference. The Casper tests could probably be rewritten to use the more human-readable `name` attributes on each field, rather than the crazy IDs that Drupal generates.

**Comment by sergiitk** [comment]
Renamed 47 to 54 (including not published).
