### ISSUE TITLE
remove reportback crons

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4905]
we currently have crons looking for inconstancies in reportback items and the reportback flagged state
refs #4658
it might be time to remove those

**Comment by mikefantini** [comment]
@angaither these resolve issues once they appear yeah?

is the idea that we remove them so that if there are issues still remaining or new ones that pop up we're able to catch them?

or is it more just that since we think everything is fixed we no longer need these running?

**Comment by angaither** [comment]
@mikefantini yeah, I think this could be stopping us from catching issues if there are more, and hopefully we don't need them

**Comment by mikefantini** [comment]
ok great let's remove that shiz @angaither
