### ISSUE TITLE
Global: Add Global English language

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#4911]
Plus, think of better name for it.

CC @sheydari-ds @mikefantini

**Comment by mikefantini** [comment]
@sergii-tkachenko sorry can you please clarify why you think we need a better name for it than "Global English"?

The idea is that the content that would be in those fields would meet two criteria:
1. they are in English
2. all information is globally relevant

The only distinguishing factor between this and US English is that US English would have some content that is more locally specific (i.e. the US English version of a campaign would have a stat like "1 in 3 teens in the US..." while the Global English version of a campaign would have a stat like "1 in 4 teens in the world...").

The idea is then when we want to serve Spanish speaking teens across the world we would have a Global Spanish translation. The only difference between the Global Spanish translation and the Mexican Spanish translation would be that the Mexican Spanish translation would have information specific to Mexico (i.e. "1 in 3 teens in Mexico") while the Global Spanish version would have information that worked in a global context (i.e. "1 in 4 teens in the world").
