### ISSUE TITLE
using an image w/o a landscape crop in the sponsor image field on /node/add/campaign results in error page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4916]
went to create a new campaign on staging (http://staging.beta.dosomething.org/campaigns/please-dont-break-anything) and got the following error page

![image](https://cloud.githubusercontent.com/assets/6330971/9500356/e3eadbd0-4bf2-11e5-99ae-72db7fc73579.png)

**Comment by mikefantini** [comment]
@sergii-tkachenko if i don't include an entry in the image field here it works as intended

![image](https://cloud.githubusercontent.com/assets/6330971/9500402/3ee2eb68-4bf3-11e5-93bc-d47d246adacb.png)

**Comment by sergiitk** [comment]
Great catch. Looking into it on local.

**Comment by mikefantini** [comment]
@sergii-tkachenko also when i add a different image it works properly

**Comment by sergiitk** [comment]
Could you add the one that fails?

**Comment by mikefantini** [comment]
yeah weird it just seems to be this image that's causing it to fail http://staging.beta.dosomething.org/node/1634

**Comment by mikefantini** [comment]
yeah weird it just seems to be this image that's causing it to fail http://staging.beta.dosomething.org/node/1634

**Comment by mikefantini** [comment]
yeah it was breaking with that node because there is no landscape crop for that node.

added a landscape crop and it works properly now @sergii-tkachenko

**Comment by sergiitk** [comment]
So for some reason partner image is passed as an object sometimes, rendered img tag expected.

**Comment by angaither** [comment]
fixed with #4917

**Comment by sergiitk** [comment]
@angaither It's not fixed with #4917 you decided we need to find better solution.
