### ISSUE TITLE
Problem Shares on Hot Module Campaigns Misaligned

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4918]
![image](https://cloud.githubusercontent.com/assets/12396076/9501613/45848da8-4bfa-11e5-9240-40f84e6cf1ce.png)

**Comment by DFurnes** [comment]
I believe this is fixed by #4900.

**Comment by sergiitk** [comment]
Hm... #4900 fix Is on staging...

**Comment by sergiitk** [comment]
Looks like Deploy-Assets job hasn't been working for past 3 Release jobs.

**Comment by sergiitk** [comment]
Maybe that's the reason.

**Comment by namimody** [comment]
Note: the reason for this is because there wasn't sufficient information for the campaign lead's bio. With name and position and photo, the problem shares appear correctly.

**Comment by mikefantini** [comment]
even in some instances where all info is there, the spacing seems off.

i think the share prompt is supposed to be on the line below the campaign lead info.

see http://staging.beta.dosomething.org/campaigns/patient-playbooks?source=node/1165

when viewing full screen on my macbook air in chrome looks off:

![image](https://cloud.githubusercontent.com/assets/6330971/9528979/b177b0c8-4cc5-11e5-96d6-7ad1f51ad60a.png)

when viewing with a slightly smaller browser it looks great:
![image](https://cloud.githubusercontent.com/assets/6330971/9528993/bbdba6be-4cc5-11e5-85cc-9a3cf8702c32.png)

**Comment by mikefantini** [comment]
@sbsmith86 do you mind taking a peek when you have a sec?

not a huge rush
