### ISSUE TITLE
Campaign Gallery should be showing promoted and approved items for single reportback

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4924]
On this campaign: http://staging.beta.dosomething.org/campaigns/please-dont-break-anything, only `promoted` reportbacks are showing from a Reportback that contains multiple reportback-items with both `approved` and `promoted` statuses, and may be an issue across other campaigns.

**Comment by namimody** [comment]
@weerd do you know if this was addressed by #4927? thanks!

**Comment by angaither** [comment]
@namimody ya it was 🍶
