### ISSUE TITLE
hot module not showing despite being in range

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4926]
[This campaign](http://staging.beta.dosomething.org/node/1656/edit) created by [uid 8](http://staging.beta.dosomething.org/user/8) has a high season that ends on August 27th 2015. However, on August 26th 2015 at 8:24pm EST the hot module is not showing up for me as [this new user - uid 1705230](http://staging.beta.dosomething.org/user/1705230) I just created.

For [uid 8](http://staging.beta.dosomething.org/user/8) who created the campaign, it is showing up as ending in 3 hours (as of August 26th 8:24pm EST).

uid 8 has time zone set as America/New York. uid 1705230 has time zone set as UTC.

How do we make it so that:
1. The hot module expires at 11:59pm EST the night of the end of the high season
2. That all users see this as being the end time (i.e. at 10:59pm EST users in New York, Chicago, LA, Sydney, Rome, etc. all see 1 hour left)

![image](https://cloud.githubusercontent.com/assets/6330971/9509671/7e6d38c8-4c30-11e5-97bf-9b0d3461e447.png)

UID 1705230:
![image](https://cloud.githubusercontent.com/assets/6330971/9509730/ff3cd08a-4c30-11e5-8f02-80b01f6e2b86.png)

UID 8:
![image](https://cloud.githubusercontent.com/assets/6330971/9509751/40fe8e28-4c31-11e5-9103-ee3737019742.png)

**Comment by angaither** [comment]
@deadlybutter can you take a look at this?

**Comment by itsjoekent** [comment]
I'll see if Drupal has anyway built in way of converting time zones / getting the differences

**Comment by weerd** [comment]
Adding here for reference:
 For Campaign class ended up creating a custom helper function to deal w/ the dates in Droops that might help:

https://github.com/DoSomething/phoenix/blob/d0f9f0b20bfe6973f527ab52af984eeddc9bc373/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L66

**Comment by namimody** [comment]
Hey guys, not sure if I'm missing something but here is what I am seeing around 6 PM EST on 8.31. I believe I should be seeing about 6 hours left?
![image](https://cloud.githubusercontent.com/assets/12396076/9591752/94bcd55a-500b-11e5-8cee-81e0cebaf3c7.png)

**Comment by itsjoekent** [comment]
:rage: :tableflip: I'll look again tomorrow first thing, I dont understand why timing logic gives us so many problems

**Comment by itsjoekent** [comment]
weee this is interesting, hot module is off and win module is displaying now, and it's not been 21 hours since you posted that

https://www.dosomething.org/campaigns/lead-stampede?source=node/1141
