### ISSUE TITLE
no approved reportbacks showing up in gallery at all

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4927]
only promoted reportbacks are showing up, no promoted are showing up at all

see http://staging.beta.dosomething.org/campaigns/hot-module

potentially related to #4924

**Comment by mikefantini** [comment]
hmmm actually i take it back.

that campaign is acting funny, but http://staging.beta.dosomething.org/campaigns/patient-playbooks looks good.

self assigning for now, will dig in more later

**Comment by angaither** [comment]
closed with #6081 #6102
