### ISSUE TITLE
Progress Update value not reflected in hot module graph

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4929]
when I enter a value in the Progress Update field on custom settings it updates the number displayed above the graph but not the graph itself.

see [node 1283](http://staging.beta.dosomething.org/campaigns/patient-playbooks)

![image](https://cloud.githubusercontent.com/assets/6330971/9510659/7c4b8746-4c3c-11e5-8fac-a3a2751f1e53.png)

![image](https://cloud.githubusercontent.com/assets/6330971/9510673/9eb8b736-4c3c-11e5-9e1f-6481dcb9a5ff.png)

@angaither not sure if that's a you or @sbsmith86 thing

cc: @namimody

**Comment by angaither** [comment]
in [`dosomething_reportback.cron.inc`](https://github.com/DoSomething/phoenix/blob/f9d8acb18317e51ec4c06ed56071dfcc81e9cd53/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.cron.inc#L24) before setting the variable it should also get the progress override and add the two together

**Comment by sbsmith86** [comment]
^^ Si, if the value gets added there, it will be reflected in the graph.
