### ISSUE TITLE
some copy from campaign fields were wiped from production in translation deploy

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4930]
it seems like the "What You Get" section has been wiped from production

example [node 2930](https://www.dosomething.org/node/2930/edit)

**Comment by sergiitk** [comment]
This is one of translatable fields. Let's wait for the script to finish and clean cache. This may help.

**Comment by mikefantini** [comment]
got it thanks @sergii-tkachenko

**Comment by sergiitk** [comment]
Looks like it hasn't been erased from Thor, I expect this to be on same on prod: https://thor.dosomething.org/node/2930/edit

**Comment by sergiitk** [comment]
Hm, it looks like the field exists in other nodes on prod: https://www.dosomething.org/node/74/edit?destination=admin/content.
Could it be somebody removed it by an accident earlier?

**Comment by mikefantini** [comment]
i'm seeing a few fields that seem to be wiped right now @sergii-tkachenko 

[node 1508](https://www.dosomething.org/node/1508/edit) is missing:
- What You Get
- Secondary Call to Action
- Time and Place

**Comment by sergiitk** [comment]
@mikefantini Script executed 100%. Yes, it looks like some fields have been lost. Don't know why yet, there was no errors during the execution. Plus, I ran it over thor db (created from prod) and it was fine...

**Comment by sergiitk** [comment]
I'll re-run the deployment procedure to make sure everything is on.

**Comment by sergii-tkachenko** [comment]
Regarding 1508: field value is in the db, figuring out why it's not displayed:

```
+-------------+----------+---------+-----------+-------------+----------+-------+-----------------------------------------------------------+-----------------------------+
| entity_type | bundle   | deleted | entity_id | revision_id | language | delta | field_call_to_action_value                                | field_call_to_action_format |
+-------------+----------+---------+-----------+-------------+----------+-------+-----------------------------------------------------------+-----------------------------+
| node        | campaign |       0 |      1508 |       15274 | en       |     0 | Make and share Thumb Socks to reduce texting and driving. | NULL                        |
+-------------+----------+---------+-----------+-------------+----------+-------+-----------------------------------------------------------+-----------------------------+
```

**Comment by sergiitk** [comment]
What You Get field of 1508 doesn't exist in db:

```
mysql> SELECT * FROM `field_data_field_value_proposition` WHERE `entity_id` = 1508;
Empty set (0.00 sec)
```

cc @sheydari-ds

**Comment by mikefantini** [comment]
sorry @sergii-tkachenko a bit confused, I expect node 1508 to have each of
- What You Get
- Secondary Call to Action
- Time and Place

which of these are you saying don't exist in the db?

**Comment by sergiitk** [comment]
So it looks like that for **some** fields records in data database got missed. I will create a script that restores it from the last data revision. Agreed with @sheydari-ds.

**Comment by namimody** [comment]
Campaign specific starter statement copy also seems to have disappeared from front end and back end for some campaigns:

https://www.dosomething.org/campaigns/get-lucky?source=node/1141
https://www.dosomething.org/campaigns/lead-stampede?source=campaigns

Seems to appear fine on:
https://www.dosomething.org/campaigns/birthday-mail
https://www.dosomething.org/campaigns/school-standstill?source=campaigns

**Comment by namimody** [comment]
Yellow staff pick label on homepage also seems to have disappeared: 

![image](https://cloud.githubusercontent.com/assets/12396076/9530808/0bd7af00-4cd0-11e5-868a-ffb427462a77.png)

**Comment by mikefantini** [comment]
@namimody created an issue for your comment as it appears to be unrelated. #4944

**Comment by sergiitk** [comment]
@mikefantini actually #4944 is not related.

**Comment by mikefantini** [comment]
it looks like https://www.dosomething.org/node/3501/edit had all of it's content wiped too. Sam says that she saw it all there on tuesday.

**Comment by mikefantini** [comment]
@sergii-tkachenko @sheydari-ds

**Comment by mikefantini** [comment]
@sergii-tkachenko another example https://www.dosomething.org/node/1536/edit

I think it might be any campaigns that were unpublished did not get updated in your last fix for this.

**Comment by sergiitk** [comment]
@mikefantini I found easy way to fix this. When you see such campaign, just click `Translate` tab, then `Edit` again. Missing fields will be restored automatically: https://www.dosomething.org/node/1536/edit

**Comment by sergiitk** [comment]
It looks like the translation module didn't create translations for unpublished nodes. It does it automatically on the `Translate` tab.

**Comment by mikefantini** [comment]
hmm ok thanks @sergii-tkachenko
