### ISSUE TITLE
br admin and mx admin should only have access to br and mx fields

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4934]
As a brazil admin or mexico admin, I should only have access to Brazilian Portuguese fields or Mexican Spanish fields respectively (i.e. I shouldn't be able to create a campaign in the English fields nor should I be able to edit any content in the English fields).

Currently, when I go to create a campaign as a brazil admin I:
1. default am presented with English fields
2. have access to non translated fields (like Primary Cause, Cause, Primary Action Type, etc.)

Also when switching from English to Brazilian Portuguese I still have the non translated fields presented to me.

What should happen is that when trying to create a campaign as a brazil admin:
1. Brazilian Portuguese should be default selected as the language on /node/add/campaign
2. I shouldn't be able to change this language
3. Only Brazilian Portuguese fields should show to me - so if the field was not made translatable, then I should not be able to enter content in that field.

cc: @julielorch @sergii-tkachenko @blisteringherb @sheydari-ds

**Comment by sergiitk** [comment]
Here's few thoughts on technical implementation:
- Alter node edit form
- Check if the content type being edited is translatable. You can do this by checking corresponding `language_content_type` variable, e.g. `language_content_type_campaign`.
- Check if user editing the content is in restricted local groups (Brazilian or Mexican admin, or we can assign a common group to this users, like Regional Sitemanager)
- Go through all available fields recursively. If the field is not translatable, hide it using [`hidden`](https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7#hidden) form API attribute
- Optional: hide a container if it contains only hidden fields

Here's how to determine if a field is translatable: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.drush.inc#L145-L152

**Comment by joolaay** [comment]
![country partner admin view v2](https://cloud.githubusercontent.com/assets/6331017/9550589/3d11b34a-4d7a-11e5-950a-3f507a3a7cda.jpg)
![country partner admin view v22](https://cloud.githubusercontent.com/assets/6331017/9550593/3d16dbe0-4d7a-11e5-8fae-e35b025d9f58.jpg)
![country partner admin view v23](https://cloud.githubusercontent.com/assets/6331017/9550590/3d12661e-4d7a-11e5-9610-365ab0fe5808.jpg)
![country partner admin view v24](https://cloud.githubusercontent.com/assets/6331017/9550591/3d13ec32-4d7a-11e5-8b3e-c4a729936f08.jpg)
![country partner admin view v25](https://cloud.githubusercontent.com/assets/6331017/9550592/3d14e092-4d7a-11e5-93bf-1a958370246f.jpg)

@sergii-tkachenko @mikefantini: Here are admin wires for Campaign Add + Image Upload.

**Comment by mikefantini** [comment]
@blisteringherb @angaither would love if you two could weigh in here as well with any thoughts

**Comment by angaither** [comment]
@sergii-tkachenko your solution sounds :+1:

**Comment by blisteringherb** [comment]
I'm wondering if a simpler solution might be to hide the 'Translate' tab, and then only allow users to see the translation that applies to them on the node edit page. I'm thinking that putting in a hook_menu_alter for node/%/edit that triggers the add translation chain if the allowed translation hasn't yet been created for that node and if it already exists it will send the user to node/%/edit/es-mx so they never actually get to the edit screen for the non-allowed translations.

For instance if a user with the Brazil admin role tries to visit `node/36/edit`, they'll be redirected to `node/36/edit/pt-br` if the translation already exists, and if not they'll go to `node/57/edit/add/en/pt-br`.  The other languages in the upper right corner of the node edit screen will be hidden except for those that they're allowed to see, and they won't have access to the translate tab.

For node/add, the user will just be sent to node/add/campaign, where the language drop down will be selected on the default language for that role, but other allowed languages will be available.

We'll probably need a strongarm variable for each of these roles with the default and available languages.

**Comment by mikefantini** [comment]
@blisteringherb - thanks for the comments! 

The way the Brazil/Mexico Admin roles are structured right now are that these editors can only edit their own content, not edit content another user created. But given that we may need to change this permission moving forward, this solution would make me feel more comfortable with that because the bottom line is that we only want a Brazilian Admin interacting with Brazilian Portuguese fields.

The critical path for this is a Brazilian/Mexican Admin being able to create campaigns in their language, so focusing on the /node/add/campaign experience. And just to be clear, _we never want_ a Brazilian/Mexican admin interacting with fields outside of their language. So in the /node/add/campaign experience not only should Brazilian Portuguese be default selected for a Brazilian Admin, but that user _should not_ be able to change the language.

**Comment by mikefantini** [comment]
related issue: #4835

**Comment by mikefantini** [comment]
one thing that should be done here is that on /admin/config/regional/entity_translation:
- [ ] default language should be set to "Author language"
- [ ] hide language selector should be selected
- [ ] exclude language neutral from the available languages should be selected

basically it should look like this:

![image](https://cloud.githubusercontent.com/assets/6330971/9615147/623f33b6-50c4-11e5-9c2a-66736139e3e8.png)

cc: @angaither @deadlybutter

**Comment by angaither** [comment]
@mikefantini @blisteringherb I actually don't see those config options in the strongarm variables to export... in the db i see one setting for each node types eg `entity_translation_settings_node__campaign`

but (maybe I'm being dense) it doesn't look like it's exportable??

@mikefantini that means it won't get overriden when we deploy, but we should probably still figure out a way to capture/export it

**Comment by mikefantini** [comment]
got it thanks @angaither. mind creating an issue for that?

**Comment by mikefantini** [comment]
also @angaither do you want me to make sure prod/thor are configured like this then?

**Comment by blisteringherb** [comment]
@angaither You're right, I don't see it in the possible Strongarm exports from Features, but I'm wondering if you manually set up the strongarm export if it will work.

**Comment by itsjoekent** [comment]
PR to fix this was merged https://github.com/DoSomething/phoenix/issues/5004 but keeping open until its verified on Thor

**Comment by mikefantini** [comment]
@deadlybutter meta tags and revision information should be hidden as well for Brazil admin and Mexico admin
![image](https://cloud.githubusercontent.com/assets/6330971/9667721/88fd6f3a-524b-11e5-976b-711feeb53ea0.png)

**Comment by angaither** [comment]
@deadlybutter in permissions

**Comment by itsjoekent** [comment]
The meta-tag permission worked fine but the revisions aren't going down as easy

<img width="1351" alt="screen shot 2015-09-04 at 9 51 01 am" src="https://cloud.githubusercontent.com/assets/897368/9685179/91d19de4-52ea-11e5-8862-be7a6b4546a8.png">
