### ISSUE TITLE
add more copy to error message if cc doesn't go through on /donate

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4938]
can't find existing error message copy but please add to it "Having problems with donating? Please try again or email donate@dosomething.org."

@deadlybutter please post what full copy of error message would be here just to make sure it all makes sense together.

related to #4937

**Comment by itsjoekent** [comment]
I found where the error is being set (Line #415 in payment module),

```
    $error = $e->getMessage();
    drupal_set_message($error, 'error');
```

There is error messages depending on what went wrong (Italic text is the current error message),

_Your card was declined._ Having problems with donating? Please try again or email donate@dosomething.org.

_Your card's security code is incorrect._ Having problems with donating? Please try again or email donate@dosomething.org.

_Your card has expired._ Having problems with donating? Please try again or email donate@dosomething.org.

_The zip code you supplied failed validation._ Having problems with donating? Please try again or email donate@dosomething.org.

**Comment by mikefantini** [comment]
@deadlybutter looks good to me. Only edit would be for the last one to read "Your zip or postal code does not match the card provided. Having problems with donating? Please try again or email donate@dosomething.org."

**Comment by itsjoekent** [comment]
Hm, I can do that but the code's gonna be a little funky since thats the copy Stripe provides in its API response

**Comment by mikefantini** [comment]
oh ok nevermind then @deadlybutter - super annoying that they provide such whack copy.

not worth doing funky code to change it

**Comment by itsjoekent** [comment]
alrighty
