### ISSUE TITLE
query of campaigns where high season end date is on or after August 31st 2015

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4940]
need query of campaigns where high season end date is set any time on or after August 31 2015? b/c of the way that we set up hot module, but without wanting _all_ campaigns to have it just yet we need to take high season off for any campaigns that end Aug 31 (and also end Sept 30 and Oct 31 just in case)

**Comment by angaither** [comment]
```
select n.nid, n.title, hs.field_high_season_value, hs.field_high_season_value2
from node n
inner join field_data_field_high_season hs on hs.entity_id = n.nid
where n.type = 'campaign'
and hs.field_high_season_value2 > '2015-08-31 00:00:00'
order by hs.field_high_season_value2 DESC;
```
