### ISSUE TITLE
need a solution for win module w/ impact number in millions

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4942]
rare, but could happen

@lkpttn please advise. do we use a smaller font?

![image](https://cloud.githubusercontent.com/assets/6330971/9528895/232350ca-4cc5-11e5-9816-b2f3ed1bc9c7.png)

**Comment by sbsmith86** [comment]
@lkpttn @mikefantini Did we make a decision on how to handle this situation? I can't remember.

**Comment by lkpttn** [comment]
@sbsmith86 When you get back we can take a look at it, but I think we scaled everything down with the breakpoints to take care of it.

**Comment by mikefantini** [comment]
@lkpttn @sbsmith86 are we good on this issue? Did you two ever sync on this?

**Comment by sbsmith86** [comment]
@mikefantini nope, but i can test some stuff out and we send screenshots to see if it works @lkpttn

**Comment by mikefantini** [comment]
Great thanks @sbsmith86!

**Comment by angaither** [comment]
NOPE
