### ISSUE TITLE
staff pick label missing from homepage

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4944]
Yellow staff pick label on homepage also seems to have disappeared. happening on staging and prod.

working properly on both staging and prod on /volunteer/

also working properly when i filter campaigns on the homepage

![image](https://cloud.githubusercontent.com/assets/12396076/9530808/0bd7af00-4cd0-11e5-868a-ffb427462a77.png)

**Comment by sergiitk** [comment]
Hey, already worked out the fix.

**Comment by mikefantini** [comment]
@sergii-tkachenko - :speedboat:
