### ISSUE TITLE
CSS Not Applying on Donate Module

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4948]
![image](https://cloud.githubusercontent.com/assets/12396076/9533540/bd49dca8-4ce0-11e5-8ef2-e623eb9d0916.png)

ZIP and postal code field should be shorter.

**Comment by itsjoekent** [comment]
Because we switched back to Paypal (https://github.com/DoSomething/phoenix/issues/4838#issuecomment-135792333) I'm going to assume this is low priority for now @mikefantini ?

**Comment by mikefantini** [comment]
yup definitely. thans @deadlybutter

**Comment by angaither** [comment]
going to close until/if we switch back to stripe
