### ISSUE TITLE
Global Admin Role

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4949]
Some of this is TBD conversation with Micah and Bladt but starting a list.

I also want us to finalize a real definition of the purpose of the Global Admin
### New requirements
- [x] Access to admin menu

---

---
##### Old requirements

Global Admin should have access to:
- [x] fields in all languages
- [x] config -> DS config -> DS campaign
- [x] publish content
- [x] publish translations
- [x] all other fields editors have access to

**Comment by itsjoekent** [comment]
@mikefantini Is this still being decided on or can I start workin on this?

**Comment by mikefantini** [comment]
@deadlybutter this can be worked on, it's just an incomplete list, so please just mark off boxes rather than closing the issue

**Comment by itsjoekent** [comment]
sure thing, ill also make sure the PR says not to merge until you tell me the list is complete

**Comment by mikefantini** [comment]
@deadlybutter i believe we can merge it, we may just need to add permissions in the future

**Comment by itsjoekent** [comment]
gotcha

**Comment by angaither** [comment]
blocked on deciding which new permissions we need to give regional admins

**Comment by mikefantini** [comment]
closing. will open new issues as new permissions are needed

**Comment by itsjoekent** [comment]
Created a new global admin on prod, tried going to /admin/content, got a 404

This is blocking me from testing what issues are / aren't working on prod & thor (which is now a thing I need to look for)

**Comment by itsjoekent** [comment]
Going to update the original issue with new checklist of things global admins are missing (looking at prod atm). @mnelson338 at some point in the near future I will have you login as a global admin and see if you think you're missing access to anything still

**Comment by angaither** [comment]
I think we are good with this one
