### ISSUE TITLE
Brazil Admin/Mexico Admin should see edit tab on campaign view page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4951]
As a logged in user with the Brazil Admin or Mexico Admin role when I'm on a campaign page that I created I should:
1. see the action page, not the pitch page
2. see the edit tab when viewing the action page (same as an editor role would see it)

![image](https://cloud.githubusercontent.com/assets/6330971/9547931/8bab928c-4d6b-11e5-8592-2c585b5578fb.png)

**Comment by angaither** [comment]
@deadlybutter mind knocking this one out? 
the action page access is because the user roles need to be added to the `dosomething_user_is_staff()` check
though, can you check that function and post here what else that is called by/what that gives the editor access to?

**Comment by itsjoekent** [comment]
sure thing

**Comment by itsjoekent** [comment]
`dosomething_user_is_staff` has an array of user roles which it uses for verification
- administrator
- editor 
- communications team
- member support 

that function is called in a few places
- Gives them access to a few extra user fields (filed_partner, field_school_id, field_user_registration_source, picture, field_under_thirteen, field_job_title)
- Allows them to view all term pages https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_taxonomy/dosomething_taxonomy.module#L32
- Un-signup https://github.com/DoSomething/phoenix/blob/ffb2ee968fc45dc5854ccb03c3dbf993eb38fe05/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L750
- Pitch page access 
  https://github.com/DoSomething/phoenix/blob/025f19fc9c2289b31c7b9f405cf52712f0389d58/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L293
- Bypass pitch page to view full action page
  https://github.com/DoSomething/phoenix/blob/025f19fc9c2289b31c7b9f405cf52712f0389d58/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L785
- access to confirmation page regardless of reportback status.
  https://github.com/DoSomething/phoenix/blob/025f19fc9c2289b31c7b9f405cf52712f0389d58/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L367
- display tabs 
  https://github.com/DoSomething/phoenix/blob/83b61d349fc441a5e9ff79eb7de11f5dcb57256f/lib/themes/dosomething/paraneue_dosomething/includes/preprocess.inc#L83

**Comment by angaither** [comment]
@deadlybutter what is tabs?

**Comment by angaither** [comment]
@deadlybutter perhaps we should just add `dosomething_global_is_regional_admin` as a check to action page access, because it looks like we won't want regional admins to have access to all those things.

**Comment by itsjoekent** [comment]
@angaither I was assuming 'tabs' are the tabs above a node "edit view etc". its in the preprocess file (not module specific) so it makes sense I guess?

and yeah I was thinking thats probably the best route to go (re: pitch page)

**Comment by angaither** [comment]
:+1: let's go the `regional_admin` test then
