### ISSUE TITLE
Global User Registration Emails

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4955]
When a Brazilian/Mexican user creates an account, s/he should receive a welcome to DS email in Brazilian Portuguese/Mexican Spanish.
- [x] Brazilian Portuguese user registration email
- [x] Mexican Spanish user registration email

Note: I don't think we have to add anything for the "Global English" users, because our default US English transactional email should trigger and should be good to use. Only potential pitfall is if linking people to /campaigns (which the email currently does) is a problem for global users - i.e. will this redirect global users to the global version of /campaigns.

@sergii-tkachenko I believe @DeeZone had a question on how he/message broker would know which mandrill template to send to which user (i.e. how to know whether to use the Brazilian Portuguese template or the US English one for example).

---
- [x] Update `dosomething_user_new_user()` to include user language
- [x] Update `dosomething_user_new_user()` to include new user template name **OR** allow `dosomething_mbp()` to define template name.
  https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L448-L514

```
      $params = array(
        'email' => $account->mail,
        'uid' => $account->uid,
        'user_language' => dosomething_user_get_field('field_language', $account),
        'email_template' => $template,
        'first_name' => dosomething_user_get_field('field_first_name', $account),
        'reset_link' => user_pass_reset_url($account),
      );
```
- [x] Update `dosomething_mbp_get_template_name()` to define the template name based on the user language rather than the current `dosomething_settings_get_affiliate_country_code()`. Use the `user_language` value in the `$param` value passed in the `dosomething_mbp_request()` call.

**Note**: Country code is currently returned by `dosomething_settings_get_affiliate_country_code()`  rather than language of user. 

---

**Related**:
- Trello card for Message Broker:
  - https://trello.com/c/Qieo5HqA
  - https://trello.com/c/JbcQKzvl

**~~BLOCKED by~~**:
- https://github.com/DoSomething/phoenix/issues/5168 There a need for the user language setting to define the transactional template name.

**Comment by sergiitk** [comment]
cc @sheydari-ds. How are we going to detect user county? Fastly headers?

**Comment by ghost** [comment]
@sergii-tkachenko Yes, it's going to be via Fastly Country-code headers.

**Comment by sergiitk** [comment]
Ok, we can implement custom language detection strategy and just pass current language code to the templates.

**Comment by deezone** [comment]
@sergii-tkachenko Can I assume that the Fastly header / user country will be set in the Drupal user profile?

The goal is user registration and password reset transactionals use the country templates (thus language) based on the initial Fastly detected user origin.

**Comment by deezone** [comment]
@sergii-tkachenko @mikefantini Is there an issue to build the "custom language detection strategy" functionality into the Drupal code base? This functionality could then be referenced when generating the transactional message request for Message Broker.

**Comment by sergiitk** [comment]
I don't think so. @sheydari-ds?

**Comment by ghost** [comment]
@sergii-tkachenko @DeeZone I don't think so. We're doing detection on that header for a number of other things in Drupal anyways, so I don't see this as being a huge lift.

**Comment by mikefantini** [comment]
@sheydari-ds do you mind creating an issue for this just to make sure all the work that's needed is documented?

**Comment by ghost** [comment]
@mikefantini Referenced here: https://github.com/DoSomething/phoenix/issues/4959
