### ISSUE TITLE
Global Campaign Signup Transactional Email

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4956]
When a user signs up for a campaign, s/he should receive a campaign signup email in the same language as the translation of the campaign s/he signed up for. i.e. if I sign up for the Brazilian Portuguese translation of node 123, I should receive a Brazilian Portuguese campaign signup email
- [x] Brazilian Portuguese campaign signup email
- [x] Mexican Spanish campaign signup email

Also note that we need to make sure we're pulling in the proper fields for this since technically the Brazilian Portuguese and Mexican Spanish content are in different fields than the US English fields.

@sergii-tkachenko @sheydari-ds if you have any thoughts to advise @DeeZone on this please include here.

**Comment by marahml** [comment]
For separate Global transactionals, we currently don't have any new work slotted for v1. Only BR & MX. 

So a total of 8 new templates (4 per country) that are translated and match to new fields is our current focus.

If steps will be different for Global vs. US campaigns - is that something we can solve for on the content side? @mikefantini @DeeZone

**Comment by mikefantini** [comment]
created a new issue for Global English in case we can't get all templates up for launch: #5091

**Comment by deezone** [comment]
@marahml What is the difference between the expected email message sent to users who defined as "GLOBAL" vs "US"?

Is the only difference the MailChimp account / list assignment?

**Comment by marahml** [comment]
I think the main difference would be the merge tags we pull in -- but just basing that off of the issue #5091.

This is lowest priority of all templates - so focus is still on Registration & PW reset currently, then Signup and RB.

**Comment by mikefantini** [comment]
yup lowest priority. the key difference is we'll just need to literally pull from different fields because the content will be stored in different fields for users from US/BR/MX/everywhere else

**Comment by blisteringherb** [comment]
@mikefantini @marahml @DeeZone 

Can I get a list of what fields are are different? I've got the translated version of "field_pre_step_header" and "field_post_step_header" being pushed into the payload. Are those fields not used for br and mx?

**Comment by mikefantini** [comment]
just talked with @blisteringherb IRL. the translated copy is being pulled in properly so we're all good

**Comment by sheyd** [comment]
@blisteringherb Morgan, can we close this out?

**Comment by blisteringherb** [comment]
Yes, I think so. I pushed those changes yesterday and they look good to me today.
