### ISSUE TITLE
Global Report Back Transactional Email

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4957]
When a user reports back on a campaign, s/he should receive a report back transactional email in the same language as the translation of the campaign s/he reported back on. i.e. if I report back on the Brazilian Portuguese translation of node 123, I should receive a Brazilian Portuguese report back transactional email
- [ ] Brazilian Portuguese report back transactional email
- [ ] Mexican Spanish report back transactional email

Also note that we need to make sure we're pulling in the proper fields for this since technically the Brazilian Portuguese and Mexican Spanish content are in different fiends than the US English fields.

And same as my comment on #4955 we need to make /campaigns will take the user to the correct version of that URL depending on their location, but I think this should be fine.

@sergii-tkachenko @sheydari-ds if you have any thoughts to advise @DeeZone on this please include here.

**Comment by deezone** [comment]
@mikefantini @blisteringherb Is QB on the campaign signup and reportback transactions. Assigning this issue to him.

**Comment by marahml** [comment]
Same question as on this issue (https://github.com/DoSomething/phoenix/issues/4956). I'd love to not create any new templates / dev for launch if possible. 

Can you elaborate a bit more on how campaign titles will differ @mikefantini ?

**Comment by mikefantini** [comment]
created a new one for global english #5090.

I could see a situation where a title doesn't make sense globally but we'd want to keep the saying locally

i.e. a campaign that has Gym in the title vs. P.E.
