### ISSUE TITLE
Global Password Reset Emails

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4958]
When a user forgets her/his password, s/he should receive a password reset email in the same language as the version of the site s/he is viewing. i.e. if I am located in Brazil, I should receive the Brazilian Portuguese reset password email.
- [x] Brazilian Portuguese password reset email
- [x] Mexican Spanish password reset email

Note: I don't think we have to add anything for the "Global English" users, because our default US English transactional email should trigger and should be good to use. Only potential pitfall is if any funny business needs to happen to the link we provide in the email.

@sergii-tkachenko @sheydari-ds if you have any thoughts please include here

---
- [x] Update `dosomething_user_user_pass_submit()` to include user language
- [x] Update `dosomething_user_user_pass_submit()` to include password reset template name
  https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L415-L437

```
      $params = array(
        'email' => $account->mail,
        'uid' => $account->uid,
        'user_language' => dosomething_user_get_field('field_language', $account),
        'email_template' => $template,
        'first_name' => dosomething_user_get_field('field_first_name', $account),
        'reset_link' => user_pass_reset_url($account),
      );
```
- [x] Update `dosomething_mbp_get_template_name()` to define the template name based on the user language rather than the current `dosomething_settings_get_affiliate_country_code()`. Use the `user_language` value in the `$param` value passed in the `dosomething_mbp_request()` call.

**Note**: Country code is currently return with returned rather than language of user / campaign. 

---

**Related**:
- Trello card for Message Broker:
  - https://github.com/DoSomething/phoenix/issues/4955
  - https://trello.com/c/HT3AuNGA
  - https://trello.com/c/n9DN4bKF

**~~BLOCKED by~~**:
- https://github.com/DoSomething/phoenix/issues/5168 There a need for the user language setting to define the transactional template name.

**Comment by deezone** [comment]
Related Trello card on Message Broker board: https://trello.com/c/HT3AuNGA

**Comment by deezone** [comment]
`dosomething_user_user_pass_submit()` $params:

```
Array
(
    [email] => dlee+vag01@dosomething.org
    [uid] => 1705348
    [first_name] => Test Dee
    [reset_link] => http://dev.dosomething.org:8888/user/reset/1705348/1443018806/bnCyX8yrx66VCC7PCvE4g8QUvsL8gj-78HuCuHfSD4Q
    [user_language] => en-global
    [user_country] => US
)
```

`message_broker_producer_request()` payload to RabbitMQ server:

```
a:10:{s:8:"activity";s:13:"user_password";s:5:"email";s:26:"dlee+vag01@dosomething.org";s:3:"uid";s:7:"1705348";s:13:"user_language";s:9:"en-global";s:12:"user_country";s:2:"US";s:10:"merge_vars";a:3:{s:12:"MEMBER_COUNT";s:11:"3.5 million";s:5:"FNAME";s:8:"Test Dee";s:10:"RESET_LINK";s:105:"http://dev.dosomething.org:8888/user/reset/1705348/1443027553/qvucS0vJX0h8T_DQCGLYjNB5q14vEPN7NVHjAAJZfsA";}s:14:"email_template";s:19:"mb-user-password-US";s:10:"email_tags";a:1:{i:0;s:20:"drupal_user_password";}s:18:"activity_timestamp";i:1443027553;s:14:"application_id";s:2:"US";}
```
