### ISSUE TITLE
Ensure Unified Drupal Detection Mechanism for All Fastly Countries Codes

### ISSUE THREAD

**Issue by ghost** [DoSomethingArchive/legacy-website#4959]

**Comment by deezone** [comment]
Country Code value for the current user needs to be available to `dosomething_mbp.module` here: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_mbp/dosomething_mbp.module#L218-L233

Currently `dosomething_settings_get_affiliate_country_code()` takes care of defining the value.

**Comment by mshmsh5000** [comment]
Let's put this in somewhere central like [dosomething_settings](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_settings/dosomething_settings.module). There should be a function for each header we're passing from Fastly:

![fastly-headers](https://cloud.githubusercontent.com/assets/149811/9860236/d002dd4c-5af8-11e5-9b8e-9390404b0842.png)

So
- `dosomething_settings_get_geo_city()`
- `dosomething_settings_get_geo_country_code()`
- `dosomething_settings_get_geo_country_name()`
- `dosomething_settings_get_geo_latlong()` (or something, makes sense to return as a tuple)
- `dosomething_settings_get_geo_region()`

**Comment by mshmsh5000** [comment]
Then for the comment from @DeeZone above, we can update the MBP logic to check `dosomething_settings_get_geo_country_code()` first and let that value override, if it exists. This should take care of the dedicated affiliate sites where this code also needs to work, and where the affiliate value is hard-coded.

**Comment by angaither** [comment]
@sheydari-ds how do we test fastly settings locally?

**Comment by itsjoekent** [comment]
not @sheydari-ds but he picked out a VPN/Proxy we're gonna use http://torguard.net/ 

oh shit that won't work locally will it?

hey @sheydari-ds how do we test fastly settings locally?

EDIT: Possible solution I just though of. Use a tool like ngrok (https://ngrok.com/) to map our local URL to a public one on the internet. When developing hide behind a proxy via torguard and hit the public URL I just described.

**Comment by ghost** [comment]
@angaither @deadlybutter For individual requests you can forward the headers manually using Postman (e.g. X-Fastly-Country-Code: BR), @mshmsh5000 Is going to comment on more Dev friendly approaches for bigger workflow testing.

**Comment by mshmsh5000** [comment]
The easiest solution for local testing would be to modify https headers within the browser, so you can browse as a Brazilian, Mexican, etc., user. Try a popular extension like ModHeader:

https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en
