### ISSUE TITLE
meta data on campaign nodes need to be translated w/ a default

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4966]
- Page Title
- Description
- Abstract
- Keywords
- Twitter Card Title
- Twitter Card Description
- Google News Keywords

Brazil Admin and Mexico Admin should not have access to these, but we need to make sure we're pulling in the corresponding fields and using translated defaults.

i.e. instead of the description being "Volunteer and take action! [node:field_call_to_action]" for a mexican version of the campaign, it needs to be "Hacer de voluntario y tomar medidas! [node:field_call_to_action_mexican_spanish]" or something like that.

**Comment by mshmsh5000** [comment]
The [Metatag](https://www.drupal.org/project/metatag) fields are supposedly translatable via Entity Translation.

**Comment by mikefantini** [comment]
This will effect FB posts for problem shares:

![image](https://cloud.githubusercontent.com/assets/6330971/11045656/bcea6dea-86f6-11e5-99be-a5b156e34499.png)

**Comment by mikefantini** [comment]
Also effecting hot module shares:

![image](https://cloud.githubusercontent.com/assets/6330971/11045990/a0fad924-86f8-11e5-9a43-af32205a4336.png)
