### ISSUE TITLE
need BR, MX, and Global versions of homepage

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4968]
we decided we're going to be translating the home content type just like we did with campaign content types.

---

Would include the 9 campaigns we want featured to BR, MX, and global users + majority of copy needs to be in appropriate language.

I think it makes most sense to give Brazil Admin, Mexico Admin, and Global Admin access to create/edit a home node and then just serve up the appropriate homepage based on where the user is coming from.

The other option would be to make all of the pages on the home node translatable, including which of the 9 campaigns we're featuring on the homepage.

thoughts @blisteringherb @sheydari-ds @angaither

**Comment by angaither** [comment]
- only edit any home page node (so they don't create more than one)
  - also this will allow for us to not have different node ids per homepage
- make `subtitle` field translatable
- make `campagins` field reference translatable

**Comment by mikefantini** [comment]
@angaither we need `title` field to be translatable too

**Comment by weerd** [comment]
I believe `title` is auto translated... like Drupal just auto assumes it needs to be translated, and if there's a translation for it and language selected, then it'll substitute. But should confirm :grimacing:

**Comment by angaither** [comment]
since it's translatable on other content types, it already is translatable :wink:

**Comment by weerd** [comment]
what @angaither said ;)

**Comment by mikefantini** [comment]
well that's just swell.

also just documenting here, we may need to translate sponsors field reference in the future but will not be doing this for this first implementation
