### ISSUE TITLE
Adding a translated title overwrites original language title

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#4973]
When adding a new translation and title or when modifying the title of an existing translation, the title of the original translation is overwritten with the translation when the node/translation is published. The original language title can be fixed, but it will be overwritten again any time a new translation and title are added or when an existing translation title is modified.

This seems to only affect the title field as far as I can tell.

**Comment by itsjoekent** [comment]
Interesting discovery, this only impacts the translation you're editing and the original source. So MX Spanish is unaffected. 

<img width="830" alt="screen shot 2015-09-14 at 3 10 27 pm" src="https://cloud.githubusercontent.com/assets/897368/9859130/c2b6a854-5af2-11e5-9027-42a0aa1f4790.png">

I wonder what happens when I edit Spanish then...

update: it overrides the source still as expected

**Comment by itsjoekent** [comment]
also just tested making a brazil campaign as a brazil admin and then updating it as MX admin, same effect as ^

**Comment by mshmsh5000** [comment]
@deadlybutter Can you try to reproduce on Thor as it's currently (properly) configured? I just tried on Veggie Surprise, and was able to edit titles of translations without overriding the original English title.

https://thor.dosomething.org/us/node/2535/edit/en

The translations have generated the right URLs as well:
- https://thor.dosomething.org/campaigns/veggie-surprise
- https://thor.dosomething.org/us/campaigns/veggie-surprise
- https://thor.dosomething.org/br/campanhos/veggie-surpresa
- https://thor.dosomething.org/mx/campanas/veggie-sorpresa

**Comment by itsjoekent** [comment]
@mshmsh5000 Ill give it a try now, but what user role were you when you edited the titles?

**Comment by mshmsh5000** [comment]
Admin, which I realize is a major factor. But the behavior's pretty
different when the language detection logic is configured correctly, so
worth a shot.

CTO
@mshmsh5000 http://twitter.com/mshmsh5000 @dosomething
http://twitter.com/dosomething

**Comment by itsjoekent** [comment]
Yeah I wasn't able to reproduce it on Thor either... Odd?

**Comment by itsjoekent** [comment]
The only thing I can immediately think of is the system language changing from en to global-en (which isnt the case on my local)

But, why would that fix it?

**Comment by itsjoekent** [comment]
Going to take another look at this soon. Will try changing ^ on my local and other settings I can think of that are different between Thor & local & prod

**Comment by sergiitk** [comment]
Found a bug report on Drupal.org for this issue:
https://www.drupal.org/node/1991988

**Comment by itsjoekent** [comment]
I searchee entity translation's issues for this but not drupal, that makes sense
