### ISSUE TITLE
Photo Not Appearing with RB

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4975]
![image](https://cloud.githubusercontent.com/assets/12396076/9860031/9d45a80e-5af7-11e5-8d2b-2a3ba1bfba04.png)

Backend looks like photo has been deleted, user profile shows black DS logo where RB photo should be shown. According to user through ZD (https://dosomethingorg1.zendesk.com/agent/tickets/88207), she submitted her RB and got 404'd and upon returning to the campaign page sees her response to why the campaign is important to her, and "add another pic" but can't update her essay and does not see her photo. (RBID 101698)

Need to figure out if this is just happening on mini iPads or if there is a way to submit reportbacks without a photo.

To try and recreate, I deleted reportback photos from this RB of mine: 

![image](https://cloud.githubusercontent.com/assets/12396076/9860124/2693f098-5af8-11e5-996c-ec4acf81291b.png)

which at least created a change log at the bottom of the RB admin view. Because no change log appeared on the member's RB, it seems the photo never came through. Next step: try on ipad mini.

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NS9azBbk&#x2F;1469-user-reported-bug-reportback-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> User Reported Bug: Reportback Issue</a>

**Comment by angaither** [comment]
closing for #6765
