### ISSUE TITLE
win module reportback image

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4976]
the win module is showing a random reportback image, but it isn't from that campaign.

it should be a random reportback image from the campaign that was hot

**Comment by itsjoekent** [comment]
```
  $parameters = array(
    'campaigns' => $vars['nid'],
    'status' => 'promoted',
    'count' => '1',
    'random' => true,
  );
  $random_image = ReportbackItem::find($parameters)[0];
  if (isset($random_image)) {
    $promoted_image = $random_image->media['uri'];
  }
```

from the win module preprocess, don't see anything wrong at a glance. Maybe campaigns should be campaign, or the vars[nid] should be encased in an array?

**Comment by itsjoekent** [comment]
apparently 'campaigns' is supposed to be nid

shamelessly inserting suggestion we need another documentation day

**Comment by weerd** [comment]
hehe :book:

**Comment by mikefantini** [comment]
on http://staging.beta.dosomething.org/campaigns/hunt-day-2-trash-scavenger-hunt?source=node/1165 which would show the win module I get the following error

![image](https://cloud.githubusercontent.com/assets/6330971/9613469/8a5b033a-50b9-11e5-866a-434235622a72.png)

**Comment by itsjoekent** [comment]
yeah theres no promoted report backs
http://staging.beta.dosomething.org/node/1286/rb/reviewed?status=2&flagged_reason=All&promoted_reason=All

Ill add a safety check but on prod I dont think we will really ever have this
