### ISSUE TITLE
Allow for mobile only campaigns

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4986]
Some campaigns are only going to be displayed in the mobile app and not in the web app at all.
The easiest solution is to leave campaigns unpublished, and return unpublished campaigns with the `on_mobile_app` field checked via the api.

Things to check for unpublished campaigns
- [x] users can signup 
- [x] users can reportback 
- [x] kudos work

**Comment by weerd** [comment]
So I think there are going to be some inherent issues with doing some hacky code to make these work w/ the whole `unpublished` approach, and users being able to sign up for it. There's core drupal access stuff that I'm concerned is going to be a major hassle to hack around to make it work :\

**Comment by weerd** [comment]
@angaither @jonuy I'm adding steps below for how to think about approaching this and would appreciate feedback!

1) mobile app user signs into mobile app
- authentication via Northstar API

2) mobile app user clicks to view mobile only campaign
- request to Drupal API to obtain `unpublished/on_mobile_app` campaign data

3) mobile app user signs up for mobile only campaign
- request to Northstar API to sign user up for campaign (?)

4) mobile app user submits reportback
- request to Drupal API to post reportback as authenticated NS user (endpoint doesn't currently exist)

_need to flesh out more, but some initial thoughts on process_

**Comment by angaither** [comment]
@weerd sounds good, and I think we will be ok with unpublished content since the singup/reportback function isn't in drupal core and doesn't care about the status of the node. 

The only other thing is step 4 can be to the [northstar api](https://github.com/DoSomething/northstar/wiki/Spec#submitting-a-campaign-report-back)

**Comment by weerd** [comment]
After some digging, I'm going to add a `?published=false` parameter to the URL for the `/campaigns` endpoint, so we can filter by `?mobile_app=true&published=false` and thus be able to select for the campaigns we want on mobile app only.

---

I'm just going to reiterate that I feel this solution will end up causing more problems than it solves. It'll make it work for the short run, but I feel we're going to run into problems later on, plus it might also be confusing to campaign creators to remember that mobile app campaigns are not published until the `on_mobile_app` is checked, and the `publish` checkmark needs to be left unchecked... seems counterintuitive.
`¯\_(ツ)_/¯`

**Comment by jonuy** [comment]
It doesn't sound like we actually need the `?published` flag. Not all campaigns shown on the mobile app are exclusive to just the mobile app. I'd say a majority would actually be available on the web. So if `?mobile_app=true` gets us both published and unpublished campaigns already, I think we've got our workaround solution in place as far as querying for campaigns.

We do still want to test if signups and reportbacks from the API to unpublished campaigns can work though. And based on what I remember from some SMS tests, I don't think they currently do. :\

**Comment by aaronschachter** [comment]
From what I recall too, I do think there's code in the Signup/Reportback entity classes that doesn't allow activity on unpublished campaigns.

I agree with @weerd's concerns above. Could we add a boolean field like `field_mobile_app_only` instead of using "published/unpublished" ? I like this approach better than a different `campaign_type` value, since a campaign could be available on the web for some runs but perhaps mobile only on others.

Also - Would we ever want to house landing pages on the web for a mobile only campaign? e.g. Hey you  can't do this "Mobile App Cats" only on the web, but download the app!

**Comment by angaither** [comment]
The reason @mshmsh5000 suggested we go this route is because we don't want the campaign to display on the site at all. We would have to do some trickery to hide it from solr and `/campaigns`

**Comment by mshmsh5000** [comment]
We have to do trickery on one side (activity against unpublished campaigns) or the other (hide some published campaigns from the web & Solr). My bet in the abstract was what @angaither described, but I will obv defer to reality here.

Just try submitting a signup and reportback against an unpublished campaign and see what happens. If it doesn't work for reasons that are difficult to address, then you'll need a search index hook to remove campaigns with a mobile-only flag, and to suppress them from a sitemap.xml, as well as perhaps some intervention for web requests that happen to find them.

Either way, we're engaging with Drupal plumbing.

**Comment by weerd** [comment]
@aaronschachter just to clarify, the idea w/ `campaign_type` would be adding a new type, something like `Mobile Campaign` so there's 3 options:
- Campaign
- SMS
- Mobile Campaign

Selecting type of `Mobile Campaign` means it only shows up on mobile... **if** a campaign is available on both web and mobile, then you'd select a type of `Campaign` and rely on the `on_mobile_app` checkbox, so it applies to both.

Your point regarding landing pages for mobile campaigns to help drive to traffic to mobile app is intriguing...

The big caveat is some effort would be involved, and then there's Solr as @angaither mentioned, which would be a pain to update, but might need to be updated in the near future for global concerns anyhoo.

@angaither hiding from `/campaigns` shouldn't be a big deal cause I have an initial approach already in the Campaign API/Transformer stuff that's looking at the `type`.

I've chatted with @angaither about this, and with @jonuy this morning and seems like for now we can roll with how it is and no need for the `?published=false` parameter as @jonuy mentioned. It'll do for now and looking into the concerns regarding signup/reportback when campaign is unpublished.

Still good to discuss and weigh the options :)

**Comment by weerd** [comment]
@mshmsh5000 yep yep! I'm doing some testing on trying to submit w/ unpublished campaigns and will let you all know what I find...

**Comment by weerd** [comment]
Doesn't look like you can sign up for an unpublished campaign. Is there a difference between `active` and `published`?

![image](https://cloud.githubusercontent.com/assets/105849/9742330/6ed93d06-562d-11e5-95bb-bc4caa895b1a.png)

_Node 1698 is a new campaign I created on local that is unpublished._

**Comment by aaronschachter** [comment]
Yes -- `active` is a value in the`field_campaign_status`, which is set to `closed` when a campaign has been closed.

**Comment by weerd** [comment]
Checked that and on the campaign the status is set to `active` but I'm getting the `403` code above.

**Comment by weerd** [comment]
So in _**dosomething_campaign.module_\* there's a function that checks for both whether a campaign is active and published which gets called when signing up a user for a campaign:

``` php
function dosomething_campaign_is_active($node) {
  // Node must be published, and campaign status != closed.
  return /*$node->status == 1 &&*/ !dosomething_campaign_is_closed($node);
}
```

By commenting out the check for `$node->status == 1` we can side-step it....

**Comment by angaither** [comment]
@weerd  we could can update that check to say (warning: pseudo code)

```
 // If it's a mobile campaign, just check if the campaign is closed
 if ( $node->mobile_app_field == 1 && !dosomething_campaign_is_closed($node)) {
   return TRUE;
 }
 // otherwise make sure the node is published
 else if ($node->status == 1 && !dosomething_campaign_is_closed($node)) {
   return TRUE; 
 } 
 // the node is unpublished or closed, NO SOUP FOR YOU
 return FALSE;
```

**Comment by angaither** [comment]
If we go the route of publishing and excluding from search/sitemap

from what I can tell... we can't just disallow it in `dosomething_search_apachesolr_query_alter` with `dosomething_search_filter_types` because we don't have the node at that point. 

it looks like there's a `hook_apachesolr_exclude` which has the node and we can check values to exclude the node from that point. 

as far as exluding it from the sitemap, it looks like we need to to that on a node by node basis, which doesn't look so terrible since it's only a couple of nodes. 

cc @blisteringherb

**Comment by weerd** [comment]
@angaither related to the pseudo code you suggested above, we could actually go a level above to the function that calls that functions which is the `_campaign_resource_access_alt()` which actually turns out to be a function that I've indicated is meant to be deprecated to begin with:

https://github.com/DoSomething/phoenix/blob/d70a566f4cca97aff4a2ce981128c630abb02ad9/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L201-L224
