### ISSUE TITLE
Clarify Fields on SMS Game Backend

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4990]
![image](https://cloud.githubusercontent.com/assets/12396076/9635569/1651224c-5165-11e5-994a-1e878c5aec17.png)

The field labels on the opt-in paths under configuration > dosomething config > third party opt ins > sms games are unclear, and have resulted in the wrong fields being filled out for multiplayer v. single player games.

**Comment by DFurnes** [comment]
Discussed this with my good friends @namimody and @tongxiang, and we're just going to throw an error if all four fields are filled in on an SMS game (rather than silently accepting the single player config and ignoring the other two fields).
