### ISSUE TITLE
make static content fields translatable

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4992]
all static content fields _except_ for the following need to be translatable:
- hero image
- video provider
- video ID
- blocks

everything else though on static content should be translatable

**Comment by angaither** [comment]
blocked by #4850

**Comment by angaither** [comment]
cc @sergii-tkachenko

**Comment by mikefantini** [comment]
@sergii-tkachenko can you please provide a status update on this one as well? Thanks!

**Comment by sergiitk** [comment]
@mikefantini Finishing this today!

**Comment by mikefantini** [comment]
`field_intro`, `field_intro_image`, and everything in the `field_gallery` field collection are not translatable and need to be.

![image](https://cloud.githubusercontent.com/assets/6330971/10680387/3c2ce35c-78ed-11e5-968d-fa9197bc8b9b.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10680392/48081e44-78ed-11e5-8455-d00cc4b1808c.png)

**Comment by sergiitk** [comment]
Translated:
- [x] `title`
- [x] `field_intro_title`
- [x] `field_cta_link`
- [x] `field_additional_text_title`
- [x] `field_additional_text`
- [x] `field_intro`
- [x] `field_intro_image`
- [ ] `field_gallery`

Already has been translated in Campaign Content Type:
- [x] `field_subtitle`
- [x] `field_call_to_action`

For V2:
- [ ] `field_partners`

**Comment by mikefantini** [comment]
@sergii-tkachenko @angaither since we have issues for the remaining work (#5628 for galleries and #5485 for partners) are we good to close this issue out?

Or at the very least since we're no longer translating static content for launch move this to 1.1?

**Comment by sergiitk** [comment]
@mikefantini :+1:
