### ISSUE TITLE
Set language detection to honor user's language preference

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#5000]
At admin/config/regional/language/configure, you can enable which type of language detection is enabled and change the weight for which detection gets priority. The user's language preference in their settings should take precedence for both interface and content translation. The variables to export are `locale_language_providers_weight_language` and `locale_language_providers_weight_language`.

**Comment by blisteringherb** [comment]
I've set this up in Thor for testing.

**Comment by angaither** [comment]
@blisteringherb is this issue taken care of, or do these vars still need to be exported to the global branch?
