### ISSUE TITLE
look into mgage API tracking and pulling user data

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5005]

**Comment by ghost** [comment]
Marah is going to setup a meeting for Dee and I with the mGage technies. From the mGage documentation, it looks like you can create an API endpoint in their infrastructure to interact with their data however you want (which seems odd). 

Further clarification post-meeting. 

Current documentation here: https://mgage.app.box.com/s/urbfvapzk61fyxxmhr9y3mywlxqijl5c

**Comment by sheyd** [comment]
Call scheduled for tomorrow.

**Comment by sheyd** [comment]
Call with Dee and I had with mGage was really great. Their API is robust, and they're willing to send us data exports as we need them, and look into getting data we might not have yet :+1:
