### ISSUE TITLE
figure out how to proxy Mexico and Non-US/BR/MX user experience

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5008]
related to #5001 
- [ ] Mexico user
- [ ] non-US/BR/MX user

**Comment by ghost** [comment]
@mshmsh5000 I think the easiest route is to sign up for a month to month account on TorGuard (https://torguard.net/anonymoustorrentvpn.php). Their VPN services are available in a lot of countries, and we can mimic a lot using their services. They're one of the more trusted VPN services, and give us a lot of flexibility. If you want to setup an account and add the credentials to LastPass, or I can have Gleb set this up on his CC, this should solve this problem for us.

**Comment by mshmsh5000** [comment]
:+1:

**Comment by ghost** [comment]
@namimody @mshmsh5000 @mikefantini @angaither @blisteringherb 
Wiki link: https://github.com/DoSomething/phoenix/wiki/VPN-Server-for-Testing-International-Sites
