### ISSUE TITLE
Static Image on Win Module Update: Spacing and New Image

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5011]
Hi @sbsmith86! Per our conversation in Slack re: the centering of text in the win module -- I was talking to Julie about it and she noted that it seems there is an extra space in the code to place the static image -- there is more space between the header image and the static win image than there is between the image and the campaign lead's speech bubble -- which is contributing to the text in the center looking uncentered.

Additionally, the image is looking pixelated, so we are asking creative for an SVG of the win module graphic.

**Comment by namimody** [comment]
@mikefantini seems we can't upload SVGs to the site, so while we have the correct file from creative, we can't change it out on the backend (https://www.dosomething.org/admin/config/dosomething/dosomething_campaign) and this is the only type of file that will reliably work.

Do we know how difficult it is to change the settings to allow for SVGs?

**Comment by DFurnes** [comment]
Is there a reason this is being set in the admin form, rather than as part of the theme?

**Comment by sbsmith86** [comment]
@namimody We will have to update it to be set in code, rather then in the admin form.

**Comment by namimody** [comment]
Oh okay @sbsmith86! So you do just need the SVG?

I thought it was set here: https://www.dosomething.org/admin/config/dosomething/dosomething_campaign

**Comment by mikefantini** [comment]
totally defer to you two @namimody @sbsmith86 on the best way to resolve this issue.

let's just be mindful of the ds campaign config @namimody mentioned and remove it if it's no longer needed

**Comment by sbsmith86** [comment]
@namimody yep at the moment it is set in the config but we would remove that config and just include it in the theme. So just the SVG is needed and like @mikefantini said, I will make sure to remove the config field.

**Comment by namimody** [comment]
Sweet thanks @sbsmith86! Will get the SVG to you ASAP.

Do you want me to make a new issue re: removing the config field?

**Comment by sbsmith86** [comment]
@namimody we can take care of it in this issue.
