### ISSUE TITLE
Language related bug on Home page

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5015]
Keep getting this PHP notice popping up in logs:

```
Notice: Undefined index: en in dosomething_home_preprocess_node() (line 50 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_home/dosomething_home.module).
```

Likely to do with language/translation stuffs.

**Comment by angaither** [comment]
this is caused if there's no cover image and it's on the campaign node
not likely going to happen in prod, but defense! :football:

**Comment by angaither** [comment]
closing this, it only is caused if there isn't an image set
