### ISSUE TITLE
Drupal Admin menu keeps disappearing

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5019]
You can clear the cache and see it again, but only for that one cleared-cache load and then it reappears.

Might be related to the gzipping... see following links:

http://stackoverflow.com/a/14040312

> It happens when your HTTP request's headers claim that the content is gzip encoded, but it isn't. Turn off gzip encoding setting or make sure the content is in fact encoded.

http://drupal.stackexchange.com/a/35075

---

@angaither @blisteringherb @DFurnes

**Comment by DFurnes** [comment]
This happens to me all the time on my local dev.
