### ISSUE TITLE
Langauge index errors on dosomething_campaign

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5024]
`Notice: Undefined index: und in dosomething_campaign_get_hot_time_left() (line 622 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc).`

**Comment by angaither** [comment]
also seeing
`Notice: Undefined index: 0 in dosomething_campaign_is_hot_module()`

**Comment by angaither** [comment]
`Notice: Undefined index: und in dosomething_campaign_run_preprocess_winners() (line 133 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_campaign_run/dosomething_campaign_run.module).`

**Comment by angaither** [comment]
`Notice: Undefined index: und in dosomething_campaign_run_preprocess_klout_gallery() (line 153 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_campaign_run/dosomething_campaign_run.module).`

**Comment by itsjoekent** [comment]
I can look at the hot module stuff, might be related to recent changes I made

**Comment by itsjoekent** [comment]
I'm not seeing this occurring right now, but there are other important dblog errors that have to be resolved. I'll make another issue, @angaither should we close this until we see these errors popup again?

edit; new issue: https://github.com/DoSomething/phoenix/issues/5866

**Comment by angaither** [comment]
@deadlybutter seeing the klout gallery and winner errors on thor
along with plenty undefined notices
https://thor.dosomething.org/us/campaigns/dont-be-sucker
https://thor.dosomething.org/us/campaigns/comeback-clothes

**Comment by itsjoekent** [comment]
importing tor content on my local to see if i can reproduce
