### ISSUE TITLE
ZenDesk Tickets Not Going Through SIte

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5026]
![image](https://cloud.githubusercontent.com/assets/12396076/9687364/0c22001e-52f7-11e5-861b-0cdac2040c01.png)

Myself, Hannah, and at least one other member got this error message when trying to submit a help ticket via the Contact Us link at the bottom of the site. The questions do not go through to ZD.

**Comment by DFurnes** [comment]
Can verify that these are broken on production. Frustratingly, the same settings (subdomain, account email & API key) work fine when testing on my local. Continuing to investigate. :mag:

**Comment by DFurnes** [comment]
Creating a new API key seems to have cleared things up.

**Comment by DFurnes** [comment]
Closing this since the issue seems to have been solved, but we should keep an eye on things. :eyes:

**Comment by namimody** [comment]
Created a discussion issue to figure out how to monitor this on prod so it doesn't happen again: https://github.com/DoSomething/phoenix/issues/5033
