### ISSUE TITLE
Ryan's Playbooks and Suspended for WHAT?: Advocate Missing Majority of Content

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5032]
For some reason, https://www.dosomething.org/campaigns/suspended-what-advocate and https://www.dosomething.org/campaigns/ryans-playbooks are missing the majority of content.

Need to revert to a previous revision for these two, determine if this is happening on any other campaigns, and if so, why it happened.

**Comment by mikefantini** [comment]
@namimody see #4930 for what happened with unpublished campaigns.

perhaps we can have @sergii-tkachenko take a look at this when he is back, but I don't think dev on this should be prioritized right now since we do have a fix and it's pretty rare we republish unpublished content.

**Comment by namimody** [comment]
https://ghana.dosomething.org/campaigns/would-you-rather-0
https://ghana.dosomething.org/campaigns/anti-bullying-checklist

Thanks @mikefantini! Was just checking something else and noticed that these two campaigns on Ghana seem to be missing content as well, but don't have a translate tab. Do you think the issue is related? (Revision history on these campaigns doesn't turn up any more content, unfortunately.)

**Comment by mikefantini** [comment]
@mnelson338 do you know if this is still an issue on the Ghanaian site?

**Comment by mnelson338** [comment]
@mikefantini  It is - but I also think that the campaign content is incomplete rather than a technical issue. I'm going to unpublish the campaigns and check in with the Ghana team

**Comment by mikefantini** [comment]
Thanks @mnelson338!
