### ISSUE TITLE
Monitoring ZenDesk Functionality on Production

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5033]
As per https://github.com/DoSomething/phoenix/issues/5026, ZD tickets were once again not going through site via the Contact Us link at the bottom of the campaign pages. This was fixed quickly by creating a new API key, but should not have happened in the first place. Additionally, the error was only occurring on prod, not local or staging environments. How can we monitor this functionality on prod?

**Comment by DFurnes** [comment]
We should attach StatHat monitoring on any errors during the Zendesk ticket process if we don't already have it, and trigger alerts if any of those occur.
