### ISSUE TITLE
Campaign Language value in transaction message request

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5036]
Campaign signup / reportback transactionals:
- [x] Campaign Signup
- [x] Campaign Reportback

The language of the specific campaign the user signed up for or reported back to defines what language the transactional message should be in.

**Also**: The country code value for the user needs to be available to `dosomething_mbp.module` here: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_mbp/dosomething_mbp.module#L218-L233

**~~BLOCKED by~~**:
Currently `dosomething_settings_get_affiliate_country_code()` takes care of defining the affiliate value. This issue is blocked by the need for the functionality within the Drupal App to gather the campaign country as well as the user language.

**Sample payload**:

```
{
  "activity": "campaign_signup"
  "email": "xyz@geemail.com"
  "uid": "123456789"
  "merge_vars":
    {
     "MEMBER_COUNT": "4 million"
     "FNAME": "Bob"
     "CAMPAIGN_TITLE": "School Insider",
     "CAMPAIGN_LINK": "https://www.dosomething.org/campaigns/school-insider",
     "CALL_TO_ACTION": "Provide tips and information to new students at your school.",
     "STEP_ONE": "Make Your Sheet!",
     "STEP_TWO": "Snap a Pic",
     "STEP_THREE": "Deliver the Sheet"
    }
  "email_template": "mb-campaign-signup-mx"
  "user_language": "CH",
  "mailchimp_list_id": "133qwer456"
  "birthdate": "916876800"
  "subscribed": 1
  "email_tags"
    {
      "MX",
      "drupal_campaign_signup"
      "drupal_campaign_signup_MX";
    }
  "activity_timestamp" 1432086537
  "application_id": "DRUPAL";
}
```

**Related**:
- https://github.com/DoSomething/phoenix/issues/4959
- https://github.com/DoSomething/phoenix/issues/4955
- https://github.com/DoSomething/phoenix/issues/4958
- https://trello.com/c/xIxS5lPt

**Comment by mshmsh5000** [comment]
@blisteringherb Can we close this?
