### ISSUE TITLE
Homepage fact tile

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5039]
@blisteringherb and @DFurnes what did you do to get the Charleston as the main tile on the homepage?

we need to do a similar thing for the yahoo partnership, where the main tile doesn't link to a campaign node (@mikefantini remembers creating a dummy campaign node and changing the redirect on it)
The image should link to an 11-facts page.

**Comment by DFurnes** [comment]
Yep, dummy campaign (which lets us set the title, description, and tile image), which is then set to redirect to another URL. Kinda hacky, but it works.

**Comment by mikefantini** [comment]
ah yeah ok we just created a redirect in the drupal interface. i can just have @ArielSD make this happen.
