### ISSUE TITLE
add revisions to fact pages

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5040]
same functionality as we have on campaign nodes so that we can easily see revision history and revert to previous revisions

**Comment by angaither** [comment]
@sbsmith86 all we should have to do here is to check `create a new revision` on the content type manage page. (in the publishing option section)
then export that new option to features

let me know if you need help with this!

**Comment by sbsmith86** [comment]
@angaither it's just `drush fu feature_name` right?
