### ISSUE TITLE
save on a new campaign dies!

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5042]
![](https://slack-files.com/files-pub/T024GV2BW-F0AAPFLLF-4f72c8a74e/pasted_image_at_2015_09_08_01_52_pm.png)

**Comment by angaither** [comment]
this is because the default language is set to `author language` in `/admin/config/regional/entity_translation` 
I have a feeling our users don't have a default language set. 
We can do one of two things here
1. Set the language for everyone with admin status, might be a pain
2. Set the default to be `default` which would then be english for campaigns and the override a the language on a node_save depending on the user role or the URL

cc @blisteringherb @mikefantini @weerd

**Comment by weerd** [comment]
hmmm, #2 seems more ideal

**Comment by blisteringherb** [comment]
It sounds like #2 would be a good solution, but we can always run a script to change the default language for all users for a quick and dirty solution.

**Comment by angaither** [comment]
we could do some sort of script to set everyone in the `dosomething_user_is_staff` language to english 
and then anyone who is a regional admin to whatever the language needs to be.
but would need to make sure that new staff users get their language set properly
