### ISSUE TITLE
Add menu tab for editing reportback for editors

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5045]
@deadlybutter so looks they don't have the `view tabs` permission, but they do have the ability to navigate to `reportback/[id]/edit`

**Comment by namimody** [comment]
Hi @angaither -- hate to be more of a pain but is this a quick fix? Causing a few problems for leads with hot module campaigns (They want to approve certain RBs but can't because the quantities are ridiculous).

**Comment by angaither** [comment]
@namimody checking in prod, that [permission is already enabled.](https://www.dosomething.org/admin/people/permissions)
who is having trouble with this? maybe they don't have the correct roles?

**Comment by namimody** [comment]
Hmm which role should they have @angaither? Adam https://www.dosomething.org/user/2752150/edit) has member support and editor roles. He doesn't see the gray striped bar when visiting this page though: https://www.dosomething.org/reportback/74013

![image](https://cloud.githubusercontent.com/assets/12396076/9820328/2ebb1234-5881-11e5-9a36-d0b0273ca413.png)

**Comment by angaither** [comment]
ahhhh, got it got it. 
@deadlybutter so looks they don't have the `view tabs` permission, but they do have the ability to navigate to `reportback/[id]/edit`

**Comment by itsjoekent** [comment]
Oh I didnt even know there was a button

**Comment by namimody** [comment]
Thanks @angaither and @deadlybutter -- for now, leads will just use the workaround where they can access the edit page by going to dosomething.org/reportback/RBID/edit. We can take the up the tab piece of it at another time.
