### ISSUE TITLE
Registration form client-side validation

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#5046]
As we enter the wider global world, we should make sure that our validation isn't too US-centric! For example, we currently offer suggestions for common misspellings on email addresses. Do we need to offer additional suggestions for common mail providers in other countries?

(Making this issue as follow-up to an offline conversation with @mikefantini.)

**Comment by DFurnes** [comment]
International phone numbers currently validate correctly on the client-side, and we can use translation to offer region-specific placeholders:

![screen shot 2015-09-08 at 4 57 41 pm](https://cloud.githubusercontent.com/assets/583202/9747265/bb580802-564a-11e5-99d5-f3cce43411f6.png)

Regional email addresses also seem to validate correctly:

![screen shot 2015-09-08 at 4 58 11 pm](https://cloud.githubusercontent.com/assets/583202/9747277/cccbb80e-564a-11e5-910c-dbd0104f14f5.png)

**Comment by DFurnes** [comment]
Here's the list of domains we currently use for "suggestions":

> "yahoo.com", "google.com", "hotmail.com", "gmail.com", "me.com", "aol.com", "mac.com",
> "live.com", "comcast.net", "googlemail.com", "msn.com", "hotmail.co.uk", "yahoo.co.uk",
> "facebook.com", "verizon.net", "sbcglobal.net", "att.net", "gmx.com", "mail.com", "outlook.com",
> "aim.com", "ymail.com", "rocketmail.com", "bellsouth.net", "cox.net", "charter.net", "me.com",
> "earthlink.net", "optonline.net", "dosomething.org"

It looks like we already have some common international domains, but perhaps it'd be good to look into any that we're missing?

**Comment by DFurnes** [comment]
Also pinging @julielorch, because I heard you've been giving this some thought! :smile:

**Comment by angaither** [comment]
waiting on recs from @julielorch

**Comment by joolaay** [comment]
@DFurnes @angaither reviewing auth flow ideas at this week's tech sync, this is part of it. Here's some more info: https://docs.google.com/document/d/1BvhHRUy7KkiZ2AgtfhtvHNtUGjubCnbGYuPtZGRXevU/edit#

**Comment by joolaay** [comment]
@angaither sorry, which recs?

**Comment by angaither** [comment]
@julielorch based on the doc you linked, but it looks like, other than content changes, there's no dev work to be done on the auth flow

**Comment by joolaay** [comment]
@angaither at the least we have to expand validation for SMS + Email. The rest depends on whether we show the same auth to all users globally or show different auth flows to partner countries w SMS programs. cc @mikefantini we can discuss at this week's tech sync?

**Comment by angaither** [comment]
@DFurnes mentioned in the comments above validation for phone numbers international emails currently work

**Comment by joolaay** [comment]
word.

**Comment by angaither** [comment]
@DFurnes @julielorch cool, looks like we are good to close this issue out, I'll open a different one for discussion re: different modals

**Comment by mikefantini** [comment]
@angaither sorry reopening for two things:
1. may need to add more suggestions for email addresses
2. what about date field? currently help text is in MM/DD/YYYY which is obviously counter to how most people write out the date. what does facebook do about date fields for different users?

**Comment by DFurnes** [comment]
Oh, good catch @mikefantini! We do have some support for `DD/MM/YYYY` validation (in the DoSomething UK config, I believe), but it'd be an extra build if we wanted that to toggle dynamically.

**Comment by mikefantini** [comment]
also a data question in terms of storing the different variations properly @DFurnes @sheydari-ds @angaither

**Comment by angaither** [comment]
we will always sanitize the date and store the same way no matter what the user gives us :wink:

**Comment by DFurnes** [comment]
Aye, Drupal stores all birthdates as `YYYY-MM-DD` so no issues there.

**Comment by mikefantini** [comment]
:+1:

**Comment by mikefantini** [comment]
@mnelson338 assigning over to you. can you please add in any email client suggestions we'd want to add to @DFurnes's list? i'm just not sure what other popular international email addresses we may or may not want to add.

> "yahoo.com", "google.com", "hotmail.com", "gmail.com", "me.com", "aol.com", "mac.com",
> "live.com", "comcast.net", "googlemail.com", "msn.com", "hotmail.co.uk", "yahoo.co.uk",
> "facebook.com", "verizon.net", "sbcglobal.net", "att.net", "gmx.com", "mail.com", "outlook.com",
> "aim.com", "ymail.com", "rocketmail.com", "bellsouth.net", "cox.net", "charter.net", "me.com",
> "earthlink.net", "optonline.net", "dosomething.org"

**Comment by mnelson338** [comment]
@mikefantini @DFurnes 
the only one I would add: sina.com - Otherwise it looks good to me.

**Comment by angaither** [comment]
@DFurnes I think we are good to close this out, right?

**Comment by DFurnes** [comment]
:white_check_mark: from me!
