### ISSUE TITLE
Login modals vary per country code

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5051]
Do we show the same auth to all users globally or show different auth flows to partner countries w SMS programs?
#### relevant docs
- https://docs.google.com/document/d/1BvhHRUy7KkiZ2AgtfhtvHNtUGjubCnbGYuPtZGRXevU/edit

**Comment by mikefantini** [comment]
@julielorch can you please add comments

**Comment by joolaay** [comment]
@angaither @mikefantini 
- If US, MX, BR, Ca, UK then all auth fields show
- If global, then suppress SMS 
- If we anticipate building an SMS program in a specific country, then will will show SMS field 6 mos. ahead of time

More: https://docs.google.com/document/d/1BvhHRUy7KkiZ2AgtfhtvHNtUGjubCnbGYuPtZGRXevU/edit#

**Comment by sbsmith86** [comment]
@angaither @mikefantini I am working on hiding cell phone fields in #5085. I will update that issue to use the ruleset Julie outlined. What else work needs to be done for this issue? Or is this just a discussion?

**Comment by angaither** [comment]
@sbsmith86 I think we are good to go with this one, just didn't remove the labels. right @mikefantini?

**Comment by mikefantini** [comment]
@angaither we can close this one now yeah? because won't #5085 do the work we need for this? is there any other work that this issue represents?

**Comment by angaither** [comment]
:+1:
