### ISSUE TITLE
hide address field for non-US users

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5052]
currently shows up on the profile and any campaigns where we collect address.

right now we have US-centric fields (state, zip code). obviously we've resolved this issue on individual international sites, but need a solution for the one site to rule them all **TM**
#### solution

one fine solution is punting for now on this by hiding these fields on the user profile for non-US users and not enabling address collection on campaign nodes

**Comment by angaither** [comment]
@mikefantini are we going with disabling this for non-US users for now?

**Comment by mikefantini** [comment]
hide for non-US. make issue to deal with for realz in 1.1

**Comment by sbsmith86** [comment]
@angaither @mikefantini sorry i was a bit confused on this issue. I think I figured it out, but just to confirm. 

This is issue is to hide the address and collection fields on the **user profile edit page** not on the "My Account" page, which doesn't show address?

**Comment by mikefantini** [comment]
@sbsmith86 yeah sorry for the confusion, but yes you are correct. It's on the /user/[uid]/edit form.

http://screencast.com/t/OYaR8fESX3G
