### ISSUE TITLE
BR Portuguese version of campaign not showing to BR Admin

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5060]
I just created a Brazilian Portuguese translation of node 5613 on Thor.

However when I go to view that campaign as a Brazilian Admin, I don't see the Brazilian Portuguese version I created. Instead I see the US English version.

the node view links to
https://thor.dosomething.org/campaigns/enlgish

**Comment by mikefantini** [comment]
hmm actually is this expected behavior because we don't have the Brazilian socks proxy set up and I'm in the US? #5001 

cc: @angaither @sheydari-ds

**Comment by angaither** [comment]
@mikefantini yeah, we haven't done work to redirect the user to the correct content based on local yet (afaik)

**Comment by angaither** [comment]
@mikefantini closing this one in favor of #5130
