### ISSUE TITLE
Thor not saving content in BR Portuguese

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5061]
I just created a translation for Brazilian Portuguese of node 5613 with Title "Pretend this is Portuguese" and CTA "Pretend this is Portuguese" and saved it.

However, when I go back to edit it, I see this:

![image](https://cloud.githubusercontent.com/assets/6330971/9775846/9e242974-5720-11e5-8725-cec5f9df691f.png)

**Comment by angaither** [comment]
it seems that when you edit/add translation content as an `admin` it works correctly
however when you do it as a regional admin, it doesn't save the content... permissions?

**Comment by angaither** [comment]
did some initial research on this.. there's two permissions that I _thought_ were blocking the save 
`Translate entities of type Content` or `Translate any entity` but it's still not saving locally after adding those.  
-_-

**Comment by mikefantini** [comment]
assigning over to @deadlybutter to take a peek

**Comment by itsjoekent** [comment]
yeah was only able to reproduce as a regional admin. have an idea, i think

In addition to the two you tried I also tried adding `Translate content` but still didn't save properly.

**Comment by itsjoekent** [comment]
_phew_ @mikefantini you we're right, these issues are related https://github.com/DoSomething/phoenix/issues/5048#issuecomment-139387489 (thank you for pointing that out, thats what led to me just testing for it)

Can confirm when you remove the bug inducing code from ^ that issue, this issue no longer occurs. :tada:
