### ISSUE TITLE
Enable direct data access for UK and Canada

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5063]
Disintermediate Micah from their data pulls.

**Comment by ghost** [comment]
Adding Canada per Jeff Bladt's request.

**Comment by sheyd** [comment]
Instructions sent to Damien in the UK for PC connectivity. UK RDS readonly user credentials in LastPass. 

@mshmsh5000 or @Bladt Who's our CA contact(s)?

**Comment by mshmsh5000** [comment]
That would be the esteemed @mfurdyk!

**Comment by mfurdyk** [comment]
![image](https://cloud.githubusercontent.com/assets/244123/10077877/4f30a6f8-62b0-11e5-8f5b-1fc798d5ca25.png)

I'm at mfurdyk@takingitglobal if you want to send any details directly!

**Comment by sheyd** [comment]
Setup complete and instructions sent. Will troubleshoot anything additional via e-mail as needed.
