### ISSUE TITLE
BR/MX users should see email address instead of contact us modal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5078]
Instead of "Questions? Contact Us" which then links to a modal, users in Brazil and Mexico should be directed to email us.
- [x] BR users - "Questions? Email ajuda@dosomething.org"
- [x] MX users - "Questions? Email ayuda@dosomething.org"

and we decided global users should still have the same Zendesk flow as US users currently have.

---

@mnelson338 can you please edit this comment to have the email addresses you want these questions to go to?

also @mnelson338 how do you want global users to be treated? should they submit zendesk tickets like US users do? Personally this makes the most sense to me, but your call.

**Comment by mnelson338** [comment]
@mikefantini 

BR users: ajuda@dosomething.org 
MX users: ayuda@dosomething.org 

I agree - global users should go to zendesk.

**Comment by mikefantini** [comment]
@angaither this can get the ol fender label yeah? :art:

**Comment by angaither** [comment]
perhaps in the preprocess before we set if we didn't set [zendesk form](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/themes/dosomething/paraneue_dosomething/templates/system/partials/info-bar.tpl.php#L17) 
print out email address that co-responds to the country code if it exists.

**Comment by sbsmith86** [comment]
@angaither si

**Comment by mikefantini** [comment]
@sbsmith86 was this working for you previously? I honestly can't recall if this was working before or not, but now that we have "Contact Us" translated the contact us modal that links to Zendesk is able to be triggered by MX users. We just want the email address to be displayed and no contact us modal.

cc: @weerd

**Comment by sbsmith86** [comment]
@mikefantini yea this was working. Is it broken on prod?

**Comment by mikefantini** [comment]
sorry @sbsmith86 thor

**Comment by sbsmith86** [comment]
@mikefantini Using TorGuard I accessed Thor from Mexico and I am seeing the correct email address. I'm looking at GTFO. Are there any steps I should be taking to reproduce this? 

<img width="1036" alt="screen shot 2015-10-13 at 4 59 24 pm" src="https://cloud.githubusercontent.com/assets/1700409/10468227/e4c225a0-71cb-11e5-8d49-5887c17fb15c.png">

**Comment by mikefantini** [comment]
ah got it @sbsmith86. so based on some of the other decisions we've made re: which content to show which users and just general language rules we've made, I think we actually want this experience to be dictated by URL not country code in fastly header. i.e. if I'm in the US and I go to thor.dosomething.org/mx/voluntario/gtfo I should see "¿Preguntas? Mande un email a ayuda@dosomething.org" or something like that.

and if I'm in Mexico and go to thor.dosomething.org/us/campaigns/gtfo I should see Questions? Contact US which should trigger the Zendesk help modal.

Let me know if that makes sense.

**Comment by sbsmith86** [comment]
I think that makes sense.

**Comment by sbsmith86** [comment]
Closing per #5520

**Comment by chloealee** [comment]
Closing with fix from #6101
