### ISSUE TITLE
Pull all 11 Facts Edit Links

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5081]
Hi! To make the lives of Felicia and Gabe easier for this yahoo partnership, would be great to get a CSV of all edit links of published 11 facts pages on production. Not sure who has time to help with this, so leaving that up to you @angaither! Thanks!

**Comment by angaither** [comment]
@namimody they can be accessed in prod via content search. is a CSV still needed?
https://www.dosomething.org/admin/content/search?title=&type=fact_page&field_cause_tid=All&status=1

**Comment by namimody** [comment]
@angaither Unfortunately it seems the edit links from there don't work when pasted into a Google Sheets or Excel, so we'd really like someone to pull this (or show me how to not be an idiot with copy and paste).

Basically, for the partnership with Yahoo, we are changing all calls to actions on 11 Facts pages to go to Yahoo search instead of a related campaign. The partnership doesn't launch until October, but in order for the content team to queue up all the changes, they'll need to fill out this spreadsheet for 172 fact pages
:
![image](https://cloud.githubusercontent.com/assets/12396076/9860626/5de6b47e-5afb-11e5-8ff9-80b4204cba30.png)

so that the day before launch, they can easily update all the pages. Let me know if it's easier to sync in person about this!

**Comment by angaither** [comment]
@namimody if you do a query for all fact pages with a `status = 1`, with the node id... the edit link would just be node/[id]/edit

you could also `copy link address` with copy/paste

**Comment by namimody** [comment]
Perfect, thanks Andrea! Copy link address led me to the Google Chrome Extension Link Clump -- where you can bulk copy links. :D
