### ISSUE TITLE
Admin w/ English Language set seeing Brazilian campaigns

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5083]
uid 329195

![image](https://cloud.githubusercontent.com/assets/6330971/9801150/543b4404-57df-11e5-9005-52af88f19cfc.png)

**Comment by blisteringherb** [comment]
For some reason the global finder code that I merged in earlier got un-merged so I re-merged it. That fixed the issue with the broken images and seeing multiples of the same campaign after filtering.
