### ISSUE TITLE
need dd/mm/yyyy birthday field for non-US users

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5084]
non-us users (so BR, MX, and global users) should get presented with a different birthday field that accepts dates as mm/dd/yyyy. All birthday fields regardless of how they are input should obviously be stored the same way in the same column in the db.

@mnelson338 does anyone else use the mm/dd/yyyy format besides :us:?

related to #5046

**Comment by mnelson338** [comment]
@mikefantini Majority of the world uses dd/mm/yy. I think this should be our default, and what we use for the Global experience. 
The only major outlier to flag is China who uses: yyyy-mm-dd

**Comment by DFurnes** [comment]
Makes sense to me! We currently have `DD/MM/YYYY` support configured on our UK international site, so we can probably use the same approach in the global world but vary the experience based on the user's country code header.

**Comment by sbsmith86** [comment]
@mikefantini  Want to make sure I got the breakdown correct, see below. Are we breaking out China? or would those users get the global experience?

_US_: MM/DD/YYY
_BR, MX, Global_: DD/MM/YYYY
_CHINA(?)_: YYYY/MM/DD

**Comment by mikefantini** [comment]
@sbsmith86 looks good to me, except Chinese users will get the global experience, so no need to do work for Chinese users for launch
