### ISSUE TITLE
hide cell phone field on auth flow for global users

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5085]
- If US, MX, BR, Ca, UK then all auth fields show
- If global, then suppress SMS 
- If we anticipate building an SMS program in a specific country, then will will show SMS field 6 mos. ahead of time

related to #5046

**Comment by DFurnes** [comment]
This is hopefully something we can do when building the form with Dr00ps. We should know the user's country via their Fastly country code header, and will be varying the cache by country code (just like we did in CGG & AGG!).
