### ISSUE TITLE
Global English Report Back Transactional

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5090]
When a user reports back on a campaign that is translated in Global English, s/he should receive a report back transactional email in Global English. This is needed because content could potentially be different in |campaign_title|.

Also note that we need to make sure we're pulling in the proper fields for this since technically the Global English content are in different fiends than the US English fields.

And same as my comment on #4955 we need to make /campaigns will take the user to the correct version of that URL depending on their location, but I think this should be fine.

related to #4957 

<b>Adding to this:</b>
We need 4 new templates (New User Register, Campaign Sign-Up, Report Back, Password Reset) for global users [Non-U.S., Non-Mexico, or Non-Brazil]. We want to serve different content to U.S. and global users. For example, things we'll mention for U.S. users and not global users are: The Help Center, Scholarships, and U.S. specific campaigns. The screenshot below is an example of the current U.S./Global template. See how we mention Teens for Jeans and GTFO? I'll work with Ben on content, we just need four new templates to trigger for global users. Here are the Global stubs:

New User Register: https://us4.admin.mailchimp.com/templates/editor?id=56713
Campaign Sign Up: https://us4.admin.mailchimp.com/templates/editor?id=56717
Report Back: https://us4.admin.mailchimp.com/templates/editor?id=56721
Password Reset: https://us4.admin.mailchimp.com/templates/editor?id=56725

![u s specific content](https://cloud.githubusercontent.com/assets/8696853/10945626/4a447546-82ec-11e5-87a6-6203865d56e5.png)

**Comment by mikefantini** [comment]
if we can confirm GL users receive US reportback transactional when we test then we can move to 1.1

cc: @namimody

**Comment by mikefantini** [comment]
confirmed that I'm getting transactionals still as a GL user so this can be 1.1.

**Comment by ArielSD** [comment]
@DeeZone @sergii-tkachenko @blisteringherb @marahml Just updated the description to include 4 new global templates! Please let me know if I can clarify. Thanks!

**Comment by deezone** [comment]
@mikefantini @marahml @ArielSD @sergii-tkachenko 

Issue to default to default to Global templates rather than the current US defaults: https://github.com/DoSomething/mbc-transactional-email/issues/25

US users will continue to be sent US templates but unsupported countries will default to the global templates.
