### ISSUE TITLE
Affiliate Instances Do Not Have Updated Member Count

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5109]
![image](https://cloud.githubusercontent.com/assets/12396076/9856626/cfd4478a-5ae3-11e5-89cf-bb19fc6a4195.png)

^ on uk.dosomething.org, canada.dosomething, etc.

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zQE6FDgp&#x2F;1459-of-members-not-updated-on-affiliate-instances"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> # of Members Not Updated on Affiliate Instances</a>

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zQE6FDgp&#x2F;1459-of-members-not-updated-on-affiliate-instances"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> # of Members Not Updated on Affiliate Instances</a>

**Comment by namimody** [comment]
@angaither any thoughts on this? Thanks!

**Comment by angaither** [comment]
@namimody uhm, it's a variable set in each database separately. not sure if/how it gets updated automatically....
(cc @deadlybutter)

**Comment by itsjoekent** [comment]
No I don't think the affiliate sites would be updated. I can update the script however to do this, would be trivial.

_BUT_ if we're migrating everyone to one site, is there really any point?

**Comment by namimody** [comment]
Thanks @angaither and the @deadlybutter! Call is up to @mikefantini!

**Comment by namimody** [comment]
Just going to close this since we are so close to launching global. Let me know if that's the wrong call @mikefantini.

**Comment by itsjoekent** [comment]
BTW they can manually update this until than
