### ISSUE TITLE
RB Image Rotation Functionality Not Saving

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5112]
![image](https://cloud.githubusercontent.com/assets/12396076/9858335/1e9f4068-5aee-11e5-8bf4-e21497f22943.png)

If I click 90 and save, the banner notification at the top will say updated, but the image on the back end and front end will remain in its initial orientation.

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bgqbusNA&#x2F;1480-rb-image-rotation-functionality-not-saving"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> RB Image Rotation Functionality Not Saving</a>

**Comment by sbsmith86** [comment]
@namimody @mikefantini I tested this on my local, staging.dosomething.org, and staging.beta.dosomething.org as an admin and as an editor and the rotation seems to be going through and being reflected in the reviewed box and on the frontend on the campaign page.

**Comment by namimody** [comment]
@sbsmith86 interesting! on prod, ive been messing with this one -- it came in correctly oriented, I rotated, front end showed:

![image](https://cloud.githubusercontent.com/assets/12396076/10375651/c8264bea-6dc7-11e5-8bc3-d7c9cad0156d.png)

backend now shows:
![image](https://cloud.githubusercontent.com/assets/12396076/10375661/d4213900-6dc7-11e5-97b8-ff5c8053b5a9.png)

but rotating behavior is based off of what is shown on frontend. sort of a different issue -- thoughts?

**Comment by sbsmith86** [comment]
@namimody what campaign is this?

**Comment by sbsmith86** [comment]
nevermind i see lol

**Comment by sbsmith86** [comment]
@namimody yea, I am seeing a difference on that photo between what is shown on the frontend and what is shown on the backend, which is weird. My gut is telling me it's some sort of caching issue.

**Comment by sbsmith86** [comment]
Ah yea, I flushed cache on prod an now everything seems to match up. I'm not sure im entirely clear on what the issue you were describing was, but feel free to swing by my desk so we can go over it in person.

**Comment by mikefantini** [comment]
yeah just did some digging and then saw the updates on this issue, but rotation seems to be working just isn't being shown on either the /rb/reviewed view _or_ the /admin/reportback/ view but it is working properly on the permalink

**Comment by sbsmith86** [comment]
@mikefantini If I submit a reportback, go to review it, rotate and save, I actually do see it rotated in the /rb/reviewed box. But I think maybe older reportbacks that haven't been reviewed are being cached and that's why the updates are being reflected sometimes. Is that a separate issue we need to work on? Should I close this one out?

**Comment by namimody** [comment]
Hate to bring this back from the dead, but this photo https://thor.dosomething.org/admin/reportback/107783 is rotated on the back end and the user profile, but not on the action page. I cleared cache and it still appears unrotated. Is this relate to the separate issue you noted @sbsmith86?

**Comment by sbsmith86** [comment]
@namimody  Hmm this looks good on the action page to me.... am I looking at the right thing (https://thor.dosomething.org/us/campaigns/50-cans) ?

![screen shot 2015-11-30 at 3 11 11 pm](https://cloud.githubusercontent.com/assets/1700409/11483102/a2ea9076-9774-11e5-8859-1114c81d11aa.png)

and by "looks good" I mean it looks the same in all places.

**Comment by mikefantini** [comment]
@sbsmith86 to answer your question here https://github.com/DoSomething/phoenix/issues/5112#issuecomment-146672599 I think we should probably resolve this for older reportbacks because I can see this being quite confusing for editors if they are looking at old reportbacks. Your call on whether you'd like to create a new issue for it or not.

**Comment by namimody** [comment]
OY i see it rotated on the action page now, @sbsmith86! Is there a delay that should be expected? Would be helpful to relay to editors if so!

**Comment by sbsmith86** [comment]
@namimody @mikefantini I will look into any caching logic around this and see if we can clean it up so the change is quicker. If I can't fix, it at very least we will know exactly what to expect. I'll let you know!

**Comment by angaither** [comment]
@namimody @sbsmith86 yeah, this stuff is cached, and clears when you do a cache clear!

**Comment by namimody** [comment]
@angaither to clarify, a cache clear of the site or of an individual's internet browser?

thanks!

**Comment by angaither** [comment]
@namimody site cache clear
