### ISSUE TITLE
can't create a translation for a campaign from /admin/content

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5114]
When a user is on /admin/content and she clicks on edit for a campaign that does not have a translation added in her language, the page just refreshes. This happens regardless of whether the user is an admin, a BR/MX admin, editor, etc.

instead, it should behave the same as it would if I went to /node/[nid]/edit for a given node, essentially the work that was done in #5020

**Comment by itsjoekent** [comment]
guessing this is because the init() logic only runs on a node edit page. I can add in a check for this page as well

**Comment by itsjoekent** [comment]
Interestin, this bug occurs when the campaign source language and the user language do not match, also confirmed user roles have no effect on the bug.

**Comment by itsjoekent** [comment]
did some digging, the languages are loaded fine but the URL isn't being constructed properly from this page. 

```
en
es-mx
/node/1716/edit/es-mx
```

that node on my local has no existing es-mx translation, but the URL construction logic thought there was 

EDIT: Never mind this is working fine, I just forgot to refresh or something

**Comment by itsjoekent** [comment]
Added in base URL to the front of the redirect url,

'http://dev.dosomething.org:8888/node/1716/edit/es-mx'

nothin. hmm, what else could be doing this

**Comment by itsjoekent** [comment]
This bug is only occurring for non-published campaigns

**Comment by itsjoekent** [comment]
HAH, found it, right click and copy the URL from the 'edit' button. Paste that into a new tab, it should end with something like this, 

```
?destination=admin/content
```

if you hit enter in the current state, you'll go back to admin/content. _However_ if you remove that bit from the URL, you'll goto the correct edit page. 

I'm not sure why it worked on the few published campaigns I tried earlier though...?

EDIT: Yeah, this is appended to every /edit url but it's only breaking some of them. 

EDIT 2: Okay this isn't it either.. I copied the URL by right clicking edit, pasted into URL bar, hit enter and it worked fine. 

EDIT 3: What the shit. This campaign edit button didn't work before but now it does.

**Comment by itsjoekent** [comment]
Okay, starting over with new campaign. This is an MX campaign I haven't touched yet.

https://thor.dosomething.org/mx/campaigns/test-mx-titleeeeeee
- Clicking edit does not work (page refreshes)
- Right click, copy address equals `https://thor.dosomething.org/node/5617/edit?destination=admin/content`
- Open link in new tab does not work
- Right click, copy address into new tab, remove `?destination=admin/content` and hit enter, works
- Clicking edit does not work

**Comment by itsjoekent** [comment]
Solution seems to be changing the link to not include the ?destination=admin/content

Or maybe not? clicking edit causes a redirect, from chrome network tab, 

```
Remote Address:199.27.76.65:443
Request URL:https://thor.dosomething.org/node/5617/edit?destination=admin/content
Request Method:GET
Status Code:302 Moved Temporarily
```

**Comment by itsjoekent** [comment]
this is starting to possibly make sense. because we re-direct them to the proper edit page on the first request, that second request thinks we're supposed to then send them back to admin/content. 

maybe? 

aligns with everything ive seen so far

EDIT: YEP HAHAHAHAH SUCK IT DRUPAL I WIN. I changed the html to not include that URL segment and it worked fine. SUCK IT DRUPAL.
