### ISSUE TITLE
hide language settings from all users except for admins/global admins

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5117]
authenticated users can change their language currently. we don't want this to be the case right now.

currently being set on https://thor.dosomething.org/user/2987552/edit

![image](https://cloud.githubusercontent.com/assets/6330971/9860981/6853468c-5afd-11e5-8054-c2370bbd5e91.png)

this should block merging the global branch to dev

admins and global admins should be able to see this on other users' profiles

cc: @angaither

**Comment by angaither** [comment]
I cannot for the life of me find where this is set. 
[according](http://drupal.stackexchange.com/questions/55299/disable-user-language-setting-in-user-edit-page) to the [internet](https://www.drupal.org/node/1049282)
it _should_ be in `$form['locale']` but that doesn't seem to exist.

**Comment by angaither** [comment]
oy, the ol' `['#after_build']` trick
