### ISSUE TITLE
Turn Off Login Event Fire on Page Load

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5119]
We released a code change around 21 July that has been automatically firing a “login” event on every page load, resulting in incorrect bounce rate stats.

![image](https://cloud.githubusercontent.com/assets/12396076/9879411/4be52c66-5b95-11e5-8479-436e5d9c8298.png)

It is likely due to: 

https://github.com/DoSomething/phoenix/commit/83d934114f5b9328637dae87e1d836a20b68a71b
and 
https://github.com/DoSomething/phoenix/pull/4705

and more specifically:
https://github.com/deadlybutter/dosomething/blob/3ffd7710fb56df776ed59a7853bda70ea1ff5e2b/lib/modules/dosomething/dosomething_user/dosomething_user.module#L235

The login form renders on every page, so this form_alter runs on every page. That’s why the event always fires.

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GHcI3oFW&#x2F;1481-bounce-rate"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Bounce Rate</a>

**Comment by angaither** [comment]
for context of why this was added #4589

**Comment by namimody** [comment]
Check here when we believe this is fixed: https://www.google.com/analytics/web/?hl=en&pli=1#report/content-landing-pages/a493209w819276p798164/%3F_u.date00%3D20150901%26_u.date01%3D20150914/

**Comment by DFurnes** [comment]
@namimody This should be fixed as soon as we deploy to production.

@Bladt ~~The new events are renamed `Authorization - Register` and `Authorization - Login` so that they don't conflict with the old broken events. As a heads up, `Authorization - Login` fires after a user registration as well (since the newly registered user is then "logged in"). Let me know if that's an issue and I can look into another route!~~

**Comment by namimody** [comment]
Thanks @dfurnes! :D

On Thu, Oct 15, 2015 at 11:34 AM, David Furnes notifications@github.com
wrote:

> @namimody https://github.com/namimody This should be fixed as soon as
> we deploy to production.
> 
> @Bladt https://github.com/Bladt The new events are Authorization -
> Register and Authorization - Login (so that they don't conflict with the
> old broken events). As a heads up, Authorization - Login fires after a
> user registration as well (since the newly registered user is then "logged
> in"). Let me know if that's an issue and I can look into another route!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/phoenix/issues/5119#issuecomment-148425707
> .

## 

Namita (Nami) Mody

Junior Product Manager
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255

**Comment by DFurnes** [comment]
@Bladt I did some further refactoring in #5536 and now the `Authorization - Login` custom event will _only_ be triggered when the user logs in via the login form (and `Authorization - Register` will still only be called when the user registers). So they no longer overlap!
