### ISSUE TITLE
Reportback Items endpoint returns NULL users

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#5124]
This was working great, but suddenly stopped working -- very soon after a staging deploy. I have a hunch that cache clear wipes out the cached Northstar User info?

Refs: https://github.com/DoSomething/LetsDoThis-iOS/issues/345#issuecomment-140480156

![Null Users](https://cloud.githubusercontent.com/assets/1236811/9885875/5b1ef1ba-5b9c-11e5-9db3-bad3f8d24956.png)

**Comment by chloealee** [comment]
Weird! Isn't the cache clear supposed to wipe out the northstar user info. since we don't want to keep that info. in phoenix? 

Does this mean that it's not making the call correctly anymore (from phoenix to northstar) to get the user info?

```
    $client = _dosomething_northstar_build_http_client();

    $northstar_user_info = drupal_http_request($client['base_url'] . '/users/drupal_id/' . $id, array(
      'headers' => $client['headers'],
      'method' => 'GET',
      ));
```

**Comment by jonuy** [comment]
@chloealee Yea, while cache probably does and should clear info out, if it has been cleared out we should be retrieving it again. It does potentially mean that call isn't working in some fashion. Are the environment variables for this function set on staging and prod?

```
function _dosomething_northstar_build_http_client() {
  $base_url = NORTHSTAR_URL;
  if (getenv('DS_ENVIRONMENT') === 'local') {
      $base_url .=  ":" . NORTHSTAR_PORT;
    }
  $base_url .= '/' . NORTHSTAR_VERSION;

  $client = array(
    'base_url' => $base_url,
    'headers' => array(
      'X-DS-Application-Id' => NORTHSTAR_APP_ID,
      'X-DS-REST-API-Key' => NORTHSTAR_APP_KEY,
      'Content-Type' => 'application/json',
      'Accept' => 'application/json',
      ),
    );

  return $client;
}
```

**Comment by chloealee** [comment]
@jonuy I believe they are already on staging and prod because this function already existed (I didn't add when I created the `dosomething_northstar_get_northstar_user` function. I'll do some more digging to see what the issue might be!
