### ISSUE TITLE
hide campaign type from regional admins on /node/add/campaign

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5125]
![image](https://cloud.githubusercontent.com/assets/6330971/9887046/95b8e3c0-5bbb-11e5-827f-a704ed086277.png)

**Comment by itsjoekent** [comment]
is this the only field which is no longer being hidden? if thats the case can we verify that the field is marked as translatable

**Comment by mikefantini** [comment]
hmm actually @deadlybutter everything looks good on thor. staging seems to be missing a lot of the global stuff.

**Comment by itsjoekent** [comment]
gotcha and yeah that makes sense, most of the global work isn't on the dev branch and we only deploy dev to staging.

but based on that meeting i imagine this is changing soon

**Comment by mikefantini** [comment]
yeah https://github.com/DoSomething/phoenix/pull/5120 was meant to be merged in but wasn't before staging was deployed. looking all good now.
