### ISSUE TITLE
nothing but title saves first time i create a campaign as regional admin

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5126]
http://staging.beta.dosomething.org/node/1701/edit

![image](https://cloud.githubusercontent.com/assets/6330971/9888032/c8c715ca-5bc0-11e5-9e89-8944b84cc559.png)

cc: @angaither

**Comment by mikefantini** [comment]
it still works properly for editors FYI

**Comment by angaither** [comment]
caused by `dosomething_global_presave()`

when I commented that function out, everything saved correctly
