### ISSUE TITLE
auth modal doesn't appear after logging out

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5127]
to recreate:
- log in to the site
- log out
- try to log back in

the modal never appears

**Comment by mikefantini** [comment]
worked in firefox, but issue is occurring in chrome Version 45.0.2454.85 (64-bit)

**Comment by DFurnes** [comment]
`ReferenceError: Can't find variable: Modernizr`

Looks like the Modernizr build failed when building assets (and therefore modals aren't working, since we depend on Modernizr to do feature detection for CSS3 animations).

**Comment by DFurnes** [comment]
From the [Jenkins staging build](https://jenkins.dosomething.org/job/Deploy-Staging/213/console):

![screen shot 2015-09-15 at 4 00 14 pm](https://cloud.githubusercontent.com/assets/583202/9888407/ec562772-5bc2-11e5-909f-5874b5db9bbd.png)

**Comment by DFurnes** [comment]
It looks like the Modernizr team pushed a new version of [their website](https://modernizr.com) with the release of Modernizr 3.0, which [broke their grunt-modernizr plugin](https://goo.gl/tLPr46). Looking into a good quick fix.

**Comment by mikefantini** [comment]
nevermind, it broke on firefox for me too

**Comment by DFurnes** [comment]
@mikefantini Yep, it will be broken for any browsers. What happened is that one of the dependencies that we use for feature detection on the front-end was broken, so it wasn't creating functioning builds. Since modals depend on this component, they were silently failing when they tried to load.

**Comment by DFurnes** [comment]
Verified that this is fixed now on staging. Closing! 

Opened a [follow-up issue](https://github.com/DoSomething/phoenix/issues/5129) to update Modernizr when we have some time.
