### ISSUE TITLE
Update Modernizr to newest release

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#5129]
The Modernizr team released the long-awaited [version 3.0](https://modernizr.com/news/modernizr-3-new-release-site). We should look into updating our build process when [grunt-modernizr](https://github.com/Modernizr/grunt-modernizr) is officially updated, and also using official versions of tests that we had previously manually included, like the [CSS3 :checked selector](https://github.com/DoSomething/forge/blob/be086f42e642f5b6d003f1bdd923e2f321734593/js/modernizr/checked.js#L1-L4) test.

**Comment by DFurnes** [comment]
Oh, here's another one that's been done. 🎯 Closing!

**Comment by angaither** [comment]
YAIS @DFurnes 👏
