### ISSUE TITLE
Display country-specific content at URLs with country prefix

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#5130]
#### Dosomething.org
- Friendly to Global users
- Available in Global English, Spanish, Portuguese translations 
- Surfaces when there isn’t a country specific URL
#### DoSomething.org/mx
- Country specific redirects with native content + global content

Basic Fastly flow here - https://drive.google.com/a/dosomething.org/file/d/0BwVjZK9CrAH_VGMyeXphU0V3YWc/view

In most cases Fastly will direct the user to the appropriate URL, but content that's visited directly with a country prefix should not be redirected.

**Comment by mshmsh5000** [comment]
Every variation of this needs to be represented in the doc that @namimody is putting together.

**Comment by mshmsh5000** [comment]
These tests (in red) are meant to relate to this issue. We'll need to agree on these as a group, how they get implemented, and in what layers (app vs. Fastly)

![redirect-tests](https://cloud.githubusercontent.com/assets/149811/9919949/33eaf0fa-5c9e-11e5-8b57-df6111e9c313.png)

**Comment by angaither** [comment]
things we talked about 
- [ ] url alias per language
- [ ] translation redirect module

**Comment by mikefantini** [comment]
URL alias per language: http://thor.dosomething.org/admin/config/search/path/patterns

seems like we'll have to add in https://www.drupal.org/project/pathauto_i18n to apply alias to each translation

cc: @blisteringherb

**Comment by mshmsh5000** [comment]
Current bad behavior: #5163

**Comment by angaither** [comment]
hm
I also just found this setting

`https://thor.dosomething.org/admin/config/regional/language/edit/en`
![screen shot 2015-09-18 at 3 56 08 pm](https://cloud.githubusercontent.com/assets/645205/9969660/d986bbae-5e1d-11e5-960b-35471ad25664.png)

**Comment by mshmsh5000** [comment]
BLARGH -- good find @angaither -- I don't think we've configured this at all correctly yet:

![detection](https://cloud.githubusercontent.com/assets/149811/9970102/0a773632-5e21-11e5-8fb3-3c75c518522b.png)

**Comment by mshmsh5000** [comment]
This is set up correctly, i.e., to obey path prefix and not domain:

https://thor.dosomething.org/admin/config/regional/language/configure/url

I changed [the detections settings](https://thor.dosomething.org/admin/config/regional/language/configure) to simplify:

![url-first](https://cloud.githubusercontent.com/assets/149811/9978084/2a3ddfac-5eee-11e5-822a-8f1567c2aed0.png)

For both interface and content, the URL overrides, followed by the user's language preference.

We now have language-specific path settings that appear to be redundant.

**Pathauto settings**

![path-settings](https://cloud.githubusercontent.com/assets/149811/9978114/3dcb01a2-5eef-11e5-9861-d525059b5991.png)

**Language codes**

![language-settings](https://cloud.githubusercontent.com/assets/149811/9978117/507bcdc2-5eef-11e5-84a6-8cf2d8320364.png)

This is leading to some confusion in the paths that are getting created for content. For instance, a Brazilian translation of a global campaign:

https://thor.dosomething.org/pt-br/br/campaigns/brazil-animal-campaign

This suggests that we should remove the Pathauto settings and update the language codes to the scheme we want:
- **[nothing]** Global English
- **us** US English
- **mx** Mexican Spanish
- **br** Brazilian Portuguese

I've removed the Pathauto settings, so there's just one default pattern.

![no-pathauto](https://cloud.githubusercontent.com/assets/149811/9978137/b5cfd25e-5eef-11e5-8d33-7ed96e3360a8.png)

Now, when we try to set **[nothing]** as the language/path prefix code for Global English, we run into this:

![global-eng-path](https://cloud.githubusercontent.com/assets/149811/9978143/e0971088-5eef-11e5-8c87-07ba6d26c78b.png)

**Next step:** Try setting Global English as the default language in the system. Then [set the language prefixes](https://thor.dosomething.org/admin/config/regional/language) to the path prefix scheme we desire.

After any of these changes, we'll need to delete and regenerate aliases on Thor. If we ever do this on production, we'll need to make _absolutely sure_ Drupal auto-generates redirects from old paths to new ones (e.g., `/campaigns/awesome` to `/us/campaigns/awesome`).

**Comment by mshmsh5000** [comment]
## Settings implemented on Thor

### Language detection

![lang-detect](https://cloud.githubusercontent.com/assets/149811/10005461/66f27082-6085-11e5-92a0-58d77d8db3c0.png)

_N.b._ The first section, _User interface text language detection_, should only apply for non-entity content. My theory is that, for Phoenix, it will only apply to admin-side menus, which is why I made **User** the primary determinant. But we'll need to test this carefully.

### Default and enabled languages

![default-lang](https://cloud.githubusercontent.com/assets/149811/10005571/ef8c3644-6085-11e5-8b53-e85f9a432391.png)

(The Solr config warning is documented in #5176 for follow-up.)

### Individual language config

On the individual language config pages ([en-us example](https://thor.dosomething.org/pt-br/admin/config/regional/language/edit/en)), the country codes for use in URL construction are set to these:
- **Global English:** [blank -- no code]
- **US English:** `en`
- **Mexican Spanish:** `mx`
- **Brazilian Portuguese:** `br`

### Pathauto patterns

Here, we just add translations of _campaigns_ to use for BR and MX campaign paths:

![path-patterns](https://cloud.githubusercontent.com/assets/149811/10005742/0a200f2a-6087-11e5-9e74-14b5aa850a94.png)

**Comment by mshmsh5000** [comment]
Updated the PT/ES "campaign" path patterns to something less...militaristic, pending review by actual translators:

![path-patterns](https://cloud.githubusercontent.com/assets/149811/10021292/76a54190-6115-11e5-95da-b004de8dd96b.png)

**Comment by mshmsh5000** [comment]
I'm splitting off the redirect behavior into a different issue (#5183).

**Comment by blisteringherb** [comment]
Just to distill all the findings above and to make sure I understand, here's what I've done which seems to work.
1. Change the i18n Pathauto settings so that they do not contain 'br' or 'mx'.
2. Add 'br' and 'mx' to path prefix settings in `admin/config/regional/language`
3. Enabled URL detection `admin/config/regional/language/configure`
4. Delete and bulk update all URL aliases for content
5. Reindex content in solr
6. Profit.

The links to campaigns seem to work properly now and the admin paths also have the appropriate language prefix. I've exported all these settings and made a PR against the global branch. https://github.com/DoSomething/phoenix/pull/5220
