### ISSUE TITLE
no info getting pulled into permalink page as owner or non-owner

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5132]
items missing from owner:
- caption
- author name
- why participated

items missing from non-owner:
- problem
- solution (fact OR statement)
- caption
- author name

owner on staging:

![image](https://cloud.githubusercontent.com/assets/6330971/9905652/366ca2fa-5c54-11e5-9ddd-2a5771972fdd.png)

owner on prod:

![image](https://cloud.githubusercontent.com/assets/6330971/9905763/d636f678-5c54-11e5-894f-a8adf1a538c7.png)

non-owner on staging:

![image](https://cloud.githubusercontent.com/assets/6330971/9905627/17a67530-5c54-11e5-8116-2cfdd2b3c055.png)

non-owner on prod:

![image](https://cloud.githubusercontent.com/assets/6330971/9905771/e377a06c-5c54-11e5-9078-40bee11dee42.png)

**Comment by angaither** [comment]
this actually isn't broken for me locally (with the latest code and the database from stage)
I think it might be a cache issue --since the results of are stored in a custom cache table. 
@sheydari-ds how are custom cache tables dealt with on stage? is it on redis, can I log into a client and look?

**Comment by ghost** [comment]
@angaither Redis is run on staging. You can use this client here: http://redisdesktop.com/ for browsing. Ping me when you have time and I can help get it set up for you.

**Comment by angaither** [comment]
Actually the `caption/user name/why participated` is all there... the text is just white
cc @DFurnes

**Comment by angaither** [comment]
as far as the non owner stuff
it looks like the majority of content is missing from  `dosomething_campaign_load()` probably from translation stuffs

**Comment by angaither** [comment]
the problem fact and solution are also there, they are just showing up as white text

**Comment by angaither** [comment]
@DFurnes I think the issue is from the most recent forge changes (since that's the last time the file was touched) https://github.com/DoSomething/phoenix/commit/7e15f5fdb5d96165d466cc052816f27eb32ef74d
