### ISSUE TITLE
Query to get total chars on a specific campaign node

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5133]
pull the total word count from a given campaign node
field list tbd...

**Comment by angaither** [comment]
I think a super quick and dirty way we can get this is on stage
from `dosomething_campaign_load` on a specific campaign 

```
  $wcc = (array) $campaign;
  $count = 0;
  foreach($wcc as $wcc_thing) {
    if (is_string($wcc_thing)) {
      $count += str_word_count($wcc_thing);
    }
  } 
 dpm($campaign);
```

but this ignores facts, steps and faqs

cc @fantini @mnelson338

**Comment by itsjoekent** [comment]
If we're getting hacky I have an even hackier idea... I can make a simple node script that crawls every campaign page and counts all of the words on it

**Comment by angaither** [comment]
closing @mnelson338 got it already :ok_hand:
