### ISSUE TITLE
SEO: Ensure proper hreflang and canonical URL markup

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5136]
Relates to #4910 and this article:

https://support.google.com/webmasters/answer/189077?hl=en

Two principles I think we can agree on:
1. If a page has variations in other languages, they should be noted in the header as `<link rel="alternate" hreflang="es-mx" href="https://www.dosomething.org/mx/my/url" />`
2. If a page has no variations in other languages, but is accessible by multiple URLs, the header should specify the [canonical URL](https://support.google.com/webmasters/answer/139066?hl=en) as `<link rel="canonical" href="https://www.dosomething.org/my/url" />`

**Comment by weerd** [comment]
@mshmsh5000 @angaither any suggestions on how to best determine if the page _has_ variations in other languages? Some pages (like Facts pages) might have some stuff translated which has been included in POEditor, but not the rest of the page content:

![image](https://cloud.githubusercontent.com/assets/105849/10110036/a47f5be8-6398-11e5-9075-da9d708e774a.png)

**Comment by mikefantini** [comment]
@weerd what's the url for that fact page?

**Comment by weerd** [comment]
@joe just showed me that if a node has translations the `translations` object should be populated with the available translations (which I didn't have before since my campaigns on local are not translated, but I just added one).

![image](https://cloud.githubusercontent.com/assets/105849/10110214/d39cce14-6399-11e5-8cda-9a4f1f92e244.png)

However, stuff with partial content translated will still pose an issue.

**Comment by weerd** [comment]
@mikefantini it's on my local since my local has the .PO file imported with some translations from POEditor.

**Comment by itsjoekent** [comment]
are fact pages actually supposed to have two different languages? that doesnt seem right

**Comment by weerd** [comment]
@deadlybutter it's not that they have two different languages, it's that there's `node` content and content from DB getting output on the same page. The DB content is translated via `t()` and the **.po** file, while currently we aren't translating Fact page `node` content.

**Comment by itsjoekent** [comment]
gotcha... yeah this is a tricky one

**Comment by weerd** [comment]
@mshmsh5000 for number 2 in the issue, by "accessible by multiple URLs", do you mean content that may have redirects from other urls? Is there an example on the DS site I can refer to?

**Comment by weerd** [comment]
Okie doke. Had a quick meeting w/ @mshmsh5000 and we're going to break off part 2 of this issue into it's own issue and table it temporarily until we have the full prefixed URL setup working properly along with all the static content available (that could be duplicates between english and global english which is where the canonical stuff would apply). So once that's set we can test and move forward with an implementation.
