### ISSUE TITLE
Give Site Admins Ability to Archive Activity

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5137]
Currently site admins (ex: Michaela) do not have the ability to archive activity and need it to re-run campaigns. Can we allow them to see and use the second to last tab on the campaign admin options?

![image](https://cloud.githubusercontent.com/assets/12396076/9922068/2f3e08c6-5cb2-11e5-906c-a878cc6dfa67.png)

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PlUP19tJ&#x2F;1482-archive-activity-ability"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Archive Activity Ability</a>

**Comment by mikefantini** [comment]
@namimody we might want to limit this to site admins since this can't be undone. this would create a sort of +1 process for this. thoughts?

**Comment by namimody** [comment]
Hmmm I see @mikefantini. Are any leads currently site admins? I think giving one lead the power to do so, so that ability and responsibility is housed with the team, would be good. What do you think?

**Comment by mikefantini** [comment]
@namimody yeah it would be great if you could do a permissions audit here https://www.dosomething.org/admin/people. but yes at least one campaign lead Ben, and Felicia should be site admins

**Comment by namimody** [comment]
@angaither was just going through FRUGS and noticed this issue. I think I can close as we will no longer be archiving activity with the new runs configuration. And there isn't anything we need to change re: site permissions for this reconfig -- as from what I understand, editors already have permission to create and edit runs. If that's all correct, I'll close!

**Comment by angaither** [comment]
bam perf

**Comment by namimody** [comment]
:raised_hands:
