### ISSUE TITLE
Trying to Submit RB without Photo Should Result in Banner Error

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5141]
Currently, if you try to submit an RB without a photo, the page shifts a bit, but no error message is provided as to why the RB is not submitting. Perhaps a banner error message could read, "Oops! Try submitting again when you've added a photo of you taking action."

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zBqzRoag&#x2F;1486-trying-to-submit-rb-without-photo-should-result-in-banner-error"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Trying to Submit RB without Photo Should Result in Banner Error</a>

**Comment by namimody** [comment]
@mikefantini @angaither thoughts on adding this?

**Comment by mikefantini** [comment]
Seems like a worthwhile enhancement to have. I'd just adjust the copy slightly to read: "Oops! Make sure to upload a photo of you completing the campaign before submitting."

A little clearer error message IMO.
