### ISSUE TITLE
Query to pull out hardcoded content 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5144]
to help with #5007 we need to upload the content that is currently in these settings into the POEditor
#### custom copy in variable table

``` sql
SELECT `name`, `value` 
FROM variable 
WHERE `name` like "dosomething_%" 
AND (`name` like "%copy%" or 
    `name` like "%body%" or 
    `name` like "%label%" or 
    `name` like "%header%" or 
    `name` like "%title%" or 
    `name` like "%msg%" or
    `name` like "%intro%" or 
    `name` like "%permalink%" or
    `name` like "%prompt%" or
    `name` like "%link%" or 
    `name` like "%text%"
);
```
#### custom copy in dosomething_helpers

``` sql
SELECT `name`, `value`
FROM dosomething_helpers_variable
WHERE `name` like "%msg%"
OR `name` like "%copy%";
```

**Comment by angaither** [comment]
@weerd @mikefantini I've attached the queries above, not sure what the next step is to export/upload? this to be checked against the list @julielorch created

**Comment by weerd** [comment]
```sql
select `value` from variable where `name` like "dosomething_%" and (
	`name` like "%copy%" or 
	`name` like "%body%" or 
	`name` like "%label%" or 
	`name` like "%header%" or 
	`name` like "%title%" or 
	`name` like "%msg%" or
	`name` like "%intro%" or 
	`name` like "%permalink%" or
	`name` like "%prompt%" or
	`name` like "%link%" or 
	`name` like "%text%"
)
```

This is the one I used last night.

**Comment by mikefantini** [comment]
@angaither i'm not sure what the next step is either.

@weerd thoughts?

also here is the doc that needs to be checked against just for reference (obviously tab 2 isn't in droops)

https://docs.google.com/spreadsheets/d/1N94cbs30GZxJvZvzoGszekhI1YOcGzwkRO9AwwguwBo/edit#gid=0

**Comment by angaither** [comment]
@mikefantini so this is what I was going to talk to you about. 
we have to 
- [x] [export the content from prod](https://gist.github.com/angaither/71aba87edb95b1fd588b)
- [x] [convert it from a CSV -> POT file](https://gist.github.com/angaither/c8ecab944f7a0dd49d46)
- [x] upload it
- [ ] Check it against that doc

**Comment by weerd** [comment]
And I'm working on this part #5147, based on same data pulled from prod to update the code.

**Comment by angaither** [comment]
did the first two steps of this

**Comment by weerd** [comment]
Should this be closed @angaither?

**Comment by angaither** [comment]
I think we should wait close it till we find if other content is missing

**Comment by angaither** [comment]
based on [this doc](https://docs.google.com/spreadsheets/d/1N94cbs30GZxJvZvzoGszekhI1YOcGzwkRO9AwwguwBo/edit#gid=0)

things missing

### header footer content
- [header content](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/themes/dosomething/paraneue_dosomething/paraneue_dosomething.info#L23-L27)  
  - theme settings needs t()
- [footer content](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/themes/dosomething/paraneue_dosomething/paraneue_dosomething.info#L49-L67)
  - theme settings needs t()
  - privacy policy -- title of a static content node(translated via static content)

### user login
- [my account link](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/themes/dosomething/paraneue_dosomething/templates/system/partials/navigation.tpl.php#L37) 
  - needs t()
- "user account" at top of login page -- no idea
- error message (username/email taken) -- might be in drupal core?

### password reset page
- email new password button - no idea

### registration form

### registration form errors
- [error copy is in Drupal.t()](https://github.com/DoSomething/phoenix/blob/c6cc43a45aca8deb8fa3cc62ede7614644a1e1ce/lib/themes/dosomething/paraneue_dosomething/js/validators/address.js)

### user profile
- [nothing here](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_user/dosomething_user.theme.inc#L41)
- [no_signups_copy](https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/modules/dosomething/dosomething_user/dosomething_user.theme.inc#L46)
  -- both wrapped in t() already, but it's in user.module 
- field labels (first name, cell # etc) -- in the module 

### zendesk error message
- [in module](https://github.com/DoSomething/phoenix/blob/f47679866a9f8175ee9c911077e4cc5865ab0dc2/lib/modules/dosomething/dosomething_zendesk/dosomething_zendesk.module#L236)

### campaign pages

#### most of this stuff appears to be in the module
- [sign up button](https://github.com/DoSomething/phoenix/blob/80f68cc0a27a9f0044b967a22f9e6abd98142959/lib/modules/dosomething/dosomething_signup/dosomething_signup.forms.inc#L53) -- in module
- [a dosomething campaign...](https://github.com/DoSomething/phoenix/blob/6da5195e2786138aeb92be8b088a0ec636984a16/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L607) -- in module
- [FAQs](https://github.com/DoSomething/phoenix/blob/8df54592194c1ba22eb4b44b8a559c16191dc7ae/lib/modules/dosomething/dosomething_helpers/modal-links.tpl.php#L22) -- also in tpl in a module :what:
- [learn more about :issue:](https://github.com/DoSomething/phoenix/blob/8df54592194c1ba22eb4b44b8a559c16191dc7ae/lib/modules/dosomething/dosomething_helpers/modal-links.tpl.php#L7)
- [why we <3 :partner:](https://github.com/DoSomething/phoenix/blob/8df54592194c1ba22eb4b44b8a559c16191dc7ae/lib/modules/dosomething/dosomething_helpers/modal-links.tpl.php#L14)
- [stuff you need, vips, snap a pic etc](https://github.com/DoSomething/phoenix/blob/6da5195e2786138aeb92be8b088a0ec636984a16/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L420)
- [reportback form stuff, why is this important, number of x y'ed](https://github.com/DoSomething/phoenix/blob/050f2eacc04bb063490b313ad56fa069cbda9249/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.forms.inc#L86)
- [campaign signup message](https://github.com/DoSomething/phoenix/blob/80f68cc0a27a9f0044b967a22f9e6abd98142959/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L697)

**Comment by angaither** [comment]
lots of this stuff is in module files, so looks like we will have to export those for POE cc @weerd

**Comment by weerd** [comment]
@mikefantini @angaither 

https://github.com/DoSomething/phoenix/blob/98ee1bc76940a4a70db1ddd501bbe8ecb4a3ce3f/lib/themes/dosomething/paraneue_dosomething/paraneue_dosomething.info#L49-L67 These don't seem to match what's actually in footer on prod...

**Comment by mikefantini** [comment]
@weerd footer copy seems to be located here https://www.dosomething.org/admin/appearance/settings/paraneue_dosomething

**Comment by mikefantini** [comment]
@weerd please make sure to check for "oh snap! we'll work on that. want to try another combo?" it may be split up into two different strings.

**Comment by weerd** [comment]
Oh snap! I'll work on that. Good call. Will make sure it's added :wink:

**Comment by weerd** [comment]
@mikefantini most of the stuff @angaither pointed out in the comment above should be set in POT files and will be adding to the Phoenix project on POEditor soon.

There's some more modules I'll probably check as well...

**Comment by weerd** [comment]
@mikefantini btw, forgot to mention that the "Oh Snap!..." copy was already extracted in the theme POT file. Just confirmed it exists in POEditor too :wink:

**Comment by mikefantini** [comment]
awesome thanks!
