### ISSUE TITLE
Ensure Secured User Access

### ISSUE THREAD

**Issue by ghost** [DoSomethingArchive/legacy-website#5151]
Expire old SSH keys, segment users, etc.

**Comment by mikefantini** [comment]
@sheyd any update on this?

**Comment by mikefantini** [comment]
@sheyd should this move to the Phoenix release 2.1 milestone?

**Comment by sheyd** [comment]
@mikefantini It occurs to me this isn't just one ticket. I'll put a pin in this to break it out into actionable steps, and add some of the tickets to 2.1.

**Comment by angaither** [comment]
i
