### ISSUE TITLE
Return Fastly geo headers to the client

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5154]
At least while we develop. Maybe just the country code?

**Comment by ghost** [comment]
Setup and tested. With Mexico TorGuard Proxy:

`mocha:hubot-george sheydari$ curl -Iv thor.dosomething.org
- Rebuilt URL to: thor.dosomething.org/
-   Trying 23.235.40.65...
- Connected to thor.dosomething.org (23.235.40.65) port 80 (#0)
  > HEAD / HTTP/1.1
  > Host: thor.dosomething.org
  > User-Agent: curl/7.43.0
  > Accept: _/_
  > 
  < HTTP/1.1 301 Moved Permanently
  HTTP/1.1 301 Moved Permanently
  < Server: Varnish
  Server: Varnish
  < Retry-After: 0
  Retry-After: 0
  < Location: https://thor.dosomething.org/
  Location: https://thor.dosomething.org/
  < Content-Length: 0
  Content-Length: 0
  < Accept-Ranges: bytes
  Accept-Ranges: bytes
  < Date: Fri, 18 Sep 2015 15:09:09 GMT
  Date: Fri, 18 Sep 2015 15:09:09 GMT
  < Via: 1.1 varnish
  Via: 1.1 varnish
  < Connection: close
  Connection: close
  < X-Served-By: cache-ord1726-ORD
  X-Served-By: cache-ord1726-ORD
  < X-Cache: HIT
  X-Cache: HIT
  < X-Cache-Hits: 0
  X-Cache-Hits: 0
  < X-Fastly-Country-Code-Client: MX
  X-Fastly-Country-Code-Client: MX`
