### ISSUE TITLE
Remove first name fields from SMS game form

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#5157]
The first name fields tested in #4247 and implemented in #4710 are unfortunately being reverted! :fire: Although they increased completion rate for games, they decreased conversion rates significantly. Therefore, we're going to remove those fields and return styles to how they were previously.

/cc @mikefantini @namimody

**Comment by DFurnes** [comment]
According to Freddie, there are no changes needed on the Node backend for this change & he's working on updating the language used in the games to not reference player names.

**Comment by DFurnes** [comment]
@mikefantini This is ready to go once #5160 is merged. Just waiting on confirmation that we're okay for these changes to go live.

**Comment by mikefantini** [comment]
we will be by the time we deploy to prod yeah. thanks @DFurnes
