### ISSUE TITLE
global footer needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5166]
not sure exactly how we're doing this work, but want to make sure we have a place to discuss how we'll be doing this work.

**Comment by angaither** [comment]
still not sure if we have a path (pun intended) forward with this, or what the plan is. adding the blocked label to surface the issue.

**Comment by mikefantini** [comment]
here is where we find the footer: https://www.dosomething.org/admin/appearance/settings/paraneue_dosomething

**Comment by mshmsh5000** [comment]
So, two approaches:
1. Define each section of links as a block, instead of a custom setting. We provide different blocks for each language.
2. Go with the MailChimp settings approach: Create a separate set of settings for each country. Not sure how this works for the entire page of Paraneue settings, though.

**Comment by angaither** [comment]
@DFurnes I think the easiest way to approach this based on how it's currently built, is to go the mailchimp approach that @deadlybutter took [here](https://github.com/DoSomething/phoenix/blob/3a17e0779da5a63c337ec9dcbfc89043fe74cc23/lib/modules/dosomething/dosomething_signup/dosomething_signup.admin.inc#L22)

**Comment by mikefantini** [comment]
@DFurnes any updates on this?

**Comment by DFurnes** [comment]
I have a branch in progress for this on my local. I'm out Thursday and Friday, but should easily be able to finish this up on ~~Monday~~ right, TUESDAY! :smile:

**Comment by mikefantini** [comment]
:) we're off Monday but Tuesday sounds good! once you finish this can you please make sure to deploy to Thor so TSG can test?

cc: @namimody

**Comment by mikefantini** [comment]
also once this is done we'll need to edit the footer to replicate what we'll want it to be on prod. see https://docs.google.com/document/d/1_nK9VZQ6DQIZ46A6XCxQqeK1TUcO1ssMyJUNSbyPDr4/edit
