### ISSUE TITLE
Set user language based on fastly header when registering

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#5168]
When a user signs up we should read the Fastly headers and set there language appropriately. Functions in dosomething_settings can be found to read the data embedded in the headers.

cc: @DeeZone @mikefantini 

**Related**:
- https://github.com/DoSomething/phoenix/issues/4955 - User Registration transactional email
- https://github.com/DoSomething/phoenix/issues/4958 - Password reset transactional email

**Comment by itsjoekent** [comment]
apparently this didnt work 

from @namimody 

New user from Brazil got stored as global english, and got sent Brazilian transactional

**Comment by angaither** [comment]
@deadlybutter see my notes in #5263 
I think we should break both of these out into a new function together

**Comment by mikefantini** [comment]
just to recap:

if (fastly header is supported lang) { set that lang} 
else if (some other random country) { global english} 
else if (fastly header not set) {us english}

**Comment by deezone** [comment]
Looking at the StatHat report for mbc-transactional-email which is logging the country being sent from the Drupal app / Fastly over the weekend. There's are occasionaly periods when Fastly is returning "1" or "0" as the detected country. 

I'd suggest the logic @angaither is suggesting also include catching non two letter country codes from Fastly as well.

cc: @mikefantini
