### ISSUE TITLE
RB Gallery Not Showing Photos Using Correct Logic

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5170]
The first 6 photos of the gallery ​_should_​ pull from first promoted and then if less than 6 promoted, approved photos.

Additionally, when no photos were promoted on the back end, but were approved, the gallery should pull the approved ones in rather than show placeholder images.

Currently, on Suspended for What, 6 photos are approved and only 5 are showing:
![image](https://cloud.githubusercontent.com/assets/12396076/10001117/30a85b16-606e-11e5-9542-f760e3e8d984.png)

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c0Txakv7&#x2F;1488-rb-gallery-not-showing-photos-using-correct-logic"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> RB Gallery Not Showing Photos Using Correct Logic</a>

**Comment by mikefantini** [comment]
Yeah it doesn't seem like approved photos are showing up at all on the gallery.

@angaither assigning over to you to assign out.

**Comment by angaither** [comment]
@weerd mind taking a look once you wrap up some POT files

**Comment by mikefantini** [comment]
Here is an example: https://staging.dosomething.org/us/campaigns/test-campaign

**Comment by angaither** [comment]
planning for @weerd to take a look at this within this sprint, but not merge until Jan

**Comment by aaronschachter** [comment]
Possibly related to #5653
