### ISSUE TITLE
fatal error from ds user module

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5178]
[`( ! ) Parse error: syntax error, unexpected '{' in /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_user/dosomething_user.module on line 463`](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L463)

**Comment by itsjoekent** [comment]
missing a second )
