### ISSUE TITLE
Extract translatable entity content into structured format (XML, JSON)

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5186]
Need for an external translation service. This extraction should be for any content that's normally managed by editors, and that's not stored in special config vars:
- Campaign content
- Facts
- Static content

**Comment by mikefantini** [comment]
ideally only pulling out this content: https://trello.com/b/HWVvUsxW/translation-pipeline

**Comment by mshmsh5000** [comment]
First thought is to construct a View that outputs to RSS.

Sample extraction, just to show what we get with a five-minute effort:

http://www.feedbucket.com/?src=http://phantomclick.com/campaigns.xml&start=20

**Comment by mshmsh5000** [comment]
At least two problems with the Views RSS approach:
1. [The output itself](https://gist.github.com/mshmsh5000/ad345e6ee001048f5aa9) is messy.
2. Doesn't provide an ingestion method for translated content.

**Comment by mshmsh5000** [comment]
Here's sample RSS output [cleaned up into an array](https://gist.github.com/mshmsh5000/5e9c12c1cc57cb5d4c0e).

It's not bad. A few awkward missing spaces from stripping tags out of the default RSS output.

...And missing Facts. Looking into that.

**Comment by angaither** [comment]
closing, we aren't going this route!

**Comment by mshmsh5000** [comment]
Phew -- you really didn't want to see the PR for this one.
