### ISSUE TITLE
only administrators and global admins should have access to Translate Tab

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5191]
![image](https://cloud.githubusercontent.com/assets/6330971/10030180/5dd22550-6144-11e5-9fad-757d6bc8fe3c.png)

**Comment by angaither** [comment]
this was added when I granted regional admins the ability to translate content in #5180

**Comment by angaither** [comment]
this isn't working, hook_menu_alter() will hide any other tab, but I think there's a bug in how entity_translate handles those menu items

I was seeing errors in drush from this in the entity translate module

``` php
 if (isset($backup['node'])) {
    $item = $backup['node'];
    // Preserve the menu router item defined by other modules.
    $callback['page callback'] = $item['page callback'];
    $callback['file'] = $item['file'];
    $callback['module'] = $item['module'];
    $access_arguments = array_merge(array(1, $item['access callback']), $item['access arguments']);
  }
  else {
    $callback = FALSE;
    $access_arguments = array(1);
  }

  $items['node/%node/translate']['page callback'] = 'entity_translation_overview';
  $items['node/%node/translate']['page arguments'] = array('node', 1, $callback);
  $items['node/%node/translate']['access arguments'] = $access_arguments;
  $items['node/%node/translate']['access callback'] = 'entity_translation_node_tab_access';
  $items['node/%node/translate']['file'] = 'entity_translation.admin.inc';
  $items['node/%node/translate']['module'] = 'entity_translation';
```

error with array merge `$access_arguments = array_merge(array(1, $item['access callback']), $item['access arguments']);`

**Comment by angaither** [comment]
I tried changing the weight of this module, didn't work
tried implementing `hook_implements_alter()` still nothing

this code will hide any other tab with those permissions
(change to `node/%node/edit` and it works as expected, so not sure what's going on here

**Comment by mshmsh5000** [comment]
Fuck this issue

**Comment by mshmsh5000** [comment]
How about a JS HACK where we just hide the goddamn tab.

**Comment by mshmsh5000** [comment]
@angaither drupal_add_js()

**Comment by weerd** [comment]
So I got the above to work and properly hide the Translate tab... only issue w/ a JS solution as opposed to a PHP solution is that the tab shows up in two places... the admin CMS side and here:

![image](https://cloud.githubusercontent.com/assets/105849/10253203/2132e0e4-690a-11e5-8cda-c708ffd82930.png)

So I'm going to create an issue to hide it on the fender side as well.

**Comment by weerd** [comment]
So I got the above to work and properly hide the Translate tab... only issue w/ a JS solution as opposed to a PHP solution is that the tab shows up in two places... the admin CMS side and here:

![image](https://cloud.githubusercontent.com/assets/105849/10253271/7e9768ae-690a-11e5-9ea6-b8477d43546f.png)

So I'm going to create an issue to hide it on the fender side as well. 

_Note: I thought I was wrong and was looking at different page, so the above defs needs to be done as well. Sorry for the mixup_

**Comment by angaither** [comment]
lol 
"Do not allow pointless translation tab access"
https://www.drupal.org/node/2422435
