### ISSUE TITLE
need a global solution for address collection

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5193]
related to #5052 

need to:
1. swap out US-centric fields for Global ones when users are non-US (i.e. no state, zip)
2. figure out a solution for address validation

**Comment by mshmsh5000** [comment]
_Re: Validation:_ I'm into the validation approach in the [Phone module](https://www.drupal.org/project/phone) -- patterns broken out by countries.

_Re: Address collection:_ The more recent [Address module](https://www.drupal.org/project/address) seeks to address this.
