### ISSUE TITLE
Campaign Content added by DS Mexico only appearing in Active view - not in Admin/Edit

### ISSUE THREAD

**Issue by mnelson338** [DoSomethingArchive/legacy-website#5198]
The content for Do Something Mexico campaign: Noche De Monopoly (https://www.dosomething.org/node/5757 ) in the active view of the campaign ![screen shot 2015-09-23 at 10 48 34 am](https://cloud.githubusercontent.com/assets/14057906/10048409/af6bb862-61e0-11e5-93ce-56fe80fa233f.png)
but is not reflected in the Admin/Edit view of the campaign 
![screen shot 2015-09-23 at 10 46 44 am](https://cloud.githubusercontent.com/assets/14057906/10048414/b4d6c292-61e0-11e5-97da-3f587a57b0cb.png)

**Comment by mikefantini** [comment]
also note:

when @mnelson338 was on /admin/content logged in as the user who created node 5757 and she copied the link address of the edit button on /admin/content and then removed "?destination=admin/content" from the end of the copied URL, she saw the content in the edit view that was supposed to be there.

however, just now when trying to recreate those steps, we are still seeing no content in the fields on /edit.

**Comment by angaither** [comment]
@mnelson338 @mikefantini what's the url of the node/edit page they are seeing?

**Comment by angaither** [comment]
from the db

| nid | type | language | title |
| --- | --- | --- | --- |
| 5757 | campaign | es-mx | Noche de Monopoly |

| entity_type | bundle | entity_id | language | field_call_to_action_value |
| --- | --- | --- | --- | --- |
| node | campaign | 5757 | en | Organiza una agradable noche familiar de juegos con un clásico juego de mesa |

**Comment by mikefantini** [comment]
@angaither as a Mexican Admin I see a blank view on https://www.dosomething.org/node/5757/edit

**Comment by mikefantini** [comment]
@mnelson338 should be able to include the link she is seeing when logged in as the user who created the node

**Comment by mikefantini** [comment]
i'm also now seeing this campaign page with no content on the stylized view again as a Mexican Admin:

![image](https://cloud.githubusercontent.com/assets/6330971/10051996/6b9ca742-61f2-11e5-9e74-8cd379e9d353.png)

**Comment by mikefantini** [comment]
but logged in as an administrator i do see the content on https://www.dosomething.org/campaigns/noche-de-monopoly:

![image](https://cloud.githubusercontent.com/assets/6330971/10052016/8f0b636c-61f2-11e5-88bc-71253649e573.png)

**Comment by mikefantini** [comment]
but I'm not seeing content in the fields in the backend of https://www.dosomething.org/node/5757/edit/es-mx when logged in as an administrator 

![image](https://cloud.githubusercontent.com/assets/6330971/10052036/b2b446da-61f2-11e5-902e-9e15089e4b0b.png)

**Comment by mnelson338** [comment]
@angaither For node/edit page: 
English: https://www.dosomething.org/node/5757/edit/add/es-mx/en
![screen shot 2015-09-23 at 1 26 22 pm](https://cloud.githubusercontent.com/assets/14057906/10052839/e9230e82-61f6-11e5-815e-5b5f7cfdd212.png)

Spanish: https://www.dosomething.org/node/5757/edit/es-mx?language=es-mx 
![screen shot 2015-09-23 at 1 26 04 pm](https://cloud.githubusercontent.com/assets/14057906/10052826/df7756c2-61f6-11e5-91c0-199e9e3ae217.png)

**Comment by mikefantini** [comment]
we believe that this is also causing the following experience:

as an MX Admin, if I go to /node/add/campaign and save the form I get a 404

**Comment by angaither** [comment]
we could change the default language to authors language here `admin/config/regional/entity_translation`
but that means we will have to fix this error #5042  in a different way

**Comment by namimody** [comment]
Not sure how helpful this is @mikefantini @sergii-tkachenko @angaither but as a US site admin, I can go into the Noche Monopoly, add content to the Mex Spanish tab, save, see it in the active view, close out, and reopen the active view to find the content saved in both active and edit.

Please note -- when I was editing content, necessary fields for creating a campaign were wiped (name, CTA, starter statement).

As a Mexican admin looking at the active tab, we saw the Spanish PLAN IT content. We saw my content in the English tab AND my content showed up in some fields in the active tab (Spanish content in the PLAN IT section, Nami's content in the DO IT section, both languages had content in the starter statement section, but the Spanish was showing). When we clicked into the Spanish edit tab, there was no content. As a MX admin, we added content to PROVE IT, which showed on active, and appears in edit when you return to that tab. Then, as a Mexican admin we put in content into the PLAN IT section (where Spanish content was appearing on the active tab but not on the edit tab), and it overrode all previously appearing copy. 

Then, uh, as a Mexican admin we stopped being able to see the Mexican/English options on the edit tab...even if we erased the /en from the end of the campaign /edit URL. (https://www.dosomething.org/node/5757/edit/en)
