### ISSUE TITLE
Clicking on campaign title re-directs to explore campaigns 

### ISSUE THREAD

**Issue by mnelson338** [DoSomethingArchive/legacy-website#5199]
Clicking the titles of new campaigns created by DS Mexico admin in "Search Content," redirects to explore campaigns. ![screen shot 2015-09-23 at 10 52 28 am](https://cloud.githubusercontent.com/assets/14057906/10048524/5130da4c-61e1-11e5-81d4-321e09bff5cf.png)

![screen shot 2015-09-23 at 10 54 12 am](https://cloud.githubusercontent.com/assets/14057906/10048556/74d840f2-61e1-11e5-840c-c0ae2c068580.png)

Clicking "Edit" doesn't go anywhere. 

Note: Content is being accessed using a DS Mexico Log in

**Comment by mikefantini** [comment]
possibly related to #5114 

cc: @deadlybutter

**Comment by itsjoekent** [comment]
yeah I originally thought this was related to the URL logic I added a few days ago, but I tested that and it worked fine. something else is going on... hm

**Comment by itsjoekent** [comment]
clarified with Micah and learned, this is only happening on prod...? and seems to be only affecting MX content. weird

**Comment by deadlybutter** [comment]
okay just tried doing this again this morning and the bug isn't occurring, I'll try as a global admin

**Comment by itsjoekent** [comment]
clicked on the title, URL is correct, just the campaign doesn't show

**Comment by itsjoekent** [comment]
all of these title links have the bug EXCEPT the one that isn't labeled "new". (monopoly) 

![screen shot 2015-09-25 at 9 58 44 am](https://cloud.githubusercontent.com/assets/897368/10102372/09a47a4e-636c-11e5-9ade-429d7ae42207.png)

**Comment by itsjoekent** [comment]
new discovery.

the monopoly link above goes to /node/nid

the others go to /campaigns/the-campaign-name

**Comment by itsjoekent** [comment]
went through a bunch of NID's, found one of the broken campaigns (El reto de los 50 litros), using the NID link works

https://www.dosomething.org/node/5693

**Comment by mikefantini** [comment]
yeah @deadlybutter i've been seeing the link disparity a lot on the homepage of thor as well

**Comment by itsjoekent** [comment]
I believe ^ that issue is the cause of this. admin/content links to /campaigns _however_ as explained in the above issue referenced, the URL for this campaign is /campanas (which is incorrect). Hopefully fixing that fixes this.

**Comment by itsjoekent** [comment]
yep that was it. fixed!

**Comment by itsjoekent** [comment]
happening for a few campaigns on prod again

**Comment by mikefantini** [comment]
I "fixed this" by creating a US English translation for each of these. 

I suspect this might have something to do with prod not being configured properly?

@namimody add to the QA doc for admins. closing for now.
