### ISSUE TITLE
Salt steps not running

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#52]
It seems like some of the salt steps listed in top.sls are not running.  For instance, drush is not installed and the install.sls does not seem to be firing.

Some investigating is necessary.

**Comment by mchitten** [comment]
It actually is running, but Drush isn't being downloaded properly therefore the dependencies on install.sls aren't fulfilled.  Investigating...

**Comment by desmondmorris** [comment]
@mchitten yah!  that makes sense :)

**Comment by mchitten** [comment]
Turns out it's an issue with ssh-agent.  Drush was installing fine last time I checked, but we can't fix the deal with cloning this repo.  Install steps are provided after running `vagrant up`, per #64

**Comment by desmondmorris** [comment]
good detective work
