### ISSUE TITLE
Password Reset web page in user language

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5201]
When a user is sent a password reset link in a transactional email message the message is sent in a language that's dependent on the country / DS affiliate the user signup at: 
- MX (Mexico: Spanish)
- BR (Brazil: Portuguese).

The password reset web page is currently only in English.

![image](https://cloud.githubusercontent.com/assets/2119264/10049721/bb52ab76-61e6-11e5-94c9-a1682a181360.png)

It's unclear if the page can rendered in different languages based on:
- a value in the reset key: 

```
http://dev.dosomething.org:8888/user/reset/1705348/1443018806/bnCyX8yrx66VCC7PCvE4g8QUvsL8gj-78HuCuHfSD4Q
```
- perhaps by appending a language preference to the reset link:

```
...vsL8gj-78HuCuHfSD4Q?origin=MX
```

The parameter option could be used by Drupal when rendering the page to choose a translation.

**Comment by mikefantini** [comment]
@DeeZone ok so when a user comes to this page they would have to be anonymous, so in that case we'd be relying on their location to determine what content to show them.

Given that, I _think_ if we just send the user the normal link, the content will be translated into the appropriate language for the user once we inject the translated POT files.

In any case, once everything else is set up let's see if this is working properly or not by just serving up the normal link and not doing anything special to the URL.

cc: @weerd @mshmsh5000

**Comment by mshmsh5000** [comment]
We _can_ add the same URL-prepending logic to these as we do to nodes ( #5183 ). That may be the only way to translate the content.

Also

https://www.drupal.org/node/86287
