### ISSUE TITLE
add other affliates to lang map

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5205]
for auth flow needs to hide/show certain fields based on country codes. 

UK and CA should be added to the lang map variable
should they be global english as language? 

refs #5052 #5085
cc: @blisteringherb @mshmsh5000

**Comment by mshmsh5000** [comment]
I'm not clear on why this is a Global 1.0 task, since UK and CA are out of scope and still have their own sites.
- en-gb
- en-ca
- fr-ca

Especially given Canada's two languages, I don't think we want to touch this right now.

**Comment by angaither** [comment]
@mshmsh5000 If we want to hide/show specific fields in the auth flow, I think it will be easier to have this stuff in the strongarm so @sbsmith86 can call one function to check countries, [instead of creating an array of country codes](https://github.com/sbsmith86/dosomething/commit/75aed93bde496350645ec49a01e38afde482c227#diff-b4b14fec58a66c7539097ce097603450R82)
I don't think we need to define roles, or permissions or the language, just the country if we want the auth flow to show different things.

**Comment by mshmsh5000** [comment]
Got it, got it. :+1:
