### ISSUE TITLE
Mailchimp list ID in user registration

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5212]
When a user registers a new user account on the Drupal site:
- [x] a MailChimp list ID value needs to be include in the transactional request to Message Broker. 
- [x] The MailChimp list ID will be used by the `mbc-registration-email` application to add the user to the appropriate MailChimp account (API key) and related list.

**~Blocked by~**
- Not able to install on Thor due issues detailed here: https://trello.com/c/py9MCdIy "Permission denied (publickey)."

**Related**:
- https://github.com/DoSomething/mbc-registration-email/issues/58

**Comment by DeeZone** [comment]
**Test `user_register`:
- [ ] `user_language` = `en`
- [ ] `user_country` = `US`
- [ ] `email_template` = `mb-user-register-US`
- [ ] `mailchimp_list_id` = `f2fab1dfd4` (General US DoSomething list)
```
Array
(
    [activity] => user_register
    [email] => dlee+thorUS01@dosomething.org
    [uid] => 3118613
    [user_language] => en
    [user_country] => US
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Dee Thor Us 1
        )
    [email_template] => mb-user-register-US
    [mailchimp_list_id] => f2fab1dfd4
    [birthdate] => 929232000
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )

    [activity_timestamp] => 1444339916
    [application_id] => US
)
```

**Comment by DeeZone** [comment]
```
Array
(
    [activity] => user_password
    [email] => dlee+thorUS01@dosomething.org
    [uid] => 3118613
    [user_language] => en
    [user_country] => US
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Dee Thor Us 1
            [RESET_LINK] => https://thor.dosomething.org/us/user/reset/3118613/1444341234/kHmXkHV0upL-wbO-KqkGvmnpOnSNc67Ewm7knc6LAqA
        )
    [email_template] => mb-user-password-US
    [email_tags] => Array
        (
            [0] => drupal_user_password
        )
    [activity_timestamp] => 1444341234
    [application_id] => US
)
```

**Comment by marahml** [comment]
@DeeZone any update on mailchimp list integration? 

@DeeZone @mikefantini if dev on this isn't complete, we should prioritize over the email digest investigation / work. want to make sure users go into the correct list as soon as we can so we don't have to backlog importing.

**Comment by deezone** [comment]
@marahml I'll have this wrapped up for first thing tomorrow.
