### ISSUE TITLE
rb noun/verb translated in hot module but not reportback form

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5213]
I think this will be resolved with some of the work that @weerd is doing, but just want to document here. Assigning to myself for now until after we get some of @weerd's stuff in.

hot module:

![image](https://cloud.githubusercontent.com/assets/6330971/10057739/c5ca558a-620f-11e5-97b3-5fa4dfcb8274.png)

reportback form:

![image](https://cloud.githubusercontent.com/assets/6330971/10057752/d61cbe28-620f-11e5-9480-5c7d00c43596.png)

**Comment by angaither** [comment]
@weerd did this get fixed with your prs today?

**Comment by angaither** [comment]
si, this is bueno!

**Comment by weerd** [comment]
Yep yep!
