### ISSUE TITLE
no campaigns appearing in thor when make filter choices in finder

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5217]
@blisteringherb is seeing this for an anonymous user, but can't replicate the behavior in #5204. The issues he's seeing are related to the fact that there are no en-global translated campaigns for several of the tags. If we switch the default language to 'en-global' it will break the finder, because the initial loading of the finder doesn't make any calls (from what he can tell) to Solr to find out what filters should be disabled. 

@DFurnes it feels like that can't be correct, do you remember how the finder initially hides the tags before the user has interacted with the filter?

Here's what @blisteringherb's seeing
![screen shot 2015-09-23 at 4 35 47 pm](https://cloud.githubusercontent.com/assets/28132/10058027/328cd944-6211-11e5-881d-822cf2411511.png)

**Comment by blisteringherb** [comment]
@DFurnes said that "we just made sure each opt had at least 1 result then let facets handle it from there."  So if we have global english as the default language, we have to have a campaign for each one of the options translated into global english or else we'll get that blank result.

**Comment by mikefantini** [comment]
So big picture this is what should happen:
- I'm located in the US
- I'm an anonymous user
- I should see US English campaigns both on the homepage and when using the finder

I thought that #5154, #5115, #4885, and perhaps #4959 would have accounted for this, but perhaps #5130 and #5183 are needed for this behavior to work properly?

Let's discuss at today's meeting cc: @mshmsh5000

**Comment by mshmsh5000** [comment]
Here's what _does_ happen right now:
- I load the US homepage at https://thor.dosomething.org/us
- I see the US home page
- I see US campaigns when using the finder

When #5183 is implemented, a US user should load https://thor.dosomething.org/, get bounced to https://thor.dosomething.org/us, and see the correct behavior.

**Comment by mikefantini** [comment]
thor.dosomething.org is functioning properly as the Global Homepage/finder now so closing this issue. once #5349 is done, the homepage will be redirecting properly so as a user coming to the homepage from the us will be taking to thor.dosomething.org/us
