### ISSUE TITLE
Migrate to MariaDB RDS from MySQL RDS

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5224]
Matt, quick comparison sheet:

https://docs.google.com/spreadsheets/d/1LrNPUHd8NTQ0u2ODFDoeaRnrp_1PhTFg2tFACUCeWf0/edit#gid=0

**Comment by angaither** [comment]
woah

**Comment by sheyd** [comment]
:jack_o_lantern: Prioritization Pending

**Comment by sheyd** [comment]
@mshmsh5000 ^^

**Comment by mshmsh5000** [comment]
Commented on the doc. Thanks @sheyd!

**Comment by sheyd** [comment]
Testing on Thor successful. Next steps to move user over are:
- [x] Migrate Staging to MariaDB
- [x] Migrate Data WareHouse to MariaDB 10.1 on server
- [x] Migrate Prod to MariaDB RDS
- [ ] Re-setup Data Replication to Data Warehouse from Prod

**Comment by sheyd** [comment]
Upgraded Prod to m3.xlarge instance.

**Comment by sheyd** [comment]
After many painful trials and tribulations, we're back to MySQL through and through here, and are unlikely to migrate to MariaDB at any point soon.
