### ISSUE TITLE
yahoo partner image fact page takeover

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5236]
add the yahoo image on every fact page.
instead of printing the partner logo dynamically, just hardcode the yahoo partner image into the template. 

put this behind a feature flag, so we can turn it on when the partnership launches, and then remove the code later

**Comment by namimody** [comment]
@angaither @sbsmith86 The logo will also need to be hyperlinked to something along the lines of search.yahoo.com [UTM parameter] -- final link coming soon.

**Comment by angaither** [comment]
@namimody is this link with the partner image linked the same as the ones in the google doc, or is this a new link that will be the same across all nodes?

**Comment by namimody** [comment]
@angaither new link that will be the same across all nodes!

**Comment by namimody** [comment]
Shoot @angaither totally my bad on this, apparently, "Powered By Yahoo" on 11 Facts is going to link to search.yahoo.com on desktop, and do.yahoo.com on mobile, both with specific UTM parameters (to come). cc @sbsmith86

**Comment by namimody** [comment]
Hey @sbsmith86! Links below:

Parameter for the Yahoo logo on mobile:
http://do.yahoo.com/?fr=do_dslogo&.tsrc=do-dslogo

Parameter for the Yahoo logo on desktop:
http://search.yahoo.com/?fr=do_dspc&.tsrc=do-dspc
