### ISSUE TITLE
yahoo CTAs

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5237]
we can just [make the google doc into a :js: file](https://docs.google.com/spreadsheets/d/18XMsv8MGZlP1t2gTWumpCdfj24h8yvJHkccSjZ0hfZw/edit#gid=1825152800) with all the links mapped to the node ids

then for each node, find the fact link from the js file
`¯\_(ツ)_/¯`

**Comment by sbsmith86** [comment]
ooo fun.

**Comment by sbsmith86** [comment]
@angaither @namimody 

A couple of questions: 
- Does this mean we are going to be doing the mobile vs desktop CTA title/button on all of these nodes as well?
- If so, does the google doc outline what the mobile CTA should be or the desktop one?

**Comment by angaither** [comment]
AFAIK
- yes
- mobile

only mobile fact pages have the yahoo CTA/button
@namimody correct me if I'm wrong here

**Comment by namimody** [comment]
@angaither your two answers to the above seem right!

One question about your initial issue comment -- not sure if this is is semantics, or code logic, or me being confused -- for each node, wouldn't the code need to find the CTA and search query URL vs. the fact link?

**Comment by sbsmith86** [comment]
@namimody I think it's just semantics, yea for each node, we would find the CTA and yahoo search url for the mobile version of the CTA based on the doc.

**Comment by namimody** [comment]
:+1: thanks for clarifying @sbsmith86!

**Comment by namimody** [comment]
Parameter for 11 facts links:
http://do.yahoo.com/?fr=do_11fcts&.tsrc=do-11fcts&p={SEARCH%20QUERY}

Spreadsheet: https://docs.google.com/spreadsheets/d/18XMsv8MGZlP1t2gTWumpCdfj24h8yvJHkccSjZ0hfZw/edit#gid=1825152800

hiya @sbsmith86 -- links you need above! If you can concatenate in column G (of FINAL sheet) with your mad excel skills, that would be amazing (I'm having a hard time with the %20), but if it's not immediately obvious to you, I'll take another stab.

**Comment by sbsmith86** [comment]
Closing this now since we have the final JSON up.
