### ISSUE TITLE
images missing from homepage on thor

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5246]
as a US user, or an anon user, images are missing from the homepage on thor. 

![screen shot 2015-09-25 at 9 15 30 am](https://cloud.githubusercontent.com/assets/645205/10101316/011f3f54-6366-11e5-9ea5-2efbc8af538f.png)

``` php
 $image_nid = $node->field_image_campaign_cover[$lang_code][0]['target_id'] ?: $node->field_image_campaign_cover[language_default()->language][0]['target_id'];
```

on thor for an anon user that evaluates to 
get image nid in global english, or image id in global english.

it works on stage, because the default language is still english. 

refs #5185

**Comment by angaither** [comment]
I'm not sure what the plan is for setting the default language of our content. 
Should it all be global english? If so, this will be fixed when we migrate that. 
If not, we should fix this to get the image from the node, in the node's default language, not the site's default language.

**Comment by angaither** [comment]
ok, yes. actually shouldn't this always say

```
$image_nid = node's translated image
else
$image_nid = node's original language image
```

cc @blisteringherb @mikefantini

**Comment by angaither** [comment]
ok, yes. actually shouldn't this always say

```
$image_nid = node's translated image
else
$image_nid = node's original language image
```

cc @blisteringherb @mikefantini

**Comment by itsjoekent** [comment]
my normal account has this problem, but just made a new user account for testing something else and the homepage looked fine. weird.

![screen shot 2015-09-25 at 9 47 21 am](https://cloud.githubusercontent.com/assets/897368/10102053/722102a6-636a-11e5-8e76-92a03ae918a9.png)

**Comment by blisteringherb** [comment]
It should probably be the source language for the node since I imagine the first language the node was created in should have an image.

**Comment by angaither** [comment]
Ok, that's what I did in the PR :wink:

**Comment by blisteringherb** [comment]
Whoops, I clicked this link in my email first and didn't see it.
