### ISSUE TITLE
CTAs not appearing on the homepage for anonymous users

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5249]
related to #5246 and #5217 as an anonymous user visiting Thor from the :us: I'm not seeing some CTAs on the homepage

I don't think that the solution we went with in #5246 should perfectly apply here because CTA is a required field, so there _shouldn't be_ any option for a translation to be published without having a CTA. And if we did go the route of #5246 we'd then be pulling in the CTA in the original language (most likely US-English) which wouldn't make sense for a Mexican user to see.

If the campaign doesn't exist at all in a translation that is appropriate for the user (i.e. doesn't exist in Mexican Spanish or Global English) then it shouldn't even be appearing in the finder in the first place.

But maybe I'm missing something.

![image](https://cloud.githubusercontent.com/assets/6330971/10103966/1477535c-6375-11e5-8d7c-584e6b6b684c.png)

cc: @angaither @blisteringherb

**Comment by angaither** [comment]
@mikefantini the code that gets the tagline currently tries to get it from the site's language. 
I think it should only be getting it from the node's lang. 
but yes, if there isn't a translation it probably shouldn't appear on the homepage, but I think that's a different issue.

**Comment by mikefantini** [comment]
right yeah that's a different issue @angaither. I'm just saying that I don't think we need to worry about that use case so much.

instead we should just make sure that the CTA is pulling from the node's language.

**Comment by angaither** [comment]
:+1:

**Comment by mikefantini** [comment]
@angaither should we update the title of the issue to reflect that this should just be about having the CTA pull from the node's language?
