### ISSUE TITLE
Global button classes

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#525]
All "buttons" on the site should have a base `btn` class applied to them. Depending on the situation, "button" here could be defined as:
- `<button>`
- `<a>`
- `<input>`

Depending on how the "button" is being used a modifier class should be applied. This will likely need to happen on a case-by-case basis. Modifiers include: `small`, `medium`, `large` and `secondary`.

**Comment by DFurnes** [comment]
After some consultation with the Drupal crowd – we can tell Drupal to style form buttons with `btn` by setting a default for the theme using `hook_form_alter`. It makes sense to then add `small`, `medium`, etc. using the specific form array if we want to customize it from the defaults.

**Comment by aaronschachter** [comment]
I'd propose defining this `hook_form_alter` inside paraneue_dosomething's template.php (or, better yet -- in paraneue's template file, as part of the starter theme, in case we ever create a separate subtheme).

**Comment by DFurnes** [comment]
+1 Makes sense.

**Comment by barryclark** [comment]
This one might be done already @DFurnes ?
