### ISSUE TITLE
Creating new campaign as MX admin does not set the source language to MX Spanish

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#5250]
Reproduced this on Thor & Staging. 

Create a new MX admin user, role = mx admin, lang = mx spanish

Create a new campaign 

In an admin account, edit that campaign and go to the translate tab. The source language is english. Should be mx.

**Comment by itsjoekent** [comment]
@mikefantini would you say this is high priority?

**Comment by mikefantini** [comment]
@deadlybutter is this happening in thor or just on prod?

**Comment by itsjoekent** [comment]
Reproduced it on thor & staging, I can try prod as well if you want?

**Comment by mikefantini** [comment]
no i just wanted to see if it was happening on thor. thanks

**Comment by itsjoekent** [comment]
related / being solved here: https://github.com/DoSomething/phoenix/issues/5198

**Comment by angaither** [comment]
fixed with #5317
