### ISSUE TITLE
RBs with Reviewed Status But No Reviewer/Source Info in Admin Backend Marked as Pending/0 in (Slave) DB

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5251]
Notes from Shawn RBs:

RBID, SQL status, flagged status | admin backend view

92388, one approved, one pending, 0 | both approved
40958, one approved, one pending, 0 | both approved
92845, one excluded, one pending, 0 | both excluded
92518, one excluded, one pending, 0 | both excluded

Possibilities:
- Admin choices are not being reflected in DB/entirety of Drupal admin backend
- One photo is being reviewed changing the status of the whole RBID on the backend, but because one photo really hasn't been reviewed, status remains as pending
- The second photo is never appearing in the inbox to be reviewed in the first place, but the entire RB status is being changed based on the first being reviewed.

For RB 92518, you can see that the lower photo (marked as pending in SQL) has no information about being excluded, reviewed, or the source below the photo:
![image](https://cloud.githubusercontent.com/assets/12396076/10104494/ec2902f8-6377-11e5-86bd-bc0622682f97.png)

Same occurs for RB 92845, you can see the lower photo (marked as pending in SQL):
![image](https://cloud.githubusercontent.com/assets/12396076/10104518/18d9c094-6378-11e5-9781-f61eb6edf5b8.png)

Same occurs RB 40958: 
![image](https://cloud.githubusercontent.com/assets/12396076/10104571/5cf66d72-6378-11e5-8685-eabb554321cf.png)

and RB 92388: 
![image](https://cloud.githubusercontent.com/assets/12396076/10104599/7d77ee54-6378-11e5-8cb5-3ae156d8af16.png)

**Comment by namimody** [comment]
@mikefantini no joke my phone has no photo space -- next steps for isolating issue below:
- make a new user
- submit a RB
- as an admin, exclude
- submit another RB, don't review
- check SQL for correct logic (excluded // pending // 0)
- check backend view for status of second RB

**Comment by namimody** [comment]
@mikefantini 

select rb.rbid, rbf.fid, rbf.status, rb.quantity, rb.flagged, from_unixtime(rb.created)
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
where rb.nid = ?!?!

**Comment by mikefantini** [comment]
ok so this is as I suspected. not a huge deal. The bug here is that in the http://staging.beta.dosomething.org/admin/reportback/[rbid] view, an unreviewed file will have the radio selection of the file before it pre-populated (i.e. in the photo below, 5387 is still unreviewed and pending, but because 5386 was excluded, "exclude" is being selected in this view. 5387 will still be unreviewed unless the form on /admin/reportback/[rbid] is submitted or the file is separately reviewed in the inbox view.

![image](https://cloud.githubusercontent.com/assets/6330971/10139287/24355b88-65d0-11e5-88f7-9702cd6d4487.png)

marking as low priority.

**Comment by angaither** [comment]
@namimody @mikefantini are we still seeing this issue?

**Comment by namimody** [comment]
@angaither it is still happening, but I think the question now is if we want to fix it or not. It's all technically working, its just that in the particular use case where a member submits multiple photos, not all of them have been reviewed yet, and a campaign lead looks at the /admin/reportback view of a particular reportback, it _appears_ that the unreviewed photos have been reviewed and have the same status as a previously reviewed photos. However, the photo is still in the inbox. I think we leave it -- what are your thoughts? cc @mikefantini
