### ISSUE TITLE
Translation appears to be unpublished but has published status on /translate

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5260]
Edit of the version is unpublished:

![image](https://cloud.githubusercontent.com/assets/6330971/10111218/77c75a12-63a0-11e5-84a2-e72f73fa538b.png)

But appears as published on /translate:

![image](https://cloud.githubusercontent.com/assets/6330971/10111225/8175d3f4-63a0-11e5-8acd-0ce3587fd5c3.png)

**Comment by angaither** [comment]
refs #5180

**Comment by angaither** [comment]
@mikefantini I've tried a couple of times to reproduce this but haven't been able to

I'm translating a published campaign as a regional admin, each time I edit the campaign, I see it created in the translation list, but it isn't published.

**Comment by mikefantini** [comment]
I think we already fixed that they were being auto published with #5158. however I think the weird thing here is that "This translation is published" acts differently than Published status.

With published status, once the box is checked it remains checked until it's unchecked. Thus it serves as an actual status of the state of whether the node is published or not. 

With "This translation is published" the checkbox gets cleared every time, regardless of whether the translation remains published or not. Also because of this, the message "Translation not published" appears next to the checkbox, again regardless of whether the translation is published or not.

Aside from being confusing, this also means that it's impossible to unpublish a previously published translation of a campaign.

Ideally this checkbox would behave the same way the node published status behaves (i.e. is an accurate representation of the current state and is able to be toggled on/off).

**Comment by angaither** [comment]
ah, got it. and just to be sure, regional admins shouldn't see this/be able to publish translations for now, correct?

**Comment by mikefantini** [comment]
correct just administrators and global admins

**Comment by angaither** [comment]
lord

I set the default value of autopublish campaigns to be false

`$form['translation']['status']['#default_value'] = FALSE;` 
but this doesn't take the status into account once it's already been pushlished. 

to get the status, it looks like I'll have to get the URL of the edit form to get the current lang
then check inside deep inside form array and get the status of the translation, and set the default value to that, if it's set, or false if not

... there has to be a setting for not autopublishing translations, but I cannot find it.
