### ISSUE TITLE
Date formats are not passing server side date validation

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#5262]
When registering from a country that is not US, users should enter their birthdays in the `DD/MM/YYYY`. This is passing the client side validation, but is not passing server side validation when the registration form is submitted. 

<img width="417" alt="screen shot 2015-09-25 at 5 03 56 pm" src="https://cloud.githubusercontent.com/assets/1700409/10112241/7ee6b9bc-63a7-11e5-8195-604ee888fd6a.png">

**Comment by angaither** [comment]
might have to switch around the date format after it's passed in `dosomething_user_form_alter`

**Comment by sbsmith86** [comment]
@angaither it looks like I would have to change the format of the date the user passed in in `dosomething_user_register_validate` which is the validation handler, because when `dosomething_user_form_alter` is run it doesn't have the form values. Is that what you meant/sound right to you?

**Comment by angaither** [comment]
@sbsmith86 yes!

**Comment by DFurnes** [comment]
For what it's worth, `DD/MM/YYYY` validation works on the UK international site so there's some code hidden away _somewhere_ that seems to handle this.

**Comment by sbsmith86** [comment]
@DFurnes I **think** that it works on the uk site because there is a date format setting on that field set in the drupal UI. But it would require a feature export to change that on the one site to rule them all and we can't do that conditionally based on country code.

**Comment by DFurnes** [comment]
Oh, gotcha. That makes sense. :grin:

**Comment by sbsmith86** [comment]
@sergii-tkachenko @mshmsh5000 Hey I'm having some issues with this bug and hoping you guys might be able to provide some guidance. 

The issue is that we need to change the date format `field_birthdate` on the user registration form and user profile form. Global users should be using the `DD/MM/YYYY` format and US users should be using `MM/DD/YYYY`. I can not seem to figure out the correct way to do this. I have tried:
- creating a custom `#validation` function for the birthday field that would run before the submit handler is run that would change the format of the date provided so that it can pass validation. But that didn't work.
- creating an `#after_build` function that manipulates the date format of that field for global users. This works, but seems hacky. 

It seems what I need is a way to change the date entry settings on that field based on country code: 

![screen shot 2015-09-30 at 5 03 58 pm](https://cloud.githubusercontent.com/assets/1700409/10206660/06c02494-6796-11e5-9b04-f03ce0f865a1.png)

But I don't know how to do this. Or, is there some other solution that I am not considering?

**Comment by mshmsh5000** [comment]
It seems that we're better off creating our own validation routine and just using that. The [Phone module](https://www.drupal.org/project/phone) ships with its own list of countries and validation patterns, and has an implementation like this:

```
function phone_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (isset($item['value']) && $item['value'] != '') {
      $ccode = $field['settings']['country'];
      $value = $item['value'];
      if (!valid_phone_number($ccode, $value)) {
        $country = phone_country_info($ccode);
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'phone_invalid_number',
          'message' => t($country['error'], array('%value' => $value)),
        );
      }
    }
  }
}
```

**Comment by sbsmith86** [comment]
@mshmsh5000 Thanks for your help on this!! Right now that field is using a `date_text` widget which I think is what is causing the date module to invoke it's own validation. In order for a custom validation routine to work, would I have to switch the field to just be a regular text field?
