### ISSUE TITLE
Thor: Registration doesn't pass country code to Northstar

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5263]
For a Sena's test user (See @sheyd for details), which was a BR user, he received the PT-BR confirmation transactional. But the user data recorded in Northstar has no country at all.

May be incomplete data passed to NS, or NS not recording data we passed. Calling it a Phoenix issue until we determine otherwise.

**Comment by angaither** [comment]
NS attempts to [get the country from the address field](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_northstar/dosomething_northstar.module#L164)
we've disabled that field for non-us users. we need to save that in the `dosomething_user.module`

we currently have a [conditional that fires on a new user to set the user's language.](https://github.com/DoSomething/phoenix/blob/a6944b7444172f0e5119e8a9754e87a0a96406cb/lib/modules/dosomething/dosomething_user/dosomething_user.module#L467-L476)
this country save should be done in a similar way, and perhaps these two should be grouped together in their own function. `dosomething_user_set_new_user_global_attributes`

**Comment by itsjoekent** [comment]
@chloealee wanna hold off on this one real quick while I fix-up #5168 and make that function?

**Comment by itsjoekent** [comment]
@chloealee this is unblocked :D see the PR above for the function where we gotta add northstar support

**Comment by chloealee** [comment]
great, thanks @deadlybutter ! Super helpful to get started on this :)

**Comment by angaither** [comment]
reopening to deal with sending the entire address, along with the country code
