### ISSUE TITLE
DS-Build Command URL Update

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5264]
Please see spreadsheet for details.

[DS-Build-Update-Issue.xlsx](https://github.com/DoSomething/phoenix/files/2761/DS-Build-Update-Issue.xlsx)

**Comment by mshmsh5000** [comment]
Summarized here:

> Update ds-build/pull/Vagrant command to point to something other than staging.beta.dosomething.org

Actually, that's the whole description.

**Comment by mshmsh5000** [comment]
stagingdata.dosomething.org

**Comment by mshmsh5000** [comment]
Addressed in DoSomething/ansible-dosomething#35

**Comment by mshmsh5000** [comment]
https://github.com/DoSomething/ansible-dosomething/pull/36
