### ISSUE TITLE
Remove excess dosomething_northstar files from docroot

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5267]
In the project root:

```
$ ls -lA | grep northstar
-rw-r--r--   1 mholford  staff    4096 Sep 18 13:52 ._dosomething_northstar.install
-rw-r--r--   1 mholford  staff     327 Sep 18 13:52 dosomething_northstar.install
```

There's no `.install` file in the Northstar module itself, so first we need to determine whether this is supposed to be there. Then clean up the files.

**Comment by angaither** [comment]
ahh, yeah we need that to install custom northstar cache, just need to move it to the correct location `lib/modules/dosomething/dosomething_northstar/dosomething_northstar.install`

we can remove the `._dosomething.northstar.install` file
