### ISSUE TITLE
Unable to make new users from /admin/people

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#5277]
On Thor. Creating a new user from /admin/people/ refreshes the page and does not appear to create the user (unable to login). Debugged with @sheyd and the request is going through in the logs so it seems to be a code issue.

**Comment by itsjoekent** [comment]
@mikefantini what priority is this?

**Comment by angaither** [comment]
@deadlybutter can you provide more details? what kind of user were you? what was the submit button url pointing to?

**Comment by itsjoekent** [comment]
EDIT: never mind i was switching between issues im an idiot. updating OP now

**Comment by itsjoekent** [comment]
And now its not happening, the fuck
