### ISSUE TITLE
en-global path prefix should be blank

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5278]
Reverting the global feature keeps settings this path prefix back to "en-global", but it should be blank.

![en-global-prefix](https://cloud.githubusercontent.com/assets/149811/10146000/7e986ec0-65f4-11e5-8198-6b83f9d71434.png)

**Comment by mshmsh5000** [comment]
https://github.com/DoSomething/phoenix/blob/global/lib/modules/dosomething/dosomething_global/dosomething_global.strongarm.inc#L78

This should be 

```
'prefix' => '',
```

**Comment by sergiitk** [comment]
@mshmsh5000 As I understand from https://thor.dosomething.org/admin/config/regional/language/edit/en, English language prefix should also be set to `us`, right?

**Comment by mshmsh5000** [comment]
That looks right:
- US English prefix: `us`
- Global English prefix: [blank]

**Comment by sergiitk** [comment]
Done: https://github.com/DoSomething/phoenix/pull/5310/files

**Comment by angaither** [comment]
@sergii-tkachenko can we close this issue?

**Comment by sergiitk** [comment]
Yes!
![image](https://cloud.githubusercontent.com/assets/672669/10234034/c9032ae2-689a-11e5-8aef-cb4b49833faf.png)
![image](https://cloud.githubusercontent.com/assets/672669/10234045/d07a3fa4-689a-11e5-801b-0de2ffba3caf.png)
