### ISSUE TITLE
translate taxonomy

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5280]
#### For sure translate this:
- [ ] action type
- [ ] cause
#### Maybe we don't need this:
- [ ] image tags
- [ ] issue
- [ ] kudos
#### Def don't need to translate this:
- [ ] partner
#### How to enable:
1. turn on i18n_taxonomy
2. profit

**Comment by angaither** [comment]
looks like entity_translate module also handles this
http://dev.dosomething.org:8888/admin/config/regional/entity_translation
http://nielsdefeyter.nl/archive/2014/setup-entity-translation-right-way

**Comment by weerd** [comment]
Some additional info: https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_set_message/7

**Comment by mshmsh5000** [comment]
We need to confirm whether user-facing taxonomy terms (e.g., for Campaign Finder) get handled by PO-level translation.

**Comment by weerd** [comment]
@mshmsh5000 yep yep, I need to look into it cause there are some other areas where we have JS related string output that should otherwise be translated in a similar fashion to the above.
