### ISSUE TITLE
Incorrect logout link for BR user

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#5283]
When logged in as a Brazilian user, this is the logout link

https://files.slack.com/files-pri/T024GV2BW-F0BESA4J1/screen_shot_2015-09-28_at_4.11.38_pm.png

/bruser/logout

**Comment by mikefantini** [comment]
needs to be updated to be /br/user/logout. happening for US, MX, and BR

to recreate:
- log in as a user w/ MX SP set as language
- go to thor.dosomething.org/mx
- try to log out

**Comment by itsjoekent** [comment]
@angaither I said at standup I was working on this one / was making progress, any reason you switched assignee?

**Comment by itsjoekent** [comment]
fixed on thor/global branch ^^
