### ISSUE TITLE
Some Finder Results Point to www.

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5284]
As a global user, filter by environment, Veggie Surprise shows up and points to www.

**Comment by mikefantini** [comment]
@sheyd @blisteringherb can we close this out? seems to be working now. was work done to resolve this?

cc: @namimody

**Comment by sheyd** [comment]
@mikefantini @namimody Yes. @blisteringherb re-indexed the site in search, and it worked after that.
