### ISSUE TITLE
MX & BR: SIGNUP EMAIL: Merge tags are pulling in GL content

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5285]
Merge tags for MX Signup Email should pull in merge tags for MX content. 

![image](https://cloud.githubusercontent.com/assets/6784628/10147942/d9c0bbc2-65fe-11e5-8ede-c446c92ee186.png)

**Comment by mikefantini** [comment]
let's hold on this until #5282 is completed because fixing this may resolve the issue
