### ISSUE TITLE
Create Redirect from /mx/campaigns to /mx/campanas (tilda) (?)

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5287]
Did not spell Mexican version of campaigns right, but we need to set up a redirect from /mx/campaigns to that URL.

**Comment by mikefantini** [comment]
we'll also need on for /br/campaigns to whatever we decide that should be.

we also should make sure that /us/campaigns is being linked to properly from user reg and reportback emails @namimody

**Comment by namimody** [comment]
[added to QA sheet @mikefantini!]

**Comment by mikefantini** [comment]
this will probably be one of the last issues we close out for this milestone as I want to make sure everything else is working before we add this in

**Comment by mikefantini** [comment]
closed and added to #5457
