### ISSUE TITLE
GL: PW RESET: Password reset emails sending incorrect template

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5289]
PW reset email triggers "empty" signup email: 
![image](https://cloud.githubusercontent.com/assets/6784628/10148111/c0fd0ab8-65ff-11e5-8167-19edf2121871.png)

**Comment by deezone** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/2119264/10170453/f29c8d8e-66a2-11e5-9ef0-cad7eded8fac.png)

**Comment by marahml** [comment]
@ArielSD is this email not on the new template?

**Comment by deezone** [comment]
@marahml Please take note of the test user -> CZ (Check Republic) thus a "global user" thus a US template.

Below is a signup for a Brazilian user (thus the new registration template).

![image](https://cloud.githubusercontent.com/assets/2119264/10198642/e2528adc-676a-11e5-9dc6-3ef8e16539bf.png)
