### ISSUE TITLE
GL + MX + BR design for ALL transactional emails: Update templates

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5290]
Global + Mexico + Brazilian transactional emails need updated to: 
- [x] Correct width of the email
- [x] Remove Ben's face from signup email AND report back email (it's redundant, because he's already in the user registration email. His picture should only be on the new user registration email) 
- [x] Add Ben's face to `mb-user-register-us`
- [x] Remove Ben's face from any password reset emails
- [x] Remove sidebar text from any email that doesn't have Ben's photo

New U.S./Global Templates:
- [x] https://us4.admin.mailchimp.com/templates/edit?id=56653 (New User Register)
- [x] https://us4.admin.mailchimp.com/templates/edit?id=56657 (Campaign Sign Up)
- [x] https://us4.admin.mailchimp.com/templates/edit?id=56661 (Reportback)
- [x] https://us4.admin.mailchimp.com/templates/edit?id=56669 (Password Reset)

Testing:
- [ ] Formatting for U.S. New User Register isn't showing in gmail.

**Comment by angaither** [comment]
@weerd or @sbsmith86 or @DFurnes there's 12 templates to look at, it'll probably take 1/2 day.

**Comment by sbsmith86** [comment]
@angaither sorry, what templates?

**Comment by angaither** [comment]
@sbsmith86 @ArielSD has email templates that he needs help getting updated

**Comment by sbsmith86** [comment]
@weerd Hey! So i need to I need to update these [mailchimp templates to](https://us4.admin.mailchimp.com/templates/) to the  "Correct width of the email". @ArielSD Thought you  might have some insight as to what the correct width of the email template should be. Any insight you can provide?

**Comment by weerd** [comment]
Not sure how much insight I can provide... I had taken a quick look with @ArielSD to see if I could make some suggestions for how to fix things. The code is a bit convoluted because I think a "responsive" mailchimp theme was used, but set to be `600px` fixed width... So there's a lot of media query based code that actually doesn't apply, etc. From what I can tell from taking a quick gander at the code, the fixed width size is the `600px`, but not sure how that all relates to the padding, etc.

cc: @DeeZone might have some further insight?

**Comment by deezone** [comment]
@weerd Me, know anything about responsive... in my dreams!

**Comment by weerd** [comment]
@DeeZone lol. Meant more about info on the template: size, width, etc :)

**Comment by marahml** [comment]
hi @weerd! we experienced the same issue a long long time ago and I think you helped us figure out a similar solution. per your note above, we think that we need to be able to configure the template to size based on a % instead of set width. do you have thoughts on how do that?

**Comment by sbsmith86** [comment]
@marahml Hey! I think im just confused as to what the current issue is with the templates and that will help me narrow down the fix. Is it that the section with ben's picture is too wide? Is it that they are not responsive on mobile? See screenshots below:

![screen shot 2015-10-06 at 10 41 13 am](https://cloud.githubusercontent.com/assets/1700409/10311942/f4df2506-6c16-11e5-8bdc-1b44067d3ff8.png)

![screen shot 2015-10-06 at 10 43 05 am](https://cloud.githubusercontent.com/assets/1700409/10311982/1cc1f53a-6c17-11e5-9942-a403cfaf5c06.png)

**Comment by marahml** [comment]
ah got it. thanks @sbsmith86! 

Hmm I'm not sure either, but looking at this, it could be 1) Ben's photo or 2) that "help@dosomething.org" is too long of string for that sidebar.

**Comment by sbsmith86** [comment]
Documenting this here:  I’ve finished updating the `mb-user-xxxx-br/mx` and the `mb-campaign-xxxx-br/mx` mailchimp templates. There were 8 of them (4 for each country). 

Looked over the US templates and they look good except for the fact that they don't have the image in the header, instead they just have a purple background. Not sure if this is on purpose of if I should update these templates to use the image. I will I will leave the issue open until we confirm either way.

@marahml @ArielSD  /cc @angaither

**Comment by sbsmith86** [comment]
@ArielSD all these templates should be updated now. I didn't see any sidebar text without ben's photo but let me know if there are any other updates needed!

**Comment by mikefantini** [comment]
sorry @sbsmith86 when you say all templates should be updated now do you mean that you updated US transactionals to include the image header, Ben's photo, etc.?

**Comment by sbsmith86** [comment]
@mikefantini Yea. @ArielSD made new US/Global templates that have the image header and ben's photo (registration email only). I made some style and html updates to the templates so that they looked correct and worked responsively. From what I understand, these templates are not live yet, so the old US/global templates (purple header, no ben, etc) are still being used, but they are looking to replace those with the new ones once they are ready.

**Comment by marahml** [comment]
That's right Shae. Thank you for reformatting! When Dee's back on monday we'll push these live for US + GL.

**Comment by ArielSD** [comment]
Thanks so much, Shae!

**Comment by deezone** [comment]
@marahml @ArielSD The update can be "pushed" from the MailChimp templates to Mandrill. No need for my involvement.

**Comment by marahml** [comment]
great thanks @DeeZone. just wanted to wait until you were back in case anything goes wrong. @ArielSD , go for it!

**Comment by marahml** [comment]
@ArielSD once you update and test templates, just update us here so we can know if we can close this or not. thanks!

**Comment by sbsmith86** [comment]
@marahml I think I'm going to go ahead and close this issue. The only problem we were seeing in terms of formatting was that in gmail some of the styles were not taking. @ArielSD made a new issue to address that, #5444 . I have done some work to fix it and will document where we are at in that issue.
