### ISSUE TITLE
GL + BR + MX: REPORT BACK email: should link to country-specific /campaigns

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5293]
Right now, incorrect merge tag is configured for "Tackle Another Campaign" button in report back emails.

Should point to /campaigns for whatever country user is coming from.

**Comment by mikefantini** [comment]
yeah should be /mx/campaigns or /br/campaigns and then we'll do work with #5287 to make sure they end up at the right place for now

**Comment by mikefantini** [comment]
and ideally we future proof this for when we have more languages in the site in the future

related to #5294 and #5295

**Comment by mikefantini** [comment]
also reportback emails from thor are currently linking to prod, they should link to the environment from which they were generated

**Comment by deezone** [comment]
@mikefantini How important is the link to the related environment vs always pointing to production? This will require a nontrivial tech build (one day).

**Comment by blisteringherb** [comment]
I've fixed these links to add the prefix, but since they were pointing at /campaigns which is the global link, the user should be redirected.

**Comment by mikefantini** [comment]
oh yeah good call @blisteringherb 

@DeeZone I defer to @mshmsh5000 on that question. if it has to be just one environment let's keep it production.

**Comment by mshmsh5000** [comment]
@DeeZone @mikefantini Let's keep the references to production, then.

**Comment by mshmsh5000** [comment]
@marahml @blisteringherb @DeeZone Can we close this out?

**Comment by deezone** [comment]
@blisteringherb 's call... I suspect yes.

**Comment by blisteringherb** [comment]
I just verified that this is working now. You'll probably get a 404 through because production doesn't yet respect URLs with the country prefixes.
