### ISSUE TITLE
MX + BR USER REG email: "Sign up" link points to malformed link

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5295]
"Sign up" link is pointing to a malformed link. Should point to /campaigns based on country the user is coming from.

**Comment by mikefantini** [comment]
@marahml this should be for user reg emails correct?

Sign Up is the prompt in user reg emails, it's Prove It for campaign sign up emails.

and yeah let's have this point to /mx/campaigns or /br/campaigns. we'll then need to create redirects once we decide on what this final url should be refs #5287

**Comment by marahml** [comment]
ah yea! just updated

**Comment by deezone** [comment]
Updated related templates to point to:
- https://www.dosomething.org/br/campaigns
- https://www.dosomething.org/mx/campaigns
