### ISSUE TITLE
In Thor Nginx 404 Page is Intermittently Shown Instead of Drupal 404

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5298]
Sample URI that gives Nginx 404:

https://thor.dosomething.org/mx/campanas/ole-andrea-mexico

**Comment by sheyd** [comment]
Figured out the issue here. We have to add a "error_page 404 /thispageissomethingwrong.php" directive to the `listen /` sub-section. Setting this up in Tower. Will cross-link the PR.

**Comment by sheyd** [comment]
Deployed to Prod.

**Comment by sergiitk** [comment]
@sheyd Can you deploy this to Thor as well? The error is still there.

**Comment by sheyd** [comment]
@sergii-tkachenko The deploy was there first. I don't get any Nginx 404 pages. Which page did you run into the error on?

**Comment by sheyd** [comment]
Nevermind, error is now recurring whenever I test. Re-opening ticket.

**Comment by angaither** [comment]
I'm not seeing this error any more
