### ISSUE TITLE
Track Down Any Missing Users from MailChimp Outage

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5299]
For the date range of 9/22/15@9:58AM - 9/25/15@6:15PM, extract from their original sources and cross-compare the following:
- [x] All Mobile Commons User Registrations
- [x] All MailChimp User Registrations
- [x] All Northstar User Registrations
- [x] All Drupal User Registrations
- [x] All Queued Users in RabbitMQ

**Comment by sheyd** [comment]
- Mongo Query: `db.users.count({"created_at": {"$gte": ISODate("2015-09-22T05:58:00Z"), "$lt": ISODate("2015-09-25T14:15:00Z")}})`
- Drupal Query: `select * from users where created between unix_timestamp("2015-09-22 05:58:00") and unix_timestamp("2015-09-25 14:15:00")`
- Data Warehouse Query (For Mobile Commons numbers): `select * from mobile_users where (created_at between '2015-09-22 05:58:00' AND '2015-09-25 14:15:00') AND (status='Active Subscriber')`

**Comment by sheyd** [comment]
Current numbers:

Northstar: 1992
Drupal: 1825
Mobile Commons: 3057

MailChimp shows significant drop-off to subscriptions during that time range.

**Comment by sheyd** [comment]
@DeeZone @mshmsh5000 Uncle Mike has approved processing the existing queue, since our numbers match up closely to the backlog. Please make sure the MailChimp null valued queued subscribers get assigned to MailChimp list-id: f2fab1dfd4

**Comment by deezone** [comment]
@sheyd Roger!

**Comment by sheyd** [comment]
@DeeZone When the user imports are finished, can you re-assign this ticket to me? I'm going to do a final numbers count to make sure we're consistent across the board.

**Comment by deezone** [comment]
Finished processing the `userRegistrationQueue`. MailChimp should be up to date.

**Comment by sheyd** [comment]
User import count confirmed.
