### ISSUE TITLE
Awesome Things module

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#530]
## Awesome Things

Herein lies a proposal to name `dosomething_general.module` **awesome_things**.
### Cultural Relevancy

Our Awesome Things menu was a symptom of a lot of the issues this very rebuild is endeavoring to address. This module name ensures that it will be gone but not forgotten.
### Ease of Access

As all of our other modules are prefaced with `dosomething_` having our general library named Awesome Things will ensure that it is at the top of the directory list every time. That assists tab completion, too!
### Semantics

Any library of helper functions is destined to be a junk drawer of sorts. Here at Do Something, we refer to those collections as "awesome things."

As an alternative, I am also a fan of `dosomething_fuckit.module`.

**Comment by aaronschachter** [comment]
I recently thought of the names "dosomething_sitewide" or "dosomething_global".  But... I still like "dosomething_fuckit" quite a bit.  I think it would make sense to talk through out what kind of functions we need to put in here, possibly in person at retrospective this afternoon.

**Comment by deezone** [comment]
The long name space "function dosomething_awesome_things_<name>()" should also weed out the laziness in us. We could also give a nod to Mike with dosomething_crazyshit

**Comment by DFurnes** [comment]
`dosomething_any_cause_anytime_anywhere_mic_drop_` COME ON GUYS GET ON BRAND

**Comment by aaronschachter** [comment]
Sad to say `dosomething_fuckit` didn't make the cut but that'll be for some future shit we build. `dosomething_helpers` module is alive and well and closes this issue.
