### ISSUE TITLE
need a view of which content is translated into which language

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5300]
Goal is to be able to see all campaign and static content and the status of what language that content exists in.

bonus points if we can group it by content type. also if doing two different content types is too complex, let's just stick with campaign content.

| NID | TRANSLATE | US EN | GL EN | BR PT | MX SP |
| --- | --- | --- | --- | --- | --- |
| 32 | [13 Gallon Challenge](https://thor.dosomething.org/node/32/translate) | Published | Not translated | Not translated | Not published |
| 5459 | [GTFO](https://thor.dosomething.org/node/5459/translate) | Published | Published | Published | Published |
| 5626 | [Editor Created Test](https://thor.dosomething.org/node/5626/translate) | Not published | Published | Not Published | Not Published |

maybe this could be a new tab on /admin/content as "Translation Status"

only administrators and Global Admins should have access to this

**Comment by itsjoekent** [comment]
sorry @mikefantini just to confirm, do you want two tables, one for campaigns and one for static content? or one table but a filter mechanism?

**Comment by deadlybutter** [comment]
also as far as Im aware, there is no way to publish/unpublish a translation. I can check if the translation exists or if the campaign is active/closed in that translation.

**Comment by angaither** [comment]
@deadlybutter let's just stick with one table and an exposed filter in the view

**Comment by itsjoekent** [comment]
gotcha

**Comment by angaither** [comment]
@mikefantini this is a little complex to get exactly like what you have mocked out, but @deadlybutter and I came up with something similar.
@deadlybutter is going to throw up screenshots of what he has, and we can evaluate what we can change to make it more helpful

**Comment by itsjoekent** [comment]
ill put the v1 screenshots in the PR. for vlater this is all the complex logic we'll need 

https://github.com/deadlybutter/dosomething/commit/c696f0cb6e3012db66e81e116c3042a20b5e70b9

**Comment by itsjoekent** [comment]
Going to hop back on this one, will have a PR / screenshots in the afternoon so @mikefantini can approve its ok enough to ship
