### ISSUE TITLE
Translated content is shown as cached arrays

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5302]
to recreate go to https://thor.dosomething.org/mx/node/2070 as a user with language set as MX SP.

you'll see something like this:

![image](https://cloud.githubusercontent.com/assets/6330971/10166778/886d7b3a-6693-11e5-81ac-54c4325970d9.png)

even though:
- "Bzzzinga! Esto es lo que necesita saber para crear sus bandas abejorros." should be the campaign starter statement - nothing showing
- "Averiguar donde plantar las flores. Usted puede comenzar un jardín de abejas cualquier lugar donde haya tierra - en su patio trasero, en la escuela, o puede Bee-ify un jardín ya existente." should be the Time and Place - but "Array" is showing

**Comment by mikefantini** [comment]
... and flushing all cache fixed it

**Comment by mikefantini** [comment]
@angaither @weerd @blisteringherb any thought on why we would need to clear cache here? and is this something we'll need to do regularly as translations happen on an ongoing basis?

**Comment by weerd** [comment]
I definitely had to do some cache clearing post-importing POEditor .po file into Droops.

**Comment by angaither** [comment]
yeah, the content is grabbed in the theme layer in droops, so it's cached
shouldn't be an issues once the translations are created, but when we're updating them frequently we will probably see this

**Comment by mikefantini** [comment]
@angaither is there a v1.1 issue we can create to address this problem? it's definitely possible that some are updated pretty regularly before they are launched (and potentially after they are launched)

**Comment by angaither** [comment]
@mikefantini yeah, let's just move this issue to that milestone for now

**Comment by mikefantini** [comment]
hmmm seeing this again on https://thor.dosomething.org/mx/node/3534/edit this time.

flushed cache but the problem still persists. let's definitely keep an eye on this

**Comment by mikefantini** [comment]
Backend of https://thor.dosomething.org/mx/node/2535/edit and https://thor.dosomething.org/br/voluntario/veggie-surprise filled out, but no copy shows on front end. Content working correctly for English and Global English.

**Comment by weerd** [comment]
Resaving the campaign from within the `/edit` view in the admin seems to properly poke Droops so that the content outputs correctly. :grimacing:

**Comment by mikefantini** [comment]
Hmmm ok. So this may just be an issue when we use @blisteringherb's Google Translate script. Obviously we won't be doing this in production, so I'm going to keep this open for now until we get campaign content translated in prod. If all of that looks ok, then I'll close this out.

**Comment by weerd** [comment]
:dancer: ¡OLÉ!

**Comment by mikefantini** [comment]
This is the only page on thor I'm now seeing this on:

https://thor.dosomething.org/mx/sobre/preguntas-frequentes

![image](https://cloud.githubusercontent.com/assets/6330971/11044703/71356d8c-86f1-11e5-8b7e-88dad863b9cd.png)

**Comment by mikefantini** [comment]
And clearing cache isn't resolving it.

@angaither @weerd either of you have any thoughts?

**Comment by mikefantini** [comment]
Technically we can launch without an FAQs page I guess. Keeping this in 1.0 but removing the blocker label.

**Comment by angaither** [comment]
looks like the issue is with the `additional_text` field on the node. 
the content is getting returned like this:

![image](https://cloud.githubusercontent.com/assets/645205/11094722/58f0cab8-885f-11e5-8657-104edee58b9e.png)

other content is returning fine, because it doesn't have the different formats. 

...not sure why this isn't broken on prod, or when this changed

cc @blisteringherb @sergii-tkachenko

**Comment by sergiitk** [comment]
@angaither I have seen it before. Here's how we should handle the display: https://github.com/DoSomething/phoenix/blob/68eab581dfa94ee91c645fe765586ba7a0491251/lib/modules/dosomething/dosomething_static_content/dosomething_static_content.module#L48-L54

**Comment by angaither** [comment]
@sergii-tkachenko yeah, I swapped it to formatted text, and it's a fatal error

**Comment by weerd** [comment]
You could try running the field through my extraction function to grab stuff properly:

https://github.com/DoSomething/phoenix/blob/68eab581dfa94ee91c645fe765586ba7a0491251/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L105

**Comment by angaither** [comment]
...but that must have been cache, cause I cleared cache, and now it works fine as a formatted text field

**Comment by mikefantini** [comment]
Because this effects the solution for #5745 (which we can now close), we'll actually need to fix this before launching. Re-adding blocker.
