### ISSUE TITLE
inconsistent URLs in finder results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5303]
when i got to thor.dosomething.org/mx and filter by Environment I get a range of URLs for the campaigns. These include:
- https://thor.dosomething.org/mx/voluntario/gtfo-mx
- https://thor.dosomething.org/mx/campaigns/meatless-mondays (for Lunes Sin Carne)
- https://thor.dosomething.org/mx/node/819 (for Bombs Away Semilla)

cc: @mshmsh5000 not sure if any of the work you're doing on URLs will address this or if you have any thoughts on what may be happening here

**Comment by mikefantini** [comment]
i'll delete these aliases, resave the nodes so better aliases get generated, reindex solr, clear drupal cache

**Comment by blisteringherb** [comment]
I went through and ran the bulk update and reindexing yesterday and these seem to have been resolved. When I went to do the delete and bulk update there were only about 5500 aliases, and after recreating the aliases there are around 22k. When the homepage loads, the URLs are still incorrect (missing the prefix) but when you use the finder the URLs are correct.

**Comment by angaither** [comment]
@mikefantini confirm that this is fixed and close out

**Comment by mikefantini** [comment]
urls from finder results look good to me. and I'm also seeing the proper prefix when the homepage loads.
