### ISSUE TITLE
Issues with the reportback-items API endpoint on staging servers

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5319]
Depending on which staging url we direct the request to, the response is either a 503 error or slow enough (~40s) to timeout the connection on the client-side (ex: mobile app).
### staging.dosomething

**Request:** GET http://staging.dosomething.org/api/v1/reportback-items.json

**Response:**

```
Error 503 backend read error

backend read error

Guru Mediation:

Details: cache-iad2123-IAD 1443623243 365296685

Varnish cache server
```
### staging.beta.dosomething

**Request:** GET http://staging.beta.dosomething.org/api/v1/reportback-items.json

**Response:** The response is correct. The response time though is ~40s which currently times out connections on the mobile app.
### More notes
- Both http://staging.beta.dosomething.org/api/v1/campaigns.json and http://staging.dosomething.org/api/v1/campaigns.json work and respond quickly
- Part of the `/reportback-items` endpoint's response is a user object like...

```
"user": {
  "id": "55bcf222469c64a31f8f5555",
  "first_name": "Ansley",
  "last_name": "Something",
  "photo": "<some url on AWS or null>",
  "country": "<some country code or null>"
}
```

  If I'm remembering correctly, Phoenix may be making requests back to Northstar to get this information... oh, yep, pretty sure it is. Not sure if that has anything to do with the issues: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php#L119

**Comment by jonuy** [comment]
Also worth mentioning, the image uri's that come back in the staging.beta response return 404s.

ex:
Response from the staging.beta reportback-items request...

```
{
  "id": "22682",
  ...
  "media": {
    "uri": "http://staging.beta.dosomething.org/sites/default/files/styles/480x480/public/reportbacks/2930/uid_1835306-nid_2930-0.jpg?itok=-Vrp73yB",
    "type": "image"
  },
```

And then we pull this out to try to get the photo to display:
http://staging.beta.dosomething.org/sites/default/files/styles/480x480/public/reportbacks/2930/uid_1835306-nid_2930-0.jpg?itok=-Vrp73yB

**Comment by sheyd** [comment]
@jonuy Not sure why the images are 404'ing, but the API responses are back to normal now that the DB switch is back to normal on staging. 

I'll investigate the image 404's a bit more.

**Comment by jonuy** [comment]
@sheyd It's probably not worth investigating the 404 anymore. After switching the DB back, the uri's in the responses when querying now look like they're good.

**Comment by sheyd** [comment]
Roger.
