### ISSUE TITLE
Yahoo CTA Bug with pulling JSON from gist

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#5321]
## Once upon a time not long ago...

We implemented the Yahoo CTA functionality to pull JSON with CTA data from rawgit.com so if data changed we didn't have to do a code deploy each time the data updated. In order to further accommodate changes in the data, we use the dev/testing url rawgit provides to pull the JSON because the prod url they provide is cached permanently and changes to the JSON wouldn't be reflected. 
## What happened next :question: :exclamation:

Rawgit be maaadddddd. Because we are using the test url on production, rawgit.com is sending us 503 errors on our http request to get the JSON, breaking the whole damn yahoo experience. 
## Happily ever after..

Going to go back to hosting the file ourselves so we don't have to deal with this. Changes to the data are not expected anymore and if it does, we will just have to do a code deploy.

**Comment by DFurnes** [comment]
:100: Nice issue documentation!
