### ISSUE TITLE
Edit Tab on Published or Unpublished Campaign Runs Inaccessible

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5326]
Sample URL:
https://www.dosomething.org/node/5429/edit (logged in as admin)

Output from web-server logs for request:

Oct  1 10:17:37 ip-10-100-35-11 drupal: https://www.dosomething.org|1443709057|php|23.235.46.29|https://www.dosomething.org/node/5429/edit%7Chttps://www.dosomething.org/node/5356/edit%7C1193105%7C%7CRecoverable||0||Notice: Trying to get property of non-object in dosomething_user_init() (line 49 of /var/www/www.dosomething.org/releases/20150930202159/lib/modules/dosomething/dosomething_user/dosomething_user.module).
Oct  1 10:17:37 ip-10-100-35-11 drupal: https://www.dosomething.org|1443709057|access denied|23.235.46.29|https://www.dosomething.org/node/5429/edit%7Chttps://www.dosomething.org/node/5356/edit%7C1193105%7C%7CRecoverable||0||node/5429/edit|https://www.dosomething.org/node/5356/edit|1193105||Recoverable
Oct  1 10:17:37 ip-10-100-35-11 drupal: https://www.dosomething.org|1443709057|php|23.235.46.29|https://www.dosomething.org/node/5429/edit%7Chttps://www.dosomething.org/node/5356/edit%7C1193105%7C%7CRecoverable||0||Notice: Undefined index: country in dosomething_global_get_countries() (line 193 of /var/www/www.dosomething.org/releases/20150930202159/lib/modules/dosomething/dosomething_global/dosomething_global.module).

**Comment by itsjoekent** [comment]
happening on thor as well, seems to be a bug

**Comment by angaither** [comment]
fun fact this one works... https://www.dosomething.org/node/5828/edit

**Comment by namimody** [comment]
A couple of additions:

-- seems that Lizzy tried to access the /edit of a campaign and saw the same error, but then shortly after was able to access the /edit tab
-- based on this list (https://www.dosomething.org/admin/content/search?title=&type=campaign_run&field_cause_tid=All&status=All) the /edit of the last three runs created _can_ be accessed, but nothing prior

**Comment by itsjoekent** [comment]
Only happening on Thor and Prod, not happening on staging or local. 

On Thor its for everything im trying on: https://thor.dosomething.org/admin/content

On Prod its not happening for any of the latest ones here: https://www.dosomething.org/admin/content

**Comment by itsjoekent** [comment]
@mikefantini talked with @sheyd -- can we pause this until we update the Thor DB with the latest snapshot? we think its related

**Comment by mikefantini** [comment]
@deadlybutter even though it's also happening on prod?

**Comment by itsjoekent** [comment]
its not always happening on prod, if you click on the most recent campaign runs /edit works fine

**Comment by mikefantini** [comment]
@deadlybutter once you knock out your Global 1.0 issues can you please take a look at this one now that thor has production db again?

cc: @namimody @angaither
