### ISSUE TITLE
Mailchimp Environmental Variables

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#5327]
We're going to be deploying the mobile app splash page and we need to make sure these two variables are populated. I have the list ID and assume the User ID is our API key.

```
<form class="email-signup" action="//dosomething.us4.list-manage.com/subscribe/post?u={{ site.mailchimp.user-id }}&amp;id={{ site.mailchimp.list-id }}" method="post" novalidate>
```

**Comment by DFurnes** [comment]
@lkpttn You can just hard-code these in your splash page. No need for environment variables!

**Comment by sheyd** [comment]
@DFurnes hard-code BAD!! :no_good: It's better to have as an env variable so it's not in a public repo.

**Comment by DFurnes** [comment]
They're just going to be output into a plain HTML tag. There's nothing "secret" about them.

**Comment by angaither** [comment]
![](https://s-media-cache-ak0.pinimg.com/originals/60/79/c0/6079c08f756963bf22ab4f456508371f.jpg)

**Comment by sheyd** [comment]
@DFurnes is :100: smart on this. Info isn't any sort of disclosure. Talked to @lkpttn as well. 

@angaither I think it's best if this lives in Phoenix repo, but can be persuaded to put it elsewhere. Your thoughts on best location? (We can still put it as resolveable to ds.org without it being part of Phoenix).

**Comment by angaither** [comment]
it's just a one page app, right? doesn't @lkpttn have it living elsewhere currently? 
@sheyd I would say if we don't need the code to live in phoenix, since it has nothing to do with the main drupal app, let's keep it outta here.

**Comment by DFurnes** [comment]
I've had really good experiences using Github pages for static sites. That's what we're using for [tech.dosomething.org](http://tech.dosomething.org) and [forge.dosomething.org](http://forge.dosomething.org).

**Comment by sheyd** [comment]
@angaither Roger, I'll put it elsewhere. @DFurnes I'd prefer to track log hits to this, etc. (and have a little more control over downtime). I'll have it served up out of another repo, and post where here.

**Comment by angaither** [comment]
:github: has no downtime.

**Comment by itsjoekent** [comment]
yeah it does lol, just last week (or was it this week)  me & tong noticed for a few minutes

**Comment by itsjoekent** [comment]
Can we just make a json file on amazon S3 and make a public URL for it? You could easily layer Amazon's CDN on that as well

**Comment by sheyd** [comment]
I looked around at :allthethings: that would work and make this easiest. GitHub is our best option, but with a caveat. @lkpttn Let's discuss in the morning.

**Comment by sheyd** [comment]
@lkpttn I think we're all setup and on our way to completion on this. Infrastructure is setup, and you and Dee are working out the form details.
