### ISSUE TITLE
Recommendation: install environment indicator.

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5332]
Now when we have local, staging, thor, international qa, prod, international prod environments it's really easy to miss where're you at and edit node/change vital setting on production instead of local.
I suggest we install [Environment Indicator](https://www.drupal.org/project/environment_indicator).
settings.php configuration example:

``` php
<?php
// Whether the Environment Indicator should use the settings.php variables for the indicator. On your production environment, you should probably set this to FALSE.
$conf['environment_indicator_overwrite'] = TRUE;

// The text that will be displayed on the indicator. 
$conf['environment_indicator_overwritten_name'] = 'Staging';

// Valid css colors for the text and background of the admin toolbar and environment indicator.
$conf['environment_indicator_overwritten_color'] = '#ff5555';
$conf['environment_indicator_overwritten_text_color'] = '#ffffff';

// Where your indicator may appear. Allowed values are "top" and "bottom".
$conf['environment_indicator_overwritten_position'] = 'top';

// A boolean value indicating whether the Environment Indicator should be visible at all times, fixed at the top/bottom of the screen.
$conf['environment_indicator_overwritten_fixed'] = FALSE;
?>
```

Moar @ https://www.drupal.org/node/1992866

It also has integration with admin_menu module we use.

What do you think @mshmsh5000 @angaither @sheyd @blisteringherb @deadlybutter?

**Comment by sergiitk** [comment]
This looks good:
![](https://www.drupal.org/files/project-images/envindicator-integration.png)

**Comment by DFurnes** [comment]
We installed this a long time back, and had to remove it due to some issue (performance, I think?) 

@aaronschachter Do you remember any details?

**Comment by angaither** [comment]
https://github.com/DoSomething/phoenix/pull/1892
lots of JS as I remember

**Comment by sergiitk** [comment]
They released 7.x-2.x-dev branch recently, might be better.

> This is a complete rewrite of the module and a shift in the paradigm while maintaining the main features.
> https://www.drupal.org/node/1992808

**Comment by angaither** [comment]
@sergii-tkachenko perhaps, but maybe let's table this till after the global work?

**Comment by sergiitk** [comment]
Sure, sure!

**Comment by sergiitk** [comment]
I intended this ticket as a reminder :smiley:.
