### ISSUE TITLE
Rescue Mexican campaigns from bug #5198

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5335]
A list of candidates affected by #5198:
- [Bailando a través del tiempo](https://www.dosomething.org/node/5676/edit/es-mx)
- [Regala un mundo: dona un libro](https://www.dosomething.org/node/5677/edit/es-mx)
- [Las casas hogar mexicanas tienen alrededor de 19 mil niños, pero no cuentan con suficientes recursos para todos.](https://www.dosomething.org/node/5678/edit/es-mx)
- [En la Ciudad de México hay más de 800 mil personas mayores. Muchos de ellos viven en asilos, olvidados por sus familias .](https://www.dosomething.org/node/5679/edit/es-mx)
- [Convivir rutinariamente con personas mayores no sólo anima su día, aumenta su esperanza de vida y su estado de salud.](https://www.dosomething.org/node/5680/edit/es-mx)
- [La recolección de libros ayuda a una mejor distribución de los recursos en las casas hogar.](https://www.dosomething.org/node/5681/edit/es-mx)
- [Diversión sobre papel](https://www.dosomething.org/node/5686/edit/es-mx)
- [Los pequeños que tienen que ser hospitalizados, pueden sufrir depresión por no interactuar con niños de su edad.](https://www.dosomething.org/node/5687/edit/es-mx)
- [Afortunadamente, los juegos y actividades pueden ayudar en gran medida al tratamiento de la depresión en los niños.](https://www.dosomething.org/node/5688/edit/es-mx)
- [No se puede borrar](https://www.dosomething.org/node/5689/edit/es-mx)
- [Cambiar nuestros hábitos para usar de manera más eficiente el agua y reducir su consumo considerablemente.](https://www.dosomething.org/node/5691/edit/es-mx)
- [El mexicano en promedio consume 350 litros de agua al día, ¡7 veces más de lo recomendado!](https://www.dosomething.org/node/5692/edit/es-mx)
- [El reto de los 50 litros](https://www.dosomething.org/node/5693/edit/es-mx)
- [Donación de sangre zombie](https://www.dosomething.org/node/5694/edit/es-mx)
- [En México menos del 0.1% de la población dona sangre.](https://www.dosomething.org/node/5695/edit/es-mx)
- [Noche de Monopoly](https://www.dosomething.org/node/5757/edit/es-mx)

**Comment by sergiitk** [comment]
@mikefantini @angaither It turned out just "Noche de Monopoly" is affected.

**Comment by angaither** [comment]
@sergii-tkachenko awesome! is the plan just to re-create that node then?

**Comment by sergiitk** [comment]
Yes, just this one node.
