### ISSUE TITLE
Enable the retrieve endpoint for the taxonomy_term resource

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5342]
![screen shot 2015-10-01 at 5 08 19 pm](https://cloud.githubusercontent.com/assets/696595/10233933/7c063a62-685f-11e5-907a-2b0e1885b857.png)

I'm planning to use it for the mobile app to retrieve tag names that'll be displayed for campaign groups. So I'll be making calls like...

https://staging.dosomething.org/api/v1/taxonomy_term/670.json

It's sounding like it gets automatically disabled every time there's a deploy, so until then I'll just be manually reenabling it.

**Comment by chloealee** [comment]
@angaither I'm having trouble finding the module name where this is located. I tried to implement a `hook_form_alter` in `dosomething_api.module` and a `hook_form_FORM_ID_alter` in `dosomething_helpers.module` using the form `id="services_edit_form_endpoint_resources"` but neither worked. Am I adding in the incorrect module?

**Comment by angaither** [comment]
ahh, @chloealee services is a bit different, this is a setting that you have to change in the drupal settings and then export with features (kind of like what we did when adding new fields) 
check out [this page](http://dev.dosomething.org:8888/admin/structure/services/list/drupalapi/resources) locally

**Comment by chloealee** [comment]
oh gotcha, thanks @angaither ! So, I'd click on it through that link, save it, and then export with the pre-checked feature? Export like this: https://www.drupal.org/node/2294809

**Comment by angaither** [comment]
yes, except export with `drush fe` which I can walk you through if you want :smile:

**Comment by chloealee** [comment]
oh awesome - that'd be great! I just found this as an example: 

```
features-export
explanation: Export a feature from your site into a module. If the feature exists, new components are added into that feature.
aliases: fe
Syntax: drush features-export name_of_feature component1 [component2...]
Example: drush fe my_new_blog_feature views_view:view_name
```

in my vagrant box, would I just do `drush fe enable_retrieve_endpoint resources`?

**Comment by angaither** [comment]
to see what hasn't been exported you can run
`drush fc` 
it will show you a list of options and services will be one of them
from there, you can see what has/hasn't been exported and you can get the name of the feature component

then you will export to `dosomething_api`

**Comment by chloealee** [comment]
oh great, thanks so much Andrea!! I just did `drush fe dosomething_api views_view:taxonomy` and it seems it created the module. How do I know if it worked correctly to submit for review?

**Comment by angaither** [comment]
if you do `git status` or `git diff` you should be able to see the changes made

**Comment by chloealee** [comment]
awesome!! Thanks for walking me through! Submitting a PR now.
