### ISSUE TITLE
Home page is not redirecting anonymous users to correct country

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5349]
- If I'm in the US,
- And I request the home page (e.g., `https://thor.dosomething.org/`),
- Then I should get redirected to the US home page.

**Comment by itsjoekent** [comment]
this worked fine yesterday, trying to figure out why it suddenly broke

EDIT: Works for my local, not andrea or shae. Also broken on thor

**Comment by angaither** [comment]
@sbsmith86 and I are being redirect to `en-global` in the homepage url

**Comment by itsjoekent** [comment]
note: checked @sbsmith86 settings and she didn't have anything filled out for the path prefix. seems like something else (code) is causing it

**Comment by itsjoekent** [comment]
clearing cache fixed the en-global bug

**Comment by itsjoekent** [comment]
reverting features fixed the rest of the problems.

the settings in http://dev.dosomething.org:8888/admin/config/regional/language/configure were out of date. 

@sbsmith86 let me know if drush cc all and drush fra fix your local for this bug!
