### ISSUE TITLE
Ensure translation of Hot Module

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5352]
![image](https://cloud.githubusercontent.com/assets/6330971/11251140/e8661eac-8dfd-11e5-8d42-df8f87aff842.png)

Need to make sure it's pulling in the correct translated terms (i.e. title) and that all misc. words are in POEditor.

Also includes share copy.

![image](https://cloud.githubusercontent.com/assets/6330971/11251166/0eacd984-8dfe-11e5-968f-9729ed451aa2.png)

---

cc @mikefantini

**Comment by weerd** [comment]
So the Hot Module social share copy is translated, but we need to make sure to add a proper translation for the `reportback_noun_verb`. 

Also, when specifying the deadline it indicates it via english language using "... _by_ October 31st" or whatever the deadline is. We should probably translate **by**:

```
Sé parte de la 100,000 playbook-os enviados by October 31st cumplida de @dosomething; ¡¿quién está listo para despegar?!  http://dev.dosomething.org:8888/node/1283?
```

**Comment by mikefantini** [comment]
@weerd we need to translate October also yeah?

**Comment by weerd** [comment]
FYI, I did not translate "playbooks" properly; it's definitely not "playbook-os".

**Comment by weerd** [comment]
Oh yeah... translations for the months would be good too! Maybe add those to the document of outstanding items to include in POEditor?

**Comment by weerd** [comment]
Will be attempting to update the code here to translate the "by", etc:

https://github.com/DoSomething/phoenix/blob/dcb3d3306408f63e3895b81e6a30de896ff7332d/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L323
