### ISSUE TITLE
non-staff users should never see message broker error message

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5365]
![image](https://cloud.githubusercontent.com/assets/6330971/10256356/b7150326-691e-11e5-9166-0da095521ef7.png)

this should only show up for staff roles because they can't do anything about it and shouldn't know that something is down with message broker.

**Comment by chloealee** [comment]
@mikefantini do you know if this is still happening? I tried to replicate this by signing up with a new account but didn't pop up for me: 
![screen shot 2016-04-11 at 1 12 13 pm](https://cloud.githubusercontent.com/assets/9019452/14435693/22c26af0-ffe7-11e5-8bc0-300b0b2964cf.png)

**Comment by mikefantini** [comment]
@chloealee in order to trigger this error the MessageBroker config on phoenix needs to be set up in a specific way. I can't recall what that needs to be missing in the config for this error to be triggered. @DeeZone do you recall what causes this error to show up?

**Comment by deezone** [comment]
@chloealee Add a bogus value to the Message Broker config: `/admin/config/services/message-broker-producer/mq-settings` to any of the fields. For example:

`host`: `10.100.25.137` <- valid
`host`: `66.666.66.666` <- invalid

The error message is being generated here: https://github.com/DoSomething/message_broker_producer/blob/master/message_broker_producer.module#L250

**Comment by chloealee** [comment]
super helpful - thanks @DeeZone !

**Comment by chloealee** [comment]
@DeeZone @mikefantini I was going to work on this but just realized it's on the message broker repo, not phoenix. I've never contributed to message broker before! Should I release so someone else can take it or is it okay to work on this?

**Comment by deezone** [comment]
@chloealee @mikefantini https://github.com/DoSomething/message_broker_producer/issues/98

I encourage @chloealee to work on it...

**Comment by mikefantini** [comment]
Apologies just getting to this...

I'm not sure how it works but @chloealee are you saying that the decision to show this error to drupal admin users vs. all users on the phoenix side not the message broker side?

cc: @angaither for any guidance on this

**Comment by deezone** [comment]
@mikefantini @chloealee Currently the `message_broker_producer` module is responsible for displaying the message. There's currently no logic to filter the display by user role / permission. My dated Drupal knowledge suggests the following but @angaither would be the best person to confirm:

To meet the request of limiting the display of the error message:
- create a permission to administer   `message_broker_producer` module -> `administer message_broker_producer`.
- Assign the permission to the "administrator" role
- Check for the `administer message_broker_producer` permission before displaying the error message:

Something like:

```
if (user_access('`administer message_broker_producer`')) {
  display error message...
}
```

**References**:
-  `hook_permission`: https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_permission/7.x
- Users, roles and permissions : https://www.drupal.org/node/120614
- https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_access/7.x
