### ISSUE TITLE
Sign Up Transactional Email - Campaign Link Bug on Production

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5366]
"Prove It" button links to https://thor.dosomething.org//node/?source=node/2805#prove for GL EN user.

![image](https://cloud.githubusercontent.com/assets/6330971/10259517/35827884-6937-11e5-9477-25b869b73a4f.png)

cc: @marahml

**Comment by mikefantini** [comment]
also getting an error for MX SP transactionals

https://thor.dosomething.org/mx/node/?source=node/17#prove

![image](https://cloud.githubusercontent.com/assets/6330971/10259565/b3fc3538-6937-11e5-8e51-288a1278b8ae.png)

**Comment by deezone** [comment]
For what it's worth, `https://thor.dosomething.org/mx/node/?source=node/17#prove` should be `https://thor.dosomething.org/mx/node/17#prove`. Confirmed this is a valid URL that resolves to MX campaign page.

**Comment by marahml** [comment]
Any button link updates since we've tested @DeeZone @blisteringherb?

**Comment by mikefantini** [comment]
The link for the campaign sign up transactional email is broken on prod.

when I sign up for https://www.dosomething.org/campaigns/just-dont-wear-blackface?source=node/1141 I get the below email. Click on the "GET STARTED" button takes me to http://mandrillapp.com/track/click/9261257/www.dosomething.org?p=eyJzIjoidmdRQmxSMjVRYzRvdUpOdWpjNGZBZG50a253IiwidiI6MSwicCI6IntcInVcIjo5MjYxMjU3LFwidlwiOjEsXCJ1cmxcIjpcImh0dHBzOlxcXC9cXFwvd3d3LmRvc29tZXRoaW5nLm9yZ1xcXC91c1xcXC9ub2RlXFxcLz9zb3VyY2U9bm9kZVxcXC81ODQwXCIsXCJpZFwiOlwiMzBiOTQyMWI0MTRjNDcyOWE2MjdjZTQ5ZTU3MTVhMjhcIixcInVybF9pZHNcIjpbXCJlOTE0NjNlMDcxODQ5MzUwMDBlZjM4NzQ4YmRjYmEyY2ZlZDc1M2IwXCJdfSJ9 which redirects me to https://www.dosomething.org/us/node/?source=node/5840

this link should take me to https://www.dosomething.org/campaigns/just-dont-wear-blackface#prove

**Comment by mikefantini** [comment]
@blisteringherb I think this is working now and just needs to be deployed to production correct?

If so can you please close this out?
