### ISSUE TITLE
MX SP user receiving wrong email template for sign up transactional

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5368]
signed up for https://thor.dosomething.org/mx/voluntario/plantar-par-tay-mx and got the following email:

![image](https://cloud.githubusercontent.com/assets/6330971/10259657/9bd70090-6938-11e5-8911-20625728ada6.png)

**Comment by blisteringherb** [comment]
Hm, I verified these were working on Fri, and I just tried again, and it looks like I'm getting the correct templates. One thing I did notice though on Fri was when I tried with my gmail account, it looks like the email template was cached. I used Mailinator this morning so there wouldn't be any caching, and this is what I got:

![image](https://cloud.githubusercontent.com/assets/28132/10283896/b760139c-6b4f-11e5-930c-5aadff90a2aa.png)

**Comment by mikefantini** [comment]
verified this is working

cc: @marahml
