### ISSUE TITLE
make sure all users are in Mobile Commons and MailChimp

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5372]
from both Friday afternoon and Saturday night

**Comment by sheyd** [comment]
There is a disparity in the numbers. Drupal reports about 4700 users being added during that period, but Mobile commons and Northstar numbers are off by up to 2000.  Digging deeper to figure out the correct number and diff.

**Comment by sheyd** [comment]
Creation numbers during the Saturday night downtime match up a lot closer:

From 2015-10-03 20:25:00 GMT - 2015-10-04 06:30:00 GMT:

Northstar: 462
Drupal: 447
Mobile Commons: 551

**Comment by Bladt** [comment]
Could this be the Niche imports? I'm seeing 1,638 on Oct 3rd and 1,428 on Oct 4th. Looking more closely, only the 1,428 (based on created values in dosomething.users) fall in the period in question.

**Comment by sheyd** [comment]
Potentially eff'd pending resolution of this ticket. If not effed, at least blocked by: https://github.com/DoSomething/phoenix/issues/5549

**Comment by sheyd** [comment]
Re-check this pending resolution of #5549

**Comment by sheyd** [comment]
User accounts accurate here as well.
