### ISSUE TITLE
Modernizr 404 due to country code prefix

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#5374]
It looks like `modernizr.js` is being loaded with the country code prefix... this path doesn't exist, so...

<img width="763" alt="screen shot 2015-10-05 at 3 52 20 pm" src="https://cloud.githubusercontent.com/assets/583202/10291693/2be79414-6b79-11e5-8847-7be6fb1674ca.png">

Note the added `/us/content` on the beginning of the URL. Strangely, only happens to this one script.

**Comment by DFurnes** [comment]
Relevant code...

From [html.tpl.php](https://github.com/DFurnes/phoenix/blob/dev/lib/themes/dosomething/paraneue_dosomething/templates/system/html.tpl.php#L35-35):

``` php
  <script type="text/javascript" src="<?php print PARANEUE_DS_PATH; ?>/dist/modernizr.js"></script>
```

And from [template.php](https://github.com/DFurnes/phoenix/blob/dev/lib/themes/dosomething/paraneue_dosomething/template.php#L4-4):

``` php
define('PARANEUE_DS_PATH', drupal_get_path('theme', 'paraneue_dosomething'));
```

Any global gurus have any ideas why this would be triggering that `/us/` prefix? @weerd @blisteringherb

**Comment by DFurnes** [comment]
This might be related to changes made in #5373, although the particular line in question was not significantly changed. It's also worth mentioning that this works fine on [staging.beta.dosomething.org](http://staging.beta.dosomething.org), but not on  [staging.dosomething.org](https://staging.dosomething.org) so it's likely only triggered when a Fastly country header is present.

**Comment by weerd** [comment]
Yeah, I tried a few different things on my local, and switching languages etc too, but no prefixed country code in path. Seems to be a Fastly thing... is there a way to keep Fastly (or Drupal responding to Fastly) from modifying asset paths?

**Comment by mikefantini** [comment]
@blisteringherb this is the issue @DFurnes was discussing in stand-up

**Comment by DFurnes** [comment]
This is now fixed [on staging](https://staging.dosomething.org).
