### ISSUE TITLE
Error Message When Trying to Unsubscribe from Digest

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5377]
In digest to eolson@dosomething.org, I clicked unsubscribe, and got this: 

![image](https://cloud.githubusercontent.com/assets/12396076/10292632/4c098dd8-6b7e-11e5-864f-db2d2d46e250.png)

**Comment by deezone** [comment]
@namimody Please add a copy of the link that the Unsubscribe link points to.

**Comment by namimody** [comment]
@DeeZone http://subscriptions.dosomething.org/?targetEmail=eolson%40dosomething.org&key=79d8486abb1998304a34829fc17db561

**Comment by deezone** [comment]
@namimody Can we please review this link together as it's working for me. I suspect your computer is struggling to get outside of the DoSomething office network.

**Comment by namimody** [comment]
Tried it at home @DeeZone and got to the right screen! Sorry for flagging unnecessarily -- closing!
