### ISSUE TITLE
Create GET endpoint for taxonomy terms

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5393]
#### The current landscape

We currently have a GET that we can enable using what Services gives us by default. We can get at it through something like...

http://staging.dosomething.org/api/v1/taxonomy_term/670.json

which gives a response like...

```
{
  tid: "670",
  vid: "5",
  name: "Sports",
  description: "",
  format: "markdown",
  weight: "0",
  uuid: "9fb331e7-e09e-4a98-8cae-0234e3855305",
  vocabulary_machine_name: "tags",
  metatags: [ ]
}
```

We can use this on the mobile app right now to get some tag names that we display within the app.
#### The request

What we'd like is for the response data to be transformed so that it's wrapped in a `data` object in the same way other responses are.

```
{
  data: {
    tid: "670",
    vid: "5",
    name: "Sports",
    description: "",
    format: "markdown",
    weight: "0",
    uuid: "9fb331e7-e09e-4a98-8cae-0234e3855305",
    vocabulary_machine_name: "tags",
    metatags: [ ]
  }
}
```

An example from a different endpoint that does this: https://www.dosomething.org/api/v1/reportbacks/1982.json

**Comment by aaronschachter** [comment]
An ideal addition (not needed for v1) would also be to alter the `GET` index query, to return all Taxonomy Terms in the expected format, and to filter by fields. We need to fully spec it out, but the ideal way we should handle Interest Groups is by dynamically querying for the interest group id's we should display (right now we have 4 term id's hardcoded in the app, and the plan is to edit the term names whenever we need to change the interest groups :cactus:)

**Comment by mikefantini** [comment]
from @jonuy "this is not needed for kiwi launch"

**Comment by aaronschachter** [comment]
This issue, or the addition? We should create a separate issue to keep track of addition (but I didn't want to necessarily junk up the phoenix issues).

**Comment by mikefantini** [comment]
question for @jonuy ^. i was just documenting :wink:

**Comment by jonuy** [comment]
The issue overall I was saying we wouldn't absolutely need for kiwi. The additional work of formatting all taxonomy queries plus a vocabulary to provide the interest group ids we should be querying for -- up for discussion with whichever dev ends up taking this on and if it's big enough that it should be broken out into two issues.

**Comment by chloealee** [comment]
@jonuy @aaronschachter I can work on this today! Should this be broken out into two issues? Happy to tackle both but would love to chat about [additional formatting](https://github.com/DoSomething/phoenix/issues/5393#issuecomment-146015949) so I make sure I understand correctly. Let me know!

**Comment by jonuy** [comment]
@chloealee I actually don't think we ended up using this endpoint on the Android app once we got away from the interest groups idea. And I can't seem to find anywhere we're using it in iOS right now, but @aaronschachter should probably confirm that.

Either way, it's still probably a thing we'll want to clean up and do, so I'd say go for it. And if you've got the bandwidth to also do the index query with the pagination and everything, that'd be cool too.

**Comment by aaronschachter** [comment]
We query the News API for the list of Cause terms in iOS -- so changes to the `terms` endpoint won't break anything there. 

@jonuy can you confirm for sure we don't use the `terms` endpoint in Android, just to be sure any changes to this endpoint won't break things?

**Comment by jonuy** [comment]
Yea, Android doesn't use it right now.
