### ISSUE TITLE
Message broker monitoring 

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5396]
Re @marahml:

> Per a convo w/ me, @sheyd and @DeeZone, Sena said he could spin up a monitoring solution in the next day or two that would ping us when the message queue is backed up. 

The goal is to send alerts (email, sms, Slack) when queues in the Message Broker system fill up. Certain queues should remain at or near zero messages when the related consumer application is healthy.
## Queues of Interest:
- **transactionalQueue**: All transactional email requests coming from the Drupal, Voting or user import applications pass through this queue. Any more than a few messages indicates that the mbc-transactional-email (https://github.com/DoSomething/mbc-transactional-email) consumer is overloaded, has encountered an error or crashed.
- **mobileCommonsQueue**: All transactional sms requests coming from the Drupal, Voting or user import applications pass through this queue.  Any more than a few messages indicates that the mbc-registration-mobile (https://github.com/DoSomething/mbc-registration-mobile) consumer is overloaded, has encountered an error or crashed.
- **userRegistrationQueue**: All submissions to MailChimp to add email / users. This includes all MailChimp accounts including international affiliate countries. This queue is consumed in batches. The number of messages will fluctuate between 0 - 100. Any more than 100 indicates that the mbc-registration-email (https://github.com/DoSomething/mbc-registration-email) consumer is overloaded, has encountered an error or crashed.

cc @mikefantini @mshmsh5000

**Comment by deezone** [comment]
@sheyd Looks like some server setup will be needed to get the RabbotMQ command line tools working: https://www.rabbitmq.com/management-cli.html

**Comment by deezone** [comment]
@sheyd @marahml Added the top queues, their descriptions and how they need to be monitored.

**Comment by marahml** [comment]
@sheyd just checking in on status of this. is it something we see moving to next sprint? cc @mikefantini

**Comment by sheyd** [comment]
@marahml Digging into this now. I think I should be able to get this in this week.

**Comment by sheyd** [comment]
All the good notifications baked in here:

https://jenkins.dosomething.org/view/All/job/Rabbit%20MQ%20Monitoring/

@mshmsh5000 So far only notifying @DeeZone until we can get the kinks worked out. After we're satisfied with the thresholds, I'll add the rest of us.
