### ISSUE TITLE
Edits to Partner Admin Experience 

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#5397]
Here's a quick outline of what we discussed:

-Remove Action Guide, Campaign Group, Campaign Run from Field selection from Content --> Add Content in Admin view

-Remove Creator Info from Campaign Template

-Restrict Image Uploader to only Square and Landscape

**Comment by mikefantini** [comment]
closing this out as it's now represented in #5419 #5420 and #5421

**Comment by julielorch** [comment]
@mikefantini: Shower songs and Bookmark Climate Change - moved from "ready to translate" to "Global English only" in Trello
