### ISSUE TITLE
Hot Module Doubles Content in "Progress Update" Field

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5400]
Seems that inputting a number into campaign page >> custom settings >> goals settings >> progress update causes the impact number to be equal to:

[# in progress update field \* 2] + reviewed reportback impact quantity 

after CRON runs.

For example:

at start:
ACTION PAGE = 18
BACK END TOTAL APPROVED QUANTITY: 18
PROGRESS UPDATE FIELD = 0

added 900 in progress update field and saved:
ACTION PAGE = 918
BACK END TOTAL APPROVED QUANTITY: 18
PROGRESS UPDATE FIELD = 900

ran CRON:
ACTION PAGE = 1,818
ACTION PAGE SHOULD SHOW: 918
BACK END TOTAL APPROVED QUANTITY: 918
PROGRESS UPDATE FIELD = 900

:(

ALSO maybe worth noting:
ran CRON again:
ACTION PAGE = 1,1818
ACTION PAGE SHOULD SHOW: 918
BACK END TOTAL APPROVED QUANTITY: 918
PROGRESS UPDATE FIELD = 900

approved RB with quantity 100:
ACTION PAGE = 1,1818
BACK END TOTAL APPROVED QUANTITY: 918
PROGRESS UPDATE FIELD = 900

ran CRON:
ACTION PAGE = 1,1918
BACK END TOTAL APPROVED QUANTITY: 1,018
PROGRESS UPDATE FIELD = 900

**Comment by angaither** [comment]
@namimody where are you seeing this happen? I'm not able to replicate
looking at the test campaign on stage everything seems to be :ok: 
https://staging.beta.dosomething.org/us/campaigns/test-campaign

**Comment by namimody** [comment]
On Thor put this in at 2:35 PM EST: 

![image](https://cloud.githubusercontent.com/assets/12396076/11821768/2912d7e2-a339-11e5-84c7-17736bbad770.png)

Front end correctly showed:

![image](https://cloud.githubusercontent.com/assets/12396076/11821776/3de3a282-a339-11e5-93ea-08b7518ae3e3.png)

Going to run CRON...

**Comment by namimody** [comment]
After running CRON, front end showed:

![image](https://cloud.githubusercontent.com/assets/12396076/11821918/eba1070c-a339-11e5-9329-0c2f92cd47ab.png)

Back end showed:
![image](https://cloud.githubusercontent.com/assets/12396076/11821927/f4650bd6-a339-11e5-8cd1-ced8509f141d.png)

The front end should be showing a total of 611 items wished for. The back should be showing a total approved quantity of 511.

Running CRON again keeps everything the same.

@angaither -- still seems to be happening :(

**Comment by angaither** [comment]
@namimody back end shows 611 + 100, isn't that 711 correct then?

**Comment by namimody** [comment]
@angaither it should be 611. 711 means that the # in the "progress update" field was doubled -- did you see both comments? When I added 100 to the "progress update" field, the total approved quantity was 511, so the front end showing 611 initially was correct. 

From there, the logic should be that only new reviewed reportbacks are added to the impact quantity.

 Thoughts?

**Comment by angaither** [comment]
I think the issue is [this cron](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.cron.inc)
the variable shouldn't ever be set to the total + override, since the override is always added in after
