### ISSUE TITLE
Update to Yahoo: Change hyperlink of Yahoo logo on desktop version of 11 Facts pages

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5403]
@sbsmith86 we are still waiting for the exact link, but we also need to change the hyperlink behind the Yahoo logo on 11 facts pages (desktop) to a site that talks about the partnership. Just putting this on your radar, will send the link over ASAP.

**Comment by namimody** [comment]
@sbsmith86 the link: http://do.yahoo.com/?fr=do_dslogo&.tsrc=do-dslogo

**Comment by sbsmith86** [comment]
@namimody does it still need to switch between `do.yahoo.com` on mobile and `search.yahoo.com` on desktop?

**Comment by namimody** [comment]
@sbsmith86 nope! the link above will connect to do.yahoo.com which will recognize desktop users and act differently. Does that help?

**Comment by sbsmith86** [comment]
@namimody yes sir-eee!
