### ISSUE TITLE
remove global features from staging DB

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5404]
when the global stuff got deployed to Staging it didn’t get removed properly from the DB

**Comment by DFurnes** [comment]
It looks like the fix that Andrea applied in https://github.com/DoSomething/phoenix/commit/1aa08b4c0e3e52c7377fe18135193a1ff24ae729 got accidentally reverted.

**Comment by DFurnes** [comment]
``` diff
--- a/lib/modules/dosomething/dosomething_home/dosomething_home.module
+++ b/lib/modules/dosomething/dosomething_home/dosomething_home.module
@@ -41,7 +41,7 @@ function dosomething_home_preprocess_node(&$vars) {
       $tiles['nid'] = $nid;
       $tiles['is_staff_pick'] = $node->field_staff_pick[LANGUAGE_NONE][0]['value'];
       $tiles['title'] = $node->title;
-      $tiles['tagline'] = $node->field_call_to_action[$lang_code][0]['safe_value'];
+      $tiles['tagline'] = $node->field_call_to_action[$node->language][0]['safe_value'];
```

Updating that fixes things on my local:
![screen shot 2015-10-07 at 10 17 37 am](https://cloud.githubusercontent.com/assets/583202/10340130/a3894c6a-6cdc-11e5-9cf7-be0373ce61cb.png)

**Comment by blisteringherb** [comment]
@DFurnes  I think what's making this break is that the default language was set to global english. I manually fixed it and the subtitles are showing up properly again.

**Comment by DFurnes** [comment]
Hmm, okay. Wouldn't we want to use the node's language though, rather than the global language (since we will have cases where we're showing nodes in multiple languages in order of user's preference)? #5249 has context of Andrea's rationale when making the change, but I'm obviously not nearly as involved in this global work so I could be misunderstanding!
