### ISSUE TITLE
Yahoo: Remove yahoo partnership from fact pages

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#5406]
Just making this issue to remind us to pull out all of the yahoo related code from fact pages when the partnership is over.

**Comment by mshmsh5000** [comment]
This issue should fix this notice, currently filling up the logs in production:

```
Notice: Undefined variable: yahoo_partnership in include() (line 72 of [/path/to]/lib/themes/dosomething/paraneue_dosomething/templates/fact/node--fact_page.tpl.php).
```

**Comment by angaither** [comment]
@sbsmith86 looks like we are good to remove this code now!
