### ISSUE TITLE
Thor and Staging Content Showing up in Google Search

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5412]
Searched notes from Shawn in google, got this: -- note that Notes from Shawn GL shows up.

![image](https://cloud.githubusercontent.com/assets/12396076/10345792/f9294c48-6cf9-11e5-9c6d-22554a897df8.png)

As a note, doesn't seem to be happening at first glance with "bully text superstar edition" or "gtfo do something" queries.

**Comment by mikefantini** [comment]
staging:

![image](https://cloud.githubusercontent.com/assets/6330971/10346002/e844887e-6cfa-11e5-8a81-5d7eef4351f5.png)

**Comment by angaither** [comment]
nofollow or disallow!

**Comment by weerd** [comment]
**robots.txt**!!

**Comment by namimody** [comment]
@angaither what does nofollow or disallow mean? :innocent:

**Comment by angaither** [comment]
https://support.google.com/webmasters/answer/96569?hl=en

https://support.google.com/webmasters/answer/6062596?hl=en

**Comment by mikefantini** [comment]
@blisteringherb mind taking a look at this one this week? cc: @mshmsh5000

**Comment by mshmsh5000** [comment]
1. This site is a Classic Of The Web: http://www.robotstxt.org/
2. Since the `drush build` will include the Drupal distro `robots.txt`, we likely need a step in `cap` or `ds` that replaces this in non-prod builds with a highly-restrictive version.

**Comment by sergiitk** [comment]
Wr can do it [here](https://github.com/DoSomething/phoenix/blob/9a88d55fc47386e454363a8cdefd47009753e119/bin/ds#L241).

**Comment by blisteringherb** [comment]
I've added `return 200 "User-agent: *\nDisallow: /\n";` to the robots.txt location block in Nginx on staging and Thor which seems to do the trick.

**Comment by angaither** [comment]
@blisteringherb if that doesn't get overwritten on deploy & it works, wanna close this out then?

**Comment by angaither** [comment]
confirmed

![image](https://cloud.githubusercontent.com/assets/645205/11727291/130bcfbc-9f51-11e5-83ce-0c7b6cc78add.png)
