### ISSUE TITLE
Message Broker transactional message - Missing `user_county` for MX, BR, and GL EN user_register

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5418]
Bugs / missing information in transactional requests sent to Message broker:
- "activity": "user_register" from Mexico user
  - [ ] Missing `user_country` value, in this case it should be "MX".

```
Array
(
[activity] => user_register
[email] => dlee+MX02@dosomething.org
[uid] => 2987574
[user_language] => en
[merge_vars] => Array
  (
    [MEMBER_COUNT] => 4 million
    [FNAME] => Mx Dee
  )
[email_template] => mb-user-register-US
[mailchimp_list_id] => f2fab1dfd4
[birthdate] => 929232000
[subscribed] => 1
[email_tags] => Array
  (
    [0] => drupal_user_register
  )
[activity_timestamp] => 1443209069
[application_id] => US
)
```

**Comment by mikefantini** [comment]
@DeeZone @blisteringherb for what it's worth I did receive an MX user registration transactional on thor just now

**Comment by marahml** [comment]
@ArielSD can you restest user registration so we can see if this is in fact working or not? cc @DeeZone @mikefantini

**Comment by ArielSD** [comment]
@marahml @mikefantini @DeeZone I tested both Mexico and Brazil on Friday and everything worked properly- should I test again?
