### ISSUE TITLE
Make field_created_copy not translatable on the campaign template

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5420]
@julielorch can you please verify that none of the campaigns in the Ready to be Translated list on https://trello.com/b/HWVvUsxW/translation-pipeline were created by any members?

also @mnelson338 this would mean we couldn't translate any campaigns that were created by members. if this is going to be the case for the next few months then that's fine, we can always change our minds later. but i just don't want to go back and forth.

**Comment by joolaay** [comment]
@mikefantini: Shower songs and Bookmark Climate Change - moved from "ready to translate" to "Global English only" in Trello

cc @mnelson338

**Comment by mnelson338** [comment]
@mikefantini Happy to hold for now on translating campaigns that are member created. Eventually, we will want the capability that's for v1.1 or later

**Comment by mikefantini** [comment]
Sorry for the delay on this. @mnelson338 what do you think the timeline is for wanting Member Created Campaigns up for MX/BR/GL-EN users? If it's "sometime between now and February" I'd rather keep this field exposed. If it's "sometime after February" then we can hide for now and re-expose then.

**Comment by mnelson338** [comment]
After February, so let's hide now. @mikefantini

**Comment by mikefantini** [comment]
Got it thanks.

@angaither assigned over to you to assign out. We can either make this field untranslatable or just hide it from Regional Admins, whichever is easiest.

**Comment by angaither** [comment]
@mikefantini @mnelson338 probably easiest to disable the ability to translate this content for now
as long as we don't have any copy in that field we want to save (from thor/production)...

**Comment by angaither** [comment]
in thor, it looks like we have only `und` language types, but in prod, it's a mix of `en` and `en-global`

**Comment by mnelson338** [comment]
@angaither @mikefantini  Let's go with what's easiest and disable translation on MCC campaigns

**Comment by mikefantini** [comment]
Yeah @angaither it's fine. The two campaigns that have an `en-global` translation don't have this field filled out.

**Comment by angaither** [comment]
closed with #5515
