### ISSUE TITLE
hide fields on /node/add/image from regional admins

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5421]
is it possible to hide the following fields on /node/add/image from regional admins?
- field_image_portrait
- field_image_thumbnail
- field_image_video
- field_image_video_poster

@julielorch @mnelson338 by removing thumbnail images this would mean that partners would not be able to create any duo galleries used on campaign runs, /about/who-we-are, and other static content pages we may want to one day translate. For translation purposes, we could still just use whatever is used on the US versions. But if they ever needed to create their own campaign run, they couldn't use the duo gallery.

By removing the video image and video poster, if we change the image on a translation of a campaign we wouldn't be able to have video tiles on the homepage.

can you two please confirm you're good with this before we move forward?

**Comment by joolaay** [comment]
@mikefantini the goal is to make it as simple as possible for partners to correctly upload content, and I'm concerned with offering fields that they can't interact with.

I'd like to restrict to just square and landscape for now, and start to toggle on additional features partners needs become more complex.

@mnelson338 what do you think?

**Comment by mnelson338** [comment]
@julielorch Agreed for 1.0 

As a flag: When we move other affiliates over (Uk, Canada, Indonesia) I would like to continue offering them the ability to use video - It's something they are asking for. If this means we should enable it for partners from the get go, then let's do that.
