### ISSUE TITLE
language issues on /user

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5422]
As a user from Mexico (with Mexican Spanish as my language), when I go to my profile from a Global English link, the campaigns that I'm signed up for have a Global English title but a Mexican Spanish CTA:

![image](https://cloud.githubusercontent.com/assets/6330971/10355722/37d6845e-6d3d-11e5-907b-8800cd11c597.png)

When I go to /mx/user everything is in Spanish:

![image](https://cloud.githubusercontent.com/assets/6330971/10355779/d5824cf6-6d3d-11e5-99fa-fa61c03bb761.png)

@mshmsh5000 similar to the homepage shouldn't this stay true to the node's language? Also shouldn't /user redirect me to /mx/user even if I'm trying to hit it from a Global English url?

ref: #5405 #5349 #5348

**Comment by mikefantini** [comment]
also for what it's worth once I report back on a campaign even if I'm on my profile using the Global English link the campaign in the "You Did" section remains in the language of the campaign that I reported back on (in this case Mexican Spanish)

![image](https://cloud.githubusercontent.com/assets/6330971/10355937/7ed7d842-6d3f-11e5-99f6-b91e71600974.png)

**Comment by mshmsh5000** [comment]
Closed #5422 via #5436
