### ISSUE TITLE
DD/MM/YYYY Format dring Account Creation Accessed By Some via dosomething.org

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5427]
Three users in ZenDesk have reported problems entering their birthday.

Two were accessing the site on iPhone:
one user: "The birthday i was putting in is 21/12/1999 it said to put day/month/year."
second user: "im using my iphone. my birthday is october 9 2001 and its telling me to use two letter for the month but im not sure what letters to use. i texted the number and when i said i couldnt send pictures from my phone it sent me to the website and when i ran into the issue, it told me to email you."

We've asked these two users where they are from and where their phones are from.

a third user sent in this screenshot of dosomething.org, but you see the date format is DD/MM/YYYY -- and the text around the DS site is in French.

![image](https://cloud.githubusercontent.com/assets/12396076/10370051/42f974a4-6dab-11e5-846b-298512b1cffd.png)

**Comment by mikefantini** [comment]
confirmed that this is working on production. it was because #5262 wasn't deployed on production. it is now.
