### ISSUE TITLE
Child Campaign/Group Campaign Signup Error Message

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5433]
Getting a "there was an error processing your request" error when signing up for a child campaign where on the campaign group we configure it to do an automatic parent signup

example staging.dosomething.org/node/1418/edit

![image](https://cloud.githubusercontent.com/assets/6330971/10378003/6e3388ca-6dd4-11e5-9b04-8587674196ed.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10378071/d2cb7a86-6dd4-11e5-8a74-a611710f028b.png)

@angaither we'll have to fix this before GGW goes live November 1st/ideally before we send it over to AARP October 17th.

**Comment by mikefantini** [comment]
you don't get that error when we don't do the automatic sign up

**Comment by mikefantini** [comment]
also this error message on backend

![image](https://cloud.githubusercontent.com/assets/6330971/10378143/3f8b165e-6dd5-11e5-8f1f-1aea66d77c57.png)

**Comment by angaither** [comment]
@mikefantini the invalid argument rule is happening because we are trying to get the current language of the [site, not of the node](https://github.com/DoSomething/phoenix/commit/f527d979b6603314336044f152b532e4b8126bfd)
looks like this was introduced by @sergii-tkachenko to fix #5456

**Comment by mikefantini** [comment]
From notes we put into Slack:

We are not translating Campaign Groups, and we will only have `automatic_sign_up` for campaigns that exist as US-EN only campaigns.

Also `automatic_sign_up` signs up a user up for the Campaign Group if that user signs up for any of the Child Campaigns. So for instance, if Teach Your Grandma Emojis is a campaign associated with the Campaign Group GGW, and we have `automatic_sign_up` enabled on GGW, then if I sign up for Teach Your Grandma Emojis, I'm automatically getting signed up for GGW as well.

**Comment by angaither** [comment]
we could default to `en` in that line. but would have to update it later, if we plan on translating or having campaign groups in other languages.

**Comment by sergiitk** [comment]
It looks like this is not the issue. Just found this in the error log:
![image](https://cloud.githubusercontent.com/assets/672669/10770091/1f2cbfda-7cf2-11e5-9e17-97eb15bb03a2.png)

```
EntityMetadataWrapperException: Unknown data property title_field. in EntityStructureWrapper->getPropertyInfo() (line 335 of /var/www/dev.dosomething.org/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).
```

and

```
exception 'EntityMetadataWrapperException' with message 'Unknown data property title_field.' in /var/www/dev.dosomething.org/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc:335
```
