### ISSUE TITLE
Setup PHP Parsing on Static Assets (Folio) Servers

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5434]
The mobileapp.dosomething.org page needs PHP processing so we don't hit the double-opt-in limit of the MailChimp form. cc: @marahml. @mikefantini We need proper prioritization for this ticket. Whole thing will likely take about 2 hours.

**Comment by mikefantini** [comment]
@sheyd i think if this is going to take 2 hours let's just get this up now so we can finish up this job

cc: @marahml

**Comment by sheyd** [comment]
Done and deployed. @lkpttn notified.
