### ISSUE TITLE
If Campaign is missing content in "issue" field, then share copy reads oddly

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5438]
Noticed this whilst working on translation stuff. If a campaign is missing an entry in the **Issue** field under **Taxonomy and Discovery** then the default copy for the owners permalink confirmation page will read as a broken sentence that doesn't make much sense (see screenshot below):

![1c6a1474-6e82-11e5-91a6-15055900e12a copy](https://cloud.githubusercontent.com/assets/105849/10399748/a5e1678e-6e82-11e5-9938-5e07244aafcf.png)

We may want to either require the field in the future, or change the copy to not rely on having an entry in the **Issue** field.

---

@mikefantini @namimody

**Comment by mikefantini** [comment]
@namimody can you please add this field to your list of fields to pull on campaigns to see what's missing?

**Comment by namimody** [comment]
I did!

On Wed, Oct 14, 2015 at 11:53 AM, mikefantini notifications@github.com
wrote:

> @namimody https://github.com/namimody can you please add this field to
> your list of fields to pull on campaigns to see what's missing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/phoenix/issues/5438#issuecomment-148095509
> .

## 

Namita (Nami) Mody

Junior Product Manager
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255

**Comment by namimody** [comment]
Going to try and write this query myself this sprint.
