### ISSUE TITLE
Mexico Report Back Email

### ISSUE THREAD

**Issue by ArielSD** [DoSomethingArchive/legacy-website#5440]
Username ascottdicker+MexicoThor@dosomething.org reported back on Igualdad de condiciones and didn't get the reportback email.

https://us4.admin.mailchimp.com/templates/edit?id=56693

**Comment by deezone** [comment]
@ArielSD Looks like it was sent to you but you've not opened the email message yet:
![image](https://cloud.githubusercontent.com/assets/2119264/10440413/f06ef816-710c-11e5-9db0-6cc10bff2213.png)

**Comment by ArielSD** [comment]
@DeeZone @blisteringherb Yup, it came, just way after all of the other transactionals. Thanks!
