### ISSUE TITLE
*|STEP_TWO|* Merge Var In English

### ISSUE THREAD

**Issue by ArielSD** [DoSomethingArchive/legacy-website#5442]
In the campaign sign up transactional emails for both Brazil and Mexico, the _|STEP_TWO|_ merge variable is populating in the body in English. 

Mexico Template: https://us4.admin.mailchimp.com/templates/edit?id=56685
Brazil Template: https://us4.admin.mailchimp.com/templates/design?tid=56681

![screen shot 2015-10-09 at 4 44 30 pm](https://cloud.githubusercontent.com/assets/8696853/10405167/2bc83ec8-6ea5-11e5-85fa-ce929bf71ffb.png)

**Comment by deezone** [comment]
@ArielSD Assigning @blisteringherb as this is campaign related transactionals.

**Comment by deezone** [comment]
@ArielSD @blisteringherb @mikefantini 

"Snap a Pic" is not translated:
![image](https://cloud.githubusercontent.com/assets/2119264/10441091/206346ca-7113-11e5-95ea-8b6807b88465.png)

**Comment by mikefantini** [comment]
yeah this will be translated when we get the PO files back from our translators
