### ISSUE TITLE
Transactional Template Formatting In Gmail

### ISSUE THREAD

**Issue by ArielSD** [DoSomethingArchive/legacy-website#5444]
When properly formatted templates come into gmail, our formatting is stripped. (font, link color, spacing)

![screen shot 2015-10-09 at 4 57 16 pm](https://cloud.githubusercontent.com/assets/8696853/10405509/47b5a7f4-6ea7-11e5-9682-89f6d92c12fa.png)

**Comment by deezone** [comment]
@ArielSD This is something you could run past @sbsmith86 when the templates are reviewed for responsiveness.

**Comment by sbsmith86** [comment]
Update: I belive the issue was that the CSS was being set in the <head> tag which gets stripped out of the code on some platforms, like gmail and yahoo. I used Mailchimp’s inliner tool to convert the styles to inline styles which is the recommended way to handle styling in html emails. I have sent the fixed templates to mandrill and started testing. Looking good so far but will wait until the final sign off from @ArielSD before closing this issue.

/cc @marahml

**Comment by sbsmith86** [comment]
@ArielSD Following up on last night the `help@dosomething.org` formatting is just the default styling that gmail uses for email addresses. Do we need to override this?

**Comment by ArielSD** [comment]
@sbsmith86 Ideally, yes- is that too big of a lift?

**Comment by sbsmith86** [comment]
@ArielSD okie dokie. updated in both mandrill and mailchimp. Please take a look and let me know if I can close this issue. Thanks!

**Comment by ArielSD** [comment]
@sbsmith86 Now the text is black/grey, but still linked. Just forwarded you the email!

**Comment by sbsmith86** [comment]
@ArielSD which template? I probably just missed one. I just registered as a user from Brazil and got the correct format 
<img width="210" alt="screen shot 2015-10-15 at 3 07 22 pm" src="https://cloud.githubusercontent.com/assets/1700409/10524625/8bb3f450-734e-11e5-83c7-be008628ae0e.png">

**Comment by ArielSD** [comment]
Ah, @sbsmith86 , yup, above is what I got as well- Are we able to format "help@dosomething.org" the same way as "FAQ"?

**Comment by ArielSD** [comment]
Hey @sbsmith86 Just checking up on this again- thank you!

**Comment by sbsmith86** [comment]
@ArielSD The templates have been updated to style the `help@dosomething.org` text the same as `FAQ`. The updated templates have been saved in mailchimp and are currently saved as drafts in mandrill. Can you take a look and let me know if we can close out this issue?

**Comment by ArielSD** [comment]
The link is now properly in "Clicky Clicky Blue", and we're pointing to the Help Center instead of FAQ or help@dosomething.org. Thanks, Shae!

**Comment by sbsmith86** [comment]
Closing!
