### ISSUE TITLE
Translated Auth Flow Help Text for Cell Field

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#5446]
@marahml suggested additional help text for MX + BR cell fields, because they won't immediately receive a welcome SMS. 

@mikefantini and I thought about adding help text to the translation, but we're not sure how difficult this is knowing that "cell" pops up in numerous. 

Mentioned briefly to @weerd, but maybe @sbsmith86 you have some ideas?

**Comment by marahml** [comment]
Per our convo, here's a copy suggestion: 

"We're working on getting texting up in your country. When we do, we'll send volunteer opportunities right to your phone!"

**Comment by sbsmith86** [comment]
@julielorch yea we can add help text to that field based on country code on the registration form. Where else does this field pop up?

**Comment by mikefantini** [comment]
@marahml i'm a bit concerned about how long that copy is given that it needs to fit on this form (where optional is) especially on mobile devices.

![image](https://cloud.githubusercontent.com/assets/6330971/10457818/c96cd074-7195-11e5-8722-b9a46da095e1.png)

@sbsmith86 i tried adding it in to see what it would look like through inspect element but couldn't figure out how to get the text to wrap. Would it be relatively quick for you to put this together in browser and put a screenshot in this issue? both on desktop and the mobile breakpoint?

**Comment by marahml** [comment]
Totally! Your call on how many characters would make most sense here. Here's a couple more options:
- "We'll let you know as soon as DoSomething texts are available in (country)!"
- "We're working on getting texting up in (country)!" (<--- though, not 100% users will understand what that means)
-  "As soon as we have texting available in your country, we'll send volunteer opps to your phone!"
- "You might not here from us asap, but we're working to be able to text our (country) members soon!"

**Comment by sbsmith86** [comment]
@mikefantini I can do that, is there a particular one you want to test? It might take just a little bit longer to try out all of the options marah put together.

**Comment by sbsmith86** [comment]
@mikefantini @julielorch @marahml I tried out a few options on mobile and desktop, take a look (also ignore the help text under the birthday field...that's only on my dev for code reference): 

### "We're working on getting texting up in your country. When we do, we'll send volunteer opportunities right to your phone!"

<img width="388" alt="screen shot 2015-10-13 at 11 47 02 am" src="https://cloud.githubusercontent.com/assets/1700409/10460062/a1c74f80-71a0-11e5-986b-566cecdec426.png">
<img width="622" alt="screen shot 2015-10-13 at 11 46 40 am" src="https://cloud.githubusercontent.com/assets/1700409/10460064/a1ca0fea-71a0-11e5-97ed-4f4b9c8199e4.png">

### "We're working on getting texting up in (country)!"

<img width="389" alt="screen shot 2015-10-13 at 11 48 27 am" src="https://cloud.githubusercontent.com/assets/1700409/10460069/a8993602-71a0-11e5-9c60-1547943fab5e.png">
<img width="626" alt="screen shot 2015-10-13 at 11 48 13 am" src="https://cloud.githubusercontent.com/assets/1700409/10460070/a89a82dc-71a0-11e5-97f5-549cb827dcbc.png">

### "As soon as we have texting available in your country, we'll send volunteer opps to your phone!"

<img width="391" alt="screen shot 2015-10-13 at 11 49 20 am" src="https://cloud.githubusercontent.com/assets/1700409/10460075/aebca6c2-71a0-11e5-821d-37339ee5def9.png">
<img width="613" alt="screen shot 2015-10-13 at 11 49 07 am" src="https://cloud.githubusercontent.com/assets/1700409/10460076/aec32056-71a0-11e5-8261-d613176b398d.png">

**Comment by mikefantini** [comment]
Huh I was totally thinking this would go next to the "(optional)" - which would have been really tight spacing - so I think this makes more sense. Thanks @sbsmith86!

@julielorch totally defer to you on your thoughts on this from a UX perspective.

Also @DFurnes want to make sure breaking up the form like this jives from a Forge perspective.

**Comment by DFurnes** [comment]
Yeah, totally cool with me. :+1: It might be worth considering using the [Footnote](http://forge.dosomething.org/#footnote) pattern so it shows up as "subtext" more clearly when scanning?

**Comment by joolaay** [comment]
Agree with @DFurnes to use Footnote, otherwise it's a bit bold.

**Comment by sbsmith86** [comment]
@mikefantini @julielorch what text did you want?

**Comment by joolaay** [comment]
"Get volunteer opportunities to your phone! Texting available in (country) soon"

**Comment by marahml** [comment]
Let's change "to" --> "on" so it makes sense without having to add in "sent" to your phone. So:

"Get volunteer opportunities on your phone! Texting available in (country) soon"

**Comment by sbsmith86** [comment]
Closing per #5538
