### ISSUE TITLE
dosomething_user_new_user_attributes() missing comment block

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5447]
The `dosomething_user_new_user_attributes()` is missing a comment block. It points to `dosomething_northstar_update_user()`.

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L539-L544

**Comment by itsjoekent** [comment]
also updating 

dosomething_user_update_user
