### ISSUE TITLE
Update UPS api

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5451]
I got an email about updates we need to make to support the UPS API

> UPS is in the process of upgrading communication security protocols for all web-based applications,  including UPS Developer Kit Application Programming Interfaces (APIs), which are used to integrate UPS functionality into your website and applications.
> 
> Effective May 31, 2016, UPS will require the TLS 1.2 security protocol. After that date, any communication requests submitted to UPS using older protocols (TLS 1.1 or earlier) will fail. 

http://www.ups.com/content/us/en/resources/techsupport/data-security.html

refs #5193

**Comment by chloealee** [comment]
I’ve been researching a little and it seems like we might not need to change the code? Seems like it has to do with the browser or at a lower level than the actual application but not sure if I'm understanding correctly. http://www.vbforums.com/showthread.php?806289-TLS-1-2-security-protocol

@sheyd do you have any insight to this?

**Comment by angaither** [comment]
ooo! they now have a JSON api available. that might be interesting
https://www.ups.com/upsdeveloperkit/downloadresource?loc=en_US

**Comment by sheyd** [comment]
@angaither @chloealee We need to do some testing to see if our current code will work or not. I'd recommend a short code snippet using `drupal_http_request` to a website that has the same security restrictions (like... Google or something, I'll come up with a better list), and see if we get errors back or not. 

I don't have better visibility into this, as TLS negotiation seems to depend on PHP version, OpenSSL version, and the implementation of the PHP functionality in calling the secure URL. References [here](https://api.drupal.org/comment/53378#comment-53378) and [here](https://www.drupal.org/node/2659568). 

There is a DevOps workaround, but it's a lot overhead and work. Outside of a list of secure websites, let me know what else I can do to help.

**Comment by sheyd** [comment]
@angaither @chloealee Found a website that exists solely for testing this sort of thing. The URL to request is this: `https://fancyssl.hboeck.de/`

**Comment by chloealee** [comment]
Thanks, @sheyd ! I'll check now.

**Comment by chloealee** [comment]
@sheyd do we have to make sure we can hit that url specifically in `dosomething_user_valid_address.inc` or can it be any file in the app?

**Comment by chloealee** [comment]
@angaither @sheyd yay confirmed that we got a `200` code when hitting this URL `https://fancyssl.hboeck.de/`! Should I close out this issue?

Popped this in `Transformer.php`
![screen shot 2016-02-24 at 5 11 20 pm](https://cloud.githubusercontent.com/assets/9019452/13302773/a9e4e8de-db19-11e5-9536-43368e61eb18.png)

And hit the `http://dev.dosomething.org:8888/api/v1/campaigns` endpoint with the following results: 
![screen shot 2016-02-24 at 5 12 00 pm](https://cloud.githubusercontent.com/assets/9019452/13302789/c1464e46-db19-11e5-83e0-b54544f17ef0.png)

**Comment by angaither** [comment]
:+1: awesome!
