### ISSUE TITLE
DO IT Photo Misaligned

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5452]
![image](https://cloud.githubusercontent.com/assets/12396076/10460676/615a5a0c-71a3-11e5-9697-72c4f95a27c0.png)

Photo in DO IT section of BR and MX versions not appearing with correct alignment. As a note, the photo is not noted in the DO IT gallery backend section for these two translations, seems just to be pulling in from the English or Global English. (Cover image is pulling in as well)

https://thor.dosomething.org/br/voluntario/veggie-surprise
https://thor.dosomething.org/mx/voluntario/veggie-sorpresa

May be related to https://github.com/DoSomething/phoenix/issues/5453

**Comment by mikefantini** [comment]
@namimody I believe  this is misaligned just because the content is missing

**Comment by namimody** [comment]
Okay @mikefantini -- should we worry that the BR and MX versions are pulling in images from GL and/or US versions?

**Comment by DFurnes** [comment]
@mikefantini That's correct. It's offset so that it appears next to the "Snap A Pic" header but in this case there's not enough content below it to keep it from overflowing into the next section.

**Comment by mikefantini** [comment]
@namimody can you specify "pulling in images from GL and/or US versions"?

If you mean as the header and Do It photo then we should only worry about this if referencing a different image doesn't work properly. But if this is the photo that those versions are referencing then no we shouldn't be worried.

And for the rb gallery we decided we want all rbs to show on all versions of the gallery regardless of where the user is from

**Comment by mikefantini** [comment]
closing this out for now. @namimody please reopen if you have other concerns.
