### ISSUE TITLE
PLAN IT + DO IT Content Not Appearing on Front End

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5453]
Backend of https://thor.dosomething.org/mx/node/2535/edit and https://thor.dosomething.org/br/voluntario/veggie-surprise filled out, but no copy shows on front end. Content working correctly for English and Global English.

BR:
![image](https://cloud.githubusercontent.com/assets/12396076/10460966/f094740e-71a4-11e5-8523-ec3414d5dcc2.png)

MX:
![image](https://cloud.githubusercontent.com/assets/12396076/10460976/ff953a10-71a4-11e5-8573-65027f0823f9.png)

**Comment by mikefantini** [comment]
duplicate of #5302
