### ISSUE TITLE
Win module copy not replacing tokens

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#5455]
We are seeing this on the win module. The entity tokens are not being replaced correctly. 

![screen shot 2015-10-13 at 1 37 31 pm](https://cloud.githubusercontent.com/assets/1700409/10463346/1ba351f8-71b2-11e5-9d72-074a5da3b2c1.png)

Possibly related to the translation work being done here and we need to figure out the correct way of doing the translation for that token replacement to go through.
https://github.com/DoSomething/phoenix/blob/c35f51e6e990773826a8ea83169136d4800b70e7/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.theme.inc#L172

**Comment by weerd** [comment]
@sbsmith86 the `t()` doesn't seem to be affecting it. I think something is weird w/ the `token_replace()`... it's attempting to replace `[node:field_reportback_noun]` with the entire `$node` object... that seems incorrect... shouldn't it replace that string value for another string value?

**Comment by sbsmith86** [comment]
@weerd hmm I just look on my dev quickly. When I removed the `t()` function everything worked great. then I tried this. 

```
$campaign_win_copy = t((variable_get('dosomething_campaign_win_copy')));
$copy_token_replaced = token_replace($campaign_win_copy, array('node' => $node));
```

And that also works great, so it does seem related to the t() function some how.

**Comment by weerd** [comment]
Cool cool. I tried something similar but maybe I had something cached messing w/ it. I'll update then :)

**Comment by weerd** [comment]
Yep. I was just being dumb. Thanks for the help Chef @sbsmith86 :)
