### ISSUE TITLE
Footer disappeared on staging

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#5466]
The footer has disappeared on staging after deploying #5454. Strangely, everything works fine on my local Vagrant box when running on the [v1.3.19](https://github.com/DoSomething/phoenix/releases/tag/v1.3.19) tagged release. Looking into it some more to see what may have went wrong...

**Comment by DFurnes** [comment]
Tried clearing cache on both staging and my local dev. No changes.

After inspecting the `system` SQL table on both local and staging, the old theme settings (which should be being used for the [fallback](https://github.com/DoSomething/phoenix/blob/417d532382d704251830bf46f7ed3b1148a7161f/lib/themes/dosomething/paraneue_dosomething/includes/preprocess.inc#L192-L197) and setting the new initial values for country-based footer settings) are in the theme settings entry in both environments.

<img width="1280" alt="screen shot 2015-10-13 at 4 55 41 pm" src="https://cloud.githubusercontent.com/assets/583202/10468109/42974512-71cb-11e5-86cb-e128182667ea.png">

:mag:

**Comment by DFurnes** [comment]
Well, actually my local should have the new theme settings (e.g. `footer_links_us_first_column_heading`) in that blob as well and it _doesn't_. :confused:

**Comment by DFurnes** [comment]
Not a solution, but an [interesting bit](https://www.drupal.org/node/177868) on the Drupal theming guide about "Initializing the default values" and "Adding additional settings to a new version of your theme".

:book:

**Comment by angaither** [comment]
@DFurnes I pulled down the latest code, cleared cache and my footer is :mag: missing. I think a `ds pull stage` will let you see the issue locally?

**Comment by DFurnes** [comment]
Yeah, pulling staging's DB lets me see the issue locally. And just figured out what I did...

![1429834843384](https://cloud.githubusercontent.com/assets/583202/10487378/adc0561c-7261-11e5-85fc-3876f668bcc1.jpg)
