### ISSUE TITLE
404 on "RESET MY PASSWORD" Button

### ISSUE THREAD

**Issue by ArielSD** [DoSomethingArchive/legacy-website#5473]
In the mb-user-password-us template, I was sent to a 404 page when I clicked the RESET MY PASSWORD button. 

Here's the template:
https://us4.admin.mailchimp.com/templates/editor?id=56669

**Comment by deezone** [comment]
Same issue, nasty MailChimp trying to helpful with the addition of the root link to the MailCHimp server.
- Fixed and updated to Mandrill.
