### ISSUE TITLE
incorrect URLs in campaign collections

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5474]
child campaigns in campaign collections have the following URL structure https://staging.dosomething.org/volunteer/campaigns/hunt-day-1?source=node/1172 but they should have https://staging.dosomething.org/campaigns/hunt-day-1?source=node/1172 as an example (i.e. lose the /volunteer/ for the child campaigns).

example: https://staging.dosomething.org/volunteer/aaron-test-grouped-campaign

![image](https://cloud.githubusercontent.com/assets/6330971/10485508/990a5b04-7258-11e5-958c-5a3f514dee6c.png)

I believe this was introduced with the script that was written to fix #5341 

@angaither we resolved this issue on production by using optimizely to fix URLs on https://www.dosomething.org/volunteer/boosomethingorg. We'll be reviewing content for GGW with a sponsor next week so would be great to get this resolved by then.

**Comment by mikefantini** [comment]
also causing problems on Old School Impact which is sponsored. Again fixing with optimizely right now but obviously now ideal

**Comment by angaither** [comment]
not sure why/how these were created but if you look on URL alias page in prod, you can/change/update/remove the volunteer from the URLS

both examples have volunteer before them. we will want to fix them here, not optimizley. 
https://www.dosomething.org/admin/config/search/path/list/impact
https://www.dosomething.org/admin/config/search/path/list/boosomething

obviously fixing them one off isn't ideal, but I'm not sure what would have caused these to be changed.

**Comment by namimody** [comment]
@mikefantini @angaither might this have something to do with a change in URL structure for the sake of SEO? I know that volunteer is a keyword we wanted to put in URLs for taxonomy collections...

**Comment by mikefantini** [comment]
all collections _should_ have /volunteer/ as part of the URL
- Collection: BooSomething.org
- URL of Collection: www.dosomething.org/volunteer/boosomethingorg
- Campaign that's part of collection: Zombie Blood Drive
- URL of Campaign: www.dosomething.org/campaigns/zombie-blood-drive

^ this is how it should be.

This is what is currently happening:
- Collection: BooSomething.org
- URL of Collection: www.dosomething.org/volunteer/boosomethingorg
- Campaign that's part of collection: Zombie Blood Drive
- URL of Campaign: www.dosomething.org/volunteer/campaigns/zombie-blood-drive

The URL of the campaign 404's when you try to click on it because www.dosomething.org/volunteer/campaigns/zombie-blood-drive should be www.dosomething.org/campaigns/zombie-blood-drive since www.dosomething.org/volunteer/campaigns/zombie-blood-drive doesn't exist. For some reason when the campaign is listed on the collection in the tile view it is adding /volunteer/ to the URL

**Comment by angaither** [comment]
test here! 
https://staging.dosomething.org/volunteer/aaron-test-grouped-campaign

**Comment by mikefantini** [comment]
Sam said she saw this working properly on prod on Monday

**Comment by angaither** [comment]
@sergii-tkachenko wondering if you can shed any light on this? possibly related to #5341

**Comment by sergiitk** [comment]
@angaither I don't think it's related. This is no more than malformed link:
![image](https://cloud.githubusercontent.com/assets/672669/10520764/a8276722-7374-11e5-88fa-22aade843a66.png)

**Comment by namimody** [comment]
Just to record the Optimizely hack for posterity:

collection URL: https://www.dosomething.org/volunteer/old-school-impact
Optimizely test: https://app.optimizely.com/edit?experiment_id=3700860009

collection URL: https://www.dosomething.org/volunteer/boosomethingorg
Optimizely test: https://app.optimizely.com/edit?experiment_id=3685780112

**Comment by namimody** [comment]
Optimizely tests have been turned off.
