### ISSUE TITLE
Facebook Problem Shares Not Creating Image

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5482]
On Thor US: after clicking Facebook icon on a problem share, brought to this popup:
![image](https://cloud.githubusercontent.com/assets/12396076/10497501/377ea37c-7294-11e5-9f43-a44e9f30419e.png)

and after sharing the pop up modal shows a 404 and the following is posted to FB:
![image](https://cloud.githubusercontent.com/assets/12396076/10497603/c47d5ec6-7294-11e5-8121-7b61c72b1b5d.png)

@sbsmith86 do you think this has to do with Facebook's caching logic? It's working for me on phoenix but not on Thor and TSG reported as a bug. Thanks!

**Comment by sbsmith86** [comment]
@namimody hmm im not sure, but it could be an issue with the problem share images not generating correctly. I would have to look into what's happening on thor (i.e are the images being generated, are they in the right location, etc)

**Comment by namimody** [comment]
@sbsmith86 thanks for the update! is there anything I can do to help with this?

**Comment by angaither** [comment]
is this the same as #5439?

**Comment by angaither** [comment]
since it's trying to get the language of the image?

**Comment by sbsmith86** [comment]
@angaither I think this is different since these images aren't nodes. These are the problem fact images that are generated by cron, and we just grab them from `/html/sites/default/files`. But it seems like they aren't there, or maybe there is a different directory structure on thor?

**Comment by angaither** [comment]
ahhh, right right right... also, maybe cron isn't running correctly? 
@sheyd

**Comment by sheyd** [comment]
@angaither @sbsmith86, try it now. I've just added the CORS rule for sharing assets to Thor.

**Comment by sbsmith86** [comment]
@sheyd Trying to run cron on thor to generate the images but the cron job keeps failing.

**Comment by sheyd** [comment]
@sbsmith86 The GUI always fails. You can run it from here:

https://jenkins-thor.dosomething.org/job/Drupal%20Cron/ (hit the "log in" in the upper right, it's auth'd against GitHub, so you should be able to get in).

**Comment by sbsmith86** [comment]
Thanks @sheyd! So, there is another issue going on here. I have confirmed that the images are being generated in thor. But they are located at URLs like: 

`https://thor.dosomething.org/sites/default/files/images/problem-5459.png`

However the code is trying to find them at 

`https://thor.dosomething.org/ussites/default/files/images/problem-5459.png`

And that def. don't exist. So definitely an issue we need to figure out.

@namimody @angaither

**Comment by angaither** [comment]
ohhhhh. redirect stuffs.......... (cc @deadlybutter)

**Comment by angaither** [comment]
do we need to not redirect image urls for now?

**Comment by itsjoekent** [comment]
yeah i guess we can exclude /sites

**Comment by DFurnes** [comment]
Yeah, asset URLs definitely shouldn't be rewritten... so `/profiles` should be excluded too.

**Comment by angaither** [comment]
should also look at how image node path urls are generated...

**Comment by mikefantini** [comment]
Making this a 1.0 issue with lower priority. Even as a US user I get 404'd when trying to share the problem fact.

![image](https://cloud.githubusercontent.com/assets/6330971/10624847/b42ca204-776a-11e5-88cf-ad5fbec60212.png)

**Comment by mikefantini** [comment]
also note this is the URL of the pop-up after I post on FB https://staging.dosomething.org/usds-share-complete?post_id=10103752193386179_10104399445437879#_=_

**Comment by angaither** [comment]
@sbsmith86 can you take a look at this when you get a chance, looks like it's a malformed url
