### ISSUE TITLE
Campaign Signup transactional payload

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5486]
The params sent with the transactional request for campaign report backs has the following incorrect values:
- [ ] `mailchimp_grouping_id` should not be set
- [ ] `mailchimp_group_name` should not be set

**Note**: `mailchimp_grouping_id` and `mailchimp_group_name` are only set for very rare cases where the US version of a campaign has a MailChimp `interest name` assigned in third party opt_id settings in the Drupal app.

```
Array
(
    [activity] => campaign_signup
    [email] => tacaclucet@thrma.com
    [uid] => 3118654
    [user_language] => pt-br
    [user_country] => BR
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 milhões
            [FNAME] => Poppo
            [CAMPAIGN_TITLE] => GTFO
            [CAMPAIGN_LINK] => https://thor.dosomething.org/br/node/?source=node/5459
            [CALL_TO_ACTION] => Obter o filtro! Limpar o lixo ponta de cigarro.
            [STEP_ONE] => Limpo. Eles. Acima.
            [STEP_TWO] => Snap a Pic
            [STEP_THREE] => Toss 'Em
        )
    [email_template] => mb-campaign-signup-BR
    [subscribed] => 1
    [event_id] => 5459
    [email_tags] => Array
        (
            [0] => 5459
            [1] => drupal_campaign_signup
        )
    [mailchimp_list_id] => 66fd18c5a9
    [mailchimp_grouping_id] => 10641
    [mailchimp_group_name] => GTFO2015
    [activity_timestamp] => 1444860818
    [application_id] => US
)
```

**Comment by mikefantini** [comment]
I just chatted with @DeeZone and we decided to move this to 1.1.

If this issue is not done, then if we ever translate a campaign that has `mailchimp_grouping_id` or `mailchimp_group_name` set on https://www.dosomething.org/admin/config/dosomething/opt_in then the queue will get backed up.

However, we are moving this to 1.1 because 1. we won't be translating campaigns for launch that would have these set and 2. with the digest sending we are no longer setting these on campaigns moving forward.

We should probably still do this just to be safe, but again, not a launch blocker.

**Comment by deezone** [comment]
@mikefantini This is an issue on Message Broker side as having `mailchimp_grouping_id``and`mailchimp_group_name` values in campaign signups triggers a consumer to try to sign the user up to a MailChimp list. In the case of global users it will be in the MailChimp account for their country. The global MailChimp accounts don't have "interest groups by campaign" settings making these values invalid and resulting in an error from the MailChimp submission.

The MailChimp campaign signup queue will currently keep backup signaling an error from MailChimp. This can be programmed around on the Message Broker side but I think it would be wise if the producer (Drupal app) sent valid information.

**Comment by mikefantini** [comment]
@DeeZone since we aren't translating campaigns for launch that have these set can't we keep this 1.1?

**Comment by deezone** [comment]
@mikefantini To confirm I understand, there will be no / zero campaigns with `mailchimp_gouping_id` and `mailchimp_group_name`settings that have an affiliate (non-English) version? If that's the case, please move this to G1.1.

**Comment by mikefantini** [comment]
Yup. We'll keep this at 1.1.
