### ISSUE TITLE
Header – Style

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#549]
Style the global header element as per Seth's initial header design for the initial release.

![global-header](https://f.cloud.github.com/assets/1479130/2066231/e8c9e208-8ceb-11e3-9b3a-362185b9e01c.png)
![mobile-header](https://f.cloud.github.com/assets/1479130/2066650/9dff2f5c-8cf1-11e3-830d-9d37df527c24.png)

**Comment by DFurnes** [comment]
@mmwtsn Are we switching "Sign In" and search ordering and styling back from how they are in the Action Page mocks?

![screen shot 2014-02-18 at 10 21 36 am](https://f.cloud.github.com/assets/583202/2196502/63398370-98b0-11e3-87bf-ae221b15dd53.png)

**Comment by mmwtsn** [comment]
There isn't a definitive navigation design that was approved as Seth left before completing the site chrome and Keri has been iterating throughout the design process.

This issue is 15 days old. It was initially created with Seth's approved design. That has since changed.

The file you linked looks good. Let's move forward with that design.
