### ISSUE TITLE
Does TorGuard work on Mobile Devices

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5495]

**Comment by sheyd** [comment]
@namimody @mikefantini @mshmsh5000 

iOS Instructions: https://torguard.net/knowledgebase.php?action=displayarticle&id=59
Android Instructions: https://torguard.net/knowledgebase.php?action=displayarticle&id=34

**Comment by mikefantini** [comment]
Awesome thanks @sheyd. @namimody can you please send over to TSG?

**Comment by sheyd** [comment]
Links added to Phoenix VPN wiki page here:

https://github.com/DoSomething/phoenix/wiki/VPN-Server-for-Testing-International-Sites

**Comment by namimody** [comment]
Thanks @sheyd!
