### ISSUE TITLE
save user language 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5496]
when a user signs up, we should set the language in 
`dosomething_user_user_insert()`

we can call to convert the country code to the associated language

**Comment by angaither** [comment]
actually, it [does look like we are doing this](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L601) 
it just isn't working. also it should be moved to the insert hook

**Comment by angaither** [comment]
this happens when you visit thor.dosomething.org/mx (or br) explicitly.

**Comment by angaither** [comment]
also, see `dosomething_user_set_fields`

**Comment by angaither** [comment]
this seems to be working now. (tested locally and on thor with torguard.) 
https://thor.dosomething.org/mx/user/3118720/edit

**Comment by deezone** [comment]
Duplicate of #5553
