### ISSUE TITLE
non-admins can't access any campaign pages because of double-country code in URL

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5497]
As a user coming from Mexico, if I filter home page campaigns by "Environment" I see results which include the following:

![image](https://cloud.githubusercontent.com/assets/105849/10524643/a94392a0-734e-11e5-8bdb-a09a27e89e18.png)

When selecting the "Fish Bowl Baggies" campaign, I get a 404 page and the URL has duplicate country prefixes which is likely the cause for the 404:

`https://thor.dosomething.org/mx/mx/voluntario/fish-bowl-baggies`

![image](https://cloud.githubusercontent.com/assets/105849/10524703/f2d0c6ae-734e-11e5-80af-691c20adb710.png)

**Comment by weerd** [comment]
Note: seems to happen with all campaigns on homepage

**Comment by sbsmith86** [comment]
I am seeing the same issue as a user from Brazil. If I click on "GTFO" (without using the finder), I get taken to: 

`https://thor.dosomething.org/br/br/voluntario/gtfo` 

I also tried manually removing the second `/br/` but was still redirected to the above url

**Comment by namimody** [comment]
Micah said: "I created a test US user on thor. when I used those credentials, I could not access campaigns from the homepage"

**Comment by mikefantini** [comment]
@angaither non-admin users can't access campaigns because of this bug. Obviously this is blocking several test cases and really blocking TSG altogether since they have completed most of the non-campaign test cases we are ready for.

**Comment by angaither** [comment]
yeah, if am not using torguard, and click the URL from the finder does `/mx/us/campaigns/science-sleuth`

@deadlybutter I think this is more `init_hook` trouble 
that code has gotten pretty hairy...

**Comment by mikefantini** [comment]
@angaither is there anything left to do on this issue?

**Comment by angaither** [comment]
closed with #5521
