### ISSUE TITLE
Privacy Policy in login/register popup needs to be translated

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5504]
![image](https://cloud.githubusercontent.com/assets/105849/10525758/8eec6700-7354-11e5-9e53-5d4bb98cab0a.png)

Need to make sure "Privacy Policy" in the small greyed out text is translated.

---

cc: @mikefantini

**Comment by mikefantini** [comment]
Hmmm @weerd I'm not seeing this in POEditor.

**Comment by mikefantini** [comment]
Ah it appears as if it's because POEditor is pulling in "!terms". See https://poeditor.com/projects/po_edit?order=&filter=&id=39074&id_language=196&search=Creating+an+account.

**Comment by weerd** [comment]
So just to clarify on @mikefantini point, Drupal uses `!terms` and `!privacy` to pull in and insert the links to the the respective pages so those tokens are needed. This all happens in `t()` so it should be translating. There was something up with the code which should be fixed now and will be confirming on Thor it works.

**Comment by weerd** [comment]
Confirmed on Thor; both "Terms of Service" and "Privacy Policy" are translated.
