### ISSUE TITLE
11 Facts page are 404ing

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5505]
Happens as anonymous user coming from both US or MX, but loads if signed in as a US admin:

https://thor.dosomething.org/facts/11-facts-about-human-trafficking

**Comment by mikefantini** [comment]
This also 404s logged in as an authenticated user in the US.

**Comment by angaither** [comment]
@mikefantini since this content isn't getting translated, we should be able to visit https://thor.dosomething.org/facts/11-facts-about-human-trafficking as is?

with no country prefix? correct?

cause they work right now if you go to
https://thor.dosomething.org/us/facts/11-facts-about-human-trafficking

**Comment by mikefantini** [comment]
Yeah @angaither we need https://thor.dosomething.org/facts/11-facts-about-human-trafficking to redirect to https://thor.dosomething.org/us/facts/11-facts-about-human-trafficking.

I feel like these issues are related: #5006 #5136 and #5316

**Comment by angaither** [comment]
@mikefantini and everyone, regardless of language/country should be redirected to that?

**Comment by mikefantini** [comment]
Hmm actually let me take a step back. I'm not sure if I was correct that we want https://thor.dosomething.org/facts/11-facts-about-human-trafficking to redirect to https://thor.dosomething.org/us/facts/11-facts-about-human-trafficking.

This is the situation: we currently get ~850,000 entrances each month to our 11 facts pages and these come from all over the world. Very few users navigate to these pages internally, almost all traffic comes from external search.

We need to make sure that _everyone in the world_ can search on Google "facts about tornadoes" and be taken to our fact page. So even if I'm on https://www.google.com.mx and I search for "facts about tornadoes" I should still get our facts page surfaced in my Google search results and I should be able to access the facts page from Google.

@blisteringherb @angaither let me know if you need any other info on this.

**Comment by mikefantini** [comment]
Also going to https://staging.dosomething.org/mx/facts/11-facts-about-bullying as a user in Mexico brings up the US EN fact page:

![image](https://cloud.githubusercontent.com/assets/6330971/10625407/ecbf3e8c-7770-11e5-8bac-785fea48d4a6.png)

**Comment by blisteringherb** [comment]
@angaither  In order to make this work, we'll need to run a script to change the language of all of the fact pages to `en-global`. Because the default language for the site is en-global and it doesn't have a prefix, it seems that Drupal won't "fall back" to the only published node like it will for prefixed URLs. Do you see any issues with that?

**Comment by mikefantini** [comment]
@angaither @blisteringherb does this mean when people access 11 facts from the US (i.e. via Google Search) and they navigate to other pages, they will go to Global English pages, or will they they get redirected to US pages?

**Comment by angaither** [comment]
from what i understand about this 
- we want to keep the urls as they currently are
- we do NOT have translated content or URLs for this

so, yes @blisteringherb that makes sense to me since the urls won't need a prefix, they should be in `global-english`

**Comment by blisteringherb** [comment]
Sorry @angaither @mikefantini, I misspoke on needing to change the language for the 11 facts pages. My dev environment wasn't displaying the correct information. I've put in a pull request to block the redirect behavior for any node that's not translatable. It fixes this issue, and I don't think it will impact any other node types that it shouldn't.

**Comment by mikefantini** [comment]
@blisteringherb so will the URL be /us/facts/ or /facts/?

**Comment by blisteringherb** [comment]
@mikefantini It will be /facts without a prefix.

**Comment by mikefantini** [comment]
Sweet thanks!
