### ISSUE TITLE
/user links are pre-appended with /us

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5506]
when I login from 
`https://thor.dosomething.org/mx` I am logged in and then get redirected to `https://thor.dosomething.org/us/user/3118670`
it should be
`https://thor.dosomething.org/mx/user/3118670`

@mshmsh5000 also noticed password redirect links are getting sent to `us/user/password-reset`

**Comment by angaither** [comment]
might be related to #5497

**Comment by itsjoekent** [comment]
ill see if my shiz fixes this

**Comment by angaither** [comment]
fixed with #5521
