### ISSUE TITLE
Adding a translation causes fatal error (sometimes)

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#5509]
Currently only happening on my dev. When I go to a campaign that doesn't have a translation, and try to add one, I get this error. 

`EntityMalformedException: Missing bundle property on entity of type field_collection_item. in entity_extract_ids() (line 7844 of /var/www/dev.dosomething.org/html/includes/common.inc).`

**Comment by angaither** [comment]
@sbsmith86 I just tried this locally and I'm not able to replicate this

**Comment by sbsmith86** [comment]
@angaither cool. We can close this. I will try rebuilding on dev and pulling the latest on global like you suggested in slack.

**Comment by angaither** [comment]
@sergii-tkachenko I just got this on my local as well
- on global branch
- default lang is `en-global`
- trying to create a translation of the homepage node
  - `http://dev.dosomething.org:8888/node/1485/edit/add/en/en-global`
- when I save the node I get the error
  - `EntityMalformedException: Missing bundle property on entity of type field_collection_item. in entity_extract_ids() (line 7844 of /var/www/dev.dosomething.org/html/includes/common.inc).`

This is causing a few issues, since I can't replicate some of the bugs we are seeing on thor

**Comment by angaither** [comment]
@sergii-tkachenko do you mind taking a look/seeing if you can replicate this?

**Comment by angaither** [comment]
my workaround currently is create a translation on stage
- pull down the latest stage database
- drush fra -y to re-setup global biz

**Comment by sergiitk** [comment]
This error on drupal.org: https://www.drupal.org/node/1281974.

**Comment by sergiitk** [comment]
Looks like this happens with combination of Entity Translation + Field Collection + Fields Collection Translation patch (https://www.drupal.org/node/1344672). Maintainer's comment:

> The comments are saying this happens when saving nodes using entity translation. The current beta and dev versions of field collections do not yet support entity translation. If you need field collections to work with entity translation you can try the patch in the issue for it: #1344672: Field Collection: Field translation (entity_translation) support.
> https://www.drupal.org/node/1281974#comment-9439113

CC @sheyd @mshmsh5000

**Comment by sergiitk** [comment]
Some users from the ticket claim that downgrading to beta8 works. This doesn't work for us, because the   Fields Collection Translation patch is failing to apply to beta8:

```
field_collection-7.x-1.0-beta8 downloaded. [ok]
Unable to patch field_collection with field_collection-add_entity_translation_support-1344672-459.patch. [error]
```

**Comment by mikefantini** [comment]
@sergii-tkachenko @angaither if I remember correctly we labeled this a blocker because it was slowing down dev. Given @sergii-tkachenko's findings is this worth keeping a blocker or do we just go for the work around? Will this still be an issue once we merge global into dev?

**Comment by sergiitk** [comment]
@mikefantini I'm investigating this right now.

**Comment by angaither** [comment]
@mikefantini it was labeled a blocker b/c of the gallery field, not because it was slowing down dev

**Comment by mikefantini** [comment]
Since @sergii-tkachenko wasn't able to replicate we are going to close this issue out.

Related to #5628
