### ISSUE TITLE
Remove coutry code from CAMPAIGN_LINK campaign_signup transactional mbp request

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5511]
Remove coutry code from `CAMPAIGN_LINK` merge_var path:

```
[CAMPAIGN_LINK] => https://thor.dosomething.org/br/campaigns/take-back-streets?source=node/2043
```

should be:

```
[CAMPAIGN_LINK] => https://thor.dosomething.org/campaigns/take-back-streets?source=node/2043
```
## **Details**:

The expected logic is a user will be directed to the appropriate language version of a campaign if they navigate to the base / default campaign URL. 
- Based on the detected user location, anonymous users will be directed to the campaign language version associated with their location (by country). 
- Logged in users will be directed to the language version defined by their user account language setting. In the case where a version of the campaign does not exist the user will directed to the English version of the campaign.

cc: @mikefantini

**Example `[activity] => campaign_signup`**:

```
Array
(
    [activity] => campaign_signup
    [email] => al.c@specialistsguild.org
    [uid] => 3118649
    [user_language] => pt-br
    [user_country] => US
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Kurapika
            [CAMPAIGN_TITLE] => Retomar as ruas
            [CAMPAIGN_LINK] => https://thor.dosomething.org/br/campaigns/take-back-streets?source=node/2043
            [CALL_TO_ACTION] => Vire rua assédio em capacitação.
            [STEP_ONE] => Faça sua marca
            [STEP_TWO] => Snap a Pic
            [STEP_THREE] => Não param por aí
        )
    [email_template] => mb-campaign-signup-US
    [subscribed] => 1
    [event_id] => 2043
    [email_tags] => Array
        (
            [0] => 2043
            [1] => drupal_campaign_signup
        )
    [activity_timestamp] => 1444941779
    [application_id] => US
)
```

**Serialized**:

```
a:12:{s:8:"activity";s:15:"campaign_signup";s:5:"email";s:25:"al.c@specialistsguild.org";s:3:"uid";s:7:"3118649";s:13:"user_language";s:5:"pt-br";s:12:"user_country";s:2:"US";s:10:"merge_vars";a:8:{s:12:"MEMBER_COUNT";s:11:"4.2 million";s:5:"FNAME";s:8:"Kurapika";s:14:"CAMPAIGN_TITLE";s:15:"Retomar as ruas";s:13:"CAMPAIGN_LINK";s:76:"https://thor.dosomething.org/br/campaigns/take-back-streets?source=node/2043";s:14:"CALL_TO_ACTION";s:35:"Vire rua assédio em capacitação.";s:8:"STEP_ONE";s:15:"Faça sua marca";s:8:"STEP_TWO";s:10:"Snap a Pic";s:10:"STEP_THREE";s:18:"Não param por aí";}s:14:"email_template";s:21:"mb-campaign-signup-US";s:10:"subscribed";i:1;s:8:"event_id";s:4:"2043";s:10:"email_tags";a:2:{i:0;s:4:"2043";i:1;s:22:"drupal_campaign_signup";}s:18:"activity_timestamp";i:1444941779;s:14:"application_id";s:2:"US";}
```

**Comment by blisteringherb** [comment]
@DeeZone I'm not quite sure what happened here, but rather than removing the prefix, I need to understand why the user language is pt-br, but the user country is US. The code as it's written is supposed to add that prefix, but it's also supposed to also have the translated URL.

**Comment by mikefantini** [comment]
@blisteringherb I think what @DeeZone was referencing was something that you had brought up originally - if we're redirecting users from www.dosomething.org/campaigns to www.dosomething.org/us/campaigns (or /br/campaigns, etc.) then do we even need to add the country prefix in the email? Instead can we just link users to /campaigns and let the redirect logic take care of the rest.

**Comment by blisteringherb** [comment]
@mikefantini @DeeZone There are a few reasons why in general we'd want to send the user to the explicit URL for the campaign. There's a performance hit for 301 redirects, and it'll be much clearer for analytics purposes to have users visit the direct URL. Also since we're rewriting URLs all over the site to use the prefix and translated path, I think we should be doing that here also to keep that as consistent as possible.

**Comment by mikefantini** [comment]
Got it. Works for me @blisteringherb. So can this issue be closed out or is there more for you to look in to?

**Comment by blisteringherb** [comment]
@mikefantini I think we can close this out.
