### ISSUE TITLE
Need to ensure translation of a variety of miscellaneous strings.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5517]
Strings to add to POEditor via POT files:
- [x] "Registration successful. You are now logged in." (seen when creating a new account)
- [x] "User account" (seen when viewing own user profile)
- [x] Months of the year
- [x] "by"
- [x] "Privacy Policy"
- [x] "My Account"
- [x] "Sign Up"
- [x] "Create new account"
- [x] "MM/DD/YYYY"
- [x] "Edit Status"

Refs #5513 
Refs #5352 
Refs: #5504

---

@mikefantini

**Comment by weerd** [comment]
Updated on POEditor and Thor as well.

**Comment by mikefantini** [comment]
@weerd what about MM/DD/YYYY (which should be DD/MM/AAAA)? It's in POEditor but not displaying https://poeditor.com/projects/po_edit?order=&filter=&id=39074&id_language=196&search=MM%2FDD%2FYYYY

![image](https://cloud.githubusercontent.com/assets/6330971/10551277/ff8765b2-7419-11e5-8a75-5ffa5061336c.png)

cc: @sbsmith86

**Comment by sbsmith86** [comment]
Yea, i didn't run that placeholder text through `t()` :flushed: 

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L18

**Comment by weerd** [comment]
Ah, righty-o. I can update that!

**Comment by weerd** [comment]
actually, @sbsmith86 it seems like you're doing some logic there with the ternary to decide on how to display date format, so `t()` probs _shouldn't_ be used right? I just need to update the `YYYY` to be `AAAA` 

año === year (in spanish, ¡olé!)

**Comment by mikefantini** [comment]
@weerd can you please make sure it's DD/MM/AAAA for Brazilian users as well? Thanks!

**Comment by sbsmith86** [comment]
@weerd I'm not all clear on all the details of how we are using `t()`... but I thought that all hard coded strings need to be ran through it. If the ternary needs to be removed for it to work, then feel free to rework that logic. We just need to make sure to show `MM/DD/YYY` placeholder text for US users only.

**Comment by weerd** [comment]
I think the logic is fine. it's just that in spanish **Year** is **Año** and so YYYY to spanish users doesn't make sense is all. So just going to update the string for spanish to be AAAA. The only scenario where I think maybe keeping it in POEditor would make sense is if it varies from that for other languages too, which would then make it easier for us to just keep in POEditor based on the language.

what say you @mikefantini?

**Comment by mikefantini** [comment]
@weerd @sbsmith86 I'm fine with whatever you think will be easier to update in the future for other languages.

My gut tells me POEditor since that won't require any code pushes.

**Comment by weerd** [comment]
Yeah, probs POEditor. I'll switch it around then.

**Comment by weerd** [comment]
Referencing these in following doc: https://docs.google.com/spreadsheets/d/1dFO6KGS5ryqI-x2EjPNDupwHqS6p9fK32oeHfTx8t0M/edit#gid=0

**Comment by mikefantini** [comment]
Closing this out since remaining work is represented in #5855
