### ISSUE TITLE
Anonymous users are able to access unpublished translations of nodes

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5519]
The Brazilian Portuguese translation of School Insider (https://thor.dosomething.org/br/voluntario/escola-insider) is unpublished. However, as an anonymous user I'm able to go directly to that link.

Also, when I go directly to that link, the source language Title is pulled in.

See how on https://thor.dosomething.org/br/node/5356/translate, the BR PT translation is unpublished, and yet I'm able to view it as an anonymous user, and the US English title is pulled in (i.e. School Insider vs. Escola Insider.

![image](https://cloud.githubusercontent.com/assets/6330971/10619791/a162f634-7745-11e5-9372-68143d6e3a2f.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10619799/ad873e84-7745-11e5-9b43-9916931b329d.png)

This is why it appeared as if the homepage for various translations was pulling in the GL EN title, it was because those translations were unpublished.

Brazil:

![image](https://cloud.githubusercontent.com/assets/6330971/10549303/5141f40a-740e-11e5-8f6a-c750fa25abf1.png)

US:

![image](https://cloud.githubusercontent.com/assets/6330971/10549315/6389c3ae-740e-11e5-8b82-98706d7bff3d.png)

**Comment by mikefantini** [comment]
If I'm logged in as an administrator I see the correct homepage title, even though the translation is unpublished:

![image](https://cloud.githubusercontent.com/assets/6330971/10549430/eec09f4c-740e-11e5-8eed-9d513c06fb0f.png)

**Comment by mikefantini** [comment]
This is happening because the translations are not published.

Once I publish a translation the title works properly.

This is happening on campaigns as well where the translation is unpublished (i.e. https://thor.dosomething.org/br/node/5356/translate)

![image](https://cloud.githubusercontent.com/assets/6330971/10619791/a162f634-7745-11e5-9372-68143d6e3a2f.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10619799/ad873e84-7745-11e5-9b43-9916931b329d.png)

**Comment by mikefantini** [comment]
I _think_ we're safe to move this to 1.1 because 1. ideally users shouldn't be able to navigate directly to that URL and 2. we shouldn't have too many translations floating around that we don't want to publish.

**Comment by mikefantini** [comment]
Bummer. Nope this probably needs to be a 1.0 issue because the unpublished translation is still showing up in SOLR results.

See School Insider show up on /br and /br/search even though the BR PT translation is unpublished. https://thor.dosomething.org/br/node/5356/translate

![image](https://cloud.githubusercontent.com/assets/6330971/10621719/6cadd160-7750-11e5-81e0-763abcd30b2e.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10621650/16c71d74-7750-11e5-98a6-374ab3c0d0b8.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10621685/38aeb08c-7750-11e5-8503-9afe46ec8771.png)

**Comment by mikefantini** [comment]
Again, if we don't think we can get this done by 1.0, the other alternative is to make sure that all translations are published. And any translations that we don't want published are deleted.

Obviously this isn't a long-term or even medium-term solution, but could be the best route to go depending on how difficult this issue is to fix.

**Comment by mikefantini** [comment]
We need to make sure that all US EN translations are published on production before we merge this into dev and push to prod. Currently a lot of the campaigns that have been translated into different languages have US EN translation unpublished for some reason.

**Comment by angaither** [comment]
@mikefantini I think the title showing in english and the fact that the campaign shows up in solr might be two different issues
cc @blisteringherb

**Comment by mikefantini** [comment]
Yeah agreed @angaither: the main issue here is that anonymous users are able to navigate to and access unpublished translations.

It just so happens that when they do so, the source title gets pulled in. Which is actually good because I'm not sure we would have found this bug otherwise.

I'll create an issue for the title thing separately.

**Comment by angaither** [comment]
@blisteringherb can you take a look at unpublished translations showing up in search?

**Comment by angaither** [comment]
@mikefantini should our admins/global admins be able to see the campaign if it's unpublished and everyone else should get a 403?

**Comment by mikefantini** [comment]
I think we should have the same rules around unpublished translations as we have around unpublished content.

i.e. admins should be able to see unpublished translations and other users should get 403 if they try to go directly to that path.

**Comment by angaither** [comment]
@mikefantini when you say 'admins' you mean anyone with 'access admin menu' permission, not just the admin role.

then this will also be a new bug that the BR version shows the wrong content (to staff/admins)

**Comment by mikefantini** [comment]
Right I'm saying anyone who can currently view unpublished content on the site should be able to view unpublished translations.

Can you explain the new bug this would create? Any role that can see unpublished content should be able to go directly to /br/voluntario/whatever to see the BR version.

Oh unless you're saying we'll see the source language title?

**Comment by angaither** [comment]
correct, it's returning source lang content if the translation is unpublished

**Comment by mikefantini** [comment]
But just for title @angaither. We can add a 1.1 issue for that.

**Comment by mikefantini** [comment]
Right, the title bug is only for auth users, anyone who _should_ have access to unpublished translations should be able to see all the content in the translated language. So I don't think this will introduce another issue.

**Comment by angaither** [comment]
closed with #5571
