### ISSUE TITLE
Editors (US) should only see English option when editing campaigns

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5522]
Currently, a site editor sees the following when editing a campaign:

![image](https://cloud.githubusercontent.com/assets/12396076/10549918/f7228828-7411-11e5-9ca9-ab0479e616a6.png)

They should only see the last option (English).

**Comment by namimody** [comment]
@angaither is the decision just to expose all four options for less complexity?

**Comment by angaither** [comment]
yaaa, for now
