### ISSUE TITLE
International: campaign titles are empty on edit page

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5526]
The titles are blank on edit page after reverting from `v1.3.20` to `v1.0.20`.

Example:
https://uk.dosomething.org/node/1406/edit

**Comment by sergiitk** [comment]
The easiest way to fix it is to delete translatable title field in the campaign content type field management and then replace the title again. The fields will be copied automatically.

**Comment by sergiitk** [comment]
It takes 5 minutes to do all the procedure and seems like very lo-risky.
cc @mshmsh5000 @sheyd

**Comment by mshmsh5000** [comment]
Sounds good, given
1. We do on a non-Friday,
2. We tell UK + Canada in advance, and
3. We back up the DB.

**Comment by sergiitk** [comment]
100% agree.
