### ISSUE TITLE
In POEditor but translation not appearing on thor

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5527]
- [x] First Name
- [ ] User account
- [ ] "(And you've entered to win the scholarship!)" - on alpha permalink when scholarship attached.

**Comment by weerd** [comment]
Where specifically? Is this from the modal? Profile page?

**Comment by weerd** [comment]
Found it. On the modal ;)

**Comment by weerd** [comment]
Referencing these in following doc: https://docs.google.com/spreadsheets/d/1dFO6KGS5ryqI-x2EjPNDupwHqS6p9fK32oeHfTx8t0M/edit#gid=0

**Comment by angaither** [comment]
closing in favor of #5517
