### ISSUE TITLE
Redirect loop when trying to go to thor homepage from Japan

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5528]
![image](https://cloud.githubusercontent.com/assets/6330971/10552245/8b70948a-7420-11e5-9706-716eac5dcd53.png)

**Comment by mikefantini** [comment]
moved to #5541

---

I also get a redirect loop as an administrator in the US trying to go to https://thor.dosomething.org/campaigns/out-closet-cards-gl:

![image](https://cloud.githubusercontent.com/assets/6330971/10552347/56cc268a-7421-11e5-98ec-21195b25ecd1.png)

**Comment by angaither** [comment]
@mikefantini is this on all campaigns? or just campaigns in global english? 
trying to replicate this locally

**Comment by mikefantini** [comment]
moved to #5541

---

I'm getting the same error message when I try to go to https://thor.dosomething.org/campaigns/out-closet-cards-gl as a non-admin authenticated user. And same thing as an anonymous user.

![image](https://cloud.githubusercontent.com/assets/6330971/10583356/70ac8a96-765a-11e5-9fee-f57153384b1c.png)

**Comment by angaither** [comment]
fixed with #5542
