### ISSUE TITLE
Action – Build Out Template

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#553]
![keri_actionpg mob_final 3](https://f.cloud.github.com/assets/1479130/2066728/8cf1c3ae-8cf2-11e3-830a-1c4ec815b1ed.jpg)

![vwtn8gxdm9tzchje1ricqreojvb-qk3ib9kfszupep-ytlvvr74wkhw5kn1lgv5njv6q6xubtn8](https://f.cloud.github.com/assets/1479130/2066748/bf93809a-8cf2-11e3-82dd-846e1b66abf8.jpg)

**Comment by barryclark** [comment]
@mmwtsn Most up to date versions of this with the updated nav are now on the wiki
