### ISSUE TITLE
Need similar BR/MX path setups for /about/ as we have for /campaigns/

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5531]
Once static content is translated, we need a similar solution for /about/ as we have for /campaigns/ (i.e. /voluntario is the alias translation).

@angaither I assume this can be 1.1 but not sure if it will mess things up for launch if we change it later.

**Comment by angaither** [comment]
@mnelson338 we will need to know what the alias of these should be in the different languages

**Comment by joolaay** [comment]
We'll only have one column for non-US footer: /About.

"About" needs to translated to Br Portuguese and Mx Spanish (we have all of the pages translated, and will take the titles to populate the footer in paraneue). cc @mnelson338 

List of Footer translations:
https://docs.google.com/document/d/1_nK9VZQ6DQIZ46A6XCxQqeK1TUcO1ssMyJUNSbyPDr4/edit

**Comment by mnelson338** [comment]
Spanish: sobre
Portuguese: sobre

@angaither

**Comment by angaither** [comment]
@sergii-tkachenko do you mind setting this up with your cherry-picked branch?

**Comment by sergiitk** [comment]
Why not through the individual PR?
