### ISSUE TITLE
Campaigns without a prefix aren't working

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5541]
As an anonymous user from Japan:
- Current Behavior: I go to https://thor.dosomething.org/campaigns/out-closet-cards-gl and I get a 404 even though this campaign is published.
- Desired Behavior: I go to https://thor.dosomething.org/campaigns/out-closet-cards-gl and I see the campaign.

As an anonymous user from the US:
- Current Behavior: I go to https://thor.dosomething.org/campaigns/out-closet-cards-gl and I get a redirect loop error

![image](https://cloud.githubusercontent.com/assets/6330971/10552347/56cc268a-7421-11e5-98ec-21195b25ecd1.png)
- Desired Behavior: I go to https://thor.dosomething.org/campaigns/out-closet-cards-gl and I get taken to https://thor.dosomething.org/us/campaigns/out-closet-cards

This US behavior is happening for anonymous users, non-admin authenticated users, and administrators in the US.

It is also happening for users in Mexico.

**Comment by angaither** [comment]
fixed with #5542
