### ISSUE TITLE
When field collections are translated, the US English gets overwritten

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5550]
https://www.dosomething.org/node/3624/edit

![image](https://cloud.githubusercontent.com/assets/6330971/10592460/407ba17e-768a-11e5-8f0c-9db31ab44dea.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10592492/7138b3e2-768a-11e5-9689-6e22c9b4cb98.png)

**Comment by mikefantini** [comment]
When I edit the US English version to be back in English it then overrides the MX SP content.

This is only happening on headers of field collections.

In addition to fixing this bug, let's please write a script to do some cleanup on production (for published and unpublished content).

**Comment by mikefantini** [comment]
cc: @mnelson338 ^

**Comment by mikefantini** [comment]
Campaigns that I manually updated:
- https://www.dosomething.org/node/15
- https://www.dosomething.org/node/5475

**Comment by sergiitk** [comment]
That's bad. I have seen this behavior with older field_collections patch. When I was testing latest patch I specifically checked if this bug still exists — and it didn't. Will investigate this today.

**Comment by mikefantini** [comment]
Hmmm @sergii-tkachenko if you tested it, do you think it might have been a permissions thing or a language setting? The user that overwrote the header content was:
- Role: Global Admin
- Language: Global English

**Comment by mikefantini** [comment]
I'm an idiot. Field collection translations were merged into global not dev and so they aren't on production yet. Also, translators have Global Admin access, and so they are able to enter in content into field collections which saves the copy for all languages.

Apparently there is also a bug with revisions view, which is why I thought the old copy wasn't in revisions.

Closing this out and will either revert to old revisions or just manually update the fields after discussing with @mnelson338
