### ISSUE TITLE
$account->language not set on user registration

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5553]
When a new user account is created the user language setting in the new user account needs to be set. 

```
global $account;
echo $account->language;
```
- Perhaps the language value should be based on the FASTLY header country code? A Brazilian example:

```
$user_country = dosomething_settings_get_geo_country_code(); // Returns "BR"
$user_language = dosomething_global_convert_country_to_language($user_country); // Returns "pt-br"
```

thus `$account->language` should be "`pt-br`", currently it's "`en`".
- Or perhaps there's some other business logic that defines what the user language preference should be?

**BLOCKING**: https://github.com/DoSomething/phoenix/pull/5532

cc: @mikefantini

**Comment by angaither** [comment]
@DeeZone I am seeing this work as expected. 
When a user signs up from BR or MX, their language is getting set to Portuguese in the account correctly.

**Comment by deezone** [comment]
@angaither Perhaps there's a difference in our idea of what "work as expected" is?

After creating a new user with the `X-Fastly-Country-Code:BR` header the language setting for the account remains as the default `en`.
![image](https://cloud.githubusercontent.com/assets/2119264/10641444/477ac6b8-77e7-11e5-9c3a-1406f4dfa169.png)

**Comment by angaither** [comment]
@DeeZone are you testing this locally? 
make sure you're on the global branch and you've run `drush fra -y` to get the latest code updates
if you still having trouble with this, I can help

**Comment by deezone** [comment]
Checked out `global` branch and it works - duh!
