### ISSUE TITLE
Bump Vagrant box version to 1.0.6

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5554]
https://atlas.hashicorp.com/dosomething/boxes/phoenix

Need to load newest Vagrant box.

**Comment by angaither** [comment]
closed with #5555

**Comment by sergiitk** [comment]
No, it hasn't been merged yet.

**Comment by angaither** [comment]
surely this has been merged by meow.

**Comment by mshmsh5000** [comment]
Yeah @angaither our Vagrant box is version like 6000 now. SIX THOUSAND
