### ISSUE TITLE
Blank translated fields pull in from other translations

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5556]
GTFO MX's (https://thor.dosomething.org/mx/voluntario/gtfo) problem fact, FAQs, and DO IT first step fields are blank. Logic seems to be that when non-English fields are blank, content from English translation (https://thor.dosomething.org/us/node/5459/edit/en) gets pulled in. Seems to occur for any field not filled out on Spanish or Portuguese translation.

See erroneous problem fact here:

![image](https://cloud.githubusercontent.com/assets/12396076/10617757/2029064a-773a-11e5-819f-a59f1893e45a.png)

**Comment by mikefantini** [comment]
Another example where I removed VIP from BR PT translation of https://thor.dosomething.org/br/node/2043/edit:

![image](https://cloud.githubusercontent.com/assets/6330971/10620324/5df39b8a-7748-11e5-9fc9-104d9ff95d3b.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10620296/3c23898e-7748-11e5-99cd-c5ce0fdbfeb1.png)

**Comment by mikefantini** [comment]
Moving this to 1.1 since it _seems_ like we are translating all fields when we are translating copy and not leaving any blank.

**Comment by mikefantini** [comment]
Apparently this might have happened with some of the translation and so this needs to be a 1.0 issue.

**Comment by angaither** [comment]
@mikefantini what does _this_ mean?

> Apparently this might have happened with some of the translation and so this needs to be a 1.0 issue.

**Comment by mikefantini** [comment]
@angaither we may have cleared out entire fields when doing translation (i.e. instead of translating the US EN copy in the VIP field into BR PT, just leaving it blank in the BR PT field). This would result in the US EN copy of the VIP field appearing on the BR PT version of the campaign.

**Comment by angaither** [comment]
@mikefantini should our admins/global admins be able to see the campaign if it's unpublished and everyone else should get a 403?

**Comment by angaither** [comment]
this is perplexing.

**Comment by angaither** [comment]
it _seems_ like this is a bug in the module https://www.drupal.org/node/2416879

**Comment by angaither** [comment]
there is also a question box we have checked in the config options with translation fallback, but unchecking it didn't seem to fix it....
![screen shot 2015-10-21 at 5 20 58 pm](https://cloud.githubusercontent.com/assets/645205/10650586/3c8be684-7818-11e5-8034-2a87f607742c.png)

**Comment by mikefantini** [comment]
Also happens on US EN view of campaign if GL EN exists on backend but US EN does not:

![image](https://cloud.githubusercontent.com/assets/6330971/10695425/a8f96954-7971-11e5-8ef6-83d831de3739.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10695445/b8d2bae2-7971-11e5-8082-dcba78efe2b2.png)

https://staging.dosomething.org/node/31/edit/en?language=en

**Comment by mikefantini** [comment]
Doesn't matter what the language is, if content exists in a field in one translation but the field is blank in another, the content will still show up even on the translation where the field is blank:

![image](https://cloud.githubusercontent.com/assets/6330971/10695694/0a12dc2e-7973-11e5-8514-2573a83cca27.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10695699/15fb1b64-7973-11e5-8ec2-fdbdbdaba5ea.png)

https://staging.dosomething.org/campaigns/mirror-messages

**Comment by mikefantini** [comment]
Not a blocker because we will fix this via a content solution for launch, but still something we should (obviously) address.

**Comment by itsjoekent** [comment]
should this be in milestone 1.1?

**Comment by angaither** [comment]
so I tried the checkbox to disable language fallback and it seems to work now?
