### ISSUE TITLE
modules didn't turn on in global branch

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5557]
- [ ] pathauto i18n
- [ ] pathauto i18n node
- [ ] apachesolr_multilingual

**Comment by angaither** [comment]
these are in the [dosomething.info](https://github.com/DoSomething/phoenix/blob/global/lib/profiles/dosomething/dosomething.info) file on the global branch and they should have been enabled when we deployed to stage

**Comment by mikefantini** [comment]
@angaither is this still an issue/something we want to add to 2.1?

**Comment by angaither** [comment]
I think we can close this out, we turned it on manually in prod, but we should investigate if this continues to happen

**Comment by angaither** [comment]
I added `dosomething_gladiator` and it didn't automatically enable with [this script](https://github.com/DoSomething/phoenix/blob/dev/bin/enable_modules.php)

**Comment by angaither** [comment]
The problem was `apachesolr_confgen` wasn't enabling because it requires a dependency we don't have installed, so all other were failing

```
The following projects have unmet dependencies:                                                                                                    [ok]
apachesolr_confgen requires querypath
```

fixed by removing that module, since we don't seem to need it
