### ISSUE TITLE
Translation status shows whether node is published or not, not whether translation is published or not

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5558]
[Translation status](https://thor.dosomething.org/admin/content/search/translation?title=i+am+woman&type=All&field_cause_tid=All&status=All) indicates that all translations of "I am Woman, Hear Me Score" are published, however when I go to the [translate tab](https://thor.dosomething.org/us/node/5519/translate) of this campaign, I can see that the US English version is not translated.

related to: #5371

**Comment by angaither** [comment]
we might have to do some tricky `view_alter` to this to pull in `Entity translation: Translation status` for each one
