### ISSUE TITLE
Regional Admins are able to edit US EN fields

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5562]
Some of the logic of #4934 seems to have gone away. Now on both thor and staging, Regional Admins are able to edit fields outside of their language depending on what country they are visiting the site from.

As an example, when I go to edit a campaign, as a Brazil admin with Language set to Brazilian Portuguese from the US I have access to US English fields. If I am visiting from BR, I get taken to the BR PT fields. This happens regardless of how I get to the edit view of the node (i.e. whether I access it from /admin/content and click on the edit link of a campaign, go directly to /node/[nid]/edit, or go to a URL alias and then click on the edit tab of the admin view.

Previously, as a Brazilian Admin taking any one of these actions would add a Brazilian Portuguese translation and I would be editing Brazilian Portuguese fields.

Normally, this wouldn't really be an issue, since our partners are located on the ground. However, we need to figure out a path forward because our translators are located in the US.

Either we need to:

a. have @mnelson338 add all translations we want created, then send the translators the exact links to translate (i.e. https://staging.dosomething.org/br/voluntario/double-lunch-br-pt, and make sure that users don’t go to /admin/content or navigate to an edit page in any other fashion

or

b. we need to change this so that behavior is determined by role/language and not determined by fastly URL redirect logic.

Given that we've had to make so many tweaks to URL redirect logic, I think the best course of action is option a.

@angaither @mnelson338 @julielorch @mshmsh5000 @blisteringherb please add any thoughts you may have.

**Comment by mnelson338** [comment]
@mikefantini I agree - A. seems like the best option. 

However, there is a third option: Translators send me the content, and I add it in using option A. which removes the concern of translators doing something with navigation. Essentially, we would have more control. This might be the easiest solution.

**Comment by mikefantini** [comment]
The only risk with that option @mnelson338 is that it would be easier for you (or any other non-native speaker) to have copy/paste human error than one of the translators.

**Comment by mnelson338** [comment]
@mikefantini good point. So let's go with option A. I have just gone through and created translations for all the campaigns and pulled the direct links. I'll wait for your go ahead to send to the translators.

**Comment by mikefantini** [comment]
Let's move this to 1.1 since we have a plan for launch and we can figure out a course of action for post-launch.
