### ISSUE TITLE
Mobile footer breaks if there is only one column set

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5564]
If the MX footer is set like this (which is the desired set up): https://thor.dosomething.org/mx/admin/appearance/settings/paraneue_dosomething

Then the footer appears like this on mobile:
![image](https://cloud.githubusercontent.com/assets/6330971/10625723/7dad90b2-7774-11e5-89b5-101a9ce95c97.png)

cc: @julielorch

**Comment by DFurnes** [comment]
Oof! Yeah, that's no good.

**Comment by DFurnes** [comment]
Talked with @julielorch and we're going to fix this by spreading things between the three columns. :hammer:

**Comment by angaither** [comment]
@DFurnes if we are solving this with a content fix, should we close this issue?

**Comment by DFurnes** [comment]
Is the fix tracked in Trello or somewhere else? Or do you have your own todo list @julielorch?

**Comment by mikefantini** [comment]
Closing this out because we're going with a content solution of spreading the footer out across the three columns.
