### ISSUE TITLE
SMS Game form layout breaks

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5567]
When I loaded the page everything looked fine. Then when I entered in my first name and then my cell phone number and tabbed over to my friend's cell number field the layout looked like this:

![image](https://cloud.githubusercontent.com/assets/6330971/10626093/ad4f52b0-7779-11e5-9b4d-1e37310ca921.png)

**Comment by DFurnes** [comment]
Having trouble replicating this. I tested filling the form on that node in Safari 9 & Chrome 46 by entering each field and tabbing to the next one... can you try to reproduce again and see if there's something I'm missing to trigger it?

**Comment by mikefantini** [comment]
Closing this, having a hard time reproducing. May have been a rendering error on Chrome's side.

@namimody let's both watch out for this when testing in the future.
