### ISSUE TITLE
Signup & Reportback: US templates are being triggered for MX & BR 

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5569]
On staging, all transactional messages as MX user were US-EN template

User registration transactional:

![image](https://cloud.githubusercontent.com/assets/6330971/10641267/791d02e0-77e6-11e5-8872-20930fec8cf3.png)
![image](https://cloud.githubusercontent.com/assets/6330971/10641275/8873cf26-77e6-11e5-83b1-6da2e113c50a.png)

Campaign sign up transactional:

![image](https://cloud.githubusercontent.com/assets/6330971/10641312/b96de8b4-77e6-11e5-91fa-f438a0bb36db.png)
![image](https://cloud.githubusercontent.com/assets/6330971/10641320/c73a84a2-77e6-11e5-97f8-762531973d33.png)

Report back transactional:

![image](https://cloud.githubusercontent.com/assets/6330971/10641339/deb734cc-77e6-11e5-9891-0532a558512c.png)
![image](https://cloud.githubusercontent.com/assets/6330971/10641344/e58e1216-77e6-11e5-9afe-c44eb0099393.png)

Forgot password transactional:

![image](https://cloud.githubusercontent.com/assets/6330971/10641353/f0995256-77e6-11e5-95bb-55c5e4066c1f.png)

_Note:_ the only things translation on "Citemos al campeón" are Title, CTA, During Header, RB Noun, and RB Verb (i.e. After Header is still in English on the node and "Snap a Pic" is still in English as well).

cc: @DeeZone

**Comment by blisteringherb** [comment]
@mikefantini Unfortunately since we switched out the DB and code on staging I can't say for sure why these templates were using the en-us templates. I can keep this open, and we can see if, after importing the production db into Thor and running through our checklist this issue still persists.

**Comment by mikefantini** [comment]
Got it @blisteringherb. Since everything has been working correctly in Thor, do we need to do another test run of staging before we deploy everything to production?

cc: @angaither @sheyd

**Comment by angaither** [comment]
@mikefantini we can do the same thing to thor that we did to staging by refreshing the thor db with the production data
I think we should do this once we have the real translated content in prod

**Comment by deezone** [comment]
@mikefantini @blisteringherb I think this PR: https://github.com/DoSomething/phoenix/pull/5579 will resolve the MX / BR user registrations and password reset transactions being sent in the correct language template.

**Comment by deezone** [comment]
@mikefantini Testing after recent PRs to global confirms all of these transactions are using the correct templates by user country.

Example of test results in Mandrill, search "Outbound Messages" for : "dlee+ThorTest1004@dosomething.org"

https://mandrillapp.com/activity?date_format=mm%2Fdd%2Fyy&q=dlee%2BThorTest1004%40dosomething.org&date_range=7&start_date=10%2F16%2F2015&stop_date=10%2F23%2F2015]
