### ISSUE TITLE
unpublished translations showing up in solr

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5570]
related #5519

![image](https://cloud.githubusercontent.com/assets/6330971/10621650/16c71d74-7750-11e5-98a6-374ab3c0d0b8.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10621685/38aeb08c-7750-11e5-8503-9afe46ec8771.png)

**Comment by blisteringherb** [comment]
I'm still trying to figure this one out, but I've noticed that for some reason this is a thing (node_load(2307)): 

```
    [translations] => stdClass Object
        (
            [original] => en
            [data] => Array
                (
                    [en] => Array
                        (
                            [entity_type] => node
                            [entity_id] => 2307
                            [revision_id] => 16833
                            [language] => en
                            [source] => 
                            [uid] => 1942967
                            [status] => 1
                            [translate] => 0
                            [created] => 1402941066
                            [changed] => 1443715191
                        )

                    [es-mx] => Array
                        (
                            [entity_type] => node
                            [entity_id] => 2307
                            [revision_id] => 16833
                            [language] => es-mx
                            [source] => en
                            [uid] => 0
                            [status] => 1
                            [translate] => 0
                            [created] => 1444351996
                            [changed] => 1444395898
                        )

                    [pt-br] => Array
                        (
                            [entity_type] => node
                            [entity_id] => 2307
                            [revision_id] => 16833
                            [language] => pt-br
                            [source] => en
                            [uid] => 0
                            [status] => 1
                            [translate] => 0
                            [created] => 1444351996
                            [changed] => 1444395898
                        )

                )

        )
```

I think we saw the result of this also on the home page when it initially loads (rather than in the results from the finder) for the title and CTA for "Quote of a Champion" when there was an unpublished MX translation.

**Comment by mshmsh5000** [comment]
Post-2.0.3 deploy, we see unpublished translations showing up in search results. Might be limited to static content?

Example: https://www.dosomething.org/us/search/apachesolr_search/jeans

![search-results-1](https://cloud.githubusercontent.com/assets/149811/10922264/347efe74-8248-11e5-821c-016139c0cff0.png)

These yields 404s, e.g.,

![search-results-2](https://cloud.githubusercontent.com/assets/149811/10922282/48e26694-8248-11e5-852d-f9904d44b7b1.png)

**Comment by mshmsh5000** [comment]
cc @namimody

**Comment by mikefantini** [comment]
@blisteringherb this is happening for campaign pages as well:

![image](https://cloud.githubusercontent.com/assets/6330971/11040556/f019bbd8-86da-11e5-9079-db1ae9e7f78c.png)

**Comment by mikefantini** [comment]
The same thing is happening on /mx/campaigns.

![image](https://cloud.githubusercontent.com/assets/6330971/11044490/3438bbce-86f0-11e5-8707-073da9f7ee7a.png)

Here, kidnapped cosmetics exists as a translation in MX SP but the translation is not published.
