### ISSUE TITLE
Problem and Solution Facts Don't display correctly on frontend

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5572]
As a an admin or a Brazilian admin, you can't change the problem or solution fact for the Spanish or Portugese translations of the campaign.

The backend will shows: 
![image](https://cloud.githubusercontent.com/assets/12396076/10644306/0ba98e44-77f6-11e5-9821-fb7185521c6e.png)

Front end shows: 
![image](https://cloud.githubusercontent.com/assets/12396076/10644312/13a6ab2c-77f6-11e5-895a-334feea539a0.png)

Occurs even if I use TorGuard to come from Brazil OR try to use a fact that exists in prod fact database.

**Comment by angaither** [comment]
they save correctly in the backend, but the template is pulling the english version, not the translated content
