### ISSUE TITLE
Global Admins do not have sufficient permissions to translate some fields

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5574]
As a Global Admin, when trying to translate an existing campaign on thor, I'm seeing this message and an uneditable field "This field has been disabled because you do not have sufficient permissions to edit it." Even though these fields should be translatable per #4835 

Seeing it for `field_solution_copy`, `field_solution_support`, `field_pre_step_copy`, `field_photo_step`, and `field_post_step_copy`.

![image](https://cloud.githubusercontent.com/assets/6330971/10645670/f5fb8258-77fc-11e5-880a-1b52a39815eb.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10645687/0835bf06-77fd-11e5-8bae-5bc4eed94ce2.png)

Here is the user: https://thor.dosomething.org/user/3118757

Here are example campaigns: https://thor.dosomething.org/node/3316/edit/add/en/en-global and https://thor.dosomething.org/node/5651/edit/en-global.

**Comment by mikefantini** [comment]
We can work around this for launch by making people administrators instead of Global Admins. So making this 1.1.

**Comment by mikefantini** [comment]
Also seeing it for FAQ Answer fields and During/After tip copy fields.

![image](https://cloud.githubusercontent.com/assets/6330971/10694958/0f3220e2-796f-11e5-8bd5-6f19665899e3.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10694973/1d6f88ca-796f-11e5-9226-1fc77ccd0d22.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10694979/24286f60-796f-11e5-871c-2d2b7bf906b4.png)

**Comment by itsjoekent** [comment]
Translation is enabled for these fields (see bottom portion of the screenshot)

![screen shot 2015-11-09 at 11 33 10 am](https://cloud.githubusercontent.com/assets/897368/11039441/b1e5116e-86d5-11e5-8f52-2c5d08ed109a.png)

**Comment by angaither** [comment]
@deadlybutter I think I was wrong about the field collections, they all look like long text fields, checkout if we did something special for `field_secondary_call_to_action`  that's a long text that also has translation enabled, does it work?
