### ISSUE TITLE
Birthday Date client-side validation not working for MX users on Thor

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5576]
Before I fill out the form:
![image](https://cloud.githubusercontent.com/assets/6330971/10646452/2e6b0c0e-7801-11e5-8d8a-8ba5053a6390.png)

After I filled out the form:
![image](https://cloud.githubusercontent.com/assets/6330971/10646397/e1f40402-7800-11e5-803d-33cbd0a5b559.png)

cc: @weerd

**Comment by mikefantini** [comment]
Note: 

After I got the client side errors, I tried a birthday that would pass (01/02/1996) and it stored the month and day fields properly (I think):

![image](https://cloud.githubusercontent.com/assets/6330971/10647493/b2ff0e66-7806-11e5-9e1e-85e20369f77a.png)

**Comment by mikefantini** [comment]
Hmmm... 05/30/1996 doesn't work either:

![image](https://cloud.githubusercontent.com/assets/6330971/10647824/bc3baa82-7808-11e5-9c89-d075f94bc824.png)

**Comment by sbsmith86** [comment]
Hmmm...this is working for me. 
![screen shot 2015-10-21 at 4 09 20 pm](https://cloud.githubusercontent.com/assets/1700409/10648729/2f127608-780e-11e5-9cdd-1284b9ea6181.png)

**Comment by sbsmith86** [comment]
Oh also I was able to successfully submit the form.

**Comment by mikefantini** [comment]
@shae were you on thor.dosomething.org/mx using TorGuard?

**Comment by sbsmith86** [comment]
@mikefantini torGuard

**Comment by mikefantini** [comment]
Here is the doc of use cases we'll talk through IRL in tomorrow's meeting https://docs.google.com/spreadsheets/d/1Fwe8yVJ615M0ZkFnUDvd4ikVIjWyy1KNpH6L-iPy9Y0/edit#gid=0

**Comment by mikefantini** [comment]
@sbsmith86 does this issue still represent work that needs to be done for this or is this still needed?

**Comment by sbsmith86** [comment]
@mikefantini so what we are going to do is update the POEditor translations to translate `YYYY` to `AAAA` see issue #5636 which is assigned to @weerd 

And then, we will update the code to switch between `MM/DD/YYYY` and `DD/MM/YYYY` formats based on country code. That should match everything up.

**Comment by sbsmith86** [comment]
Closing via #5637
