### ISSUE TITLE
User Registration & PW Reset: US templates are being triggered for MX & BR 

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5578]
user_language / user_country in user_register / user_password transactional requests

Fixes #5499

Related: #5470
- Removes `user_country` from user registrations to allow `dosomething_mbp` to coordinate value.
- Adjusts collection of `user_language` and `user_country` for payloads.

**To test**:
The payload generated by `dosomething_mbp` to send to RabbitMQ server should look like:
- [x] `user_register`:

```
Array
(
    [activity] => user_register
    [email] => dlee+VAGTest27@dosomething.org
    [uid] => 1705478
    [user_language] => pt-br
    [user_country] => BR
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 3.5 million
            [FNAME] => Dee Vag Test 27
        )
    [email_template] => mb-user-register-BR
    [mailchimp_list_id] => 66fd18c5a9
    [birthdate] => 929232000
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )
    [activity_timestamp] => 1445462046
    [application_id] => US
)
```
- [x] `user_password`:

```
(
    [activity] => user_password
    [email] => dlee+VAGTest27@dosomething.org
    [uid] => 1705478
    [user_language] => pt-br
    [user_country] => BR
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 3.5 million
            [FNAME] => Dee Vag Test 27
            [RESET_LINK] => http://localhost:8888/br/user/reset/1705478/1445462130/2tUbpFnHSEN6DoMGKLvl73utxEKj7Nzw1YcxIqPpDDY
        )
    [email_template] => mb-user-password-BR
    [email_tags] => Array
        (
            [0] => drupal_user_password
        )
    [activity_timestamp] => 1445462130
    [application_id] => US
)
```

**Comment by deezone** [comment]
@marahml Testing confirms all of the MailChimp accounts are being updated with user emails as expect. Please confirm / test and close this issue as you see fit.

**Comment by marahml** [comment]
Just tested as a BR user on Thor, and my email (mlidey+brazil1026@dosomething.org) did not go into the DoSomethingBrazil Mailchimp account.

Testing other cases now..

**Comment by marahml** [comment]
GL email addresses are going into US Mailchimp Account > DS members.

But they should be going into US Mailchimp Account > International. 

Tested with mlidey+global1026@dosomething.org.

**Comment by marahml** [comment]
Confirmed - these emails are correctly being triggered!
