### ISSUE TITLE
Static content: User permissions

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#558]
Export permissions into `dosomething_static_content` to grant "editor" access to create, edit, but not delete any static content.  e.g: https://github.com/DoSomething/dosomething/pull/565/files

**Comment by mikefantini** [comment]
@blisteringherb can we have this in the staging site for Friday's meeting at 4?

**Comment by aaronschachter** [comment]
Updated description to include all available perms per content type.
