### ISSUE TITLE
field_step_pre and field_step_post wiped from campaigns on staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5580]
Interestingly, copy remains for `field_faq`.

I know for a fact that `field_step_pre` and `field_step_post` existed for https://staging.dosomething.org/node/1631/edit.

![image](https://cloud.githubusercontent.com/assets/6330971/10655063/38dad78a-783f-11e5-98b5-e723e52dad05.png)

@sergii-tkachenko did something happen with the script you wrote when deploying field collection translation to staging?

cc: @angaither

**Comment by sergiitk** [comment]
Yes, I noticed this when we were testing global to staging deployment. Looking how to fix this.

**Comment by sergiitk** [comment]
@mikefantini I just checked pre-field collection DB dump for node 1631 (Space Jam) and neither During Tips nor After tips were there.

**Comment by sergiitk** [comment]
Sorry, not that sure already. Testing this one more time.

**Comment by mikefantini** [comment]
Hmmm ok. @sergii-tkachenko I'm not sure when these might have been lost, but I am positive they existed previously. Is there some other time we may have lost them?

Is there another way to test whether we would lose During/After Tips when we deploy to prod?

**Comment by sergiitk** [comment]
@mikefantini We definitely would lost them. Figuring out what's wrong with this fields.

**Comment by mikefantini** [comment]
And @sergii-tkachenko, you can confirm that no campaigns in staging have this content correct? Didn't you notice this previously?

**Comment by sergiitk** [comment]
Yes, I can confirm that During Tips and After Tips fields are missing from staging.

**Comment by sergiitk** [comment]
I didn't notice it previously. I just checked old version and repeated all steps I followed during testing and fields are there (note that the fields are translatable):

![image](https://cloud.githubusercontent.com/assets/672669/10672553/9222a63c-78f9-11e5-9dc7-ce6dc8a9acb9.png)
