### ISSUE TITLE
Translations get unpublished after each save from the edit tab

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5581]
Translation is published:

![image](https://cloud.githubusercontent.com/assets/6330971/10655553/a7f830b4-7843-11e5-9c69-c1a2da644a4b.png)

I go to edit it as an editor and it's marked as "Not Published". Also the field to publish it when I first save it is disabled:

![image](https://cloud.githubusercontent.com/assets/6330971/10655559/b9bf3b76-7843-11e5-8614-2c665735b3e5.png)

And so when I save it as an Editor, the US EN translation which _was_ published is now no longer published.

![image](https://cloud.githubusercontent.com/assets/6330971/10655623/2ecd1e2e-7844-11e5-8f14-1861515b92eb.png)

Then when I go to edit it again as an Editor, I am able to publish it:

![image](https://cloud.githubusercontent.com/assets/6330971/10655601/16a98f3a-7844-11e5-937a-e8951927b99f.png)

And I can confirm that it is published:

![image](https://cloud.githubusercontent.com/assets/6330971/10655637/5efa7600-7844-11e5-8d58-7dc4ac67a461.png)

But then as an Editor when I go to edit the content again, the translation is once again set to be unpublished and again the field to publish it is disabled.

![image](https://cloud.githubusercontent.com/assets/6330971/10655656/b22294d4-7844-11e5-8c48-ef6029434ed8.png)

And so it goes back to being unpublished:

![image](https://cloud.githubusercontent.com/assets/6330971/10655662/ca0774c0-7844-11e5-983a-54385c1b5bc3.png)

And then the cycle repeats itself.

This explains why we are seeing so many campaigns on production have unpublished US EN translations cc: @namimody

**Comment by mikefantini** [comment]
Seeing a different experience as a Brazil Admin:

Brazilian translation is published:
![image](https://cloud.githubusercontent.com/assets/6330971/10655755/aea2a370-7845-11e5-93bb-bb96574e2e49.png)

However, when I update it as a Brazil Admin, it remains published:
![image](https://cloud.githubusercontent.com/assets/6330971/10655772/e28f4a80-7845-11e5-8f1a-7cd8b88612de.png)

And then when I go to edit as an Administrator, the translation remains published and the field to publish the translation is disabled:
![image](https://cloud.githubusercontent.com/assets/6330971/10655807/31116fe4-7846-11e5-9adc-2d5bc9eb4105.png)

And the translation remains published:
![image](https://cloud.githubusercontent.com/assets/6330971/10655827/4a561ca2-7846-11e5-81e0-d9433b222ba5.png)

Because the field remains disabled, It appears as if I'm unable to publish the translation even though I'm an administrator.

However, the only way I can unpublish the Brazilian Portuguese translation is if another translated version is published:
![image](https://cloud.githubusercontent.com/assets/6330971/10655892/0af3d24c-7847-11e5-9c72-f7d57dbf2334.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10655902/32596446-7847-11e5-86a0-604266261005.png)

And this makes sense because otherwise I would just unpublish the campaign.

**Comment by mikefantini** [comment]
OH MY GOD THIS MAKES NO SENSE.

As an editor whether or not the publish field is disabled or not depends on _how you get to /edit_. 

If you enter by clicking on the edit tab, the publish translation field is disabled and deselected. If you enter by clicking on the edit link on the translate tab, the field is enabled and selected. Here is a video to prove I'm not crazy (coming soon because obviously I found a bug with Jing so it's not working either now):

http://screencast.com/t/XDNwwA6S4vLV

**Comment by mikefantini** [comment]
I confirmed that this actually is happening to regional admins as well (and did it on thor this time), again when you navigate to the edit from the edit tab.

The reason I wasn't seeing this earlier was because I was on staging in the US and so I was navigating directly to /edit/pt-br and not going through the edit tab, and so I wasn't reproducing the bug.

Here is a video of a Brazil Admin reproducing the issue:

http://screencast.com/t/ye2lcsvXBeu

**Comment by mikefantini** [comment]
@angaither we can look at this together in the morning. I'm hesitant to delete/edit any of the comments just so that it's all documented, but happy to walk through this with you IRL if any of this is confusing.

Potentially related to #5158, #5469, and/or #5260.

**Comment by mikefantini** [comment]
Last thing I'll say about this tonight: I'm not sure why I'm seeing the Publish Translation field disabled sometimes and not other times, but I'm consistently able to reproduce that by going to /edit from the edit tab the translation defaults to being unpublishing upon save.

**Comment by mikefantini** [comment]
Also note, this only happens when another translated version of the campaign exists.

So for instance with Level Playing Field on production: because we only have this campaign exist in a US English version, any time we save it from the Edit tab, the translation remains published. 

If we were to add a translated version in another language, and then save the US EN version via the edit tab, it would default to having the US EN translation unpublished.

**Comment by angaither** [comment]
love this

**Comment by itsjoekent** [comment]
I agree with Fantini's assessment. 

> OH MY GOD THIS MAKES NO SENSE.

Can we make a label for this?
