### ISSUE TITLE
Hot Module Shows Date 1 Day Before Deadline

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5582]
Backend shows:
![image](https://cloud.githubusercontent.com/assets/12396076/10667265/62fe67ba-78a4-11e5-935a-bc145378cfdd.png)

Front end shows:
![image](https://cloud.githubusercontent.com/assets/12396076/10667256/59707814-78a4-11e5-90e4-f811e5930a61.png)

Note that the header photo and the hot module show different dates when the "show end date on pitch page and action page" box is checked. The header photo shows the correct date, and the hot module shows the day before. Therefore, this is not a problem on campaigns without the hot module.

Solve until this is fixed: set deadline on the backend to one day later than the actual deadline, don't show date in header photo.

**Comment by angaither** [comment]
@deadlybutter a blast from the past, mind taking a look at this?

**Comment by itsjoekent** [comment]
good ol date logic.

**Comment by itsjoekent** [comment]
Unable to reproduce on local... :/

![screen shot 2015-11-04 at 3 04 29 pm](https://cloud.githubusercontent.com/assets/897368/10950405/89a8cf2a-8305-11e5-97fb-63ca2d6cdc3f.png)

**Comment by itsjoekent** [comment]
Unable to reproduce on staging 

![screen shot 2015-11-04 at 3 17 26 pm](https://cloud.githubusercontent.com/assets/897368/10950728/30c1e868-8307-11e5-818a-6a48256fdae3.png)

http://staging.beta.dosomething.org/campaigns/test-campaign

**Comment by mikefantini** [comment]
@deadlybutter try checking your time zone setting and the time zone for @namimody's user on prod?

I honestly can't remember what we decided to do for setting user timezones but this is probably what is causing the issue?

Does the timezone for new users differ from either your or @namimody's timezones?

**Comment by itsjoekent** [comment]
yep it was nami's timezone. set to Africa/Abidjan 

![screen shot 2015-11-04 at 3 26 17 pm](https://cloud.githubusercontent.com/assets/897368/10950942/82bb630a-8308-11e5-871d-a34af80924ae.png)

fixed it for ya nami!

**Comment by mikefantini** [comment]
@deadlybutter can you confirm what Time Zone users are supposed to be set as? And then do a query on prod to see which if any users aren't set as that time zone?

**Comment by angaither** [comment]
@deadlybutter but what about users who don't have EST? Isn't that what `dosomething_campaign_set_est_timezone` was supposed to do? So that we don't have to worry about if we have users with different timezones

**Comment by itsjoekent** [comment]
yeah thats a good point, timezone shouldn't matter. why is this only happening on prod though? something isnt adding up

**Comment by mikefantini** [comment]
@deadlybutter it may not only be happening on prod. Set your user timezone to Africa/Abidjan and see if you can reproduce on your local.

Was `dosomething_campaign_set_est_timezone` only used on the hot module and not on this element on the header image?

**Comment by itsjoekent** [comment]
yes that function was only used in hot module, could explain it possibly. ill try setting my lang on local and see what happens

**Comment by itsjoekent** [comment]
yes happens when i switch my lang to africa, good catch fantini!

**Comment by angaither** [comment]
it still doesn't make a whole lot of sense though, in the example @namimody provided the date on the top display matched what was in the backend and the hot module was wrong

**Comment by namimody** [comment]
Hi @angaither and @deadlybutter -- I was just looking at https://www.dosomething.org/us/campaigns/treat-yo-friends (node 5646 on prod) and saw a discrepancy between the header photo and hot module date again. However, this time around, the hot module shows the correct end date (Dec 31 -- per the backend setting and the header photo shows Dec 30. Clearing browser cache did not fix the issue. Additionally, the discrepancy appeared only on my admin account. See screenshots below:

Admin account (profile time zone: America/New York. please note, I'm currently sitting in Phoenix, AZ)
![image](https://cloud.githubusercontent.com/assets/12396076/11172451/138e5436-8bc5-11e5-81df-01459698af0f.png)

Non-admin account (profile time zone: "none selected")
![image](https://cloud.githubusercontent.com/assets/12396076/11172444/fcdc4a90-8bc4-11e5-8ff4-40e1e3e87dfd.png)

**Comment by namimody** [comment]
(Let me know if this warrants creating a new issue and I can do that!)

**Comment by itsjoekent** [comment]
I think I know why this is happening, standby

**Comment by mikefantini** [comment]
@namimody can you please confirm this is working as expected?
