### ISSUE TITLE
Clicking on Photo or "PROVE IT" on USer Profile Brings User to /campaigns

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5584]
As a non-admin user coming from Japan: if I click the photo or "PROVE IT buttons on these campaigns on my user profile: 

![image](https://cloud.githubusercontent.com/assets/12396076/10672689/a82d6654-78bf-11e5-92af-9ebce061003d.png)

I get brought to /campaigns when I should be brought to the action page or prove it section of the campaign
![image](https://cloud.githubusercontent.com/assets/12396076/10672695/b7ebe930-78bf-11e5-9f16-ae3b67888526.png)

**Comment by angaither** [comment]
looks like that url is missing the country prefix

**Comment by angaither** [comment]
@weerd do you mind taking a look at this?

**Comment by weerd** [comment]
Seems like the `%23` is messing with the URL, which technically shouldn't since it's just the url encoded `#`. If I switch it to a `#` it goes to the right page.
