### ISSUE TITLE
"Contact Us" Disappears on GL EN Version When Window is Resized or Viewed on iPhone

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5587]
There is no access to submitting a question when window is resized (happens on Chrome and Safari, at least) or when site is viewed from iPhone.

Chrome:
![image](https://cloud.githubusercontent.com/assets/12396076/10673472/0e5b6b3e-78c4-11e5-977d-5f58eb98b3f5.png)

Safari:
![image](https://cloud.githubusercontent.com/assets/12396076/10673476/157aa2e0-78c4-11e5-9804-28ffe22da3ea.png)

iPhone (via Japan):
![image](https://cloud.githubusercontent.com/assets/12396076/10673465/fd970dc6-78c3-11e5-8de8-1c8908ee184a.png)

When coming from US on an iPhone, "Contact Us" appears as it should.

**Comment by itsjoekent** [comment]
Unable to reproduce

![screen shot 2015-12-03 at 12 55 17 pm](https://cloud.githubusercontent.com/assets/897368/11568983/34f9f28c-99bd-11e5-9979-49c40ef9b518.png)

**Comment by namimody** [comment]
@deadlybutter I can't reproduce either (was in NZ via TorGuard and still saw Contact Us when I resized the window. Closing.

**Comment by itsjoekent** [comment]
:+1:
