### ISSUE TITLE
Reportback Text Not Wrapping on iPhone

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5588]
Happening on iPhone in at least US and Japan.

Hitting the page shows: 
![image](https://cloud.githubusercontent.com/assets/12396076/10673747/78dc4536-78c5-11e5-9447-ea2b79af050c.png)

"Why is this important to..." is cut off. 

Then, if one clicks "submit your pic without uploading a photo and/or putting content in the fields, fields shake and text above first field gets red with anger, text above second field does not:
![image](https://cloud.githubusercontent.com/assets/12396076/10673786/b8d5bd34-78c5-11e5-8a3f-4c88f916a339.png)

To rectify, "Why is this important to you?" should wrap and should turn red when field is not filled out but someone attempts to submit form.

**Comment by angaither** [comment]
@DFurnes mind taking a look at this, didn't you do this before?
