### ISSUE TITLE
RB Image Upload Error Message Doesn't Vanish

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5590]
In Part 4 of campaigns where pic is uploaded, if pic smaller than 480 x 480 is uploaded, error messages won't disappear from previous failed upload attempts even when pic larger than 480 x 480 is finally posted.

To recreate: try to reportback with a photo on an iphone that is less than 480 by 480, get an error message. Try to reportback with a photo that is at least 480 by 480, error message persists. Not a problem on desktop, but happens in at least MX and US and GL EN.

![image](https://cloud.githubusercontent.com/assets/12396076/10674154/923afb9c-78c7-11e5-927d-5e8a1878d1fe.png)

**Comment by namimody** [comment]
@julielorch reported this as an issue on desktop yesterday via Brazil (while testing the interim experience before Portuguese content is published). Which milestone should we put it in @angaither?

**Comment by mikefantini** [comment]
Added this to 1.1. If we get Zendesk questions we can prioritize accordingly.
