### ISSUE TITLE
Header Nav Doesn't Adhere to Country When Entering Explicitly

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5593]
If I am in the US, go to https://thor.dosomething.org/mx (without using TorGuard), and click the logo or "Explore Campaigns" in the header nav, I get brought to:

logo: https://thor.dosomething.org/us/node/1141
Explorar Campanas: https://thor.dosomething.org/us/campaigns

These are both US translations of the site, not /mx versions.

Although static content is not set up yet, clicking "what is dosomething.org" on /MX brings me to: https://thor.dosomething.org/mx/about/who-we-are (where I currently get 404d, but at least the /mx appendix is on the URL.

**Comment by angaither** [comment]
@namimody I think this was tested before the header branch refactor stuff
I'm going to close this out and we can reopen if it's still an issue

**Comment by namimody** [comment]
@angaither this is still an issue. :/ if I click on the DS logo or "explorar campanas" from the header nav, while at https://thor.dosomething.org/mx (arrived their explicitly, not using TorGuard), I get redirected to https://thor.dosomething.org/us and https://thor.dosomething.org/us/campaigns, respectively. Shouldn't these links go to /mx versions?

**Comment by angaither** [comment]
@namimody don't think so since you aren't using torguard

**Comment by mikefantini** [comment]
Yeah I think we can re-close this. We want people to be able to go directly to country specific links regardless of their location, but when they navigate our site, we want to give them an experience that is specific to their location (i.e. taking them to /us/campaigns or /us on the homepage).

cc: @julielorch
