### ISSUE TITLE
Stripped formatting in mb-new-user-register-BR

### ISSUE THREAD

**Issue by ArielSD** [DoSomethingArchive/legacy-website#5595]
After inputting translated Portuguese content into the template, proper formatting is stripped. 

https://us4.admin.mailchimp.com/templates/edit?id=56673

**Comment by ArielSD** [comment]
@sbsmith86 Just checking up on this one, you think it'll be an easy fix? I know you're swamped, thank you!

**Comment by sbsmith86** [comment]
@ArielSD sorry for the delay. Just fixed this template and moved it into mandrill. Let me know if all looks good!

**Comment by sbsmith86** [comment]
Closing until I hear otherwise.

**Comment by ArielSD** [comment]
@sbsmith86 The mb-user-register-br template looks perfect, thank you!

Weird thing happend: I just had to edit the mb-user-register-us template, and it became too wide again:

https://us4.admin.mailchimp.com/templates/edit?id=56653

**Comment by ArielSD** [comment]
@sbsmith86 It looks like this happens whenever we edit content in the UI? Just to let you know, we still might make edits, so please hold on this until we have final copy; we don't want you doing extra work! CC: @namimody

**Comment by angaither** [comment]
@ArielSD is going to update the templates in the code itself, closing!
