### ISSUE TITLE
Digest chrome translation 

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5596]
Translate chrome of digest into Brazilian, Portuguese and Mexican Spanish.

**Digest MailChimp Templates**: 
https://us4.admin.mailchimp.com/templates/#f_folder:113;t:template-list
- Global: https://us4.admin.mailchimp.com/templates/edit?id=56741
- MX (Mexico): https://us4.admin.mailchimp.com/templates/edit?id=56733
- BR (Brazil): https://us4.admin.mailchimp.com/templates/edit?id=56737
- US (United States): https://us4.admin.mailchimp.com/templates/edit?id=56729
- **Campaign row in digest message**: Translation of "Did It? Prove It!" button:
  ![image](https://cloud.githubusercontent.com/assets/2119264/10924875/f63b8a32-8257-11e5-9b7f-61498b94b7b0.png)

**Comment by mikefantini** [comment]
@marahml what are all the different phrases that need to be translated? "DID IT? PROVE IT!" and "News from the team" seem to need translation anything else?

@DeeZone @weerd do either of you have any thoughts on how we would do this?

Also can some of the content be translated on the template itself? I.e. the content that appears here on the MX template:

![image](https://cloud.githubusercontent.com/assets/6330971/11503704/e723288e-980f-11e5-8321-ddd9049becc1.png)

**Comment by deezone** [comment]
@mikefantini From the tech perspective, translated is needed for:

As you suggested...
- DID IT?
- PROVE IT!
- "News from the team" 

These three are in the Drupal app which are sent to Message Broker as `merge_vars` in the request payload.

Any text in the banner, in this case:
- Here's how to crush it - even harder than you already are.
- Ready to rock your campaigns?
- You signed up for these campaigns. Score! Now use our pro tips to rock them and send pics of your impact.

These additional translations would be managed in the template within MailChimp and sent to Mandrill when ready for deployment.

**Comment by mikefantini** [comment]
Hmm ok thanks @DeeZone. @DeeZone or @weerd do either of you have any idea where these are located off the top of your heads?

Also do we know how we would get the translations to appear properly in the digest?

cc: @angaither

**Comment by deezone** [comment]
Correction, not in the Drupal app at all, my bad!
- **"News from the team"** - https://github.com/DoSomething/mbc-digest-email/blob/master/src/MBC_DigestEmail_MandrillMessenger.php#L153
- **"Did It. Prove It"** - https://github.com/DoSomething/mbc-digest-email/blob/master/templates/campaign-markup.inc#L26

> Also do we know how we would get the translations to appear properly in the digest?

The changes will have to be managed / applied at the template / HTML / CSS / code level.

The rest is at the template level in MailChimp as your example points out.

**Comment by mikefantini** [comment]
Wait but so @DeeZone do you know how/where to create translations for "News from the team" and "Did It? Prove It!"

Also is @mnelson338 aware that translated content is needed for this?

**Comment by weerd** [comment]
Don't know off hand. Are these items that could be POT-ified?

**Comment by deezone** [comment]
> Wait but so @DeeZone do you know how/where to create translations for "News from the team" and "Did It? Prove It!"

_Yes_, just need the actual translated text. It will be managed in files here: 
https://github.com/DoSomething/mbc-digest-email/tree/master/templates

> Also is @mnelson338 aware that translated content is needed for this?

Something @marahml and / or @ArielSD are coordinating.

@weerd Sorry, no "POT-ified" magic available here.

**Comment by mikefantini** [comment]
Ok so @DeeZone I'm going to assign over to you then since it seems like we just need the actual copy translated.

@mnelson338 can you please work to get translations for "News from the team", "Did It? Prove It!", and all content this template translated?

https://us4.admin.mailchimp.com/templates/edit?id=56757

**Comment by mnelson338** [comment]
Translations: 
Did it? Prove it! 
Spanish: ¿Lo hizo? Prov él!
Portuguese: Fez isso? Prov-lo!

News from the team
Spanish: Noticias del personal
Portuguese: Notícias da equipe

@mikefantini I don't have a log in to mailchimp, so can't access the template. If you can direct me to the right person I can get it set up. Thanks!

**Comment by deezone** [comment]
@mnelson338 Do you have access to LastPass? There's an entry for MailChimp access or you can come poke me for the password. 

@ArielSD can coordinate the template work for Global Digest. The templates of interest are:
- **Brazil: mb-digest-v1_0-br**: https://us4.admin.mailchimp.com/templates/edit?id=56757
- **Mexico: mb-digest-v1_0-mx**: https://us4.admin.mailchimp.com/templates/edit?id=56749
- **Global: mb-digest-v1_0-gl**: https://us4.admin.mailchimp.com/templates/edit?id=56745

**Comment by ArielSD** [comment]
@mnelson338 
We need to translate the subject lines as well. Please let me know how I can help:

```
  'Your weekly DoSomething campaign digest',
  'Your weekly DoSomething.org campaign roundup!',
  'A weekly campaign digest just for you!',
  'Your weekly campaign digest: ' . date('F j'),
  date('F j') . ': Your weekly campaign digest!',
  'Tips for your DoSomething.org campaigns!',
  'Comin\' atcha: tips for your DoSomething.org campaign!',
  '*|FNAME|* - It\'s your ' . date('F j') . ' campaign digest',
  'Just for you: DoSomething.org campaign tips',
  'Your weekly campaign tips from DoSomething.org',
  date('F j') . ': campaign tips from DoSomething.org',
  'You signed up for campaigns. Here\'s how to rock them!',
  'Tips for you (and only you!)',
  'Ready for your weekly campaign tips?',
  'Your weekly campaign tips: comin\' atcha!',
  'Fresh out the oven (just for you!)',
```

**Comment by marahml** [comment]
Just catching up here - and looks like everyone's on it. Thanks for handling team and let me know if you need anything!

**Comment by deezone** [comment]
@ArielSD @mnelson338 We'll also need the From settings for the global digest emails (BR & MX) as well:
- From name: ("DoSomething.org" in US digest)
- From address: ("help@dosomething.org" in US digest)

**Comment by mnelson338** [comment]
@DeeZone @ArielSD  Here are the digest translations: https://docs.google.com/spreadsheets/d/1r_qsX6xZqiwZ1ze3K-V4AXjDOnpjOs0skK5VOat58Ng/edit#gid=0 

Let me know if there is anything else

**Comment by deezone** [comment]
@mnelson338 Thanks for the translations, they look good.

Any thoughts on the Digest message settings for:
- From name: ("DoSomething.org" in US digest)
- From address: ("help@dosomething.org" in US digest)

Should the same values be used for the other languages?

**Comment by mnelson338** [comment]
@DeeZone 

From name should remain the same for all translations 
From address: 
US + Global -- help@dosomething.org 
Brazil -- ajuda@dosomething.org 
Mexico -- ayuda@dosomething.org

**Comment by deezone** [comment]
@mnelson338 : ayuda@dosomething.org is functional? Do we need to poke someone to let them know the digest is using it?

**Comment by marahml** [comment]
@DeeZone we're also using that for member support. Hannah is monitoring!

**Comment by deezone** [comment]
Application of translations will be tracked on the related Trello card: https://trello.com/c/YsQDnoEp
