### ISSUE TITLE
Some Static Content Appears w/o Titles in Search

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5615]
![image](https://cloud.githubusercontent.com/assets/12396076/10704276/c96664b2-79a3-11e5-9afe-dc0935f478f5.png)

![image](https://cloud.githubusercontent.com/assets/12396076/10704282/db9b4eae-79a3-11e5-9e12-b64a3a882a5a.png)

![image](https://cloud.githubusercontent.com/assets/12396076/10704299/ed7346ae-79a3-11e5-9679-5ddbdb2dde16.png)

**Comment by angaither** [comment]
hmm, I thought maybe there wasn't a US translation of this, but that's just not true. @blisteringherb mind taking a look at this?

**Comment by blisteringherb** [comment]
As a quick fix for these, resaving the node and reindexing fixes the issue. It's clearly not ideal. I'm wondering if some of the static content field work may have impacted these nodes. Any thoughts @sergii-tkachenko?

**Comment by sergiitk** [comment]
Could be. I'll take a look at this later, working on higher priority now.

**Comment by sergiitk** [comment]
@blisteringherb Yes, I was related to #5575. The content needed to be reindexed. This was a one one-time thing related to change in the title field representation.
@namimody Good to close this?

**Comment by blisteringherb** [comment]
:+1:  Thanks @sergii-tkachenko

**Comment by namimody** [comment]
@sergii-tkachenko @angaither @blisteringherb sorry, to clarify -- reindexing the content fixes the bug. however, is it expected that we would still see this on thor? thanks!

https://thor.dosomething.org/us/search/apachesolr_search/resources
![image](https://cloud.githubusercontent.com/assets/12396076/10825196/47db8ff8-7e3a-11e5-8129-0146f16a04cb.png)

**Comment by sergiitk** [comment]
@namimody I'm not sure if the content has been reindexed on thor. Let do that.

**Comment by sergiitk** [comment]
Reindex didn't help. Lets wait for Thor to be updated with latest dev changes (#5663) and revisit this issue.

**Comment by sergiitk** [comment]
Ok, latest global build fixed the issue:
![image](https://cloud.githubusercontent.com/assets/672669/10827388/530c1086-7e77-11e5-88ed-ac5b574107b2.png)

**Comment by namimody** [comment]
Thanks team! :D Closing.
