### ISSUE TITLE
Campaign Title Doesn't Update in Search

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5617]
Campaign "Don't Be A Sucker" changed to "Just Pull Out" (yep) with CTA "Don't take any chances, breh." by an "Administrator" on the site. The translation updated was unpublished.

The title changed on campaign page (and the site was accessible via an incognito anon window?), but searching for the new title didn't yield results, while searching for the old title did, because the translation was unpublished. The old title, however, is paired with the new CTA. Clicking on the old title (paired with new CTA) in search results brings you to the newly titled campaign (with updated URL). 

Campaign Page:
![image](https://cloud.githubusercontent.com/assets/12396076/10704751/14d10e86-79a7-11e5-904e-d4ba30cadfcc.png)

Search Results:
![image](https://cloud.githubusercontent.com/assets/12396076/10704761/29c8c2a2-79a7-11e5-9c5c-ad9ebbe33e22.png)

![image](https://cloud.githubusercontent.com/assets/12396076/10704769/3a09f74e-79a7-11e5-88c9-eba51f26ddce.png)

**Comment by angaither** [comment]
not a safe method. @blisteringherb probably just re-index solr, right?

**Comment by blisteringherb** [comment]
@angaither yup, reindexing should fix that

**Comment by namimody** [comment]
Andrea and Morgan's comments above reference remedying the title of the campaign not changing in search.

**Comment by namimody** [comment]
@mikefantini I'm going to close this -- looking back, I think it addressed two "issues":
- unpublished content being accessible to non admin/inauthenticated users, which is now fixed
- campaign titles not updating in search was just because it needed to be reindexed
