### ISSUE TITLE
Figure out if having "site admin" role doesn't allow you to create campaigns

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5619]
![image](https://cloud.githubusercontent.com/assets/12396076/10706510/675f6a36-79b5-11e5-9d30-ea4e7f0f320d.png)

Michaela has site admin, member support, and editor roles and cna't create a campaign.

**Comment by angaither** [comment]
hmm, I don't think site admin role is the problem. drupal should take the highest permission and use that. 

also, I just tested with those roles and it to worked ok. 
what error does she get when she tries to create a campaign?

**Comment by namimody** [comment]
@angaither she can use the admin nav to create a campaign, then fills out all the content, then hits save and gets returned to /edit with no content and these errors: 

![image](https://cloud.githubusercontent.com/assets/12396076/10734298/f80af9cc-7bd8-11e5-8dc2-fee86cb49893.png)
