### ISSUE TITLE
Users should be able to access GL EN content if translation is unpublished or does not exist in their region

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5620]
If a user is coming from Mexico and a campaign has a published translation in GL EN but MX SP translation either doesn't exist or is unpublished, then the Mexican user should 1. have the GL EN content surface via SOLR (finder/search/ /campaigns) 2. be able to access that content (i.e. not get 404'd).

MX user:
- GL EN = published
- MX SP = published
- go to www.dosomething.org/campaigns/sea-turtle-street-sweep, get redirected to https://www.dosomething.org/mx/voluntario/limpieza-de-calles-por-la-tortuga-marina and see MX SP content

MX user:
- GL EN = published
- MX SP = unpublished or does not exist
- go to www.dosomething.org/campaigns/sea-turtle-street-sweep, I get GL EN content

---

Coming from US as an anon user.

Re-poppin Bottles and Quote of a Champion have published translations in GL EN but not US EN. The GL EN versions show up in solr, but if hover over them they show a URL like, "thor.dosomething.org/us/campaigns/quote-champion"

![image](https://cloud.githubusercontent.com/assets/12396076/10706983/8c0c872e-79ba-11e5-88f6-9d65e225b5b9.png)

and you get 404'd when you click:
![image](https://cloud.githubusercontent.com/assets/12396076/10706986/9d47e808-79ba-11e5-8b09-a096c7ae486d.png)

**Comment by mikefantini** [comment]
This is desired bahvior.

**Comment by namimody** [comment]
@mikefantini sorry, a bit confused -- I thought that if the GL EN version existed and the US EN version didn't, US members could see the GL EN version?

**Comment by mikefantini** [comment]
Oops didn't read comment closely enough. Closed too soon.

This only seems to be an issue when a US EN version _did_ exist and then is unpublished. I.e. I created a new campaign only in GL EN and am able to access that fine as a US user (authenticated or anonymous).

https://thor.dosomething.org/campaigns/english-global-only

**Comment by mikefantini** [comment]
Since any of our GL EN campaigns will have started as US EN campaigns for launch I'm moving this to 1.1

**Comment by itsjoekent** [comment]
happening for administrator accounts as well

**Comment by angaither** [comment]
@namimody sorry, a little unclear
should these not appear in search, or should the user get taken to a non-prefixed URL?

**Comment by namimody** [comment]
@angaither I believe it's like this:
- if a published campaign is in GL EN but not US EN, a GL EN or US EN user should see the GL EN translation in search and sign up
- the bug is that if a US EN campaign was published once but has since been unpublished, but a GL EN version is published, solr surfaces the US EN version of the campaign, and clicking on it 404s for anon users and signed-in-non-admin users. 
- at one point, this behavior was also occurring for admins, but that behavior seems to have resolved itself.

**Comment by angaither** [comment]
@deadlybutter can you take a look at this one?

**Comment by blisteringherb** [comment]
@deadlybutter I started trying to figure a related issue out. It seems that the apachesolr_multilingual module indexes unpublished translations. I believe line 131 of the apachesolr_multilingual module does this:

`if ($langcode != $original_langcode && LANGUAGE_NONE != $langcode)`

when it should be doing this

`if ($langcode != $original_langcode && LANGUAGE_NONE != $langcode && $entity_translation['status'] ==1 )`

That fixes indexing unpublished translations. The harder issue to fix is removing a translation from the Solr index when it gets unpublished, but I don't have a fix for that just yet.

**Comment by itsjoekent** [comment]
awesome, if you can fix the solr issues I'll keep focusing on the redirect problem. 

I've made the logic which fixes the problem itself, but consequently made a redirect loop. workin on a solution to that now.

EDIT: fix is here: https://github.com/DoSomething/phoenix/compare/dev...deadlybutter:5620?expand=1#diff-359ccdb85a973fa7f0b7f6677e963466

**Comment by mikefantini** [comment]
Hmmm ok @deadlybutter documenting here:

It seems to be working properly from US testing. One thing I noticed however is that when I went to create a GL EN only campaign with my admin account, after I published it I was redirected to https://thor.dosomething.org/us/campaigns/gl-en-test and got the following error message.

![image](https://cloud.githubusercontent.com/assets/6330971/11701021/2e764086-9e9b-11e5-93dc-806c7063104e.png)

However, when I go to https://thor.dosomething.org/campaigns/gl-en-test I am staying on https://thor.dosomething.org/campaigns/gl-en-test and seeing the GL EN content as an anonymous user, as a non-admin authenticated user with language set to English, and then with my admin account, which is the desired behavior. So maybe it's just a weird issue when I was creating a GL EN campaign from /us/node/add/campaign?

**Comment by mikefantini** [comment]
Just wrapped up testing and it all looks good to me.

One thing I'll note though is that there is an inconsistency between Brazilian visitors and French visitors when visiting the unappended URL of a campaign that only has a US EN translation.
- Anonymous user in Brazil goes to thor.dosomething.org/campaigns/thumb-wars gets redirected to thor.dosomething.org/us/campaigns/thumb-wars
- Anonymous user in France goes to thor.dosomething.org/campaigns/thumb-wars gets the Global translation unavailable page.

Probably not a big deal because the real solution is probably coming up with a smarter 404 that notifies users which translations exist and allows them to explicitly navigate to them, but just bizarre that the two behaviors are different.

@deadlybutter do you have any thoughts on why this might be? Again, probably not a huge deal.

**Comment by itsjoekent** [comment]
@mikefantini anonymous or authenticated?
