### ISSUE TITLE
Data Storage Check

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5621]
Hi @angaither! Could you check the following things in Northstar? :)
- [x] nmody+brazilian@dosomething.org's country is stored as Brazil and number is stored as 212-929-9571
- [x] nmody+mexican@dosomething.org's country is stored as Mexico and number is stored as 718-249-1151
- [x] nmody+worldcitizen@dosomething.org's country is stored as Luxembourg 
- [x] nmody+american@dosomething.org's country is stored as US and number is stored as 718-529-3518

Thank you! 

For reference, relates to: https://docs.google.com/spreadsheets/d/1uMpdZxa94akk8FTXVLl0zWdEj578LjtUVdONVjVlPvw/edit#gid=1731726767

**Comment by angaither** [comment]
@namimody thor northstar?

**Comment by namimody** [comment]
@angaither si! gracias!

**Comment by angaither** [comment]
@namimody all looks :+1:
