### ISSUE TITLE
Authenticated users should not be able to access action guides

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5627]
Currently as an authenticated user I'm able to access an action guide by going directly to the node. 

Access to action guides should behavior the same way Images or Campaign Runs do, users can see them on the campaign, but not if they go directly to the image node.

![image](https://cloud.githubusercontent.com/assets/6330971/10739382/7f30b7c0-7bf2-11e5-97c5-d2fb75295d24.png)

**Comment by angaither** [comment]
needs to be a [staff only content type](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L147)

**Comment by mikefantini** [comment]
This was all happening on thor with user 3118816.

Also happening on production.

Moved the other issue we were seeing here https://github.com/DoSomething/ServerConfig/issues/80

**Comment by angaither** [comment]
@mikefantini while we are here, besides these node types, should we revoke access to any other type? `('fact', 'image', 'campaign_run')`

**Comment by mikefantini** [comment]
Hmmm @angaither not sure about `not_found`.

I don't know enough about how the 404 page functions to say, but we don't really want anyone going directly to those _nodes_ right?

**Comment by angaither** [comment]
it'll just appear as a page not found, funny how that works, def not crucial, but we can hide them.
