### ISSUE TITLE
Hacky header translation business!

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#5629]
Due to an issue with translation and nested field collections, we can't translate static content nodes. (Come on, Dries!) Instead, we're going to make a unique node for each country and link to the relevant node IDs for each country's header & footer settings.

Via @mshmsh5000 in Slack:

> Matt Holford [4:09 PM]
> Soooo if the header and footer are both manually manageable per country, then we should be able to create new static content nodes for any static content nodes we’d like to translate that have galleries.
> 
> Matt Holford [4:09 PM]
> We’ll lose any Drupal-side redirect business: Specifically, if I hit `/about/who-we-are` from Mexico, and we’ve created a separate node for the Mexican version of that page, I won’t get automatically redirected to the correct page.
> 
> Matt Holford [4:10 PM]
> For the cost of that, we’ll have the ability to enter all translated static content without having to fix the field collection translation bug that’s currently broken ​_for the entire world,_​ not just for us.

**Comment by sergiitk** [comment]
Ref #5628.
