### ISSUE TITLE
Global Transactional Email Updates

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5630]
BRAZIL:
The new member transactional email mentions help@dosomething.org, but should ask people to email "ajuda@dosomething.org"

GLOBAL:
The help center shouldn't be included because it discusses scholarships and things, would be great to swap this out and link to the global FAQ page. (Link to come)

MEXICO:
All good!

US:
Where the new member and reportback transactional emails link to dosomething.org/campaigns -- they should actually link to dosomething.org/us/campaigns. However, this new URL won't exist until we launch global -- will changing the templates I received via Thor change the templates currently being sent via prod?

Thanks!

**Comment by ArielSD** [comment]
@namimody Everything is updated except your last question: We have one set of templates for Global/U.S., so changing the template you receive via Thor will change the template currently being sent via production. We can change it RIGHT when the URL is live?

**Comment by namimody** [comment]
Updates to erroneous first comment in thread:

GLOBAL/US NEW MEMBER TRANSACTIONAL TEMPLATE:
- @ArielSD the global/US template for v 1.0 should link to https://www.dosomething.org/about/faq beneath Ben's face and should not mention the help center. Please ask Ben for sign off on copy!
- regarding the "explore campaigns" button -- this can link to dosomething.org/campaigns. this URL will redirect.

cc @marahml

**Comment by ArielSD** [comment]
@marahml @namimody 
Copy is updated to push to /faq under Ben's face. We're mentioning GTFO and Teens for Jeans in the body, which are U.S. specific- going to ben for copy edit's now. 
Thanks!

**Comment by angaither** [comment]
@ArielSD is going to update the templates in the code itself, closing!

**Comment by angaither** [comment]
wrong issue!

**Comment by ArielSD** [comment]
@namimody I just changed the links in the U.S. New User and Reportback emails to /us/campaigns. Right now, anything not from Mexico or Brazil is receiving these. We have another issue for Global templates to be created:

https://github.com/DoSomething/phoenix/issues/5090

**Comment by namimody** [comment]
Hey @ArielSD sorry for the confusion, in my latest comment I noted that I was wrong and that dosomething.org/campaigns would redirect for users. Can we change this? Sorry about that.

**Comment by ArielSD** [comment]
Ah, @namimody you're exactly right, I missed that. Reverted! Do we need anything else to close this issue?

**Comment by namimody** [comment]
I think we are all set -- thanks @ArielSD!
