### ISSUE TITLE
mailchimp_list_id for Global users

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5635]
**BLOCKING**:
- https://github.com/DoSomething/phoenix/issues/5499

When any `dosomething_mbp` transaction requires the `mailchimp_list_id` value. The value is looked up by `dosomething_signup_get_mailchimp_list_id()` (https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L655-L675)

```
  ...

  global $user;
  $user_language = $user->language;
  $country_code = dosomething_global_convert_language_to_country($user_language);
  $field_name = "dosomething_signup_" . strtolower($country_code) . '_mail_list_id';
  return variable_get($field_name);
```

In the case where the user is global (non-affiliate or US) the `user_language` is `en-global` which is not a value supported by `$field_name = "dosomething_signup_" . strtolower($country_code) . '_mail_list_id';`. The result is an empty `mailchimp_list_id` value.

**Solution**:
- Rename the `dosomething_signup_global_mail_list_id` system variable to `dosomething_signup_en-global_mail_list_id`

**Comment by angaither** [comment]
@DeeZone 

three possible solutions here

1 set the country code to global if none is returned

```

  global $user;
  $user_language = $user->language;
  $country_code = dosomething_global_convert_language_to_country($user_language);
  if (empty(country_code)) {
    $country_code = 'global'
   }
  $field_name = "dosomething_signup_" . strtolower($country_code) . '_mail_list_id';
  return variable_get($field_name);

```

2  return a default value of the global list id, if no variable for the country is found. 

```
  $field_name = "dosomething_signup_" . strtolower($country_code) . '_mail_list_id';
  return variable_get($field_name, 'varialbe_get('dosomething_signup_global_mail_list_id');
```

3  if no list id is returned, get the global list id

```
 $list_id =  variable_get($field_name, 'varialbe_get('dosomething_signup_global_mail_list_id');
 if (empty($list_id)) {
  $list_id = variable_get('dosomething_signup_global_mail_list_id');
 }
'''
```

**Comment by deezone** [comment]
@angaither Would it a better alternative to make this change further up the "code chain":

```
function dosomething_global_convert_language_to_country($language) {
  $lang_map = variable_get('dosomething_global_language_map', '');
  $country_code = $lang_map[$language]['country']
  if (empty($country_code)) {
    $country_code = 'global';
  }
  return $country_code;
}
```

from:

```
function dosomething_global_convert_language_to_country($language) {
  $lang_map = variable_get('dosomething_global_language_map', '');
  return $lang_map[$language]['country'];
}
```

**Comment by angaither** [comment]
@DeeZone I think that might be a tad confusing since that function should return a country code and `global` is node a two letter country code.
