### ISSUE TITLE
ds script assumes sandbox environment

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#564]
If the ds script is to work outside of sandbox instances, we need to provide for variations in MySQL connection strings. So two immediate places to address:

[Initial DB catalog creation](https://github.com/DoSomething/dosomething/blob/dev/bin/ds#L95)

[drush site-install](https://github.com/DoSomething/dosomething/blob/dev/bin/ds#L157)

I imagine the best approach to this will be env vars, a la [this approach](https://github.com/DoSomething/dosomething/issues/472#issuecomment-33823884).

**Comment by desmondmorris** [comment]
I believe this is addressed with this: https://github.com/DoSomething/dosomething/pull/860.  Safe to close?

**Comment by barryclark** [comment]
@aaronschachter @mshmsh5000 safe to close?
