### ISSUE TITLE
Reportback Items API: status property is null for all Reportback Items

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#5653]
![screen shot 2015-10-28 at 9 14 35 am](https://cloud.githubusercontent.com/assets/1236811/10794895/5f0ba6f4-7d54-11e5-8910-b1500bcf8cac.png)

**Comment by weerd** [comment]
Something got borked with the query and it is no longer returning the `status` in the returned query object. Looking into it and will provide a fix to restore.

**Comment by weerd** [comment]
Ok, so the query isn't borked it's a permission thing. Do we want to expose `status` for anonymous `GET` requests? And what about `flagged` and `why_participated`? Were we being prematurely cautious or is there legit reasons why we shouldn't expose those?

https://github.com/DoSomething/phoenix/blob/be73e4c425d986f71174c17393c7e61695ccf5dd/lib/modules/dosomething/dosomething_reportback/dosomething_reportback_item.query.inc#L75-L79

@aaronschachter @angaither

**Comment by weerd** [comment]
Technically, it should still be filtering the queries by the specified status (if one is supplied other than the default of `approved`, it's just not showing what the status is for each item when it's an anon request.

**Comment by weerd** [comment]
One option to help is that we could make it so anon requests will reveal the status, but items with a status of `excluded` and `flagged` are not included in the response?

**Comment by aaronschachter** [comment]
That sounds logical to me, it does bring up a minor question of whether or not we want to expose what's published vs. approved publicly though... to those h8ck0rz out there who are trying to determine if their Reportback Item made the grade. I would be fine with it being public.

**Comment by weerd** [comment]
LOL. we could add `pending` to the list of stuff to not show for anons ;)

**Comment by weerd** [comment]
Ok, so @aaronschachter and I discussed it further and these are the updates to address how results are returned for items based on `status`:

**Default request:**
- will now return both `approved` AND `promoted` items.

**Anonymous `GET` requests:**
- will _not_ include `pending`, `excluded`, and `flagged` items
- will ignore requests with query params asking for above mentioned statuses: `?status=excluded` return 0 items

**Authenticated `GET` requests:**
- with no query params, returns expected default
- can override default and use query params to request any of the statuses (multiple statuses also works): `?status=promoted,approved,pending`

@uy fyi on upcoming updates to the returned items

cc: @angaither
