### ISSUE TITLE
scholarships in global transactional user_registration email

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5654]
The transactional email for **global** user registrations (https://us4.admin.mailchimp.com/templates/edit?id=56653) mentions scholarships. The `mb-user-register-us` MailChimp template is used for both US and Global users.

![image](https://cloud.githubusercontent.com/assets/2119264/10795216/2ebf3554-7d6f-11e5-91c5-7f53af17a256.png)

**Comment by marahml** [comment]
GREAT flag @DeeZone. @ArielSD can you remove?

Thanks!

**Comment by ArielSD** [comment]
@DeeZone @marahml Edited and closing- do we need to created separate templates for Global and U.S.?

**Comment by deezone** [comment]
@ArielSD 

> do we need to created separate templates for Global and U.S.?

Good question. I suspect you're right, a seperate template would allow for different messaging between the US and the world.

Perhaps create an issue with the Global 1.1 tag as well as a related Trello card for the Message Broker board.
