### ISSUE TITLE
Turn off 'User' content language detection strategy on dev branch?

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5657]
Do we need `User` Content language detection on US now?
![image](https://cloud.githubusercontent.com/assets/672669/10802360/285b6ef2-7dc5-11e5-9cca-651dd8946573.png)

We have 1330 users (including 20 from the US) that have other than US English language set in their profile (most of those are set to `en-global`). Some pages that are not supposed to be translatable look wrong for them because Drupal tries to display content fields in language of their preference, but it does not exists for this content, see #5647.
I don't know if we're using `$user->language` for non-admin users at all.

If we really don't need it, I'd suggest to turn it off. Thor lunch will do this anyway:
![image](https://cloud.githubusercontent.com/assets/672669/10802470/bf5a8586-7dc5-11e5-8291-2f3374031ad5.png)

Before launching Thor it makes total sense to fallback all content to English.

---

@mshmsh5000 @angaither @blisteringherb @mikefantini

**Comment by angaither** [comment]
if `global` branch removes this, turn it right off then!

**Comment by mshmsh5000** [comment]
+1

CTO
@mshmsh5000 http://twitter.com/mshmsh5000 @dosomething
http://twitter.com/dosomething
