### ISSUE TITLE
Potentially refactor how language code is acquired.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5664]
Where we are retrieving and setting the language code here:
https://github.com/DoSomething/phoenix/blob/a37f06325cd4dd13495be1f5e13c952676d2ead2/lib/modules/dosomething/dosomething_fact/dosomething_fact.module#L90

Might be easier to user this helper function instead:
https://github.com/DoSomething/phoenix/blob/a37f06325cd4dd13495be1f5e13c952676d2ead2/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L578

Test to make sure that what is returned as the language code is actually based on the url path, because that is what we require for how we decided what regional Fact content to show.

cc: @angaither

**Comment by itsjoekent** [comment]
I think this requires a bigger discussion planning, as I think a few parts of the code will need to be refactored. The big problem comes down to when a single country has two languages, as currently all of our functions assume its 1 lang per country 
_(TLDR: We need to decouple the country and language logic)_

Did some research and I think this is our best option. We'll create a new function to read the "Accept-Language" header all browsers should be sending. Whats great about this header is that it sends the sub code as well if its one of those cases where its not the primary language of the country. From the W3 website,

> Mainstream browsers allow these language preferences to be modified by the user. The value itself is a defined by BCP 47, typically as a two or three letter language code (eg. fr for French), followed by optional subcodes representing such things as country (eg. fr-CA represents French as spoken in Canada).

Debugging will be more annoying cause I'm not sure how we'll be able to fake this / override the browser (we can edit our browser language I guess), however the alternative is storing a giant list of cities and there associated language, and comparing that on every request. Not ideal.

**Comment by itsjoekent** [comment]
I'll prototype around with that ^ and report my findings

---

This is the rule I'll follow _(running on the assumption we're adding a language selector)_

Anonymous user: 
- Get Country => Fastly
- Get Language => Accept User Lang header

Auth user:
- Get country => Fastly 
- lang when signing up => Accept User Lang header
- lang everywhere else => User lang

The user lang header technically comes with the matching country, however
1) According to W3 it's not always sent
2) Our country logic should stay the way it is so we know when to call them a global user or not

**Comment by itsjoekent** [comment]
Started implementing ^^, so far everything works :ok: 

all the refactoring I've done so far --> 
https://github.com/DoSomething/phoenix/compare/DoSomething:dev...deadlybutter:5664

**Comment by itsjoekent** [comment]
Refactoring the preprocess helper and message broker uses is proving to be fun (the MB one isn't super important as it correctly uses headers 99% of the time)

(for reference here is the PR for the helpers.inc https://github.com/DoSomething/phoenix/pull/5275 )

helpers.inc is a tough one https://github.com/DoSomething/phoenix/blob/8982c7d9c8021b6fdb46ff3a92bd7a40b64712a5/lib/themes/dosomething/paraneue_dosomething/includes/helpers.inc#L396

**Comment by itsjoekent** [comment]
this needs to be refactored with the logic being introduced https://github.com/DoSomething/phoenix/pull/5727/files#diff-4d5c67be6fe19a956caa33c45ac022cbR160
