### ISSUE TITLE
404 Not Fount nginx/1.4.6 (Ubuntu) error when trying to access MX Campaign

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5667]
I am located in the US and trying to access the Mexican translation of a campaign by going directly to the url: https://thor.dosomething.org/mx/voluntario/limpio-y-ecol%C3%B3gico and I get a 404 Not Fount nginx/1.4.6 (Ubuntu) error.

I'm logged in as an admin. Here is the edit URL: https://thor.dosomething.org/mx/node/3413/edit/es-mx

![image](https://cloud.githubusercontent.com/assets/6330971/10837439/ce50fd2a-7e8f-11e5-8a9f-2cdc9ca23631.png)

**Comment by mikefantini** [comment]
All translations are published. I'm able to view the Brazilian translation. And I've been able to view other Mexican versions on other campaigns.

**Comment by angaither** [comment]
ahh, tilda in the url perhaps?

**Comment by mnelson338** [comment]
Hola - saw it on this campaign: https://thor.dosomething.org/us/node/5639/ 

I can't access the user facing view in Portuguese or Spanish but I can access the admin view

**Comment by angaither** [comment]
it's def b/c of the tilda, when you go to the node/nid, it works
https://thor.dosomething.org/br/node/5639/
https://thor.dosomething.org/mx/node/5639/

**Comment by sergiitk** [comment]
@angaither It's not. If you delete just last o, it works (drupal 404, as expected):
https://thor.dosomething.org/mx/voluntario/limpio-y-ecológic

@sheyd I can't see https://thor.dosomething.org/mx/voluntario/limpio-y-ecol%C3%B3gico in thor's access log, could it be app routing on the upper level, like varnish?

**Comment by sergiitk** [comment]
Hm. this request isn't in varnish either.

**Comment by sergiitk** [comment]
What is really really really weird:
- This doesn't work (with ó replaced with normal o) https://thor.dosomething.org/mx/voluntario/limpio-y-ecologico
- This doesn't work (with random get method) https://thor.dosomething.org/mx/voluntario/limpio-y-ecológico?x=2sdfsdfsdfsdfsdf
- This works (without last letter) https://thor.dosomething.org/mx/voluntario/limpio-y-ecológic

**Comment by sergiitk** [comment]
These don't (WHAT?):
- https://thor.dosomething.org/mx/voluntario/limpio-y-aaaaaaaaaaaico
- https://thor.dosomething.org/mx/voluntario/aaaaaa-a-aaaaaaaaaaaico
- https://thor.dosomething.org/mx/voluntario/aaaaaaaaaaaico
- https://thor.dosomething.org/mx/voluntario/aico
- https://thor.dosomething.org/mx/a/aico
- https://thor.dosomething.org/mx/aico
- https://thor.dosomething.org/aico

**Comment by sergiitk** [comment]
All chars seems to be fine:

```
0000000    h   t   t   p   s   :   /   /   t   h   o   r   .   d   o   s
          104 116 116 112 115  58  47  47 116 104 111 114  46 100 111 115
0000020    o   m   e   t   h   i   n   g   .   o   r   g   /   m   x   /
          111 109 101 116 104 105 110 103  46 111 114 103  47 109 120  47
0000040    v   o   l   u   n   t   a   r   i   o   /   a   i   c   o
          118 111 108 117 110 116  97 114 105 111  47  97 105  99 111
0000057
```

**Comment by sheyd** [comment]
@angaither @sergii-tkachenko @blisteringherb @mikefantini Yeah, I did a test and saved without the accent on the `trafico`, and it still 404'd.

**Comment by sergiitk** [comment]
Nailed it!

My inner monologue:
— `https://thor.dosomething.org/aico`...
— `aico`?
— `a.ico`!
— `*.ico`!!!

**Comment by sergiitk** [comment]
Here's the reason. Instead of looking for `*.ico` files to make exception for them, we did look for `*ico` (missing dot). We have been affected with this bug for a very long time!
Example: https://www.dosomething.org/hi/imma/url/whateverico
Note `ico` at the end.

Also this explains why this error doesn't appear in the error log:
https://github.com/DoSomething/tower/blob/e26946b1b07908efdc0d01e25ae4df88df7ddac5/roles/dosomething.phoenix/templates/nginx/app.j2#L48

**Comment by mikefantini** [comment]
I'm still getting 404'd when I go to https://thor.dosomething.org/mx/voluntario/marca-el-cambio-clim%C3%A1tico?source=campaigns

![image](https://cloud.githubusercontent.com/assets/6330971/11046362/fe067838-86fa-11e5-9ecb-116a80fcf35f.png)

**Comment by sergiitk** [comment]
Hey @mikefantini! This issue has been closed automatically by this [PR](/DoSomething/tower#170).
This means the bug is fixed in code. However, this change hasn't been deployed to production yet.
Should we wait for @sheyd to deploy this change? Otherwise, @blisteringherb and I can do it today.

**Comment by mikefantini** [comment]
@sergii-tkachenko is there any reason it hasn't been deployed to thor yet?

**Comment by sergiitk** [comment]
We didn't want to interact with last week's Global Deploy. @sheyd planned to do it last Thursday, I think he just forgot.

**Comment by mikefantini** [comment]
So @sergii-tkachenko it's possible to deploy first to thor, test it there, and then deploy to prod?

**Comment by sergiitk** [comment]
I can't find Thor Job Template on Ansible Tower. @blisteringherb Do you know how @sheyd provisions Thor environment?

**Comment by sergiitk** [comment]
@mikefantini If this is critical, I can make the change manually.

**Comment by mikefantini** [comment]
@sergii-tkachenko It's blocking us from launching Spanish and Portuguese content, but so is some translation work that should be done by Wednesday or Thursday. So as long as it's done by then it's fine.

**Comment by sergiitk** [comment]
Ok, I'll do the change manually on Thor and test it today so tomorrow we could do the same on Prod.

**Comment by mikefantini** [comment]
:+1:

**Comment by sergiitk** [comment]
Done.

**Comment by sergiitk** [comment]
Check this: https://thor.dosomething.org/mx/voluntario/limpio-y-ecol%C3%B3gico

**Comment by mikefantini** [comment]
Looks good to me!

**Comment by sergiitk** [comment]
Prod fixed: https://www.dosomething.org/mx/voluntario/marca-el-cambio-clim%C3%A1tico
