### ISSUE TITLE
field_fact_problem displays twice if field_fact_solution doesn't exist on a translation

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5668]
Possibly related to #5572 

Currently if `field_fact_solution` doesn't exist on a translation, `field_fact_problem` is being output underneath The Solution instead of `field_solution_copy`

![image](https://cloud.githubusercontent.com/assets/6330971/10837959/3bb7b222-7e96-11e5-83a0-dfa89d2d267f.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10837953/2abda954-7e96-11e5-8f39-f4a77658c47b.png)

https://thor.dosomething.org/mx/voluntario/limpieza-de-calles-por-la-tortuga-marina

The logic should be:
- Display `field_fact_problem` underneath The Problem
- Display either `field_fact_solution` _or_ `field_solution_copy` and then `field_solution_support` underneath The Solution

**Comment by mikefantini** [comment]
Happening for US EN translations as well. Note the difference between prod and thor:

Prod:

![image](https://cloud.githubusercontent.com/assets/6330971/10837982/93b64380-7e96-11e5-8fc1-bea488c29b35.png)

Thor:

![image](https://cloud.githubusercontent.com/assets/6330971/10837985/9dfc6e82-7e96-11e5-883e-b58d657085e2.png)

**Comment by weerd** [comment]
I have a slight bug in my logic for when I'm trying to account for the node state, when it might have a translation and when it might not, since the `dosomething_campaign_load()` gets called twice during the request cycle for some odd reason... Working on a fix.
