### ISSUE TITLE
Campaigns on SMS Game Confirmation Page go to /campaigns

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5673]
After I complete an SMS game, I get taken to a page confirming my submission went through: https://thor.dosomething.org/us/campaigns/5685/confirmation

The campaigns that are highlighted should link to the campaign page. Currently, the user gets taken to /campaigns for each.

This is working on production, but not on thor.

![image](https://cloud.githubusercontent.com/assets/6330971/10885467/59c51400-814b-11e5-8789-1b9737c55823.png)

**Comment by mikefantini** [comment]
Seeing this behave very erratically. Sometimes I get taken to the campaign page, and sometimes it takes me to /campaigns. Note when I get a 404 it's because the US EN translation was unpublished.

http://screencast.com/t/isURa8Ayn2e

**Comment by mikefantini** [comment]
I'm on Firefox 41.0.2

**Comment by angaither** [comment]
seems the url is malformed
https://thor.dosomething.org/us/campaigns/50-cans%3Fsource%3Dcampaigns/5685/confirmation
should be
https://thor.dosomething.org/us/campaigns/50-cans?source=campaigns/5685/confirmation

**Comment by DFurnes** [comment]
We ran into this same problem somewhere else and @diego fixed it up. If those source guys are added by string concatenation, `url()` tries to be helpful and escapes them (i.e. not helpful). This might be the same deal?

**Comment by itsjoekent** [comment]
this is annoying, i accidentally "fixed" the bug while testing.

when you copy the link from the confirmation page (as andrea pointed out already), the URL is bad
https://thor.dosomething.org/us/campaigns/50-cans%3Fsource%3Dcampaigns/5685/confirmation

when you manually fix the URL and enter it again, everything works fine as it should.

this is when it gets really weird, after I've done that ^, I copied the URL from the same campaign on the confirmation page. **and the URL is correct**

https://thor.dosomething.org/campaigns/pregnancy-text?source=campaigns/5685/confirmation

I was able to do this for every campaign on the confirmation page

**Comment by itsjoekent** [comment]
this is the URL I got on my local trying to reproduce 

http://dev.dosomething.org:8888/campaigns/fantini-test?source=campaigns/4/confirmation

I blame the ?source=  i remember we had to remove this somewhere else as well

**Comment by angaither** [comment]
@deadlybutter we don't have to remove ?source, just use drupal's url function and pass it in as a part of the `$options` array, it's likely being manually concatenated currently

**Comment by namimody** [comment]
Seeing this happen again -- clicking on any of the campaigns on the confirmation page results in a 404:

![image](https://cloud.githubusercontent.com/assets/12396076/12334644/0a4606de-bac9-11e5-8e28-7e83bfde050f.png)

Part of the reason for this could be the insertion of an additional "/us/" - for example:
- https://www.dosomething.org/us/us/campaigns/teens-jeans%3Fsource%3Dcampaigns/6054/confirmation
- https://www.dosomething.org/us/us/campaigns/quitters-always-win%3Fsource%3Dcampaigns/6054/confirmation

A good number of people have hit the 404 from this bug in the last couple of weeks (https://analytics.google.com/analytics/web/#report/content-pages/a493209w819276p798164/%3F_u.date00%3D20160101%26_u.date01%3D20160113%26explorer-table.filter%3D404%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowCount%3D100/) so would be great to get in to next sprint.

**Comment by itsjoekent** [comment]
No I think it's because of this bit in the URL `%3Fsource%3Dcampaigns`

actually the entire URL seems borked, double US, node nid and alias...
