### ISSUE TITLE
Global Campaign Runs: various translation bugs

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5676]
When you create a campaign run, the content doesn’t appear in the backend, and doesn’t appear in the campaign view on the campaign’s close date.
## 

Reported by @mikefantini 
CC @sheyd

**Comment by sergiitk** [comment]
I just found out on Thor than when an admin edits Campaign Run, Drupal redirects to incorrect edit page:
https://thor.dosomething.org/node/5878/edit/add/en/en-global

EDIT: this is another issue.

**Comment by sergiitk** [comment]
This ticket is for providing site-wide solution of #5671.

**Comment by sergiitk** [comment]
There's 2 ways to fix it:
1. Execute update query manually before global deployment (safer for the deployment, risky for prod DB)
2. Execute update query after global deployment, using drush (risky for the deployment, safer for prod DB)

Also, the second option will take about an hour more.
Which one should we go with? 

@sheyd @mikefantini

**Comment by sheyd** [comment]
@sergii-tkachenko I'm going to have to go with option 2 on this. Anything that endangers the Prod DB is to be avoided as much as possible. Can you explain in a little more details the risks running the command via drush poses to the deployment?

**Comment by sergiitk** [comment]
@sheyd Just because we will be changing 2 things at once. We're introducing a lot of new code with Global deploy and I don't really know how this fields will behave after the release. I'll start testing it now.

**Comment by sheyd** [comment]
@mikefantini As annoying as it is... do you think this justifies a full refresh of thor, the deploy steps, and spot checking things after @sergii-tkachenko runs the fix script? 

Not sure how much time/risk factor we're willing to tolerate here.

**Comment by mikefantini** [comment]
@sheyd @sergii-tkachenko we'll want to do a prod db import into Thor later this week anyways so we can test this then when we do that.
