### ISSUE TITLE
US users are not redirected to US URL if there is no GL EN translation

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5677]
Level Playing Field:
- node is published
- US EN translation is published
- GL EN translation does not exist

As an anonymous user coming from the US, if I go to https://thor.dosomething.org/campaigns/level-playing-field, I'm _not_ being redirected to the US experience. The desired behavior is that I would be getting redirected.

Some tangible side effects to this are that
1. Problem fact is missing on the pitch page
2. I'm seeing the GL EN footer

![image](https://cloud.githubusercontent.com/assets/6330971/10889539/9835071c-8160-11e5-8067-b1375d8753d7.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10889549/a2f060b6-8160-11e5-918d-9c0c6e60fd45.png)

Since we have a lot of marketing out there pointing people directly to the base URL (i.e. www.dosomething.org/campaigns/level-playing-field) we need to resolve this before we launch.

**Comment by deadlybutter** [comment]
Can't reproduce on my dev?
