### ISSUE TITLE
No Prob Statement Appearing for Anon User

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5679]
https://thor.dosomething.org/us/campaigns/veggie-surprise

![image](https://cloud.githubusercontent.com/assets/12396076/10889857/6a5760f4-8162-11e5-904c-c6d993b46757.png)

The prob statement appears for admin users who view the pitch page, but not for anon users. The fact appears in the backend of the campaign. Can't seem to replicate on any other campaigns at the moment.

**Comment by angaither** [comment]
@namimody that us-english campaign is unpublished

refs #5675

**Comment by angaither** [comment]
it works on published campaigns
![image](https://cloud.githubusercontent.com/assets/645205/10890164/768f330e-8164-11e5-8ebb-e1d30c5cce24.png)

**Comment by namimody** [comment]
Ahhh okay got it thanks @angaither! I'll close this then.
