### ISSUE TITLE
Cause filter of finder should be in two columns on thor

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5682]
![image](https://cloud.githubusercontent.com/assets/6330971/10891577/c07d3e54-816c-11e5-93f7-338e377ab48d.png)

Testing on Firefox 41.0.2 from Brazil via TorGuard.

**Comment by DFurnes** [comment]
Hmm, not seeing this in Firefox 41.0.2 on OS X 10.11.1, on either production or Thor:

<img width="1365" alt="screen shot 2015-11-02 at 3 53 19 pm" src="https://cloud.githubusercontent.com/assets/583202/10894020/0b12e79a-817a-11e5-9932-8d7c89c80efd.png">

I'll look into setting up TorGuard to see if somehow it's only appearing for BR users, but I can't think of a reason that'd be occurring. :confused:

**Comment by sheyd** [comment]
@DFurnes Keep in mind thor now has headers that make "BR" act like Global English, not Brazil

**Comment by DFurnes** [comment]
Hmm. We're serving identical stylesheets and markup for that section to all country codes though. But we'll see... strange things have been happening with CSS column bugs lately, so who knows!

**Comment by DFurnes** [comment]
@mikefantini I'm unable to reproduce this across environments or country codes. Going to close, but please re-open if you continue seeing this.
