### ISSUE TITLE
Logging in on a non-campaign page from the US takes user to /user/ not /us/user/

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5683]
As a user located in the US, if I log in on any non-campaign pages (i.e. the homepage), I get taken from www.dosomething.org/us to www.dosomething.org/user/[uid].

Because it doesn't have /us/ in the URL, it's not pulling in content properly (i.e. campaign title, image, CTA for campaigns I'm signed up for).

I believe we want the user go to /us/user/[uid]

![image](https://cloud.githubusercontent.com/assets/6330971/10893381/7cceff94-8176-11e5-93ac-2de428ee62c2.png)

**Comment by itsjoekent** [comment]
Unable to reproduce locally even after a drush fra and latest code? workin on hotmodule stuff now but mind taking a look @angaither later to figure out whats going on?

**Comment by angaither** [comment]
@deadlybutter you should be able to log in and see it go to `user/id` we basically want to revert the logic added for #5506

**Comment by itsjoekent** [comment]
OH I was on an outdated feature branch when i did this,i can reproduce now
