### ISSUE TITLE
Problem Statement Not Appearing in Permalink View

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5684]
![image](https://cloud.githubusercontent.com/assets/12396076/10893604/bd3697e4-8177-11e5-9688-2fbf789fcf41.png)

Should appear like this (although this screenshot is missing a CTA above sign up)
![image](https://cloud.githubusercontent.com/assets/12396076/10893644/f4a82300-8177-11e5-8c6f-89f6cc8ef928.png)

(Problem statement appears on pitch page for anon users)

**Comment by namimody** [comment]
Happens via Facebook, TUmblr, and Twitter

**Comment by mikefantini** [comment]
I can confirm this isn't working. Not great obviously, but I don't think this needs to be considered a launch blocker.

**Comment by angaither** [comment]
ahh, problem fact things... @weerd mind taking a look at this?

**Comment by weerd** [comment]
K. I'm on it.

**Comment by angaither** [comment]
..not sure how these things should act with translations, it might be a little wonky

**Comment by weerd** [comment]
![image](http://o.aolcdn.com/hss/storage/midas/949f35ec7d79b32249919ad26202223b/202721400/tumblr_n98pc5oDZB1qb4p3ko1_500-1.gif)

**Comment by mikefantini** [comment]
At the very least we should make sure that the following scenario works:
- US user A reports back on a US EN campaign
- US user B views US user A's reportback permalink
- US user B should see the US EN Problem and Solution content

cc: @weerd @angaither

**Comment by namimody** [comment]
Hi Squad, unfortunately this still seems to be a problem :( -- reopening

![image](https://cloud.githubusercontent.com/assets/12396076/11752961/82b9c638-a010-11e5-9506-73d47e98b698.png)
