### ISSUE TITLE
Campaign Info (except hyperlinked PROVE IT button) Not Appearing on User Profile

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5687]
This seems to be somewhat intermittent. I see this on my Thor admin view:

![image](https://cloud.githubusercontent.com/assets/12396076/10895173/c80b36a8-8180-11e5-8bb9-109401147bd9.png)

I wanted to try and recreate so I then signed up for a bunch of campaigns using a regular user account, and my user profile acted correctly (all images, titles, and CTAs showed). Then, I forgot my password on this account, reset it, and logged back in. Then, my user profile looked like this:

![image](https://cloud.githubusercontent.com/assets/12396076/10895147/9a48a854-8180-11e5-951b-9a7d21890f89.png)

As a note, the PROVE IT buttons work correctly.

**Comment by angaither** [comment]
duplicate #5683
