### ISSUE TITLE
Escaping US language Thor instances

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#5690]
![screen shot 2015-11-02 at 5 19 35 pm](https://cloud.githubusercontent.com/assets/1865372/10896110/ed65b996-8185-11e5-8be9-85519cab3ed2.png)

![screen shot 2015-11-02 at 5 20 26 pm](https://cloud.githubusercontent.com/assets/1865372/10896126/07cfaf1c-8186-11e5-9a65-3c375241a99d.png)

When editing a profile (and maybe some other places, still exploring) we lose the `/us/` in the URL which allows a user to escape out into Global English land and break some pages.

CC: @angaither @namimody

**Comment by lkpttn** [comment]
Second situation, when first signing in from thor.dosomething.org/us, the user profile is a global profile and doesn't show campaign images, correct footer, etc.

![screen shot 2015-11-02 at 5 24 02 pm](https://cloud.githubusercontent.com/assets/1865372/10896238/9af75272-8186-11e5-9213-c15c0adec88c.png)

**Comment by angaither** [comment]
duplicate of #5704
