### ISSUE TITLE
Need temp 302 from /us/facts/my-fact-url to /facts/my-fact-url

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5699]
Post-2.0.3, 11 Facts are not translated. They still serve at the bare URL (e.g., `/facts/11-facts-about-animal-testing`).

Implement a Fastly 302 redirect for remove the `/us` from these paths.

**Comment by sheyd** [comment]
Fixied this via this nutty logic in our Varnish layer (was just easier):

In vcl_recv:

```
  if (req.url ~ "/us/facts/") {
     set req.url = regsub(req.url, "^/us/facts/", "/facts/");
     error 800 "Moved Temporarily";
  }
```

In vcl_error:

```
  if (obj.status == 800) {
      set obj.http.Location = "http://www.dosomething.org" + req.url;
      set obj.status = 302;
      return (deliver);
  }
```
