### ISSUE TITLE
Helpers: Test bug -- fix getInfo() group

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#570]
Group should be set to 'DoSomething', not 'Dosomething helpers'

**Comment by blisteringherb** [comment]
It looks like this was already fixed?  https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.info#L4

**Comment by aaronschachter** [comment]
yip

**Comment by aaronschachter** [comment]
This is actually for the Dosomething Helpers Test.  Let's either fix this or just get rid of the test, since it doesn't actually have any tests.

![screen shot 2014-04-09 at 5 29 09 pm](https://cloud.githubusercontent.com/assets/1236811/2661516/093c13f6-c02e-11e3-8ea6-cb6c1e97a1e6.png)
