### ISSUE TITLE
Need temp 302 from /us/volunteer/[title] to /volunteer/[title]

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5700]
Post-2.0.3, Campaign Collections are not translated. They still serve at the bare URL (e.g., /volunteer/[title]).

Implement a Fastly 302 redirect for remove the /us from these paths.

Example www.dosomething.org/us/volunteer/seniors-and-smartphones to www.dosomething.org/volunteer/seniors-and-smartphones

**Comment by sheyd** [comment]
Fixied this via this nutty logic in our Varnish layer (was just easier):

In vcl_recv:

```
  if (req.url ~ "/us/volunteer/") {
     set req.url = regsub(req.url, "^/us/volunteer/", "/facts/");
     error 800 "Moved Temporarily";
  }
```

In vcl_error:

```
  if (obj.status == 800) {
      set obj.http.Location = "http://www.dosomething.org" + req.url;
      set obj.status = 302;
      return (deliver);
  }
```

**Comment by mshmsh5000** [comment]
**N.b.** We reverted this behavior on 2015-12-07, once we launched GGW as a campaign collection.
