### ISSUE TITLE
Images are missing from the US static pages

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5702]
Gallery images and Intro image from the US static pages when viewed as non-admin:
https://www.dosomething.org/us/about/our-people
![image](https://cloud.githubusercontent.com/assets/672669/10923984/86ac004a-828c-11e5-8458-98689308d84b.png)

**Comment by mikefantini** [comment]
Here is an example of a page that is missing inro image as well:

https://www.dosomething.org/us/about/who-we-are

**Comment by angaither** [comment]
fixed with #5701

**Comment by angaither** [comment]
ah, intro images are still missing, reopening!
