### ISSUE TITLE
Can't Delete Redirects from Campaign Pages

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5703]
As an administrator, we can't delete redirects from the campaign page (this view):

![image](https://cloud.githubusercontent.com/assets/12396076/10939059/cf67d77e-82cc-11e5-9fb7-4435b6236ac7.png)

Clicking delete on a redirect refreshes the page and returns you to the top of the page with this view:

![image](https://cloud.githubusercontent.com/assets/12396076/10939066/e42595ac-82cc-11e5-80d3-70cc2340ad03.png)

Redirects can be deleted by admins from: 
https://www.dosomething.org/admin/config/search/redirect

**Comment by angaither** [comment]
@namimody since we don't manage redirects in phoenix anymore, can we close this issue out? [🌃 ](https://github.com/DoSomething/nightwing)

**Comment by namimody** [comment]
Shore, @angaither
