### ISSUE TITLE
DBLog error for user language in API request

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5705]
We are attempting to set the `$language` [here](https://github.com/DoSomething/phoenix/blob/859331aaf2bb15dfe7a85860e8dc39e0261539ad/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L151) but if user is anonymous (ie: anon GET request) we get errors.

**Comment by weerd** [comment]
@blisteringherb I believe this is an update you made to include the `$language`. Would you mind filling me in or pointing me to the PR/Issue related to the update? I'm curious cause this isn't necessarily the user's language that created the RB, but the language for the requestor. Just trying to get more context on why it was included and where it ends up getting used once included in the object (since there's also an error related to it, if it's an anon user).

**Comment by blisteringherb** [comment]
@weerd It gets used for the reportback email to select the correct template for sending the reportback email to the user.

**Comment by weerd** [comment]
Gotcha @blisteringherb ... so this would send an email to the user regarding their specific reportback? Cause from the API side, it's always going to be the same if it's the API user... so it's not the specific language for the user that reported back.

**Comment by blisteringherb** [comment]
Yup, that's right. Will you be sending reportbacks via the API?

**Comment by weerd** [comment]
Yar.

**Comment by blisteringherb** [comment]
Hm, how will we be getting the user's language via the API?

**Comment by weerd** [comment]
@blisteringherb I can update since I have to fix the anon user issue w/ the language anyhoo. It would also make more sense to pop it into the User object nested in the Reportback object, that contains the rest of the user info too. Might just need to update the email part that uses that variable.

**Comment by weerd** [comment]
@blisteringherb I suspect via Northstar, which is where we get the rest of the user data.

Could you point me to where in the code that `$language` property was otherwise then being used? Or is that a Message Broker thing?

**Comment by weerd** [comment]
Also, something to keep in mind is that this Reportback class is currently ONLY really used for the API.

**Comment by weerd** [comment]
@blisteringherb I chatted with @DeeZone and doesn't seem like this is being used within email things. Could it have been an update specifically for mobile app stuff? @jonuy mind chiming in?

**Comment by jonuy** [comment]
Can we set a default language in the Reportback code to like, english or global english or whatever the default is? Northstar I think does make some of the GET /reportback calls, but the mobile app itself also makes its own directly to Phoenix. With Phoenix as the final destination for both of the requests, having a fallback set there I think makes sense.

And a small aside - It's safe to assume that reportback submissions via API are still ok though, right? In addition to the mobile app, SMS also submits reportbacks through the Phoenix API. Reportbacks at least seemed to be working on staging when I was testing earlier today.

**Comment by weerd** [comment]
@uy We can set a default language if desired... which I am doing in the PR I merged indicated above #5717. However, the question is more _what_ language to assign to the RB? The campaign it's associated with or the user it's associated with? Right now we're using `global $user` language and that would always be the same (either `NULL` cause it's an anon GET request) or the API user's language (which is unrelated to the RB entirely).

PR #5717 updates so that it no longer gives `NULL` as the language if it's an anon GET request-response, but still doesn't address the larger issue of none of those actually related to the language of the RB. Thoughts?
