### ISSUE TITLE
Images are missing from taxonomy term pages

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5710]
https://www.dosomething.org/volunteer/poverty is displaying as:
![image](https://cloud.githubusercontent.com/assets/12396076/10956215/d35ee5c4-8327-11e5-903d-4c9de2b5b7c8.png)

https://www.dosomething.org/volunteer/animals is displaying as:
![image](https://cloud.githubusercontent.com/assets/12396076/10956262/3f344c4e-8328-11e5-92a6-cb879b1621de.png)

However, clicking on the campaign square brings you to the correct campaign page.

Related to: https://github.com/DoSomething/phoenix/issues/5647

**Comment by sergiitk** [comment]
Correction: this is not campaign collection, this is taxonomy terms (tags).
