### ISSUE TITLE
Redirect Problem w/ MCC Form

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5711]
https://www.dosomething.org/campaigns/submit-your-idea should show what is seen here: https://www.dosomething.org/us/about/submit-your-campaign-idea, but instead links to /campaigns. Unsure where/when this redirect logic broke but was reported by Hannah on 11/4, one day after Global 1.0 launched.

**Comment by mikefantini** [comment]
@namimody I believe the link is https://www.dosomething.org/about/submit-your-campaign-idea and that redirect seems to work fine.

If you can verify this please close this out. Thanks!

**Comment by namimody** [comment]
@mikefantini yep, we've switched out the link in the MCC macro to https://www.dosomething.org/about/submit-your-campaign-idea. Should we be concerned that the link didn't auto redirect? might there be other edge cases -- or not something to worry about?

**Comment by mikefantini** [comment]
@namimody it might be worth keeping an eye out for this on the 404's monitoring. But I think for now we can close this out.

If you want to add in the redirect from /campaigns/submit-your-campaign-idea go for it. But I think we should just keep using the /about/submit-your-campaign-idea moving forward when we market this.
