### ISSUE TITLE
Campaign Collections are missing content on prod

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5714]
The content is missing from both the front end and the back end.

This includes Cover Image and Facts that were referenced. Potentially other fields as well.

Example: https://www.dosomething.org/node/5780/edit 

cc: @angaither 

Potentially related to #5676

**Comment by sergii-tkachenko** [comment]
Duplicate of #5710.

**Comment by mikefantini** [comment]
This campaign collection https://www.dosomething.org/node/5780/edit is also missing content from the back end, but it's showing up on the front end.

![image](https://cloud.githubusercontent.com/assets/6330971/10973980/df0aa508-83ad-11e5-9d8c-38099c9c1eec.png)

**Comment by sergiitk** [comment]
@mikefantini So I didn't yet executed the fix for o #5676 on prod. I'll sync with @sheyd, backup the db and will run the fix.

**Comment by mikefantini** [comment]
Got it. Thanks. Is the plan to run that on Thor first?

**Comment by sergiitk** [comment]
@mikefantini Yes

**Comment by sergiitk** [comment]
Hey @mikefantini, since I can't access backend normally now (see #5716), could you please provide me with the list of fields that we need to fix? Preferably in machine format, f. ex.: `field_additional_text_title`.

**Comment by mikefantini** [comment]
@sergii-tkachenko I'm not sure what else these are missing, but they are still definitely missing cover image and facts:

https://thor.dosomething.org/taxonomy/term/13/edit -> https://thor.dosomething.org/volunteer/bullying

https://thor.dosomething.org/taxonomy/term/16/edit -> https://thor.dosomething.org/volunteer/animals

It seems as if the images, titles, and CTAs of the campaigns they are referencing are now appearing again however.

**Comment by sergiitk** [comment]
Missing fields on Taxonomy Terms turnout to be another issue, see #5758.

**Comment by angaither** [comment]
@sergii-tkachenko @mikefantini is this still an issue?

**Comment by sergiitk** [comment]
@angaither I believe it's not an issue anymore: https://www.dosomething.org/volunteer/old-school-impact

**Comment by mikefantini** [comment]
Yeah we should be good on this.
