### ISSUE TITLE
Incorrect redirect of global admins on node edit page

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5716]
As an admin accessing the backend from outside the US I'm trying to edit nodes that are not translatable, like this:
https://thor.dosomething.org/node/5780/edit
But it redirects me to:
https://thor.dosomething.org/node/5780/edit/add/en/en-global

Hence I can't see or edit all untranslatable nodes.

---

cc @mikefantini

**Comment by mikefantini** [comment]
Hmmm @sergii-tkachenko what language is set for your user?

**Comment by sergiitk** [comment]
@mikefantini nop, `/us/` redirects me to
https://thor.dosomething.org/us/node/5780/edit/add/en/en-global

**Comment by sergiitk** [comment]
The user language in profile is English, but I don't think it affects anything now.

**Comment by mikefantini** [comment]
Hmmm ok. @deadlybutter we still want this logic for content that is translatable, just not for content that is not translatable
