### ISSUE TITLE
Auth modal not appearing on thor

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5719]
![image](https://cloud.githubusercontent.com/assets/6330971/10975673/1909d15e-83b6-11e5-878b-99b286fe31fc.png)

TSG is scheduled to test Mexican/Brazilian experience this afternoon so let's please get this deployed to thor after it's resolved.

**Comment by DFurnes** [comment]
Will take a look in just a minute. My hunch is that the [Modernizr patch we applied a little ways back](https://github.com/DoSomething/phoenix/pull/5128) might no longer be working. It looks like the grunt-modernizr released [a new stable release](https://www.npmjs.com/package/grunt-modernizr) that supports Modernizr v3, so I'm going to see if we can get back on that.

**Comment by mikefantini** [comment]
This is currently working on prod currently just FYI.

**Comment by DFurnes** [comment]
The Jenkins job for [deploying to Thor](https://jenkins-thor.dosomething.org/job/Deploy-Thor/139/console) shows an error when building the Modernizr file. So presumably our next deploy to staging or production might end up like this as well:

```
DEBUG [71957d95]    [4mRunning "modernizr:all" (modernizr) task[24m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [1mLooking for Modernizr references[22m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m2[39m matches in js/reportback/Reportback.js
 DEBUG [71957d95]   [32m>> [39m[90mfilereader, json[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m1[39m match in scss/content/_finder.scss
 DEBUG [71957d95]   [32m>> [39m[90mchecked[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m1[39m match in scss/content/_win-module.scss
 DEBUG [71957d95]   [32m>> [39m[90msvg[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m1[39m match in scss/patterns/_statistic.scss
 DEBUG [71957d95]   [32m>> [39m[90mplaceholder[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m1[39m match in node_modules/@dosomething/forge/scss/_base/_fonts.scss
 DEBUG [71957d95]   [32m>> [39m[90msvg[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m1[39m match in node_modules/@dosomething/forge/scss/_regions/_navigation.scss
 DEBUG [71957d95]   [32m>> [39m[90msvg[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[32m2[39m matches in node_modules/dosomething-modal/src/modal.js
 DEBUG [71957d95]   [32m>> [39m[90mcssanimations, target[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39mReady to build using these settings:
 DEBUG [71957d95]   
 DEBUG [71957d95]   [32m>> [39m[90maddTest, html5printshiv, testProp, fnBind[39m
 DEBUG [71957d95]   [32m>> [39m[90mYour file will be minified with UglifyJS[39m
 DEBUG [71957d95]   
 DEBUG [71957d95]   [37m[1mBuilding your customized Modernizr[22m[39m
 DEBUG [71957d95]   [31mFatal error: Cannot read property 'replace' of undefined[39m
```

**Comment by DFurnes** [comment]
So, it looks like we updated to the latest Modernizr version already [in an earlier PR](https://github.com/DoSomething/phoenix/blob/52f34695ce4135ed92ecca46270f2a96d0f336e4/lib/themes/dosomething/paraneue_dosomething/package.json#L39). Unfortunately, it looks like this latest version errors out [when passing custom tests in the build](http://dfurn.es/20xtjsV)... I think the best short-term fix is to roll back to the old patched version we were using and wait on Modernizr v3 to get a bit more stable.

**Comment by DFurnes** [comment]
@mikefantini Just deployed this fix to Thor, and things seem to be working again.

**Comment by mikefantini** [comment]
Thanks @DFurnes!
