### ISSUE TITLE
Incorrect user data attached to a reportback

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5729]
In at least one case on staging, the user object that comes back on a reportback GET request does not match the actual user who submitted the reportback. It doesn't happen on 100% of accounts, but depending on how often something like this might happen, would it be a Kiwi launch blocker?
#### So what happened

![android_rb](https://cloud.githubusercontent.com/assets/696595/10982134/9b92e0fc-83d9-11e5-9491-dbfa1b86f4a8.png)
1. Jeff submitted a reportback through the mobile app. You can see it here: http://staging.beta.dosomething.org/reportback/3388
2. Jeff viewed that individual reportback on the app. The app says "melissa" submitted that reportback.
#### Where did Melissa come from

It's getting returned from the API: https://staging.beta.dosomething.org/api/v1/reportbacks/3388.json

Both the name and the id on that doc aren't Jeff's. 

```
user: {
  id: "560c007ea59dbfc6038b4572",
  first_name: "melissa",
  last_name: null,
  photo: null,
  country: null
}
```

That is at least a valid id though on northstar-qa and that person is named melissa.

Not sure where the actual problem lies, but it seems like it's something around the Northstar user retrieval code in Phoenix.

cc: @angaither @marahml @weerd

**Comment by jonuy** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HpaJJcBs&#x2F;10-report-back-display-profile-name-changed-to-other-people-s-name"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Report back display profile name changed to other people&#39;s name.</a>

**Comment by weerd** [comment]
@uy Can you run a mongo query on that NS user _id to find out what their drupal id is and then check to see if the user id matches Jeff's?

It could also be that the syncing script that moves Drupal users into Northstar has a bug?

**Comment by jonuy** [comment]
@weerd 

Well this is odd. It seems like Melissa and Bladt have the same `drupal_id` on our Northstar staging db. 

**Melissa**

```
rs0:PRIMARY> db.users.find({_id:ObjectId('560c007ea59dbfc6038b4572')}).pretty()
{
    "_id" : ObjectId("560c007ea59dbfc6038b4572"),
    "email" : "**redacted**",
    "drupal_id" : "1705409",
    "birthdate" : "**redacted**",
    "first_name" : "melissa",
    "password" : "$2y$10$7/vqIWopFGJTAtBOmgq9zeJbP9UcgczOQpQRgtjW2ku0nk/bsevNi",
    "updated_at" : ISODate("2015-09-30T15:32:18.018Z"),
    "created_at" : ISODate("2015-09-30T15:32:14.741Z")
}
```

**Bladt**

```
rs0:PRIMARY> db.users.find({_id:ObjectId('560eecdba59dbf4d168b4568')}).pretty()
{
    "_id" : ObjectId("560eecdba59dbf4d168b4568"),
    "country" : "US",
    "email" : "**redacted**",
    "first_name" : "jeff",
    "mobile" : "",
    "password" : "$2y$10$h4Q4yFzq8jYC4yjF6uHh4eFjQyJVCkYAgAaey9NuivsHu8akP8rYS",
    "source" : "letsdothis_android",
    "drupal_id" : "1705409",
    "updated_at" : ISODate("2015-10-02T20:45:16.629Z"),
    "created_at" : ISODate("2015-10-02T20:45:15.580Z"),
        ...
}
```

I'm not sure how that happened. The Melissa account doesn't seem to exist on our Phoenix staging db. I searched for users with her email and her first name. Nothing seemed to match. The Melissa account also doesn't have a `drupal_password` property so it doesn't seem like it was an account brought over with one of our syncing scripts.

Any ideas of any other way the account might've gotten into Northstar with a `drupal_id`? I'm gonna go into staging now and see if I can find any other accounts that have duplicate `drupal_id`s

**Comment by weerd** [comment]
Production DB? Maybe check there too?

**Comment by jonuy** [comment]
Yea, nothing found on production either.

**Comment by weerd** [comment]
@angaither @DFurnes @chloealee any chance any of you might shed some light on this? If it's a bug, probs ideal to figure it out soon so we can clean up the messed up data @_@

**Comment by jonuy** [comment]
I'm finding a lot of user documents with the same `drupal_id` on both Northstar production and staging. I'm guessing this is what we expected from the syncing scripts and we were just gonna merge documents later on? Hard to tell if this could have been a source of Bladt's `drupal_id` getting assigned to a rando.

Just for some examples:

**Staging** has two docs of a mobilewah fantini

```
rs0:PRIMARY> db.users.find({drupal_id:'1700152'}).pretty()
{
  "_id" : ObjectId("559442a3a59dbfca578b4947"),
  "email" : "mfantini+mobilewah@dosomething.org",
  "drupal_id" : "1700152",
  "birthdate" : "1999-05-30 00:00:00",
  "first_name" : "Mike",
  "last_name" : "Fantini",
  "updated_at" : ISODate("2015-07-01T19:42:27.607Z"),
  "created_at" : ISODate("2015-07-01T19:42:27.607Z")
}
{
  "_id" : ObjectId("55a422bda59dbfb37a8b4815"),
  "email" : "mfantini+mobilewah@dosomething.org",
  "drupal_id" : "1700152",
  "drupal_password" : "$S$DG4aoO.9/wybvmn4bjo1j4vZa5I5FcVkcq0GVuEKi4TbRmg2y7t4",
  "birthdate" : "1999-05-30 00:00:00",
  "first_name" : "Mike",
  "last_name" : "Fantini",
  "created_at" : ISODate("2014-05-19T19:48:46Z"),
  "updated_at" : ISODate("2015-07-13T20:42:37.700Z")
}
```

**Production** has 3 documents for 2719748

```
{
  "_id" : ObjectId("554a9dfb469c64ec7d8b5b81"),
  "email" : "**redacted email same across all 3 docs**",
  "drupal_id" : "2719748",
  "password" : "$2y$10$qWbdn1bFhWbusZXQcafHJ.U/mhWq4PRF0NBd/czI2/gdd7uNB1fGu",
  "updated_at" : ISODate("2015-05-06T23:04:27.404Z"),
  "created_at" : ISODate("2015-05-06T23:04:27.404Z")
}
{
  "_id" : ObjectId("554a9e25469c64ed7d8b5b7a"),
  "email" : "**redacted email same across all 3 docs**",
  "drupal_id" : "2719748",
  "updated_at" : ISODate("2015-05-06T23:05:09.580Z"),
  "created_at" : ISODate("2015-05-06T23:05:09.580Z")
}
{
  "_id" : ObjectId("5553a892469c64ec7d8b750d"),
  "email" : "**redacted email same across all 3 docs**",
  "mobile" : "7032440405",
  "first_name" : "Claudia",
  "birthdate" : "1997-06-27 00:00:00",
  "drupal_id" : "2719748",
  "password" : "$2y$10$jJTEs3YQvUTs0KbH3Ii.V.k.PaS1JjDsdDGjRwUkXjRiOGjXsbe5a",
  "country" : "US",
  "addr_street1" : "**redacted**",
  "addr_city" : "**redacted**",
  "addr_state" : "**redacted**",
  "addr_zip" : "**redacted**",
  "updated_at" : ISODate("2015-05-13T19:40:02.322Z"),
  "created_at" : ISODate("2015-05-13T19:40:02.322Z")
}
```

**Comment by angaither** [comment]
yeah, there's a bug in Northstar that's causing duplicate mongo accounts even if the email and or phone number match DoSomething/northstar/issues/187

**Comment by chloealee** [comment]
@angaither @jonuy I put that script on hold to work on other issues that were higher priority. Right now, the only things on my to-do list are writing a unit test (https://github.com/DoSomething/northstar/issues/230), forwarding campaign activity from phoenix -> Drupal (https://github.com/DoSomething/phoenix/issues/4571), and user dedupe script (https://github.com/DoSomething/northstar/issues/187 referenced above). Priority wise, should I jump on this first?

**Comment by jonuy** [comment]
Both #187 and #4571 are important. IMO maybe #187 would take priority? #187 might also help find out if this bug (#5729) is actually more widespread or just somehow only affects Bladt's staging account.

**Comment by chloealee** [comment]
okay thanks @jonuy ! I'll jump back on https://github.com/DoSomething/northstar/issues/187 now.

**Comment by chloealee** [comment]
@jonuy finally finished the dedupe script! I don't think we'll run it until after the holidays but wanted to keep you updated for this bug.

**Comment by jonuy** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9polXi8V&#x2F;317-user-dedupe-script"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> User dedupe script</a>

**Comment by angaither** [comment]
closing after merge/run of the dedupe script
