### ISSUE TITLE
Remove CKEditor library

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#573]
I assume this is not necessary, given that we're going to use Markdown across the board:

https://github.com/DoSomething/dosomething/commit/7e4b3b2b

Can we just revert? @desmondmorris since this was your commit, please comment then reassign.

**Comment by desmondmorris** [comment]
@mshmsh5000 a revert will kill some of the formatting in the make file.   A commit to remove will be best.

**Comment by mshmsh5000** [comment]
Sorry, I didn't mean a technical revert -- just a commit to remove. Thanks!

**Comment by mshmsh5000** [comment]
@angaither Can you take care of this? Thanks!
