### ISSUE TITLE
Campaigns api `terms_id` vs `term_id`

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5734]
Currently if a campaign only has one `tags` set and you pass it in via `terms_id` it doesn't return that campaign. 
It works if you pass in `term_id`
## example urls

node 1377 is missing from this first call, even though it has term 670

http://staging.beta.dosomething.org/api/v1/campaigns.json?mobile_app=true&term_ids=670&mobile_app_date=2015-11-02

http://staging.beta.dosomething.org/api/v1/campaigns.json?mobile_app=true&term_id=670&mobile_app_date=2015-11-02

cc @jonuy

**Comment by jonuy** [comment]
I'm gonna also cc @marahml

For context, we were thinking the mobile app could get exclusive campaigns by creating on them on the site but just leaving them unpublished so web users wouldn't be able to see them. As far as I know, we don't have any mobile app exclusive content on deck, so we're fine for the immediate future at least.

**Comment by angaither** [comment]
oh exclusive content you say? we don't believe in that here. 
EQUALITY!
