### ISSUE TITLE
field_created_copy content got wiped on production

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5735]
![image](https://cloud.githubusercontent.com/assets/6330971/11003184/000dbcdc-847f-11e5-872d-99a5575b12fd.png)

`field_created_copy` field is wiped from prod:

Examples:
- https://www.dosomething.org/us/node/2933/edit
- https://www.dosomething.org/us/node/3455/edit

Is this because of #5420?

**Comment by sergiitk** [comment]
@mikefantini I think it is. The line that fixes the translations for this field still exists: https://github.com/DoSomething/phoenix/blob/0b305da69d613a3a2b8ef2eba32b2437e6d0446c/bin/ds-global#L118

**Comment by sergiitk** [comment]
So the field hasn't been disabled properly.
I tested on Prod DB locally, the easiest way to fix this is to manually enable this field for translation and then disable it again.
![image](https://cloud.githubusercontent.com/assets/672669/11072995/2ffbead4-87f1-11e5-8d45-4d2137b7b88c.png)

**Comment by mikefantini** [comment]
Just confirmed on thor. Thanks @sergii-tkachenko!

**Comment by sergiitk** [comment]
Fixed on production.
