### ISSUE TITLE
Privacy Policy and Terms of Service 404 for BR/MX users

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5745]
Clicking on either in the footer takes me to https://thor.dosomething.org/br/sobre/terms-service or https://thor.dosomething.org/br/sobre/privacy-policy which both 404.

@mnelson338 we're not translating these right?

@angaither if we're not translating them, what do you think is the best course of action?

**Comment by mnelson338** [comment]
We are translating - but it's not a launch blocker (essentially, we're just translating to be proactive for the day when we have on the ground staff - but we will not be breaking any laws by having english versions) 

I need to get approval from Aria on the new policies - but we can use the old ones until they are approved. 

@mikefantini

**Comment by mikefantini** [comment]
Hmm ok. Well we need some solution because right now the pages 404. So either we need to get translations in there (do we already have translations?) or we need to figure out how to not have users 404 when going to the English content.

@angaither do you have thoughts on how we can go about resolving this? Should we create a page that is (actually) in US EN but have the path be /br/sobre/terms-service?

**Comment by angaither** [comment]
@mikefantini those nodes are appear to be in saved in english, with english content, so they would 404 because they aren't in the lang of the visitor

**Comment by mikefantini** [comment]
@angaither how do you suggest we fix this from 404'ing? Is there a non-code fix we can do? We can launch the BR/MX experiences with Terms of Service and Privacy Policy that 404s.

**Comment by angaither** [comment]
@mikefantini we just have to change the language on those nodes

**Comment by mikefantini** [comment]
Ok right so this one needs to just have translations created for each language for both of the nodes.

Even though we'll have translations created technically, all of the words will still be in US English for the time being.

Unfortunately, because of #5302 we should do this only on thor for now (and publish the translations) and then once #5302 is closed, we should do it on production.

@julielorch mind setting these translations up?

**Comment by joolaay** [comment]
@angaither are these links hardcoded? I don't see them in paraneue settings.

**Comment by angaither** [comment]
@julielorch not hardcoded, it's stored [here](https://www.dosomething.org/admin/config/dosomething/dosomething_user)
since it's only one field currently, we will have to add additional options (like we did for header/footer) settings to allow this to be different across counties

**Comment by joolaay** [comment]
Okie all set on thor.
