### ISSUE TITLE
/br/sobre/faqs and /mx/sobre/contacto throw error messages

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5747]
https://thor.dosomething.org/br/sobre/faqs

https://thor.dosomething.org/mx/sobre/contacto

![image](https://cloud.githubusercontent.com/assets/6330971/11041322/1e9db9e2-86df-11e5-9eb5-91ebaa409130.png)

"The website encountered an unexpected error. Please try again later."

All other static content pages seem to work.

**Comment by angaither** [comment]
@mikefantini nids?

**Comment by mikefantini** [comment]
@angaither 6013 and 6009

**Comment by angaither** [comment]
@deadlybutter mind taking a stab at this one?

**Comment by angaither** [comment]
looks like it’s something wonky with translation and `field_intro` and `additional_text`, it ​_works_​ if both are there. we are going to take that route for now

**Comment by angaither** [comment]
this now works, https://thor.dosomething.org/mx/sobre/contacto

@julielorch is going to update this on prod for the nodes that are messed up

**Comment by angaither** [comment]
@deadlybutter I think you should still try to figure out why the static content type breaks when only `additional_text` is filled out

**Comment by joolaay** [comment]
Updated on prod.

**Comment by mikefantini** [comment]
@julielorch do you mind updating on thor as well so that we don't have any unnecessary red flags?

**Comment by angaither** [comment]
@mikefantini since we have a content work around for this I'm going to remove the blocker label

**Comment by itsjoekent** [comment]
WE HAVE A BREAKTHROUGH, ITS THE INTRO FIELD.

http://media2.giphy.com/media/b6EKyJd8S1DX2/giphy.gif
