### ISSUE TITLE
Remove Questions? Contact Us from static content types

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5750]
Currently for BR/MX users it's showing up on static content pages as well.

![image](https://cloud.githubusercontent.com/assets/6330971/11044608/ecbe5758-86f0-11e5-8472-a9945e07ef14.png)

**Comment by angaither** [comment]
@mikefantini should it be only on campaign nodes? not campaign groups, or just not on static content nodes?

**Comment by mikefantini** [comment]
Yeah you're right @angaither sorry for the confusion. It just shouldn't show up on static content nodes.

It should only show on campaign nodes, campaign group nodes, and taxonomy terms.

**Comment by chloealee** [comment]
@mikefantini @angaither It looks like this has already been fixed? I can't seem to replicate and the below doesn't have the bar anymore! 

https://thor.dosomething.org/mx/sobre/%C2%BFqu%C3%A9-es-dosomethingorg

**Comment by chloealee** [comment]
I mis-understood. Looks like this isn't popping up because @sbsmith86 's code got reverted somehow? Ref #5078

**Comment by chloealee** [comment]
@sbsmith86 came by and walked me through this! We added back her code that got reverted somehow and made a fix for this. PR coming in the next few min!
