### ISSUE TITLE
MX/BR problem share images need to be generated using the SP/BR fact

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5751]
![image](https://cloud.githubusercontent.com/assets/6330971/11045686/e8d131d2-86f6-11e5-83e6-b5d51055f83a.png)

Also note for these we are not actually translating the fact, we're just referencing a different fact in the MX/BR translation of the campaign.

**Comment by sbsmith86** [comment]
Just making a note for myself. I think what we have to do is get all the translation facts for the campaign node and then when cron runs we have to create images for each one. We should probably store the images in folders that correlate to their country prefix, and then when building out the social media buttons, we will have to find URL of the problem share image based where the user is coming from. So if the user is at `/mx/etc` we would look for the problem share images in the 'mx' directory. 

I am a little concerned about performance, as the english images already take a relatively long time to generate, if we have to do three per campaign (or more as we add more languages) it will take even longer.
