### ISSUE TITLE
Full width gallery pattern - static content

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#5753]
We've been talking about this for a while, @DFurnes @lkpttn @mikefantini all know what's up. We need more flexibility on localized static content pages. Here's a sketch for full width gallery pattern:

[full width static gallery pattern.pdf](https://github.com/DoSomething/phoenix/files/30353/full.width.static.gallery.pattern.pdf)

Additional thoughts?

**Comment by DFurnes** [comment]
Yeah, I like this idea. This looks like a `.container__block` with an `img` in it (probably using our `1440x810 px` image style) and a `container__block.-narrow` below it.

**Comment by mikefantini** [comment]
@angaither can you please assign out when you have a chance?

**Comment by angaither** [comment]
@DFurnes wanna take a stab at this?

**Comment by DFurnes** [comment]
Sure! :hocho:

**Comment by angaither** [comment]
🔨 

![image](https://cloud.githubusercontent.com/assets/645205/15408394/03135bdc-1dde-11e6-9f15-2a145388b902.png)
