### ISSUE TITLE
Show More shows up on finder even if there are no more results

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5754]
![image](https://cloud.githubusercontent.com/assets/6330971/11046263/5aafeec6-86fa-11e5-96cb-4a39652ea1f4.png)

**Comment by DFurnes** [comment]
The Solr response is showing more "matches" than are being passed (for example, the query for the selections you used above [shows "2" matches exist](https://cloud.githubusercontent.com/assets/583202/11046405/4007babc-86fb-11e5-8faa-457634139140.png) even though only one is returned). My guess is that unpublished nodes might be counting towards the given total.

@blisteringherb We're using `grouped.entity_id.matches` to [determine whether or not to show the pagination link](https://github.com/DoSomething/phoenix/blob/860b7b8c1a7382cdf136bd1547fc7708e3eca66a/lib/themes/dosomething/paraneue_dosomething/js/finder/ResultsView.js#L108-L109). Should I be switching that to a different value now that we're doing global stuff, or is this a bug in our Solr configuration?

**Comment by DFurnes** [comment]
@blisteringherb Any ideas? I'm going to re-assign to you since it seems like Solr is sending incorrect information to the Finder, but let me know if there's something that needs fixing on my end!

**Comment by namimody** [comment]
@blisteringherb should I move this to the devops repo? thanks!
