### ISSUE TITLE
Add Drupal.t() in DS Validation package

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5759]
The following validation messages need to be wrapped in the `Drupal.t()` function for the time being until the Validation package is updated to allow customizing the messages from within the main project that pulls in the Validation dependency.
- [x] "Looks good!"
- [x] "That doesn't match."
- [x] "Did you mean {$suggestion}? Fix it!"

**Comment by DFurnes** [comment]
This should be good now in `v0.2.2`, pending new translations.

**Comment by DFurnes** [comment]
Re-assigning to you, @weerd, for the translationz.
