### ISSUE TITLE
Fastly caching on GET endpoints

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5762]
I'm pretty sure @blisteringherb already started on this work. Just creating an issue now so others can chime in and follow along on progress if need be.

---

We're occasionally seeing slow response times (anywhere from > 5000ms to 40000ms) from the Phoenix API when hitting it from the mobile app and from Runscope tests. Improving the response times here will greatly improve the UX of the app and, particularly when the calls either throw a 503 or have response times > 30000ms, avoid timeout errors on the app.

There could be more, but these were the ones we thought could be most helpful to cache:
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1300,1301,1302,1303&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1300&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1301&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1302&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1303&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/taxonomy_term/1300.json
- GET www.dosomething.org/api/v1/taxonomy_term/1301.json
- GET www.dosomething.org/api/v1/taxonomy_term/1302.json
- GET www.dosomething.org/api/v1/taxonomy_term/1303.json

**Up for discussion?**
- GET /reportback-items - There was some Drupal caching work done here with #5726. Could it also make sense to put this behind Fastly?

cc: @marahml @sheyd

**Comment by marahml** [comment]
Hey @blisteringherb thanks again for your help on this! Once this is done, we'll be able to submit to the app store. Hoping to do this in the next couple of days. For context, due to the lengthy review process - if we don't submit the app this week, it may end up pushing the launch to 2016.

Let me or @jonuy know where we can help in providing more info!

**Comment by jonuy** [comment]
@marahml Hi! @blisteringherb told me in our #api room that he's made caching improvements in Fastly for the endpoints listed.

I'm gonna see what improvements in response time Runscope reports with its daily email tomorrow. But so far so good it seems!

**Comment by blisteringherb** [comment]
I've added a `Surrogate-control: maxage=86400" header to these endpoints:

```
GET www.dosomething.org/api/v1/taxonomy_term/1300.json
GET www.dosomething.org/api/v1/taxonomy_term/1301.json
GET www.dosomething.org/api/v1/taxonomy_term/1302.json
GET www.dosomething.org/api/v1/taxonomy_term/1303.json
```

Fastly documentation indicates that the Surrogate control header will instruct Fastly to cache those endpoints. It overrides the Cache-control header.

**Comment by angaither** [comment]
@blisteringherb @jonuy are we :ok: to close this issue out?

**Comment by blisteringherb** [comment]
I think we should be good on this.
