### ISSUE TITLE
Drupal caching on campaign API endpoints

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5763]
Both Runscope tests and anecdotal mobile app testing have shown occasionally slow response times or 503 error codes on GETs to the campaigns API endpoint. I'm not sure how much of a gain we'd get here compared to #5762 and I'm not even particular certain on what objects we'd cache, but it's worth investigating.

In particular, the mobile app makes calls like:
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1300,1301,1302,1303&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1300&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1301&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1302&mobile_app=true&mobile_app_date={yyyy-mm-dd}
- GET www.dosomething.org/api/v1/campaigns.json?term_ids=1303&mobile_app=true&mobile_app_date={yyyy-mm-dd}

**Bonus though should totally maybe be a separate issue**
These calls also get made from the Android app and Runscope's recently been showing ~10000 ms response times on them from staging at least:
- [staging] GET www.dosomething.org/api/v1/taxonomy_term/667.json
- [staging] GET www.dosomething.org/api/v1/taxonomy_term/668.json
- [staging] GET www.dosomething.org/api/v1/taxonomy_term/669.json
- [staging] GET www.dosomething.org/api/v1/taxonomy_term/670.json
- [prod] GET www.dosomething.org/api/v1/taxonomy_term/1300.json
- [prod] GET www.dosomething.org/api/v1/taxonomy_term/1301.json
- [prod] GET www.dosomething.org/api/v1/taxonomy_term/1302.json
- [prod] GET www.dosomething.org/api/v1/taxonomy_term/1303.json

cc: @marahml @angaither

**Comment by weerd** [comment]
@jonuy side note, the `/taxonomy_term` endpoint didn't get the treatment I did to aim for the Transformer approach etc. Maybe something worth eventually investing into to do that. Is that to return Campaigns based on, for example `/taxonomy_term/1303.json`? If so, we could probs just switch them to use using the `/campaigns.json?term_ids=1303` etc...

**Comment by jonuy** [comment]
@weerd The taxonomy_term endpoint is being used to get the name of the term id. The idea is that depending on the campaigns tagged, the name could change from month to month.

We've also talked about just setting up entirely new vocabulary for the mobile app to use. But yea, that's probably outside the scope of this issue.

**Comment by weerd** [comment]
Isn't the name of the `term_id` provided in the `/campaigns` endpoint along w/ the id?

![screen shot 2015-11-11 at 2 07 53 pm](https://cloud.githubusercontent.com/assets/105849/11100192/c2dd0dba-887d-11e5-836a-140c9350ccd2.png)

But I could be misunderstanding...

**Comment by jonuy** [comment]
Indeed it is. From an implementation standpoint it was just easier getting it from the taxonomy_term endpoint instead of digging into a campaigns object, searching through an array, and then pulling that back up and out to where the relevant UI would be able to use it.

**Comment by weerd** [comment]
Gotcha, ok.
