### ISSUE TITLE
A black rectangle lingers after removing a video on the campaign template

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5773]
https://staging.dosomething.org/us/campaigns/teens-jeans

![image](https://cloud.githubusercontent.com/assets/6330971/11150269/446036a0-89f5-11e5-8d10-7ed7bf19c029.png)

@angaither we need a solution for this for Monday's Teens for Jeans soft launch.

**Comment by angaither** [comment]
strange, it seems to still be pulling a video from an old revision. 
@sergii-tkachenko @blisteringherb any idea why this would happen?
cleared cache a million times, replaced the video, removed the video, nothing.
my local correctly removes the reference to the video
![image](https://cloud.githubusercontent.com/assets/645205/11151600/03d8f2a0-89fc-11e5-8077-4004afab4dcd.png)

**Comment by sergiitk** [comment]
@angaither Note: video is not yet translatable.

**Comment by angaither** [comment]
@sergii-tkachenko not trying to translate the field, it had a value in a previous revision and now it's removed, but the dpm shows it's still pulling something

**Comment by sergiitk** [comment]
Yes, just decided to mention that it should not be affected by all the translation stuff.

**Comment by sergiitk** [comment]
Could it be redis cache?

**Comment by angaither** [comment]
@sheyd and I just tried clearing redis cache, and it still appears. maybe it needs 100 clears?

**Comment by sergiitk** [comment]
@angaither The field is empty on the backend.
![image](https://cloud.githubusercontent.com/assets/672669/11151885/327e80f2-8a38-11e5-8e3a-159ff7560001.png)

**Comment by sergiitk** [comment]
So it shoes empty html
![image](https://cloud.githubusercontent.com/assets/672669/11151906/4b992574-8a38-11e5-9f1e-4f4d573b92d8.png)

**Comment by angaither** [comment]
right, but if you look at the dpm, that html is there because `field_video` is not empty
