### ISSUE TITLE
Content Disappears from "Hot Module progress override copy" Backend

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5787]
You can fill out the "Hot Module progress override copy" field, save, and see the content appear in the speech bubble of the hot module. However, when you return to https://www.dosomething.org/us/node/2091/custom-settings, no content appears in the "override copy" field.

![image](https://cloud.githubusercontent.com/assets/12396076/11198555/96615510-8c93-11e5-8fab-a829775f04ed.png)

**Comment by angaither** [comment]
@deadlybutter mind taking a stab at this one?
I don't think you can use `variable_get` [here](https://github.com/DoSomething/phoenix/commit/63755498f7fe7400fe99555058c714a131af6e5c) since it's a custom dosomething config var, not a drupal default variable.

**Comment by itsjoekent** [comment]
oh yeah, i think this needs to use the $vars
