### ISSUE TITLE
Extra Space in Between Copy and State Selector Dropdown Menu

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5788]
The extra space appears on https://staging.dosomething.org/us/campaigns/teens-jeans (or any campaign with a school finder) like so:

![image](https://cloud.githubusercontent.com/assets/12396076/11198682/c6884da6-8c94-11e5-9997-56c917e9bdef.png)

**Comment by mikefantini** [comment]
@angaither it would be good to assign this one out as well as a backlog issue to be picked up.
