### ISSUE TITLE
Markdown Not Appearing For Tips In School Finder

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5789]
Help text appears like this in the front end:
![image](https://cloud.githubusercontent.com/assets/12396076/11199265/06809d28-8c9a-11e5-8b9e-9d1a685e6975.png)

But should be numbered, as the content is numbered in the Do Something config.

Not sure if this is helpful/expected behavior, but markdown is also not possible in the "form copy" field. **Bolding** words does not work.
![image](https://cloud.githubusercontent.com/assets/12396076/11199393/092e6f72-8c9b-11e5-8f10-125b7992bb95.png)

**Comment by mikefantini** [comment]
The priority culprit is the copy that can be found here https://www.dosomething.org/admin/config/dosomething/dosomething_user:

![image](https://cloud.githubusercontent.com/assets/6330971/11214501/a1b88f10-8d0f-11e5-8f04-705e214dc422.png)

**Comment by mikefantini** [comment]
@angaither mind assigning this one out?
