### ISSUE TITLE
POEditor language should be based on URL

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5791]
As a user in Brazil, if I go to a GL EN translation of a campaign, the text in POEditor should be in English not Portuguese.

Content should be based on URL - https://thor.dosomething.org/campaigns/cleanup-drills.

![image](https://cloud.githubusercontent.com/assets/6330971/11215694/89d60ade-8d15-11e5-9ddc-95773983dc59.png)

**Comment by mikefantini** [comment]
... this seems to work properly sometimes. Not sure what the pattern is.

**Comment by mikefantini** [comment]
Is it because of this?

https://thor.dosomething.org/admin/config/regional/language/configure

![image](https://cloud.githubusercontent.com/assets/6330971/11219096/79d79ace-8d26-11e5-89f5-c868226a8bbc.png)

Is following the user's language preference causing this inconsistency with POEditor?

cc: @angaither @mshmsh5000

**Comment by weerd** [comment]
@mikefantini I'm reasonably certain that the `t()` that uses the PO translations can't be otherwise controlled apart from the language settings. How it works is dictated on what Drupal thinks is the correct language to use and that's based on the above language config.
