### ISSUE TITLE
malformed urls on campaigns with special chars

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5796]
try with `/node/2259` on thor/prod

clicked view from the node edit page
![image](https://cloud.githubusercontent.com/assets/645205/11221675/5e45d768-8d34-11e5-97c1-52d40c8830cd.png)

clicked on the campaign from the homepage
![image](https://cloud.githubusercontent.com/assets/645205/11221686/6ff62a12-8d34-11e5-9707-655fd8df4e87.png)

hit the url dosomething.org/node/2259
also got a 404

**Comment by mshmsh5000** [comment]
Clicking through from the search results [works fine for me](http://cl.ly/3A1U2n3b0Z2G). This version of the URL works fine when pasted directly into Chrome, for instance:

https://www.dosomething.org/br/voluntario/bandeira-de-espa%C3%A7o-seguro

Chrome substituted the appropriate character, and then successfully makes the request: http://cl.ly/1X2x39351n04

In fact, I'm unable to reproduce this on any browser @mikefantini @angaither. I wonder if it's (a) a transient problem or (b) browser/browser-version-dependent.

**Comment by angaither** [comment]
hm, also unable to reproduce coming from br
though when I clicked `view` from `/node/2259/edit/pt-br` I get taken to the english url with a redirect loop
![image](https://cloud.githubusercontent.com/assets/645205/11747864/8d5e4608-9ff3-11e5-848b-3a73a078e32d.png)

**Comment by itsjoekent** [comment]
unable to reproduce redirect loop above ^ ?? should my torgaurd be enabled to test that?

**Comment by angaither** [comment]
@deadlybutter yeah, was testing on thor, with torguard

**Comment by angaither** [comment]
as a br editor, with my lang set ;)

**Comment by itsjoekent** [comment]
connected to brazil via tor gaurd, set user lang to br, clicked edit, went to the /edit/pt-br, clicked view, went to https://www.dosomething.org/br/voluntario/bandeira-de-espa%C3%A7o-seguro (worked on, no redirect loop error).

da fuq is happening

**Comment by angaither** [comment]
malformed is no longer an issue, opening a new one for the redirect loop

**Comment by itsjoekent** [comment]
:repeat:
