### ISSUE TITLE
dosomething_settings_get_geo_country_code()` defaults to "IS"

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5802]
When testing on local (https://github.com/DoSomething/phoenix/pull/5801) with TorGuard not running, `dosomething_settings_get_geo_country_code()` returns "IS" as the country code. 
- Is it possible that the default when the user geo location is unknown is not working?

Example `user_register` payload with user language and country settings:

```
Array
(
    [activity] => user_register
    [email] => dlee+update-test98@dosomething.org
    [uid] => 1705551
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 3.5 million
            [FNAME] => Test
        )

    [user_country] => IS
    [user_language] => en-global
    [email_template] => mb-user-register-GL
    [mailchimp_list_id] => 8e7844f6dd
    [birthdate] => 771465600
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )

)
```

**Comment by angaither** [comment]
@DeeZone that's the country code from iceland
where were you coming from in torguard?  
I haven't noticed this issue and have seen country codes coming in correctly

**Comment by deezone** [comment]
@angaither 

> When testing on local (#5801) with TorGuard not running

so in effect I was coming from the "US". I'll keep an eye on this to see if it keeps happening with other tests I'm running today.

**Comment by angaither** [comment]
@DeeZone when you test locally, you have to manually set the headers [with the mod headers chrome tool](https://github.com/DoSomething/phoenix/wiki/Fastly-Global-Header-Setup#fastly-headers-and-mappings)

**Comment by deezone** [comment]
Cool, good to know. Thanks.
