### ISSUE TITLE
Reportback Entity Include Reportback Language

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5803]
When a user reports back, the submission generate a `reportback` entity. The entity is sent to `dosomehting_reportback_mbp_request($entity)` which needs the language of the campaign to define what language the report back transactional email template and related merge_vars should be in.

**Related / Blocking**:
- https://github.com/DoSomething/phoenix/pull/5801

cc @mikefantini

**Comment by deezone** [comment]
@angaither @mikefantini Any thoughts on who can work on this? I've never done custom entity work within Drupal 7. Happy to take a shot if you're good with my bumbling.

**Comment by angaither** [comment]
@DeeZone you should be able to call `dosomething_global_get_language()` with the correct params to get the node language

**Comment by deezone** [comment]
@angaither The tricky thing about `dosomething_global_get_language($account, stdClass $node = NULL, $respect_url = TRUE)` is the `$node` is not the campaign node but rather the reportback object when it comes time to trigger the transactional request. I think @blisteringherb ran into this as well.

Perhaps `dosomething_global_get_current_prefix()` could be used?

**Comment by angaither** [comment]
@DeeZone the reportback entity should have `nid` attached to it, you can pass that through 

`dosomething_global_get_language($account, node_load($entity->nid))`

**Comment by deezone** [comment]
General functionality working. Possible bug in #5935 still to be resolved.
