### ISSUE TITLE
Clicking to Campaign from User Profile 404s

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5805]
Clicking on a campaign photo, campaign title, or PROVE IT button on a user profile should bring you to the campaign action page (and clicking on the photo or PROVE IT button should bring you directly to the PROVE IT section of the campaign). 

Currently, clicking on an image or clicking on the PROVE IT button brings the user to a 404. The URL after clicking the image or the PROVE IT button is something like: https://www.dosomething.org/us/us/campaigns/staring-stars#prove. It is likely that the /us/us is what is causing it to 404.

![image](https://cloud.githubusercontent.com/assets/12396076/11254137/241b6452-8e0d-11e5-9246-2ca65486761b.png)

cc @mikefantini

**Comment by mikefantini** [comment]
@angaither it would be great to get a fix pushed to prod this sprint if possible.

**Comment by angaither** [comment]
@deadlybutter mind taking a look at the double country code in the profile here?

**Comment by itsjoekent** [comment]
the href is broken, not a redirect problem

> href="/us/us/campaigns/thumb-wars#prove"

gonna checkout the preprocessing logic for this
