### ISSUE TITLE
Some Edit Links on Content Search View Don't Work

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5806]
In the content search view (https://www.dosomething.org/admin/content/search?title=&type=All&field_cause_tid=All&status=All&language=All&page=1), some of the edit links simply refresh the view instead of loading the /edit tab of a campaign. 

For example, experience is borked for "Senseless Attacks" and "Happy Scrappy Holidays" and "Let's DO This" but works for "Paris peace sign" and the wrapping paper waste facts. I can't seem to find a clear rule about what works and what doesn't, but if that rule is key to fixing the bug, I can do some more digging.

![image](https://cloud.githubusercontent.com/assets/12396076/11254683/230b9674-8e10-11e5-8b94-cb98d75c53ff.png)

This is related to https://github.com/DoSomething/phoenix/issues/5114

**Comment by angaither** [comment]
@deadlybutter looks like the `?desination=` string isn't getting removed from the `view_alter`
that might still be what's causing these to reload the page?

**Comment by itsjoekent** [comment]
weird I thought we fixed that

**Comment by itsjoekent** [comment]
oh this is on admin/content/search and we fixed just admin/content
