### ISSUE TITLE
Fix global links generated by url() function

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5810]
Urls and links, generated by `url` function with appear to be broken:

> - I've caught it not properly apply the path alias on nodes (on global / translated titles)
> - It often makes duplicate prefixes (like what the referenced bug here is describing)
> - I've also had problems with it applying the correct language to a URL
> 
> This is why for many days now I've been manually building the URL with path_alias and get prefix, because it always works fine without problem. Whereas url() consistently gives me problems and does not behave well with global functionality.
> @deadlybutter, https://github.com/DoSomething/phoenix/pull/5808#discussion_r45375334

Examples: #5796, #5474, #5423, #5808

cc @angaither

**Comment by mikefantini** [comment]
@angaither is this one we should add to 2.1 milestone?
