### ISSUE TITLE
Remove signup by promo code

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5816]
@aaronschachter is it safe to revert the [entire pr](https://github.com/DoSomething/phoenix/pull/4243/files)?

**Comment by aaronschachter** [comment]
I _think_ so, but I don't know for sure -- I remember work some was done in Northstar to support querying by signup source, so it may use this code (and should also be removed) cc @jonuy. The iOS app def isn't hitting any of those endpoints.
