### ISSUE TITLE
Campaign Titles w/ a ' Appear Incorrectly in User Profile 

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5818]
"Don't Be a Sucker" and "Re-poppin' Bottles" campaign titles appear incorrectly in the user profile "You're Doing section. Linked here (https://www.dosomething.org/us/user/1193105) and as shown below:

![image](https://cloud.githubusercontent.com/assets/12396076/11284753/89db07b2-8ed9-11e5-83ac-faf382879ddd.png)

![image](https://cloud.githubusercontent.com/assets/12396076/11284776/b0c440fa-8ed9-11e5-90de-b3b41453af1e.png)

The campaign titles appear correctly in internal search, and once they fall into the "You Did" section of the user profile, as shown below:
![image](https://cloud.githubusercontent.com/assets/12396076/11284768/9f45a4b8-8ed9-11e5-9abe-80cc27c6427a.png)

**Comment by angaither** [comment]
I feel like we've fixed this :100: times.

**Comment by angaither** [comment]
i can't find user profile ones, but checcck it
#1694
#4286
#4287
