### ISSUE TITLE
Editors are 404'd When Trying to Add Reportback

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5821]
Sometimes campaign leads need to add a reportback for a user because the member is having trouble with the form or the campaign has already closed. 

However, when leads (Lizzy, UID 2806506, editor and member support role designations) try to add a reportback via the flows shown below (at https://www.dosomething.org/admin/users/rb/add), they can't. They can access the "add reportback" URL and add all necessary information, but upon clicking "submit your pic" get 404'd. This is not a problem for me (UID: 1193105, administratior + editor + creative team role designations)

(This is a bug on both staging and prod)

![image](https://cloud.githubusercontent.com/assets/12396076/11303411/cd8a7dca-8f70-11e5-804a-ca637c604227.png)

**Comment by angaither** [comment]
@namimody I'm seeing this work on stage/thor as an editor/member support role

I think the reason you would get 404'ed is when you don't select a user from the autocomplete and it can't associate it with a user
then you would get taken to `/reportback/?fid=XXXX`

**Comment by namimody** [comment]
Yep, that was it @angaither! Thanks!
