### ISSUE TITLE
Bug with disabling Optimizely

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5824]
Ref #5798.

1) This code block is never being executed on staging, only on local
2) This code won't work, because it asks for for the confirmation interactively

```
Disabling Optimizely module on staging.
The following extensions will be disabled: optimizely
Do you really want to continue? (y/n): y
```

3) You also need to uninstall the module

cc @angaither

**Comment by angaither** [comment]
https://github.com/DoSomething/phoenix/pull/5813

**Comment by sergiitk** [comment]
Duplicate of #5811.
