### ISSUE TITLE
Delete RB Button Not Working on UK Site

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5838]
Images can be deleted via marking as flagged and then checking "delete this image"
![image](https://cloud.githubusercontent.com/assets/12396076/11372962/2680600e-929e-11e5-8b17-2efc1681f348.png)

but entire RBs cannot be deleted via https://uk.dosomething.org/reportback/338%3Ffid%3D790/edit and the delete tab at the top. 
![image](https://cloud.githubusercontent.com/assets/12396076/11372987/3ce21c8e-929e-11e5-9231-bdd6e4801f7a.png)

Clicking delete results in this error message and the continued existence of the RB.

![image](https://cloud.githubusercontent.com/assets/12396076/11373031/6a141644-929e-11e5-965e-ba200a4bdc92.png)

**Comment by namimody** [comment]
As a note, this button is working on the US site.

**Comment by mikefantini** [comment]
@namimody has this come up recently? Personally I don't really think it's a huge deal and not worth fixing, especially because there are work around (i.e. delete image upon flagging and edit quantity). Thoughts?

**Comment by namimody** [comment]
@mikefantini I'm fine with that. this came up on 11/24, and all I said is that I would make an issue, but no timeline. happy to just communicate the workaround if that works best.

**Comment by mikefantini** [comment]
Yeah let's please do that @namimody
