### ISSUE TITLE
Apply bounce rate fix to international branch

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5846]
Remember #5119? It's still a problem on the international sites. Let's please apply the PRs (#5536 and #5478) to that branch.

**Comment by DFurnes** [comment]
Whoops, should've left a comment on this. The relevant commits (d55d3083e83f9a7049a282d54c37b1149aff09d2, 349cef918dbdff34de2679060e1b1cc885388122, and cd5073cd3b3cc471c657a88e9f09e56141734ca0) have been cherry-picked to the [`intl-sites`](https://github.com/DoSomething/phoenix/tree/intl-sites) branch and should be ready to deploy.

**Comment by mshmsh5000** [comment]
:+1:

**Comment by sergiitk** [comment]
International release tag created: https://github.com/DoSomething/phoenix/releases/tag/intl-v1.0.1
