### ISSUE TITLE
Make additional fields translatable on the campaign template

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5849]
We've run into a few instances in which we wanted to create translations for campaigns (GL EN or otherwise) but couldn't because certain fields weren't translatable. It seems like this was mainly caused by:
1. campaign had a scholarship
2. campaign had a file in the Plan It Section in English
3. campaign was in high season (and that content is not ready for POEditor)

So because of this, it seems like we need to make the following fields translatable:
- [ ] field_scholarship_amount
- [ ] field_official_rules
- [ ] field_downloads
- [ ] field_high_season
- [ ] field_display_end_date

cc: @namimody

**Comment by mikefantini** [comment]
cc: @julielorch @mnelson338 

Also @mnelson338 I can't remember, but did we need to make any/many translations unpublished because they were MCC?

**Comment by mnelson338** [comment]
Not a pressing need right now for MCC @mikefantini
