### ISSUE TITLE
Hot Module Ignores Month When Counting Down

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5856]
For example, https://www.dosomething.org/us/campaigns/treat-yo-friends ends on Dec 31. However, the page shows: 

![image](https://cloud.githubusercontent.com/assets/12396076/11486593/15fb9584-9788-11e5-8702-9a15a0197236.png)

with the correct date in the header photo, the correct x-axis on the graph, but the dark blue banner (showing 30 hours left) is counting down from the date only -- as if tomorrow is the 31st and the deadline is November 31st, seemingly ignoring the end month.

Currently hacked in Optimizely here: 
Treat Yo Friends: https://app.optimizely.com/edit?experiment_id=4029790077
50 Cans: https://app.optimizely.com/edit?experiment_id=4029960026
GGW: https://app.optimizely.com/edit?experiment_id=4027640328

**Comment by angaither** [comment]
oh, doi, when we get difference back, we [literally ignore the month](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc#L634-L635)

![image](https://cloud.githubusercontent.com/assets/645205/11666009/41f5fa9a-9db8-11e5-8736-9cfb1e5195b0.png)
