### ISSUE TITLE
User activity sync script 

### ISSUE THREAD

**Issue by chloealee** [DoSomethingArchive/legacy-website#5859]
I am working on an update to sync user activity data between pheonix and northstar so every time a user signs up or submits a reportback on the web, the mobile device will also be aware of this and all user activity will be up-to-date (https://github.com/DoSomething/phoenix/issues/4571).  

However, this will only sync activity after the code is merged so we'll need to run a script that transfers/syncs campaign activity that happened pre-merge of https://github.com/DoSomething/phoenix/issues/4571.

**Comment by angaither** [comment]
before any of this happens, we need a way to mass migrate this info, without logging in each user.
we will also need to override the `created_at` attributes and submit the timestamps from the signups and reportbacks

### migrate signups
1. will need a way to force send a timestamp
2. timestamp should be converted to mongo date format

```
select u.uid, u.mail, s.sid, s.nid, s.timestamp
from users u
inner join dosomething_signup s on s.uid = u.uid;
```

### migrate reportbacks

```
select u.uid, u.mail, r.rbid, r.nid, r.created, r.quantity, r.why_participated, r.num_participants, rf.fid, f.filename, concat("/sites/default/files/reportbacks/", r.nid , "/", f.filename) as link
from users u
inner join dosomething_reportback r on r.uid = u.uid
left join dosomething_reportback_file rf on r.rbid = rf.rbid
inner join file_managed f on f.fid = rf.fid
```

this above query will NOT work for campaigns that have been closed and the reportback is now associated with a different nid

**Comment by angaither** [comment]
Instead of syncing data to northstar, which will probably get out of sync, we can call to get this info from NS so we are going #6110 route instead
