### ISSUE TITLE
Campaign Collections are missing content on front end

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5862]
Content is not being output properly on Campaign Collections. The following fields/field collections aren't working as intended:
- `field_intro_title` 
- `field_intro`
- `field_faq`
- `field_gallery`

Not sure if other content is being displayed properly or not.

example: https://www.dosomething.org/volunteer/step-game

Potentially related to #5714

**Comment by angaither** [comment]
It looks like it's because the fields are translatable and I disabled fallback, was this displaying correctly before @mikefantini?

**Comment by mikefantini** [comment]
Hmmm @angaither I actually think it may be because that node is unpublished. @sergii-tkachenko didn't you run a script to fix this for published nodes?

It's working properly on https://www.dosomething.org/volunteer/seniors-and-smartphones

**Comment by mikefantini** [comment]
This issue also exists on thor:

https://thor.dosomething.org/volunteer/step-game

**Comment by mikefantini** [comment]
Ok so for Collection nodes the fix @sergii-tkachenko did was this: https://github.com/DoSomething/phoenix/pull/5691 and he executed it here: https://github.com/DoSomething/phoenix/issues/5724.

It seems like this just needs to be done again for unpublished nodes.

Are you able to take this on @sergii-tkachenko?

cc: @angaither

**Comment by sergiitk** [comment]
@mikefantini Ah, sorry again for the confusion. It did not excluded unpublished nodes, that was a fix FOR unpublished nodes.
