### ISSUE TITLE
display error message if quantity is more than a 32 bit integer

### ISSUE THREAD

**Issue by tongxiang** [DoSomethingArchive/legacy-website#5863]
The largest 32 bit integer is `2147483647`. Submitting `2147483648` as a reportback quantity fails uninformatively, and leads Phoenix to direct the user to the 404 page with no error message. 

Discovered while working on [this issue](https://github.com/DoSomething/LetsDoThis-iOS/issues/668) in the mobile app. @aaronschachter

**Comment by itsjoekent** [comment]
I'm running on the assumption a user will never reportback a quantity of 2147483648

In that case we just need to build validation which prevents the user from doing this / handles the resulting error.

@mikefantini sound correct?

**Comment by mikefantini** [comment]
@deadlybutter I think this assumption is fine. I guess the other question is if any other large quantities fail.

In terms of validation error, I think a client side error of "Hmmm that seems a bit high" or something like that would be appropriate.

**Comment by itsjoekent** [comment]
:+1:

**Comment by tongxiang** [comment]
any quantity greater than `2147483647` will fail.

**Comment by angaither** [comment]
that's unreasonable anyways
