### ISSUE TITLE
Resolve global log errors

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#5866]
These are spamming the crap out of the log

MESSAGE Notice: Trying to get property of non-object in locale_language_url_rewrite_url() (line 429 of /var/www/dev.dosomething.org/html/includes/locale.inc).
LOCATION    http://dev.dosomething.org:8888/us/user/1700226
REFERRER    http://dev.dosomething.org:8888/us

LOCATION    http://dev.dosomething.org:8888/us/user/1700226
REFERRER    http://dev.dosomething.org:8888/us
MESSAGE Notice: Undefined index: country in dosomething_global_get_countries() (line 414 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_global/dosomething_global.module).

(This ^ is happening for multiple indexes, "en-global, pr-br, etc")

**Comment by sergiitk** [comment]
We're still receiving a bunch of `Notice: Trying to get property of non-object in locale_language_url_rewrite_url() (line 429 of /var/www/www.dosomething.org/releases/20151208192456/html/includes/locale.inc).` on every page.

**Comment by itsjoekent** [comment]
this ones been around for a while, was planning on looking into it

**Comment by itsjoekent** [comment]
I'm currently exceeding my backtrace limit, workin on fixing that.

so far all of the calls to this function _that I can see right now_ are coming from core. 

![screen shot 2015-12-16 at 2 17 35 pm](https://cloud.githubusercontent.com/assets/897368/11851299/f205182e-a3ff-11e5-84fd-9c59c1c1b336.png)

The common theme I'm noticing is this:

24  0.2469  5816728 url( )  ../common.inc:4240
25  0.2469  5817992 drupal_alter( ) ../common.inc:2243
26  0.2469  5818392 locale_url_outbound_alter( )    ../module.inc:1140
27  0.2469  5818392 locale_language_url_rewrite_url( )

So I'm guessing we have a bad "url" call somewhere.

This error happens when I..
- Click campaign from home page, click DS logo to go back to homepage
- Click campaign and refresh 

But not for static content or anything else from what I can tell.

I'll keep investigating.

**Comment by sergiitk** [comment]
@deadlybutter  Was this fixed?

**Comment by itsjoekent** [comment]
I didnt see it when I loaded Thor, are you?

**Comment by itsjoekent** [comment]
nevermind i apparently didnt click around enough, found it again

**Comment by weerd** [comment]
Duplicate issue... resolved with: #6522
