### ISSUE TITLE
Document Global Content Setup and Backend Details

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#5871]

**Comment by itsjoekent** [comment]
@sergii-tkachenko do you want me to take care of the redirect documentation?

**Comment by sergiitk** [comment]
Yes please! Thank you.

**Comment by itsjoekent** [comment]
https://github.com/DoSomething/phoenix/wiki/DoSomething-Global#redirect-logic

If you need me to document other global things let me know

**Comment by sergiitk** [comment]
Images for wiki:

**Comment by sergiitk** [comment]
![image](https://cloud.githubusercontent.com/assets/672669/11756288/9dd4cc64-a061-11e5-9745-a94f81d39b27.png)

**Comment by sergii-tkachenko** [comment]
![image](https://cloud.githubusercontent.com/assets/672669/11756718/b3c1af62-a064-11e5-95f5-02f9f4f10cbb.png)

**Comment by sergiitk** [comment]
![image](https://cloud.githubusercontent.com/assets/672669/11756728/caedd1e8-a064-11e5-9079-07dbb5ef203b.png)

**Comment by sergiitk** [comment]
Heredoc: https://github.com/DoSomething/phoenix/wiki/Making-content-translatable
