### ISSUE TITLE
Mobile App Transactionals

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5872]
Transactional email messages triggered by the mobile application are not resulting in the expected email messages. 

The request process is **Mobile App** -> **NorthStar** (UserAPI) -> **Drupal API** -> **Message Broker**. Somewhere in this flow the needed values are not being passed to result in a complete request to Message Broker.

**Issue Summary**:
- **`user_registration`**: Message not sent
- **`user_password`**: Message not sent
- **`campaign_signup`**: working as expected.
- **`campaign_reportback`**: `*|CAMPAIGN_TITLE|*`merge_var` is not set.
- Incomplete user document in `mb-user` database (used to generate digest messages).

**Example Incomplete User Document in `mb-user` Database**:

> Darren "Dee" Lee [20:28] via Slack
> @aaron: An example of a "funky" payload passing through Message Broker:
> 
> {
>    "_id" : ObjectId("565c96b0d86f5ff3f7341316"),
>    "email" : "don.draper+201511301024@dosomething.org",
>    "created" : ISODate("2015-11-30T18:26:17.350Z"),
>    "subscribed" : 1,
>    "campaigns" : [
>        {
>            "reportback" : ISODate("2015-11-30T18:26:41Z"),
>            "signup" : ISODate("2015-11-30T18:26:17Z"),
>            "nid" : 1503,
>            "_id" : ObjectId("565c94c935f7e1ad3e52221f")
>        }
>    ]
> }
> 
> This is flagged because there's no drupal_uid.
> 
> Searching the Drupal app for "don.draper+201511301024@dosomething.org" is not found and yet 
> the user is signed up for a campaign?
> 
> Does this look DS Mobile App related?

---

> Aaron Schachter [11:10] via Slack
> @dee to answer your question from last night - yes that’s a test user i’ve been using in the mobile 
> app. i’ve been testing mostly on staging. when we create users in northstar by passing
> `create_drupal_user=1"` into the query string which should create the account. but perhaps one of 
> the northstar endpoints is not sending the right data to the relevant phoenix reportback endpoint.  
> https://dosomething.slack.com/archives/phoenix/p1448933281001311

**Related / Duplicate**:
- https://github.com/DoSomething/phoenix/issues/5870

**Comment by deezone** [comment]
**Note to self**:
- User registration: dlee@dosomething.org, 347xxxzzzz
  - no transactional received.
- Second user registration: dlee+mobileApp-151203-01@dosomething.org
  - no transactional email received
  - no log entry for `dlee+mobileApp-151203-01@dosomething.org` in Mandrill or `mbc-transactional-email`.

**Assumptions**:
- A call from the mobile app is made to the userAPI (Northstar) to create a Drupal user. Existing user does not produce transactional email?
- Logout of app allows new user registration, "+" in registration email is seen as different user?

**Questions**:
- Where to look at mobileApp and userAPI logs for user registrations? Looking for entries for `dlee@dosomehting.org` and `dlee+mobileApp-151203-01@dosomething.org`.
- A call from the mobile app is made to the userAPI (Northstar) to create a Drupal user. Existing user does not produce transactional email?

cc @jonuy @angaither @aaronschachter - comments to questions?

**Comment by aaronschachter** [comment]
Just replicated the reportback bug getting a _CAMPAIGN TITLE_ email on staging: It was a PBJ Slam reportback transactional for `aschachter+20151207@dosomething.org`

@DeeZone Yes - no emails for an existing user. Not sure where / who should be looking into the user registration emails issue.

**Comment by aaronschachter** [comment]
Same email (missing the title merge tag) when reporting back with the same user for Mirror Messages.

**Comment by aaronschachter** [comment]
Also worth noting the Signup transactionals I received for these two campaigns worked ok -- the Campaign title was displayed properly in the copy

**Comment by deezone** [comment]
@aaronschachter Any comments to address the outstanding "Question" above?

> Where to look at mobileApp and userAPI logs for user registrations? Looking for entries 
> for dlee@dosomehting.org and dlee+mobileApp-151203-01@dosomething.org.

https://github.com/DoSomething/phoenix/issues/5872#issuecomment-161822247

**Comment by jonuy** [comment]
@DeeZone 

> Where to look at mobileApp and userAPI logs for user registrations?

I don't think there are any easily accessible logs at least to see. Would ssh'ing into the mongo db itself and checking out the documents there be enough? What sort of info are you interested in finding?

> Existing user does not produce transactional email?

If we've got the user in Northstar and that user's already got an assigned Drupal id (which I suspect should be the case in a majority of these scenarios) [we don't forward the call](https://github.com/DoSomething/northstar/blob/dev/app/Http/Controllers/UserController.php#L109) onto Phoenix. So yea, I can see in that scenario transactional emails not getting sent. I'm not sure though about the case where there's a user that exists on Phoenix but not on Northstar. Do we want to send a transactional if a user's account had already existed?

**Comment by deezone** [comment]
@jonuy vv ?

> Would ssh'ing into the mongo db itself and checking out the documents there be enough?

Queries on the Mongo db would work.

What's the Mongo server and db name? I seem to only be able to get at `mongo4` for the Message Broker stuff. Perhaps I need more rights once I know where to look. What Mongo server do you use for the mobile app / Northstar?

**Comment by deezone** [comment]
Thanks @jonuy , my response and question for perhaps you or @aaronschachter :

> If we've got the user in Northstar and that user's already got an assigned Drupal id (which I 
> suspect should be the case in a majority of these scenarios) we don't forward the call onto Phoenix.

That makes sense.

What about user password resets? The transactional email that provides a reset link in an email is not sent. Does that make sense in the case of the app? Can you reset your password via the mobileApp or perhaps that's on the roadmap?

**Comment by aaronschachter** [comment]
On the roadmap for version WayLater -- right now we direct users to the web in order to reset password.

**Comment by jonuy** [comment]
@DeeZone I'll DM you with info about connecting to the db

**Comment by deezone** [comment]
@aaronschachter 
- The transactional email to reset a password is required functionality - got it. 
- As opposed to the current state of transactional email for user registration not being sent for existing Drupal users is acceptable? Perhaps there should be a different transactional email sent for mobile app registration? Not to complicate the process but perhaps in fact make the process easier / more clearly defined.

**Comment by deezone** [comment]
@aaronschachter 

> right now we direct users to the web in order to reset password.

Odd, testing by Eva suggested the password reset from the app was not triggering a transactional email. If the user is simply provided a link to the password reset page this is something different. I'll make a point of walking through the process with the test app to better understand the process / experience / expectations / results.

**Comment by sergiitk** [comment]
Note: I tried to reproduce this on staging using `https://northstar-qa.dosomething.org/v1/user/campaigns/1283/reportback` API, but the campaign title seems to be there. I will try to do the sane on Production.

**Comment by sergiitk** [comment]
Additional investigation showed that Production is affected and staging is not.
I followed the same flow using northstar API on prod and staging:
- Login `/v1/login`
- Signup `/v1/user/campaigns/5779/signup`
- Reportback `/v1/user/campaigns/5779/reportback`

Only on production MB payload lacked `CAMPAIGN_TITLE` merge var.
I suspect that Northstar <-> Phoenix connection works through Fastly, which detects Northstar IP and adds some country/language specific headers that affect enduser language.

CC @DeeZone

**Comment by deezone** [comment]
@sergii-tkachenko Thoughts on next steps? 

Is it possible to track down the code that's affecting the enduser language? Perhaps there's defaults missing when the headers values are NULL?

**Comment by sergiitk** [comment]
So I think #6019 should fix it. Let's deploy this to prod and test.

**Comment by deezone** [comment]
:+1:

**Comment by sergiitk** [comment]
Fix confirmed on prod:
![image](https://cloud.githubusercontent.com/assets/672669/12335488/1d22675e-bb08-11e5-9d59-61be75ce7937.png)

**Comment by deezone** [comment]
Which means our system very dependent on the FASTLY headers working? Is this an issue or simply a technical fact? Is there a solution at the code level to provide feedback on the status of the headers? Should there be defaults when they're not working?

**Comment by sergiitk** [comment]
Actually, Fastly is the primary source of user geopositioning right now.

**Comment by itsjoekent** [comment]
yes, current implementation is very Fastly dependent. We do have some places in the code that null check its response however and i believe it uses english as the default in that case (as most of our users are english speaking)
