### ISSUE TITLE
Page Layout Breaks When Translation is Unpublished

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5873]
**What happened? What steps did you take before it happened?**
When a previously published GL EN version of a campaign is unpublished, the translation is correctly no longer accessible, but the page looks like the screenshot below.

To reproduce, publish both a GL EN and EN translation of a campaign, and unpublish the GL EN version. Using Torguard from Japan, try to access the campaign, you should see something like the screenshot below.

**What should be happening?**
Users should be brought to the US EN translation of the campaign.

**When did it start/when did you notice it?** 
Unsure.

**Is it low, medium, or high priority? If high, please state why.**
High. Campaigns that should only be published in US EN (because they have a scholarship) are also published in GL EN. If we unpublish the GL EN version, the page looks borked.

What device are you seeing it on?
Desktop.

Relevant Screenshots:
![image](https://cloud.githubusercontent.com/assets/12396076/11536693/8de35ad6-98e7-11e5-996c-10ba3be7e735.png)

**Comment by angaither** [comment]
I just tested this, it works meow!

**Comment by namimody** [comment]
@angaither what're you seeing if you go to the GL EN URL of a US EN only campaign as an anon user? I'm still seeing the page as shown above?

As an aside, the expected behavior noted above is likely incorrect. I think @mshmsh5000 and @mikefantini and I talked and thought the ideal UX for someone should be: if a user ends up on a campaign URL that is not translated for their country/language, they should see a landing page that allows them to choose which experience they would like to see. If that is what was decided, then I suppose we should close this issue and make one for creating that type of landing page?

**Comment by mshmsh5000** [comment]
I am +1 on the "choose an available translation" option, because it gives
the user a clear choice to make and eliminates any assumptions we would
otherwise make in this situation.

CTO
@mshmsh5000 http://twitter.com/mshmsh5000 @dosomething
http://twitter.com/dosomething
