### ISSUE TITLE
Calculation issue with total property in pagination object for API response

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5874]
![image](https://cloud.githubusercontent.com/assets/105849/11544904/69906bee-9912-11e5-81ac-74c4721ba701.png)

`retrieved_count` is 25 but the `total` is 0? :confused:

**Comment by aaronschachter** [comment]
@weerd I'm seeing this occur in the `campaigns` index endpoint when a count is not specified. Seems to work ok when a count is specified though.

![screen shot 2016-01-05 at 9 04 47 am](https://cloud.githubusercontent.com/assets/1236811/12121718/a368277e-b38b-11e5-9aa2-56e505f6291d.png)

![screen shot 2016-01-05 at 9 05 45 am](https://cloud.githubusercontent.com/assets/1236811/12121699/8d437714-b38b-11e5-9b09-6a0a4bcafc6b.png)

**Comment by weerd** [comment]
@aaronschachter ok. I'll reopen then and take another look. thanks for the heads up!

**Comment by weerd** [comment]
PR #5983 updates the total for RB items, but this is likely still off for campaigns. However, the fix for RB items sets up the approach to fix for other endpoints. Update coming as soon as Campaign run updates are done!

**Comment by weerd** [comment]
Closing for now. We can reopen if still an issue (or not if aiming for new content platform).
