### ISSUE TITLE
Add node status to translate tab

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5876]
Currently the translate tab shows original translation as published, even if the node is not
Add node status to that tab, to make it less confusing

![image](https://cloud.githubusercontent.com/assets/12396076/11547383/5bb106d2-9921-11e5-8316-5efc0b8023cc.png)
### Original report

**What is happening?**
When a campaign is created in x language, saved, and then the "translate" tab is viewed, the translation just created is noted as "published" even thought it was never published and 404s for anon users.

**What should be happening?**
Published statuses in the "translate" tab should reflect the actual published status...

**How can someone replicate it?**
Create a campaign, note the language. Save. Check the "translate" tab.

**When did it start/when did you notice it?**
I noticed it today.

**Comment by mikefantini** [comment]
@namimody I assume this happens because the node itself is unpublished. It's a bit confusing I guess because once the node itself is published, there's no real action that needs to be taken to get the English translation itself published.

I'm wondering if instead of worrying about this potential complexity we can just add to the top of this view the published status on the node itself? Not even sure if that's possible though.

@angaither @namimody thoughts?

**Comment by angaither** [comment]
@namimody @mikefantini yeah, it looks like by default the translation is published even if the node isn't

**Comment by mikefantini** [comment]
Yeah @angaither do you think it's possible to add published status of the node to the /translate view or is that v. hard?

**Comment by angaither** [comment]
it's probably not too difficult, though it might be a bit confusing with all the different ~published stati~
though in this :earth_asia:al life, what isn't confusing

**Comment by mikefantini** [comment]
![image](https://cloud.githubusercontent.com/assets/6330971/11594366/9605bb6e-9a77-11e5-8542-6181a7327257.png)

**Comment by mikefantini** [comment]
I think it's worth adding published status of the node to the top of this view. Either in the table itself or just above. And then we'll just have to educate people that if the node itself isn't published, it doesn't matter if translations are or not.

I do think this will clear things up especially for testing purposes.

**Comment by namimody** [comment]
:100: agreed!

**Comment by sergiitk** [comment]
@angaither @chloealee Sound like a legit bug. Should we report it to `entity_translations` [issues](https://www.drupal.org/project/issues/entity_translation)?

**Comment by angaither** [comment]
@sergii-tkachenko I mean, depends, it's showing the status of the translation, which is published

**Comment by sergiitk** [comment]
Looks like it is confusing not just to us: https://www.drupal.org/node/2428565
They propose to change the wording from "Published" to "Translated" to avoid confusion. Makes sense actually.

We easily make a patch and post it there. If not accepted, we can just use it by applying this patch via the installation profile.

Thoughts?

**Comment by chloealee** [comment]
@sergii-tkachenko that does make more sense! I'll work on making the patch to change the wording and submitting with your patch as a reference. Thank you!

**Comment by sergiitk** [comment]
Awesome. Let me know if you need any help on this. Also you're welcome to assign the PR to me if  you wish.

**Comment by chloealee** [comment]
Great, thanks so much! Will do. This is SO helpful - I would be very lost otherwise!

**Comment by namimody** [comment]
Hi @angaither and @chloealee -- after talking about this with @mnelson338 and the campaigns team -- this might actually be a more confusing configuration - Micah now has to go into each translations tab and scroll to the bottom to see if a campaign is published in a translation :/ 

Would it be possible to return the table to looking like this:
https://cloud.githubusercontent.com/assets/12396076/11547383/5bb106d2-9921-11e5-8316-5efc0b8023cc.png

**Comment by mikefantini** [comment]
Yeah so this is what we would want this to look like in order to clean this up:

![image](https://cloud.githubusercontent.com/assets/6330971/14327328/c16c23bc-fbff-11e5-86c1-7a4fa7b29165.png)

Key elements:
1. Node status. Indicates whether the node itself or published or not. Options for the value in that slot are Published or Unpublished.
2. Translation status. Indicates whether a translation on the node is published or not. Options for the value in that slot are Published, Unpublished, or Not translated (if no translation exists in that language).

So for this issue to be closed out it should essentially look like the screenshot in this comment.

**Comment by chloealee** [comment]
thanks @namimody and @mikefantini ! So, here's what needs to be changed:
1. Add comment under Node status to read "Translations are only published and live to the public if the   node is published as well. Use the node status to determine if a translation is published."
2. Translation status. Change status options to Published, Unpublished, or Not translated.

Did I get everything?

**Comment by namimody** [comment]
Hi @chloelee! 2 looks right to me. I think for the node status, @angaither
mentioned that we should keep the node published status, but not add the
help text because that's specific to our use case. Without the help
text, this patch is more likely to be pulled into Drupal. Cc @mikefantini
to confirm as well

On Thursday, April 7, 2016, Chloe Lee notifications@github.com wrote:

> thanks @namimody https://github.com/namimody and @mikefantini
> https://github.com/mikefantini ! So, here's what needs to be changed:
> 1. Add comment under Node status to read "Translations are only
>    published and live to the public if the node is published as well. Use the
>    node status to determine if a translation is published."
> 2. Translation status. Change status options to Published,
>    Unpublished, or Not translated.
> 
> Did I get everything?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/phoenix/issues/5876#issuecomment-206935798

## 

Namita (Nami) Mody

Product Manager: Internal Systems and Analytics
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255
(see all the badass things we did in 2015
https://www.dosomething.org/sites/default/files/Q4DASHV2.compressed.pdf!)

**Comment by chloealee** [comment]
@namimody ah okay - makes perfect sense! Thanks!

**Comment by mikefantini** [comment]
Yeah @chloealee @namimody we're no longer going to have the note "Translations are only published and live to the public if the node is published as well. Use the node status to determine if a translation is published."

**Comment by chloealee** [comment]
@angaither @sergii-tkachenko should I submit a new patch for this in the same [issue](https://www.drupal.org/node/2428565) we posted as last time? I don't think we should since we fixed the issue in the last patch and this would be changing it to not follow the request in the issue. Do we create a new issue and submit it there?

**Comment by sergiitk** [comment]
+1 For the new issue.

**Comment by chloealee** [comment]
great, thanks @sergii-tkachenko ! Here's the [new issue](https://www.drupal.org/node/2702055) with patch attached. I'll create a PR to get this in our code now.

**Comment by chloealee** [comment]
Here is the [link](https://github.com/DoSomething/phoenix/issues/5876) to the issue. cc @sergii-tkachenko

**Comment by sergiitk** [comment]
@chloealee Yes, I already commented on it.

**Comment by chloealee** [comment]
@sergii-tkachenko ah I see, you wanted me to add the link to the [patch](https://www.drupal.org/files/issues/entity_translation-adds_node_status_changes_to_unpublished_and_adds_translation_status_to_header-2702055-3-7.43.patch).
