### ISSUE TITLE
Associating Multiple Runs with Campaign, Prioritizing One Run to Show

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5877]
**Problem/Requirement:**
Campaigns open and close multiple times. Each time a campaign closes, a run is created, and signups/reportbacks are archived to the run. When the campaign reopens and runs again, we should be able to associate multiple runs with the same campaign. Then, we should be able to choose which one should display when the campaign closes again.

**Feature Summary:**
Currently, multiple runs can be associated with the same campaign, but one cannot choose which run is the most recent for display purposes.

**Current Workaround w/o Feature (if applicable):**
Currently, we have to associate old runs with other random (open) campaigns and associate the correct run with the correct campaign, close the campaign, and then publish the run. This has resulted in many runs randomly and incorrectly associated throughout the site. It is also a confusing experience for editors.

**Comment by angaither** [comment]
this should be a node reference field (perhaps a dropdown) `field_current_run` on the campaign node

the field should display only campaign run types
in the campaign module form alter, we can scope this to display only runs that have the current campaign nid in the field.

**Comment by angaither** [comment]
this field should be required!

**Comment by sbsmith86** [comment]
Should this field (should all fields?) be translatable?

![screen shot 2016-01-05 at 9 56 39 am](https://cloud.githubusercontent.com/assets/1700409/12118109/b9753a00-b392-11e5-86d0-52b4fd53ac32.png)

@angaither

**Comment by angaither** [comment]
@sbsmith86 great question. currently campaign runs are not translatable. So I suppose yes. so we can have different runs for different translations of the node. 

cc @namimody @mikefantini @mnelson338

**Comment by sbsmith86** [comment]
Closed with #5979
