### ISSUE TITLE
Improve campaigns response validation in Runscope test

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5881]
This is particularly helpful for the mobile app and ensuring the content it displays is setup properly.

**Runscope test:** https://www.runscope.com/radar/5tt8kuiumbfl/047608f5-3f9e-45d8-88f2-b02ae9f43b5b/overview

Currently, among other things, the validation setup will check if 12 campaigns are returned by the endpoint. But we're sometimes also finding campaigns that are tagged incorrectly. So while 12 may return and the test will pass, there may actually be 5 campaigns assigned to one tag leaving only 1 in another. This instead should be a failure.

Also take liberties to add more fine-grained validation and/or add more tests to the schedule.

cc: @marahml

**Comment by tongxiang** [comment]
Added a check that each of the four term IDs is represented by three campaigns each, and that no one campaign has been registered with more than one term ID.
