### ISSUE TITLE
Notice: Undefined variable: _SESSION in dosomething_global_init() line 22

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5883]
Open https://thor.dosomething.org/us/volunteer/animals as an anon.
Looks like the session hasn't been started yet at `dosomething_global_init()`.

**Comment by itsjoekent** [comment]
Not getting this locally? Its simple to fix 

```
    if (!isset($_SESSION)) {
      $_SESSION = array();
    }
```

but weird I can't reproduce

https://gist.github.com/deadlybutter/65f0c22da5927e0f8423

**Comment by sergiitk** [comment]
Do you see the error at https://thor.dosomething.org/us/volunteer/animals?
![image](https://cloud.githubusercontent.com/assets/672669/11569700/f5e14dfe-99fb-11e5-9ba9-14181f200903.png)

**Comment by itsjoekent** [comment]
Yep!

**Comment by sergiitk** [comment]
But not locally?

**Comment by itsjoekent** [comment]
Nope.

And it looks like we should just call this at the top

https://api.drupal.org/api/drupal/includes!session.inc/function/drupal_session_start/7

it will preserve the existing session and its more drupal-y

**Comment by sergiitk** [comment]
Makes sense.

**Comment by sergiitk** [comment]
Also, use `if (!empty($_SESSION['dosomething_global_redirected']))`.
