### ISSUE TITLE
Update validation on reportback-items Runscope test

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#5884]
**Runscope test:** https://www.runscope.com/radar/5tt8kuiumbfl/4eca9485-82fc-4ded-9f5d-00b766f627b1

All users on Phoenix should have a corresponding user on Northstar. So when a GET /reportback-items call is made, the `user` object should be populated with an id and first name at the very least. Yet, sometimes we'll see bugs where this is returned instead:

```
user: {
  id: null,
  first_name: null,
  photo: null,
  country: null
}
```

The current validations on the Runscope test let this pass, but we should probably fail it.

cc: @marahml

**Comment by tongxiang** [comment]
Added this line to the script section: `item.user.id !== null && item.user.first_name !== null`. (Within a for loop, we're iterating through all the reportback items and checking the user object. 

However, it seems like no staging reportbacks have valid user objects. Hence, this test for staging will always fail. Is that meaningful to us? @jonuy

**Comment by jonuy** [comment]
@tongxiang Yea, it's actually what prompted the need for this test. There should always be valid user objects and the previous validation rules didn't fail. The failures we're seeing now are things we should fix.
