### ISSUE TITLE
Cover image isn't displaying for non-admin users on taxonomy terms

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5888]
See thor.dosomething.org/volunteer/animals

**Comment by sergiitk** [comment]
I can't reproduce it anymore @mikefantini.

**Comment by sergiitk** [comment]
It works both on Thor and locally.

**Comment by mikefantini** [comment]
Hmm yeah neither can I. Ok I'll close out for now then @sergii-tkachenko and I'll just keep an eye out for it.

**Comment by sergiitk** [comment]
I think, as I suspected in Slack, this could be related to some of @deadlybutter's fixes for PHP notices that were on that page.

**Comment by itsjoekent** [comment]
:tada: 

dance
