### ISSUE TITLE
Campaign Names Disappear From Profile When Activity is Archived

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5889]
**What is happening?**
When activity is archived, a user who has reported back for that campaign no longer sees the campaign name associated with their reportback on a their profile.

**What should be happening?**
The name of the campaign run should show instead on a profile once the campaign activity is archived onto that run.

**How can someone replicate it?**
Report back for a campaign, create a run for it, and archive activity to the run. Check your user profile's RB section to see the campaign name gone.

**Relevant Screenshots:**
![image](https://cloud.githubusercontent.com/assets/12396076/11568944/138755ae-99bd-11e5-96ac-3ea7a31ab3cf.png)

**Comment by mikefantini** [comment]
@namimody I updated the desired behavior slightly. We actually want it to pull in the campaign run name. This is how it was working previously and is probably the easiest dev solution that also works from a UX perspective.

We may have to update campaign run titles to account for this (plus help text possibly?).

**Comment by namimody** [comment]
@mikefantini that works!

I actually found this issue because I (thought I) saw that the campaign run name was being pulled onto user profiles, but the help text for creating a campaign run titled noted that the title was not user facing. I'll go ahead and make that issue.

**Comment by angaither** [comment]
closing in favor of #5975
