### ISSUE TITLE
Change name of dosomething_helpers_isset()

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#5899]
Related to conversation in #5896

Look into changing the name of the function from `dosomething_helpers_isset()` to `dosomething_helpers_get_value()` to avoid confusion with core PHP function `isset()`

**Comment by angaither** [comment]
@weerd see [`dosomething_user_get_field()`](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1023) as a comp/help for this type of function

**Comment by weerd** [comment]
@angaither I'll take a looksee, but overall aiming to _not_ use `entity_metadata_wrapper()`. It's the :japanese_ogre:

**Comment by angaither** [comment]
oh wasn't suggesting that, more so [this](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1032-L1037)

**Comment by weerd** [comment]
Ah, ok! Will do :)

**Comment by weerd** [comment]
this is changing to use the new [`data_get()`](https://github.com/DoSomething/phoenix/blob/658b2516baffba8ff802a8f79100928454e38755/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L36) from the TightenCo `Collect` package which brings us Laravel-like collections.

So this issue just needs to now address going through and updating calls to `dosomething_helpers_isset()` with `data_get()`.

**Comment by itsjoekent** [comment]
![walkinwalkout](https://cloud.githubusercontent.com/assets/897368/18055156/bccfc286-6dd4-11e6-8489-789cdacfb0e7.gif)

**Comment by weerd** [comment]
Ended up adding the tightenco/collect package which contains a `data_get()` that's much more fleshed out and handles many more scenarios. `dosomething_helpers_isset()` is getting deprecated.
