### ISSUE TITLE
Hot module time left way off

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5907]
Everything says 9 hours left regardless of amount of time left:

https://thor.dosomething.org/us/campaigns/grandparents-gone-wired-0

https://thor.dosomething.org/us/campaigns/superstressface

**Comment by sbsmith86** [comment]
It works on my Dev, so something is off between environments.

**Comment by mikefantini** [comment]
Works for:
- https://www.dosomething.org/us/campaigns/grandparents-gone-wired-0
- https://www.dosomething.org/us/campaigns/50-cans

Doesn't work for:
- https://www.dosomething.org/us/campaigns/reelwomen

**Comment by mikefantini** [comment]
Actually no campaigns are working. They just appeared to be working because of optimizely tests that are running

**Comment by mikefantini** [comment]
Note for myself to set these as hot again once this is pushed to prod: https://docs.google.com/spreadsheets/d/1uOMlmIle58u5h0XkKWQhSAsJA9Ehqwtjs3wZVexqLpc/edit#gid=0&vpid=A1

**Comment by angaither** [comment]
fixed with #5910
