### ISSUE TITLE
Add mGage integration into phoenix

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5913]
We have mGage for UK, Brazil, and Mexico. We need to add this integration into drupal so that users in those countries are able to have a similar transactional text message experience as US users receive.

Ideally we could find a way to add these configurations to https://www.dosomething.org/admin/config/dosomething/opt_in for each country.

Something else to consider, I believe that currently as a Brazilian user when I register with my cell phone number the site is trying to add me to Mobile Commons. This isn't really a huge deal right now because Mobile Commons should just bounce those users. But ideally, we wouldn't be sending these users over to Mobile Commons at all.

@marahml @mshmsh5000 @DeeZone @sergii-tkachenko @angaither 

**Related**:
- https://github.com/DoSomething/mbc-registration-mobile/issues/23
- https://github.com/DoSomething/phoenix/issues/5939

**Comment by marahml** [comment]
Great, thanks @mikefantini! A couple of questions for the group: 
- Can we just take the CGG functionality and replicate it for the BR + MX auth forms?
- @DeeZone @angaither I believe as of yesterday, all prev. phone numbers from AGG were pushed to mGage?

Looping in @classicfreddie here too

**Comment by deezone** [comment]
@mikefantini The Message Broker mbc-registration-mobile app keys on `user_country` and `application_id`. The mobile number is added to the appropreate SMS service (Mobile Commons (2 accounts: US / CA) - mGage: 2 lists, MX / BR)) based on these two key values.
- Users from `user_country` 'US', 'CA', 'BR" or "MX" and the `CGG` `application_id` are processed.
- Users from `user_country` 'US' and 'CA' and the Drupal `application_id` are processed.
- All other submissions with mobile numbers are skipped.

Logic that defines the current flow: https://github.com/DoSomething/mbc-registration-mobile/blob/master/src/MBC_RegistrationMobile_ServiceDirector.php#L50-L97

The mGage settings for CGG are currenty hard coded into the mbc-registration-mobile app (mbc-registration-mobile app: https://github.com/DoSomething/mbc-registration-mobile/blob/master/src/MB_mGage.php#L78-L88). 

Addition to the Drupal app for mGage settings is different than the Mobile Commons requirements, the values should include:
- `opt_in_ID`
- `opt_in_keyword`

@marahml Yes, last years CGG (not AGG as you inquired about above) have been imported to mGage lists.

**Comment by marahml** [comment]
@angaither thoughts on who best to take this on, on the Phoenix side?

**Comment by sergiitk** [comment]
I can take this if @angaither is OK with that.

**Comment by angaither** [comment]
:+1: I believe the bulk of this is already done, will just need an addtional op in field here
https://www.dosomething.org/admin/config/dosomething/opt_in

**Comment by angaither** [comment]
@DeeZone can you explain what the `opt_in_keyword` is?

**Comment by deezone** [comment]
@angaither 

> I believe the bulk of this is already done

Details on what needs to be done: https://github.com/DoSomething/phoenix/issues/5939 The additional fields but adjustments in several other locations.

> explain what the opt_in_keyword is?

A value mGage requires in addition to the `opt_in_id` value. Unlike Mobile Commons  opt in which has a default keyword, mGage mimics the user sending an actual keyword to a shortcode.

**Comment by angaither** [comment]
is that per campaign? or do we have a default one that can get overridden per campaign?

> A value mGage requires in addition to the opt_in_id value. Unlike Mobile Commons opt in which has a default keyword, mGage mimics the user sending an actual keyword to a shortcode.

**Comment by deezone** [comment]
Both the `opt_in_id` and `opt_in_keyword` (mGage) values should have a default value by country (MX/BR). 

The default values could be overridden at the campaign level just like the current Mobile Commons setting. The campaign specific `opt_in_id` / `opt_in_keyword` settings should only be available in campaigns with MX/BR language versions. 

Campaigns with a US English version should only have the `opt_in_id` setting (Mobile Commons), not `opt_in_keyword`.

`global-en` campaigns should not have `opt_in` settings. SMS (Mobile Commons / mGage) messaging outside of US, MX, BR and CA is not supported.

I suspect this is leading to a later global version having campaigns with different `opt_in` settings by language within the campaign. One campaign, several languages, different `opt_in` settings.

**Comment by angaither** [comment]
vNext
