### ISSUE TITLE
Additional Materials Appear on Back End but Not Front End

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5915]
#### Current Behavior

Additional materials that have previously appeared and have been correctly uploaded to back end no longer appear on front end.
#### Desired Behavior

Additional materials uploaded on the back end of a campaign appear as hyperlinks in the Stuff You Need Section of campaign.
#### Steps to Replicate

Check the active and edit views of different campaigns with additional materials (https://www.dosomething.org/us/campaigns/school-insider, https://www.dosomething.org/us/campaigns/reelwomen, https://www.dosomething.org/us/campaigns/say-it-stars, https://www.dosomething.org/us/campaigns/teens-jeans). You will see the material appear in the backend (under Plan It) but not in the front end.
#### Why This Matters

Several high priority campaigns are currently missing crucial additional materials from the front end.
#### Relevant Screenshots

Back End
![image](https://cloud.githubusercontent.com/assets/12396076/11648484/151a7dcc-9d43-11e5-9d10-7bbe4f3b1fad.png)

Front End 
![image](https://cloud.githubusercontent.com/assets/12396076/11648492/22e414b8-9d43-11e5-9972-67e7e55b45b1.png)

**Comment by mikefantini** [comment]
Possibly related to #5849 @angaither mind assigning out?

**Comment by angaither** [comment]
@deadlybutter mind taking a look here, looks like it's pulling `[LANGUAGE_NONE]' in [campaign_helpers](https://github.com/DoSomething/phoenix/blob/6e17bb9fcd4af5ded35a05288c369608dc185bfb/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc#L208-L216)

**Comment by itsjoekent** [comment]
was just looking at this! sure thing
