### ISSUE TITLE
Display only days left

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5922]
on the hot module, instead of saying date it ends, just display number of days
- [x] Display days left
- [ ] add help text (TBD) to say it ends x day in EST

cc @mikefantini @lkpttn

**Comment by mikefantini** [comment]
Reopening so we wrap up the second part of this issue once we have designs.

**Comment by mikefantini** [comment]
Ok so currently on thor the number of days/hours left is dependent on the user's timezone. However, 11:59pm EST is the same number of hours away regardless of what timezone you are in and so it should be displayed the same regardless of whether you are in Sydney, Berlin, New York, or LA.

On thor.dosomething.org/us/campaigns/dont-be-sucker the High Season End Date is set for December 10th 2015. 11:59pm EST for 12/10/15 is currently 33 hours away.

When my user timezone is set for NYC EST, the hours left displays properly:
![image](https://cloud.githubusercontent.com/assets/6330971/11695884/7be6912a-9e7f-11e5-90c3-3b60d4fa9818.png)

When my user timezone is set for UTC, the hours left displays incorrectly (24 hours too few):
![image](https://cloud.githubusercontent.com/assets/6330971/11695903/a6fa39a2-9e7f-11e5-8f2c-3a2bb2bbad2c.png)

Again, regardless of where I am located 12/10/15 11:59pm EST is 33 hours away, and so this is what should be displayed for users regardless of what their timezone is set as.

**Comment by itsjoekent** [comment]
is UTC the only one that is broken?

**Comment by mikefantini** [comment]
@deadlybutter I spot checked a few:
- NY 33 hours left
- LA 33 hours left
- UTC 9 hours left
- Melbourne Australia 9 hours left
- Paris, France 9 hours left
- Sao Paulo, Brazil 33 hours left

**Comment by itsjoekent** [comment]
interesting, thanks!

**Comment by lkpttn** [comment]
![hot module l](https://cloud.githubusercontent.com/assets/1865372/11720463/5da1976a-9f2d-11e5-815e-0a5eb7465c04.png)
![hot module s](https://cloud.githubusercontent.com/assets/1865372/11720462/5d9ba1b6-9f2d-11e5-98fe-c2dc3d806703.png)

New designs. What you can't really see is the forced line break before the date so it always shows up on one line.

**Comment by itsjoekent** [comment]
@mikefantini am I doing ^ or is @DFurnes ?

**Comment by mikefantini** [comment]
@deadlybutter this is @angaither's call.

**Comment by angaither** [comment]
@deadlybutter go for it!
