### ISSUE TITLE
Temporary Fix for 5915

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5927]
#### Related Issue

https://github.com/DoSomething/phoenix/issues/5915
#### Affected Pages

All campaign pages with additional materials hosted on the site, but hacked on Naughty or Nice, Say it with the Stars, Not Stuck in Traffick, Treat Yo Friends, and #ReelWomen -- both their GL EN and EN translations.
#### Hack Explanation

Downloads were not displaying despite being uploaded on the back end, so we added them to the stuff you need section like so (last line in Stuff You Need):
![image](https://cloud.githubusercontent.com/assets/12396076/11669955/4d279d14-9dcd-11e5-87ab-10eeb38b4cd9.png)
#### Please note if this needs to be undone at some point and why.

This needs to be undone when the fix for 5915 is deployed to Prod otherwise the materials will all show up twice in the Stuff You Need section.

**Comment by mikefantini** [comment]
Also documented here https://docs.google.com/a/dosomething.org/spreadsheets/d/1ryBMOw05mMYtK49Gms20QZHfAbnqze5wkykyylvyc_E/edit?usp=sharing

**Comment by namimody** [comment]
Reverted now that the fix has been deployed to prod. Closing.
