### ISSUE TITLE
UK: WSOD with vInspired user credentials

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5930]
From Victoria:

> Our developers are trying to work out an issue where people are getting a white screen after entering their vinspired log in details on DS

Possibly a user API integration issue?

**Comment by sergiitk** [comment]
@mshmsh5000 I just created an account on vinspired and was able to log in with it on DS UK:
![image](https://cloud.githubusercontent.com/assets/672669/11697513/93a14100-9ec2-11e5-9b28-1b1007550d54.png)

**Comment by angaither** [comment]
🇬🇧 ❌
