### ISSUE TITLE
Campaign Signup transactional in campaign not user language

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5935]
When a user signs up for a campaign, the language of the campaign should be used to determine the contents of the transactional email. An example scenario:
- User from Brazil signs up for campaign from Mexico that's only in English and Spanish.

The `campaign_language` should be used to define the `merge_var` content values for the signup email:

```
$content = $wrapper->language($params['campaign_language']);
```

not the current:

```
$content = $wrapper->language($params['user_language']);
```

**Comment by angaither** [comment]
refs #5804 #5803
