### ISSUE TITLE
Run URLs through Facebook Debug endpoint

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#5936]
We have a lot of issues with Facebook not crawling new or updated content fast enough. For example, if a campaign is just published, then we have to wait for the page to be shared at least once before Facebook will pull in the data. Another example is permalink pages where each page is a new url custom to the user, and when the user goes to share it, the data isn't ready for Facebook.

Good news is, I found out that [Facebook has an endpoint](https://developers.facebook.com/docs/sharing/opengraph/using-objects#update) you can hit that runs URL's through the debugger so we can pre-cache them whenever we want. 

I suggest we, 
- [ ] Create a function that accepts a URL and makes a call to that endpoint so that it can get scraped.
- [ ] When something gets published, run it through this function
- [ ] Before taking a user to their permalink page, run it through this function. 

Thoughts, @angaither ?

**Comment by angaither** [comment]
@sbsmith86 I'm down for this but maybe the permalink call should be a non-blocking js solution? I don't want to slow requests for the user before showing them the permalink page

on publishing a campaign we need to call it for problem shares/hot module, right?
we could run that as a post publish hook, or as a part of the cron that creates the shares

**Comment by sbsmith86** [comment]
@angaither Hot shares and problem shares are a little different because they aren't dependent on the meta tags on the page, instead we explicitly pass the data as a query string in the link used to create the facebook share dialog, so we should be fine there. This is specific for when you like, copy a url, and paste it into facebook to share it. 

Issue #5096 is for changing the permalink Facebook share functionality to behave more like hot/problem shares, maybe we can go that route instead so we don't have to worry about blocking the page.

**Comment by sbsmith86** [comment]
#5096 was done, so I think we can close this.
