### ISSUE TITLE
Missing function: dosomething_helpers_get_variable()

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5938]
`dosomething_helpers_get_variable()` does not exist. The `general_campaign` setting is always being used:

```
  $opt_in = dosomething_helpers_get_variable('node', $node->nid, $var_name);
  // If not:
  if (!$opt_in) {
    // Use general opt_in_path.
    $var_name = 'dosomething_signup_mobilecommons_opt_in_path_general_campaign';
    $opt_in = variable_get($var_name);
  }
```

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L593-L595

User campaign signups to campaigns with a specific `opt_in` are not used.

**Related**:
- https://github.com/DoSomething/phoenix/issues/5939

**Comment by sergiitk** [comment]
[Does it?](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.variable.inc#L293-L302)

**Comment by deezone** [comment]
I was wondering how that was possible. An include file!
