### ISSUE TITLE
Expand third party subscription to include Mobile Commons and mGage

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5939]
**Important**:
- Read discussion in https://github.com/DoSomething/phoenix/issues/5913

When a user signs up, the Mobile Commons `opt_in` value is included in the request message sent to Message Broker.  `opt_in_id` and `opt_in_keyword` need to be added to transactional request sent to Message Broker.
- [ ] Adjust `dosomething_signup_third_party_subscribe()`:
  https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L451-L466 to lookup `opt_in_id` and `opt_in_keyword` based on `user_country`. The values are based on:
- if `user_country` is `US` use US Mobile Common value for `opt_in`. `opt_in_keyword`set to NULL.
- if `user_country` is `CA` use US Mobile Common value for `opt_in`. `opt_in_keyword`set to NULL. (multisite, may not apply).
- if `user_country` is `MX` or `BR` use mGage values for the country.
- if `user_country` not `US`, `CA`, `MX` or `BR`, don't set `opt_in_id` and `opt_in_keyword`
- [ ] The `opt_in` value is added to message payload with `dosomething_signup_third_party_subscribe()` which needs to include mGage `opt_in` and `opt_in_keyword` values. Perhaps the new format should be:

```
  if ($params['mobile'] && $opt_in && !$user_is_old) {
    $params['moblie_opt_in'] = {
      'opt_in_id` => 1234,
      'opt_in_keyword` => abc,
  };
```
- [ ] Remove Mobile Commons specific message setting name: `mc_opt_in_path_id` -> `mobile_opt_in`

**Related**:
- https://github.com/DoSomething/phoenix/issues/5938
- https://github.com/DoSomething/mbc-registration-mobile/issues/23

**Comment by angaither** [comment]
@DeeZone isn't this the same as #5913
I don't think that drupal should care if we are sending and mGage opt_in or a mobile commons opt_in, it should just get the id.

**Comment by deezone** [comment]
@angaither 

#5913 was a "#discussion" which felt like it was getting long. This issue is my effort to define the tech. Once the tech solution is clear we can close #5913.

Perhaps the solution is:

```
    $params['moblie_opt_in'] = [
      'id` => 1234,
      'keyword` => 'abc'
   ];
```

> it should just get the id
> where logic surrounding `user_country` defines which of the `mobile_opt_in` combinations to use? The `keyword` would be blank in the case of Mobile Commons being the SMS service of choice.

**Comment by deezone** [comment]
@deadlybutter Updated issue description to reflect what was discussed in https://github.com/DoSomething/phoenix/issues/5913. Please let know if you have any questions.

**Comment by itsjoekent** [comment]
will do!

**Comment by itsjoekent** [comment]
unless you object @angaither I talked with Dee & he said to close this out for now
