### ISSUE TITLE
11 Facts CTAs not Appearing on Front End

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5941]
#### Current Behavior

While CTA content exists on the back end for 11 Facts pages, CTAs do not appear on the front end between facts 5 and 6 or at the bottom of the page. 
#### Desired Behavior

If CTA content exists on the back end of an 11 Facts page, it should appear on the front end of the facts page. If it helps: on Thor v2.0.48, CTAs were working correctly. On prod v2.0.46, they were not working.
#### Steps to Replicate

Look at the back end of an 11 facts page. If it has content in the "Call to Action" field, but the CTA is not showing on the front end, you replicated the bug.
#### Why This Matters

11 Facts get a lot of traffic, and the CTAs are our only conversion points on those pages.
#### Relevant Screenshots

https://www.dosomething.org/facts/11-facts-about-hurricanes
![image](https://cloud.githubusercontent.com/assets/12396076/11725951/4a00be44-9f4a-11e5-98cd-dc38df339986.png)

![image](https://cloud.githubusercontent.com/assets/12396076/11725970/62800a9c-9f4a-11e5-86bf-82ea5ca4f676.png)

**Comment by mikefantini** [comment]
Important to note that the content appears when the URL is preappended with /us/: example https://thor.dosomething.org/us/facts/11-facts-about-bullying.

@mshmsh5000  can we undo https://github.com/DoSomething/phoenix/issues/5699 so that this at least works for US users? Are there any SEO implications?

**Comment by mshmsh5000** [comment]
We should be able to, yes.

We're specifying the `/us/` URL as the canonical:

![canonical-facts](https://cloud.githubusercontent.com/assets/149811/11823942/f4485d46-a344-11e5-8056-8dfffe515732.png)

So, if we remove the redirect from #5699, we should see the `/us/` URL appear in search results. This will make sense until we provide translations of 11 Facts pages, at which point we'll need to check `canonical` and `hreflang` values very carefully.

**Comment by sheyd** [comment]
Reverted the changes in Varnish.

**Comment by angaither** [comment]
@namimody seeing CTAs here
![image](https://cloud.githubusercontent.com/assets/645205/11940246/5e663d92-a7f5-11e5-8997-03893ac7d82e.png)

**Comment by mikefantini** [comment]
@angaither it's not the "Sign up for a campaign and make the work suck less." CTA that's in question, that is appearing on both US and GL EN versions.

See the button and call out difference here:

US:

![image](https://cloud.githubusercontent.com/assets/6330971/11940641/fae4094a-a7f7-11e5-8bec-4e0585a8e43a.png)

GL EN:

![image](https://cloud.githubusercontent.com/assets/6330971/11940648/031ffec0-a7f8-11e5-9843-37a8be6ace3e.png)

That's the content that isn't being displayed properly.

**Comment by angaither** [comment]
ah, ok, removed my inane comment then

**Comment by angaither** [comment]
trying different variations of, the problem is when you view it on `/us/` the lang code is not in the vars array, but it is when viewing the global base url

```
    if (dosomething_global_get_current_prefix()) {
      $key = "[0]";
    }
    else {
      $key = "[$lang][0]";
    }

    dpm($key);
    dpm($vars['field_call_to_action']{$key}, 'cta');
```

**Comment by weerd** [comment]
@angaither @namimody So just to make sure, the CTA applies and should be display for both US and Global, correct?

**Comment by angaither** [comment]
@weerd yup!

**Comment by weerd** [comment]
Ok, so I've traced it back to the Facts module... something happened where the fields containing the CTA infoz are no longer in the `$vars['content']` array, but sit outside of it in the general `$vars` array. That is the main issue. Also need to add some logic so that it uses the language info as well.

**Comment by angaither** [comment]
I think it's not in the content array, when the language doesn't match?

**Comment by weerd** [comment]
Yep, you are correct! Is it a problem if I'm not grabbing the data from within the content array anymore?
