### ISSUE TITLE
clicking view on campaign edit without prefix, causes redirect loop

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5952]
if an editor navigates from the backend directly to a node/edit link, when clicking `view` on the node they are taken to the global english url and in a redirect loop.
this happens when you have a translation, are using torguard, and you are and editor of that county with user language set to match

when I clicked `view` from `/node/2259/edit/pt-br` I get taken to the english url with a redirect loop
![image](https://cloud.githubusercontent.com/assets/645205/11747864/8d5e4608-9ff3-11e5-848b-3a73a078e32d.png)

**Comment by itsjoekent** [comment]
cant reproduce locally, ill try again on Thor

**Comment by itsjoekent** [comment]
on thor I got this one 
![screen shot 2015-12-15 at 10 39 13 am](https://cloud.githubusercontent.com/assets/897368/11815070/1d67a844-a318-11e5-90bf-a7eb8d9f63be.png)

**Comment by angaither** [comment]
@deadlybutter right, do it on a node that has a translation in the language you're looking at

**Comment by itsjoekent** [comment]
made the global translation for it

went to https://thor.dosomething.org/node/843/edit

clicked view

got brought too https://thor.dosomething.org/campaigns/pregnancy-text-gl

**Comment by angaither** [comment]
@deadlybutter I was seeing it for BR admins/translations, not sure why/how it would be specific to them

**Comment by itsjoekent** [comment]
I was doing it as a US editor, I can try doing it as a BR admin as well

**Comment by itsjoekent** [comment]
went to http://dev.dosomething.org:8888/br/node/1485/edit/pt-br as BR admin, clicked view, worked fine

this is so weird

**Comment by itsjoekent** [comment]
I created MX translation on space jam 

![screen shot 2016-01-04 at 10 49 02 am](https://cloud.githubusercontent.com/assets/897368/12093419/d0c0b9fe-b2d0-11e5-80aa-0ee33fca7ee4.png)

and new MX editor with correct lang

![screen shot 2016-01-04 at 10 49 54 am](https://cloud.githubusercontent.com/assets/897368/12093452/075b0f46-b2d1-11e5-8ffb-94c5741e48d2.png)

I set my mod header to MX

I went to space jam with the following link as new MX admin http://dev.dosomething.org:8888/mx/node/1631

clicked the edit button, worked fine

i can try on thor + torguard once the login issue is resolved over there

**Comment by itsjoekent** [comment]
just did the exact same this time, but used Torgaurd and Treat Yo Friends.

No redirect loop, no error.

Here is the URL I went too: https://thor.dosomething.org/mx/node/5646
Here is the URL I got brought to by clicking edit: https://thor.dosomething.org/mx/node/5646/edit/es-mx
Here is the User: https://thor.dosomething.org/mx/user/2632038/edit

**Comment by angaither** [comment]
@deadlybutter the error is when you go from the edit page to view page

**Comment by itsjoekent** [comment]
yeah im a doof

**Comment by itsjoekent** [comment]
so i was right yesterday, this is the line of code causing the bug 

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.module#L610

the problem is that this is technically intentional functionality now. I can change the permission so it only applies to US admins & editors maybe?

edit: for example `Administer content` is only given to global admins, US admins and US editors

edit 2: or, i dunno how this would work 100%, but maybe ignore this logic if you're coming from the edit page

**Comment by angaither** [comment]
maybe an easier solution would be to edit those view links in the content search to have the county code pre-appeneded? 
so you always go to `/mx/node/231/edit/es-mx`
