### ISSUE TITLE
Borked Behavior for MX Admin

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5956]
#### Current Behavior

When an MX admin (using TorGuard to simulate MX experience) clicks on the "edit" link under OPERATIONS in the content view of the site, they get brought to a page that shows the campaign but with a header that indicates it is the English translation of the campaign, however content is in Spanish. If they click on the "view" tab, they are brought to the URL of another campaign: https://www.dosomething.org/campaigns/no-se-puede-borrar, which shows the Drupal error message "global translation unavailable for:"
#### Desired Behavior

When an admin clicks on any link in the content (https://www.dosomething.org/admin/content) or search content (https://www.dosomething.org/admin/content/search) view of the site, they should be brought to the translation of the campaign that is most applicable to them (if it exists), as well as be able to navigate to the "view" of the same campaign they were originally looking to edit.
#### Steps to Replicate

Log in as a MX admin from Mexico. Go to the content views and search content views, and click on the "edit" links. Check the headers of the /edit pages to see which language they are denoting. Click the view tabs from the /edit view to see where you are brought.
#### Why This Matters

It's a confusing experience for any admin, especially one who is not in the office. It also creates extra work for Micah and the product team because of the back and forth required.
#### Countries Affected (optional)

at least MX
#### Relevant Screenshots

clicking on "edit" under OPERATIONS here...
![image](https://cloud.githubusercontent.com/assets/12396076/11822580/3d02fd82-a33d-11e5-8320-cf6f71b6f7e1.png)

brings you to (note the header)...
![image](https://cloud.githubusercontent.com/assets/12396076/11822624/80aeaf68-a33d-11e5-8cc2-9a564cfe2601.png)

clicking the view tab on on the page above brings the user to -- note the URL: it is another campaign's URL --
![image](https://cloud.githubusercontent.com/assets/12396076/11822655/adcb7904-a33d-11e5-825a-91dfd5eb8a76.png)

**Comment by namimody** [comment]
@mikefantini this is not always consistent campaigns. could this behavior be because some campaigns were created with English as a source language before country-specific admin user roles existed?

**Comment by angaither** [comment]
@namimody I think this is a duplicate of #5952

**Comment by itsjoekent** [comment]
Can we verify this is no longer an issue/was a duplicate of ^? #5952 was fixed yesterday

**Comment by namimody** [comment]
This no longer seems to be an issue! Closing! cc @mnelson338

**Comment by itsjoekent** [comment]
yay :tada:
