### ISSUE TITLE
Campaign run data manual cleanup

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5959]
- [ ] fix old runs so that they are associated with real campaigns (not Fantini Testing Always)
- [ ] make sure old runs have proper start and end dates
- [ ] update titles on runs for campaigns that have been opened/closed multiple times (i.e. Teens for Jeans run 1 should really be Teens for Jeans run 3, and Teens for Jeans 2014 should really be Teens for Jeans run 1)
- [ ] Update current run on campaigns that have been closed before

**Comment by namimody** [comment]
Thanks @angaither! When does this need to happen in the order of operations?

**Comment by angaither** [comment]
@namimody also need need to set end dates on campaign runs that should be closed

**Comment by mikefantini** [comment]
We also need to figure out what to do with members who signed up for campaigns that were temporarily opened but should have been closed: https://docs.google.com/a/dosomething.org/spreadsheets/d/1-lrnWtY7C9h0m_vGwRd1e9zUGPb-oLXgv-RsIH-r0Qs/edit?usp=sharing

**Comment by angaither** [comment]
@mikefantini from the bug last week?

**Comment by mikefantini** [comment]
@angaither yeah this was from when campaigns that were supposed to be closed were actually active for a few days last week.
