### ISSUE TITLE
Campaign Form - Timing; start date in one year, end date in the next

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#596]
The campaign form won't allow you to have a start date in one year and an end date in the next.

i.e. start date = nov 1, end date = feb 1

**Comment by aaronschachter** [comment]
This is a setting we can change on the field, to allow you to select the next year.  It does require you having to go in and change it year after year though.  @mikefantini and I to pow wow about dates / campaign runs later today to talk through workflow a bit more.
