### ISSUE TITLE
Create varnish redirect for Old School Impact

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5964]
We are closing the campaign collection for Old School Impact. However, because collections cannot be closed, we have to do a hack where we create a dummy campaign for the collection and close that.

Here are the [action steps](https://docs.google.com/document/d/1FzY0xPaxg2lL6puTgyDxFmcfJLYg7rxauvF2d1Qb0Z8/edit) for "closing" Old School Impact. Once those are completed, we'll then need to enable a varnish redirect from from /us/volunteer/old-school-impact to /us/campaigns/old-school-impact. This will need to take place on January 1st.

cc: @sheyd @blisteringherb

**Comment by namimody** [comment]
Collection: https://www.dosomething.org/us/volunteer/old-school-impact (now unpublished)
Campaign: https://www.dosomething.org/us/campaigns/old-school-impact (now published in closed state)

**Comment by blisteringherb** [comment]
I've set up that redirect in Fastly and activated it. It's working as expected.
