### ISSUE TITLE
Action Page - links to external sites

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#597]
Links to external sites on the action page should default open in a new tab without the campaign lead entering target="_blank" in the markdown.

**Comment by barryclark** [comment]
I've been a little less sure about this recently after reading [this Chris Coyier article](http://css-tricks.com/use-target_blank/). 

Thoughts @DFurnes @mmwtsn @mikefantini?

**Comment by mikefantini** [comment]
@barryclark @DFurnes @mmwtsn I get that argument and am open to going that route for launch (especially because it's the easier route to go), but I would then like to put that through user testing and see if it trips users up or not.

My fear is that users will click on links simply because they are available and then just get off track and have difficulty navigating back. But a. maybe that won't be an issue and b. will encourage us to use external links extremely sparingly.

**Comment by barryclark** [comment]
@mikefantini Good point on the user testing, let's go without target="_blank" for now and definitely test it.

**Comment by mikefantini** [comment]
opening this back up as it's come up a ton and seems to fit in better with the user experience of using the action page as the main reference and not wanting to lose your place when going to another site (see article for that being one of the reasons to open up in a new tab).

**Comment by mikefantini** [comment]
also to be clear, the goal is for any external links to open up in a new tab

**Comment by weerd** [comment]
Chatted with @Barry and @DFurnes and we decided best to backlog this issue for now given the other priorities etc.

**Comment by barryclark** [comment]
Yea, backlogged. Let's chat about this @mikefantini.

**Comment by barryclark** [comment]
@mikefantini I'm pretty sure that campaigns team have the ability to do this themselves now? If so please close.

**Comment by mikefantini** [comment]
@barryclark yeah I mean we always had the ability to target="_blank". But I really want to avoid us treating this super inconsistently across the site.

Instead it would be ideal to either always open in a new tab or always open it on the same tab.

We can close for now though.

**Comment by barryclark** [comment]
@mikefantini thanks
