### ISSUE TITLE
Seckit blacklisting good URIs

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5977]
Seckit settings ( https://www.dosomething.org/admin/config/system/seckit ) currently blocking
- https://cdn.optimizely.com
- https://js-agent.newrelic.com
- https://bam.nr-data.net
- https://dsrealtimefeed.herokuapp.com

Super blowing up our logs.

(a) Can we please fix this?
(b) Do we want to enable the dsrealtimefeed connection from prod?

/cc @deadlybutter @sergii-tkachenko @angaither

**Comment by sergiitk** [comment]
Yes, I will whitelist these as part of #5783.

**Comment by itsjoekent** [comment]
thats odd. i can promise you the connection is already going through and has been for some time (so im not sure what you mean by "blocking"). 

it doesn't pass any sensitive user data or receive anything back from the dsrealtimefeed, so i dont think theres any security risk in allowing it? its essentially a "ping" with the users country code.

**Comment by mshmsh5000** [comment]
This is what I mean:

![blocked](https://cloud.githubusercontent.com/assets/149811/12117220/5770593e-b38d-11e5-8ced-99cd40f340b1.png)

Some connection to that app is being blocked.

**Comment by itsjoekent** [comment]
Right but on my end its working just fine? (see the dots on the globe below) Could it just be a warning that doesn't actually block?

http://lobby.dosomething.org/module/static#globe

**Comment by DFurnes** [comment]
@deadlybutter Yep, it's [currently in "report only" mode](https://github.com/DoSomething/phoenix/issues/5783).

**Comment by itsjoekent** [comment]
gotcha
