### ISSUE TITLE
script to autofill campaign current run field

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5981]
this should maybe be a db update

query for all campaigns that are closed 
get the current run nid
put that value in the `field_current_run` on the campaign node 

fill in the `field_current_run` for all active campaigns based on the run nodes that were created

cc @namimody we can do this work, but I know it won't be correct for the ones that you have edited yourself. that's #5959

**Comment by angaither** [comment]
can't be done without #5961

**Comment by sbsmith86** [comment]
Just putting this note here, cause I think I can handle this in this issue. But I just realized that unpublished campaign runs are being shown as options in the select dropdown for this field. I should probably update that so only published campaign runs can be selected.

**Comment by angaither** [comment]
@sbsmith86 hm, I'm not sure published/unpublished matters that much for the run

**Comment by sbsmith86** [comment]
@angaither oh ok! thought cause we were using it to figure out active/closed state, it should be published

**Comment by angaither** [comment]
@sbsmith86 from my understanding, the campaign is active when it has a run node that does not have an end date, and the end date is greater than today

**Comment by sbsmith86** [comment]
@angaither we should also populate this field for active campaigns, now right?

**Comment by angaither** [comment]
we should be good to go once work for #6037 is merged in. but you could probably get started writing this :+1:

**Comment by sbsmith86** [comment]
@angaither yep, im on it. just clarifying the issue description, where you say to query only for closed campaigns. @chloealee 's script created campaign runs for all active campaigns, so should we fill this field out for closed, active, or both?

**Comment by angaither** [comment]
@sbsmith86 great question. 
@chloealee's script just created run nodes, it didn't actually fill out the `current_run` on campaign nodes

so I think this should probably do both things.

**Comment by sbsmith86** [comment]
Closed via #6047
