### ISSUE TITLE
Create open and close date field to campaign run nodes

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5988]
create a date field on run nodes (with a collect end date checked)

this should not be required
the default open date should be 'today'
the close date default should be empty

**Comment by itsjoekent** [comment]
99.9% sure but want to confirm this should be translatable

**Comment by mikefantini** [comment]
Sorry late to the party @deadlybutter @angaither but yes this needs to be translatable.

**Comment by angaither** [comment]
@deadlybutter to keep things consistent with high and low season, can you make the default be to 'collect the end date'
so that both start and end date fields are open by default

**Comment by itsjoekent** [comment]
![screen shot 2016-01-08 at 9 46 25 am](https://cloud.githubusercontent.com/assets/897368/12200421/c6144506-b5ec-11e5-9004-b1dc3320bbaf.png)

is it not working as intended? the only thing not checked is 'required'

**Comment by angaither** [comment]
currently you have to check show end date to see the second date field 
![image](https://cloud.githubusercontent.com/assets/645205/12200507/29a7f266-b5ed-11e5-9f07-fb9bb09170d9.png)
![image](https://cloud.githubusercontent.com/assets/645205/12200511/2fbbbe12-b5ed-11e5-9e3a-eb25e0fadce0.png)

in high/low season both options are available  
![image](https://cloud.githubusercontent.com/assets/645205/12200531/4be22f90-b5ed-11e5-94e7-d977cd4aeecb.png)

**Comment by itsjoekent** [comment]
I thought in our meeting thats what we decided to do (since not all campaigns need an end date)

**Comment by angaither** [comment]
correct, it shouldn't be required, but the option should be displayed

**Comment by itsjoekent** [comment]
when I make collect and end date required 2 things happen

![screen shot 2016-01-08 at 10 01 12 am](https://cloud.githubusercontent.com/assets/897368/12200803/d3823d90-b5ee-11e5-8db1-adb4e07c1bae.png)

1) I cant save it without any value. selecting the blank options in the list cause it to turn red as seen above.

2) the "no default" value will default to "now", even though I told it not too.

![screen shot 2016-01-08 at 10 03 28 am](https://cloud.githubusercontent.com/assets/897368/12200857/1895d3b0-b5ef-11e5-8b03-059926d3648e.png)

**Comment by angaither** [comment]
hmm, so it only displays the option if it's required?

**Comment by itsjoekent** [comment]
yea, thats how the high season field is configured

**Comment by angaither** [comment]
bummer, ok. re-closing
