### ISSUE TITLE
update campaign status field

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5989]
- disable the field in the ui
- auto calculate the field on campaign run node save
- create a cron job to auto calculate the field 
- make the field translatable

`field_campaign_status` would be `open` when the run has a start date and no end date
`field_campaign_status` would be `closed` when the run end date is before `now`

**Comment by sbsmith86** [comment]
@angaither an issue I am running into is that `field_campaign_status` is not translatable, but `field_run_date` is. How do we determine which `field_run_date` values to use to populate the `field_campaign_status` field?

Or is campaign status supposed to be translatable as well? I forget...

**Comment by angaither** [comment]
@sbsmith86 I believe `field_campaign_status` is supposed to be translatable, right @mikefantini?

**Comment by mikefantini** [comment]
Correct @sbsmith86 @angaither
