### ISSUE TITLE
add run id to api responses 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5991]
The `field_current_run` id needs to be exposed in the api in the following responses 
- [ ] ~~get signups~~
- [x] get reportbacks
- [x] get campaigns

**Comment by weerd** [comment]
@angaither Would the `current_run` for a reportback actually be the current run or the run it's actually associated with?

**Comment by angaither** [comment]
whaaa

**Comment by weerd** [comment]
If you're doing a GET request for `/reportbacks` what does "current_run" mean in that context? Wouldn't it just be "campaign_run" that the reportback corresponds to? I don't think it has anything to do with what the current run is... the only place that matters with a reportback is when submitting one and needing to apply the current run id to that uploaded file.

**Comment by angaither** [comment]
you are correct good sir!

**Comment by angaither** [comment]
this can be closed now, right?

**Comment by weerd** [comment]
Not yet. I need to update the old GET signups endpoint

**Comment by weerd** [comment]
working on it...

**Comment by weerd** [comment]
@aaronschachter is the GET `/signups` endpoint used anywhere? I can't find any documentation on it in the API wiki, so not sure what parameters it's implying I can pass, but all I get is:

``` json
[
  "Missing required argument parameters"
]
```

when I hit `/api/v1/signups`

**Comment by aaronschachter** [comment]
Kill it with fire. It's code I added before we were using Northstar for the mobile app for Signup Groups, which we've since abandoned:  https://github.com/DoSomething/phoenix/pull/4243

**Comment by weerd** [comment]
@angaither I think we can close this one now. The only signup related stuff w/ `run_nid` happens in `/campaigns/:id/signup` and the `run_nid` stuff accounted for in the function called `dosomething_signup_create()` from within the endpoint callback :)
