### ISSUE TITLE
Varnish Redirect for Designated Texter

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5992]
#### Current Behavior

Title of https://www.dosomething.org/us/node/5359/edit was changed back to "Don't Booze and Cruise". The links on Fastweb are: https://www.dosomething.org/us/campaigns/designated-texter?utm_source=partner&utm_medium=scholarship_listing&utm_campaign=fastweb AND https://www.dosomething.org/campaigns/designated-texter. If people click this link, they are brought to a page with the URL as above, but it looks like dosomething.org/us/campaigns.
#### Desired Behavior

People who click https://www.dosomething.org/us/campaigns/designated-texter?utm_source=partner&utm_medium=scholarship_listing&utm_campaign=fastweb OR https://www.dosomething.org/campaigns/designated-texter get brought to https://www.dosomething.org/us/campaigns/don%E2%80%99t-booze-and-cruise. 

We need a redirect from https://www.dosomething.org/us/campaigns/designated-texter to https://www.dosomething.org/us/campaigns/don%E2%80%99t-booze-and-cruise
#### Why This Matters

People who come in through Fastweb cant currently find the campaign.

**Comment by sheyd** [comment]
DONE! In Varnish.
