### ISSUE TITLE
un-unique uid/nid combo in signup and reportback tables

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5993]
Currently the uid/nid combo in both the `dosomething_signup` and `dosomething_reportback` tables need to be unique

we need to update this combo to be `uid`/`nid`/`run_id`

**Comment by angaither** [comment]
refs #6002

**Comment by angaither** [comment]
also note, there are functions that exist when creating new signups and reportbacks vs updating current ones, those need to be updated accordingly as well

**Comment by angaither** [comment]
fixed with #6038

**Comment by weerd** [comment]
@angaither Should we have an issue for updating the functions for creating/editing/deleting signups & reportbacks. I was considering it part of this issue but since closing it could be separate new one?

**Comment by angaither** [comment]
bah, appoligies
