### ISSUE TITLE
Script to un-archive run activity 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5995]
write a db_update to move all signups and reportbacks from run nodes back to the original campaign node

make sure to save the run id to the sign up and reportback as well

**Comment by angaither** [comment]
### signups

```
select n.nid, n.language, n.title, n.created, c.field_campaigns_target_id, s.sid, s.uid, s.nid
from node n
inner join field_data_field_campaigns c on n.nid = c.entity_id
inner join dosomething_signup s on s.nid = n.nid
where n.type = 'campaign_run';

foreach signup
  // change signup node id to campaign id
  s.nid = c.field_campaigns_target_id
  // change signup run id to campaign run nid
  s.run_nid = n.nid
```

### reportbacks

```
select n.nid, n.language, n.title, n.created, c.field_campaigns_target_id, rb.rbid, rb.uid, rb.nid
from node n
inner join field_data_field_campaigns c on n.nid = c.entity_id
inner join dosomething_reportback s on rb.nid = n.nid
where n.type = 'campaign_run';

foreach reportback
  rb.nid = c.field_campaigns_target_id
  rb.run_nid = n.nid
```

**Comment by chloealee** [comment]
@angaither just to double check, would the `s.run_id` be the `s.sid` that is returned from the query?

**Comment by angaither** [comment]
@chloealee `run_nid` should be set to the campaign run nid.

**Comment by chloealee** [comment]
@angaither ah I see now! Got confused because I forgot to add it to the query. Thank you!

**Comment by chloealee** [comment]
@angaither I keep running into this error: `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '10-362' for key 'uid-nid' [error]` and I found on google to do this: https://www.drupal.org/node/2073317 (bottom of page, axel.rutz's comment). Is it okay to do this?

**Comment by angaither** [comment]
@chloealee ah, tricky. you're now waiting for an upstream pull request #6038

**Comment by chloealee** [comment]
@angaither ah makes sense, okay thanks! I'll keep an :eyes: on that and rebase when it's merged.

**Comment by chloealee** [comment]
@angaither can I close this now that #6136 has been merged?

**Comment by chloealee** [comment]
Closing with #6136 merge.

**Comment by itsjoekent** [comment]
just leavin this here for reference https://dosomething.slack.com/archives/deploys/p1454697879000883

**Comment by angaither** [comment]
running these shows data is still on run nodes.

```
select s.sid, s.uid, s.nid, n.title
from dosomething_signup s
inner join node n on s.nid = n.nid
where n.type = 'campaign_run';

select rb.rbid, rb.uid, rb.nid, n.title
from dosomething_reportback rb
inner join node n on rb.nid = n.nid
where n.type = 'campaign_run';
```
