### ISSUE TITLE
Reportback display: Mask usernames that are actually email addresses

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#5997]
If username matches an email regex, mask the string.

![username-email](https://cloud.githubusercontent.com/assets/149811/12161510/7866499a-b4c4-11e5-82e0-5e740a2b56af.png)

**Comment by aaronschachter** [comment]
I discovered this earlier today when testing the mobile app -- would it make sense to add the same filtering in our API?

**Comment by mshmsh5000** [comment]
My $0.02: I'd rather we pass around accurate data, and filter/mask per client.

**Comment by aaronschachter** [comment]
Now that we're exposing the User's first name publicly in the LDT apps (if their Reportback has been approved), might be worth displaying in the rows on the Review Reportbacks webform, next to the email

cc @mikefantini @angaither

**Comment by itsjoekent** [comment]
@mshmsh5000 so you're suggesting we make a simple JS regex check on this page?

I feel like it makes more sense to do this in Drupal without touching the API. Relying on fender JS to remove sensitive info isn't gonna stop a CURL request or a browser with JS disabled

**Comment by mshmsh5000** [comment]
@deadlybutter No, definitely suggesting the template or user preprocessing layer in Drupal.

**Comment by itsjoekent** [comment]
gotcha, just making sure!
