### ISSUE TITLE
Not redirecting admin users to proper translation

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#6005]
moved into new issue from: https://github.com/DoSomething/phoenix/issues/5985#issuecomment-169793434

@mikefantini I think this keeps causing confusion / needs some kind of change. I like the idea of not redirecting for when your testing/QA'ing/Global admining, but for everyday admins this tends to be more of a pain than anything (as dee is currently experiencing for example) 

Can we make this global admin specific? For admins trying to QA & want redirecting off, they can just add the global admin role.

**Comment by mikefantini** [comment]
@deadlybutter here's why I'm hesitant to go this route. Everyone who is experiencing this pain (for the most part) will need to be able to view the GL EN translation of a campaign at some point. Whether it's Ben or a campaign lead (to verify for editing purposes) or @mnelson338 / @namimody for testing/regular admin work.

I'm open to other solutions but 1. I don't want to over-engineer this and 2. this reinforces what we should always keep in mind: admin experience should never be used as a proxy for end-user experience, this just happens to be a very noticeable example of the difference between the two.

**Comment by itsjoekent** [comment]
> admin experience should never be used as a proxy for end-user experience, 

if thats the policy then that settles it!
