### ISSUE TITLE
Varnish Redirect for Help Center

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6006]
#### User Story

As a user in the US, I'd like to see the Help Center. As a user outside of the US and not in BR or MX, I'd like to see the most relevant static content FAQ page. As a US user who hits https://www.dosomething.org/us/about/faq, I'd like to instead be brought to: https://help.dosomething.org/hc/en-us
#### Additional Information

Currently, people who Google "do something faq" are brought here: https://www.dosomething.org/us/about/faq and currently we have new member transactional email, which links to https://www.dosomething.org/about/faq -- then redirecting US user to the /us/ FAQ page, but that's not the most up to date or best way to get the info they are looking for.
#### Why This Matters

The more people who use the help center, the less questions staff gets. Additionally, help center interaction data greatly informs Hannah and the campaigns team, so the more people use it, the better.

(Should I just assign put this in the dev-ops channel, @mikefantini?

**Comment by mikefantini** [comment]
Yeah @namimody this should be a request for DevOps

**Comment by sheyd** [comment]
In place.
