### ISSUE TITLE
Associate signups/reportbacks to runs

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6008]
currently when a user signsup or reportsback the campaign nid is stored, the current run nid needs to be stored to this row as well.

**Comment by itsjoekent** [comment]
update
- query is done
- problem: update hook behind weirdly. running drush updb only works once, and even if i edit the system table i still have to reimport the entire DB. Going to use a snapshot plugin for Vagrant that sergii suggested.

**Comment by angaither** [comment]
@deadlybutter the update hook only runs once intentionally, to test locally you either have to update the hook number by one, or update the latest hook run in for that module in that table

**Comment by itsjoekent** [comment]
right thats what im doing, and it works once but then it never works again. i talked with sergii about it and he wasnt sure what was goin on either
