### ISSUE TITLE
Sponsor Logo Not Appearing Correctly Based on Backend Inputs

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6009]
#### Current Behavior

When a sponsor with a logo is added or removed from the sponsors and partners field on the /edit backend, the logo does not get added or disappear from the header photo.

Example campaign w/ problem: https://thor.dosomething.org/us/campaigns/teens-jeans
#### Desired Behavior

The logo should correspond to the status of the sponsors/partners field in the backend.
#### Steps to Replicate

Add a sponsor (with a logo) to a campaign on the /edit view of a campaign. Save. You'll see the "why we <3 [sponsor name]" in the KNOW IT section and at the bottom of the action page, but will not see the logo in the header photo.

Go to a campaign with a sponsor. Using the "Remove" button, remove the sponsor and save. You'l see the sponsor mention disappear from the KNOW IT section and bottom of the page, but not from the header photo. (See Teens for Jeans screenshots below)
#### Why This Matters

Leads need to be able to add sponsors and have their logos appear! :)
#### Relevant Screenshots

Backend looks like this:
![image](https://cloud.githubusercontent.com/assets/12396076/12202797/98c5a4de-b5f9-11e5-8047-ba7bbf544fcd.png)

Front end looks like this:
![image](https://cloud.githubusercontent.com/assets/12396076/12202756/66e1b25a-b5f9-11e5-972a-68cbf18c3596.png)
![image](https://cloud.githubusercontent.com/assets/12396076/12202764/6deb1762-b5f9-11e5-9276-a57646d57348.png)

Possibly related to issue https://github.com/DoSomething/phoenix/issues/5968 and PR https://github.com/DoSomething/phoenix/pull/5972

@mikefantini @angaither would be great to get a fix in this sprint.

**Comment by mikefantini** [comment]
@sbsmith86 FYI I think @katiecrane is going to be taking a look at this. We think it might be related to caching issues from #5945
