### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by desmondmorris** [DoSomethingArchive/legacy-website#601]
Swap out mysql for MariaDB in VM

**Comment by barryclark** [comment]
@desmondmorris is this still a valid issue?

**Comment by barryclark** [comment]
@sergii-tkachenko can you close this now? :clap:

**Comment by sergiitk** [comment]
Wow, haven't seen it. Sure. it's done: #4374.

**Comment by barryclark** [comment]
Aww yiss. An issue close for free! :+1:
