### ISSUE TITLE
Add run nid to current signups and reportbacks

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6014]
after (or at the same time as) #5981 
all signups and reportbacks should have run id added to the col
currently they all default to 0
![image](https://cloud.githubusercontent.com/assets/645205/12240301/a1529112-b85a-11e5-9077-3fdcd3cd1c90.png)

refs #5995 #5993

**Comment by itsjoekent** [comment]
how do we make sure that #5981 happens first?

**Comment by angaither** [comment]
nodes to check 
https://dosomething.slack.com/archives/G0KH8RRST/p1453912394000009

checking for duplcates
https://dosomething.slack.com/archives/G0KH8RRST/p1453913240000010
