### ISSUE TITLE
Static Header image spacing

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#6021]
What happened to this spacing? Needs substantially more whitespace.
![screen shot 2016-01-12 at 3 16 35 pm](https://cloud.githubusercontent.com/assets/6331017/12275698/7fb33878-b93f-11e5-8801-2444e5c5e063.png)

**Comment by weerd** [comment]
@angaither according to @lkpttn 

> ...that layout with the header isn’t currently implemented. We generally do the 24px spacer and that looks consistent in the header.

So I'm going to close this one.
