### ISSUE TITLE
Static content text leading needs improvement

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#6022]
H1 & text & captions have the same Leading, it's difficult to understand what text goes with which elements. @lkpttn should take a run through. 
![screen shot 2016-01-12 at 3 19 03 pm](https://cloud.githubusercontent.com/assets/6331017/12275759/e1919382-b93f-11e5-8422-076ec367247d.png)

**Comment by angaither** [comment]
THIS HAS BEEN COMPLETED 
![image](https://cloud.githubusercontent.com/assets/645205/15408086/674ad410-1ddc-11e6-89e0-ca58e9a8a5b8.png)
