### ISSUE TITLE
Where did all the whitespace go?

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#6023]
@lkpttn can you have a look? @mikefantini any idea how we got here?

![screen shot 2016-01-12 at 3 19 40 pm](https://cloud.githubusercontent.com/assets/6331017/12275776/f9a8fa3c-b93f-11e5-9377-5d2e9b608557.png)

**Comment by mikefantini** [comment]
@joolaay I'm not sure, @lkpttn and/or @DFurnes should though.

**Comment by DFurnes** [comment]
As far as I know, spacing is all the standard multiples of `24px` from all the Neue 6 updates. It might be worth sitting down to figure out specific problem areas?
