### ISSUE TITLE
Call to action button triggers Auth Flow

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#6024]
@mikefantini we discussed this as a way to test one-click onboarding on the about page. 

Call to action: Become a Member today
Button: Join
Behavior: Auth Flow modal appears

**Comment by angaither** [comment]
![](http://cuddlebuggery.com/wp-content/uploads/2014/10/rashida-jones-the-office-shrug-gif.gif)

**Comment by joolaay** [comment]
Oh hey are you doing cleanup??

HI! It looks like you're not sure what this ticket meant. It's a shitty
placeholder for...adding an account creation flow outside of the realm of
campaign signups. The old...one click to create an account, or that a call
to action button that might trigger an auth flow.  cc@lkpatton

I LOVE AND MISS YOU DOOODES.
