### ISSUE TITLE
Remove all old code for the /campaigns/gallery.json endpoint

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6033]
With the updates in #5983, the old `/campaigns/gallery.json` relationship endpoint in Services is no longer needed, so we should remove all that old code.
- [x] Turn off the endpoint in services
- [x] Remove the code for the resource.

**Comment by angaither** [comment]
bold.

> Services is no longer needed

**Comment by weerd** [comment]
Go big or go home :dancer:
