### ISSUE TITLE
Campaign status and actual view of campaign not matching up

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6057]
#### Current Behavior

If a campaign has a run associated with it that has an end date that has already passed, then the campaign status will be set to closed and the view of the campaign will be in the closed state. If I change the end date on the run so that it is a date in the future, the campaign status will be set to active. However, the view of the campaign remains in the closed state.
#### Desired Behavior

If campaign status = active, then the campaign view should be in the active state.
#### Steps to Replicate
1. Go to a campaign that is closed
2. Edit the end date of the current run to a date in the future
3. Verify that the status of the campaign is now set to active
4. Verify that despite step 3, the view of the campaign is still in the closed state.
#### Why This Matters

This prevents campaigns from changing state from active to closed which has a big impact especially on sponsored campaigns.
#### Relevant Screenshots + Links

Comeback Clothes on thor: https://thor.dosomething.org/us/node/362/edit

Campaign status = active
![image](https://cloud.githubusercontent.com/assets/6330971/12428424/76c5674a-beb2-11e5-908d-87c89ad04f61.png)

View = closed state still
![image](https://cloud.githubusercontent.com/assets/6330971/12428441/836785e6-beb2-11e5-8f13-20cbfe5df727.png)

Comeback Clothes run 2 on thor: https://thor.dosomething.org/us/node/5439/edit

![image](https://cloud.githubusercontent.com/assets/6330971/12428443/8d94a454-beb2-11e5-9df2-f69ea0675e03.png)

**Comment by mikefantini** [comment]
@sbsmith86 so actually this does appear to be a bigger issue.

When a campaign goes from status = active to status = closed the view doesn't change either.

See how on https://thor.dosomething.org/us/campaigns/fantini-run-test the status is set to closed, but the view is still in the active state.

**Comment by mikefantini** [comment]
Just a note: let's not deploy this to prod until #5959 is completed.

**Comment by sbsmith86** [comment]
@mikefantini opened a PR for this #6061

**Comment by namimody** [comment]
record of which campaigns were unpublished: https://dosomething.slack.com/archives/phoenix/p1453492102005064 + science sleuth, 50 cans, treat yo friends + no bull
