### ISSUE TITLE
Campaign Run end date should set campaign status to closed at midnight EST the following day

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6058]
#### Current Behavior

If the end date on a campaign run is set for 1/31/16, then the campaign status of the associated campaign gets set to closed on 1/31/16. 
#### Desired Behavior

If a campaign run end date is set for 1/31/16, then on 2/1/16 at 00:00:00 EST the campaign status should be set to closed. So whether you are in New York, LA, Beijing, or anywhere else, regardless of the timezone on your user profile, the campaign should be closed at 2/1/16 at 00:00:00 EST.
#### Steps to Replicate
1. Create a campaign
2. Create a campaign run associated with that campaign and have the end date be the current date
3. Set the new run as the current run on the campaign
4. Verify that campaign status = closed
#### Why This Matters

We advertise to our users and sponsors that campaigns that close will do so at 11:59pm EST on the last day of the month. There would be lots of user confusion if the campaign closed earlier than advertised.
#### Relevant Screenshots + Links

Campaign run with end date set for today: https://thor.dosomething.org/us/node/6464/edit

Associated campaign where status = closed:
https://thor.dosomething.org/us/node/6463/edit

**Comment by sbsmith86** [comment]
@angaither does cron run at midnight? I can certainly make sure the end date is set to midnight EST of the date specified but the status will only actually get updated when the cron job runs again.

**Comment by angaither** [comment]
@sbsmith86 it runs every hour at :05 so, yes at 12:05am it'll run

**Comment by sbsmith86** [comment]
cool cool. thanks.
