### ISSUE TITLE
Sql support for manual cleanup

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6059]
refs #5671 
- find all campaigns that have a run (not created with @chloealee's script) 
- get the first and last signup from each campaign to find the start/end date of that campaign
- export a CSV of data

| run_id | run_title | campaign_id | campaign_title | run_edit_link | start_date | end_date |
| --- | --- | --- | --- | --- | --- | --- |
| 12 | comeback clothes q1 | 362 | comeback clothes | dosomething.org/node/12/edit | 1-4-2014 | 1- 31-2014 |

**Comment by itsjoekent** [comment]
dumping progress in the event i accidentally loose it

```
select n.nid as 'Run NID', n.title as 'Run Title', field_data_field_campaigns.field_campaigns_target_id as 'Campaign ID', concat('dosomething.org/node/', n.nid, '/edit') as 'Edit Link'
from node n
inner join field_data_field_campaigns
on field_data_field_campaigns.entity_id = n.nid
where n.type = 'campaign_run'
and n.nid < 6166;
```

**Comment by itsjoekent** [comment]
```
select n.nid as 'Run NID', n.title as 'Run Title', field_data_field_campaigns.field_campaigns_target_id as 'Campaign ID', concat('dosomething.org/node/', n.nid, '/edit') as 'Edit Link', min(from_unixtime(s.timestamp)) as 'Min', max(from_unixtime(s.timestamp)) as 'Max'
from node n
inner join field_data_field_campaigns
on field_data_field_campaigns.entity_id = n.nid
inner join dosomething_signup s
on s.nid = field_data_field_campaigns.field_campaigns_target_id
where n.type = 'campaign_run'
and n.nid < 6166;
```

**Comment by itsjoekent** [comment]
two problems with above query...

1) Only returns 1 item in the output (I assume thats because it only ran for the signups i introduced in the join...?)

2) Returns 1970 for min and 2016 (today, this second) for max. something in the timestamp isnt being passed correctly.

**Comment by itsjoekent** [comment]
https://docs.google.com/a/dosomething.org/spreadsheets/d/1Ir16wQCvIxtWmS5Y8ZvdedHXMj20T-qpuvbguvPYNrw/edit?usp=sharing
