### ISSUE TITLE
Add campaign FAQs to Contact Us modal on action page

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6062]
#### User Story

As a user, when I go to submit a question through the Contact Us modal, I want to see the FAQs before submitting my question to see if it can be answered without waiting for a response from a campaign lead.
#### Additional Information (optional)

In my mind the approach is to:
1. Edit the copy here https://www.dosomething.org/admin/config/dosomething/dosomething_zendesk so that we acknowledge the FAQs
2. Add the FAQs between ^ intro text and the submission form.

However this might look wonky so I'm open to other ideas and would be happy to talk through options.

Also this shouldn't matter, but FAQs are updated throughout the campaign so these would need to update accordingly as well.
#### Why This Matters

It would allow the user to get her question answered more quickly than having to wait for a campaign lead to respond.

Also, currently about 10% of campaign leads' time is spent answering Zendesk questions. About 80% of these questions are covered in the FAQs.

**Comment by angaither** [comment]
@mikefantini faqs are often pretty long, do you see them getting pulled into the question modal? or just a link to them?

**Comment by mikefantini** [comment]
Yeah I worried about that. Simply linking to the FAQs could be a quick fix, although I worry it might not drop the number of questions that dramatically. We could try to be pretty persuasive with copy though - something like "Get your question answered right away by first checking our FAQs which are updated regularly." And at the very least it'd be an incremental improvement over what we have right now and we could monitor how much of a reduction in tickets we get.

Another option would be to have an interaction like we have for sources where the questions are exposed, the answers are hidden, and you can expand/collapse them. Not sure if we love or hate that idea though, especially @DFurnes @lkpttn, but it could be an option. This option might also be out of scope for this.

So I guess I'm saying I'd be down with linking to them as a first iteration and let's monitor how much of a reduction in zendesk tickets we get. And then I'd also love to know people's thoughts on the interaction idea and if that's an enhancement we'd like to explore in the future.

**Comment by angaither** [comment]
all bold **READ THE FAQs**
Just in lookin at the TFJ one, it's like three scrolls down to see them all 
![image](https://cloud.githubusercontent.com/assets/645205/12590812/bd68cc3e-c432-11e5-8288-cca4a2219583.png)

**Comment by mikefantini** [comment]
@angaither yeah which is why the expand/collapse might not be the worst idea anyways.

But again, in the sake of small incremental improvements I'm down with linking for now.

Maybe add it below the current text in that modal as a new paragraph:

"Or get your question answered right away by first [checking our FAQs](www.dosomething.org) which are updated regularly."
