### ISSUE TITLE
Total reportback quantity is being reported differently on the site than what the DB is showing

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6065]
#### Current Behavior

Total reportback quantity is off for some campaigns - the amount being displayed on /rb/reviewed and on the hot module do not match what you'd expect given the results from a SQL query. It seems to have jumped after today's deploy. 

It seems to only be affecting older campaigns? I can't figure out why some campaigns are effected and why some aren't. For example https://www.dosomething.org/us/node/10/rb/reviewed and https://www.dosomething.org/us/node/9/rb/reviewed are off, but https://www.dosomething.org/us/node/5775/rb/reviewed and https://www.dosomething.org/us/node/1144/rb/reviewed aren't. I thought it might be related to #6064, but it seems as if this issue is occurring on thor as well (see https://thor.dosomething.org/us/node/9/rb/reviewed) and #6064 only appears to have occurred in production.

I also don't understand why it's off but the amount that it's off. I checked activity that was on other runs associated with the campaign (there are now none for nid 10) but that didn't explain the difference. I checked if it was pulling in all flagged or pending reportbacks, but that didn't explain the difference either.
#### Desired Behavior

That the total reportback quantity return to its previous logic, specifically summing the quantity for all rbid's where flagged = 0.
#### Steps to Replicate
1. Go to https://www.dosomething.org/us/node/10/rb/reviewed and see the total reportback quantity
2. Query the impact for this campaign in SQL
3. Note the discrepancy.
#### Why This Matters

https://www.dosomething.org/us/node/10 is sponsored by CVS and they have been actively monitoring the hot module for this campaign. As an interim fix I removed the graph in optimizely and and edited the number being output and Adam's quote to reflect the current impact.

Beyond that, the campaigns team relies on these impact numbers to report up to sponsors, and so these need to be accurate for accounting purposes.

**Comment by mikefantini** [comment]
Possibly related to #6004?

Also query for steps to replicate that I was using is:

`select rb.rbid, rbf.fid, rbf.status, rb.quantity, rb.flagged, from_unixtime(rb.created)
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
where rb.nid = 10`

**Comment by angaither** [comment]
@mikefantini this is not related to the duplicate run nodes. 

because the campaign has multiple languages (in the case of nid 10, it's `language_none` and `en`
the total is getting doubled. 

here is what is running to aggregate the totals

```
SELECT n.nid, SUM(rb.quantity) as total
FROM node n
INNER JOIN field_data_field_campaign_status s on n.nid = s.entity_id
INNER JOIN dosomething_reportback rb on n.nid = rb.nid
WHERE n.type = 'campaign'
AND s.field_campaign_status_value = 'active'
AND rb.flagged = 0
GROUP BY n.nid;
```

which returns 3978 for node 10
if you remove the join on active campaigns it returns the correct amount 1989

**Comment by angaither** [comment]
this happened when we translated the campaign status field

**Comment by angaither** [comment]
from @sergii-tkachenko 

> we need to run [this](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.drush.inc#L168) to fix it

we could also remove the active campaign join and run totals for all campaigns until this is fixed.

**Comment by mikefantini** [comment]
@angaither if we're able to run the fix and get that out today then that seems like the best course of action so we don't have to do additional unnecessary work. 

But if you don't think the real fix can get deployed to prod today then I'm down to remove the join and run totals if you think that makes the most sense.

**Comment by angaither** [comment]
@mikefantini 
Sergii is running the fix on thor, and then will run it on production.
this will work fine for campaigns that are in one language only (like node 10)
but the query will need to be updated to deal with content that is translated

refs #6004

**Comment by sergiitk** [comment]
Thor's ready, please ensure it works as we expect now.

**Comment by sergiitk** [comment]
Ref #6026: we needed to run the translations script after translating `field_campaign_status` field:

`drush ds-global-field-fix field_campaign_status`

As explained here:
https://github.com/DoSomething/phoenix/wiki/Making-content-translatable#enable-field-translation

**Comment by sergiitk** [comment]
Also we need to run:

1.

```
drush ds-update-field-language field_campaign_status
```

2.

``` sql
delete from field_data_field_campaign_status where language = 'und'
```

**Comment by sergiitk** [comment]
@angaither @mikefantini Need your green light and I'm ready to run this on prod.

**Comment by sergiitk** [comment]
Going for prod. Before:

```

mysql> select count(*) from field_data_field_campaign_status;
+----------+
| count(*) |
+----------+
|      773 |
+----------+
1 row in set (0.00 sec)
```

**Comment by sergiitk** [comment]
```
$ drush ds-global-field-fix field_campaign_status
Replacing field values for field_campaign_status.
Data successfully processed.
```

```
mysql> select count(*) from field_data_field_campaign_status;
+----------+
| count(*) |
+----------+
|      583 |
+----------+
1 row in set (0.00 sec)
```

**Comment by sergiitk** [comment]
```
$ drush ds-update-field-language field_campaign_status
Updating field_campaign_status from "und" to "en".
11 fields updated.
94 fields left.
```

```
mysql> select count(*) from field_data_field_campaign_status;
+----------+
| count(*) |
+----------+
|      583 |
+----------+
1 row in set (0.00 sec)
```

**Comment by sergiitk** [comment]
```
mysql> delete from field_data_field_campaign_status where language = 'und';
Query OK, 94 rows affected (0.02 sec)
```

```
mysql> select count(*) from field_data_field_campaign_status;
+----------+
| count(*) |
+----------+
|      489 |
+----------+
1 row in set (0.00 sec)
```

**Comment by sergiitk** [comment]
Done.

**Comment by mikefantini** [comment]
Closing out as this is now resolved on prod for the campaigns in question and #6004 will address the rest of the issue.

**Comment by weerd** [comment]
FYI, I have some stuff in the works that should help with this in the future and storing the counts in Redis and not the DB during my Campaign Gallery updates. Part of the issue is that we only store the count on creation and review, but not on deleting or updating RB items (or something like that)...

**Comment by angaither** [comment]
@weerd actually this issue was caused because we translated a field that we were joining on so the results were getting added multiple times (depending on how many translations of the node there are)

**Comment by weerd** [comment]
Ah, hokay!
