### ISSUE TITLE
Expose Campaign type in api

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#6069]
add field `field_campaign_type` to the get campaign endpoint

**Comment by sheyd** [comment]
Currently, API returns `mobile_commons` with `opt_in_path_id` and `friends_opt_in_path_id`, which can be used by ETL scripts to import campaigns to the Data 1.0 warehouse in an automated way. Part of the campain_loader script looks for whether campaign is SMS campaign or not. Having the SMS component exposed via API will help campaign ingestion pipeline be automated instead of manual.

**Comment by angaither** [comment]
@sheyd what fields are you looking to have exposed? it looks like `opt_in_path_id` and `friends_opt_in_path_id` are currently exposed

**Comment by weerd** [comment]
The `Campaign` class does have a type property exposed to the class but doesn't get passed along to the API. This could be something we expose.
https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign/includes/Campaign.php#L16

**Comment by sheyd** [comment]
@angaither Specfically looking for if a campaign is an SMS game or not.

**Comment by sheyd** [comment]
Updated title to better reflect what looking for.

**Comment by angaither** [comment]
@chloealee if you enjoyed #6077 you'll LOVE this one

**Comment by chloealee** [comment]
@angaither yes, keep these coming! Was just telling Dave how much I liked these :)
