### ISSUE TITLE
DS build: Param to copy staging db

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#607]
Add a param to download db (and files dir?) from staging.

**Comment by desmondmorris** [comment]
We should take advantage of the `sql-sync` command.  This will require us to setup aliases properly, but its a much cleaner and more scalable approach. 
`

**Comment by aaronschachter** [comment]
As far as files, perhaps create a separate issue to setup https://drupal.org/project/stage_file_proxy ?

**Comment by desmondmorris** [comment]
We can also rsync files using drush aliases and rsync
