### ISSUE TITLE
Closed campaign notify me breaks pages

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6070]
on closed campaigns this happens
https://thor.dosomething.org/us/node/362

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'run_nid' in 'where clause': SELECT s.sid AS sid FROM {dosomething_signup_presignup} s WHERE (uid = :db_condition_placeholder_0) AND (nid = :db_condition_placeholder_1) AND (run_nid = :db_condition_placeholder_2) ; Array ( [:db_condition_placeholder_0] => 2714639 [:db_condition_placeholder_1] => 362 [:db_condition_placeholder_2] => 5439 ) in dosomething_signup_exists() (line 314 of /var/www/www.dosomething.org/releases/20160122201438/lib/modules/dosomething/dosomething_signup/dosomething_signup.module).
```

**Comment by angaither** [comment]
we should probably discuss the proper solution to this since adding run_nid to that table doesn't make a lot of sense

@mikefantini

**Comment by itsjoekent** [comment]
Context- What are pre signups?

**Comment by angaither** [comment]
@deadlybutter it's essentially a signup button for campaigns when they are closed, so an option to get on the mailing list and be notified when the campaign opens again
![image](https://cloud.githubusercontent.com/assets/645205/12553551/2a470408-c346-11e5-8c5f-02c2a3730ecb.png)

**Comment by itsjoekent** [comment]
I think I found a simple fix, let me try this

**Comment by angaither** [comment]
@deadlybutter mind if I ask what?

**Comment by itsjoekent** [comment]
we already check in the function causing the error if its a presignup or not, https://github.com/DoSomething/phoenix/blob/80c0ebe55d80069267563a964783c4c2e735fd70/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L305

we just need to make sure that in that case, run nid isnt added as a condition if its a presignup

**Comment by itsjoekent** [comment]
so something like this...

```
  $result = db_select($signup_tbl, 's')
    ->condition('uid', $uid)
    ->condition('nid', $nid);

  if (!$presignup) {
    $result->condition('run_nid', $runId);
  }

  $result->fields('s', array('sid'))->execute();
```

I think this will work? ill try it now

**Comment by itsjoekent** [comment]
ok nevermind that doesn't compile...

**Comment by itsjoekent** [comment]
this works though, just not as DRY

```
  if ($presignup) {
    $result = db_select('dosomething_signup_presignup', 's')
      ->condition('uid', $uid)
      ->condition('nid', $nid)
      ->fields('s', array('sid'))
      ->execute();
  }
  else {
    $result = db_select('dosomething_signup', 's')
      ->condition('uid', $uid)
      ->condition('nid', $nid)
      ->condition('run_nid', $runId)
      ->fields('s', array('sid'))
      ->execute();
  }
```

**Comment by itsjoekent** [comment]
and confirmed the notify me button worked with that code
