### ISSUE TITLE
Why can't I select a run node?

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6074]
[here](https://www.dosomething.org/us/campaigns/50-cans) [and here](https://thor.dosomething.org/us/node/3478)

from https://www.dosomething.org/us/node/3271/edit
![image](https://cloud.githubusercontent.com/assets/645205/12522812/be9963a8-c120-11e5-8902-0740ae1ca206.png)

there are runs, and they are associated to the campaign, but it doesn't display them as options in the dropdown

**Comment by sbsmith86** [comment]
@angaither I think this is an issue with translations lining up. For the examples you gave on Thor: 

**Science Sleuth**
The Science Sleuth campaign only has a english translation.

There are two campaign runs for science sleuth:
**Science Sleuth 2015** - Only published translation is english global, so the english version of the campaign isn't showing it.
**Science Sleuth 2014** - Only publish translation is english but it is tied to “social media makeover", so the campaign is not showing it.

**50 Cans**
Only published translation is english

There are two campaign runs for 50 cans:
**50 cans 2015** - Only published translation is english global
**50 cans 2014** - Only publish translation is english but it is tied to “social media makeover"

So, if we were to add a english translation of the 50 cans 2015 campaign run, and tie it to the 50 cans campaign, we should see it show up in the drop down. I didn't want to do that yet, though, so we can continue to investigate this issue if we need.

**Comment by angaither** [comment]
That would make sense (cc @mikefantini)

**Comment by mikefantini** [comment]
Works for me @sbsmith86. I can go ahead and give that a shot now.

**Comment by mikefantini** [comment]
Fixed both on prod: [50 cans](https://www.dosomething.org/us/campaigns/50-cans) and [Science Sleuth](https://www.dosomething.org/us/campaigns/science-sleuth).

We can close this out then yeah @sbsmith86 @angaither? cc: @namimody
