### ISSUE TITLE
Missing fields from /api/v1/campaigns/:nid response

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#6077]
**BLOCKED**
Currently with both the `/api/v1/content/:nid` to `/api/v1/campaigns/:nid` endpoints are not providing the fields listed below. It's currently not possible to generate digest messages.

**Reason**:
`/api/v1/content/:nid` is set to be depreciated based on the documentation (https://github.com/DoSomething/phoenix/wiki/API#retrieve-a-campaign-will-be-deprecated) and currently has bugs in it's response. 

**Goal**:
Replacing the call in generation of the weekly digest email message by the Message Broker system from `/api/v1/content/:nid` to `/api/v1/campaigns/:nid`.

**Needs**:
The digest requires the following missing fields returned as a part of the `campaigns/:nid` response:
- DO IT: During Tip Header - `step_pre[0]->header`
- DO IT: During Tip Body - `step_pre[0]->copy`

![image](https://cloud.githubusercontent.com/assets/2119264/12525883/116acb2a-c136-11e5-909b-76c96676158a.png)
- `latest_news`

![image](https://cloud.githubusercontent.com/assets/2119264/12525901/37679100-c136-11e5-8bb1-3969110e05f8.png)

cc @sergii-tkachenko 

**Related**:
- Message Broker Trello card: https://trello.com/c/QVBFbjTl

**Comment by angaither** [comment]
@DeeZone the `/campaigns` endpoint doesn't have all the node data currently, and we have no plans to depreciate the `content` endpoint currently. What kinds of bugs are you seeing in that response?

**Comment by deezone** [comment]
@angaither  Last week the `/campaigns` endpoint was returning NULL values when the digest ran on Thursday afternoon. Perhaps a larger intermittent issue as I can no longer reproduce it.

"Retrieve a campaign (will be deprecated)"
https://github.com/DoSomething/phoenix/wiki/API#retrieve-a-campaign-will-be-deprecated

Based on the title and discussions with @weerd I was under the impression the endpoint is going to be deprecated? Would it not make sense for the Message Broker system to start the transition to all the great, current, maintained, loved endpoints in both the Drupal app and Northstar?

**Comment by angaither** [comment]
@DeeZone it would make sense if it had all the fields/translations that message broker uses
but currently `campaigns` endpoint doesn't expose content in other languages is not supported and it doesn't have all the fields you need. 
we can certainly keep this issue open and address it, but I don't think the most loved api has everything you need

**Comment by deezone** [comment]
Thoughts on going forward? 

There's a need to support global digest which will require an endpoint that allows requesting campaign details by translation. Rather than add features to an endpoint that's marked for depreciation would it not make sense to focus efforts on a single endpoint?
1. Add the two missing fields (detailed above)
2. add support for language parameter in request

**Comment by angaither** [comment]
> Rather than add features to an endpoint that's marked for depreciation

sorry, what features. I was under the impression that the `content` api has what you need?

support for language is a large task and we probably won't get to it this quarter.

**Comment by deezone** [comment]
@angaither Regardless of the language support:

Detailed in the issue description. If `/campaigns` had the following three fields:
- DO IT: During Tip Header - step_pre[0]->header
- DO IT: During Tip Body - step_pre[0]->copy
- latest_news
  then `/content` could be depreciated as Message Broker would no longer need it.

@weerd @deadlybutter For what it's worth, `/content` use to return values in `step_pre[0]`. It is now empty but I do see values in `pre_step_header`. Perhaps the campaign entity has been restructured recently?

**Comment by chloealee** [comment]
@weerd @deadlybutter I'm playing around in `Transformer.php` and did `print_r($data);` on line 204. Would these be the new equivalents? 

`step_pre[0]->header` is now `field_pre_step_header`
`step_pre[0]->copy` is now `field_promoting_tips`
`latest_news` is now `field_latest_news_copy`
