### ISSUE TITLE
High season end date appears in header photo on campaigns in the closed state

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6092]
#### Current Behavior

High season end date is showing on header photo when a campaign is in the closed state if "Show End Date on Pitch & Action Page" is enabled.
#### Desired Behavior

Since the campaign is closed, this end date should no longer appear.
#### Steps to Replicate
- View a campaign that is closed
- Make sure "Show End Date on Pitch & Action Page" is enabled
- Verify that end date appears in the header photo below the call to action
#### Why This Matters

It's confusing for the user to tell them a campaign is going to end when it already has.
#### Relevant Screenshots + Links

For an example, check out https://www.dosomething.org/us/campaigns/bake-sales-babies and see that Ends February 22nd appears on the header photo.

![image](https://cloud.githubusercontent.com/assets/6330971/12598717/f927e03a-c459-11e5-9638-a5299d1e5b48.png)

**Comment by angaither** [comment]
we are calling `dosomething_campaign_get_campaign_status` to get the campaign status on the node, which is essentially the same function as `dosomething_campaign_is_closed`
the latter was refactored to deal with that field no longer being language_none, while the former was not.
