### ISSUE TITLE
Expose GET signup endpoint

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6110]
We're thinking that syncing all user activity data into Northstar is probably going to create more headaches for us in the future than it's worth. It seems like the best path forward is to expose this information from the Drupal API and let Northstar act as a authentication "proxy" for accessing those endpoints from the mobile app.

(In the future, the Northstar proxy code could be removed once we add some sort of [API management layer](https://github.com/DoSomething/northstar/issues/49) to let any service use the same Northstar authentication key/token.)

For Drupal to handle these endpoints, we need to add an endpoint for getting all of a given user's signups... e.g `signups/:user_id`. This will be used for the "hub" screen on the mobile app, and would return a (paginated?) collection of all signups the user has made.

```
GET signups/312412
```

``` json
{
  "data": [
    {
      "signup_id": 1234123,
      "campaign_id": 1337,
      "source": "<source>",
      "created_at": "<date>"
    },
    {
      "signup_id": 2145555,
      "campaign_id": 1338,
      "source": "<source>",
      "created_at": "<date>"
    }
  ]
}

```

It might also make sense to have an endpoint for querying a user's current signup status for a given campaign: perhaps `campaigns/:campaign_id/signups/:user_id`? Response should contain the signup the given user has made to that campaign, if they exist.

For example:

```
GET campaigns/1337/signups/312412
```

``` json
{
  "data": {
      "signup_id": 1234123,
      "campaign_id": 1337,
      "source": "<source>",
      "created_at": "<date>"
  }
}

```

**Comment by angaither** [comment]
@weerd if you could work with @chloealee on this that would be :ok_woman:

**Comment by weerd** [comment]
¡OLÉ! @chloealee lets have an endpoint creation party :tada:

**Comment by chloealee** [comment]
@weerd yay can't wait!

**Comment by aaronschachter** [comment]
This might be overkill, but here goes: if the main data source is Phoenix, any thoughts on embedding a  campaign object, like we do for the `reportbacks` and `reportback-items` endpoints?  If we also add a `reportback` property - a user's profile could be displayed in a single API request. (`user/:id/signups`)

Refs https://github.com/DoSomething/northstar/issues/210

**Comment by weerd** [comment]
Yeah, I was gonna say I'd prefer a structure like this that follows along with what we're doing in our newer endpoints and Northstar:

``` json
{
  "data": [
    {
      "id": "1234123",
      "source": "<source>",
      "created_at": "2014-03-18T00:00:00-00:00",
      "campaign": {
        "id": "1337",
        "title": "Campaign Title If Useful For Response"
      }
    },
    {
      "id": "2145555",
      "source": "<source>",
      "created_at": "2014-03-18T00:00:00-00:00",
      "campaign": {
        "id": "1338",
        "title": "Other Campaign Title If Useful For Response"
      }
    }
  ]
}
```

Including the Campaign object would give us more info apart from the `title` for the response if using the `teaser` view like the RB endpoints use.

**Comment by weerd** [comment]
I'd also like to aim to maintain the RESTful style routing we've been establishing across our APIs with our newer endpoints, so I'd suggest the endpoint for a specific user on a specific campaign via the signups endpoint user url parameters like: 

```
/signups?users=:id&campaigns=:id
```

Plus, similar to how the RB Items endpoint can pass multiple campaign ids `/reportback-items?campaigns=1321,362` it could be something similar with signups and retrieve a collection of signups for a series of users on a few campaigns which could be useful:

```
/signups?users=123,789,456&campaigns=1321,362
```

_not actually sure if passing multiple ids is useful though..._

**Comment by angaither** [comment]
@weerd I don't think multiple users is helpful, but multiple campaigns for sure.
but if you leave that blank, does it default to sending all campaigns?

**Comment by weerd** [comment]
Makes sense. Not sure yet about what happens if left blank. Maybe it defaults to grab all campaigns for the user passed. Otherwise the general index collection of `/signups` can just be a paginated list from most recent to oldest or something.

**Comment by weerd** [comment]
We'll see where the road takes us! :car:
