### ISSUE TITLE
SMS reportbacks need to include run ID

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6111]
#### Current Behavior

We're now associating a run ID with every reportback. In order to properly calculate the impact for a campaign run we need all reportbacks to have run ID associated with it. Each campaign node has a current run ID field set. This is the run ID that new reportbacks should be assigned. 

Currently SMS reportbacks have run ID set to NULL.
#### Desired Behavior

SMS reportbacks would have run ID set to the current campaign run ID.
#### Why This Matters

Without this our current method of calculating impact would not include any impact that gets reported via SMS.

cc: @angaither @jonuy @marahml @classicfreddie

**Comment by classicfreddie** [comment]
@jonuy is this something we should update when we're configuring the reportbacks in compose? if so, how?

**Comment by jonuy** [comment]
@classicfreddie yea, it sounds like we'll need to update the SMS node app to allow us to set a run ID that gets sent along with an SMS reportback.

@mikefantini do you know if the Phoenix reportback endpoint is setup to receive this run id? The [wiki section](https://github.com/DoSomething/phoenix/wiki/API#campaign-reportback) doesn't seem to mention it.

@DFurnes not sure if this is already an issue in Northstar (agh and the mobile app @marahml), but I assume we'll need to update all the reportback calls being made in those systems as well.

**Comment by aaronschachter** [comment]
@jonuy I opened https://github.com/DoSomething/LetsDoThis-iOS/issues/757 in iOS, as we'll need to refactor Signups and Reportbacks once the Campaign's Current Run is integrated into the API

**Comment by mikefantini** [comment]
@weerd did you update the Phoenix reportback endpoint to receive the run id/do you know if there an issue for it? I wasn't able to find anything about this, but might have missed something.

**Comment by weerd** [comment]
Yep! Just need to keep in mind that it's within the `campaign` object in the `/reportbacks` or `/reportback-items` endpoint response: https://thor.dosomething.org/api/v1/reportback-items/171037

**Comment by aaronschachter** [comment]
@weerd I think the issue here is for a `POST`ing a Reportback to the Current Run. Ideally the `POST` reportback endpoint knows how to get the current run and set the new Reportback's `run_nid` accordingly.

**Comment by weerd** [comment]
Oh, gotcha. Well for POSTing it uses the old endpoint that is actually a targeted action on the `/campaigns` endpoint (not ideal, but need to update `/reportback` endpoint with POST requests which will be a while). Anyhoo, the only thing I addressed with it is that all the functions that get called by the callback in the POST action related to reportbacks handle having a `run_nid`; which just means that you don't need to pass one, and the functions go and search for the current run based on the campaign id passed. 

Again, in an ideal future, the `run_nid` should be passed. It can be updated to allow passing one I believe, but it should be defaulting to figuring it out on it's own (same as with rest of DS reportback submission via the webapp).

**Comment by aaronschachter** [comment]
I don't think we should be able to pass a `run_nid`: you should only be able to reportback for the current run. It think it's awesome that you don't have to - but from what you say it, it sounds like the SMS Reportbacks which submit to the endpoint should have their Current Run set already and this original issue is a bug?

**Comment by weerd** [comment]
yeah, potentially sounds like it. Could it be possible that the campaign being reported-back on via SMS doesn't have a current run id?

**Comment by mikefantini** [comment]
All active campaigns have a current run id. Verified with my own :eyes:.

**Comment by weerd** [comment]
Ok, so then what are all the "avenues" that an SMS reportback can happen from? Just this endpoint?

**Comment by jonuy** [comment]
Had an IRL chat with @weerd because I couldn't really understand what was going on above. Here's what I've got after that...
- SMS reportbacks are submitted through the Phoenix /campaigns/:nid/reportback API endpoint. [[src](https://github.com/DoSomething/ds-mdata-responder/blob/dev/app/lib/ds-content-api/index.js#L323)]
- From looking at the code, it doesn't seem like a run id needs to be submitted along with the request. The Phoenix code should just default to whatever the current campaign run is. [[src](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L705)]

@mikefantini Are we currently seeing issues with reportbacks from SMS not being tagged with a run ID?

**Comment by angaither** [comment]
@jonuy yeah, mobile reportbacks are coming in with `NULL` as the `run_nid`

**Comment by classicfreddie** [comment]
@jonuy Do we need to include the run_nid in compose? 

{
  _id: ObjectId("56abc38e606241001b000000"),
  campaign_completed_id: 200191,
  campaign_nid: 6621,
  campaign_optout_id: 141607,
  endpoint: "yoteach2016",
  message_caption: 200187,
  message_complete: 200191,
  message_not_a_photo: 200181,
  message_quantity: 200183,
  message_why: 200185,
  message_quantity_sent_invalid: 200189
}

**Comment by jonuy** [comment]
If @weerd and I were looking at [this code](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L705) and [this code](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L666) correctly, we shouldn't need to submit a `run_nid` with the SMS reportback. Phoenix should be able to determine what it is on its own.

**Comment by angaither** [comment]
right, and those functions are returning null, so I guess there's some reason those aren't working

**Comment by angaither** [comment]
cc @deadlybutter

**Comment by itsjoekent** [comment]
:cry:

**Comment by weerd** [comment]
@jonuy when a reportback gets submitted via SMS, is the `file` sent through or a `file_url` based on the properties passed in the [body](https://github.com/DoSomething/phoenix/wiki/API#campaign-reportback) of the POST request? 

If using the `file` property instead of the `file_url`, there may be an issue with the logic here, since it would also require a `filename` property which we haven't specified in the API docs.
https://github.com/DoSomething/phoenix/blob/62106f609af0c415e97559b19b05e9394a600338/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L338

If using `file`, do you also pass a `filename`?

I was able to successfully submit a reportback to a newly signed up campaign as an auth user (non-admin) using the `file_url` property instead of the `file`, and the proper `run_nid` was assigned to the Reportback! I'm working on testing out other scenarios too...

**Comment by jonuy** [comment]
@weerd SMS reportbacks send a `file_url` [[src](https://github.com/DoSomething/ds-mdata-responder/blob/dev/app/lib/ds-content-api/index.js#L294)]

**Comment by weerd** [comment]
cool, ok. good to know!

**Comment by weerd** [comment]
@mikefantini my tests are coming out fine, with correct submission and actual integers assigned to the `run_nid` without issue. If the reportbacks are not getting assigned a `run_nid` when submitting from SMS, not sure what is causing it then. The functions in the endpoint and those that were updated to account for `run_nid`s even if no `run_nid` is passed via the body properties of the POST request are working fine.

Is there any additional info that could help me investigate further?

**Comment by angaither** [comment]
@weerd looking meow, there is a chance we might have fixed this with the latest deploy. it looks like we haven't gotten any null run nids since yesterday

**Comment by weerd** [comment]
oh sweet! :lollipop: cool. I'll hold off further testing then, since we might just be able to close this :dancer:

**Comment by angaither** [comment]
@mikefantini sending this one over to you for now, we can keep an eye on it over the next few days and see if it continues to be an issue

**Comment by mikefantini** [comment]
Sweet! Sounds good to me. @angaither do you have a query I can pull to check on this later in the week?

**Comment by angaither** [comment]
@mikefantini haven't had any since feb 1, I think we are ok to close, since we have had signups since then and they've all not been `NULL`

![](https://media.giphy.com/media/xTiTnlOUSSDKH3jr5C/giphy.gif)

```
select sid, uid, nid, from_unixtime(timestamp)
from dosomething_signup
where run_nid is null
order by timestamp desc
```

**Comment by weerd** [comment]
:tada:
