### ISSUE TITLE
Add Automatic Running of Ghost Inspector Tests to Thor Deploy Jenkins Job

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6128]
RUN ALL TESTS:

https://api.ghostinspector.com/v1/suites/56980f16812f6dd51bc172f2/execute/?apiKey=[...]

GET SUITE DETAILS:

https://api.ghostinspector.com/v1/suites/56980f16812f6dd51bc172f2/?apiKey=[...]

LIST SUITE TESTS:

https://api.ghostinspector.com/v1/suites/56980f16812f6dd51bc172f2/tests/?apiKey=[...]

**Comment by mshmsh5000** [comment]
- Added the [Notifications plugin](https://wiki.jenkins-ci.org/display/JENKINS/Notification+Plugin) to Thor Jenkins
- Added a job, _Ghost Inspector Suite_, which makes the HTTP call to the _Phoenix Core Experiences (Thor)_ suite using the Notifications plugin
- Added a post-build step to the _Deploy-Thor_ Jenkins job to call this GI job
- Configured the Thor suite in GI to notify Slack (in #deploys) on test failure, and when passing after a failure.

**Comment by mshmsh5000** [comment]
Working on the best notification configuration for this.

Ghost Inspector integrates with Slack, but doesn't have sparse notifications of the kind that we'd be okay with seeing on a regular basis. For instance, there's no polite "this test suite has passed" message, only verbose messages with the final screenshot.

I'm going to try piping verbose GI messages into a dedicated Slack channel (#ghost-inspector). The Jenkins job should be notifying starts and stops to the general #deploys channel.

**Comment by mshmsh5000** [comment]
The remaining problem is that the Jenkins job isn't actually notifying #deploys -- not sure what's going on there.

**Comment by angaither** [comment]
@mshmsh5000 doesn't look like there's a downstream event to notify slack on that job

**Comment by mshmsh5000** [comment]
Aaaaaahaaaaaaaa :eyeglasses: :custard:
