### ISSUE TITLE
Modal login form HTTPS issue

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#613]
The form blocks generated by `user_login_block` and `user_registration_form` (used in auth modals) still seems to want to submit to `https://...:8888` so it's broken on localdev in DoSomething/paraneue#20.

**Comment by DFurnes** [comment]
Looks like the form is submitting to `https://dev.dosomething.org:8888/node?destination=node`, which doesn't seem right. /cc @desmondmorris @mshmsh5000

**Comment by desmondmorris** [comment]
@dfurnes I just gave it a run through.  Its not respecting the port.  When I change the port to 8889 in dev tools, "works as expected".  This should not be any issue once we are in a more production like environment, where the ports wont matter.

This may be mitigated if all pages are served behind SSL.  I cant remember where we landed here.  @mshmsh5000 thoughts?

**Comment by mshmsh5000** [comment]
**Form question**: Have you tried forcing https via the forms API? https://api.drupal.org/api/drupal/includes%21form.inc/7 

http://screencast.com/t/WZZ5cIIaqZq2

**Comment by mshmsh5000** [comment]
**SSL question**: Problem is (a) [we lose Varnish page caching](http://mikkel.hoegh.org/blog/2012/07/24/varnish-as-reverse-proxy-with-nginx-as-web-server-and-ssl-terminator/), and (b) SSL deployment to Akamai is expensive. If modal login is a non-starter without sending everything over SSL, then let's decide very soon so I can try to come up with an alternative.

**Comment by mshmsh5000** [comment]
Hmm...actually, the `$form['https'] = TRUE` behavior doesn't seem to allow for an alternate secure URL. It just switches protocols.

**Comment by desmondmorris** [comment]
Yeah the protocol is all good, its just the port part.  Can we point secure and insecure to the same port with apache?  Then, we will not have to switch the ports at all.  My guess is a big no :)

**Comment by mshmsh5000** [comment]
No, each is essentially a separate process that needs to claim its own port. Let me mess with something, though.

**Comment by mshmsh5000** [comment]
OK. This is worth trying, but you'll need to rebuild your Vagrant image as root to test.

http://screencast.com/t/4uAcf6RprX

Change to Vagrantfile:
`# Bare Apache httpd (http and https)
  config.vm.network :forwarded_port, guest: 8888, host: 80
  config.vm.network :forwarded_port, guest: 8889, host: 443`

Change to settings.local.php: https://gist.github.com/mshmsh5000/8853150

**Comment by DFurnes** [comment]
Right, so it seems like the issue is that since the form is posting to a `node/*` address, the Secure Pages module isn't overriding the port for us on local dev. So it should work fine on production – no need to reconsider plans in that regard.

My original question was whether it should be posting a login form to `node/` at all. It seems to work, but shouldn't that be posting to `user/login/` instead? That would solve our problem, since Secure Pages could safely redirect all the traffic on that endpoint to HTTPS on the correct port.

**Comment by DFurnes** [comment]
@angaither Any progress looking into this?

**Comment by barryclark** [comment]
Assigning @mshmsh5000 on to this. + Milestone 0.2.0

**Comment by mshmsh5000** [comment]
@DFurnes @angaither Yes, my understanding was that all auth forms would submit to a user/\* URL, which (a) normalizes the behavior and (b) allows for path-based https settings.

This should be easy -- an endpoint that includes a "?return_to=URL" or "?from=URL" param.

@angaither Let's discuss.

**Comment by mshmsh5000** [comment]
@DFurnes Andrea has a fix -- stay tuned!

**Comment by DFurnes** [comment]
:confetti_ball:
