### ISSUE TITLE
Can't "Add Another Item" on Our Team page

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6133]
#### Current Behavior

If you click "Add Another Item" on the "our Team" page, the page layout breaks and images cannot be referenced.
#### Desired Behavior

Adding another item does not cause the page to break...
#### Steps to Replicate
1. Go to: https://thor.dosomething.org/us/node/556/edit
2. Scroll to the bottom and click the "Add another item" button
3. Watch layout break.
#### Why This Matters

Sam can't add new staff photos until this is fixed. 
#### Relevant Screenshots + Links

https://thor.dosomething.org/us/node/556/edit

![image](https://cloud.githubusercontent.com/assets/12396076/12822418/f99c26ce-cb35-11e5-8b6b-a109db1ea570.png)

Click "add another item" and then this happens:
![image](https://cloud.githubusercontent.com/assets/12396076/12822530/760ebdde-cb36-11e5-9eb1-dd095629b52c.png)

**Comment by namimody** [comment]
This doesn't seem to be a problem on static content pages like "Our Partners" https://thor.dosomething.org/us/node/532/edit

**Comment by namimody** [comment]
Anddddd Luke made a video: https://trello.com/c/mhxEsXYc/1528-drupal-bug-adding-new-item-to-gallery-stops-page-functions

**Comment by angaither** [comment]
@namimody this actually does allow you to add new things, not sure what's wrong with the admin theme when you add a new gallery item, but if you save without an image and go back it works fine

before a save, you can still insert content, the theme just looks a little strange
![image](https://cloud.githubusercontent.com/assets/645205/13114913/9c001fb0-d563-11e5-81ef-a63d926267d6.png)

this is after a save, and you can add an image
![image](https://cloud.githubusercontent.com/assets/645205/13114811/1f6fd968-d563-11e5-91b3-f26360bfe18a.png)
![image](https://cloud.githubusercontent.com/assets/645205/13114822/2f941f20-d563-11e5-8dc6-23eed88dea67.png)

**Comment by namimody** [comment]
Hi @angaither -- wait so you're saying that a new item can't be added with both an image and content at once, but can be added piecemeal?

**Comment by angaither** [comment]
@namimody yeah, you could technically paste in the correct image thing, but it's easier to save and wait for the autocomplete.
I don't see any errors or js or otherwise when it happens, I'm not sure it's worth investing a lot of time into fixing.

**Comment by namimody** [comment]
Hmm @angaither trying to understand -- when you say you don't see any errors in Js or anywhere else you can't see what's going wrong in the code, so fixing will be really difficult?

(By the way, is there any thing different about this page vs. other static content pages? Curious why we're not seeing this happen more places...)

**Comment by angaither** [comment]
> when you say you don't see any errors in Js or anywhere else you can't see what's going wrong in the code, so fixing will be really difficult?

correct

> (By the way, is there any thing different about this page vs. other static content pages? Curious why we're not seeing this happen more places...)

there's just the most items on this page

**Comment by namimody** [comment]
Alright thanks @angaither. I'll close and let Sam know.
