### ISSUE TITLE
User login/registration form fields

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#614]
Currently, we're using the default Drupal login/registration fields in the new world. We're running into a couple issues where default behavior conflicts with our existing user flow: 
- We can't authenticate users if they provide either an email+password cell phone+password. This is inconsistent with our current login behavior.
- We prompt users to create a username when registering. I think the current behavior is to generate a unique username for them behind-the-scenes.

**Comment by desmondmorris** [comment]
- Allowing users to authenticate via email and cell can all be added in.  I would like to make sure this is full requirement.  If so, we need to make sure these fields exist on the user object and alter the login submission hook in the background.
- We can suppress the username field and populate on the backend.  It would be a great time to revisit the algorithm or process that we currently have for this.  If email is always necessary for registration, I vote for using the email address as the username as well.

Adding @angaither

**Comment by DFurnes** [comment]
As far as I know, email is always required for web registration. It's only mobile users that should be able to register without an email.

**Comment by desmondmorris** [comment]
Yeah we need to figure that scenario out.  Maybe we need to just generate the user for web and mobile regs.  A MD5 hash or something

**Comment by angaither** [comment]
FYI: the fields from the new world demo are currently on the user object & the registration form
https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.features.field_instance.inc
