### ISSUE TITLE
Allow Editors to Add Files to the Site

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6141]
#### User Story

Editors (campaign leads) need to add images and files to the site to reference in things like SMS games. They should be able to access the "file types" on the menu:

![image](https://cloud.githubusercontent.com/assets/12396076/12828376/6df1e3e4-cb52-11e5-8de7-86e34f702709.png)
#### Additional Information (optional)

Currently, their admin menu looks like this: 
![image](https://cloud.githubusercontent.com/assets/12396076/12828341/3d480f48-cb52-11e5-9de5-309fd1dda3b3.png)
#### Why This Matters

It will allow leads to act faster and without having to ask the product team for things. 
#### Current Workaround w/o Feature (if applicable)

They have to ask the product team to add files.

**Comment by katiecrane** [comment]
@namimody I've got it now so editors have the "file type" menu item, but as far as I can tell that just gives them access to edit/add file types, not the actual files. Is that what you wanted? If not, can you tell me where the actual file adding happens to make sure that is working?

**Comment by namimody** [comment]
Oh dear @katiecrane -- this was my mistake...they need access to: https://www.dosomething.org/file/add :see_no_evil: 

Which is housed under 
![image](https://cloud.githubusercontent.com/assets/12396076/13157077/dbf651ac-d653-11e5-8bb5-1721eb4e063f.png)

They actually probably don't need access to adding file types. I'm so sorry!!

**Comment by katiecrane** [comment]
@namimody should they just be allowed to view all the files and add new ones? Any editing or deleting?

**Comment by namimody** [comment]
View, add, edit I think @katiecrane! Unless not allowing them to delete is very complex, in which case you can allow them to delete.

cc @mikefantini in case he has any thoughts here.

**Comment by katiecrane** [comment]
@namimody It's no problem, there are checkboxes for everything. Turns out there is also a download option, thoughts on that?

**Comment by mikefantini** [comment]
Let's not let them delete for now. Reduces the risk of someone incidentally deleting something @katiecrane @namimody 

Download seems like a safe option though.

**Comment by katiecrane** [comment]
@mikefantini okay I"ll add downloads to the PR tomorrow

**Comment by katiecrane** [comment]
@mikefantini adding downloads doesn't seem to alter the code or the site so I'm not sure if those checkboxes really do anything
