### ISSUE TITLE
Remove the cache parameter from the campaigns endpoint

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6143]
The `/campaigns` endpoint currently has a `cache` boolean url parameter that can be passed. This used to be necessary with helping to clear the cache for the campaigns index endpoint, since there was no other way to properly clear the cache if a campaign was edited.

However, with #6109 & #6126 in place, the cache (if set to "temporary") can be cleared either on a general cache clear, or if set to a specified number of hours or to "permanent" then it can be cleared when a campaign is updated (for both the cache of the single campaign and all collections where the campaign might be a part of the response).

With the above options in place, I'd like to remove the `cache` url parameter which makes some of the logic in the `ApiCache` class a little wonky since some endpoints (like the show `/campaigns/:id`) don't really bother with passing additional parameters. @DFurnes also pointed out that it is probably not best to allow clearing the cache by hitting an endpoint :scream: 

@DFurnes is for it, but wanted to check with both @uy and @aaronschachter since you _might_ be using the cache parameter in places for the mobile app...

**Comment by aaronschachter** [comment]
Haven't been using `cache` param anywhere in iOS.

**Comment by weerd** [comment]
Ok, good to know :) @jonuy ?

**Comment by jonuy** [comment]
Not using this anywhere in code, but have used it multiple times to manually clear. As long as we've got another method to clear cache, then this is fine.

**Comment by weerd** [comment]
Closing for now, considering we're going to move to a new platform in the future and this isn't really a high priority issue.
