### ISSUE TITLE
FAQs line appears in Contact Us Modal even if there are no FAQs

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6149]
See https://thor.dosomething.org/us/campaigns/shower-songs as an example

Refs: #6062 and #6091

**Comment by mikefantini** [comment]
![image](https://cloud.githubusercontent.com/assets/6330971/12854263/a512ece2-cc06-11e5-8429-9b0094f1a50c.png)

May need to view as a non-admin to see the line?

**Comment by itsjoekent** [comment]
just verified with @katiecrane ^ being an admin blocks this bug from happening _on thor_, however on local it doesn't make a difference for me. just pulled the latest changes ~5 minutes ago

**Comment by katiecrane** [comment]
For me it was happening only for non-admins, but I just submitted a PR to fix it for all users
