### ISSUE TITLE
Intro container image bug

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6150]
![image](https://cloud.githubusercontent.com/assets/105849/12856456/0e4c2640-cc13-11e5-9f06-bb31162ae3db.png)

Bug where the template is incorrectly thinking there is an image for the intro block and forcing the text to only within the half column.

**Comment by namimody** [comment]
OH BRILLIANT @weerd!

**Comment by weerd** [comment]
:smile:

**Comment by namimody** [comment]
Hii @weerd! Was just poking around the site and noticed that a couple of static content pages still have alignment like this -- did you want the content to go all the way across, or is this correct?

![image](https://cloud.githubusercontent.com/assets/12396076/13113581/9b3f0eb6-d55d-11e5-9411-1891c58a6d6b.png)

![image](https://cloud.githubusercontent.com/assets/12396076/13113589/a6c009e8-d55d-11e5-8708-f6267309b57e.png)

**Comment by DFurnes** [comment]
@namimody We usually use the three-quarters width Container for text blocks because otherwise the line-width would be super long and difficult to read. :smile:

**Comment by weerd** [comment]
@namimody yep yep, what @DFurnes said. The issue addressed where it was suuuuper compact like on the International page and was due to a bug where it was inserting an empty image tag on the right even though visually it seemed empty.

**Comment by namimody** [comment]
Ahhh thanks @DFurnes and @weerd! #expectedbehavior :raised_hands:
