### ISSUE TITLE
Include Campaign Run property in Signup response object

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6153]
### Updated description

Include the Signup's Campaign Run id as well as whether Campaign Run is the Campaign's current Run. This will allow us to query for a user's "Prove it" campaigns (current campaigns which they need to complete / reportback on)
### Original description

Refs #6110

Discussed how the GET `signups` index will work with @weerd, he mentioned ability to filter by a User ID and by Campaign ID's.  The mobile app needs to know which of those Signups are for current Campaign Runs. Ideally we could support passing a query parameter like `current=true` or `active_campaigns=true` which would do some heavy lifting by joining the Signups Run on a Campaign's Current Run.

Including the Reportback information within the Signup object (#6151) would make it easy to find a User's current "Prove It" campaigns, we could just loop through a User's `current=true`  and look for Signups that don't have a Reportback.  Way less critical, but additionally could see a use for another param like `completed=false` or `reported_back=false` to let the API handle it.

**Comment by aaronschachter** [comment]
Updated this issue title per discussions with @chloealee @DFurnes and @weerd . As long as we have the information we need, we don't need a query parameter, a client can just filter the records by traversing through the response:

```
{
  "data": {
    "id": "2",
    "created_at": "1393010906",
    "campaign_run": {
        "id": "1982",
        "current": true,
    },
    "campaign": {
      ...
    },
    "reportback": {
      ...
    }
  }
}
```

**Comment by aaronschachter** [comment]
@weerd @chloealee Might be sweet to additionally include the Run's End Date if possible... That way we'll be able to know whether the user's current signups are for active campaigns (when a date doesn't exist, or when a date in the future exists -- we can display a message like "5 days left"). 

```
{
  "data": {
    "id": "2",
    "created_at": "1393010906",
    "campaign_run": {
        "id": "1982",
        "current" true,
        "ends_at": "1424978282",
    },
```

cc @angaither

**Comment by chloealee** [comment]
@aaronschachter ah good idea! 
@weerd to double check, is the `end` in `high_season` the correct value to include?

```
timing: {
  high_season: {
    start: "2015-07-18T00:00:00+0000",
    end: "2015-07-25T00:00:00+0000"
  },
  low_season: null
},
```

**Comment by weerd** [comment]
I'm not 100% positive but I don't think the timing dates are the actual campaign dates, but more for that whole hot module type stuff... but not entirely sure :\  @mikefantini?

**Comment by weerd** [comment]
We could do a timing object as well with just the `start` and `end` properties to follow the pattern and use the standard ISO-8601 format that we're pushing towards for our API responses (cc: @DFurnes)

```
{
  "data": {
    "id": "2",
    "created_at": "1393010906",
    "campaign_run": {
        "id": "1982",
        "current" true,
        "timing": {
            start: "2015-07-18T00:00:00+0000",
            end: "2015-07-25T00:00:00+0000"
        },
    },
```

**Comment by chloealee** [comment]
ah I think you're right, @weerd ! I'm looking at the API documentation right now - I don't think that the `start` and `end` dates for the campaign runs are exposed?

**Comment by aaronschachter** [comment]
I was under the impression (but actually can't confirm since I haven't been in the code or reviewing PRs) that Start and End dates should be defined on Campaign Run node (not the Campaign node's High Season field). 

cc @angaither @deadlybutter

**Comment by itsjoekent** [comment]
correct, the high season is only being used for the hot module, but that is going away from what i understand.

**Comment by mikefantini** [comment]
High season date is also what currently shows on the header photo if we want to display when a campaign is going to end.

**Comment by chloealee** [comment]
ah cool, thanks all! So high season date can should be the same value as the current run's dates then?

Also, if it isn't the current run, do we want the `start` and `end` in `timing` to both return `null`?

**Comment by aaronschachter** [comment]
It makes sense to still display `timing` regardless of whether the run is current, we may want to display the start/end dates once Users have multiple runs they participated in and we wanted to build out profiles accordingly.

**Comment by mikefantini** [comment]
Also @chloealee it would make sense if they were the same, but just note that this is not always the case currently.

**Comment by chloealee** [comment]
gotcha, makes sense!

**Comment by weerd** [comment]
Yeah, lets defs always show the `timing` even if not current run, so we can see timing on all runs of a campaign. If a campaign run (old ones) don't happen to have a date then `null` seems appropriate.

**Comment by aaronschachter** [comment]
Lets create a separate issue for `timing`, as its not critical for mobile app.
