### ISSUE TITLE
Address fields no longer show up when collecting user address on campaign

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6158]
Address fields no longer show up when you configure a campaign to collect user address via the Custom Settings on the campaign.

Example: https://thor.dosomething.org/us/node/1508/custom-settings

![image](https://cloud.githubusercontent.com/assets/6330971/12874702/ce65cbea-cda6-11e5-8ab2-91e9687bc029.png)

![image](https://cloud.githubusercontent.com/assets/6330971/12874692/859bc93c-cda6-11e5-8cc4-305965f7f378.png)

**Comment by mikefantini** [comment]
Only seems to work if you configure the shipment form in custom settings, not the signup data form. I guess that's ok if we want to exclusively use the shipment form for sending things to users instead of the signup data form.

If that's the case though then we should remove address collection option from the signup data form.

**Comment by mikefantini** [comment]
And actually if we went this route we'd have to add "prompt after signup" option to the shipment form.

**Comment by mikefantini** [comment]
@angaither I assume the route you want to go with this is actually just having address show up when an admin tries to collect user address from the Sign Up Data form?

**Comment by katiecrane** [comment]
@mikefantini @angaither Okay so currently the option to collect addresses from sign up data form is more broken than the "shipment form" option. I'm confused about if we want to kill one of those and fix the other one or fix both?

**Comment by mikefantini** [comment]
@katiecrane I think we should not touch the Shipment Form and fix the Sign Up Data Form for now.

Let me know if that makes sense/if you have any other questions.

**Comment by katiecrane** [comment]
@mikefantini makes sense and I think it's all fixed, just doing a couple more tests

**Comment by mikefantini** [comment]
Amazing thanks @katiecrane
