### ISSUE TITLE
Campaign: Action Guide fields

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#616]
Depends on #615 

New fields for
- Action Guide nid (EntityReference)
- Action Guide Copy

@mikefantini to provide placement / sequence, labels, and help text.

**Comment by mikefantini** [comment]
@aaronschachter action guides should be listed as bullet points within Stuff You Need. These should always be placed at the end of the list. Also one campaign could have multiple action guides associated with it.
i.e.:
- paper 
- scissors 
- this guide on making cards
- this guide on being generally awesome

Fields needed:
- Action Guide nid (EntityReference)
- Action Guide Description
  -- help text for Action Guide Description: this is what will appear in Stuff You Need (i.e. These tips on making birthday cards)

**Comment by aaronschachter** [comment]
@mikefantini Does the Action Guide description need to live on the campaign itself? Or would it be part of the Action Guide node?

In other words, do we need to have different descriptions for the same action guide on campaign per campaign?  The simpler build would be that it's always the same no matter where the Action Guide is referenced, but wanted to confirm is that the requirement is the description to be attached to teh campaign (not the action guide)

**Comment by mikefantini** [comment]
let's put the description on the action guide itself
