### ISSUE TITLE
API requests with no results should return empty array instead of error message

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6163]
The request is successful, but we get an error message. TouchLab had asked for an empty array instead, this may make error handling in a little easier, as this isn't an actual error.
- [x] signups 
- [x] reportbacks
- [ ] campaigns

e.g. https://staging.dosomething.org/api/v1/reportback-items?campaigns=1

![screen shot 2016-02-11 at 11 12 15 am](https://cloud.githubusercontent.com/assets/1236811/12981875/96711eb2-d0b0-11e5-89dc-93e11103cfe2.png)

cc @weerd @jonuy

**Comment by aaronschachter** [comment]
Commenting out [this `if` block](https://github.com/DoSomething/phoenix/blob/ef7021a8e89835acd6b21cb5e559b2dbce183b12/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L126) seems to fix, it's throwing an exception when we don't really have an error here, just empty `data`.

Testing with @chloealee on `signups` endpoint by removing that `throw Exception` gives us desired behavior in API (but just need to make sure it wont break anything in the gallery)

![screen shot 2016-02-12 at 2 56 03 pm](https://cloud.githubusercontent.com/assets/1236811/13019161/b7d418de-d19b-11e5-96f0-f649da099352.png)

**Comment by aaronschachter** [comment]
@weerd I'm still seeing the "No signup data found" for `signups: http://staging.beta.dosomething.org/api/v1/signups?user=56c50367a59dbf994e8b456d

![screen shot 2016-02-17 at 8 26 38 pm](https://cloud.githubusercontent.com/assets/1236811/13130787/cd3f1b7a-d5b4-11e5-93c4-316fe441d2d2.png)

**Comment by weerd** [comment]
The signups stuff hasn't been merged in yet... it's in #6168.  Also, you're querying w/ a Northstar ID to Phoenix which isn't going to do much good. Didn't @DFurnes setup a proxy via NS for that shiz?

**Comment by aaronschachter** [comment]
Ah ok. Yep, i was querying northstar but just tested phoenix as a sanity check and forgot to switch to a phoenix ID. Technically makes sense to keep this open until we get #6168 in but good to know it's on the way!

**Comment by weerd** [comment]
But yeah, makes sense to leave open. Even w/ NS id (or random string) should still be empty array so didn't really matter that it was an NS id. :)

**Comment by chloealee** [comment]
@angaither I think we can close this with #6168 merged in, correct? 

Looks like [campaigns](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign/includes/CampaignTransformer.php#L46) and [reportbacks](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/ReportbackTransformer.php#L31) also already return an empty array instead of error message!

**Comment by angaither** [comment]
@chloealee great!

**Comment by aaronschachter** [comment]
We should add this logic into individual resources: going to a non campaign at `api/v1/campaigns/[id]` results in a 200 if the ID doesnt exist.

![screen shot 2016-03-10 at 1 16 49 pm](https://cloud.githubusercontent.com/assets/1236811/13684892/b7d297fc-e6c2-11e5-9e1b-0758f3a98f55.png)

**Comment by DFurnes** [comment]
If we want this to be  :sparkles: RESTful :sparkles:, any resources that don't exist should return a `404` status code.
