### ISSUE TITLE
💯 Emoji RB Support

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6167]
Adding emoji kills the reportback submission

![image](https://cloud.githubusercontent.com/assets/645205/13063428/fd2fe6c0-d415-11e5-873a-00b30a588977.png)

submitting that returns a 404 for me. 

I _think_ this will require us to not use UTF-8 encoding in the db. 

https://dosomethingorg1.zendesk.com/agent/tickets/149465
http://www.jeffgeerling.com/blogs/jeff-geerling/solving-emoji-problem-drupal-7

**Comment by sheyd** [comment]
@angaither Adding this in case (and I think we should for sanity of mind), change to actual UTF8 (i.e. utf8mb4) across the :globe_with_meridians: 
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by namimody** [comment]
- [ ] edit Thor DB structure
- [ ] edit Thor web app
- [ ] edit prod DB structure
- [ ] deploy
- [ ] change data warehouse to ensure slave replication process still continues to work
- [ ] edit quantum DB

**Comment by namimody** [comment]
https://www.dosomething.org/admin/reportback/128124 -- dunno what those recycling signs are (emojis?), but interesting they show up in back end and in the caption on the front end...

**Comment by angaither** [comment]
closing because we can hope for better days in repo https://github.com/DoSomething/guardian

**Comment by namimody** [comment]
@angaither does it make sense to move this issue to the Quasar repo?

**Comment by ngjo** [comment]
hi @angaither -- @hbghidey and i were just talkinga bout this today! hannah was recreated this issue on mobile (full thread here: https://trello.com/c/vfFRBOiT/1602-users-hitting-404-page) but essentially, when someone submits a RB w/ an emoji over mobile, they get a 404 page and then when they hit back, they see the reportback gallery but then the submission button is gone

is there anything we can do to accept emojis (makes a lot of sense for mobile reporting back, especially), or should we add text in there that tells the user that they can't submit emojis?

**Comment by angaither** [comment]
yup, it's not just mobile, it's anytime emoji is submitted the reportback doesn't go through. 
but I'm not sure it makes sense to prioritize this issue in phoenix since we want to move reportbacks to rogue.

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vfFRBOiT&#x2F;1602-users-hitting-404-page"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Users hitting 404 page</a>

**Comment by jessleenyc** [comment]
Would we be able to accept emojis in rogue? Thinking about how this is throwing off our 'pending' reportbacks count.

**Comment by angaither** [comment]
> Thinking about how this is throwing off our 'pending' reportbacks count.

these reportbacks wouldn't be `pending` this is the problem where the reportback id exisits, and there's no file #6765

**Comment by ngjo** [comment]
yah -- no need to prioritize, but if that's the case -- i'll sync w/ @hbghidey to include that in the tech macro for the time being to help the member submit w/o emojis (sorrrrrriiieee, no fun emojis 🤑 for youuuuu!!!) thanks!

**Comment by angaither** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CDJfrL7m&#x2F;3-as-a-user-i-would-like-to-be-able-to-submit-an-emoji-with-my-reportback-so-that-i-can-express-myself-without-words-also-so-the-s"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As a user, I would like to be able to submit an emoji with my reportback so that I can express myself without words (also so the system doesn&#39;t break).</a>

**Comment by mirie** [comment]
We have emoji support in Phoenix-Next and Rogue. We will not be supporting emoji's in Phoenix-Ashes. We already are stripping out emojis from reportbacks per #7014.
