### ISSUE TITLE
forward users to gladiator

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6170]
after #6169 we need to send an HTTP request to send the user who opted into the competitions #4616
this might be a chance to get guzzle working in this repo
#4594

**Comment by angaither** [comment]
@sbsmith86 i just thought of something, for now you can test this with forwarding to gladiator from local to local, then switch out the url's for each env

**Comment by sbsmith86** [comment]
@angaither yea, definitely wouldn't send people to prod from my dev. But I'm not sure what endpoint im supposed to be hitting. I think @weerd was gonna set something up?

**Comment by angaither** [comment]
@sbsmith86 you can use `gladiator.app:8000`!

**Comment by angaither** [comment]
oh, but to the actual ENDPOINT. doi

**Comment by angaither** [comment]
refs #6246
but needs more error protection
as well as potential api updates DoSomething/gladiator/issues/54

**Comment by mshmsh5000** [comment]
This endpoint (`/api/v1/users/`) is crapping out with a 500 on QA with a POST payload, but only when you add the `Accept: application/json` header.
