### ISSUE TITLE
Emoji support on the frontend

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6173]
in addition to #6167 we need to handle what emoji looks like for devices that do not natively support emoji
explore this! :mag: :haircut: :100:

**Comment by DFurnes** [comment]
I haven't looked into this too closely, but it looks like something like [heyupdate/emoji](https://github.com/heyupdate/Emoji) might do the trick.

**Comment by mirie** [comment]
Closing this as well since #6167 has been closed.
