### ISSUE TITLE
Redirect for Nickelodeon Partnership

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6178]
Vanity URL: dosomething.org/halo

Should redirect to: https://www.dosomething.org/us/campaigns/treat-yo-friends

Thanks!

**Comment by blisteringherb** [comment]
I've added this redirect into Fastly, and it appears to be working.

**Comment by namimody** [comment]
Thanks so much @blisteringherb!

**Comment by namimody** [comment]
New campaign, new request, old issue!

On Monday, dosomething.org/halo needs to redirect to: https://www.dosomething.org/us/campaigns/patient-playbooks

**Comment by mshmsh5000** [comment]
I've updated the Fastly config and tested. (And it works! So I stopped testing.)
