### ISSUE TITLE
Members need to be able to log in with email, cell (username?)

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#619]
Dave and Maxwell originally flagged this. On our current site lots of members log in using the cell number, username or email address. 

Can users currently do this in the new login flow?

**Comment by DFurnes** [comment]
There's some discussion on this in #614.

**Comment by barryclark** [comment]
Think we need to clarify the username part of this. Email and cell are def required, but it'd be great if there was a way to see how many people currently use a username to login, and if it'll be possible for us to drop that. 

(updating the title to reflect this)
