### ISSUE TITLE
paraneue image note found notices

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6202]
#### Current Behavior
- all sorts of theme errors in the admin section when placing the `no-image-found` placeholder
#### Desired Behavior
- no errors
- [`dosomething_image`](https://github.com/DoSomething/phoenix/commit/aa2197da29f9109c8391acdcbbe8992804eeab4c) needs to find a not found image regardless of theme
#### Relevant Screenshots + Links

![](https://files.slack.com/files-pri/T024GV2BW-F0NGDUYQN/pasted_image_at_2016_02_22_03_09_pm.png?pub_secret=aff3f5ced9)

**Comment by DFurnes** [comment]
The problem is that we're using the `PARANEUE_PATH` constant that's defined in the theme from a module, so when that module is used outside of the theme it has no idea what that constant is.

We should probably move the "theming" of not-found images into the theme.

**Comment by angaither** [comment]
at this point.......
