### ISSUE TITLE
Expose competition in campaign api

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6205]
To support DoSomething/gladiator/issues/14 the api needs to expose if the campaign has a competition on it.

**Comment by chloealee** [comment]
@angaither this isn't already a field on the cms, I'll have to add and also expose in the `/campaigns` endpoint, right?

**Comment by angaither** [comment]
@chloealee yes, but it's not a field, it's a custom-setting on the signup data form
![image](https://cloud.githubusercontent.com/assets/645205/13262782/9bf04880-da34-11e5-8fdd-0f76a132f172.png)

**Comment by chloealee** [comment]
ooohh thank you! I'm assuming that there should be a column for this in the `dosomething_signup_data_form` table but not seeing it there. Do I have to do anything to make sure the boolean value reflects in the database?

**Comment by sbsmith86** [comment]
@chloealee you probably need to run `drush updb -y`

**Comment by chloealee** [comment]
thanks, @sbsmith86 ! Hmmm just did that and refreshed Sequel Pro and still don't see it :-/

Only seeing these fields: 
![screen shot 2016-02-23 at 2 17 15 pm](https://cloud.githubusercontent.com/assets/9019452/13263600/2fccb0b8-da38-11e5-8762-d617b27baa8b.png)

**Comment by sbsmith86** [comment]
that's weird cause there should be a few new fields in there. [This is the hook](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/dosomething_signup.install#L680-L696) that sets them up. Are you sure it ran?

**Comment by chloealee** [comment]
weird! Is it skipping over `function dosomething_signup_update_7023()`? I don't think I've run `drush updb -y` in awhile and it looks like it just did `function dosomething_signup_update_7024()`?

![screen shot 2016-02-23 at 2 28 01 pm](https://cloud.githubusercontent.com/assets/9019452/13263952/ece7e702-da39-11e5-8bd9-aeab0ec6269e.png)

Is there a way to update on `function dosomething_signup_update_7023()` in particular and isolate that one?

**Comment by sbsmith86** [comment]
yea you can rollback your drush updates in sequel pro

Get the current schema version you are on

`SELECT * from system where name = 'dosomething_signup'`;

Update the schema version to the one right before the one you want to run:

`UPDATE system SET schema_version = 7022 WHERE name = 'dosomething_signup';`

and then try running drush updb again. 

Also[ this is another way](https://www.deeson.co.uk/labs/re-running-update-hooks-drush)

**Comment by chloealee** [comment]
ah this is awesome - thanks so much @sbsmith86 !! It worked!!
