### ISSUE TITLE
hreflang can refer to unpublished campaign translations

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#6209]
#### Current Behavior

Detected by Google's WMT. A campaign that's published in one language (say, `en-us`) may have an alternate URL specified via `hreflang` to translation that's not actually published.

WMT crawls that alternate URL, which is actually a 404 page, and dings us because it doesn't see a reciprocating `hreflang` link that points back to the original `en-us` campaign.
#### Desired Behavior

The alternate-language URL shouldn't appear, because that translation isn't actually published.
#### Steps to Replicate

Replicable for any URL tracked in the [WMT analysis](https://www.google.com/webmasters/tools/i18n?siteUrl=https://www.dosomething.org/):

**As an anonymous user:**
1. Load the original (published) URL, e.g., https://www.dosomething.org/campaigns/not-stuck-traffick
2. View source
3. Locate the `rel="alternate"` markup in the source, e.g., `<link rel="alternate" hreflang="es-mx" href="https://www.dosomething.org/mx/voluntario/sin-atarcarse-en-el-tráfico" />`
4. Load that URL, and verify that it's a 404.
#### Why This Matters

This seems to relate to the confusion documented in #5876 &mdash; i.e., the system has an inconsistent understanding of when a translation is published.
#### Countries Affected (optional)

All
#### OS/Browser (optional)

All
#### Relevant Screenshots + Links

Google's view:

<img width="985" alt="wmt-hreflang" src="https://cloud.githubusercontent.com/assets/149811/13269310/18fce93a-da55-11e5-8ea5-0019aeb7ba3a.png">

Source of `en-us` (published) version:

<img width="966" alt="rel-alternate-hreflang" src="https://cloud.githubusercontent.com/assets/149811/13269351/564e1908-da55-11e5-8dd4-c99f943ed72d.png">

Resulting 404:

<img width="909" alt="404" src="https://cloud.githubusercontent.com/assets/149811/13269371/6e720a44-da55-11e5-863d-3f9d8215003d.png">

Drupal thinks "this translation is published":

<img width="791" alt="translation-published" src="https://cloud.githubusercontent.com/assets/149811/13269391/884d8830-da55-11e5-8589-e134ae61abcd.png">

The Translate tab disagrees:

<img width="1087" alt="translate-tab" src="https://cloud.githubusercontent.com/assets/149811/13269427/a0745d62-da55-11e5-9b7d-112a2ec61c1e.png">

**Comment by angaither** [comment]
i don't think it's related to the translation tab, the [code that adds the link](https://github.com/DoSomething/phoenix/blob/ad3ddbb5a6e198fa84a6574e9f0477e3616c2237/lib/themes/dosomething/paraneue_dosomething/includes/preprocess/preprocess_node.inc#L6) doesn't actually check if the translation is published before adding the link
