### ISSUE TITLE
Cloning Campaign Nodes for Rapid Response

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6210]
#### User Story

Leads/Calvin would like to duplicate existing campaigns with one click for news response and white label.
#### Additional Information (optional)

I found this but don't know much about the nuance of it: https://www.drupal.org/project/node_clone especially re: reportbacks, translations, and field collections.

Obviously, this isn't a huge priority, but wanted to start a discussion on it.
#### Why This Matters

The time that is spent on creating a rapid response campaign should be primarily spent on crafting the right tone and message, not copying and pasting.
#### Current Workaround w/o Feature (if applicable)

Creating a new campaign step by step by copying and pasting everything.

**Comment by namimody** [comment]
Hey @angaither! Any thoughts on this?

**Comment by angaither** [comment]
@namimody yeah seems like this convo might be related to #6235 in the sense that if we are creating duplicate nodes, what happens to the original?
but, we can certainly try this module and see how it works with translation and cloning

**Comment by namimody** [comment]
Awesome, thanks @angaither! Yea that's a great point -- this is definitely connected to #6235, so let's see what comes out of tech/campaigns sync next week re: retiring campaigns and then we can discuss this with some more concreteness?

**Comment by angaither** [comment]
@namimody @mikefantini I think this is something we decided as an org not to do, correct?

**Comment by namimody** [comment]
@angaither I don't think we need to do it, I haven't really seen the need for it in the last three months (as in, I haven't seen much replicating and tweaking of campaigns) -- gonna close!
