### ISSUE TITLE
address on 'update my profile' not validating

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6214]
#### Current Behavior

you can update an address to say whatever you want, it doesn't validate
#### Desired Behavior
- address validate like on the signup data form
#### Steps to Replicate
- go to user/XXX/edit and update the address
- put in something that doesn't make sense
#### Relevant Screenshots + Links

no errors on user/edit
![image](https://cloud.githubusercontent.com/assets/645205/13301739/6b8c93b6-db14-11e5-8bf8-399d360bd622.png)

errors on signup data form
![image](https://cloud.githubusercontent.com/assets/645205/13301749/74959804-db14-11e5-981f-8a7c4456e4cf.png)

This probably has something to do with the fact that `field_address` is treated different than the signup data form [here](https://github.com/DoSomething/phoenix/blob/5896b2823f770c6aa3a1e9cf46d474ef4ae60564/lib/modules/dosomething/dosomething_user/dosomething_user_valid_address.inc#L43)

**Comment by angaither** [comment]
@chloealee i also noticed the address is probably not validating when admins change the page at `http://dev.dosomething.org:8888/us/user/10/edit` because[ it's checking for `user/id/edit` without the us prefix](https://github.com/DoSomething/phoenix/blob/0dae77850b1124ea7e12b12adc36dd465fb68ab9/lib/modules/dosomething/dosomething_user/dosomething_user.module#L261)
since we are only validating us address we can probably update that line

**Comment by angaither** [comment]
I forgot that the info form recently added address #6027, so it's probably as simple as adding validation to it. 

cc @katiecrane

**Comment by katiecrane** [comment]
Oooo whoops yeah I just had it updating the values and didn't do anything special to validate it it looks like. Sorry!

**Comment by chloealee** [comment]
@angaither on my local when I go to edit, it doesn't have the country code - `http://dev.dosomething.org:8888/user/1704953/edit` but still allows it to save (I didn't update the `preg_match` to include the us prefix`). 

Also, should I be adding this validation again in `dosomething_user.module` even though it's already [here](https://github.com/DoSomething/phoenix/blob/0dae77850b1124ea7e12b12adc36dd465fb68ab9/lib/modules/dosomething/dosomething_user/dosomething_user.module#L262) (where you noted above)?

**Comment by angaither** [comment]
it's two issues
- the user info [edit form](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1204) needs to have validation added 
- admin update form
  the country code only gets set locally if you [manually set fastly headers](https://github.com/DoSomething/phoenix/wiki/Fastly-Global-Header-Setup#quick-setup-for-local-testing)

**Comment by chloealee** [comment]
ah, thanks for clarifying, @angaither !
