### ISSUE TITLE
Create cron to set up competitions

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6225]
in order to only have one place to configure competitions
phoenix can ping gladiator to get the info and set the proper variables to set up a competition

**Comment by itsjoekent** [comment]
talked with @weerd about this in Slack --

> IMO makes more sense to just have the front end query the gladiator api, if it returns true, the frontend creates a modal
> like how attn does there stuff for example
> otherwise we’re still just contributing to the monolith but with less code
> 
> if we’re moving towards a services approach, drupal should not know or care about what services its working with
> JS can easily do competitions without ever touching drupal

@weerd has additional thoughts I think

cc: @angaither

**Comment by angaither** [comment]
@deadlybutter I don't think we should try to build that for the first version, there's trickyness with the skip and the modal popping up after another modal that already works with the signup data form.

**Comment by itsjoekent** [comment]
@angaither I guess I dont fully understand what the signup data form is then, where is it used? (as in, example on the site right now)

**Comment by angaither** [comment]
@deadlybutter after a user signs up for a campaign and there's potentially additional information needed
(address/school/otherquestions) a second modal pops up that collects this info and stores responses with the signup. it allows for a skip and there's UX rules around when it shows up. since it's built it seems easiest to use what we already have
the fields are already set up to allow for competitions signups, this issue just makes it so when you set up a competition you only do so in gladiator.
phoenix will grab the info from gladiator and set up the form accordingly
