### ISSUE TITLE
Scholarship Winner Not Appearing on Naughty or Nice Closed State

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6226]
#### Current Behavior

Despite having all the necessary winner fields filled out on the run node (6601), the front end of the closed state is still saying that we are sifting through applications.
#### Desired Behavior

When a campaign has a number in the incentive field of the /edit view of the campaign node and has winner information filled out on the associated run node, the front end of the closed state should show the scholarship winner. Working example: https://www.dosomething.org/us/campaigns/thumb-wars
#### Steps to Replicate

This seems to only be happening on Naughty or Nice on production and Thor. Other campaigns are working fine. The one difference for this campaign is that the original language for the campaign was GL EN. 

I can't replicate on another campaign that had the original language as GL EN -- I tried: https://thor.dosomething.org/campaigns/happy-scrappy-holidays, and it worked. I could totally be missing something, but I have no other ideas about what to try.
#### Why This Matters

We want to fame scholarship winners on the closed state for the individual, but also to let other members know that we do actually give out scholarships. :)
#### Relevant Screenshots + Links

https://www.dosomething.org/us/campaigns/naughty-or-nice

![image](https://cloud.githubusercontent.com/assets/12396076/13400190/aaccccbc-ded4-11e5-800f-079a467443a7.png)

![image](https://cloud.githubusercontent.com/assets/12396076/13400304/222dade4-ded5-11e5-94f8-2f14be9ca1b9.png)

**Comment by angaither** [comment]
@namimody is this only on one specific campaign or all campaigns?

**Comment by namimody** [comment]
Only on this specific campaign @angaither. @mikefantini and I can't figure out why.

**Comment by angaither** [comment]
@namimody is there other content that should be getting pulled in that isn't, or is it just winner content?

**Comment by angaither** [comment]
@namimody the winner content is pulling from the run node referenced in the global english version of the campaign
I think this might be because en global is the default language of the node, so it's pulling form the run in that language

see https://thor.dosomething.org/node/6153

I'm going to close this issue out, and we can open a different one if we find runs aren't working across multiple languages (they may not be)

**Comment by namimody** [comment]
Ooof thanks @angaither. This is fun: there are two "Naughty or Nice run 1"s with very similar time frames. The two translations of the campaign are associated with different runs. Both runs are translated. 

![image](https://cloud.githubusercontent.com/assets/12396076/13675833/656faec0-e6b1-11e5-89bd-0e4e940ab272.png)

For now, I added the scholarship winner information to the run associated with the GL EN translation of the site.

However, we need to:
a) figure out which run signups/reportbacks are associated with and then delete the other one
b) fix this issue with runs -- @angaither doesn't this scenario indicate that the campaigns default language trumps associations of campaign translations with runs?
