### ISSUE TITLE
New Images/Facts are Not Immediately Referenced By Field

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6227]
#### Current Behavior

If a backend site user adds a fact or image using the green plus sign, the fact or image gets created but the field they would like to input it in is not autopopulated with the new item. 
#### Desired Behavior

Newly created facts or images should autopopulate in the field after they are created.
#### Steps to Replicate

Go to a campaign or static content page. Add a fact or image using the green plus sign. Save the image or fact. You will not see the newly created fact/image referenced within the field. You can try it here: https://thor.dosomething.org/us/node/2532/edit
#### Why This Matters

This was the behavior previously, so leads and other admins perceive the site to be broken and not saving the fact created/image uploaded. Plus, it's a better UX.

**Comment by angaither** [comment]
my hunch is the field is translatable and images/facts are not so they aren't automatically referenced. 
again, since this is a module we use but didn't build the fix for this will probably take a while

Refs #5523

**Comment by angaither** [comment]
tried a bunch of debugging on this one, disabling translations and adding debug statements to the `entity_connect` module, but it couldn't get anywhere

**Comment by namimody** [comment]
Ahh thanks so much for looking into this @angaither! What's the next step if debugging efforts so far haven't been fruitful?

**Comment by angaither** [comment]
@namimody not sure, we could check for patches/write a patch
anywho, giving this a :x:L label

**Comment by katiecrane** [comment]
@angaither @namimody I dug around in this too, focusing on the entity connect module and the fact module and I was unable to find anything helpful. Most of the variables in the entity connect module were too big to print out too.

**Comment by namimody** [comment]
Oh bummer, thanks a ton for looking though @katiecrane! I guess let's de-prioritize for now then, @angaither?

**Comment by angaither** [comment]
@katiecrane the other place that might be helpful to look is for [bugs in the module](https://www.drupal.org/project/issues/entityconnect) and see if there are any patches for this

**Comment by angaither** [comment]
if that isn't fruitful :apple: :banana: :watermelon: then, yes we should de-prioritize

**Comment by katiecrane** [comment]
@angaither I didn't find any :strawberry: :green_apple: there. Some of the issues are close to what we're seeing, but I don't think any of them are the same.
