### ISSUE TITLE
Guns Out Redirect

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6228]
NEED: 
dosomething.org/flex and dosomething.org/gunsout 

TO REDIRECT TO:
https://www.dosomething.org/us/campaigns/guns-out

By EOD Wednesday, 3/2. Thanks!!

**Comment by sheyd** [comment]
@namimody Re-direct is in place!

**Comment by namimody** [comment]
THanks @sheyd!!
