### ISSUE TITLE
Funky Signups data - possibly only on Thor.

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6229]
#### Current Behavior

Some Campaign data from the `signups` API endpoint is not associated with a Campaign (but instead what seems to be a Campaign Run node). These Signups have a Campaign Run value 0.
#### Desired Behavior

The Campaign property should reference a valid Campaign, and the Campaign Run property should reference a valid Campaign Run.
#### Steps to Replicate

https://northstar-thor.dosomething.org/v1/signups/642325
Its campaign is set to 3110, which is a Campaign Run node for SuperStressFace: https://thor.dosomething.org/node/3110
Its campaign Run is set to 0.
Said node id has many reportbacks: https://thor.dosomething.org/api/v1/reportback-items?campaigns=3110

However the signup on prod looks correct: https://northstar.dosomething.org/v1/signups/642325
https://thor.dosomething.org/api/v1/signups/642267
Again, looks correct on prod: https://northstar.dosomething.org/v1/signups/642267
#### Why This Matters

User Profiles in DS-iOS display Reportbacks without Campaign information.
#### Relevant Screenshots + Links

![screen shot 2016-03-01 at 9 05 19 am](https://cloud.githubusercontent.com/assets/1236811/13435017/ffc95bc8-df8c-11e5-9dcb-fbe3a281505c.png)
![screen shot 2016-03-01 at 8 44 12 am](https://cloud.githubusercontent.com/assets/1236811/13435021/028ca446-df8d-11e5-878e-37a5b96aab5a.png)
![simulator screen shot mar 1 2016 9 04 20 am](https://cloud.githubusercontent.com/assets/1236811/13435023/06387eda-df8d-11e5-8d13-0406a2c78069.png)

cc @jonuy

**Comment by aaronschachter** [comment]
Another example:
https://thor.dosomething.org/api/v1/signups/588786 has a Campaign of 3547, Campaign Run = 0. 
https://thor.dosomething.org/node/3547 is a Campaign Run node (Birthday Mail Run 1)
https://thor.dosomething.org/api/v1/reportback-items?campaigns=3547

**Comment by angaither** [comment]
@aaronschachter I was thinking we can do another thor/prod refresh and see if things look better, does that sound ok?

**Comment by aaronschachter** [comment]
Sounds good - we'll just need to coordinate with @marahml and @jonuy to schedule the downtime.

The 2nd example looks good on prod too https://www.dosomething.org/api/v1/reportback-items?campaigns=3547 vs https://thor.dosomething.org/api/v1/reportback-items?campaigns=3547

A sanity check would could run in the meantime on prod is just a query to see if we see any Signups or Reportbacks with a `run_id` set to 0.

**Comment by angaither** [comment]
oh, i know the answer to that. 
on prod: 
there's about ~40 reportbacks with `run_nid` as 0 
~200k signups with `run_nid` as 0

**Comment by angaither** [comment]
@aaronschachter besides the issues covered in #6232 I think the examples you provided here are fixed.
closed if you agree!

**Comment by aaronschachter** [comment]
New data set looks good!  Open question of how'd it get so funky in the first place? :guitar: Will keep an eye out.
