### ISSUE TITLE
Campaign CSV export

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#623]
Deluca needs a CSV export of campaign data to sync with his filemaker database.

Fields needed:
- nid
- title
- status
- high season start date
- high season end date
- primary cause tag
- all cause tags
- primary action type tag
- all action type tags
- hours
- issue
- sponsors

cc: @barryclark

**Comment by angaither** [comment]
We can use a view (with https://drupal.org/project/views_data_export) however that only supports a MySQL database... so if we are switching to MariaDB (#601) we shouldn't use this.

In the past I've used `services` and `services_views` however then you run into funkyness with the export where you can't override the default pager. The maximum results on a page is 10 and you manually need to request new pages.

It might be easiest to create a script that queries the database and have a job in jenkins that runs this when needed.

**Comment by angaither** [comment]
`SELECT n.nid, n.title, n.status, hs.field_high_season_value, hs.field_high_season_value2, pct.name as primarycause, group_concat(DISTINCT ct.name separator ', ') as causes, patt.name as primaryactiontype, group_concat(DISTINCT att.name separator ', ') as actiontypes, ah.field_active_hours_value as hours, it.name as issue
FROM node n
LEFT JOIN field_data_field_high_season hs on n.nid = hs.entity_id
LEFT JOIN field_data_field_primary_cause pc on n.nid = pc.entity_id
LEFT JOIN taxonomy_term_data pct on pct.tid = pc.field_primary_cause_tid
LEFT JOIN field_data_field_cause c on n.nid = c.entity_id
LEFT JOIN taxonomy_term_data ct on ct.tid = c.field_cause_tid
LEFT JOIN field_data_field_primary_action_type pat on n.nid = pat.entity_id
LEFT JOIN taxonomy_term_data patt on pat.field_primary_action_type_tid = patt.tid
LEFT JOIN field_data_field_action_type fat on n.nid = fat.entity_id
LEFT JOIN taxonomy_term_data att on att.tid = fat.field_action_type_tid
LEFT JOIN field_data_field_active_hours ah on n.nid = ah.entity_id
LEFT JOIN field_data_field_issue i on n.nid = i.entity_id
LEFT JOIN taxonomy_term_data it on i.field_issue_tid = it.tid
LEFT JOIN field_data_field_sponsor s on n.nid = s.entity_id
LEFT JOIN taxonomy_term_data st on s.field_sponsor_tid = st.tid
WHERE n.type = 'campaign'
GROUP BY n.nid;`

**Comment by aaronschachter** [comment]
Per @angaither 's research and SQL query, i think it's safe to ask the data team to handle this request as per @mshmsh5000 's comments in sprint planning today.  Ideally we would not want data team messing with a Drupal view anyway, as they'd need to be updating features and committing into the repo if we went that route.

**Comment by mshmsh5000** [comment]
@angaither @aaronschachter [MariaDB is binary-compatible with MySQL](https://mariadb.com/kb/en/mariadb-versus-mysql-compatibility/); i.e., any query/module/code that works with MySQL should continue to work after this switch.

**Comment by aaronschachter** [comment]
If we go the View route though, do we just leave the view in the db, not defined in a feature, and train data team on Views?  Or devs would just always have to update / maintain the views feature?  The 2nd sounds easier to maintain but also turns into us handling any data request around this CSV.

**Comment by mikefantini** [comment]
closing this issue. put card on data team's trello board: https://trello.com/c/HH9UxlsW
