### ISSUE TITLE
Support for count query param in GET signups index endpoint

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6230]
#### Current Behavior
- The Signups endpoint only returns 25 results, regardless of any `count` query parameter passed.(https://northstar-thor.dosomething.org/v1/signups?user=554c2f3f469c64ed7d8b6061&count=500). The signup in particular i'm looking for is here: https://northstar-thor.dosomething.org/v1/signups?user=554c2f3f469c64ed7d8b6061&campaigns=6621 and is not returned by the GET `signups?user=:id` query. Also tried passing [`count=all`](https://github.com/DoSomething/phoenix/blob/a64fe84b159586a638a5d15f247e79eb8a2c4ede/lib/modules/dosomething/dosomething_signup/dosomething_signup.query.inc#L24) without luck.
#### Desired Behavior
- Support `count` query parameter to bring back more than 25 records 
#### Why This Matters

Power users, such as Ben Kassoy, who is the user ID mentioned above, may see incomplete profiles while using the mobile app if they have more than 25 signups. (As we close and open more campaigns, this could happen more often). I found this bug by clicking through Ben's profile from the Yo Teach campaign, but then could not find the reportback on his profile (the mobile app query is https://northstar-thor.dosomething.org/v1/signups?user=554c2f3f469c64ed7d8b606)

**Comment by aaronschachter** [comment]
@DFurnes Do we need to make changes on the Northstar side to accept the `count` query string?

**Comment by DFurnes** [comment]
@aaronschachter Nope, all query strings on the request are just forwarded directly to Phoenix (aside from `user`, since we do a little processing on that).

**Comment by chloealee** [comment]
@weerd Do you think it'd also be a good idea to add pagination and all the other API updates I made for `Reportbacks` in this [PR](https://github.com/DoSomething/phoenix/pull/6223)?

**Comment by weerd** [comment]
Yeah, defs add pagination w/ the count stuff taking action :)

**Comment by chloealee** [comment]
Cool, thanks @weerd !
