### ISSUE TITLE
clean up straggler signups

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6232]
- signups on homepage node
- signups on other content types ['image', 'fact', 'campaign_group', 'campaign_run']
- duplicate (?) signups with a run_nid of 0

**Comment by angaither** [comment]
state of the union: 
![image](https://cloud.githubusercontent.com/assets/645205/13467903/51f01b62-e06e-11e5-9b39-784a168133c3.png)

```
select count(s.uid) as count,s.nid, s.run_nid, n.title, n.type
from dosomething_signup s
inner join node n on n.nid = s.nid
where run_nid = 0
group by n.nid
order by n.type
```

**Comment by angaither** [comment]
it looks like signups haven't happened on a non-campaign node since dec 2015.
so _I think_ that bug is fixed, I certainly haven't been able to replicate it locally.

**Comment by angaither** [comment]
there are also reportbacks on non-campaigns, but they appear all to be done by nefarious staff members

**Comment by angaither** [comment]
after the script  #6238
we will have 219 signups where `run_nid = 0`
I checked those, and they can be removed safely after, since all of those users signed up again, and the signup with a 0 run is just a duplicate

**Comment by angaither** [comment]
okay. there are 219 signups that have a `run_nid` of 0 and are still on a node. 
but there's more signups with a `run_nid` of 0 with no node. 
whaaa

**Comment by angaither** [comment]
removed the duplicate (219) duplicate signups from thor. 

the remaining signups with a `run_nid` of 0 are on nodes that have been deleted

@aaronschachter do you think leaving those orphaned signups will cause problems?
we should maybe be removing activity from nodes that are removed?

**Comment by aaronschachter** [comment]
There's a chance they can could potentially cause problems on the profile -- sounds sensible to delete all of a node's activity if we're deleting the node.  A minor UX thing we could add to hopefully avoid this in future is a delete confirmation that indicates there is activity which exists (and then potentially a `hook_delete` to delete correspond activity... although hopefully we won't be in the business of deleting campaign nodes anymore..)

**Comment by angaither** [comment]
this was done on prod as well

**Comment by angaither** [comment]
with a few exceptions that are all staff members
the only remaining signups with `run_nid = 0` is the mysteriously removed node `3251`

I'm going to leave them... in case we ever figure that out.
Also the signups and reportbacks don't show up anywhere (api or profile) so I think we are ok. 

closing this b.
