### ISSUE TITLE
Campaigns API: return closed status if the node is unpublished (or don't return campaign at all)

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6233]
#### Current Behavior
- An unpublished campaign node can exist with `active` campaign status, resulting in a 500 error upon signup. I think this is possible as hack to allow for "mobile app" campaigns only -- campaigns that exist in the app but not on the web. That's no longer a thing.
#### Desired Behavior
- The campaign.status should be returned as `closed` because the node is unpublished, or don't return a campaign at all
#### Why This Matters

Ran into scenarios on mobile app where I tapped through someone's profile to a unpublished campaign, where its `campaign.status == 'active'`. Tried to signup and got a 500 error back.
#### Relevant Screenshots + Links

![screen shot 2016-03-02 at 9 09 50 am](https://cloud.githubusercontent.com/assets/1236811/13468790/3e3fbee8-e059-11e5-963b-f2e7f5916511.png)

Last column is "Published":
![screen shot 2016-03-02 at 9 09 21 am](https://cloud.githubusercontent.com/assets/1236811/13468794/4ad88a9a-e059-11e5-9b21-0b2b111cee56.png)

**Comment by angaither** [comment]
probably easiest to remove unpublished campaigns from the api

https://github.com/DoSomething/phoenix/pull/5175
