### ISSUE TITLE
Retire campaigns

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6235]
- is this a new (? translatable) field on campaigns
- or maybe a new `active/closed/retired` state
- what happens when a user visits a retired campaign they signed up for
- retired campaigns don't show up in solr results

**Comment by mikefantini** [comment]
Other questions to consider:
- What are the different reasons we'd retire a campaign? Unimpactful CTA, unpopular CTA, controversial/offensive campaign, celeb takeover.
- What content would we want the user to see for a retired campaign? Does it change depending on the reason it was retired?

**Comment by mikefantini** [comment]
Campaigns we should :eyes: once we decide what to do:
- 24
- 45
- 1536

**Comment by mikefantini** [comment]
Still waiting to hear from campaigns team on this.

**Comment by namimody** [comment]
@mikefantini we should def be hearing next Wednesday from them!

**Comment by angaither** [comment]
next wednesday is long gone.
