### ISSUE TITLE
Migrate We Are Able activity so it's all on one campaign

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6237]
#### Current Behavior

Multiple campaigns were created for We Are Able and both have signups and reportbacks.
#### Desired Behavior

All of the activity on node 2931 should be migrated over to 5438. We'll need to associate the runs of 2931 to 5438 as well.
#### Why This Matters

Because we shouldn't have two of the same campaign

**Comment by angaither** [comment]
@mikefantini which run should signups on `2931` be migrated to?

```
update signups 
where nid = 2931
set nid = 5438
and run_nid = X
```

**Comment by mikefantini** [comment]
@angaither I was thinking we would just keep the signups on the same run but just associate the runs with 5438 instead of 2931. Does that make sense?

**Comment by angaither** [comment]
:+1:

**Comment by mikefantini** [comment]
So 5438 would have 4 runs instead of 2

**Comment by angaither** [comment]
instead of doing the change in the db, then those campaign runs will need to be updated to point to `5438`

**Comment by mikefantini** [comment]
@angaither let's coordinate this then because I don't want 2931 to be unpublished and not closed. Should I just move those over now and create a placeholder run for 2931?

Also you still need to update the campaign nid for the signups no?

**Comment by namimody** [comment]
@mikefantini does it matter at all that this campaign is being reopened for a celeb partnership right now?

**Comment by chloealee** [comment]
@namimody @mikefantini should this be done before #6258?

**Comment by namimody** [comment]
I think #6258 makes sense to do first, great idea @chloealee!

**Comment by mikefantini** [comment]
@angaither let's chat about this one IRL to make sure we're on the same page on what needs to be done.
