### ISSUE TITLE
Change Campaign Template date to "X hours/days remaining"

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6242]
##### User Story

Users can become confused with dates that end on a specific day without time zone context. Chris brought us stories of users who thought they missed the Teens For Jeans deadline because it ended on Eastern time and they were thinking in terms of Pacific time.
##### Additional Information

We should emulate the now-defunct Hot Module and change how the date is displayed at certain time periods. For example, a campaign will end on April 31st and states "Ends April 31st". During the last week, the countdown says "Ends in X days". During the last day, it changes to "Ends in X hours". Extra credit: Can determine between singular and multiple numbers - "1 day" vs "3 days".

[IRL EXAMPLE](https://s3.amazonaws.com/f.cl.ly/items/2N1v1h3M1X073R2U0a1K/Screen%20Shot%202016-03-03%20at%201.40.53%20PM.png?v=250cdad1)
##### Why This Matters

Less confused users is better! Could decrease the amount of support tickets and maybe bring a little urgency in the absence of the hot module.
##### Current Workaround w/o Feature (if applicable)

Optimizely override to insert "Midnight EST" in the date box.

**Comment by angaither** [comment]
not a small.
