### ISSUE TITLE
Standardize API Markdown properties  

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6250]
#### Current Behavior
- Fields on a Campaign node can be saved as Markdown (and returned in API as an object with `raw` and `formatted` values) or as Plain Text (returned as just a string). 
#### Desired Behavior
- Always return API property of a text field as an object with `raw` and `formatted`, regardless if the format is Markdown or Plain Text
#### Why This Matters

Complicates building apps which consume the Campaigns API  
#### Relevant Screenshots + Links

https://www.dosomething.org/api/v1/campaigns/57 (per 3/8/16 - 9am PST)
![screen shot 2016-03-08 at 8 26 20 am](https://cloud.githubusercontent.com/assets/1236811/13609296/238969e2-e50d-11e5-819b-c3b34e5699fc.png)

Refs https://github.com/DoSomething/LetsDoThis-iOS/issues/930, https://github.com/DoSomething/phoenix/issues/5069#issuecomment-193846798

**Comment by aaronschachter** [comment]
This gets a little tricky for something like `tagline` or even `title`, where we'd never store the value as Markdown... it brings to mind just simply returning the `raw` value for all fields as a string instead an object vs knowing which properties are strings and which are objects.  If we went this route, it'd make sense for a v2 as it would break apps referencing the `raw` property (or make the change in v1 and fix LDT apps before launch). Thinking out loud (and not suggesting thats what should necessarily happen)

I'm curious to how other API's handle formatted text... cc @weerd

**Comment by chloealee** [comment]
@aaronschachter if we just returned the `raw` value for all fields as a string instead of an object, everything would read like `tagline` or `title` does, getting rid of `raw` and `formatted` entirely?

**Comment by DFurnes** [comment]
Yeah, I think returning either the unformatted text or the raw Markdown source is the way to go here. It also feels like returning the processed HTML is making an assumption that it'll be displayed in a web browser, which is not always the case.
