### ISSUE TITLE
Clicking view more on the report back gallery doesn't display more photos

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6257]
#### Current Behavior
- Clicking view more on the reportback gallery of campaign causes an endless spinner and no additional photos to appear. Note: there are more than 6 approved/promoted reportbacks.
#### Desired Behavior
- Clicking view more will display the additional promoted/approved reportback images according to previously logic.
#### Steps to Replicate
- Sign up for https://thor.dosomething.org/us/campaigns/guns-out
- Go to the gallery
- Click view more
- Witness that no additional photos load
#### Why This Matters

Users consistently call out seeing other people doing the action as a motivating factor for them to take the action themselves. Also looks like no one is doing our new spotlight campaign which isn't true.
#### Relevant Screenshots + Links

https://thor.dosomething.org/us/campaigns/guns-out

![image](https://cloud.githubusercontent.com/assets/6330971/13653373/59877828-e61f-11e5-872e-7bf591d96d4a.png)

![image](https://cloud.githubusercontent.com/assets/6330971/13653364/4a6ff496-e61f-11e5-8415-648a28a05eba.png)

cc: @angaither @weerd

**Comment by mikefantini** [comment]
According to @weerd:

"The only error I’m seeing being reported is this one.. a varnish related one. I don’t know enough about varnish to comment on it tho

![image](https://cloud.githubusercontent.com/assets/6330971/13653505/18571b46-e620-11e5-8855-7f30f9b55fe2.png)

The call that it makes does work: https://thor.dosomething.org/api/v1/reportback-items?campaigns=6690&status=promoted,approved&exclude=182991,180768,181273,183046,182989,182990&count=12 and it does save/grab items from cache

Did maybe the structure of the markup change? I know @chloealee had some question regarding theme wrappers or something related to them that came up in prior issue and those wrappers help establish a certain markup that is relied upon by the javascript code so it knows where to place the data… @chloealee do you remember if anything changed regarding those?"

**Comment by chloealee** [comment]
@mikefantini @weerd nothing has changed with any `theme_wrappers` yet but might potentially in the future - I'll let both of you know if/when they do!

**Comment by angaither** [comment]
console looks a bit angry @weerd @chloealee 
![image](https://cloud.githubusercontent.com/assets/645205/13676223/f4a60872-e6b2-11e5-97cf-c403d3fc7551.png)

**Comment by chloealee** [comment]
@angaither @DFurnes I'm not sure if this is related but I got an error in the logs saying `Notice: Trying to get property of non-object in ReportbackItem->build() (line 116 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php).`

When I `print_r($northstar_response);` [here](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php#L114) I get back `Unauthorized access.` 

Do you know why I might not have access even though I'm an admin?

**Comment by angaither** [comment]
@chloealee i don't think that's related.
check out Reportback.js
I think what's going on is the api response changed, and it's trying to grab something that has moved or no longer exists. 

try to `console.log(response);` in the `done` function of the request

![image](https://cloud.githubusercontent.com/assets/645205/13676223/f4a60872-e6b2-11e5-97cf-c403d3fc7551.png)

**Comment by angaither** [comment]
@chloealee also, when making front end changes, to see updates to the JS make sure to run `ds grunt --watch` and wait till the files compile.
it's the drush cc all of the fender world!

**Comment by chloealee** [comment]
ah awesome, thanks @angaither ! I think I just found it actually! I changed the API in #6223 to have `prev_uri` and `next_uri` be nested under `links`. Trying to add that structure in now and hopefully this will be the fix! Thanks for the hints to lead me here :)

**Comment by weerd** [comment]
@chloealee Ah! That makes total sense! Nice find :dancer:

**Comment by chloealee** [comment]
thanks @weerd !
