### ISSUE TITLE
Automation of Migrating Campaign Activity to Runs

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6258]
#### User Story

As a site admin, I'd like to be able to retroactively associate campaign sign ups and reportbacks with the correct run, without having to make an issue/bother a dev.
#### Additional Information (optional)

Refs: https://github.com/DoSomething/phoenix/issues/6237 and discussion here: https://dosomething.slack.com/archives/campaign-template/p1457449052000240
#### Why This Matters

Segmenting campaign activity by run is super important for assessing campaign health and data purposes. Because it's sometimes difficult to tell when we need a new run, we anticipate this being a need in the future.
#### Current Workaround w/o Feature (if applicable)

A dev needs to be manually migrate the data with a scary sql-update command. 

cc @mikefantini

**Comment by chloealee** [comment]
sounds like two things need to be updated: 
1. Automate signups and reportbacks to associate themselves with correct campaign run, depending on current time and campaign run dates. 
2. Add to user interface to be able to retroactively associate campaign signups and reportbacks with the correct run.

Is this right @namimody ?

**Comment by namimody** [comment]
BRILLIANCE IN BULLET POINTS.

Just one amendment @chloealee -- I think the association to a campaign run should be based on sign up time and reportback submission time vs. current time?

**Comment by chloealee** [comment]
ah yes, that's what I meant - thanks for clarifying @namimody !

**Comment by chloealee** [comment]
@weerd Looking at this [PR](https://github.com/DoSomething/phoenix/pull/6066), it seems like `dosomething_helpers_get_current_campaign_run_for_user()` already associates a new signup with the current campaign run upon building it. I believe when a new campaign run is created, it's also set to the campaign's current run, so [#1](https://github.com/DoSomething/phoenix/issues/6258) (at least for signups) is already done? 

cc @namimody

**Comment by chloealee** [comment]
oh, maybe it doesn't update the current run [upon creation of new run](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_campaign_run/dosomething_campaign_run.module#L337) after all! 

Now I see that current run gets set manually here: 
![screen shot 2016-04-13 at 1 26 51 pm](https://cloud.githubusercontent.com/assets/9019452/14502873/71654e30-017b-11e6-96a1-ab7a2b13e242.png)

So updated steps:
1. Automate current run to update based on each of the current runs dates. 
2. Add to user interface to be able to retroactively associate campaign signups and reportbacks with the correct run.

**Comment by angaither** [comment]
@chloealee this issue is about moving the signup and reportback activity to the run node, not about associating the run to the campaign node

**Comment by chloealee** [comment]
@angaither so is this editing the user interfaces [here](http://dev.dosomething.org:8888/us/signup/3298) and [here](http://dev.dosomething.org:8888/admin/reportback/3544) (or to create a new interface) to do something like make these pages editable, add `run nid` to both pages, be able to choose a new `run nid`, backend makes sure the run nid exists and is associated to the correct campaign, and save?

**Comment by angaither** [comment]
@chloealee you can use this as an opportunity to remove the `archive activity` form, since this is an unused feature. 
you can replace the form with this new migration feature

**Comment by chloealee** [comment]
@namimody do we want to be able to migrate activity from run to run (that belong to the same campaign) or also across campaigns (e.g. migrate Comeback Clothes run 1 activity to Thumb Wars run 1)?

**Comment by aaronschachter** [comment]
Question (and potential land mine?) -- Now that we've removed the unique key on `uid` and `nid`, for data queries based on Run -- couldn't we query by Reportback created date to determine what Run a reportback should associated with, instead using the Run nid value?

If we go this route -- the issue turns into making sure the Start/End dates are accurate for Campaign Runs (and refactoring data queries accordingly), vs whether the Run field is accurate for all signups and reportbacks and building out migrate webforms.

This is the approach I've been considering for v2 / Guardian.

**Comment by namimody** [comment]
@aaronschachter I don't know too much about how this works, but I guess I have a few initial questions: 
- From a data perspective, does this mean we would have to input the start and end dates of all runs instead of simply using the run ID? From a simplicity perspective, I feel like simply using the run ID is more simple?
- Every so often, we have to add a reportback manually for a member who has missed the deadline for any number of reasons. While this use case is definitely not the majority of reportbacks, if the "Created By" date is outside of the designated start/end dates, we could have a cohort of reportbacks floating around without an assigned run, which would be problematic, right?

**Comment by namimody** [comment]
@chloealee because of situations like the one detailed in #6237, I'm inclined to say that being able to migrate activity across campaigns would be a handy feature to have!

cc @angaither @mikefantini

**Comment by aaronschachter** [comment]
> From a data perspective, does this mean we would have to input the start and end dates of all runs instead of simply using the run ID?

We wouldn't be adding Run start/end dates to Reportbacks or Signups -- the suggestion is that for a given Signup/Reportback, to find out which Run it belongs to, we query for the Campaign Run that was open during the time submitted. If we go this approach, we longer need to store the Run on the Signup/Reportback at all. This helps to avoid scenarios where Signups and Reportbacks are created with incorrect Runs because of configuration errors -- like the convo [you linked to in Slack](https://dosomething.slack.com/archives/campaign-template/p1457449052000240) where it sounds like the Run was created a few days late, after Members had already submitted Signup/Reportbacks to the  now-previous Run.

This for sure would require some code changes and changes to any data aggregation pulls we do -- but I think it would simplify things in the long run and especially help us in migrating to v2. 

> Every so often, we have to add a reportback manually for a member who has missed the deadline for any number of reasons.. if the "Created By" date is outside of the designated start/end dates, we could have a cohort of reportbacks floating around without an assigned run, which would be problematic, right?

This could be solved by making the Created Date editable, so staff could set the Created Date to a date within the range to associate it to the desired Run.

> Because of situations like the one detailed in #6237, I'm inclined to say that being able to migrate activity across campaigns would be a handy feature to have!

My $0.02 is that it's a relatively dangerous feature to add because it opens up a new door to poke holes in our data integrity.  Misfires (users accidentally submitting the Migrate Campaign form, selecting incorrect Campaign) could go unnoticed, and could be quite difficult to troubleshoot if/when the mistakes were made long before we find them.

**Comment by chloealee** [comment]
Thanks @aaronschachter and @namimody ! All really great points and thanks for flagging! Chatted with @angaither this am at our check in and think it's best to move forward by being able to edit campaign run instead of edit dates - there are many reportbacks/signups that need to get migrated to a different run and currently, all runs do not have the correct timestamps and some are associated with the wrong node.

**Comment by aaronschachter** [comment]
I'm slightly concerned if our Runs don't have the correct timestamps that the migration forms may cause more incorrect data.

Just to clarify: the potential form we're talking about would bulk migrate all activity from one Run to a different Run -- not just a form for a single Signup/Reportback. Is that correct?

**Comment by chloealee** [comment]
@aaronschachter yes, this will bulk migrate all activity and not just a single signup/reportback! 

Per our sprint sync, we'll put a hold on this issue for now and revisit after this hackweek sprint and discuss further then!

**Comment by angaither** [comment]
going to close this one out for meow since we got the inbox down to zero, and leads aren't blocked anymore!

**Comment by namimody** [comment]
@angaither sorry  -- gonna have to reopen this. From what I understand, this issue is more about addressing problems like this:

Currently, the Elephant Tusk Force campaign has two translations. The US EN translation is set to run 2 (node 6810) with start and end dates during April of 2016. This translation is now closed.

The GL EN translation is set to run 1 (node 6556) which is translated, but both translations of the run have a start date in August of 2015, and no end date. Therefore, the campaign appears open to global users, allowing them to sign up and report back. If we would like to have this campaign open for GL EN members, we need to create a run 3, and set the GL EN translation to run 3. However, we now have data flowing to run 1 for the members that saw the GL EN translation of the campaign.

The best course of action would be to associate all activity from:

August 27, 2015 - March 31, 2016 with RUN 1 (node 6556)
April 1, 2016 - April 30, 2016 with RUN 2 (node 6810)
May 1, 2016 - present with RUN 3 (not created yet)

And detailed here: https://trello.com/c/Fr5S1cs1/1567-elephant-tusk-force-reportbacks-came-through-while-campaign-is-in-closed-state 

vs. problems of getting through a high volume of reportbacks (addressed by issue https://github.com/DoSomething/phoenix/issues/6392)

What's the best course of action here?

Campaign link for reference: https://www.dosomething.org/us/campaigns/elephant-tusk-force

**Comment by ngjo** [comment]
The GL EN translation of Dunk You Very Much (https://www.dosomething.org/node/6647/edit/en-global) didn't have a close date, but it was supposed to have been closed on April 1, 2016 to coincide with the US EN run. We just added the end date to close out this campaign.

We'll need to do a similar thing w/ the data here -- create a new Run (in GL EN) and attribute the activity received after April 2, 2016 to that new run. The run should have a start date of April 2, 2016 and no end date (we want to keep this GL EN translate campaign open indefinitely).

**Comment by namimody** [comment]
Because we are going to resolve this with a scary SQL update command instead of building an admin view, I'm creating a new issue for Elephant Tusk Force and Dunk You Very Much (https://github.com/DoSomething/phoenix/issues/6673) and closing this one.
