### ISSUE TITLE
API individual resources should return error code 404 when not found

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6261]
#### Current Behavior
- Requesting a non existing campaign from the `campaigns/:id` endpoint results in a 200 with an `error` object.
#### Desired Behavior
- A 404 response should be returned
#### Why This Matters

It's RESTful best practice :stars: and makes it easier to build apps with our API.  This is not critical for app launch as we have a [workaround for this in the iOS repo](https://github.com/DoSomething/LetsDoThis-iOS/blob/d8f8c406465caa13f8b1e4cdd2d883125307b960/Lets%20Do%20This/Networking/DSOAPI.m#L271), but would be nice to remove the hack post-v1.1.0
#### Relevant Screenshots + Links

Refs https://github.com/DoSomething/phoenix/issues/6163#issuecomment-195054295
![screen shot 2016-03-10 at 1 16 49 pm](https://cloud.githubusercontent.com/assets/1236811/13686918/275f8940-e6cd-11e5-92cf-17dc98da9b99.png)
_

**Comment by aaronschachter** [comment]
It'd be good to audit all of these individual resources -- finding the same behavior for the `reportbacks` endpoint in https://github.com/DoSomething/phoenix/issues/6266#issuecomment-196519104. This reportback in particular should indicate access denied  -- it [does exist](https://thor.dosomething.org/admin/reportback/60) -- its just flagged.

![screen shot 2016-03-14 at 2 13 19 pm](https://cloud.githubusercontent.com/assets/1236811/13760170/f01621f4-e9ee-11e5-8089-ec40923784e1.png)

**Comment by chloealee** [comment]
Re-opening to fix `/signups`. 

`/reportbacks` and `/reportback-items` `403` and `404` errors to be fixed in #6274

**Comment by angaither** [comment]
after the merge of #6276

DoSomething/northstar/issues/313 issue started to happen

**Comment by chloealee** [comment]
Chatted about this IRL with @angaither and @DFurnes. When debugging, we found that it was throwing a `404` status code but also returning the signup object because there was a signup but it couldn't find any kudos. 

In order to throw accurate response codes, @DFurnes suggested to add response codes at the transformer level.
