### ISSUE TITLE
Signups API - Join bug on Reportbacks?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6266]
#### Current Behavior
- Unsure if this is a bug in the JOIN in the Signups query, or if it's a data issue. Ran into this while testing mobile app with my DS account (user id 1176550)-- My reportback (ID 60) shows up in each of my 2 signups (id's 896000 and 44209): https://www.dosomething.org/api/v1/signups?user=1176550&campaigns=362

![screen shot 2016-03-12 at 11 12 21 am](https://cloud.githubusercontent.com/assets/1236811/13724728/58f23d32-e843-11e5-8d92-af1e525b3241.png)
#### Desired Behavior
- Each signup should have a unique Reportback ID, if it exists for that Signup's run.
#### Why This Matters

Funky profile in mobile app, see below.
#### Relevant Screenshots + Links

May be related to https://github.com/DoSomething/LetsDoThis-iOS/issues/956

![comebackclothes](https://cloud.githubusercontent.com/assets/1236811/13724752/fc672b6c-e843-11e5-88d0-8506a0a89f0d.gif)

**Comment by angaither** [comment]
@aaronschachter I think this is a problem with the join in the query, there's actually only one record for the reportback
![image](https://cloud.githubusercontent.com/assets/645205/13746877/de409630-e9cb-11e5-9e7b-9cd77fecdcd9.png)

**Comment by chloealee** [comment]
@angaither I think I fixed the query issue but still seeing the `Notice: Trying to get property of non-object` error in the logs for [this line](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php#L116) and [this line](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L167).

When using `print_r` to see what the `$northstar_response` is, it says `Unauthorized access.` I'm not sure why this would be though since I'm coming from an admin account?

**Comment by angaither** [comment]
@chloealee the lines above don't check that `$northstar_response->data` exists

**Comment by chloealee** [comment]
@angaither doesn't that get checked in the lines above before it enters that if block? 

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php#L115

https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L166

**Comment by chloealee** [comment]
ohhh i see what you mean! Just updated it.

**Comment by aaronschachter** [comment]
@chloealee -- Testing this on thor:
https://thor.dosomething.org/api/v1/signups?user=1176550&campaigns=362

I see 2 signups, but no reportback 60 - `reportback` is now NULL for both. Does RBID 60 have a valid run ID?

![screen shot 2016-03-14 at 1 01 59 pm](https://cloud.githubusercontent.com/assets/1236811/13758113/00d58282-e9e5-11e5-85af-e3aa1a2d3eeb.png)

**Comment by chloealee** [comment]
hmm @aaronschachter you're right - I'm seeing that too. Looks like it was `created_at` and `updated_at` a long time ago too so it should be the same data in thor and prod, right? 

```
created_at: "2014-03-18T07:32:49+00:00",
updated_at: "2015-01-12T20:33:19+00:00",
```

From @angaither 's screen shot it looks like there is a run ID (`2341`)?

**Comment by chloealee** [comment]
@aaronschachter actually, just tried to hit `https://thor.dosomething.org/api/v1/reportbacks/60` and it looks like that reportback doesn't exist on thor. That might be the issue here? 

@angaither is it okay to signup and reportback for a campaign on thor, then create a new campaign run and signup and reportback for that one to test? I know that thor is supposed to be as close to production as possible so just want to check before I do this!

**Comment by chloealee** [comment]
ah interesting I think I found something - signups aren't included in the `/signups` response if you've already reported back.

**Comment by aaronschachter** [comment]
That does sound interesting. Confirmed RB 60 exists by viewing my Thor web profile:  https://thor.dosomething.org/us/user/1176550 -> https://thor.dosomething.org/admin/reportback/60

**Comment by chloealee** [comment]
but wait - that's not consistent with what is showing up on your profile on thor because your signups are showing up if you've reported back but just the reportback isn't showing up, right? @aaronschachter

**Comment by aaronschachter** [comment]
Reportback 60 is flagged -- https://thor.dosomething.org/api/v1/reportbacks/60 is returning the "No reportback data" message. This is actually getting returned as a 200 with an `error` object, which isn't right (same issue as #6261) -- seems appropriate to throw an error code here (403?) with a message like "Access denied" for when we're denying access to view an individual Reportback. cc @DFurnes @weerd 

This may help explain why my user has the reportback set to NULL for those 2 signups.

![screen shot 2016-03-14 at 1 48 41 pm](https://cloud.githubusercontent.com/assets/1236811/13759730/c64598ac-e9ec-11e5-9235-7abc45b0ca6b.png)

**Comment by chloealee** [comment]
@aaronschachter ahh great find! I can update that now.

**Comment by aaronschachter** [comment]
I wasn't seeing a `reportback` returned in browser because I wasn't logged in as an admin. When I am, hitting https://thor.dosomething.org/api/v1/signups?user=1176550&campaigns=362 in browser contains a `reportback` for id 60 as we'd expect. Seems like we need to make this request as the authenticated user.... which I'm not sure will work yet by just passing the headers to the request on the app code side. I'll try on Thor and open a new issue if not. 

@DFurnes @weerd 

![screen shot 2016-03-14 at 4 03 57 pm](https://cloud.githubusercontent.com/assets/1236811/13762823/d9a2f590-e9fe-11e5-9143-a037fee6db15.png)

**Comment by chloealee** [comment]
@aaronschachter @angaither made the fix above that @aaronschachter caught. Should I make a PR for that and merge, then test on Thor to see if that clears up the issue?

**Comment by chloealee** [comment]
@aaronschachter @angaither ah didn't refresh and see the message above! Disregard the above unless I should still change the error code to a 404 above [line 96](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/Reportback.php#L96)?

**Comment by aaronschachter** [comment]
@chloealee -- We still need a 404 but technically thats a separate issue #6261 (which I opened to address all individual resources, not just the campaigns/:id)

**Comment by chloealee** [comment]
okay cool, thanks @aaronschachter ! I'll get on that :)

**Comment by aaronschachter** [comment]
For reportback ID 60 in particular we should throw an access forbidden error if the user doesn't have access (403 i think) and then 404 for when there is no reportback that exists. This isn't necessary for app launch -- its just general API improvements that we'll want to get to eventually if not now.

cc @weerd @DFurnes

**Comment by chloealee** [comment]
@aaronschachter that makes sense. Want me to create a separate issue for that one?

**Comment by DFurnes** [comment]
Yep, 403 for permissions issues & 404 for when no reportback exists. :+1:

**Comment by aaronschachter** [comment]
@chloealee Could re-open #6261 or create new issue, up to you. Technically the 403's are a different issue than the 404's in #6261. I'm not sure if there's a `reportback-items` individual resource, `reportback-items/:id`, but thatd be another endpoint this would apply to

**Comment by chloealee** [comment]
@aaronschachter sounds good! I'll re-open #6261 to fix `/signups` and then create another issue (#6274) for `/reportback-items` and `/reportbacks`
