### ISSUE TITLE
Elephant Task Force Redirect

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6270]
#### Request

dosomething.org/us/campaigns/elephant-task-force should redirect to dosomething.org/us/campaigns/elephant-tusk-force
#### Additional Information (optional)

The campaign's name was changed, but "task force" still lingers on search and could easily be searched for. /campaigns/elephant-task-force redirects, but the /us/ URL does not. 

![image](https://cloud.githubusercontent.com/assets/12396076/13780987/011453dc-ea98-11e5-9ac5-a99226283d10.png)
#### Why This Matters

"dosomething.org/us/campaigns/elephant-task-force" appears in Google search. When clicked, it brings the user to the dosomething.org/us/campaigns view. :(

**Comment by mshmsh5000** [comment]
Closed via Fastly redirect (Fastly v63).

**Comment by namimody** [comment]
Thanks so much @mshmsh5000! :elephant:

**Comment by mshmsh5000** [comment]
Just a note that Google has picked up the 301.

<img width="711" alt="task-tusk" src="https://cloud.githubusercontent.com/assets/149811/13953324/c241cb9c-f011-11e5-86e4-97f51117295e.png">
