### ISSUE TITLE
Use a mongo id to get to a user profile

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6275]
#### User Story

As an admin I should be able to view user profile in other apps and copy the link with the mongo id, and phoenix knows to take me to the user profile page
#### Additional Information (optional)

dosomething.org/user/[crazymongoid] shows user profile
#### Why This Matters

as we rely more on mongo ids, that should mean something in phoenix
#### Current Workaround w/o Feature (if applicable)

phoenix user id needs to be exposed in other apps, as well as the mongo id

**Comment by DFurnes** [comment]
Yes!! :+1:

**Comment by angaither** [comment]
Seeing a lot of errors when trying to get to users this way
