### ISSUE TITLE
URL Redirect for Four Legged Finisher

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6284]
Could dosomething.org/finisher redirect to https://www.dosomething.org/us/campaigns/four-legged-finisher (node 6692, currently unpublished)?

We'd need it set up by Tuesday, 3/22.

Thanks!!

**Comment by mshmsh5000** [comment]
Closed via Fastly redirect (Fastly v64).

**Comment by namimody** [comment]
Thanks for this too @mshmsh5000! :dog: :cat:

**Comment by namimody** [comment]
@mshmsh5000 sorry about this -- could we also have dosomething.org/finishers redirect to https://www.dosomething.org/us/campaigns/four-legged-finisher? Last minute change in campaign title -- apologies again!

**Comment by mshmsh5000** [comment]
@namimody The existing redirect rule actually catches that variation already:

http://dosomething.org/finishers

:beers: :cake:

**Comment by namimody** [comment]
@mshmsh5000 I'm _so_ sorry about this again -- but I just realized that since the title of the campaign actually changed to "Four Legged Finishers" the destination URL is actually: https://www.dosomething.org/us/campaigns/four-legged-finishers and so the redirects are currently routing to /campaigns. :no_smoking: :cat: :dog: :see_no_evil:

**Comment by namimody** [comment]
Documenting that this is all set!
