### ISSUE TITLE
Cron to migrate people in the failed task log

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6287]
#### User Story

As a user I want to be entered into a competition. 
#### Additional Information (optional)

When users don't get entered into the gladiator app, they are stored in the `dosomething_gladiator_failed_task_log`
We should have a check for that on each cron, and migrate users over who are still in that log.
#### Current Workaround w/o Feature (if applicable)

Manually make post requests from people who are in the log.

**Comment by itsjoekent** [comment]
@angaither from what I understand you already wrote the code for this (not the cron part, the POST request part)

**Comment by angaither** [comment]
@deadlybutter I didn't write anything special for people in the queue used the code that's already in the module.
