### ISSUE TITLE
Adding Member Age to Profile

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6291]
#### User Story

There are many occasions where a campaign lead needs a member's age for a wrap report, sponsor updates, the gala, conference, or social post. It would be great if member age could be part of their admin-facing profile.
#### Additional Information (optional)

This age will need to always consider the current date so it is not static.
#### Why This Matters

Will save campaign leads time.
#### Current Workaround w/o Feature (if applicable)

A campaign lead does this: 
1. Go to their profile: https://www.dosomething.org/us/user/2319718
2. Go to edit info: https://www.dosomething.org/us/user/2319718/info
3. Grab their date of birth. 
4. Go to someplace like this: http://www.myagecalculator.com/

How feasible is this @angaither?

**Comment by angaither** [comment]
trés fanc, v ok.

**Comment by namimody** [comment]
YAY @angaither! Is this a small / medium / large? Maybe we try for next sprint?

**Comment by chloealee** [comment]
@namimody @angaither when testing this, I found that the address validation seems to be triggered even though address isn't required. Wanted to flag for another bug/issue:
![screen shot 2016-03-24 at 3 11 45 pm](https://cloud.githubusercontent.com/assets/9019452/14028428/d8d36a38-f1d2-11e5-8f88-c84acd656665.png)

**Comment by chloealee** [comment]
Issue created: #6317
