### ISSUE TITLE
Optimize Optimizely Snippet

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6297]
#### Current Behavior

When Optimizely is running on a page, sometimes the original version of the page we are testing on flickers before showing the test version. This could mean that an entirely different hero image shows for a second, or that text we want to remove/amend shows briefly.
#### Desired Behavior

The test should load without looking glitchy.
#### Why This Matters

If we run a test, we want to ensure the results are a reaction to the test itself, not a glitchy experience.
#### Relevant Screenshots + Links

Optimizely troubleshooting guide: https://help.optimizely.com/hc/en-us/articles/200457495-Troubleshooting-Page-loads-slowly-or-flashes-original-appears-briefly-before-variation-?flash_digest=22a03a0034c94e96819dfdd9b1636bbd88907661

You can check out the glitch currently on: dosomething.org/us/campaigns/guns-out

**Comment by angaither** [comment]
@namimody not sure there's much we can do about this...

**Comment by DFurnes** [comment]
One thing we can do (which they mention on the support page you linked) is cut down the number of tests we have active at any given time. Our Optimizely snippet is 375kb (100kb gzipped) right now, which is probably one of the biggest reasons you're seeing lag. (For context, all of the other scripts we bundle with our site are only 97kb gzipped). :hourglass:

**Comment by DFurnes** [comment]
But, like @angaither said, there's always going to be _some_ lag since the changes are only happening locally on the user's computer once the Optimizely snippet fully loads and renders the A/B test. The best we can do is try to make that "flash" as brief as possible.

**Comment by namimody** [comment]
@DFurnes mind if I put 30 mins on for us next week for this?

**Comment by DFurnes** [comment]
Sure! 👍

**Comment by namimody** [comment]
Started at a snippet size of 107 KB, removed JQuery got it down to 84 KB, and then to 63 KB after we excluded paused + draft experiments from being included in the snippet.

@DFurnes for the win (per usual)!
