### ISSUE TITLE
Include api key in gladiator calls

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6300]
Add api key to gladiator settings form
and to all requests
DoSomething/gladiator/issues/69

**Comment by angaither** [comment]
add header
`X-DS-Gladiator-API-Key = [KEY]`

**Comment by weerd** [comment]
@joe Extra task!

Change the url query param for the `/contest` endpoint in the cron check from `run_nid` to `campaign_run_id` :dancer:

**Comment by itsjoekent** [comment]
Apparently it was already campaign_run_id. (OOPS)

```
      json_encode([
        'id' => $user->mail,
        'term' => 'email',
        'campaign_id' => $values['nid'],
        'campaign_run_id' => $values['run_nid'],
      ]),
```
