### ISSUE TITLE
Disable Northstar module after pulling DB from staging.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#6304]
## _FEATURE OVERVIEW_

Is this a feature? A bug? A bit of both? :bug: :dancer: 
#### User Story

When I pull the staging database to my local machine, it should disable the Northstar module so it doesn't continue syncing "dev" changes to Northstar QA.
#### Additional Information (optional)

…
#### Why This Matters

When all of our local environments are hooked up to a single Northstar QA instance, it's possible that we might accidentally pollute data being used by other people (e.g. if I changed a password on my local, it'd also get updated on Northstar QA for everyone else).
#### Current Workaround w/o Feature (if applicable)

Disable Phoenix's Northstar module, or set it to talk to a local instance.

**Comment by angaither** [comment]
we can add this to the list of drush command that are run [here](https://github.com/DoSomething/phoenix/blob/dev/bin/ds#L509)

**Comment by angaither** [comment]
I'm also okay with setting this to `dev.dosomething.org`
