### ISSUE TITLE
Non admin login is 404'ed

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6310]
#### Current Behavior

After a non-admin logs in, the user is 404'ed
#### Desired Behavior

user is taken to profile
#### Steps to Replicate

log in as a non-admin user, or create a new account and try to view your profile
#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/645205/13997904/a8da90ea-f10a-11e5-86d6-37ca4202e165.png)

**Comment by katiecrane** [comment]
pretty sure this is caused by messing with the access arguments with our menu_alter [here](https://github.com/DoSomething/phoenix/pull/6294/files#diff-ad30a5d569ca2ae6d2e04223aa501104R114)
