### ISSUE TITLE
Campaigns API index endpoint doesn't contain meta.pagination

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6314]
#### Current Behavior

**GET** `campaigns` doesn't contain a `meta` object, as the Signups and Reportbacks do. (introduced in #6223)
![screen shot 2016-03-23 at 4 35 06 pm](https://cloud.githubusercontent.com/assets/1236811/14004191/7a2a158a-f115-11e5-9102-7bbb7891b5da.png)
#### Desired Behavior

Consistent response per other endpoints:
![screen shot 2016-03-23 at 4 37 32 pm](https://cloud.githubusercontent.com/assets/1236811/14004215/942aaac6-f115-11e5-9886-f56c7bddb0fd.png)

Currently not using `pagination` object in iOS yet, not sure about Android -- @jonuy ?

**Comment by jonuy** [comment]
Yea, the Android implementation does use pagination on /campaigns. Making a change on that right now would break the screen with the list of campaigns by cause.

Two potential ways forward:
1. Make the change to update the API response right now before v1.1 gets published to the Play Store. I'll need to upload a new v1.1.1 or something apk, but this will avoid us causing users' apps to break if they don't choose to download an update.
2. Version the change and release it as part of an api v2.

**Comment by DFurnes** [comment]
I think I'd prefer to add a `meta.pagination` property to the response and keep the old root-level `pagination` and `retrieved_count` included for compatibility. Since it's not a public API, we can always just monitor usage of older app bundles and remove down the line without making a formal v2.
