### ISSUE TITLE
Need to filter out restricted reportbacks in index view

### ISSUE THREAD

**Issue by chloealee** [DoSomethingArchive/legacy-website#6319]
#### Current Behavior
- Currently, restricted reportbacks are not filtered out from the index view. 
- `/reportbacks?flagged=true` returns flagged RBs
#### Desired Behavior
- Depending on permissions, restricted reportbacks should be filtered out for anon users. 
- If only one reportback is found or `/reportbacks?flagged=true` is hit from an anon user account, status code should be 403 and `Access denied.` should be returned. 

**Question** Should this actually return an empty array, similar to the empty array that is returned when hitting `/reportback-items?status=flagged` from a non admin account?
#### Steps to Replicate
- Visit https://staging.dosomething.org/api/v1/reportbacks?flagged=true with an anon user account. 
- You'll see flagged RBs and a 200 status code. 
#### Why This Matters
- Only admins should be able to view flagged reportbacks.

**Comment by weerd** [comment]
Not actually sure if `/reportbacks?flagged=true` works anymore, or is supposed to work, post the changes made in #6293... :shrug:
