### ISSUE TITLE
Display User avatars and first name in admin Reviewer webform

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6323]
#### User Story

User uploads great reportback via mobile app, and we promote it. Unfortunately they've also created an account with inappropriate first name and avatar, which is displayed publicly in mobile app campaign gallery
#### Current Workaround w/o Feature (if applicable)

Browsing Reportback Items API in a separate tab with a JSON viewer plugin to find the avatar URL, and then clicking into it... for each reportback...

**Comment by chloealee** [comment]
@aaronschachter is it safe to close this re: [this convo](https://github.com/DoSomething/phoenix/issues/6327#issuecomment-208989724)?

**Comment by aaronschachter** [comment]
Sounds good @chloealee ! We'll resolve this issue in the new Reviewer app.
