### ISSUE TITLE
Add Link of Parent Campaign to Run

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6326]
#### User Story

If a campaign lead is editing a run, and then saves the run, they are brought to a page that looks like the one below. It's not helpful for them -- it doesn't show what the closed state will look like, nor does it give them any way to navigate to the page of the parent campaign. It would be great if either:

a) this page could have a link to the campaign and the campaign's closed state
b) this page could look like the published state of the run 
#### Additional Information (optional)

Right now, campaign leads who arrive at the page below are going to the Drupal search content view to find the link to the parent campaign node. :unamused: 
#### Why This Matters

There should be an easy way for them to navigate to the campaign page.
#### Relevant Screenshots and Links

https://thor.dosomething.org/us/node/6556
https://www.dosomething.org/us/node/5411/closed

![image](https://cloud.githubusercontent.com/assets/12396076/14079538/8eebc5b2-f4cc-11e5-996b-76cf1b718885.png)

**Comment by chloealee** [comment]
@angaither where is https://thor.dosomething.org/us/node/6556 located in the code? I was expecting something like `node--campaign.tpl.php` but can't find the same for `campaign_run`.

**Comment by angaither** [comment]
@chloealee there might not be a template for this node since we didn't customize the view.
you would have to create a tpl following the same pattern that exists for `node--campagn.tpl.php` to get a link to the campaign to show up

**Comment by chloealee** [comment]
@angaither ah got it - thanks!!

**Comment by chloealee** [comment]
@namimody would you rather it just redirect back to the campaign page (https://www.dosomething.org/us/node/5411/closed) or look the same as the screen shot above with two new links?

**Comment by angaither** [comment]
@chloealee let's just make the campaign title link to the campaign. 
since when you make a run when you open campaigns now, not to close them

**Comment by chloealee** [comment]
@angaither cool sounds good!

**Comment by namimody** [comment]
Hi @angaither and @chloealee! Apologies I was OOO for this convo. The link to the campaign page is GREAT (can't wait to show leads this at tech/campaigns sycn tomorrow) but I do think we need a link to the closed view of the campaign as well. Runs are created for opening a campaign, and run content is populated for closing a campaign, so there should be an easy way to access the closed state as well. 

Thoughts?

**Comment by chloealee** [comment]
@namimody sounds good to me! Not as familiar with the campaign flow as I should be. When a campaign lead closes the campaign run, does the information added for the closed state populate `/node/:campaign_id/closed` (should this url pattern be the link to the closed view of the campaign?)?

**Comment by namimody** [comment]
Thanks @chloealee! The closed state can be viewed here:

https://www.dosomething.org/**translationabbreviation**/node/**NID**/closed

@angaither does that sound good to you?

**Comment by angaither** [comment]
@namimody does what sound great? adding a link to the closed state? SURE! 
do you want it to show up always, or only when the run is closed?

**Comment by namimody** [comment]
Woo! And I'd like it to show up always @angaither! Campaign leads often populate closed states before the run officially closes :)

**Comment by chloealee** [comment]
@namimody all set! Added with #6354.

**Comment by chloealee** [comment]
@namimody shoot I didn't refresh to see that you opened this otherwise I would have said "Fixes" in my PR instead of "Refs"! Closing this with the merge from #6354.
