### ISSUE TITLE
Add campaign run to signups/reportback params

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6328]
#### User Story

As an external service I want to grab activity for a particular campaign & a particular run only
#### Additional Information (optional)

currently we can look for at a signup endpoint for a particular campaign, but old runs might be included in this  `https://www.dosomething.org/api/v1/signups?campaigns=6661&competition=true`
we need to add `run=id` to the url 
#### Why This Matters

As we bulid out competitions, future users might signup on a campaign that has had multiple runs and the data will be confusing

**Comment by chloealee** [comment]
@angaither should we be able to grab multiple runs at a time? If so, I'll make the param plural (to `runs`).

**Comment by chloealee** [comment]
@angaither to clarify - do you also want the `runs` param to be added to the `/reportbacks` endpoint? Not sure if that's what you mean in the title of this issue so want to double check before I submit the PR!

**Comment by angaither** [comment]
@chloealee signups and reportbacks

**Comment by chloealee** [comment]
cool, thanks @angaither ! I don't think `/reportbacks` has the `campaigns` param like `/signsup` do - should I add that too or just the `runs` param?

**Comment by angaither** [comment]
I thought [campaign](https://github.com/DoSomething/phoenix/wiki/API#optional-query-parameters-3) was an optional param on reportbacks?

**Comment by chloealee** [comment]
Reopening this issue - #6359 broke some things in Thor.
