### ISSUE TITLE
Forge 6.7 Modal markup changes

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6347]
#### Current Behavior

Forge 6.7 messes up the post-signup modals. Competition, school picker and sign-up reason modals are affected.
#### Desired Behavior

It should look pretty and organized. Adding a `-emphasized` flag to the heading provides a fix, but we also need to resize/remove the upper right skip button.

We should also change the markup for the facts modal to use the emphasized style for consistency. 
#### Why This Matters

Launch blocker for Forge 6.7 
#### Relevant Screenshots + Links

![screen shot 2016-04-05 at 2 07 51 pm](https://butt.githubusercontent.com/assets/1865372/14293112/1f0a94f8-fb39-11e5-8da9-5222e9f35e12.png)
![screen shot 2016-04-05 at 3 11 54 pm](https://cloud.githubusercontent.com/assets/1865372/14294798/c31ba1c0-fb40-11e5-8ab6-ba74cf09f890.png)

**Comment by DFurnes** [comment]
Just noting here that this is specifically an issue on the unmerged #6334 PR.

**Comment by DFurnes** [comment]
Closing, as this is fixed in #6334 now.
