### ISSUE TITLE
Forge 6.7 Inverse Banner Markup

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6351]
#### Current Behavior

Only for Forge 6.7! No margins or padding between the banner and the next `<h>` element
#### Desired Behavior

Should be consistent with the other campaign template sections
#### Steps to Replicate

Only seems to appear on SMS campaign Step 2.
#### Relevant Screenshots + Links

![screen shot 2016-04-05 at 4 07 15 pm](https://cloud.githubusercontent.com/assets/1865372/14296603/dea85480-fb48-11e5-9d99-86c2e2daf80b.png)

**Comment by DFurnes** [comment]
Closing, since this was fixed in #6334.
