### ISSUE TITLE
Runs param on /reportbacks breaks with pagination and returning correct data

### ISSUE THREAD

**Issue by chloealee** [DoSomethingArchive/legacy-website#6372]
#### Current Behavior
- When using the `runs` param with `/reportbacks`, each page returns same exact reportback objects. This breaks because only values for one campaign run id are returned if you pass multiple ids in the `run` param e.g. `https://www.dosomething.org/api/v1/reportbacks?campaigns=1508&runs=5654,3182`
  ![screen shot 2016-04-13 at 3 11 59 pm](https://cloud.githubusercontent.com/assets/9019452/14506134/55415c08-018a-11e6-8085-b232806f7de5.png)
  ![screen shot 2016-04-13 at 3 14 02 pm](https://cloud.githubusercontent.com/assets/9019452/14506143/61706686-018a-11e6-8f6d-c56a2863d1c9.png)
- Correct data is not returned - the below returns no reportbacks when there are in fact reportbacks in the database.
  ![screen shot 2016-04-13 at 3 18 30 pm](https://cloud.githubusercontent.com/assets/9019452/14506302/0e3610fa-018b-11e6-8f87-7ca31e1e35f3.png)
  ![screen shot 2016-04-13 at 3 19 30 pm](https://cloud.githubusercontent.com/assets/9019452/14506380/7c9ae566-018b-11e6-85c6-a296e0f81adf.png)
#### Desired Behavior
- Pagination should return different reportback objects on each page. 
- Data should be returned if it exists in the database. 
#### Steps to Replicate
- Hit URLs in screenshots. 
- Make sure that your Language Settings in your user profile are set to English (not English, Global).
#### Why This Matters
- Currently, incorrect data is being returned when using the `runs` param.
#### Countries Affected (optional)
- It seems like `/reportbacks?campaigns=362` (or any campaign nid) + params only gets returned if your language is set to English. Is this okay @aaronschachter ?

**Comment by chloealee** [comment]
cc @angaither @weerd @sbsmith86 @deadlybutter too as an FYI for gladiator work - is this blocking anyone significantly?

**Comment by weerd** [comment]
@chloealee I don't think so at the moment... I think we're only really using the `/signups` endpoint, but if this also affects that endpoint then maybe?

**Comment by itsjoekent** [comment]
well we are still facing a bug in gladiator regarding the runs / signup thing, but i dont believe it has anything to do with this phoenix

**Comment by chloealee** [comment]
ahh shoot @weerd I missed this and looks like it actually is messing up in the same way on `/signups`. I'll create another issue and hop on that now since it seems like a blocker!

New issue for `/signups` endpoint and pagination - #6373

**Comment by chloealee** [comment]
Closing this issue - looks like `campaigns` param is broken for `/reportbacks` which is causing second problem. `runs` param works correctly. New issue [here](https://github.com/DoSomething/phoenix/issues/6404).
