### ISSUE TITLE
Remove Find a Campaign button on mobile homepage

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6375]
It doesn't functionally do anything since we results update as soon as you select them...

cc: @DFurnes

**Comment by mikefantini** [comment]
![image](https://cloud.githubusercontent.com/assets/6330971/14790344/d78290b2-0ade-11e6-9345-726251d92e65.png)

**Comment by angaither** [comment]
refs #1891

**Comment by weerd** [comment]
We should probs keep the button if JS fails for whatever reason. Can probably do some logic and remove the button if JS is working fine, otherwise keep it because then form works like a simple dropdown select of choices and then you need to click button to submit. cc: @DFurnes thoughts?

**Comment by DFurnes** [comment]
@weerd Unfortunately the query for the campaign finder is built [on the client-side](https://github.com/DoSomething/phoenix/blob/dev/lib/themes/dosomething/paraneue_dosomething/js/finder/SolrAdapter.js) so there isn't an easy fallback. I know there were some informal discussions a long time back about making a "search" service that'd act as an intermediary between Solr and the client-side app but I don't think it's been prioritized.

**Comment by weerd** [comment]
Oh crap yeah, forgot that detail. Okie doke! Been so long since I've touched the campaign finder, haha! Thanks for the reminder @DFurnes 💃
