### ISSUE TITLE
Absolute width of yellow underlines exceeds the container width on iPhone 5 sized devices

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6376]
![slack for ios upload](https://cloud.githubusercontent.com/assets/1865372/14567424/012615b8-0302-11e6-904e-e7fd945d7be8.jpg)

**Comment by DFurnes** [comment]
This was fixed in [Forge 6.7.1](https://github.com/DoSomething/forge/releases/tag/v6.7.1) and will show up on our next deploy. 🔜
