### ISSUE TITLE
If partner term translation does not exist hide "In partnership with"

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6379]
#### Current Behavior
- Not showing who the partner is for the Elephant Tusk Force campaign. 
#### Desired Behavior
- Partner name should be displayed. 
#### Steps to Replicate
- 1. While signed in, navigate to https://www.dosomething.org/node/5411
- 2. Scroll all the way down
#### Why This Matters
- Partners should be displayed if they are present. If not, the line should be hidden.
#### Relevant Screenshots + Links

<img width="1022" alt="screen shot 2016-04-16 at 3 38 18 am" src="https://cloud.githubusercontent.com/assets/14931921/14573084/58dceb78-0385-11e6-95fe-81b66c6dddb0.png">

**Comment by mikefantini** [comment]
This was resolved by adding a translation for the partner term.

Changing the title of this issue to hide "In partnership with" if partner term is not translated into the language the campaign is in.
