### ISSUE TITLE
Task: Patch international branch with security updates

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#6384]
## _Patch international branch with security updates_

Current [International branch](https://github.com/DoSomething/phoenix/tree/7e32c6bb143bf3abb8f122fa3847ee13872b9d64) is outdated.
- [ ] Make a list of updates to include
- [ ] Patch the branch
- [ ] Test the branch
- [ ] Deploy to prodtucion

cc @sheyd @mikefantini @angaither

**Comment by angaither** [comment]
@sergii-tkachenko I believe this is a duplicate of #6331

**Comment by sergiitk** [comment]
Hm, #6331i is Indonesia specific. The change will affect all international sites. Should we keep both tasks or close one?

**Comment by angaither** [comment]
@sergii-tkachenko it's up to you. the ask for updates came from indoenisa, but if you prefer this issue, that's fine, but I don't think we need both

**Comment by sergiitk** [comment]
Closed as a duplicate of #6331.
