### ISSUE TITLE
Posting Reportback to API does not store source

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#6385]
#### Current Behavior
- Neither the `dosomething_reportback` or `dosomething_reportback_file` tables contain a source column, which means we're not tracking the platform a Reportback is submitted for -- even though we're sending a `source` value when posting from the [mobile app](https://github.com/DoSomething/LetsDoThis-iOS/blob/6448d07491cb7ca42c597f9af9b85b3353518953/Lets%20Do%20This/Networking/DSOAPI.m#L210). 

The [`campaigns/:id/reportback` endpoint](https://github.com/DoSomething/phoenix/blob/18f5e064e135cdc70d5b1bf0df60091c37fb8a50/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L131) calls [`dosomething_reportback_save`](https://github.com/DoSomething/phoenix/blob/18f5e064e135cdc70d5b1bf0df60091c37fb8a50/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L352), which calls [`dosomething_reportback_set_properties`](https://github.com/DoSomething/phoenix/blob/b2706b012d415a2d94796bb6df776da538dcd2e4/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L731), which [doesn't check for a `source`](https://github.com/DoSomething/phoenix/blob/b2706b012d415a2d94796bb6df776da538dcd2e4/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L767)  -- it wouldn't have a column to set it to.. unless we hijack the `dosomething_reportback_files.review_source` column. That feels quite 😷  but a little less than work than creating a new column -- plus would it go on the Reportback or the Reportback Files table?
#### Desired Behavior
- Store the posted Reportback `source`, either in DS Reportback or DS Reportback Files
#### Why This Matters

Don't have a clean (or any?) way to tell if a Reportback was submitted via mobile app, web, or SMS. I think the hack we used (and likely still use?) is checking the IP in `remote_addr` for a Mobile Commons IP (cc @jonuy )

**Comment by angaither** [comment]
I was just talking to @Bladt about this yesterday!

**Comment by lkpttn** [comment]
I talked to @Bladt about this just a couple hours ago! Being able to tell if RBs are coming from the mobile apps is a key data point that has lots of juicy implications. Also useful to formalize the SMS procedure and future-proof for other platforms.

**Comment by aaronschachter** [comment]
One hack that seems a little smaller 👕  than adding a new column(s) to the DS Reportback table is to store the newly created Reportback ID in Northstar, at least to associate the `source` for both `letsdothis_ios` and `mobileapp_android`

https://github.com/DoSomething/northstar/blob/4a14440a3ca257c7e999fb750745a8478a3a5cfe/app/Services/Phoenix.php#L310

**Comment by DFurnes** [comment]
Since these requests are being proxied through Northstar, we could likely filter `remote_addr` by Northstar's IP. We could also (with potentially less fidelity) use the StatHat stat [for that route](https://www.stathat.com/v/stats/MZO3).
