### ISSUE TITLE
Missing CSS modifier on the profile containers

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6387]
#### Oh behave

The middle section on the profile is missing the `-padding` modifier on it's container
#### Relevant Screenshots + Links

![screen shot 2016-04-20 at 2 33 24 pm](https://cloud.githubusercontent.com/assets/1865372/14687265/99205ca0-070a-11e6-9ed2-38ef561c10d0.png)

**Comment by DFurnes** [comment]
This is fixed now on staging & production!
