### ISSUE TITLE
Feature flag for "Do not include this campaign in the mobile app"

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6388]
#### User Story

We only display the problem and solution fields in the mobile app so there are some[ campaigns that you can't complete](https://docs.google.com/document/d/1M6OZbu45B-dKGWtjKRBffdEFDpAE6G08Dw_9mu0t_ig/edit) due to a lack of information or the inability to download PDFs and templates. This is not only confusing for users, but limits the actions we can feature in the app.
#### Additional Information (optional)

We used to have a "Show in mobile app" flag that we used when we were only showing 12 campaigns a month. That code may have some pieces that are useful for this issue.
#### Why This Matters

We want to offer every campaign in the app, but until we can prioritize those features in the app builds we should prevent users from accidentally stumbling into these campaigns. 
#### Current Workaround w/o Feature (if applicable)

We're not pushing people to the campaigns from the news feed, but users can still wander into them.

**Comment by angaither** [comment]
we actually deleted those mobile app fields with #6241
If we are eventually going to prioritize adding features to be able to view the PDFs attached in the web, maybe there's a different way we can handle this rather than recreating a mobile app check box?

cc @aaronschachter

**Comment by aaronschachter** [comment]
👍  @angaither -- My vote would be to expose the attachment URL's in the Campaigns API and make app code changes to download attachments if they exist, vs worrying about hiding campaigns from the Actions tab based on copy...

**Comment by angaither** [comment]
@aaronschachter @lkpttn which fields do we need to expose? only downloads? or action guide as well?

**Comment by aaronschachter** [comment]
Might want to run this by @mikefantini or Campaigns team, but based on wiki it looks like Downloads is the field to expose: https://github.com/DoSomething/product/wiki/Campaign-Template:-Edit-Tab#action-guide
Action Guide is a node type.

**Comment by angaither** [comment]
yeah, but it looks like quite a few with action guides are excluded [in this list](https://docs.google.com/document/d/1M6OZbu45B-dKGWtjKRBffdEFDpAE6G08Dw_9mu0t_ig/edit) that @lkpttn provided

**Comment by lkpttn** [comment]
I've started putting together a doc that goes over our options so we can see what lines up best, effort/reward wise. 

https://docs.google.com/document/d/1H3wYTDCWdvpjlLVxaIeiQ-tu6X_In50-zm4mybV4_F4/edit

**Comment by lkpttn** [comment]
This issue has been moved into two separate issues,

#6412 for action guides
#6413 for downloads
