### ISSUE TITLE
Should Fact Pages Rank Above Campaigns in Solr?

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6390]
Perhaps more of a discussion, @mikefantini?

![image](https://cloud.githubusercontent.com/assets/12396076/14756498/c832e89c-08b7-11e6-8d43-b36152db96e9.png)

**Comment by angaither** [comment]
I guess we will never know.

**Comment by mikefantini** [comment]
Oh god. Sorry. When we tried to boost campaigns previously we were getting very funky results, so we took boosts off for search.
