### ISSUE TITLE
Unpublishing Translations Results in Error Page

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6391]
#### Current Behavior

Noticed that two campaigns on production should not be published. Tried to unpublish, was confronted with error and unpublishing didn't save.
#### Desired Behavior

Unpublishing a translation should result in translation no longer being published.
#### Steps to Replicate
- go to a translated campaign with different translation published
- try to unpublish a translation, and save
#### Why This Matters

Some translations should not be published. Publishing translations seems to work fine.
#### Countries Affected (optional)

All
#### Relevant Screenshots + Links

URL of error page: https://www.dosomething.org/node/40/edit/en-global

![image](https://cloud.githubusercontent.com/assets/12396076/14756540/0e60e594-08b8-11e6-8467-278b5d2d5171.png)

**Comment by angaither** [comment]
the full error from thor

```
Notice: Undefined index: token type in flag_token_info() (line 88 of /var/www/www.dosomething.org/releases/20160420133630/html/profiles/dosomething/modules/contrib/flag/flag.tokens.inc).
EntityMetadataWrapperException: Unknown data property field_run_date. in EntityStructureWrapper->getPropertyInfo() (line 335 of /var/www/www.dosomething.org/releases/20160420133630/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).
```

**Comment by angaither** [comment]
@namimody seems like the error is happening because there's no run for global english

**Comment by namimody** [comment]
@angaither you're brilliant, this worked! all good now. closing!
