### ISSUE TITLE
Batch Exclude Reportbacks to Clear Campaign Inboxes

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6392]
#### User Story

As a campaign lead, I want all fids on the nodes listed below with a quantity under _x_ to be marked as excluded before Thursday of this week.
#### Additional Information (optional)

Campaign (Node ID) // Threshold for Exclusion // Runs Affected
# SuperStressFace (2710) //  threshold: 10 // Run: 3110, 6660, 6470

Notes from Shawn (2805) // threshold: 250 // Run: 3494, 5828
Shower Songs (3590) //  threshold: 100 // Run: 5278, 6511
Trash Scavenger Hunt (2929) // threshold: 200 // Run: 3111
#### Why This Matters

The campaigns team doesn't have the bandwidth to clear out these inboxes. The most pressing concern is that Shower Songs is reopening in May and the inbox needs to be cleared before it launches again -- currently there are approx. 11,800 images that need to be reviewed.
#### Order of Operations
- [x] Nami provides impact threshold for four campaigns + verifies with campaign leads
- [x] Chloe writes code
- [x] Chloe and Nami test code on Thor
- [x] Ask Sena to backup production
- [x] Deploy to production and confirm!

cc @angaither @mikefantini

**Comment by angaither** [comment]
@chloealee this should be a php script or custom drush command, instead of an update hook so we can pass in params (nid, run_nid, and quantity) to know which rbs we want to bulk exclude and run it X times (instead of having one update hook per campaign)

**Comment by chloealee** [comment]
thanks @angaither, makes sense! I'm following a [tutorial](https://www.mikestiv.com/blog/drush-commands-and-hooks) right now to create a custom drush command - does it make sense to put this custom drush command in [`dosomething_reportback.drush.inc`](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.drush.inc) or to create a new drush command file separate for the job of batch excluding?

**Comment by angaither** [comment]
@chloealee you can put it in the existing file

**Comment by chloealee** [comment]
@angaither quick q! If I put this in `dosomething_reportback.drush.inc`, would I have to implement a new `hook_drush_command` that describes my new custom command (with arguments) in order to run it?

**Comment by angaither** [comment]
@chloealee no, you can add it to the array that's returned [here](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.drush.inc#L7)

**Comment by chloealee** [comment]
oh cool, thanks @angaither !
