### ISSUE TITLE
Expose sponsor info in campaigns endpoint

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6393]
# _FEATURE OVERVIEW_

---
#### User Story

As an api consumer, I should know which campaigns are sponsored, to give love on the app. 
#### Additional Information (optional)

"sponsor & partner display"

```
affiliates: {
  partners: [
    {
      name: "H&M",
      sponsor: true,
      media: {
        uri: https://www.dosomething.org/sites/default/files/styles/wmax-423px/public/partners/HM-1.png?itok=N8vhbM3I,
        type: "image"
      },
      uri:  http://hm.com
    }
 ]
}
```

"partner display"

```
affiliates: {
  partners: [
    {
      name: "H&M",
      sponsor: false,
      media: {
        uri: null,
        type: null
      },
      uri:  http://hm.com
    }
  ]
}
```
#### Why This Matters

they pay us, their logo/name should be exposed. 
### Example

adding a bool value https://github.com/DoSomething/phoenix/pull/6208/files
### Sample nodes

Staging:
- 362
- 1334

Thor:
- 362
- 1508
- 5775

Prod:
- 362
- 6692

**Comment by aaronschachter** [comment]
@angaither @weerd what does the `affiliates` object look like with multiple partners?  does it make sense to build as an array vs an object?

**Comment by weerd** [comment]
Oh crap. @aaronschachter good call. That's actually what I meant 😬 Updating!

**Comment by weerd** [comment]
Actually, wait... debating...

**Comment by aaronschachter** [comment]
@mikefantini @angaither Would you mind adding some node nid's to this issue for testing against prod / thor?

**Comment by weerd** [comment]
@aaronschachter maybe something like this? `partners` is a property on the `affiliates` object, and it contains an array of partners. If there are other "types" of affiliates, we just add them to the `affiliates` object similar to the `partners` property?

_NOTE_: I updated the description code example above!

**Comment by aaronschachter** [comment]
@weerd Makes sense.. `sponsors` sound like a potentially another type.. vs using the `sponsor` boolean on a `partner` object. 

I don't remember the history behind decision of a `sponsor` boolean on the Partners field collections vs a separate Sponsor field collection -- but likely having less Field Collections had something to do with it. In this case I could see having separate `sponsors` and `partners` properties though? cc @mikefantini @angaither

**Comment by weerd** [comment]
Yeah, I was chatting with @angaither about it and originally proposed it as 2 different properties, but then she showed me it's a boolean in the admin, so seemed to make more sense as being the same thing but with an additional flag. Not sure though... I could see if being separate too; would help avoid the empty `media` object when it's just a partner. Thoughts? Nice thing is w/ the API response we can do whatever we want... we don't have to follow what is laid out in the Drupal Admin interface 💃

**Comment by aaronschachter** [comment]
Definitely!   Re:

> I could see if being separate too; would help avoid the empty media object when it's just a partner.

The media object is defined on the Partner taxonomy term, not with the Campaign's `field_partners` -- called "Sponsors and Partners" in the Campaign edit form (so technically we could still have a valid media object when it's just a partner).  

As I'm reviewing both the Partners field collection and the Partners taxonomy vocabulary (which would perhaps help to rename as Affiliates to align with the proposed API property), I'm remembering that the `field_partners` field collection does allow us to specify the sort of Partners -- which will be important for if/when we need to display 2 sponsors in the mobile app (refs https://github.com/DoSomething/LetsDoThis-iOS/issues/991) -- so agree w @angaither  it makes sense to keep `partners` as an array with a `sponsor` boolean.. Separating into 2 separate properties could potentially be more confusing if that's not how we collect the data... ?

**Comment by mikefantini** [comment]
@aaronschachter @angaither @weerd added some sample nodes for thor and prod for testing.

**Comment by aaronschachter** [comment]
@weerd I can give this one a shot, but need some guidance on how the DS API Transformer code should work. So far looks like we need the following to implement -- with some questions:
- Add the Campaign's `field_partners` field collection data into the Campaign [`build`](https://github.com/DoSomething/phoenix/blob/18f5e064e135cdc70d5b1bf0df60091c37fb8a50/lib/modules/dosomething/dosomething_campaign/includes/Campaign.php#L134) function in `dosomething_campaign/includes/Campaign.php`. 
  - Needs new `getAffiliates()` or `getPartners()` method to traverse the `field_partners` data. 
  - New `getPartner` method for the Partner vocabulary (Don't think we'd want to use `getTaxonomyTerm()` as our Partner vocabulary has extra fields -- per next question) 
  - New DS API Transformer function to expose the Partner's `field_partner_logo`? It's a File field -- so it doesn't seem like we can use [`transformMedia`](https://github.com/DoSomething/phoenix/blob/18f5e064e135cdc70d5b1bf0df60091c37fb8a50/lib/modules/dosomething/dosomething_api/includes/Transformer.php#L299), which is translating our DS Image content type fields
- Add the relevant `affiliates` object in the DS API > includes > [`transformCampaign`](https://github.com/DoSomething/phoenix/blob/728b9b8184f69fcd55df1d7f701d3cac4bba881c/lib/modules/dosomething/dosomething_api/includes/Transformer.php#L191) ... but get confused here between  differences in the `build` function and our `transform`

**Comment by weerd** [comment]
@aaronschachter I'm trying to see if it's something I can punch out quickly. I'll let you know soon :)
