### ISSUE TITLE
/campaigns Page Not Displaying Properly for BR and MX experience

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6394]
#### Current Behavior

The /campaigns page on BR and MX are presenting campaigns in English. When clicked, some campaigns 404, some campaigns go to the BR or MX translation (clicking on an English icon on /campaigns goes to a Portuguese pitch page, for example), and in some cases the URL changes but the /campaigns page simply refreshes.
#### Desired Behavior

Taking MX as an example: 
The /campaigns page should show campaigns that are translated into Spanish and GL EN. Campaigns translated into Spanish should appear in Spanish on /campaigns. Campaigns translated into GL EN should appear in English on /campaigns.

No campaigns should 404 when clicked. All campaigns should bring users to the campaign pitch page of the campaign when clicked. Destination URLs should all be of published translations/campaigns.
#### Steps to Replicate

Go to https://www.dosomething.org/mx/campaigns or https://www.dosomething.org/br/campaigns and look at the campaigns listed. It _seems_ that:
- all campaigns are appearing in English, regardless if they are translated or not
- When clicked, campaigns that are only in GL EN and US EN end up in a loop and while the URL changes in the top bar, the /campaigns page reloads. The URL looks incorrect -- showing /campaigns/ vs. /voluntario/ (From /campaigns: https://www.dosomething.org/br/campaigns/visionary-volunteer?source=campaigns, From the homepage: https://www.dosomething.org/br/voluntario/atualize-seu-status)
- Campaigns are all being presented in English on /campaigns. however, when clicked, campaigns that are translated in BR PR or MX SP go to translated pitch page. (This campaign, Staring with the Stars, is appearing in English on /mx/campaigns, but when clicked it takes you to: https://www.dosomething.org/mx/voluntario/mirando-con-las-estrellas?source=campaigns)
- Additionally, some unpublished translations are present on /campaigns, and are 404ing when clicked (Bookmark Climate Change -- https://www.dosomething.org/mx/voluntario/marca-el-cambio-climático?source=campaigns -- , Not Stuck in Traffick, Repoppin, etc)
- The one exception is Don't Be A Sucker. It is translated and the translations are published, but clicking on it brings you to /campaigns. Given the above pattern, one would expect to be brought to the translated pitch page. https://www.dosomething.org/us/node/46/translate
#### Why This Matters

It's a bizarre user experience to see only English campaigns on the BR and MX site, and we aren't showing people all the campaigns they can do. Additionally, people should be able to access the campaign they are looking for through /campaigns. Site users have no other way to access the campaign.
#### Countries Affected (optional)

BR and MX. Does not appear to be a problem on GL EN.
#### Relevant Screenshots + Links

Refs: https://github.com/DoSomething/phoenix/issues/6389, https://github.com/DoSomething/phoenix/issues/6289 -- also worth noting that closed campaigns are appearing in the finder and US /campaigns, unsure if the issues are related: https://github.com/DoSomething/phoenix/issues/6374

cc @angaither @mikefantini @mnelson338

**Comment by sergiitk** [comment]
Just to clarify —Explore Campaigns page is rendered by Solr.

Here's what I dug up on this issue:
1)

> in some cases the URL changes but the /campaigns page simply refreshes

This happens for campaigns that are not available within given country. For such pages 404 should be displayed. This happens because `explore_campaigns` view accepts all incorrect urls by a wildcard `/campaigns/*`. Example: https://www.dosomething.org/campaigns/sdfsdf

**Comment by sergiitk** [comment]
2) Logic responsible for filtering campaigns by language appears incorrect. It [factors in](https://github.com/DoSomething/phoenix/blob/696a915ade1e7a25f4dcb216cad3b609ef6a7e4b/lib/modules/dosomething/dosomething_search/dosomething_search.module#L131) user geodata to prepare language filters. Thus, it doesn't matter what site user is at, only user country determined by Fastly.

As I understand, it should use [`dosomething_helpers_get_current_language_content_code()`](https://github.com/DoSomething/phoenix/blob/696a915ade1e7a25f4dcb216cad3b609ef6a7e4b/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L631) instead.

The catch here is that this filtering happens globally for all Solr query, as it's implemented in `hook_apachesolr_query_alter()`.

**Comment by itsjoekent** [comment]
yeah the global_get_user_vars function @sergii-tkachenko linked above was just a way to grab a million variables for the custom routing logic in global. there are more specific functions to figure out what lang the node should be displayed in (whose names escape me right now, but theyre probably in the dosomething global module)

**Comment by sergiitk** [comment]
3)

> Campaigns translated into Spanish should appear in Spanish on /campaigns. Campaigns translated into GL EN should appear in English on /campaigns.

The reason why content always is displayed in English is that  `explore_campaigns`  view uses 'Entity Id' field for grouping. When Solr indexes entities, it creates one record per translation. This is achieved with complex internal id (for example, `"3tj1ah/node/13/en-global"`).

When results are retrieved from it, every translation is returned as a separate record. However, grouping by id combines all translations records for same node id into one, and first language returned is displayed first (usualy, English), the rest — discarded.

**Comment by sergiitk** [comment]
4) Translation status (published/unpublished) is not factored in search query. We need to make sure that if translation isn't published for requested language, it's not displayed. See `sm_translations` solr field.

This explains why `Bookmark Climate Change` on Brazilian site is displayed on Explore Campaigns page, but falls to 404 when clicked. It's translated and active, but its `pt-br` translation isn't published.

**Comment by sergiitk** [comment]
Example for item 3: for Brazilian page both translations of `node/15` (Momm-o-grams) are returned, after grouping by id 15, only first, English Global, is displayed:
![image](https://cloud.githubusercontent.com/assets/672669/14899987/3084f46a-0d97-11e6-94c2-4603fabcd864.png)

![image](https://cloud.githubusercontent.com/assets/672669/14900005/41619e1e-0d97-11e6-8a25-da15016a8a29.png)

When view format is switched to `Unformatted list`, both translations are displayed:
![image](https://cloud.githubusercontent.com/assets/672669/14900060/8131b9b6-0d97-11e6-8712-ddf68e7e177f.png)

**Comment by crittermike** [comment]
I tracked it down to this line: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_search/dosomething_search.module#L133

That is attempting to set the language based on the `HTTP_X_FASTLY_COUNTRY_CODE` header, and just returns `en-global` by default if that header isn't found. So it's ignoring the `/br/` or `/mx/` or whatever path in the URL completely.

What's the correct fix here? Should this be updated to pay attention to the country code in the URL as opposed to the `HTTP_X_FASTLY_COUNTRY_CODE` header? Or at least fall back to the country code in the URL if that header isn't found? Or some other alternative?

**Comment by blisteringherb** [comment]
I believe there's a function somewhere for getting the language that takes the URL prefix into account. I'll have to hunt it down though, it's been a while sine I've touched that code.

**Comment by crittermike** [comment]
@blisteringherb You might be talking about this one? https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.module#L715

Can I take that to mean that we can just use the country code from the URL and ignore that header from Fastly, when deciding what language to filter by on the /campaigns page?

**Comment by DFurnes** [comment]
> Can I take that to mean that we can just use the country code from the URL and ignore that header from Fastly, when deciding what language to filter by on the /campaigns page?

Yeah, I think that's probably a safe assumption. If the user isn't at a language-prefixed URL and has a Fastly country header, they should always be redirected to a URL with a valid country code.
