### ISSUE TITLE
Missing mobile padding inside campaign template containers

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6398]
![screen shot 2016-04-21 at 1 19 03 pm](https://cloud.githubusercontent.com/assets/1865372/14919600/8fe242ea-0df7-11e6-8c53-0fb0b825bba9.png)
#### Behavior

Maybe the list element isn't getting any padding on the bottom when it's stacked up?
#### Desired Behavior
- It should have padding.

**Comment by DFurnes** [comment]
Ah, bummer. This is a side-effect of how we changed vertical padding to be on the `.container__row` in Forge 6.7. I think the best quick solution is to add that padding to `.container__block` on mobile breakpoints and we can maybe give more thought to how the container classes work in a future release.

**Comment by DFurnes** [comment]
This has been fixed in [Forge 6.7.2](https://github.com/DoSomething/forge/releases/tag/v6.7.2).

**Comment by DFurnes** [comment]
And deployed to Staging. 🚀
