### ISSUE TITLE
Run Runscope Tests for API Coverage on Deploy

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6399]
#### User Story

As a system of products that relies heavily on our two APIs, we should add existing automated testing of APIs to our deploy process.
#### Additional Information (optional)

Slack convo: https://dosomething.slack.com/archives/deploys/p1461937288000287
#### Why This Matters

Automated testing is just the best.

**Comment by DFurnes** [comment]
We've got a [small set of tests](https://www.runscope.com/radar/5tt8kuiumbfl) already configured to monitor some of the Phoenix endpoints (that I think Uy made): campaigns index, reportbacks index, taxonomy terms (causes), and reportback-items index.

**Comment by angaither** [comment]
oh yeah, I think we should update the ticket to say "run set of tests" pre-deploys and post messages to :slack:

**Comment by namimody** [comment]
How's that @angaither

**Comment by DFurnes** [comment]
@angaither Ah, gotcha. We currently run those hourly against production. Runscope is less useful (in my humble opinion) for _testing_ testing than for monitoring, but it'd definitely be a step in the right direction!

**Comment by angaither** [comment]
@DFurnes hrm, I'd like a way to check api responses (mainly that nothing is missing) before we deploy to prod. you think nah runscope?

**Comment by DFurnes** [comment]
I think it's a step in the right direction! I've just found for Northstar that they're more useful to "smoke test" that everything's a-okay in each environment (and then get alerts when it's not), rather than testing in a "is this safe to merge/deploy" sense.

**Comment by angaither** [comment]
:thinking_face:
