### ISSUE TITLE
Modal Problems

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6400]
#### Current Behavior

Modal design seems to be off with the new updates to Forge -- see screenshot below. Quite a few modal exist on Birthday Mail, as one place you could take a look (https://www.dosomething.org/us/node/2461/active)
#### Desired Behavior

Leaving this for you to fill out @lkpttn!
#### Why This Matters

Tons of modals across the site, plus Birthday Mail is sponsored.
#### OS/Browser (optional)

Chrome
#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/12396076/14931428/51d6fcec-0e39-11e6-9ed1-d6d6ea532c9d.png)

cc @mikefantini

**Comment by namimody** [comment]
Issue moved to [DoSomething/forge #553](https://github.com/DoSomething/forge/issues/553) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by DFurnes** [comment]
@namimody Bummer! 

Looks like the modal you screenshotted is an action guide modal... can you expand on which other ones are having issues? (I'll do a once-over again, but would love to make sure I don't miss any you've already found!)

**Comment by namimody** [comment]
@DFurnes yes! the one I found were all action guides, specifically on Birthday Mail -- https://www.dosomething.org/us/campaigns/birthday-mail. Hope that helps!
