### ISSUE TITLE
Do Something Thumbnail Missing From Search

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6403]
#### Current Behavior

When using internal search, static content pages show up with a broken image.
#### Desired Behavior

Static content pages should appear with the DS logo adjacent to the search result.
#### Steps to Replicate

Search something that would turn up a static content page. 
#### Why This Matters

Broken images look sad. :(
#### Relevant Screenshots + Links

https://www.dosomething.org/us/search/apachesolr_search/your?page=1
![image](https://cloud.githubusercontent.com/assets/12396076/15019019/24a0b6a0-11ea-11e6-8c97-6b333032fa2d.png)

cc @mikefantini

**Comment by DFurnes** [comment]
Oh blah, this links to the `dist/assets` folder in Forge which was removed with the build system updates in Forge 6.7. Should be a quick fix to change this to the plain 'ol Forge `assets` folder.

**Comment by jessleenyc** [comment]
hey @namimody got this when I hit the 404 page from birthday mail earlier but I'm assuming this is the same issue right??

<img width="483" alt="screen shot 2016-05-05 at 10 23 42 am" src="https://cloud.githubusercontent.com/assets/14931921/15046481/e21119be-12ad-11e6-9581-0412e586afa1.png">

**Comment by namimody** [comment]
@jessleenyc yes -- same issue! The 404 page pairs with populated search results in an attempt to help the user find what they are looking for, and an update to our pattern library removed the default image.

**Comment by jessleenyc** [comment]
@namimody Thanks, thought that might be the case -- glad I didn't create a duplicate. See you later today!
