### ISSUE TITLE
Birthday Mail Campaign Link Returning a 404 Page 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6410]
#### Current Behavior
- Birthday mail campaign is returning a 404 page when you click on the campaign from the DS homepage. 
#### Desired Behavior
- Should direct to campaign.
#### Steps to Replicate
1. Navigate to homepage
2. Click on "Birthday Mail" (the first highlighted staff pick campaign)
#### Why This Matters

This is the first campaign a user sees when they land on the DS homepage - page shouldn't return a 404
#### Relevant Screenshots + Links

<img width="1265" alt="screen shot 2016-05-05 at 10 22 00 am" src="https://cloud.githubusercontent.com/assets/14931921/15046241/c3d59f16-12ac-11e6-9e9d-c2d938219b05.png">
<img width="1272" alt="screen shot 2016-05-05 at 10 28 18 am" src="https://cloud.githubusercontent.com/assets/14931921/15046243/c5461cd6-12ac-11e6-80d4-ddcff48c9e5d.png">

**Comment by namimody** [comment]
Thanks for flagging! Try now, @jessleenyc? :)

**Comment by jessleenyc** [comment]
@namimody good to go! (should I close?)

**Comment by namimody** [comment]
💃
