### ISSUE TITLE
PHP 7.0 Compatibility - Continue keyword

### ISSUE THREAD

**Issue by blisteringherb** [DoSomethingArchive/legacy-website#6416]
#### Current Behavior
- `'Error: 'continue' not in the 'loop' or 'switch' context in
  /var/www/www.dosomething.org/releases/20160510153234/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module, line 1212` error on deploy after upgrading to PHP 7.0. 
#### Desired Behavior
- There shouldn't be a PHP fatal error when running any code
#### Steps to Replicate
- It happens on deploy, but chances are it will happen whenever the reportback code is run.
#### Why This Matters
- We can't upgrade to PHP 7.0 until we fix all places where we use the `continue` keyword outside of a switch
#### Relevant Screenshots + Links

https://jenkins-thor.dosomething.org/job/Deploy-Thor/405/console
https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L1212

**Comment by angaither** [comment]
yikes https://github.com/DoSomething/phoenix/search?utf8=%E2%9C%93&q=continue

**Comment by mshmsh5000** [comment]
In the first instance, this looks just like a misuse of `continue` instead of `return`. Am I missing something?

A lot of the others in that search are legitimate uses (i.e., within a loop).

**Comment by angaither** [comment]
ooo, you're right @mshmsh5000 I just looked above and saw they were mostly in `if`s but didn't look up further :eyes: ⏫
