### ISSUE TITLE
Show takeover screen after sign up

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#6425]
On campaign pages, after a user signs up for a campaign, trigger the display of a "takeover screen". This will hold content related to onboarding, other campaigns to signup for, etc.

**Comment by chloealee** [comment]
Done with https://github.com/DoSomething/phoenix/commit/75cd1be2daeb79380088a8b14aed30e7acdcd6c9 with @sbsmith86
