### ISSUE TITLE
Detect if a sign up is from a new account or an old one

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#6430]
We could display different experiences for people who just created an account to sign up for a campaign vs those who have already been members.

**New Folks:** If a user signs up for an account and then signs up for a campaign we could display more of an onboarding experience for them. 

**Old Folks:** If a member has already had an account, we could cut right to showing them other campaigns to sign up for.

**Comment by sbsmith86** [comment]
Note: Pass parameter when signing up a user that designates if the users is new or old so messaging can detect it as well.

**Comment by sbsmith86** [comment]
@chloealee looking at the mocks that fantini made up and wondering if for this first pass of this issue, instead of worrying about implementing the experience for new vs existing users, we just append something to the  `source` param we pass to the signup endpoint. 

For example, if it is a new user the source should be `repeat-signup-new` and `repeat-signup-existing` for old users, or something like that. This way we can at least track it and also maybe just do the new user experience for the first round of testing. Thoughts?

**Comment by chloealee** [comment]
@sbsmith86 that makes sense to me! So if it's an existing user, nothing changes for them and they have the same signup experience that is live on prod right now, right?

**Comment by sbsmith86** [comment]
@chloealee yea at least for now.

**Comment by chloealee** [comment]
@sbsmith86 looking more closely at this issue, do you mean changing the `source` param we have now (`multi-signup-module`) to either `repeat-signup-new` or `repeat-signup-existing`? 

Another route I was thinking would be to utilize the existing [`dosomething_signup_set_signup_message`](https://github.com/DoSomething/phoenix/blob/bb4fa06179e98a3b76cc14dd5a4791edfc8cf3e1/lib/modules/dosomething/dosomething_signup/dosomething_signup.module#L807) and set that if an existing user. If the user is new, set the onboarding takeover so all user logic would happen in the `dosomething_signup.module`. 

Does this route make sense to flesh out?

**Comment by sbsmith86** [comment]
@chloealee sure! I still think it would be cool to pass that information to the JS that the user is new, even if we don't care to store it (My thought initially was that would be good for data tracking and/or messaging but that could be pointless, shrug lol) But as this idea flushes out, like if we eventually want different experiences for new/existing users, it would be useful to know that info on the front end. 

Also, we don't know if we are really gonna put this experience in the status bar like we have it already. So might be useful to extract, into a new function, something that just returns whether the sign up is from a new or existing user, and we can use that as you outlined or in other places, like determining to show a modal (or whatever it is)

**Comment by chloealee** [comment]
@sbsmith86 ahh I see! So maybe a mix of both? Do the user logic in `dosomething_signup.module` and pass that to js if it's an existing or new member. Then when we make the signup POST request, replace `multi-signup-module` (`source` param) with either `repeat-signup-existing` or `repoeat-signup-new`?

**Comment by sbsmith86** [comment]
@chloealee I think you are right about not messing with the `source` param right now (at least not until we know what we need to track or not.) but otherwise yes!

**Comment by chloealee** [comment]
awesome, thanks @sbsmith86 !

**Comment by chloealee** [comment]
@sbsmith86 yikes I think I was thinking about this wrong all day but wanted to get your opinion before I change it. 

In order to check if a user was new or existing, I defined a new user as one whose account was created at the same time as the signup. However, now I'm realizing that maybe a user will register for an account but not necessarily signup for a campaign right away. E.g. I go to DoSomething.org on Monday and sign up for a user account. I don't sign up for a campaign until Friday of that week. In this case, we still want to show the user the onboarding experience since this is their first campaign, right? 

So we should be defining a "new user" as one that has never signed up for a campaign? In other words, we only want to show the onboarding experience to users on their first campaign and beyond that, they just get the multi-signup takeover/module?

**Comment by sbsmith86** [comment]
imo, I think it makes sense to just show this sorta onboarding/repeat signup experience for only first time signups. Let's not even worry about what we do for other users (so they would just get the same experience they have now).

Maybe we should bring this up at stand up to discuss with fantini and team to see what they were thinking?

**Comment by chloealee** [comment]
sounds good - thanks for the feedback!

**Comment by chloealee** [comment]
Closing with #6476
