### ISSUE TITLE
Shower Songs Runs + Reportbacks

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6440]
#### Relevant Screenshots + Links

up until 7:05 PM EST on 5/13/16, Shower Songs GL EN was set to:
https://www.dosomething.org/node/6511/edit/en-global
![image](https://cloud.githubusercontent.com/assets/12396076/15263549/0c8ab59c-1939-11e6-97a2-d6bb80fe9202.png)

Shower Songs US EN was set to: 
![image](https://cloud.githubusercontent.com/assets/12396076/15263556/1c96b2ba-1939-11e6-9fe3-4d32963a937a.png)

Reportbacks seem to be split between the two runs, when they should probably all be on one run. for this reason, I've translated run 6858 into GL EN and set the GL EN translation to be associated with run 6858. Now, both campaign translations are set to the same run.

Additionally, Shower Songs run 2 (https://www.dosomething.org/node/6511/edit/en-global) has no end date for either the US or GL EN. We need to set this.

The question is -- for the reportbacks that appeared on run 6511, is it because the members were truly coming from locations outside the US or because of https://github.com/DoSomething/phoenix/issues/6159?

**Comment by namimody** [comment]
cc @mikefantini

**Comment by angaither** [comment]
@namimody can you include links or IDs to the reportbacks you think are incorrect?

**Comment by namimody** [comment]
@angaither you would be better at writing this query in SQL than me -- but basically it would be any reportbacks associated with campaign NID: 3590 and run NID: 6511 that came in after May 1st 2016. Is that helpful?

**Comment by angaither** [comment]
@namimody handing back over to you for more details
