### ISSUE TITLE
Able to create duplicate mobile users via API.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#6450]
#### Current Behavior

Requests to the `api/v1/users` endpoint will allow you to create duplicate records for the mobile field.
#### Desired Behavior

It should not let you do this.
#### Steps to Replicate
1. Make an API request to the `api/v1/users` endpoint.
2. Then, do it again with the same mobile.
3. Repeat as many times as desired.
4. React in horror to the disaster you have wrought! 😨 ☎️ 
#### Why This Matters

We don't want dupes. Dupes are bad.

👮

**Comment by DFurnes** [comment]
It turns out this endpoint also doesn't sanitize mobile numbers like we do elsewhere (any punctuation or letters are stored directly in the database). I'm wary of doing too much refactoring, but it sure feels like there should be some shared business logic between this and "web" registration.

**Comment by angaither** [comment]
@DFurnes based on no mobile cleansing, as well as #6442 (we are somehow [still](https://github.com/DoSomething/phoenix/blob/5758474cb8273954936a2988c037ee52007c8225/lib/modules/dosomething/dosomething_api/resources/member_resource.inc#L169)  calling [this old-ass function](https://github.com/DoSomething/phoenix/blob/b2706b012d415a2d94796bb6df776da538dcd2e4/lib/modules/dosomething/dosomething_settings/dosomething_settings.module#L36)) I think we will have to refactor this endpoint a tad
