### ISSUE TITLE
expose kudos on user profile

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6457]
let peeps see in their profile if others kudoed their item

**Comment by lkpttn** [comment]
![2 0 profile likes](https://cloud.githubusercontent.com/assets/1865372/15906644/c2f21d54-2d87-11e6-9b5b-df9402d1ebda.png)

12px distance from the second reportback line to the top of the heart icon

**Comment by itsjoekent** [comment]
hmmm, after https://github.com/DoSomething/phoenix/pull/6577 gets merged it might make sense to break Kudos out of the photo template. otherwise we're gonna have some duplicate code.

also @lkpttn in this mockup some of the hearts are pressed, people can heart there own reportbacks?

**Comment by lkpttn** [comment]
Yes indeed, people can like their own reportback

**Comment by itsjoekent** [comment]
@angaither should this be enabled by the global toggle I built here https://github.com/DoSomething/phoenix/pull/6559

or do i make a new one specific to user profiles?

**Comment by angaither** [comment]
@deadlybutter this and #6545  should be enabled by the global toggle
