### ISSUE TITLE
set default kudos for entire site

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6458]
- replace the `heart` emoji with the SVGs provided

**Comment by angaither** [comment]
@lkpttn we are using the heart and here is the SVGs
https://dosomething.slack.com/files/piercey/F1EQSUM9P/gray-heart.svg
https://dosomething.slack.com/files/piercey/F1EP7FJHZ/pink-heart.svg

**Comment by lkpttn** [comment]
Here's what it looks like in practice:

![kudos gallery](https://cloud.githubusercontent.com/assets/1865372/15870725/31f3b146-2cbf-11e6-99a6-e14850ab59a0.png)

Icon is 30px wide. Font is the gamma heading, which should be roughly 18px.
12px to the left and bottom edges. The text is normal #4a4a4a.

**Comment by angaither** [comment]
@deadlybutter mind picking this up next?

**Comment by itsjoekent** [comment]
@angaither sure

**Comment by itsjoekent** [comment]
talked w/ the 😎 fenders -- going to 

1- use CSS to do this
2- switch the <a> to a button because that makes more sense
