### ISSUE TITLE
Editable Content Regions + Markdown Breaking Layout

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#646]
When Markdown is selected as the input format there is the potential that layouts can break if the field variable is wrapped in an inline element.

For example, the following markup pulled from the Campaign template file will result in a paragraph element nested inside another paragraph element:

```
// node--campaign.tpl.php
<p class="tip-body"><?php print $item['copy'] ?></p>

// resulting HTML
<p class="tip-body"><p>Broken layout!</p></p>
```

Every element wrapping an editable content region should be a block level element with paragraph styles applied if applicable to prevent this.

**Comment by barryclark** [comment]
@mmwtsn Think this guy should be fixed by your solve of just not wrapping content in paragraph tags. Closing.

**Comment by desmondmorris** [comment]
You could also disable the auto conversion of line breaks to P tags in the text formatter.  This may cause other issues, but is worth taking a look at

**Comment by mmwtsn** [comment]
Already taken care of! Aaron checked that option last week:
![md](https://f.cloud.github.com/assets/1479130/2196489/3f936bc0-98b0-11e3-9083-0ea5f8aafbf8.png)
