### ISSUE TITLE
Fix Niche Flow

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6470]
#### Current flow
1. User is created via the api
2. Sent a link to reset password
3. Click the dumb login link
4. Reset password/edit profile
#### Easier flow
1. User is created via the api
2. Sent a link to reset password
3. Skip the login thing, and just reset password/edit profile
#### Additional Information (optional)

[There's a module for this](https://www.drupal.org/project/simple_pass_reset) but it looks like it has some serious excess code. 
We could use that, or write something ourself, and override the edit form to display more relevant things
#### Why This Matters

The current flow ~sucks~
Also, we could probably make #1003 while we are at it

**Comment by DFurnes** [comment]
This could also work well as a "complete your profile" two-step registration flow in Northstar.

**Comment by angaither** [comment]
according to @DeeZone we no longer send password reset emails to niche users
so this link probably needs to be included in the signup for niche emails

**Comment by deezone** [comment]
James is implementing the link in the current Niche onboarding process. I'll let him chim in once he has a GitHub account.
