### ISSUE TITLE
Bump message_broker_producer requirements warning

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#6472]
#### Current Behavior

The Message Broker module displays a requirements error on the Drupal status report. This is because of a bug that was [fixed in the module in May 2015](https://github.com/DoSomething/message_broker_producer/commit/56d095c07a7bef745d89becb5a5767a9654cc3a6). This fix is in [v0.2.6](https://github.com/DoSomething/message_broker_producer/releases/tag/0.2.6), the most recent release (as of May 2016).
#### Desired Behavior

The module displays a happy, green row on the Status Report page.
#### Steps to Replicate

Visit the Status Report page at `/admin/reports/status`.
#### Why This Matters

We should have meaningful feedback on whether the installation is healthy.
#### Relevant Screenshots + Links

<img width="872" alt="status-report" src="https://cloud.githubusercontent.com/assets/149811/15396247/2d4768ce-1da9-11e6-8d6b-4dae787b3fd9.png">
#### Testing Notes

As there are non-trivial changes in the v.0.2.6 release, we'll need to test messaging delivery thoroughly before releasing to prod.

**Comment by sergiitk** [comment]
Not relevant anymore, the module will be deprecated soon.
