### ISSUE TITLE
share campaign

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6483]
As a user I get a "unique" url that I can share with friends so other people can sign up from me
- create a custom URL that is a link to the campaign's pitch page with a UID attached
- eg dosomething.org/campagins/organ?source=[uid]

**Comment by chloealee** [comment]
@angaither @sbsmith86 will these links live as social share icons/do we want to just add the `source=[uid]` to the [`dosomething_helpers_share_bar`](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.share.inc#L130) function to include or will we give the link to user to share in a different way?

**Comment by angaither** [comment]
@chloealee I don't think we want to do the whole social share bar with these 

cc @mikefantini

**Comment by mikefantini** [comment]
@angaither @chloealee sorry is the "whole social bar" FB, Twitter, Tumblr?

**Comment by sbsmith86** [comment]
We can certainly choose which social media options you want to use, but all the `dosomething_helpers_share_bar` outputs is like:

```
<ul>
<li class="-facebook">Facebook</li>
<li class="-twitter">Twitter</li>
</ul>
```

Regardless, i think they will be icons at least, right? and then you just need to append the `source=[uid]` param to the `path` that you send to `dosomething_helpers_share_bar`. That should output all the markup you need with the appropriate classes

**Comment by sbsmith86** [comment]
@mikefantini the "whole share bar" can be fb, tumblr, twitter. But, it doesn't have to be. You could just do a subset of those, or we can add more if you want.

**Comment by mikefantini** [comment]
@angaither I was initially thinking icons. And @sbsmith86 mentioned we could potentially display the link as well.

Ideally I'd want to see what the different options look like before making a final call - is this something that's easy enough to look at on dev or would you want this mocked up?

**Comment by chloealee** [comment]
cool thanks, all! I think this is easy enough to look at on dev for options, np!

**Comment by chloealee** [comment]
@mikefantini here's what it looks like with share buttons and the link (obviously we can tweak with better design and copy!). Right now, this is just in the drop down we built for the multi-signup but I can pop all of this into the modal that will pop up getting more of the user's info. to interact with the Organize API. 
![screen shot 2016-05-25 at 4 09 29 pm](https://cloud.githubusercontent.com/assets/9019452/15554669/53929eb0-2293-11e6-9896-416883cc5779.png)
