### ISSUE TITLE
Remove tests?

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#6486]
#### Current Behavior

The functional and unit tests are out of date and have not been updated (or run) in a very long time.
#### Proposed Behavior

Since these aren't being used, we should consider removing them from the repository.
#### Why This Matters

We shouldn't have code in the repository that isn't being used, since it is confusing for onboarding.
#### Relevant Tickets

References DoSomething/devops#52.

**Comment by aaronschachter** [comment]
Refs https://github.com/DoSomething/phoenix/issues/1746 too, e.g. [`dosomething_reportback.test`](https://github.com/DoSomething/phoenix/blob/a1163d189604f3878b7231743b80b061559e9f43/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.test)
