### ISSUE TITLE
Import UK users

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6492]
### User story

As a uk.dosomething.org user I should be able to log in to dosomething.org

As we retire the uk site, we should import UK users. 🇬🇧 ➡️ :us:
### Steps
- we can run a script like [this](https://github.com/DoSomething/phoenix/blob/dev/scripts/import-all-the-things.php) to import users from the uk
- set `source` to `DS UK`
- do not import campaign activity

**Comment by itsjoekent** [comment]
script seems ok, only worry is will the global language be set by this? I dont think it will but could be wrong

**Comment by itsjoekent** [comment]
in case i lose it, query that gets
- first name
- last name
- email
- pass
- birthday 

```
SELECT u.uid, u.mail, u.pass, fn.field_first_name_value, ln.field_last_name_value, bd.field_birthdate_value
FROM users u
JOIN field_data_field_first_name fn
ON fn.entity_id = u.uid
JOIN field_data_field_birthdate bd
ON bd.entity_id = u.uid
JOIN field_data_field_last_name ln
ON ln.entity_id = u.uid
```

**Comment by itsjoekent** [comment]
good question we need to answer when we test on Thor

<img width="483" alt="screen shot 2016-06-24 at 1 04 13 pm" src="https://cloud.githubusercontent.com/assets/897368/16344759/326d74f4-3a0c-11e6-9d28-15ae672e00e9.png">

**Comment by angaither** [comment]
@deadlybutter we also want to make sure those users can still log in, password hashing stufff ;)

**Comment by itsjoekent** [comment]
update based on lunch convo with @angaither and @Bladt we're going to just import all of the users into Mailchimp & send them a message to create an account on dosomething.org -- I'll pass the CSV over to whoever is going to send the email!

Also I assume that means we will need Ben to quickly write something up?

**Comment by itsjoekent** [comment]
BY THE ORDER OF @angaither WE ENACT ARTICLE 50 AND CLOSE THIS ISSUE. BREXIT.

<img width="437" alt="screen shot 2016-06-30 at 2 00 02 pm" src="https://cloud.githubusercontent.com/assets/897368/16498722/0a3778cc-3ecb-11e6-95a8-f68b9d49b8ad.png">

**Comment by itsjoekent** [comment]
i thought i hit close & comment, whoops haha
