### ISSUE TITLE
Favicon not appearing

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6504]
#### Current Behavior

Favicon not appearing
#### Desired Behavior

Favicon should appear
#### Steps to Replicate

navigate to: https://www.dosomething.org/us
#### Why This Matters

good branding?
#### OS/Browser (optional)

Mac OSX El Capitan Version 10.11.5 / Chrome 50.0.2661.102
#### Relevant Screenshots + Links

![screen shot 2016-05-25 at 3 27 22 pm](https://cloud.githubusercontent.com/assets/14931921/15554300/7ef4c346-2291-11e6-9c63-de3562049dbf.png)

**Comment by DFurnes** [comment]
...gah! That `/dist/` folder change strikes again! 😩 

```
  <link rel="shortcut icon" href="/profiles/dosomething/themes/dosomething/paraneue_dosomething/node_modules/@dosomething/forge/dist/assets/images/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="/profiles/dosomething/themes/dosomething/paraneue_dosomething/node_modules/@dosomething/forge/dist/assets/images/apple-touch-icon-precomposed.png">
```

These should both be updated to point to `/node_modules/@dosomething/forge/assets/images/`.
