### ISSUE TITLE
Display issue in "Do It" tabs when no tips are provided.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#6506]
#### Current Behavior

If there aren't any "tips" in the "Do It" section, it seems like we still print out an empty container which looks kinda messy.
#### Desired Behavior

We should probably hide this section if it's content is empty!
#### Steps to Replicate

Check out the bottom of the "Do It" section on [Four Legged Finishers](https://www.dosomething.org/us/campaigns/four-legged-finishers#do) action page.
#### Why This Matters

It's messy.
#### Countries Affected (optional)

The whole globe.
#### OS/Browser (optional)

All of 'em.
#### Relevant Screenshots + Links

![screen shot 2016-05-26 at 10 33 37 am](https://cloud.githubusercontent.com/assets/583202/15578147/5b0039a6-232d-11e6-92ac-6aca84d6064c.png)

**Comment by DFurnes** [comment]
Oh, we also seem to be allowing more than 3 "tips" to be included per section which ends up looking a little awkward when the "tabs" wrap to a second line (also seen on Four Legged Finishers):

![screen shot 2016-05-26 at 10 37 39 am](https://cloud.githubusercontent.com/assets/583202/15578309/fbd4371a-232d-11e6-970f-431158816f83.png)

**Comment by angaither** [comment]
apparently these are editorially required for emailz
