### ISSUE TITLE
# of People Participating Showing Up on All Pitch Pages

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6516]
#### Current Behavior

On every non-SMS campaign pitch page, you can see the "# of people participating."
#### Desired Behavior

Only the second CTA should show near the second sign up button. It should not show the # of people participating.
#### Steps to Replicate

Go to any campaign's pitch page and look at the second CTA. It will also show the # of people participating in the campaign.
#### Why This Matters

We ran including this number on the pitch page as a test, and it didn't help conversion rate consistently, and therefore we should remove it ASAP. Additionally, the numbers that are being pulled in are wrong.
#### Relevant Screenshots + Links

https://www.dosomething.org/us/node/6692/pitch
![image](https://cloud.githubusercontent.com/assets/12396076/15596829/b2d83a6e-2398-11e6-9cf4-47fee8feb4d2.png)

Inspect Element shows:
![image](https://cloud.githubusercontent.com/assets/12396076/15596813/955cb2d0-2398-11e6-8319-c78184de01f2.png)
#### Additional Information

Could it be related to: https://github.com/DoSomething/phoenix/pull/6511 at all?

This is the JS snippet that we used to run this test on specific campaigns within Optimizely: 

`jQuery(".campaign--pitch").find(".cta").removeClass("optimizely-hide-count").addClass("optimizely-show-count");
$("h2.with-count").replaceWith("<h2 class=\"cta__message with-count\">Join 58,760 people recycling clothes.</h2>");`

These are the campaigns that we ran the test on in Optimizely:

![image](https://cloud.githubusercontent.com/assets/12396076/15609643/388da846-23ef-11e6-95d4-55c28ca69f47.png)

**Comment by DFurnes** [comment]
Oh, I removed the styles for this in #6494. 😞 Didn't realize we were still calculating and outputting this on the page. I can put in a fix this morning.

**Comment by namimody** [comment]
cc @mikefantini as an FYI
