### ISSUE TITLE
Add Description Field to Campaign Run Node

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6526]
#### User Story

Runs for campaigns for different reasons. Sometimes we add a scholarship to a campaign, sometimes there is a celebrity influencer, sometimes there is a sponsor. All of this context as to why we start a new run is not logged anywhere central to all teams, making it hard to make sense of different runs from a data/campaigns/tech perspective. 

What we would like is to add a description field to a run (maybe in the Basic Info Section) that would allow a campaign lead to add a few lines of description as to why they are creating a new run of the campaign.

![image](https://cloud.githubusercontent.com/assets/12396076/15678886/e479ba4c-271d-11e6-9b39-1b2275442771.png)
#### Additional Information (optional)

Maybe the field could have help text like, "Describe why you are creating a new run. Write it with enough context so that a future campaign lead could read it and immediately understand why a new run was created. Will this run have a scholarship? Is there a celebrity endorsing the campaign? Does the campaign have a new sponsor? In which countries is this run going to be available? etc."
#### Why This Matters

It's important for different teams to understand the context for creating a new run, and to help attribute campaign activity.

**Comment by angaither** [comment]
@chloealee mind taking a look at this while waiting for organz

**Comment by chloealee** [comment]
@angaither so sorry - just seeing this now! Do you want me to jump on this now before moving forward with more organize work? @sbsmith86 and I just broke up some work and I was about to start creating the endpoints to hit the API on the backend and pass info to frontend.

**Comment by chloealee** [comment]
@namimody do we also want the description to show up on this page (I've put a placeholder where it will be)? 
![screen shot 2016-06-02 at 1 30 13 pm](https://cloud.githubusercontent.com/assets/9019452/15754452/34eee67e-28c6-11e6-9cb5-1fabad5fd905.png)

**Comment by namimody** [comment]
@chloealee thanks for asking! Sure -- let's expose the run description on this view, but could we make the order:

Campaign
Campaign Closed State
Run Description

Thanks!!!

**Comment by chloealee** [comment]
@namimody sure thing!
