### ISSUE TITLE
Allow kudos actions on 'view more' reportbacks

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6544]
Reportback items rendered on the frontend after clicking `view more` need to have kudos options on them

**Comment by weerd** [comment]
This requires some API updates for the reportback-items endpoint to include the same kudos info that we're using on the initial gallery before the view more.

**Comment by weerd** [comment]
Might be easier then expected. I was getting confused since most of the items that are loaded via the view more just don't already have kudos on them...
