### ISSUE TITLE
Add kudos on the permalink

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6545]
Enable kudos on the permalink page
![image](https://cloud.githubusercontent.com/assets/645205/15784900/9f30e4b2-2982-11e6-9c62-2daec39ea945.png)

**Comment by jessleenyc** [comment]
@angaither, just to clarify - are you looking for a mockup? @lkpttn is there anything I can do to be helpful here?

**Comment by lkpttn** [comment]
@jessleenyc yeah no worries, I'm going to provide this mockup today.

**Comment by lkpttn** [comment]
![2 0 permalink likes](https://cloud.githubusercontent.com/assets/1865372/15906487/0bdcbdb8-2d87-11e6-9e3b-485fdd7d219b.png)
