### ISSUE TITLE
Store user fields after a user submits organ reg form

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6557]
We should be able to fill out on a user once they submit the organ donation form
- [ ] `field_birthdate`
- [ ] `field_mobile`
- [ ] `field_address`
- [ ] `field_last_name`

**Comment by ngjo** [comment]
I'm thinking the most useful ones: 
-state
-postal_code
-phone_number
-birthdate (if we don't have it)
-last_name
-street_address
-apartment
-city

and -gender (mike mentioned we don't have a field that maps back to this and want to also double check with jeff if this is something we'd even want to track)

**Comment by ngjo** [comment]
@katiecrane or @angaither does the "field_address" include their full address (apt, if they gave it, for example) city and state?

**Comment by katiecrane** [comment]
@ngjo yeah I'm pretty sure, as far as I know it is an array of all the address information that we have

**Comment by ngjo** [comment]
awesome, thanks @katiecrane !
