### ISSUE TITLE
Vagrant 2.0 box build errors

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#6561]
#### Current Behavior

The `ds build --install` and `ds build` commands cause a bunch of errors when run on the [PHP 7 version of the Vagrant box](https://github.com/DoSomething/phoenix/pull/6438) and result in a broken installation.

I've copied the errors into two gists for aid debugging: [when running `ds build --install`](https://gist.github.com/DFurnes/2f47756e2ea08328e001e14af71a744e) and [when running `ds build`](https://gist.github.com/DFurnes/cdcbbe2b0a57b05b5d7720a890cc903b) for help diagnosing the issue. In the meantime, I'll revert back to the stable PHP 5.9 version of the box.
#### Desired Behavior

It should work, without errors!
#### Steps to Replicate

Try to run `ds build --install` on a fresh copy of the new Vagrant box.
#### Why This Matters

Now that the production servers are running PHP 7, we should be running it in development too so we don't run into unexpected problems when deploying code.

🏭

**Comment by DFurnes** [comment]
Downgrading my Vagrant box to 1.0.7 fixed the issue, in the meantime.

**Comment by sergiitk** [comment]
Working on this today.

**Comment by DFurnes** [comment]
Sergii walked me through this setting this up today. It turns out it actually _was_ working when I tried to do this previously and the "unrecoverable error", "non-functional Drupal environment", and "No Drupal site found" messages were all expected behavior. 😮 

Closing!

**Comment by sergiitk** [comment]
Closing this, it is works with latest Phoenix. Here's Slack log with Dave:

Dave Furnes:
[5:16 PM] Yeah, it gets to the `Build complete.` line.
[5:16 PM] Trying a `ds pull stage —db` now.
[5:16 PM] Still getting a lot of errors related to New Relic and Varnish, but maybe those are expected too?
[5:18 PM]  Looks like it’s working!

Sergii Tkachenko
[5:18 PM]   Varnish is expected, we simply don't have it installed in phoenix vagrant
[5:19 PM]   New relic isn't relevant as well
[5:19 PM]  I'll try to fix New Relic today though
[5:19 PM]  And drush
