### ISSUE TITLE
Dblog errors about organz

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6562]
#### Current Behavior

@weerd saw this in dblog

```
Notice: Undefined variable: register_organ_donor in include() (line 387 of /var/www/dev.dosomething.org/lib/themes/dosomething/paraneue_dosomething/templates/campaign/node--campaign.tpl.php).`
```

and this

```
Notice: Undefined property: stdClass::$register_organ_donor in paraneue_dosomething_preprocess_node_campaign() (line 186 of /var/www/dev.dosomething.org/lib/themes/dosomething/paraneue_dosomething/includes/preprocess/preprocess_node.inc).
```
#### Desired Behavior

no errors
#### Steps to Replicate

I think it's because the organ donation module isn't turned on for him, so we need to wrap all code in checks if the module is enabled 
#### Why This Matters

reasons

**Comment by chloealee** [comment]
@weerd I'm having trouble replicating this on my local - can you tell me at what point you saw these in the dblogs? 

@angaither looks like there are checks if the module is enabled already but the variables and properties are undefined for some reason.

**Comment by weerd** [comment]
@chloealee Toggle off the organ donation stuff, and then load a few campaigns. I don't have any of the organ donation stuff activated on my local, but get those errors whenever I load any campaign.

**Comment by chloealee** [comment]
@weerd hmmm I tried doing that but still can't get those same errors. I am getting another error though: 

```
Notice: Undefined property: stdClass::$id in include() (line 17 of /var/www/dev.dosomething.org/lib/themes/dosomething/paraneue_dosomething/templates/system/patterns/photo.tpl.php).
```

**Comment by chloealee** [comment]
ahh - I see that you're fixing those in a separate PR now (#6563)! Are you still seeing the errors in this issue? @weerd

**Comment by weerd** [comment]
@chloealee yep. that'll be fixed with this one #6563

**Comment by weerd** [comment]
![image](https://cloud.githubusercontent.com/assets/105849/15872075/95b06ff2-2cc5-11e6-9076-2bc9fecce098.png)

yep yep.

**Comment by chloealee** [comment]
hm weird! Thanks for sending - I keep trying to replicate.

**Comment by chloealee** [comment]
oh sorry - I was confused above! By enabled I thought it meant the organ donation box was checked in custom settings. But now I see why I was misunderstanding - sorry about that!

**Comment by weerd** [comment]
No worries :)
