### ISSUE TITLE
Three Dots in Header Photos

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6567]
#### Current Behavior

Some campaigns have three dots that appear on the left of the header photo, and some don't.
#### Desired Behavior

Three dots should not appear.
#### Steps to Replicate

Go to the header photo of the campaigns listed below.
#### Why This Matters

These dots are weirddd.
#### OS/Browser (optional)

Chrome
#### Relevant Screenshots + Links

A campaign with three dots:
https://www.dosomething.org/us/campaigns/pride-over-prejudice
![image](https://cloud.githubusercontent.com/assets/12396076/15872677/9e9f547c-2cc8-11e6-9b0b-283a8b426a4d.png)

Another campaign with three dots:
https://www.dosomething.org/us/campaigns/school-board-tweeter?source=campaigns
![image](https://cloud.githubusercontent.com/assets/12396076/15872726/d0b7f68a-2cc8-11e6-89c1-0d1d55475db8.png)

Another campaign with three dots:
https://www.dosomething.org/us/campaigns/re-poppin-bottles?source=campaigns
![image](https://cloud.githubusercontent.com/assets/12396076/15872735/e13dd6f0-2cc8-11e6-938f-f2e543fa566e.png)

A campaign without three dots:
https://www.dosomething.org/us/campaigns/birthday-mail
![image](https://cloud.githubusercontent.com/assets/12396076/15872708/be40ac90-2cc8-11e6-8cc6-039cae59912c.png)

Inspect Element shows:
![image](https://cloud.githubusercontent.com/assets/12396076/15872758/023bb7e6-2cc9-11e6-8f97-5163165ae3bc.png)

**Comment by mshmsh5000** [comment]
This looks like an Optimizely problem:

<img width="913" alt="ellipsis" src="https://cloud.githubusercontent.com/assets/149811/15899759/cf3d8b6a-2d6a-11e6-8928-aad6d745d3f6.png">

**Comment by angaither** [comment]
ah! lovely! 

> there's nothing we can do

**Comment by ngjo** [comment]
Happened on this issue -- adding some dot dot dot instances on campaign pages that I've come across on my own:

![screen shot 2016-07-07 at 4 55 30 pm](https://cloud.githubusercontent.com/assets/2658867/16953237/4e43364a-4d9a-11e6-9bf2-729e71e1d7a6.png)
![screen shot 2016-07-07 at 4 55 41 pm](https://cloud.githubusercontent.com/assets/2658867/16953236/4e4206d0-4d9a-11e6-8153-e56b2ebdd199.png)
![screen shot 2016-07-11 at 1 25 58 pm](https://cloud.githubusercontent.com/assets/2658867/16953235/4e405b28-4d9a-11e6-80f4-97af15d839ef.png)
![screen shot 2016-07-11 at 11 07 23 am](https://cloud.githubusercontent.com/assets/2658867/16953233/4e3f4b84-4d9a-11e6-8493-5dfb4f9f33fc.png)
![screen shot 2016-07-11 at 11 15 45 am](https://cloud.githubusercontent.com/assets/2658867/16953238/4e4507ea-4d9a-11e6-87d2-5e9e66a19100.png)
![screen shot 2016-07-11 at 11 40 47 am](https://cloud.githubusercontent.com/assets/2658867/16953234/4e40105a-4d9a-11e6-9b9b-7045e5c9bd7a.png)
![screen shot 2016-07-11 at 11 42 43 am](https://cloud.githubusercontent.com/assets/2658867/16953241/4e4859e0-4d9a-11e6-95d7-b9f756c178c4.png)
![screen shot 2016-07-11 at 11 44 22 am](https://cloud.githubusercontent.com/assets/2658867/16953239/4e46506e-4d9a-11e6-9129-34f59dda5224.png)
![screen shot 2016-07-11 at 11 44 36 am](https://cloud.githubusercontent.com/assets/2658867/16953240/4e46dbe2-4d9a-11e6-87fe-bf153925ca64.png)

**Comment by namimody** [comment]
@ngjo since this is Optimizely issue, I think it's something that you + me + @DFurnes (our dev Optimizely expert) could handle -- here's something I found on it:

https://community.optimizely.com/t5/Using-Optimizely/Optimizely-breaking-jquery-dotdotdot-ellipsis-feature-when-test/m-p/9085#M2316

Also -- just checked Thor (which Optimizely doesn't run on) and the "..." aren't showing up:
https://www.dosomething.org/us/campaigns/solitary-statements
![image](https://cloud.githubusercontent.com/assets/12396076/16960273/b6a06d5e-4db6-11e6-87fd-8360e4ba88ca.png)

**Comment by angaither** [comment]
not seeing this anymeow! 🔮
