### ISSUE TITLE
11 facts – style

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#658]
Preprocess and theme the 11 Facts pages.

**Comment by aaronschachter** [comment]
Tons of preprocess errors due to no `isset` checks: https://s3.amazonaws.com/uploads.hipchat.com/34218/363821/MuBC3spnZW6VzGG/Screen%20Shot%202014-03-04%20at%2010.35.15%20AM.png

**Comment by barryclark** [comment]
@aaronschachter I haven't touched this yet, but will get to it soon.

**Comment by barryclark** [comment]
Remaining tasks broken out into separate issues.
