### ISSUE TITLE
Able to select multiple search filters at once

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6581]
#### Current Behavior

-Currently able to select multiple causes/times/types on campaign search
#### Desired Behavior
- Should only be able to select item from each list
#### Steps to Replicate
1. navigate to home page
2. click cause
3. quickly click on different categories. observe multiple categories highlighted. 
4. repeat for other time & type
#### Why This Matters

-Selecting multiple items is not currently a feature we offer. 
#### OS/Browser (optional)

Safari & Chrome
#### Relevant Screenshots + Links

![screen shot 2016-06-09 at 1 45 10 pm](https://cloud.githubusercontent.com/assets/14931921/15940256/3a5b006a-2e49-11e6-9f55-2e1cba0b46d8.png)

**Comment by angaither** [comment]
we have seen this before (#2584 #1695)
