### ISSUE TITLE
Create custom setting to enable & configure unique social share link

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6584]
#### User Story

As an admin I would like to enable a unique social share link per campaign.
As an admin I would like to provide custom text to share with the link. 
#### Additional Information (optional)

This should be a toggle in the `custom settings` of a campaign.
There should also be a text field (it would be cool it if also had a counter)
#### Why This Matters

We can customize the share per campaign.

**Comment by aaronschachter** [comment]
It'd be nice to expose this into the API too to populate the "Share photo" copy when sharing a Reportback from mobile app.

**Comment by chloealee** [comment]
@aaronschachter makes sense! So this is when a user shares one of their own reportbacks on their social channels? Should we create a separate issue for this?

**Comment by aaronschachter** [comment]
@chloealee yup! sounds good re: separate issue, it's more of a nice-to-have vs anything needed for milestone. i'd imagine the copy would still be the same, even though we're sharing a reportback photo (its still for the campaign).
