### ISSUE TITLE
Wording about why we're asking them to sign-up to DS to become an organ donor

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6589]
#### User Story

As a non-member user, when I come to the pitch page and decide to "register to donate" I'm prompted w/ the "sign-up to be a member." 

Would like to see an explanation about why we are asking them to sign-up either on the pitch page or on the actual sign-up page.
#### Why This Matters

The user might be confused, "why do I need to sign up for this other thing before i can sign up to be an organ donor" and then decides not to sign-up or register to be a donor.

**Comment by angaither** [comment]
@ngjo I have a feeling we don't need an issue for this, and we can just put this in the campaign template somewhere

**Comment by ngjo** [comment]
Sounds good @angaither -- so it can go in the "What You Get" section? Or have we put this kind of language in a different spot in the past?

**Comment by angaither** [comment]
@ngjo I'm def not an expert on the best place to put things in the campaign template (cc @namimody or @mikefantini)

**Comment by namimody** [comment]
@ngjo would love to be helpful here -- but not too familiar with the organ donation flow. :/ does the pitch page look just like the regular pitch page for a campaign?

**Comment by angaither** [comment]
@namimody yaaaa

**Comment by namimody** [comment]
ohhh thanks @angaither then yes yes -- probs the What You Get section as the problem and solution statements also appear on the action page!

**Comment by angaither** [comment]
kewl, I'll close this meeee-out then
thanks @namimody!

**Comment by namimody** [comment]
@ngjo let me know if you want to chat about this in Slack or real life -- happy to help!

**Comment by ngjo** [comment]
@namimody IRL if that's ok! I'll put something on the calendar for 30 min so I don't forget!
