### ISSUE TITLE
Query for competitions

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6590]
#### User Story

As an admin, I need to be able to query the database to know who have:

(1) Signed up

(2) Fallen off the form (possible to track where they've fallen off the form -- should that be a custom event? I'm talking to data team about this but keeping here for now)

(3) Completed registrations

(4) Including this here, but I think the entrances  -- do I need to create a separate issue for that -- i'll ask data team too, but keeping here for now:
- Number of entrances via custom social links
- Number of sign-ups via custom social links

The query will need to pull: first name, email
#### Why This Matters

So we know what's going on

**Comment by angaither** [comment]
1. campaign signups from other users will be something like 
   
   ```
   select u.uid, u.mail
   from users u
   inner join dosomething_signup s on s.uid = u.uid
   where s.source like "user/%"
   and n.nid = ____
   ```
2. unclear what this query will look like currently

**Comment by ngjo** [comment]
@angaither Can I also add a request for the query for "people who have successfully completed the registration form" to this one or should I create a separate issue? Thanks!

**Comment by ngjo** [comment]
@angaither I want to give the competitions team an update and wanted to know if you think the 3 queries above are doable. Recap:

(1) number of people signed up for campaign
(2) number of people who have completed the registration form
(3) number of people who have fallen off the form

Thanks!

**Comment by ngjo** [comment]
@angaither I updated this issue to more clearly reflect what we want for voter. 1,2,3 are all the same -- # 4 is a new one though that we were talking about and wasn't exactly sure where to add, but didn't want to lose it so added it here! Let me know, thanks!

**Comment by angaither** [comment]
closing for #6777
