### ISSUE TITLE
Pop-up reminder to register (for those who didn't complete the form)

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6592]
#### User Story

As a user, if I qualify to fill out the registration form but decide to fill out the form later or accidentally close out of the form (basically leave the form behind), when I come back to the pitch page, I want to be prompted again to fill out the registration form. 
#### Additional Information (optional)

Form doesn't need to be filled out w/ what they might have put in there previously. We only want to keep prompting the 18+ year olds who haven't become registered donors.
#### Why This Matters

To maximize the number of registered donors we have.

**Comment by angaither** [comment]
@ngjo I think this is how the form already works, but @sbsmith86 can confirm

**Comment by sbsmith86** [comment]
yea this is how it functions. There is no official "reminder" messaging on it, that would be some extra logic.

**Comment by ngjo** [comment]
awesome, thanks for confirming! 

(separately: would this be something I should close out...or do you guys close these things out? thanks!)
