### ISSUE TITLE
Option to email the Unique ID (social declaration stage)

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6593]
#### User Story

As a user, in addition to Facebook/Twitter, I'd like to be able to email my Unique ID along with some pre-populated messaging to friends/family.
#### Additional Information (optional)

See: https://www.lucidchart.com/documents/edit/b4784dd7-e99c-4bc1-9892-256376d49593 
#### Why This Matters

ORGANIZE did a study that email was the most effective way of promoting organ donation ("Email was by far the most effective channel. People receiving an email were between 13 and 23 times more likely to register than people who viewed the same content over social media." AND "When receiving the email from your employer (or a trusted friend), 70% of people who started the registration process actually finish it. When receiving the email from a brand (whose email blasts they opted in to, but for which they do not work), only 17.5% of people who started the registration process completed it.") via: https://organize.org/blog/we-are-not-perfect-but-you-can-be.html

We'd like to provide this option if possible

**Comment by angaither** [comment]
since we changed this to a copy/paste link #6637 do we need this issue?

**Comment by ngjo** [comment]
I think the copy paste works, but could we keep this issue open and if there's time or a v2 optimization to look into the possibility of doing this? Can we put issues in a hold status or something?

**Comment by ngjo** [comment]
@angaither @sbsmith86 just reviewing the issues and I think this one is important, but I think the other issues are higher priority. This is a "nice to have" kind of thing
