### ISSUE TITLE
Update Kudos API to accept user query to help not kill the API on gallery

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6594]
Had a quick chat with @DFurnes regarding Kudos and the potential for the API to get overwhelmed...

With the advent of the new Kudos Reactions being activated, right now when viewing more items hits the `/reportback-items` endpoint and nests a [`kudos` object](https://gist.github.com/weerd/1f351d23468c5096b332d5317af1579b) which contains an array of the data. In the data is the term info, and then all the kudos items that were applied to that term along with the user information, etc. 

Lets say Kudos is very popular, and there end up being RB items with like 900 kudos hearts and variations in quantities among the rest. That is A LOT of data passed in a JSON response, when all we really care about is the term and the quantity and if the current user responded with a kudos to a particular RB item in the gallery. So something more to the effect of:

``` json
"kudos": {
  "data": [
    {
      "term": {
        "id": "641",
        "name": "heart",
        "total": 900,
      }
      "user_reacted": true,
    },
    {
      "term": {
        "id": "646",
        "name": "poo",
        "total": 102,
      }
      "user_reacted": false,
    }
  ]
}
```

@DFurnes suggested that maybe in the AJAX request we pass along the user id as a parameter, and then when querying for kudos, it can take into account the user id and add a boolean to the response to indicate whether they already reacted with that kudos term on a RB item. I think this would definitely help reduce the length of the JSON response _significantly_ if kudos proves to be popular.

Thoughts?

@angaither @DFurnes 

__NOTE: Currently I'm working on a interim solution for dealing with the client knowing if current user reacted to a *view more_ RB item added dynamically, by filtering through the list of kudos items in the current response and trying to match the user id. Totally not ideal, but will be much easier if we implement the above suggested approach and I can update this once the above is working._

Checklist:
- [x] Allow passing current user id as a URL parameter.
- [ ] Update the `/kudos` endpoint
- [ ] Update the `/reportback-items` endpoint which includes kudos data

**Comment by weerd** [comment]
@jessleenyc pinging you on this so you're aware of it :)

**Comment by angaither** [comment]
I'm down with this. 
but also `user-reacted:` not `userReacted` 😉

**Comment by weerd** [comment]
true. I forgot, but I think we actually use snakecase in the api instead of hyphens. anyhoo, cool. I'll make update once back from Staff Retreat!

**Comment by weerd** [comment]
Side note: Trying to approach this in a way that doesn't break the index `/kudos` endpoint, but it does bring to light that the main index `/kudos` endpoint is kinda worthless at the moment and maybe should be revised for future use. 

Currently, getting a list of all the individual kudos, doesn't seem to be of much use. Maybe the index could return all "approved for use" kudos terms and then within each organized by reportback and quantity of that kudos per each reportback or something? Not sure... defs not for the PR that will address this issue, but some food for thought, especially since nothing is currently using that endpoint, we could easily go in and fix it up!

Thoughts @DFurnes?

**Comment by weerd** [comment]
#6642 wasn't a full fix for this issue. Meant to reference this issue, not indicate it as fixed, so re-opening.
