### ISSUE TITLE
Translate Action Guide Field

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6596]
#### User Story

The action guide field is not translated, but should be, as it is very likely that there are different instructions we want to give for different experiences.

https://www.dosomething.org/admin/structure/types/manage/campaign/fields/field_action_guide
#### Additional Information (optional)

The field is under the "PLAN IT" section 

![image](https://cloud.githubusercontent.com/assets/12396076/15975734/0132b380-2f1d-11e6-8ce6-ca2ae77b1341.png)
#### Why This Matters

We want to be able to customize the experience as much as possible for different users.

cc @mnelson338

**Comment by angaither** [comment]
make sure this doesn't break the output of the action guide in the  `campaigns` API
