### ISSUE TITLE
Add Scholarship Confirmation to SMS Games

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6597]
#### User Story

As a member, I want confirmation that I have qualified for the scholarship. Currently, I don't get any. 😢 It would be great to have copy on this page (which I see after I submit my number and three friends' numbers) that notes I have been entered into the scholarship.

The copy could be a subtitle under "Thanks for sharing!" And read: "And you've entered to win the scholarship!"

![image](https://cloud.githubusercontent.com/assets/12396076/15976101/cb96b6b6-2f1e-11e6-9282-597a3b2d145e.png)

As a member of the member support team, I want members to know they were qualified for the scholarship without them having to ask.
#### Additional Information (optional)

We already have this functionality for non-SMS campaigns. 
![image](https://cloud.githubusercontent.com/assets/12396076/15976030/7543337a-2f1e-11e6-9a02-f81651359b3f.png)

Refs: 
https://github.com/DoSomething/phoenix/issues/4121
https://github.com/DoSomething/phoenix/pull/4122

Additionally, this confirmation copy should only appear if the SMS game has a scholarship attached.
#### Why This Matters

The member support team has flagged "Am I qualified for the scholarship?" as a frequent question coming from members who sign up for SMS games.

cc @mikefantini @hbghidey @jamjensen

**Comment by angaither** [comment]
the issue here is [these links are public](https://www.dosomething.org/us/campaigns/6798/confirmation) so we would need to check
1. is user logged in
2. did the user actually sign up?
3. are there other steps to be eligible for being entered here? do they need to complete the game?

**Comment by namimody** [comment]
@angaither: interesting point re: public links! Perhaps helpful thoughts follow: 
1. The most likely scenario is that a user is _not_ logged in before or after they fill out the SMS game form -- they would likely hit the site from Fastweb, not be logged in, fill out their name and four cell numbers, and then hit submit, never logging in. However, someone may have just reported back on a campaign and then found the SMS game and signed up, so then they would be logged in.
2. Er, hmm. Could we allude to the fact that the member needed to have signed up in order to be eligible for the scholarship?
3. @hbghidey in your opinion, what is the ideal copy based on what would be most clear to members and most true to the scholarship rules, and encompass both our thoughts above re #2? For the moment, I've recommended the copy could be a subtitle under "Thanks for sharing!" And read: "And you've entered to win the scholarship!" -- going to add this to our product/support agenda as well! ( @angaither that meeting is today, so we will circle back after -- thanks!)

**Comment by namimody** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ddu3rkT6&#x2F;10-sms-games-scholarship-confirmation"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> SMS games: Scholarship confirmation</a>

**Comment by hbghidey** [comment]
@namimody @angaither Ideal copy would be "Thanks for sharing! You've taken the first step in being entered to win the scholarship. Next step is to complete the game!" The message is relatively vague but  we can sprinkle additional context in the campaign page copy, FAQs and SMS confirmation message to let users know that the game will need to be shared and completed in order to be entered into the drawing. If we see spot additional confusion, we can readdress.

**Comment by angaither** [comment]
Sounds 🆗 !
I think it's probably fine to just show this message to everyone then, ya @namimody? 
![image](https://cloud.githubusercontent.com/assets/645205/16313658/3172ac1e-3948-11e6-8150-5f49c99b9079.png)

**Comment by angaither** [comment]
It looks like currently if there is a value in `field_reportback_confirm_msg` that is currently displayed in that `subtitle` section, so we would like to remove that and replace with this text?

**Comment by namimody** [comment]
- @hbghidey just a thought -- is it alright to always say "game" even if the SMS campaign is in the adviser template? is there a word that might be more encompassing but equally user friendly?
- @angaither oh wow, that's a great catch. hmm I think that it would be great to have this language hardcoded if the campaign has a scholarship, or perhaps make that field required and provide two examples of copy that could go there -- one for the advisor template and one for the choose your own adventure template.

@mikefantini do you have a preference?

**Comment by angaither** [comment]
@namimody since we already have this field, it might make more sense to have campaign leads fill out the text here if there's a scholarship on the game that way we don't need to worry if the advisor template doesn't need it, but games do

**Comment by namimody** [comment]
@angaither I think it's preferred if it's hardcoded and appears dynamically depending on if there is a scholarship or not. Both advisor and game templates can have scholarships -- and the hardcoding works really well on non-SMS campaigns. Additionally, I'd like to minimize the number of things that leads have to do manually, if this is a best practice for all SMS experiences with scholarships.

I think the best solution is to have this text appear below "Thanks for sharing!":

"You've taken the first step in being entered to win the scholarship. Next step is to complete the experience!"

This should work for all scenarios.

**Comment by sbsmith86** [comment]
@namimody @angaither Just want to confirm that If there is **no** scholarship, it should display the text in the `field_reportback_confirm_msg` but if there is a scholarship, we display the text outlined above?
