### ISSUE TITLE
Add Snapchat + We Heart It to Footer

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6598]
#### User Story

The digital marketing team would like us to update the social media icons in our footer to include Snapchat and We Heart It (and remove Tumblr). 

To turn on these icons, we first need to add the new Forge patterns to the array (IDK what I am really saying here, @angaither...sorry.)

![image](https://cloud.githubusercontent.com/assets/12396076/15976670/19840c5e-2f22-11e6-8641-1d5709d53585.png)
#### Additional Information (optional)

This is blocked by: https://github.com/DoSomething/forge/issues/557
#### Why This Matters

Want to be hip with what the kids are using.

**Comment by weerd** [comment]
@namimody @lkpttn do we have the svgs for these somewhere?

**Comment by namimody** [comment]
@weerd https://github.com/DoSomething/forge/issues/557 here!

**Comment by weerd** [comment]
oh, gotcha. Didn't realize that issue had it! Thanks @namimody

**Comment by weerd** [comment]
@namimody is there a preference? I'm seeing 3 on icomoon:

![image](https://cloud.githubusercontent.com/assets/105849/16238028/c6125c40-3793-11e6-8627-92f8769d294d.png)

I'm assuming the middle one, but want to make sure.

**Comment by namimody** [comment]
@weerd let's do the middle one!

**Comment by weerd** [comment]
cowabunga!
