### ISSUE TITLE
User Profile Kudos - Neg Numbers

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6605]
#### Current Behavior

Kudos going into negative numbers on user profile. 
#### Desired Behavior

Kudos numbers should toggle positively by 1. 
#### Steps to Replicate
- Navigate to user account page
- Click on heart.

![screen shot 2016-06-13 at 5 27 57 pm](https://cloud.githubusercontent.com/assets/14931921/16023773/5b241e8a-318c-11e6-86e9-9a51361ac00f.png)

**Comment by DFurnes** [comment]
Right now, we're deciding to increment/decrement the counter based on whether the AJAX response includes a `kid` value in the response (which is what successful kudos creations have).

It probably makes sense to explicitly check for each of the expected responses, and if it's something unexpected (like a permissions issue or 404 or something) just not update the interface.

**Comment by itsjoekent** [comment]
agreed -- checking for anything other than a 200 should work?

**Comment by DFurnes** [comment]
That seems like a good idea!

**Comment by itsjoekent** [comment]
hmm, so this is the error being logged in the console on staging

`Failed to load resource: the server responded with a status of 500 (Internal Server Error : An error occurred (23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4068-1700226-0' for key 'fid_uid_tid')`

**Comment by itsjoekent** [comment]
I just pulled the latest locally and I'm not having any issues or seeing that ^ though, could this have anything to do with stage?

**Comment by DFurnes** [comment]
It sounds like we might have a bug in our validation code for that endpoint (or are solely relying on the database constraint to prevent dupes). Either way, it'd definitely be good to have better client-side error handling and maybe do a little digging on the server-side endpoint.

**Comment by itsjoekent** [comment]
Yeah going to need more time for investigating the SQL error, in order to fix the negative numbers I'll quickly do the HTTP code check in the JS.

**Comment by angaither** [comment]
@deadlybutter I think the [`create` method](https://github.com/DoSomething/phoenix/blob/274089f4a40eb76e5483b210e6775b03deeaae87/lib/modules/dosomething/dosomething_kudos/includes/KudosController.php#L19) just needs to be wrapped in a `try` and it returns an error if a record already exitsts

**Comment by itsjoekent** [comment]
started fixing a bunch of errors in ^ -- still looking into why Kudos isn't incrementing (tried the create method try/catch).

is there a good way to debug in these API functions? cc: @weerd ?

**Comment by itsjoekent** [comment]
just gonna log some things I notice...

the values being passed into KudosController create function is missing a TID `"{"fid":"3541","uid":"1700226","tid":null}"`. That doesn't seem right.

Potentially related to ^, the Kudo being created def. does not look right.
`{"id":null,"term":null,"reportback_item":null,"use…:"3541","uid":"1700226","tid":null,"is_new":true}`

**Comment by itsjoekent** [comment]
this might explain the missing TID, figure template does not have `data-kudos-term-id` on the element, but its in photo template (where Kudos works)
