### ISSUE TITLE
Update or remove automatically calculated rb & signup numbers on campaign run nodes

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6614]
#### Current Behavior
- Automatically calculated rb & signup totals on campaign runs are not reflecting the correct numbers. 
#### Desired Behavior
- The automatic sign up calculation should be eliminated from the template. Since it will never reflect mobile sign up numbers, making it appear incorrect.
- The reportback number should only pull the impact count from reportbacks associated with the run, not from all runs of the campaign.
#### Steps to Replicate
1. log into drupal
2. search content by closed campaign and campaign run (i.e. 'notes from shawn')
3. select one of the runs
4. click 'edit'
5. scroll to and click 'what you did' 
6. click 'totals'
7. observe total participant and quantity numbers in gray (refs screenshot below)
#### Why This Matters

To avoid confusion, the numbers should be correct to avoid confusion. 
#### Relevant Screenshots + Links

![screen shot 2016-06-21 at 11 27 26 am](https://cloud.githubusercontent.com/assets/14931921/16236064/f8d0cf66-37a4-11e6-9e93-2b99c7b332ac.png)

**Comment by namimody** [comment]
@jessleenyc looks great! a few edits:

-- always a good idea to add a hyperlink to where the screenshot is from :)
-- I updated the issue title to say campaign runs v. Drupal to be more specific
-- you can remove the optional fields from the template if they aren't applicable to the particular issue
-- I added some labels and added the issue to the FRUGS Frenzy milestone
-- I updated the "Desired Behavior" and "Why This Matters" to be more specific and more broad, respectively. Let me know if you want to talk this out in person!
