### ISSUE TITLE
Competitions row is null/1 and no 0s

### ISSUE THREAD

**Issue by Bladt** [DoSomethingArchive/legacy-website#6617]
#### Current Behavior
- Queried `dosomething_signup` and all values are either `1` or `null` for `dosomething_signup.competition`
#### Desired Behavior
- `dosomething_signup.competition` should return `1` (yes to comp), `0` (no to comp) or `null`
#### Steps to Replicate
- query this: `select
  ds.competition, 
  count(*)
  from
  dosomething.dosomething_signup ds
  group by ds.competition
  `
#### Why This Matters

From an analytics perspective, makes reporting on competitions impossible. Need accurate data that differentiates between yes and no. Blocker for current reporting. 

From an operational perspective, I have no idea how/if this is impacting user experience or gladiator administration

cc @angaither

**Comment by angaither** [comment]
@Bladt as a not great workaround you can check for `dosomething_signup.signup_data_form_response = 0` &&  `dosomething_signup.competition = NULL`

**Comment by angaither** [comment]
I think we are only ever setting the value to 1 [here](https://github.com/DoSomething/phoenix/blob/ede9a4f85a414b6be18df1a2d99dd1a265027442/lib/modules/dosomething/dosomething_signup/dosomething_signup.signup_data_form.inc#L589)

@sbsmith86 mind taking a look at this one?

**Comment by Bladt** [comment]
@angaither  thanks! Just to be clear: all `0`'s in `dosomething_signup.signup_data_form_response` are being shown as `null` in `dosomething_signup`?

**Comment by angaither** [comment]
@Bladt whaaat
you'll be looking for this

```
select whatever
from dosomething_signup
where signup_data_form_response = 0
and competition = NULL
```
