### ISSUE TITLE
In form validation messages are not appearing

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6625]
#### Current Behavior
- In form validation messages are not appearing
#### Desired Behavior
- Error/success messages should appear
#### Steps to Replicate
- Fill out fields on the account creation form and confirm that messages like "Hi Mike" aren't appearing
#### Why This Matters
- Users are inputting incorrect information and not understanding why their entry does not work.
#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/6330971/16289160/cb1a4094-38c0-11e6-9d06-365a67a31205.png)

**Comment by mikefantini** [comment]
@DFurnes is this a quick fix? Not sure the scale but someone on twitter was unable to create an account because they were entering their birthday as /02 vs. /2002 and had no idea what was going on.

**Comment by DFurnes** [comment]
Hmm, that's a bummer. Taking a look. 👀
