### ISSUE TITLE
Kudos visual bug on the profile - Show more

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6628]
#### Current Behavior

When using the "Show More" functionality of the RB section of the profile, additionally loaded RBs have visual issues with the kudos.
#### Desired Behavior

Similar to the campaign template gallery, the additionally loaded images should display as the original set.
#### Steps to Replicate

Go to a profile and click "Show More" if the user has enough reportbacks.
#### Why This Matters

Users should be able to see how many kudos they have on their photos!
#### Relevant Screenshots + Links

![screen shot 2016-06-23 at 12 55 36 pm](https://cloud.githubusercontent.com/assets/1865372/16312638/a8ec1294-3943-11e6-83e0-cff31b5c914b.png)

**Comment by itsjoekent** [comment]
Looks fine to me, just click the box! 😆

**Comment by itsjoekent** [comment]
Ohhh the custom template the JS is using still has the old classnames, should be easy fix
