### ISSUE TITLE
Create and expose 'view on web' link

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6641]
#### User Story

As a user on the mobile app, I would like the option to view the web content only on the web without re-logging in. 
#### Additional Information
- Create a custom setting to hold `magic_link_copy` 
- Expose the the copy in the API

included in the `/campaigns` api response

```
magic_link_copy: click here to fill out the form on the web
```
#### Why This Matters

Some experiences (i.e. organ donation, filling out address forms) is only available on the web, instead of building this experience out for mobile, let's just forward the user to be authenticated to that campaign in a browser.

**Comment by aaronschachter** [comment]
@angaither @katiecrane I'm not seeing signs of the Magic Link in the API response, or in the [docs](https://github.com/DoSomething/phoenix/blob/dev/documentation/endpoints/campaigns.md) (refs #6669)

**Comment by katiecrane** [comment]
@aaronschachter ah I need to update the docs. Currently it is only being added to the response if there is copy in there. Do we want it to work differently? [Code is here](https://github.com/DoSomething/phoenix/blob/c0f3434549a1b3a598c4f857dbebcd844b18f8ea/lib/modules/dosomething/dosomething_api/includes/Transformer.php#L269-L272)

**Comment by aaronschachter** [comment]
I believe our standard behavior is to include the property with a null value when there's no copy:

<img width="871" alt="screen shot 2016-07-08 at 9 55 59 am" src="https://cloud.githubusercontent.com/assets/1236811/16695027/4dfe7d44-44f2-11e6-8226-88968359f6cc.png">

**Comment by katiecrane** [comment]
@aaronschachter ahh okay. Thanks @aaronschachter! I can fix that up
