### ISSUE TITLE
Pre-select state based on the inputted zip code

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6650]
#### User Story

As a user, if I input my zip code, I'd like the form to know what state I live in already. But if that's not possible (different API call), then it would be nice if the state wasn't pre-selected as Alabama.
#### Why This Matters

One less click! OR so we don't have false Alabama submissions.

Screenshot for what spot I'm talking about -- 11717 is in NY, so would like New York to be selected already or have nothing selected.

![screen shot 2016-06-29 at 2 28 07 pm](https://cloud.githubusercontent.com/assets/2658867/16469480/3b86873a-3e1f-11e6-95b5-dc567cac778b.png)

Related Issue: #6651

**Comment by angaither** [comment]
hrm. while this is a good idea, it would require a different api call to something like google maps or a different third party service & I'm not sure it's worth the effort.
I'm going to add a low-priorty label and if we have time we can address this

**Comment by ngjo** [comment]
Kk -- would it be easier than to make it so no state is selected (similar to this re: gender #6651 ) so then it's not accidentally submitted as Alabama?

**Comment by angaither** [comment]
@ngjo right, that would be the same thing as #6651 where we are providing custom options instead of what organize gives us

**Comment by ngjo** [comment]
@angaither Cool -- would that be easier/more possible than doing a diff. api call? And if so, should I edit this issue to be that instead, or leave as is for the time being?

**Comment by angaither** [comment]
@ngjo sure! editing the issue sounds 🆗

**Comment by sbsmith86** [comment]
@angaither @ngjo I **think** having no state selected would just require use to merge one custom option to the top of the state array they provide us. it's some custom work...not the worst, and definitely easier than hitting any other APIs
