### ISSUE TITLE
On default, have no gender selected on registration form

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6651]
#### User Story

As a user, I don't want the gender field to be pre-populated.
#### Additional Information (optional)

Here's a screenshot of what it's defaulting to:
![screen shot 2016-06-29 at 5 36 51 pm](https://cloud.githubusercontent.com/assets/2658867/16469610/016492b2-3e20-11e6-93f1-eeaf4d323f48.png)
#### Why This Matters

Don't want to make any assumptions around this

This could be related to Issue #6588 (which I'm meeting w/ Sam about tomorrow), or it could just say "Select" or something like that

**Comment by angaither** [comment]
yaa, this and #6588 bot require us to put custom logic around one question, since currently we are just printing out all the choices the Organize API returns

**Comment by ngjo** [comment]
👍!!! Will post up what Sam says about the gender stuff. Stay tuned!
