### ISSUE TITLE
Change "Show End Date" on Campaign Run to "Choose End Date"

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6659]
#### User Story

On the campaign run, the checkbox to select an end date says "show end date" -- this is misleading because:
1. there is a show end date checkbox on the campaign node, which makes the end date appear in the header photo, and this checkbox serves a different purpose.
2. if someone clicks this checkbox on the campaign run, it shows the same date as the start date. this appears as though the end date has actually been set, but Drupal is really just populating the field.

We should:
1. change the text from "show end date" to "select end date"
2.  if possible, the end date field should not autopopulate with the start date listed on the campaign run. (if this is not possible, we'd like to amend the help text as cited below -- please let us know if that's the case!)
3. Add help text to the Timing part of the form

> These dates determine whether the campaign is open or closed. If the run has no end date selected, it will appear open. If the campaign does have an end date, the campaign will automatically switch to the closed state at 12:05 AM the day after the end date. If the campaign is translated and open across different translations, then the start and end dates must be correctly set for _every_ translation of the run."

https://www.thor.dosomething.org/us/node/6810/edit/en
![image](https://cloud.githubusercontent.com/assets/12396076/16492409/ac86c3ce-3eaf-11e6-8e5e-dddb133ced09.png)
#### Why This Matters

It's confusing to have to set the end dates on both the run and the campaign, but this should help clear up that distinction.

cc @ngjo

**Comment by angaither** [comment]
1. change the text from "show end date" to "select end date"
   this is default drupal text to physically display the end date field on the back end. We can remove that text if we require the end date on the field itself, which I don't think is something we want to do, since we don't know always when runs end
2. if  possible, the end date field should not autopopulate with the start date listed on the campaign run 
   There shouldn't be a default text here, it's not selected to have a default. If there's a default displaying it may be an issue with the drupal date module. field settings below
   ![](https://i.imgur.com/5K2Se5S.png) 
3. add help text
   no problem!

**Comment by namimody** [comment]
Thanks for the notes here, @angaither!

1) Bummer. I'll just make a note to mention this confusing language in campaigns/tech sync.
2) Hmmm...looks like there is a problem with the Drupal Date Module. For example, if you click "Show End Date" on this run, it auto-fills in with the start date. https://thor.dosomething.org/us/node/6191/edit/en

3) Adding help text would be great! Given what we now know about points 1 and 2, let's make the help text as follows:

"These dates determine whether the campaign is open or closed, and group sign up and reportback activity. If the run has no end date selected, the campaign will stay active. If the campaign run does have an end date, the campaign will automatically switch to the closed state at 12:05 AM the day after the end date. 

To select an end date, click "Show End Date" and use the dropdown menu to select a date. Be sure the date is correct, and not simply the date that autofills in the field. If the campaign is translated and open across different translations, then the start and end dates must be correctly set for every translation of the run."

**Comment by angaither** [comment]
did all of this but the autofill date thing
