### ISSUE TITLE
Randomize the reportback gallery 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6660]
#### User Story

As user I want to see random items in the gallery, not the most recent items in the gallery
Remove the order by call [here](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback_item.query.inc#L96), or just update the call to the endpoint to fetch random reportbacks
#### Additional Information (optional)

This also might help with the slow query we are seeing #6616 
#### Why This Matters

We want new members to see DS as a community that encourages each other's actions through liking one another's photos. Currently we have the gallery set up in such a way that when you view more beyond the original 6 it is ordered by most recent. This naturally will prioritize photos that will have the least amount of likes making it appear as if there is even less activity on the platform than there currently is. We're hoping that by listing by random this will show a mix of likes on photos showing both activity and not setting up a situation where the same photos always get likes and others get ignored.

**Comment by weerd** [comment]
Howdy!

@jessleenyc @lkpttn part of the reason I suspect there isn't enough randomization in the gallery is that based on the last update we did to the gallery, it was specified that we want to showcase _promoted_ Reportback Items in random order first and then showcase _approved_ items in random order. 

If there are very few promoted items then you will typically see those same items in the initial gallery. If we want more randomization, then we would need to not actually treat promoted items as _promoted_ and just mix them in with the rest of the approved, but then we'll have less of the really great user Reportback Items showing prominently in the campaign gallery.

Just want to provide some context for how it currently works, to help find a solution to the logic for how the items are showcased.

**Comment by jessleenyc** [comment]
Hi @weerd!

I was under the impression that after a user clicks 'view more' the photos shown are most recently approved photos, _not_ approved items in random order.  

But to confirm, what we currently have is random promoted photos in the initial 6 photo gallery. Then after you click 'view more' we're currently grabbing random approved photos, not sorted by time?

**Comment by jessleenyc** [comment]
@weerd, to clarify -- we want to keep the first six photos as promoted random and the 'view more' photos that show up as approve random.

**Comment by weerd** [comment]
@jessleenyc so, there's a pretty major issue that will keep us from actually randomizing the "approved" items in the view more. For the view more to work, we rely on the pagination to allow us to not end up completely repeating the same items multiple times in a row AND so that we have an actual total that we can rely on to use when it's paging through Reportback Items.

If we randomize the view more, it completely breaks the pagination since we won't know what's been shown and what hasn't etc. I forgot that @mikefantini and I had a chat about this during the second round of updates we did to the gallery which brought us to its current state.

**Comment by jessleenyc** [comment]
@weerd:

1) is there another way to avoid repeating items?
2) what do you mean by having an actual total?

**Comment by weerd** [comment]
@jessleenyc 

1) Not that I know of unfortunately. The current functionality is based on functionality that the API was built to support. The idea being that when you click `view more`, it asks the API for page 1 of the collection of RB items for that Campaign (excluding the first 6 randomly selected promoted items) already displayed. Clicking `view more` again will grab page 2 of the collection, and so on until you've displayed the _total_ RB items available for that campaign.
2) I misspoke: so while we would have a total number of items, the context for how a randomly selected grouping of 12 RB items is gathered breaks the pagination we rely on to make the view more work. Based on how the code works, the pagination relies on the query being exactly the same each time, except for asking for the next 12 items (next page) in a known, ordered collection of RB item results. If the items are randomized, the query is different every time and thus pagination is no longer a thing.

**Comment by weerd** [comment]
Just as a separate note, the idea behind how we implemented`view more` and pagination is get the ordered collection, and allow the member to keep seeing more and more items to their hearts desire until they got to the first approved submission on the campaign.

If we want a random collection of items, we could just say the `view more` is to become a one time click button and grabs a random assortment and plops it into the gallery. You only click it once and that's it. No clicking to page to go through the collection of reportbacks...

That would be entirely changing how that section works, but tossing this out there for discussion as a potential option.

**Comment by mikefantini** [comment]
@weerd are there any performance concerns with the approach of one `view more` shows all photos? Also for this are you saying that this would just show a set number of random photos but not give the user the option of seeing all reportbacks?

**Comment by weerd** [comment]
oh totally. I wasn't suggesting loading all the RB items with the single view more click... just like a set number (20? 30?) of random items but that's it.

And "yes" to the second question.

**Comment by jessleenyc** [comment]
@weerd can we keep pagination by pulling two pages at once--so every time we 'view more' it's pulling in 24 recent items but we get a wider assortment to randomize?

**Comment by weerd** [comment]
@jessleenyc yep. We can change the number of items per page. So still 1 page at a time but with 24 items. The only requirement is that the number per page be divisible by 4, 3, and 2... so the number of items displayed works nicely on desktop, tablet, and mobile respectively, without an odd item hanging out alone in a row.

**Comment by weerd** [comment]
> but we get a wider assortment to randomize?

Are you saying randomize within the grouping delivered per page? So always the same 24 on page 1 but randomize the visual order of those 24?

**Comment by weerd** [comment]
@jessleenyc Update. @mikefantini and I chatted IRL. 

One potential solution to look into is to initially grab a random assortment of 18 items (choosing from promoted first, then approved). Show the first 6 items as usual in the initial gallery, then on _first click_ of the **view more** button, we show the rest of those 12 items... only on _second click_ of the **view more** do we then send an API call to query the DB and get the ordered and paginated list of items.

There's going to be some lift for this since it impacts both the backend and the frontend for the gallery.

**Comment by jessleenyc** [comment]
Thanks for the update @weerd.  A couple Qs:

-Do you know if we're able to track how often members click on 'view more'?
-Would you be the only engineer working on this ticket or will it involve more people since it's both front and backend work?

**Comment by mikefantini** [comment]
@jessleenyc I'm putting in a data request now to see how often people click on `view more`

**Comment by jessleenyc** [comment]
@mikefantini can we pause on this ticket until we get that info so focus is on onboarding?

**Comment by weerd** [comment]
@jessleenyc to answer the second item, yes, I think so. I did the work on both the front-end and back-end for the gallery stuff including the API it uses, so I'm probably the one most familiar with all that.

**Comment by mikefantini** [comment]
I totally agree @jessleenyc. Here is the data card https://trello.com/c/KDxek96I

**Comment by jessleenyc** [comment]
Great - to add, we have a manual push coming in for kudos tomorrow so we'll get some additional likes there. Let's de-prioritize this and focus on onboarding.

**Comment by weerd** [comment]
sounds good.

**Comment by jessleenyc** [comment]
07/12 - 07/29 
Total Unique Action Page Views: 20,297
Total Unique 'View More' Clicks: 2,204
Members Who View Additional Gallery Photos: 10.85%

**Comment by angaither** [comment]
@jessleenyc can we tell how many times the user clicked view more?

**Comment by jessleenyc** [comment]
@angaither as in,  **total** 'view more' clicks? 9,133

**Comment by angaither** [comment]
@jessleenyc no, you can click the 'view more' multiple times, I'm curious if someone clicks it 1 time, or 20 times

**Comment by jessleenyc** [comment]
@angaither Not sure how to find that answer via google analytics. I'll put a request with @bladt in.

**Comment by angaither** [comment]
closing this out, we can re-open if we want to re-visit this in the future
