### ISSUE TITLE
Display onboarding on a campaign signup

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6662]
#### User Story

As a user, after I signup for a campaign I would like to see onboarding message box 
#### Additional Information (optional)

This should happen the first time and only the first time the authenticated user sees the action page.
This should appear on every single signup the user makes

**Comment by sbsmith86** [comment]
@angaither is this still a thing?

**Comment by angaither** [comment]
@sbsmith86 I mostly assigned this to you to see if any of the functionality you and @chloealee created could work for this

**Comment by sbsmith86** [comment]
@angaither ahh i can work on it...but wasn't sure how it fit in with the way @weerd and @deadlybutter were building this, since it seems they are rebuilding from the bottom up.

**Comment by angaither** [comment]
@sbsmith86 nah, that's fine I'll unassign you.
