### ISSUE TITLE
Run Scary SQL Update Command for Incorrect Runs (Elephant Tusk Force and Dunk You Very Much)

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6673]
### Elephant Tusk Force

Currently, the Elephant Tusk Force campaign has two translations. The US EN translation is set to run 2 (node 6810) with start and end dates during April of 2016. This translation is now closed.

The GL EN translation is set to run 1 (node 6556) which is translated, but both translations of the run have a start date in August of 2015, and no end date. Therefore, the campaign appears open to global users, allowing them to sign up and report back. If we would like to have this campaign open for GL EN members, we need to create a run 3, and set the GL EN translation to run 3. However, we now have data flowing to run 1 for the members that saw the GL EN translation of the campaign.

The best course of action would be to associate all activity from:

August 27, 2015 - February 29, 2016 with RUN 1 (node 6556)
March 1, 2016 - March 31, 2016 with RUN 2 (node 6810)
April 1, 2016 - April 30, 2016 with RUN 3 (node 7011)
May 1, 2016 - present with RUN 4 (node 7053)

And detailed here: https://trello.com/c/Fr5S1cs1/1567-elephant-tusk-force-reportbacks-came-through-while-campaign-is-in-closed-state

Campaign link for reference: https://www.dosomething.org/us/campaigns/elephant-tusk-force
### Dunk You Very Much

The GL EN translation of Dunk You Very Much (https://www.dosomething.org/node/6647/edit/en-global) didn't have a close date, but it was supposed to have been closed on April 1, 2016 to coincide with the US EN run. We just added the end date to close out this campaign.

We'll need to do a similar thing w/ the data here -- create a new Run (in GL EN) and attribute the activity received after April 2, 2016 to that new run. The run should have a start date of April 2, 2016 and no end date (we want to keep this GL EN translate campaign open indefinitely).

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Fr5S1cs1&#x2F;1567-elephant-tusk-force-reportbacks-came-through-while-campaign-is-in-closed-state"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Elephant Tusk Force reportbacks came through while campaign is in closed state</a>

**Comment by jessleenyc** [comment]
Issue moved to [DoSomething/quasar #218](https://github.com/DoSomething/quasar/issues/218) via [**ZenHub**](https://www.zenhub.com/)
