### ISSUE TITLE
Discrepancy in # of Kudos

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6685]
#### Current Behavior
1. Likes on action page gallery are not matching likes on permalink page or profile
2. Likes on permalink page and profile are being stored incorrectly (i.e. liking something on the permalink page is not adding to the overall kudos count)
#### Desired Behavior
1. If a photo has 9 likes it should have 9 likes everywhere we display kudos.
2. If I like a photo on the permalink or profile I want it to be liked everywhere
#### Steps to Replicate
- Look at a photo in the gallery. 
- Check to see if the # of kudos matches on the permalink for that photo or the profile of the user.
- Confirm that it does not.
#### Why This Matters
- The data should be the same across the site. It's confusing for users to see different # of likes in different places.
#### Relevant Screenshots + Links
- Profile: https://www.dosomething.org/us/user/2956739

![image](https://cloud.githubusercontent.com/assets/6330971/16633239/5172224e-4396-11e6-81ab-27b822f605cd.png)
- Permalink: https://www.dosomething.org/reportback/97544

![image](https://cloud.githubusercontent.com/assets/6330971/16633231/4909650e-4396-11e6-8020-607f55cc3e17.png)
- Gallery: 
  https://www.dosomething.org/us/campaigns/thumb-wars

![image](https://cloud.githubusercontent.com/assets/6330971/16633201/15cc8a4a-4396-11e6-947e-a492540d46eb.png)

cc: @jessleenyc

**Comment by itsjoekent** [comment]
just a note for when i debug tomorrow -- noticed the data-kid seemed to be blank

**Comment by angaither** [comment]
@deadlybutter might be nice to take this as an opportunity to condense this into some shared code!

**Comment by itsjoekent** [comment]
Oh i think I found the problem, the perma link is using RBID, campaign template is using FID
