### ISSUE TITLE
POEditor Refresh for Phoenix Language Updates

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6686]
#### User Story

We have a couple of things we need to update across all global experiences. To do this, we need to add the string to the PO file and import into POEditor, then translate, export and import back into production.
#### Additional Information

Text Strings: 
###### Problem Share Prompt

Original US EN:
"F that, spread the word"

Updated US EN:
- [x] "Share this stat with friends"

We are going to leave the Portuguese and Spanish translations the same, even though the US EN language is changing.
###### Member Count Token

Original US EN: 

Updated US EN:

Instead of the member count on the site ticking up using a dynamic "member count" token, we'd like to set it at 5.3 million members.
###### Mic Drop

Original US EN: 
DoSomething.org makes the world suck less. One of the largest orgs for young people and social change, our millions of members tackle campaigns that impact every cause, from poverty to violence to the environment to literally everything else. Any cause, anytime, anywhere. _mic drop_ 

Updated US EN: 
- [x] DoSomething.org makes the world suck less. One of the largest orgs for young people and social change, our millions of members tackle campaigns that impact every cause, from poverty to violence to the environment to literally everything else. Any cause, anytime, anywhere.

We are removing "mic drop" from branding per the request from Ben here: https://trello.com/c/tN8pKBnB/1560-please-remove-mic-drop-from-mobile-and-my-entire-life

In POEditor, there is also simply the "*mic drop" string -- this should be removed as well.
#### Why This Matters

The original problem share prompt has been flagged a number of times by sponsors for language. We would like to change that language on the US EN site, as well as make some other brand updates.

**Comment by weerd** [comment]
```
Member Count Token

Original US EN:

Updated US EN:

Instead of the member count on the site ticking up using a dynamic "member count" token, we'd like to set it at 5.3 million members.
```

@jessleenyc @ngjo @angaither Not really sure what the above section in the issue description means or how it relates translation stuff...?

**Comment by weerd** [comment]
The "*mic drop" removal doesn't really matter. If we have removed references to if from the site, then it just won't get translated. We can have a cleanup issue of the POT files if needed after all the new ones get merged.

It matters more when new text is added that needs to be translated, rather than the removal of text.

**Comment by weerd** [comment]
Imported the two updated terms into POEditor. Since we're reusing the same Spanish and Portuguese translations for the two items that were updated, I added the same translations to the the new terms now in POEditor (so at least these two are translated).
