### ISSUE TITLE
Registration form data not logging in user profile

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6692]
#### Current Behavior

I've completed the registration form and looking at my user profile, but it looks like only the last name was added.
#### Desired Behavior

Name, Address, and Birthday should all be logged in user profile (and I think in this instance, 'Address' referred to the entire address -- street, city, state, zip -- but correct me if I'm mistaken here).
#### Steps to Replicate
1. Create a dummy account
2. Sign-up for campaign
3. Take note of what's not pre-populated
4. Complete form
5. Check profile page
#### Why This Matters

Capturing info to build out user profiles
#### Relevant Screenshots + Links

This is what was empty when I got to the registration form:

![screen shot 2016-07-07 at 3 30 28 pm](https://cloud.githubusercontent.com/assets/2658867/16668002/2640790a-445d-11e6-9a81-99b2b799de62.png)

This is my user profile -- only "last name" was filled in:

![screen shot 2016-07-07 at 4 11 14 pm](https://cloud.githubusercontent.com/assets/2658867/16668202/0def8412-445e-11e6-85f5-aeb47ddd555a.png)

Related: #6658

**Comment by katiecrane** [comment]
The changes are showing up at `/user/{id}/info` and in the database... open Q: does the user profile pull from a different place?
