### ISSUE TITLE
Add Custom Event To Fire In Google Analytics For "View More"

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6698]
#### User Story

As an admin, I'd like to see how often members click on 'view more' to see more photos in the reportback gallery.
#### Why This Matters

This will help inform the decision we make on whether or not to pursue randomizing the reportback gallery -- https://github.com/DoSomething/phoenix/issues/6660

**Comment by sbsmith86** [comment]
@jessleenyc is there a way you would like this tracked/categorized in Google Analytics. 

![image](https://cloud.githubusercontent.com/assets/1700409/16742107/44786dbe-4774-11e6-90d8-5fab593ba93f.png)

The image above outlines the three parameters we send to GA with the click event. I wanted to check if you had a preference on what the values should be for `category`, `action`, and `label` for tracking this particular interaction.

**Comment by jessleenyc** [comment]
@sbsmith86 

eventCategory = "Gallery"
eventLabel = "View More Clicks"

Thank you!

**Comment by sbsmith86** [comment]
During testing, noticed that the button is added after page load and didn't see any requests going out to GA from staging. I need to rebind the click tracking after the button is added to the page.
