### ISSUE TITLE
JavaScript - "Drupal is not defined"

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#670]
Seeing this locally across multiple files with Neue/Paraneue up to date. Database/Drupal install is two days old.
![js-error](https://f.cloud.github.com/assets/1479130/2162225/cd8560e4-94cf-11e3-9b08-5c7574ab323a.png)

**Comment by DFurnes** [comment]
Yep, that's because we're killing the `Drupal` JSON script element so any scripts that rely on it are erroring out. We should be killing the rest of these scripts before launch, so likely not an issue. Worst-case, we re-enable the `settings` script block.

**Comment by DFurnes** [comment]
See DoSomething/paraneue#15 for some more context.
