### ISSUE TITLE
FAQ link in contact us modal not clicking through

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6705]
#### Current Behavior

When you go to a campaign and click the "Questions? Contact Us" -- the FAQ link in the contact modal doesn't click through to anything (stays on the contact modal).
#### Desired Behavior

When you click the FAQ link, it should bring the user to the FAQs. 
#### Steps to Replicate
1. Go to any campaign, for example: https://www.dosomething.org/us/campaigns/skype-senior
2. Click on "Questions? Contact Us" in the lower right hand corner
3. Try to click "check our FAQs"
#### Why This Matters

So the user can get to the FAQs.
#### Relevant Screenshots + Links

![screen shot 2016-07-11 at 10 41 39 am](https://cloud.githubusercontent.com/assets/2658867/16734986/6ca8483c-4755-11e6-9bc2-e9ba137f00ff.png)

Related issues: #6062

**Comment by ngjo** [comment]
@angaither  Would it be possible to tackle this as soon as possible? It's affecting every campaign, including sponsored campaigns, and I imagine, is frustrating for the user. Thanks!

cc @namimody

**Comment by katiecrane** [comment]
@ngjo @angaither I think this is actually only broken for closed campaigns

**Comment by ngjo** [comment]
@katiecrane ahhh yeah, you're right! looks like it's working for open ones (https://www.dosomething.org/us/campaigns/supermarket-stakeout)

**Comment by katiecrane** [comment]
@ngjo does it make sense to not have a link to FAQs on closed campaigns? I'm guessing even if we could pull them from the previous time, they might change by time it opens again

**Comment by ngjo** [comment]
@katiecrane Would it be possible to link to the domain FAQs https://help.dosomething.org/hc/en-us for closed campaigns?

If the FAQs change, then yeah, we might not want to link to them. If linking to the help center isn't an option, could we just remove the FAQ language from modals on closed campaigns?

cc @namimody -- what do you think?

**Comment by katiecrane** [comment]
@ngjo I thiiiiiink that we can do that. We for sure can remove the FAQ language from the modals on closed campaigns though.

**Comment by namimody** [comment]
I think linking to the help center is a good idea, can we change the language on the modal for closed campaigns though @katiecrane?

**Comment by katiecrane** [comment]
@namimody I'm pretty sure we can since I got the FAQ copy to disappear on closed campaigns, so it's just a matter of adding it in.

**Comment by namimody** [comment]
Great @katiecrane -- how does that sound to you @ngjo? If 💯, want to take a stab at the copy pointing to the Help Center from a closed campaign Contact Us modal?

**Comment by ngjo** [comment]
Works for me!

@namimody Here's some proposed copy -- let me know how I can tweak.

Before submitting your question, be sure to check out our in-depth [Help Center](https://help.dosomething.org/hc/en-us) to see if it's been answered before!

Before submitting your question, be sure to check out our in-depth [Help Center](https://help.dosomething.org/hc/en-us) where we provide a tons of answers to frequently asked questions!
