### ISSUE TITLE
Campaign finder CAUSE area pre-selecting when TIME chosed

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6719]
#### Current Behavior

When conducting usability tests, a user selected TIME, **2-5 hours**, as their first option and then  **Health** was automatically selected in the CAUSE drop-down. 

Tried recreating this as both an admin or a member, but didn't happen either time...not sure if this  a known issue, but wanted to flag here. Video is attached.
#### Desired Behavior

A cause space shouldn't be pre-selected -- especially since there are campaigns in the other cause spaces that exist for the 2-5 hour range (see screenshot of our attempt to recreate)
#### Steps to Replicate

Unable to replicate, but if you wanted to try:
1. Go to DS homepage
2. Select 2-5 hours in the TIME drop-down
3. Health should be pre-selected
#### Why This Matters

Bad user experience
#### OS/Browser (optional)

Google Chrome/ OS X
#### Relevant Screenshots + Links

Link to User Video: 
https://dosomething.slack.com/files/hannah/F1RGNNFHT/campaign_finder_bug.mov

How it's appearing when we try to recreate the issue (CAUSE is not pre-selected as Health):
![screen shot 2016-07-13 at 6 25 47 pm](https://cloud.githubusercontent.com/assets/2658867/16821938/442f558e-4927-11e6-9b6f-bb2724445279.png)

cc @hbghidey

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;R880wBWt&#x2F;1587-campaign-finder"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Campaign Finder</a>

**Comment by angaither** [comment]
hmmm, I'm also unable to replicate this.

**Comment by ngjo** [comment]
what's the best process for things that aren't replicable...should i still post an issue for your investigation and then we just close it for when it might come up again?

**Comment by angaither** [comment]
@ngjo I think if we can't replicate it I'm not sure if it needs an issue? It might belong in the trello board till we can replicate things.

**Comment by ngjo** [comment]
kk, sounds good! will do that moving forward -- thanks @angaither (closing this out for the time being and updating trello card)
