### ISSUE TITLE
Disable the Onboarding component on Closed Campaigns

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6729]
@jessleenyc @lkpttn  I'm assuming we _don't_ want to show the Onboarding stuff on closed campaigns? I believe currently it will display on those campaigns. While considering this, are there other campaign types we don't want it to show on? Grouped campaigns (are those still a thing?)

cc: @angaither

**Comment by angaither** [comment]
I think we are actually ok here, since we only want to show onboarding AFTER a signup, since there aren't signups on closed campaigns, this shouldn't be an issue.

**Comment by weerd** [comment]
Currently the logic for campaign pages only excludes **pitch pages**, so the onboarding feature is showing for closed campaigns. Upcoming PR will keep this from happening.

**Comment by jessleenyc** [comment]
@weerd just catching up on this. We don't want onboarding to show on SMS only games -- will this PR account for that? I was under the assumption it wouldn't show because there is no 'sign up' button but since it was showing for closed campaigns, wanted to flag.

**Comment by weerd** [comment]
Hey @jessleenyc, forgot to ping you back. Yep, the PR that closed this issue also account for _not_ showing the Onboarding experience on sms games :)
