### ISSUE TITLE
Staff Pick not translated in staging

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6747]
#### Current Behavior

staff pics is not translated
#### Desired Behavior

staff pics should be translated
#### Steps to Replicate
1. Login to staging
2. Go here: https://staging.dosomething.org/us/node/1286/edit (or any other campaign)
3. Scroll to "Taxonomy" section
4. See this:
   ![screen shot 2016-07-25 at 10 43 48 am](https://cloud.githubusercontent.com/assets/2658867/17105300/aaa9205c-5254-11e6-83a4-fc93e70bbd9c.png)
#### Why This Matters

should be translated and something went wrong when the script was run to translate it

**Comment by angaither** [comment]
closing for #6631
