### ISSUE TITLE
ds script – update sandbox environment with content from staging site

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#675]
Update `dev` flag of `ds build` to pull the latest from the staging database rather than generating placeholder content.

**Comment by aaronschachter** [comment]
This is related to / possibly duplicating #607

**Comment by mmwtsn** [comment]
Good catch. Should this exist as a new flag or a replacement for `dev`?

**Comment by desmondmorris** [comment]
The steps documented here should do it for you.  This needs more eyes to test

https://gist.github.com/desmondmorris/3c5dd8392a26efc5a840

**Comment by mshmsh5000** [comment]
@mmwtsn @desmondmorris Make sure you see [my addenda to those instructions](https://gist.github.com/desmondmorris/3c5dd8392a26efc5a840#comment-1178746).

**Comment by desmondmorris** [comment]
@mshmsh5000 yah thanks for that.  I mentioned some of this here: https://github.com/DoSomething/dosomething/pull/789
