### ISSUE TITLE
CSS changes for the form

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6751]
#### User Story

As a user, I want to look at a form that only has what's necessary. 
#### Additional Information (optional)
- [x] translate field from all form pages
  ![screen shot 2016-07-26 at 10 19 43 am](https://cloud.githubusercontent.com/assets/2658867/17141579/7d91ed30-531a-11e6-964d-006cc39810f1.png)
- [x] "Some states offer online voter registration. Learn more." from all form pages
  ![screen shot 2016-08-02 at 1 38 46 pm](https://cloud.githubusercontent.com/assets/2658867/17338757/a5f7a994-58b6-11e6-8f66-99df1548d24f.png)
- [x] survey questions
  ![screen shot 2016-08-02 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/2658867/17338795/e60e81c4-58b6-11e6-8a9d-a21c5b6997e7.png)
- [x] "Receive email from DS" and "Send me txt messages from"
  ![screen shot 2016-08-02 at 1 44 04 pm](https://cloud.githubusercontent.com/assets/2658867/17338869/3d6f470a-58b7-11e6-95eb-0fe7d6d7511e.png)
- [ ] text changes to the "hang on. you are eligible to register online in your state" page

Option 1: delete this entire page of the form and just have the next registration page pop up 

Option 2:
(waiting on final language for this, but here's tentative to give you an idea of what's going on)
**Title**: "Woohoo! Let's get you registered to vote!"
**Delete**: "You can complete your voter registration online with the state right now - using the application provided by Secretary of State.
If your driver's license or state identification card is invalid or the state can't find or confirm your DMV record - don't worry - you can also finish your registration with Rock the Vote. You will just have to print, sign, and mail it in."
![screen shot 2016-08-02 at 1 46 17 pm](https://cloud.githubusercontent.com/assets/2658867/17338934/9a2edffa-58b7-11e6-9e19-4519d1caf753.png)
-[ ] swap link on "continue" button or delete and add back in a new button -- when someone clicks "continue" it should go to the next page of the RTV form
![screen shot 2016-08-02 at 1 51 28 pm](https://cloud.githubusercontent.com/assets/2658867/17339083/46771da4-58b8-11e6-9186-85475500e17b.png)
-[ ] remove thigns from 2nd to last page of form
![screen shot 2016-08-02 at 1 52 53 pm](https://cloud.githubusercontent.com/assets/2658867/17339145/8f31311a-58b8-11e6-941a-c0680093f2bf.png)
![screen shot 2016-08-02 at 1 54 20 pm](https://cloud.githubusercontent.com/assets/2658867/17339179/b7f9959c-58b8-11e6-8e57-e9eac019f087.png)
- [ ] add text to download page of the form
  Current: "You still need to sign and mail in your form."
  Change to: "You still need to sign and mail in your form to be officially registered to vote."
  ![screen shot 2016-08-02 at 1 55 55 pm](https://cloud.githubusercontent.com/assets/2658867/17339262/1bb267b2-58b9-11e6-983f-012d97a73b6e.png)
- [ ] edit the form's social shares (edit them or remove in lieu of ours). Are we able to edit what is in their social shares? If not, let me know and I will provide more information for this.
  ![screen shot 2016-08-02 at 1 56 18 pm](https://cloud.githubusercontent.com/assets/2658867/17339279/278f5cb6-58b9-11e6-85bc-49bab808cf53.png)

Let me know if you need more detail on any of these! Thanks!

**Comment by angaither** [comment]
edited the files and @ngjo will send them off to RTV

**Comment by ngjo** [comment]
sent!

**Comment by ngjo** [comment]
update -- she's been super swamped but will be looking into this now

**Comment by ngjo** [comment]
update -- jen at RTV has pushed all of the changes but there looks like there's a small additional change (mobile field is required even tho we've cut that checkbox). we're trying to get her to remove this ATM; otherwise, we're good to go on this front

**Comment by ngjo** [comment]
all changes are live -- we couldn't get everything, but it's been approved by lizzy. closing out, thanks!
