### ISSUE TITLE
Suppress Welcome/Sign Up Site Notifications 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6753]
#### User Story

As a user, I don't want to see two notifications in the smasher that confirms my sign up or welcomes me to DS. 
#### Additional Information (optional)

Let's suppress / remove messages that offer the same information as onboarding for campaigns that will be presented with onboarding. We should keep messages pertaining to competitions or error messages. 
#### Why This Matters

The onboarding experience confirms sign up & welcomes the user to DS. We shouldn't send them the same message twice.

**Comment by mikefantini** [comment]
@deadlybutter after chatting w/ @jessleenyc seems like this one is actually the blocker for releasing screen 2 not #6688. Updating the labels now.

**Comment by itsjoekent** [comment]
okie dokes
