### ISSUE TITLE
Add GIF or Video to Screen 2

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6757]
#### User Story

As a user, I want to see exactly how to complete a campaign. 
#### Why This Matters

We've received feedback that users will often complete a campaign but not reportback. We hope this will show users how easy it is to reportback and that reporting back is part of completing a campaign.

**Comment by jessleenyc** [comment]
Currently blocked by file size -- @deadlybutter please follow up with @DFurnes to see if using a video on mobile is a temporary solution for when we only have 1 screen present.

**Comment by jessleenyc** [comment]
Since we'll be able to load gifs behind the scenes when we have more than one screen for onboarding, we've decided on a temporary fix for v1. We'll be using video files on both desktop & mobile. Desktop videos will autoplay while mobile videos will have a visible play button.

**Comment by DFurnes** [comment]
Good news is that the mobile `<video>` restrictions [are getting relaxed](https://webkit.org/blog/6784/new-video-policies-for-ios/) in iOS 10 so we'll only have to compromise with a "play" button for a little bit. 😄

**Comment by jessleenyc** [comment]
@DFurnes will the video still go into full-screen mode?

**Comment by DFurnes** [comment]
Nope! From the linked blog post:

> On iOS 9, `<video>`s will only begin playing as a result of a user gesture. So pages which replace an `<img>` with a `<video>` will require a user gesture before displaying their animated content, and, on iPhone, the `<video>` will enter fullscreen when starting playback.
> 
> Starting in iOS 10, WebKit relaxes its inline and autoplay policies to make these presentations possible, but still keeps in mind sites’ bandwidth and users’ batteries.
> 
> By default, WebKit will have the following policies:
> - `<video autoplay>` elements will now honor the autoplay attribute, for elements which meet the following conditions:
>   - `<video>` elements will be allowed to autoplay without a user gesture if their source media contains no audio tracks.
> - …
> - On iPhone, `<video playsinline>` elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
