### ISSUE TITLE
Grid – Wider Container Needed

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#676]
The width of our container with full-width background images needs to be wider than the default 1200px. If we are still interested in using a 13" MacBook Air's built-in monitor as reference the min-width of the container needs to be 1401px.

I vote 1440px.

**Comment by DFurnes** [comment]
That seems reasonable to me. :+1:

**Comment by DFurnes** [comment]
Was too eager. Re-opening this guy so we can deal with this later. :bike:

**Comment by mmwtsn** [comment]
Good effort! We'll revisit when we're not crunched for time.

**Comment by barryclark** [comment]
Removing milestone and assigning @DFurnes
