### ISSUE TITLE
Store whether or not a user was presented with onboarding at sign-up 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6761]
#### User Story

As an admin, I want to know if a user was shown the onboarding flow when they signed up for a campaign. 
#### Additional Information (optional)

Per our data discussion, we should consider storing this information in sign-ups. 
#### Why This Matters

This will allow us to answer questions such as 'what percentage of users sign up for additional campaigns through onboarding?' In general, this will help us see if onboarding is the right place to offer additional campaigns.

**Comment by itsjoekent** [comment]
Can we clarify what this means? Every new signup once onboarding is launched will be shown this flow. Are we talking about logging actually making it through the entire flow?

**Comment by jessleenyc** [comment]
@deadlybutter oh yeah, now that we've clarified that it's shown per campaign I'll close this until that changes and we base it on user.
