### ISSUE TITLE
Updating quantity on reportbacks

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6762]
#### Current Behavior
- tell us what happened
  when someone tries to update the quantity on their RB, we saw in our meeting that you are required to upload a new photo. this is happening for the user and on the admin edit view of the alpha permalink
#### Desired Behavior
- what should have happened
#### Steps to Replicate
1. sign up for a campaign
2. RB 
3. Try to update quantity
#### Why This Matters

so users can update their quantity (maybe they wrote it wrong) and so admins can adjust the quantity if it's wrong.
#### Relevant Screenshots + Links

![screen shot 2016-07-26 at 3 24 01 pm](https://cloud.githubusercontent.com/assets/2658867/17152250/03fe602c-5345-11e6-94b7-2ce7fbd5c9c2.png)

**Comment by ngjo** [comment]
@angaither i just tested it again on thor as a user submitting a RB and then updating quantity and it let me do it...but it was acting wonky in yesterday's meeting, right?!?!

**Comment by angaither** [comment]
@ngjo yeahhhh it was!

**Comment by mshmsh5000** [comment]
If a member is forced to re-upload an existing image (with the same file name), she may get a 500 response because of the DB-side integrity constraint [described here](https://www.drupal.org/node/1192586). The problem is intermittent. I see a dozen in production from the last week.

**Comment by mshmsh5000** [comment]
One dopey solution to the 500 error is just to remove the `UNIQUE` constraint from `file_managed.uri`. Not sure what the possible side effects could be, but the only time we see this constraint invoked is to serve these illegitimate 500s.

**Comment by angaither** [comment]
@mshmsh5000 the file should automatically add a `-0` or '-1' though right? b/c we generate the file names once they are uploaded

**Comment by mshmsh5000** [comment]
What we're seeing is people uploading files with identical names. I wonder whether there's any way the renaming process gets bypassed, or `file_managed` gets used with the uploaded file name before we change it.

**Comment by mshmsh5000** [comment]
Also, `file_managed` wtf

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vfFRBOiT&#x2F;1602-users-hitting-404-page"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Users hitting 404 page</a>

**Comment by mshmsh5000** [comment]
[Some of the dark magic involved.](https://github.com/drupal/drupal/blob/7.x/includes/file.inc#L1406)

> The file will be added to the {file_managed} table as a temporary file. Temporary files are periodically cleaned.

Oh, they are? _Periodically cleaned?_ By which helpful elves?

Oh, [those elves](https://github.com/drupal/drupal/blob/7.x/modules/system/system.module#L3041). The cron elves. Seriously, what kind of language is that? Edit:

> The file will be added to the {file_managed} table as a temporary file. Temporary files are removed on cron. See `modules/system/system_cron()` for implementation.

Not sure why that's such a stretch.

Anyway. So I'd bet a wooden nickel that if you upload a file with the same name again between cron runs you can get this error message.

We could engineer a solution for this: Imitate this cron job after file uploads, for instance. Or we could just remove the `UNIQUE` constraint.

**Comment by angaither** [comment]
@katiecrane I think error is showing up is b/c of this PR #6286
