### ISSUE TITLE
Campaign – "High Season" year fields starts at year 0

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#677]
This field should be restricted to a smaller range.

![years](https://f.cloud.github.com/assets/1479130/2196780/3d6ef478-98b4-11e3-8fa3-9c9443897821.png)

**Comment by aaronschachter** [comment]
For new campaigns, it's only available for with range 2014-2015.  Campaigns that were entered before this commit https://github.com/DoSomething/dosomething/commit/fd43a7e767f1d27ce974396eb332c176603a08e2 will have this issue.  Can be resolved by saving the year as 2014.

**Comment by mmwtsn** [comment]
Thanks. I'll update Julie/Mike.
