### ISSUE TITLE
Show Onboarding For Competitions with Campaigns

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6772]
#### User Story

As an admin, I want all users to see the onboarding flow if they are signing up for a campaign.
#### Additional Information (optional)

Currently, onboarding is not appearing for campaigns with competitions. 
#### Why This Matters

It's important for all users to feel validated for signing up, have context about DS, and understand how to reportback.

**Comment by itsjoekent** [comment]
already have a PR ready waiting review! https://github.com/DoSomething/phoenix/pull/6771
