### ISSUE TITLE
Share modal to pop-up after over 18 registration completion

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6776]
#### User Story

As a user who has completed the registration form, I'd like to be prompted with my custom social share link (like we had with organs) and instruction text for what to do with the URL.
#### Additional Information (optional)

Something we talked about as a possibility and just adding here as a note:

(1) editing RTV's "download" form experience and adding the custom social link there ![screen shot 2016-07-27 at 6 38 07 pm](https://cloud.githubusercontent.com/assets/2658867/17194998/48be07d2-5429-11e6-84bc-6a7e7a74bbc8.png)

(2) editing RTV's "download" form to tell the user where to find the custom social link on the action page
#### Why This Matters

We want to engage the user with the custom link so they know what to do with it and are sharing it out to have more impactT

**Comment by angaither** [comment]
@ngjo I thought we decided this should be the competitions flow?

**Comment by ngjo** [comment]
@angaither yah, you're right, this should be a part of the under 18 flow -- im realizing what i wrote above should actually be a part of this issue: #6751 since it's about editing the css of that form page. re-assigning to myself so i remember to combine into that issue. thanks!
