### ISSUE TITLE
Query: Attempt to get registrations against custom social link

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6777]
#### User Story

As an impact admin, I want to be able to see who has registered via a custom social link. I will use this to drive competitions.
#### Additional Information (optional)

Brief recap of what (i think) we talked about: 
- file 1 of alpha (email, name), their custom social link, and the betas (email, name) that come in through that custom social link and sign-up
- file 2 from RTV of number of completed registrations

do a comparison of betas emails on file 1 and file 2 -- that would be the true # of people the alpha got to successfully register
#### Why This Matters

so we can have a competition around registrations
#### Steps for Testing (my notes)
1. make gladiator competition 
2. manually opt-in "Yes"
3. save the custom social link
4. use the custom social link multiple times w/ different email addresses
5. some tests will be 18+ and completing the registration form and some will be under 18 and doing social

**Comment by angaither** [comment]
isn't this the same as #6590?

**Comment by ngjo** [comment]
@angaither sorrrrt of -- i think this one has more to do with registrations via the custom social share link though, and #6590 are those "easier" metrics to pull whereas this one was so messy sounding with looking at different files that i thought it'd be useful to differentiate the two. if you'd prefer i combine them into one issue, lemme know and i can do whatever!

**Comment by angaither** [comment]
@ngjo hm I think I'm a bit confused here then. Because I thought the only deliverable thing for the impact team was a query to run so that they could pull the file themselves?

**Comment by ngjo** [comment]
@angaither hmm, no you're right -- can we use this issue for the time being because this is the ideal data they can get, and then if this isn't possible (registrations via the custom social link), then  we might have to consider one of the other queries? 

i think that other issue didn't fairly demonstrate the complexity of the ask and --> work to pull together. this is clearly me overthinking everything, lol. but does that work to use this issue over the other one?

**Comment by angaither** [comment]
@ngjo sure

**Comment by ngjo** [comment]
@angaither Adding a low-priority tag to this -- since competitions are different now, this might not be as necessary. keeping it open in case they do need something like this or post-launch, we do want this information for some other reason.

**Comment by ngjo** [comment]
Hi hi @katiecrane wanted to confirm that the competitions query you built will pull:

alpha name, alpha email, custom social share link, # of sign-ups, # of registrations

They'll be using these details in their competition emails. Anddddd TSG will be testing against a custom social link w/ a northstar ID as the user, so we'll be able to test this out on a bigger scale!

**Comment by katiecrane** [comment]
@ngjo the custom social share link isn't stored in the database so I wasn't pulling that. everything else is included though!

**Comment by ngjo** [comment]
hi hi @katiecrane sounds good! I'm gonna finish writing up those "instructions" for how to use the query later today -- I'll probably sync with you beforehand so I fully understand how it's working first. Stay tuneeeed, thanks!
