### ISSUE TITLE
Store user fields after a user submits voter reg form 

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6778]
## _FEATURE OVERVIEW_

We should be able to fill out on a user once they submit the organ donation form
- [ ]  field_birthdate
- [ ]  field_mobile
- [ ]  field_address
- [ ]  field_last_name

Ref: https://github.com/DoSomething/phoenix/issues/6557 and https://github.com/DoSomething/phoenix/issues/6692

Note: Follow-up with Mike/Data team about overriding stuff

**Comment by angaither** [comment]
@ngjo I'm actually not sure if this is possible because we don't have control over the RTV form

**Comment by ngjo** [comment]
@angaither ahhhh intteresting, that makes sense -- if it was something we really wanted  (talking to mike about this), is it possible to store this data by uploading RTV's completed registration csv? this could even be something we do down the line even, if we have the csv on hand?

**Comment by angaither** [comment]
@ngjo we would have to write a script to handle that

**Comment by ngjo** [comment]
@angaither sounds good, i'll talk to mike/data and update here!
