### ISSUE TITLE
Using Google Analytics to Track Who is Sharing the Unique Social Link

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6779]
#### User Story

As a DS employee, I'd like to see the number of people who are sharing the unique social links. 
#### Additional Information (optional)

Mike mentioned using GA's custom events for this!
#### Why This Matters

So we know if people are sharing the custom social link!

**Comment by ngjo** [comment]
@katiecrane I think once we get teh social share buttons working (wooohoo!!!1) we'll want to tackle this so that we know how many people are sharing the custom social!

**Comment by ngjo** [comment]
Hey @katiecrane ! It's ok that we can't track whether the person actually went on to share the link or not, we just want to use the custom event to track whether or not they've clicked. 

Here's what we'd like custom events on:
- [ ] Clicking the FB share (in each place it shows up )
- [ ] Clicking the Twitter share (in each place it shows up)
- [ ] Clicking the Tumblr share (in each place it shows up)
- [ ] Clicking on the actual social share modal
- [ ] If possible, clicking on the custom social share link itself (in each place it shows up) -- not sure if this one is possible since it's not really a button though, but would like to track this if possible.

Thanks!

**Comment by katiecrane** [comment]
@ngjo the social share link is just text so that's not trackable to my knowledge

**Comment by ngjo** [comment]
@katiecrane kk, no problem -- can you confirm once you start in on this one? if it's not trackable, then we can cut that from the list and jsut track the other ones on the list. thanks!

**Comment by katiecrane** [comment]
@ngjo :
The social buttons will send info to GA just like the normal social buttons. Since for this campaign we will only have the custom social share buttons, we know that any data in there for this campaign came from those buttons.

We also track modals opening and closing automatically.

Does that sound okay?

**Comment by ngjo** [comment]
@katiecrane gonna close this issue and open a new one to make sure GA is tracking this stuff once the campaign goes live. thanks!
