### ISSUE TITLE
Chrome – Style Confirmation Messages

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#678]
Confirmation message are currently bumping the site chrome down and temporarily breaking the page layout.

**Comment by mmwtsn** [comment]
![confirmation](https://f.cloud.github.com/assets/1479130/2196867/5d905e08-98b5-11e3-87b7-d76aebaf6648.png)

**Comment by desmondmorris** [comment]
Those are spit out by the `$messages` variable within page.tpl.php in paraneue. May need a wrapper or something?

https://github.com/DoSomething/paraneue/blob/master/paraneue/templates/system/page.tpl.php#L39

**Comment by mmwtsn** [comment]
They should probably have their own wrapper and live outside of `main` and absolutely positioned similarly to how the navigation block is to avoid pushing content down the page.

**Comment by DFurnes** [comment]
+1. Will clean that up later today.
