### ISSUE TITLE
Adding "Join"  competiton modal to the under 18 flow

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6780]
#### User Story

As an admin, I'd like the "join competition" prompt to come up on screen for those in the under 18 flow  #6773 
#### Additional Information (optional)

Like we talked about, if this is possible, editing the competition modal to have their custom social link in here and that they should share it to join the competition and win things
#### Why This Matters

Getting people to join the competitions can have big impact
#### Current Workaround w/o Feature (if applicable)

Manual competitions

(added this ticket so our meeting/thoughts is captured somewhere!)

**Comment by angaither** [comment]
this one also can be combined with #6776

**Comment by ngjo** [comment]
If we have this "join" modal on, will these emails go into Gladiator? Can the Impact team use some of Gladiator's features (splitting, reminder emails) for their outreach? 

Either way, they would be managing the leaderboard on their own, but would love if some of the emailing could still be done the tool.
