### ISSUE TITLE
Reportback file name export

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6782]
#### User Story

As a PM, I want to have file names for the original photo for all promoted, approved, and excluded reportbacks on campaign nid 48 run nid 6955 from 12:00am EDT July 28th-3:00am EDT on July 30th 2016. (So all of the 28th, all of the 29th, and 3 hours on the 30th).
#### Why This Matters

We are testing our Day of Action idea and compiling these photos for a video for social.

cc: @sheyd

**Comment by angaither** [comment]
@sheyd when I make this query on prod, the DB created timestamp would be in UTC, right?

**Comment by angaither** [comment]
@mikefantini what the heck is this time range?

**Comment by mikefantini** [comment]
It's 27 hours (all of today in EDT and 3 extra hours for PDT). @angaither

**Comment by angaither** [comment]
@sheyd @mikefantini  this should work

```
select REPLACE(f.uri, 'public://', '')
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
inner join file_managed f on rbf.fid = f.fid
where rb.nid = 48 and rb.run_nid = 6955
and rb.created > UNIX_TIMESTAMP(STR_TO_DATE('07-28-2016 12:00AM', '%m-%d-%Y %h:%i%p'))
and rb.created < UNIX_TIMESTAMP(STR_TO_DATE('07-29-2016 03:00AM', '%m-%d-%Y %h:%i%p'))
and rb.flagged = 0; 
```

**Comment by angaither** [comment]
@Maahipoopoo is looking for the same type of thing for Power to the Period, she doesn't need date ranges, just reportback files from nid = 6922 and run_nid = 6923

**Comment by mikefantini** [comment]
@angaither just updated issue with new range.

**Comment by angaither** [comment]
@mikefantini uploaded the list of files to [slack](https://dosomething.slack.com/files/andrea/F1X5EB10D/day-of-action.csv) we will just need devops to pull the files ⬇️

**Comment by angaither** [comment]
doneee

**Comment by mshmsh5000** [comment]
Just a note that if you're pulling RBs from a fresh flash sale, e.g., and need to pull all that haven't yet been reviewed, then you also want those where `flagged` is `NULL`. So the last condition should read

```
AND (rb.flagged = 0 OR rb.fagged IS NULL);
```
