### ISSUE TITLE
Show Most Recent Photo Upload On User Profile 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6785]
#### User Story

As a user, I would like to see my most recently uplaoded photo to a campaign on my user profile, and not the first photo I uploaded to the campaign. 
#### Why This Matters

As we encourage members to re-upload their reportback photos, broken images are still appearing on their user profile because our logic has it show the first photo, not the most recent. 
#### Screenshots

![screen shot 2016-08-01 at 11 36 48 am](https://cloud.githubusercontent.com/assets/14931921/17299432/4e846790-57dc-11e6-8f1f-9d47a772fba5.png)

**Comment by angaither** [comment]
@jessleenyc we are going to get more broken images if we pull in the most recent, since those are the files missing.
also are you sure we don't already pull in the most recent?

**Comment by jessleenyc** [comment]
cc @mikefantini
