### ISSUE TITLE
Mobile app to website -- already signed up for voter registration campaign

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6786]
#### User Story

As a mobile app user, when I click "sign-up" on voter registration, I want to be taken to the web voter registration experience without having to log in again. 
#### Additional Information (optional)

I believe this functionality exists, but creating this ticket just so we know it needs to be "turned on"

Does it work that the user is already signed-up for the campaign too when they come from mobile, or do they click "sign-up" again?
#### Why This Matters

So the user doesn't have to log into the site when coming from the mobile app (already signed up).

**Comment by angaither** [comment]
@ngjo I don't think there's anything needed from the phoenix end of this, once we have the campaign node created, select "enable magic link" in custom settings and the app will need to forward users if that property is set in the api

**Comment by ngjo** [comment]
Thanks @angaither -- @lkpttn do you need this open or in a different format for what you need to do to prep the mobile app for the voter registration campaign? (clicking in mobile sends you to the website and then you're already logged in). let me know!

**Comment by lkpttn** [comment]
@ngjo I think we're good, we have a corresponding issue in the app repo: https://github.com/DoSomething/LetsDoThis-iOS/issues/1035

**Comment by angaither** [comment]
okie, let's close this 🚫
