### ISSUE TITLE
Screen 2: Update Header Copy 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6793]
#### Current Behavior

Header text currently says "This Is How You Do It"
#### Desired Behavior

Text should say "Whoo! You're Signed Up."

(Had a convo w/ Joe about it right before the image file bug hit the site -- prob just didn't have a chance to update. Making it official with an issue)
#### Why This Matters

Since we're only showing screen 2 for this iteration, we want to acknowledge user sign up.

**Comment by weerd** [comment]
Yep yep. Sorry. Was going off of the design on the Sketch version 2.1 of the file I have on my local which has a different title.
