### ISSUE TITLE
Reportback Review Timestamp Inconsistency / Campaign Ending Early 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6794]
#### Current Behavior

Reportbacks reviewed around 9pm July 31st were showing up as reviewed Aug 1 at 2:00am . See screenshot below. In addition, several members have reached out and said that Pride Over Prejudice closed a day early, on July 30. 
#### Desired Behavior

Reportbacks reviewed time should reflect the time the reportback was reviewed. Campaigns should close on their end date, not the day before.
#### Steps to Replicate

I haven't been able to reproduce the early campaign closed state in thor but added the issue to this ticket in case the issues could be related. 

I haven't been able to reproduce the reportback review time because several of the images are still broken and we have to review in batch. 
#### Why This Matters

If there's a timing issue in drupal, that might have caused a campaign to close early. The last day of campaigns is when we generally see a big influx of reportbacks so it's crucial that the campaign doesn't close early.
#### Relevant Screenshots + Links

![screen shot 2016-08-01 at 10 29 42 am](https://cloud.githubusercontent.com/assets/14931921/17306064/f8fc8d82-57fb-11e6-92aa-e6fe2f6c1d57.png)

**Comment by angaither** [comment]
@jessleenyc I think this issue might belong in the devops repo

**Comment by jessleenyc** [comment]
Issue moved to [DoSomething/devops #159](https://github.com/DoSomething/devops/issues/159) via [**ZenHub**](https://www.zenhub.com/)
