### ISSUE TITLE
Extra padding on mobile - 'X'

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6804]
#### Current Behavior

'X' looks like it have extra padding-left on mobile. 
#### Desired Behavior

X should appear aligned to the right of the screen. 
#### Steps to Replicate
1. Navigate to staging.dosomething.org
2. Sign up for a campaign
3. Observe onboarding 
#### Why This Matters

Having a floating X is poor design -- and not what our mockups display!
#### Relevant Screenshots + Links

![img_3656](https://cloud.githubusercontent.com/assets/14931921/17344046/ad6833f2-58ce-11e6-86e5-106aa85bb6a2.jpg)

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WnQyw3sp&#x2F;1589-gladiator-feature-to-edit-the-leaderboard-photos"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Gladiator -- Feature to Edit the Leaderboard Photos</a>
