### ISSUE TITLE
Linking to gallery in Stuff You Need section

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6809]
#### User Story

As an admin, I want to be able to link to an image gallery in the stuff you need section.
#### Additional Information (optional)

We talked about this in real life, and this has been done before, but creating this issue in case there are additional things we do need to do to implement this. We'd like to create a link to a gallery like: https://www.dropbox.com/sh/0axy13f0f25c8b4/AACIjRTn4up42MfpW6mikEpYa?dl=0 (example of gallery that was on four legged finishers)
#### Why This Matters

So the user can get different cards to share

**Comment by angaither** [comment]
@ngjo I don't think we need an issue for this, since there's no code required to put a link in the stuff you need section, going to close this out
