### ISSUE TITLE
Feature card signup animation

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#6819]
#### Current Behavior
- When signing up for a campaign via the feature card, the button wobbles.
#### Desired Behavior
- after discussion with Luke we decided it should actually look something like this https://dribbble.com/shots/2325445-Listen
#### Steps to Replicate
- When signing up for a campaign via the feature card, the button wobbles.

**Comment by jessleenyc** [comment]
@joe or @weerd can you clarify the desired behavior for the image card on larger screens? 'the card should load landscape on non mobile widths' -- what does this mean?

**Comment by weerd** [comment]
@jessleenyc if you click on that slack link in the "Current Behavior" section it shows in a screen shot that if we use the square version of the campaign cover image, then on tablet, when the FeatureCard is at its most widest, it looks odd and isolated with a bunch of whitespace around it. So we likely need to switch out and use the landscape version for tablet to fill the wider area for tablet.

**Comment by itsjoekent** [comment]
Accidentally made a second issue for the cover image, but since the work was broken out for this issue between me & diego I think it makes sense anyway https://github.com/DoSomething/phoenix/issues/6839
