### ISSUE TITLE
Onboarding gallery controller

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#6820]
#### User Story

As a user, I should be able to navigate between the different onboarding slides 
#### Why This Matters

We can't launch with more slides if this does not exist
#### Current Workaround w/o Feature (if applicable)

Only enable 1 slide at a time

**Comment by jessleenyc** [comment]
Gallery controllers work -- https://github.com/DoSomething/phoenix/issues/6878 will take care of the transition.

**Comment by itsjoekent** [comment]
This code wasn't merged yet, I'm going to re-open until that happens
