### ISSUE TITLE
Add "Onboarding" Source for Campaign Signups

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6827]
#### User Story

As an admin, I want to track users that sign up for additional campaigns through onboarding. 
#### Why This Matters

1) For campaign signups, our definition of 'new' is based on a member creating an account and signing up for a campaign within five minutes. Now that we're prompting users to sign up for multiple campaigns, adding a source will let us know which campaign the new member signed up for first. 
2) This will also give us insight on the effectiveness of this slide.

**Comment by itsjoekent** [comment]
This was already an issue which I closed? https://github.com/DoSomething/phoenix/issues/6759

**Comment by jessleenyc** [comment]
Sorry about that!
