### ISSUE TITLE
Editors: Publish / unpublish ability

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#683]
With current permissions, editors currently cannot change the node status: changing from unpublished to published, or vice versa.

The current defaults are:
Campaign: unpublished
Static content: published

Currently only an administrator has the ability to publish/unpublish, possibly because of the "bypass node access" permission. This may be actually safer than allowing editors to freely publish/unpublish.  Thoughts?

**Comment by barryclark** [comment]
@aaronschachter This might be a pain in the ass for testing for them though, right?

**Comment by aaronschachter** [comment]
Looking into this and it seems if we grant access to "Administer content", an editor has the ability to change the Publishing status.

I'm not crazy about the extra permissions it also grants, which are allowing them to change the author, the authoring date, sticky, promoted, but it's a minor concern.  For now this is the easiest way to go, will send thru a PR to grant editors access to "administer content".
