### ISSUE TITLE
Customizing the social buttons text

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6833]
#### User Story

As an admin, I'd like to be able to customize what would show up in the social buttons (facebook, twitter, tumblr). 

This doesn't necessarily have to be the same set of social buttons (the ones under the problem) -- there might be a campaign in the future where they would still want the problem populated in the social buttons, but also another set of social buttons that can be customized -- not sure what the likelihood is, but putting that out there in case it's important for planning now.
#### Additional Information (optional)

For example, with voter registration, we want the social buttons on the social modal ( #6832 ) to be specific to voter reg, meaning it would say something like "Lose Your V Card today! Share your custom social link: _custom social URL_"

Twitter: changing the tweet
Facebook/Tumblr: change the text and image -- let's talk about what's doable!
#### Why This Matters

Easier for the user to just click a button to share, but the message we want them to share isn't just the problem statement (what's being pulled now), we would want to change it. And for this campaign, it would be something to do with voter registration along w/ their custom social link. Basically, gives us more flexibility with the social buttons, so we're not restricted to the social buttons only populating w/ the problem statement.

**Comment by angaither** [comment]
@ngjo a bit confused here, do we want to share something other than the problem statement?

**Comment by ngjo** [comment]
@angaither Yahhhs, exactly -- and this feature would be used for other campaigns where we don't want the social buttons to be about sharing the problem statement.

**Comment by angaither** [comment]
@ngjo hmmm, I think that would take some thinking about where it goes/what it says then
as the current design doesn't make much sense if you aren't sharing the problem statement

![image](https://cloud.githubusercontent.com/assets/645205/17526862/116bfb82-5e37-11e6-95f7-1342ceb25ca5.png)

I think this should be de-prioritized until we have a more concrete idea of how we will be updating the template

**Comment by ngjo** [comment]
so we're on the same page, @angaither i'll work on writing something for how this would work and will post here today/tomorrow!

**Comment by ngjo** [comment]
@angaither how's this for a start? let me know what i can do further map this out. I'll also sync with mike tomorrow!

**Overview**: 
These would be separate share buttons from the Problem Share social buttons (https://cloud.githubusercontent.com/assets/645205/17526862/116bfb82-5e37-11e6-95f7-1342ceb25ca5.png). These social share buttons would have customizable text that would be written by the campaign lead. Depending on the campaign, it should be able to pull in the custom social share link. 

If we have the custom social share buttons enabled, we would likely want to hide the Problem Share social buttons from the Action Page so that there aren't multiple sharing options. Or maybe we move the Problem Share to the Pitch Page. (Do we have any data on how often these Problem Shares are shared?). In the interim, we can do this on Optimizely.

_(I'm putting it here if it affects the above possibilities or how we might approach things, but I think it would be useful if the Problem Statement social share messages could be customizable as well. There are instances when the Problem Statement is really long and it looks really bad on Facebook or Twitter. Campaign leads should always try to cut down the Problem Statement, but sometimes it's not possible because of sponsor restrictions. In these situations, it would be ideal if the campaign lead could write separate social share messaging to overwrite the lengthier Problem Statement)._

**Application of Customizable Social Share Buttons**

These would be important if we have a campaign whose primary purpose is to share a custom social share link or a specific message on social. Chances are, this specific message is not the problem statement and we want the user to be greeted by it in a different part of the flow, not under the Problem Statement.

For better user experience, we'd want to be able to customize social buttons so that it's pre-populated with the message we would want and the user could just click on the social button (instead of asking them to copy and paste something into social media).

**Examples**
- For example, for voter or organ registration, we would want the social share buttons to show up in a share modal that includes a prompt along with the custom social share link.

Person X: "Registering to vote is important! Do it at ds.org/voter/source=user/X"
Person Y: "Registering to vote is important! Do it at ds.org/voter/source=user/Y"
- For example, for campaigns with different user flows (voter and organ come to mind), we might want different social shares for the specific flow.

Over 18: "I registered, you should too at ds.org/voter/source=user/over-18"
Under 18: "If you're over 18, don't forget to register to vote! ds.org/voter/source=user/under-18"
- For example, on donation campaigns, maybe we want a customized social shares that cover different parts of the lengthier campaign when they haven't reported back and wouldn't have gotten the alpha permalink view.

"I just started my donation drive for Power the Period! Talk to me about how to donate or visit ds.org/power/ to learn more!"

"I just started my donation drive for Game-Winning Drive! Got used toys? Give them to me! Learn more at ds.org/game/

**Comment by ngjo** [comment]
@katiecrane synced with the team -- we'll get an image and text for the custom social shares you built!
