### ISSUE TITLE
Clicking Sign Up From Onboarding Isn't Signing Up For Certain Campaigns

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6837]
#### Current Behavior

When I sign up for "Mind On My Money" during onboarding I can see the campaign in my user profile under "You're Doing" but when I click into the campaign, it brings me to the pitch page. This is the only campaign I've seen this issue for so far, but it is consistent each time I try a different login. Please investigate why it's occurring with this campaign and check if there are campaigns in prod that might experience this. 
#### Desired Behavior

When I sign up for a campaign during onboarding and visit the campaign later, I should be directed to the action page. 
#### Steps to Replicate

1) Sign up for a campaign that's not "Mind on my money"
2) Look for a sign up opportunity for "Mind on my money" on onboarding
3) Sign up
4) Close out of onboarding and navigate to user profile
5) Click on Mind on my money
6) Notice pitch page
#### Why This Matters

A user shouldn't have to re-sign up for a campaign they've already signed up for. Also, if it's showing up in 'you're doing' are we counting them as signed up in the database?

**Comment by itsjoekent** [comment]
I just signed up for Mind on my money via onboarding flow, it's in the database exactly how it should be

<img width="949" alt="screen shot 2016-08-09 at 9 51 50 am" src="https://cloud.githubusercontent.com/assets/897368/17518714/03881e94-5e17-11e6-98de-a8bc905880f0.png">

are you sure this is a bug?

**Comment by itsjoekent** [comment]
just tried with non admin account & was able to reproduce, only for this one campaign

**Comment by angaither** [comment]
@jessleenyc where are you testing this? staging?

**Comment by jessleenyc** [comment]
@angaither yes

**Comment by angaither** [comment]
that campaign doesn't have a run attached to it on staging, so I'm wondering if that's why it's not redirecting you correctly

**Comment by jessleenyc** [comment]
hmm. @angaither I just tried testing by disassociating runs with thumb wars but keep getting this errror: 

![screen shot 2016-08-09 at 10 12 48 am](https://cloud.githubusercontent.com/assets/14931921/17519443/f49da996-5e19-11e6-8ab1-3b3769262352.png)

**Comment by itsjoekent** [comment]
Wait what? We only needed to make a new run for it which I (painfully) did (DRUPAL WHY)

So it has a run now but getting a funky error back 
<img width="1533" alt="screen shot 2016-08-09 at 10 14 10 am" src="https://cloud.githubusercontent.com/assets/897368/17519501/2534620c-5e1a-11e6-8488-9dc37c9909e8.png">

**Comment by itsjoekent** [comment]
Oh wait i changed the start date not the end date on the run

**Comment by jessleenyc** [comment]
I was testing the opposite, to see if the same bug would occur for a campaign if I removed its associated runs.

**Comment by angaither** [comment]
... but we know that doesn't work. campaigns should all have runs, you get the fatal error without it

**Comment by itsjoekent** [comment]
Confirmed run was the problem! thanks @angaither

**Comment by jessleenyc** [comment]
@angaither I didn't know that! How did it end up without a run to start with no fatal error?

**Comment by itsjoekent** [comment]
@jessleenyc mind if I close this?
