### ISSUE TITLE
Need to click "X" twice to close out of onboarding

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6838]
#### Current Behavior

Tested several onboarding experiences and need to click 'x' twice to close the container. The first click shows a blue box surrounding the element. See below screenshot. 
#### Desired Behavior

The container should close with one click.
#### Relevant Screenshots + Links

![screen shot 2016-08-09 at 9 42 47 am](https://cloud.githubusercontent.com/assets/14931921/17518417/d1f078c8-5e15-11e6-8fc9-16ea3f0a58e3.png)

**Comment by weerd** [comment]
@deadlybutter mind taking a look at this. Some change you made w/ the `request.abort` stuff introduced this bug:

![image](https://cloud.githubusercontent.com/assets/105849/17524183/7bbb8590-5e2b-11e6-8bcb-690dd323956f.png)

**Comment by weerd** [comment]
happens on first click of close button and didn't before the above code added.

**Comment by itsjoekent** [comment]
(look at the PR above haha)

**Comment by weerd** [comment]
🍳 cellent. If anything just helps add more info on the issue, haha

**Comment by itsjoekent** [comment]
👍 yeah no big deal, just wanted to make sure you were aware :D
