### ISSUE TITLE
Onboarding Not Appearing For Certain Campaigns

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6844]
#### Current Behavior

On staging, I logged into a non-admin account and cleared my localstorage cache in the console via localStorage.clear(). Navigated to a campaign, clicked signup and did not see onboarding.
#### Desired Behavior

Onboarding should be enabled for all campaigns. 
#### Steps to Replicate

I haven't been able to replicate consistently. Wrote down some campaigns it happened with but after I log out, sign in with a different account, onboarding appears for them. 
- Peanut Butter & Jam Slam
- Justice For Elephants
- Test Oct
#### Why This Matters

This should be investigated because we don't want members to miss onboarding. 
#### Relevant Screenshots + Links

![screen shot 2016-08-09 at 3 19 02 pm](https://cloud.githubusercontent.com/assets/14931921/17530406/61c08ec8-5e45-11e6-94e8-f34dc8dfb3e2.png)

**Comment by jessleenyc** [comment]
@deadlybutter  from this morning:
UID 1707948
jlee+5@dosomething.org

![screen shot 2016-08-10 at 10 31 51 am](https://cloud.githubusercontent.com/assets/14931921/17557665/18982b60-5ee6-11e6-86ae-b1c15ed10851.png)

**Comment by itsjoekent** [comment]
so far I've tried signing up on each of these campaigns 3 times & making a new account upon signup. i also tried making 3 new accounts & then signing up for each campaign on the same account. I'll look at the uid / signups to see if there is anything funky going on but not sure how to debug this one

**Comment by jessleenyc** [comment]
@deadlybutter today was the first time it happened to be during incognito mode?

**Comment by jessleenyc** [comment]
Closing this unless it's flagged again.
