### ISSUE TITLE
We don't let the world into competitions, but we show them the modal anyways 

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6849]
#### Current Behavior

Currently we display the competition modal across all translations. 
this causes issues like 
1. users see content that isn't in their language
2. users aren't actually ported into gladiator b/c the runs aren't the same

(n.b. normally users who opt into this are global english users who were wrongfully assigned the language) 
#### Desired Behavior

We need to either 
- not offer the modal across all experiences
- always match global english runs with english runs when offering a competition
- fix #6748 
#### Steps to Replicate
- opt in to a compeitions via the modal if you are global english and you won't get a transaction 'welcome to comp' email.  
#### Why This Matters

People want in, and they aren't getting in. 
if you look in the `dosomething_gladiator_failed_task_log` every time there's a `500` it means that user wasn't added to gladiator b/c of a run mis-match

**Comment by mikefantini** [comment]
Our best bet is probably disabling the competition prompt for any non /us/ experience.

**Comment by ngjo** [comment]
For SuperStressFace, US and GL EN are now both set to run 7066
