### ISSUE TITLE
Registration form server-side validation and data sanitation

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#685]
Hey @angaither, 

@DFurnes raised a concern this morning about making sure we have basic server-side validation and data sanitation in place on the registration form to prevent against someone with malicious intent, or someone without JS turned on.

We're thinking that Drupal probably takes care of that, could you confirm what server side validation is currently taking place on the registration form?

**Comment by angaither** [comment]
@barryclark We've got validation on cell numbers based on pattern matching. 
https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_user/dosomething_user.module#L27

There's also basic form validation within drupal https://api.drupal.org/api/drupal/includes%21form.inc/function/drupal_validate_form/7

**Comment by DFurnes** [comment]
Looks great. Just wanted to make sure we weren't relying on client-side validation for all of our validation needs.
