### ISSUE TITLE
Slide 1 Copy Errors

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6852]
#### Current Behavior

Copy reads: 
By joining [campaign] campaign, you've teamed up with 5.4 million other members who are making an impact on the causes affecting your world.
#### Desired Behavior

Please add 'the' before the campaign name and update our member count to 5.3 million. 

It should read: 

By joining the [campaign] campaign, you've teamed up with 5.3 million other members who are making an impact on the causes affecting your world.

**Comment by itsjoekent** [comment]
for context 

![screen shot 2016-08-10 at 2 09 09 pm](https://cloud.githubusercontent.com/assets/897368/17565160/3af08e32-5f04-11e6-8c26-e0196636bcee.png)
