### ISSUE TITLE
Speed up feature card transition timing 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6854]
#### User Story

As a user, I'd like to be offered a new campaign to sign up for quicker. 
#### Additional Information (optional)

Please update the transition time to 1.5 seconds. 
#### Why This Matters

If the button doesn't change quickly and show a new campaign, members might not see it and we could lose an opportunity for them to sign up.

**Comment by weerd** [comment]
Chatted with @lkpttn and going with 3 seconds for the full wait, since the button itself needs 1.5s to do its thing.
