### ISSUE TITLE
figure -left/-center bug with img wrapped in <a> tag

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#6857]
#### Current Behavior

The `figure -left -center` classes collapse the image when the figure media is wrapped in in <a> tags.
#### Desired Behavior

The visuals should not change if the image is also a link
#### Relevant Screenshots + Links

<img width="1261" alt="screen shot 2016-08-10 at 1 56 10 pm" src="https://cloud.githubusercontent.com/assets/1865372/17565208/73692846-5f04-11e6-93d3-8b5780118f58.png">
<img width="1271" alt="screen shot 2016-08-10 at 2 00 59 pm" src="https://cloud.githubusercontent.com/assets/1865372/17565226/8915d554-5f04-11e6-99d0-70d8f42fb117.png">

**Comment by angaither** [comment]
@lkpttn I hope you self assigned because you intend to fix this. 😄
