### ISSUE TITLE
Disable Onboarding for Global English

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6860]
#### User Story

Currently, onboarding is pulling in campaigns without translations on the featurecard. Let's disable onboarding for global english and create a fix for it after we've shipped all three slides for US english first. 
#### Additional Information (optional)

An example: Smiles for soldiers appeared in onboarding, when I signed up for it I saw this page: 

![screen shot 2016-08-10 at 5 38 51 pm](https://cloud.githubusercontent.com/assets/14931921/17572308/c065af94-5f21-11e6-958d-cb7cbc50f355.png)

Upon investigation, drupal shows that this campaign isn't translated at all so the campaign should not appear in onboarding. 

![screen shot 2016-08-10 at 5 38 57 pm](https://cloud.githubusercontent.com/assets/14931921/17572311/c1e4515e-5f21-11e6-9903-6873d710d079.png)
#### Why This Matters

Signing members up for campaigns that don't exist on global creates a poor user experience. Our current focus is on US so let's disable until we can accommodate.

**Comment by itsjoekent** [comment]
Members should never find themselves on the "Global translation does not exist" page you are seeing here

**Comment by jessleenyc** [comment]
@deadlybutter i found this on a non-admin account on thor. are you suggesting this won't happen in prod?

**Comment by itsjoekent** [comment]
how did you reach this page? tor guard as global english?

**Comment by jessleenyc** [comment]
@deadlybutter recapping our convo - yep! i was using torguard new zealand and was able to sign up for Smiles For Soldiers on onboarding. After clicking into my user profile, I saw the below. Clicked on one of the campaigns w/ the DS logo and was brought to an empty campaign. 

![screen shot 2016-08-11 at 10 02 03 am](https://cloud.githubusercontent.com/assets/14931921/17591139/cbff9d90-5faa-11e6-88de-98e522228a32.png)
