### ISSUE TITLE
Update first line of slide one with competitions notification

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6864]
#### User Story

Similar to what we did for slide 2, let's move the competition notification into slide one underneath the header. 
#### Additional Information (optional)

This line should only pull in if a user joins a competition. If the user does not join, no text should appear. 
#### Why This Matters

Currently, our site doesn't acknowledge competitions so it's important that we get messaging to our members who enter competitions.

**Comment by itsjoekent** [comment]
In the future we can join simple issues like this #6865
