### ISSUE TITLE
Pulling in Custom Social Share Link into Gladiator

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6871]
#### User Story

As an impact member, I would like the custom social share link to be made available as a mail merge field in Gladiator
#### Why This Matters

In talking to Mike about competitions, he (smartly) pointed out that it'd be useful to have this custom social share link included as a mail merge option in messaging. So, when I message a competitor, I'd like to reference their custom social share link in the emails so that it's easy for them to know what they should be doing. 

We would use this for any campaign that has competitions and custom social share links.

This could be:
- "Use your [custom social share link] and the more people you can get registered, the more chances at the $ you have!"
- Get more people to register via your link, here's a tweet for you: "Tweet this: "Register to vote at [custom social share link]"

**Comment by angaither** [comment]
@ngjo this issue would actually belong in the gladiator repo then. 
Also since we are using the phoenix id for the social share, not the northstar id, gladiator doesn't have that variable. 

hmmm maybe we should be using NS id for the share link?

**Comment by ngjo** [comment]
@angaither whoops, sorry about that! i wasn't sure how to get it in both voter-registration and gladiator...can it live in two places?

i think if it takes the northstar ID to pull into gladiator, that might be the best bet since we'll likely use these custom social share links in competition emails... what would it take to make the switch?

thanks!

**Comment by jessleenyc** [comment]
Issue moved to [DoSomething/gladiator #334](https://github.com/DoSomething/gladiator/issues/334) via [**ZenHub**](https://www.zenhub.com/)
