### ISSUE TITLE
Add another option into active hours for the quickest campaigns

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6876]
#### User Story

As an admin, I want to differentiate campaigns that can be completed instantly.
#### Additional Information (optional)

Ideally the text for the checkbox says 'instant' but if there needs to be a number, lets use 0 or 0.05, whatever our sorting logic will accept for the onboarding experience. 
#### Why This Matters

This will allow us to further curate the campaigns that appear in onboarding and get users into more campaigns that they have a greater chance of reporting back on.

**Comment by angaither** [comment]
@jessleenyc we already have a field to differentiate short campaigns, did you want to add an option in here for less time? 
![image](https://cloud.githubusercontent.com/assets/645205/17701608/749ada50-6398-11e6-8e32-69d2b3a3297d.png)

**Comment by jessleenyc** [comment]
@angaither we're looking to add an option that represents a campaign you can complete instantly. This way, we can better curate the campaigns pulled into onboarding.

**Comment by angaither** [comment]
@jessleenyc so add in an option for lower than `0.5` hours?

**Comment by jessleenyc** [comment]
@angaither yep. '0.1'?

**Comment by angaither** [comment]
@jessleenyc @deadlybutter  I added the new option to campaigns, but I'm not sure how this will work with the campaign finder/onboarding. I think there might be some additional work here.

**Comment by itsjoekent** [comment]
@angaither We can test on staging but it should work fine for onboarding since its just a number

**Comment by angaither** [comment]
hmm yeah I was just playing around with the finder on staging and `instant` options don't show up on the finder when you click 1 hour or less.

**Comment by jessleenyc** [comment]
@angaither should i create a separate phoenix ticket to address?

**Comment by angaither** [comment]
@jessleenyc depends, what do we want the interaction to be here? 
should they show up in that `less than 1 hour` group? should it be it's own group?
Does it actually work in onboarding? 

Should I roll back this field option until we figure these questions out?

**Comment by itsjoekent** [comment]
Have we re-indexed Solr?

**Comment by angaither** [comment]
yarrr

**Comment by itsjoekent** [comment]
just did some Finder debugging, its passing the correct query parameter when you press the 1 hour or less

<img width="580" alt="screen shot 2016-08-17 at 2 33 12 pm" src="https://cloud.githubusercontent.com/assets/897368/17748499/bf3fe25e-6487-11e6-9492-a1bc48971d8d.png">

**Comment by itsjoekent** [comment]
feels like this is solr related

**Comment by angaither** [comment]
oy, the option didn't deploy to thor properly either curse you #6735! 

![image](https://cloud.githubusercontent.com/assets/645205/17748686/934d35ce-6488-11e6-9a8c-4d97166a6643.png)

![image](https://cloud.githubusercontent.com/assets/645205/17748696/99103402-6488-11e6-8809-72e77782444d.png)

**Comment by angaither** [comment]
I ssh'ed into thor and re-ran `drush fra -y` and it added the option. why wouldn't this work in the deploy [here](https://github.com/DoSomething/phoenix/blob/dev/bin/ds#L293)

EVEN THOUGH IT SAID IT DID THAT EXACT THING
![image](https://cloud.githubusercontent.com/assets/645205/17748842/3e1eed26-6489-11e6-8f13-4fdd9852e755.png)

**Comment by itsjoekent** [comment]
I love drupal

**Comment by angaither** [comment]
I think it _does_ show up correctly in the finder on thor
after I 
1. manually reverted the feature
2. updated a campaign (the sports drive one on the homepage from 2 hours to instant)
3. reindexed
4. cleared cache
5. reindexed
6. cleared cache

boom an insant campaign updated instantly 
![image](https://cloud.githubusercontent.com/assets/645205/17749257/def08b14-648a-11e6-9e55-ad57f4f06239.png)

![image](https://cloud.githubusercontent.com/assets/645205/17749243/d38690a2-648a-11e6-90c4-cfb9452edc96.png)

**Comment by itsjoekent** [comment]
> 1. reindexed
> 2. cleared cache
> 3. reindexed
> 4. cleared cache

**Comment by jessleenyc** [comment]
I'm seeing the 'instant' campaign in both onboarding and the finder as well. I'll let @mikefantini chime in on whether or not we should create a new time category for instant campaigns or have it be grouped in with '1 hour or less' on the finder.

**Comment by jessleenyc** [comment]
Since it's appearing in both onboarding and the finder can we actually close this ticket and open a new one if we want to update the finder? @angaither

**Comment by angaither** [comment]
yaaa, and I think it's working ok in the finder. I would like to leave this open till the field is working in prod, since I had to do a few manual things after the deploy -_-

**Comment by mikefantini** [comment]
I don't have a super strong opinion on changing the finder filter to be 1 hour or less or adding an instant filter.

@jessleenyc let's maybe poll the room in tech-campaigns sync when we in person confirm with them that it's been added?

**Comment by jessleenyc** [comment]
@angaither do you need to do some of these manual things on prod before i test it out?
@mikefantini sounds good.

**Comment by angaither** [comment]
looks like it rolled into prod SWIMMINGLY. closing this meowt
