### ISSUE TITLE
Add hearts functionality to reportback photos on onboarding

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6879]
#### User Story

As a user, I want to interact with photos by giving hearts. 
#### Additional Information (optional)

Pulled this out as a separate issue so we can ship slide 3 without hearts initially. 
#### Why This Matters

We want our members to start interacting with our site as early and often as possible.

**Comment by angaither** [comment]
@jessleenyc can you update this issue with some info?
