### ISSUE TITLE
Signup source is saving utm params as well

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6891]
#### Current Behavior

Currently when we store signup source it's saved with all the UTM params if they are there. we don't want that
`user/[northstar_id&utm=blahblahblah`
#### Desired Behavior

cut all sources at the `&` so we don't save UTM params in the signup source
#### Steps to Replicate
- signup with a source and utm params, you'll see a lot of nonsense in the table

**Comment by angaither** [comment]
looks like this is only happening for the "organ//custom" share stuff and not all links with UTM params

**Comment by katiecrane** [comment]
@angaither thanks! noted
