### ISSUE TITLE
Scholarship page is unpublishing its translation

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6899]
#### Current Behavior

When you edit the scholarship page https://thor.dosomething.org/us/about/easy-scholarships, the "translation is published" unchecks itself so the page isn't published and 404s.
#### Desired Behavior

These checkboxes shouldn't be unchecking themselves -- published pages should stay published!
#### Steps to Replicate
1. go to scholarships page
2. edit the scholarships page
3. save your edits (you might have to wait a while after editing to see this happening, it doesn't happen all the time, but it has happened 4 times now to 3 different users: me, luke, marissa)
4. view scholarship page incognito or logged out of admin view
5. it may or may not be 404ing
#### Why This Matters

Pages shouldn't be unpublishing themselves and acting like this! Is it possible that this is happening to other pages?
#### Relevant Screenshots + Links

This is being unchecked on its own:
![screen shot 2016-08-18 at 11 14 38 am](https://cloud.githubusercontent.com/assets/2658867/17779252/fafd5e36-6534-11e6-93fa-296e13ebce56.png)

**Comment by angaither** [comment]
> This is being unchecked on its own

👻

**Comment by angaither** [comment]
@ngjo does this happen on all static content pages, just this page? have you been able to replicate this on staging?

**Comment by ngjo** [comment]
It is a ghost! And sorry! Yeah, it's only been happening on production so far that's been confirmed -- I tried replicating on thor/staging, but it wasn't happening...but I wasn't sure if that was cuz it's only a prod issue or because it just wasn't unchecking itself those times on thor/staging. i can keep doing it daily and see if anything happens tho.

I just tried the privacy policy page and terms of service and it didn't happen there -- all of those pages' translations are published. Not sure if it's worth noting, but the scholarship page has the GL EN as "not published".

Let me know if repeatedly testing the scholarship page on thor/staging will help. Ghost hunters! 

@angaither

**Comment by angaither** [comment]
@ngjo it would for sure be helpful to have this happening on staging somewhere to figure out why/how to fix it.

Is there something with having a translation created, but not published on static pages that causes this?

**Comment by ngjo** [comment]
@angaither kk, i'll play around with it on staging and hopefulllly it breaks. and yeah, that's what i was thinking about the translations...but lol, that seems weird, doesn't it?

i'll start testing on staging tomorrow and post here if it unpublishes

**Comment by ngjo** [comment]
@angaither i wasn't able to recreate this so closing for the time being...hoping the 👻  has moved on to another site to haunt.

will reopen if it happens/i can recreate. thanks!
