### ISSUE TITLE
Update Onboarding Slide 3 Reportback logic

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6909]
#### User Story

As a user, when I reach the end of the onboarding experience I see at least 1 promoted RB item if available, and the rest are a random selection from promoted and approved.
#### Additional Information (optional)
- [ ] Display at least one promoted photo if available
- [ ] Display random assortment of promoted and approved for rest of items
#### Why This Matters

We want to have a nice assortment of our best RB items for the onboarding experience.
#### Current Workaround w/o Feature (if applicable)

Will likely need more than 1 API call to gather the RB items, and on second call make sure to disallow the first promoted item that was already obtained.

**Comment by jessleenyc** [comment]
Issue moved to [DoSomething/TeamRocket #9](https://github.com/DoSomething/TeamRocket/issues/9) via [**ZenHub**](https://www.zenhub.com/)
