### ISSUE TITLE
Changing the language in the upload photo section

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6913]
#### User Story

As a member, I'd like to have more context about what the photo uploader is and that someone is reviewing my photo. As an admin, I want the member to know that the photo will be reviewed and that the photo is the scholarship entry.
#### Additional Information

For campaigns that have scholarships on them:
—— scholarship, no RB: “Add your photo here for a scholarship entry!”
—— scholarship, RB: “Add another photo and we’ll check it out!”

For campaigns that don't have a scholarship on them:
— — no scholarship, no RB “Add your photo here and we’ll check it out!”
—— no scholarship, RB “Add another photo and we’ll check it out!"
#### Why This Matters

We want to add clarity around the RB process -- a part of that is clarifying why the photo is important and that someone actually looks at them!
#### Examples

![screen shot 2016-08-22 at 10 27 08 am](https://cloud.githubusercontent.com/assets/2658867/17858262/03e69910-6853-11e6-9acb-b944ad8b4d16.png)

![screen shot 2016-08-22 at 10 28 22 am](https://cloud.githubusercontent.com/assets/2658867/17858316/2c0bf228-6853-11e6-89d4-e4825129b3a9.png)

**Comment by angaither** [comment]
I think maybe this text is too long. 
here's what it looks like in real life

![image](https://cloud.githubusercontent.com/assets/645205/17907878/de29da58-694b-11e6-88c1-0e6359dcced6.png)

![image](https://cloud.githubusercontent.com/assets/645205/17907894/e9c1b4d0-694b-11e6-8667-68356241868f.png)

**Comment by ngjo** [comment]
@lkpttn is there anything we can do here from a design standpoint? or do we need to change the text?

cc @angaither

**Comment by angaither** [comment]
I mean, we can move the text down but it looks _very very_ cramped on smaller screens

**Comment by lkpttn** [comment]
Do we have a max width for the handwriting container and the arrow is an :after element?
