### ISSUE TITLE
Add a title above the  photo upload and gallery

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6915]
#### User Story

As an admin, I'd like it to be clearer to the member what the RB gallery is.
#### Why This Matters

We want to increase RBs and one way to do that is to be clearer about what the member is looking at when they see the RB gallery and upload section.

**Text to Add**
JOIN OTHERS MAKING A DIFFERENCE

![screen shot 2016-08-22 at 10 55 10 am](https://cloud.githubusercontent.com/assets/2658867/17859273/eb2b5a38-6856-11e6-81cc-ce997082d6b2.png)

**Comment by angaither** [comment]
@ngjo are we removing the text above? Pics or it didn't happen and the reportback copy?
![image](https://cloud.githubusercontent.com/assets/645205/17862840/ff3c893a-6864-11e6-8774-b736332e444f.png)

**Comment by ngjo** [comment]
Whoops, sorry -- shoulda made a bigger photo. It's a new title, so we'd keep pics or it didn't happen ("helpful tips" is another new section that i haven't made an issue for, but will be):

![screen shot 2016-08-22 at 12 52 17 pm](https://cloud.githubusercontent.com/assets/2658867/17863340/46c4bf6e-6867-11e6-959c-5e753cd11e80.png)
