### ISSUE TITLE
New section in PROVE IT ("Helpful Tips")

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6917]
#### User Story

As a member, I want more clarification about how to complete a campaign. As an admin, I'd like these helpful tips to be a clear separate section.
#### Additional Information

The "Helpful Tips" section would go after the "Report back Copy" in the backend.
- [ ] Add a section that is "Helpful Tips" in the PROVE IT section
  ![screen shot 2016-08-22 at 1 31 18 pm](https://cloud.githubusercontent.com/assets/2658867/17864606/bb0b5f9a-686c-11e6-8882-5cfd9fcc6231.png)
  ![screen shot 2016-08-22 at 1 31 47 pm](https://cloud.githubusercontent.com/assets/2658867/17864622/cbc94da6-686c-11e6-8579-e46277a92a6b.png)
- [ ]  **Pre-populated text**: These tips should be added to all campaigns and show up in the Drupal text box so that the campaign lead knows what the helpful tips are that will show up and edit or delete if they need to -- they should be able to add helpful tips before or after these prepopulated tips:
- Upload your photos as you go. As soon as you have one or more [Report Back Noun] [Report Back Verb], take a photo and upload it!"
- Upload one photo at a time.

![screen shot 2016-08-22 at 1 34 22 pm](https://cloud.githubusercontent.com/assets/2658867/17864724/3d8c74d6-686d-11e6-89f2-0665fea3dc41.png)
- [ ] Instruction Text for the Helpful Tips section (for the campaign lead to understand what to do with this new field)

_Above are some commonly used Helpful Tips, feel free to delete or edit these pre-filled tips to better match your campaign. If this campaign has a scholarship, be sure to add a helpful tip about how to qualify for the scholarship -- this should be the first item in the list. Be explicit and stress the simplicity of the process._ 

![screen shot 2016-08-22 at 1 45 02 pm](https://cloud.githubusercontent.com/assets/2658867/17865063/b98cbdf6-686e-11e6-8ea5-9ff3b3e33f0d.png)
#### Why This Matters

Trying to remove any confusion about how to reportback and why they should do it.

**Comment by angaither** [comment]
Lots of questions on this one.
- Do we want this field to be translated? 
  - if so, do we provide a default in each translation? 
  - if we do provide a default in each translation, I'm not sure that's a thing drupal supports
  - does it make sense to provide a default if we need to get this translated?
- Without running a script, there isn't a way to automatically backfill content to apply that default across any campaign that already exists
- I don't think we can use the reportback noun/verb as placeholders within the node itself
  - I could be wrong about this, but I couldn't find an example
  - because of that, it would be additional work to make that auto-replace.

**Comment by ngjo** [comment]
@angaither apologies in advance for the obvious questions im about to ask to then attempt to answer your questions!

**translation**
- Is there a way to have a field only on the US site? (i'm guessing not if you're asking about translations, but wanted to confirm)
- So if we had default text in there, that (english) text would appear on all experiences (MX, BR, global) right? If so, then yeah, we prolly shouldn't have default text in there then. 
  -So if we just have the field "Helpful Tips", it would only show up on the front-end if the user put content in the field? or would "helpful tips" always show up on the live site?
- Can we translate a field later on if we wanted or needed to or is this a mess?

**script**
- just to weigh the option -- how difficult would that script be to build and/or run? would it become more complicated if the field is/isn't translated?

**reportback noun/verb**
- would you be able to confirm whether or not this is doable? if it's not doable, could you outline a little more what the additional work would entail? (so we can weigh the option or nix it)

thaaaanks!

**Comment by angaither** [comment]
@ngjo if we aren't providing default text, the script and the reportback noun is all a non issue as the campaign lead would be able to add the noun and the verb into the text on a per campaign basis.

helpful tips would only exist if the campaign lead entered text in the box. 

translation - it's somewhat of a pain to add in later, if we don't translate the field it will show up (in english) on all translations

**Comment by ngjo** [comment]
@angaither let's translate the field now then and don't provide default text in there or the reportback noun/verb (we'll want to add more instruction text where the commonly used helpful tips are though so the lead can just copy and paste from there). ill sync w/ michaela that we're adding the field and she can relay it to the admins of hte other sites.

oh i dont think i asked this, but the field will be able to support markdown?

What do you need from me to "translate" the fields? Do you need to know what "helpful tips" is in the other languages?

Would we still be able to run the script to backfill text (not using the reportback noun/verb) for the majority of the campaigns for the US experience?

**Comment by angaither** [comment]
if we aren't providing default text we don't need
- to know what "helpful tips" is in the other languages? 
- and won't need to run a script to backfill

**Comment by ngjo** [comment]
kk -- sounds good, so to confirm, we're going to:
- \- add the helpful tips section that will be translated (meaning that other experiences can add their own helpful tips in their language)
- -add instruction text to the helpful tips section (that will include some commonly used helpful tips for the campaign lead to copy and paste into the field)
- -we won't be adding default text to the field
- -the field will accept markdown

for the "helpful tips" other language thing, I was talking about the title header "helpful tips." if they added helpful tips in spanish, would the title "helpful tips" itself appear in spanish or would we need to code it in spanish (and portuguese for BR) right now? 

let me know if i got that down right, thanks @angaither !

**Comment by angaither** [comment]
ahh, the header, yes there are some additional steps to translate that actual header. 
I think we need to add it to the POT files and then upload translations somehwere (@weerd knows the details)

But FWIW, we haven't been doing for other text that we recently added to the template (#6915, #6913, #6914)

**Comment by ngjo** [comment]
mmhhh right right, @angaither would it be worthwhile to create a separate issue that translates these other template texts for the other experiences and tackle them all at once down the line?

that way we can at least move forward now with this helpful text section?

**Comment by angaither** [comment]
YES! let's do that. 

>  would it be worthwhile to create a separate issue that translates these other template texts

please add the updated "instructional text" here so I can update the field ℹ️

**Comment by ngjo** [comment]
**Instructional Text**

Please use this section to outline some Helpful Tips for the member. Be explicit and stress the simplicity of the process.

Here are some commonly used Helpful Tips -- copy and paste and edit ones that are relevant to your campaign into the text field: 
- Upload your photos as you go. As soon as you have one or more [Report Back Noun] [Report Back Verb], take a photo and upload it!
- Upload one photo at a time.

Note: If this scholarship has a campaign, you should list any helpful tips about qualifying for the scholarship first. 

@angaither

**Comment by angaither** [comment]
from @ngjo 

> "Helpful Tips" only shows up if there's text in that field? Moving forward I'm pretty sure all campaigns will be using this section, but I'm more worried about it showing up on older campaigns w no tips filled in.
