### ISSUE TITLE
Matching custom social share font and size to DS standard

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6919]
#### User Story

Minor, but as an admin, I'd like for the custom social share link (wherever it shows up) to match the font/size of the regular DS text
#### Why This Matters

So it matches and isn't distracting

![screen shot 2016-08-22 at 2 17 38 pm](https://cloud.githubusercontent.com/assets/2658867/17868183/c5454dc2-687b-11e6-98dc-7652019f511f.png)

**Comment by katiecrane** [comment]
@ngjo at some point back during organs we were putting this in `<code>` tags so it looked like that. easy enough to pop those out though

**Comment by ngjo** [comment]
@katiecrane lets get those code tags outta here! thanks!

**Comment by ngjo** [comment]
Actually @katiecrane , just talked with @lkpttn about this -- he thinks that the < code> tags should be modified so that the text matches our text and is inline, lightly colored, with a touch of padding.

Example:
![screen shot 2016-08-23 at 9 51 47 am](https://cloud.githubusercontent.com/assets/2658867/17894757/7ba656f0-6918-11e6-99d0-4b2f06ae7138.png)

@lkpttn can you provide more detail here?

**Comment by katiecrane** [comment]
this isn't something that's already in forge is it?

**Comment by lkpttn** [comment]
@katiecrane We don't have a codified style for the `code` block so we could either do that or make it a modified blockquote.

**Comment by DFurnes** [comment]
Talked this over with @lkpttn this morning, and I think it'd make good sense add "padded gray box"  as a layout pattern in Forge. It might also make sense to give `<pre>` tags the same visual styles that we apply to `<code>` tags as well, although it'd also work to combine the two here `<code><pre>...</pre></code>`.

**Comment by katiecrane** [comment]
@DFurnes @lkpttn the gray box returns! sounds like a great idea!

**Comment by katiecrane** [comment]
another change we wanted to make is to put the buttons above the text (#6923). what are thoughts on the looks of this? @lkpttn @DFurnes (this is the same gray box that we made before for that other thing zombie style, using `#f7f7f7` for the gray color)

![image](https://cloud.githubusercontent.com/assets/4240292/17908668/69c38552-694f-11e6-908a-63caba092a76.png)

**Comment by lkpttn** [comment]
I might prefer the light grey we have in forge, #DDDDDD. I'll have to look at them side by side.

**Comment by katiecrane** [comment]
@lkpttn this is #DDDDDD

![image](https://cloud.githubusercontent.com/assets/4240292/17933619/c9c1f1e4-69e2-11e6-86ca-afcfb996c793.png)

**Comment by lkpttn** [comment]
Ok I guess I do fall back on #F7F7F7. Wanna hear from @DFurnes tho. Thanks Katie!

**Comment by DFurnes** [comment]
Let's add `#f7f7f7` as an `$off-white` color variable, since it seems to keep popping up. 👍 

@katiecrane You can add it to `app.scss` under a `// Variables` heading for now, and then we can merge it into Forge as another one of the "grayscale" shades later on.
