### ISSUE TITLE
campaign (header) – style sponsor logo

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#692]
Once Aaron passes over the sponsor logo, one version needs to be styled.

**Comment by mmwtsn** [comment]
H&M, Keri and Mike all prefer the lower right-hand corner treatment. As the design is not finalized, other versions will be tested in Optimizely.

**Comment by mikefantini** [comment]
Here is the H&M logo. Need it to be added here: http://staging.beta.dosomething.org/taxonomy/term/369/edit?destination=admin/structure/taxonomy/partners

![h m logo red](https://f.cloud.github.com/assets/6330971/2350762/895e7a6c-a574-11e3-93a1-b205f5b0eb46.png)

**Comment by mmwtsn** [comment]
Fixed by #1096
