### ISSUE TITLE
Whole competitions modal turning into a link

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6928]
#### Current Behavior

For some reason, all of the text in the competitions modal for under 18 folks on lose your v card is showing up as a clickable link. When you click it, it launches the share modal.

This is only happening on Thor, not Staging. 👻 !!!!
#### Desired Behavior

All the text in the competitions modal shouldn't be a clickable link.
#### Steps to Replicate
1. Go to Thor
2. Create an account as under 18
3. Sign up for ETF (https://thor.dosomething.org/us/campaigns/elephant-tusk-force)
4. You'll see the modal and all the text is a link
#### Why This Matters

It shouldn't be like this.
#### Relevant Screenshots + Links

![screen shot 2016-08-23 at 9 43 11 am](https://cloud.githubusercontent.com/assets/2658867/17897565/9c5d36ca-6922-11e6-8dfa-b5f2f32b65ed.png)

Here's what you cited in Slack, @katiecrane 

`$materials['content'] .= '<ul><li><a href="#" data-modal-href="#modal-share"> ' . $copy . '</li></ul>';`

**Comment by katiecrane** [comment]
closed with #6926
