### ISSUE TITLE
Theme oboarding as a modal

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#6929]
#### User Story

As a user, I should see onboarding as a modal instead of a dropdown.
#### Additional Information (optional)

This should only be used via a specific class flag, which we'll use Optimizely to apply
#### Why This Matters

We want to test if modals work better for the type of interaction we're looking for

**Comment by angaither** [comment]
@deadlybutter can you add some info here about how this works with other post-signup modals?
- signup data form
- voter reg
- competitions

**Comment by itsjoekent** [comment]
@angaither wont be used on any campaign with one of those modals, thats why its triggered by the flag class via optimizely

**Comment by angaither** [comment]
@deadlybutter is this done? can we close this out?

**Comment by itsjoekent** [comment]
yep sorry about that!
