### ISSUE TITLE
Any User Can Set Kudos Anonymously

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/legacy-website#6933]
#### Current Behavior

Full report here:

https://cobalt.io/dosomething/dosomething/reports/97
#### Desired Behavior

Provide authentication mechanism for Kudos to be restricted to individual user and not over-rideable.
#### Steps to Replicate

Check Cobalt report, or with @deadlybutter who's also re-created it.
#### Why This Matters

We want kudos to accurately reflect use trends and likes, and not be open to spammable/botnet behavior.

**Comment by sheyd** [comment]
@angaither Assign out as needed.

**Comment by angaither** [comment]
@deadlybutter mind taking a 👀  here since you replicated?

**Comment by itsjoekent** [comment]
@angaither as I mentioned in #security -- this feels like a good thing for oAuth to take care of. In the short term I guess we can use the csrf to validate in some way, ill have to poke diego about this one as im not familiar with how the api does auth

**Comment by DFurnes** [comment]
The authenticated user's session token and CSRF token should both be sent with all AJAX requests already, so you can compare the `$user` parameter against the `:user_id` in the endpoint function. Could work elegantly with an OAuth access token, but by no means requires it! :)

**Comment by itsjoekent** [comment]
things I would have never known before! thanks @DFurnes
