### ISSUE TITLE
campaign – dates missing form header sections

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#694]
There are no dates on the campaign pages (both pitch and action) in the header section over the campaign background image.

![dates](https://f.cloud.github.com/assets/1479130/2200446/779230ba-98e2-11e3-9428-66f91b5bba1b.png)

**Comment by barryclark** [comment]
@mmwtsn Is this blocked on any content type work? cc @aaronschachter

**Comment by mmwtsn** [comment]
This was closed by #767
