### ISSUE TITLE
Share modal link in the Do It Section not working

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6941]
#### Current Behavior

when you add the link to the share modal in the DO IT section, it appears as a link, but when you click it, the social share modal doesn't pop up. Instead, when you click it, it takes you to the top of the page.
#### Desired Behavior

We can add the link to the share modal in the DO IT section and when you click it, the share modal pops open.
#### Steps to Replicate
1. go to https://thor.dosomething.org/us/campaigns/elephant-tusk-force
2. scroll to do it
3. see the link "TEXT THAT IS THE LINK TO THE MODAL GOES HERE"
4. click it
#### Why This Matters

We're trying to surface teh Vcards as much as possible, and it would be a lot better if in the DO IT section when we reference the vcards, we can just link to the social modal instead of saying "and scroll back to the STUFF YOU NEED section and find that information there"

**Comment by katiecrane** [comment]
@ngjo this should be working now, there must have been a typo in the link

**Comment by ngjo** [comment]
Magic, thanks @katiecrane !!!
