### ISSUE TITLE
Magic link on prod doesn't work because of global redirect

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#6942]
#### Current Behavior
- after you click the magic link (in the app) it redirects to the country specific page
- this means an additional redirect query `redirect=campaigns/the-best-campaign` would be ignored and you are sent to the home page.
#### Desired Behavior
- you're logged in and redirected properly 
#### Steps to Replicate
- blah it's a whole thing
- Request a magic link from an authenticated API request
- Append a redirect query to that link
- Go to that link in prod

Look at [this PR](https://github.com/DoSomething/LetsDoThis-iOS/pull/1049) for more info

**Comment by aaronschachter** [comment]
@angaither I've just tested this morning with production and still get redirected to homepage at `www.dosomething.org/us`. Here's an example link:
https://www.dosomething.org/user/magic/3257305/1472569588/[removed]?redirect=node/2070

**Comment by angaither** [comment]
@aaronschachter hmmmmmm, which user? I tested this yesterday with my account & test account and it worked

**Comment by aaronschachter** [comment]
https://www.dosomething.org/us/user/3245402. I've just sent a 1.2.0(2) iOS build through Fabric that I've been seeing it with.

**Comment by angaither** [comment]
ah, ye ol' language mismatch will do it

That user is [`global-english` language on the profile](https://www.dosomething.org/us/user/3245402/edit), and the bumble bee's campaign [only exists in english](https://www.dosomething.org/us/node/2070/translate)

**Comment by aaronschachter** [comment]
Ah, snaps. That user was likely created before we [switched our API user's language](https://github.com/DoSomething/phoenix/issues/6251#issuecomment-194422333).

Tested with a new user and confirmed the magic link worked in app. Thanks @angaither!
