### ISSUE TITLE
Inconsistent structure in Kudos object in API depending on authentication status.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6948]
#### Current Behavior
- The `/reportback-items` endpoint includes reactions data for an item in the `kudos` property. However, depending on if you are making an auth'ed vs anonymous API request the structure of the `kudos` object is different. It is either a regular indexed array vs an associative array respectively.
#### Desired Behavior
- Structure of `kudos` object should be consistent regardless of authentication status, it should just be different in the data it exposes depending on access.
#### Why This Matters
- Consistent expectation of data structure in API responses is crucial!
#### Relevant Screenshots + Links

Authenticated API User:
![image](https://cloud.githubusercontent.com/assets/105849/17974654/e6e3bde8-6ab4-11e6-8e12-8249f4a3d218.png)

Unauthenticated API User:
![image](https://cloud.githubusercontent.com/assets/105849/17974674/f9c4493c-6ab4-11e6-8088-d82ac6c66886.png)

**Comment by jessleenyc** [comment]
Issue moved to [DoSomething/TeamRocket #8](https://github.com/DoSomething/TeamRocket/issues/8) via [**ZenHub**](https://www.zenhub.com/)
