### ISSUE TITLE
Dynamically update gallery likes from the likes received in onboarding

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6952]
#### User Story

As a user, if I liked a photo in onboarding, I want to see that reflected in the gallery when I scroll down in the action page. 
#### Additional Information (optional)

Since we're not using React to create the RB items in the Reportback gallery, we can't dynamically update RB items in gallery if the rb is liked in onboarding. 
#### Why This Matters

This can be confusing to the user and they should see that the photo they liked, is liked everywhere.

**Comment by itsjoekent** [comment]
Wait, have we tested / observed this? Im not sure why the API would return differently based on onboarding / campaign template / user profile, it uses the same data?

**Comment by itsjoekent** [comment]
OH now i get it...

**Comment by weerd** [comment]
:trollface: I've had it happen to me while working on Reactions on local development.

**Comment by jessleenyc** [comment]
Issue moved to [DoSomething/TeamRocket #7](https://github.com/DoSomething/TeamRocket/issues/7) via [**ZenHub**](https://www.zenhub.com/)
