### ISSUE TITLE
Add whatwg-fetch library to lib.js instead of webpack config.

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#6954]
The `whatwg-fetch` library is a polyfill we add to help browsers out that don't support the native `window.fetch` api. We currently include the library via the webpack config file, but typically we add our polyfills in the `lib.js` file. Let's move it in there and test to make sure the `ApiClient.js` is still working as it should!

**Comment by angaither** [comment]
> whatwg-fetch

![](https://i.kinja-img.com/gawker-media/image/upload/qfxawjsdwg20rhp1oqdi.gif)
