### ISSUE TITLE
action page (navigation) – nav. not scrolling

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#696]
Having issues using the new `position: sticky` polyfill to make the campaign navigation scroll with the user.

**Comment by barryclark** [comment]
@DFurnes Could you take a look at this guy. Thanks!

**Comment by mmwtsn** [comment]
:thumbsup:

**Comment by mmwtsn** [comment]
OK, I got this working. It looks like the issue was related to certain dependencies not installed during the [original installation](https://github.com/DoSomething/ds-neue/commit/32ffef5ae66f22af3a0748a40b6fc7b82e253496) of the polyfill. When re-installing at the Paraneue DS-level with Bower and including [the included CSS](https://github.com/filamentgroup/fixed-sticky/blob/master/fixedsticky.css) file, the polyfill was working.

That said, it was behaving strangely and only worked with native support disabled. I'm going to fall back to our original JavaScript implementation for launch.
