### ISSUE TITLE
action page (navigation) – section indicator

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#697]
When a user scrolls past a page section that should be reflected visually in the nav.

**Comment by barryclark** [comment]
Shooting this one over to you too @DFurnes

**Comment by mmwtsn** [comment]
@DFurnes [This](https://github.com/DoSomething/ds-neue/blob/highlight/js/nav-highlight.js) was working when I last touched it back when we were prototyping. Might come in handy if you don't feel like starting from scratch.
