### ISSUE TITLE
Translating additional campaign template text that we've added to US EN

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6970]
#### User Story

We've added some text to the template that should be translated into other languages
#### Need translations for this text
- [x] JOIN OTHERS MAKING A DIFFERENCE
- [x] Add your photo here for a scholarship entry!
- [x] Add another photo and we’ll check it out!
- [x] Add your photo here and we’ll check it out!
- [x] Your Impact
- [x] Enter # here -- like '300' or '5'
- [x] No need to write an essay, but we'd love to see why this matters to you!
- [x] Helpful Tips
#### Already in POEditor
- [x] Explore Campaigns
- [x] What is DoSomething?
- [x] Any Cause, Any Time, Anywhere
- [x] Young People + Social Change
#### Additional Information (optional)

See context in these issues: #6915, #6913, #6914, #6917 
#### Why This Matters

So that it's translated for non US experiences!

**Comment by weerd** [comment]
@ngjo @jessleenyc cc: @mikefantini 

Some of the items in the list above are already in POEditor and have actually been translated... were they on this list because they're not working?

**Comment by ngjo** [comment]
Hey @weerd -- do you have screenshots of what's translated already in POEditor? I can use it to dig into this more. There were some funny translation issues for Global that might mean that they weren't working...

**Comment by weerd** [comment]
@ngjo I added you as a contributor to the POEditor project. I can see if I can make you an admin once you create an account... I could only add you to the spanish translations at the moment. But you can search in there for terms. There's way too many to send screenshots of them @_@
