### ISSUE TITLE
Prevent Facebook from violating the content security policy

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#6981]
![screen shot 2016-08-31 at 10 26 36 am](https://cloud.githubusercontent.com/assets/897368/18132609/7f1dc37e-6f65-11e6-8dd7-d9e4f2f41536.png)

**Comment by DFurnes** [comment]
References DoSomething/phoenix#5783.

**Comment by itsjoekent** [comment]
temp workaround was just adding the *.facebook.com to scripts, iframe, etc rules. and *.facebook.net to the script rule 

(Facebook has a dot net?!)
