### ISSUE TITLE
[SA-CONTRIB-2016-050] Flag module: Information Disclosure

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#6988]
## _Flag module: Information Disclosure_

[Flag](https://www.drupal.org/project/flag) module is vulnerable and must be updated. View report on Drupal.org: https://www.drupal.org/node/2793115
- Advisory ID: DRUPAL-SA-CONTRIB-2016-050
- Project: [Flag](https://www.drupal.org/project/flag)     (third-party module)
- Version: 7.x
- Date: 2016-August-31
- Security risk: 12/25 ( Moderately Critical)
  AC:None/A:User/CI:Some/II:None/E:Theoretical/TD:Default
- Vulnerability: Information Disclosure
## _SOLUTION_

Install the latest version:
- If you use the Flag module for Drupal 7.x, upgrade to [Flag 7.x-3.8](https://www.drupal.org/node/2793073).

cc @angaither @blisteringherb

**Comment by angaither** [comment]
we can just disable this module. we don't use it.

**Comment by sergiitk** [comment]
Even better.
