### ISSUE TITLE
Content changes to lose your v card

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6999]
- [x] In the registration modal (both when you first sign-up and when you click on it from the "Stuff you Need" section: We changed the text around and link to the share modal instead, so we want to remove the social stuff in the rectangle. I tried doing this in Optimizely, but when I changed it on the registration modal, it changed the competition modal:

![screen shot 2016-09-02 at 1 27 14 pm](https://cloud.githubusercontent.com/assets/2658867/18212592/0284d8da-7112-11e6-8fce-a5d50909878b.png)
- [ ] I have an optimizely fix in for this one, but it's annoyingly only working in one of the registration modals. Can we get some padding around the X in the top right corner of the registration modal:
  ![screen shot 2016-09-02 at 1 38 04 pm](https://cloud.githubusercontent.com/assets/2658867/18212705/94f8390a-7112-11e6-9383-d19d5e8cb895.png)
- [x] On the competitions modal here:
  ![screen shot 2016-09-02 at 1 51 00 pm](https://cloud.githubusercontent.com/assets/2658867/18213071/5506abf4-7114-11e6-8e75-384958962501.png)

replace that content with:

_Below is your unique registration link to share for this competition. If you click on one of the social media icons below, this will automatically share your unique registration link! Tag friends so they sign up to register to vote and move you up the competition leaderboard!_
- [ ] im sneaking this one in there, if it's possible. in optimizely, i can't hide the "skip" button on the competitions modal without it it also hiding on the register to vote modal (they're tied!)...would it be possible for you to hide the competition modal's skip button?

let me know if you have any questions and THANK YOU so much! forthcoming, a process that avoids these last minute changes!

**Comment by angaither** [comment]
@ngjo you should be able to unclick 'allow skip' in the signup data form setup re:

> hide the "skip" button

**Comment by ngjo** [comment]
@angaither i think the only problem is if i hide teh skip on the competitions modal, it hides the X on the registration modal.

"allow skip" also generates the "no thanks" at the bottom of join too. but no worries, it's easier to just have the skip on the competition too and if we really have to, ill jump into optimizeyl and try to make something happen, lol. thanks!
