### ISSUE TITLE
QA: Tests should run in a separate DB

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#70]
This is the default behavior for Drupal's Testing module, to create a copy of the database.

The legacy testing_suite runs an override to prevent this from happening and actually runs the tests on the QA database, adding/deleting nodes, users to the QA db.  No bueno.  Keep it separated.

**Comment by aaronschachter** [comment]
I suppose this can be closed for now, as the tests do run in a separate DB.  It will however make an automated full SimpleTest of all tests in the DoSomething group run slowly.  But, perhaps we don't need to worry about this yet.

**Comment by mchitten** [comment]
Closing this until we come to that bridge.
