### ISSUE TITLE
action page (know it) – "the problem" video / image placeholder is missing

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#700]
Both the YouTube video and it's fallback placeholder are missing inside "the problem" section of the Action Page's "know it" section.

**Comment by barryclark** [comment]
@mmwtsn should these be assigned to backend, or are you still looking at them?

**Comment by mmwtsn** [comment]
@barryclark This one is on me. If there is an issue on the module side I'll shoot it over to Aaron.

**Comment by barryclark** [comment]
Awesome, ty

**Comment by mmwtsn** [comment]
Resolved. Possibly by #806.
