### ISSUE TITLE
Let FB users login with oauth credentials

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#7003]
Checkout this magic https://api.drupal.org/api/drupal/modules!user!user.module/function/user_external_login_register/7.x

Blocked by oauth token verification endpoint Im gonna be adding to NS

**Comment by DFurnes** [comment]
> Blocked by oauth token verification endpoint Im gonna be adding to NS

Is there an issue describing this some more? 🌵

**Comment by itsjoekent** [comment]
Nope! I'll make it over in the NS repo in a bit, been wrapping up the Drupal stuff
