### ISSUE TITLE
Mockup: Slide 1 & 3 Design Changes

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#7036]
_TASK_
Create mockups for swapping slide 1 & 3. Thoughts:
- Does slide 1 text need to be shortened to show reportbacks?
- How many reportbacks do we show?
- Don't forget to create mockups for desktop, tablet, and mobile!

**Comment by lkpttn** [comment]
I have a couple initial ideas that I think are worth noodling on.
- Same copy with 4 reportbacks (very tall probably)
- Less copy with 4 reportbacks (less tall?)
- Same copy with single reportback in feature card slot (does this achieve our goal?)
  - Could change info to showcase the member more
- Same copy, two reportbacks (50/50 split)

**Comment by lkpttn** [comment]
![reportbacks](https://cloud.githubusercontent.com/assets/1865372/18595409/a4ba580e-7c12-11e6-883e-026d5c872731.png)
