### ISSUE TITLE
Swap slide 1 & 3

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#7037]
_TASK_
Resort the order of onboarding so the reportbacks are displayed first w/ a welcome message and additional campaign signups are shown last.

**Comment by jessleenyc** [comment]
@deadlybutter no longer blocked on design! Still waiting on updated copy but hopefully this will be enough to get you started.

https://cloud.githubusercontent.com/assets/1865372/18595409/a4ba580e-7c12-11e6-883e-026d5c872731.png

**Comment by itsjoekent** [comment]
@jessleenyc Maybe I'm missing something... has something changed besides the amount of RB's to display? We decided in Slack yesterday how to handle that per device so I never felt blocked on this issue
