### ISSUE TITLE
Mockup: Three Cards 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#7039]
_TASK_
Create mockups to show three campaigns that users can sign up for and how copy should be placed. Please provide mocks for mobile, tablet, and desktop.

**Comment by lkpttn** [comment]
![campaigncards](https://cloud.githubusercontent.com/assets/1865372/18595423/ab7a60c6-7c12-11e6-9cef-7e4eea1424b4.png)

**Comment by lkpttn** [comment]
^ blue text is an accident!

**Comment by lkpttn** [comment]
<img width="1107" alt="screen shot 2016-09-16 at 1 40 16 pm" src="https://cloud.githubusercontent.com/assets/1865372/18595537/2acfda54-7c13-11e6-9570-49a9a22567d4.png">
