### ISSUE TITLE
Display Three Campaign Signup Cards

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#7042]
_TASK_
Show three campaigns on last slide of onboarding. Once the mockup is ready, I'll add it to this ticket.

**Comment by jessleenyc** [comment]
@deadlybutter - mockups, still waiting on updated copy. https://cloud.githubusercontent.com/assets/1865372/18595537/2acfda54-7c13-11e6-9570-49a9a22567d4.png

**Comment by itsjoekent** [comment]
Also @jessleenyc in the future can we link to the issue Luke was working in rather than the png itself?

**Comment by jessleenyc** [comment]
@deadlybutter absolutely! do you want the png link also or just the link to the issue?

#7039

**Comment by itsjoekent** [comment]
Just the issue is fine! :D

**Comment by itsjoekent** [comment]
Note: Only remaining task here is styling. Markup is on the page!
