### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#7064]
_TASK_
QA tasks completed in this story.
- [x] Campaigns are pulling in the right order --> staff pick/instant
- [x] Checkmark appears after a user signs up for a campaign
- [x] Campaigns signed up for appear in user profile
- [x] Design QA by Luke
- [x] Safari
- [x] IE
- [x] Chrome
- [x] Firefox
- [x] Android
- [x] iOS Chrome
- [x] iOS Safari

**Comment by itsjoekent** [comment]
@jessleenyc ready for QA!

**Comment by jessleenyc** [comment]
Leaving a note here that iOS Safari works but not on private browsing.
