### ISSUE TITLE
action page (do it) – last content section missing copy

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#707]
The last section of the "do it" section of the action page is not displaying any copy. It is simply printing a single letter.

**Comment by barryclark** [comment]
@aaronschachter This one is bizzare. Any idea what's going on here?

**Comment by barryclark** [comment]
@aaronschachter @angaither Any ideas? 

Example here: http://stage.dosomething.org/campaign/19# There should be more content displayed below "Hype It Up" near the bottom of the page.

**Comment by barryclark** [comment]
Thanks @angaither!
