### ISSUE TITLE
Dev / QA: DB scrub script

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#71]
This script should run when a dev or QA instance is setup.  It should:
- Anonymize user data, and/or possibly delete all users with uid != 1, and then add a few authenticated users with the various roles defined in dosomething_user.
- If lots of nodes, delete them to maintain a very small set of content.

**Comment by mshmsh5000** [comment]
devel_create_users() should work nicely here. Just need to make sure we don't break important DB references (node creator nids, etc.).

**Comment by aaronschachter** [comment]
This isn't necessary for milestone 0.1 -- we don't have any users yet.  Keeping open but removing milestone.

**Comment by barryclark** [comment]
@aaronschachter @mshmsh5000 this seems necessary for milestone 0.2?

**Comment by aaronschachter** [comment]
I agree, once we import all of our users into the beta site db, we'll want this.   I believe this would be happening in 0.2

**Comment by barryclark** [comment]
Assigning over to @mshmsh5000

**Comment by aaronschachter** [comment]
Still open - moving into backlog.

**Comment by mshmsh5000** [comment]
Here's a Classic Issue :older_man: :older_woman: we should resuscitate.

We run into dev problems when working with a restrictive set of content locally. I'd much rather have a working set that has
- A full set of content (campaigns, facts pages, static content, etc.)
- A small set of member users

**Comment by angaither** [comment]
I think we can actually close this one out, if we aren't gong to be moving QA into dev. and stage is mainly good enough for dev
