### ISSUE TITLE
Global feature flag to turn Rogue

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#7107]
#### User Story

As an admin, I want to be able to be able to turn rogue collection of reportback on for all campaigns instead of per campaign.
#### Additional Information (optional)

We currently have a feature flag that is set per campaign to turn rogue collection on/off for that node. [We want to change this to be a global feature flag](https://github.com/DoSomething/phoenix/pull/7102#issuecomment-251706307) that when turned on will start posting reportbacks to rogue for all campaigns across the site.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to have a global feature flag to turn Rogue on for all campaigns](https://trello.com/c/ZDpieyHx/92-as-a-developer-i-want-to-have-a-global-feature-flag-to-turn-rogue-on-for-all-campaigns)
