### ISSUE TITLE
Send northstar user id to rogue

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#7110]
#### User Story

Send northstar user id over to rogue when we send a reporrback.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) As a developer, I want Rogue to have the Northstar ID so that I know the member whose RB it is.](https://trello.com/c/sl8S6ytY/49-1-as-a-developer-i-want-rogue-to-have-the-northstar-id-so-that-i-know-the-member-whose-rb-it-is)
