### ISSUE TITLE
Rogue failure experience for end users. 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#7116]
#### User Story

As a user, if my reportback doesn't successfully get sent to rogue or get sent back to phoenix, I would like to see some sort of messaging or experience that indicates my reportback was submitted even though I don't get taken to the permalink page. 
#### Additional Information (optional)

When rogue is turned on we attempt to send the reportback to rogue and the the reportback gets sent back and stored in phoenix. We then direct the user to the permalink page that confirms the submission was received. If something errors out on the backend with sending the RB to rogue or sending it back to Phoenix we should have some sort of sensible experience that lets the user know what's going on. We are logging stuff on our back end, but don't surface things to user. 
#### Current Workaround w/o Feature (if applicable)

Currently, we just reload the campaign page.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an admin, I want users to receive error messages if there's an error in rogue receiving/sending reportbacks to/from phoenix.](https://trello.com/c/qIEUGdWk/98-as-an-admin-i-want-users-to-receive-error-messages-if-there-s-an-error-in-rogue-receiving-sending-reportbacks-to-from-phoenix)
