### ISSUE TITLE
Allow campaign signups as a result of OpenID Connect logins.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#7122]
#### User Story

As an engineer, I want campaign sign ups to work when authenticating through northstar so that I can deploy northstar auth to prod.
#### Additional Information (optional)

Currently, OpenID Connect login always redirects you to your user profile. This is usually what we want, but for campaign signups we "bundle" the signup action alongside logging in. So once the user is redirected back from Northstar, we want to automatically sign them up for the right campaign.
#### Why This Matters

We need this to ship OpenID Connect authentication on prod.
#### Current Workaround w/o Feature (if applicable)

No.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) As an engineer, I want campaign sign ups to work when authenticating through northstar so that I can deploy northstar auth to prod.](https://trello.com/c/z0DUetm4/67-5-as-an-engineer-i-want-campaign-sign-ups-to-work-when-authenticating-through-northstar-so-that-i-can-deploy-northstar-auth-to-p)

**Comment by angaither** [comment]
FWIW we've had this (https://github.com/DoSomething/phoenix/issues/1289) issue since forever, and it might be worth re-thinking the log/in sign-up functionality on a campaign

**Comment by DFurnes** [comment]
Agreed! 👍
