### ISSUE TITLE
checking on status of posting to Rogue with Gateway

### ISSUE THREAD

**Issue by katiecrane** [DoSomethingArchive/legacy-website#7123]
#### Current Behavior

When submitted a reportback to Rogue, we currently check the code of the response that we get back from Gateway. However, what gets returned back to us is not the full response but is just the reportback. So, when we try to get the response code, we get nothing, which makes us think that the task failed. The reportback ends up in the normal table AND the failed task table, and the user does not end up on the permalink page, even though their reportback was successfully posted.
#### Desired Behavior

We don't want reportbacks that were posted successfully in the failed task log, and we want users to hit the permalink page if their reportback was successfully posted.
#### Steps to Replicate

Turn on Rogue and submit a reportback.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to check for Rogue failures in a way that works with the Gateway response.](https://trello.com/c/Mq96cp5X/108-as-a-developer-i-want-to-check-for-rogue-failures-in-a-way-that-works-with-the-gateway-response)
