### ISSUE TITLE
Validation messages are broken everywhere.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#7129]
#### Current Behavior

Validation messages get unnecessary padding and break the layout, likely as a result of https://github.com/DoSomething/forge/pull/563.
#### Desired Behavior

Validation messages should not look broken.
#### Steps to Replicate

Use any form on the site with a validation message.
#### Why This Matters

It looks broken.
#### Countries Affected (optional)

All.
#### OS/Browser (optional)

Every.
#### Relevant Screenshots + Links

![screen shot 2016-10-17 at 4 36 36 pm](https://cloud.githubusercontent.com/assets/583202/19454666/0b6fe130-9488-11e6-9d9a-f8a3cc832b79.png)

![screen shot 2016-10-17 at 4 38 16 pm](https://cloud.githubusercontent.com/assets/583202/19454685/1e7ca9ac-9488-11e6-89c8-ae98ccdf50ea.png)

**Comment by itsjoekent** [comment]
so the package.json specifies `"@dosomething/forge": "~6.7.7",` & we reverted the change in `6.7.8` but for some reason it's not using the new version. Yet the ~ should catch the minor revision to dot 8....

https://github.com/DoSomething/forge/commit/ad78f1eb67365bef646018d368b56f6cdac89d82

**Comment by itsjoekent** [comment]
the version of Forge on prod is `"version": "6.7.8",` -- so this is pretty strange

**Comment by itsjoekent** [comment]
hmm, wondering Is it possible there is a caching issue?

**Comment by itsjoekent** [comment]
Yeah that was it, Sena just purged the cache and its back to normal
