### ISSUE TITLE
User: PHP Notice in dosomething_user_form_alter

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#713]
When securepages is disabled:

`Notice: Undefined variable: secure_url in dosomething_user_form_alter() (line 100 of /vagrant/lib/modules/dosomething/dosomething_user/dosomething_user.module).`

Setting a default value for $secure_url in case securepages is disabled would fix.

**Comment by mshmsh5000** [comment]
FYI, I made a hot fix to the staging instance so this error wouldn't freak out the content editors. We can update properly tomorrow.
