### ISSUE TITLE
Auth modals in campaign template

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#715]
When I click the signup button on a pitch page (http://stage.dosomething.org/node/5
) it should trigger the auth modal, then redirect me to the action page after authenticating. 

Shooting this one over to you @DFurnes, give @aaronschachter a shout if you need anything else.

**Comment by mmwtsn** [comment]
This can be tested once `user.js` is deleted as discussed in Pull Request #724.

Users are able to authenticate from the pitch page, however, the destination of the redirect post form submission is **/user/login**, not the current node.

**Comment by DFurnes** [comment]
I think the way we settled on handling this was including a hidden form element that includes the NID of the campaign to redirect to. What's the status on that?

/cc @angaither b/c User module stuff!

**Comment by barryclark** [comment]
@angaither Shooting this one over to you, would be great to get the flow working as soon as possible.

**Comment by angaither** [comment]
@DFurnes the `nid` should be displaying in the HTML in the form login on all campaigns. 
After the user submits the login/registration form it redirects to the campaign node. 
The only part that I think is missing is the actual `signup` button doesn't trigger the modal.

**Comment by aaronschachter** [comment]
This may be an issue with just the class/id on the button: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L371

**Comment by angaither** [comment]
This is working. :dancers:
