### ISSUE TITLE
Do not send a rb item's updated status to Rogue if the rb item doesn't exist in Rogue.

### ISSUE THREAD

**Issue by chloealee** [DoSomethingArchive/legacy-website#7158]
#### User Story

If a rb item doesn't exist in Rogue, Phoenix shouldn't send the updated status to Rogue when an admin reviews rb items. 
#### Why This Matters

Since we aren't migrating data before turning on Rogue, things will break if we don't fix this!

**Comment by katiecrane** [comment]
I don't think this is a bug.

Steps:
1. Turn Rogue off
2. Submit a reportback
3. Turn Rogue on
4. Add another image to that reportback
5. Review both reportback files
6. I didn't get any errors and all statuses updated correctly in both Phoenix and Rogue databases

Code that takes care of this: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.admin.inc#L288-L292

**Comment by chloealee** [comment]
ah yes - thanks for finding this, @katiecrane ! I will close this now.

**Comment by katiecrane** [comment]
confirmed! I printed out the data that was getting passed to `dosomething_rogue_update_rogue_reportback_items` and got

```
array (size=1)
  0 => 
    array (size=2)
      'rogue_reportback_item_id' => string '174' (length=3)
      'status' => string 'accepted' (length=8)
```

when I updated TWO files, not one 😄

**Comment by chloealee** [comment]
@katiecrane the above is for a separate issue, right? Looks like it is still a bug then since it's only sending one updated reportback item instead of of two?

**Comment by katiecrane** [comment]
@chloealee No that's for this issue. I followed the Steps listed in the above comment but just printed out the data to make sure it wasn't actually sending more updates than it appeared to. It should only be sending one because only one exists in Rogue.
