### ISSUE TITLE
Message Broker and drush.make - how to include libraries with depenancies

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#716]
The messagebroker-phplib library is needed for the message_broker_producer.module.  messagebroker-phplib is defined as a drupal library but messagebroker-phplib has additional dependancies of libraries defined in composer.json.

Are the following changes to drush.make sufficient for this addition?

```
; Message Broker PHP Library
libraries[messagebroker-phplib][download][type] = "git"
libraries[messagebroker-phplib][download][url] = "https://github.com/DoSomething/messagebroker-phplib.git"
```

@desmondmorris 
How do I get the additional composer defined dependancies defined in composer.json to be installed in /vendor as well? 

```
; GIT PROJECTS

; Message Broker Drupal 7.x Producer
projects[message_broker_producer][type] = "module"
projects[message_broker_producer][download][type] = "git"
projects[message_broker_producer][download][url] = "https://github.com/DoSomething/message_broker_producer.git"
projects[message_broker_producer][subdir] = "contrib"
```

**Comment by desmondmorris** [comment]
Tag a release with the vendors dependencies included, then point to the tag from the make file.  I think that is the best way, without adding complexity to our process at this very moment

```
`download[type] = git`
Use a git repository as the source for this project. Options:
`url` - the URL of the repository. Required.
`branch` - the branch to be checked out. Optional.
`revision` - a specific revision identified by commit to check out. Optional.
`tag` - the tag to be checked out. Optional.
```

per: http://drush.ws/docs/make.txt
