### ISSUE TITLE
Hook up report back modal

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#717]
The modal doesn't need to be styled yet, but getting it triggering and functional so that we can test the full campaign flow is a priority. 

[Modal Documentation](https://github.com/DoSomething/ds-neue/blob/dev/js/modal.js)

**Comment by mmwtsn** [comment]
Are we default to register or log in across the new site?

**Comment by mikefantini** [comment]
@mmwtsn - default to log in

**Comment by mmwtsn** [comment]
This issue was incorrectly referenced by #724. Report back modals still needed.
