### ISSUE TITLE
reportback file source not sent to Rogue

### ISSUE THREAD

**Issue by katiecrane** [DoSomethingArchive/legacy-website#7189]
_BUG_
-------------------
#### Current Behavior
If a reportback file has a `source` and is sent to Rogue, the `source` is not.

#### Desired Behavior
Send the `source` to Rogue.

#### Steps to Replicate
Seems that `source` is only set on files that were created via calls to the Phoenix api, so need to check for it when sending items that already exist.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(4) As a developer, I want to send the "source" in Phoenix over into Rogue](https://trello.com/c/GaUHA9Zv/156-4-as-a-developer-i-want-to-send-the-source-in-phoenix-over-into-rogue)
