### ISSUE TITLE
Dev: Reject pull request if any DoSomething SimpleTests fail

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#72]
Likewise, when QA runs scripts - it should fail if a DoSomething Simpletest fails.  Currently, it only fails if a Behat test fails.

**Comment by mchitten** [comment]
We'll probably have to build a custom script for this one -- Unfortunately, SimpleTest doesn't send a KILL message back, to stop tests.   Most likely we'll need a watch script to listen for "1+ Error" or "1+ Exception" and kill tests accordingly.

**Comment by desmondmorris** [comment]
It would make it impossible for us to open pull requests early to get developer feedback.  Especially feedback concerning broken tests.  I vote to -1 this one

**Comment by mshmsh5000** [comment]
I think we should only automate the rejection of production builds based on tests. Failing tests at other stages constitute interesting information.

If we create a stable staging instance for partner/sponsor review, we may kill that build on test failure as well.

**Comment by aaronschachter** [comment]
Closing this for now as well - we can revisit once a prod environment is alive.
