### ISSUE TITLE
Add CAPTCHA to the Contact Us Modal

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7245]
_FEATURE OVERVIEW_
-------------------
#### User Story
From Hannah: We are receiving thousands of spam messages a month from the Contact Us modal on various SMS games. We batch select and mark the tickets as spam but ideally, we would be able to implement a spam deterrent so the tickets are not routing into Zendesk in the first place. I have reached out to Zendesk and if we are able to provide them with additional info on the ticket creation process, they may be able to help. Here is what they had to say:

"Can you tell me where you have a ticket creation process deployed? Since you seem to have a customized process for this you will likely need to have your developers implement some sort of spam deterrent such as requiring users to login, captcha, or some other spam prevention tool that would prevent tickets from being submitted."

#### Additional Information (optional)
I tried to see if I could add it in myself and I came across this: https://www.drupal.org/node/1254710 -- I couldn't even find the User Management, lol. Might help you more than it did me!

This is specific to SMS games where you don't have to be logged in to submit a support ticket -- but if it's easiest to add teh CAPTCHA to all support modals, that's fine too.

I also have some DS ZenDesk URLs that I wasn't sure where to post them -- let me know and I can share them with you.

#### Why This Matters
Too much spam! 

#### Current Workaround w/o Feature (if applicable)
Manually removing spam.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zendesk spam tickets: Implementing CAPTCHA?](https://trello.com/c/TgXIP0gj/1616-zendesk-spam-tickets-implementing-captcha)

**Comment by itsjoekent** [comment]
closed https://github.com/DoSomething/phoenix/pull/7437
