### ISSUE TITLE
Tags Needed for Adding Images

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#728]
- add report back tag
- add indoor tag
- add outdoor tag

cc: @barryclark

**Comment by mikefantini** [comment]
@angaither thinking about this more you're right -> we should change "report back" tag to be "user submitted"

**Comment by barryclark** [comment]
:thumbsup:

**Comment by mikefantini** [comment]
@angaither not seeing this reflected in staging. can we connect on this in the morning?

**Comment by angaither** [comment]
Terms were removed by this [commit](https://github.com/DoSomething/dosomething/commit/a933009702cb6a307f92c32ecb7949199aedf502)
