### ISSUE TITLE
Crop button doesn't work

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7298]
_BUG_
-------------------
#### Current Behavior
Not able to crop the photo which is preventing people from reporting back.

#### Desired Behavior
You can use the crop functions and crop the photo to upload

#### Steps to Replicate
1. go to a campaign
2. sign up
3. upload a photo
4. resize
5. try to click crop (might not work)

#### Why This Matters
people can't reportback

#### OS/Browser (optional)
On whatismybrowser.com/w/T5ADRGE and was able to use the resize cropping thing, but wasn't able to click Crop.

#### Relevant Screenshots + Links
Zendesk problem ticket (click 'incidents' at top of ticket to see all tickets): https://dosomethingorg1.zendesk.com/agent/tickets/274340

Video example of not being able to click crop button: https://dosomething.slack.com/files/jen/F3ZH6V3E3/cant_click_crop.mov

Seemed like refreshing the page and then reuploading made it work...

**Comment by DFurnes** [comment]
This one was pretty strange – the best guess I have is that a cached version of the script for that page was being loaded and somehow failed to register the client-side validation function.

@ngjo, @hbghidey, and I were all able to reproduce this issue at the time, and then magically [refreshing the page seemed to fix it](https://dosomething.slack.com/archives/campaign-template/p1485877631000234) for all of us... not sure if that means something changed server-side, or anyone experiencing this issue should just refresh to clear it up.

**Comment by mshmsh5000** [comment]
We should see the number of incidents decline over time if it's a cached-script problem.

**Comment by mirie** [comment]
Per @hbghidey this issue has been resolved!

There was an issue with the jump link and it was causing users to have issues zooming + submitting reportbacks.  We were able to recreate by using the broken URL > uploading a photo (which doesn’t show up) > clicking submit > photo shows up zoomed in.

• Here’s the URL: https://www.dosomething.org/us/campaigns/love-letters-challenge?source=gladiator&utm_source=dosomething&utm_medium=email&utm_campaign=Gladiator#prove

• Here’s my RB: https://www.dosomething.org/us/reportback/231796?fid=338718
