### ISSUE TITLE
Closed campaigns showing up on taxonomy pages

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7305]
_BUG_
-------------------
#### Current Behavior
On some taxonomy pages like https://www.dosomething.org/us/volunteer/environment, you can see that there are closed campaigns showing up like Planet Zombie (https://www.dosomething.org/us/campaigns/planet-zombie?source=taxonomy/term/4) or GTFO (https://www.dosomething.org/us/campaigns/gtfo?source=taxonomy/term/4).

#### Desired Behavior
Only active campaigns show up on these taxonomy pages.

#### Steps to Replicate
1. Go to a taxonomy page like https://www.dosomething.org/us/volunteer/environment  or https://www.dosomething.org/us/volunteer/animals
2. Open some campaigns and see that some are closed

#### Why This Matters
-Marketing will be using these pages to pitch campaigns around cause spaces to potential partners and they should be open campaigns to show there's lots of options.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an admin, I don't want closed campaigns to show on the taxonomy pages](https://trello.com/c/eUFOstA9/255-as-an-admin-i-don-t-want-closed-campaigns-to-show-on-the-taxonomy-pages)

**Comment by DFurnes** [comment]
This seems to be happening in [`dosomething_taxonomy_get_campaigns`](https://github.com/DoSomething/phoenix/blob/a05bd197bea695eed6cd0ff58d796d94a886f3a0/lib/modules/dosomething/dosomething_taxonomy/dosomething_taxonomy.module#L111-L128) which pulls from the `campaigns_by_term` view. Adding an "is active" filter to that view should be a quick fix.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Showing closed campaigns on taxonomy collections](https://trello.com/c/N2sOv4Pg/1651-showing-closed-campaigns-on-taxonomy-collections)
