### ISSUE TITLE
Error when providing Northstar ID to signups endpoint.

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#7329]
_BUG_
-------------------
#### Current Behavior
@aaronschachter reported a bug with the Phoenix signups endpoint [in Slack](https://dosomething.slack.com/archives/C02BBRN5A/p1490378610150414):
> hey @weerd -- i remember you mentioned a change made to the Phoenix signups to accept NS User ID. I'm wondering if it could maybe be causing a really strange, and new -- i believe -- issue I'm seeing in Gambit https://github.com/DoSomething/gambit/issues/827#issuecomment-289100468

Likely the specific error from the logs:
```
Notice: Trying to get property of non-object in dosomething_user_convert_to_legacy_id():
line 1164 of var/www/www.dosomething.org/releases/20170323151344/lib/modules/
dosomething/dosomething_user/dosomething_user.module.
```

#### Desired Behavior
We should be able to make requests to this endpoint with either Drupal IDs or Northstar IDs and receive a successful response.

#### Steps to Replicate
See linked issue comment above.

#### Why This Matters
We need to be able to fetch a user's signups without errors! 💣

📶

**Comment by weerd** [comment]
Gah! Thanks for flagging this @aaronschachter and @DFurnes for helping investigate!
