### ISSUE TITLE
Campaign Date Variable

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#734]
Campaign's team would like to show the end date of each campaign in the following format: `Ends August 31`.

**Comment by aaronschachter** [comment]
@mikefantini Is this "end date" the end date of the High Season, or the actual end date of the campaign run?

**Comment by mikefantini** [comment]
@aaronschachter @mmwtsn this is the end date of the high season _if_ Show End Date on Pitch & Action Page is selected.

If it is not selected, then no date appears
