### ISSUE TITLE
Add hardcoded versioning when making requests to Rogue API 

### ISSUE THREAD

**Issue by chloealee** [DoSomethingArchive/legacy-website#7345]
_BUG_
-------------------
#### Current Behavior
- Currently, we are hardcoding the API version in the [`dosomething_rogue_client`](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_rogue/dosomething_rogue.module#L42) function. 
- As a developer, I don't want the API versions to be retrieved from Rogue feature flag when we build the client to make requests to Rogue.

#### Desired Behavior
- Since we're hitting endpoints in Rogue in both `v1` and `v2`, we don't want to grab the version from Rogue settings when we build the client. 

#### Why This Matters
- So we can use `dosomething_rogue_client` whenever we are making calls to Rogue. 

Refs https://github.com/DoSomething/phoenix/pull/7343#discussion_r109768985

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bla](https://trello.com/c/1RlTeYnS/352-bla)
