### ISSUE TITLE
Action Guides: Image Issues

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#735]
- remove Hero Image field
- image search isn't working on intro image (i.e. images I have uploaded don't show up in the results). this works on the gallery images however

**Comment by mikefantini** [comment]
cc: @barryclark

**Comment by mikefantini** [comment]
![image](https://f.cloud.github.com/assets/6330971/2213185/8967ca5e-99bc-11e3-8ce3-1ffc13a832d7.png)

also add action guide on /node/add/campaign takes me to http://stage.dosomething.org/admin/entityconnect/add/entityconnect-form-TRJh0xa_juBivYCypAZKTdGtpCZogTICV5G5rCmgoFA which is a blank page:
![image](https://f.cloud.github.com/assets/6330971/2213194/c148f6f0-99bc-11e3-99b3-aa09fae14b75.png)

**Comment by mikefantini** [comment]
seeing this issue with adding facts on /node/add/campaign too

**Comment by aaronschachter** [comment]
Blank entityconnect screen is a known issue - created #736 to address.
