### ISSUE TITLE
EntityConnect WSOD

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#736]
Occurring on staging when using the Add or Edit Entity Connect buttons.

![image](https://f.cloud.github.com/assets/6330971/2213185/8967ca5e-99bc-11e3-8ce3-1ffc13a832d7.png)

Adding an action guide on /node/add/campaign takes me to http://stage.dosomething.org/admin/entityconnect/add/entityconnect-form-TRJh0xa_juBivYCypAZKTdGtpCZogTICV5G5rCmgoFA which is a blank page:
![image](https://f.cloud.github.com/assets/6330971/2213194/c148f6f0-99bc-11e3-99b3-aa09fae14b75.png)

Occurs for Facts as well on campaign node form.

**Comment by aaronschachter** [comment]
The error that occurs (which you can see by going to another page after getting the WSOD) is:

Notice: Trying to get property of non-object in entityconnect_add() (line 36 of /vagrant/html/profiles/dosomething/modules/contrib/entityconnect/includes/entityconnect.menu.inc).
Notice: Trying to get property of non-object in entityconnect_add() (line 38 of /vagrant/html/profiles/dosomething/modules/contrib/entityconnect/includes/entityconnect.menu.inc).
Notice: Trying to get property of non-object in entityconnect_add() (line 39 of /vagrant/html/profiles/dosomething/modules/contrib/entityconnect/includes/entityconnect.menu.inc).
Notice: Undefined variable: output in entityconnect_add() (line 116 of /vagrant/html/profiles/dosomething/modules/contrib/entityconnect/includes/entityconnect.menu.inc)

**Comment by aaronschachter** [comment]
The errors above are referencing `cache_get` commands.  This module is working fine locally but not on staging.

**Comment by barryclark** [comment]
@angaither Do you have time to take a look at this today? It's making it very difficult for the campaigns team to add Action Guides and 11 Facts.

**Comment by angaither** [comment]
The code is trying to grab data to create the node/add form based on the cache_id in the url. 
There's ~20 rows in the cache table that have the `entityconnect-form-crazyid`
However, when you click the add button, and get taken to `/admin/entityconnect/add/entityconnect-form-crazyid` there's no matching ID in the cache table.

Not sure what's going on here as it works fine locally. 
@mshmsh5000 are we intercepting/moving/slowing drupal cache on staging? redis? something with memcache?

**Comment by mshmsh5000** [comment]
@angaither The staging instance is using vanilla Drupal cache tables in the DB.

@desmondmorris Is the staging.beta DB relatively up to date? Can we update and re-test there? Thx

**Comment by angaither** [comment]
@mshmsh5000 @desmondmorris @mikefantini 
This is working on staging.beta!
closing!
:tada::tada::tada::violin:
