### ISSUE TITLE
Valid Address API

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#74]
Use service like USPS to validate that an address is legit.  Should be an external DS Library to be used by any webapp / app.

**Comment by barryclark** [comment]
This isn't necessary for the mailing work this sprint, @angaither, but is a "nice to have" if you get time.

**Comment by mikefantini** [comment]
@barryclark @angaither after chatting with @Bladt sounds like we should definitely try to get this in this sprint as it's a huge time/money suck if we don't have it. Going to put it into this sprint as medium priority.

**Comment by angaither** [comment]
[USPS](https://www.usps.com/business/web-tools-apis/address-information.htm)
- free
- only takes xml
- no geocode

[Geocode.io](http://geocod.io/)
-  2,500 queries/day 
- takes json
- geocodes & has 'accuracy indicator' on addresses 
- @desmondmorris is all about it

![](http://f.cl.ly/items/0R1N1Q1F1H0L3i1L3Z1V/Screen%20Shot%202014-03-24%20at%204.37.02%20PM.png)

[Google](https://developers.google.com/maps/documentation/geocoding/)
- 2,500 queries/day
- json/xml
- geocodes

**Comment by DFurnes** [comment]
Potential bullet point to add to the Google list: "The Geocoding API may only be used in conjunction with a Google map; geocoding results without displaying them on a map is prohibited."

**Comment by mikefantini** [comment]
removed the comment from #1539 so that we keep that to styling and keep discussions on this issue about whether to validate client side or server side

**Comment by angaither** [comment]
I think we should handle the actual address parsing on the client side, this way we know invalid addresses aren't saved with the user. We can handle asking 'is this what you meant' before the data is saved. 
@DFurnes thoughts?

**Comment by DFurnes** [comment]
This should be a check on the sever-side before the data is saved to the user's profile then, right?

Client-side validation is really just a nice way to help the user catch errors without wasting their time on a full page reload. We shouldn't be relying on it to prevent bad data from hitting the database, since it won't run if a user has JavaScript disabled, or scripts don't load due to an error, etc.

**Comment by DFurnes** [comment]
If we're caching these validations on the server, we can make an AJAX call to that check on client-side so the page doesn't have to refresh if the user needs to make any changes.

Let's chat on Monday about how we should handle this so we're all on the same page. :)

**Comment by angaither** [comment]
AJAX call FTW. I'm on it. 

I'm exploring the USPS service now as that's what we actually need, since geocode.io only returns an 'accuracy indicator'
can't wait to get down with XML.

**Comment by barryclark** [comment]
@angaither Still not heard back from USPS? We should maybe think about moving forward with another service.

**Comment by angaither** [comment]
The only other service I found that seems to validate addresses is http://smartystreets.com/ It costs money. 
![](http://f.cl.ly/items/0j3J0q3y3i111025320G/Screen%20Shot%202014-04-10%20at%2010.09.35%20AM.png)

I checked with a queens address however, and it didn't return the formatted 'range' 
![](http://cl.ly/image/2F300y2E3l3O/Screen%20Shot%202014-04-10%20at%2010.12.14%20AM.png)

I'm not sure what level of validation we are looking for here...

**Comment by angaither** [comment]
Addresses can be validated by a menu hook, using the UPS service #1768 
This integration is not complete, as it doesn't validate before saving the user object.
Next steps, to validate with an ajax callback before the save happens.

**Comment by barryclark** [comment]
@angaither Let us know when it's fender time for helping with that. cc @DFurnes

**Comment by angaither** [comment]
Oh, it's a fender issue, but I'm taking a stab at it. :blush:

**Comment by angaither** [comment]
Closing, user addresses & signup form data addresses are validated against the UPS api
