### ISSUE TITLE
422 when passing northstar_id to POST /campaigns/:id/reportback

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#7484]
_BUG_
-------------------
#### Current Behavior

The *POST* `/campaign/:id/signup` is successfully returning a Signup ID when posting `northstar_id`, but the Reportback resource returns `{"error":{"code":422,"message":"Missing uid query parameter specifying a user id."}}`

#### Desired Behavior
- A successful response with a Reportback ID

#### Steps to Replicate
I found this bug while making the change in Gambit. Also verified it's a Phoenix by using Paw to post:

```
curl -X "POST" "https://staging.dosomething.org/api/v1/campaigns/1672/reportback" \
     -H "Accept: application/json" \
     -H "Content-type: application/json" \
     -H "Cookie: [removed]" \
     -H "X-CSRF-Token:[removed]" \
     -d $'{
  "quantity": "3",
  "file_url": "http://www.fox.com/sites/default/files/X-Files_hero.png",
  "why_participated": "asdfasdfasd",
  "source": "phoenix-js-test",
  "caption": "asdf",
  "northstar_id": "55767606a59dbf3c7a8b4571"
}'
```

#### Why This Matters
*POST* `/campaign/:id/signup` requests have been failing in Gambit intermittently because Northstar Users sometimes don't have Phoenix ID's, which is required for *POST* Campaign `/signup` and `/reportback` requests.

We're attempting to pass `northstar_id` in hope to stop failed Signup requests, and making the change to the Reportback requests as well to keep the code consistent.

#### Relevant Screenshots + Links
* https://github.com/DoSomething/gambit/pull/941
* https://github.com/DoSomething/gambit/issues/922#issuecomment-318103610
* https://github.com/DoSomething/phoenix/pull/7480

**Comment by DFurnes** [comment]
Ugh sorry, I lied when I updated the documentation. We (confusingly) accept Northstar IDs under the `uid` parameter on that endpoint. I'll make a PR to update it to work as `northstar_id` as well.
