### ISSUE TITLE
Dev / QA configuration variables

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#75]
Programatic way to set variables like Google Analytics key.  Possibilities include in settings.php, or in the profile install hook.  

Could be useful for different variables for different environments?

**Comment by desmondmorris** [comment]
There will be a number of these configuration variables to consider.  Some more sensitive than others.  GA keys can be stored as plain text without much harm.  DB configurations, access_tokens and api keys we must handle a bit more securely.  Environment variables can help us here:

conditional $conf vars in settings.php + $_ENV vars should do the trick

**Comment by mshmsh5000** [comment]
QA env-specific variables are stored for now at

blackangus:/home/jenkins/README-dosomething-vagrant

There are three specific settings in that doc -- there will be more, obviously -- we'll need to automate after a clean build.

**Comment by mshmsh5000** [comment]
To log in directly to new app pool: https://qa-secure.dosomething.org:8889/user
