### ISSUE TITLE
Homepage of MX version of site is missing homepage

### ISSUE THREAD

**Issue by mirie** [DoSomethingArchive/legacy-website#7551]
_BUG_
-------------------
#### Current Behavior
When going to https://www.dosomething.org/mx as a non-admin user, the homepage tiles do not load and instead a 404 message is displayed

#### Desired Behavior
The homepage tiles should display the featured campaigns instead of the 404 message.

#### Steps to Replicate
Go to https://www.dosomething.org/mx

#### Why This Matters
The homepage experience is broken, making it confusing for site visitors. Additionally, users are unable to signup for homepage featured campaigns unless they locate them elsewhere.

#### Countries Affected (optional)
Mexico

#### Relevant Screenshots + Links
**Using Torguard (Mexico City) as an anonymous user:**

![Screen Shot 2018-08-08 at 5.25.39 PM.png](https://images.zenhubusercontent.com/58ed335351aa2c30577b1645/b570ead0-8af3-4291-8b99-22b6bc18ca46)

Same happens when going to https://www.dosomething.org/mx without Torguard (as an anonymous user).

**This is the view when logged in as an admin in the US, going directly to https://www.dosomething.org/mx (same, as expected, if using Torguard):**

![Screenshot 2018-08-08 21.21.26.jpg](https://images.zenhubusercontent.com/58ed335351aa2c30577b1645/1b452583-8ee5-4637-9909-4df87d21e377)

**Comment by mirie** [comment]
One of the campaigns on the homepage (first tile) is: https://www.dosomething.org/mx/voluntario/beneficia-con-lo-que-ya-no-necesitas?source=node/1141. I can access this campaign as an anonymous user without issue.

**Comment by mirie** [comment]
I noticed on https://www.dosomething.org/mx/node/1141/edit/es-mx that the translation is unpublished. This box is ticked off for: https://www.dosomething.org/br/node/1141/edit/pt-br. https://www.dosomething.org/br/node/1141 is accessible to both admin and anon users.

<img width="789" alt="screenshot 2018-08-08 21 59 44" src="https://user-images.githubusercontent.com/896728/43873840-63b5f2e0-9b56-11e8-8e00-571bde78eb14.png">

**Comment by mirie** [comment]
I checked the box for "This translation is published" - this appears to have fixed the issue with the homepage tiles.

https://www.dosomething.org/mx/node/1141 is now accessible to anon users. 

<img width="898" alt="screenshot 2018-08-08 22 03 02" src="https://user-images.githubusercontent.com/896728/43873934-d6c33a90-9b56-11e8-8fd7-02ce99ab4e19.png">

**Comment by mirie** [comment]
@ngjo : Would you mind letting our partners in Mexico know that the homepage should be working now? There's no revision history turned on, but I suspect that somehow this box was unchecked on the last edit before this issue. Also please close this issue if you agree that this is resolved and I didn't miss a case/scenario where the homepage tiles remain missing. Thanks!

**Comment by ngjo** [comment]
Oooooh quick and smart sleuthing @mirie ! I know one thing we've seen on the US scholarship page is that when someone edits the page, it sometimes mysteriously un-publishes itself.

I've checked the site on Torguard too and it looks good, so going to close the issue and let our partners know. Thank you!!!
