### ISSUE TITLE
Formatting for MX Doesn't Seem to Be Working

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#7553]
_BUG_
-------------------
#### Current Behavior
Text that's formatted to be in a bulleted list isn't showing up that way

#### Desired Behavior
Text that's formatted to be in a bulleted list should show up that way

#### Steps to Replicate
1. Go to the [MX campaign ](https://www.dosomething.org/mx/node/8187/edit/en) and try to make a bullet under the Plan It section (not sure if this is affecting other fields too)
2. Save
3. See that it's not formatted

Not sure if this matters or not, but the MX campaign isn't published yet - we were trying to see what it'd look like before publishing.

#### Why This Matters
Our partners in Mexico are trying to publish their campaign and this section won't format! If we need to work around this with some text changes, let me know and I can work with them on this.

#### Countries Affected (optional)
MX

#### Relevant Screenshots + Links
![screen shot 2018-09-10 at 12 28 03 pm](https://user-images.githubusercontent.com/2658867/45310692-ffb6f380-b4f4-11e8-96c7-4444efd12ac1.png)
![screen shot 2018-09-10 at 12 27 49 pm](https://user-images.githubusercontent.com/2658867/45310693-ffb6f380-b4f4-11e8-9713-b06e62254535.png)
![screen shot 2018-09-10 at 12 29 01 pm](https://user-images.githubusercontent.com/2658867/45310733-207f4900-b4f5-11e8-9348-432690f4186b.png)
![screen shot 2018-09-10 at 12 28 53 pm](https://user-images.githubusercontent.com/2658867/45310734-207f4900-b4f5-11e8-86b2-1de65867580f.png)

[MX Campaign Page](https://www.dosomething.org/mx/node/8187/edit/en) 
[US Campaign Page](https://www.dosomething.org/us/node/6045/edit)

**Comment by ngjo** [comment]
I let Karina know that we're looking into this and if she's able to, to rephrase the bulleted list as one phrase for the time being so this isn't blocking her

**Comment by mirie** [comment]
@ngjo: It appears that the text was formatted incorrectly (all the bullets were on one line) for the spanish translation. Does it look as expected now?

**Comment by ngjo** [comment]
It does look right @mirie ! For documentation, it was user error! We were editing the English page, not the Spanish page and that's why it wasn't showing up. Gotta select the right language!

![screen shot 2018-09-11 at 1 21 19 pm](https://user-images.githubusercontent.com/2658867/45376428-c5695700-b5c5-11e8-893c-440c4b35401d.png)
