### ISSUE TITLE
Reportback: Error if you upload same image

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#756]
Can't have the same file name for a file.  WTF

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'public://reportback/adidat.jpg' for key 'uri': INSERT INTO {file_managed} (uid, filename, uri, filemime, filesize, status, timestamp, uuid) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7); Array ( [:db_insert_placeholder_0] => 5 [:db_insert_placeholder_1] => adidat.jpg [:db_insert_placeholder_2] => public://reportback/adidat.jpg [:db_insert_placeholder_3] => image/jpeg [:db_insert_placeholder_4] => 64373 [:db_insert_placeholder_5] => 0 [:db_insert_placeholder_6] => 1392937586 [:db_insert_placeholder_7] => 4f7de168-4a7d-40ef-9d58-9b4ac322b76c ) in drupal_write_record() (line 7201 of /vagrant/html/includes/common.inc).

**Comment by barryclark** [comment]
Wat. Any thoughts on a solve for this on @aaronschachter?

**Comment by aaronschachter** [comment]
I'd imagine this is a common issue, need to investigate more but it would involve renaming the file, either via contrib module or custom code.

if we wanted to go the route of creating our own multi-upload widget, we could avoid this error, but thats a totally separate issue (and not worth doing so if it is only to avoid this error)

**Comment by barryclark** [comment]
@aaronschachter Yea, we've run into this in the past. Such a common problem, surprised there isn't an option for renaming files in there.

**Comment by aaronschachter** [comment]
Closing this, we're ditching Field API and will be using our own functions to name files.
