### ISSUE TITLE
Campaign: On sign up or registration, update the user's Mobile Commons DOB

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#759]
Similar to what we had to do with #450.

When we POST to `https://secure.mcommons.com/profiles/join` we also need to pass along the user's DOB. This would go in the `person[date_of_birth]` field. `YYYY-MM-DD`

cc: @mikefantini

**Comment by aaronschachter** [comment]
@jonuy @mikefantini - Just want to clarify: Anytime a user signs up for a campaign and we opt-in to mobile commons (which is #450) , we just need to additionally include the user's DOB as an additional `person[date_of_birth]` in the args we pass?

**Comment by mikefantini** [comment]
@aaronschachter yeah exactly
