### ISSUE TITLE
Preprocess JS - User.js

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#764]
Per description #724 - the login modal on a pitch page does not work unless Drupal's core User module's User.js is removed or renamed manually.

This issue is to handle this programatically, ideally through a `hook_preprocess_js` to avoid messing with core.

**Comment by barryclark** [comment]
Shooting this over to @desmondmorris as he worked on the previous solution.

**Comment by barryclark** [comment]
Related to #670

**Comment by angaither** [comment]
Closing, fixed in https://github.com/DoSomething/paraneue/pull/24
