### ISSUE TITLE
Campaigns Template - Sponsor Fields + Modal

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#768]
Need new fields on campaigns node. These should live within the Sponsors and Partners Group.

Fields:
- partner name (not sponsor name because we may give this to a non-sponsor)
- body text
- partner photo
- partner video

Note:
- need the ability to add multiple per campaign
- need markdown (ability to add links and create separate paragraphs)

This will open up in a modal on the action page.

See annotated wires here: https://trello-attachments.s3.amazonaws.com/511573a78e553913770000ea/52d9ad6d1b4858440e574065/8c828a9e1d6211fd5acd421b4ce4ae34/Action_Page_-_Sponsor_Modal_v0.1.png

See mocks here: https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/Xk7eqRtsusVCuKB/keri_actionpg%20mob_aero_modal.jpg

**Comment by mikefantini** [comment]
cc: @barryclark

**Comment by mikefantini** [comment]
@aaronschachter @barryclark put this into 0.2 since we need to get it done for March 17th.

**Comment by aaronschachter** [comment]
Proposed build:
- The sponsor vocabulary becomes "partner" vocabulary, which has a Partner logo file field.
- Delete field_sponsors and field_partners multi-value fields from campaign.
- Create a new field collection, field_campaign_partners with fields:
  - Partner Term ID (entity reference - single value to Partners vocab)
  - Is Sponsor (boolean)
  - Partner Copy (Long text with Markdown)
  - Partner Image (Node ref to Image type)
  - Partner Video (Video field collection)

In the preprocess function, loop through all field_campaign_partners.
Foreach partner:
- If partner is sponsor: output the logo in the header for the "Powered by [logo]"
- If partner has Partner Copy set, output the Partner modal link and copy/image/video
- List the partner name in the campaign footer.

**Comment by angaither** [comment]
Seems good, just a few questions: 

Can we store the following with the partner term:
- Partner logo
- Partner video
- Perhaps partner copy (though I can see why this may be different per campaign the partner sponsors... perhaps we can do a default living with the term and override per campaign as needed?) 

Also, since image nodes now have minimum requirements, I think we should leave the partner image as a field attached to the term.

**Comment by aaronschachter** [comment]
The partner logo does live on the term, but yeah - the copy/image/video are supposed to live on the campaign node as they can change per campaign.  I believe the image/photo is something that is separate from the logo.

I also was considering defaults on the Partner term... but also want to keep things as simple in back-end as possible.  We can always add that later if we end up needing it.

**Comment by angaither** [comment]
Ah, ok. Didn't realize the logo/image were different things.

**Comment by aaronschachter** [comment]
Closing this guy.  All fields exist to allow for sponsor modal copy, image, and video.  Remaining bender item is preprocessing the video in #958
