### ISSUE TITLE
ZenDesk contact form

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#770]
Use ZenDesk API to create a contact form that appears on campaigns.

Should create a ZenDesk ticket with the logged in user's UID, email, name and campaign they are submitting from. 

Notes:
Official ZenDesk PHP Library: http://developer.zendesk.com/blog/2014/02/20/introducing-the-zendesk-php-api-client-library/
Examples: https://github.com/zendesk/zendesk_api_client_php

**Comment by barryclark** [comment]
@aaronschachter What are you thinking for the UI for this? Can we use our modals for the form?

**Comment by aaronschachter** [comment]
Yup thats what i was a-thinkin

**Comment by barryclark** [comment]
Sweet, loop in @DFurnes when you're working on this too pls.
