### ISSUE TITLE
Action Page - Content changes for Sponsors

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#780]
The following changes need to be made for sponsored campaigns:
- sponsor logo appears on hero image with "Powered by" text
- link "Why we <3 [partner name]" should appear (in mocks it's "Why is [partner name] sponsoring, but use Why we <3 language instead).
- link should open up sponsor modal (see #768 for details)

Examples:
https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/DcxIX6UDY7oH8Dz/sponsor_desk_hm.jpg
https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/BoxMA0R7r2uxjAo/sponsor_desk_ggw.jpg
https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/TwpeuehsllXpdZI/sponsor_desk_hrblock.jpg

**Comment by aaronschachter** [comment]
These changes have been made.
