### ISSUE TITLE
Action Page - Customer coloring for sponsors

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#781]
From #780 ...

headers are in sponsor color (i.e. all headers under Know It, Plan It, and main headers undo Do It)
Prove It section is in sponsor color
Prove It section has sponsor specific texture
Note: unlike in the mocks, Prove It on the persistent nav should stay in primary action color blue (it shouldn't change to the sponsor color).

Examples:
https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/DcxIX6UDY7oH8Dz/sponsor_desk_hm.jpg
https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/BoxMA0R7r2uxjAo/sponsor_desk_ggw.jpg
https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/TwpeuehsllXpdZI/sponsor_desk_hrblock.jpg

**Comment by barryclark** [comment]
@mmwtsn Let's chat about how to implement this.

**Comment by mmwtsn** [comment]
@barryclark We could just print the color out as an inline style the same way we're printing out the hero image.

What were you thinking?

**Comment by DFurnes** [comment]
That seems like a reasonable solution to me :+1:

**Comment by barryclark** [comment]
@mmwtsn :thumbsup: good plan

**Comment by aaronschachter** [comment]
Variables are now available within the campaign and campaign--pitch tpl files.  Example usage:

`color="<?php if isset($alt_color): print '#' . $alt_color; endif; ?>"`

`src="<?php if isset($alt_bg_src): print ' . $alt_bg_src; endif; ?>"`

**Comment by barryclark** [comment]
Think this is closed now @mmwtsn ?

**Comment by mmwtsn** [comment]
Closed by #1096
