### ISSUE TITLE
DS build --install error - Missing Xmlsitemap_18n

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#783]
WD php: Exception: Required modules: Required modules not found.     [error]

The following modules are required but were not found. Move them into
the appropriate modules subdirectory, such as sites/all/modules.
Missing modules: Xmlsitemap_18n in install_verify_requirements()
(line 768 of /vagrant/html/includes/install.core.inc).
WD php: Warning: Cannot modify header information - headers already  [warning]
sent by (output started at /opt/drush-6.2.0/includes/output.inc:38)
in drupal_send_headers() (line 1217 of
/vagrant/html/includes/bootstrap.inc).
Exception: Required modules: Required modules not found.

The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as <em>sites/all/modules</em>. Missing modules: <span class="admin-missing">Xmlsitemap_18n</span> in install_verify_requirements() (line 768 of /vagrant/html/includes/install.core.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]

**Comment by barryclark** [comment]
Think you're working on the sitemap @mshmsh5000? Assigning over.

**Comment by mshmsh5000** [comment]
Yes, this is mine.
