### ISSUE TITLE
DS Build --install error: blocked_ips not found

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#784]
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.blocked_ips&amp;#039; doesn&amp;#039;t exist: SELECT 1 FROM {blocked_ips} WHERE ip = :ip; Array
(
    [:ip] =&amp;gt; 127.0.0.1
)
 in drupal_is_denied() (line 1916 of /vagrant/html/includes/bootstrap.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.system&amp;#039; doesn&amp;#039;t exist: SELECT \* FROM {system} WHERE type = &amp;#039;theme&amp;#039; OR (type = &amp;#039;module&amp;#039; AND status = 1) ORDER BY weight ASC, name ASC; Array
(
)
 in system_list() (line 165 of /vagrant/html/includes/module.inc).</p><hr />Drush command terminated abnormally due to an unrecoverable error.   [error]
Updating database...

**Comment by mshmsh5000** [comment]
Trying to reproduce now.

**Comment by mshmsh5000** [comment]
Has anyone seen this, esp since merging PR 786?

**Comment by aaronschachter** [comment]
I don't see this error anymore, but I do get weird behavior with a `ds build --install` now.  Opening a separate issue and closing this.
