### ISSUE TITLE
Drush error:  Cannot change an existing field's type

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#785]
Field type change introduced in #777 is causing an error upon `drush cc all` :

WD php: FieldException: Cannot change an existing field's type. in   [error]
field_update_field() (line 234 of
/vagrant/html/modules/field/field.crud.inc).
FieldException: Cannot change an existing field&#039;s type. in field_update_field() (line 234 of /vagrant/html/modules/field/field.crud.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]

The easiest way to fix:
1. Delete Sponsor Image field from the Sponsor vocabulary:
   http://dev.dosomething.org:8888/admin/structure/taxonomy/sponsors/fields/field_image_sponsor_logo/delete
2. Revert the taxonomy feature:  `drush -y fr dosomething_taxonomy`

Once this is resolved on staging, a dev should close this issue.

This is something we'll need to watch out for in future features changes.  Best practice may be to create a new field instead and delete the old one with an update hook.

**Comment by aaronschachter** [comment]
This error won't appear in the staging environment until we deploy again, but the error will appear locally for you if your codebase is up to date.  To unbork local environments, follow steps in the description of deleting the field from the Sponsors vocabulary and then reverting the `dosomething_taxonomy` feature.

**Comment by angaither** [comment]
Updated on stage!
