### ISSUE TITLE
DS build --install errors:  xmlsitemap

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#787]
Strange errors when I run  `ds build --install`:

```
Starting Drupal installation. This takes a few seconds ...           [ok]
/usr/local/bin/ds: line 177: 28321 Segmentation fault      drush site-install dosomething -y --db-url=mysql://root@localhost/dosomething --site-name=DoSomething
Granting basic permissions..
```

then later...

```
The drush command 'fra' could not be found.  Run `drush cache-clear  [error]
drush` to clear the commandfile cache if you have installed new
extensions.
```

The build completes but the paraneue_dosomething theme is not enabled.  This has happened twice now.  Trying to run just `drush site-install dosomething` gives a bit more information:

```
WD Apache Solr: HTTP Status: 0; Message: Request failed: Connection  [error]
refused; Response: ; Request: Unknown; Caller: call_user_func_array()
(line Unknown of Unknown)
WD Apache Solr: HTTP 0; Request failed: Connection refused in        [error]
apachesolr_cron
WD Apache Solr: No Solr instance available during indexing.          [error]
Segmentation fault
```

Ok, next I comment out the apachesolr modules:

```
; dependencies[] = apachesolr
; dependencies[] = apachesolr_search
```

and run `drush site-install dosomething` again.  The installation completes, and I get an admin password.  Visiting the site I get: 

```
Fatal error: Unsupported operand types in /vagrant/html/profiles/dosomething/modules/contrib/xmlsitemap/xmlsitemap.module on line 1070
```

Upon disabling xmlsitemap via drush, I am able to access the new site.

**Comment by aaronschachter** [comment]
Not sure what priority this is as far as whether or not we'll be running `ds build --install` anymore, but ideally it should work.

**Comment by mshmsh5000** [comment]
xmlsitemap has an array concatenation ( += style) against a variable assumed to be an array. I might just add a patch for that.

**Comment by mshmsh5000** [comment]
Did that "add a patch for that" thing.

**Comment by angaither** [comment]
#788 seems to fix
 `Fatal error: Unsupported operand types in /vagrant/html/profiles/dosomething/modules/contrib/xmlsitemap/xmlsitemap.module on line 1070`
When visiting the site, however I still see the error when it's building.

Also still seeing 
`WD Apache Solr: HTTP Status: 0; Message: Request failed: Connection refused; Response: ; Request: Unknown; Caller: call_user_func_array() (line    [error]
Unknown of Unknown)
WD Apache Solr: HTTP 0; Request failed: Connection refused in apachesolr_cron                                                                      [error]
WD Apache Solr: No Solr instance available during indexing.`

but the build completes.

**Comment by angaither** [comment]
Oh. Actually it seems the `Fatal error: Unsupported operand types in /vagrant/html/profiles/dosomething/modules/contrib/xmlsitemap/xmlsitemap.module on line 1070` is still happening, just on every other page refresh now....

**Comment by aaronschachter** [comment]
Renamed this issue and creating a separate issue for the Apache Solr issues.
