### ISSUE TITLE
Production environment

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#79]

**Comment by barryclark** [comment]
Assigning @desmondmorris on this, although it's a bit ancient.

**Comment by desmondmorris** [comment]
This will be an on-going task for a bit.  We are working with RS devops on this

**Comment by desmondmorris** [comment]
**complete**
- Single webhead
- cap deployments to webhead
- varnish + pound config
- mariadb redundancy
- logstash instance

**pending**
- redis funtime
- finish connecting new relic and log stash to everything

**Comment by barryclark** [comment]
@desmondmorris do the pending tasks need to be done for Tuesday?

**Comment by desmondmorris** [comment]
@barryclark ideally

**Comment by mikefantini** [comment]
@desmondmorris is this ticket fully up to date? 

currently trying to do overall priority of all outstanding issues

**Comment by mikefantini** [comment]
and @desmondmorris should this get the priority label? (i.e. can we not launch unless this is closed out)

**Comment by desmondmorris** [comment]
@mikefantini only stuff pending is around logging and reporting.  But prod environment is ready for gametime
