### ISSUE TITLE
DS build --install: Apache Solr errors

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#794]
Full description listed in #787

Wasn't able to complete build without commenting out related search modules in the build.

**Comment by mshmsh5000** [comment]
Huh. Shouldn't you be able to install these without configuring them? Or @blisteringherb are there Strongarmed config variables that are killing this for folks without Solr already running?

**Comment by blisteringherb** [comment]
@mshmsh5000 The strongarmed vars are causing errors, but they're not fatal errors as far as I can tell.  I'm not sure the best way to handle setting up the solr server/the apachesolr settings if it's not done when the modules are enabled.

**Comment by aaronschachter** [comment]
I was getting the Segmentation error on my local, but yeah it didn't prevent the build from running.  It was just super slow.
