### ISSUE TITLE
DS build: Composer package installation

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#796]
We'll need to install a few different libraries via Composer.  This issue is to install the relevant packges into their own directories in the libraries path.

**Comment by desmondmorris** [comment]
What libraries exactly?  Why can we load these via make?

**Comment by desmondmorris** [comment]
I think I see why, bc the autoloader is not present.  This may present some complexities.  Good to catch this and start this queue

**Comment by desmondmorris** [comment]
Can we just provide a composer.json file with the dependencies?  There is also the composers installers concept - https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by aaronschachter** [comment]
Yep, I'm a composer n00b but I think that's the idea.  That `installer-paths` seems like it would do the trick

**Comment by aaronschachter** [comment]
Discussed with @desmondmorris -- We'll handle this by running `composer install` within vagrant, inside each library directory we need to install.  https://github.com/DoSomething/dosomething/wiki/DoSomething-modules#wiki-libraries.

There is a 'ds composer` function that will run this for each specified library.
