### ISSUE TITLE
Hubot script to deploy to production

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#80]
This has some issues that need to be resolved first:
- #79 
- #77

**Comment by mmwtsn** [comment]
We need a physical deploy button, too.

![looks safe](http://www.ukrocketman.com/images/fire_open_250.jpg)

**Comment by desmondmorris** [comment]
@maxwell yes hell yeah we need that

This is fixed with: https://github.com/DoSomething/hubot-george/pull/14
