### ISSUE TITLE
Pitch login bug

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#801]
If you enter the wrong password, you are directed to user/login.

This means that once you enter the right password, you won't be signed up for the campaign, since you are no longer on the pitch page.

**Comment by DFurnes** [comment]
@aaronschachter I don't think this is a front-end issue. When server-side validation fails on the wrong password, it should be passing a query-string or something to the `user/login` page so we can keep the user in the same flow.

**Comment by barryclark** [comment]
shooting over to @angaither thanks!

**Comment by DFurnes** [comment]
Yay! Thanks @angaither! :smile:
