### ISSUE TITLE
all pages – js taking too long to execute on vagrant boxes

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#815]
:racehorse:

**Comment by barryclark** [comment]
Are we still having problems with this @DFurnes @mmwtsn @aaronschachter ?

**Comment by mmwtsn** [comment]
JavaScript form Paraneue DS is clocking in at `7.26` seconds for me locally. A complete sponsored Action Page is loading with fonts and assets in `12.98` seconds. Not pretty.

**Comment by barryclark** [comment]
Updated title as this is only a problem on our vagrant setups, not on the staging server.

**Comment by barryclark** [comment]
Shifting to backlog and assigning @desmondmorris (cc @mshmsh5000)

**Comment by desmondmorris** [comment]
un-assigning myself for now.  This should be a more general vm peformancing benchmarking and optimization task.  Things we should get to once we get the local environment (LAMP) running the same stack as our new prod env (LEMP)

**Comment by aaronschachter** [comment]
@DFurnes Is this still an issue?

**Comment by DFurnes** [comment]
Don't think so. Closing.
