### ISSUE TITLE
Static content - intro_image not displaying

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#836]
I have uploaded an image and included it in the intro_image field, however it never gets displayed. 

http://stage.dosomething.org/content/fantini-static-content-test
http://stage.dosomething.org/node/30/edit

**Comment by barryclark** [comment]
Unsure whether this is @blisteringherb or @angaither, would be great if you guys could take a look. Thanks!

**Comment by blisteringherb** [comment]
I reassigned it to me.
