### ISSUE TITLE
View term pages permissions

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#841]
Currently all taxonomy term pages are visible to anon users: e.g. http://stage.dosomething.org/cause/poverty

I'd imagine we don't want anonymous users or authenticated users to view these pages, as it hasn't been in scope to theme or handle these term pages. This issue is to deny access to any non-staff users viewing a taxonomy term page.

**Comment by angaither** [comment]
In other news, why are they themed like campaigns?

**Comment by aaronschachter** [comment]
My guess is because there isn't a node--campaign-teaser.tpl.php that exists, so it's using the node--campaign.tpl.php.

**Comment by aaronschachter** [comment]
The view could also be overridden to display just a campaign title instead of a rendered node.  Actually this might be a relatively simple way to implement the access check.
