### ISSUE TITLE
action (know it) – switch facts and video/placeholder

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#844]
For the initial launch we are going with facts/sources in the left column of the campaign page in lieu of a YouTube video or PSA placeholder image.

**EDIT:** except on sponsored campaigns for which Fantini has requested that we keep all links in the rightmost column of the "Know It" section to allow for a video/placeholder image.

**Comment by mikefantini** [comment]
@mmwtsn sponsored campaigns would have the facts/sources in the left column like other campaigns, until the is PSA added.

I.e. H&M from March 18-April 2nd would have that info in the left column and then once we launch the PSA it would revert to the original mocks.

**Comment by barryclark** [comment]
@mmwtsn @mikefantini  think this might be done?

**Comment by mmwtsn** [comment]
This one is still open. Given that H&M doesn't have a PSA slated for production until **April 10th**, the updated left-column fact location will due until **Milestone 0.3.0.**

**Comment by barryclark** [comment]
Thanks @mmwtsn

**Comment by mikefantini** [comment]
@mmwtsn this should not be pushed to production this sprint, but the high priority item is adding in a dummy video, reviewing how it looks with design and hilary, and making sure we're good to go for when we do have the H&M PSA for April 10th.

Ideally adding the PSA to H&M wouldn't affect how the other campaigns look, but let's chat about that if that's problematic.
