### ISSUE TITLE
Validation issue with Drupal's birthdate form markup

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/legacy-website#853]
The validation function we're using expects to find a corresponding `<label for="#id">` tag for the ID of the validated input field. Drupal outputs a whole mess of tags but apparently not a field label (although it does for all the other fields on the form).

![screen shot 2014-02-25 at 3 29 59 pm](https://f.cloud.github.com/assets/583202/2262599/f6148e96-9e5b-11e3-9eb7-a9cae2dbf0d8.png)

Can we make that `<span>` into a `<label>` with a `for=""` attribute pointing to the corresponding input field? I've tried poking around in the Form API array using `dpm()` but I'm not seeing anything I can edit to fix it up.

/cc @angaither

**Comment by angaither** [comment]
We can override the tpl on our theme
https://api.drupal.org/api/drupal/modules!field!theme!field.tpl.php/7
`field-type-[field_type]` and override all dates or 
`field-name-birthdate` and just override the birthday

**Comment by angaither** [comment]
@DFurnes ok to close this one?

**Comment by DFurnes** [comment]
Yep! :hammer:
