### ISSUE TITLE
Campaign: On sign up or registration, update the user's Mobile Commons first name and email

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#858]
Two more things should happen when a user signs up for a campaign and provides a mobile number:
- [ ] Pass along user's first name
- [ ] Pass along user's email

See #450 #759 and #857 for related issues.

cc: @jonuy

**Comment by barryclark** [comment]
Shooting this one over to @angaither

**Comment by angaither** [comment]
Was fixed with #886
