### ISSUE TITLE
Auth - Create an Account Required Fields Needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#869]
First Name and Birthday should both be required fields and they should have \* indicating that they are required.

![image](https://f.cloud.github.com/assets/6330971/2273144/8e07ef8a-9f0c-11e3-930d-d00f23f26093.png)

**Comment by barryclark** [comment]
@DFurnes I think, as per Luke W's book, if there's only one field that's optional then it's that field that should be indicated rather than all of the required fields. So here we should remove all of the *s and add an (optional) in for the optional field. Thoughts?

**Comment by DFurnes** [comment]
@barryclark Totally agreed.

**Comment by barryclark** [comment]
Assigning this to you @DFurnes :beers:

**Comment by mikefantini** [comment]
Re-assigning to @DFurnes currently email, password, and confirm password are still appearing as required.

Also can we flip cell number and email since email is required?

**Comment by DFurnes** [comment]
Re-opening since the CSS changes & flipping cell and email fields both haven't been merged in yet.
