### ISSUE TITLE
Add Coder module to drupal-org.make

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#87]

**Comment by aaronschachter** [comment]
Assigning to @mchitten as he's currently working with Coder, PHP CodeSniffer, and automated Github API code reviews. 

I'd imagine we'd want this in the drupal-org.make file to avoid having Coder module changes show up in our repo, although I'm not well versed in the best practices for where it should live.  Main issue here is for devs to be able to run Coder locally before submitting the pull request, and ideally keep the Coder module files out of the tracked changes.

**Comment by mchitten** [comment]
Done through #148
