### ISSUE TITLE
Auth Flow: Google Analtyics track sign in/reg failures

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#874]
Need to set up tracking on Google Analytics so that we know how often people fail trying to sign in/register on the site.

This will provide us with a baseline so that we can see if we are moving in the right direction whenever we make changes to the auth flow.

cc: @Bladt

**Comment by DFurnes** [comment]
As a heads up, we're trying to catch most registration errors using client-side validation in the new world. So we'll need to hook in using some sort of custom Google Analytics event there since most errors will never be hitting the server.

**Comment by barryclark** [comment]
@mshmsh5000 Google Analytics tracking for log in/registration isn't currently prioritized for Tuesday launch. Let me know if that needs to change.

**Comment by mikefantini** [comment]
duplicate of #1473
