### ISSUE TITLE
Partners: Editors Need Ability to Add

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#877]
Editors need access to http://stage.dosomething.org/admin/structure/taxonomy/partners/add

cc: @barryclark

**Comment by mikefantini** [comment]
@aaronschachter editors still don't have access to this

**Comment by aaronschachter** [comment]
Apparently the "edit" terms permission doesn't let you "add" terms. Suggested fixes:
- Grant administer terms permission to editors (very quick and somewhat terrifying)
- https://drupal.org/project/taxonomy_access_fix

**Comment by mikefantini** [comment]
Moving this to the backlog.

We should go with this solution https://drupal.org/project/taxonomy_access_fix but not a priority right now.

For now I will be responsible for adding all partners.

**Comment by aaronschachter** [comment]
Related trello card https://trello.com/c/bFbddyup

**Comment by mikefantini** [comment]
+1 I can't wait to never create a partner again
