### ISSUE TITLE
Push number of campaigns started to Mobile Commons profile on campaign sign up

### ISSUE THREAD

**Issue by jonuy** [DoSomethingArchive/legacy-website#879]
Need to:
- Create a custom profile field on Mobile Commons: `campaigns_started` @jonuy
- When a user signs up on the web for a staff pick or non-staff pick campaign, in addition to opting them into a Mobile Commons path, also update the user's `profile[campaigns_started]` field with the number of campaigns she's started.

Context: Mobile Commons can only detect the number of subscriptions a user has on the Mobile Commons platform. So a user could do 5 campaigns on the web, and then sign up for one on mobile, and we could incorrectly treat them as one who's starting their first ever campaign.

cc: @mikefantini

**Comment by aaronschachter** [comment]
The `dosomething_signup` module contains a function called `dosomething_signup_get_signup_nids_by_uid($uid)`.  We should create a function `dosomething_signup_get_signup_count_by_uid($uid)`  which would return the count of the result array returned by `dosomething_signup_get_signup_nids_by_uid`

**Comment by barryclark** [comment]
@jonuy Do we still need this?

**Comment by jonuy** [comment]
@barryclark We ran into this and other issues with trying to determine if a mobile user was doing their first campaign or not. As far as I know, there's no active attempt to get this going again, but it'd certainly be a nice-to-have for if we do get around to it.

**Comment by barryclark** [comment]
@jonuy Thanks, backlogging.

**Comment by angaither** [comment]
oh interesting, check out this issue.
@chloealee @jonuy @DFurnes 

looks very similar to #5184

**Comment by jonuy** [comment]
It does sorta have that same feel of syncing info from one service to another. We can close this particular one out though. There hasn't been talk of doing any special personalization like this for SMS since probably May 2014.

**Comment by angaither** [comment]
bam :hammer:
