### ISSUE TITLE
User Registration: MailChimp Subscription

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#892]
When a user registers for the site (whether through general site reg or through signing up for a campaign) she should get subscribed to MailChimp group NewMembers2012.

We should pass through to the user's MailChimp profile:
- email (key)
- first name
- birthday
- mobile number

cc: @barryclark

**Comment by mikefantini** [comment]
also, we should update the group name (i.e. shouldn't be NewMembers2012); but I don't want it to fuck up any old code we have, so we need to time that properly.

@DeeZone @aaronschachter @marahml any thoughts? You guys know way more about MailChimp Groups than I do.

**Comment by deezone** [comment]
The List name "NewMembers2012" is only used internally via the MailChimp admin UI. Currently the list name that the public sees for things like unsubscription is set to "Do Something Members". I don't think it's possible to rename a List but there is an ID: 71893 that I think most of our custom code references. If the name changes the ID will remain the same.

**Comment by aaronschachter** [comment]
Yes -- we'll want to store the mailchimp ID (71893) as the variable value, and not whatever its corresponding label is ("NewMembers2012").

**Comment by mikefantini** [comment]
great. will changing the label name effect how anything is currently working? i.e. will it effect PB Jam Slam or Mind On My Money?

**Comment by aaronschachter** [comment]
Yes it would break things in the old campaign, unless - @DeeZone will message broker be handling subscriptions upon signups? or will it still be dosomething_mailchimp_subscribe ?  If it's still handled in `dosomething_mailchimp_subscribe` we would need a code change to make it smarter and not use GroupName.

**Comment by deezone** [comment]
Currently working on the Message Broker solution to handle creating MailChimp entries when a new user registers and signs up for campaigns. It's a part of the 0.3.0 release, we're currently still working on parts of 0.2.0 - expect progress next week.

**Comment by mikefantini** [comment]
Ben Kassoy said we actually just need them subscribed to the Do Something Members List not the the actual Group NewMembers2012

**Comment by deezone** [comment]
@mikefantini - understood. A general new user signup to the website will now result in the creation of an entry in MailChimp assigned to the mail list "Do Something Members". A campaign signup will result in assigning "interest group" ids to the email in MailChimp.

**Comment by deezone** [comment]
@aaronschachter I think this is the issue you were making reference to earlier today. Based on Mike's comment above from Ben, a new user registration should result in a new entry in MailChimp but _not_ an interest group assignment of NewMembers2012 which I think is now called "UserRegistration". 

Perhaps Marah can confirm, what do you think @mikefantini ? Do we need another round of clarification or can I proceed with no group assignment for new accounts?

**Comment by mikefantini** [comment]
@DeeZone @aaronschachter just clarified with @marahml and we do _not_ need to make a group assignment for new users (in NewMembers2012 or any other group). 

We just need to make sure that a general new user signup to the website results in the creation of an entry in MailChimp assigned to the mail list "Do Something Members". And that a campaign signup results in assigning "interest group" ids to the email in MailChimp.

**Comment by deezone** [comment]
Fantastic, this is already done. Next is the mobile number and then this issue is done.

**Comment by aaronschachter** [comment]
@DeeZone but then don't you want to remove the code that was added that did this today? https://github.com/DoSomething/mbc-registration-email/pull/7/files

**Comment by deezone** [comment]
Related: #1480

**Comment by deezone** [comment]
@aaronschachter Yes, removed group assignment from general email signup to mailchimp in mbc-registration-email.
