### ISSUE TITLE
Staff Pick Campaigns: MailChimp Group Subscription

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#893]
Need the ability to subscriber users to a specific MailChimp Group for specific staff pick campaigns.

I.e. I sign up for H&M and I am subscribed into the H&M MailChimp Group.

This should happen whether I am a new or returning user.

See #892 for related MailChimp subscription issue.

**Comment by deezone** [comment]
@angaither This can be combined through the message_broker_producer_request() call. I can take care of this if you like?

**Comment by angaither** [comment]
@DeeZone sure!

**Comment by mikefantini** [comment]
@angaither we'll still need the admin page so that @marahml can add MailChimp Groups to campaigns that need them.

**Comment by angaither** [comment]
@mikefantini yup, that's #859

**Comment by mikefantini** [comment]
Also @DeeZone we'll need this in place and tested by March 14th. Let me know if you have any questions.

**Comment by aaronschachter** [comment]
@DeeZone Let's keep this issue open until Message Broker is configured to hardcode any grouping_id and group names, and we're set up to add Mailchimp opt-in without any code deployments.
