### ISSUE TITLE
Images: Filter Needed on Campaign Hero Images

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#912]
We need to attach the image filter we want to the actual image itself because certain devices may not render the CSS in the way we want and therefore won't display the filter, making the white text on top of the photos unreadable.

@angaither is going to investigate ImageMagick to see if this will resolve the issue.

Best case scenario: ImageMagick is able to apply the filter we need  and is easy enough to implement for the 0.2 release.

Worst case scenario: We adjust the Image Node to have fields for:
- landscape crop, no filter
- landscape crop, filter
- square crop, no filter
- square crop, filter

**Comment by angaither** [comment]
Depends on #948
