### ISSUE TITLE
SCSS Compile issue on ds build

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#921]
Running "sass:compile" (sass) task
Warning: /vagrant/lib/themes/dosomething/paraneue_dosomething/scss/app.scss:13: error: file to import not found or unreadable: "../../../../html/profiles/dosomething/themes/dosomething/paraneue/paraneue/bower_components/pattern-library/scss/helpers"
 Use --force to continue.

Aborted due to warnings.
Build complete.
![screen shot 2014-02-28 at 3 18 57 pm](https://f.cloud.github.com/assets/645205/2297993/a9c2d65e-a0b5-11e3-9282-fa5d9a9d3b11.png)

**Comment by deezone** [comment]
Ran into this earlier today - check that your key is installed.

**Comment by angaither** [comment]
AHH. Yes, ok. Mine keeps disappearing. Thanks :+1:
