### ISSUE TITLE
Zendesk: Ticket Groups

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#928]
- [x] Create admin form to configure the Zendesk group_id for each Cause term tid
- [x] Create Zendesk ticket with the group_id of a Campaign's Primary Cause
- [x] For staff picks, use priority "high" instead of "normal".

**Comment by marahml** [comment]
As part of the triggering system with groups - is it possible add keywords that would trigger tickets that are coming into Zendesk (from help@dosomething.org) to auto-filter into groups. ie) If we said that any email with the words "earth day" should go to the environment group, and they skipped the ZD inbox and just went to that group. ?

**Comment by aaronschachter** [comment]
I know it'd be possible to add this if we're submitting all tickets via a form on the site (would be a separate issue from this one).  There may be some automatic filters to set up in the Zendesk admin that would filter emails to help@dosomething.org but i"m not sure.

**Comment by marahml** [comment]
Hey @aaronschachter! Just did some tests using staff-picks and non-staff-picks. I'm seeing not seeing priority or group assignment happening in ZenDesk. Am I doing something wrong?

**Comment by aaronschachter** [comment]
@marahml Our worfklow is currently closing issues when they're resolved in code, but not actually on production (something on our list to change).  I've deployed the changes to http://staging.beta.dosomething.org/ so you can test there.  Will let you know when we deploy to production.

**Comment by aaronschachter** [comment]
@marahml This has been deployed to production. I've given it a quick test and looks good. Feel free to reopen and comment if any issues.

**Comment by marahml** [comment]
So exciting. Tested and works great. Thanks Aaron!

On Mon, Mar 31, 2014 at 12:09 PM, Aaron Schachter
notifications@github.comwrote:

> Closed #928 https://github.com/DoSomething/dosomething/issues/928.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DoSomething/dosomething/issues/928
> .

## 

_Marah Lidey_
Digital Engagement Manager, DoSomething.org
(212) 254-2390 Ext. 215

follow me: twitter.com/marahml
follow us: twitter.com/dosomething http://www.twitter.com/dosomething
