### ISSUE TITLE
Site Registration - Allow Under 13

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#931]
For the site registration flow, we should allow users under the age of 13 to join the site.

I.e. we shouldn't have any age restrictions for registering for the site. 

cc: @barryclark

**Comment by mikefantini** [comment]
Note: users under the age of 13 will be able to:
- sign up for the site
- sign up for campaigns
- report back on campaigns

**Comment by aaronschachter** [comment]
This is working as is, there are currently no age restrictions in place for user registration, campaign sign up, or reporting back.

**Comment by aaronschachter** [comment]
Re-opening and assigning to @DFurnes -- There are no restrictions in back-end code but this is an issue to investigate in the client-side User form registration
