### ISSUE TITLE
Static Content - Markdown is not working

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#933]
Not working on Action Guides either: #891

**Comment by mikefantini** [comment]
assigning to @blisteringherb

**Comment by barryclark** [comment]
Thanks @mikefantini

**Comment by blisteringherb** [comment]
Do we know which field specifically isn't working, and in what way it's not working?  I've checked the intro field on static content, and it appears to be working and outputting the correct markup.

**Comment by barryclark** [comment]
Just checked on staging and it's working correctly now. Not sure what happened, but FIXED!
