### ISSUE TITLE
Image Styles features-revert error

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#934]
`drush -y fra` or `drush -y fe [stuff]` results in this error: 

```
array_merge(): Argument #1 is not an array image.module:586 
```

which seems related to image styles -- https://drupal.org/node/1973278

**Comment by angaither** [comment]
Finally saw this error on http://dev.dosomething.org:8888/admin/config/media/image-styles
It's because two modules were not enabled locally, try `drush en imagecache_actions imagecache_canvasactions -y`

**Comment by aaronschachter** [comment]
Ah, good catch. Are they currently enabled on staging?  

Question to the group: Perhaps best practice to catch new modules should be to `dosomething.info` accordingly, and use that profile has the guideline for everything that should be enabled?

**Comment by angaither** [comment]
Yes, just enabled them on staging. 
Seems like yes, all modules in ds.info should be enabled, maybe should this happen on ds build?

**Comment by aaronschachter** [comment]
That sounds like a good way to make sure of it. 

I'm not sure how we'd actually go about checking that profile's info file (without parsing the file and running drush php-eval for (!if module_enabled($name) ) then drush enable module....

@mshmsh5000 @desmondmorris -- any thoughts / concerns?  I suppose one risk might be enabling a module automatically which needs auth variables in order to fully function.  and making sure that those modules handle the lack of auth variables gracefully.

**Comment by angaither** [comment]
Fixed after modules were enabled on stage.
