### ISSUE TITLE
DS update-files removes symlinks

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#939]
Run `ds update-files`, make changes, then wonder if you still know how to PHP.  

And then realize oh, just no more symlinks

Not sure if this is by design, but seems like a bug?

**Comment by desmondmorris** [comment]
@aaronschachter which symlinks are broken exactly?  The modules/themes?  If so, this is not by design

**Comment by aaronschachter** [comment]
I know definitely modules was broken, but did not try themes.

**Comment by desmondmorris** [comment]
Cool.  I will give it a look
