### ISSUE TITLE
Production: Upgrade Varnish to latest

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#94]
Needs to be the same version as in QA, so we can maintain consistent VCL rules.

See #83 -- if this ruleset is stored in an external VCL, both prod and QA default.vcl can include that file.

if (path = "aboutus") then
  route to pool1;

if (path = "campaigns") then
  route to pool2;

We can define pool1 and pool2 in the main default.vcl files.

**Comment by mshmsh5000** [comment]
Note that this upgrade (2.x to 3.x) involves non-trivial changes to the VCL, including actual procedure calls that differ between the two versions.

**Comment by barryclark** [comment]
- @desmondmorris 

Pls assign this to milestone 0.2.0 if it's needed for launch.

**Comment by desmondmorris** [comment]
The shiny new varnish instance in production is 3.0.2.  

We will however need to upgrade varnish in our VM if it hasnt been yet
