### ISSUE TITLE
action page - modal styling

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#942]
[Mocks](https://s3.amazonaws.com/uploads.hipchat.com/34218/237177/Xk7eqRtsusVCuKB/keri_actionpg%20mob_aero_modal.jpg) via the Product Wiki.

**Comment by mmwtsn** [comment]
@barryclark Is this good to go? :zap:

**Comment by DFurnes** [comment]
Huehuehuehuehue
