### ISSUE TITLE
Errors on DS build

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#944]
`<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.blocked_ips&amp;#039; doesn&amp;#039;t exist: SELECT 1 FROM {blocked_ips} WHERE ip = :ip; Array
(
    [:ip] =&amp;gt; 127.0.0.1
)
 in drupal_is_denied() (line 1916 of /vagrant/html/includes/bootstrap.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &amp;#039;dosomething.system&amp;#039; doesn&amp;#039;t exist: SELECT * FROM {system} WHERE type = &amp;#039;theme&amp;#039; OR (type = &amp;#039;module&amp;#039; AND status = 1) ORDER BY weight ASC, name ASC; Array
(
)
 in system_list() (line 165 of /vagrant/html/includes/module.inc).</p><hr />Drush command terminated abnormally due to an unrecoverable error.`

**Comment by aaronschachter** [comment]
I've run into this #784, but intermittently unfortunately.  Ran a bunch of build's this weekend and haven't seen it since filing #784.

**Comment by deezone** [comment]
Just ran into this as well. For me, a recent past build trashed the db. This error message is the result of the database being empty. I ran a `ds build --install` after looking at the db with `drush sql-cli -> show tables;`

Thanks to Matt for pointing way...

**Comment by angaither** [comment]
Importing the stage db fixed this.
