### ISSUE TITLE
Updated Image styles/sizes Needed

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#948]
If we are going with square and landscape crops for campaign hero image, I need the final max-height/width to crop the photos (and too add the mask) to.

**Comment by mmwtsn** [comment]
**landscape**: `1440x810`
**square**: `768x768`

These are based on the `16:9` ratio for landscape crops we decided on at a max-width of `1440px` and the [tablet breakpoint](https://github.com/DoSomething/ds-neue/blob/dev/scss/globals/_grid-settings.scss#L14) set in Neue.

**Comment by angaither** [comment]
@mmwtsn thanks, closing!
