### ISSUE TITLE
Hosting for misc images used in themes

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#954]
We can host these images in misc places for now, but it's going to get messy soon. 

Can we get setup for storing images on Rackspace Cloud?

cc @desmondmorris

**Comment by desmondmorris** [comment]
We should store these in `images` or `img` directly in the paraneue_dosomething or paraneue themes.

**Comment by DFurnes** [comment]
@desmondmorris +1

**Comment by barryclark** [comment]
Sweet. @DFurnes could you set up an images folder in paraneue_dosomething please?
