### ISSUE TITLE
Move the H&M campaign to a title based URL

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#955]
H&M is going to be titled "Comeback Clothes".

**Comment by barryclark** [comment]
Will the URL for it be http://www.dosomething.org/campaigns/comeback-clothes ? @aaronschachter

**Comment by aaronschachter** [comment]
it can be whatever we want it to be.  do we have a desired naming pattern for campaigns?

e.g. 

dosomething.org/campaigns/[title]
dosomething.org/campaign/[title]
dosomething.org/[cause]/[title]
dosomething.org/[title]

**Comment by barryclark** [comment]
It's always been: dosomething.org/[title]

I think we're sticking with that. cc @mikefantini

**Comment by mikefantini** [comment]
ah no, chatted with Matt about this earlier and was going to create an issue for it..

we want campaigns to be dosomething.org/campaigns/[title]

However, for campaigns that we do external marketing for we will want to create specific URLs for marketing purposes. The ideal would be www.teensforjeans.org or www.comebackclothes.org but at the very least we would want www.dosomething.org/teensforjeans or www.dosomething.org/comebackclothes.

**Comment by barryclark** [comment]
@mshmsh5000 @mikefantini Apologies if this has been covered previously but what's the disadvantage of using /[title]? It's cleaner, more sharable, matches our current convention for campaigns, and matches Mike's minimum vanity URL requirement. 

cc @aaronschachter

**Comment by mshmsh5000** [comment]
@barryclark @aaronschachter @mikefantini We need a consistent pattern to switch app pools.

During the pre-platform-1.0 period, we have Varnish deciding whether to route any incoming request to the old or the new pool depending on the URL pattern.

If campaign URLs don't have a consistent pattern, then we need to write one exception for each campaign title -- PITA  to maintain and prone to errors.

So we need something like /campaigns/[title] to power a single rule in Varnish.

We can still create vanity redirects, but keep in mind that those will continue to be served by the old app. So

**/comebackclothes** => Varnish => old app => redirect = > **/campaigns/comebackclothes** => Varnish => new app

**Comment by mshmsh5000** [comment]
Note that Varnish will cache the 301, so there's no substantial performance hit involved with these vanity redirects.

**Comment by barryclark** [comment]
Sweet, thanks for explaining that @mshmsh5000.

**Comment by aaronschachter** [comment]
This has been implemented.
