### ISSUE TITLE
Install Global Redirect

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#960]
Add Global redirect module into the build via make file.  

Does not need to be enabled in dosomething.info

Needed for indexing old nodes, and for #955

**Comment by barryclark** [comment]
@aaronschachter will we need this for 0.2.0?

**Comment by aaronschachter** [comment]
This is closely related to #1110, this is necessary for pointing beta nodes to legacy nodes in the Explore Campaigns.  Not sure if one module does the trick or if we need both (as per explanation in #1110)

**Comment by blisteringherb** [comment]
@aaronschachter you mentioned it doesn't need to be enabled, were you thinking it would be harmful in some way if it were automatically enabled?
