### ISSUE TITLE
action page (know it) - <script> not being closed somewhere

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#970]
Looks like a script tag isn't being closed somewhere wreaking havoc with the styles below The Solution section on http://staging.beta.dosomething.org/campaign/66

Possibly related to: https://github.com/DoSomething/paraneue/pull/34/files

cc @DFurnes @mmwtsn

**Comment by barryclark** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by mmwtsn** [comment]
Still happening after the merge! Reopening.
