### ISSUE TITLE
QA: Self-assigned SSL cert

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#98]
For now. If we need a legit SSL cert for third-party interaction, we can go there.

**Comment by desmondmorris** [comment]
@mshmsh5000 any dis-advantages to serving all authenticated requests behind SSL?

**Comment by mshmsh5000** [comment]
We could try. My experience is that doing SSL switching based on URLs is a lot easier than on auth status. I'd also rather keep with the simpler Akamai config that serves http traffic on Akamai and https directly from the app. (Deploying SSL certs to Akamai is expensive.)

We could try switching all authenticated traffic to SSL in a later version. I like the idea of maximizing our members' privacy. Given that authenticated traffic will be a tiny fraction of total traffic, we should still be serving most content from cache.

Any other thoughts/opinions on this?

**Comment by mshmsh5000** [comment]
I think we want this: http://docs.saltstack.com/ref/modules/all/salt.modules.tls.html

**Comment by mshmsh5000** [comment]
Salt calls are basically

`tls.create_ca salt`
`tls.create_csr salt`
`tls.create_ca_signed_cert salt localhost`

Figuring out the best way to capture this in a Salt State file.
