### ISSUE TITLE
Dynamic login message - Welcome Back / You've Signed Up

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#980]
Need to update the notification for when a user signs up for a campaign and when a user returns to a campaign they are already signed up for.

Notification messages should look like this:
https://s3.amazonaws.com/uploads.hipchat.com/34218/407723/jn8yiKwQ2EQROAt/Action%20Page%20Notification.pdf

**Comment by aaronschachter** [comment]
Discussion with @mikefantini today:

Desired behavior for "Welcome back" message is any time a user logs in, NOT any time they return to a campaign node.  Ideally this should check whether or not the user is new, or for us to count number of logins (or at least set a field/flag for "returning user"), so you don't get "welcome back" upon your first login.

Need to investigate the one scenario where a user logs in via pitch page, and not displaying both messages.

**Comment by mikefantini** [comment]
Yeah it's for any time a user logs in, _unless_ they are logging in to sign up for a campaign for the first time of that campaign's current run. 

Then they should get the "You're signed up" notification.

**Comment by aaronschachter** [comment]
The campaign signup message has been completed in #992, so updating the issue title per what's left to build for this.

Per discussion with @mikefantini, the dynamic sign-in message that says "Welcome back" per comments above is not needed for 0.2  Moving this to backlog.

**Comment by barryclark** [comment]
Didn't manage to get this in for v1.0. Closing this and can re-open if we do it in v2.
