### ISSUE TITLE
Switch to https for user login/edit/register

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomethingArchive/legacy-website#99]
Requires #98 for testing.

Techniques and discussion of [D7 Secure Pages](https://drupal.org/project/securepages) module status [here](http://drupal.stackexchange.com/questions/23149/redirect-user-login-to-https-all-other-requests-to-http).

We may not need Secure Pages, since we're constructing a custom auth flow; but that module's techniques for forcing requests to https are still useful.

**Comment by DFurnes** [comment]
:heart:!

It might be worth defaulting to HTTPS for all pages on logged-in sessions to prevent session hijacking.

**Comment by mshmsh5000** [comment]
Desmond suggested this in #98 as well. The session security concerns are largely mitigated by enforcing a secure cookie, but I agree that, performance and scalability considerations aside, it'd be nice to go secure for the whole site for authenticated users.
