### ISSUE TITLE
campaign - scholarship amounts should have a comma when displayed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#997]
The scholarship amount field on the campaign node only allows numeric values. However, when scholarship amounts are displayed to the user, they should have a comma to denote thousand (i.e. 10,000 not 10000).

**Comment by aaronschachter** [comment]
This can be handled in the dosomething_campaign preprocess via [number_format](http://no1.php.net/number_format)

**Comment by mikefantini** [comment]
@aaronschachter is it a quick fix?

**Comment by aaronschachter** [comment]
yup!
