### ISSUE TITLE
auth - birthday confirmation is inaccurate

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#998]
When registering for the site, the message I receive after filling out the birthday field (i.e. Cool, 14) is not calculating my birthday properly.

Whether I say my birthday is 3/4/2000 or 3/6/2000 it says "Cool, 14!" (date is 3/5/2014).

For 3/4/2000 it should say "Cool, 13!"; for 3/6/2000 it should say "Cool, 14!"

**Comment by angaither** [comment]
oh, math. :heavy_plus_sign:

**Comment by DFurnes** [comment]
Yeah, that's a thing I've never been known to do well. :apple: :pencil: :facepunch:
